### ISSUE TITLE
[Question] Why only 5 methods for latent upscaling ?

### ISSUE THREAD

**Issue by tetsuoo-online** [comfyanonymous/ComfyUI#1011]
My question is about what is called "highres fix" or "second pass" in other UIs.
Regenerate a bigger image using any upscalers like my favorites 4x-UltraSharp or 4x_NMKD-Siax_200k doesn't seem possible in ComfyUI ? You can only _resize_, which is very different... and I rarely need that.
I can see only 5 methods available : nearest-exact,bilinear,area,bicubic,bislerp. I tried them all, most gives terrible artifacts with a denoise strength under 0.5, which I always need to improve any image, especially while applying LoRAs.
The node 'Load Upscale Model' doesn't seem to be of any help (only 1 node can be connected to it), please what am I missing ?

![image](https://github.com/comfyanonymous/ComfyUI/assets/45845308/1d7e5b54-af88-44f2-957c-c9781671c233)

**Comment by TeutonJon78** [comment]
There is a difference between latent space and pixel space.

Latent upscalers are used between various sampling nodes but before the VAE decoding step. These would attach to the "latent" inputs/outputs of nodes.

The upscalers you mention are pixel space upscalers and applied to an "image" output after the VAE decoding step. If you do an upscaler loader node, you'll see the ones you're expecting (if they are in the appropriate directory). You'd wire the output of VAE decode into Upscale Image node alone with the "load upscaler node" and then take the image output of that node and put it into a preview and/or save image node.

You can only connect up node ports of the correct type.

**Comment by tetsuoo-online** [comment]
ok, well I cannot explain why pixel upscalers can be used for latent upscaling in other UIs, that's how it is. Very sad news here, thanks anyway :(
![image](https://github.com/comfyanonymous/ComfyUI/assets/45845308/24341e78-c100-4602-a598-4124b4653e5a)

**Comment by ltdrdata** [comment]
> ok, well I cannot explain why pixel upscalers can be used for latent upscaling in other UIs, that's how it is. Very sad news here, thanks anyway :(
> ![image](https://github.com/comfyanonymous/ComfyUI/assets/45845308/24341e78-c100-4602-a598-4124b4653e5a)
> 

A1111 hides internal process. It is convenient. But on the otherway, it leads misunderstandings, too.

**Comment by comfyanonymous** [comment]
See the second example on this page: https://comfyanonymous.github.io/ComfyUI_examples/2_pass_txt2img/

**Comment by tetsuoo-online** [comment]
> See the second example on this page: https://comfyanonymous.github.io/ComfyUI_examples/2_pass_txt2img/

Oh. My. Goood~~ Thank you I tried and it's amazing. I've been using auto1111 for more than 6 months, I can tell something right away : This upscale to 1536x1536 on my 3060 is freaking **_FAST_**. I can't mess with too much nodes but with ComfyBox it's going to be great, I'm loving it :D

![image](https://github.com/comfyanonymous/ComfyUI/assets/45845308/e1c141bc-9720-4c51-975f-c580fa5809a3)
