### ISSUE TITLE
mouse drag Behavior, and shortcut need~

### ISSUE THREAD

**Issue by kelsoz** [comfyanonymous/ComfyUI#103]
I use blender node system many years,  it feels nice

comfyUI in  UI behavior  can like blender node system?

Blender's nodes do a good job, and there are many usefull behavior and shortcut keys available.

for example: 
1. Drag the left mouse button to select multiple nodes
2. Middle mouse button to pan
3. Drag the new node to the connected line to automatically insert and connect
4. Many useful shortcut keys are available, such as x to delete, shift a to add nodes

What I need most now is to change the middle mouse button to pan, which is a default setting in almost all other software

**Comment by jwvanderbeck** [comment]
Of course for everyone that finds Blender familiar, there is another that finds blender horrid because it is so different from other industry standard programs :)

I think as long as there is documentation it isn't such a big deal but having to figure out the hotkeys through random trial and error isn't so great :)

**Comment by MoonMoon82** [comment]
Maybe a custom keymap config file would be great, so if you're into Blender, just download a ~blender_keymap.config file and place it in the comfyui folder... something like that. For users of other programs it would just be easy to provide such files for each taste.

**Comment by Jongulo** [comment]
I know people have been able to get SD working natively in Blender. If there was a node based plugin that would be incredible.

**Comment by robinjhuang** [comment]
Consolidating here: https://github.com/comfyanonymous/ComfyUI/issues/624
