### ISSUE TITLE
segmentation fault error on prompt queue

### ISSUE THREAD

**Issue by lonse1** [comfyanonymous/ComfyUI#1052]
on linux im getting the following error after queuing a prompt in the webui
`segmentation fault (core dumped)  python main.py` 
python version is 3.11.3

**Comment by orangeberet** [comment]
hi! did you fix that?

**Comment by Nelnitorian** [comment]
Hi! I am facing the same error.

### Environment
OS: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
GPU: AMD Radeon RX 6600
Python: 3.10.12
Models used: ```sd_xl_base_1.0.safetensors``` and ```sd_xl_refiner_1.0.safetensors```
Libraries (from ```pip install -r requirements.txt```):
```
torch (2.0.1+rocm5.4.2)
torchsde(0.2.5)
einops (0.6.1)
transformers>=4.25.1 (4.31.0)
safetensors>=0.3.0 (0.3.1)
aiohttp (3.8.5)
accelerate (0.21.0)
pyyaml (5.4.1)
Pillow (9.0.1)
scipy (1.11.1)
tqdm (4.65.0)
jinja2 (3.1.2)
typing-extensions (4.7.1)
networkx (3.1)
filelock (3.12.2)
pytorch-triton-rocm<2.1,>=2.0.0 (2.0.1)
sympy (1.12)
boltons>=20.2.1 (23.0.0)
trampoline>=0.1.2 (0.1.2)
numpy>=1.19.* (1.24.1)
requests (2.25.1)
tokenizers!=0.11.3,<0.14,>=0.11.1 (0.13.3)
regex!=2019.12.17  (2023.6.3)
huggingface-hub<1.0,>=0.14.1 (0.16.4)
packaging>=20.0 (23.1)
attrs>=17.3.0 (23.1.0)
frozenlist>=1.1.1 (1.4.0)
aiosignal>=1.1.2 (1.3.1)
charset-normalizer<4.0,>=2.0 (3.2.0)
async-timeout<5.0,>=4.0.0a3 (4.0.2)
multidict<7.0,>=4.5 (6.0.4)
yarl<2.0,>=1.0 (1.9.2)
psutil (5.9.5)
fsspec (2023.6.0)
cmake (3.26.4)
lit (16.0.6)
idna>=2.0 (3.3)
MarkupSafe>=2.0n(2.0.1)
mpmath>=0.19 (1.3.0)
```
### Error description
After executing ```python3 main.py```, it will start thinking for a while and then throw a dump core. It goes through the "Load Checkpoint" job without errors.

This is the workflow:
![image](https://github.com/comfyanonymous/ComfyUI/assets/28271500/46d8e0e7-d990-4f63-b673-140004de26a6)


This is the information displayed:
```Total VRAM 8176 MB, total RAM 15923 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6600 : native
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type EPS
adm 2816
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Segmentation fault (core dumped)
```


### Steps to reproduce
- Clone repository: ```git clone https://github.com/comfyanonymous/ComfyUI```
- Install requirements: ```python3 -m pip install -r requirements.txt && python3 -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.4.2```
- Execute: ```python3 main.py```

Use the web interface. Click on "Queue Prompt" button. Then wait for the checkpoint to load (properly?) and fail when starting "CLIP Text Encode (prompt)".

### Investigation
I have tried searching for something related to comfyui and core dumps, but only this issue popped. I monitored my machine to check if it had something to do with resources and it does not seem so. Monitored via nvtop.

Image of nvtop resource usage:
![image](https://github.com/comfyanonymous/ComfyUI/assets/28271500/4346896e-ce95-4478-868e-755fe5136e2c)
