### ISSUE TITLE
VAEDecode().decode using an additional 10GB of VRAM when executing the raw Python code. 

### ISSUE THREAD

**Issue by pydn** [comfyanonymous/ComfyUI#1053]
Hi All,

I've created a script that will convert a workflow_api.json export from the UI into a standalone executable python file that can be run without pinging the local server. The code works as intended, but the VAE Decoder is taking up 10 GB of VRAM when I get to that step, which is not happening when executing the code within the GUI. I assume there is a backend process I'm not finding in the execution.py to control for VRAM loading. Could anyone help me figure this out? My code to reproduce is below. It will work when you run it from the `script_examples/` folder.

The code below is the python equivalent of running the [SDXL example](https://comfyanonymous.github.io/ComfyUI_examples/sdxl/) from ComfyUI_examples

```
import sys
sys.path.append("../")
from nodes import EmptyLatentImage
from nodes import CheckpointLoaderSimple
from nodes import CLIPTextEncode
from nodes import SaveImage
from nodes import KSamplerAdvanced
from nodes import VAEDecode

def main():
	checkpointloadersimple = CheckpointLoaderSimple()
	checkpointloadersimple_4 = checkpointloadersimple.load_checkpoint(ckpt_name="sd_xl_base_1.0.safetensors")
	emptylatentimage = EmptyLatentImage()
	emptylatentimage_5 = emptylatentimage.generate(width=1024, height=1024, batch_size=1)
	cliptextencode = CLIPTextEncode()
	cliptextencode_6 = cliptextencode.encode(text="evening sunset scenery blue sky nature, glass bottle with a galaxy in it", clip=checkpointloadersimple_4[1])
	cliptextencode_7 = cliptextencode.encode(text="text, watermark", clip=checkpointloadersimple_4[1])
	ksampleradvanced = KSamplerAdvanced()
	ksampleradvanced_10 = ksampleradvanced.sample(add_noise="enable", noise_seed=721897303308196, steps=25, cfg=8, sampler_name="euler", scheduler="normal", start_at_step=0, end_at_step=20, return_with_leftover_noise="enable", model=checkpointloadersimple_4[0], positive=cliptextencode_6[0], negative=cliptextencode_7[0], latent_image=emptylatentimage_5[0])
	checkpointloadersimple_12 = checkpointloadersimple.load_checkpoint(ckpt_name="sd_xl_refiner_1.0.safetensors")
	cliptextencode_15 = cliptextencode.encode(text="evening sunset scenery blue sky nature, glass bottle with a galaxy in it", clip=checkpointloadersimple_12[1])
	cliptextencode_16 = cliptextencode.encode(text="text, watermark", clip=checkpointloadersimple_12[1])
	ksampleradvanced_11 = ksampleradvanced.sample(add_noise="disable", noise_seed=0, steps=25, cfg=8, sampler_name="euler", scheduler="normal", start_at_step=20, end_at_step=10000, return_with_leftover_noise="disable", model=checkpointloadersimple_12[0], positive=cliptextencode_15[0], negative=cliptextencode_16[0], latent_image=ksampleradvanced_10[0])
	vaedecode = VAEDecode()
	vaedecode_17 = vaedecode.decode(samples=ksampleradvanced_11[0], vae=checkpointloadersimple_12[2])
	saveimage = SaveImage()
	saveimage_19 = saveimage.save_images(filename_prefix="ComfyUI", images=vaedecode_17[0].detach())


if __name__ == "__main__":
	main()
```

**Comment by MaxTran96** [comment]
following

**Comment by pydn** [comment]
Update: Replacing vaedecode = VAEDecode() with vaedecode = VAEDecodeTiled() reduces total VRAM usage to 18 GB from 23 GB. An improvement, but still seems to be different than what is happening when the code is executed in the GUI.

**Comment by MaxTran96** [comment]
i tried that but it seems like its not able to generate photo that has my trained subject. This same trained model works just fine on ComfyUI/Runpod to generate a photo of trained subject but somehow i cant get it to generate the trained subject via python code

**Comment by MaxTran96** [comment]
do you know what does this error mean?
```
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 6, in main
  File "/home/ubuntu/content/ComfyUI/nodes.py", line 446, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "/home/ubuntu/content/ComfyUI/comfy/sd.py", line 1149, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "/home/ubuntu/content/ComfyUI/comfy/utils.py", line 11, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/usr/local/lib/python3.8/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by MaxTran96** [comment]
how would i remove. the refiner class? I dont think i need that refiner layer

**Comment by MaxTran96** [comment]
i figure it out, the base model was corrupt

**Comment by MaxTran96** [comment]
i have a question, how would i modify the python code above to generate N images not 1

**Comment by pydn** [comment]
Put the code in a for loop and be sure to randomize the sampler seed. How experienced are you with Python?

**Comment by MaxTran96** [comment]
Quite experienced, but i was wondering since the prompt will be the same, will the for loop need to be outside of main() like
For x in range(n)
    Main()

Or can i just do
Def main():
  //code
  For x in range(n):
     Save_image() code

**Comment by pydn** [comment]
As long as you make sure the sampler seed is randomized, it should work by just looping over main(). I haven't confirmed myself, but it should work. The save image function should automatically add a new suffix after the provided prefix and not overwrite the new image.

**Comment by arjun810** [comment]
Were you able to figure anything out here? Is VAEDecodeTiled worse in any way?

**Comment by pydn** [comment]
@arjun810 During my testing, I haven't been able to tell a difference in the output between VAEDecode and VAEDecodeTiled. So I'm happy with this resolution.

I just released an extension to convert any native ComfyUI workflow into executable python code which you can find here: https://github.com/pydn/ComfyUI-to-Python-Extension

Let me know if you have any questions.

**Comment by pydn** [comment]
> Quite experienced, but i was wondering since the prompt will be the same, will the for loop need to be outside of main() like For x in range(n) Main()
> 
> Or can i just do Def main(): //code For x in range(n): Save_image() code

Following up that optimizing the logic for looping is integrated into my [ComfyUI-to-Python-Extension](https://github.com/pydn/ComfyUI-to-Python-Extension) repo

**Comment by arjun810** [comment]
Thanks!

I was able to figure out why VAEDecode was consuming extra memory. You need to run torch in inference mode, as seen here:

https://github.com/comfyanonymous/ComfyUI/blob/master/execution.py#L327

Adding that line to your generated script (outside the loop) worked for me, and I no longer get the OOM issue.

Thanks for looking into this and making the script!

**Comment by pydn** [comment]
Amazing! Thank you for tracking that down! I'll add to the repo

**Comment by pydn** [comment]
Those are default parameters in the sdxl workflow example. I think it's basically the refiner model picking up where the base model left off. If you've looked at outputs from both, the output from the refiner model is usually a nicer, more detailed version of the base model output. Kind of like image to image.

**Comment by MaxTran96** [comment]
why did you do a for loop instead of setting batch_size to 10 instead of 

for q in range(1, 10): (I assume you mean range(10) to get a batch size of 10?

**Comment by pydn** [comment]
If you have a workflow where you want to increase the batch size, that will be built into the script. Keep in mind, the repo I built is meant to copy your ComfyUI workflow that you set up. My example is just a very basic one.

 So if you want a batch size of 10, you will create 10 new images each for loop. The for loop acts as a queue for your workflow. And yes, it should be range(10). I'll update that in the repo as well.

**Comment by pydn** [comment]
@AIManifest That's awesome that you've built that code! I thought about going a layer deeper in the abstraction as well, but thought starting with the nodes classes was a good clean starting point that people could use for experimentation or point them to the deeper levels in the source code if they want to make further adjustments.

**Comment by AIManifest** [comment]
Disregard family, `with torch.inference_mode` was the glue to the entire flow, fixed any issue😍 Thanks again @arjun810!

**Comment by AIManifest** [comment]
@pydn you’re awesome my friend. I was amazed at how clean ur code was! And thanks, I’m addicted to taking apart these masterful codes and seeing what makes them click! I’ve also observed that doing this and running with Raw code helps understand what makes better images and ultimately makes me generate more eye candy for myself to feast on lol. Love all around!✌🏽

**Comment by AIManifest** [comment]
@pydn @arjun810 hey friends, running into a bit of a pickle. My script is working great, just wondered if any of you masterful tinkerers have encountered the refiner not having `any` effect on refining the image? Can't seem to figure out why after hours of tracing through the scripts.

**Comment by AIManifest** [comment]
Disregard, I found my bug lol (whoop whoop!)
