### ISSUE TITLE
Default nodes not being found on install?

### ISSUE THREAD

**Issue by hempires47** [comfyanonymous/ComfyUI#1061]
been trying to make use of SDXL workflows from Civit but upon loading them I'm hit with many errors by what are (apparently) default included nodes.

for instance, in Sytans 'official' SDXL workflow I get the error that no nodes called "ImageScaleBy" or "ImageBlend" can be found.

I've tried updating, and now a full reinstall and the issue persists, not really sure what else to try at this point!

![image](https://github.com/comfyanonymous/ComfyUI/assets/48775687/be35a911-45aa-46d7-b707-7e68a2ba72a4)

**Comment by ltdrdata** [comment]
It's deactivated by Allor custom node.
There is a config which is preventing deactiavtion.

**Comment by hempires47** [comment]
well goddamn, I figured it'd be something simple I was missing but yeah that's completely solved it, cheers!
