### ISSUE TITLE
Error occurred when executing CLIPVisionEncode

### ISSUE THREAD

**Issue by DIRECTEDBYKUBA** [comfyanonymous/ComfyUI#1064]
Hi there, 
somehow i cant get unCLIP to work 

The .png has the unclip example workflow i tried out, but it gets stuck in the CLIPVisionEncode Module.
What can i do to solve this? 

Error occurred when executing CLIPVisionEncode:

'NoneType' object has no attribute 'encode_image'

File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 144, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 742, in encode
output = clip_vision.encode_image(image)

![unclip_2pass](https://github.com/comfyanonymous/ComfyUI/assets/141161676/51b5ed7c-d5d9-4b88-a973-a54882039653)

**Comment by comfyanonymous** [comment]
Make sure you are using an unCLIP checkpoint, regular ones won't work.

**Comment by gollum10086** [comment]
Hello,is this problem solved for yours?I'm also having the same issue but don't know how to do it.If you solve this problem, can you tell me how to fix it?

**Comment by DIRECTEDBYKUBA** [comment]
> Hello,is this problem solved for yours? I'm also having the same issue but don't know how to do it. If you solve this problem, can you tell me how to fix it?

The issue for me was that I tried to run this on a Checkpoint without unClip, so if you have the same issue, then u need to download an unClip checkpoint for this workflow, most of the checkpoints for unClip workflows, have ''unclip'' in the file- or general name. 
After using a unClip Model this Error Code didn't show up for me again.  
But if u have this Issue with an unClip Checkpoint, maybe someone else can help.

**Comment by gollum10086** [comment]
Thank you for help，I'll try to download an unClip checkpoint for this workflow.

**Comment by CodeAlexx** [comment]
i now get the same error with wan i2v workflow posted on the comfy newsletter

![Image](https://github.com/user-attachments/assets/8a90b4bf-7331-4e94-94f2-ae299e2b7dae)
