### ISSUE TITLE
xformers not used properly, half the speed compared to auto1111

### ISSUE THREAD

**Issue by 2blackbar** [comfyanonymous/ComfyUI#1078]
Getting 1.7 seconds in auto1111 with 512x512 20 steps euler
comfy gets me 3 seconds to do same image with same settings, thats half the speed, and its pretty big slowdown from auto1111
Any chance to fix that in the future ? 
Id like to use comfy more but this is pretty big dealbreaker, half the speed.
rtx 3090 win10

**Comment by kasper93** [comment]
I recommend using nightly PyTorch, it is way faster than xformers. At least on 4090, YMMV.

**Comment by 2blackbar** [comment]
how fast it is with 20 steps 512 res euler sampler ? i got 1.7 on auto1111
Here i managed to get 2.30 btu still trying to squeeze in more speed 
How do you guys load own vae ? im new cant find a way to load my own vaes from my models folder

**Comment by comfyanonymous** [comment]
With: main.py --gpu-only

I get:
```
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 24.45it/s]
Prompt executed in 0.95 seconds
```

**Comment by 2blackbar** [comment]
The hell, what gpu drivers ? this is win10 ?
Ok now i have 1.33 but not 0.95 thats crazy , how did you get it ? do i need some new cuda lubs or nvidia drivers ?

**Comment by comfyanonymous** [comment]
I'm on Fedora Linux using a very recent pytorch nightly.

**Comment by 2blackbar** [comment]
You heard of anyone on win10 getting that speed ? Thats like twice as fast from my max auto1111

**Comment by 2blackbar** [comment]
How do i isntall latest nightly  2.10.0 on my win machine? finding whl manually and all ? no simpler way?

**Comment by 2blackbar** [comment]
Its satisfied but still crap speeds 
Requirement already satisfied: torch in f:\sd\venv\lib\site-packages (2.1.0.dev20230801+cu118)
Requirement already satisfied: torchvision in f:\sd\venv\lib\site-packages (0.16.0.dev20230802+cu118)
Requirement already satisfied: torchaudio in f:\sd\venv\lib\site-packages (2.1.0.dev20230802+cu118)
Requirement already satisfied: filelock in f:\sd\venv\lib\site-packages (from torch) (3.12.2)
Requirement already satisfied: fsspec in f:\sd\venv\lib\site-packages (from torch) (2023.6.0)
Requirement already satisfied: sympy in f:\sd\venv\lib\site-packages (from torch) (1.12)
Requirement already satisfied: jinja2 in f:\sd\venv\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: networkx in f:\sd\venv\lib\site-packages (from torch) (3.1)
Requirement already satisfied: typing-extensions in f:\sd\venv\lib\site-packages (from torch) (4.7.1)
Requirement already satisfied: requests in f:\sd\venv\lib\site-packages (from torchvision) (2.31.0)
Requirement already satisfied: numpy in f:\sd\venv\lib\site-packages (from torchvision) (1.23.5)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in f:\sd\venv\lib\site-packages (from torchvision) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in f:\sd\venv\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: certifi>=2017.4.17 in f:\sd\venv\lib\site-packages (from requests->torchvision) (2023.7.22)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\sd\venv\lib\site-packages (from requests->torchvision) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in f:\sd\venv\lib\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\sd\venv\lib\site-packages (from requests->torchvision) (1.26.16)
Requirement already satisfied: mpmath>=0.19 in f:\sd\venv\lib\site-packages (from sympy->torch) (1.3.0)
WARNING: There was an error checking the latest version of pip.

**Comment by robinjhuang** [comment]
Closing to consolidate conversation in https://github.com/comfyanonymous/ComfyUI/issues/1065
