### ISSUE TITLE
API random seed 

### ISSUE THREAD

**Issue by 2Pz** [comfyanonymous/ComfyUI#1085]
is there any way to set a random seed like -1 in this example ?

https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py

how to set random seed for every generation ?

Thanks

**Comment by fuami** [comment]
https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py#L150

You can feed it any seed you want on this line, including a random seed. Such as:
prompt["3"]["inputs"]["seed"] = random.randint(1,4294967294)

**Comment by dotgrid** [comment]
> You can feed it any seed you want on this line, including a random seed. Such as:
> 
> prompt["3"]["inputs"]["seed"] = random.randint(1,4294967294)

I've used this approach in my integration, and I can confirm that it works wonderfully.

**Comment by 2Pz** [comment]
i see, 
i thought there is something like -1 like A1111's api, btw thanks for the help !! :)

**Comment by 2Pz** [comment]
i see,
i thought there is something like -1 like A1111's api, btw thanks for the help !! :)

> 



> > You can feed it any seed you want on this line, including a random seed. Such as:
> > prompt["3"]["inputs"]["seed"] = random.randint(1,4294967294)
> 
> I've used this approach in my integration, and I can confirm that it works wonderfully.
