### ISSUE TITLE
FileNotFoundError when launching after first launch

### ISSUE THREAD

**Issue by oakey1979** [comfyanonymous/ComfyUI#1091]
ComfyUI runs the first time, but the subsequent launches always gives an error with double slashes in the filepaths. Win 11. How do I avoid the double slash in the filepath?  : FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\o\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\.git\\__init__.py'

Cannot import C:\Users\oakey\ComfyUI_windows_portable\ComfyUI\custom_nodes\.git module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\o\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\.git\\__init__.py'

A re-install lets me launch again, but only the first launch works. Closing and restarting results in the same error.

**Comment by ltdrdata** [comment]
You did uncompressed mistakenly to custom_nodes dir.

Remove hidden .git dir from there. And other garbage.

That type custom nodes must be placed i subfolder of custom_nodes dir.

**Comment by oakey1979** [comment]
Thanks!
