### ISSUE TITLE
KSampler (Advanced) steps / end_at_stpes

### ISSUE THREAD

**Issue by Spybyte** [comfyanonymous/ComfyUI#1095]
Hi,

I'm new to ComfyUI so it might be my mistake. I'm trying to understand the relation between steps / end_at_step. Depending on the values I use the output gets more and more noisy. I don't know if it's a bug.
So I use the SDXL base model to generate an Image. In KSampler (Advanced) I use the default settings

steps: 20 / end_at_step 10000

Now I change it to 

steps: 20 / end_at_step 20

No visible change. If I use

steps: 100 / end_at_step 20

the result is pretty blurry. It get's worse if I switch the sampler to dump_2m_sde and scheduler to arras.

If you enable return_with_leftover_noise you can't see anything at all, except colored noise.

What am I missing?

**Comment by n00mkrad** [comment]
You're supposed to use it in combination with a 2nd sampler (e.g. the SDXL refienr) that finished your denoising.

**Comment by fuami** [comment]
My understanding is that "Steps" is the total job length, and start/end steps control which of those steps to run.

So if you create a sampler with 40 steps, and stop at 20, you've stopped with the job half done.
If you duplicate the sampler, add it after the first, then set its range to 20 thru 40, it will finish the job.

You can use this in interesting ways, such as changing the prompt at various stages, as well as more esoteric things.

**Comment by Spybyte** [comment]
Thanks for clarifying. I completely misunderstood the concept behind steps.I thought it’s just the number of iterations.

**Comment by n00mkrad** [comment]
> Yes, I know. But if I limit the end_at_step to let’s say 20, why is the image getting worse if I set steps to a high number? And getting better if I set it also to 20. For me it doesn‘t make sense. In both cases it should do not more then 20 steps. Or am I wrong?

Because you only ran 20 out of 100 steps. It won't finish.

**Comment by ThioJoe** [comment]
Ok so if I'm understanding this right, basically the level of "noise to image" done per step depends on the number of steps. Starting from pure latent noise & no image to zero latent noise & pure image. So if you only two 3 steps, it does whatever amount of generation per step to finish at 3 (call it 'big change per step'). But if you do 100 steps with the same seed, theoretically you get the same final image just way higher quality. So I guess the reason the steps/end_at_step ratio matters is how far along in the process you are to what it is 'expecting'.

------------------
What I'm still unsure about is how to account for this when using the refiner KSampler. Say you have the base ksampler like:
```
steps = 100
start_at_step = 0
end_at_step = 20
```
And say you want to do 100 steps total. When you get to the refiner KSampler, do you set it up like a second separate generator, or a continuation of the first? So would it be..
```
steps = 100
start_at_step = 20
end_at_step = 100
```
or
```
steps = 80
start_at_step = 0
end_at_step = 80
```

Or does it not matter?

**Comment by Spybyte** [comment]
Yes, that makes sense now.  I was under the assumption that step is just the number of iterations. But after having a look at the source code it also calculates the denoise ration. Thank you all for clarifying.
