### ISSUE TITLE
[Feature Request] Add torch.compile support

### ISSUE THREAD

**Issue by kasper93** [comfyanonymous/ComfyUI#1097]
According to benchmark here: https://huggingface.co/docs/diffusers/main/en/optimization/torch2.0 torch.compile can give significant performance boost with certain hardware. Of course in expense of compilation time. It would be nice for Comfy to be able to utilize torch.compile. Probably not enabled by default, but with an CLI option or otherwise in node parameters.

**Comment by zsxkib** [comment]
Hi! 😊

Just checking in—has support for `torch.compile` been implemented yet? I saw the feature request and was curious if it's available in the latest version or still in progress. Thanks for the awesome work on ComfyUI! 🙏

**Comment by comfyanonymous** [comment]
Yes, you can use the TorchCompileModel node.
