### ISSUE TITLE
Feature: folder to place workflow.json files

### ISSUE THREAD

**Issue by linonetwo** [comfyanonymous/ComfyUI#110]
Currently there is no a standard place for them, they all get to the Downloads folder, become difficult to manage.

**Comment by SphaeroX** [comment]
I'm also for it here would be my suggestion (do not want to open an extra ticket for it):

**Description:**
Currently, the process of managing workflow configurations in ComfyUI involves manually downloading JSON files and moving them to the appropriate folders. I suggest introducing a centralized workflow management approach within the project to streamline this process.

**Proposal:**
Introduce a workflow management feature within the ComfyUI project. This feature would allow for the storage and retrieval of workflow configurations directly within the project, eliminating the need to manually download and move JSON files.

**Comment by ltdrdata** [comment]
In ComfyUI's new menu style, workflows are saved in `ComfyUI/user/default/workflows`.

**Comment by linonetwo** [comment]
Really? Thanks, I haven't draw things for a while. If so, I close this.

**Comment by Woisek** [comment]
Otherwise, one can either create a folder for that in the Comfy folder itself or else where convenient ... 🤷‍♂️
