### ISSUE TITLE
Support lora for stable diffusion xl

### ISSUE THREAD

**Issue by xings19** [comfyanonymous/ComfyUI#1111]
I used diffusers to train lora on sdxl, but the current Loadlora Node can't support loading these parameters

**Comment by comfyanonymous** [comment]
If you give me one of those loras I will add support for them.

**Comment by xings19** [comment]
lora weights download link:
https://cloud.tsinghua.edu.cn/f/46fba485780f45afbdd4/?dl=1

Use Diffusers can load this weight:
```python
from diffusers import DiffusionPipeline
import torch

model_path = "takuoko/sd-pokemon-model-lora-sdxl"
pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16)
pipe.to("cuda")
pipe.load_lora_weights(model_path)

prompt = "prompt."
image = pipe(prompt, num_inference_steps=30, guidance_scale=7.5).images
```

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/c5d7593ccfb4dd3a97175e01b9fa883086f5d8b4

It should work now.
