### ISSUE TITLE
[Bug] Queue order getting scrambled after each generation

### ISSUE THREAD

**Issue by thelemuet** [comfyanonymous/ComfyUI#1114]
Order looks fine initially but after the first generation from the queue is finished, the pending queue order gets scrambled and looks like this:

![queue1](https://github.com/comfyanonymous/ComfyUI/assets/86247933/526667e9-a019-4f6c-80a1-8a6fb4cc6d7a)

And gets scrambled again after each generation.

If intentionally animating from increasing/decreasing values, can't use file names or file dates to recover correct order of image sequence, have to visually go thru and rename every image one by one or rearrange on a timeline :(

Unsure what details to provide other than this started happening today after updating (thru menu). Also uninstalled any custom nodes I had installed in the last couple days to make sure, and it happens regardless of workflow (screenshot is after restarting Comfy and using default workflow).

Can anyone who updated today confirm/replicate?

**Comment by thelemuet** [comment]
Apologies, I may have gunned the jump, looks like it's only a visual bug in the UI. My issue was something else causing my sequence to seem out of order and when I noticed that the pending queue was out of order I assumed incorrectly that it was related. Issue can be closed if you feel the visual bug is not worth a fix, as it doesn't affect anything other than maybe confuse people that are lacking sleep.

**Comment by Lowkus** [comment]
It's still a bug in my opinion.
