### ISSUE TITLE
Core masking functionality has one or two small holes

### ISSUE THREAD

**Issue by coreyryanhanson** [comfyanonymous/ComfyUI#1126]
As I was building a custom node, I noticed two basic node behaviors that would be common enough for the extension ecosystem to get messy were it left up to external libraries.
* A node for "ImageCompositeMasked" - Currently while "LatentCompositeMasked" enables combining two different latents with a mask, there is currently no way to do that with regular image layers. There might be occasions where it makes sense to combine image layers with a mask before they are encoded by the vae or after they are decoded.
* An optional mask input parameter for the Save Image node (or alternatively a SaveImageMasked node). This is not only useful for present/future workflows that experiment with alpha channels, but also for previewing components during troubleshooting.

**Comment by Saquib764** [comment]
@coreyryanhanson I feel the same way, I had to use python notebook to overlay one PNG image onto another. I would be really handy to have this as a native node.

created a PR for this feature.  @comfyanonymous
