### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by FilipeF12** [comfyanonymous/ComfyUI#1133]
Where are workflows stored?

**Comment by okolenmi** [comment]
In downloads folder.

**Comment by FilipeF12** [comment]
Sorry, I was not clear. Not workflows I explicitly save, I mean workflows ComfyUI saves. See below:

Example: I create a workflow for a "dog in spacesuit in space". Shut down for the night. Next day launch ComfyUI, workflow for "dog in spacesuit in space" appears. Where is that workflow stored?

**Comment by phazzzy** [comment]
> Next day launch ComfyUI, workflow for "dog in spacesuit in space" appears. Where is that workflow stored?

Hi! Current workflow automatically stored in broswer localStorage, and restored on tab reload.

**Comment by FilipeF12** [comment]
got it. thank you!
