### ISSUE TITLE
[Feature Request] on/off switch on nodes with the same inputs and outputs

### ISSUE THREAD

**Issue by Bocian-1** [comfyanonymous/ComfyUI#114]
An 'on/off switch' on some of the nodes with the same inputs and outputs functionally turning them into Reroute nodes.

For example, a LoraLoader could be disabled this way when not needed without reconnecting any sockets. It would then pass the model and clip through as if it was a Reroute node.

**Comment by comfyanonymous** [comment]
>LoraLoader could be disabled this way when not needed without reconnecting any sockets

Setting strength to zero in the LoraLoader will also "disable" it.

**Comment by Bocian-1** [comment]
My bad, I should've thought about it. Thank you for clearing that up
