### ISSUE TITLE
Error: OpenAI API key is invalid OpenAI features wont work for you

### ISSUE THREAD

**Issue by unique311** [comfyanonymous/ComfyUI#1143]
Error: OpenAI API key is invalid OpenAI features wont work for you?

**Comment by pennyvc** [comment]
this is a bug with... quality of life suite I think, you need an API key for gpt to use some of its nodes and it throws this error.

**Comment by unique311** [comment]
Thanks., @pennyvc, that worked....
QualityOfLifeSuit_Omar92::NSP <----that was the custom node  throwing the error.
its  fixed  now.

**Comment by Piscabo** [comment]
As of today... not fixed...?
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready
ERROR:aiohttp.server:Error handling request

**Comment by pennyvc** [comment]
It requires you to provide the node an API key from chatgpt so that it can log in and run, its gonna throw that error every time until you put in an api key. I don't bother, i don't even use that part of the pack.

**Comment by Piscabo** [comment]
> 

Where exactly do do that input? I do have an API key.

**Comment by harold1110** [comment]
> > 
> 
> Where exactly does one, do that input (filename)? I do have an API key.

You can put you api key by going to the ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92  and open config.json with notepad or any other editor. There you will find "openAI_API_Key": 
Paste it in the place of example api key.

**Comment by harold1110** [comment]
> Error: OpenAI API key is invalid OpenAI features wont work for you?

1.) First get your API key from https://platform.openai.com/account/api-keys.

2.) Then go to this location: ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92 and open config.json with notepad or any other editor. There you will find "openAI_API_Key":
Paste your API key in the place of example api key.

Done!

**Comment by fmdesingproduction** [comment]
hi, i'm getting the same error

Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready

i generated a new key in 
https://platform.openai.com/api-keys
i pay for the subscription and i added 10 euros in case the error was coming for insuficent credit , installed the extention in comfyUI  from the manager and then downloading the zip file and replaced them
I changed the json file to

{
    "autoUpdate": true,
    "branch": "dev",
    "openAI_API_Key": "chat gpt api"
}

but i still get the same error , what could it be?

**Comment by mikaelE78** [comment]
I have the same error :
Error: OpenAI API key is invalid OpenAI features wont work for you.

Is there any solution?

Thank you in advance!

**Comment by JuMayr** [comment]
same here. added brand new api key. restarted everything. API Key is working with direct CURL usage.

**Comment by ltdrdata** [comment]
Unfortunately. QoL node is unmaintained for a while.

If you want to find alternatives of the GPT feature. You can find it from here.

https://github.com/vienteck/ComfyUI-Chat-GPT-Integration

Otherwise, just ignore it.

**Comment by rethink-studios** [comment]
Installed vienteck's version, set up a new key and received this error when trying to run: 
Failed to talk to OpenAi. sleeping for 10 seconds and trying again

I'm reaching out to Vienteck via discord...

**Comment by mustbeinsane** [comment]
remove the quotes then it worked
