### ISSUE TITLE
Issue with loading PNG images with transparency

### ISSUE THREAD

**Issue by Saquib764** [comfyanonymous/ComfyUI#1162]
When we remove background of any subject, the mask generated is not strictly binary i.e the mask has some value between 0-255 at the border of the subject. This produces a smooth transition from subject to the background on which it is overlayed using PIL alpha composite function.

However, in the LoadImage node, the RGB channels are exported directly w/o accounting for the transparency at the border. This produces white artifact at the subject border. This may adversely affects the latent composition done later in the workflow. Running canny edge on this image also results in a bad edge detection.

I have attached the a comparison, I use a custom node to multiple the RGB channel with its mask (right most image).

<img width="1264" alt="Screenshot 2023-08-08 at 22 18 02" src="https://github.com/comfyanonymous/ComfyUI/assets/1567949/724a2cc5-22b5-4488-a3d0-ea7129fe80b6">

Multiplying RGB with its mask changes the RGB values. I understand one might need the exact RGB values. I suggest we add a third output in the LoadImage module to handle the "smooth" edge-d subject.

**Comment by ihmily** [comment]
Maybe you need https://github.com/ihmily/ComfyUI-Light-Tool, it can load transpant image normally

![image](https://github.com/user-attachments/assets/fa6e45f4-c1b7-4b41-a2e8-e2b638de1454)

![image](https://github.com/user-attachments/assets/9dff5218-405f-4e48-b14a-8cb53a356816)
