### ISSUE TITLE
How to use comfyUI on the Sagemaker Studio Lab

### ISSUE THREAD

**Issue by csnEDGMC** [comfyanonymous/ComfyUI#1167]
SageMaker Studio Lab cannot install software and use NPM.

I can start stable diffusion, but I can't use it.

Gradio (or localtunnel) don't work on SageMaker SL, so ngrok is used instead.

I don't know how to use ngrok, I ask for your help and tell me to run the code.

Thanks!

**Comment by imner0** [comment]
> SageMaker Studio Lab cannot install software and use NPM.
> 
> I can start stable diffusion, but I can't use it.
> 
> Gradio (or localtunnel) don't work on SageMaker SL, so ngrok is used instead.
> 
> I don't know how to use ngrok, I ask for your help and tell me to run the code.
> 
> Thanks!

do you find any solution?
