### ISSUE TITLE
Broken Software

### ISSUE THREAD

**Issue by Webslug** [comfyanonymous/ComfyUI#1185]
Comfy UI does not work out of the box on Windows, hopefully I can get it to work.

![rubbish](https://github.com/comfyanonymous/ComfyUI/assets/7551638/23e3fdc2-6c46-4719-8595-6414c1e3b93b)

**Comment by comfyanonymous** [comment]
I don't know how you missed the README_VERY_IMPORTANT.txt file but it has documentation for that: https://github.com/comfyanonymous/ComfyUI/blob/master/.ci/windows_base_files/README_VERY_IMPORTANT.txt#L15

**Comment by Webslug** [comment]
I downloaded the v1-5-pruned-emaonly.ckpt file and placed it in the checkpoints sub folder.

Still does not work.  I can only conclude this software is broken.

Thanks.

**Comment by Webslug** [comment]
I placed the file in the checkpoints folder but it still does not work. 

v1-5-pruned-emaonly.ckpt

Broken software, giving up.  Thanks anyway.
