### ISSUE TITLE
UserWarning bug ?

### ISSUE THREAD

**Issue by Fhantomchaos** [comfyanonymous/ComfyUI#119]
So i got this bug while trying to make a pic after the Area Composition Examples
any one had ideal how can i fix this  ?
```
  0%|                                                                                           | 0/13 [00:00<?, ?it/s]C:\Users\Dtrun\AppData\Local\Programs\Python\Python310\lib\site-packages\torchsde\_brownian\brownian_interval.py:594: UserWarning: Should have tb<=t1 but got tb=14.614644050598145 and t1=14.614644.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")

```

**Comment by comfyanonymous** [comment]
That's a harmless warning, you can ignore it.

**Comment by Fhantomchaos** [comment]
> That's a harmless warning, you can ignore it.

 oh I see, this seems to report like stopping the process for each area in the image in order
 Thanks you for your work 👍
