### ISSUE TITLE
Please, make it so connecting a node takes the first free of the same type and if nothing free then take the first of the same type.

### ISSUE THREAD

**Issue by Extraltodeus** [comfyanonymous/ComfyUI#1196]
It would be a lot more efficient as we could just start throwing connexions across the workflow instead of having to zoom and aim precisely at the input. I keep missing the input connectors 😪

**Comment by M1kep** [comment]
Current Behavior:
- Connection always goes to the first slot of with matching type, regardless if it is connected already(GIF attached)

Requested Behavior:
- Connection goes to first free slop of matching type. If there is are free slots, overwrite the first one(Fallback to current implementation)

This sound right?

![CleanShot 2023-08-12 at 13 01 37](https://github.com/comfyanonymous/ComfyUI/assets/2661819/d67c6d5d-d163-4c60-b68a-436a443b9db8)

**Comment by Extraltodeus** [comment]
>This sound right?
Yes it does! (I guess that by "If there is are free slots" you meant "If there there are no free slots")

I've been looking through the .js files and even found the matching functions in litegraph.core.js then used GPT4 to try to guess what to do but gave up after two hours because nothing had any effect and I really don't know neither the framework nor really am I an afficionado of javascript.

**Comment by alexbofa** [comment]
this is a great idea

**Comment by ltdrdata** [comment]
This is fixed in new front.
