### ISSUE TITLE
[Feature Request] Custom node plugin API

### ISSUE THREAD

**Issue by ljleb** [comfyanonymous/ComfyUI#12]
In my opinion this idea has so much potential. It's really cool to be able to set up my own pipeline without having to write a single line of code.

I would like the community to be able to create custom nodes like upscaler nodes or controlnet processing, text nodes (i.e. to reuse prompts for different parts of the same pipeline), stuff like this.

How hard would it be to make an API that allows people to write their own nodes as external code?

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/tree/master/custom_nodes

The node format will probably change a bit though.
