### ISSUE TITLE
Saving to an SMB share?

### ISSUE THREAD

**Issue by PlantsThatsWhatsUp** [comfyanonymous/ComfyUI#1203]
I'm on ubuntu trying to change output to an SMB share so I'm running:
python3 main.py --listen --output-directory smb://IP/share

but it's not working (it makes a subdirectory in the comfyui folder). Is what I'm trying to do possible?

**Comment by M1kep** [comment]
Are you running on Linux or Windows?

IMO, it may just be easier to mount the SMB on startup and then point comfy to the mount point, but am interested to see what it would take to work

**Comment by PlantsThatsWhatsUp** [comment]
Thanks for the response. Running Linux; I ended up mounting the share on boot by modifying fstab which worked perfectly. I think that's a sufficiently complete solution and hopefully someone looking for the same will see this thread and suggestion.
