### ISSUE TITLE
FEAT: evaluate implementing "negative ADM guidance"

### ISSUE THREAD

**Issue by tildebyte** [comfyanonymous/ComfyUI#1217]
WDYT? Worthwhile, or cargo-cult BS?

https://github.com/lllyasviel/Fooocus/blob/main/modules/adm_patch.py (implementation of bullet 2 from https://github.com/lllyasviel/Fooocus/tree/main#tech_list), to wit:

> Negative ADM guidance. Because the highest resolution level of XL Base does not have cross attentions, the positive and negative signals for XL's highest resolution level cannot receive enough contrasts during the CFG sampling, causing the results look a bit plastic or overly smooth in certain cases. Fortunately, since the XL's highest resolution level is still conditioned on image aspect ratios (ADM), we can modify the adm on the positive/negative side to compensate for the lack of CFG contrast in the highest resolution level.

**Comment by tildebyte** [comment]
Addl. info:

It really boils down to monkey-patching [`SDXL(BaseModel).encode_adm()`](https://github.com/comfyanonymous/ComfyUI/blob/0cb6dac943a2550f6e5c5cf4f99a64b40c89ac80/comfy/model_base.py#L181) with

```python
    if kwargs.get("prompt_type", "") == "negative":
        width *= 0.8
        height *= 0.8
    elif kwargs.get("prompt_type", "") == "positive":
        width *= 1.5
        height *= 1.5
```

**Comment by comfyanonymous** [comment]
From our tests this doesn't seem to improve anything, it also directly contradicts the point number 6 on that repo.

**Comment by tildebyte** [comment]
Yeah, I tried it locally... I was not impressed.

**Comment by FrancescoSaverioZuppichini** [comment]
is there a paper for `Negative ADM guidance` I have no idea of what ADM is

**Comment by stephantual** [comment]
Given that "reimplementing fooocus in comfyUI" has become a bit of a rite of passage for a lot of us, I'm glad to report this thread is #1 on google when searching for "negative ADM guidance". Thank you @comfyanonymous for comfirming what we always suspected.
