### ISSUE TITLE
Image to image adds bright line artifacts towards the edges on lower denoise values

### ISSUE THREAD

**Issue by ramyma** [comfyanonymous/ComfyUI#1245]
Running a simple image to image flow with denoise value ~ < 0.5 results in bright artifact lines.

I made a comparison to A1111 and it doesn't have the same issue.
You might want to open the images in an image editor to be able to zoom in to see it more clearly.

Examples:
input
![black](https://github.com/comfyanonymous/ComfyUI/assets/14105815/19ae2eaa-6aaf-4378-93fa-4d01d02b1494)
Comfy Output  - denoise 0.01
![ComfyUI_00114_](https://github.com/comfyanonymous/ComfyUI/assets/14105815/ad9b3a54-4541-41af-8d2a-fa5d1fcfa47a)
A1111 Output - denoise 0.01
![image](https://github.com/comfyanonymous/ComfyUI/assets/14105815/c1dcc447-2f89-43aa-9729-5940f3cc7b7e)

Input
![image (181)](https://github.com/comfyanonymous/ComfyUI/assets/14105815/78e46f58-8ea6-4137-8e33-4a1fa378ce08)

Comfy Output - denoise 0.01
![ComfyUI_00113_](https://github.com/comfyanonymous/ComfyUI/assets/14105815/5f6601d2-df69-4616-91e9-d0bbd764706d)
A1111 Output - denoise 0.01
![image](https://github.com/comfyanonymous/ComfyUI/assets/14105815/b7c5b0b5-bd82-4ca9-8c6d-8cf544fa0be4)

Comfy Output ( check right and bottom borders and overall quality compared to the A1111 output) - denoise 0.36
![ComfyUI_00112_](https://github.com/comfyanonymous/ComfyUI/assets/14105815/839bcb77-83f6-4d76-95fc-dd7d3a98e68d)
A1111 Output - denoise 0.36
![image](https://github.com/comfyanonymous/ComfyUI/assets/14105815/119878a1-786a-4b4c-a4fc-db6d86c5ccd9)

Comfy Flow:
![Screenshot from 2023-08-17 04-49-19](https://github.com/comfyanonymous/ComfyUI/assets/14105815/2115017b-b34a-41ab-afc7-507c5cc344bc)

A1111 Params:
![Screenshot from 2023-08-17 04-55-16](https://github.com/comfyanonymous/ComfyUI/assets/14105815/5b4205e8-a921-4cc9-a3fc-04c5165d89f8)

**Comment by ramyma** [comment]
@comfyanonymous this seems like a deeply rooted issue, it certainly affects any loop back flow with lower denoise values. I hope you can have a look at it, thanks!

**Comment by ramyma** [comment]
@comfyanonymous does https://github.com/comfyanonymous/ComfyUI/commit/bed116a1f916f23b65c7b68cf60d09b2401fcf29 fix this issue?

**Comment by comfyanonymous** [comment]
yes this issue should be fixed now

**Comment by ramyma** [comment]
It seems like it's actually fixed, thanks!
