### ISSUE TITLE
High VRAM usage since "Smarter memory management" commit

### ISSUE THREAD

**Issue by MoonRide303** [comfyanonymous/ComfyUI#1246]
Happens since introducing "Smarter memory management" - previously Comfy was keeping low VRAM usage and allowed using other applications while running it. Since this change Comfy easilly eats up to 16 GB of VRAM when using both SDXL models.

Trying to emulate behaviour of 8 GB VRAM GPU (by adding `torch.cuda.set_per_process_memory_fraction(0.5, 0)` at the beginning of `model_management.py`) results in errors like that:
```
Error occurred when executing KSamplerAdvanced:

Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated : 7.99 GiB
Requested : 10.00 MiB
Device limit : 15.99 GiB
Free (according to CUDA): 6.61 GiB
PyTorch limit (set by user-supplied memory fraction)
: 8.00 GiB
```

even when trying to generate single 1024x1024 image. Previous commit stays under 8 GB for the same use case. Could we have this new VRAM-eater implementation made optional, not the default? Or, alternatively, maybe we could have parameter defining amount of VRAM (GB / %) that Comfy would try not to cross?

**Comment by comfyanonymous** [comment]
It will eat up the free memory but it should still allow the use of other apps because the calculations are based on the amount of free vram not the total amount.

I added --disable-smart-memory for those that want the old behaviour: https://github.com/comfyanonymous/ComfyUI/commit/3aee33b54e53e032755edf253ba39005bae6e20e

**Comment by MoonRide303** [comment]
Verified on [1498f1a3423292495a5aab9941208cecdc30ac38](https://github.com/comfyanonymous/ComfyUI/commit/1498f1a3423292495a5aab9941208cecdc30ac38), VRAM usage stays under 8 GB with `--disable-smart-memory` while generating 1024x1024 using 2-stage SDXL workflow - closing.
