### ISSUE TITLE
Weired error when run inference with SDXL on 32GB mem

### ISSUE THREAD

**Issue by lucasjinreal** [comfyanonymous/ComfyUI#1253]
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1147, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: API call is not supported in the installed CUDA driver
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

How could this happen, 32GB should enough for SDXL, and my cuda enviroment runs anything else OK.

**Comment by comfyanonymous** [comment]
Try: --disable-cuda-malloc
