### ISSUE TITLE
Support clip_g vision model

### ISSUE THREAD

**Issue by laksjdjf** [comfyanonymous/ComfyUI#1254]
I am currently developing a [custom node](https://github.com/laksjdjf/IPAdapter-ComfyUI) for the [IP-Adapter](https://github.com/tencent-ailab/IP-Adapter). 
The IP-Adapter for SDXL uses the [clip_g vision model](https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models/image_encoder), but ComfyUI does not seem to be able to load this.
Would it be possible for you to add functionality to load this model in ComfyUI?

**Comment by comfyanonymous** [comment]
It's now supported: https://github.com/comfyanonymous/ComfyUI/commit/76d53c4622fc06372975ed2a43ad345935b8a551
