### ISSUE TITLE
VRAM usage spikes during VAE after update

### ISSUE THREAD

**Issue by cmcjas** [comfyanonymous/ComfyUI#1256]
Hi, earlier today I've made an update to my ComfyUI (windows portable version) through the ComfyUI Manager extension, but after the update I've noticed that my vram usage spikes during the vae process. I was generating at 1216x832 resolution with SDXL, which used to max out at around 6-7gb of vram usage during vae on my RTX 3080. However, after the update, my vram usage went up to almost 10gb during vae, and this also happens when using the Ultimate SD upscale extension, as a result, I do sometimes experience sudden slow down with the user interface during these moments. I've not changed drives or any of my settings, so I'm pretty sure it's caused by the latest update. Strangely enough, vram usage during both the base & refiner generation process actually went down a bit with the latest update, it's just the vae process towards the end saw a noticeable increase in vram usage. 

It would be appreciated if someone could give me some advice on this or tell me how to downgrade my ComfyUI to an older version. Thanks

**Comment by comfyanonymous** [comment]
Are you using the nightly or the regular?

**Comment by cmcjas** [comment]
> Are you using the nightly or the regular?

Sorry I'm not so sure which build I'm using atm. I downloaded ComfyUI from the main github page many weeks ago when SDXL 0.9 first released to the public, so very much a newbie here. Since then I've done numerous updates through either update_comfyui.bat or the manager extension, but I do know there's a folder called nightly inside my .ci directory.

**Comment by cmcjas** [comment]
Here's a quick update, after some digging I finally managed to find the releases page for ComfyUI on GitHub. From there, I downloaded one of the regular build that's 4 days old, and did some testing and no longer have the vram spikes issue that I've mentioned earlier, so it seems the latest build broke something, maybe it's to do with the new Intel Arc GPU implementation? 

Also with the latest update, I keep seeing this new log - 'loading new' on my cmd which seems a bit curious. 

In any case, I will stick with this 4 days old build for now until this vram issue with vae is fixed.

**Comment by comfyanonymous** [comment]
Does it fix it if you use: --disable-smart-memory ?

**Comment by cmcjas** [comment]
> Does it fix it if you use: --disable-smart-memory ?

I pasted this command into my run.bat and I would like to confirm that it did indeed fixe the vram spikes issue related to vae when using SDXL. Thanks. Perhaps you should mention this on the github page, as it could be helpful for those with limited vram.
