### ISSUE TITLE
How to use command line arguments like --disable-smart-memory when you are run using "python main.py" from cmd ?

### ISSUE THREAD

**Issue by One1-Piece** [comfyanonymous/ComfyUI#1271]

**Comment by Arron17** [comment]
python main.py --cuda-malloc --preview-method auto --disable-smart-memory

And whatever else arguments you want

**Comment by One1-Piece** [comment]
Thanks !

**Comment by Kicher2006** [comment]
Can you explain step by step what needs to be done, I don't know much about code but I can copy and paste where needed.

**Comment by ltdrdata** [comment]
> Can you explain step by step what needs to be done, I don't know much about code but I can copy and paste where needed.

If you are using portable version. Edit `run_nvidia_gpu.bat`
