### ISSUE TITLE
Abysmal speed since "Update"?

### ISSUE THREAD

**Issue by Niutonian** [comfyanonymous/ComfyUI#1272]
I've been a ComfyUI user since its inception, and until now I never had any speed problems, but since yesterday evening, I haven't been able to render any images. Loading the base model take 6min + then the refiner stage is almost 30 minutes. 

i9-11900KF
RTX 3070 8Gb + 16Gb Ram
I do not know what happened never had a problem with Comfy,
Can anyone help me debug it, 

Cheers

[full console output --> PasteBin](https://pastebin.com/LUd0hiUr)

-----------------------------------------
Total VRAM 8192 MB, total RAM 16266 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
Using xformers cross attention
Adding extra search path checkpoints E:\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs E:\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae E:\stable-diffusion-webui\models/VAE
Adding extra search path loras E:\stable-diffusion-webui\models/Lora
Adding extra search path loras E:\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models E:\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models E:\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models E:\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings E:\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks E:\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet E:\stable-diffusion-webui\models/ControlNet
 
Import times for custom nodes:
   0.2 seconds: E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
 
Starting server
 
To see the GUI go to: http://127.0.0.1:8188
got prompt
Failed to validate prompt for output 57:
* ImageUpscaleWithModel 56:
  - Required input is missing: image
Output will be ignored
Failed to validate prompt for output 53:
* ImageUpscaleWithModel 54:
  - Required input is missing: image
Output will be ignored

-----------------------------------------
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
left over keys: dict_keys(['conditioner.embedders.1.model.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
loaded straight to GPU
loading new
loading new
loading new
unload clone 1
100%|████████████████████████████████████████████████████████████████████████████████| 373/373 [03:08<00:00,  1.98it/s]
-----------------------------------------
100%|██████████████████████████████████████████████████████████████████████████████| 3438/3438 [31:48<00:00,  1.80it/s]
E:\COMFYUI\ComfyUI_windows_portable\ComfyUI\nodes.py:1269: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
Prompt executed in 2658.78 seconds

**Comment by One1-Piece** [comment]
True, also for me, it took so long to load the refiner, and sometimes it gets stuck at the start of the Ksampler node, It says **"loading new"** and then I have to wait very long until it finishes, but after the same prompt again will not cause slowness. Once I change the prompt it will again take too long to do the entire process again. I think just before the **"loading new"** update it worked properly. 

I tried using **--disable-smart-memory** which did help but it reduces my speed for some reason.

**Comment by Niutonian** [comment]
I will try  --disable-smart-memory too.

**Comment by comfyanonymous** [comment]
So this happens even on the latest update?

**Comment by Niutonian** [comment]
As of now yes, but let me update it to the latest and report if it still takes forever to generate images

**Comment by One1-Piece** [comment]
Hi, The Checkpoints Loader both the base and refiner are faster now, but now It gets Stuck at **KSampler Node** and takes too long. It said the prompt executed in **765.73 seconds**. I do remember before the "loading new" update it took around max 100 - 150 sec at the start. I do have RTX 3080 10GB, I think VRAM is not that bad.

**Comment by One1-Piece** [comment]
Hi, After the Update, The Checkpoint Loaders both the base and refiner are faster now, but now It gets Stuck at **KSampler Node** and takes too long. It said the prompt executed in **765.73 seconds**. I do remember before the "loading new" update it took around max 100 - 150 sec at the start. I am using RTX 3080 I think VRAM is not that bad.

**Comment by acofalc** [comment]
I have the same problem from recent update. I have 3070ti 8gb and 32gb ram, i know it is not the best vram but speed was acceptable. Now is 3-4 times slower, "loading new" is showing often.

**Comment by eldragon0** [comment]
I'm seeing really bad memory leak issue. 4090 is having a hard time running anything over 1kx1k on sdxl, where I can do 3.5k x 3.5k on 1.5 without an issue.  I just bounce off 24GB vram used until it crashes

**Comment by comfyanonymous** [comment]
If you have this issue can you update to the latest and see if it improved. If you still have it can you post more info about your system?

Information like:
Total amount of ram
Your operating system
Your GPU
Which version do you have: regular standalone, nightly standalone, manual install?

**Comment by Niutonian** [comment]
I just added some RAM today hoping it would fix the issue but I still get a black image.
Comfy work well using 1.5 though, so the problem seems to be SDXL related.
My setup:
64Gb
RTX3070 8Gb
Windows 11
I use Comfy standalone regular.
-
I will attach my workflow below, the image is black

![SDXL_0 9_Output_00129_](https://github.com/comfyanonymous/ComfyUI/assets/89068652/f3b2a84c-96c7-44f8-9fdb-a47fb4351636)

**Comment by eldragon0** [comment]
Comfyui windows portable, fully up to date
13900k,
32 GB ram
windows 11 h2
4090 newest drivers
works fine with 1.5 and 2.0 flows, but sdxl loads the checkpoints, take up about 19GB vram, then pushes to 24 GB vram upon running a prompt, once the prompt finishes, (or if I cancel it) it just sits at 24 GB until I close out the comfyui command prompt

**Comment by comfyanonymous** [comment]
Just to make sure can you grab the latest version of the windows portable, don't install anything except the SDXL + refiner checkpoints and run the example workflow https://comfyanonymous.github.io/ComfyUI_examples/sdxl/

**Comment by One1-Piece** [comment]
Hi ! Hope you are all doing well. After the new update, These are the improvements that I've observed and am quite happy with:

1. The initial launch for ComfyUI significantly improved, reducing from **750 sec** to **250 sec** when I first press the Queue button. After that, it is the normal speed for generations.
2. Checkpoints are loading fast now even if I change them.
3. It does not get stuck at KSampler nodes like before.
4. Now if I change prompts, it does not take much time to proceed to the KSampler Node, and I think now it is even better than before the "loading new" update came.
5. Also now the ComfyUI FrontEnd is smoother than before as it does not get stuck so I am able to move my mouse even when the whole process is going on from start to finish because I couldn't move my mouse properly before as it used to get stuck.

I will let you know in case there are errors or if something unusual happens.

Thanks for the update, really appreciate it ! 😀

**Comment by Niutonian** [comment]
Hello, reinstalling the app using the latest Windows portable version has solved the problems, and as One1-Piece has noted, everything seems to be faster!!
@comfyanonymous thanks a lot for the update and for putting in the work,

**Comment by eldragon0** [comment]
> Just to make sure can you grab the latest version of the windows portable, don't install anything except the SDXL + refiner checkpoints and run the example workflow https://comfyanonymous.github.io/ComfyUI_examples/sdxl/

I hang around 16GB vram usage when I run this, but if I do any additonal upscaling I bounce off 24GB still.

**Comment by t8ja** [comment]
Can anyone run this workflow with 8GB of Vram ?
[https://github.com/nerdyrodent/AVeryComfyNerd/blob/main/Reposer.png](url)

`torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 5.86 GiB
Requested               : 101.53 MiB
Device limit            : 7.92 GiB
Free (according to CUDA): 68.94 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
`

Perhaps if there was a way to run workflows from the command line, thereby saving some browser taken Vram...
