### ISSUE TITLE
Error occurred when executing CheckpointLoaderSimple

### ISSUE THREAD

**Issue by enslaved2die** [comfyanonymous/ComfyUI#1283]
I dont understand this issue.
Im using StableSwarmUI and this is happening on an additional ComfyUI Backend.
Any ideas?

```
Error occurred when executing CheckpointLoaderSimple:

Error while deserializing header: MetadataIncompleteBuffer

File "C:\opt\stable\comfy\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\opt\stable\comfy\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\opt\stable\comfy\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\opt\stable\comfy\ComfyUI\nodes.py", line 446, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
File "C:\opt\stable\comfy\ComfyUI\comfy\sd.py", line 1316, in load_checkpoint_guess_config
sd = utils.load_torch_file(ckpt_path)
File "C:\opt\stable\comfy\ComfyUI\comfy\utils.py", line 11, in load_torch_file
sd = safetensors.torch.load_file(ckpt, device=device.type)
File "C:\opt\stable\comfy\python_embeded\lib\site-packages\safetensors\torch.py", line 309, in load_file
with safe_open(filename, framework="pt", device=device) as f:
```

Edit: 
Happening on 2.1 and SDXL based Models
Comfy is up to date
When I use a working ComfyUI Backend copy the whole folder to the other computer it still doesnt work.
The only difference between the working one and the not working one is the working one has a GTX1070 and the not working one a GTX1080ti

**Comment by enslaved2die** [comment]
I used a Git Repository to manage all my Models, this was the problem somehow only manual downloaded ones work.
Dont know why, but works for now...

**Comment by ShashwatDubey99** [comment]
i am having the same problem

**Comment by hattabe** [comment]
Just update custom nodes: ComfyUI_smZNodes

cd /ComfyUI/custom_nodes/ComfyUI_smZNodes
git pull

or you can use manager to update ComfyUI_smZNodes

**Comment by bobcanada** [comment]
I am having the same problem.  Tt's puzzel for me.

**Comment by KellyHeongoing** [comment]
I have updated custom nodes: ComfyUI_smZNodes, but not solved the problmes, is there other method?

**Comment by kodai-rr** [comment]
having the same issue 

![Image](https://github.com/user-attachments/assets/5c5629b3-298a-4471-b5fe-576dc5fba7b0)

**Comment by kodai-rr** [comment]
has anyone found a solution yet?

**Comment by ltdrdata** [comment]
> has anyone found a solution yet?

It seems like your model file might be invalid.
