### ISSUE TITLE
Stop/Cancel queue hotkey?

### ISSUE THREAD

**Issue by Lex-DRL** [comfyanonymous/ComfyUI#1290]
I can't find such hotkey in the [community wiki](https://blenderneko.github.io/ComfyUI-docs/Interface/Shortcuts/).

How about adding it?

I suggest `Ctrl+?` to cancel the current operation and `Ctrl+Shift+?` to clear the entire queue, where `?` might be either of:
- Actually, `.` (so, `?` with shift)
- `PageDn` (with semantic meaning "go to end", but an actual `End` usually has a ton of functionality attached to it already)
- `\`
- `Pause`

These keys are chosen as:
- Non-conflicting with Ctrl/Ctrl+Shift combinations within text field;
- Not used in graph currently (and rarely used at all);
- Located near Enter (to switch fast between start/stop when playing with prompt).

**Comment by thewayur** [comment]
or BIG CANCEL button (atleast for now)

**i came here create this shortcut recommendation and u already did this.**

**Comment by fernicar** [comment]
Or just Escape to cancel if not in modal or dialog, hold Escape to clean queue.
could be added at:
ComfyUI_windows_portable\ComfyUI\web\extensions\core\keybinds.js
			// Close out of modals using escape

**Comment by Lex-DRL** [comment]
@fernicar Doesn't escape conflict with "cancel edits" action when editing a field's contents?

**Comment by GameMusicSmash** [comment]
Hello All ..
So all you have to do to cancel the comfyUI operation :

Under "Queue Prompt" button
a small button "View Queue"

Whatevver you see Running press "Cancel"

Happy Comfing

**Comment by Lex-DRL** [comment]
@GameMusicSmash Yes, I'm pretty sure everyone who commented in this thread is aware about it.
But the issue is about doing so **with a hotkey**.

ComfyUI seriously lacks in UX department, and lack of convenient hotkeys is one of those areas.
