### ISSUE TITLE
error when using control-lora

### ISSUE THREAD

**Issue by garychan22** [comfyanonymous/ComfyUI#1315]
hi, I am trying to use the pretrained control-lora released by stableai [https://huggingface.co/stabilityai/control-lora]() but got the error
```
got prompt
Failed to validate prompt for output 8:
* ControlNetLoader 9:
  - Value not in list: control_net_name: 'control-lora/control-lora-recolor-rank256.safetensors' not in []
Output will be ignored
```
how can I resolve this problem? thanks!

**Comment by garychan22** [comment]
I have found that this error appears when I have not put the model into the controlnet folder, resolved now!

**Comment by sayakpaul** [comment]
I am dealing with something similar:

```
got prompt
Failed to validate prompt for output 8:
* ControlNetLoader 9:
  - Value not in list: control_net_name: 'control-lora/control-lora-canny-rank256.safetensors' not in ['control-lora-canny-rank256.safetensors']
Output will be ignored
```

I have put the ControlLoRA file in the appropriate folder too:

<img width="948" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/22957388/5e641c4f-dd36-4cf8-8a05-5579f1292079">

Any idea on how I could mitigate this?

**Comment by ltdrdata** [comment]
> I am dealing with something similar:
> 
> ```
> got prompt
> Failed to validate prompt for output 8:
> * ControlNetLoader 9:
>   - Value not in list: control_net_name: 'control-lora/control-lora-canny-rank256.safetensors' not in ['control-lora-canny-rank256.safetensors']
> Output will be ignored
> ```
> 
> I have put the ControlLoRA file in the appropriate folder too:
> 
> <img width="948" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/22957388/5e641c4f-dd36-4cf8-8a05-5579f1292079">
> 
> Any idea on how I could mitigate this? 

refesh browser or click refresh button.

Your node's model specify subdir "control-lora" which is not yours.

**Comment by sayakpaul** [comment]
That cut it. Thanks!
