### ISSUE TITLE
ComfyUI Portable

### ISSUE THREAD

**Issue by DerD4nnY** [comfyanonymous/ComfyUI#1331]
Hey there, 

I downloaded the Portable... started the .bat .... and once I try "Queue Prompt" I get this: 

https://preview.redd.it/a8w10xs17bkb1.png?width=1503&format=png&auto=webp&s=2c3ba812a787d014ad30a46572dd1aeba3052dd0

**Comment by comfyanonymous** [comment]
Make sure your .ckpt file isn't corrupt and the right size (2 or more gigabytes).

**Comment by DerD4nnY** [comment]
ok I will try it thank you very much :)

**Comment by DerD4nnY** [comment]
> Make sure your .ckpt file isn't corrupt and the right size (2 or more gigabytes).

ckpt.... or safetensors... testint 1.99 GB Safetensor now
