### ISSUE TITLE
Only able to do one controlnet image then have to reload the model

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [comfyanonymous/ComfyUI#1334]
It works for the first image then I get this

100%|##################################################################################| 30/30 [00:15<00:00,  1.93it/s]
Prompt executed in 43.71 seconds
3
Prompt executed in 0.00 seconds
got prompt
3
Prompt executed in 0.00 seconds
got prompt
3
Prompt executed in 0.00 seconds
got prompt
3
Prompt executed in 0.00 seconds
got prompt
3
Prompt executed in 0.00 seconds
got prompt
3
Prompt executed in 0.00 seconds
got prompt
3
Prompt executed in 0.00 seconds
got prompt
3
Prompt executed in 0.00 seconds

Have to reset the model again

![image](https://github.com/comfyanonymous/ComfyUI/assets/77267159/2a90027b-33ac-4b5b-ad96-e7f77c5f4c02)

![image](https://github.com/comfyanonymous/ComfyUI/assets/77267159/eae2bf0e-568f-4e0f-b6f5-2c1a92950eaf)

I hit queue nothing happens on all models

**Comment by mcmonkey4eva** [comment]
Nothing happens because your seed is fixed and input is unchanged, ie there's nothing new to do, the output will be the same.
