### ISSUE TITLE
Error occurs when executing SDXL Base Prompt Encoder

### ISSUE THREAD

**Issue by var1ableX** [comfyanonymous/ComfyUI#1336]
Earlier today this flow was working. Below the issue comes up when using CR flavour of the SDXL specific prompt encoder. I can confirm the same issue comes up with the native SDXL base prompt encoder as well. 

Workaround is to use the older style prompt encoder.

Error occurred when executing CR SDXL Base Prompt Encoder:

list indices must be integers or slices, not str

File ".../ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File ".../ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File ".../ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File ".../ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/Comfyroll_Nodes.py", line 1029, in encode
tokens1["l"] = base_clip.tokenize(pos_l)["l"]

![comfyui_SDXL_prompt_issue](https://github.com/comfyanonymous/ComfyUI/assets/839040/56bc6323-306b-44e2-92e6-55a94c2bcdaa)

**Comment by mcmonkey4eva** [comment]
This should be reported to the comfyroll extension
