### ISSUE TITLE
Windows Zip Installer Package contains Torch 0.21 Dev from Nightly

### ISSUE THREAD

**Issue by WinstonWoof** [comfyanonymous/ComfyUI#1337]
as of around 22:00 BST Aug25 both zip files from your github page contain0.21 dev version of torch dated 24 Aug

I have an older one that is dated 3 Aug that is fine

![image](https://github.com/comfyanonymous/ComfyUI/assets/128506111/c2b764bb-f5bf-4ba2-89da-4e2de2f4b9fe)

**Comment by mcmonkey4eva** [comment]
...?
