### ISSUE TITLE
 [Bug] Added support for lora with norms

### ISSUE THREAD

**Issue by ckmlai** [comfyanonymous/ComfyUI#1347]
Right now, loras/lycoris with trained norm layers fail to load.
Is the patch from https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/12503/commits aplicable in here?

`lora key not loaded lora_unet_down_blocks_0_attentions_0_norm.b_norm
lora key not loaded lora_unet_down_blocks_0_attentions_0_norm.w_norm
lora key not loaded lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_down_blocks_0_attentions_1_norm.b_norm
lora key not loaded lora_unet_down_blocks_0_attentions_1_norm.w_norm
lora key not loaded lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_down_blocks_0_resnets_0_norm1.b_norm
lora key not loaded lora_unet_down_blocks_0_resnets_0_norm1.w_norm
lora key not loaded lora_unet_down_blocks_0_resnets_0_norm2.b_norm
lora key not loaded lora_unet_down_blocks_0_resnets_0_norm2.w_norm
lora key not loaded lora_unet_down_blocks_0_resnets_1_norm1.b_norm
lora key not loaded lora_unet_down_blocks_0_resnets_1_norm1.w_norm
lora key not loaded lora_unet_down_blocks_0_resnets_1_norm2.b_norm
lora key not loaded lora_unet_down_blocks_0_resnets_1_norm2.w_norm
lora key not loaded lora_unet_down_blocks_1_attentions_0_norm.b_norm
lora key not loaded lora_unet_down_blocks_1_attentions_0_norm.w_norm
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_down_blocks_1_attentions_1_norm.b_norm
lora key not loaded lora_unet_down_blocks_1_attentions_1_norm.w_norm
lora key not loaded lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_down_blocks_1_resnets_0_norm1.b_norm
lora key not loaded lora_unet_down_blocks_1_resnets_0_norm1.w_norm
lora key not loaded lora_unet_down_blocks_1_resnets_0_norm2.b_norm
lora key not loaded lora_unet_down_blocks_1_resnets_0_norm2.w_norm
lora key not loaded lora_unet_down_blocks_1_resnets_1_norm1.b_norm
lora key not loaded lora_unet_down_blocks_1_resnets_1_norm1.w_norm
lora key not loaded lora_unet_down_blocks_1_resnets_1_norm2.b_norm
lora key not loaded lora_unet_down_blocks_1_resnets_1_norm2.w_norm
lora key not loaded lora_unet_down_blocks_2_attentions_0_norm.b_norm
lora key not loaded lora_unet_down_blocks_2_attentions_0_norm.w_norm
lora key not loaded lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_down_blocks_2_attentions_1_norm.b_norm
lora key not loaded lora_unet_down_blocks_2_attentions_1_norm.w_norm
lora key not loaded lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_down_blocks_2_resnets_0_norm1.b_norm
lora key not loaded lora_unet_down_blocks_2_resnets_0_norm1.w_norm
lora key not loaded lora_unet_down_blocks_2_resnets_0_norm2.b_norm
lora key not loaded lora_unet_down_blocks_2_resnets_0_norm2.w_norm
lora key not loaded lora_unet_down_blocks_2_resnets_1_norm1.b_norm
lora key not loaded lora_unet_down_blocks_2_resnets_1_norm1.w_norm
lora key not loaded lora_unet_down_blocks_2_resnets_1_norm2.b_norm
lora key not loaded lora_unet_down_blocks_2_resnets_1_norm2.w_norm
lora key not loaded lora_unet_down_blocks_3_resnets_0_norm1.b_norm
lora key not loaded lora_unet_down_blocks_3_resnets_0_norm1.w_norm
lora key not loaded lora_unet_down_blocks_3_resnets_0_norm2.b_norm
lora key not loaded lora_unet_down_blocks_3_resnets_0_norm2.w_norm
lora key not loaded lora_unet_down_blocks_3_resnets_1_norm1.b_norm
lora key not loaded lora_unet_down_blocks_3_resnets_1_norm1.w_norm
lora key not loaded lora_unet_down_blocks_3_resnets_1_norm2.b_norm
lora key not loaded lora_unet_down_blocks_3_resnets_1_norm2.w_norm
lora key not loaded lora_unet_mid_block_attentions_0_norm.b_norm
lora key not loaded lora_unet_mid_block_attentions_0_norm.w_norm
lora key not loaded lora_unet_mid_block_attentions_0_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_mid_block_attentions_0_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_mid_block_attentions_0_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_mid_block_attentions_0_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_mid_block_attentions_0_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_mid_block_attentions_0_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_mid_block_resnets_0_norm1.b_norm
lora key not loaded lora_unet_mid_block_resnets_0_norm1.w_norm
lora key not loaded lora_unet_mid_block_resnets_0_norm2.b_norm
lora key not loaded lora_unet_mid_block_resnets_0_norm2.w_norm
lora key not loaded lora_unet_mid_block_resnets_1_norm1.b_norm
lora key not loaded lora_unet_mid_block_resnets_1_norm1.w_norm
lora key not loaded lora_unet_mid_block_resnets_1_norm2.b_norm
lora key not loaded lora_unet_mid_block_resnets_1_norm2.w_norm
lora key not loaded lora_unet_up_blocks_0_resnets_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_0_resnets_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_0_resnets_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_0_resnets_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_0_resnets_1_norm1.b_norm
lora key not loaded lora_unet_up_blocks_0_resnets_1_norm1.w_norm
lora key not loaded lora_unet_up_blocks_0_resnets_1_norm2.b_norm
lora key not loaded lora_unet_up_blocks_0_resnets_1_norm2.w_norm
lora key not loaded lora_unet_up_blocks_0_resnets_2_norm1.b_norm
lora key not loaded lora_unet_up_blocks_0_resnets_2_norm1.w_norm
lora key not loaded lora_unet_up_blocks_0_resnets_2_norm2.b_norm
lora key not loaded lora_unet_up_blocks_0_resnets_2_norm2.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_0_norm.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_0_norm.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_1_norm.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_1_norm.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_2_norm.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_2_norm.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_up_blocks_1_resnets_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_1_resnets_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_1_resnets_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_1_resnets_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_1_resnets_1_norm1.b_norm
lora key not loaded lora_unet_up_blocks_1_resnets_1_norm1.w_norm
lora key not loaded lora_unet_up_blocks_1_resnets_1_norm2.b_norm
lora key not loaded lora_unet_up_blocks_1_resnets_1_norm2.w_norm
lora key not loaded lora_unet_up_blocks_1_resnets_2_norm1.b_norm
lora key not loaded lora_unet_up_blocks_1_resnets_2_norm1.w_norm
lora key not loaded lora_unet_up_blocks_1_resnets_2_norm2.b_norm
lora key not loaded lora_unet_up_blocks_1_resnets_2_norm2.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_0_norm.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_0_norm.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_1_norm.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_1_norm.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_2_norm.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_2_norm.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_up_blocks_2_resnets_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_2_resnets_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_2_resnets_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_2_resnets_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_2_resnets_1_norm1.b_norm
lora key not loaded lora_unet_up_blocks_2_resnets_1_norm1.w_norm
lora key not loaded lora_unet_up_blocks_2_resnets_1_norm2.b_norm
lora key not loaded lora_unet_up_blocks_2_resnets_1_norm2.w_norm
lora key not loaded lora_unet_up_blocks_2_resnets_2_norm1.b_norm
lora key not loaded lora_unet_up_blocks_2_resnets_2_norm1.w_norm
lora key not loaded lora_unet_up_blocks_2_resnets_2_norm2.b_norm
lora key not loaded lora_unet_up_blocks_2_resnets_2_norm2.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_0_norm.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_0_norm.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_1_norm.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_1_norm.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_2_norm.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_2_norm.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_norm3.b_norm
lora key not loaded lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_norm3.w_norm
lora key not loaded lora_unet_up_blocks_3_resnets_0_norm1.b_norm
lora key not loaded lora_unet_up_blocks_3_resnets_0_norm1.w_norm
lora key not loaded lora_unet_up_blocks_3_resnets_0_norm2.b_norm
lora key not loaded lora_unet_up_blocks_3_resnets_0_norm2.w_norm
lora key not loaded lora_unet_up_blocks_3_resnets_1_norm1.b_norm
lora key not loaded lora_unet_up_blocks_3_resnets_1_norm1.w_norm
lora key not loaded lora_unet_up_blocks_3_resnets_1_norm2.b_norm
lora key not loaded lora_unet_up_blocks_3_resnets_1_norm2.w_norm
lora key not loaded lora_unet_up_blocks_3_resnets_2_norm1.b_norm
lora key not loaded lora_unet_up_blocks_3_resnets_2_norm1.w_norm
lora key not loaded lora_unet_up_blocks_3_resnets_2_norm2.b_norm
lora key not loaded lora_unet_up_blocks_3_resnets_2_norm2.w_norm`

**Comment by comfyanonymous** [comment]
Do you have a lora file in this format?

**Comment by ckmlai** [comment]
Yes, I've got a few
[loras.zip](https://github.com/comfyanonymous/ComfyUI/files/12453621/loras.zip)

**Comment by ckmlai** [comment]
It's working perfectly right now. Thank you!
