### ISSUE TITLE
Can it run on M1？

### ISSUE THREAD

**Issue by guangxinzhao** [comfyanonymous/ComfyUI#135]
Can it run on M1？

**Comment by thinkyhead** [comment]
Yes, but only with CPU-based generation, which takes over 3.1 seconds per generation-step on an M1 Ultra. To prepare the installation, make a local copy of ComfyUI, set up Miniconda, open a Terminal in the ComfyUI folder, and then:

```sh
conda create -n comfyui python=3.10 -y
conda activate comfyui
pip install -r requirements.txt
```

Run the web interface with:
```sh
python ./main.py --cpu
```

And open the browser to http://127.0.0.1:8188

**Comment by GaidamakUA** [comment]
Hope this pull request gets accepted soon. https://github.com/comfyanonymous/ComfyUI/pull/244
But for now you can use fork from this PR. It's ~3 times faster than CPU.

**Comment by enzyme69** [comment]
@GaidamakUA how to test / check if this additional magic repo to make the MPS faster actually works?

**Comment by GaidamakUA** [comment]
@GaidamakUA Forget it. My PR was accepted. ComfyUI is now GPU accelerated on Macs.

**Comment by GaidamakUA** [comment]
@comfyanonymous Please, close the issue. It is solved.
