### ISSUE TITLE
Controlnet Inpaint similar to A1111 controlnet inpaint "resize + fill"

### ISSUE THREAD

**Issue by rook2pawn** [comfyanonymous/ComfyUI#1350]
I am generating a 512x512 and then wanting to extend the left and right edges and wanted to acheive this with controlnet Inpaint.

Saw something about controlnet preprocessors working but haven't seen more documentation on this, specifically around *resize and fill*, as everything relating to controlnet was its edge detection or pose usage.  This is the workflow i am working on

[workflow](https://i.imgur.com/KYo34gx.png) and wasn't getting success yet and wondering if there was more direction provided by the author to help. 

Appreciate anyone's insights here

**Comment by ltdrdata** [comment]
Are you trying to perform outpainting?

**Comment by rook2pawn** [comment]
Yes I am trying to out paint the edges where I added padding, using
controlnet inpaint.

**Comment by rook2pawn** [comment]
I have a generated a similar approach  with setLatentNoiseMask after padding image for outpainting
uploaded the file which should contain the graph if github preserves the metadata

![ComfyUI_00179_](https://github.com/comfyanonymous/ComfyUI/assets/176303/90df2dfa-6f16-4321-af84-5d7ce233276d)


![Screenshot_7](https://github.com/comfyanonymous/ComfyUI/assets/176303/12544224-c794-455f-803a-dd4c2ff1349f)

Issue can be closed now unless anyone wants to add anything further

**Comment by bluelocate** [comment]
I tried above but it's not working well when using realistic photos from 'Load Image'

**Comment by alexopus** [comment]
> Are you trying to perform outpainting? [outpaint.json.txt](https://github.com/comfyanonymous/ComfyUI/files/12449808/outpaint.json.txt)
> 
> Then, this is the workflow I've been experimenting with in relation to outpainting. It could be a valuable reference.

Thank you @ltdrdata, this is looking very promising! However when I run the workflow, it gives me an error:

```
Error occurred when executing ImpactKSamplerBasicPipe:

'NoneType' object is not subscriptable

  File "/home/user/comfy/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comfy/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comfy/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comfy/custom_nodes/ComfyUI-Impact-Pack/modules/impact/special_samplers.py", line 507, in sample
    latent = nodes.KSampler().sample(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comfy/nodes.py", line 1237, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comfy/nodes.py", line 1194, in common_ksampler
    latent_image = latent["samples"]
                   ~~~~~~^^^^^^^^^^^
```

One thing I had to change is to switch from IPAdapter to IPAdapterPlus:

![image](https://github.com/comfyanonymous/ComfyUI/assets/25933468/f6105fa5-c204-4722-a1cf-2812d5034726)

Not sure if that could be the reason for the error?

Maybe something is out of date?

**Comment by alexopus** [comment]
nvm, I figured it out. It was the switch nodes not playing well with reroutes again.
