### ISSUE TITLE
APPLE M1  error: input types 'tensor<1x8320x1xf16>' and 'tensor<1xf32>' are not broadcast compatible

### ISSUE THREAD

**Issue by suxiaohei2000** [comfyanonymous/ComfyUI#1352]
got prompt
Global Step: 440000
model_type EPS
adm 0
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
missing {'cond_stage_model.text_projection', 'cond_stage_model.logit_scale'}
left over keys: dict_keys(['betas', 'alphas_cumprod', 'alphas_cumprod_prev', 'sqrt_alphas_cumprod', 'sqrt_one_minus_alphas_cumprod', 'log_one_minus_alphas_cumprod', 'sqrt_recip_alphas_cumprod', 'sqrt_recipm1_alphas_cumprod', 'posterior_variance', 'posterior_log_variance_clipped', 'posterior_mean_coef1', 'posterior_mean_coef2', 'model_ema.decay', 'model_ema.num_updates', 'cond_stage_model.transformer.text_model.embeddings.position_ids'])
loading new
loading new
  0%|                                                    | 0/20 [00:00<?, ?it/s]loc("varianceEps"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/d9889869-120b-11ee-b796-7a03568b17ac/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<1x8320x1xf16>' and 'tensor<1xf32>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
zsh: abort      python main.py --force-fp16
(comfyUI) su@MacBook-Max ComfyUI % /Users/su/miniconda3/envs/comfyUI/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by briankariuki** [comment]
Gettting the same error. How did you fix it?

**Comment by kingcozz** [comment]
same error: anyway to fix this? 

`missing {'cond_stage_model.text_projection', 'cond_stage_model.logit_scale'}
left over keys: dict_keys(['cond_stage_model.transformer.text_model.embeddings.position_ids', 'model_ema.decay', 'model_ema.num_updates'])`

**Comment by kingcozz** [comment]
happens and fails at 10% everytime, 
![image](https://github.com/comfyanonymous/ComfyUI/assets/92553627/c6c2ef74-1b6d-48eb-b962-7bd33d4ae60f)
