### ISSUE TITLE
LoRA loading issues on Colab

### ISSUE THREAD

**Issue by loopeplz** [comfyanonymous/ComfyUI#1357]
In short my personal LoRA is working along with some the default ones from api page along with a ghibli one but I cannot get dreamshaper 8 or some others that I been trying to use. I'll run it with the matching base and I'll get something like this: 

lora key not loaded model.diffusion_model.time_embed.2.weight  

Along with these sometimes: 

NOT LOADED transformer.text_model.encoder.layers.11.self_attn.out_proj.weight
loading new
loading new
ERROR diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight shape '[640, 2048]' is invalid for input of size 491520

Please let me know what information I can provide to help. Using clean copy of updated comfyui via google colab. Workflow is identical to the one on the examples. All downloaded via api except personal ones.

**Comment by mcmonkey4eva** [comment]
Are you perhaps mixing SDXL and SDv1 model files? They're not intercompatible.
