### ISSUE TITLE
An error occurred while using two SD1.5 controlnet models as controls to generate images.

### ISSUE THREAD

**Issue by Mocha-s** [comfyanonymous/ComfyUI#1364]
After today's update, an error occurred when I used two SD1.5 controlnet models as controls to generate images. An error occurs even if no plug-in is loaded. SDXL does not. After I tried to go back to the older version, SD1.5 worked fine.
[comfyui.log](https://github.com/comfyanonymous/ComfyUI/files/12466815/comfyui.log)
![Snipaste_2023-08-30_00-09-11](https://github.com/comfyanonymous/ComfyUI/assets/20685520/497ecf83-6ea3-4b6f-bc87-3cc382ca379e)

**Comment by mcmonkey4eva** [comment]
This seems to relate to extensions (Impact Pack). Does it still occur on latest Comfy with all extensions updated?
