### ISSUE TITLE
LoRA Loading issue - both CPU and GPU 

### ISSUE THREAD

**Issue by ac-pill** [comfyanonymous/ComfyUI#1365]
Hi guys.

I'm trying to run a simple workflow with 1 Lora loader, and I'm getting the same error, when I'm running Comfy on GPU or on CPU.

Please notice I'm running on a cloud server so maybe the script is not getting the correct device on the Lora Loader module?
Also, I update my local Comfy with the latest pull.

The error is causing the exception below:
`Error occurred when executing LoraLoader:

'CLIP' object has no attribute 'device'

File "/workspace/ComfyUI/execution.py", line 154, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/workspace/ComfyUI/execution.py", line 84, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/workspace/ComfyUI/execution.py", line 77, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/workspace/ComfyUI/nodes.py", line 557, in load_lora
model_lora, clip_lora = comfy.sd.load_lora_for_models(model, clip, lora, strength_model, strength_clip)
File "/workspace/ComfyUI/comfy/sd.py", line 62, in load_lora_for_models
new_clip = clip.clone()
File "/workspace/ComfyUI/comfy/sd.py", line 101, in clone
n.device = self.device`

Does anyone has any idea what could be?
I'll try to fix on a local fork and push it up here

**Comment by comfyanonymous** [comment]
Make sure you update, I don't see a self.device on line 101 in sd.py or anywhere in the clone function: https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/sd.py#L95

**Comment by ac-pill** [comment]
Thanks @comfyanonymous, I did another pull and seems to be fixed.
Also, notice in CPU mode, I needed to remove --use-pytorch-cross-attention, as the process was killed in linux without warning or log error.

Seems to be working fine now.
