### ISSUE TITLE
Running the Batch count for 20 Steps in API format

### ISSUE THREAD

**Issue by p0mad** [comfyanonymous/ComfyUI#1367]
Hi,
I have used the Basic API as described here https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py

and then tested with my workflow and its great. but when the input is a sequence and i need to read each image one by one, I need to keep the seed constant but the batch Count for queuing needs to be as large as my image directory. while for the basic example it only runs once and stop queuing for the following images!

Can you please give me some insights on how to do that?(or is there any other way)

Thanks

**Comment by signorinileandro** [comment]
Hi! Have you found a solution for this?
