### ISSUE TITLE
Seed is not saved as INT if used as input

### ISSUE THREAD

**Issue by Svyaga** [comfyanonymous/ComfyUI#1369]
If you convert seed from Widget to Input in KSampler then seed is not saved as INT in metadata.
Examples:
![SeedInput_00001_](https://github.com/comfyanonymous/ComfyUI/assets/143509676/797e6026-72c3-433b-ad19-949d0e5ee9af)
![SeedWidget_00001_](https://github.com/comfyanonymous/ComfyUI/assets/143509676/6e9499de-2183-41e2-8dd4-e480738667d3)
![1](https://github.com/comfyanonymous/ComfyUI/assets/143509676/3d4f1c0c-b222-450e-9631-48526d82ea45)
![2](https://github.com/comfyanonymous/ComfyUI/assets/143509676/607717f0-8268-4d9b-94c2-3faefdce3949)
You can see that SaveImage node took [35,0] as seed value as an Input from KSampler.

**Comment by wcurti** [comment]
The metadata isn't actually metadata in the way other frontends save metadata, it's a workflow json so you can load the workflow when you drag and drop the image on ComfyUI.

["35", 0] indicates that the "seed" value is inherited from node 35.
