### ISSUE TITLE
CheckpointLoader node is broken

### ISSUE THREAD

**Issue by ponchojohn1234** [comfyanonymous/ComfyUI#1370]
Commit https://github.com/comfyanonymous/ComfyUI/commit/15adc3699f74e0f3fcd3c29e62f8256825098e88 broke the Load Checkpoint (with Config) node

![qweasd](https://github.com/comfyanonymous/ComfyUI/assets/59420956/cb1dad43-8ba5-44ec-8d80-1717f2e2bd29)

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/fe4c07400c792ff8c5247cc4697235e33d96fcc9

Should be fixed now.
