### ISSUE TITLE
How to have consistent text when using choice { a |  b |  c } 

### ISSUE THREAD

**Issue by rook2pawn** [comfyanonymous/ComfyUI#1372]
When a prompt is given a choice {a | b | c} and that prompt is reused somewhere else in the graph, is it possible to "fix" so that its only evaluated only once? 

Currently Im seeing that everytime a prompt is being referenced, the choice is re-evaluated. Is there a technique around this?

**Comment by ntdviet** [comment]
CLIP it, using the CLIPTextEncode or something similar. Clipped prompts are then consistent everywhere you use it.

**Comment by rook2pawn** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/176303/c4e6388c-d85e-49bf-aad0-6f0228427888)
Yes, I was able to use the Clip Text Encode widget (right clicking on the widget and selecting convert text to input)

the other modules that came in very handy was the WAS custom nodes text concatenate and text multiline
![image](https://github.com/comfyanonymous/ComfyUI/assets/176303/0748aaf1-72c5-454b-93e3-824311493d4f)

I confirmed this in fact, locks in the random choice throughout the lifecycle of the graph!

**Comment by WASasquatch** [comment]
WAS-NS uses <a|b> which is not only seedable but won't get buggy cause it isn't JS for no reason other then think it's slick. Lol 😂

**Comment by Torcelllo** [comment]
How do you get a visual on the concatenated text? And then save that?
