### ISSUE TITLE
Applied workaround for CuDNN issue

### ISSUE THREAD

**Issue by visjble** [comfyanonymous/ComfyUI#1377]
Heu, I just pull todays' git and now getting this warning:
```

/home/me/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py:459: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride
```
It did load in lowvram mode and I was able to generate images. Is there anything I should do on my machine to improve/avoid this warning? thanks

**Comment by comfyanonymous** [comment]
That's fine, this warning can be ignored.

**Comment by visjble** [comment]
If you could pls demystify for me, does the quantity of vram have an impact on the type of image generated, if the parameters are exactly the same? thank you

**Comment by comfyanonymous** [comment]
In ComfyUI if you don't have enough vram it's just going to be slower, it should not affect the images being generated.

Different GPUs can give slightly different images because some operations are not 100% deterministic but the difference should be small.

**Comment by visjble** [comment]
THank you!
