### ISSUE TITLE
Can img2img set the size directly without using upscale?

### ISSUE THREAD

**Issue by py0712** [comfyanonymous/ComfyUI#1380]
Can img2img inside comfyui set the size directly without upscale? Because vae encode connected to the latent, can not put Empty Latent Image can not set the size, there is a way to img2img directly set their own size to generate images, rather than using the upscale, like webui a1111 in the img2img can directly set the size!

**Comment by ltdrdata** [comment]
> Can img2img inside comfyui set the size directly without upscale? Because vae encode connected to the latent, can not put Empty Latent Image can not set the size, there is a way to img2img directly set their own size to generate images, rather than using the upscale, like webui a1111 in the img2img can directly set the size!

When comparing with A1111, it's important to note that A1111 conceals internal operations. If you set the size in img2img to make it different from the input image, it doesn't mean you're skipping the upscale; rather, it implies that the upscale is being performed internally.

**Comment by py0712** [comment]
I use img2img in a1111 to set the size directly to zoom in as well, because changing the size directly to zoom in a1111 is better than even using the zoom tool. How do I use the node connection if I want to replicate the hide operation in a1111? Forgive me my English is not very good, I hope you can read my question, thanks!
