### ISSUE TITLE
Loading aborted due to error reloading workflow data

### ISSUE THREAD

**Issue by YuQiQAQ** [comfyanonymous/ComfyUI#1381]
TypeError: Cannot read properties of undefined (reading 'constructor')
TypeError: Cannot read properties of undefined (reading 'constructor')
    at RerouteNode.onConnectionsChange (http://127.0.0.1:8188/extensions/core/rerouteNode.js:89:27)
    at LGraphNode.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2504:11)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2240:26)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1230:15)
    at reader.onload (http://127.0.0.1:8188/scripts/app.js:1538:10)
This may be due to the following script:
/extensions/core/rerouteNode.js
![image](https://github.com/comfyanonymous/ComfyUI/assets/102429252/49a64bff-654a-400f-b3aa-de69b8c644e9)

**Comment by wangdong2023** [comment]
I got something similar, ` Cannot read properties of undefined (reading 'widgets')` when I am trying to delete a particular mtb node. Error from `comfy_shared.js`

**Comment by mcmonkey4eva** [comment]
Is this still an issue on the latest version of Comfy?

**Comment by le-khang** [comment]
How do you guys fix this? I got similar error but for 'length'

![2023-10-23 11_00_09-ComfyUI](https://github.com/comfyanonymous/ComfyUI/assets/35536989/427a9db5-8db7-4a14-abd5-4d42631bd6c6)

**Comment by ltdrdata** [comment]
> How do you guys fix this? I got similar error but for 'length'
> 
> ![2023-10-23 11_00_09-ComfyUI](https://user-images.githubusercontent.com/35536989/277229034-427a9db5-8db7-4a14-abd5-4d42631bd6c6.png)

Disable the `comfyui-custom-scripts` of pythongosssss and `rgthree`, and try again.

**Comment by le-khang** [comment]
> Disable the `comfyui-custom-scripts` of pythongosssss and `rgthree`, and try again.

I deleted each node until the workflow works and found the problem.

![2023-10-23 12_42_21-ComfyUI](https://github.com/comfyanonymous/ComfyUI/assets/35536989/7a7a574d-0c11-434f-96d4-cb7c3ad4c208)

- I have multiple Lora Loader Block Weight nodes of Inspire Pack
- The lora name widget is converted to input and is connected to Primitive Node (so I can let it choose Lora randomly)
- When I first open the workflow, some Primitive Nodes don't show any Lora, somes show Loras normally (attached image)
- So I disconnect the Primitive Nodes and connect again and it works.
- I update ComfyUI & all nodes to the lastest version and the workflow is working fine.

Also I use character U,U,U,U,U,U... for random block weight vector, in [the ](https://github.com/hako-mikan/sd-webui-lora-block-weight) Hako Mikan said that it will be from -1.5 to 1.5 but when I check it also be 2.97, -1.891, etc. Does it have a limit?
Thank you very much.

**Comment by rdcoder33** [comment]
still getting the same error. i don't have any nodes installed

**Comment by miurgh** [comment]
same

**Comment by ltdrdata** [comment]
> still getting the same error. i don't have any nodes installed

This kind of issue can occur when a broken workflow remains in the browser cache.
It may be necessary to clear the browser cache.

**Comment by ibadmore** [comment]
same, deleted the browser cache as well and still getting the issue.

**Comment by ibadmore** [comment]
This is the workflow I am loading: https://github.com/MrForExample/ComfyUI-3D-Pack/blob/main/_Example_Workflows/CharacterGen/CharacterGen_to_Unique3D.json

**Comment by miurgh** [comment]
Deleting the browser cache does not work.
Does not work in another browser.
Does not work on another PC.
Does not work on a different operating system.

**Comment by ibadmore** [comment]
I was able to fix by reverting to an older build of mine but now can't install newer nodes.

**Comment by christian-byrne** [comment]
Workflows are stored in localStorage which won't normally be cleared when clearing cache/cookies unless using specific settings. Look up how to clear localStorage for your specific browser. on Chrome you can navigate to:

```
chrome://settings/content/siteDetails?site=http%3A%2F%2Flocalhost%3A8188%2F
```

Then click `Delete data`

**Comment by kanarch66** [comment]
The latest comfyui update has conflict with video helper suit.  Uninstall this custom node to remove the error.
The question. Which custom node should replace it? any suggestion?

**Comment by kanarch66** [comment]
a [fix](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/issues/388) here

**Comment by RichardGoldbergSchool** [comment]
What fixed it for me: deleting all the pycache folders in my comfy folder.
