### ISSUE TITLE
Last commit broke ControlNetLoader

### ISSUE THREAD

**Issue by lllleow** [comfyanonymous/ComfyUI#1387]
I updated to the last commit in the master branch and started getting this error when trying to use ControlNet:

`TypeError: cat() received an invalid combination of arguments - got (Tensor, int), but expected one of:
 * (tuple of Tensors tensors, int dim, *, Tensor out)
 * (tuple of Tensors tensors, name dim, *, Tensor out)`

I rolled back to 1c794a21613d2d99f1cac13aee3c8e6fee16def3 and the error stopped happening.
If anyone get this error, rollback your ComfyUI and it will start working again.

**Comment by comfyanonymous** [comment]
Should be fixed now.
