### ISSUE TITLE
ComfyUI generation stops after 1 or 2 prompts

### ISSUE THREAD

**Issue by sopsss** [comfyanonymous/ComfyUI#1396]
This problem occurs on both batch queue and single prompt execution, comfyUI somehow stopped working after 1 or 2 generations. Does this have to do with my GPU or some settings within comfyUI? No error messages were prompt, just simply got prompt then prompt executed

Specs:Intel i5 9300H

GTX1660TI Mobile 6GB VRAM, Driver Version 536.67

32GB DDR4 Ram

Kingston SA2000 M.2 SSD

![image](https://github.com/comfyanonymous/ComfyUI/assets/68120748/1f51c167-da87-497a-8cbc-785be55d0f21)

Another place I've asked - https://www.reddit.com/r/comfyui/comments/167vjp1/comfyui_stopped_rendering_after_some_time/

**Comment by comfyanonymous** [comment]
Nodes only get executed again if them or their parents change so you need to change the seed or the prompt if you want it to generate again.

**Comment by sopsss** [comment]
> 

The base images i've used are frames extracted from a video then feeding them in batches without changing the prompt and the seed. Would this be the issue?

The attachment below is the workflow
![dance_00001_](https://github.com/comfyanonymous/ComfyUI/assets/68120748/9121cb95-e94c-49ed-a040-00f4d6521a8d)

**Comment by sopsss** [comment]
@comfyanonymous Ah I think i found the problem, the batch loader wasn't incretementing the images after each loop. Thanks for your help!
