### ISSUE TITLE
Workflows Fail to Run when Queue Prompt Selected

### ISSUE THREAD

**Issue by WinstonWoof** [comfyanonymous/ComfyUI#1397]
JUst updated ComfyUI to "ComfyUI Revision: 1391 [36ea8784]"

Now  some of my workflows wont even start (Heavyweight,MiddleWeight,LightWeight,ChatGPT Demo)

There are no errors in the console they simply wont start running when Queue Prompt clicked

Revision, Revison+ & Revision+++ start & run fine

(each workflow (should be) embedded in relevant screenshot or see https://discord.com/channels/1002292111942635562/1089974139927920741/1147476447741607986)
![Winstons_Middleweight](https://github.com/comfyanonymous/ComfyUI/assets/128506111/25f05986-efa6-4e4c-82d9-5c2a8e5d1572)
![Winstons_ChatGPT_Demo](https://github.com/comfyanonymous/ComfyUI/assets/128506111/830690ee-1bdb-4012-ae92-774524ed0b7b)
![Winstons_Heavyweight](https://github.com/comfyanonymous/ComfyUI/assets/128506111/100b458e-d976-418f-b7ea-55b5b9ab4cb4)
![Winstons_Lightweight](https://github.com/comfyanonymous/ComfyUI/assets/128506111/b5d4fd03-5146-436a-a5a6-c68999361b96)
![Winstons_ReVision_Basic](https://github.com/comfyanonymous/ComfyUI/assets/128506111/f5142769-42b0-4470-a09c-a6af6b9ffceb)
![Winstons_ReVisionPlus](https://github.com/comfyanonymous/ComfyUI/assets/128506111/68541f79-57ef-42b5-8e4d-4514991d2802)
![Winstons_ReVisionPlusPlusPlus](https://github.com/comfyanonymous/ComfyUI/assets/128506111/11b99961-3723-475a-ba72-a6d86224ff3d)

**Comment by WinstonWoof** [comment]
FYI "Rolled back" using Windows Portable download to ComfyUI Revision: 1374 [fe4c0740] and issue not present

**Comment by WinstonWoof** [comment]
As discussed for reference

![image](https://github.com/comfyanonymous/ComfyUI/assets/128506111/05a1bb65-e2dc-4efe-99ff-7247211c8759)

**Comment by WinstonWoof** [comment]
ComfyUI Revision: 1394 [6962cb46]
Confirmed working correctly again now

Cheers

**Comment by WinstonWoof** [comment]
FYI  another one I've noticed since yesterdays conversation.

Using git checkout 0e3b64117218c50a554b492269f5f35779839695 this Tiny Terra Nodes Debug  works as expected ie prints to condole plus in its own window (1st Image)

Using anything newer (currently on ComfyUI Revision: 1397 [a74c5dbf]) the Node in the workflow no longer displays the debug info although still in console

![image](https://github.com/comfyanonymous/ComfyUI/assets/128506111/d4aacbb2-a7d8-4b70-a1e9-a45f320c399b)

![image](https://github.com/comfyanonymous/ComfyUI/assets/128506111/8c833437-02d4-48da-92f1-9fe8b182e8bc)

**Comment by mcmonkey4eva** [comment]
Closing as original issue is fixed and new issue relates to an extension
