### ISSUE TITLE
many ksampler of custom nodes broken

### ISSUE THREAD

**Issue by BoosterCore** [comfyanonymous/ComfyUI#1399]
after the recent update of ComfyUI,many ksampler of custom nodes broken, with such error: 'ModelPatcher' object is not iterable.Is there any good solution?

**Comment by BoosterCore** [comment]
Sorry, I found that this problem has nothing to do with the upgrade of ComfyUI, but a problem with a version of Efficiency Nodes two days ago, which caused many KSampler nodes in other custom nodes connected to it to have problems.
Now the updated version of Efficiency Nodes has solved this problem.

**Comment by mcmonkey4eva** [comment]
Please redirect this report to that extension's github page.
