### ISSUE TITLE
Can't use multiple text inputs

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#140]
If I set something up like:

```python
    @classmethod
    def INPUT_TYPES(s):
        return {
                    "required": {
                            "text": ("STRING", {"multiline": True}),
                            "key": ("STRING", {"multiline": False}),                            
                            "clip": ("CLIP",),
                    }
                }
```

Only one text area will show. I want to add a new text field to a search key, additionally I have a couple other nodes in the works that will require quite a few text inputs.

**Comment by WASasquatch** [comment]
I found that for some reason, non-multiline strings need to come before multiline strings, for some reason. 

```python
{
                    "required": {
                            "key": ("STRING", {"multiline": False}), 
                            "text": ("STRING", {"multiline": True}),
                            "clip": ("CLIP",),
                    }
                }
```

**Comment by comfyanonymous** [comment]
Those multiline inputs are something I added in a hackish way so the CLIPTextEncode would actually be usable. It can only be used as the last node input and you can't use two of them on the same node.

**Comment by WASasquatch** [comment]
Fair enough. Probably better the short fields come before the long bracket of text anyway from a UI standpoint.

**Comment by WASasquatch** [comment]
Is there any way to output text back to the node? Display what was parsed?

**Comment by comfyanonymous** [comment]
You can use multiple multiline text inputs on the same node now so this is fixed.

**Comment by WASasquatch** [comment]
Awesome. I'll close this.
