### ISSUE TITLE
Is it feasible to implement weights to the Conditioning (Concat)?

### ISSUE THREAD

**Issue by coreyryanhanson** [comfyanonymous/ComfyUI#1403]
I know a long standing quirk in user experience across all implementations of Stable Diffusion is that reducing attention weights for a token is not as effective as increasing them (ie 0 weight can still retain a strong influence from any given token)

At the moment, there isn't much documentation about the implication and limitations of concatenating CONDITIONING datatypes after the conversion. My low level understanding of those specific tensors is a bit incomplete. Is a concat of "a dog" and "walks in a park" expected to have slightly different behavior than "a dog walks in a park" since they were processed in isolation from each other? If so and the entanglement of neighboring tokens can be removed, would it be possible to weigh these conditioning data types after the fact within a concat node and have an alternative way of reducing their influence?

**Comment by miabrahams** [comment]
Concat is equivalent to the BREAK keyword in A1111. CLIP processing is done separately for each prompt, then they are combined together into a single tensor.

Concat:   [conditioning1, conditioning2]
Average: x*conditioning1 + (1-x)*conditioning2

If you wanted to down-weight one part of the conditioning data you could use ConditioningZeroOut and ConditioningAverage to blend it towards zero before concatenating.

**Comment by coreyryanhanson** [comment]
That is an interesting solution that works amazing! It's a shame something like that isn't more documented.

If you don't mind me asking, what is the effect of having multiple conditioning chunks in Stable Diffusion? Do each of these act as individual constraints to the denoising prediction with kind of an intersection logic applied to them. For instance "a dog" BREAK "in a car" would be analogous to "a dog" <and statement> "in a car".

If so, are there any drawbacks to chaining together many conditions like this (assuming all conditions share an area of overlap).

Also I was curious if you knew anything about the implications of concatenating a raw "ConditioningZeroOut" with a prompt. The image processes almost as expected considering only 1 prompt, but it varies under the same seed from what would be processed if there was no concatenation with the zeroed out tensor. What do the set of conditioning zeros do exactly?

**Comment by mcmonkey4eva** [comment]
A lot of questions like that come down to "well, it depends on the AI's mood", and the more practical example is best found by simply trying it and seeing what happens.

Concatenating zeroes would be... a rather odd thing to do. Zeroes are relatively similar (though not the same!) as an empty prompt - you can broadly expect SD to favor nonsensical simple patterns when not given properly inputs, so when using concat you'll be biasing the generation towards that type of result.

**Comment by coreyryanhanson** [comment]
@mcmonkey4eva It is an odd thing to do. And there's no practical reason for concatenating zeros other than maybe a shortcut to in the suggested blend setup to avoid having to disconnect and reconnect nodes. However, it serves as a useful A/B test to better understand what is happening with the nodes.

Thank you for the information about the distinction from an empty prompt. If I were to use an empty prompt as a baseline for concatenation, there is also a (now smaller) divergence in the end result under the same seed.

![ComfyUI_01004_](https://github.com/comfyanonymous/ComfyUI/assets/17171838/e336118e-7b79-43d4-aa4b-ca43e25e76f3)
_"a dog"_

![ComfyUI_01003_](https://github.com/comfyanonymous/ComfyUI/assets/17171838/b74a71fd-8795-4058-9dcc-7b5c7b43e692)
"a dog" concat ""

If I go further and compare a generation of a single prompt of a "a dog" to an empty prompt against the prompt repeatedly concatted to a sequence of empty prompts, there is a very slight divergence between the two.

![ComfyUI_01002_](https://github.com/comfyanonymous/ComfyUI/assets/17171838/71e4337b-81ca-499f-b730-3d1d91fb5a1c)
_"a dog" concat "" concat "" concat "" concat ""_

I realize that much of the results could be unexplainable as a black box within the tranformers themselves. But seeing that these are inputs (outputs of one model but manually extended before entering the next model), there should be a way to have a basic understanding for what is going on under the hood.

**Comment by coreyryanhanson** [comment]
I'm going to reopen this temporarily, as my original intent was to have some sort of discussion in place for something with very little documentation before closing. I haven't seen this discussed in detail anywhere else, and I suspect something useful could come out of it for other people who find this through search engine searches later.

**Comment by mcmonkey4eva** [comment]
The discussion tab is available for ongoing discussions: https://github.com/comfyanonymous/ComfyUI/discussions
This is an Issue, a section for posting if something is wrong with ComfyUI or marking down feature requests for it.

**Comment by coreyryanhanson** [comment]
I get that. I was hoping for everything to be all in one place, but I can start a thread and if any updates link them here. Thanks
