### ISSUE TITLE
83669 IOT instruction (core dumped) - Ubuntu / AMD

### ISSUE THREAD

**Issue by joetech** [comfyanonymous/ComfyUI#143]
I'm trying to run this for the first time and getting this error.

**_83669 IOT instruction (core dumped) python main.py_** (the full error is below)

I'm on Ubuntu with an AMD GPU and Python 3.10.8
The errors before the core dump happen when I run Stable Diffusion WebUI as well, but never impact using it.
I am starting this by first invoking the existing python environment used for Stable Diffusion WebUI

What can I do to fix this or further diagnose it?

> (venv) ➜  ComfyUI git:(master) python main.py 
> /opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
> /opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
> WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
>     PyTorch 1.13.1+cu117 with CUDA 1107 (you have 1.13.1+rocm5.1.1)
>     Python  3.10.10 (you have 3.10.8)
>   Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
>   Memory-efficient attention, SwiGLU, sparse and more won't be available.
>   Set XFORMERS_MORE_DETAILS=1 for more details
> Set vram state to: NORMAL VRAM
> 2023-03-18 00:41:09.055800: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2023-03-18 00:41:09.138636: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
> 2023-03-18 00:41:09.138654: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> free(): invalid pointer
> [1]    83607 IOT instruction (core dumped)  python main.py

**Comment by comfyanonymous** [comment]
```pip uninstall xformers```

Then upgrade to latest pytorch + rocm with:
```pip install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.4.2```

You should probably also to make sure:
```pip install -r requirements.txt```

**Comment by joetech** [comment]
Thanks for the fast reply.  I completed those steps and now it complains that:

> tensorflow 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.0 which is incompatible.

If I uninstall and reinstall protobuf==3.19.0, I then get:

> open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 3.19.0 which is incompatible.

Either way, the UI loads, but if I try to run the default workflow with the Illuminati Diffusion model (the only one I copied over so far), it queues and starts and then crashes with the following:

> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188
> got prompt
> /home/joe/projects/stable-diffusion-webui/venv/lib/python3.10/site-packages/safetensors/torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
>   with safe_open(filename, framework="pt", device=device) as f:
> /home/joe/projects/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
>   return self.fget.__get__(instance, owner)()
> /home/joe/projects/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
>   storage = cls(wrap_storage=untyped_storage)
> making attention of type 'vanilla' with 512 in_channels
> Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
> making attention of type 'vanilla' with 512 in_channels
> LatentDiffusion: Running in v-prediction mode
> DiffusionWrapper has 865.91 M params.
>   0%|                                                                                                                                                                              | 0/20 [00:00<?, ?it/s]MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' naive_conv.cpp: HIPRTC_ERROR_COMPILATION (6)
> MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: naive_conv.cpp
> MIOpen(HIP): Warning [BuildHip] /tmp/comgr-0efaaa/input/naive_conv.cpp:39:10: fatal error: 'limits' file not found
> #include <limits> // std::numeric_limits
>          ^~~~~~~~
> 1 error generated when compiling for gfx1030.
> terminate called after throwing an instance of 'miopen::Exception'
>   what():  /long_pathname_so_that_rpms_can_package_the_debug_info/data/driver/MLOpen/src/hipoc/hipoc_program.cpp:304: Code object build failed. Source: naive_conv.cpp
> [1]    86814 IOT instruction (core dumped)  HSA_OVERRIDE_GFX_VERSION=10.3.0 python main.py

**Comment by comfyanonymous** [comment]
What's your GPU?

**Comment by joetech** [comment]
AMD Radeon rx 6800

After trying to make this work, my Automatic 1111 web UI is failing the same way.  It'll open, but when I try to render, it crashes with the same MIOpen exception.

**Comment by comfyanonymous** [comment]
You don't need to use this on the 6800: HSA_OVERRIDE_GFX_VERSION=10.3.0

Try doing: sudo apt install g++

That might install the C++ headers and fix the error.

**Comment by joetech** [comment]
I figured, but used only to cover my bases.  `g++` was already the latest version, but I found [this issue](https://github.com/RadeonOpenCompute/ROCm/issues/1889) specific to the 6800 which led me to `sudo apt install libstdc++-12-dev` and that got both UIs working.  Thanks for all your help.
