### ISSUE TITLE
Loading models from non-comfyUI folder takes an extremely long time

### ISSUE THREAD

**Issue by lemonade10-code** [comfyanonymous/ComfyUI#1432]
Bug: The first time loading a model stored in automatic1111 webui folder using extra_model_paths.yaml takes an extremely long time (10 minutes or more for a xl model). Subsequent generations after loading the model is not impacted.

If the model is in the comfyUI folder however it loads much more rapidly (30 seconds).

Graphics Card: Nvidia 3060 12GB

**Comment by mcmonkey4eva** [comment]
That is quite likely related to your OS and Filesystem more than it is comfy?
Modern SSD design will typically cache recently accessed files in high-speed storage, and less-recent files in slow-speed storage

**Comment by lemonade10-code** [comment]
Closing the issue because the problem was something else and I'm an idiot. 😩
