### ISSUE TITLE
Question: ComfyUI API LORA

### ISSUE THREAD

**Issue by Niutonian** [comfyanonymous/ComfyUI#1435]
I have been using the basic example to build my comfyui app. 
I would like to know if it is possible to control a LORA directly from the script.
that's it,

Thanks

**Comment by pydn** [comment]
If you are deploying a separate app, this extension may be a good idea for you. https://github.com/pydn/ComfyUI-to-Python-Extension

It converts workflow_api.json files to Python code that can run your workflow without the ComfyUI server.

**Comment by Niutonian** [comment]
@wcurti I am using an flask app to generate images through my own interface, right now I have all the setting controllable, but I do not know how to insert Lora's into the Api to generate images with them

**Comment by Niutonian** [comment]
@pydn I will give it a try, thanks for sharing

**Comment by mcmonkey4eva** [comment]
In general you should learn how to use ComfyUI through the workflow interface before trying to muck with API/internals.
