### ISSUE TITLE
Crash on Sampler with AMD 6750XT

### ISSUE THREAD

**Issue by MaximeBrl** [comfyanonymous/ComfyUI#1444]
Do you have an idea why ComfyUI crash ? Is it a RAM problem or  GPU VRAM ?
I am on Linux with AMD 6750xt. I am trying to use SDXL.  T
Total VRAM 12272 MB, total RAM 15888 MB

I tried 2 different workflow.
Everything works but when I arrive at the end of this moment https://ibb.co/fHLQ4GD, my screen freezes and 5sc later, I have a killed on my console (https://ibb.co/J5n2nPh).
On the 2nd workflow, it freezes on KSampler and crashs few seconds later : https://ibb.co/QfDKTFd

I don't have more information in the log file.
I had just one error out of about 20 tests:  "Ran out of memory when regular VAE decoding, retrying with tiled VAE decoding"

Here are the Worflows : 

- https://civitai.com/models/118005/sdxl-workflow-templates-for-comfyui-with-controlnet
- https://civitai.com/models/119528/sdxl-comfyui-ultimate-workflow

**Comment by mcmonkey4eva** [comment]
Sudden `Killed` on Linux indicates a RAM overload.

- Try closing unrelated programs if you can
- Try the default workflow (none of the complex custom stuff) to see if you can at least run SDXL itself when not using the fancy things
