### ISSUE TITLE
Error in KSampler

### ISSUE THREAD

**Issue by SmoothBrainApe** [comfyanonymous/ComfyUI#1453]
It just appeared out of nowhere.

Error occurred when executing KSampler:

mat1 and mat2 shapes cannot be multiplied (308x2048 and 768x320)

It was working yesterday but this happened today. Any ideas?

**Comment by SmoothBrainApe** [comment]
Upon further investigation, it appears whenever I use any controlnet model starting in control_v11p_sd15. Is this a bug?

**Comment by ltdrdata** [comment]
> Upon further investigation, it appears whenever I use any controlnet model starting in control_v11p_sd15. Is this a bug?

Could you please check if the SDXL model has not been selected as a checkpoint?

**Comment by SmoothBrainApe** [comment]
> > Upon further investigation, it appears whenever I use any controlnet model starting in control_v11p_sd15. Is this a bug?
> 
> Could you please check if the SDXL model has not been selected as a checkpoint?

Oh I see so that's where it went wrong. I was using controlnet models for SD 1.5 and using SDXL checkpoint. My bad. Gonna leave this here in case someone encounters the same problem. Imma download those SDXL controlnet then. Thanks for the clue
