### ISSUE TITLE
⚠ No more free Colab for ComfyUI

### ISSUE THREAD

**Issue by x-legion** [comfyanonymous/ComfyUI#1460]
![image](https://github.com/comfyanonymous/ComfyUI/assets/97628039/a4b38215-c4c9-4cf1-b512-3cd9951a8383)

**Comment by comfyanonymous** [comment]
Yes, ComfyUI has become too popular.

**Comment by loboere** [comment]
any cure?

**Comment by x-legion** [comment]
> any cure?

DM me. I'll send you the cure. 🤑

**Comment by mcmonkey4eva** [comment]
Yeah Colab is banning any form of WebUI on their service now :(
