### ISSUE TITLE
[Feature Request] String Nodes to connect on any node values

### ISSUE THREAD

**Issue by SmoothBrainApe** [comfyanonymous/ComfyUI#1470]
Hi,

Thank you for bringing comfyUI to life! It is a magnificent piece of software! I prefer this any day than other SD webui. I just want to request a feature if that's ok?

In my workflow, there are multiple times that I resize the image to a certain resolution, and they all have to be the same. Can there be a way to have a 'string node' where I can put a value in there, then connect them as input to the upscale nodes so if I work on a different resolution image, I just simply change the 'string node' and it will change the value on all the upscale nodes? If you use the node system of blender 3d software, you would be able to visualize what I mean. Thank you! Keep up the good work!

**Comment by aegis72** [comment]
Why not just start with an Int? 
![image](https://github.com/comfyanonymous/ComfyUI/assets/118572301/1dc6e8e0-ebbc-43d0-ae3d-ea4e03acdb6a)

**Comment by SmoothBrainApe** [comment]
> Why not just start with an Int? ![image](https://user-images.githubusercontent.com/118572301/268037843-1dc6e8e0-ebbc-43d0-ae3d-ea4e03acdb6a.png)

I see what you mean. I found out something much easier. Using 'Primitive' from 'utils', right click on the 'width' or 'height' on upscalers and turn them to inputs, connect primitive and you will have the strong node! It's genius if you ask me but it is not obvious.

Anyway I found a solution to my problem. Closing this now.
