### ISSUE TITLE
Some backends have errored on the server. Check the server logs for details.

### ISSUE THREAD

**Issue by CyberWar8bit** [comfyanonymous/ComfyUI#1474]
I'm having an issue during last days. I found the message: "Some backends have errored on the server. Check the server logs for details." in the browser window. When I check the server log I found this:
![Sin título](https://github.com/comfyanonymous/ComfyUI/assets/144515191/c04d60fb-dc01-4802-a5f9-a9718b840bf5)

And in the code panel I found this error message:
08:27:16.127 [Init] Self-Start ComfyUI on port 7822 is loading...
08:27:16.234 [Info] Self-Start ComfyUI on port 7822 unexpectedly exited (if something failed, launch with `--loglevel debug` to see why!)
08:27:16.234 [Info] Self-Start ComfyUI on port 7822 had errors before shutdown:
ComfyUI error: Traceback (most recent call last):
ComfyUI error:   File "/content/drive/MyDrive/StableSwarmUI/dlbackend/ComfyUI/main.py", line 66, in <module>
ComfyUI error:     import comfy.utils
ComfyUI error:   File "/content/drive/MyDrive/StableSwarmUI/dlbackend/ComfyUI/comfy/utils.py", line 1, in <module>
ComfyUI error:     import torch
ComfyUI error: ModuleNotFoundError: No module named 'torch'

I run StableSwarmIU from googlecolab. tryed to run in different browsers, To make a temporal or google drive install, and try to copy the ConfyUI directory directly from here to the drive folders, but I get no success to fix the problem.

Any help would be very welcomed.

**Comment by mcmonkey4eva** [comment]
Colab has recently banned webuis on their service :(

**Comment by peter65374** [comment]
so Colab version of all SD webui including ComfyUI won't work so far?...Even if colab pro?

**Comment by ltdrdata** [comment]
> so Colab version of all SD webui including ComfyUI won't work so far?...Even if colab pro?

randomly possible.
