### ISSUE TITLE
Loras not found, only LyCoris

### ISSUE THREAD

**Issue by david9039** [comfyanonymous/ComfyUI#1485]
When using a Lora loader (either ComfyUI nodes or extension nodes), only items in the Lycoris folder are shown.  Loras that are located in the /models/lora folder are not in the list to be used by Lora nodes.

If I copy the Lora files into the Lycoris folder, and refresh the webpage, they will show up in the Lora loader node.

**Comment by NeedsMoar** [comment]
It should be /models/loras

That might be what's causing it.   :D   Comfy doesn't have its own lycoris folder so I'm guessing you're sharing with another UI that named the folders differently?  If that's the case you could just add the /models/lora to the extra directories file to keep the other program from having issues.

**Comment by david9039** [comment]
It was a folder name error.  I had the folder named /model/loras, but the yaml file was referencing /model/lora.

Totally my error.  Resolved.
