### ISSUE TITLE
Strange log messages.

### ISSUE THREAD

**Issue by okolenmi** [comfyanonymous/ComfyUI#1486]
Everything works fine, but maybe there is some problem during processing image by default VAE Decode node.

A lot of strange log messages:
`You shouldn't move a model when it is dispatched on multiple devices.`

![изображение](https://github.com/comfyanonymous/ComfyUI/assets/55319814/fa705253-7463-4531-ba30-eb82f334d23e)

**Comment by LubuLubu2** [comment]
Yep, since last update i get this as well. it adds one line with each generation.

**Comment by comfyanonymous** [comment]
You can ignore this, it's just the accelerate library being annoying.

**Comment by DarkCoverUnleashed** [comment]
Yep I too started getting this message. And I really thought someone else was also getting the images I was generating on some other devices.

**Comment by aegis72** [comment]
Is there a way to suppress console warnings like these?

**Comment by comfyanonymous** [comment]
This message won't appear anymore since: https://github.com/comfyanonymous/ComfyUI/commit/36a7953142ccf3f9debf9305e3cbeb3bfe956ee3
