### ISSUE TITLE
[Feature request] --medvram support

### ISSUE THREAD

**Issue by throwaway-mezzo-mix** [comfyanonymous/ComfyUI#149]
For my GTX 960 4gb the speed boost (even if arguably not that large) provided by --medvram on other UI's (Like Auto1111's) makes generating quite a bit less cumbersome. 

It would be great if it was supported here.

**Comment by comfyanonymous** [comment]
By default the behaviour is similar to --medvram on the a1111 ui (unloading models from vram after they are used). --highvram is what you can use if you want them to stay on vram.

**Comment by throwaway-mezzo-mix** [comment]
I must have misunderstood what --medvram did, then. I was under the impression that it was also bit more VRAM hungry and slightly faster. Thank you for the clarification.

In that case this Issue is pointless, so I'm gonna close it. Feel free to reopen for whatever reason if you feel like it.
