### ISSUE TITLE
Preserve original photo when using 'Outpaint'

### ISSUE THREAD

**Issue by bluelocate** [comfyanonymous/ComfyUI#1494]
Hello I'm trying Outpaint in ComfyUI but it changes the original Image even if outpaint padding is not given.
How can I solve this issue? I think just passing outpainting, degrades photo quality(you can find it easily by comparing the person's face)

**Original**
![original](https://github.com/comfyanonymous/ComfyUI/assets/16236663/a3cb38c8-b640-4902-87f4-e3615f93b366)

**Result**(No Padding)
![result](https://github.com/comfyanonymous/ComfyUI/assets/16236663/7ca0e243-2d11-48f0-8d9a-cc6a8e694aa5)

<img width="1934" alt="screenshot" src="https://github.com/comfyanonymous/ComfyUI/assets/16236663/1ed1c8f4-09ec-4819-bd26-96d20077c8e5">

**Comment by ltdrdata** [comment]
It's a limitation of VAE.
Face portion is too small for VAE.

The only solution is compositing on pixel space after outpaint.

**Comment by comfyanonymous** [comment]
yes you can do an "image composite masked" from the output of the pad image node to the output of the VAE decode node.

**Comment by bluelocate** [comment]
Great! I tried "image composite masked" and it works! 
Thank you for advise
