### ISSUE TITLE
How can i upload image through API?

### ISSUE THREAD

**Issue by anomySz** [comfyanonymous/ComfyUI#1495]
Hi there,

I just wanna upload my local image file into server through api. is it possible?

When i was using ComfyUI, I could upload my local file using "Load Image" block.
But, I don't know how to upload the file via api

the example code is [this](https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py).

please let me know.

Thanks in advanced.

**Comment by miabrahams** [comment]
POST to /upload/image/.

There is an example at app/widgets.js at line 404. The definition is in server.py line 159.

**Comment by juancopi81** [comment]
I am trying to upload an image as a mask, I found @routes.post("/upload/mask") but I have not been able to do it correctly, uploading the images is working ok now, but I still unsure about how to use upload mask, I tried:

```
original_ref = {
                'filename': mask,
                'type': 'input',
                'subfolder': 'input'
            }
            
```

And then I got this response:

Response: {'name': 'mask (3).png', 'subfolder': '', 'type': 'input'}

Any example about how to use it?

Thanks

**Comment by mcmonkey4eva** [comment]
that response means your file was uploaded, and is named `mask (3).png` and you can now use it in a workflow by that name

**Comment by lianshuailong0715** [comment]
> POST to /upload/image/.
> 
> There is an example at app/widgets.js at line 404. The definition is in server.py line 159.

Can you provide a demo example for Image2Image pipeline or txt2img pipeline with Controlnet as https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py

**Comment by LianShuaiLong** [comment]
Can you provide a demo example for Image2Image pipeline or txt2img pipeline with Controlnet as https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py

**Comment by el0911** [comment]
> upload/image

line 404 am i the only one that finds that comedic?
