### ISSUE TITLE
[feature request] nested node

### ISSUE THREAD

**Issue by John-WL** [comfyanonymous/ComfyUI#150]
I wonder what would be needed to implement a nested/composite node that can run and edit a sub-workflow. 

What I mean is something like the grouped node in blender. 

It would be nice to be able to save them as custom nodes as well to load them later on. 

It would also be nice to allow nested nodes to be used in nested nodes themselves. 

I saw that there's a way to make your own custom js extension to run whatever code is needed in ComfyUI, I thought that maybe there was a way to implement the missing code to be able to use all the functionalities of litegraphjs to make this nested node thing possible. 

Any concrete ideas on how to achieve this?

**Comment by John-WL** [comment]
I thought about just calling the API, but that definitely won't work as you can only add a prompt to the queue. 

Furthermore, there's a lot of data forwarding that would be needed, and so I think making a node that calls the API for that is a bad idea.

**Comment by Kuinox** [comment]
I too would like nested nodes.

**Comment by ltdrdata** [comment]
> I too would like nested nodes.

There are 2 approaches are developing.


This is subgraph feature. This will be included built-in, eventually.

https://github.com/comfyanonymous/ComfyUI/pull/724


And this is a workflow component feature. This is an experimental project. Currently, you can use as an extensiom. But, I am not decided, yet.

https://github.com/ltdrdata/ComfyUI-Workflow-Component


Usability of each approaches are little bit different.

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/pull/1776
