### ISSUE TITLE
API images seem extremely similar when called back to back

### ISSUE THREAD

**Issue by MarkPopovich** [comfyanonymous/ComfyUI#1507]
Hi, 

I have noticed that when I call the API back-to-back with different text prompts, I'm getting very similar images. For example, if I prompt a women first and then a man, I will get women for both images (and vice versa). 

I'm using the following workflow with the two upscale nodes and the second image save turned off: https://civitai.com/models/138176/capybaras-sdxl-workflow-v13

Is there a way I can control the cache between prompts to prevent this? On the other hand, is it possible to save whatever information is causing this to happen so that I can load it in a controlled fashion later? For example, it actually seems useful if I want to generate the same character in different situations. 

Thanks

**Comment by wcurti** [comment]
Can you post both images? It would be easier to see what's going on by the embedded workflows.

**Comment by mcmonkey4eva** [comment]
If you're calling the API automatically, I strongly recommend providing unique generated IDs to the SaveImage node's prefix value, to guarantee the images don't get mixed. If that's not it, as said above please post the images and any other info

**Comment by Jingwen-genies** [comment]
Hey @mcmonkey4eva I got the same issue with websocket, is there any good suggestions for websocket node? I'm not sure if the websocket is has the prefix when it returns
