### ISSUE TITLE
MacOs. How to install in usr/local/

### ISSUE THREAD

**Issue by iplanwebsites** [comfyanonymous/ComfyUI#1509]
For context, I'd like to setup ComfyUI in a student computer lab.  

On macOs, by default, the install script installs comfy UI in the user home directory. 
What would be the best way to install everything in `usr/local/ `so the models and UI are accessible to all users of my computer?

**Comment by mcmonkey4eva** [comment]
Research `venv` or `conda`, both are options to constrain a python-based application to a single folder
