### ISSUE TITLE
VAE Inpainting resizes Image slightly

### ISSUE THREAD

**Issue by lord-lethris** [comfyanonymous/ComfyUI#1510]
I got a weird issue with the VAE Inpainting node, in respect that it seems to shrink or grow an image in weird and interesting ways.

If I leave the original image "as is" - VAE Inpainting will "sometimes" rescale the image inconsistently either UP or DOWN by a few pixels - by inconsistently, I mean it will either rescale width, hight or both by 2 - 5 pixels.

If I scale the image, VAE Inpainting will resize the shortest side by about 3 pixels every time.

I have attached the workflow for reference

**Case scenario of why this is an issue:** 

> If I sample an image based from a reference image, then try to overlay these images using blend node, the blend node will return an error as both images no longer match.

![image](https://github.com/comfyanonymous/ComfyUI/assets/1736720/82a4eeeb-6b48-4578-980b-5f4c5126f32f)

[VAE_Inpainting_issue_Test.zip](https://github.com/comfyanonymous/ComfyUI/files/12602159/VAE_Inpainting_issue_Test.zip)

**Comment by comfyanonymous** [comment]
That's because the VAE only works with images that are multiples of 8 pixels.

**Comment by lord-lethris** [comment]
Yea...  I worked out a tempry fix, whereby I pass the original image though an Encoder/Decoder routine.
