### ISSUE TITLE
Squeeze input for SaveImage

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#152]
I have a issue where if PIL RGB images are converted to numpy, and then tensor, that SaveImage cannot handle them. The reason is because it's not squeezing the input so it gets an extra shape, it seems.

https://github.com/comfyanonymous/ComfyUI/blob/master/nodes.py#L760

A fix, which still works for all other instances of Save Image that I've been using it for is 

```python
            i = 255. * image.cpu().numpy().squeeze()
```

Additionally, as a suggestion, it probably would be prudent to make "IMAGE" nodes actually be "TENSOR" nodes, and then have a Tensor to Numpy and Numpy to Tensor node where you then do any image operations on, to cut out all the back and forth conversion constantly.  Maybe different colors to differentiate Tensor based nodes and Image based nodes.

**Comment by comfyanonymous** [comment]
That's strange, in the line before this:
```for image in images:```

The "images" variable is supposed to be a shape like this: [1, 768, 768, 3]
Which means the "image" variable will have a shape like: [768, 768, 3]


So it should not need to be squeezed to work.

Can you print the shape of your images so I can see what's going on?

**Comment by WASasquatch** [comment]
So, it turns out the image processor I was using was returning a RGBA, but strangely, `.convert(RGB)` wasn't doing it. I was able to figure it out with numpy though.
