### ISSUE TITLE
Node Grip Snapping

### ISSUE THREAD

**Issue by Phinlorian** [comfyanonymous/ComfyUI#1537]
More of a quality of life thing. I have OCD, so I would highly appreciate it if you could add a feature that lets nodes snap to a grid so I don't spent 25 minutes of my time making sure that its all perfectly aligned 😭😭

**Comment by comfyanonymous** [comment]
Hold the shift key, adjust the grid size in the options.

**Comment by XPHUPZHJ** [comment]
But Groups don't snap to Grid

**Comment by PlayOnly** [comment]
I just reply to this thread for **future reference and google algorithm** Dont mind me.

Use [https://github.com/pythongosssss/ComfyUI-Custom-Scripts](url)

**Comment by 4lt3r3go** [comment]
holy sh1t i just found this now. thanks everyone. i suffered for two years without mind finding a solution. finally solved

> More of a quality of life thing. I have OCD, so I would highly appreciate it if you could add a feature that lets nodes snap to a grid so I don't spent 25 minutes of my time making sure that its all perfectly aligned 😭😭

**Comment by BarnMTB** [comment]
For people searching for the solution, it is now available in Settings:

1. Open `Settings` (Comfy button > `Settings`)
2. On the Settings sidebar, select `Lite Graph`
3. Under the `Canvas` section, turn on the `Always snap to grid` toggle

This way, you don't have to hold `Shift` key all the time.

**Comment by geroldmeisinger** [comment]
also see https://github.com/Comfy-Org/ComfyUI_frontend/issues/16389
