### ISSUE TITLE
How to enable seed randomization via API?

### ISSUE THREAD

**Issue by D1maD1m0nd** [comfyanonymous/ComfyUI#1540]
```
"3": {
        "inputs": {
            "seed": 3778562406736107,
            "steps": 30,
            "cfg": 8,
            "sampler_name": "euler",
            "scheduler": "normal",
            "denoise": 1,
            "model": [
                "4",
                0
            ],
            "positive": [
                "6",
                0
            ],
            "negative": [
                "7",
                0
            ],
            "latent_image": [
                "5",
                0
            ]
        },
        "class_type": "KSampler"
    },
```
    
Is there such a function in the configs or do I need to generate it myself?
`seed = torch.randint(0, 2 ** 63 - 1, []).item()`

**Comment by jn-jairo** [comment]
You need to generate it yourself, the backend doesn't generate seeds, the random seed we have in the web ui is generated by javascript and update the input for you. If you don't use the default frontend you need to randomize the seed yourself.

**Comment by oceanogeology** [comment]
@D1maD1m0nd how do you solve this problem, i encouter this problem also.
