### ISSUE TITLE
After actively closing the program, it does not work properly when it is started again

### ISSUE THREAD

**Issue by MycenaeanGreece** [comfyanonymous/ComfyUI#1548]
After I close the program manually, it doesn't work when I start it again. As soon as I click on the "Queue Prompt" button, it quits automatically. I have to restart the computer to get it working again.

Before that, there was a situation where there was not enough video memory, so I restarted the program.

I used these plugins:
comfy_controlnet_preprocessors
ComfyUI-Custom-Scripts

 A screenshot of the console at the time of the error is shown below:
![image](https://github.com/comfyanonymous/ComfyUI/assets/22862424/408c34ec-e0fb-49ff-b836-5b34ffd47727)

**Comment by mcmonkey4eva** [comment]
Rapid sudden exit usually indicates dangerously low system memory. Try restarting your PC, or running without custom nodes and load the smallest model you can. Also open task manager to the "Performance" tab and monitor your system and gpu memory
