### ISSUE TITLE
it always try to connect huggingface.co and cant work offline when using different nodes

### ISSUE THREAD

**Issue by whmc76** [comfyanonymous/ComfyUI#1549]
using [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux)
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /yzd-v/DWPose/resolve/main/yolox_l.onnx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002551770DC00>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/yzd-v/DWPose/resolve/main/yolox_l.onnx
WARNING:huggingface_hub.utils._http:'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /yzd-v/DWPose/resolve/main/yolox_l.onnx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002551770DC00>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/yzd-v/DWPose/resolve/main/yolox_l.onnx
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /yzd-v/DWPose/resolve/main/dw-ll_ucoco_384.onnx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002551770D450>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/yzd-v/DWPose/resolve/main/dw-ll_ucoco_384.onnx
WARNING:huggingface_hub.utils._http:'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /yzd-v/DWPose/resolve/main/dw-ll_ucoco_384.onnx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002551770D450>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/yzd-v/DWPose/resolve/main/dw-ll_ucoco_384.onnx
Processing interrupted

using impact pack Facedetailer
Loads SAM model: E:\ComfyUI_windows_portable\ComfyUI\models\sams\sam_vit_b_01ec64.pth (device:AUTO)
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /CIDAS/clipseg-rd64-refined/resolve/main/preprocessor_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000254C203ACB0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/CIDAS/clipseg-rd64-refined/resolve/main/preprocessor_config.json
WARNING:huggingface_hub.utils._http:'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /CIDAS/clipseg-rd64-refined/resolve/main/preprocessor_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000254C203ACB0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/CIDAS/clipseg-rd64-refined/resolve/main/preprocessor_config.json
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /CIDAS/clipseg-rd64-refined/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000254C2039510>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/CIDAS/clipseg-rd64-refined/resolve/main/tokenizer_config.json
WARNING:huggingface_hub.utils._http:'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /CIDAS/clipseg-rd64-refined/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000254C2039510>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/CIDAS/clipseg-rd64-refined/resolve/main/tokenizer_config.json
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /CIDAS/clipseg-rd64-refined/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000254C203A860>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/CIDAS/clipseg-rd64-refined/resolve/main/config.json
WARNING:huggingface_hub.utils._http:'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /CIDAS/clipseg-rd64-refined/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000254C203A860>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/CIDAS/clipseg-rd64-refined/resolve/main/config.json

**Comment by hylarucoder** [comment]
network issue with vpn?

**Comment by whmc76** [comment]
> network issue with vpn?

Of course, if you turn on the VPN, you can connect normally, but this should only be downloaded once. The problem now is that these errors will be repeated every time you use it if you don't turn on the vpn.

**Comment by mcmonkey4eva** [comment]
Those are issues with those custom nodes and should be reported on the githubs for those
