### ISSUE TITLE
[Question] Support for Multi-GPU Setups?

### ISSUE THREAD

**Issue by GaryCraft** [comfyanonymous/ComfyUI#155]
Trying to run on windows with 2 quadro cards, is it supported?
and how do I make the program use both, as when I tested it, it only uses one.

**Comment by zhuzhe1983** [comment]
I also have some RTX A2000 cards on same pc， and I want to use all of the cards for big workflow, especially for multi picture output。

And if comfyUI can use different cards for different queue task, It will be amazing.

**Comment by robinjhuang** [comment]
Consolidating multi-gpu support onto 
https://github.com/comfyanonymous/ComfyUI/issues/162
