### ISSUE TITLE
optional inputs

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#156]
Optional inputs don't seem to be working? 

I have me inputs like so

```python
        return {"required":
                    {"model": ("MODEL",),
                    "seed": ("INT", {"default": 0, "min": 0, "max": 0xffffffffffffffff}),
                    "steps": ("INT", {"default": 20, "min": 1, "max": 10000}),
                    "cfg": ("FLOAT", {"default": 8.0, "min": 0.0, "max": 100.0}),
                    "sampler_name": (comfy.samplers.KSampler.SAMPLERS, ),
                    "scheduler": (comfy.samplers.KSampler.SCHEDULERS, ),
                    "positive": ("CONDITIONING", ),
                    "negative": ("CONDITIONING", ),
                    "latent_image": ("LATENT", ),
                    "denoise": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 1.0, "step": 0.01}),
                    },
                "optional":
                    {"seed_override": ("SEED",),}
                }
```

but no seed_override input shows, can they only be required?

**Comment by comfyanonymous** [comment]
Yeah I have not had time to actually implement those.

**Comment by WASasquatch** [comment]
Ah drat. Running into so many road blocks.

**Comment by VeraLapsa** [comment]
I'm working on adding the optional inputs in to the code. 

I actually have the inputs working but I want to make sure that they are visually different so it'll be a bit longer before I can create a PR.

**Comment by WASasquatch** [comment]
> I'm working on adding the optional inputs in to the code.
> 
> I actually have the inputs working but I want to make sure that they are visually different so it'll be a bit longer before I can create a PR.

Is there a way to set the elements opacity? Perhaps an optional input is half opacity (dot and all)?

**Comment by comfyanonymous** [comment]
They should be working now.

**Comment by WASasquatch** [comment]
> They should be working now.

Awesome! Thanks so much @comfyanonymous
