### ISSUE TITLE
trying to reupload one of the examples of sd xl please help

### ISSUE THREAD

**Issue by greedykoylu** [comfyanonymous/ComfyUI#1560]
![grafik](https://github.com/comfyanonymous/ComfyUI/assets/145487690/994f2b14-08b5-4f21-9ea6-d1b0205ee86b)

**Comment by greedykoylu** [comment]
this happens when i drag the magical bottle as shown in examples into the ui and then change checkpoints and queue it up.

**Comment by comfyanonymous** [comment]
That means your SDXL checkpoint is corrupt.

**Comment by hylarucoder** [comment]
@greedykoylu try another sdxl model?
