### ISSUE TITLE
LoRA cast on GPU can fail on MPS

### ISSUE THREAD

**Issue by apurtell** [comfyanonymous/ComfyUI#1562]
Commit b92bf819  (Do lora cast on GPU instead of CPU for higher performance) causes execution failure on MacOS whenever a LoRA loader is part of the workflow and the LoRA is FP16. Verified by reverting this commit. 

    Traceback (most recent call last):
    [ ... uninteresting frames skipped ... ] 
    File "/ComfyUI/comfy/model_management.py", line 282, in model_load
      self.real_model = self.model.patch_model(device_to=patch_model_to) #TODO: do something with loras and offloading to CPU
    File "/ComfyUI/comfy/model_patcher.py", line 160, in patch_model
      out_weight = self.calculate_weight(self.patches[key], temp_weight, key).to(weight.dtype)
    File "/ComfyUI/comfy/model_patcher.py", line 190, in calculate_weight
      mat1 = v[0].to(weight.device).float()
    TypeError: BFloat16 is not supported on MPS

**Comment by lord-lethris** [comment]
I am getting this too - on Windows Running DirectML.
Updated and the errors started happening.  So I updated all the nodes and still getting error.

I also tried: 

- Several different LoRA loaders.
- Tested knows working Workflows.
- Tested both SD and SDXL

Still got errors.

Only happens when trying to Add a LoRA.

SDXL Error:

```
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
New prompt: Simple Background, Plain Background, Just a head shot of a boy, (((dark Brown Classic side sweep))), ((medium size black beard)), ((goatee beard)), ((Grey eyes)), wearing ((blue headphones)), black rimmed Rectangle Glasses, cashmere turtleneck, with a "furrowed brow" expression, focus on head, only a head
model_type EPS
adm 2816
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
loading new
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
loading new
[F D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_util.cc:118] Invalid or unsupported data type.
PS D:\apps\SD-WebUI\ComfyUI>
```

SD Error

```
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
New prompt: Simple Background, Plain Background, Just a head shot of a boy, (((dark Brown Classic side sweep))), ((medium size black beard)), ((goatee beard)), ((Grey eyes)), wearing ((blue headphones)), black rimmed Rectangle Glasses, baseball jersey, with a "sad smile" expression, focus on head, only a head
loading new
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
loading new
[F D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_util.cc:118] Invalid or unsupported data type.
PS D:\apps\SD-WebUI\ComfyUI>
```

**Comment by comfyanonymous** [comment]
Does this fix it? https://github.com/comfyanonymous/ComfyUI/commit/1cdfb3dba4e7af11e2e05dc6a6276ba84eb1adf2

**Comment by NeedsMoar** [comment]
That fixes it for me.  
Now to finish up some other things, power down this machine, install the RTX4090, and pretend like torch_directml never existed.  :D
