### ISSUE TITLE
Ksampler - primitive input bug

### ISSUE THREAD

**Issue by alenknight** [comfyanonymous/ComfyUI#1567]
when trying to add a ```primitive input``` to ```Ksampler``` or ```ksampler advanced``` - with ```control_after_input``` throws an error (trying to have a universal seed control in workflows)
also the primitive node never adopts the input.
see screenshot.
![image](https://github.com/comfyanonymous/ComfyUI/assets/22153900/fa763e32-9cf7-4728-b05a-2f219022c14d)

terminal doesn't show any errors

**Comment by ltdrdata** [comment]
`control_after_input` should not converted to input.

**Comment by VikingTechLLC** [comment]
If you convert "seed" to input first, it will automatically remove the "control_after_input" option.  So yeah, as ltdrdata mentions, don't connect to that.  Just convert seed first, then connect a primitive to "seed" input

**Comment by JFg111** [comment]
The problem with all the suggested solution is that they do not solve the initial problem.
I have the same problem as alenknight...
When using flux in some workflow, we have several Ksampler daisy chained together all with DIFFERENT seeds. The problem is that we would like to be able to tell them all globally in a single place that the seed they are using should ALL be either (fixed .or. increment .or. decrement .or. randomize) WHILE NOT changing the DIFFERENT VALUE of ALL THE DIFFERENT SEED in the different Ksampler. In other words, I would like to use only one control node to tell all the Ksampler to either fix, increment, decrement, or randomize their seeds. Right now the only way to control how the seed is to be handled is to go and change the control_after_generate in all the Ksampler manually which is a pain.
On the other hand, it seems that all these Ksampler nodes can express the "control_after_gnerate" as an input. UNFORTUNATELY, there seem to be no node able to control that "control_after_generate" input since it's none of the standard types of variables like INT.

**Comment by ltdrdata** [comment]
> The problem with all the suggested solution is that they do not solve the initial problem. I have the same problem as alenknight... When using flux in some workflow, we have several Ksampler daisy chained together all with DIFFERENT seeds. The problem is that we would like to be able to tell them all globally in a single place that the seed they are using should ALL be either (fixed .or. increment .or. decrement .or. randomize) WHILE NOT changing the DIFFERENT VALUE of ALL THE DIFFERENT SEED in the different Ksampler. In other words, I would like to use only one control node to tell all the Ksampler to either fix, increment, decrement, or randomize their seeds. Right now the only way to control how the seed is to be handled is to go and change the control_after_generate in all the Ksampler manually which is a pain. On the other hand, it seems that all these Ksampler nodes can express the "control_after_gnerate" as an input. UNFORTUNATELY, there seem to be no node able to control that "control_after_generate" input since it's none of the standard types of variables like INT.

The `Global Seed` in Inspire Pack provides a similar function. It forcibly sets all seeds based on the value of the Global Seed. (Except for cases converted to input)
It can have the same seed as the Global Seed, or seeds can be assigned sequentially starting from the Global Seed. Or it can assign completely random seeds.

Unless the `Global Seed` node is removed or muted, it is forcibly applied regardless of the `control_after(before)_generate` setting.

All nodes' seeds can have the same value as the Global Seed, or each node's seed value can be assigned sequentially starting from the Global Seed. Alternatively, completely random seeds can be assigned.

**Comment by JFg111** [comment]
Oh!... Now I know what is going on....
Weirdly the noise input for the core Ksampler is not the same as the noise input of the Inspire Ksampler and does NOT create the same node from a premitive. The only way to have an external seed for the Inspire Ksampler is to use the seed as input. However the primitive created from that is not affected by the Inspire Global Seed which is weird... The only way for an inpire Ksampler to have it's seed changed by the Inspire Global Seed is to leave it as a widget inside the Inspire Ksampler... In other words core Ksampler onto which we have connected an external seed node do work with the Inspire Global Seed but not the Inspire Ksampler...
Anyway....
It now works!!!!! 
Tanks!!! :-)

**Comment by ltdrdata** [comment]
> Oh!... Now I know what is going on....
> Weirdly the noise input for the core Ksampler is not the same as the noise input of the Inspire Ksampler and does NOT create the same node from a premitive. The only way to have an external seed for the Inspire Ksampler is to use the seed as input. However the primitive created from that is not affected by the Inspire Global Seed which is weird... The only way for an inpire Ksampler to have it's seed changed by the Inspire Global Seed is to leave it as a widget inside the Inspire Ksampler... In other words core Ksampler onto which we have connected an external seed node do work with the Inspire Global Seed but not the Inspire Ksampler...
> Anyway....
> It now works!!!!!
> Tanks!!! :-)

Yes, that is the intended behavior. This exception is made to ensure it is not affected by the Global Seed.
Connecting through a Primitive node explicitly signifies that you want separate control.
