### ISSUE TITLE
Video Custom Node

### ISSUE THREAD

**Issue by Nuked88** [comfyanonymous/ComfyUI#1573]
Hi!
I'm trying to create a custom node able to show a video in it, similar to what the Preview/Save Image or Load Image do with pictures, but i don't really understand how i can put a video element as widget, the best thing for me would be have the ability to insert custom html element in a node but i dont really understand if this is possible or not. Anyone have some idea?
I've already managed to make the upload of the video by dragging it on the node and get the url from comfyUI for showing it.

**Comment by ltdrdata** [comment]
How about take a look demo of Litegraph.

**Comment by Nuked88** [comment]
> How about take a look demo of Litegraph.

Yeah... but then I found this https://github.com/jagenjo/litegraph.js/issues/369#issue-1660231476 
And I got a little bit discouraged xD

**Comment by ltdrdata** [comment]
> > How about take a look demo of Litegraph.
> 
> Yeah... but then I found this https://github.com/jagenjo/litegraph.js/issues/369#issue-1660231476 
> And I got a little bit discouraged xD

But you can start from there :)
