### ISSUE TITLE
UI disappears. Nodes do not redraw after copy/paste nodes

### ISSUE THREAD

**Issue by txirrindulari** [comfyanonymous/ComfyUI#1582]
On Ubuntu 22.04, Firefox, Chromium and Opera, with any node workflow. When selecting one or more nodes and do copy/paste, all the UI disappears except the lines connections. Is there something I am missing on configuration?
![comfyui_error_pantalla](https://github.com/comfyanonymous/ComfyUI/assets/2056993/908c0266-04af-4fa8-afd8-9e3f1d1e64ae)

**Comment by ltdrdata** [comment]
press F12 and see console log.
What error messages are displayed on there?

**Comment by txirrindulari** [comment]
First after pasting:
Warning, nodes missing on pasting

Then when trying to move the new pasted node, there appears a bunch of errors, all related to " this.graph._nodes[i] is undefined
    processMouseMove http://0.0.0.0:8088/lib/litegraph.core.js:6398 "

Here an example of one of them:
Uncaught TypeError: this._nodes[i] is undefined
    serialize http://0.0.0.0:8088/lib/litegraph.core.js:2121
    get_new_candidate_state http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:227
    before http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:149
    onBeforeChange http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:120
    beforeChange http://0.0.0.0:8088/lib/litegraph.core.js:2024
    processMouseDown http://0.0.0.0:8088/lib/litegraph.core.js:6111
    processMouseDown http://0.0.0.0:8088/scripts/app.js:779
    pointerListenerAdd http://0.0.0.0:8088/lib/litegraph.core.js:14319
    bindEvents http://0.0.0.0:8088/lib/litegraph.core.js:5614
    setCanvas http://0.0.0.0:8088/lib/litegraph.core.js:5573
    LGraphCanvas http://0.0.0.0:8088/lib/litegraph.core.js:5329
    setup http://0.0.0.0:8088/scripts/app.js:1152
    async* http://0.0.0.0:8088/:14
litegraph.core.js:2121:13
    serialize http://0.0.0.0:8088/lib/litegraph.core.js:2121
    get_new_candidate_state http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:227
    before http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:149
    onBeforeChange http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:120
    beforeChange http://0.0.0.0:8088/lib/litegraph.core.js:2024
    processMouseDown http://0.0.0.0:8088/lib/litegraph.core.js:6111
    processMouseDown http://0.0.0.0:8088/scripts/app.js:779
    (Asíncrono: EventListener.handleEvent)
    pointerListenerAdd http://0.0.0.0:8088/lib/litegraph.core.js:14319
    bindEvents http://0.0.0.0:8088/lib/litegraph.core.js:5614
    setCanvas http://0.0.0.0:8088/lib/litegraph.core.js:5573
    LGraphCanvas http://0.0.0.0:8088/lib/litegraph.core.js:5329
    setup http://0.0.0.0:8088/scripts/app.js:1152
    InterpretGeneratorResume self-hosted:1469
    AsyncFunctionNext self-hosted:852
    (Asíncrono: async)
    <anonymous> http://0.0.0.0:8088/:14

**Comment by ltdrdata** [comment]
> First after pasting: Warning, nodes missing on pasting
> 
> Then when trying to move the new pasted node, there appears a bunch of errors, all related to " this.graph._nodes[i] is undefined processMouseMove http://0.0.0.0:8088/lib/litegraph.core.js:6398 "
> 
> Here an example of one of them: Uncaught TypeError: this._nodes[i] is undefined serialize http://0.0.0.0:8088/lib/litegraph.core.js:2121 get_new_candidate_state http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:227 before http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:149 onBeforeChange http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:120 beforeChange http://0.0.0.0:8088/lib/litegraph.core.js:2024 processMouseDown http://0.0.0.0:8088/lib/litegraph.core.js:6111 processMouseDown http://0.0.0.0:8088/scripts/app.js:779 pointerListenerAdd http://0.0.0.0:8088/lib/litegraph.core.js:14319 bindEvents http://0.0.0.0:8088/lib/litegraph.core.js:5614 setCanvas http://0.0.0.0:8088/lib/litegraph.core.js:5573 LGraphCanvas http://0.0.0.0:8088/lib/litegraph.core.js:5329 setup http://0.0.0.0:8088/scripts/app.js:1152 async* http://0.0.0.0:8088/:14 litegraph.core.js:2121:13 serialize http://0.0.0.0:8088/lib/litegraph.core.js:2121 get_new_candidate_state http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:227 before http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:149 onBeforeChange http://0.0.0.0:8088/extensions/ZZZ-Bmad-DirtyUndoRedo/WorkflowHistory.js:120 beforeChange http://0.0.0.0:8088/lib/litegraph.core.js:2024 processMouseDown http://0.0.0.0:8088/lib/litegraph.core.js:6111 processMouseDown http://0.0.0.0:8088/scripts/app.js:779 (Asíncrono: EventListener.handleEvent) pointerListenerAdd http://0.0.0.0:8088/lib/litegraph.core.js:14319 bindEvents http://0.0.0.0:8088/lib/litegraph.core.js:5614 setCanvas http://0.0.0.0:8088/lib/litegraph.core.js:5573 LGraphCanvas http://0.0.0.0:8088/lib/litegraph.core.js:5329 setup http://0.0.0.0:8088/scripts/app.js:1152 InterpretGeneratorResume self-hosted:1469 AsyncFunctionNext self-hosted:852 (Asíncrono: async) http://0.0.0.0:8088/:14

Disable Bmad-DirtyUndoRedo extension and retry.

**Comment by txirrindulari** [comment]
Great!!! It works now after removing Bmad-DirtyUndoRedo from extensions folder, although I also removed it from the custom node folder and I don't know if it was necessary
