### ISSUE TITLE
errors in portable comfy from today, no models show up in nodes despite having yaml file with paths that worked in previous builds from month ago also it totally ruined my workflows with basic pipe and more which dont work now

### ISSUE THREAD

**Issue by 2blackbar** [comfyanonymous/ComfyUI#1585]
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: flatbuffers, protobuf, opencv-contrib-python, absl-py, sounddevice, mediapipe
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'G:\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\cv2\\cv2.pyd'
Consider using the `--user` option or check the permissions.

Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facedetailer\__init__.py", line 9, in <module>
    from .FaceDetailer import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facedetailer\FaceDetailer.py", line 2, in <module>
    from mediapipe import solutions
ModuleNotFoundError: No module named 'mediapipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facedetailer\__init__.py", line 15, in <module>
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-r', requirements_path])
  File "subprocess.py", line 369, in check_call
subprocess.CalledProcessError: Command '['G:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', '-r', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\facedetailer\\requirements.txt']' returned non-zero exit status 1.

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facedetailer module for custom nodes: Command '['G:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', '-r', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\facedetailer\\requirements.txt']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ksampler\\__init__.py'

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ksampler module for custom nodes: [Errno 2] No such file or directory: 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ksampler\\__init__.py'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ksampler
   0.0 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes-master
   0.0 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\reference_only.py
   0.0 seconds (IMPORT FAILED): G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_preprocessors
   0.0 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.1 seconds (IMPORT FAILED): G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_pixelization
   0.1 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet-main
   0.1 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-main
   0.1 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.2 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   0.3 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.3 seconds (IMPORT FAILED): G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIT
   0.5 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.7 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
  10.5 seconds (IMPORT FAILED): G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facedetailer
  89.6 seconds (IMPORT FAILED): G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by mcmonkey4eva** [comment]
`ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\cv2.pyd'`

Seems like a filesystem/permission in Windows error related to your `G:` drive. You'll want to check that the drive is (A) working, (B) able to write new files into it, and (C) configured with your windows user as the owner of all files

If it's a portable drive, you might want to double check that it's formatted as NTFS - other windows-compatible filesystems like FAT32 tend to have conflicts with some software.
If it's a network drive... uh, don't boot software off a network drive lol.

**Comment by ltdrdata** [comment]
> `ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\cv2.pyd'`
> 
> Seems like a filesystem/permission in Windows error related to your `G:` drive. You'll want to check that the drive is (A) working, (B) able to write new files into it, and (C) configured with your windows user as the owner of all files
> 
> If it's a portable drive, you might want to double check that it's formatted as NTFS - other windows-compatible filesystems like FAT32 tend to have conflicts with some software. If it's a network drive... uh, don't boot software off a network drive lol.

Generally, permission errors with `cv2.pyd` occur when trying to install specific package dependencies while ComfyUI is running in a Windows environment.

**Comment by 2blackbar** [comment]
if i will run comfy as admin, will this get resolvd? ill try it
