### ISSUE TITLE
[feature request] Load the ComfyUI workflow itself as a node

### ISSUE THREAD

**Issue by nefudev** [comfyanonymous/ComfyUI#1586]
## Current Issues
- Workflow becomes complicated as the number of functions you want to use increases
- Reusability of created workflows is poor

## request
I want to treat all nodes in one workflow file as if they were one node, and place and edit them in different workflows.

## Details
- I want to handle ComfyUI workflows like components of react, vue, etc
- I want to place arbitrary interface nodes in the workflow to realize input/output for componentization.
- Interface nodes can be titled, and I want to display the title I set when I node a workflow
- I want to place componentized workflows as nodes in other workflows.
- I want to view and edit workflow nodes placed in other workflows by double-clicking them.
- I want to maintain the calling workflow and return to the calling workflow once editing is complete.

Attachment of reference image
![img_0001 5](https://github.com/comfyanonymous/ComfyUI/assets/132149510/a01706f6-3daf-47cd-8651-7fbea98978af)

## Isn't Nested enough?
What I want to do is close to what ComfyUI_NestedNodeBuilder can do, but with the following problems
- Currently somewhat unstable. Nesting may be canceled when an error occurs.
- Saved nest nodes may become unusable in the future.
- When modifying a nested node, it is expanded in the caller's workflow. If there are too many nodes, it becomes difficult to nest them again.

## Finally
- I am not yet familiar with ComfyUI in depth. If you have a feature similar to this request, I would appreciate it if you could let me know!

**Comment by mcmonkey4eva** [comment]
As you've already found, there's extensions and other feature requests for nesting workflows-within-workflows already.

**Comment by ltdrdata** [comment]
For the reference:

https://github.com/ssitu/ComfyUI_NestedNodeBuilder
https://github.com/ltdrdata/ComfyUI-Workflow-Component
