### ISSUE TITLE
UI element are not sharp, especially if you zoom out.

### ISSUE THREAD

**Issue by LuposX** [comfyanonymous/ComfyUI#161]
UI elements are blurry, like very low resolution, if you zoom out all details is lost. See picture.

![Screenshot from 2023-03-19 15-35-49](https://user-images.githubusercontent.com/36456825/226183071-ea8cb8b3-0b9e-482c-b2f1-ab6562303727.png)
![Screenshot from 2023-03-19 15-36-02](https://user-images.githubusercontent.com/36456825/226183096-ff14f454-000e-4d20-9b60-3179cd7acfad.png)

**Comment by WASasquatch** [comment]
Seems ComfyUI isn't using a high dpi canvas? which might explain this on certain resolution/devices.

**Comment by LuposX** [comment]
weird, I installed the GUI normally, idk what the issue would be.

**Comment by VOOM108** [comment]
Same here on Windows 10 4K w. 150% scaling 

The text in the textboxes is clear, all other text is blurry unless zoomed in as much as possible.

**Comment by LuposX** [comment]
Last github pull fixed it for me.

**Comment by gegear** [comment]
chrome, press F12

find this :

<canvas id="graph-canvas" tabindex="1" class=" lgraphcanvas" width="300" height="150" style="cursor: crosshair;"></canvas>

set width and height to fixed it.
