### ISSUE TITLE
VAEDecodeTiled causes visible seams in tiling

### ISSUE THREAD

**Issue by cathodeDreams** [comfyanonymous/ComfyUI#163]
Hello. When generating large images I use the VAEDecodeTiled node to avoid CUDA memory errors, but in doing so it seems to result in an image that does contain visible seams where the tiling occurred. Are there steps I cant take to mitigate this or will it be inherent to using the node?

Here are two images showing the effect. They are simple 2-pass latent upscales.

![ComfyUI_02583_](https://user-images.githubusercontent.com/127776538/226195936-af0a6d71-25de-4a53-8c0f-1903c96579f0.png)

![ComfyUI_02590_](https://user-images.githubusercontent.com/127776538/226195971-df3abafd-69f4-4fe4-aa4b-0ca1bec33350.png)

**Comment by comfyanonymous** [comment]
Yes, that's a known issue that I'm going to fix. This is the reason why it's in the _for_testing section.

**Comment by cathodeDreams** [comment]
No rush, much to do. Didn't know if that was what specifically kept it in testing.

**Comment by WASasquatch** [comment]
Sounds like it's using Go Big type method, which if so, can't really be overcome without doing stuff like img2img color fix, which also imo, produces bad quality.

**Comment by comfyanonymous** [comment]
If you update to the latest code it's still not perfect but it should be improved.

**Comment by cathodeDreams** [comment]
It is significantly better comfy thank you. As of currently my issue is concluded, though I'm sure the node can continue to be improved.

![ComfyUI_03850_](https://user-images.githubusercontent.com/127776538/226973300-d5bacf7b-3b1c-4158-9718-9c399f6a6b49.png)

**Comment by WASasquatch** [comment]
That looks spectacular and rather continuous even when raising the levels of the image
