### ISSUE TITLE
Comfyui paperspace notebook is broken

### ISSUE THREAD

**Issue by ca3gamedev** [comfyanonymous/ComfyUI#1630]
Hi, the comfyui paperspace notebook is simply old and has bugs.

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/blob/master/notebooks/comfyui_colab.ipynb

Have you tried this it should work on paperspace too.

**Comment by ca3gamedev** [comment]
> https://github.com/comfyanonymous/ComfyUI/blob/master/notebooks/comfyui_colab.ipynb
> 
> Have you tried this it should work on paperspace too.

I will leave my solution to others.

The checkpoint folder issue is solved with using the custom path folders yaml file and then set up a custom checkpoint folder path.
