### ISSUE TITLE
Correct seed is not saved to files made as a batch

### ISSUE THREAD

**Issue by no-connections** [comfyanonymous/ComfyUI#165]
Only the starting seed is saved to all files in a batch. 
Meaning if you load the image by drag and drop it will not produce the same image.

**Comment by WASasquatch** [comment]
A stable diffusion batch ***is done with one seed*** which produces all images, where internally it augments the seed. The script doesn't know what the seed is. It's the same as doing a batch size of 12 with batch count of 1 in WebUI, where you get 12 images with one generation internally, based on the one seed you set.

**Comment by no-connections** [comment]
Oooh batch count is what I want the which was semi hidden under extra options. Not the same thing as batch size. Should have read closer.
So the added question would be, how do I get the "internal" seed for each image with batch size so it can be reproduced? or is that just impossible.

**Comment by WASasquatch** [comment]
I wanna say they wouldn't just randomize it but probably increment it, sorta how I did for Easy Diffusion, cause one digit change is the same as any other random number. Have you tried just doing your original seed + 1 to see if it brings about the second image?

**Comment by no-connections** [comment]
Incrementing don't seem to be the same.
Maybe someone that knows the inner workings could comment on what happens and if there is a solution to make those images reproduce able at a later time as a single image without doing it as a batch again. A batch with the same seed comes out identical.
