### ISSUE TITLE
Torch Error, but I do follow the README's instructions

### ISSUE THREAD

**Issue by AZmisc** [comfyanonymous/ComfyUI#1655]
Here I start with no Torch, cache cleared. Then I install Torch using ComfyUI's readme command. Regretfully, I get an error:

![CUI Torch2](https://github.com/comfyanonymous/ComfyUI/assets/47092625/5193e71d-efc6-4287-a132-1ca536168c66)

**Comment by comfyanonymous** [comment]
pytorch ROCm is Linux only at the moment.
