### ISSUE TITLE
Error with values while trying to run

### ISSUE THREAD

**Issue by Logini228** [comfyanonymous/ComfyUI#166]
Hello, I already generated few images when I run by default nodes. Then I tried to run the example of area composition, and I got this error:
:\Users\User\Desktop\ComfyUI_windows_portable\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py:594: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")

I tried to run "update_comfyui_and_python_dependencies" but it did not help

**Comment by comfyanonymous** [comment]
that's a harmless warning you can ignore it.
