### ISSUE TITLE
LoadImage Filter List - too much clutter and no way to clean up cache

### ISSUE THREAD

**Issue by vararth** [comfyanonymous/ComfyUI#1660]
I use img2img a lot and usually just drag and drop images into the LoadImage node - the problem is even in new workflows, all the older used images show up in the filter list - is there any way to clear out the filter list from both older and newer workflows?

![image](https://github.com/comfyanonymous/ComfyUI/assets/66017370/945df40d-0703-45ab-b603-f6a60de5539e)

**Comment by ltdrdata** [comment]
You can delete obsolete files from `ComfyUI/input`

**Comment by vararth** [comment]
Thanks for helping a noob :)
