### ISSUE TITLE
Attempting to run: "Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?"

### ISSUE THREAD

**Issue by sunilw** [comfyanonymous/ComfyUI#167]
I managed to install and run comfyui on ubuntu, using python 3.9.12.

I didn't run it for a few days.

Coming back to it a few days later, attempting to run it fails with:

> UserWarning: Failed to load image Python extension: 'libc10_hip.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
>   warn(
> Set vram state to: NORMAL VRAM
> [1]    1129525 segmentation fault (core dumped)  python main.py
>

**Comment by comfyanonymous** [comment]
What's your gpu and how exactly did you try to install it?

If you are on AMD try: pip install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.4.2

**Comment by sunilw** [comment]
Hi. Sorry, I should have included those details.

I'm running an RTX 3090.

I installed simply following the installation directions in the readme.

Also, after this recent attempt to run comfy failed, I went to the project root and ran this command again:

> pip install -r requirements.txt

After running that command I get messages indicating that every requirement has been satisfied. Nothing new is installed.

**Comment by comfyanonymous** [comment]
oh I thought you were on AMD because libc10_hip.so looks like an AMD lib.

Try:
```
pip uninstall torch torchvision torchaudio

pip install torch==1.13.1 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117 xformers
```
