### ISSUE TITLE
ComfyUI Feeding data via Widget -> Input results in non-responsive UI

### ISSUE THREAD

**Issue by var1ableX** [comfyanonymous/ComfyUI#1671]
Having a significant issue with ComfyUI - if I convert a widget to an input and try to feed data from a separate node any attempt to generate images fails -- UI doesn't respond to "generate prompt" button. I did update ComfyUI Manager today as well as all other extensions. I tried loading fairly complex workflows that were working fine yesterday and they are all non-responsive.

I have attached a basic workflow to illustrate the problem -- attempt to feed text prompt from text node or width from Int literal both result in the issue. If I revert back from input to widget Generation starts working again.

Any suggestions to fix this appreciated -- seems like its just me as I'm sure others would have reported issues by now.

![comfyui_broken](https://github.com/comfyanonymous/ComfyUI/assets/839040/1f545461-00e3-43a2-878e-a08df13b6316)

**Comment by comfyanonymous** [comment]
There were some changes to the primitive nodes: https://github.com/comfyanonymous/ComfyUI/pull/1669

This might have broken some custom scripts.

**Comment by JayAitch1729** [comment]
I can break the default script by just changing the 'width' variable in 'Latent Image' from a widget to an input. I think it's worse that 'some custom scripts' - any script that has turned a widget into an input appears to be broken now.

**Comment by ltdrdata** [comment]
> I can break the default script by just changing the 'width' variable in 'Latent Image' from a widget to an input. I think it's worse than 'some custom scripts' - any script that has turned a widget into an input appears to be broken now.

In my environment, there is no issue. Try testing it with all the other custom nodes disabled.
Don't forget to remove everything except the 'core' directory in 'web/extensions'.

**Comment by JayAitch1729** [comment]
I'll try that, but that seems like a workaround rather than a solution?

**Comment by ltdrdata** [comment]
> I'll try that, but that seems like a workaround rather than a solution?

We need to figure out what is the real problem.

**Comment by JayAitch1729** [comment]
> > I'll try that, but that seems like a workaround rather than a solution?
> 
> We need to figure out what is the real problem. After removing the custom node and verifying that there are no issues, you should identify which custom node is causing the problem and report it to the creator of that custom node, requesting an compatibility update.

Ah with you now! I'll give that a go - high time I parsed back my custom nodes, and maybe the one that's broken isn't one I use anyway :)

**Comment by JayAitch1729** [comment]
Looks like it was 'Nested Nodes'. I was lucky, it was the third thing I added back in. I can live without this one :)

**Comment by ltdrdata** [comment]
> Looks like it was 'Nested Nodes'. I was lucky, it was the third thing I added back in. I can live without this one :)

Ah that is... I reported to him, already.
Just I didn't thought that it is related to converting to input.

**Comment by ltdrdata** [comment]
> Ok thanks, I’ll uninstall Nested and give it a try. What’s strange is my image workflow above doesn’t use any nested nodes — why I ignored the error re nested nodes in the log last night — will report back later today.

It is not a just node. It is kinda infra extension.

**Comment by var1ableX** [comment]
> > Ok thanks, I’ll uninstall Nested and give it a try. What’s strange is my image workflow above doesn’t use any nested nodes — why I ignored the error re nested nodes in the log last night — will report back later today.
> 
> It is not a just node. It is kinda infra extension.

Thanks for the tip - I managed to find / fix it - Uninstalling via Manager didn't get rid of the folder under Web->Extensions. I moved that to trash and things seem to be working again.

**Comment by XeoOuYang** [comment]
pythonsssss widget break the scrip，after I uninstall it， everything works fine.
