### ISSUE TITLE
Disabling search

### ISSUE THREAD

**Issue by PassiveLemon** [comfyanonymous/ComfyUI#168]
I find that the double click search thing is incredibly annoying and would like to know if there is a way to disable it. I'm fine if I have to modify some files.

Maybe in the future, a toggle to enable and disable it?

**Comment by FaridSafi** [comment]
As a quick dirty modification you can delete `this.showSearchBox(e);` in `web/lib/litegraph.core.js`

**Comment by PassiveLemon** [comment]
Thanks for that. It works perfectly

**Comment by PassiveLemon** [comment]
For anyone in the future, you can add the line `sed -i 's/this\.allow_searchbox = true;/this.allow_searchbox = false;/' /stable-diffusion/web/lib/litegraph.core.js
` in the ComfyUI entrypoint.sh and it will enable so you don't have to do it manually.
