### ISSUE TITLE
How I have a multi gpu system and I want to add an AMD 6900

### ISSUE THREAD

**Issue by dfghsderftgerdf** [comfyanonymous/ComfyUI#1716]
What do I need to add to allow comfy to run on my AMD which I'm using using with RTX gpu's already?

**Comment by NeedsMoar** [comment]
More information about the operating system, computer specifications, and what you're expecting to happen;  do you want to be able to team it with the RTXs within single images (not possible afaik) or just generate extra images on it?  

RDNA2 is going to be slow for stable diffusion inference at any rate, even the rudimentary matrix scheduling instructions they added to RDNA3 don't exist.  I don't know what generation the RTX cards are but 650W power spikes probably aren't worth a 5-10% speedup assuming you're doing frames that don't need to be shared cross-device 

If you're on linux I think you can set up torch-rocm and it'll still be able to generate code for CUDA.  It's not available for Windows yet so the only way to use both would be a venv with torch-directml alongside a venv with torch-cuda.  I can predict from 7900XTX & all-cpu speeds in directml that on a 6900, everything maybe 1024x1024 and up will be slower on the video card than on a 16 core CPU.  I'm basing this on 1280x1280 and up being slower on the 7900XTX than on a 32 core TR PRO 5975WX when I accidentally ran the model on CPU.  

I ended up buying a 4090 to avoid the mess for now.  There are a few things like AMD ProRender and the ncnn-vulkan (or any other pure vulkan projects) that can use both cards and split work between them but AMD hasn't gotten around to adding their new raytrace instructions to the renderers they support yet so NVIdia is up to 3.5x faster even in ProRender.  I'm hoping eventually they'll support the same workloads from Windows ROCm.  AMD has the advantage in vector fp16 which translates well to a lot of games, even though I don't play much of anything anymore.

**Comment by dfghsderftgerdf** [comment]
Uh, I have a 6900 installed on a windows 10 machine, I'll remove the RTX card if I can get this gpu running since it has 24gb of vram. 

It says this on the comfy github: [DirectML (AMD Cards on Windows)](https://github.com/comfyanonymous/ComfyUI#directml-amd-cards-on-windows)
pip install torch-directml Then you can launch ComfyUI with: python main.py --directml  

still I added this and it fails to run!

**Comment by NeedsMoar** [comment]
The DirectML backend can't coexist with the CUDA one, so torch / torch-gpu and all the related packages need to be removed entirely and the directml versions installed.  You're not going to enjoy the experience though, I'm just warning you.   

This removes your ability to run on CUDA devices of course.  

I'd tell you to wait for rocm on windows if you're going to try it so you can use both cards and get more reasonable speeds.  The memory management alone will be rough.

**Comment by dfghsderftgerdf** [comment]
Looks like I'm putting this idea on the back shelf until the new upgrade then, thanks for the info!
