### ISSUE TITLE
Loras in multiple locations?

### ISSUE THREAD

**Issue by Charuru** [comfyanonymous/ComfyUI#1720]
Is there anyway to look in multiple locations / disks for loras? If it's not here then check other there behavior. Running out of diskspace for Loras.

**Comment by NeedsMoar** [comment]
Yes
Edit extra_model_paths.yaml.example in the ComfyUI root as it instructs (in the file) and save it without the .example and restart and you can load from any directory tree wherever;  haven't tested network shares but I'd imagine they'd work too, just won't be very fast unless you have higher speed links to your file server than most computers support.

**Comment by Charuru** [comment]
> Yes Edit extra_model_paths.yaml.example in the ComfyUI root as it instructs (in the file) and save it without the .example and restart and you can load from any directory tree wherever; haven't tested network shares but I'd imagine they'd work too, just won't be very fast unless you have higher speed links to your file server than most computers support.

Ohh thanks, I thought this replaces the location but it's really an extra location and it loads from both places. Thanks.
