### ISSUE TITLE
[Feature Request] Share example graphs

### ISSUE THREAD

**Issue by ifsheldon** [comfyanonymous/ComfyUI#173]
Hi! Thanks for this awesome work! 

Can you please share the examples on the example website? I tried to connect the nodes myself according to the images of the example node graph and I took an hour to check what went wrong when a wrong generated image came out since I'm a bit sloppy. I guess there may be someone like me, so it would be great to share the example graphs saved in JSON. Thanks again!

**Comment by comfyanonymous** [comment]
Save the PNGs on the page and load them with ComfyUI.

**Comment by WASasquatch** [comment]
> Save the PNGs on the page and load them with ComfyUI.

Embedding the workflow JSON with images?

**Comment by comfyanonymous** [comment]
ComfyUI puts the workflow in all the PNG files it generates but I also went the extra step for the examples and embedded the workflow in the screenshots like this one for example: https://comfyanonymous.github.io/ComfyUI_examples/2_pass_txt2img/hiresfix_latent_workflow.png

**Comment by ifsheldon** [comment]
Awesome! I missed some lines in the README and on the example page about the metadata. Thanks for the explanation!

**Comment by WASasquatch** [comment]
That's pretty nifty, but probably should be a preference since not everyone wants to share and shouldn't have to strip files. It is for commercial use after all.

**Comment by anonymoussss** [comment]
@comfyanonymous 
Your work is pretty cool! How did you save the workflow as a png that can be loaded?

**Comment by WASasquatch** [comment]
> 

I made a tool for that, it's on the plugins list I maintain: https://GitHub.com/WASasquatch/ComfyUI_Plugins click on the WORKFLOW2PNG link in the others link. You can use that colab, or copy the CLI script example below the colab program.

**Comment by comfyanonymous** [comment]
> Your work is pretty cool! How did you save the workflow as a png that can be loaded?

Here's my script, use it like: `python copy_pnginfo.py source.png source_with_metadata.png destination.png`
```
import sys
from PIL.PngImagePlugin import PngInfo
from PIL import Image
image = Image.open(sys.argv[1])
image1 = Image.open(sys.argv[2])

metadata = PngInfo()
for x in image1.info.keys():
  metadata.add_text(x, image1.info[x])
image.save(sys.argv[3], pnginfo=metadata)
```
