### ISSUE TITLE
Error with KSampler

### ISSUE THREAD

**Issue by barrysutton** [comfyanonymous/ComfyUI#1738]
Running ComfyUI on Google Colab. Getting this error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.12 requires torch<2.1,>=1.7, but you have torch 2.1.0+cu118 which is incompatible.
torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 2.1.0+cu118 which is incompatible.
torchdata 0.6.1 requires torch==2.0.1, but you have torch 2.1.0+cu118 which is incompatible.
torchtext 0.15.2 requires torch==2.0.1, but you have torch 2.1.0+cu118 which is incompatible.
torchvision 0.15.2+cu118 requires torch==2.0.1, but you have torch 2.1.0+cu118 which is incompatible.

Any assistance appreciated. Thank you.

**Comment by thepeted** [comment]
I think this will be the reason.  https://github.com/facebookresearch/xformers/issues/870

**Comment by barrysutton** [comment]
Oh thanks, how does this stuff get fixed/updated? New to this.

Sent via Superhuman ***@***.***>

**Comment by comfyanonymous** [comment]
you don't need xformers if you have pytorch 2.1 so you can just ignore that.

**Comment by barrysutton** [comment]
> you don't need xformers if you have pytorch 2.1 so you can just ignore that.

The process fails when it gets to the KSampler. What is the fix you are suggesting?

**Comment by barrysutton** [comment]
Is there a workaround? Are you suggesting deleting files or ...? I'm not a coder so need some clear direction. Thanks everyone.

**Comment by comfyanonymous** [comment]
comment out the line that installs xformers or run comfyui with: --disable-xformers

**Comment by barrysutton** [comment]
> comment out the line that installs xformers or run comfyui with: --disable-xformers

Like this? 
<img width="1062" alt="Screenshot 2023-10-13 at 7 59 15 PM" src="https://github.com/comfyanonymous/ComfyUI/assets/140111147/0bedc5d6-8dbc-4925-8f1b-16c4c43a3d70">

**Comment by barrysutton** [comment]
Seems to be saying torch 2.1.0+cu118 is incompatible...
<img width="1923" alt="Screenshot 2023-10-13 at 8 21 45 PM" src="https://github.com/comfyanonymous/ComfyUI/assets/140111147/e710757a-210b-41d5-b99a-da51e2982ead">
Thanks

**Comment by barrysutton** [comment]
> --disable-xformers

You were on to something here. Any further suggestion? ComfyUI totally broken.

**Comment by barrysutton** [comment]
> I think this will be the reason. [facebookresearch/xformers#870](https://github.com/facebookresearch/xformers/issues/870)

You were on to something here. Any further suggestion? ComfyUI totally broken.

**Comment by NeedsMoar** [comment]
on the command line when you start comfy or added to the shortcut.  I start it with a file named comfy.cmd that has some parameters built in and eats everything else from the command line so it would be:

comfy --disable-xformers

The standalone versions have longer names but you'd type it after those or right click the shortcut->select properties from popup menu, and add a space and --disable-xformers at the end of the command.

**Comment by barrysutton** [comment]
> on the command line when you start comfy or added to the shortcut. I start it with a file named comfy.cmd that has some parameters built in and eats everything else from the command line so it would be:
> 
> comfy --disable-xformers
> 
> The standalone versions have longer names but you'd type it after those or right click the shortcut->select properties from popup menu, and add a space and --disable-xformers at the end of the command.

Thanks for the reply - I'm running in Google Colab. Trying to find where that would be.

**Comment by NeedsMoar** [comment]
> Thanks for the reply - I'm running in Google Colab. Trying to find where that would be.
Ah yeah I missed that part.  There should be a command prompt at the bottom but it's probably easier (if you're running from a notebook) to click on the notebook section on the left to edit the commands executed and stick the parameter in over there, if I'm remembering how those work...   If it auto-launches before you can edit the notebook  / run someone else will have to help you regarding terminating comfy without shutting down the VM and relaunching with the correct parameter. 


> you don't need xformers if you have pytorch 2.1 so you can just ignore that.
@comfyanonymous

I spent the time building it for the heck of it the other day (aka it builds cleanly on Windows).  Somebody from flash-attention-2 where xformers gets its faster attention methods if Triton isn't available unbroke the build on Windows for that as well, although I don't think comfy uses it;  I feel like it might have for a while a couple of months ago, probably before the windows build broke.  I contributed by trolling them moderately.   ;-)  

I don't know if it'll help as much on <4000 series but an average of 5s faster / 25% better times on a 2k x 2k output is pretty good.  You'll notice that it doesn't really change things that much for 1024x1024 though, so if you're not denoising large latents it's probably not worth the excess pain getting everything in the right place requires at the moment.  

pytorch-attention is slower than xformers, especially at larger generation sizes.  These are timings from an SD 1.5 model run for 50 iterations of euler ancestral kerras on a 1024x1024 latent followed by upscale with one of the model-based latent upscalers to 2048x2048 and 12 iterations of dpmpp_3m_sde_gpu at higher CFG and ~.35 denoise to detail the upsized image.  
With (I'm aware some of these don't matter but I wanted to cover everything).:

```
bitsandbytes               0.41.1
cuda-python               12.2.0
cupy-cuda12x              12.2.0
cupy-wheel          12.2.0
torch                     2.1.0+cu121
torchaudio            2.1.0+cu121
torchvision            0.16.0+cu121
transformers          4.26.1
xformers               0.0.23+d20354a.d20231007
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xFormers 0.0.23+d20354a.d20231007
memory_efficient_attention.cutlassF:               available
memory_efficient_attention.cutlassB:               available
memory_efficient_attention.decoderF:               available
memory_efficient_attention.flshattF@2.3.2:         available
memory_efficient_attention.flshattB@2.3.2:         available
memory_efficient_attention.smallkF:                available
memory_efficient_attention.smallkB:                available
memory_efficient_attention.tritonflashattF:        unavailable
memory_efficient_attention.tritonflashattB:        unavailable
memory_efficient_attention.triton_splitKF:         unavailable
indexing.scaled_index_addF:                        available
indexing.scaled_index_addB:                        available
indexing.index_select:                             available
swiglu.dual_gemm_silu:                             available
swiglu.gemm_fused_operand_sum:                     available
swiglu.fused.p.cpp:                                available
is_triton_available:                               False
pytorch.version:                                   2.1.0+cu121
pytorch.cuda:                                      available
gpu.compute_capability:                            8.9
gpu.name:                                          NVIDIA GeForce RTX 4090
build.info:                                        available
build.cuda_version:                                1202
build.python_version:                              3.10.11
build.torch_version:                               2.1.0+cu121
build.env.TORCH_CUDA_ARCH_LIST:                    None
build.env.XFORMERS_BUILD_TYPE:                     None
build.env.XFORMERS_ENABLE_DEBUG_ASSERTIONS:        None
build.env.NVCC_FLAGS:                              None
build.env.XFORMERS_PACKAGE_FROM:                   None
build.nvcc_version:                                12.2.140
source.privacy:                                    open source
```

pytorch 2.0 attention:
```

making attention of type 'vanilla-pytorch' with 512 in_channels
Global Step: 840001
Prompt executed in 32.43 seconds
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
100% -50/50 [00:08<00:00,  6.05it/s]
100% -14/14 [00:17<00:00,  1.22s/it]
Prompt executed in 26.94 seconds
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
100% -50/50 [00:08<00:00,  5.97it/s]
100% -14/14 [00:17<00:00,  1.23s/it]
Prompt executed in 27.14 seconds
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
100% -50/50 [00:08<00:00,  6.06it/s]
100% -14/14 [00:17<00:00,  1.23s/it]
Prompt executed in 27.11 seconds
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
100% -50/50 [00:08<00:00,  6.03it/s]
100% -14/14 [00:17<00:00,  1.22s/it]
Prompt executed in 26.98 seconds
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
100% -50/50 [00:08<00:00,  6.05it/s]
100% -14/14 [00:17<00:00,  1.23s/it]
Prompt executed in 27.10 seconds
```

xformers local build + flash attention (from wheel)
```
making attention of type 'vanilla-xformers' with 512 in_channels
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
100% - 50/50 [00:08<00:00,  6.16it/s]
100% - 12/12 [00:12<00:00,  1.05s/it]
Prompt executed in 22.28 seconds
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
100% - 50/50 [00:08<00:00,  6.20it/s]
100% - 12/12 [00:12<00:00,  1.05s/it]
Prompt executed in 22.19 seconds
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
100% - 50/50 [00:08<00:00,  6.25it/s]
100% - 12/12 [00:12<00:00,  1.06s/it]
Prompt executed in 23.52 seconds
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
100% - 50/50 [00:08<00:00,  6.25it/s]
100% - 12/12 [00:12<00:00,  1.05s/it]
Prompt executed in 22.13 seconds
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
100% - 50/50 [00:08<00:00,  6.18it/s]
100% - 12/12 [00:12<00:00,  1.05s/it]
Prompt executed in 22.24 seconds

```

**Comment by barrysutton** [comment]
> comment out the line that installs xformers or run comfyui with: --disable-xformers

I didn't mention previously I'm running this on Google Colab. Could you suggest how to do this in Colab environment? Thank you!

**Comment by ltdrdata** [comment]
I've applied a HOTFIX to force the use of PyTorch 2.0.1 in the Colab notebook for the manager. 
Those who need it, take note.

https://github.com/ltdrdata/ComfyUI-Manager/blob/main/notebooks/comfyui_colab_with_manager.ipynb

**Comment by barrysutton** [comment]
> I've applied a HOTFIX to force the use of PyTorch 2.0.1 in the Colab notebook for the manager. Those who need it, take note.
> 
> https://github.com/ltdrdata/ComfyUI-Manager/blob/main/notebooks/comfyui_colab_with_manager.ipynb

Should I revert the change I made to my locally stored requirements.txt file? I modified torch>=2.0.1. Should I remove this fix? It seems to have stopped working around the time you made this HOTFIX

Thanks!

**Comment by ltdrdata** [comment]
> > I've applied a HOTFIX to force the use of PyTorch 2.0.1 in the Colab notebook for the manager. Those who need it, take note.
> > https://github.com/ltdrdata/ComfyUI-Manager/blob/main/notebooks/comfyui_colab_with_manager.ipynb
> 
> Should I revert the change I made to my locally stored requirements.txt file? I modified torch>=2.0.1. Should I remove this fix? It seems to have stopped working around the time you made this HOTFIX
> 
> Thanks!

This fix is a hotfix by listing it directly with pip instead of modifying the `requirements.txt` file. Modifying the `requirements.txt` directly could cause problems with updates. Once the `xformers` issue is resolved in `torch 2.1.0`, you can change the comment and return to the previous method.

**Comment by barrysutton** [comment]
> > > I've applied a HOTFIX to force the use of PyTorch 2.0.1 in the Colab notebook for the manager. Those who need it, take note.
> > > https://github.com/ltdrdata/ComfyUI-Manager/blob/main/notebooks/comfyui_colab_with_manager.ipynb
> > 
> > 
> > Should I revert the change I made to my locally stored requirements.txt file? I modified torch>=2.0.1. Should I remove this fix? It seems to have stopped working around the time you made this HOTFIX
> > Thanks!
> 
> This fix is a hotfix by listing it directly with pip instead of modifying the `requirements.txt` file. Modifying the `requirements.txt` directly could cause problems with updates. Once the `xformers` issue is resolved in `torch 2.1.0`, you can change the comment and return to the previous method.

Thank you so much for this fix and replies. Have a safe and restful weekend.

**Comment by LukeOvermind** [comment]
Right it seems due to updates the hotfix is not working any more and getting the following errors

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.0+cu118 requires torch==2.1.0, but you have torch 2.0.1+cu118 which is incompatible.
torchdata 0.7.0 requires torch==2.1.0, but you have torch 2.0.1+cu118 which is incompatible.
torchtext 0.16.0 requires torch==2.1.0, but you have torch 2.0.1+cu118 which is incompatible.
torchvision 0.16.0+cu118 requires torch==2.1.0, but you have torch 2.0.1+cu118 which is incompatible.

removing the hotfix everything start perfect but the you get the ksampler error. [https://github.com/comfyanonymous/ComfyUI/issues/1792](url)

**Comment by LukeOvermind** [comment]
Update. Changing the hotfix from 2.0.1 to 2.1.0 seems to fix the issue.

**Comment by xybear1966** [comment]
thank you for the fix.  took a while to find.  I was looking for nodes (especailly the manager) not installing.  I was experimenting with work flows and was getting errors with the k-sampler and other things, but thought it was me and a bad flow.  then  the manager and other nodes disappeared.  Thanks again!!
