### ISSUE TITLE
ERR_NGROK_8012

### ISSUE THREAD

**Issue by smoothwalker1** [comfyanonymous/ComfyUI#1739]
Hi, I'm trying to run comfyui on sagemaker studio lab but keep getting this error;

ERR_NGROK_8012
Traffic was successfully tunneled to the ngrok agent, but the agent failed to establish a connection to the upstream web service at localhost:8188. The error encountered was:

dial tcp 127.0.0.1:8188: connect: connection refused

I'm new to computers and coding so I am completely lost. Can someone please guide me through this.

Thanks

**Comment by VincentNeemie** [comment]
When connecting on a cloud, you can't use the localhost ip address, you have to use the tunnel ip for the public address

**Comment by Acquititionm** [comment]
> When connecting on a cloud, you can't use the localhost ip address, you have to use the tunnel ip for the public address

Ty for your reply, but I'm new to all this and literally have no idea what you are talking about. I loaded a notebook, installed everything the way they mentioned and received the above error.

I don't know what you are telling me to do, I'm lost

**Comment by Da1sypetals** [comment]
have you solved this problem? i encountered something similar. thanks.

**Comment by JulianKingman** [comment]
Try running it with the `--listen` flag (e.g. `python main.py --listen`)
