### ISSUE TITLE
X-formers | Colab notebook not working anymore

### ISSUE THREAD

**Issue by manuterui** [comfyanonymous/ComfyUI#1741]
hi,

i'm currently running on ComfyUI on Colab and haven't been able to successfully install x-formers today (worked fine yesterday).

below is the error message when trying to install it and also the error when trying to run the notebook.

any suggestions on how to solve this? thanks.

hi,

i'm currently running on ComfyUI on Colab and haven't been able to successfully install x-formers today (worked fine yesterday).

below is the error message when trying to install it and also the error when trying to run the notebook.

any suggestions on how to solve this? thanks.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.12 requires torch<2.1,>=1.7, but you have torch 2.1.0+cu118 which is incompatible.
torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 2.1.0+cu118 which is incompatible.
torchdata 0.6.1 requires torch==2.0.1, but you have torch 2.1.0+cu118 which is incompatible.
torchtext 0.15.2 requires torch==2.0.1, but you have torch 2.1.0+cu118 which is incompatible.
torchvision 0.15.2+cu118 requires torch==2.0.1, but you have torch 2.1.0+cu118 which is incompatible.
```

```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0+cu118)
Python 3.10.13 (you have 3.10.12)
Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
Memory-efficient attention, SwiGLU, sparse and more won't be available.
Set XFORMERS_MORE_DETAILS=1 for more details
xformers version: 0.0.22.post3
```

**Comment by stefanoflore** [comment]
I have the same problem... :(

**Comment by LukeOvermind** [comment]
So apparently xformers arent playing nice with Pytorch 2.1. But according to Comfy you don"t need xformers with Pytorch. 

However I think the colab users like ourselves would love someone to assist us in to get this fixed. For currently its unclear exactly how to go about.

**Comment by stefanoflore** [comment]
I solved it with a new installation and setting the torch==2.0.1 parameter in the requirements.txt file

**Comment by barrysutton** [comment]
> I solved it with a new installation and setting the torch==2.0.1 parameter in the requirements.txt file

THis sounds promising! Could you help me locate this file (I seem to have several versions in the ComfyUI folder, and how to modify the doc? Thank you!

**Comment by barrysutton** [comment]
> I solved it with a new installation and setting the torch==2.0.1 parameter in the requirements.txt file

Amazing that worked for me too. The requirements.txt file no looks like this. Is this correct?

torch>=2.0.1
torchsde
einops
transformers>=4.25.1
safetensors>=0.3.0
aiohttp
accelerate
pyyaml
Pillow
scipy
tqdm
psutil

**Comment by stefanoflore** [comment]
> > I solved it with a new installation and setting the torch==2.0.1 parameter in the requirements.txt file
> 
> Amazing that worked for me too. The requirements.txt file no looks like this. Is this correct?
> 
> torch>=2.0.1
> torchsde
> einops
> transformers>=4.25.1
> safetensors>=0.3.0
> aiohttp
> accelerate
> pyyaml
> Pillow
> scipy
> tqdm
> psutil

I wrote torch== instead of >= but it should be fine

**Comment by manuterui** [comment]
can we run comfy's notebook as is, or should we run the first cell, and make adjustments in requirements.txt or perhaps pip install torch==2.0.1 in a following cell? thanks

**Comment by barrysutton** [comment]
> > > I solved it with a new installation and setting the torch==2.0.1 parameter in the requirements.txt file
> > 
> > 
> > Amazing that worked for me too. The requirements.txt file no looks like this. Is this correct?
> > torch>=2.0.1
> > torchsde
> > einops
> > transformers>=4.25.1
> > safetensors>=0.3.0
> > aiohttp
> > accelerate
> > pyyaml
> > Pillow
> > scipy
> > tqdm
> > psutil
> 
> I wrote torch== instead of >= but it should be fine

Thank you so much for your help and everyone who has commented here. I really appreciate this community.

**Comment by barrysutton** [comment]
> can we run comfy's notebook as is, or should we run the first cell, and make adjustments in requirements.txt or perhaps pip install torch==2.0.1 in a following cell? thanks

I am running the notebook as is for now, but first edited the requirements.txt doc as described above. Then connect to Colab and run the notebook.

**Comment by barrysutton** [comment]
Update: unfortunately this fix has stopped working. Any further assistance is greatly appreciated.

**Comment by barrysutton** [comment]
A HOTFIX has been applied to the pip and seems to have fixed. Here is the thread for reference. https://github.com/comfyanonymous/ComfyUI/issues/1738#issuecomment-1762958576

**Comment by manuterui** [comment]
thank you everyone for your help, it works now :)
