### ISSUE TITLE
Unsupported Hypernetwork format - mish

### ISSUE THREAD

**Issue by alexopus** [comfyanonymous/ComfyUI#1749]
I am getting following error:
```
Unsupported Hypernetwork format, if you report it I might implement it. /home/user/ai/hypernetworks/houk1se1.pt   mish True True False True
```
when using: https://huggingface.co/nvmmonkey/optimal_hypernetwork/blob/main/houk1se1.pt

Any chance to get this working?
Thanks!

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/f8caa24bcc6abf226aeb486beeffd853e711c770

**Comment by alexopus** [comment]
Thank you!
