### ISSUE TITLE
Add Headers to Groups, and only draggable by header

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#175]
It is absolutely waaaay to easier to entirely mess up your node network by accidentally grabbing groups (their bounding box is way outside the actual group when zoomed in, making it hard to size groups as is). 

Groups should probably have a header bar, which is used to physically move the group, which would greatly reduce the risk of error. 

It's especially frustrating when this happens because it often captures nodes from other groups, and then places them under other nodes, making you have to move just about everything to get to nodes, move groups back and nodes to right groups, etc.

**Comment by comfyanonymous** [comment]
That's from litegraph, the javascript library I used for the nodes: https://github.com/jagenjo/litegraph.js

**Comment by WASasquatch** [comment]
Ah. Doesn't seem very active anymore.

**Comment by comfyanonymous** [comment]
Yes but it was the best I found.

**Comment by comfyanonymous** [comment]
This has been implemented for a while now.

**Comment by WASasquatch** [comment]
> This has been implemented for a while now.

Yeah, no one referenced the active issue with the PR to link them.

Maybe should put in a stale issue rule too: https://docs.github.com/en/github-ae@latest/actions/managing-issues-and-pull-requests/closing-inactive-issues

**Comment by comfyanonymous** [comment]
Yes I need to organize these issues better. Most of them are feature requests so closing them automatically doesn't make much sense when the feature might not have been implemented.

**Comment by WASasquatch** [comment]
> Yes I need to organize these issues better. Most of them are feature requests so closing them automatically doesn't make much sense when the feature might not have been implemented.

Maybe requests should go into Discussions -> Ideas to begin with though? They aren't issues or bugs.
