### ISSUE TITLE
Load JSON (API format)

### ISSUE THREAD

**Issue by ecornbower** [comfyanonymous/ComfyUI#1750]
The save / load JSON (API format) is currently broken in the [latest release](https://github.com/comfyanonymous/ComfyUI/tree/2231edec21fadcfddea6ae627318f5a2bd88dd63).

Steps to reproduce:

1. Load the default workflow.
2. Save as JSON (API) format
3. Clear the workflow, then load the JSON that was just saved.

Actual result:

Nothing will happen, but an error will be logged:

```
TypeError
graphData.nodes is not iterable
TypeError: graphData.nodes is not iterable
    at ComfyApp.loadGraphData (http://desktop-01:8080/scripts/app.js:1439:27)
    at reader.onload (http://desktop-01:8080/scripts/app.js:1759:10)
```

Expected result:

Workflow is reloaded.

Edit: Not sure if this is the intended functionality, but would really be nice to be able to re-import exported JSON API files to make changes and re-save back out again.

**Comment by ecornbower** [comment]
Upon further inspection, it looks like the [default JSON](https://github.com/comfyanonymous/ComfyUI/blob/master/web/scripts/defaultGraph.js) has a different format than what is being [saved out](https://github.com/comfyanonymous/ComfyUI/files/12908364/default_saved.json)

Happy to make a PR for this if I can get clarification on what format should be supported / exported.

**Comment by Chaoses-Ib** [comment]
Duplicate of #1498?

**Comment by ecornbower** [comment]
@Chaoses-Ib Yes, and it appears to be (mostly) working now so I'll close this out.
