### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Silversith** [comfyanonymous/ComfyUI#177]
I haven't checked the newer version but after using this interface for a while, I've found the following possible upgrades;
* Ability to pass the seed value from one sampler to another
* In Interface file browser/image download for remote use (Nothing complicated, just a viewer like the Save_File processor that just gets an update call after save file where I can select and download the previously generated images)
* A Note Item (I'd love to be able to add notes to the interface)

Not required but possible;
* Multi Lora Loader (Being able to add multiple Lora models and switch between them quickly when necessary)
* More detailed queue view (When I've queued multiple items, I'm not 100% sure what the details of the currently processing queue is, just the prompt details on hover would be useful)

**Comment by GrimblyGorn** [comment]
Looks like you went and coded some things now too :)

I'm hoping to check them out later possibly. I see you made the note node too, that's handy on its own.

**Comment by GrimblyGorn** [comment]
Ya one thing that I've found difficult in using this is there seems to be no way of telling what values i'm passing around. In many cases it's clear from having entered the value. But there's a lot of instance where it's not as clear and there's no way to display the value. Something that allowed a universal type input and then displayed its value before possibly passing it to an output would be very handy in those scenarios. A passthrough display node for value checking/watching.

In Grasshopper you can simply hover over the output connector and it'll pop open a little display with the values that connector is receiving or passing. That could be very handy here too. This somewhat fails when there's too much for the little popup window to display. In those cases, a node to display the data would be helpful too.

This could help clarify your seed issue better probably, or any others where a value is being questioned. Might be worth looking into if you cared to or had the time. I might later too if I find some time.

**Comment by GrimblyGorn** [comment]
Oooh you fixed the Optional inputs? That was really bugging me.

I may have to go merge yours to mine now :)

**Comment by Silversith** [comment]
@comfyanonymous I've finally added my output directory solution and removed the SaveImageList node from my fork.
Please have a look and see what you think.
https://github.com/Silversith/ComfyUI/blob/master/web/extensions/core/imageFeed.js
It's essentially an image drawer that will load all the files in the output dir on browser refresh, and on Image Save trigger, it will add the image to the drawer.
The code was partially copied from https://github.com/pythongosssss/ComfyUI-Custom-Scripts and then modified.

**Comment by Silversith** [comment]
I see the delete button breaks the drawer, I'll have to fix that still

**Comment by comfyanonymous** [comment]
Make a pull request if you want me to properly look at it. It makes it easier for me to keep track of things.

**Comment by jahu00** [comment]
Ability to pass seeds would be great.

**Comment by Silversith** [comment]
> Ability to pass seeds would be great.

You can already use a primitive and convert the seeds to inputs and pass in the primitive
