### ISSUE TITLE
ComfyUI API regarding python and delimiters

### ISSUE THREAD

**Issue by Smuzzies** [comfyanonymous/ComfyUI#1787]
I've been working with the websocket script in python for a few months now and have had great success in generating through workflows via scripting. After digging more into animation workflows, I'm running into an issue and I'm hoping someone has a solution.

When passing prompt data, it's written as a frame number and the prompt that occurs at that frame number followed by a comma. That continues until all desired frame numbers are entered each on their own line (return character) and the last line does not need a comma. 

For reference:
  "0" :"graveyard ",
  "16" :"dark cold road, dead trees"

![image](https://github.com/comfyanonymous/ComfyUI/assets/110495122/18768162-ab29-4f52-bf31-2f4a23c398e8)

When the data from this node is passed using the websocket python example, the console shows errors that something is wrong with the JSON load due to expected characters. I'm assuming it does not like all the extra ( " , ; ) that exists and breaks the load injected.

I guess my question is does ComfyUI support a different method of listing "frame:prompt," data possibly with characters that won't break the rules of python? Included is some errors pulled from the generation.

[data.json](https://github.com/comfyanonymous/ComfyUI/files/13031160/data.json)
![image](https://github.com/comfyanonymous/ComfyUI/assets/110495122/c62a93da-8245-40d5-bc00-58e427a45e6d)

**Comment by jn-jairo** [comment]
Looks like an error with that "ComfyUI_FizzNodes" you should open an issue on that repository instead, and I see you already did https://github.com/FizzleDorf/ComfyUI_FizzNodes/issues/17.

But looking at the error it is most likely you are not escaping the json correctly, probably the double quotes, take a look at this example of double quote escaping https://stackoverflow.com/a/15637481.

**Comment by Smuzzies** [comment]
I believe you're likely correct. Spent a few hours last night trying different syntax on that specific line in python.

Trying to inject:

`prompt["100"]["inputs"]["text"] = f"\"0\" :\"{userinput1}\",\n\"16\" :\"{userinput2}\""`

using fstrings, so could be a combination of things causing the issue

**Comment by Smuzzies** [comment]
Appears it was the way python handles "argv" statements probably with all the double quotes as you mentioned, seems it was parsing each section from the prompt as an individual argv instead a singular value. Made some adjustments in the example websocket script provided in the Comfy github samples directory to work around it. Appreciate the help sir.
