### ISSUE TITLE
Attention methods need fix to work with HyperTile

### ISSUE THREAD

**Issue by jn-jairo** [comfyanonymous/ComfyUI#1816]
The xformer attention method was fixed to work with HyperTile but the other methods need to be fixed too, like the attention_split that I'm using, I replaced the rearrange with the reshape/permute copying from the attention_xformers and it works.

But I am not sure if it is the right way, and the other methods may need a fix too, so I am not making a PR, it is better if someone with more knowledge do it.

**Comment by rabidcopy** [comment]
Yeah I was sort of wondering about that. Thought it not working for quad or split was something wrong on my end. I use HyperTile and quad attention on SD.Next with some luck. Not supposed to be "supported", but in my own studies it only breaks the Reference ControlNet. Anecdotal though and that might not even apply to its implementation here if it does work for split and quad eventually.

**Comment by comfyanonymous** [comment]
Should be fixed with: https://github.com/comfyanonymous/ComfyUI/commit/e6bc42df4662e571365ffbafe7c2dfac2cee3116
