### ISSUE TITLE
Multiple session local or cloud server possible?

### ISSUE THREAD

**Issue by Niutonian** [comfyanonymous/ComfyUI#1819]
Hello, guys. I'm in a bind at the moment. 
I have the opportunity to teach a class about generative art, and I would like to use ConfUI because I think it's the most flexible platform and I have a few workflows already created.
But my issue is that my students are all on Macs and in the first class I did I had them all install InvokeAI, but it was a disaster (no hate to the Invoke team, they are great),
How easy or complicated would it be to install a session of ComfyUi cloud or perhaps my machines but with multiple users.
Is a setup like that possible?
Thank you, and that's all for now.

**Comment by jn-jairo** [comment]
ComfyUI accepts multiple users by default and the requests are queued, for cloud you can use the [notebook](https://github.com/comfyanonymous/ComfyUI#jupyter-notebook) and send the URL generated in the notebook to your students. You can also run it in your machine and share it using the local network or tunneling (see the notebook to know how to do it).

The UI configurations are local and saved in the browser local storage so everyone can set the UI in a way they like. In the server configurations you add the models, lora, embedding, custom nodes and things like that, and those will be available to everyone.

The input and output folders are the same for everyone but that shouldn't be a problem in a class, and may help for you to see theirs results, just ask them to change the filename prefix in the Save Image node to their name or something, you can even pass a subfolder in that name like "class_01/project_A/Mary", this way you can check theirs work and keep it organized, just remember to download it, if you are using the cloud, before closing the cloud instance.

**Comment by Niutonian** [comment]
@jn-jairo thanks a million times for your input, I never thought of setting it up like that, I will create a session and run some tests on different machines, 
This should work too if I create a --listen and let my students connect to my machine, this should be fine too as long as the output names are differents?

**Comment by ltdrdata** [comment]
> @jn-jairo thanks a million times for your input, I never thought of setting it up like that, I will create a session and run some tests on different machines, This should work too if I create a --listen and let my students connect to my machine, this should be fine too as long as the output names are differents?

Setting the file name is essentially just about the prefix, and the generated file names are always unique. Of course, it's a good practice to add an appropriate prefix to identify who created the image.

**Comment by jn-jairo** [comment]
> @jn-jairo thanks a million times for your input, I never thought of setting it up like that, I will create a session and run some tests on different machines, 
> This should work too if I create a --listen and let my students connect to my machine, this should be fine too as long as the output names are differents? 

Just complementing what @ltdrdata said, if your machine is not powerful enough to handle the amount of students, you can set up more machines and divide the students between those machines, if you don't have the resources an easy way is renting a cloud service.

**Comment by Niutonian** [comment]
@ltdrdata & @jn-jairo, 
I have around 10 students at a time, 
Hopefully, my poor 3070 will be handle to handle a queue of 768x768 images :)

**Comment by yingtao-xie** [comment]
In a remote access, queue generation can be carried out on the web, but can not see the running process (highlight node), gallery, preview image and generation image in the page, but can see the generation image in the output folder on the server, how is this?

**Comment by liusida** [comment]
hi, @Niutonian , I've just described my approach of serving ComfyUI here yesterday:
https://github.com/comfyanonymous/ComfyUI/issues/3461#issuecomment-2109166039

And I think that you might be interested.
