### ISSUE TITLE
after commit  f1062be, images with uni_pc+ddim_uniform and low stepcount no longer decode properly (but are fine in preview)

### ISSUE THREAD

**Issue by martijnat** [comfyanonymous/ComfyUI#1839]
previously, uni_pc(_bh2) with the ddim_uniform sampler was great for low step prototyping.
Before the commit the xy plot for steps looked like this: (workflow in metadata)
![bottle_00001_](https://github.com/comfyanonymous/ComfyUI/assets/22380358/d6896f58-e394-4727-8926-f3ebc0f7b4bc)
After the commit the xy plot looks like this
![bottle_00002_](https://github.com/comfyanonymous/ComfyUI/assets/22380358/5e640702-3d95-4e37-bb4d-042ff4ffde9b)
I don't mind the slightly different images, but after sampling <=3 steps, I can get proper previews using taesd, but not when decoding using a vae.

For comparison, here are the sample images decoded using the taesd preview instead of using a vae:

![null(1)](https://github.com/comfyanonymous/ComfyUI/assets/22380358/5b0cba1d-57f5-4cb8-8e3c-801ff548ddb1)
![null(2)](https://github.com/comfyanonymous/ComfyUI/assets/22380358/c97e5232-a863-480e-8d32-c8dd479f0529)
![null(3)](https://github.com/comfyanonymous/ComfyUI/assets/22380358/91f999a8-21a7-4c61-ba88-96125eacc43e)
![null(4)](https://github.com/comfyanonymous/ComfyUI/assets/22380358/e32aedcf-4d9b-4150-8844-000aec5fdfd9)
![null(5)](https://github.com/comfyanonymous/ComfyUI/assets/22380358/71e3f357-6308-454e-861f-e75533cf71d8)
![null(6)](https://github.com/comfyanonymous/ComfyUI/assets/22380358/55e735b6-ad4f-4ce9-a11c-1bff7d15a5a3)

**Comment by comfyanonymous** [comment]
This should fix it: https://github.com/comfyanonymous/ComfyUI/commit/7fbb217d3a46fc117dd78b90191e528139fb851a

**Comment by martijnat** [comment]
Oh, wow. Thanks!

It works perfectly now
![bottle_00017_](https://github.com/comfyanonymous/ComfyUI/assets/22380358/a4839116-0991-4b58-a01a-f58b5e1fc7f1)
