### ISSUE TITLE
"request entity too large" when trying to upload a video file

### ISSUE THREAD

**Issue by glennamarshall** [comfyanonymous/ComfyUI#1857]
Is there a way to get round the file size limit when loading a video through a node in the browser?  It seems to be about 100mb - anything above will give an error.  Any work around / hack welcome, thanks.

**Comment by WASasquatch** [comment]
> Is there a way to get round the file size limit when loading a video through a node in the browser? It seems to be about 100mb - anything above will give an error. Any work around / hack welcome, thanks.

Maybe use a node that loads videos from direct path itself and doesn't use the web server. `aiohttp` does support a `client_max_size` for requests though. Perhaps @comfyanonymous can add it as a launch argument to override default size.

**Comment by glennamarshall** [comment]
thanks - will look into this - hopefully like you say a launch argument would be great :)

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/a12cc0532328b93b6d8d4d5a0ca3000d0b24b72c

**Comment by glennamarshall** [comment]
> [a12cc05](https://github.com/comfyanonymous/ComfyUI/commit/a12cc0532328b93b6d8d4d5a0ca3000d0b24b72c)

thank you!

**Comment by WASasquatch** [comment]
Amazing! So fast.
