### ISSUE TITLE
Unable to run ipadapter or load ipadapter-loading custom node

### ISSUE THREAD

**Issue by DrFisura** [comfyanonymous/ComfyUI#1858]
There must have been something breaking in the latest commits since the workflow I used that uses IPAdapter-ComfyUI can no longer have the node booted at all. Pretty significant since my whole workflow depends on IPAdapter. Just to check, I doubt the problem is with my conda environment

**Comment by jn-jairo** [comment]
I also use IPAdapter-ComfyUI and it is working fine for me, I have the ComfyUI and IPAdapter-ComfyUI in the latest commit.

**Comment by DrFisura** [comment]
> I also use IPAdapter-ComfyUI and it is working fine for me, I have the ComfyUI and IPAdapter-ComfyUI in the latest commit.

Then God knows why.



Error occurred when executing IPAdapter:

'ClipVisionModel' object has no attribute 'processor'

File "/media/drfisura/fedora_localhost-live2/home/drfisura/OFFICIAL/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/media/drfisura/fedora_localhost-live2/home/drfisura/OFFICIAL/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/media/drfisura/fedora_localhost-live2/home/drfisura/OFFICIAL/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/media/drfisura/fedora_localhost-live2/home/drfisura/OFFICIAL/ComfyUI/custom_nodes/IPAdapter-ComfyUI/ip_adapter.py", line 159, in adapter
cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/media/drfisura/fedora_localhost-live2/home/drfisura/OFFICIAL/ComfyUI/custom_nodes/IPAdapter-ComfyUI/ip_adapter.py", line 228, in clip_vision_encode
inputs = clip_vision.processor(images=img, return_tensors="pt")
^^^^^^^^^^^^^^^^^^^^^

**Comment by jn-jairo** [comment]
You need to update the IPAdapter-ComfyUI, there is already a fix for it in the commit https://github.com/laksjdjf/IPAdapter-ComfyUI/commit/9dcd42c910c4793a867ddf2296f2b037c87ead72

**Comment by DrFisura** [comment]
> You need to update the IPAdapter-ComfyUI, there is already a fix for it in the commit [laksjdjf/IPAdapter-ComfyUI@9dcd42c](https://github.com/laksjdjf/IPAdapter-ComfyUI/commit/9dcd42c910c4793a867ddf2296f2b037c87ead72)

Actually, it works for me in a fresh installation of ComfyUI replicating all the custom nodes I had and my workflow, so I guess that one culprit got solved along the way. Yes, that one bit might have been the wrong one, glad to see they solved it
