### ISSUE TITLE
Getting different results from a1111 with same prompt

### ISSUE THREAD

**Issue by flowtyone** [comfyanonymous/ComfyUI#1859]
I'm getting a very washed out result using comfy, and not at all similar to the result on automatic1111. Should it be this way?

![Screenshot 2023-10-29 at 9 27 31](https://github.com/comfyanonymous/ComfyUI/assets/145925146/c009b05c-6fe8-462a-830f-e119ed7ee080)
![Screenshot 2023-10-29 at 9 26 43](https://github.com/comfyanonymous/ComfyUI/assets/145925146/b59df8a2-5056-46d1-92ce-be19d86b22ac)
![Comfyui](https://github.com/comfyanonymous/ComfyUI/assets/145925146/45bc6372-b740-4b35-b0c2-48d530c98823)
![a1111](https://github.com/comfyanonymous/ComfyUI/assets/145925146/f56ddcb4-5ef4-4cae-9eb8-6f20071dd471)

**Comment by comfyanonymous** [comment]
replace that 2 weight in the negative prompt with something lower like 1.2

**Comment by flowtyone** [comment]
> replace that 2 weight in the negative prompt with something lower like 1.2

Thanks!
