### ISSUE TITLE
All ClipTextEncodes featuring weight interpretation / Token Normalization are failing 

### ISSUE THREAD

**Issue by var1ableX** [comfyanonymous/ComfyUI#1866]
I've attached a workflow, toggle conditioning switch to 1 (works), toggle switch to 2 (fails). I'm assuming the issue is in Comfy as several nodes from different sources are failing (Efficiency, BNK, WAS).

[weight_interpretation_bug_workflow.json](https://github.com/comfyanonymous/ComfyUI/files/13200563/weight_interpretation_bug_workflow.json)

**Comment by jn-jairo** [comment]
The code related to clip has changed, those custom nodes need to adapt to the change, try updating those custom nodes because some may already had fixed it and if it not works ask the creator of those custom nodes to adapt their code to the latest ComfyUI.
