### ISSUE TITLE
suddenly unbearable slow seems memory issues?

### ISSUE THREAD

**Issue by initcold** [comfyanonymous/ComfyUI#1869]
I have a couple of ComfyUI instances running in Proxmox with passthru GPU (RTX3060 12GB) on Ubuntu server 22.04
Untill yesterday, everything run fine, response times normal (like ~ 10 seconds)
Suddenly, this morning something happened.

1 ComfyUI instance, last week it did work perfectly, I did not update anything in between (like apt or so) now performance is absent:
- loading default workspace, default prompt -> acceptable performance
- loading img2img_workflow.png  -> just for 1 img2img, its running already 11 minutes and its on 40%
![image](https://github.com/comfyanonymous/ComfyUI/assets/142996626/d69e2b5b-80f9-471e-b4b5-2ae8f2a50e2e)

output (first prompt is above default wokrspace, 2nd prompt is running 11mins/40%

koen@comfyuixl:~/comfyuixl$ python3 main.py --listen 0.0.0.0
** ComfyUI start up time: 2023-10-31 11:25:24.789790

Prestartup times for custom nodes:
   0.0 seconds: /home/koen/comfyuixl/custom_nodes/ComfyUI-Manager

Total VRAM 12044 MB, total RAM 13973 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 1625 [e60ca692] | Released on '2023-10-27'

Import times for custom nodes:
   0.1 seconds: /home/koen/comfyuixl/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://0.0.0.0:8188
FETCH DATA from: /home/koen/comfyuixl/custom_nodes/ComfyUI-Manager/extension-node-map.json
got prompt
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.67it/s]
Prompt executed in 12.35 seconds
got prompt
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Requested to load SDXLClipModel
Loading 1 new model
[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.
Warning: Ran out of memory when regular VAE encoding, retrying with tiled VAE encoding.
Requested to load SDXL
Loading 1 new model
 45%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                                     | 9/20 [13:17<16:16, 88.77s/it]

My other  ComfyUI instance, I also did update this morning apt (did not do in a while)., Now it even breaks (will add output later)

**Comment by comfyanonymous** [comment]
How big is the image you are giving it as input?

**Comment by initcold** [comment]
whoepsy.. my bad ;- (
Indeed, i was loading an 10MB image (did not realize that). 

Just ran some test with the usual size image and no issues. 

thanks for your support!
