### ISSUE TITLE
how to make controlnet  like A111 "my prompt is more important"

### ISSUE THREAD

**Issue by xueqing0622** [comfyanonymous/ComfyUI#1880]
how to make controlnet  like A111 "my prompt is more important"
![image](https://github.com/comfyanonymous/ComfyUI/assets/114840118/87726948-e38b-470d-b6e4-877c960a64ad)

![image](https://github.com/comfyanonymous/ComfyUI/assets/114840118/b2657331-490d-409c-81c7-b3a100a3e24f)

**Comment by mijuku233** [comment]
You can do it with this custom node: [ComfyUI-Advanced-ControlNet](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet)

**Comment by xueqing0622** [comment]
Wow, thx,  mijuku233, You're really a master!  (◠‿◠) 
 I thought this extension was for animation, but I didn't realize "my prompt is more important"  it was here. 
I'm going to make a single image use controlnet like A111, is this the right way to connect the node like this?
![image](https://github.com/comfyanonymous/ComfyUI/assets/114840118/fed9d66c-5379-4bba-b346-5dbc3b2bb7c5)
