### ISSUE TITLE
Scheduling the CFG scale along the generation can drastically improve results on some case

### ISSUE THREAD

**Issue by Extraltodeus** [comfyanonymous/ComfyUI#1886]
The base idea is that since stable diffusion understands the image it is generating, then why not progressively give up the control along the generation so to make the image more coherent at the end?

I did my tests by using dpmpp3m_sde at 25 steps and with a CFG scale of 7.5.

For my tests the last step was done at a CFG scale of 1 and after night of testing I can say that ending with a scale at one at least with this sampler gave me the best results.

- First column is without any modification
- second is a linear decrease
- third column is a CFG scale decrease proportional to the sigmas:

![image_grid](https://github.com/comfyanonymous/ComfyUI/assets/15731540/a24b8070-5b0a-4619-bcd5-9e00ea4c3f74)

As you can see in the first column the artifacts are overly presents and the result is overall pretty messy.

The linear decrease can be pretty nice on simple things or when generating text.

The sigmas proportional decrease let more "jesus diffusion take the wheel" and gives pretty good result but when I tested this it did seem to ignore my negative prompts a lot more.

For this test the prompt is:

"RAW photo of a typical 90's kid bedroom, memory, dust, NES, playstation, analog tv on nightstand, shadowy, nostalgia, film grain"

And no negative. Seed 200 to 205.

The 3rd column is way more what I had in mind when I typed it.

[link to my test modification of the comfy/k_diffusion/sampling.py](https://github.com/Extraltodeus/temp/blob/main/sampling.py)

I was only able to do this hacky implementation because I don't know well enough the overall pipeline to do something clean adding a complete CFG scheduling option. Sorry for that.

replace the line:

    extra_args['cond_scale'] = remap_range(sigmas[i],sigmas[0],sigmas[len(sigmas)-2],initial_cfg,1)

by:

    extra_args['cond_scale'] = remap_range(i,0,len(sigmas)-2,initial_cfg,1)

to test with a linear decrease. It only modifies the sampler dpmpp3m_sde but other samplers could benefit such idea as well.

**Comment by abesmon** [comment]
I'm looking for implementation of https://arxiv.org/abs/2404.07724 and it seems related. @Extraltodeus have you seen that paper?

**Comment by Extraltodeus** [comment]
@abesmon You can check my Automatic CFG repository to reproduce the same conditions. The "warp drive" node is inspired from this paper but I got carried further by trying to find a way to have something more adaptable.

This repository from another dev is an actual attempt at recreating what is described in the paper :

https://github.com/ericbeyer/guidance_interval

(just restart the ui after using this one as it patches the sampling function after running)
