### ISSUE TITLE
Getting trouble converting prompt from a1111 to ComfyUI

### ISSUE THREAD

**Issue by fexli** [comfyanonymous/ComfyUI#1895]
I saw a previous issue about prompt conversion in [Issue-1859](https://github.com/comfyanonymous/ComfyUI/issues/1859)

so when transferring from a111 to comfy, it is necessary to divide the weight by 10 and add 1, including both positive and negative prompts
like (watermark: 2), it needs to be converted to (watermark: 1.2)
and (floating hair: 1.2) needs to be converted to (floating hair: 1.12)

is that correct?

**Comment by fexli** [comment]
(embedding:badhandv4:1.3) also cannot function properly, but (embedding:badhandv4) or embedding:bandhandv4 can

**Comment by ltdrdata** [comment]
The weight interpretation system between comfy and a1111 is not simply associated with normalization. Please refer to the explanation in this repository.

https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb

**Comment by fexli** [comment]
it's work! thanks.
