### ISSUE TITLE
collab not working link

### ISSUE THREAD

**Issue by Ramam001** [comfyanonymous/ComfyUI#19]
after using the collab after running all the cells in collab the output of that link is not showing anything
its blank and showing some error

**Comment by comfyanonymous** [comment]
You should see the UI in an iframe on the page once it starts up. If it doesn't show  up it's probably an extension or a firefox setting.

**Comment by 7108** [comment]
no ive used other collab with web ui but they mostly give gardio or local tunnel option 

the one in this isnt that universal ig

**Comment by comfyanonymous** [comment]
I added a cell in the notebook to run it with localtunnel so this should solve your issues: https://github.com/comfyanonymous/ComfyUI/commit/5796705cc61dd6ce2cf0efdb98c786e278d2bd3f
