### ISSUE TITLE
AMD GPU VRAM allocation error (use directml)

### ISSUE THREAD

**Issue by DSN2002** [comfyanonymous/ComfyUI#1900]
Hello everyone, my GPU is AMD's RX5600XT, which has 6G VRAM, but ComfyUI can only recognize 1G VRAM. When outputting images or using Controlnet, it will prompt that VRAM is insufficient. Is there any way to make ComfyUI use all 6G VRAM?——from Google Translate
![280455773-ca8b7478-88cd-4eff-a8f5-fd0b1d77b615](https://github.com/comfyanonymous/ComfyUI/assets/89450486/0c553413-a962-47a9-b028-ee43e453cf36)

**Comment by MythicalChu** [comment]
It says that but should be using all Vram anyway, it's always been that way for me too (Rx580 8Gb), what sizes of image are you trying to generate? With controlNet my max used to be around 512x768, but I can higher after some optimizations and using Hyper tile. Also, if your checkpoint is not around 2Gb that further reduces your image size cap...

**Comment by DSN2002** [comment]
> It says that but should be using all Vram anyway, it's always been that way for me too (Rx580 8Gb), what sizes of image are you trying to generate? With controlNet my max used to be around 512x768, but I can go higher after some optimizations and using Hyper tile. Also, if your checkpoint is not around 2Gb that further reduces your image size cap...

I try to generate 512*512 size image and use controlNet.The size of checkpoint is 2.21G.The generation can only be completed once, and then you will be prompted for insufficient VRAM.Thank you for your reply.——from Google Translate

**Comment by MythicalChu** [comment]
Try with Hyper Tile, it reduces the memory needed. Look around for optimizations, like, disabling hardware acceleration of the browser you used SD on; if on windows, disable aero and other effects. After going through these I'm almost never going out-of-memory again. Some googling should land you on the reddit topic with these tips

**Comment by MythicalChu** [comment]
Oh, have you tried Low rank ControlNet? The files are small so it saves you a lot of memory. I barely notice a change in quality and always use it instead of the bigger models

**Comment by DSN2002** [comment]
> Oh, have you tried Low rank ControlNet? The files are small so it saves you a lot of memory. I barely notice a change in quality and always use it instead of the bigger models

I'm using ControlNet with 128 rank and it works great. I will try Hyper Tile. Thank you

**Comment by jangirke** [comment]
Nobody who had a fix answered.
If you found one share it.
Others like me have that problem too.
Optimizations are not the solution.

**Comment by MythicalChu** [comment]
start Comfy with these flags: "--lowvram --fp16-unet --fp16-vae --fp16-text-enc" (read the main page if you're not sure how to do that)

Still with my rx580 8Gb I can use SDXL models, gen in 896x1152 or higher, while loading 2Gb controlNet and 2Gb+ Vision from IpAdapter, so, this should help you generate like you want. You may need to use Tiled Vae Decode. Try with normal decode and find out what's your limit, since it's much faster than tiled vae decode.

If you're still going out of memory after that... well, there's a hard limit to what the amount of Vram can do... Try a lighter workflow.

**Comment by jangirke** [comment]
Sorry but the problem is that it does not detect the VRAM I have. Just using lower precision doesn't help detecting the VRAM.
How can I set the amount of VRAM I have?
