### ISSUE TITLE
【confusion！】The relationship between the "denoise" and "inference steps" in Ksampler.

### ISSUE THREAD

**Issue by Muccul** [comfyanonymous/ComfyUI#1904]
If I set total steps to 20 and denoise to 0.6, I only need to run 12 steps in practice, but it actually runs for 20 steps, wasting 8 steps of time. Do I have a misunderstanding?

**Comment by ltdrdata** [comment]
I recommend that reading these articles.

https://blenderneko.github.io/ComfyUI-docs/Core%20Nodes/Sampling/KSampler%20Advanced/
https://comfyui.creamlab.net/guides/f_KSamplerAdvanced_denoise

**Comment by Muccul** [comment]
thanks!  KsamplerAdvanced node helped me solve problem.
