### ISSUE TITLE
Mosaic Node

### ISSUE THREAD

**Issue by abbail** [comfyanonymous/ComfyUI#191]
I was messing around with the built in nodes and the examples and made a Mosaic node for working with pixel art.  Is that something anyone would be interested in?  I thought about implementing the underlying torch interpolate methods as nodes but figured this was easier and more useful for what I was doing.  It works great with [PublicPrompts/All-In-One-Pixel-Model](https://huggingface.co/PublicPrompts/All-In-One-Pixel-Model):
![mosaic](https://user-images.githubusercontent.com/5521241/226492652-3c8d6df1-c0b2-4f5a-88a9-8fc4733c4e40.png)

**Comment by abbail** [comment]
It would be cool if there were an official node/extension library such as the one [Automatic1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions) has.  No doubt many people have great ideas, but as of now I don't see any good place to put them.

I did fork ComfyUI to work on my mosaic node and the broken keyboard shortcuts.  The mosaic node is [here](https://github.com/abbail/ComfyUI/blob/master/custom_nodes/mosiac_node.py) if anyone wants it.

**Comment by GrimblyGorn** [comment]
Ya I had actually thought about looking into that more, but haven't found the time yet. There should be some .json type method we could employ that allows random [repos](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) to be linked in to pull nodes from. Not sure how that would work with this gui specifically offhand though.

I may look into this more though, it really would be handy to have a plugin directory for modded nodes and node packs you could add, or anything else for that matter probably. Likely whatever they are doing for the other webui could be ported over to this, at least for this extension portion. Can't be that hard if they pulled it off :)

One idea that keeps coming to mind for me lately is an alternate way to display the nodes available. Something like the Ribbon bar in Grasshopper3D would be nice possibly.

Also, optional descriptions for the node at the bottom would be nice. Some secondary bubble attached to the node with the description for what it is, why that matters, how it's used, etc. Just something to remind people when they're complete stuck and brain-dead as to what they're even looking at maybe :)

Lol, I might go add some of these to my ongoing wish[list](https://github.com/comfyanonymous/ComfyUI/discussions/181#discussion-4984414) next.

In the meantime I grabbed your node. I'll check it out later, but thanks for sharing either way :)

**Comment by GrimblyGorn** [comment]
Nifty :)
![2023-03-21 17_51_28-ComfyUI](https://user-images.githubusercontent.com/61724196/226759460-a511f340-477b-4afa-93d8-1a555e6589d7.png)
