### ISSUE TITLE
The new version of ComfyUI cannot be extracted using 7zip or any other extraction software today

### ISSUE THREAD

**Issue by JunieLau** [comfyanonymous/ComfyUI#1913]
The new version of ComfyUI cannot be extracted using 7zip or any other extraction software.

**Comment by Derjyn** [comment]
Not a lot of info to go on there. Likely the issue is on your end; I was able to download codebase directly from GitHub and extract with 7zip and core Windows 10 *.zip functionality. Latest release, and standalone build also extracted without issue.

Try downloading again, you potentially ended up with a corrupt file. Otherwise, let's try and include more details to figure this out.

**Comment by CHollman82** [comment]
Yep, that's a you problem. Extracts fine here using both 7zip and windows 10 built-in zip support.

**Comment by ltdrdata** [comment]
Check you file size.

**Comment by InCrIpTiOn** [comment]
Same issue, windows 11, getting this 
![image](https://github.com/comfyanonymous/ComfyUI/assets/23437039/38d25e9a-1b21-4a4f-88c5-4ba159ab82da)

**Comment by InCrIpTiOn** [comment]
extracting with admin perms fixed it

**Comment by greatBigMassive** [comment]
To confirm the original fault here, I had the same problem.
I have Windows 11, latest 7-zip and downloaded comfy from https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#installing

Windows Extract would start to slow about 6% in.
7.Zip did the same.

The solution for me was to right-click on the .7z file then go to properties.
Near the bottom was a warning telling the file "came from another computer".
See the image I have included.  

I clicked the "Unblock" tick box and clicked "OK".
![Screenshot 2024-01-15 165024](https://github.com/comfyanonymous/ComfyUI/assets/6818250/b201dd37-ced5-49ae-ad8f-751cafd8d84e)

Tried to extract again and it worked fine.

**Comment by Derjyn** [comment]
This is going to be an issue for plenty of other compressed files and, files in general for users with various security setups, OS versions, etc.

I feel bad for developers/communities that get the short end of the stick when users run into this common but simple to fix "issue".

**Comment by greatBigMassive** [comment]
I do too,  and that's why nobody has blamed them for anything and why many just create comments that are designed to help reduce the support load for developers by providing possible solutions for other users to try before then leaving another comment that doesn't provide any useful information for them other.

Many other people will end up at this thread and many have used this thread to help them find a solution but never left a comment to say "Thanks".

The wonderful world of support - you only hear from customers when there's a problem but if you give them a solution they'll most often never bother to say thanks or leave anything positive when it's all running smoothly :)

**Comment by the-najjar** [comment]
Thank you @greatBigMassive you're our hero! took me 30 minutes of search to find a solution.

**Comment by AJK83** [comment]
Hi guys,

I have the same problem, but the solutions mentioned here didn't work for me.

Does anybody have another idea?

Many thanks in advance.

**Comment by harolds** [comment]
I tried to extract the files and it was extreemly slow. After [greatBigMassive](https://github.com/greatBigMassive) fix it worked as a charm :-)

**Comment by Fafa87** [comment]
Same happens on Windows 10. 
@greatBigMassive you are really the great one!

**Comment by thewesking** [comment]
> To confirm the original fault here, I had the same problem. I have Windows 11, latest 7-zip and downloaded comfy from https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#installing
> 
> * Windows Extract would start to slow as soon as it hit the long-named .pyc files
> * 7zip did the same.
> 
> The solution for me was to right-click on the .7z file then go to properties. Near the bottom was a warning telling me the file "came from another computer". See the image I have included.
> 
> I clicked the "Unblock" tick box and clicked "OK". ![Screenshot 2024-01-15 165024](https://private-user-images.githubusercontent.com/6818250/296819603-b201dd37-ced5-49ae-ad8f-751cafd8d84e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDM5MjUsIm5iZiI6MTcxMTkwMzYyNSwicGF0aCI6Ii82ODE4MjUwLzI5NjgxOTYwMy1iMjAxZGQzNy1jZWQ1LTQ5YWUtYWQ4Zi03NTFjYWZkOGQ4NGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzFUMTY0NzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZhOGQ2ODA4NDliMDI1NDExMTdiNWVkMWJjYzZhNjQ2ZWJmOGFjODk0Mjg1NzU2OTk4MDcxNjJiMzcwMGU5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZUw2_ekggOhvxOh0kfE7sdyng4_j8Uk-BfVP-wxC_-E)
> 
> Tried to extract again and it worked fine.

thank you soooo much!

**Comment by Marc2629** [comment]
Good old windows keeping us "safe". Thank you!

**Comment by LifeAcademyGames** [comment]
Takes 30 minutes:
Right click the file, at 7z choose "open archive"
Archive windows opens in 1 sec.
Drag and drop the folders and the 3 files to another map (use SSD).

**Comment by gordon123** [comment]
> To confirm the original fault here, I had the same problem. I have Windows 11, latest 7-zip and downloaded comfy from https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#installing
> 
> * Windows Extract would start to slow as soon as it hit the long-named .pyc files
> * 7zip did the same.
> 
> The solution for me was to right-click on the .7z file then go to properties. Near the bottom was a warning telling me the file "came from another computer". See the image I have included.
> 
> I clicked the "Unblock" tick box and clicked "OK". ![Screenshot 2024-01-15 165024](https://private-user-images.githubusercontent.com/6818250/296819603-b201dd37-ced5-49ae-ad8f-751cafd8d84e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDkwOTksIm5iZiI6MTcyNTY0ODc5OSwicGF0aCI6Ii82ODE4MjUwLzI5NjgxOTYwMy1iMjAxZGQzNy1jZWQ1LTQ5YWUtYWQ4Zi03NTFjYWZkOGQ4NGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMTg1MzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU4ZGM2ZDc5MzRlMTg2ZDU3NWI4MzM3MWE2ZDgwY2U1NzBiNTI2MDY2Njg0ZmY3Mjg3N2I0M2YxZDJjYmU1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n2776ZqvvdJPh7ZhsavR-UD0eVfWiYPvR-Rd_NgNIq0)
> 
> Tried to extract again and it worked fine.

Thanks!! it took me nearly half hour to extract but when did what you said it took 3 min

**Comment by jon-bondy** [comment]
> To confirm the original fault here, I had the same problem. I have Windows 11, latest 7-zip and downloaded comfy from https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#installing
> 
>     * Windows Extract would start to slow as soon as it hit the long-named .pyc files
> 
>     * 7zip did the same.
> 
> 
> The solution for me was to right-click on the .7z file then go to properties. Near the bottom was a warning telling me the file "came from another computer". See the image I have included.
> 
> I clicked the "Unblock" tick box and clicked "OK". ![Screenshot 2024-01-15 165024](https://private-user-images.githubusercontent.com/6818250/296819603-b201dd37-ced5-49ae-ad8f-751cafd8d84e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Mzg0NjAsIm5iZiI6MTczMDkzODE2MCwicGF0aCI6Ii82ODE4MjUwLzI5NjgxOTYwMy1iMjAxZGQzNy1jZWQ1LTQ5YWUtYWQ4Zi03NTFjYWZkOGQ4NGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMDAwOTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjM2YTllYWIwNzU4MjE3Mjg2ZjRhNDk1YWI5NTQyNTAxNDMwYjRkOGIzNzI4YTQ5MDMzOGIyMjkzZTMwNDgyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.THDZQ_kEODh0W_FfcJoj4nz1U7X_3J35JnV-Sdx6VhY)
> 
> Tried to extract again and it worked fine.

Such a helpful comment!  Thank you!  Worked for me, too
