### ISSUE TITLE
Checkpoint doesnt fully cache

### ISSUE THREAD

**Issue by ppbrown** [comfyanonymous/ComfyUI#1914]
One of the things I appreciate about ComfyUI is that when you rerun a workflow, it caches stufff that is already in place/rendered.
So I was surprised to find that checkpoint doesnt cache, in the sense that if you have TWO checkpoint loaders set to the same value manually,  when you hit the second "load checkpoint", it still goes through the hassle.. even if its the same checkpoint that is already loaded.

This may seem obscure and stupid; howevr, its important if you want to easily cut-n-paste full small clumps of nodes, without having to re-link-up things to the master checkpoint.

IMO, while I just experimented and discovered that SHIFT-control-v preserves links to things outside the past (which makes this a little less useful, if you know about it), I think this would still be a nice optimization in principle.

**Comment by ltdrdata** [comment]
Actually, this is a somewhat complex issue. In the first place, it's relatively straightforward to implement the sharing of the same checkpoint model file when loaded by several different loaders. However, this is not always the definitive solution.
(FYI, In the case of efficient nodes, they use an internal cache to enable model sharing.)

Efficiently sharing the model is evident when it's used in its vanilla state, but it becomes particularly problematic when the same checkpoint is used with different model patches like lora/freeu/DT/... Using two separately loaded models doesn't result in any performance drop, but when the same checkpoint is used with different model patches, the switch cost for the model becomes quite heavy.
