### ISSUE TITLE
Error Using Animatediff

### ISSUE THREAD

**Issue by ShashwatDubey99** [comfyanonymous/ComfyUI#1915]
[AnimateDiffEvo] - INFO - Loading motion module mmsd15v2.ckpt
[AnimateDiffEvo] - INFO - Using fp16, converting motion module to fp16
[AnimateDiffEvo] - INFO - Regular AnimateDiff activated - latents passed in (3) less or equal to context_length None.
[AnimateDiffEvo] - INFO - Injecting motion module mmsd15v2.ckpt version v2.
Requested to load BaseModel
Loading 1 new model
  0% 0/20 [00:00<?, ?it/s]
[AnimateDiffEvo] - INFO - Ejecting motion module mmsd15v2.ckpt version v2.
[AnimateDiffEvo] - INFO - Cleaning motion module from unet.
[AnimateDiffEvo] - INFO - Removing motion module mmsd15v2.ckpt from cache
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/content/ShiroUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/ShiroUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/ShiroUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/ShiroUI/nodes.py", line 1236, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/content/ShiroUI/nodes.py", line 1206, in common_ksampler
    samples = shiro.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/content/ShiroUI/custom_nodes/animate/animatediff/sampling.py", line 166, in animatediff_sample
    return wrap_function_to_inject_xformers_bug_info(orig_shiro_sample)(model, *args, **kwargs)
  File "/content/ShiroUI/custom_nodes/animate/animatediff/model_utils.py", line 185, in wrapped_function
    return function_to_wrap(*args, **kwargs)
  File "/content/ShiroUI/shiro/sample.py", line 97, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/ShiroUI/shiro/samplers.py", line 785, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/ShiroUI/shiro/samplers.py", line 690, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/content/ShiroUI/shiro/samplers.py", line 630, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **extra_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/ShiroUI/shiro/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/ShiroUI/shiro/samplers.py", line 323, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options, seed=seed)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/ShiroUI/shiro/k_diffusion/external.py", line 125, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/content/ShiroUI/shiro/k_diffusion/external.py", line 151, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/content/ShiroUI/shiro/samplers.py", line 311, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options, seed=seed)
TypeError: sliding_sampling_function() got multiple values for argument 'model_options'

Prompt executed in 2.80 seconds
got prompt
[AnimateDiffEvo] - INFO - Loading motion module mmsd15v2.ckpt
[AnimateDiffEvo] - INFO - Using fp16, converting motion module to fp16
[AnimateDiffEvo] - INFO - Regular AnimateDiff activated - latents passed in (3) less or equal to context_length None.
[AnimateDiffEvo] - INFO - Injecting motion module mmsd15v2.ckpt version v2.
Requested to load BaseModel
Loading 1 new model
  0% 0/20 [00:00<?, ?it/s]/content/ShiroUI/shiro/k_diffusion/sampling.py:475: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return dpm_solver.dpm_solver_fast(x, dpm_solver.t(torch.tensor(sigma_max)), dpm_solver.t(torch.tensor(sigma_min)), n, eta, s_noise, noise_sampler)
  0% 0/20 [00:00<?, ?it/s]
[AnimateDiffEvo] - INFO - Ejecting motion module mmsd15v2.ckpt version v2.
[AnimateDiffEvo] - INFO - Cleaning motion module from unet.
[AnimateDiffEvo] - INFO - Removing motion module mmsd15v2.ckpt from cache
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/content/ShiroUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/ShiroUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/ShiroUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/ShiroUI/nodes.py", line 1236, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/content/ShiroUI/nodes.py", line 1206, in common_ksampler
    samples = shiro.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/content/ShiroUI/custom_nodes/animate/animatediff/sampling.py", line 166, in animatediff_sample
    return wrap_function_to_inject_xformers_bug_info(orig_shiro_sample)(model, *args, **kwargs)
  File "/content/ShiroUI/custom_nodes/animate/animatediff/model_utils.py", line 185, in wrapped_function
    return function_to_wrap(*args, **kwargs)
  File "/content/ShiroUI/shiro/sample.py", line 97, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/ShiroUI/shiro/samplers.py", line 785, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/ShiroUI/shiro/samplers.py", line 690, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/content/ShiroUI/shiro/samplers.py", line 626, in sample
    samples = k_diffusion_sampling.sample_dpm_fast(model_k, noise, sigma_min, sigmas[0], total_steps, extra_args=extra_args, callback=k_callback, disable=disable_pbar)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/ShiroUI/shiro/k_diffusion/sampling.py", line 475, in sample_dpm_fast
    return dpm_solver.dpm_solver_fast(x, dpm_solver.t(torch.tensor(sigma_max)), dpm_solver.t(torch.tensor(sigma_min)), n, eta, s_noise, noise_sampler)
  File "/content/ShiroUI/shiro/k_diffusion/sampling.py", line 396, in dpm_solver_fast
    eps, eps_cache = self.eps(eps_cache, 'eps', x, t)
  File "/content/ShiroUI/shiro/k_diffusion/sampling.py", line 338, in eps
    eps = (x - self.model(x, sigma, *args, **self.extra_args, **kwargs)) / self.sigma(t)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/ShiroUI/shiro/samplers.py", line 323, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options, seed=seed)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/ShiroUI/shiro/k_diffusion/external.py", line 125, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/content/ShiroUI/shiro/k_diffusion/external.py", line 151, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/content/ShiroUI/shiro/samplers.py", line 311, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options, seed=seed)
TypeError: sliding_sampling_function() got multiple values for argument 'model_options'

Prompt executed in 3.31 seconds

**Comment by GeekyGhost** [comment]
Yeah, I've been running into issues with AnimateDiff after updating comfyUI. Going to roll it back to an earlier release for now until they get it sorted.

**Comment by GeekyGhost** [comment]
Rolling back to c837a17 seems to have fixed it so AnimateDiff works, but it breaks AnimateDiff Evolved.

**Comment by GeekyGhost** [comment]
> [AnimateDiffEvo] - INFO - Loading motion module mmsd15v2.ckpt [AnimateDiffEvo] - INFO - Using fp16, converting motion module to fp16 [AnimateDiffEvo] - INFO - Regular AnimateDiff activated - latents passed in (3) less or equal to context_length None. [AnimateDiffEvo] - INFO - Injecting motion module mmsd15v2.ckpt version v2. Requested to load BaseModel Loading 1 new model 0% 0/20 [00:00<?, ?it/s] [AnimateDiffEvo] - INFO - Ejecting motion module mmsd15v2.ckpt version v2. [AnimateDiffEvo] - INFO - Cleaning motion module from unet. [AnimateDiffEvo] - INFO - Removing motion module mmsd15v2.ckpt from cache ERROR:root:!!! Exception during processing !!! ERROR:root:Traceback (most recent call last): File "/content/ShiroUI/execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "/content/ShiroUI/execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "/content/ShiroUI/execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "/content/ShiroUI/nodes.py", line 1236, in sample return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise) File "/content/ShiroUI/nodes.py", line 1206, in common_ksampler samples = shiro.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, File "/content/ShiroUI/custom_nodes/animate/animatediff/sampling.py", line 166, in animatediff_sample return wrap_function_to_inject_xformers_bug_info(orig_shiro_sample)(model, *args, **kwargs) File "/content/ShiroUI/custom_nodes/animate/animatediff/model_utils.py", line 185, in wrapped_function return function_to_wrap(*args, **kwargs) File "/content/ShiroUI/shiro/sample.py", line 97, in sample samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed) File "/content/ShiroUI/shiro/samplers.py", line 785, in sample return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed) File "/content/ShiroUI/shiro/samplers.py", line 690, in sample samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar) File "/content/ShiroUI/shiro/samplers.py", line 630, in sample samples = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **extra_options) File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/content/ShiroUI/shiro/k_diffusion/sampling.py", line 137, in sample_euler denoised = model(x, sigma_hat * s_in, **extra_args) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/content/ShiroUI/shiro/samplers.py", line 323, in forward out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options, seed=seed) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/content/ShiroUI/shiro/k_diffusion/external.py", line 125, in forward eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs) File "/content/ShiroUI/shiro/k_diffusion/external.py", line 151, in get_eps return self.inner_model.apply_model(*args, **kwargs) File "/content/ShiroUI/shiro/samplers.py", line 311, in apply_model out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options, seed=seed) TypeError: sliding_sampling_function() got multiple values for argument 'model_options'
> 
> Prompt executed in 2.80 seconds got prompt [AnimateDiffEvo] - INFO - Loading motion module mmsd15v2.ckpt [AnimateDiffEvo] - INFO - Using fp16, converting motion module to fp16 [AnimateDiffEvo] - INFO - Regular AnimateDiff activated - latents passed in (3) less or equal to context_length None. [AnimateDiffEvo] - INFO - Injecting motion module mmsd15v2.ckpt version v2. Requested to load BaseModel Loading 1 new model 0% 0/20 [00:00<?, ?it/s]/content/ShiroUI/shiro/k_diffusion/sampling.py:475: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor). return dpm_solver.dpm_solver_fast(x, dpm_solver.t(torch.tensor(sigma_max)), dpm_solver.t(torch.tensor(sigma_min)), n, eta, s_noise, noise_sampler) 0% 0/20 [00:00<?, ?it/s] [AnimateDiffEvo] - INFO - Ejecting motion module mmsd15v2.ckpt version v2. [AnimateDiffEvo] - INFO - Cleaning motion module from unet. [AnimateDiffEvo] - INFO - Removing motion module mmsd15v2.ckpt from cache ERROR:root:!!! Exception during processing !!! ERROR:root:Traceback (most recent call last): File "/content/ShiroUI/execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "/content/ShiroUI/execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "/content/ShiroUI/execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "/content/ShiroUI/nodes.py", line 1236, in sample return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise) File "/content/ShiroUI/nodes.py", line 1206, in common_ksampler samples = shiro.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, File "/content/ShiroUI/custom_nodes/animate/animatediff/sampling.py", line 166, in animatediff_sample return wrap_function_to_inject_xformers_bug_info(orig_shiro_sample)(model, *args, **kwargs) File "/content/ShiroUI/custom_nodes/animate/animatediff/model_utils.py", line 185, in wrapped_function return function_to_wrap(*args, **kwargs) File "/content/ShiroUI/shiro/sample.py", line 97, in sample samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed) File "/content/ShiroUI/shiro/samplers.py", line 785, in sample return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed) File "/content/ShiroUI/shiro/samplers.py", line 690, in sample samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar) File "/content/ShiroUI/shiro/samplers.py", line 626, in sample samples = k_diffusion_sampling.sample_dpm_fast(model_k, noise, sigma_min, sigmas[0], total_steps, extra_args=extra_args, callback=k_callback, disable=disable_pbar) File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/content/ShiroUI/shiro/k_diffusion/sampling.py", line 475, in sample_dpm_fast return dpm_solver.dpm_solver_fast(x, dpm_solver.t(torch.tensor(sigma_max)), dpm_solver.t(torch.tensor(sigma_min)), n, eta, s_noise, noise_sampler) File "/content/ShiroUI/shiro/k_diffusion/sampling.py", line 396, in dpm_solver_fast eps, eps_cache = self.eps(eps_cache, 'eps', x, t) File "/content/ShiroUI/shiro/k_diffusion/sampling.py", line 338, in eps eps = (x - self.model(x, sigma, *args, **self.extra_args, **kwargs)) / self.sigma(t) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/content/ShiroUI/shiro/samplers.py", line 323, in forward out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options, seed=seed) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/content/ShiroUI/shiro/k_diffusion/external.py", line 125, in forward eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs) File "/content/ShiroUI/shiro/k_diffusion/external.py", line 151, in get_eps return self.inner_model.apply_model(*args, **kwargs) File "/content/ShiroUI/shiro/samplers.py", line 311, in apply_model out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options, seed=seed) TypeError: sliding_sampling_function() got multiple values for argument 'model_options'
> 
> Prompt executed in 3.31 seconds

in the meantime if you aren't familiar with rolling back, I've made a temp fork of the old repository for comfyUI that works, if you want to use the checkpoint loader with noise from AnimateDiff evolved you'll have to roll it back as well. https://github.com/GeekyGhost/ComfyUI-c837a17.git

**Comment by ShashwatDubey99** [comment]
Hey, if I will update now comfyui, it will fix it or not beacase older version of comfy does not support advanced control net and when I used new version of comfy animatediff was breaked how can i fix it

**Comment by ShashwatDubey99** [comment]
Can any one tell the version of both advanced control net and Comfy which will be working
