### ISSUE TITLE
How to run multiple simultaneous generations in comfy?

### ISSUE THREAD

**Issue by D1maD1m0nd** [comfyanonymous/ComfyUI#1927]
Hi, I have a server that takes client requests and starts generating images based on my client side configuration and settings.
But I can only run one generation at a time, all the others queue up
How can I execute them in parallel?
I think for now I’ll run several copies of the program and switch clients between them (haven’t checked yet)

**Comment by NeedsMoar** [comment]
Set "batch" in the latents node you're feeding into your ksampler to >1 and it'll generate in parallel.  Your image output / preview node will have a little icon to view more the next image from the batch.

AnimatedDiff requires generating the animation frames with a batched latent like this for whatever reason.  I think some of the other animation nodes have their own sequential frame queue to avoid the obvious problem with this.   I was able to run 32 720x480 generations in parallel at roughly 35it/s overall (1.something it/s displayed * 32), and feed those into a 2x latent upscale and a 2nd ksampler (which was something like 6s/it but only 12 steps so not terrible overall)  and it only hit a max of 18GB of vram which surprised me.

**Comment by NeedsMoar** [comment]
If you're serving to other people than yourself the batches can't work unless practically all settings are the same because most everything needs to change the model weights in some way so you might not be able to do this.

**Comment by D1maD1m0nd** [comment]
I only change the image and prompt, Lora args

but I roughly understand what you mean
you will have to think about several instances of comfyui
Maybe someone else in this thread can give me some ideas
