### ISSUE TITLE
Feature Request - Wireless "Teleporter" Nodes

### ISSUE THREAD

**Issue by CHollman82** [comfyanonymous/ComfyUI#1930]
I think it would de-clutter a lot of people's workflows to add a simple pair of nodes, a "sender" and a "receiver", that let you pass a value around wirelessly. The sender would accept any type of input as well as a variable name and it would save the input value to that variable. The receiver would require you to enter a previously used variable name and then it would output that value. Of course you could have a one-to-many relationship where you store the variable once and then you can use it repeatedly in many different places.

Sure you can argue it might make things confusing not being able to see the connections, but for some BASIC things I think it would be fine, like the seed value. I generate a seed once and use it throughout and I have about a dozen different lines coming from that one node going to all different points on my flowchart, it's too much.

Yes I know about pipelines, in fact I made my own custom set of pipeline nodes... but you still have to line everything up so that wires aren't criss-crossing over everything. The time I spend making things look neat and tidy is time taken away from what I actually want to be doing.

If it's too difficult or not feasible to have a single pair of nodes that handle everything you could just do it for primitive types only. It would still be very valuable to have a small set of these that handled ints, floats, and strings, for example.

**Comment by mizukarada** [comment]
[cg-use-everywhere](https://github.com/chrisgoringe/cg-use-everywhere)

**Comment by CHollman82** [comment]
Thank you that is pretty close to what I was looking for, it's just missing the receiver nodes. Having everything that is capable of receiving a signal type automatically receive that type is a bit limiting, and I know there is the node that lets you enter a REGEX to match with the title of a node but still if you use two of the same nodes they will have the same title (right? or can you change that? I have to experiment with that I guess).

Either way thank you for showing me that, either it will do what I want or I should be able to learn from looking at it's implementation and make something that works exactly how I want.
