### ISSUE TITLE
WISH: Force Custom-Nodes to Re-Evaluate

### ISSUE THREAD

**Issue by BaronFalke** [comfyanonymous/ComfyUI#1937]
During some experiments creating my own nodes, I figured out that my "random.rand()" is only executed once.
After first execution, the value stays the same and printf does not deliver any new information.

Example Node:
![image](https://github.com/comfyanonymous/ComfyUI/assets/6080245/c5ddc80b-2802-4343-9cd4-1fba808bd429)

After some investigation I figured out, that a node is only evaluated, if it's values have changed.
So if I change my value in the node, then the "FUNCTION" is executed again.
![image](https://github.com/comfyanonymous/ComfyUI/assets/6080245/fc9286e4-36e7-454d-9211-e58bc7b98a6c)

The only workaround at moment is to add a "seed" attribute as "required".
The seed forces the node to change it's value so it is evaluated again.

It would be cool if you could add a new property in the custom node which tells the comfyui-process to execute/evaluate a node again.
Maybe something like this:
![image](https://github.com/comfyanonymous/ComfyUI/assets/6080245/a4ae1ec6-59a1-49ab-b42b-289094cced6b)

Or make it possible to use "seed" as a "hidden" attribute so it will be evaluated all the time but not visible in the node.

**Comment by ltdrdata** [comment]
You can use this trick.

```
    def IS_CHANGED(self, **kwargs):
        return float('nan')
```

**Comment by BaronFalke** [comment]
Hi, thanks for the hint.
This works fine.
Would be a good candidate for the documentation. ;D
