### ISSUE TITLE
[bug] inpaint mode 

### ISSUE THREAD

**Issue by starinskycc** [comfyanonymous/ComfyUI#1980]
![image](https://github.com/comfyanonymous/ComfyUI/assets/6244330/8f4fc6c5-5bad-4a07-bacf-268538652d9f)
face destroied,but in sdwebui ,it is ok.
![image](https://github.com/comfyanonymous/ComfyUI/assets/6244330/46f74b68-f9ed-43e7-b1dc-f10003f7593d)

controlnet inpaint is the same problem

**Comment by jn-jairo** [comment]
You are missing the ImageCompositeMasked to achieve the same process of A1111, the A1111 pastes the masked area of the generated image above the original image using the mask, you do it in ComfyUI using the ImageCompositeMasked.
