### ISSUE TITLE
SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)

### ISSUE THREAD

**Issue by ClayShoaf** [comfyanonymous/ComfyUI#1982]
Surprised I haven't seen this issue here before. I am getting this a lot when trying to use other people's workflows.

Console output:
```
got prompt
Error handling request
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/threeten/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/user/anaconda3/envs/threeten/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/user/anaconda3/envs/threeten/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/user/github/ComfyUI/server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "/home/user/github/ComfyUI/server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "/home/user/github/ComfyUI/execution.py", line 598, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'class_type'
```

**Comment by comfyanonymous** [comment]
That means you don't have a custom node that they used.

**Comment by jn-jairo** [comment]
@comfyanonymous It is missing a backend validation for missing nodes, I got it now when I remove a custom node, restarted the server but didn't refresh the page on the browser, so I loaded a workflow, it loaded without errors, but when I queue the prompt I got that error, but if I refresh the page the error changes to the missing nodes message.

**Comment by ClayShoaf** [comment]
Man, I could have sworn I tried that. You're right. I restarted the server, closed and opened a new tab, and it worked. Side question, is "Ctrl+C" the best way to restart the server?

**Comment by Torcelllo** [comment]
>Is "Ctrl+C" the best way to restart the server?

It certainly CLOSES the Server!
You must then manually re-start.

**Comment by Rpk247** [comment]
SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)

Followed solutions didnt work for me... please guide me ...
also i can't install ipadapterapply,

**Comment by jehowit** [comment]
> SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)
> 
> Followed solutions didnt work for me... please guide me ... also i can't install ipadapterapply,

same here... did you find a fix?

**Comment by originalpaul** [comment]
Same issue, JSON is clean, everything up to date including custom nodes and comfyui-manager, still doesn't work.

**Comment by stf6** [comment]
same here, I'm trying to run this workflow: [here](https://civitai.com/models/313594/jboogx-and-machine-learner-animatelcm-workflow-vid2vid-controlnet-ipadapter-highresfix-reactor-face-swap)
firstly when i try loading it, i get this popup 

_When loading the graph, the following node types were not found:
Text box
Nodes that have failed to load will show as red on the graph._

no nodes show up in install missing nodes section, everything is up-to-date.

complete error message when i try running it anyway: 
_got prompt
Error handling request
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/home/studio-lab-user/ComfyUI/server.py", line 41, in cache_control
    response: web.Response = await handler(request)
  File "/home/studio-lab-user/ComfyUI/server.py", line 53, in cors_middleware
    response = await handler(request)
  File "/home/studio-lab-user/ComfyUI/server.py", line 468, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "/home/studio-lab-user/ComfyUI/execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'class_type'_

and this popup in the ui:

_SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)_

**Comment by mzaprudin** [comment]
> same here, I'm trying to run this workflow: [here](https://civitai.com/models/313594/jboogx-and-machine-learner-animatelcm-workflow-vid2vid-controlnet-ipadapter-highresfix-reactor-face-swap) firstly when i try loading it, i get this popup
> 
> _When loading the graph, the following node types were not found: Text box Nodes that have failed to load will show as red on the graph._
> 
> no nodes show up in install missing nodes section, everything is up-to-date.
> 
> complete error message when i try running it anyway: _got prompt Error handling request Traceback (most recent call last): File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request resp = await request_handler(request) File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle resp = await handler(request) File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/home/studio-lab-user/ComfyUI/server.py", line 41, in cache_control response: web.Response = await handler(request) File "/home/studio-lab-user/ComfyUI/server.py", line 53, in cors_middleware response = await handler(request) File "/home/studio-lab-user/ComfyUI/server.py", line 468, in post_prompt valid = execution.validate_prompt(prompt) File "/home/studio-lab-user/ComfyUI/execution.py", line 625, in validate_prompt class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']] KeyError: 'class_type'_
> 
> and this popup in the ui:
> 
> _SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)_

I have the same issue issue with [My Steerable Motion workflow](https://civitai.com/models/230188/my-steerable-motion-workflow)

**Comment by ltdrdata** [comment]
> > same here, I'm trying to run this workflow: [here](https://civitai.com/models/313594/jboogx-and-machine-learner-animatelcm-workflow-vid2vid-controlnet-ipadapter-highresfix-reactor-face-swap) firstly when i try loading it, i get this popup
> > _When loading the graph, the following node types were not found: Text box Nodes that have failed to load will show as red on the graph._
> > no nodes show up in install missing nodes section, everything is up-to-date.
> > complete error message when i try running it anyway: _got prompt Error handling request Traceback (most recent call last): File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request resp = await request_handler(request) File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle resp = await handler(request) File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/home/studio-lab-user/ComfyUI/server.py", line 41, in cache_control response: web.Response = await handler(request) File "/home/studio-lab-user/ComfyUI/server.py", line 53, in cors_middleware response = await handler(request) File "/home/studio-lab-user/ComfyUI/server.py", line 468, in post_prompt valid = execution.validate_prompt(prompt) File "/home/studio-lab-user/ComfyUI/execution.py", line 625, in validate_prompt class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']] KeyError: 'class_type'_
> > and this popup in the ui:
> > _SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)_
> 
> I have the same issue issue with [My Steerable Motion workflow](https://civitai.com/models/230188/my-steerable-motion-workflow)

You have to resolve red nodes first, before execute workflow.

**Comment by DragonQuix** [comment]
Same problem.  It doesn't matter what workflows. Every workflows are not working.

**Comment by ltdrdata** [comment]
> Same problem. It doesn't matter what workflows. Every workflows are not working.

Please disable all custom node and try default workflow.

**Comment by razvanab** [comment]
I did that too, and I move out extensions in bunches until I manage to find the extensions that are problematic.

ComfyUI-Dev-Utils
comfyui-profiler
comfyui-resharpen
ComfyUI_ProfilerX
comfyui-floodgate

**Comment by ZephyrusZealz** [comment]
I had the same issue and outta nowhere none of the workflows, including the default workflows in ComfyUI wasn't working. I remembered installing the below 3 custom nodes early today and then it all broke. 
Removed them all from the 'ComfyUI\custom_nodes' path and restarted server. It's all working fine now. From @razvanab note, the issue seems to be with "comfyui-resharpen" node.

DZ-FaceDetailer
comfyui-resharpen
ComfyUI-nunchaku

**Comment by baiye1988-C** [comment]
> I did that too, and I move out extensions in bunches until I manage to find the extensions that are problematic.
> 
> ComfyUI-Dev-Utils comfyui-profiler comfyui-resharpen ComfyUI_ProfilerX comfyui-floodgate

thanks, that  useful!

**Comment by kokomo** [comment]
In my case, the error was caused by the comfyui-diffusion-cg custom node.

**Comment by ltdrdata** [comment]
> In my case, the error was caused by the comfyui-diffusion-cg custom node.

The nodepack is fixed recently.
comfyui-resharpen nodepack as well.

**Comment by jqy-yo** [comment]
After updating to the latest version of ComfyUI 650838f, I can't even run the default workflow.

**Comment by ltdrdata** [comment]
> After updating to the latest version of ComfyUI 650838f, I can't even run the default workflow.

You need to address those custom nodes.

**Comment by jqy-yo** [comment]
> > After updating to the latest version of ComfyUI [650838f](https://github.com/comfyanonymous/ComfyUI/commit/650838fd6fcb24e66bf82b3c75383f35433d7b8a), I can't even run the default workflow.更新到最新版本的 ComfyUI 后，我甚至无法运行默认工作流程。
> 
> You need to address those custom nodes.您需要解决这些自定义节点。

After updating all custom nodes to the latest version, the issue was resolved.

**Comment by ZHANG445566** [comment]
Thank you everyone for sharing. My problem has been solved. The situation I encountered was that after updating the core of ComfyUI to the latest version, the same error message appeared. Even when I rolled back ComfyUI to a previous version, it didn't work. Then, I updated all the plugins to their latest versions, and it worked. It should be that the authors of all plugins have updated their plugins according to the new version of ComfyUI, allowing the workflow to run smoothly and generate images.

谢谢所有人的分享，我的问题也解决了，我遇到的情况就是更新了comfyui的内核最新版本，所以出现同样的错误提示，包括我把comfyui的版本退回到以前的版本都不行，然后把插件更新成最新版本就可以，应该是所有插件的作者根据新版本更新插件就正常的跑通工作流出图了

**Comment by P3laton3** [comment]
for those nodes there isn't a mantained repository, shouldn't be deprecated and replaced with something else?

**Comment by razvanab** [comment]
I think a better idea will be for those extensions older than half a year, there should be a warning saying that they might break stuff for you, comfy installation.

**Comment by P3laton3** [comment]
yup, developers should keep upto date some of the most important workflows or put up a warning sign

**Comment by chadwickmoorechadwick-a11y** [comment]
Can someone help me? I have the same problem and I don't know what to do anymore. Here is the workflow I'm using.

[WanVace_WillianIA.json](https://github.com/user-attachments/files/21609618/WanVace_WillianIA.json)

**Comment by jqy-yo** [comment]
> Can someone help me? I have the same problem and I don't know what to do anymore. Here is the workflow I'm using.有人能帮我吗？我也有同样的问题，不知道该怎么办了。这是我正在使用的工作流程。
> 
> [WanVace_WillianIA.json](https://github.com/user-attachments/files/21609618/WanVace_WillianIA.json)

Remove your comfyui-diffusion-cg

**Comment by chadwickmoorechadwick-a11y** [comment]
> > Can someone help me? I have the same problem and I don't know what to do anymore. Here is the workflow I'm using.有人能帮我吗？我也有同样的问题，不知道该怎么办了。这是我正在使用的工作流程。
> > [WanVace_WillianIA.json](https://github.com/user-attachments/files/21609618/WanVace_WillianIA.json)
> 
> Remove your comfyui-diffusion-cg

I'm sorry, but I'm new here. Where can I find this? If you can take a screenshot

**Comment by jqy-yo** [comment]
> > > Can someone help me? I have the same problem and I don't know what to do anymore. Here is the workflow I'm using.有人能帮我吗？我也有同样的问题，不知道该怎么办了。这是我正在使用的工作流程。有人可以帮助我吗？我有同样的问题，我不知道该怎么办了。这是我正在使用的工作流程。有人能帮我吗？我也有同样的问题，不知道该怎么办。这是我正在使用的工作流程。
> > > [WanVace_WillianIA.json](https://github.com/user-attachments/files/21609618/WanVace_WillianIA.json)
> > 
> > 
> > Remove your comfyui-diffusion-cg删除你的 comfyui-diffusion-cg
> 
> I'm sorry, but I'm new here. Where can I find this? If you can take a screenshot抱歉，我是新来的。我在哪里可以找到这个？如果你能截图的话

Translate to English: "Search in your custom_nodes"

**Comment by aiaiaikkk** [comment]
I modified one file:

  /root/ComfyUI/server.py

  Changes made:

  1. Line 9: Added direct import
  from execution import validate_prompt
  2. Line 693: Changed function call
    - Before: valid = await execution.validate_prompt(prompt_id, prompt, partial_execution_targets)
    - After: valid = await validate_prompt(prompt_id, prompt, partial_execution_targets)
