### ISSUE TITLE
[Feature request] Group cloning

### ISSUE THREAD

**Issue by vitacon** [comfyanonymous/ComfyUI#1985]
I was surprised I did not find any option how to clone a whole group.
I had to select all nodes in the original group, clone them, create a new group and place the cloned nodes into it.
UI could save a few clicks for us. =)

**Comment by kenic123** [comment]
I also need this ,but I can't find

**Comment by sandrosem** [comment]
good idea!

**Comment by ltdrdata** [comment]
Please post any requests related to the front end here.
https://github.com/Comfy-Org/ComfyUI_frontend/issues
