### ISSUE TITLE
Can someone clearly explain how I use new kohya hires fix option to remove doubles?

### ISSUE THREAD

**Issue by brentjohnston** [comfyanonymous/ComfyUI#1994]
Edit: Ahh nm, doesn't work with 1.5 models yet.

**Comment by brentjohnston** [comment]
I found it under "for_testing" menu, now I just need to figure out where to place it.

**Comment by brentjohnston** [comment]
Nerdy rodent video covering it here https://www.youtube.com/watch?v=riLmjBlywcg

**Comment by NeedsMoar** [comment]
Youtube videos aren't really useful to many but thanks for closing your bug (nobody does, there have been 100 since last week)  and mentioning that it doesn't work with 1.5, I was wondering why it was so broken at resolutions I could normally generate at without intermediates (if desired).
