### ISSUE TITLE
AnimateDiff - local variable 'orig_maximum_batch_area' referenced before assignment

### ISSUE THREAD

**Issue by Mindspherical** [comfyanonymous/ComfyUI#1997]
This seems like a new issue impacting all of my old workflows. They stopped working since the most recent update.

Notably this is with AnimateDiff jobs.

Any ideas? Thanks!

<img width="646" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/117719106/f715a7e7-4081-41ed-9d49-fce661e46131">

**Comment by Mindspherical** [comment]
Pulled the latest update and this was fixed.

**Comment by makeoo1** [comment]
i got the same problem since i updated just few hours ago. Never happened before the update
