### ISSUE TITLE
ConditioningSetArea - areas must be dividable by 64

### ISSUE THREAD

**Issue by kutny** [comfyanonymous/ComfyUI#2]
Hi,

first thanks a lot for your work! The visual form of the pipeline helped me a lot to better understand some basic concepts of SD!

**My challenge:**
I would like to "inpaint" all the 5 windows in the following room using image2image or depth2image. I hoped that such approach would help SD to render the windows in a correct size and position - currently, the model often forgets them or make them much bigger

![](https://user-images.githubusercontent.com/729373/215809515-04571b80-a5b3-4463-970a-bab4e75b5a6e.png) .

The problem is that I cannot create a small enough ConditioningSetArea (smaller than 64x64 or just at any size which is not dividable by 64).

Do you think that there is some solution to that? Standard inpainting uses a mask image where the mask can have any shape. Can such mask also be used in your approach somehow?

Thanks

**Comment by comfyanonymous** [comment]
Both Conditioning masks and non multiples of 64 for ConditioningSetArea are implemented now.
