### ISSUE TITLE
Feature request: Load and run graphs from commandline

### ISSUE THREAD

**Issue by ChairGraveyard** [comfyanonymous/ComfyUI#20]
I'd like to be able to design graphs then run them from the commandline for automation, would this be possible? Or is already there perhaps?

**Comment by comfyanonymous** [comment]
Here's a basic example how to do that:

https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py

**Comment by ChairGraveyard** [comment]
Legend! I'll resolve the issue. Thank you!

**Comment by paulo-coronado** [comment]
@comfyanonymous @ChairGraveyard I am trying to run [basic_api_example.py](https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py), but I am getting 400 (Bad Request) error. I think the request data is not properly set... am I missing something? 🤔

**Comment by ChairGraveyard** [comment]
I haven't actually tried this yet
