### ISSUE TITLE
Server Startup in a loop

### ISSUE THREAD

**Issue by Piscabo** [comfyanonymous/ComfyUI#2003]
After the current update, server startup in in a loop? It keep installing and installing models... does not start the server.
** ComfyUI start up time: 2023-11-19 19:13:15.802594

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

Install: pip packages
 Requirement already satisfied: segment-anything in a:\ai_files\stable-diffusion-webui\venv\lib\site-packages (1.0)
[!] DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
 Requirement already satisfied: scikit-image in a:\ai_files\stable-diffusion-webui\venv\lib\site-packages (0.20.0)
 Requirement already satisfied: numpy>=1.21.1 in a:\ai_files\stable-diffusion-webui\venv\lib\site-packages (from scikit-image) (1.24.4)

**Comment by ltdrdata** [comment]
This issue seems more appropriate to be addressed at https://github.com/ltdrdata/ComfyUI-Manager/issues.

**Comment by Piscabo** [comment]
I fixed it.
