### ISSUE TITLE
Search menu when dragging to canvas is missing

### ISSUE THREAD

**Issue by halr9000** [comfyanonymous/ComfyUI#2004]
Seems the search option has gone away from this add node dialog when dragging to the canvas. Tested with no custom nodes loaded.

![image](https://github.com/comfyanonymous/ComfyUI/assets/18482/c12b74a3-8b66-47e2-8e2b-40189cd3926f)

**Comment by chrisprojs** [comment]
me too

**Comment by halr9000** [comment]
I was reinstalling for other reasons and now it's working for me.
