### ISSUE TITLE
H100 performance issues

### ISSUE THREAD

**Issue by 0xymoro** [comfyanonymous/ComfyUI#2012]
Trying to run Comfyui as an API in a H100 cluster, and it seems like it doesn't play nice with Hopper at all. There are huge delays for certain workloads that consume a lot of CPU for some reason, these aren't related to loading models or the sort. 

I tried replicating the environment of an Ampere setup as close as I can, the only difference is torch 2.0.1 + cu118 instead of +cu117 that worked for Ampere. 

Don't quite have more bandwidth to look into this at the moment but floating it for awareness, I understand Hopper/H100 is not the typical setup but there seems to be something seriously wrong with compatibility & performance issues.

**Comment by comfyanonymous** [comment]
It should work fine on the H100 for me. Which workflow are you running?

**Comment by comfyanonymous** [comment]
Try running it with: --gpu-only

**Comment by comfyanonymous** [comment]
Does it happen when using both ckpt and safetensors checkpoints?

**Comment by comfyanonymous** [comment]
I checked and the H100 machines I have access to use driver 525.

Driver 535 is what I use on my own Linux computer and it works very well so if it's a driver problem it's an issue specifically on servers/server cards.

**Comment by delirium-trigger** [comment]
4080, 4090, A10, P40, A100 are running fine on 535 for me locally.

**Comment by WooXinyi** [comment]
I encountered the same issue, and the CPU used is Intel Xeon Gold 5318Y @ 2.10GHz. What did you use?
