### ISSUE TITLE
New commit slows UI down

### ISSUE THREAD

**Issue by mizukarada** [comfyanonymous/ComfyUI#2013]
Was getting 70+ FPS dragging nodes and the screen around, but since https://github.com/comfyanonymous/ComfyUI/commit/6ff06fa7960524749d8e584100a0e50594485f29, it's less than half of that now.

**Comment by mizukarada** [comment]
Nvm. There is a setting to disable it.

**Comment by jarrod-dexter** [comment]
What setting should be disabled please? I am having the same issue. Thanks.
