### ISSUE TITLE
Koyha Deep Shrink node support for Apple MPS?

### ISSUE THREAD

**Issue by alessandroperilli** [comfyanonymous/ComfyUI#2014]
I tried to add add the node to my workflow as follows:

<img width="704" alt="Screenshot 2023-11-21 at 11 54 35" src="https://github.com/comfyanonymous/ComfyUI/assets/9775949/495bb1b0-4a9e-4e7d-8092-67c169a7170e">

Notice that the KSampler in the image is operating with an SDXL checkpoint. 

I receive the following error:

> File "xyzs/ComfyUI/execution.py", line 153, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/execution.py", line 83, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/execution.py", line 76, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 2175, in sample_adv
>     return super().sample(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 700, in sample
>     samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
>                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 537, in process_latent_image
>     samples = KSamplerAdvanced().sample(model, add_noise, seed, steps, cfg, sampler_name, scheduler,
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/nodes.py", line 1320, in sample
>     return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/nodes.py", line 1256, in common_ksampler
>     samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 22, in informative_sample
>     raise e
>   File "xyzs/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
>     return original_sample(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/sample.py", line 100, in sample
>     samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/samplers.py", line 711, in sample
>     return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/samplers.py", line 617, in sample
>     samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/samplers.py", line 556, in sample
>     samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/k_diffusion/sampling.py", line 503, in sample_dpmpp_2s_ancestral
>     denoised = model(x, sigmas[i] * s_in, **extra_args)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/samplers.py", line 277, in forward
>     out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/samplers.py", line 267, in forward
>     return self.apply_model(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/samplers.py", line 264, in apply_model
>     out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/samplers.py", line 252, in sampling_function
>     cond, uncond = calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/samplers.py", line 230, in calc_cond_uncond_batch
>     output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/model_base.py", line 68, in apply_model
>     model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 630, in forward
>     h = p(h, transformer_options)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/comfy_extras/nodes_model_downscale.py", line 26, in input_block_patch
>     h = torch.nn.functional.interpolate(h, scale_factor=(1.0 / downscale_factor), mode="bicubic", align_corners=False)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyzs/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/functional.py", line 4046, in interpolate
>     return torch._C._nn.upsample_bicubic2d(input, output_size, align_corners, scale_factors)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     NotImplementedError: The operator 'aten::upsample_bicubic2d.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

It's not clear to me if I'm doing something wrong or if there's a genuine issue. `PYTORCH_ENABLE_MPS_FALLBACK=1` does nothing to solve the problem.

Changing the position of the node doesn't make a difference either:

<img width="999" alt="Screenshot 2023-11-23 at 09 52 38" src="https://github.com/comfyanonymous/ComfyUI/assets/9775949/56575554-2bc8-4105-b549-06487a05e38f">

Thank you for any help.

**Comment by jerlinn** [comment]
I use Kohya's Hires Fix on  M2, `PYTORCH_ENABLE_MPS_FALLBACK=1` works.

TRY:
export PYTORCH_ENABLE_MPS_FALLBACK=1
cd ComfyUI 
python main.py --force-fp16

**Comment by alessandroperilli** [comment]
You are right. It works, but (at least on my system) I still receive an error if I keep the default settings to bicubic downscale/upscale. I had to change it to bilinear and the results are less than impressive.

**Comment by alessandroperilli** [comment]
@jerlinn Can you configure the Kohya node with the bicubic algo for both downscale and upscale without errors on mac?

<img width="314" alt="Screenshot 2023-12-18 at 15 40 05" src="https://github.com/comfyanonymous/ComfyUI/assets/9775949/e43bfa90-c00f-4f92-9bbb-29b931fd7d45">


I continue to receive errors when I use bicubic, and only bicubic:

> RuntimeError: "compute_indices_weights_cubic" not implemented for 'Half'

(I use `export PYTORCH_ENABLE_MPS_FALLBACK=1` and  `--force-fp16`)

But I use bicubic algos without any issue in many other nodes (mainly upscalers).

Thanks

**Comment by GitKernelDesign** [comment]
> I use Kohya's Hires Fix on  M2, `PYTORCH_ENABLE_MPS_FALLBACK=1` works.
> 
> TRY: export PYTORCH_ENABLE_MPS_FALLBACK=1 cd ComfyUI python main.py --force-fp16

works M3 Pro ^_^ Merci beaucoup !
