### ISSUE TITLE
[Feature Request] : Models rating

### ISSUE THREAD

**Issue by Mikerhinos** [comfyanonymous/ComfyUI#2033]
I'm sure that I'm not the only one having now TONS of models, loras etc.
Some for XL, some for 1.5.
I already separated them by having folders specifically for 1.5, BUT, I still have tons of them :'(

Right now they are sorted by name, though when I make updates through the Civitai Automatic1111 extension for example, and I open a model list in ComfyUI, I sometimes have no idea what my most recent/preferred are :/

One could think "If it's bad, just delete it", but maybe today I have a lora of some subject that I'd note 3/5 which is average, but I don't want to delete it because it's the only one for now.

And models/loras that have no rating = I have to test it, it's a new one.

So a rating system would be cool I think :)

**Comment by jn-jairo** [comment]
Why don't you rename the models and add a prefix with the date or whatever you want to sort them by?

**Comment by Woisek** [comment]
Hoarding is probably never a good strategy, it's often a sign of "I don't know what I'm doing".
I can see this with this comment:
> I sometimes have no idea what my most recent/preferred are

If you worked consciously, you would know exactly what you used for what and when.
A rating system doesn't help you there either in such a case ...

**Comment by Mikerhinos** [comment]
I don't have much time to play with ComfyUI these days with all the new AI tools to try and play with, but I try to get my SD models up to date using the A1111 CivitAI extension to automatically download the newest versions, unfortunately it doesn't delete previous ones so when I come back to play with ComfyUI I have a bunch of unknown models and I don't know which ones I have to try my benchmark prompts on.
Anyway nevermind it seems there's less people than I thought with the same problem lol.

**Comment by Woisek** [comment]
> but I try to get my SD models up to date using the A1111 CivitAI extension to automatically download the newest versions, 

See, another hint. You don't need to have models "up to date". This isn't a software. Models are "as is". A newer model can do things differently, not necessary better. An older model can still be of use, no matter if there is a "new version" of it.

This all sums up in the "work consciously".

> Anyway nevermind it seems there's less people than I thought with the same problem lol.

Yeah ... guess why ... 😉
