### ISSUE TITLE
[Feat Request] Stable Video support

### ISSUE THREAD

**Issue by yhyu13** [comfyanonymous/ComfyUI#2036]
Same kind of issue https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/14056

but for ComfyUI to adapat to Stable Video workflow

**Comment by comfyanonymous** [comment]
https://comfyanonymous.github.io/ComfyUI_examples/video/

**Comment by yhyu13** [comment]
Yep, seems it's done already

https://www.youtube.com/watch?v=teIKjugRFlo
