### ISSUE TITLE
[Feature Request] - Adding "Constant" Nodes

### ISSUE THREAD

**Issue by Suppenterrine** [comfyanonymous/ComfyUI#205]
I really like your UI, it's incredibly fun to work with. And the "interactive" Documentation is genuinely nice, I'm looking forward to the finished version.

While using and playing around with the UI I got the feeling that constant nodes would be a good addition.
If I have multiple Sampler nodes and want to tweak the sampler steps all at once I could do this with just one constant node where an integer or float value (like 30) is plugged into all Sampler nodes.

This would also be handy for other cases where I don't want to change some values one by one.
Especially in complex node setups.

Thank you for your work you putting in this!

**Comment by comfyanonymous** [comment]
Fixed with: https://github.com/comfyanonymous/ComfyUI/pull/243
