### ISSUE TITLE
comfyui not using all 12 cores during heavy load

### ISSUE THREAD

**Issue by djbritt** [comfyanonymous/ComfyUI#2053]
Is it normal for comfyui to not use all 12 cpu cores in conjunction with my vram during a heavy load? See photo
![comfyui-cores](https://github.com/comfyanonymous/ComfyUI/assets/28036018/caecbfdf-5262-41df-8e15-a8ee07631d58)

**Comment by ltdrdata** [comment]
It's perfectly normal. If ComfyUI start using the CPU instead of VRAM+GPU in the sampling process, it will immediately become a bottleneck.
