### ISSUE TITLE
ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub'

### ISSUE THREAD

**Issue by Ryan-shadow** [comfyanonymous/ComfyUI#2055]
Total VRAM 6144 MB, total RAM 32509 MB
Traceback (most recent call last):
  File "F:\ai\ComfyUI-master\comfy\model_management.py", line 218, in <module>
    import accelerate
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\accelerator.py", line 36, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\utils\__init__.py", line 148, in <module>
    from .megatron_lm import (
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\utils\megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\__init__.py", line 18, in <module>
    from huggingface_hub import get_full_repo_name  # for backward compatibility
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub' (C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\__init__.py)

ERROR: LOW VRAM MODE NEEDS accelerate.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER : cudaMallocAsync
VAE dtype: torch.float32
Traceback (most recent call last):
  File "F:\ai\ComfyUI-master\main.py", line 72, in <module>
    import execution
  File "F:\ai\ComfyUI-master\execution.py", line 12, in <module>
    import nodes
  File "F:\ai\ComfyUI-master\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "F:\ai\ComfyUI-master\comfy\diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "F:\ai\ComfyUI-master\comfy\sd.py", line 12, in <module>
    from . import clip_vision
  File "F:\ai\ComfyUI-master\comfy\clip_vision.py", line 1, in <module>
    from transformers import CLIPVisionModelWithProjection, CLIPVisionConfig, modeling_utils
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\__init__.py", line 18, in <module>
    from huggingface_hub import get_full_repo_name  # for backward compatibility
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub' (C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\__init__.py)

**Comment by ChenDRAG** [comment]
Have you resolve your issue? @Ryan-shadow

**Comment by venshine** [comment]
the same problem

**Comment by ltdrdata** [comment]
Based on the symptoms, it appears that the package dependency is tangled. Also, judging from the error message, it seems to be using the system Python. It is recommended to use the portable version or a venv instead.

**Comment by aadityamundhalia** [comment]
I got the same issue trying to run inside conda

**Comment by ggriffin924** [comment]
Same issue here, running inside conda python 3.10    Anyone?

**Comment by gayanechilingar** [comment]
You can see: https://github.com/huggingface/transformers/issues/15062#issuecomment-1821349949
`conda install chardet`

**Comment by mhdpr** [comment]
I had the same problem and tried `conda install chardet` which didn't work. I solved problem using `pip install transformers -U`

**Comment by harborn** [comment]
still has problem:
`ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub'`
I have tried:
`conda install chardet` and `pip install transformers -U`

**Comment by bickramjitbasu09** [comment]
> still has problem: `ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub'` I have tried: `conda install chardet` and `pip install transformers -U`

Tried this but still sama error ? what is the issue ? anyone ?

**Comment by ThistleInTheSun** [comment]
try update requests，it works for me：
`pip install --upgrade requests`

**Comment by CrackerHax** [comment]
> try update requests，it works for me： `pip install --upgrade requests`

Ty, worked for me

**Comment by jingyang2017** [comment]
worked for me

**Comment by kmuhan** [comment]
`pip install --upgrade requests` did not works for me...
I also uninstalled and reinstalled `transformers` module.
still got `ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub' (unknown location)`

**Comment by shlok55** [comment]
pip install --upgrade requests did not works for me...
I also uninstalled and reinstalled transformers module.
still got ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub'

it doesn't work for me , is there any other solutions for this ?

**Comment by sgoede** [comment]
`pip install --upgrade transformers==4.39.2` worked for me. 
Environment with Python 3.12.2, just try to downgrade your version of the Transformers package.

**Comment by lemo366** [comment]
pip3 install cchardet, It works for me.

**Comment by lemo366** [comment]
pip3 install cchardet, It works for me.

**Comment by baojudezeze** [comment]
I fixed using:
conda install chardet

**Comment by tttturtle-russ** [comment]
I've tried following
```
conda install chardet
pip install -U transformers requests
```
still have the issue

**Comment by gangtoe** [comment]
```pip install --upgrade huggingface-hub==0.22.2``` worked for me.

**Comment by dddwhy** [comment]
> I fixed using: 我修复了使用： conda install chardet

it works for me！ i use conda！

**Comment by franck-armand** [comment]
`conda install chardet`  should solve the problem.

**Comment by Michael98Liu** [comment]
Here is how I solved the error:
`conda install chardet`
`pip install transformers -U`

I encountered two subsequent dependency issues, which are solved by:
`pip install datasets==2.16.1`
`pip install pyarrow==12.0.1`

**Comment by officialsahyaboutorabi** [comment]
I had the same problem but was able to fix it using: `conda install chardet`

**Comment by Craze-H** [comment]
> I had the same problem but was able to fix it using: `conda install chardet`

i dont use conda. So i just try `pip3 install chardet` and it works.

**Comment by starryMagician** [comment]
`conda install chardet` also works for me.

**Comment by unknownhl** [comment]
Environment:  
`python 3.10.14`
` transformers 4.41.2`

`conda install chardet` works for me.

**Comment by saiteja-tally** [comment]
Environment:
`python 3.10.14`
`transformers 4.41.2`

`conda install chardet` didn't work for me.

**Comment by ugritboon** [comment]
> You can see: [huggingface/transformers#15062 (comment)](https://github.com/huggingface/transformers/issues/15062#issuecomment-1821349949) `conda install chardet`

works for me.

**Comment by whiletrue2009** [comment]
> try update requests，it works for me： `pip install --upgrade requests`

works for me

**Comment by tian-2024** [comment]
> You can see: [huggingface/transformers#15062 (comment)](https://github.com/huggingface/transformers/issues/15062#issuecomment-1821349949) `conda install chardet`

useful!

**Comment by leodeveloper** [comment]
pip3 install chardet, It works for me.

**Comment by RayminQAQ** [comment]
> pip3 install chardet, It works for me.

same for me in ubuntu system.

**Comment by DawnMagnet** [comment]
change from 3.11 to 3.9 will solve this

**Comment by Rodio346** [comment]
reinstalled hugging face library fixed the issue 
Although I do have used the above commands including 
conda install chardet
then 
pip uninstall huggingface_hub -y 
pip install huggingface_hub

**Comment by VoDophin** [comment]
> > try update requests，it works for me： `pip install --upgrade requests`
> 
> works for me
useful

**Comment by ltdrdata** [comment]
This issue appears to be related to version incompatibility between pip packages. Please try resolving it using the answered solutions, and if it's not resolved, please create a separate issue.

**Comment by hjc3613** [comment]
for me, I move my python file to another directory, is solved.
