### ISSUE TITLE
RuntimeError: shape '[320, 320, 3, 3]' invalid 102400 error with certain Lora

### ISSUE THREAD

**Issue by ericgryffindor** [comfyanonymous/ComfyUI#206]
i used a particular LORA and got "RuntimeError: shape '[320, 320, 3, 3]' is invalid for input of size 102400" what can i do to circumvent/resolve this

LORA: anthroBirdsLora_v2.safetensors
link: [WARNING NSFW](https://civitai.com/models/9620)
this lora previously worked in A1111 but here i encounter this error

Workflow attached
[workflow (2).zip](https://github.com/comfyanonymous/ComfyUI/files/11031326/workflow.2.zip)

**Comment by comfyanonymous** [comment]
Should be fixed by: https://github.com/comfyanonymous/ComfyUI/commit/cc309568e103cfff491e281c132cfb322525df61
