### ISSUE TITLE
[Enhance] Pls make SaveAnimatedMP4

### ISSUE THREAD

**Issue by szriru** [comfyanonymous/ComfyUI#2062]
It will be helpful for me if there's like SaveAnimatedMP4 to save as mp4 other than SaveAnimatedWEBP, SaveAnimatedPNG.
Or is there a custom node for this purpose already?

**Comment by comfyanonymous** [comment]
https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite

For now you can use this.

**Comment by szriru** [comment]
Thank you. It worked.
Keep up great works btw.
