### ISSUE TITLE
Zooming in and out has extreme values

### ISSUE THREAD

**Issue by Gwillymor** [comfyanonymous/ComfyUI#2072]
Using a Logitech MX Ergo mouse via it's wireless adapter and bluetooth makes a single tap on the scroll wheel zoom in and out into extreme values on Chrome web browser.

The video attached is a comparison between a regular website scrolling vs ComfyUI on a scroll speed value of 3.

https://github.com/comfyanonymous/ComfyUI/assets/152104006/58ccdf3e-6c90-421d-a75f-5271b1f9783f

**Comment by Gwillymor** [comment]
This issue is not present on Firefox, here's a reference video of ComfyUI on Firefox, same mouse, same settings.

https://github.com/comfyanonymous/ComfyUI/assets/152104006/4cbdc2ee-8c75-41e1-a6cb-8ac7082495db

**Comment by ltdrdata** [comment]
According to Lerc's opinion, there is a suspicion that multiple wheel events may be triggered with a single wheel event at this https://github.com/jagenjo/litegraph.js/blob/015547db2ebf11843b8548a3e0a2a47fb4b76dc5/src/litegraph.js#L5070

**Comment by subtleGradient** [comment]
Try this: https://github.com/subtleGradient/TinkerBot-tech-for-ComfyUI-Touchpad
It should make smooth scrolling work as expected.
Let me know if it needs a tweak for your mouse

**Comment by Gwillymor** [comment]
> Try this: https://github.com/subtleGradient/TinkerBot-tech-for-ComfyUI-Touchpad It should make smooth scrolling work as expected. Let me know if it needs a tweak for your mouse

Thank you for this, it works for smooth scrolling. I also prefer this control scheme with ctrl + mouse wheel for zooms and the scroll wheel just... scrolls.
