### ISSUE TITLE
Windows 7 problem?

### ISSUE THREAD

**Issue by Marcus199911** [comfyanonymous/ComfyUI#208]
i tried to open the ui and got this error
![error](https://user-images.githubusercontent.com/86982208/226716383-c45cf0fd-693e-4923-83c3-dcb8351d9bec.jpg)

**Comment by comfyanonymous** [comment]
You will need an older version of pytorch than the one I ship in the standalone to get it running on windows 7.

**Comment by Marcus199911** [comment]
> You will need an older version of pytorch than the one I ship in the standalone to get it running on windows 7.

i have the older one for the automaticwebui the 1.12 i think

**Comment by Marcus199911** [comment]
> You will need an older version of pytorch than the one I ship in the standalone to get it running on windows 7.

how do i switch up the newer torch for the older one

**Comment by robinjhuang** [comment]
Try following the manual install here: https://github.com/comfyanonymous/ComfyUI

Older pytorch versions can be installed here: 
https://pytorch.org/get-started/previous-versions/#v1101
