### ISSUE TITLE
How can stablediffusion comfyui  produce the same picture

### ISSUE THREAD

**Issue by zn123** [comfyanonymous/ComfyUI#2086]
How can stablediffusion comfyui  produce the same picture
![1](https://github.com/comfyanonymous/ComfyUI/assets/3916170/498a7626-bb7e-4cf4-aa7f-edae50cf6271)
![3](https://github.com/comfyanonymous/ComfyUI/assets/3916170/49e2a913-2e7a-4fbd-8d66-f801b87a9ad7)

**Comment by ltdrdata** [comment]
Try it with GPU (=A1111) in `KSampler (Inspire)`.

https://github.com/ltdrdata/ComfyUI-Inspire-Pack

**Comment by zn123** [comment]
thanks a lot  @ltdrdata
