### ISSUE TITLE
Issue: "You shouldn't move a model when it is dispatched on multiple devices."

### ISSUE THREAD

**Issue by Appolonius001** [comfyanonymous/ComfyUI#2095]
ever time i run a new image it adds one more "You shouldn't move a model when it is dispatched on multiple devices."

_From CMD_
100%|█████████| 5/5 [00:05<00:00,  1.02s/it]
**You shouldn't move a model when it is dispatched on multiple devices.**
Prompt executed in 28.48 seconds
got prompt
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 3109.9038457870483
100%|█████████| 1/1 [00:02<00:00,  2.83s/it]
**You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.**
Prompt executed in 31.37 seconds
got prompt
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 3109.9038457870483
100%|██████████| 1/1 [00:00<00:00,  1.37it/s]
**You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.**
Prompt executed in 10.96 seconds
got prompt
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 3109.9038457870483
100%|█████████| 1/1 [00:00<00:00,  1.36it/s]
**You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.**
Prompt executed in 10.20 seconds
got prompt
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 3109.9038457870483
100%|█████████| 1/1 [00:00<00:00,  1.30it/s]
**You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.**
Prompt executed in 8.97 seconds
got prompt
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 3109.9038457870483
100%|███████| 1/1 [00:00<00:00,  1.32it/s]
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
Prompt executed in 8.56 seconds
got prompt
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 3109.9038457870483
100%|███████| 1/1 [00:00<00:00,  1.37it/s]
**You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.**
Prompt executed in 8.81 seconds

**Comment by Appolonius001** [comment]
seems to only happen with sdxl models

**Comment by usigg3** [comment]
Happens to me too. Started recently after I did a complete reinstall. Did not happen at all earlier (2-3 weeks ago). It still works but I keep getting more and more messages the longer I run it. Also running on a 6G 2060.

**Comment by Appolonius001** [comment]
@usigg3 must be because the sdxl keep reloading every time?

> got prompt
> Requested to load SDXLClipModel
> Loading 1 new model
> Requested to load SDXL
> Loading 1 new model

**Comment by StableQuestion** [comment]
I have the same problem since I updated Comfy yesterday. I have a 3060 with 12GB

**Comment by yiwen2333** [comment]
same here,is there a way to fix this. SDXL turbo takes 10~20seconds to make a image,due to this reason

**Comment by zeon72020** [comment]
This happens to me with a 1.5, it doesn't seem to create any issues but I have noiticed its there.

Loading 1 new model
You shouldn't move a model when it is dispatched on multiple devices.
You shouldn't move a model when it is dispatched on multiple devices.

**Comment by qyuzhong** [comment]
Also here, with 4gb P1000, added at startup   --normalvram, this tip miraculously disappeared, Translation plug-in translation, I do not know whether it can express clear meaning.

**Comment by comfyanonymous** [comment]
This should be fixed on the latest commits.
