### ISSUE TITLE
SDXL Turbo img2img?

### ISSUE THREAD

**Issue by stratospark** [comfyanonymous/ComfyUI#2117]
Is there a way to do img2img with the custom sampler node used in the [txt2img example](https://comfyanonymous.github.io/ComfyUI_examples/sdturbo/)? I don't see a way to set denoising strength.

**Comment by sanguivore-easyco** [comment]
With a regular KSampler, it seems like SDXL turbo is rounding everything 0.5 and below for Denoise to 0 denoise and anything above to 1 denoise.

**Comment by andypotato** [comment]
I am running into the same issue. It seems that img2img is currently not supported with Comfy due to the problem @sanguivore-easyco is describing

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/e82942cc293a7f707f3ba5611e33ec2284278268

This should fix it.
