### ISSUE TITLE
'NoneType' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by nothingness6** [comfyanonymous/ComfyUI#2119]
![comfyui](https://github.com/comfyanonymous/ComfyUI/assets/105210258/f96339c1-cb60-4461-982d-7dddeb85a640)

I have no idea what's wrong with it. Just installed ComfyUI and put the model in the P:\AI_Tools\ComfyUI_windows_portable\ComfyUI\models\checkpoints\ folder. 
What am I missing?

**Comment by levicki** [comment]
You cannot load that model with regular checkpoint loading node.

**Comment by nothingness6** [comment]
> You cannot load that model with regular checkpoint loading node. It's CLIP output is not compatible with regular CLIP text encoders.

Hi, Levicki. 
I don't understand what you are talking about as I'm a newbie on this field. Could you give me more details, please?

**Comment by levicki** [comment]
You cannot load that specific checkpoint with that loader, they aren't compatible &mdash; there's no simpler way to explain it.

**Comment by ltdrdata** [comment]
> > You cannot load that model with regular checkpoint loading node. It's CLIP output is not compatible with regular CLIP text encoders.
> 
> Hi, Levicki. I don't understand what you are talking about as I'm a newbie on this field. Could you give me more details with a solution, please?

Simply. The your model isn't valid.

**Comment by ltdrdata** [comment]
> > > > You cannot load that model with regular checkpoint loading node. It's CLIP output is not compatible with regular CLIP text encoders.
> > > 
> > > 
> > > Hi, Levicki. I don't understand what you are talking about as I'm a newbie on this field. Could you give me more details with a solution, please?
> > 
> > 
> > Simply. The selected your model isn't valid. Are you trying to create a video using SVD, or are you just trying to create a single image?
> 
> Hi, Itdrdata. Thanks for simplify it. I'm trying to create text/image to video.

In that case read this.
https://comfyanonymous.github.io/ComfyUI_examples/sdturbo/

**Comment by nothingness6** [comment]
> > > > > You cannot load that model with regular checkpoint loading node. It's CLIP output is not compatible with regular CLIP text encoders.
> > > > 
> > > > 
> > > > Hi, Levicki. I don't understand what you are talking about as I'm a newbie on this field. Could you give me more details with a solution, please?
> > > 
> > > 
> > > Simply. The selected your model isn't valid. Are you trying to create a video using SVD, or are you just trying to create a single image?
> > 
> > 
> > Hi, Itdrdata. Thanks for simplify it. I'm trying to create text/image to video.
> 
> In that case read this. https://comfyanonymous.github.io/ComfyUI_examples/video/

Thanks for the link. I downloaded and tried txt_to_image_to_video.webp, but faced the same issue. Here are the screenshots :
![comfyui](https://github.com/comfyanonymous/ComfyUI/assets/105210258/4d04f815-6dd6-4219-8457-fd827435ce50)
![comfyui-02](https://github.com/comfyanonymous/ComfyUI/assets/105210258/f8a6de4e-aa41-46e2-9507-94118a2a36f2)

**Comment by jyotirmoypaul** [comment]
Load a SD1.5 Text2Image
Generation Model Here,
Like RealisticVision or,
AbsoluteReality.

*Not a SVD Model.
![GitAnonScrnsht](https://github.com/comfyanonymous/ComfyUI/assets/128355758/bf4b1086-e8cc-4195-b8f4-e4f77f7a53f2)

**Comment by nothingness6** [comment]
> Load a SD1.5 Text2Image Generation Model Here, Like RealisticVision or, AbsoluteReality.
> 
> *Not a SVD Model. ![GitAnonScrnsht](https://private-user-images.githubusercontent.com/128355758/289352135-bf4b1086-e8cc-4195-b8f4-e4f77f7a53f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTQ4NDYsIm5iZiI6MTcwMjIxNDU0NiwicGF0aCI6Ii8xMjgzNTU3NTgvMjg5MzUyMTM1LWJmNGIxMDg2LWU4Y2MtNDE5NS1iOGY0LWU0Zjc3ZjdhNTNmMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxMzIyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjZjYjExNjdhZWY1YjdhZjIzY2IyMmJlMWM0ZDViZTc5NWQ0YjE3N2YyMmU5ZmE0ZDhlN2MxYTQ4MzMxOWU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jVc2kislGvqXaU7U4fng_J6KNVVXsVoPNhNYY7wDFQk)

Hi, jyotirmoypaul.
Thanks for the reply. I changed it and then faced "Out of memory" issue. My laptop has 6GB of vram. Is there a way to use Comfy UI with 6GB vram?
![comfyui-03](https://github.com/comfyanonymous/ComfyUI/assets/105210258/fe4773b9-51f7-4e41-8c40-d17e60f0179c)

**Comment by jyotirmoypaul** [comment]
If you have only 6GB of VRAM, then you should not use the **SVD-XT** model. Go to this link - https://huggingface.co/stabilityai/stable-video-diffusion-img2vid/tree/main and download the **SVD.safetensors** model. Then put this into your **_ComfyUI/Models/Checkpoints_** folder. Then in ComfyUI workflow select **SVD.safetensors** in Image Only Checkpoint Loader(img2vid model).
You can use this workflow for text-to-video as it is more simplified - https://drive.google.com/file/d/1HYr3kz-Xg_C9eCQrGir8269UvnZlUI3S/view 
You can watch this video for more information - https://www.youtube.com/watch?v=bpaYQDgPJeQ

**Comment by nothingness6** [comment]
> If you have only 6GB of VRAM, then you should not use the **SVD-XT** model. Go to this link - https://huggingface.co/stabilityai/stable-video-diffusion-img2vid/tree/main and download the **SVD.safetensors** model. Then put this into your **_ComfyUI/Models/Checkpoints_** folder. Then in ComfyUI workflow select **SVD.safetensors** in Image Only Checkpoint Loader(img2vid model). You can use this workflow for text-to-video as it is more simplified - https://drive.google.com/file/d/1HYr3kz-Xg_C9eCQrGir8269UvnZlUI3S/view You can watch this video for more information - https://www.youtube.com/watch?v=bpaYQDgPJeQ

Great!!! It works! I can't thank you enough. 
Have a great day!

**Comment by sauceruney** [comment]
This helped me so much! Thank you all who contributed!

**Comment by muskcookie** [comment]
执行CLIPTextEncode时出现错误：

“NoneType”对象没有属性“tokenize”

**Comment by yfwang309** [comment]
please help！i’m a newbie in stable diffusion, how to handle this situation,tks
![Untitled](https://github.com/user-attachments/assets/05bddb4f-626d-4db4-8352-5188b221ce79)

**Comment by ltdrdata** [comment]
> please help！i’m a newbie in stable diffusion, how to handle this situation,tks ![Untitled](https://private-user-images.githubusercontent.com/132827441/389993747-05bddb4f-626d-4db4-8352-5188b221ce79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2Mzg0NzEsIm5iZiI6MTczMjYzODE3MSwicGF0aCI6Ii8xMzI4Mjc0NDEvMzg5OTkzNzQ3LTA1YmRkYjRmLTYyNmQtNGRiNC04MzUyLTUxODhiMjIxY2U3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxNjIyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTczMTdiMjhlNzJmMDhjMGFiNGM4MDVlYjViYzdhNzhiNDA4NDkwNDYxNmFlYzlkZjdlMWIxZTU4OTdiMjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VnHr5IJsyriXs1EykC3zpZsXrBzcV8EEEeyYiDWXqYU)

This issue typically occurs when you have selected the wrong model. What is your workflow?

**Comment by yfwang309** [comment]
> > please help！i’m a newbie in stable diffusion, how to handle this situation,tks ![Untitled](https://private-user-images.githubusercontent.com/132827441/389993747-05bddb4f-626d-4db4-8352-5188b221ce79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2Mzg0NzEsIm5iZiI6MTczMjYzODE3MSwicGF0aCI6Ii8xMzI4Mjc0NDEvMzg5OTkzNzQ3LTA1YmRkYjRmLTYyNmQtNGRiNC04MzUyLTUxODhiMjIxY2U3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxNjIyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTczMTdiMjhlNzJmMDhjMGFiNGM4MDVlYjViYzdhNzhiNDA4NDkwNDYxNmFlYzlkZjdlMWIxZTU4OTdiMjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VnHr5IJsyriXs1EykC3zpZsXrBzcV8EEEeyYiDWXqYU)
> 
> This issue typically occurs when you have selected the wrong model. What is your workflow?

![Uploading 1a.png…]()

**Comment by yfwang309** [comment]
> This issue typically occurs when you have selected the wrong model. What is your workflow?

<img width="953" alt="1a" src="https://github.com/user-attachments/assets/d63938c7-5cce-4a7f-b67a-2458d9cb4b23">
this one？

**Comment by ltdrdata** [comment]
> > This issue typically occurs when you have selected the wrong model. What is your workflow?
> 
> <img alt="1a" width="953" src="https://private-user-images.githubusercontent.com/132827441/390214030-d63938c7-5cce-4a7f-b67a-2458d9cb4b23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2OTQwNjcsIm5iZiI6MTczMjY5Mzc2NywicGF0aCI6Ii8xMzI4Mjc0NDEvMzkwMjE0MDMwLWQ2MzkzOGM3LTVjY2UtNGE3Zi1iNjdhLTI0NThkOWNiNGIyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwNzQ5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzBiY2Q5ZmUxNDYzOTZlNjAxNGVlMTAwNzRlZWZiNDFjYWVlMGE2OGFjZjYzYjc0NGQwOGM0OTQwMmM5MTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L7Pk7DSLMVNn28F9qOj1V5qPtyeKVTmTXFqGyer8Cbg"> this one？

`sd3.5_medium.safetensors` doesn't contains clip model. It needs to be loaded separately through CLIPLoader/DualClipLoader/TripleClipLoader.
https://comfyanonymous.github.io/ComfyUI_examples/sd3/
