### ISSUE TITLE
和Windows自带输入法有冲突

### ISSUE THREAD

**Issue by billowssun** [comfyanonymous/ComfyUI#2150]
当使用搜索节点功能时，使用windows自带输入法输入中文会自动关闭节点搜索菜单。

**Comment by liaceboy** [comment]
同样问题

**Comment by lzqggghotmailcom** [comment]
搜够五笔也一样

**Comment by RItziiiiii** [comment]
同样问题，
1，中文拼音输入法就不行。
2，使用英文输入就可以。
3，第一个字符输入英文，再输入中文就会正常。
然后新搜索器是正常的，但新的搜索器显示的节点没有中英对照，学习起来没那么全面。
