### ISSUE TITLE
[Feature request] invert ctrl key,delete key

### ISSUE THREAD

**Issue by mmix574** [comfyanonymous/ComfyUI#218]
I often use UE4 as a production tool, using ComfyUI
Afterwards, I felt that the operating habits were not very consistent, and I was very annoyed. The main reason here is that ctrl defaults to frame selection instead of movement. After holding down ctrl and clicking on the canvas, the movement function is used. It would be great if it could be added ( It can be a setting), and if the delete button can be used to delete nodes or add them, it will be very good

**Comment by ltdrdata** [comment]
If there is custom key binding then it will be nice.
