### ISSUE TITLE
[Feature Request] UI QOL Move Multiple Nodes

### ISSUE THREAD

**Issue by moritz-t-w** [comfyanonymous/ComfyUI#2190]
I would love to be able to move the entire selection around.

**Comment by greeze** [comment]
You should be able to move a selection of nodes by holding the space bar and dragging one of the nodes.

**Comment by moritz-t-w** [comment]
Oh I didn't realize that. Thanks

**Comment by moritz-t-w** [comment]
Doesn't work

**Comment by greeze** [comment]
Are we talking about the same thing? This is what I'm talking about:

![drag_nodes](https://github.com/comfyanonymous/ComfyUI/assets/285741/dd609e00-2197-4031-a8ee-7f6fda41942e)

I hold down the shift key and then drag one of the selected nodes, which makes all of them move. Is that not what you're trying to do?

**Comment by greeze** [comment]
> Yes that is what I am trying to do. Do you want logs or something cause this exactly the same as what I'm doing. Reproduced in firefox on arch linux on 2 pcs separately

I just edited my post, but you probably didn't receive a notification of my edit. Try again with the shift key instead of the space bar. Sorry about that! I was distracted yesterday when I originally replied.
