### ISSUE TITLE
Search Menu extends beyond window at certain zoom levels

### ISSUE THREAD

**Issue by poisenbery** [comfyanonymous/ComfyUI#2191]
The double click to open up a search bar is a very useful feature, however, it has begun to extend past the boarders of the window when ComfyUI is at certain zoom levels, making it virtually impossible to use.

Zoomed in, extends past window/screen boarder:
![Screenshot from 2023-12-05 19-15-19](https://github.com/comfyanonymous/ComfyUI/assets/78466408/6a4254c2-47e5-4955-aece-9ea1f98f838c)

Once you reach a certain point in zooming out, the menu begins to behave as expected:
![Screenshot from 2023-12-05 19-15-08](https://github.com/comfyanonymous/ComfyUI/assets/78466408/825969d0-8a18-463c-a685-0d0977458496)

I might have to remove extensions for troubleshooting. Not sure if one of them could be causing this.

**Comment by elv56** [comment]
i add the same problem and its gone since i removed the dirty undo extension, some people while ago on reddit said it solved their problem disabling it too so might be the solution to your problem hopefuly

**Comment by an90ray** [comment]
https://github.com/giriss/comfy-image-saver
this extension was the reason for me
