### ISSUE TITLE
The image produced using ComfyUI crashes, while AUTOMATIC1111 UI is ok

### ISSUE THREAD

**Issue by stoneHah** [comfyanonymous/ComfyUI#2200]
I am use the same config,but the result of ComfyUI is crazy. I try to resintall ComfyUI, but the result is same.

I also try to change the checkpoint, but have no effect
![image](https://github.com/comfyanonymous/ComfyUI/assets/13760810/6c6013d3-35a5-416e-831c-158df248d865)
![image](https://github.com/comfyanonymous/ComfyUI/assets/13760810/c321f0d6-ff34-4adc-9897-674afa385b47)

**Comment by ltdrdata** [comment]
Your weight is too high. Weighting system between ComfyUI and A1111 is different.

**Comment by dchatel** [comment]
> Your weight is too high. Weighting system between ComfyUI and A1111 are different.

Maybe. But I have a similar issue even **without** weights.

**Comment by ltdrdata** [comment]
> > Your weight is too high. Weighting system between ComfyUI and A1111 are different.
> 
> Maybe. But I have a similar issue even **without** weights. (to a lesser extend of course, but still)

In that case, you need to check if the embedding: prefix is missing from your prompt.

Many users transitioning from A1111 experience two cases of degraded image quality as described.

In the above scenario, I didn't mention it because embedding wasn't used.

**Comment by dchatel** [comment]
No embedding prefix missing either. But in my case, as I said, the extent of the "texture blow up" effect is less important.

**Comment by ltdrdata** [comment]
> No embedding prefix missing either. But in my case, as I said, the extent of the "texture blow up" effect is less important.

Without the workflow in ComfyUI and the setup in A1111, it's impossible to make any judgment.
