### ISSUE TITLE
Error occurred when executing LoraLoader:too large headrtool, each time you update, errors occur in command lines

### ISSUE THREAD

**Issue by jjiikkkk** [comfyanonymous/ComfyUI#2204]
Error occurred when executing LoraLoader:

Error while deserializing header: HeaderTooLarge

File "/kaggle/working/ui/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/kaggle/working/ui/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/kaggle/working/ui/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/kaggle/working/ui/nodes.py", line 569, in load_lora
lora = comfy.utils.load_torch_file(lora_path, safe_load=True)
File "/kaggle/working/ui/comfy/utils.py", line 13, in load_torch_file
sd = safetensors.torch.load_file(ckpt, device=device.type)
File "/opt/conda/envs/colabui/lib/python3.10/site-packages/safetensors/torch.py", line 308, in load_file
with safe_open(filename, framework="pt", device=device) as f:

**Comment by jjiikkkk** [comment]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/ComfyUI/nodes.py", line 569, in load_lora
    lora = comfy.utils.load_torch_file(lora_path, safe_load=True)
  File "/content/ComfyUI/comfy/utils.py", line 13, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by comfyanonymous** [comment]
Your lora file is corrupt or not a safetensors file.

**Comment by jjiikkkk** [comment]
> Your lora file is corrupt or not a safetensors file.

no impossible, i also upload from civitai. also the same error

**Comment by jjiikkkk** [comment]
everything goes well yesterday until yesterday evening, i think you should do sth in your repo

**Comment by greeze** [comment]
You already opened an issue for this here: https://github.com/comfyanonymous/ComfyUI/issues/2203

Please close one of these issues to minimize spam.

**Comment by jjiikkkk** [comment]
> You already opened an issue for this here: #2203
> 
> Please close one of these issues to minimize spam.

you can close that one, but the most important is to solve problems

**Comment by greeze** [comment]
I can't close that one. I'm not a maintainer here. I'm a regular ol' user just like you, albeit with a slightly smaller sense of entitlement.

**Comment by jjiikkkk** [comment]
but could you solve your repo errors, this time like last time, all users cannot find the lauching link of webui, this time quite similar to last time

**Comment by jjiikkkk** [comment]
> Your lora file is corrupt or not a safetensors file.
do test each time before updating the repo. both colab and kaggle, also the same errors
so you must have updated sth in the repo

**Comment by jjiikkkk** [comment]
i am sure it is your repo errors, i have tried several models from civitai
in order to obtain more users, please try to provide stable updates

**Comment by jjiikkkk** [comment]
who use linux or windows GPU  servers should come across the same errors

**Comment by kochmaxence** [comment]
@jjiikkkk 

You are spamming and sound entitled. Got it, English prolly isn't your first-lang... Still, if you are not happy with something, fork and PR. Otherwise, it is what it is.

![](https://media.giphy.com/media/NdKVEei95yvIY/giphy.gif)

**Comment by jjiikkkk** [comment]
> @jjiikkkk
> 
> You are spamming and sound entitled. Got it, English prolly isn't your first-lang... Still, if you are not happy with something, fork and PR. Otherwise, it is what it is.
> 
> ![](https://camo.githubusercontent.com/dc45efaaba567920f03a36657d8267218d2157baad116bc2b06e076ce75829cd/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4e644b564565693935797649592f67697068792e676966) [ ![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4e644b564565693935797649592f67697068792e676966](https://camo.githubusercontent.com/dc45efaaba567920f03a36657d8267218d2157baad116bc2b06e076ce75829cd/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4e644b564565693935797649592f67697068792e676966) ](https://camo.githubusercontent.com/dc45efaaba567920f03a36657d8267218d2157baad116bc2b06e076ce75829cd/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4e644b564565693935797649592f67697068792e676966) [ ](https://camo.githubusercontent.com/dc45efaaba567920f03a36657d8267218d2157baad116bc2b06e076ce75829cd/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4e644b564565693935797649592f67697068792e676966)

you are rude, too. shut up

**Comment by jjiikkkk** [comment]
you shut up, silly fool

**Comment by jjiikkkk** [comment]
@kochmaxence , go away, shut up, stupid, foolish

**Comment by ltdrdata** [comment]
To find errors, it's essential to start by verifying the conditions we can trust. The starting point is to ensure that the model file is correct.

It doesn't matter whether you received it from Civtai or not. The file could be corrupt from the beginning, your download method might be incorrect, or there could be network issues preventing a proper download.

And one of the most common mistakes is downloading the link instead of the actual file.

Go to the `models/loras` directory and show information about the lora file you loaded.
And show the exact file size in bytes.
And the download links also.

Then we can verify to some extent whether the file is correct. (not perfect)

**Comment by jjiikkkk** [comment]
okay thanks  a lot

**Comment by jjiikkkk** [comment]
> @jjiikkkk
> 
> You are spamming and sound entitled. Got it, English prolly isn't your first-lang... Still, if you are not happy with something, fork and PR. Otherwise, it is what it is.
> 
> ![](https://camo.githubusercontent.com/dc45efaaba567920f03a36657d8267218d2157baad116bc2b06e076ce75829cd/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4e644b564565693935797649592f67697068792e676966) [ ![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4e644b564565693935797649592f67697068792e676966](https://camo.githubusercontent.com/dc45efaaba567920f03a36657d8267218d2157baad116bc2b06e076ce75829cd/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4e644b564565693935797649592f67697068792e676966) ](https://camo.githubusercontent.com/dc45efaaba567920f03a36657d8267218d2157baad116bc2b06e076ce75829cd/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4e644b564565693935797649592f67697068792e676966) [ ](https://camo.githubusercontent.com/dc45efaaba567920f03a36657d8267218d2157baad116bc2b06e076ce75829cd/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4e644b564565693935797649592f67697068792e676966)

go away and shut up
