### ISSUE TITLE
How can I delete some group nodes created by "Convert to Group Node"?

### ISSUE THREAD

**Issue by NewEpoch2020** [comfyanonymous/ComfyUI#2220]
I don't know how to delete some node that I don't want keep any more.

![image](https://github.com/comfyanonymous/ComfyUI/assets/75068628/f5b483d7-c5fc-4c4d-9e1f-1f1a7ad4dc95)

**Comment by greeze** [comment]
It looks like that might not be possible yet 😬.

Not ideal, but if you're familiar with JSON, you could open your workflow file in a code editor and remove your "test" node from the list of group nodes. Save and reload your workflow. But make a backup of your workflow first!

I just tested and was able to remove a grouped node that way.

**Comment by NewEpoch2020** [comment]
Thank you very much, very useful.

**Comment by MirrorDraw** [comment]
Can you tell me how to delete it? I really can't find it. Thank you very much

**Comment by MirrorDraw** [comment]
Already resolved, this is only valid for the current workflow, as long as it is re-created in another workflow

**Comment by RudyB24** [comment]
Yu might like to have a look at a custom node called Integrated Nodes 
https://github.com/palant/integrated-nodes-comfyui
Those are stored in separate json files plus an overall yaml file where you can even configure which inputs and outputs you want the integrated / group node to show. Integrated nodes become new custom nodes that can be added to any other / new workflow. The nodes can also be deleted by deleting their json file and editing the yaml file. I like it a lot.

**Comment by aimpowerment** [comment]
https://github.com/comfyanonymous/ComfyUI/issues/2167

**Comment by KLL535** [comment]
How UNGROUP nodes created by "Convert to Group Node"? 
I don't have such a button. The whole group glows red, but I can't open it.

**Comment by zhanguangfeng** [comment]
right click -> Manage Group Node -> delete
