### ISSUE TITLE
honestly i do not know what you have done again, errors everyday in command lines

### ISSUE THREAD

**Issue by jjiikkkk** [comfyanonymous/ComfyUI#2221]
/opt/conda/bin/lt -> /opt/conda/lib/node_modules/localtunnel/bin/lt.jsmdoParallel extract 1-convert/2.
/opt/conda/lib
└── localtunnel@2.0.2

/kaggle/working/ComfyUI
Total VRAM 15110 MB, total RAM 32110 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
/opt/conda/lib/python3.10/site-packages/scipy/init.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

ComfyUI finished loading, trying to launch localtunnel (if it gets stuck here localtunnel is having issues)

The password/enpoint ip for localtunnel is: 35.204.107.51
/opt/conda/lib/node_modules/localtunnel/bin/lt.js:65
(async () => {
^

SyntaxError: Unexpected token (
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:549:28)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.runMain (module.js:611:10)
at run (bootstrap_node.js:387:7)
at startup (bootstrap_node.js:153:9)

**Comment by ltdrdata** [comment]
This is a package issue unrelated to ComfyUI. Did it work correctly before?

**Comment by jjiikkkk** [comment]
surely i can try my best to correct such erros, but remembered last time? comfyUI brings troubles of lauching link for all users

**Comment by jjiikkkk** [comment]
I really cannot understand why you have to upgrade node 6 to 7
it is unnecessary at all

**Comment by jjiikkkk** [comment]
many people who use notebook in command lines will have such a problem when launching the interface again
so comfyUI repo, will you consider deeply all aspects before updating each time?

**Comment by jjiikkkk** [comment]
not will have, but at the moment we all have

**Comment by NeedsMoar** [comment]
Comfy doesn't use Node, or local_tunnel, and didn't update them.   That's whatever weird mess you're running it with.

**Comment by slbillups** [comment]
@NeedsMoar this issues section is in need of help my man, by help I mean moderators to close out unrelated issues that don't provide any context into the issue and likely aren't related to your project at all. 

if you need help cleaning it up let me know...this isn't a windows 10 support forum.

**Comment by ltdrdata** [comment]
> @NeedsMoar this issues section is in need of help my man, by help I mean moderators to close out unrelated issues that don't provide any context into the issue and likely aren't related to the project at all.
> 
> @comfyanonymous if you need help cleaning it up please add a new header to the readme, or post something on the matrix instance, I'm sure there are more than enough volunteers such as myself willing to help you out.

I also don't understand where on earth the `Node.js` is coming from. The environment he is running ComfyUI in is truly a mystery.

**Comment by comfyanonymous** [comment]
I'll give them a final chance. If they make another unproductive comment I'll block them.

**Comment by jjiikkkk** [comment]
> I'll give them a final chance. If they make another unproductive comment I'll block them.

I think you are a Chinese, right?  hehe

**Comment by jjiikkkk** [comment]
> > @NeedsMoar this issues section is in need of help my man, by help I mean moderators to close out unrelated issues that don't provide any context into the issue and likely aren't related to the project at all.
> > @comfyanonymous if you need help cleaning it up please add a new header to the readme, or post something on the matrix instance, I'm sure there are more than enough volunteers such as myself willing to help you out.
> 
> Seriously. At the very least, please ban this [jjiikkkk](https://github.com/jjiikkkk) user. They've been spamming the Issues list with duplicate issues, unrelated issues, non-issues, and rude comments directed at the people who are trying to help and at the maintainers of ComfyUI.

aren't you rude, too? ridiculous

**Comment by jjiikkkk** [comment]
> Comfy doesn't use Node, or local_tunnel, and didn't update them. That's whatever weird mess you're running it with.

no, most of you install it on your computer not in command lines
