### ISSUE TITLE
ComfyUI_windows_portable>pause

### ISSUE THREAD

**Issue by RikCost** [comfyanonymous/ComfyUI#2227]
I reinstalled python and everything broke. I dont know how, I tried unisntall and install torch, its not help. But its worked before. 

![image](https://github.com/comfyanonymous/ComfyUI/assets/69048938/237d6ebb-b9dc-4da5-a143-00b254fda473)

D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --dont-upcast-attention --force-fp16 --fp16-vae --lowvram
** ComfyUI start up time: 2023-12-09 01:26:18.571957

Prestartup times for custom nodes:
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 4096 MB, total RAM 16252 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
Forcing FP16.
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1650 Ti : native
VAE dtype: torch.float16
disabling upcasting of attention
Using pytorch cross attention
### ComfyUI Revision: 1796 [97015b6b] | Released on '2023-12-08'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prompt-Expansion
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.6 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   7.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE

D:\ComfyUI_windows_portable>pause

That cpu-mode:

D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --cpu --windows-standalone-build
** ComfyUI start up time: 2023-12-09 01:37:41.079928

Prestartup times for custom nodes:
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16252 MB, total RAM 16252 MB
Set vram state to: DISABLED
Device: cpu
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
### ComfyUI Revision: 1796 [97015b6b] | Released on '2023-12-08'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prompt-Expansion
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.6 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   7.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt

D:\ComfyUI_windows_portable>pause

![image](https://github.com/comfyanonymous/ComfyUI/assets/69048938/0492ccbe-380f-45a9-9f2b-310546bedf7e)
Try 1.5-base :
![image](https://github.com/comfyanonymous/ComfyUI/assets/69048938/621d6033-01ab-41ff-803f-2e480b98c5b8)

at end:

Requested to load SD1ClipModel
Loading 1 new model
Requested to load BaseModel
Loading 1 new model
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [02:31<00:00, 18.91s/it]
Requested to load AutoencoderKL
Loading 1 new model
D:\ComfyUI_windows_portable\ComfyUI\nodes.py:1363: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
Prompt executed in 181.05 seconds

[comfyui.log](https://github.com/comfyanonymous/ComfyUI/files/13621510/comfyui.log)

**Comment by KhSTM** [comment]
Do you have this pause only when you try to use sdxl model ? 
When you load the model, watch your RAM usage, maybe you're hiting 100% and pause at this moment, mine do exactly the same thing when i'm using sdxl model.
How big is your pagefile? Maybe try to add more if he's too low.
Idk if this gonna help you

**Comment by offmybach** [comment]
same thing just happened to me.  wtf

**Comment by hysoyam** [comment]
same error

ComfyUI\nodes.py:1363: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
Prompt executed in 17.92 seconds

**Comment by RikCost** [comment]
Just realize what i using this and this error because i dont have enouch space:
![image](https://github.com/comfyanonymous/ComfyUI/assets/69048938/a3e53eaa-1d1d-42e2-81fe-0c709dca3af5)
All its my bad, ComfyUI work normal

**Comment by yimin-demo** [comment]
@RikCost Hi, I faced same issue recently. My setting is already like this but it still pauses. Do you have any idea how much space could be enough to run? or How can I delete the previous cache from comfyui running?

**Comment by RikCost** [comment]
> @RikCost Hi, I faced same issue recently. My setting is already like this but it still pauses. Do you have any idea how much space could be enough to run? or How can I delete the previous cache from comfyui running?

15-25Gb. For deleting cash just reboot pc.
