### ISSUE TITLE
BUG: Failed to update ComfyUI or several extensions / TypeError: Cannot set properties of null (setting 'onclick')

### ISSUE THREAD

**Issue by BaronFalke** [comfyanonymous/ComfyUI#2232]
I tried to update comfy ui this week, but I get this error all the time.
![image](https://github.com/comfyanonymous/ComfyUI/assets/6080245/852d6b18-3a65-4032-915b-4441aae11751)

In the console window I have this:
![image](https://github.com/comfyanonymous/ComfyUI/assets/6080245/ef7d19f1-5ca1-4c76-bf4f-40e87fe332dd)

Don't know anything else.
I will try and disable the extensions one by one and check it.

**Comment by ltdrdata** [comment]
Update ComfyUI-Manager to latest version.

**Comment by BaronFalke** [comment]
Okay, I used the "Update All" button.
I will first try "Update ComfyUI" button.

Nevertheless:
I "fixed" it by disabling all extensions and then using "Update All".
Then I endabled each extension one by one and executed update + restart.
Took a while, but now seems to work fine.

**Comment by plugcrypt** [comment]
Go to  "ComfyUI_Windows_portable\ComfyUI\comfy" Delete everything, then Download the newest version of comfyUI Portable and drop the new files in that folder
