### ISSUE TITLE
Recent commits break compatibility with some LoRas

### ISSUE THREAD

**Issue by orcinus** [comfyanonymous/ComfyUI#2240]
Unsure if this is Mac M1/2 specific, but after recent update, most (not all) of my LoRas produce completely black inferences. I suspect it's the bf16 ones, because the ones that work are the recent ones and i recently switched to fp16 to do some side-by-side comparisons.

I tried --force-fp16, --force-fp32, and no parameters, same deal.

Running graphs with affected LoRas sometimes produces this error:

```
Using split attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Requested to load SDXLClipModel
```

**Comment by comfyanonymous** [comment]
can you upload one of those loras that don't work so I can check?

**Comment by orcinus** [comment]
This is the offending commit:
2db86b4676ed2b5c8551beea25dd2ef3fe3c4f66

It doesn't make lading loras "slightly faster", it breaks loading loras.
Undo this garbage please.
And for fucks sake, start doing QA.

**Comment by comfyanonymous** [comment]
These are not breaking changes. The only things I officially support are pytorch CUDA, ROCm and CPU because that's what I have.

I don't have a Mac so it's not officially supported and if that commit breaks things that's an issue with mps pytorch not an issue with my code.

**Comment by GoldmanOz** [comment]
Having the same issue with my M1 MacBook Pro since the latest ComfyUi update...

**Comment by comfyanonymous** [comment]
@GoldmanOz is it fixed now?

**Comment by GoldmanOz** [comment]
> @GoldmanOz is it fixed now?

Yes it is, thank you so much for the quick fix... Ran SDXL with an Ipadater workflow through 4 x Loras and images produced as expected..Black screens gone.  👍🏻

**Comment by orcinus** [comment]
Working fine now.
Thanks for the quick fix.

Sorry for the abrasive posts, it was extremely late and i was tired (not an excuse, i know).

**Comment by orcinus** [comment]
FWIW, non-blocking's been incompatible with MPS for a while, seemingly still with no solution in sight:

https://github.com/pytorch/pytorch/issues/83015

It's a bug in pytorch that randomly produces stupidly high weights and results in NaNs.
