### ISSUE TITLE
moves the parent group but does not move the child group. Can we make the child group move along with the parent group when it moves

### ISSUE THREAD

**Issue by AlexanderDash** [comfyanonymous/ComfyUI#2244]
In a group, there is a group that moves the parent group but does not move the child group. Can we make it easier for the child group to move along with the parent group when moving the child group? In addition, multiple groups cannot be selected, which is too troublesome. We hope to improve it

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
