### ISSUE TITLE
inpaint odd borders?  

### ISSUE THREAD

**Issue by alenknight** [comfyanonymous/ComfyUI#2246]
when i run an inpaint, and use load image or load image mask.... i get this odd behavior with the latest update.... i can't seem to inpaint around about 20% of the border.  there's like an invisible line blocking me from reaching those areas with my mouse.
here's my logs
```
C:\AI\ComfyUIClean>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-12-10 05:12:43.586864

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUIClean\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 32703 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints C:\AI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\AI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\AI\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\AI\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\AI\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\AI\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\AI\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\AI\stable-diffusion-webui\models/ControlNet
### Loading: ComfyUI-Impact-Pack (V4.44.3)
### ComfyUI-Impact-Pack: Updating dependencies [17 -> 19]
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['C:\\AI\\ComfyUIClean\\python_embeded\\python.exe', 'install.py'] in 'C:\AI\ComfyUIClean\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: C:\AI\ComfyUIClean\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: C:\AI\ComfyUIClean\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: C:\AI\ComfyUIClean\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.48)
### Loading: ComfyUI-Manager (V1.11.1)
### ComfyUI Revision: 1805 [340177e6] | Released on '2023-12-10'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\AI\ComfyUIClean\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
DWPose: Onnxruntime with acceleration providers detected

Import times for custom nodes:
   0.1 seconds: C:\AI\ComfyUIClean\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.2 seconds: C:\AI\ComfyUIClean\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: C:\AI\ComfyUIClean\ComfyUI\custom_nodes\comfyui_controlnet_aux
   6.0 seconds: C:\AI\ComfyUIClean\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\AI\ComfyUIClean\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
```
in the screenshot, see the areas around the upper and bottom bounds?
i can't reach those areas. oddly if i mouse PAST it... then i can paint in the remaining area.  

i tested on 2 pc's and also with firefox/safari/chrome and edge

<img width="437" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/22153900/64e0b467-7dcd-46d7-a7e8-6af5e6f8aaf2">

<img width="334" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/22153900/f485cb18-8eed-4d61-a538-ba3953e0da5a">

**Comment by alenknight** [comment]
also if i restore to older version it works fine.

**Comment by ltdrdata** [comment]
I found it...

**Comment by ltdrdata** [comment]
I just PR for this
https://github.com/comfyanonymous/ComfyUI/pull/2249

**Comment by alenknight** [comment]
> I just PR for this #2249

thanks! it's kinda fixed... well def improved.  but the bottom part is still doing same.  
however, if i zoom out... then i can reach the bottom (kinda workaround for now)....

**Comment by alenknight** [comment]
<img width="420" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/22153900/25582281-5dca-4575-8c36-5c29c835572c">
this is what i mean.  the top works great now.  but the bottom is still now allowing

**Comment by ltdrdata** [comment]
> <img alt="image" width="420" src="https://private-user-images.githubusercontent.com/22153900/289443900-25582281-5dca-4575-8c36-5c29c835572c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzg0ODQsIm5iZiI6MTcwMjI3ODE4NCwicGF0aCI6Ii8yMjE1MzkwMC8yODk0NDM5MDAtMjU1ODIyODEtNWRjYS00NTc1LThjMzYtNWMyOWM4MzU1NzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA3MDMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MWIwZjZkN2RiOWE2NGNiMjIzZDM2YmM4MTYxMjRmNGU5ZmVjOTUyYmIwODY3MDhmZDYwZTAwZWRhOWE0YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.APkT-tCM_bQTfJqtxvdHWT51mQwIQmdfs4II6XpBPRg"> this is what i mean. the top works great now. but the bottom is still now allowing

I also know what the issue is. The problem is that the `div` panel representing the controls at the bottom is being obscured by something, making it not visible. It's causing an issue because the area that shouldn't originally be drawn is now visible. I'm considering how to visually improve this situation.

**Comment by alenknight** [comment]
> The problem is that the `div` panel representing the controls

is there a way to move the image around while in mask painting mode?that would be a solid enough workaround.  i can zoom in and out to get past the border block... but often times the zoom puts the desired location in an unmanageable spot.

**Comment by ltdrdata** [comment]
> is there a way to move the image around while in mask painting mode?that would be a solid enough workaround. i can zoom in and out to get past the border block... but often times the zoom puts the desired location in an unmanageable spot.

You can move image by `Ctrl-(left button) drag`

**Comment by alenknight** [comment]
thanks! that works... didn't realize can move the image...:)
