### ISSUE TITLE
When I output json in API format

### ISSUE THREAD

**Issue by a-ru2016** [comfyanonymous/ComfyUI#2295]
When I output json in API format, changes made by right-clicking and Convert ○○ to input were not reflected in the json. Also, when I output the json in API format, the Rrimitive node was not in the json. Please fix this problem. I used DeepL.

APIフォーマットでjsonを出力したところ右クリックからConvert ○○ to inputした変更がjsonに反映されていませんでした。また、同じくAPIフォーマットで出力したところRrimitiveノードがjsonにありませんでした。修正よろしくお願いします。DeepLを使いました。

**Comment by flipnism** [comment]
primitive node is virtualnode, the value will convert back to the real node, use customnode for value such as Comfyroll

**Comment by a-ru2016** [comment]
I understand how to use the rrimitive node.you mentioned using customnode, which customnode do you use?

**Comment by flipnism** [comment]
[comfyroll](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes )
[ComfyUI-Logic](https://github.com/theUpsider/ComfyUI-Logic)
i believe they have some string node

**Comment by a-ru2016** [comment]
The explanation was insufficient. I am trying to use the WD14 Tagger for a string, but when I try to convert it to the API format, the connection is lost. Do you know how to input text into CLIP Text Encode from WD14 Tagger in API format?

**Comment by kerker93** [comment]
Have you solved this problem?
When I converted  height to input in Upscale Image,it also can not be saved in API format.In API, the connection was lost,and the input became text itself.

**Comment by DarrenLee618** [comment]
Same problem, have you solved this?
I am using WD14 Tagger and convert width&height to input in Upscale Image...unfortunately，the connections are lost.
