### ISSUE TITLE
Don't display anything

### ISSUE THREAD

**Issue by jasonlbx13** [comfyanonymous/ComfyUI#230]
After python main.py, 127.0.0.1:8188 didn't display anything but blank with no errors reported.
![2023-03-23 19-14-12屏幕截图](https://user-images.githubusercontent.com/42090642/227187150-41365bc4-d13d-4a7d-88e1-d29684ee6fb5.png)
![2023-03-23 19-14-35屏幕截图](https://user-images.githubusercontent.com/42090642/227187178-3ab8020a-52d6-4f09-ba29-5c5e50804634.png)

**Comment by jasonlbx13** [comment]
i should use didn't

**Comment by jasonlbx13** [comment]
I try to solve blank so change port num in code, but didn't work

**Comment by canshuli** [comment]
升级浏览器或者换浏览器，再刷新页面大概就可以了

**Comment by jasonlbx13** [comment]
> 升级浏览器或者换浏览器，再刷新页面大概就可以了

升级浏览器有效，谢谢！

**Comment by robinjhuang** [comment]
Looks like this is fixed.
