### ISSUE TITLE
latent preview method is always NoPreview

### ISSUE THREAD

**Issue by rvorias** [comfyanonymous/ComfyUI#2300]
https://github.com/comfyanonymous/ComfyUI/blob/a5056cfb1f41f1f9e6fcd523ef8091e6e7cd6e3b/latent_preview.py#L51

Tried the cli flag, no change
Tried setting the cli default to TAESD, no change,

Tried hardcoding:
```python
def get_previewer(device, latent_format):
    previewer = None
    method = LatentPreviewMethod.TAESD
```

Only then it works like it should.

Seems like there is a spooky runtime order going on here. (Spooky because changing the CLI defaults didn't work..)

**Comment by ltdrdata** [comment]
If you are using ComfyUI-Manager. That option is overrided by Manager. You can find option in Manager menu.

**Comment by rvorias** [comment]
> If you are using ComfyUI-Manager. That option is overrided by Manager. You can find option in Manager menu.

Thank you :pray:
