### ISSUE TITLE
Error Preview or Save image from custom node

### ISSUE THREAD

**Issue by GXcells** [comfyanonymous/ComfyUI#2301]
I am trying to make this custom node
(code in the function taken from from https://stackoverflow.com/questions/71865493/is-it-possible-to-create-a-random-shape-on-an-image-in-python
and from https://stackoverflow.com/questions/40527769/removing-black-background-and-make-transparent-from-grabcut-output-in-python-ope)

    class Random_Blob:
        def __init__(self, device="cpu"):
            self.device = device
    
        @classmethod
        def INPUT_TYPES(s):
            return {"required": { "width": ("INT", {"default": 512, "min": 1, "max": MAX_RESOLUTION, "step": 1}),
                                  "height": ("INT", {"default": 512, "min": 1, "max": MAX_RESOLUTION, "step": 1}),
                                  "batch_size": ("INT", {"default": 1, "min": 1, "max": 4096}),
                                  }}
        RETURN_TYPES = ("IMAGE",)
        FUNCTION = "generate"
    
        CATEGORY = "image"
    
        def generate(self, width, height, batch_size=1):
            # define random seed to change the pattern
            seedval = 15
            rng = default_rng()
    
            # define image size
            #width=512
            #height=512
    
            # create random noise image
            noise = rng.integers(0, 255, (width,height), np.uint8, True)
    
            # blur the noise image to control the size
            blur = cv2.GaussianBlur(noise, (0,0), sigmaX=9, sigmaY=15, borderType = cv2.BORDER_DEFAULT)
    
            # stretch the blurred image to full dynamic range
            stretch = skimage.exposure.rescale_intensity(blur, in_range='image', out_range=(0,255)).astype(np.uint8)
    
            # threshold stretched image to control the size
            thresh = cv2.threshold(stretch, 175, 255, cv2.THRESH_BINARY)[1]
    
            # apply morphology open and close to smooth out shapes
            kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (9,9))
            result = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel)
            result = cv2.morphologyEx(result, cv2.MORPH_CLOSE, kernel)
    
            
            #then we transform the binary mask to a RGBA image with transparency
            resultbgr=cv2.cvtColor(result, cv2.COLOR_GRAY2BGR)#we need to convert our image of blob to RGB in order to make a RGBA image after
            _,alpha = cv2.threshold(result,0,250,cv2.THRESH_BINARY)#here we create a threshold on the first "result" binary image
            b, g, r = cv2.split(resultbgr)
            rgba = [b,g,r, alpha]
            dst = cv2.merge(rgba,4)
            tensorImg = transforms.ToTensor()(dst)
            return (tensorImg)

But I get that error, 

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\****\comfyui\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\comfyui\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\comfyui\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\comfyui\ComfyUI\nodes.py", line 1359, in save_images
    full_output_folder, filename, counter, subfolder, filename_prefix = folder_paths.get_save_image_path(filename_prefix, self.output_dir, images[0].shape[1], images[0].shape[0])
                                                                                                                                           ~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range

I think it is maybe because I don't have any implementation of batch size in my node.
EDIT: Actually, I think there is a problem when I convert cv2 to tensor. The shape of the tensor does not correspond to what we would expect (when we preview tensor in google colab for example compared to the node create empty image

Any idea how to fix that?

**Comment by GXcells** [comment]
Ok found a fix but it is really weird and I lose transparency

        tensorImg = transforms.ToTensor()(dst)#we transform the cv2 image to a tensor
        tensorImg=torch.unsqueeze(tensorImg, dim=0)
        tensorImg=tensorImg.permute(1,0,3,2)
        return(tensorImg)

But this is weird because I have to do a weird permutation off the dimension.
Without permutation if I do  "tensorImg.size()" with width =512 and height=768
I get "torch.Size([1, 4, 512, 768])"
This is not what is expected by the "preview image node"
So I permute dimensions so that channel number (4) is in the last index using "tensorImg=tensorImg.permute(0,2,3,1)"
Now if  I do "tensorImg.size()"
I get "torch.Size([1, 512, 768, 4])"
But now in comfyUi this will generate 512 images of 768 width and 4 of height which is not what should happen.

To make it generate 1 image of the right dimension I have to do
        tensorImg=tensorImg.permute(1,0,3,2)
Now if  I do "tensorImg.size()" this give "torch.Size([4, 1, 768, 512])"
     
Any hint on why we have this weird behavior and why I loose alpha transparency (becomes black)

**Comment by ltdrdata** [comment]
You have to return like this

```
return (tensorImg, )

```

not single value like this.

```
return (tensorImg)

```

**Comment by GXcells** [comment]
> You have to return tuple like this
> 
> ```
> return (tensorImg, )
> ```
> 
> not single value like this.
> 
> ```
> return (tensorImg)
> ```
> 
> This is a common mistake when starting to develop custom nodes for the first time.

Wow, thanks. Yes indeed that is my first node

**Comment by GXcells** [comment]
Completed
