### ISSUE TITLE
How to display other files images on web pages?

### ISSUE THREAD

**Issue by NO13Listener** [comfyanonymous/ComfyUI#231]
I add the files in output\Year-month-day, and it getting work, but **how to display images on web pages???**
==========
nodes.py
==========
import time

class SaveImage:
    def __init__(self):
#加入含有日期的存储图片路径#
      today=time.strftime("%Y-%m-%d",time.localtime())  #今天日期

      ZZX ="\ComfyUI\output\{}".format(today) #想保存的路径名称
      if not os.path.exists(ZZX):   #如果不存在
        os.makedirs(ZZX)     #创建

      self.output_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), "output\{}".format(today))

**Comment by WASasquatch** [comment]
Output stuff is really jank. We need to be able to output images from anywhere, and text as well. But right now it seems to be able to only display images from the output and input dir. No where else. My custom node won't display any image when saving to any custom folders.

**Comment by NO13Listener** [comment]
My friend and I fix a little about this：
First: nodes.py，you need add "import time" at first
Second: server.py，you need add "import time" at first
I think you can understand and I hope it can be helpful
![nodes_py__change](https://user-images.githubusercontent.com/125913223/227627657-672f94e9-3966-4e65-b21d-505b88311017.png)

![server_py__change](https://user-images.githubusercontent.com/125913223/227627672-635d8b2f-84fe-4f64-867c-4079c13cae63.png)

**Comment by NO13Listener** [comment]
My friend and I expand this work and its ok, try to add and change these place enough：
I think you can understand and I hope it can be helpful
![Change](https://user-images.githubusercontent.com/125913223/227640931-77826a58-a133-4aea-813f-235f3eed0156.png)

**Comment by WASasquatch** [comment]
> My friend and I expand this work and its ok, try to add and change these place enough： I think you can understand and I hope it can be helpful ![Change](https://user-images.githubusercontent.com/125913223/227640931-77826a58-a133-4aea-813f-235f3eed0156.png)

Very nice, so in the example we get images sorted by the day, like in webui. This is an appreciated share, and informational on the flow. Thank you, to you and your friend.
