### ISSUE TITLE
[bug] After json file saved, the node selection will be hard, real cursor is far away from node

### ISSUE THREAD

**Issue by Erwin11** [comfyanonymous/ComfyUI#2326]
### **comfyui version** 
commit 571ea8cdcc2d1bf4fa7f398dad68415dacfff02f (HEAD -> master, origin/master, backup_branch_2023-12-19_11_12_21, backup_branch_2023-12-19_11_12_09)
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Mon Dec 18 17:03:32 2023 -0500

    Fix SAG not working with cfg 1.0

### **Bug info**
after a json file I saved  , I reselect some node on browser, the node selection will be hard, real cursor is far away from node.
_Here is screen shot:_
![selectbug](https://github.com/comfyanonymous/ComfyUI/assets/6300501/15ced996-9de9-4fa2-8259-77d414db1fa2)

![screenshot](https://github.com/comfyanonymous/ComfyUI/assets/6300501/a0a775c6-5bd5-431f-9a05-b32cd0b9f022)

**Comment by ltdrdata** [comment]
Based on my experience, this is not an issue that occurs when saving a JSON file but rather sporadically when exporting as an image, such as `export->png`. 

Is it truly occurs when saving JSON through the save function.

**Comment by Erwin11** [comment]
yes！ >_<;  unsually I will save it as png  at the same time .   maybe it cause png , so what should I do to avoid it?
I'm create a new tab ,add json file to avoid  this, temporary.

**Comment by ltdrdata** [comment]
> yes！ >_<; unsually I will save it as png at the same time . maybe it is a reason , so what should I do to avoid it? I'm create a new tab ,add json file to avoid this, temporary.

This is a random misalignment of coordinates during the export process, and currently, the only solution is to refresh.
