### ISSUE TITLE
Issue with Custom Nodes and __init__.py

### ISSUE THREAD

**Issue by MrSmith44** [comfyanonymous/ComfyUI#2356]
I've been trying to fix this for a few hours now nothing seems to work i followed all install instructions i have python set up and also on path i have all the visual studio tools set up as i use Automatic1111 but i wanted to use Comfy UI windows standalone but it constantly has errors even when installing custom nodes with git clone and comfyui manager any help will be appreciated thank you

C:\Users\Smith\Desktop\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2023-12-23 21:18:11.658120
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\Users\Smith\Desktop\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6140 MB, total RAM 16108 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4050 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Smith\\Desktop\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\.git\\__init__.py'

Cannot import C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\.git module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\Smith\\Desktop\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\.git\\__init__.py'
### ComfyUI Revision: 1851 [a252963f] | Released on '2023-12-23'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
OpenPose Editor: Loaded
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

Import times for custom nodes:
   0.0 seconds: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.jsonC:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Selector

   0.0 seconds (IMPORT FAILED): C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\.gitFETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json

   0.0 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OpenPose-Editor
   0.6 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

**Comment by ltdrdata** [comment]
Just remove .git dir in custom_nodes.
Thar should not be placed in here.

**Comment by MrSmith44** [comment]
Thanks mate that's took away the first problem i'm going to try install the custom nodes and see how i get on really appreciate the help

**Comment by lindongyue7** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\comfyui\\ComfyUI\\custom_nodes\\BrushNet-main\\__init__.py'

Cannot import D:\comfyui\ComfyUI\custom_nodes\BrushNet-main module for custom nodes: [Errno 2] No such file or directory: 'D:\\comfyui\\ComfyUI\\custom_nodes\\BrushNet-main\\__init__.py'
2024-09-03 11:52:25,572- root:2012- WARNING- Traceback (most recent call last):
  File "D:\comfyui\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\comfyui\\ComfyUI\\custom_nodes\\segment-anything-main\\__init__.py'

**Comment by ltdrdata** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'D:\comfyui\ComfyUI\custom_nodes\BrushNet-main\**init**.py'
> 
> Cannot import D:\comfyui\ComfyUI\custom_nodes\BrushNet-main module for custom nodes: [Errno 2] No such file or directory: 'D:\comfyui\ComfyUI\custom_nodes\BrushNet-main\**init**.py' 2024-09-03 11:52:25,572- root:2012- WARNING- Traceback (most recent call last): File "D:\comfyui\ComfyUI\nodes.py", line 1993, in load_custom_node module_spec.loader.exec_module(module) File "", line 991, in exec_module File "", line 1128, in get_code File "", line 1186, in get_data FileNotFoundError: [Errno 2] No such file or directory: 'D:\comfyui\ComfyUI\custom_nodes\segment-anything-main\**init**.py'

That is not a custom node. Remove `D:\comfyui\ComfyUI\custom_nodes\BrushNet-main` dir.
