### ISSUE TITLE
some keyboard shortcuts don't work on chrome based browsers

### ISSUE THREAD

**Issue by TingTingin** [comfyanonymous/ComfyUI#2368]
I tried copy nodes (Ctrl+C) and paste (Ctrl+V) and copy nodes with connections (Ctrl+C) and (Ctrl+shift+V) it doesn't work on chrome or brave but works on opera browser some others may not work as well 

Also ctrl+shift+v brings up dev tools in chrome, brave and opera. Having some ability to customize shortcuts could go a long way

**Comment by ltdrdata** [comment]
> I tried copy nodes (Ctrl+C) and paste (Ctrl+V) and copy nodes with connections (Ctrl+C) and (Ctrl+shift+V) it doesn't work on chrome or brave but works on opera browser some others may not work as well
> 
> Also ctrl+shift+v brings up dev tools in chrome, brave and opera. Having some ability to customize shortcuts could go a long way

Did you changed shortcut of chrome browser?
I have no problem with Chrome browser.

**Comment by kaipard** [comment]
it occurred to me today , i pressed ctrl+v in a  result of a group nodes which never be changed by 'ctrl +c'

**Comment by OnlyDEWx60** [comment]
facing the same issue, did anyone find a fix plz consider replying

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
