### ISSUE TITLE
How to integrate a new upscaler

### ISSUE THREAD

**Issue by rethink-studios** [comfyanonymous/ComfyUI#237]
Hi Team,
I was just introduced to this new up-scaler : 4x_UltraSharp
https://mega.nz/folder/qZRBmaIY#nIG8KyWFcGNTuMX_XNbJ_g

Is there a way to integrate different up-scalers into Comfy?

Thanks in advance!

**Comment by comfyanonymous** [comment]
Yes like this: https://comfyanonymous.github.io/ComfyUI_examples/upscale_models/

**Comment by WASasquatch** [comment]
Yeah I've been using 4x since day once, it loads fine and works fine.

**Comment by GrimblyGorn** [comment]
I have like 40 models from [here](https://upscale.wiki/wiki/Model_Database) including 1x models and all sorts, they all load fine and the ones I've tested so far worked well.
