### ISSUE TITLE
node templates  Sometimes they disappear strangely.

### ISSUE THREAD

**Issue by liulsg** [comfyanonymous/ComfyUI#2381]
My own custom nodes often disappear strangely, and when I search the entire comfyui folder, I can't find custom nodes. This has happened many times.

**Comment by knowknow0** [comment]
I had the same problem. Have you solved it already?

**Comment by ltdrdata** [comment]
This is an issue occurring due to the template being stored in the browser. AFAIK, it has been changed to be stored on the server. Update to the latest version and check.
