### ISSUE TITLE
clip and clip_vision models

### ISSUE THREAD

**Issue by ekswathi** [comfyanonymous/ComfyUI#239]
where i can get clip and clip vision models?

**Comment by comfyanonymous** [comment]
This is the full CLIP model which contains the clip vision weights: https://huggingface.co/openai/clip-vit-large-patch14/blob/main/pytorch_model.bin

And here's the SD1.5 CLIP model: https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/text_encoder/model.safetensors

**Comment by ekswathi** [comment]
thank you
