### ISSUE TITLE
Can't Set Clip Skip with CheckpointLoaderSimple, Checkpoint Loader is Incredibly Slow

### ISSUE THREAD

**Issue by Neverdusk** [comfyanonymous/ComfyUI#240]
I've been trying to use the regular CheckpointLoader node to manually set the config for my model. However, it produces much slower results, dropping from 3-5ti/s to 1ti/s on my 3060 RTX 12 GB. The log mentions xformers, but they don't seem to be active. 

I've tried swapping between v1-inference, vi-inference-clip-skip-2, anythingv3, and my model's own config, but all of them produce incredibly slow results. Then, as soon as I switch back to CheckpointLoaderSimple, my generation speeds shoot back up to 3-5it/s.

Is there a way to get the speed of CheckpointLoaderSimple while being able to set clip skip to 2?

**Comment by comfyanonymous** [comment]
You can use the CLIPSetLastLayer node to set clip skip.

The reason regular CheckpointLoader is slower than CheckpointLoaderSimple for you is likely because you are not picking the fp16 configs.

**Comment by Neverdusk** [comment]
Got it, thank you for the explanation. Everything seems to be working perfectly now. In fact, I think it's even faster somehow.
