### ISSUE TITLE
Getting weird image result when using --normalvram

### ISSUE THREAD

**Issue by abuyazid955** [comfyanonymous/ComfyUI#2410]
I'm getting weird image output when generating with SDXL models using --normalvram. however it's fixed when i'm using --lowvram. 

But before this, i always using --normalvram and it's normal and fine.

i have tried to :
- disable the xformers
- changing encoder
- changing sdxl models
- updating comfyui and python dependencies
- updating all custom nodes
- rebuild nodes after update

![image](https://github.com/comfyanonymous/ComfyUI/assets/113452309/0807337f-5372-4e17-a87f-1b44ebb8f3b4)

**Comment by comfyanonymous** [comment]
That looks like the issue I fixed yesterday, make sure you are using the latest ComfyUI.

If that doesn't fix it can you tell me what your GPU is?

**Comment by abuyazid955** [comment]
> That looks like the issue I fixed yesterday, make sure you are using the latest ComfyUI.
> 
> If that doesn't fix it can you tell me what your GPU is?

Hi, thank you for your response.

I'm using RTX3050M 4GB

**Comment by abuyazid955** [comment]
> That looks like the issue I fixed yesterday, make sure you are using the latest ComfyUI.
> 
> If that doesn't fix it can you tell me what your GPU is?

I have tried to update the comfyui, and it's works now.
Thank you!
