### ISSUE TITLE
Install on IPAD

### ISSUE THREAD

**Issue by TmKrs** [comfyanonymous/ComfyUI#2419]
I was just wondering whether there would be an option to install it on Ipad as well? Any Ideas?

**Comment by caniyabanci76** [comment]
probably better to run it on another machine using `--listen` and then connect via ipad browser.

**Comment by benliong** [comment]
You can now probably download https://github.com/comfyanonymous/ComfyUI/issues/2419 And download a ubuntu VM to run ComfyUI totally locally on iOS (probably best for iPad). But I’d imagine that ComfyUI won’t be able to utilise Apple Silicon Neural Engine. Would be fun to just do design and testing of image generated on iPad on the plane though.

**Comment by ltdrdata** [comment]
As already answered, attempting to install ComfyUI on an IPad is not appropriate.
