### ISSUE TITLE
Feature Request: Visual Indicator of a "pinned" node

### ISSUE THREAD

**Issue by ghostsquad** [comfyanonymous/ComfyUI#2423]
maybe a little lock/pin icon that shows up in the top right corner of the node when it's "pinned". Also, would love to see the context menu change from "pin" to "unpin" if the node is pinned, and I'm unpinning it. Right now it's always just "pin".

**Comment by darkflare** [comment]
Now that the "lock" function was replaced by the "pinned" one.

**> Replaced locking with pinning in core [(#734](https://github.com/Comfy-Org/ComfyUI_frontend/pull/734))**

A visual indicator of a "pinned" node would be nice. 🙏
