### ISSUE TITLE
[Bug] API is broken suddenly for me, utf-32-be' codec can't decode bytes in position 8-11

### ISSUE THREAD

**Issue by remsky** [comfyanonymous/ComfyUI#2435]
Hey I saw some changes were made to the progress websocket packet. Sometime in the last 12 hours the api has broken for me, and not sure if it's related, I don't believe I've made any major changes on my end, but have been playing with new workflows. Could this be related?

`An error occurred: 'utf-32-be' codec can't decode bytes in position 8-11: code point not in range(0x110000)`

Which occurs here in the stream

```
{'type': 'status', 'data': {'status': {'exec_info': {'queue_remaining': 1}}, 'sid': 'dc8b0464-4a73-4395-94b3-fd62fe7dac41'}}
{'type': 'executing', 'data': {'node': '21'}}
{'type': 'executing', 'data': {'node': '20', 'prompt_id': '9fcaea6a-9217-41b5-b0ef-59f7e98c7995'}}
{'type': 'executing', 'data': {'node': '10', 'prompt_id': '9fcaea6a-9217-41b5-b0ef-59f7e98c7995'}}
{'type': 'progress', 'data': {'value': 1, 'max': 20}}
Traceback (most recent call last):
```

Here's the function I'm using based on the example code, was working fine prior

```
async def execute_and_download_images(prompt):
    images = []
    async with aiohttp.ClientSession() as session:
        prompt_data = {"prompt": prompt, "client_id": client_id}
        async with session.post(f"http://{server_address}/prompt", json=prompt_data) as response:
            prompt_id = (await response.json())['prompt_id']

        async with websockets.connect(f"ws://{server_address}/ws?clientId={client_id}") as ws:
            while True:
                message = json.loads(await ws.recv())
                if message['type'] == 'executing' and message['data']['node'] is None and message['data']['prompt_id'] == prompt_id:
                    break

        async with session.get(f"http://{server_address}/history/{prompt_id}") as response:
            raw_data = await response.read()
            print(raw_data)
            history = await response.json()
            history_data = history[prompt_id]
            for node_id, node_output in history_data['outputs'].items():
                if 'images' in node_output:
                    for image in node_output['images']:
                        async with session.get(f"http://{server_address}/view?{urllib.parse.urlencode(image)}") as img_response:
                            images.append(Image.open(io.BytesIO(await img_response.read())))
    return images
```

**Comment by remsky** [comment]
Ah nevermind. I enabled live preview, and it's sending raw jpeg binary data in between which is what caused the issue.

**Comment by NixerSo5** [comment]
hello   but  i  have a  question 
how to  show  this raw jpeg   
i  want to   save it   but  get the error  :             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-32-be' codec can't decode bytes in position 8-11: code point not in range(0x110000)

when i  run  like  this:
  img = Image.open(io.BytesIO(message))


please  help

**Comment by NixerSo5** [comment]
get the answer


def extract_jpg_image():
    jpg_byte_start = b'\xff\xd8'
    jpg_byte_end = b'\xff\xd9'
    jpg_image = bytearray()
    # 使用正则表达式提取字节数据
    with open("imgfile.txt", "rb") as file:
        file_data = file.read()
        converted_data = file_data.decode('unicode_escape').encode('latin1')
        req_data = converted_data
        start = req_data.find(jpg_byte_start)

        if start == -1:
            print('Could not find JPG start of image marker!')
            return
        end = req_data.find(jpg_byte_end, start) + len(jpg_byte_end)
        jpg_image += req_data[start:end]

        print(f'Size: {end - start} bytes')
        with open(f'extracted-img.jpg', 'wb') as f:
            f.write(jpg_image)


thank you  told  me   it is   raw jpeg binary data
