### ISSUE TITLE
Persistent 'NoneType' Error with ControlNet IP-Adapter XL Models

### ISSUE THREAD

**Issue by EtienneDosSantos** [comfyanonymous/ComfyUI#2440]
I consistently encounter a specific error when attempting to use any controlnet ip-adapter xl model in ComfyUI. Despite selecting different ip-adapter models, the same issue arises:

> Error occurred when executing ControlNetApplyAdvanced:
> 
> 'NoneType' object has no attribute 'copy'
> 
>   File "E:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 750, in apply_controlnet
>     c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent))
>             ^^^^^^^^^^^^^^^^

This error seems specific to the controlnet ip-adapter xl models. Other controlnet models function correctly without any issues.

**Comment by comfyanonymous** [comment]
https://github.com/cubiq/ComfyUI_IPAdapter_plus

If you want to use ip adapter you should use these custom nodes.

**Comment by EtienneDosSantos** [comment]
I see, thanks a lot for pointing that out to me!
