### ISSUE TITLE
[Feature] Clone Group (and all nodes)

### ISSUE THREAD

**Issue by ghostsquad** [comfyanonymous/ComfyUI#2441]
I'd like to be able to clone an entire group (nodes included). A workaround I've found is that I can "Convert to Group Node", clone the group node, then "Convert to Nodes". But this may not work in all scenarios.

**Comment by ltdrdata** [comment]
And please post any requests related to the front end here.
https://github.com/Comfy-Org/ComfyUI_frontend/issues
