### ISSUE TITLE
model_lora_keys_unet()/model_lora_keys_clip() produces some exploded/incorrect mappings

### ISSUE THREAD

**Issue by krahnikblis** [comfyanonymous/ComfyUI#2442]
hello... i'm working on some lora stuff (translating a bunch of stuff i built in JAX back to troch so i can make them into comfy nodes) and also trying to diagnose why animatediff behaves so differently which base or lora-fied models... 

not sure if i should be using this function, found it in some other code and i interpreted it as a source for mapping the key names within a model state dict to their matching names in a lora state dict - so first off if i'm using some outdated thing i guess please point me in the right direction...

problems are a few. they don't seem to affect all loras, because everyone puts different layers in their loras and it appears they could be made with different formats (diffusers or OG-SD or whatever), but i have had a few instances of getting weird model results because a lora is maybe appended multiple times? i see these main effects:
1. keys are not matched (numerically) correctly - e.g. attention layer 1 in a lora is mapped to attention layer 7 in the model
2. keys are not matched (structurally) correctly - e.g. up block in lora is mapped to input block in model, or a conv to an out
3. multiple key formats are produced - i think this might be on purpose, to allow for all possible syntaxes? e.g. some lora keys don't start with "lora_"
4. same model keys are mapped to different lora keys - i think this might just be an effect of the explosions in numbers 1 and 2, maybe also 3

replication and examples:
code snippet:
```python
        unet_key_map, text_key_map = {}, {}
        unet_key_map = comfy.lora.model_lora_keys_unet(model.model, unet_key_map)
        # debug why are the keys not matching?
        print("getting all possible keys from comfy fn")
        for k,v in unet_key_map.items():
            print(f"unet lora key = {k}, unet model key = {v}")
        text_key_map = comfy.lora.model_lora_keys_clip(clip.cond_stage_model, text_key_map)
        for k,v in text_key_map.items():
            print(f"text lora key = {k}, text model key = {v}")
```
examples of completely wrong mappings:
```
unet lora key = lora_unet_down_blocks_0_resnets_0_conv1, unet model key = diffusion_model.input_blocks.1.0.in_layers.2.weight 
^ > wrong block (down vs input) and wrong layer (0-0-1 vs 1-0-2)
unet lora key = lora_unet_down_blocks_0_resnets_1_conv2, unet model key = diffusion_model.input_blocks.2.0.out_layers.3.weight 
^ >  down vs input, 0-1-2 vs 2-0-3, and conv vs out?
unet lora key = lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_attn1_to_q, unet model key = diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_q.weight 
^ >  down vs input, 1-0-0-1 vs 4-1-0-1
unet lora key = lora_unet_down_blocks_1_resnets_1_conv1, unet model key = diffusion_model.input_blocks.5.0.in_layers.2.weight
unet lora key = lora_unet_down_blocks_2_attentions_0_transformer_blocks_1_attn1_to_q, unet model key = diffusion_model.input_blocks.7.1.transformer_blocks.1.attn1.to_q.weight
unet lora key = lora_unet_down_blocks_2_attentions_0_transformer_blocks_1_norm1, unet model key = diffusion_model.input_blocks.7.1.transformer_blocks.1.norm1.weight
unet lora key = down_blocks.2.attentions.0.transformer_blocks.7.ff.net.0.proj, unet model key = diffusion_model.input_blocks.7.1.transformer_blocks.7.ff.net.0.proj.weight
unet lora key = unet.down_blocks.2.attentions.1.transformer_blocks.8.attn2.processor.to_q, unet model key = diffusion_model.input_blocks.8.1.transformer_blocks.8.attn2.to_q.weight 
^ > i found these ones odd too - they don't even start with "lora_" and at first looked like they were rearranging the numbered tokens, but this one maps from 2-1-8-2 to 8-1-8-2 so i don't think it's a simple rearrange... 
```
^ i imagine these don't cause errors because maybe there's a shape check when running lora up-dot-down and adding to the model? in my case i 

examples of different lora keys having the same model key mapped:
```
text lora key = lora_te_text_model_encoder_layers_0_mlp_fc2, 	text model key = clip_l.transformer.text_model.encoder.layers.0.mlp.fc2.weight
text lora key = lora_te1_text_model_encoder_layers_0_mlp_fc2, 	text model key = clip_l.transformer.text_model.encoder.layers.0.mlp.fc2.weight
unet lora key = unet.up_blocks.0.attentions.0.transformer_blocks.9.ff.net.0.proj, 	unet model key = diffusion_model.output_blocks.0.1.transformer_blocks.9.ff.net.0.proj.weight
unet lora key = up_blocks.0.attentions.0.transformer_blocks.9.ff.net.0.proj, 		unet model key = diffusion_model.output_blocks.0.1.transformer_blocks.9.ff.net.0.proj.weight
unet lora key = lora_unet_up_blocks_0_attentions_0_transformer_blocks_9_ff_net_0_proj, 	unet model key = diffusion_model.output_blocks.0.1.transformer_blocks.9.ff.net.0.proj.weight
```
^ this became problematic because i was trying to use a pop(key) method and i was getting missing key errors, because a prior lora layer already consumed the same key... 

i think i'll leave it with these - the full list of outputs of course is really long, and i think most other problems i find will probably have the same root cause - some list is getting exploded against some other list. and it might be amplified because i used these functions as mappings from which to generate a lora model, so i think it explains why i've got one that's 100MB and should only be 25MB, and it's the one giving me grief about having same model keys for different lora keys...

**Comment by comfyanonymous** [comment]
Those mappings look fine. These are just the difference between diffusers key names vs ldm key names.

A down_block is an input_block and it's normal that the numbers are different for diffusers vs ldm.

**Comment by krahnikblis** [comment]
ok, i've bastardized these crosswalk functions by removing the diffusers stuff and doing a check for which type of model is present, since what i needed was a 'normal lora' name given an input model's layer name, think i got what i needed... i'll check how i did the lora-from-diffusers-torch-to-lora-in-jax naming and copypasta from there if i need.... thanks!
