### ISSUE TITLE
execute_prestartup_script is loading the wrong path

### ISSUE THREAD

**Issue by Lin1031** [comfyanonymous/ComfyUI#2443]
When using plugins developed by other developers, I encountered an error in executing `prestartup_script.py`. 

I added some `print` statements in the main function and identified the issue. 
![image](https://github.com/comfyanonymous/ComfyUI/assets/44975556/060a7d58-7a49-46b1-8faf-b8925b88a485)

I found that the `custom_nodes` path I modified in `extra_model_paths.yaml` is not being used here; 
![image](https://github.com/comfyanonymous/ComfyUI/assets/44975556/ed11316c-de81-4233-9904-14c39e0cd660)

it is still using the default `custom_nodes` path.
![image](https://github.com/comfyanonymous/ComfyUI/assets/44975556/23b612e2-95e7-4e69-a8e2-d59b21377ff3)

**Comment by ltdrdata** [comment]
`extra_model_paths.yaml` is intended to specify additional model paths, not to replace existing paths. 
Furthermore, it is not intended for specifying the `custom_nodes` path. If you specify a custom_nodes path outside of `ComfyUI/custom_nodes`, various unexpected issues may arise.

Because many custom nodes assume and operate based on that location.

**Comment by Lin1031** [comment]
> `extra_model_paths.yaml` is intended to specify additional model paths, not to replace existing paths. Furthermore, it is not intended for specifying the `custom_nodes` path. If you specify a custom_nodes path outside of `ComfyUI/custom_nodes`, various unexpected issues may arise.
> 
> Because many custom nodes assume and operate based on that location.

Because I saw the usage of `custom_nodes` under `"other_ui"` in `extra_model_paths.yaml.example`, I attempted to do so. However, it seems that I can only move `custom_nodes` back to the default location. Thank you very much.
