### ISSUE TITLE
Bug: Drag image to load workflow only loads the previous workflow

### ISSUE THREAD

**Issue by joetech** [comfyanonymous/ComfyUI#245]
On Ubuntu, I'll generate many images and then want to go back to one to try some tweaks.  To do this, I first hit the Clear button to clear the whole UI and then drag an image into the browser UI.  My understanding is that it should read the metadata from the image and load the UI/settings used to create it.  What happens instead is that it loads the UI/settings of the last image generated.  The Load button from history works to load an image, but if I've generated several hundred, it can be cumbersome to use that route.

Console has no output.

**Comment by comfyanonymous** [comment]
It loads the workflow used to generate the image. If you load an image and press Queue Prompt it will generate the same image.

**Comment by joetech** [comment]
It seems to be working for me now.  It was not behaving before.  I'll close this.
