### ISSUE TITLE
Is it possible to have string input from another node?

### ISSUE THREAD

**Issue by GaidamakUA** [comfyanonymous/ComfyUI#248]
I want to implement something like string replacement in AUTOMATIC1111.
The ultimate goal is to generate multiple characters getting older and doing same job. For that I need a node that accepts prompt string and array of replacement strings. Is it possible to just create custom node, or input system needs to be modified for that?

**Comment by GrimblyGorn** [comment]
You could likely achieve what you wanted with the various node packs from [here](https://civitai.com/?query=ComfyUI).

You could also use those as references for making your own variant nodes if they didn't perform as desired.

**Comment by GaidamakUA** [comment]
I didn't knew civit.ai has nodes for ComfyUI. Found exactly what I was looking for. Thank you.
