### ISSUE TITLE
ComfyUI VRAM issue, using A100, but still unload and load new model for each new inference

### ISSUE THREAD

**Issue by xiaocaijiayou** [comfyanonymous/ComfyUI#2484]
My workflow:
[workflow_api_comfyui_vram.json](https://github.com/comfyanonymous/ComfyUI/files/13855612/workflow_api_comfyui_vram.json)

I am using A100, with 80G VRAM, should be sufficient. 

My workflow includes IP adapter. For each new inference, the "Apply IPadapter" Node is loading and unloading some models. 
![xo6YoJ2suy](https://github.com/comfyanonymous/ComfyUI/assets/5426787/392d2dc2-050f-4b34-9ad8-b9140e14d665)

Comfyui start info:
![8InFzXSlft](https://github.com/comfyanonymous/ComfyUI/assets/5426787/bd102e05-8504-4b15-aa2f-5262b56670e2)
I turn on the gpu-only option to ensure highvram

Is there any way to stop the model unloading and loading to make the inference faster, I should have sufficient VRAM?

**Comment by xiaocaijiayou** [comment]
@comfyanonymous Could you please share the potential solution to this? Thank you!

**Comment by NeedsMoar** [comment]
Try --gpu-only if you're not already.  Sometimes that message shows up when nothing is swapped off or onto the GPU... based on your first vs second run times (assuming those WERE the first and second) the overhead of loading the model was all in the 7.85s run, the 6.2s following didn't do anything different, then something changed with your loaded image and it needed to change the model again and took an extra second.  I'm not familiar with how exactly IPAdapters work, if they're creating weights from images they may need to load a fresh set of model weights to work on with the new image when you change images.

**Comment by ac-pill** [comment]
I'm having the exact same issue, even using --gpu-only on any IP2Adapter workflow, ClipVision and SDXL Clip Model will load again.

Requested to load CLIPVisionModelProjection
Loading 1 new model
Requested to load SDXLClipModel
Loading 1 new model

**Comment by 0x1355** [comment]
Same issue on 4090. IPAdapter part of the workflow:

![comfy_issue](https://github.com/comfyanonymous/ComfyUI/assets/4979897/313dd2b4-34b2-457f-a100-d003b5f0cc07)

`--gpu-only` doesn't change this behavior.

**Comment by RedCarrotKR** [comment]
I had the same problem, but when I added the two options below, it ran on A100 80GB.
--gpu-only --disable-cuda-malloc

**Comment by stanleyftf1005** [comment]
Any solution for this? Same issue running on A100

**Comment by TwitterBlockList** [comment]
I was struggling with this problem on RTX 4080 for two weeks and with these changes in the .bat file the problem was solved!

```
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --port 8189 --cuda-device 0 --gpu-only
pause
```

**Comment by liho00** [comment]
same issue here

**Comment by ltdrdata** [comment]
The model loading part in ipadapter cannot be handled by ComfyUI.
Inquire with the relevant repository.

https://github.com/cubiq/ComfyUI_IPAdapter_plus

**Comment by LionBuer** [comment]
same problem
