### ISSUE TITLE
[Feature Request] Comfy Manager installed by default

### ISSUE THREAD

**Issue by BarrenWardo** [comfyanonymous/ComfyUI#2487]
**Feature Details :**
Comfy Manager to be installed by default with all other dependencies while installing.

**Reason :**
At this point, I don't think anyone is using ComfyUI with Comfy Manager so I feel it would be wise to install it by default so that nobody needs to install it manually every-time Comfy is installed or reinstalled.

**Additional Suggestions :**
If there is someone who really doesn't want manager to be installed by default then there can be a command argument that can be something like this.
`
--manager true | false   (true by default, use false to skip Comfy Manager Installation)
`

_Just Suggesting An Idea. I hope it works!_

**Comment by comfyanonymous** [comment]
I can ship a script to install the manager in the standalone package but I don't want to install it by default.

**Comment by BarrenWardo** [comment]
Is this possible?

```
--manager true | false   (false by default, use true to install Comfy Manager)
```

**Comment by Amorano** [comment]
Dont love it. Some of us run comfy inside containers that already are pre-loaded. Making it so there is an automated download might break a lot of said containers that disallow going to the internet or just the generalized idea of containers.

**Comment by Weixuanf** [comment]
Maybe a param to pass a list of nodes to auto install by default at server starting?
Like `python main.py —install-nodes “comfyui-manager, animate-diff” `

it’s painful to install nodes manually in cloud gpu using command line

**Comment by BarrenWardo** [comment]
@Amorano I haven't thought about it in that way but I'll do say that if this gets implemented then it'll make cloud installation much easier going forward. Doesn't it? But as you said it'll also might break existing builds so kind of downfall for now.

@Weixuanf This is also a nice approach.

**Comment by BarrenWardo** [comment]
@ltdrdata looping you in this. Any suggestions on this from your end?

**Comment by ltdrdata** [comment]
> @ltdrdata looping you in this. Any suggestions on this from your end?

There's no particular advantage to supporting installation through the CLI in that manner.

You need to know the exact name of the custom nodes. It means you need to know exact repo url. 
In other words, there isn't much difference from installing through git clone. While it may be possible to assign nicknames to some custom nodes, it cannot be a general solution.

Batch installation of custom nodes can be addressed by leveraging the snapshot feature. If you copy the snapshot file you created to `ComfyUI-Manager/startup-scripts/restore-snapshot.json`, ComfyUI will restore to that snapshot on the first start. Currently, snapshots are limited to installing a specific version precisely, but an option can be extended to ignore versions and install the latest version.

**Comment by BarrenWardo** [comment]
@ltdrdata Thank you for your opinion.

@Amorano The only reason I asked for this feature is because of my own personal experience from newbie point of view and some people who are interested in this but struggle a lot during initial stages (especially non tech background).

Personally speaking, I've no issue installing Manager separately but I've seen people struggle with they start or move from A1111 to comfy so I was thinking by having Comfy + Manager installed by default may solve the initial struggles for many. 

I know that comfy is not made to be UI friendly but more likely to understand how all of this works but since Comfy is becoming more dominant I feel that it'll be better to make the experience a little better for new enthusiasts for easy adaption.

**Comment by Void2258** [comment]
Maybe not default but having a default OPTION would be good.

**Comment by OLH21** [comment]
I teach in schools and most users that embark Stable diffusion now are not Code Savy and mainly graphic designer.
We aim to have the easier install process. I can totally understand the expert POV but the manager should now be allowed to be install from the "setup menu" or at least with a script that also could be launched from the setup. 
Totally understand the concerns but also think of lots of users. Thanks for listening in this "small" day to day improvement

**Comment by BarrenWardo** [comment]
With the comfy-cli, I don't think we need this implementation anymore. So, closing it.
