### ISSUE TITLE
[New Suggestion] Looping Controls

### ISSUE THREAD

**Issue by jerrydavos** [comfyanonymous/ComfyUI#2488]
**Idea:**

A custom loop button on the Side Menu, how much time you wanna loop it... like Auto Queue with a cap and also make a controller node, by which loop count can be controlled by the values which comes from inside the workflow.

I am into animation in comfy, so It's will be a blessing to me, as I just have to set the loop values with incrementation so I don't have to Do again and again the same things.

This is the example animation I do with comfy: https://youtube.com/shorts/GhVfdrsKCKw breakdown [here](https://www.patreon.com/posts/update-v2-1-lcm-95056616)

During my time of testing and animations, I really wanted some node which can do provide this.

Loop Workflow Node

1. Loop Count ( Slider or In )
2. Value X to Increment ( Slider or In )
3. Increment by Y ( Slider or In )
4. Loop index ( Out ) (on which loop count it is on)
5. Looping Enable/Disabled ( 0 or 1 ) (if you don't want to use loop just yet ) ( True or False can't be rerouted :/ )
6. Nesting loops. For Eg, If Master is set to loop count of 2 and a slave node is connected to master with count of 3, After Pressing Queue :

- M - 0 | S - 0
- M - 0 | S - 1
- M - 0 | S - 2
- M - 1 | S - 0
- M - 1 | S - 1
- M - 1 | S - 2

It will run total of 6 times

And extra (optional) One Enabled/Disable Looping Node for enable global looping on or off or it can be attached on the side menu.

-------------------------------------------------------------------------

This idea can be applied to various thing, like bulk producing images with changing values, and in animations.

It will be like a better flexible version of XYZ script....

I've tested this script : https://github.com/Fannovel16/ComfyUI-Loopchain this is a very good concept by fannovel16, It's good, but not ideal for normal working, only images can be used to loop a workflow, and every time you loop it mutes other nodes and unmutes them which bugs the incrementing values so make is unusable in several cases. also loop index skips value 1 it's like ( 0,0,2,3,4,5.... ) after queuing

If someone has suggestion, custom node which can do like this please comment below, it will be a great help to me. 

Hope, it this idea can be useful for the community.😊

**Comment by Koitenshin** [comment]
I know it's not exactly what you want, but if you're looking for a way to easily set up something like XYZ grids, check out the [Impact Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack).

It has an inverted switch (one output to many), so you can just set up a bunch of Preview Image nodes to one VAE Decode node, advance whatever value you want, advance the switch (manually only it seems), and it will queue up the work to output to the nodes you've specified.

And the switches are very useful. One of my workflows has a full 21x21 Preview Image Node grid and the switch is connected to all 441 outputs. I just really wish it auto incremented.

**Comment by mcmonkey4eva** [comment]
Also [Swarm](https://github.com/mcmonkeyprojects/SwarmUI) can do that type of workflow automation/gridding/etc

For Comfy core itself the most relevant things is PR 2666 - https://github.com/comfyanonymous/ComfyUI/pull/2666 - which will be adding the ability for workflows themselves to define looped behaviors
