### ISSUE TITLE
"TypeError: Failed to fetch" on run_cpu

### ISSUE THREAD

**Issue by solipsun** [comfyanonymous/ComfyUI#2499]
When I start Queue Prompt, it appears a red "Reconecting" message. When it stops and and I start it again, the red message "TypeError: Failed to fetch" appears.

How to solve?? Thanks

**Comment by ltdrdata** [comment]
It seems you ComfyUI is killed. 
You need to check if you have sufficient memory.

**Comment by Kumo523** [comment]
If I have 4 gb vram, 16 gb ram and 50 on drive. will I be able to load comfyui?

**Comment by ltdrdata** [comment]
> If I have 4 gb vram, 16 gb ram and 50 on drive. will I be able to load comfyui?

And what model did you tried?

**Comment by Kumo523** [comment]
last update of comfyui and stable-diffusion-large-turbo.

**Comment by ltdrdata** [comment]
> last update of comfyui and stable-diffusion-large-turbo.


If you look at the file size of the model you're trying to load, you'll understand why it can't be used on your machine.

**Comment by JarnoABS** [comment]
i have a GPU AMD Radeon RX 6700 XT 12GB and appears the same message.

**Comment by Kell0s** [comment]
> i have a GPU AMD Radeon RX 6700 XT 12GB and appears the same message.

I have the same GPU and issue. Did you manage to solve it?

**Comment by Sartli** [comment]
Have you finally solved this problem? Is it because of insufficient memory?
