### ISSUE TITLE
Running server doesn't bind to 0.0.0.0

### ISSUE THREAD

**Issue by sigridjineth** [comfyanonymous/ComfyUI#2531]
As being suggested on the title, it is not being able to access to comfyui web console from outer internet when just merely running `main.py` which is not explicitly noted.

**Comment by comfyanonymous** [comment]
you have to use the --listen argument to make it bind to 0.0.0.0

**Comment by NeedsMoar** [comment]
Python-based web servers aren't really recommended to be run on outward facing networks anyway, according to the python docs themselves.  The networking stack wasn't written with security of incoming connections as a consideration.

**Comment by Ma0013** [comment]
> you have to use the --listen argument to make it bind to 0.0.0.0

where do we need to change it? im so ssorry for the noob question, but i'm stuck. thank you

**Comment by ltdrdata** [comment]
> > you have to use the --listen argument to make it bind to 0.0.0.0
> 
> where do we need to change it? im so ssorry for the noob question, but i'm stuck. thank you

If you are using portable version.
Edit `run_nvidia_gpu.bat`  and add `--listen 0.0.0.0` after --windows-standalone-build
