### ISSUE TITLE
Why is KSampler creating a batch?

### ISSUE THREAD

**Issue by lingondricka2** [comfyanonymous/ComfyUI#2543]
![Untitled](https://github.com/comfyanonymous/ComfyUI/assets/155384738/86a2c67a-b424-418e-9090-9d9ba6a1f6d3)
The custom node called AutoSegmentPrompter is basically a dummy node at this moment, it just passes the inputs through.

When I bypass my custom node it works like normal.

If this is working like intended how do I stop it?

```
class AutoSegmentPrompter:
    @classmethod
    def INPUT_TYPES(s):
        return {"required": {
                     "positive": ("CONDITIONING", ),
                     "image": ("IMAGE", ),
                     "masks": ("MASK", ),
                     },
                }
                
    RETURN_TYPES = ("CONDITIONING", "IMAGE")
    FUNCTION = "doit"

    CATEGORY = "conditioning"

    def doit(self, positive, image, masks):
        results = positive
        ann_img = image
        return (results, ann_img)
```
edit: connecting a preview node to my custom node shows 11 images also.

**Comment by ltdrdata** [comment]
It's a list, not a batch, and it happened due to SEGS To Mask List. There were 11 recognized objects, and this occurred as they were processed sequentially.

If you want to process masks all at once, use SEGSToCombinedMask.

**Comment by lingondricka2** [comment]
Hi, thanks for answering, I still need the masks as a list for my custom node. Does this mean that everything downstream will activate 11 times? Even though it has nothing to do with the mask list? I can't wrap my head around it.

**Comment by ltdrdata** [comment]
> Hi, thanks for answering, I still need the masks as a list for my custom node. Does this mean that everything downstream will activate 11 times? Even though it has nothing to do with the mask list? I can't wrap my head around it.

The fact that 11 masks are being passed to KSampler through AutoSegmentPrompter means that nothing is being left unattended.

**Comment by lingondricka2** [comment]
Thanks for taking your time and thanks for making the Impact pack, I will close this and try to come up with another solution.
