### ISSUE TITLE
chained ksampler/ksampleradvanced nodes with random seed after every gen checked should generate the same seed

### ISSUE THREAD

**Issue by doctorpangloss** [comfyanonymous/ComfyUI#255]

**Comment by Neverdusk** [comment]
I don't know - I think this would severely limit the possibilities that these nodes can produce. 

You can probably already accomplish this by using custom nodes from the WAS Suite (https://civitai.com/models/20793/was-node-suites-comfyui). It comes with a seed node, which you can chain into multiple KSamplerWAS nodes from that pack to keep the seed consistent. It also has a toggle to randomize the seed after each generation, so this should accomplish what you're after.

**Comment by marcussacana** [comment]
Try use the primitive node
![image](https://user-images.githubusercontent.com/10576957/229292327-26e695f0-ab1f-4762-a753-00f79105e16c.png)
