### ISSUE TITLE
AttributeError: 'ControlLoraAdvanced' object has no attribute 'control_model'

### ISSUE THREAD

**Issue by alessandroperilli** [comfyanonymous/ComfyUI#2558]
If an `Apply ControlNet (Advanced)` node is connected to a `KSampler (Advanced)` node, you'll see this error IF, by mistake, you have set the `steps` to a value that is smaller than the value of `start_at_step`. 

For example, step = 10 and start_at_step = 27.

It was an oversight on my side, but the error message led me astray for quite some time. 

This is the full error dump:

>     File "/xyz/ComfyUI/execution.py", line 155, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/xyz/ComfyUI/execution.py", line 85, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/xyz/ComfyUI/execution.py", line 78, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/xyz/ComfyUI/nodes.py", line 1389, in sample
>     return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/xyz/ComfyUI/nodes.py", line 1325, in common_ksampler
>     samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/xyz/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
>     return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/xyz/ComfyUI/comfy/sample.py", line 104, in sample
>     cleanup_additional_models(set(get_models_from_cond(positive_copy, "control") + get_models_from_cond(negative_copy, "control")))
>   File "/xyz/ComfyUI/comfy/sample.py", line 74, in cleanup_additional_models
>     m.cleanup()
>   File "/xyz/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 572, in cleanup_inject
>     self.base.cleanup()
>   File "/xyz/ComfyUI/comfy/controlnet.py", line 305, in cleanup
>     del self.control_model
>         ^^^^^^^^^^^^^^^^^^
> AttributeError: 'ControlLoraAdvanced' object has no attribute 'control_model'

**Comment by ltdrdata** [comment]
It belongs to https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/issues

Before reaching out for inquiries, make sure that your custom nodes are up to date and that the workflow is not using an outdated version.

**Comment by alessandroperilli** [comment]
I'd happy to open the issue there, but please notice that this error was generated by the `KSampler` node, not the Apply ControlNet (Advanced) node.  
And the `Apply ControlNet (Advanced)` node is not Kosinkadink's one, but the stock one in ComfyUI:

<img width="693" alt="Screenshot 2024-01-16 at 16 09 25" src="https://github.com/comfyanonymous/ComfyUI/assets/9775949/0cd4d589-51e0-4959-ba46-a351b71e76c9">

And yes, everything was updated at the time of reporting the issue.

**Comment by ltdrdata** [comment]
> I'd happy to open the issue there, but please notice that this error was generated by the `KSampler` node, not the Apply ControlNet (Advanced) node. And the `Apply ControlNet (Advanced)` node is not Kosinkadink's one, but the stock one in ComfyUI:
> 
> <img alt="Screenshot 2024-01-16 at 16 09 25" width="693" src="https://private-user-images.githubusercontent.com/9775949/297116885-0cd4d589-51e0-4959-ba46-a351b71e76c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjQ5MjMsIm5iZiI6MTcwNTQ2NDYyMywicGF0aCI6Ii85Nzc1OTQ5LzI5NzExNjg4NS0wY2Q0ZDU4OS01MWUwLTQ5NTktYmE0Ni1hMzUxYjcxZTc2YzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMDQxMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmVhYjRlYWY4ZmY5MWFmMTA4MjI5ZTU1MWQzYjdjMTQ3YjJhOTI1ZDQ4YTg3MmMyZDQ1OGNkYmFmNzEyZWZkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aOc6ADajfVAiY6T6l1XWLz4TZutTO3FD5hfz3Nmw2FU">
> And yes, everything was updated at the time of reporting the issue.

What matters is not where it originated, but rather which code path led to its occurrence. This issue arose as a result of the code applied by 'apply controlnet,' triggering within KSampler.
