### ISSUE TITLE
Is it possible to add options such as DPM++ 2M Karras in comfyUI?

### ISSUE THREAD

**Issue by Nanyuting** [comfyanonymous/ComfyUI#2563]
As I was learning, I realized that I had the same parameters as the course, but due to the different Sampler, the results of the drawn pictures were very different. Can comfyUI add these Samplers please?
Thank you very much.
![Sampler](https://github.com/comfyanonymous/ComfyUI/assets/112244407/8e27ce23-75a4-4ba2-8a46-55ee5d0aa5be)

**Comment by MGParisi** [comment]
> It might behoove you to read the freely available documentation if you're going to try using an advanced node based suite.

Just an FYI @poisenbery its easier to say "RTFM" as its shorter, and just as cringy and unhelpful.
Most of us stopped saying that shit in 2001.
