### ISSUE TITLE
Filename formatting not working with SaveAnimatedWEBP

### ISSUE THREAD

**Issue by Tralen** [comfyanonymous/ComfyUI#2565]
Greetings,

Currently the video saving node doesn't seem to respect the formatting filename as the SaveImage node does. To reproduce:

* Right-click the SaveAnimatedWEBP node.
* Select to export filename_prefix as widget.
* Add a primitive node with the formatting, in my case `%date:yyyy-MM-dd%/%date:hhmmss%_%KSampler.seed%`
* When the video is saved, it is named with the formatting string, without actually computing the formatting.

Thank you for this wonderful tool.

**Comment by lucianosb** [comment]
Hi @Tralen , I figured that, in the latest versions of Comfy, there is no need for an Primitive Node to format the output string. It can be done directly in the Save Image node. Give it a try and let us know.

**Comment by Tralen** [comment]
Thank you, @lucianosb, it is working great with the SaveImage node, however, it still doesn't work with the SaveAnimatedWEBP node.

**Comment by lucianosb** [comment]
Indeed... there is no function similar to applyTextReplacements() implemented there as far as I could tell.
