### ISSUE TITLE
[Question] [FeatureRequestApproval] Best approach to ComfyUI scalability, aka simultaneous generations?

### ISSUE THREAD

**Issue by MindfulPol** [comfyanonymous/ComfyUI#2579]
Is there a way to tweak ComfyUI to allow for simultaneous processing of the job queue?

I would like to be able to achieve a scalable ComfyUI API, by default prompts will simply be left on the queue and be processed 1 by 1.
I'd like to be able to scale to parallel processing without necessarily hosting more than 1 comfyui client, is it possible?

Thanks in advance for any tips or advice.

**Comment by MindfulPol** [comment]
`threading.Thread(target=prompt_worker, daemon=True, args=(q, server,)).start()`
https://github.com/comfyanonymous/ComfyUI/blob/ee2c5fa72d4fc1714576fac7ba64aa5d607303d0/main.py#L216

Would it work if I simply added more workers to the thread? would you accept a PR to have the amount of concurrent workers as a param perhaps?

**Comment by rootux** [comment]
Any updates on this? This is needed 😇

**Comment by rootux** [comment]
Im looking for a solution where different computers and gpu joins the queue and process jobs

**Comment by catsled** [comment]
> https://github.com/comfyanonymous/ComfyUI/blob/ee2c5fa72d4fc1714576fac7ba64aa5d607303d0/main.py#L216
> 
> Could it work if I simply added more workers to the thread? (will try tomorrow)
> 
> Would you accept a PR to have the amount of concurrent workers as a param perhaps?

have you tried it?

**Comment by 36590798** [comment]
Same confuse, any update on this?

**Comment by pvbang** [comment]
any update? everyone...

**Comment by shkr** [comment]
Any update ?

**Comment by ltdrdata** [comment]
Parallel processing feature is being discussed here.
https://github.com/comfyanonymous/ComfyUI/discussions/3683
