### ISSUE TITLE
Custom Sampler ignores negative conditioning

### ISSUE THREAD

**Issue by Pos13** [comfyanonymous/ComfyUI#2604]
"SamplerCustom" node returns the same result whatever negative is provided. It's especially easy to test with Auto Queue enabled: changing negative does nothing.
Other sampler nodes work fine.

**Comment by comfyanonymous** [comment]
It works fine here can you show your workflow?

**Comment by Pos13** [comment]
Can't replicate it today 😖. My workflow is a basic use of turbo scheduler:
![ComfyUI_temp_motyq_00059_](https://github.com/comfyanonymous/ComfyUI/assets/64479446/8a65ef9d-c575-44d5-b77f-4f1adff0b18d)
