### ISSUE TITLE
Auto Queue not turning off

### ISSUE THREAD

**Issue by Pos13** [comfyanonymous/ComfyUI#2605]
Checking "Auto Queue" option enables automatic re-generation. But unchecking this option does nothing: mode remains active.

**Comment by Pos13** [comment]
Btw, I want to say that "Auto Queue" is so awesome feature I don't even want to turn it off 😄. Gives me a fresh inspiration on image generation.
I'm just slightly bothered by error messages sticking to the center of the screen every time I temporarily destroy my workflow to rewire it, while "Auto Queue" is on.

**Comment by dotJack** [comment]
Issue is the logic that triggers when graph is changing does not check whether the checkbox is marked or not.

potential fix : https://github.com/comfyanonymous/ComfyUI/pull/2608

**Comment by Pos13** [comment]
Works!
