### ISSUE TITLE
Support for InstantID

### ISSUE THREAD

**Issue by haofanwang** [comfyanonymous/ComfyUI#2614]
InstantID is a new state-of-the-art tuning-free method to achieve ID-Preserving generation with only single image, supporting various downstream tasks. It was built on the top of IP-Adapter and ControlNet, and should be compatible with existing pipelines.

Code: https://github.com/InstantID/InstantID

Demo: https://huggingface.co/spaces/InstantX/InstantID

**Comment by Aruen24** [comment]
![mmqrcode1706012420168](https://github.com/comfyanonymous/ComfyUI/assets/27750891/18583b5a-ad2a-4bae-be73-d18ff76faa91)

**Comment by LuLmaster69** [comment]
An extension for A1111 already has an experimental support.

**Comment by skyler14** [comment]
The instantID support for comfyUI seems very limited compared to WebUI, so it might be better to reopen this issue
