### ISSUE TITLE
Cancel current operation?

### ISSUE THREAD

**Issue by cochese9000** [comfyanonymous/ComfyUI#262]
I'm not sure if this is supported already, so will just raise as question, rather than suggestion. 

Is there a way to cancel the current operation?  e.g. if you're processing a batch or even a single image, can it be cancelled?

I know I can kill the process, but I've had problems with re-attaching with current state in similar situations.  Anything done since the last image was saved will be lost.

**Comment by comfyanonymous** [comment]
View queue -> Running -> Cancel

**Comment by cochese9000** [comment]
Oh wow, I didn't even see that option.  Sorry.  Thanks, this is an incredible piece of work, great job!
