### ISSUE TITLE
DDIM is broken on MPS

### ISSUE THREAD

**Issue by GaidamakUA** [comfyanonymous/ComfyUI#264]
`Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.`
You did a great job an this is one line fix.
Please, replace ComfyUI/comfy/ldm/models/diffusion/ddim.py, line 21
`attr = attr.to(self.device)`
with
`attr = attr.to(torch.float32).to(self.device)`

**Comment by comfyanonymous** [comment]
So it's fixed now?

**Comment by GaidamakUA** [comment]
@comfyanonymous Yeah, it works. Thank you.
