### ISSUE TITLE
External Checkpoint Loading error 

### ISSUE THREAD

**Issue by ShashwatDubey99** [comfyanonymous/ComfyUI#2643]
Error occurred when executing CheckpointLoaderSimple:

Error while deserializing header: HeaderTooLarge

File "/comfyui/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/comfyui/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/comfyui/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/comfyui/nodes.py", line 476, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
File "/comfyui/comfy/sd.py", line 427, in load_checkpoint_guess_config
sd = comfy.utils.load_torch_file(ckpt_path)
File "/comfyui/comfy/utils.py", line 13, in load_torch_file
sd = safetensors.torch.load_file(ckpt, device=device.type)
File "/usr/local/lib/python3.10/site-packages/safetensors/torch.py", line 308, in load_file
with safe_open(filename, framework="pt", device=device) as f:
**The base model is working fine but the external models are not working**

**Comment by SashaRoberts22** [comment]
Hi- how did you end up fixing this? im getting a similar error

**Comment by Ceciliammm** [comment]
Have you ever solved the problem

**Comment by ShashwatDubey99** [comment]
> Have you ever solved the problem

I just reinstall the whole comfy setup and it was fixed

**Comment by ShashwatDubey99** [comment]
> Have you ever solved the problem

Also I downloaded the models again, this time using a download manager because I don't trust Chrome for downloading large files anymore

**Comment by Ceciliammm** [comment]
> > Have you ever solved the problem
> 
> Also I downloaded the models again, this time using a download manager because I don't trust Chrome for downloading large files anymore

I will reinstall comfyui and redownload files. Thank you very much !!!!!
