### ISSUE TITLE
blank screen when opening comfyui

### ISSUE THREAD

**Issue by jejejejajaja** [comfyanonymous/ComfyUI#2649]
I think ai it self is running fine, but comfyui screen does not show anything. does anyone know what is supposed to be the problem?

My cmd prompt shows like this.
`
```
C:\Users\bvlon\Downloads\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 6144 MB, total RAM 16315 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Starting server

To see the GUI go to: http://127.0.0.1:8188/

```

and my internet browser(chrome and also same with edge) looks like this.

![캡처](https://github.com/comfyanonymous/ComfyUI/assets/157805055/95b6c045-6a88-46e7-a2a2-4d4507601b82)

I also did the same job at my another computer, and it works. so i think my installation process isn't wrong.
also tried uninstall&reinstalling python but it does not work.

**Comment by ltdrdata** [comment]
You need to check browser console log. 
Press F12 and see console messages.

**Comment by jejejejajaja** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/157805055/2f602368-c91f-4ee5-86ee-9629861aa7e2)
ok I opened console and this error appears.. what do I have to do to solve this problem..?

**Comment by jejejejajaja** [comment]
solved it! I added the comfyui address to the trusted addresses in the vaccine app. Thank you

**Comment by adeted** [comment]
> solved it! I added the comfyui address to the trusted addresses in the vaccine app. Thank you

hi,how to added the comfyui address to the trusted addresses in the vaccine app?

**Comment by adeted** [comment]
> > solved it! I added the comfyui address to the trusted addresses in the vaccine app. Thank you
> 
> hi,how to added the comfyui address to the trusted addresses in the vaccine app?

I also solved it, I replace my broswer from chrome to firefox;  maybe the js does not adapt the chrome, change the broswer and done.

**Comment by xiaoboelse** [comment]
I have the same problem as him, but my other comfyui can be opened, but this frequently used one suddenly cannot be opened. May I ask what is going on

**Comment by lavibeats** [comment]
Hello, I have same issue. there is no console messages.

![scnrn](https://github.com/user-attachments/assets/355ccda8-6c88-4c0a-8561-3f274a83b226)
