### ISSUE TITLE
VRAM ~40% used, comfyui says otherwise

### ISSUE THREAD

**Issue by djbritt** [comfyanonymous/ComfyUI#2652]
See photo

![Screenshot from 2024-01-27 19-08-00](https://github.com/comfyanonymous/ComfyUI/assets/28036018/a54bf17f-9204-4961-a820-ec7f7887203f)

Can anyone help me figure out why nvidia-smi doesn't see what comfyui sees?

**Comment by jn-jairo** [comment]
Because it happens too fast for you to see it in the nvidia-smi, it is a fraction of a second and the nvidia-smi doesn't update that fast.
