### ISSUE TITLE
Search does not search for the title of a node

### ISSUE THREAD

**Issue by Ferocit** [comfyanonymous/ComfyUI#2669]
This screenshot shows the "Load Video (Upload)" node from the Video Helper Suite:

![2024-01-29 16_57_46](https://github.com/comfyanonymous/ComfyUI/assets/3397899/4f1e7b03-09b6-47a3-b844-f397c4400f11)

This screenshot shows the search box when I search for "video":

![2024-01-29 16_23_57](https://github.com/comfyanonymous/ComfyUI/assets/3397899/3ee7f4ba-4475-471d-a978-71e610f77838)

As you can see the node "Load Video (Upload)" does not show up. It will add the correct node if I add "VHS_LoadVideo", so I suppose the search searches and shows some internal name?! 

Suggestion:
The search should show and find nodes based on the name they have in the "Add Node" menu. That would make it more consistent and it would be easier to recreate a workflow that you have only seen a picture of.

**Comment by ltdrdata** [comment]
It would be great to have a feature to search by both node name and node title.

**Comment by ltdrdata** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/128333288/37173e2c-9483-47d3-bb47-46352b377def)

Recent ComfyUI support this.

**Comment by Ferocit** [comment]
Perfect, exactly what I needed.

![grafik](https://github.com/comfyanonymous/ComfyUI/assets/3397899/739b0889-465c-426b-ac96-dfb3d19738a7)
