### ISSUE TITLE
Feature Request: Support Differential Diffusion for inpainting.

### ISSUE THREAD

**Issue by throttlekitty** [comfyanonymous/ComfyUI#2671]
This is a nice alternative to standard inpainting, it allows for the mask to be a gradient for control of strength on top of denoising.

https://github.com/exx8/differential-diffusion

**Comment by dfl** [comment]
this looks very cool, but apparently the code hasn’t been released yet.

**Comment by throttlekitty** [comment]
True, but it's laid out quite neatly in the paper. I just don't have the chops yet to implement it.

**Comment by throttlekitty** [comment]
They've now released their code!
Since the time of my post, I learned of a PR that had been sitting on the automatic1111 repo to perform the same task, I don't know how it compares. https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/14208

**Comment by AlexD81** [comment]
could someone explain how to use it?  don't see map input in the node
