### ISSUE TITLE
_C.pyd not found

### ISSUE THREAD

**Issue by Robson1970** [comfyanonymous/ComfyUI#2673]
Error after update update_comfyui_and_python_dependencies.bat

![1](https://github.com/comfyanonymous/ComfyUI/assets/138815486/e1b057fa-81b3-4a00-83da-72f56e1c6d65)

**Comment by AmdAlex2015** [comment]
As well 
![Err](https://github.com/comfyanonymous/ComfyUI/assets/166150518/875e58a7-72ee-487d-a8e1-1fe840210962)

**Comment by AmdAlex2015** [comment]
As well: _C.pyd

**Comment by ltdrdata** [comment]
You'd better uninstall xformers and reinstall it.
It seems that part of xformers package file is corrupted.

**Comment by mashad98** [comment]
Same problem did not resolve after reinstalling xformers.. :/
anyone??

**Comment by ltdrdata** [comment]
> Same problem did not resolve after reinstalling xformers.. :/ anyone??

In that case just uninstall it.

**Comment by robinjhuang** [comment]
@mashad98 Can you try the latest standalone package and see if this still happens?
