### ISSUE TITLE
Import Failed! and the extension dont work! any solution?

### ISSUE THREAD

**Issue by merecesarchviz** [comfyanonymous/ComfyUI#2685]
Hi,

After Install the extention in, when i run the comfyui i got those errors in the cmd window and the script fail to import dont working!

those are the errors:

### Loading: ComfyUI-Inspire-Pack (V0.60.1)
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1810, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\__init__.py", line 1, in <module>
    from .InstantIDNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 14, in <module>
    from insightface.app import FaceAnalysis
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID module for custom nodes: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)
### Loading: ComfyUI-Manager (V2.4.1)

**Comment by merecesarchviz** [comment]
solved

**Comment by carlchen414** [comment]
> solved

boss, how did you solve it? i got the same issues. also tried many documents. still can't import this into ...Thank you for your time

**Comment by Profileiche** [comment]
As I was seeking for a solution to get IPAdapter Nodes running in a Stability Matrix Install of ComfyUI (which is running on Python 3.10..) I encountered the following troubles leading to 

"cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)"

The main culprit is that during the installation of ComfyUI and something like IpAdapter or something else using the module insightface, we don't get the module 'insightface' and a lot of dependencies of it. So whenever Comfy tells us that a module like 'matplotlib' is missing, you need to step out to Stability Matrix, click the three dots on the ComfyUI package, and add that modules via the Python packages (yeah.. modules, packages... who cares about words?).

Yet, when you install the 'insightface' package/module, it tends to create an error associated with the vcvarsall.bat and the build_ext command. This is when during the install, something in the building of the extension 'face3d' gets messed up. Solution: Install something else that runs Insightface (like ForgeUI) and copy the associated folders from ".\forge\system\python\" into the ".\Data\Assets\Python310\" folder of Stability Matrix. (This will only work as long as ForgeUI uses the 0.7.3 version of insightface too.) This includes:

- "Include\insightface" folder
- "insightface" folder
- "insightface" and "insightface 0.7.3 dist" folder in the .\Lib\site-packages\
- "insightface-cli.exe" from .\scripts\

I also recommend to copy the 0kb sized __init__.py from .\Lib\site-packages\insightface\thirdparty  and edit it with
`from . import mesh_core_cython
from . import mesh_core`

**Comment by eymao** [comment]
> As I was seeking for a solution to get IPAdapter Nodes running in a Stability Matrix Install of ComfyUI (which is running on Python 3.10..) I encountered the following troubles leading to
> 
> "cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)"
> 
> The main culprit is that during the installation of ComfyUI and something like IpAdapter or something else using the module insightface, we don't get the module 'insightface' and a lot of dependencies of it. So whenever Comfy tells us that a module like 'matplotlib' is missing, you need to step out to Stability Matrix, click the three dots on the ComfyUI package, and add that modules via the Python packages (yeah.. modules, packages... who cares about words?). The same applies if you have to pip install other modules/packages into your associated python source folder for the environment your ComfyUI uses.
> 
> Yet, when you install the 'insightface' package/module, it tends to create an error associated with the vcvarsall.bat and the build_ext command. This is when during the install, something in the building of the extension 'face3d' gets messed up. Solution: Install something else that runs Insightface (like ForgeUI) and copy the associated folders from ".\forge\system\python" into the ".\Data\Assets\Python310" folder of Stability Matrix. (This will only work as long as ForgeUI uses the 0.7.3 version of insightface too.) This includes:
> 
> * "Include\insightface" folder
> * "insightface" folder
> * "insightface" and "insightface 0.7.3 dist" folder in the .\Lib\site-packages\
> * "insightface-cli.exe" from .\scripts\
> 
> I also recommend to copy the 0kb sized **init**.py from .\Lib\site-packages\insightface\thirdparty and write into it
> 
> from . import mesh_core_cython from . import mesh_core
> 
> and copy it into ".Lib\site-packages\insightface\thirdparty\face3d\mesh\cython" Might not be truly necessary, but good witchcraft.. you know. Also avoids that you need to use touch in this unsacred python environment.
> 
> After that it is "just" installing the other modules/python packages it is missing until it, hopefully, runs whatever node you want using insightface.

yes. you are right. I installed the PIP package "insightface" from comfyui manager and solved this question. Thanks a lot!
