### ISSUE TITLE
lora key not loaded

### ISSUE THREAD

**Issue by ChengsongLu** [comfyanonymous/ComfyUI#2689]
got prompt
model_type EPS
adm 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
missing {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}  
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])  
lora key not loaded unet.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_k.lora.down.weight  
lora key not loaded unet.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_k.lora.up.weight  
lora key not loaded unet.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_out.0.lora.down.weight  
...  
lora key not loaded unet.up_blocks.1.attentions.2.transformer_blocks.1.attn2.to_out.0.lora.down.weight  
lora key not loaded unet.up_blocks.1.attentions.2.transformer_blocks.1.attn2.to_out.0.lora.up.weight  
lora key not loaded unet.up_blocks.1.attentions.2.transformer_blocks.1.attn2.to_q.lora.down.weight  
lora key not loaded unet.up_blocks.1.attentions.2.transformer_blocks.1.attn2.to_q.lora.up.weight  
lora key not loaded unet.up_blocks.1.attentions.2.transformer_blocks.1.attn2.to_v.lora.down.weight  
lora key not loaded unet.up_blocks.1.attentions.2.transformer_blocks.1.attn2.to_v.lora.up.weight  
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model
100%|██████████| 20/20 [00:03<00:00,  5.80it/s]
Requested to load AutoencoderKL
Loading 1 new model
Prompt executed in 6.47 seconds

**I was using HuggingFace's script for lora training, but the trained lora model seems not fit to the ComfyUI system.
Does anyone know how to fix this? Or any recommandation for training my own loras which can fit the ComfyUI?**

**Thanks!!!**

**Comment by ChengsongLu** [comment]
the whole workflow is still working while the LoRA model do nothing

**Comment by ChengsongLu** [comment]
Solved in: https://github.com/comfyanonymous/ComfyUI/issues/1144#issuecomment-1892913180

**Comment by Nanky586** [comment]
@ChengsongLu sorry but i dont see a solve there. It was closed but the issue seemed to persist but got ignored.

**Comment by ChengsongLu** [comment]
> @ChengsongLu sorry but i dont see a solve there. It was closed but the issue seemed to persist but got ignored.

If you are using hugging face's script to train your own lora, there is a file "https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_sdxl_lora_to_webui.py" which can convert the lora model to the form that fit with webui&comfyui
