### ISSUE TITLE
SRFormer Support?

### ISSUE THREAD

**Issue by novacrazy** [comfyanonymous/ComfyUI#2698]
Without really thinking I tried using [this upscale model](https://openmodeldb.info/models/4x-Frankendata-FullDegradation-SRFormer) with the standard upscale model loader and upscale image using model nodes only to quickly learn [SRFormer](https://github.com/HVision-NKU/SRFormer)-based upscale architectures are not supported. 

Gave a `KeyError: 'layers.0.residual_group.blocks.0.attn.relative_position_index'`

Would it be possible to add support for this?

**Comment by comfyanonymous** [comment]
This mode codel is under a non commercial license so it's not compatible with the ComfyUI license which is a FOSS license that allows commercial use.

That means I don't think I can add support to base comfyui unless someone rewrites the code and licenses it under a FOSS compatible license.

**Comment by novacrazy** [comment]
Is it theoretically possible for a third-party extension to patch support into the existing nodes, or are those pretty much exclusively setup for ESRGAN upscaling?

**Comment by alexgenovese** [comment]
This one is under commercial use: https://openmodeldb.info/models/4x-Nomos8kSCSRFormer

**Comment by novacrazy** [comment]
> This one is under commercial use: https://openmodeldb.info/models/4x-Nomos8kSCSRFormer

That's just one model, not an SRFormer implementation. Though [supposedly](<https://github.com/HVision-NKU/SRFormer?tab=readme-ov-file#apply-our-psa-easily>) it's fairly easy to implement the algorithm itself, it's just the example project that's non-commercial. Something similar but tailored for ComfyUI's systems might be allowed.

**Comment by mizukarada** [comment]
I've been using the [spandrel PR](https://github.com/comfyanonymous/ComfyUI/pull/2146) for a while now and have been able to use all sorts of models. I wonder what the status is on that PR.
