### ISSUE TITLE
SDXL, Sometimes it crashes sometimes it doesn't

### ISSUE THREAD

**Issue by MathematicianOnGithub** [comfyanonymous/ComfyUI#2703]
When generating SDXL stable diffusion images, it usually crashes the second time I generate something it hangs or crashes with segmentation fault. So I always have to restart the UI.
I have 8GiB NVIDIA GeForce RTX 3060 Ti.
It could be that it runs out of GPU memory. Perhaps it should unload GPU memory for CLIP or unload models to do preprocessing etc. I think the order counts.
If it tries to load too much into memory it once it will absolutely fail.
Would be nice if it could deal with this somehow.
Otherwise it works smoothly. Running nvidia-smi to check GPU memory usage, and it is probably the problem here.

If you kindly point me in the right direction I could add a patch to make it work more sparingly with memory.

**Comment by MathematicianOnGithub** [comment]
Would be nice with an "offload from GPU" node or something, that would allow one to offload models or whatever prior to loading something new

**Comment by robinjhuang** [comment]
Interesting, out of memory usually doesn't result in a segmentation fault. Can you give more details about the specific error and the workflow you are using? 

Are you using the latest version of Comfy?

**Comment by ltdrdata** [comment]
If a seg fault occurs, it's an issue that has arisen from the native code side. It could be due to a corrupt package, driver, or H/W.

**Comment by MathematicianOnGithub** [comment]
Actually I was wrong about the seg fault, I misread, it was "killed", here is the journalctl log:
Feb 02 13:19:34 iota kernel: Out of memory: Killed process 277337 (python) total-vm:56580576kB, anon-rss:7506872kB, file-rss:0kB, shmem-rss:23920kB, UID:1000 pgtables:18956kB oom_score_adj:0

**Comment by MathematicianOnGithub** [comment]
got prompt
Requested to load SDXLClipModel
Loading 1 new model
stuck on this forever after changing prompt

**Comment by MathematicianOnGithub** [comment]
Solution: Extend swapdisk RAM, I had too little RAM on my machine, it wasn't the GPU RAM that ran out but the regular RAM.

swapoff -a
dd if=/dev/zero of=/swapfile bs=1G count=32 status=progress
mkswap /swapfile
swapon /swapfile

Works fine now
