### ISSUE TITLE
No "Convert Widget to Input" option on right click

### ISSUE THREAD

**Issue by formulake** [comfyanonymous/ComfyUI#2730]
I don't know if this is related to an update or a custom-node, but this was an extremely useful feature especially with setting canvas dimensions in a single node and having that replicated in other nodes. I no longer see the convert to input and convert to widget options while right clicking a node. Any help will be greatly appreciated.
![image](https://github.com/comfyanonymous/ComfyUI/assets/7622615/9ff42bdd-3312-4e82-8176-240b2c1b4a88)

**Comment by comfyanonymous** [comment]
https://github.com/rgthree/rgthree-comfy/issues/137

**Comment by formulake** [comment]
Thank you. I apologise for the duplication.
