### ISSUE TITLE
How to make GUI changes permanent?

### ISSUE THREAD

**Issue by MortalSage** [comfyanonymous/ComfyUI#2748]
Recetly I'm facing an GUI issue on every ComfyUI startup:

The image history bar pops up and reduces my window size. 
I always move away the menu and hit "X", the bar is closed.
Move back the menu.

I don't find this experience comfy, is there no way, I can keep the bar from reappearing on every launch?
Also, the menu is often partially of screen (see screenshot).
I can see this is because of comfy manager that was added, but is there no way I can have it properly aligned once and for all?

Thank you in advance.

![Screenshot 2024-02-09 164642](https://github.com/comfyanonymous/ComfyUI/assets/147339248/cb58889f-b17d-46e4-9f55-659e051a84f5)

**Comment by ltdrdata** [comment]
That belongs to https://github.com/pythongosssss/ComfyUI-Custom-Scripts

**Comment by dchatel** [comment]
In fact, there's an option in the settings (the cog icon in the floating menu).
I think it's called "remember menu position", or something like that.

**Comment by MortalSage** [comment]
Now that you remind me of it. I have that option ticked. It works, as long as I don't close the browser. 
I just tested around a bit, I can close the window and comfy, restart everything and it "remembers" that I had the menu repositioned and the feed closed. But my browser does not save it on closing. As soon as I closed it once, I'm back to default.
Also, my default menu is not positioned correctly, probably because of it being placed first and than being expanded by comfy manager.

**Comment by dchatel** [comment]
Maybe you're blocking cookies or something. I don't know how it works exactly at this point, but it sounds like a browser configuration issue.

**Comment by MortalSage** [comment]
Yeah, I know that this is the case, I set my browser to do that myself.
Sry, I didn't explain that before.
I tried setting an exception, but it still isn't working. 
Still, would have liked if I could set default options somewhere, like I can in auto1111.

Nevermind tho, will close this issue, since it's a me problem.
