### ISSUE TITLE
"new" warnings on a CLEAN install (portable)

### ISSUE THREAD

**Issue by stephantual** [comfyanonymous/ComfyUI#2765]
ComfyUI Revision: 1965 [f44225fd] | Released on '2024-02-09'

Just a got a new Win 11 box so installed CUI on a completely unadultered machine.
There are NO 3rd party nodes installed yet.

I get the following warnings when queuing anything:

**Number 1**
```
model_type EPS
adm 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
```

**Number 2**
```
C:\AI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:325: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
```

I've been reading about these on 3rd party forums and couldn't figure out their origins. Can they be ignored safely?

Thank you.

**Comment by carlosalberto2000** [comment]
This!!!
Starting using ComfyUI yesterday and this is bugging me out!

**Comment by wangfeng35** [comment]
same here.

**Comment by adrianoamalfi** [comment]
same

**Comment by carlosalberto2000** [comment]
It does not seem to affect the output, but a little insight into this would be amazing...

**Comment by jonecky816739** [comment]
> It's fixed now.

Can tell it's not. Installed fresh windows_portable yesterday and getting all these same errors.

**Comment by stephantual** [comment]
Mmm sorry to hear that but on ### ComfyUI Revision: 2096 [6c6a3925] | Released on '2024-04-02' with 95 node sets installed, I don't see it anymore. In any case,it's harmless.

**Comment by wibur0620** [comment]
> Mmm sorry to hear that but on ### ComfyUI Revision: 2096 [[6c6a392](https://github.com/comfyanonymous/ComfyUI/commit/6c6a39251fe313c56a88c90d820009073b623dfe)] | Released on '2024-04-02' with 95 node sets installed, I don't see it anymore. In any case,it's harmless.

I have adopted a fresh installation, encountering the same issue. I've already spent three days trying to resolve it. So far, none of the methods I've tried have worked, and I also feel like the speed when using the sdxl model is not as fast as before (this might be my perception). In order to address this warning, I have switched the CUDA version in the system to 12.1 and tried different versions of Torch, but the warning persists. I want to know if this has any negative impact on my use of ComfyUI?

**Comment by powerwarlord** [comment]
> > Mmm sorry to hear that but on ### ComfyUI Revision: 2096 [[6c6a392](https://github.com/comfyanonymous/ComfyUI/commit/6c6a39251fe313c56a88c90d820009073b623dfe)] | Released on '2024-04-02' with 95 node sets installed, I don't see it anymore. In any case,it's harmless.
> 
> I have adopted a fresh installation, encountering the same issue. I've already spent three days trying to resolve it. So far, none of the methods I've tried have worked, and I also feel like the speed when using the sdxl model is not as fast as before (this might be my perception). In order to address this warning, I have switched the CUDA version in the system to 12.1 and tried different versions of Torch, but the warning persists. I want to know if this has any negative impact on my use of ComfyUI?

Same here. I am new to ComfyUi, and to try solve this the last few days still not working no matter which version of CUDA or Torch I install. Many nodes is not working such as showing meshes on TripoSR

**Comment by wibur0620** [comment]
> > > Mmm sorry to hear that but on ### ComfyUI Revision: 2096 [[6c6a392](https://github.com/comfyanonymous/ComfyUI/commit/6c6a39251fe313c56a88c90d820009073b623dfe)] | Released on '2024-04-02' with 95 node sets installed, I don't see it anymore. In any case,it's harmless.
> > 
> > 
> > I have adopted a fresh installation, encountering the same issue. I've already spent three days trying to resolve it. So far, none of the methods I've tried have worked, and I also feel like the speed when using the sdxl model is not as fast as before (this might be my perception). In order to address this warning, I have switched the CUDA version in the system to 12.1 and tried different versions of Torch, but the warning persists. I want to know if this has any negative impact on my use of ComfyUI?
> 
> Same here. I am new to ComfyUi, and to try solve this the last few days still not working no matter which version of CUDA or Torch I install. Many nodes is not working such as showing meshes on TripoSR

After reinstalling and installing 50 plugins, I noticed that it takes a long time to load the model when using the ComfyUI_VLM_nodes node. Then I saw this warning, so I reinstalled comfyui without installing any nodes and found that the warning still exists. To resolve this warning, I even reinstalled the entire Windows system, but the warning persists.

**Comment by stephantual** [comment]
> After reinstalling and installing 50 plugins, I noticed that it takes a long time to load the model when using the ComfyUI_VLM_nodes node. Then I saw this warning, so I reinstalled comfyui without installing any nodes and found that the warning still exists. To resolve this warning, I even reinstalled the entire Windows system, but the warning persists.

Friend, you're overthinking this. It's harmless. It's litterally a warning message. It has no impact on performance whatsoever. Even if it DID have an impact, it would be so small, it would be dwarfed by the comfyui general recursion issues and whatnot which happen even on a totally clean install (hence the rghtree fix). 
I have >150 node set installed, with them being updated every 3 days or so, I learned to accept the warning.
If you ABSOLUTELY want to have the best perf (client side) possible, just install 3 or 4 version of comfy with 3 or 4 different node sets. It's portable, so it's like a venv but better :)
