### ISSUE TITLE
This seems more like a bug than a notion.

### ISSUE THREAD

**Issue by GrimblyGorn** [comfyanonymous/ComfyUI#277]
When double clicking any input value regardless of where, it always selects the Value title instead of more conveniently selecting the actual value of concern:
![2023-03-26 11_51_28-ComfyUI](https://user-images.githubusercontent.com/61724196/227792107-6bd6edbc-f038-4dbe-a9a7-a71d731b5883.png)
VS:
![2023-03-26 12_07_42-ComfyUI](https://user-images.githubusercontent.com/61724196/227792176-6ec02424-f3ec-4955-b141-ee2fe58e2549.png)
Switching that could be of value? :)

**Comment by jn-jairo** [comment]
You just need one click to open the dialog to change the value, you are clicking multiples times, so the first click open the dialog, and then you are clicking on the "Value" text and selecting it.

Just click one time.

**Comment by GrimblyGorn** [comment]
Yes but my point is still valid, as is yours. Currently, I can click, then realign the mouse to the text field, then click twice and it finally selects the value. If instead, that field were already realigned to start where I clicked my double click would have saved me that mouse moving and an extra click. Lol, ocd possibly but technically more optimal too I think.

On the other hand, it could be more preferable to retain this as a safer alternative to the efficiency in that you have to make effort to select and potentially change text you may not have meant to otherwise. Pros and cons I guess. This doesn't apply to the combos or string boxes anyways. Prompts are the only ones I feel I'd ever worry about erasing accidentally, but maybe seeds are concerning I guess.

**Comment by jn-jairo** [comment]
> Yes but my point is still valid, as is yours. Currently, I can click, then realign the mouse to the text field, then click twice and it finally selects the value. If instead, that field were already realigned to start where I clicked my double click would have saved me that mouse moving and an extra click. Lol, ocd possibly but technically more optimal too I think.
> 
> On the other hand, it could be more preferable to retain this as a safer alternative to the efficiency in that you have to make effort to select and potentially change text you may not have meant to otherwise. Pros and cons I guess. This doesn't apply to the combos or string boxes anyways. Prompts are the only ones I feel I'd ever worry about erasing accidentally, but maybe seeds are concerning I guess.

I know it could be more efficient, but the graph on JavaScript is made by another library (litegraph), we can make some changes that are allowed by the library but most things aren't made to be modified.

It is possible to "hack" the library to modify things, but it is usually a difficult task.

If you know how to code feel free to try to fix it, but that may be too much work for such a small thing.
