### ISSUE TITLE
ComfyUI has "Latent From Batch" node, but not "Image From Batch" node

### ISSUE THREAD

**Issue by ArgentVASIMR** [comfyanonymous/ComfyUI#2773]
I have a situation where I've got multiple gens coming out of a single ksampler node, and I want to use multiple of them. Now, I could use the `LatentFromBatch` node for this, but then every single latent I want to use has to be processed through its own `VaeDecode` node, which feels like a waste of time.

I believe it would be wise to have an `ImageFromBatch` node to bypass this, as the whole batch is already passed through a single `VaeDecode` node in order to view them. Doesn't make sense to have to run `VaeDecode` on the same image(s) twice.

**Comment by ArgentVASIMR** [comment]
The same can be said for the `RepeatLatentBatch` node. Shown below is what I have to do if I want to repeat a single image multiple times (for re-applying the same mask to multiple gens)
![image](https://github.com/comfyanonymous/ComfyUI/assets/74772174/93303cab-ca64-4d96-a981-14a37d826cf9)

**Comment by comfyanonymous** [comment]
Added: https://github.com/comfyanonymous/ComfyUI/commit/0c9bc19768683c9e2772bd75e7bf823f976ccfba

There is already a RepeatImageBatch.

**Comment by ArgentVASIMR** [comment]
> Added: [0c9bc19](https://github.com/comfyanonymous/ComfyUI/commit/0c9bc19768683c9e2772bd75e7bf823f976ccfba)
> 
> There is already a RepeatImageBatch.

Ah, apologies, but what about image from batch?
