### ISSUE TITLE
Error occurred when executing InsightFaceLoader

### ISSUE THREAD

**Issue by moonpebbles** [comfyanonymous/ComfyUI#2780]
Hi there!

Did somebody else run into this error when executing Insigh face loader?
Any advice on how to resolve this issue would be greatly appreciated! 🙌

![Screenshot 2024-02-12 162745](https://github.com/comfyanonymous/ComfyUI/assets/159068475/d4d6e676-334a-4397-aebe-854cca389b46)
![Screenshot 2024-02-12 162922](https://github.com/comfyanonymous/ComfyUI/assets/159068475/b4ec3c33-1a24-484d-b335-ac6245e1bd9f)

**Comment by JorgeR81** [comment]
Try here:
https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162

**Comment by moonpebbles** [comment]
> Try here: [cubiq/ComfyUI_IPAdapter_plus#162](https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162)
> 
> I installed InsightFace successfully, with these instructions: https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#troubleshooting
> 
> There is also a video: https://www.youtube.com/watch?v=vCCVxGtCyho

Thank you! I will definitely try it out.🙌
