### ISSUE TITLE
Two Dialog Boxes at Startup

### ISSUE THREAD

**Issue by Torcelllo** [comfyanonymous/ComfyUI#2796]
![Python Tensor problem2](https://github.com/comfyanonymous/ComfyUI/assets/114806454/e7b7ff38-cd22-4064-adf6-144f34677b62)
![Python Tensor problem1](https://github.com/comfyanonymous/ComfyUI/assets/114806454/5610ae91-7dda-47e9-97d2-b03f144301da)

Win 10, RTX 2070 8Gb VRAM, 64Gb RAM, All ComfyUI and Nodes etc up-to-date

**Comment by ltdrdata** [comment]
Try remove torchvision package and reinstall. It seems the package is corrupted.

**Comment by Torcelllo** [comment]
I have uninstalled/reinstalled the torch+cuda, and reinstalled several times ...
