### ISSUE TITLE
Are there any plans to support the graph generation feature for StableCascade models?

### ISSUE THREAD

**Issue by petercham** [comfyanonymous/ComfyUI#2798]
RT

**Comment by HelloClyde** [comment]
The author has just committed the relevant updates and examples for supporting StableCascade.

https://github.com/comfyanonymous/ComfyUI/issues/2785?notification_referrer_id=NT_kwDOAMO3vrM5NDQ4NTI5MTc0OjEyODI2NTU4#issuecomment-1949722389
