### ISSUE TITLE
Hello author, would you please advise if this project is beneficial to us? It appears quite extraordinary and even raises skepticism.

### ISSUE THREAD

**Issue by 253701** [comfyanonymous/ComfyUI#2808]
https://github.com/showlab/X-Adapter

**Comment by VelvetToroyashi** [comment]
#2197

**Comment by LuLmaster69** [comment]
> #2197

In December 2023 there was no code released for X-Adapter.
However, the code has been released for it on github.

It's also have been confirmed to have a working Tile controlnet, which is desired by many.
