### ISSUE TITLE
A couple cascade issues I've noticed so far that will give tensor errors: (yes, I know it's a super early implementation)

### ISSUE THREAD

**Issue by RandomGitUser321** [comfyanonymous/ComfyUI#2809]
If you get the error about tensor stuff when it goes to perform the clip operations, it's likely due to weighted things (like this:0.9) or having non-standard English alphabet characters in it like ß or Ł. As soon as I removed the weights and changed to non-standard letters to regular letters, it started working just fine.

I'm sure the devs are probably aware, but this is mostly just for the people that will come here wondering why their overly decorated copy+pasted 30000 word prompts won't work.

EDIT: Actually, there might be more to it than this, I think there might be some issue with max prompt length or something as well. I noticed that I started getting the error again about `RuntimeError: The expanded size of the tensor (20) must match the existing size (2) at non-singleton dimension 1.  Target sizes: [2, 20, 77, 77].  Tensor sizes: [2, 77, 77]` by just adding a single word to the prompt. I tried adding the word painting to the start and then end of the prompt and it kept spitting the error until I removed the word entirely.

**Comment by patientx** [comment]
it wont accept " (  )  .  " either and most of the words ,there is something else going on here

**Comment by Th3Rom3** [comment]
+1 I've seen this error when using parenthesis in prompts.

**Comment by comfyanonymous** [comment]
Should be fixed now.

**Comment by Th3Rom3** [comment]
Broken parentheses seem fixed as of 6bcf57ff
