### ISSUE TITLE
ZLUDA support

### ISSUE THREAD

**Issue by LeagueRaINi** [comfyanonymous/ComfyUI#2810]
any chance we will be seeing zluda support for comfy? automatic runs *fine* for the most part but its not as nice as comfy to work with

so far when forking the repo and applying the same steps as for automatic <https://github.com/vladmandic/automatic/wiki/ZLUDA>

running it with `--disable-cuda-malloc` crashes the driver,
running it with `--disable-cuda-malloc --use-quad-cross-attention` gets further but errors out when when sampling
![raw](https://github.com/comfyanonymous/ComfyUI/assets/19365835/5eda9a5f-1a9a-4fcf-8305-cd7c42cbd5c6)

**Comment by LeagueRaINi** [comment]
Ok so i got comfy working, havent tested much beside the basic node layout but here is was i did

basic setup is the same as above
- download the zluda release from <https://github.com/vosen/ZLUDA/releases/tag/v3>
- pip uninstall torch torchvision
- pip install torch==2.2.0 torchvision --index-url https://download.pytorch.org/whl/cu118
- rename zluda's `cublas.dll` to `cublas64_11.dll`, `cusparse.dll` to `cusparse64_11.dll` and copy these to files to `venv\Lib\site-packages\torch\lib`

here is what needs to be added in the code
- add a check for zluda and if `torch.backends.cudnn.enabled` is enabled disable it as there is no cudnn support right now
- scaled_dot_product causes the driver crash so avoid it by either using `--use-quad-cross-attention` or `--use-split-cross-attention`
- 
![msedge_daqWQOOeiR](https://github.com/comfyanonymous/ComfyUI/assets/19365835/51474fc0-849a-4f30-aa7c-dc5e5328273a)

**Comment by Andyholm** [comment]
Going to try this out on my 7900xtx, I'll report back after installing.

**Comment by Andyholm** [comment]
There's no cublas.dll or cusparse.dll in the ZLUDA release
![image](https://github.com/comfyanonymous/ComfyUI/assets/23746198/6a8403f3-c277-425c-8914-f7af562ceb61)

**Comment by Andyholm** [comment]
Think I did everything, but I'm getting this error when launching:

```Traceback (most recent call last):
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\main.py", line 76, in <module>
    import execution
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\sd.py", line 4, in <module>
    from comfy import model_management
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
    _lazy_init()
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\cuda\__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx```

**Comment by CraftMaster163** [comment]
@Andyholm did you find the files they were talking about? if so where are they or how get them

**Comment by Andyholm** [comment]
@CraftMaster163 Yup! Not in the link provided, but here: https://github.com/lshqqytiger/ZLUDA/releases/tag/v3.2-win

Also just realized the main post got changed, so I'll try what they added.

**Comment by CraftMaster163** [comment]
i see the files to replace were edited out what were they, also i get this error when launching with zluda 
![image](https://github.com/comfyanonymous/ComfyUI/assets/69362326/57f4db48-135b-4c6a-aa6d-ebc0b6dfca72)

**Comment by LeagueRaINi** [comment]
> i see the files to replace were edited out what were they, also i get this error when launching with zluda ![image](https://private-user-images.githubusercontent.com/69362326/305671700-57f4db48-135b-4c6a-aa6d-ebc0b6dfca72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMDc5NTcsIm5iZiI6MTcwODIwNzY1NywicGF0aCI6Ii82OTM2MjMyNi8zMDU2NzE3MDAtNTdmNGRiNDgtMTM1Yi00YzZhLWFhNmQtZWJjMGI2ZGZjYTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDIyMDczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYWUwYjNmMDBhMjc4NzcyM2QyNjRiYjFkZDE1NzgwMDViMzg0MGIzMGNmYzk3NWI4ZWQ4NGMwOGJiOTIxOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o1C1btU7cvmq9Bwlp_w8XpIUkNR0SDh1p6XxX5wZp_Y)

they where edited out cause its described on the linked wiki entry for automatic anyways.

**Comment by Andyholm** [comment]
> Think I did everything, but I'm getting this error when launching:
> 
> ```
>   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\main.py", line 76, in <module>
>     import execution
>   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\execution.py", line 11, in <module>
>     import nodes
>   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\nodes.py", line 20, in <module>
>     import comfy.diffusers_load
>   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
>     import comfy.sd
>   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\sd.py", line 4, in <module>
>     from comfy import model_management
>   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\model_management.py", line 118, in <module>
>     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
>   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\model_management.py", line 87, in get_torch_device
>     return torch.device(torch.cuda.current_device())
>   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
>     _lazy_init()
>   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\cuda\__init__.py", line 302, in _lazy_init
>     torch._C._cuda_init()
> RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx```
> ```

The reason for my error was because I didn't install HIP sdk. I only did what OP said in the original post, but it has successfully launched now. :))

**Comment by Andyholm** [comment]
Got this now when trying to generate an image:

```Error occurred when executing CLIPTextEncode:

shape '[77, -1, 77, 77]' is invalid for input of size 5929

  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\nodes.py", line 56, in encode
    cond, pooled = clip.encode_from_tokens(tokens, return_pooled=True)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\sd.py", line 131, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\sd1_clip.py", line 514, in encode_token_weights
    out, pooled = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\sd1_clip.py", line 39, in encode_token_weights
    out, pooled = self.encode(to_encode)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\sd1_clip.py", line 190, in encode
    return self(tokens)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\sd1_clip.py", line 172, in forward
    outputs = self.transformer(tokens, attention_mask, intermediate_output=self.layer_idx, final_layer_norm_intermediate=self.layer_norm_hidden_state)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\clip_model.py", line 131, in forward
    return self.text_model(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\clip_model.py", line 109, in forward
    x, i = self.encoder(x, mask=mask, intermediate_output=intermediate_output)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\clip_model.py", line 68, in forward
    x = l(x, mask, optimized_attention)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\clip_model.py", line 49, in forward
    x += self.self_attn(self.layer_norm1(x), mask, optimized_attention)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\clip_model.py", line 20, in forward
    out = optimized_attention(q, k, v, self.heads, mask)
  File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\ldm\modules\attention.py", line 117, in attention_basic
    mask = mask.reshape(mask.shape[0], -1, mask.shape[-2], mask.shape[-1]).expand(-1, heads, -1, -1).reshape(sim.shape)```

**Comment by LeagueRaINi** [comment]
> > Think I did everything, but I'm getting this error when launching:
> > ```
> >   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\main.py", line 76, in <module>
> >     import execution
> >   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\execution.py", line 11, in <module>
> >     import nodes
> >   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\nodes.py", line 20, in <module>
> >     import comfy.diffusers_load
> >   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
> >     import comfy.sd
> >   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\sd.py", line 4, in <module>
> >     from comfy import model_management
> >   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\model_management.py", line 118, in <module>
> >     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
> >   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\comfy\model_management.py", line 87, in get_torch_device
> >     return torch.device(torch.cuda.current_device())
> >   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
> >     _lazy_init()
> >   File "C:\Users\andre\Desktop\ZLUDA COMFY\ComfyUI\venv\lib\site-packages\torch\cuda\__init__.py", line 302, in _lazy_init
> >     torch._C._cuda_init()
> > RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx```
> > ```
> 
> The reason for my error was because I didn't install HIP sdk. I only did what OP said in the original post, but it has successfully launched now. :))

vlads zluda wiki entry has been linked before, given how it works i was expect that the bare minimum is already setup but thats why i kept only the link to vlads setup now 😉

**Comment by Andyholm** [comment]
I thought you were just stating your sources, lol

**Comment by CraftMaster163** [comment]
anyone know why on a 7800xt i get the error 215 on HIP SDK installer and how to fix it?

**Comment by CraftMaster163** [comment]
anyone know why i get this error, i did what the guide said and edited the file in the issue to do the same thing
got prompt
model_type STABLE_CASCADE
adm 0
Requested to load SDXLRefinerClipModel
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 56, in encode
    cond, pooled = clip.encode_from_tokens(tokens, return_pooled=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 131, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd1_clip.py", line 514, in encode_token_weights
    out, pooled = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd1_clip.py", line 39, in encode_token_weights
    out, pooled = self.encode(to_encode)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd1_clip.py", line 190, in encode
    return self(tokens)
           ^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd1_clip.py", line 172, in forward
    outputs = self.transformer(tokens, attention_mask, intermediate_output=self.layer_idx, final_layer_norm_intermediate=self.layer_norm_hidden_state)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 131, in forward
    return self.text_model(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 97, in forward
    x = self.embeddings(input_tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 80, in forward
    return self.token_embedding(input_tokens) + self.position_embedding.weight
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\sparse.py", line 163, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\functional.py", line 2237, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Prompt executed in 3.26 seconds
i also added the flag too

**Comment by Andyholm** [comment]
@CraftMaster163 Did you install HIP SDK?

**Comment by CraftMaster163** [comment]
i did, i think the issue was i had the wrong cuda compiled torch, seems to be working now other than getting stuck loading

**Comment by CraftMaster163** [comment]
now when it loads a model and tries to use it it just crashes my system

**Comment by Andyholm** [comment]
Loading went fine for me, just took a really long time the first time.
But generating doesn't work, then I get the error I posted last.

**Comment by CraftMaster163** [comment]
before my system freezes i see it says torch not compiled with flash attention, could that be why it freezes?

**Comment by LeagueRaINi** [comment]
could u guys keep that stuff out of this issue, improper installation isnt something that needs to be discussed here, just spams everyones inbox for no reason

**Comment by Andyholm** [comment]
My installation isn't improper. I followed this https://github.com/vladmandic/automatic/wiki/ZLUDA like you said, and made the edits you did, but I still get an error. Since the error is relevant to this issue, I've posted it here.

**Comment by GUUser91** [comment]
@CraftMaster163
Here's how to fix the error 215 problem
https://github.com/ROCm/ROCm/issues/2363#issuecomment-1805043942

**Comment by CraftMaster163** [comment]
@Andyholm any luck fixing the sampling issue? im having similar issue to where cudnn has an internal error

**Comment by CraftMaster163** [comment]
@Andyholm if you getting cudnn error add torch.backends.cudnn.enabled = False to the sampling file or somewhere torch is defined

**Comment by brknsoul** [comment]
@LeagueRaINi I imagine just cloning your fork is an easy way of getting started? ;-)

**Comment by Andyholm** [comment]
@CraftMaster163 Nope, but I tested ZLUDA on vladmandic/automatic and didn't notice any speed improvements over directml. I might be doing something wrong though, but idk.

**Comment by ws132** [comment]
> 好吧，我工作得很舒服，除了基本节点布局之外还没有进行太多测试，但这就是我所做的
> 
> [这是我添加到comfy/model_management.py 的](https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/model_management.py)代码，这些`torch.backends.cuda.enable_`代码是从 vlad 所做的复制的
> 
> ```diff
> @@ -194,11 +194,10 @@ if args.fp16_vae:
>  elif args.bf16_vae:
>      VAE_DTYPE = torch.bfloat16
>  elif args.fp32_vae:
>      VAE_DTYPE = torch.float32
>  
> -
>  if ENABLE_PYTORCH_ATTENTION:
>      torch.backends.cuda.enable_math_sdp(True)
>      torch.backends.cuda.enable_flash_sdp(True)
>      torch.backends.cuda.enable_mem_efficient_sdp(True)
>  
> @@ -222,11 +221,10 @@ if args.force_fp16:
>  
>  if lowvram_available:
>      if set_vram_to in (VRAMState.LOW_VRAM, VRAMState.NO_VRAM):
>          vram_state = set_vram_to
>  
> -
>  if cpu_state != CPUState.GPU:
>      vram_state = VRAMState.DISABLED
>  
>  if cpu_state == CPUState.MPS:
>      vram_state = VRAMState.SHARED
> @@ -252,11 +250,28 @@ def get_torch_device_name(device):
>          return "{} {}".format(device, torch.xpu.get_device_name(device))
>      else:
>          return "CUDA {}: {}".format(device, torch.cuda.get_device_name(device))
>  
>  try:
> -    print("Device:", get_torch_device_name(get_torch_device()))
> +    torch_device_name = get_torch_device_name(get_torch_device())
> +
> +    if "[ZLUDA]" in torch_device_name:
> +        print("Detected ZLUDA, this is experimental and may not work properly.")
> +
> +        if torch.backends.cudnn.enabled:
> +            torch.backends.cudnn.enabled = False
> +            print("cuDNN is disabled because ZLUDA does currently not support it.")
> +
> +        torch.backends.cuda.enable_flash_sdp(True)
> +        torch.backends.cuda.enable_math_sdp(False)
> +        torch.backends.cuda.enable_mem_efficient_sdp(False)
> +
> +        if ENABLE_PYTORCH_ATTENTION:
> +            print("Disabling pytorch cross attention because it's not supported by ZLUDA.")
> +            ENABLE_PYTORCH_ATTENTION = False
> +
> +    print("Device:", torch_device_name)
>  except:
>      print("Could not pick default device.")
>  
>  print("VAE dtype:", VAE_DTYPE)
> ```
> 
> 请注意，仍然需要运行舒适，[这里](https://github.com/comfyanonymous/ComfyUI/blob/master/cuda_malloc.py#L47C5-L47C26)`--disable-cuda-malloc`对非 nvidia 卡进行简单检查可能足以不需要 arg？[](https://github.com/comfyanonymous/ComfyUI/blob/master/cuda_malloc.py#L47C5-L47C26)
> 
> ```diff
> @@ -48,11 +48,13 @@ def cuda_malloc_supported():
>      try:
>          names = get_gpu_names()
>      except:
>          names = set()
>      for x in names:
> -        if "NVIDIA" in x:
> +        if "AMD" in x:
> +            return False
> +        elif "NVIDIA" in x:
>              for b in blacklist:
>                  if b in x:
>                      return False
>      return True
> ```
> 
> ![生的](https://private-user-images.githubusercontent.com/19365835/305665072-51474fc0-849a-4f30-aa7c-dc5e5328273a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDM0NjUsIm5iZiI6MTcwOTY0MzE2NSwicGF0aCI6Ii8xOTM2NTgzNS8zMDU2NjUwNzItNTE0NzRmYzAtODQ5YS00ZjMwLWFhN2MtZGM1ZTUzMjgyNzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEyNTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlM2U5ZDQ1NmEwOGIwMWRmNmM4ZWM1Y2Y0MzMyMmE1NDIwYTc5Nzg2MmViZWZjN2IyYWJjN2I5OGFiYjdlOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W2PcSm10npsTvM2V2eqeucAEbX3ORP7lX1UnVh08jBs)

Very good, it works well on my 6900xt.
only need a simple 
```
python main.py
```
can enjoying ComfyuUI.

**Comment by patientx** [comment]
Are the errors in the end -the beginning of generation- normal ? I didn't to any generation on sdnext just did the hip install- changing library files for my 6600-zluda install- copying files the comfyui venv , and started it with checkpoints from my normal comfyui install. 

> Total VRAM 8176 MB, total RAM 16309 MB

Set vram state to: NORMAL_VRAM
Detected ZLUDA, support for it is experimental and comfy may not work properly.
Disabling cuDNN because ZLUDA does currently not support it.
Device: cuda:0 AMD Radeon RX 6600 [ZLUDA] : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints D:/comfyui/models/checkpoints/
Adding extra search path clip D:/comfyui/models/clip/
Adding extra search path clip_vision D:/comfyui/models/clip_vision/
Adding extra search path configs D:/comfyui/models/configs/
Adding extra search path controlnet D:/comfyui/models/controlnet/
Adding extra search path embeddings D:/comfyui/models/embeddings/
Adding extra search path loras D:/comfyui/models/loras/
Adding extra search path upscale_models D:/comfyui/models/upscale_models/
Adding extra search path vae D:/comfyui/models/vae/

Import times for custom nodes:
   0.0 seconds: D:\c2\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Exception in thread Thread-1 (prompt_worker):
Traceback (most recent call last):
  File "C:\Users\aslan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\aslan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\c2\main.py", line 111, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "D:\c2\execution.py", line 371, in execute
    comfy.model_management.cleanup_models(keep_clone_weights_loaded=True)
TypeError: cleanup_models() got an unexpected keyword argument 'keep_clone_weights_loaded'

**Comment by patientx** [comment]
Can this be integrated into the main already ? Have to keep editing the files all the time otherwise.

**Comment by patientx** [comment]
I forked it myself (not a dev don't know how to code just a curious fellow)  , only two files needed now (as far as I know) , I also wrote detailed instructions, it is update as of today and I am going to try to keep it that way. So feel free to try it. 

https://github.com/patientx/ComfyUI-Zluda

**Comment by VeteranXT** [comment]
Currently broken after merge https://github.com/patientx/ComfyUI-Zluda

**Comment by patientx** [comment]
> Currently broken after merge https://github.com/patientx/ComfyUI-Zluda

In what way ? Updating ? The solution is on the  [github page] (https://github.com/patientx/ComfyUI-Zluda#-whats-new-) . It is working after that update fix. In spite of that I also tried installing from zero and it is working without a hitch.

**Comment by VeteranXT** [comment]
Updating works fine.  Just when i press start it auto closes soo fast i can't see error.

**Comment by patientx** [comment]
delete everything and try from the start, I don't know whats happening. Others successfully updated in the last few hours / days.

**Comment by VeteranXT** [comment]
I did just that, ./zluda is not created on install. So i coplied mine. I've fixed it manually.

**Comment by patientx** [comment]
controlled the batch files and the zluda adress everything is all right, dunno what happened. check your bat files maybe they dont have the zluda lines somehow ...

**Comment by VeteranXT** [comment]
Its fixed. So no worries!

**Comment by Kagamine-Rinrin** [comment]
> Updating works fine. Just when i press start it auto closes soo fast i can't see error. Did following: git clone https://github.com/patientx/ComfyUI-Zluda git fetch --all git reset --hard origin/maste started lnstall.bat Started start.tab
> 
> also patch zluda dose not work Zluda is missing unpon installation.


Maybe you can add "pause" at the end of the bat file
This way you will prevent it close and then you can find the cause of the error
