### ISSUE TITLE
cascade stage_c_bf16.safetensors black image with --fp16-unet

### ISSUE THREAD

**Issue by tester4488** [comfyanonymous/ComfyUI#2824]
nvidia rtx 4060
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build **--fp16-unet**

**black image with cascade stage_c_bf16.safetensors**
all works instead with stage_c_lite_bf16.safetensors

all works fine with 
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build 
and
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build  --fp8_e4m3fn-unet

it's an issue with --fp16-unet ?

**Comment by tester4488** [comment]
same also with cascade **stage_c.safetensors** and -**-fp16-unet**

**Comment by tester4488** [comment]
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]

### ComfyUI Revision: 1992 [dccca1da] | Released on '2024-02-18'

Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Torch version: 2.1.0+cu121

**Comment by comfyanonymous** [comment]
That's normal, --fp16-unet makes it inference in fp16 and cascade stage_c doesn't work in fp16.

**Comment by tester4488** [comment]
> That's normal, --fp16-unet makes it inference in fp16 and cascade stage_c doesn't work in fp16.

ok thanks
