### ISSUE TITLE
Better Naming Convention

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#283]
The default nodes are difficult to go through and find things with a lack of consistent naming convention. CamelCaseNames, lower case underscores mixing convention types, and the lack of spaces all contribute to poor UX.

**Comment by comfyanonymous** [comment]
Those are the api names, the default names of the nodes in the UI can be changed easily. I'm just bad at naming things.

**Comment by WASasquatch** [comment]
> Those are the api names, the default names of the nodes in the UI can be changed easily. I'm just bad at naming things.

That's what I figured but the dict mapping. I may just go through then and do a PR. I wasn't entirely sure if there was a specific reason for it.
