### ISSUE TITLE
Support for Stable Cascade LoRAs and embeddings

### ISSUE THREAD

**Issue by Nerogar** [comfyanonymous/ComfyUI#2831]
I've now implemented LoRA and embedding training support in OneTrainer (for now only on a separate branch https://github.com/Nerogar/OneTrainer/tree/stable_cascade) . But to actually use them, support in the inference tools is needed. I propose the following format:

## LoRA:
Each unet key has a prefix `lora_prior_unet_`, followed by the base model key in diffusers format, then `lora_down.weight`, `lora_up.weight` and `alpha`
Each text encoder key has a prefix `lora_prior_te_`, followed by the base model key in diffusers format, then `lora_down.weight`, `lora_up.weight` and `alpha`

For the unet, I have only included lora weights for the attention blocks. But the naming scheme would be the same for other blocks.

## Embedding:
The file has a single key: `clip_g`. This is the same format as SDXL embeddings, just without the clip_l key.

## Example files
I have attached two example files. The example LoRA is for the 1B variant of stage C. Both are untrained, they are just examples to show the file format.
[examples.zip](https://github.com/comfyanonymous/ComfyUI/files/14350805/examples.zip)

For reference, I have opened the same issue for SD.Next https://github.com/vladmandic/automatic/issues/2882

**Comment by comfyanonymous** [comment]
I'm against using the diffusers format for the lora keys. I think it's more appropriate to use the key names from the original implementation in the original repo since I assume that's what most interfaces will be basing their implementations on.

**Comment by comfyanonymous** [comment]
You can use the ComfyUI format which is the same as the keys in the original implementation except the 
.attention.attn.in_proj is split into 3 like:


up_blocks.0.71.attention.attn.in_proj_bias torch.Size([6144])
up_blocks.0.71.attention.attn.in_proj_weight torch.Size([6144, 2048])

Become:

up_blocks.0.71.attention.attn.to_q.bias torch.Size([2048])
up_blocks.0.71.attention.attn.to_q.weight torch.Size([2048, 2048])
up_blocks.0.71.attention.attn.to_k.bias torch.Size([2048])
up_blocks.0.71.attention.attn.to_k.weight torch.Size([2048, 2048])
up_blocks.0.71.attention.attn.to_v.bias torch.Size([2048])
up_blocks.0.71.attention.attn.to_v.weight torch.Size([2048, 2048])

**Comment by Nerogar** [comment]
My reason for using the diffusers format was, that you need to add some kind of translation anyway. The original format has q, k and v merged into a single tensor. Apart from those attention keys, the other keys are the same.

>I assume that's what most interfaces will be basing their implementations on.

Do you have any source for that? The diffusers implementations are usually pretty popular. And for SDXL and SD the Lora keys are also based on the diffusers format.

**Comment by comfyanonymous** [comment]
a1111 and comfyui both don't use diffusers and if you take both and their derivative interfaces that's over 98% of the userbase.

That means it makes no sense to use diffusers based keys and I'm not going to write yet another key converter to support their formats.

**Comment by vladmandic** [comment]
my $0.02 - any key format is fine as long as its clearly documented.
we have to deal with multiple prefixes anyhow, it doesn't matter if its in kohya-style format or diffusers.

and yes, a1111 + comfy is large majority, but it doesn't mean they shouldn't support diffusers style loras at all. and if they are supported, key converter already exists.

**Comment by comfyanonymous** [comment]
https://civitai.com/models/314077/animegao-kigurumi-sc?modelVersionId=352392

I think this is the first public stable cascade lora, not sure what tool it was trained with but the format is one that works on comfyui right now.

**Comment by Nerogar** [comment]
> https://civitai.com/models/314077/animegao-kigurumi-sc?modelVersionId=352392
> 
> I think this is the first public stable cascade lora, not sure what tool it was trained with but the format is one that works on comfyui right now.

This one doesn't put any lora weights on the attention blocks. All the other keys are the same between the diffusers and original implementation.

I'm writing a mapping function right now to convert from diffusers to your format. I honestly don't fully agree with your opinion. But it's fine with me. As long as there is a documented format, everyone should be happy.

What do you say about the `lora_prior_unet_` prefix instead of just `lora_unet_`? My reason was to enable the possibility for prior and decoder lora weights in the same file. I don't know if anyone will even train a decoder lora, but at least this will make it possible in the future.

**Comment by Nerogar** [comment]
I've updated the example files to reflect the new format.

**Comment by mx** [comment]
Please reconsider not supporting the diffusers format. The advantages of a single file for all parts of the LoRA, vs separate files for the different networks, seem rather obvious.

**Comment by Nerogar** [comment]
@mx This has nothing to do with single file vs. mutli file. All LoRAs will be a single file. I've already changed the format to the one suggested by @comfyanonymous . The only question that remains is about the key prefix. I want to use 'lora_prior_unet', but at the moment only 'lora_unet' is supported.

**Comment by Nerogar** [comment]
There are two separate problems:
I made a mistake when translating the to_out part of the attention blocks. This is now fixed in OneTrainer.

The projection layer of the text encoder doesn't receive LoRA weights. Here are the weight names:
```
lora key not loaded lora_prior_te_text_projection.alpha
lora key not loaded lora_prior_te_text_projection.lora_down.weight
lora key not loaded lora_prior_te_text_projection.lora_up.weight
```

Do you need them in a another format, or is this just not supported at all? I already opened another issue for this a while ago, but never got an answer: https://github.com/comfyanonymous/ComfyUI/issues/1163

**Comment by Nerogar** [comment]
After looking through your code, I think you only apply LoRA weights to the "text_model" part of the text encoder. The text_projection layer is not part of that, so doesn't receive lora weights.

**Comment by comfyanonymous** [comment]
Oh the text_projection is something I can fix. I don't think I have seen any loras touch it which is why it hasn't been an issue since now.

**Comment by TripleHeadedMonkey** [comment]
FYI it's not widely known as far as I know, but Kohya has not had a fully functional text encoder training available since day one of SDXL release.

So it is not surprising that the majority of lora haven't touched a portion of the available featureset, when it is only something you can train using repo like OneTrainer or HCP Diffusion.

Furthermore it's not really a good justification for not doing something that "98% of the user base don't need it" when you are the one dictating in the first place whether it is needed, as is A1111.

If the options were made available, for this and for formats like GLORA, DYLORA and IA3, then users WOULD in fact use them. Especially people like myself who use ComfyUI as a model merge/tuning facility more than I do an image generator or anything else.

That 98% of the userbase are forced into a position whereby they are in fact not allowed to use them because of some circular self-fulfilling logic that individual developers don't themselves find the applications interesting is not something that I thought I would have to deal with so regularly as an Open Source user.

**Comment by TripleHeadedMonkey** [comment]
That said. I love the work both of you are doing in general. I just wanted to make it clear that my stance on development, if I were in your position, is one to enable people to try interesting things - whatever it is. As long as it isn't specifically going to be a massive inconvenience to achieve.

That's the way I go about creating my models at least. I add features I know it is lacking, regardless of whether I personally am into that particular style, genre or concept.

**Comment by Nerogar** [comment]
Everything seems to be working now. Closing this as completed.
