### ISSUE TITLE
Stable Cascade LORAs and CNs

### ISSUE THREAD

**Issue by BlakeOne** [comfyanonymous/ComfyUI#2847]
Please add support for Stable Cascade's LORAs and CNs, it would be awesome! :)

**Comment by earthstorm86** [comment]
Hanging out for this every day especially trying the super resolution upscaler capabilities.

**Comment by saltshaker911** [comment]
any luck with Lora's and CN's yet? Cascade is amazing so far, and these nodes would make it unstoppable!

**Comment by BlakeOne** [comment]
hurray it's supported now so closing this
