### ISSUE TITLE
Strange VRAM consumption (SDXL barely fits in 8GB VRAM)

### ISSUE THREAD

**Issue by Nekotekina** [comfyanonymous/ComfyUI#2855]
When there are reports that it's possible to use SDXL with even 6 GB VRAM, I can barely fit it in 8 and additional features like controlnet seem out of question. It looks like about 1-1.5 GB of VRAM is not properly freed which makes the huge difference for "tight" setups.

ComfyUI arguments: `python main.py --dont-upcast-attention --fp16-vae --force-fp16 --disable-smart-memory`
OS: Ubuntu 22.04
GPU: AMD Radeon RX 7600 with 8 GB VRAM, ROCm version 6.0.0
PyTorch version: 2.2.9+git029a16c (custom build with custom fake version number for compatibility issues)
torch was built specifically for gfx1102, seems my GPU is not supported otherwise.
ComfyUI version: tested recent 0d0fbabd1d153611a1c21aea3515d16339abc84f with custom patch
```patch
diff --git a/comfy/model_management.py b/comfy/model_management.py
index adcc0e8..a35eb49 100644
--- a/comfy/model_management.py
+++ b/comfy/model_management.py
@@ -4,6 +4,7 @@ from comfy.cli_args import args
 import comfy.utils
 import torch
 import sys
+import gc
 
 class VRAMState(Enum):
     DISABLED = 0    #No vram present: no need to move models to vram
@@ -534,7 +535,7 @@ def text_encoder_offload_device():
 def text_encoder_device():
     if args.gpu_only:
         return get_torch_device()
-    elif vram_state == VRAMState.HIGH_VRAM or vram_state == VRAMState.NORMAL_VRAM:
+    elif vram_state == VRAMState.HIGH_VRAM or vram_state == VRAMState.NORMAL_VRAM or vram_state == VRAMState.LOW_VRAM:
         if is_intel_xpu():
             return torch.device("cpu")
         if should_use_fp16(prioritize_performance=False):
@@ -818,9 +819,9 @@ def soft_empty_cache(force=False):
     elif is_intel_xpu():
         torch.xpu.empty_cache()
     elif torch.cuda.is_available():
-        if force or is_nvidia(): #This seems to make things worse on ROCm so I only do it for cuda
-            torch.cuda.empty_cache()
-            torch.cuda.ipc_collect()
+        torch.cuda.empty_cache()
+        torch.cuda.ipc_collect()
+        gc.collect()
 
 def unload_all_models():
     free_memory(1e30, get_torch_device())
```
I don't usually use low vram but if I do without patch the speed becomes abysmal.
Other patch is supposed to return freeing memory behaviour to normal-vram mode for AMD.

After ComfyUI startup:
![image](https://github.com/comfyanonymous/ComfyUI/assets/6028184/5868e7f7-cf7a-4c98-a744-f852f1974973)

During generation with the simplest workflow (only model + prompt):
![image](https://github.com/comfyanonymous/ComfyUI/assets/6028184/5abf288d-828b-4bb3-be66-2fda48bb2af6)

When it's finished:
![image](https://github.com/comfyanonymous/ComfyUI/assets/6028184/131ed2b9-f130-4b56-be53-385605c3b1df)

During generation with IPAdapter:
![image](https://github.com/comfyanonymous/ComfyUI/assets/6028184/82a7a44d-c602-41b4-8f1a-a411417dce6d)

When it's finished:
![image](https://github.com/comfyanonymous/ComfyUI/assets/6028184/8fbc08ba-013f-4f1e-a270-6f92eaadf77f)

In this very simple case about 300 MB or VRAM remains used when all VRAM is supposed to be freed.
If I add more things, like Lora, IPAdapter, this "additional" use can reach 1 GB or even more.
It doesn't make much sense as all this is essentially "patching" model which size in VRAM should remain the same.
IPAdapter might be extension but it doesn't explain why some extra VRAM is used even in simplest mode.

I did another experiment before, I created a pickle with memory usage snapshot for torch. It seems to show memory usage within 6G with no leaks:
![image](https://github.com/comfyanonymous/ComfyUI/assets/6028184/f7984e06-5f01-42fe-af72-31982a190145)

**Comment by Th3Rom3** [comment]
This is a very interesting observation.

In my personal observation using ROCm pytorch it feels like memory handling as a whole is less efficient than the CUDA counterparts. I might be mistaken since I don't have concrete numbers but I have run out of memory on a lot of workflows that supposedly run fine with less VRAM than my 16GB.

**Comment by Nekotekina** [comment]
Closing, as those who know, do not tell.
