### ISSUE TITLE
Unable to see KSampler previews

### ISSUE THREAD

**Issue by belladoreai** [comfyanonymous/ComfyUI#2856]
The README says:

`Use --preview-method auto to enable previews.`

I assume this means modifying the `run_nvidia_gpu.bat` file by adding that parameter there, like: `.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-method auto` and then restarting ComfyUI.

I still don't see any kind of previews on my KSamplers, though?

Are there some additional steps that I'm supposed to take to get previews visible?

**Comment by ashllay** [comment]
If you have ComfyUI Manager Menu installed just change on "Preview method", if you don't have it get it [here](https://github.com/ltdrdata/ComfyUI-Manager).

**Comment by JorgeR81** [comment]
For stable cascade you also need to put the [ previewer.safetensors ] in the "vae" folder, inside the "models" folder. 

You can get it here:
https://huggingface.co/stabilityai/stable-cascade/tree/main

**Comment by belladoreai** [comment]
> If you have ComfyUI Manager Menu installed just change on "Preview method", if you don't have it get it [here](https://github.com/ltdrdata/ComfyUI-Manager).

Thank you! I had it installed already, and had the Preview setting as disabled by default. I'm guessing that's why the previews were not showing.

**Comment by IraSarmatka** [comment]
> If you have ComfyUI Manager Menu installed just change on "Preview method", if you don't have it get it [here](https://github.com/ltdrdata/ComfyUI-Manager).

I do have the manager but I'm struggling to find this preview method

**Comment by buggsi** [comment]
> > If you have ComfyUI Manager Menu installed just change on "Preview method", if you don't have it get it [here](https://github.com/ltdrdata/ComfyUI-Manager).
> 
> I do have the manager but I'm struggling to find this preview method

Same situation, it seems to be missing in the latest version!?

**Comment by richiepic** [comment]
To rephrase it: In the ComfyUI Manager Menu, in the left Coloumn you find the "Preview method" (Third from the top)
Set it to Auto or whatever you want. There you go, now you have preview.

> > > If you have ComfyUI Manager Menu installed just change on "Preview method", if you don't have it get it [here](https://github.com/ltdrdata/ComfyUI-Manager).
> > 
> > 
> > I do have the manager but I'm struggling to find this preview method
> 
> Same situation, it seems to be missing in the latest version!? ![image](https://private-user-images.githubusercontent.com/126979392/358458017-3a3d504b-cec3-4137-896c-fe518d8aee2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzgxNzYsIm5iZiI6MTcyNTE3Nzg3NiwicGF0aCI6Ii8xMjY5NzkzOTIvMzU4NDU4MDE3LTNhM2Q1MDRiLWNlYzMtNDEzNy04OTZjLWZlNTE4ZDhhZWUyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwODA0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzU4ZDc1ZWM2ZWVlYWZjYzdlOGI0MTg3ZGVlZjkwOGJiNzgwZTQ2YTcxMGU2NDYyNmEzYzJhNzBjNDliZWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zevcEyRzXPQxhlSp3Zv1eqaN0bD9OrtulqtLq1Of__c) ![image](https://private-user-images.githubusercontent.com/126979392/358458366-dd257c49-cac4-49c0-9936-247f1457887b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzgxNzYsIm5iZiI6MTcyNTE3Nzg3NiwicGF0aCI6Ii8xMjY5NzkzOTIvMzU4NDU4MzY2LWRkMjU3YzQ5LWNhYzQtNDljMC05OTM2LTI0N2YxNDU3ODg3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwODA0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzBjOTU4OWNhZDFmOTA0YzdmYWM3N2U0OWUyMTQ1MDM4ODljZDNmMDY1MDQ1OGRiYTAwMjVmOTNiN2JjNGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S3KJ3dzH-MLukoCLkzBG9KtCL0tfIWSdwnq4pH0dHx0)
