### ISSUE TITLE
Add support for SDXL-Lightning 1 step.

### ISSUE THREAD

**Issue by PeterL1n** [comfyanonymous/ComfyUI#2863]
[SDXL-Lightning](https://huggingface.co/ByteDance/SDXL-Lightning) 1-step model requires x0-prediction type. Is there currently a way to do that? Or can we add support for it?

**Comment by comfyanonymous** [comment]
I added it a few hours ago: https://github.com/comfyanonymous/ComfyUI/commit/7faa4507ecbd2ad67afcdea44b46ecdceec75232

[workflow_x0_lightning.json](https://github.com/comfyanonymous/ComfyUI/files/14365491/workflow_x0_lightning.json)

**Comment by PeterL1n** [comment]
Amazing, I will take a look and update SDXL-Lightning repo

**Comment by PeterL1n** [comment]
It worked great. Updated the SDXL-Lightning doc. Thanks!
