### ISSUE TITLE
Won't update, gives error instead

### ISSUE THREAD

**Issue by springheeledjack66** [comfyanonymous/ComfyUI#2865]
I was having issues with downloading missing nodes with the window not showing anything, I looked in the cmd output and it said my version was too old so I tried to update and got this:

stashing current changes
nothing to stash
creating backup branch: backup_branch_2024-02-21_22_56_31
checking out master branch
pulling latest changes
Traceback (most recent call last):
  File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable\update\update.py", line 62, in <module>
    pull(repo)
  File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable\update\update.py", line 16, in pull
    repo.checkout_tree(repo.get(remote_master_id))
  File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\repository.py", line 362, in checkout_tree
    payload.check_error(err)
  File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\callbacks.py", line 98, in check_error
    check_error(error_code)
  File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\errors.py", line 65, in check_error
    raise GitError(message)
_pygit2.GitError: 13 conflicts prevent checkout
ECHO is off.
This will try to update pytorch and all python dependencies, if you get an error wait for pytorch/xformers to fix their stuff
You should not be running this anyways unless you really have to
ECHO is off.
If you just want to update normally, close this and run update_comfyui.bat instead.
ECHO is off.
Press any key to continue . . .
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (2.0.1+cu118)
Collecting torch
  Using cached https://download.pytorch.org/whl/cu118/torch-2.2.1%2Bcu118-cp310-cp310-win_amd64.whl (2704.2 MB)
Requirement already satisfied: torchvision in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (0.15.2+cu118)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.17.1%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Requirement already satisfied: torchaudio in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (2.0.2+cu118)
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/cu118/torchaudio-2.2.1%2Bcu118-cp310-cp310-win_amd64.whl (4.0 MB)
Requirement already satisfied: xformers in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (0.0.20)
Collecting xformers
  Using cached https://download.pytorch.org/whl/cu118/xformers-0.0.24%2Bcu118-cp310-cp310-win_amd64.whl (102.1 MB)
Requirement already satisfied: pygit2 in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (1.12.2)
Collecting pygit2
  Using cached pygit2-1.14.1-cp310-cp310-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: torchsde in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 2)) (0.2.5)
Collecting torchsde (from -r ../ComfyUI/requirements.txt (line 2))
  Using cached torchsde-0.2.6-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: einops in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 3)) (0.6.1)
Collecting einops (from -r ../ComfyUI/requirements.txt (line 3))
  Using cached einops-0.7.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: transformers>=4.25.1 in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 4)) (4.26.1)
Collecting transformers>=4.25.1 (from -r ../ComfyUI/requirements.txt (line 4))
  Using cached transformers-4.38.0-py3-none-any.whl.metadata (131 kB)
Requirement already satisfied: safetensors>=0.3.0 in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 5)) (0.3.1)
Collecting safetensors>=0.3.0 (from -r ../ComfyUI/requirements.txt (line 5))
  Using cached safetensors-0.4.2-cp310-none-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: aiohttp in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 6)) (3.8.4)
Collecting aiohttp (from -r ../ComfyUI/requirements.txt (line 6))
  Using cached aiohttp-3.9.3-cp310-cp310-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: accelerate in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 7)) (0.20.3)
Collecting accelerate (from -r ../ComfyUI/requirements.txt (line 7))
  Using cached accelerate-0.27.2-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: pyyaml in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 8)) (6.0)
Collecting pyyaml (from -r ../ComfyUI/requirements.txt (line 8))
  Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: Pillow in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 9)) (9.5.0)
Collecting Pillow (from -r ../ComfyUI/requirements.txt (line 9))
  Using cached https://download.pytorch.org/whl/pillow-10.2.0-cp310-cp310-win_amd64.whl (2.6 MB)
Requirement already satisfied: scipy in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 10)) (1.11.1)
Collecting scipy (from -r ../ComfyUI/requirements.txt (line 10))
  Using cached scipy-1.12.0-cp310-cp310-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: tqdm in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 11)) (4.65.0)
Collecting tqdm (from -r ../ComfyUI/requirements.txt (line 11))
  Using cached tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: filelock in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.12.2)
Collecting typing-extensions>=4.8.0 (from torch)
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: sympy in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.1)
Requirement already satisfied: jinja2 in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (2023.6.0)
Requirement already satisfied: numpy in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (1.23.5)
INFO: pip is looking at multiple versions of xformers to determine which version is compatible with other requirements. This could take a while.
Collecting xformers
  Using cached xformers-0.0.24-cp310-cp310-win_amd64.whl.metadata (1.0 kB)
  Using cached https://download.pytorch.org/whl/cu118/xformers-0.0.23.post1%2Bcu118-cp310-cp310-win_amd64.whl (97.8 MB)
  Using cached xformers-0.0.23.post1-cp310-cp310-win_amd64.whl.metadata (1.0 kB)
  Using cached https://download.pytorch.org/whl/cu118/xformers-0.0.23%2Bcu118-cp310-cp310-win_amd64.whl (97.7 MB)
  Using cached xformers-0.0.23-cp310-cp310-win_amd64.whl.metadata (1.0 kB)
  Using cached https://download.pytorch.org/whl/cu118/xformers-0.0.22.post7%2Bcu118-cp310-cp310-win_amd64.whl (97.5 MB)
  Using cached xformers-0.0.22.post7-cp310-cp310-win_amd64.whl.metadata (1.0 kB)
INFO: pip is still looking at multiple versions of xformers to determine which version is compatible with other requirements. This could take a while.
  Using cached https://download.pytorch.org/whl/cu118/xformers-0.0.22.post4%2Bcu118-cp310-cp310-win_amd64.whl (97.5 MB)
  Using cached https://download.pytorch.org/whl/cu118/xformers-0.0.22.post3%2Bcu118-cp310-cp310-win_amd64.whl (97.5 MB)
  Using cached https://download.pytorch.org/whl/cu118/xformers-0.0.22.post2%2Bcu118-cp310-cp310-win_amd64.whl (97.5 MB)
  Using cached xformers-0.0.22-cp310-cp310-win_amd64.whl.metadata (1.0 kB)
  Using cached xformers-0.0.21-cp310-cp310-win_amd64.whl.metadata (1.0 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Requirement already satisfied: pyre-extensions==0.0.29 in d:\aiimagegeneration\comfyai\comfyui_windows_portable\python_embeded\lib\site-packages (from xformers) (0.0.29)
  Using cached xformers-0.0.20-cp310-cp310-win_amd64.whl.metadata (1.1 kB)
  Using cached xformers-0.0.19-cp310-cp310-win_amd64.whl.metadata (1.1 kB)
  Using cached xformers-0.0.18-cp310-cp310-win_amd64.whl.metadata (1.1 kB)
Collecting pyre-extensions==0.0.23 (from xformers)
  Using cached pyre_extensions-0.0.23-py3-none-any.whl (11 kB)
Collecting xformers
  Using cached xformers-0.0.17-cp310-cp310-win_amd64.whl.metadata (1.1 kB)
  Using cached xformers-0.0.16-cp310-cp310-win_amd64.whl.metadata (1.1 kB)
  Using cached xformers-0.0.13.tar.gz (292 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\sprin\AppData\Local\Temp\pip-install-2sio9q23\xformers_648eece1f86f4bbf88e979f7e640e378\setup.py", line 239, in <module>
          ext_modules=get_extensions(),
        File "C:\Users\sprin\AppData\Local\Temp\pip-install-2sio9q23\xformers_648eece1f86f4bbf88e979f7e640e378\setup.py", line 157, in get_extensions
          raise RuntimeError(
      RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Press any key to continue . . .

**Comment by Clear1119** [comment]
[](https://anaconda.org/xformers/xformers/0.0.25.dev750/download/linux-64/xformers-0.0.25.dev750-py310_cu12.1.0_pyt2.2.0.tar.bz2)

Download the latest version and replace  x:\ComfyUI_windows_portable\python_embedded\Lib\site-packages\xformers & xformers-0.0.XXXX

run again "update_comfyui_and_python_dependencies.bat"

**Comment by robinjhuang** [comment]
@springheeledjack66 Were you able to update? 
If you are using the standalone build, please run `update_comfyui.bat` instead of the `update.py`.
