### ISSUE TITLE
Feature Request: add expand/collapse group nodes to ease editing

### ISSUE THREAD

**Issue by DaveMayfield** [comfyanonymous/ComfyUI#2891]
Group nodes are a great feature, but a nightmare to actually use. Whenever I need to make even the smallest change I have to "convert to nodes", make my change, and then start all over customizing the inputs, outputs, and widgets. This is quite a lengthy process when several nodes make up the group node, and I tend to make many small changes until I have it just the way I want. I have had to abandon using the feature even though it is exactly what I want. It is just too painful.

So please add "expand group node" and "collapse group node" to the menu alongside "convert to nodes". Expanding the group will of course display the underlying nodes, and it will place them in a group box with the name of the group node. The group box will store the previous group node customizations, so after I have tweaked things I can do "collapse group node" and have it become the same group node again, but with my new tweaks. The important thing is that it will reuse my previous customizations. Except for anything directly affected by my tweaks of course.

Group nodes is a great feature, and I will use it all the time when it has a couple of UX enhancements.

**Comment by ghostsquad** [comment]
yes please

**Comment by pmolodo** [comment]
Yeah, I've had the exact same experience - you keep needing to tweak the nodes, and then redo the group setup, which gets tedious fast.

An alternative implementation would be to open up a modal subwindow or separate tab with a workflow for just the grouped nodes (as opposed to a box with the nodes in the current workflow window).

Just a suggestion in case it's easier to implement - if they're equally difficult, I'd probably vote for box-within-same-window UI as @DaveMayfield suggested. Thanks!

**Comment by pixelpainter** [comment]
I was thinking about this too. I think something like rgthree fast group muter/bypass node would be perfect. A node with a list of all the groups which are contained in the workflow, which you can toggle off and on to expand and collapse (instead of mute/bypass) all nodes within the group. Also you can apply some logic to the buttons on rgthree to pick specific groups instead of having them all listed

**Comment by ltdrdata** [comment]
Please move this request to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by tresorama** [comment]
We need this! 
Someone opened this request in the frontend repo ?

**Comment by pixelpainter** [comment]
not seeing anything related to this

**Comment by geroldmeisinger** [comment]
related: https://github.com/Comfy-Org/ComfyUI_frontend/issues/1077

**Comment by behastiegit** [comment]
Yes Please
