### ISSUE TITLE
Saving SDXL checkpoints results in massive structural issues - dirty workaround attached

### ISSUE THREAD

**Issue by saftle** [comfyanonymous/ComfyUI#2898]
Considering the Save Checkpoint node from [ambw_comfyui](https://github.com/szhublox/ambw_comfyui) is in core I figured this issue belongs here as well.

Please see extensive troubleshooting, errors and workaround in the related issue: https://github.com/szhublox/ambw_comfyui/issues/4.

**Comment by comfyanonymous** [comment]
That's a problem with the other tools, position_ids isn't supposed to be saved with the CLIP weights.

**Comment by saftle** [comment]
@comfyanonymous so that indeed fixed the first kohya problem, but the 2nd part is that it has an extra key. The SD Toolkit also said that it has an extra "junk key" according to it, but it was able to recognize it at least without problems.

Is this something that should be fixed as well to keep it conform?
