### ISSUE TITLE
What version do i need of python, it says 3.10 but do you mean 3.10.* or 3.10.0?

### ISSUE THREAD

**Issue by somenewaccountthen** [comfyanonymous/ComfyUI#291]
"at the time of writing this pytorch has issues with python versions higher than 3.10 so make sure your python/pip versions are 3.10."

Specifically 3.10.0 or all 3.10.* ?

edit:
ok i got 3.10.9 now
Had to do some manual installs of dependancies (wandb and click iirc).
Working now.. 

It's really a beautiful tool.

**Comment by comfyanonymous** [comment]
Glad you got it working.

Any python 3.10.* version should work.
