### ISSUE TITLE
Saving SDXL Checkpoints results in an extra key preventing finetuning in Kohya

### ISSUE THREAD

**Issue by saftle** [comfyanonymous/ComfyUI#2923]
After the latest fix by Comfyanon the first kohya error is now thankfully fixed (https://github.com/comfyanonymous/ComfyUI/issues/2898), however now it has an issue with an extra key:

![308150625-8ac08fbd-f329-40a1-847c-66475ac36db8](https://github.com/comfyanonymous/ComfyUI/assets/852777/e06c9be5-eca1-4352-a346-7742ef6f4723)

From my understanding, the key may even be duplicated in the model which is why it think it's an extra key.

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/37a86e4618098ef1e0d692d0953f072388cbc673

This should fix it.
