### ISSUE TITLE
New comfyUI leads to an error running sdxl0.9! Is it because xformers isnt anymore in the package?

### ISSUE THREAD

**Issue by zappazack** [comfyanonymous/ComfyUI#2925]
AMD Ryzen 5900X 32 GB RAM
Niv 4070 12 GB VRAM
Error:
Error occurred when executing SaveImage:

Unable to allocate 40.5 MiB for an array with shape (2304, 1536, 3) and data type float32

**Comment by zappazack** [comment]
Update: Definitely a problem of the not supported xformer package in the new comfy ui. I have tested my workflow through comfy standalone from September 2023 and everything is fine. The RAM usage of the newer comfy ui is 20-30% higher than with xformers (old comfy) as monitored by taskmanager. It seems not always newer versions are better. 
Anyway I would appreciate another solution.

**Comment by comfyanonymous** [comment]
Are you using any custom nodes in your workflow?
