### ISSUE TITLE
how to inpaint/outpaint with sdxl?

### ISSUE THREAD

**Issue by YarvixPA** [comfyanonymous/ComfyUI#2944]
Want to know how to inpaint/outpaint with sdxl?

**Comment by huwhitememes** [comment]
Google is your friend. Go say hi sometime.

https://www.youtube.com/watch?v=akwSEjgdgs0 

https://www.youtube.com/watch?v=7Oe0VtN0cQc

https://www.reddit.com/r/comfyui/comments/177m1if/best_simple_sdxl_inpaint_workflow/
