### ISSUE TITLE
Cascade Stage C, 4secs to 5mins ?

### ISSUE THREAD

**Issue by MushroomFleet** [comfyanonymous/ComfyUI#2947]
yesterday, it would take 4 seconds to load inference on Stage C, 

today its now 5 minutes with Lora, 2.5 minutes without.

feels like something isn't using GPU? 
(but actually the GPU load is maxed out)

1. updated comfyui to latest update 2nd March 2024
2. Open Stable Cascade Workflow
3. Run it.

![image](https://github.com/comfyanonymous/ComfyUI/assets/7318371/a630d616-6d63-4ce8-a9a5-60f2914d262c)

for some reason insane loading time.

**Comment by MushroomFleet** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/7318371/7a6913a1-05c8-4bdf-87ba-edd7f6a65b00)

**Comment by MushroomFleet** [comment]
I may have been the victim of a spooky Ghost
![image](https://github.com/comfyanonymous/ComfyUI/assets/7318371/fc730e5c-e37e-4987-a653-b13fcc38a867)

I restarted the PC and all is back to normal. 
Whatever it was, it's not the update.

Spooky.

**Comment by petercham** [comment]
I'm experiencing the same thing, but not sure exactly how it's reproduced, but it happens from time to time during the constant changing of input images and Prompts
