### ISSUE TITLE
MPS mode outputs noise

### ISSUE THREAD

**Issue by kelphead** [comfyanonymous/ComfyUI#302]
I am having trouble getting MPS to output anything but noise. I am on an M2 mac with 8gb ram

I get decent results in cpu only mode, but of course, it is slow:
![ComfyUI_00027_](https://user-images.githubusercontent.com/129158546/228205771-81dcd43e-ab85-4ebb-b44b-3fbe7a8c2d05.png)

But this is what I get in MPS mode (and --use-split-cross-attention)
![ComfyUI_00031_](https://user-images.githubusercontent.com/129158546/228209075-19ef4633-788c-4567-9a56-8e485624e133.png)

The workflows should be the same in both pngs

Any ideas?

**Comment by comfyanonymous** [comment]
If you use it without: --use-split-cross-attention does it do the same thing?

**Comment by kelphead** [comment]
Yes, it does the same thing

**Comment by kelphead** [comment]
This still potatoes out, I haven't found a workaround yet

**Comment by GaidamakUA** [comment]
what sampler are you using?

**Comment by kelphead** [comment]
> what sampler are you using?

I'm using the default KSampler node.

In the meantime, the issue got resolved. I've chalked it up to a botched installation of the environment/dependencies. I binned my conda env and switched to pipenv (personal preference) and now it works.

**Comment by trivita** [comment]
> > what sampler are you using?
> 
> I'm using the default KSampler node.
> 
> In the meantime, the issue got resolved. I've chalked it up to a botched installation of the environment/dependencies. I binned my conda env and switched to pipenv (personal preference) and now it works.

happen to me too, could you give details on how you fixed the problem? thanks

**Comment by jhcrypt** [comment]
> > what sampler are you using?
> 
> I'm using the default KSampler node.
> 
> In the meantime, the issue got resolved. I've chalked it up to a botched installation of the environment/dependencies. I binned my conda env and switched to pipenv (personal preference) and now it works.

I am having the exact same issue and Image. I followed the comment but getting the same issue whether using pipenv or pyenv. Running both f16 or f32 produces a black image. This was running perfect for some time using multiple workflows. Also worth mentioning while running Image2Image with SeargeSDXL workflow (for the first time) my graphics went haywire. I've been trying to fix this for days.
