### ISSUE TITLE
PatchModelAddDownscale is not compatible with controlnet

### ISSUE THREAD

**Issue by jesenzhang** [comfyanonymous/ComfyUI#3022]
PatchModelAddDownscale is not compatible with controlnet
![image](https://github.com/comfyanonymous/ComfyUI/assets/7984556/943220e4-f1fa-4b0b-b484-9b27b8857454)

**Comment by jesenzhang** [comment]
> You probably mean "not compatible".
> 
> I have a local patch for this, but I haven't bothered submitting it upstream.
> 
> ```
> commit fa12952d61477ff903b2dd43a195c9c0a1e8e245
> Author: asagi4 <130366179+asagi4@users.noreply.github.com>
> Date:   Mon Nov 20 19:53:06 2023 +0200
> 
>     Interpolate control if size does not match
> 
> diff --git a/comfy/ldm/modules/diffusionmodules/openaimodel.py b/comfy/ldm/modules/diffusionmodules/openaimodel.py
> index d782eff..45d880a 100644
> --- a/comfy/ldm/modules/diffusionmodules/openaimodel.py
> +++ b/comfy/ldm/modules/diffusionmodules/openaimodel.py
> @@ -358,6 +358,8 @@ def apply_control(h, control, name):
>          ctrl = control[name].pop()
>          if ctrl is not None:
>              try:
> +                if ctrl.shape[2] != h.shape[2] or ctrl.shape[3] != h.shape[3]:
> +                    ctrl = F.interpolate(ctrl.float(), size=(h.shape[2], h.shape[3]), mode="bicubic", align_corners=False).to(h.dtype)
>                  h += ctrl
>              except:
>                  logging.warning("warning control could not be applied {} {}".format(h.shape, ctrl.shape))
> ```

I tried it and it worked，Thanks！

**Comment by tgitit** [comment]
PatchModelAddDownscale still creates these warnings when used with controlnet.

warning control could not be applied torch.Size([2, 1280, 9, 6]) torch.Size([2, 1280, 18, 12])
warning control could not be applied torch.Size([2, 1280, 9, 6]) torch.Size([2, 1280, 18, 12])
warning control could not be applied torch.Size([2, 1280, 9, 6]) torch.Size([2, 1280, 18, 12])
warning control could not be applied torch.Size([2, 1280, 18, 12]) torch.Size([2, 1280, 36, 24])
warning control could not be applied torch.Size([2, 1280, 18, 12]) torch.Size([2, 1280, 36, 24])
etc

**Comment by Goodwillson** [comment]
Thank you for the patch, it works. Could be included into comfy?

**Comment by stephennilor** [comment]
Thanks! You should submit this as PR, it seems like it mostly works but really should be included in Comfy by now and iterated on in some capacity given that this is essentially what is needed to get it from not working at all to functioning!

> You probably mean "not compatible".
> 
> I have a local patch for this, but I haven't bothered submitting it upstream.
> 
> ```
> commit fa12952d61477ff903b2dd43a195c9c0a1e8e245
> Author: asagi4 <130366179+asagi4@users.noreply.github.com>
> Date:   Mon Nov 20 19:53:06 2023 +0200
> 
>     Interpolate control if size does not match
> 
> diff --git a/comfy/ldm/modules/diffusionmodules/openaimodel.py b/comfy/ldm/modules/diffusionmodules/openaimodel.py
> index d782eff..45d880a 100644
> --- a/comfy/ldm/modules/diffusionmodules/openaimodel.py
> +++ b/comfy/ldm/modules/diffusionmodules/openaimodel.py
> @@ -358,6 +358,8 @@ def apply_control(h, control, name):
>          ctrl = control[name].pop()
>          if ctrl is not None:
>              try:
> +                if ctrl.shape[2] != h.shape[2] or ctrl.shape[3] != h.shape[3]:
> +                    ctrl = F.interpolate(ctrl.float(), size=(h.shape[2], h.shape[3]), mode="bicubic", align_corners=False).to(h.dtype)
>                  h += ctrl
>              except:
>                  logging.warning("warning control could not be applied {} {}".format(h.shape, ctrl.shape))
> ```
