### ISSUE TITLE
Images tab widget not available since last update 

### ISSUE THREAD

**Issue by d-kobi** [comfyanonymous/ComfyUI#3037]
![Screenshot 2024-03-13 at 17 04 12](https://github.com/comfyanonymous/ComfyUI/assets/139005649/7b331cc3-c4f2-41e2-b50f-3471a6d5bf99)

The image icon is no longer available in the UI and I cannot find a way to make the images history tab appear anymore.

**Comment by ltdrdata** [comment]
That feature belongs to https://github.com/pythongosssss/ComfyUI-Custom-Scripts

**Comment by d-kobi** [comment]
Thanks! Didn't remember that :P
