### ISSUE TITLE
CLI option to run workflows

### ISSUE THREAD

**Issue by rne1223** [comfyanonymous/ComfyUI#304]
It would be nice to have a cli to run the workflows created by the UI.

**Comment by comfyanonymous** [comment]
There's this: https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py

**Comment by robinjhuang** [comment]
@rne1223 Try our cli tool! https://github.com/Comfy-Org/comfy-cli

`comfy launch --background`
`comfy run --workflow <path to workflow file>`
