### ISSUE TITLE
High CPU and GPU usage while idle on the comfyui page

### ISSUE THREAD

**Issue by deepfree2023** [comfyanonymous/ComfyUI#3045]
I'm not sure why, but perhaps due to the recent updates to comfyui, I noticed that there is a consistent high CPU and GPU usage when I have the comfyui page open without performing any actions. Both the CPU and GPU usage remain about 20%. However, the issue is immediately resolved when I switch to other webpages, but come back if I switch to comfyui again.

**Comment by J-Cott** [comment]
I have this exact issue, still on the latest version, I am starting to think it is a bitcoin miner in a custom node or something.

**Comment by huchenlei** [comment]
> I have this exact issue, still on the latest version, I am starting to think it is a bitcoin miner in a custom node or something.

Please file an issue with reproduction steps in https://github.com/Comfy-Org/ComfyUI_frontend/issues. Thanks!
