### ISSUE TITLE
Using API with cloudflare url?

### ISSUE THREAD

**Issue by jayceftg** [comfyanonymous/ComfyUI#3046]
When I used the API via
`req =  request.Request("http://127.0.0.1:8188/prompt", data=data)`
on the remote machine, it works.

However, if I use the cloudflare url instead of 127.0.0.1:8188, it doesn't connect and gives a 403 error. 
`raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 403: Forbidden` Has any one used the API with the clourdflare url?

**Comment by PKS-formido** [comment]
Hi, how did you resolve this issue?

**Comment by trojblue** [comment]
+1 on this
