### ISSUE TITLE
how to convert the workflow.json to the api ["/prompt"] `s  props

### ISSUE THREAD

**Issue by Laixinsz** [comfyanonymous/ComfyUI#3050]
how to convert the workflow.json to the api ["/prompt"] `s  props
如何将保存的工作流json文件转为/prompt提示词列队接口需要的入参。

**Comment by bigcat88** [comment]
Save in API format from ComfyUI web interface

**Comment by liusida** [comment]
To add my two cents: in `Settings`, `Enable Dev mode Options` first, and you'll see the "Save (API format)" button.

**Comment by ltdrdata** [comment]
> Save in API format from ComfyUI web interface

You can't. prompt data doesn't contains workflow.
