### ISSUE TITLE
How to not open the default browser at startup

### ISSUE THREAD

**Issue by ac169** [comfyanonymous/ComfyUI#3117]
Startup parameter **-auto-launch** can be configured to open the default browser at startup, but I did not add this parameter in my script. Is there a parameter that can be turned off to automatically start the browser.

**Comment by DivannKokos** [comment]
--disable-auto-launch

**Comment by ac169** [comment]
> --disable-auto-launch

Thank you, I try it, but there is no introduction to this parameter in the document I found.

**Comment by ac169** [comment]
main.py: error: unrecognized arguments: --disable-auto-launch

**Comment by DivannKokos** [comment]
hm, are you on windows? write full bat/how you launch

**Comment by ac169** [comment]
> hm, are you on windows? write full bat/how you launch

**ComfyUI_windows_portable_nvidia_cu118_or_cpu_31_07_2023**

run_nvidia_gpu.bat

The current normal startup script

```
.\python_embeded\python.exe -s ComfyUI\main.py --listen 192.168.1.100 --port 8000 --windows-standalone-build
pause
```

I personally think there are differences in the versions

**Comment by DivannKokos** [comment]
you didn't write where you've tried to add the command but for me at least its working after --windows-standalone-build
i.e. my is 
```
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-auto-launch
pause
```
difference in the versions? i don't know, i run the latest

**Comment by ac169** [comment]
> you didn't write where you've tried to add the command but for me at least its working after --windows-standalone-build i.e. my is
> 
> ```
> .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-auto-launch
> pause
> ```
> 
> difference in the versions? i don't know, i run the latest

It has nothing to do with the parameter order, I think it should be because the version I am using has not yet added or removed this option. Reference: [how to prevent auto launch?](https://www.reddit.com/r/comfyui/comments/15ly7y3/comment/jvdn35v/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) Expected after removing the `--windows-standalone-build`
