### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'clientId')

### ISSUE THREAD

**Issue by emil302s** [comfyanonymous/ComfyUI#3120]
I was running the nightly build for a while and then decided to run the updater. This caused the UI to give me the error "TypeError: Cannot read properties of undefined (reading 'clientId')" when I try to queue the prompt. So, I decided to run the 26_02_2024 build, but the problem persists. It gives no errors in the console.
<img width="1030" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/15109742/65e7beed-86fd-4d8d-98ca-a3fc51e6b001">

**Comment by MultiChen** [comment]
How did you solve this problem?

**Comment by emil302s** [comment]
> How did you solve this problem?

As far as I can remember, I removed a custom node that caused this issue.

**Comment by MultiChen** [comment]
> > How did you solve this problem?
> 
> As far as I can remember, I removed a custom node that caused this issue.

Thank you for your reply and solution ideas
