### ISSUE TITLE
Websocket is very unstable and often stuck without sending any messages

### ISSUE THREAD

**Issue by axel578** [comfyanonymous/ComfyUI#3128]
For the API websocket is very unstable, even using the comfy ui websocket code,
You can just test it out and use it with several models, sometimes you will see if the generation is intensive/hard.
Even thow the computer is running fine, the websocket won't transmit progress when generating an image and ws.recv() will wait indefinetly.

My whole program is broken because of this, and the worse is with cascade that litterally crashes randomly the websocket.

To reproduce this issue:
use comfy ui api code template.
use several models several times, you will encounter the issue.

Of course it won't happen if your test case is limited to one call/generation, try to call it multiple times one after the other, and try switching models.

I tried many thing to debug the underlying issue, but I can't manage to find out, its really killing any API call use case, and I don't want to use diffusers as everybody knows why.

**Comment by bigcat88** [comment]
Hm. I didn’t notice this, we used ComfyUI with a websocket for 50-200 runs of different flows (2/3 cascade passes, platform + refiners, photomaker) and everything was fine.
Code in ComfyUI mostly related to message signalling this is here: 
https://github.com/comfyanonymous/ComfyUI/blob/c6de09b02e20d748739fb6af58e196ebdd12825a/execution.py#L271-L399

and inside `recursive_execute` function that called in a cycle.

---
_In our situation in the end we just realized that we don't need websocket at all since we can just execute ComfyUI workflows directly using its **Prompt_executor** class and not keep it running as a separate process.
It’s good that the ComfyUI code is written so that this is quite easy to do without changing anything in Comfy itself :)_

**Comment by comfyanonymous** [comment]
Can you give more details about how you are running ComfyUI and where you are running it? Are you running ComfyUI on a server and running your client from a home internet connection?

**Comment by axel578** [comment]
`import websocket #NOTE: websocket-client (https://github.com/websocket-client/websocket-client)
import uuid
import json
import urllib.request
import urllib.parse
import datetime
import requests
import threading
import select
import time

server_address = "127.0.0.1:8188"
client_id = str(uuid.uuid4())

id_request = -1


def send_async_post_request(id, progress):
    def target():
        url = ''  # Replace with your server's actual URL
        data = {

        }
        try:
            requests.post(url, json=data)
        except Exception as e:
            print(f"Error sending request: {e}")

    thread = threading.Thread(target=target)
    thread.start()


"""def queue_prompt(prompt):
    print("Queuing prompt")
    p = {"prompt": prompt, "client_id": client_id}
    data = json.dumps(p).encode('utf-8')
    req =  urllib.request.Request("http://{}/prompt".format(server_address), data=data)
    print(req)
    return json.loads(urllib.request.urlopen(req).read())"""

def queue_prompt(prompt):
    print("Queuing prompt")
    p = {"prompt": prompt, "client_id": client_id}
    data = json.dumps(p).encode('utf-8')
    # Create the request object with the URL and the data to be sent
    req = urllib.request.Request("http://{}/prompt".format(server_address), data=data)
    # Add the 'Content-Type' header to specify the type of data being sent
    req.add_header('Content-Type', 'application/json')
    print(req)
    # Send the request and read the response
    response = urllib.request.urlopen(req).read()
    # Convert the response from JSON format to a Python dictionary and return it
    return json.loads(response)

def get_image(filename, subfolder, folder_type):
    data = {"filename": filename, "subfolder": subfolder, "type": folder_type}
    url_values = urllib.parse.urlencode(data)
    with urllib.request.urlopen("http://{}/view?{}".format(server_address, url_values)) as response:
        return response.read()

def get_history(prompt_id):
    with urllib.request.urlopen("http://{}/history/{}".format(server_address, prompt_id)) as response:
        return json.loads(response.read())
def receive_message_with_timeout(ws, timeout=20.0):
    start_time = time.time()  # Record the start time
    while True:
        elapsed_time = time.time() - start_time
        remaining_time = timeout - elapsed_time
        if remaining_time <= 0:
            print("Timeout: No data received in {} seconds.".format(timeout))
            break  # Exit if the total timeout has elapsed

        # Wait for data to be ready with a maximum wait of remaining_time, checking every 0.1 seconds for data
        ready = select.select([ws], [], [], min(0.1, remaining_time))
        if ready[0]:  # If data is ready
            try:
                out = ws.recv()
                # Process the received message
                print("Received:", out)
                return out  # Exit after processing the message
            except websocket.WebSocketTimeoutException:
                print("WebSocketTimeoutException: No data received.")
                break  # Handle the timeout exception as needed
            except Exception as e:
                print("Error:", str(e))
                break  # Handle other exceptions as needed
        # Optional: Perform any periodic checks or keep-alive signals here if needed

def get_images(ws, prompt, timeout):
    global id_request
    prompt_id = queue_prompt(prompt)['prompt_id']
    print(prompt_id)
    output_images = {}
    progress_bar = 0.0
    last_progress = None
    last_status = None
    last_post_progress = None
    while True:
        #{'type': 'progress', 'data': {'value': 1, 'max': 20}}
        if last_progress is not None:
            current_time = datetime.datetime.now()
            time_diff = (current_time - last_progress).total_seconds()
            if time_diff > timeout:
                print("No images: Progress last updated more than "+str(timeout)+" seconds ago.")
                return {}  # Return no images
        if last_status is not None:
            current_time = datetime.datetime.now()
            time_diff = (current_time - last_status).total_seconds()
            if time_diff > timeout*2:
                print("No images: Status last updated more than "+str(timeout*2)+" seconds ago.")
                return {}  # Return no images
        print("Loading a new message ...")
        if progress_bar > 0.0:
            out = receive_message_with_timeout(ws, timeout)
            """ready = select.select([ws], [], [], 55)
            if ready[0]:
                out = ws.recv()
                # Process the received message
            else:
                print("Timeout: No data received in {} seconds.".format(55))
                break  # Or handle timeout as needed"""
        else:
            out = receive_message_with_timeout(ws, timeout-5)
        print("New message loaded ...")
        if isinstance(out, str):
            message = json.loads(out)
            print("[COMFY SERVER MSG]:")
            print(message)
            #send_async_post_request
            if message['type'] == 'progress':

                print("matched progress for "+str(id_request))
                if last_progress == None:
                    last_progress = datetime.datetime.now()
                if last_post_progress == None:
                    if id_request != None:
                        if id_request != -1:
                            print("Sending Update progress request on the way")
                            send_async_post_request(id_request, int((message['data']['value']/message['data']['max'])*100))
                            progress_bar = int((message['data']['value']/message['data']['max'])*100)
                            last_post_progress = datetime.datetime.now()
                elif (datetime.datetime.now() - last_post_progress).total_seconds() > 2.5:
                    print("Sending Update progress request for "+str(id_request))
                    if id_request != None:
                        if id_request != -1:
                            print("Sending Update progress request on the way")
                            send_async_post_request(id_request, int((message['data']['value']/message['data']['max'])*100))
                            last_post_progress = datetime.datetime.now()
                last_progress = datetime.datetime.now()
                last_status = datetime.datetime.now()
            if message['type'] == 'status':
                last_status = datetime.datetime.now()
            if message['type'] == 'executing':
                data = message['data']
                if data['node'] is None and data['prompt_id'] == prompt_id:
                    break #Execution is done
            # Check if last_progress is more than 20 seconds ago
        
        else:
            continue #previews are binary data
    print("TO history")
    history = get_history(prompt_id)[prompt_id]
    print(history)
    for o in history['outputs']:
        for node_id in history['outputs']:
            node_output = history['outputs'][node_id]
            if 'images' in node_output:
                images_output = []
                for image in node_output['images']:
                    image_data = get_image(image['filename'], image['subfolder'], image['type'])
                    images_output.append(image_data)
            output_images[node_id] = images_output
    print("output images: \n")
    print(str(output_images)[:20])
    progress_bar = 0
    return output_images




from flask import Flask, request, jsonify
import json

app = Flask(__name__)

# Dummy function to generate images; replace with your actual image generation code.
def generate_images(prompt, timeout):
    print("generating image")
    prompt = prompt
    print("starting")
    ws = websocket.WebSocket()
    print("loading")
    ws.connect("ws://{}/ws?clientId={}".format(server_address, client_id))
    print("Connected or ?")
    print(ws)
    images = get_images(ws, prompt, timeout)
    return images

import base64

def binary_to_base64_png(data):
    # Create a dictionary to store the base64-encoded PNG data
    base64_data = {}

    for key, binary_list in data.items():
        # Create an in-memory PNG image for each binary
        base64_images = []
        for binary in binary_list:
            # Encode the binary data in base64
            encoded_image = base64.b64encode(binary).decode("utf-8")
            
            # Add the PNG MIME type
            base64_with_mime = f"data:image/png;base64,{encoded_image}"
            base64_images.append(base64_with_mime)

        # Store the result in the dictionary
        base64_data[key] = base64_images

    return base64_data

is_previous_cascase=False
#stable_cascade_stage_b
@app.route('/generate_images/<int:id>', methods=['POST'])  # Updated route
def get_generated_images(id):
    global id_request
    global is_previous_cascase
    try:
        id_request = id
        print("statting..;")
        data = request.get_json()
        print(data)
        prompt = data
        timeout=25
        if "super" in str(prompt):
            timeout = 120
            is_previous_cascase = True
        elif is_previous_cascase == True:
            is_previous_cascase = False
            timeout = 90
        if not prompt:
            return jsonify({'error': 'Invalid JSON data'}), 400
        
        images = binary_to_base64_png(generate_images(prompt, timeout))  # Replace with your image generation logic
        print(str(images)[:100])
        return jsonify({'images': images}), 200
    except Exception as e:
        print(str(e))
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':`


Very sorry for the slow response, Here is the full coded (beware I edited the website api call on the first function.

As you will see in my code, I really tried everything to make it stable, but either I did something wrong (very probably but I can't manage to find), either websocket is too unstable (I did other projects with websocket without any problems its weird I know).

As you can see I'm running a flask API.
I'm running the API on my home computer ( its a small project I made right now).
The internet is honestly really good, I have other websockets usig socket IO working really fine. However here locally (yeah the websocket is communicating to a comfy ui instance on the same machine).

I get some weird issues like:
Not receiving any messages even thow I can see the progress bar increasing on comfy ui side,
The image generated sometimes taking more than 40 seconds to be received by the websocket, and sometime snot even half a second.

**Comment by axel578** [comment]
> Can you give more details about how you are running ComfyUI and where you are running it? Are you running ComfyUI on a server and running your client from a home internet connection?

I really fails on the ws.recv randomly, like the websocket is not receiving any more messages dont worry about the timeout its not the issue,really the webocket is not receiving anything randomly

**Comment by axel578** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/44734791/876784c5-6ed8-4756-96c7-537844259652)
Its following really some kind of patterns where 1/4 times its failing. Like I don't receive any new messages from websocket for too long (even thow here I didn't switched models at all).

**Comment by axel578** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/44734791/43a6524d-4475-47a6-9f95-e04d68e3f4a5)
Here is one, it got stuck on 1/10 and stopped sending messages, I don't receive any messages after that, I activated debug on websocket put it said nothing.

**Comment by axel578** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/44734791/bf85a60b-f82e-4e99-98d8-7b957cf6ffd3)
I modified main.py of comfy ui to debug, its actually sending the messae, but now randomly the websocket is not receiving any

**Comment by axel578** [comment]
Just fixed by removing the select, its the one in fault here.

**Comment by axel578** [comment]
Not fixed my bad, the ws.recv still doesnt receive anything :/ noo

**Comment by axel578** [comment]
My receive code is the following:
```python
def receive_message_with_timeout(ws, timeout=20.0):
    start_time = time.time()  # Record the start time
    while True:
        elapsed_time = time.time() - start_time
        remaining_time = timeout - elapsed_time
        if remaining_time <= 0:
            print("Timeout: No data received in {} seconds.".format(timeout))
            break  # Exit if the total timeout has elapsed

        # Wait for data to be ready with a maximum wait of remaining_time, checking every 0.1 seconds for data
        print("preparing new message")
        print("Asking new message")
        out = ws.recv()
        # Process the received message
        print("Received:", out)
        
```

I really tried everything this time.

**Comment by bigcat88** [comment]
did you create a new websocket connection after each prompt?

**Comment by axel578** [comment]
Dont do the same error to create a new websocket each time, I don't know why I did that.

**Comment by abaybektursun** [comment]
+1 connections keeps timing out randomly (websocket client on the same system, localhost). Even after 100 retries, it keep hanging when trying to get the progress, although generation continues no problem.

**Comment by abaybektursun** [comment]
Looks like I had a branch in my code that left unclosed connection. Seems like to prevent timeouts one must always close out the connection before starting a new request

**Comment by ekleziast** [comment]
any updates there? I run multiple ComfyUI instances on different ports with different GPUs, open a new websockets connection on each request and close the connection after processing is complete but it still stucks at random time. What is the correct way to handle the ComfyUI API? Should I leave one connection without breaking it, or should I open a new one for each request?
