### ISSUE TITLE
Showing which custom nodes are missing will be great.

### ISSUE THREAD

**Issue by liusida** [comfyanonymous/ComfyUI#3141]
For example, when I load a graph from JSON file, very often I'll see errors like this:
![image](https://github.com/comfyanonymous/ComfyUI/assets/14249458/b4bd39d3-7c2a-4e55-951f-0292c4297248)

However, this error message is not that informative, because I don't know what custom nodes should be installed for those types. So I need to google them one by one, and read the posts to guess the names for the custom nodes.

I think it'll be great to also show the custom node names, for example, `ComfyUI-Advanced-ControlNet`, so it'll save users a lot of time.

Thanks again for this great project.

**Comment by simartem** [comment]
have you got  (https://github.com/ltdrdata/ComfyUI-Manager) ?
it installs missing nodes in a workflow

**Comment by liusida** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/14249458/faae71d4-fb0c-4fac-bc1e-7c82d39b16c1)
Thanks! I found it!
