### ISSUE TITLE
about Queue Prompt panel

### ISSUE THREAD

**Issue by Li1177** [comfyanonymous/ComfyUI#3175]
I have a very simple question: for some reason, the Queue Prompt panel of my comfyui can't be moved around freely with the mouse anymore. Can you tell me how to adjust it?

![image](https://github.com/comfyanonymous/ComfyUI/assets/110624605/ae765484-177b-4004-863e-1bb40986feaf)

**Comment by mord0d** [comment]
On small resolution (≈1366×768, 1280×1024 maybe) or with large zoom (which logically equivalent to small resolution), the menu is pinned to the right side.

I don't think it's a good idea (it's *painful* to use ComfyUI from a smartphone) but that's how it works.

**Comment by Li1177** [comment]
> On small resolution (≈1366×768, 1280×1024 maybe) or with large zoom (which logically equivalent to small resolution), the menu is pinned to the right side.
> 
> I don't think it's a good idea (it's _painful_ to use ComfyUI from a smartphone) but that's how it works.


My question is that I have always been running comfyui on Colab. Previously, I could move the Queue Prompt panel, but recently, it suddenly became immovable. This happened right after an update that introduced CPU and GPU monitoring features. After that update, the panel got locked in place and couldn't be moved anymore.

**Comment by Li1177** [comment]
Previously, this panel could be moved freely, but after adding a CPU/GPU status monitor, it became immovable. My runtime environment is Colab, and I use the Chrome browser. I adjusted the browser's display to zoom out to 80%, and now I can move it freely again.

**Comment by mord0d** [comment]
> an update that introduced CPU and GPU monitoring

This is a third party module named [Comfyui-Chrystools](https://github.com/crystian/ComfyUI-Crystools), it's not part of ComfyUI itself.

*// Sorry for necroposting.*
