### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm) for simple workflow

### ISSUE THREAD

**Issue by CPapadim** [comfyanonymous/ComfyUI#3179]
I'm running a simple wokflow (attached) that is giving this error.  I ran extensive testing to try to isolate it and stripped down the workflow as much as possible.  I can reproduce this in ComfyUI without any custom nodes installed (aside from the Manager). 

It occurs in workflows that load multiple models and use at least one ControlNet.  The more models the more likely.  For example, in the attached workflow at the bottom of this post, I am using two controlnets and a Conditioning Combine, and because of the Conditioning (Combine) controlnets are requested twice.

```
Requested to load BaseModel
Requested to load ControlNet
Requested to load ControlNet
Requested to load ControlNet
Requested to load ControlNet
Loading 5 new models
```

In this setup I can reproduce the error.  If I remove one of the controlnets or remove the Conditioning (Combine) so that only two Request to Load ControlNet are made, the error doesn't occur.   

The behavior is that the first run works fine, but if I run the workflow again it gives this error.  In investigating this someone suggested that the perhaps first time all models and embeds are in CPU, during the generation they are moved to the GPU and some node doesn't bring them back to the CPU before processing, but I can't confirm this myself.  It's also the case that the first run after changing parameters (like controlnet strength) can have the subsequent run work, but it once again starts failing afterwards. 

Currently running it on 4070 8GB VRAM 16GB Ram.  These workflows were working fine prior to me updating Comfy in the past few days.   I am not seeing any out of memory errors.

I also tried running with `python -m main --force-fp16` but same issue

Here is the debug workflow that I've cut down as much as possible while still being able to reproduce the error reliably

[debug_workflow.json](https://github.com/comfyanonymous/ComfyUI/files/14817645/debug_workflow.json)

It's very barebones.  It uses two combined positive prompts, two controlnets chained in a sequence, and a KSamplerAdvanced.

And the Traceback

```
Requested to load ControlNet
Loading 1 new model
  0%|                                                                                                                                                       | 0/20 [00:00<?, ?it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/ComfyUI/nodes.py", line 1403, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
  File "/ComfyUI/nodes.py", line 1339, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/ComfyUI/comfy/sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/ComfyUI/comfy/samplers.py", line 705, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/ComfyUI/comfy/samplers.py", line 610, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/ComfyUI/comfy/samplers.py", line 548, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/BaseVENV/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ComfyUI/comfy/samplers.py", line 286, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ComfyUI/comfy/samplers.py", line 273, in forward
    return self.apply_model(*args, **kwargs)
  File "/ComfyUI/comfy/samplers.py", line 270, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "/ComfyUI/comfy/samplers.py", line 250, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "/ComfyUI/comfy/samplers.py", line 198, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
  File "/ComfyUI/comfy/controlnet.py", line 182, in get_control
    control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint, timesteps=timestep.float(), context=context.to(dtype), y=y)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ComfyUI/comfy/cldm/cldm.py", line 287, in forward
    emb = self.time_embed(t_emb)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ComfyUI/comfy/ops.py", line 52, in forward
    return super().forward(*args, **kwargs)
  File "/BaseVENV/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
```

**Comment by CPapadim** [comment]
I tried running with `--gpu-only` and the error goes away, giving credence to the idea mentioned that somehow the models not being correctly moved between CPU and GPU being the issue.

**Comment by CPapadim** [comment]
I reverted to this commit https://github.com/comfyanonymous/ComfyUI/commit/40e124c6be01195eada95e8c319ca6ddf4fd1a17 prior to a variety of model loading and unloading changes and the error goes away, so whatever is causing it seems to be part of changes to how models are loaded / unloaded.

**Comment by comfyanonymous** [comment]
I can confirm this is a bug and I'll fix it soon.

**Comment by comfyanonymous** [comment]
Should be fixed now.

**Comment by jokero3answer** [comment]
> 我尝试运行`--gpu-only`，错误消失了，这证实了提到的想法，即模型没有在 CPU 和 GPU 之间正确移动是问题所在。

This problem has appeared again. How can I fix it? How to mobilize only the gpu?

**Comment by Zeelyne** [comment]
same problem occured when i ran my workflow, this bug appeared at the Ksampler node. I added  "--gpu-only" in my run_nvidia_gpu.bat and it didnt work.

**Comment by Zeelyne** [comment]
> I tried running with `--gpu-only` and the error goes away, giving credence to the idea mentioned that somehow the models not being correctly moved between CPU and GPU being the issue.

Would you please show me how to insert this `--gpu-only` command? I am newbie to comfyUI and am not very familiar with the script. Thanks a lot!!

**Comment by dnrghostfox** [comment]
> 我可以确认这是一个错误，我会很快修复它。

The same problem, confused for several days, was encountered when running the ipadapter flux workflow

**Comment by rookieron321** [comment]
same issue encountered loading PulID flux the error occurs when the workflw goes through sampler custom advanced node was working fine before

**Comment by pipCloneMe** [comment]
Got the same error with PuLID Flux, used to work well.

**Comment by verybigelephants** [comment]
this error happens even on fal.ai's comfy instance

**Comment by magicvr** [comment]
> > I tried running with `--gpu-only` and the error goes away, giving credence to the idea mentioned that somehow the models not being correctly moved between CPU and GPU being the issue.
> 
> Would you please show me how to insert this `--gpu-only` command? I am newbie to comfyUI and am not very familiar with the script. Thanks a lot!!


What he meant is, in your root directory, open the run_nvidia_gpu.bat file that you usually use to start, open it with Notepad, and load the end of the first line (remember the space)

**Comment by Phrosh** [comment]
--gpu-only fixes the issue for me, but is slow AF.
I tried --lowvram and this works like a charm.
Maybe ComfyUI tries to prevent OOM and screws things up with that...

**Comment by rootliuat** [comment]
> Got the same error with PuLID Flux, used to work well.
I also have this problem. Is there a solution?

**Comment by Cyl0nius** [comment]
Still get the ERROR even with modified run.bat:

.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --gpu-only
pause


Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

ComfyUI do not care, still swapping between CPU and GPU.

2025-01-14 17:11:45 INFO     move vae and unet to cpu to save memory                     flux_train_network_comfy.py:164                    INFO     move text encoders to gpu

**Comment by id-Colin** [comment]
The CLIP Text Encode (Prompt) node will report an OOM error if the parameter --gpu-only is used. The Apply PuLID Flux node will report an error RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument tensors in method wrapper_CUDA_cat) if this parameter is not used. I only have 4G video memory. Is it impossible to use PuLID Flux?

**Comment by PriMaVeraFS** [comment]
> Should be fixed now.

I'm still having this issue when using grounding dino node.

**Comment by ltdrdata** [comment]
The device mismatch issue caused by a custom node cannot be resolved in the ComfyUI core. It needs to be addressed in the respective custom node repository.

**Comment by Ithriel86** [comment]
I found for myself that the missmatch was in where the controlnet image was loaded. I fixed the issue by routing the image through a node called "image to deivce" from comfyui_essentials right before the applycontrolnet node and setting it to the matching device, "gpu" in my case.
