### ISSUE TITLE
[Feature Request] support multi-GPUs by Device ID in parameters.

### ISSUE THREAD

**Issue by AI-Robot-Morris** [comfyanonymous/ComfyUI#319]
Hi there,

pls help to support Multi-GPUs by Device ID running in different instances, coz we are teaching this ComfyUI in our class, this multi-GPU feature can save our time and money to setup machine for learning. We can setup 4 gpus in one machine to support 4 stduents use ComfyUI currently. DONT need to prepare 4 machine for 4 students learning.

Please help and provide this feature in coming days
Thanks millions

**Comment by comfyanonymous** [comment]
You can now use: 

--cuda-device to set the device id that a ComfyUI instance will use like this: --cuda-device 1

**Comment by AI-Robot-Morris** [comment]
brilliant!!! it works excellent,  thanks millions.
