### ISSUE TITLE
The comfy.samplers.calc_cond_uncond_batch function is deprecated please use the calc_cond_batch one instead.

### ISSUE THREAD

**Issue by DamienCz** [comfyanonymous/ComfyUI#3196]
When I use the sd upscale in ComfyUI, the command window keeps popping up with the warning "WARNING: The comfy.samplers.calc_cond_uncond_batch function is deprecated please use the calc_cond_batch one instead." but the program continues to run...

![微信图片_20240403231616](https://github.com/comfyanonymous/ComfyUI/assets/132655237/3523a8b5-efdf-4278-b6b9-9b0fb75c5e55)
![微信图片_20240403231621](https://github.com/comfyanonymous/ComfyUI/assets/132655237/e0dba449-b49d-46c6-a0ad-9579423dfdda)

**Comment by ltdrdata** [comment]
This is warning message for custom node developer.
