### ISSUE TITLE
Generate batch of images inside same latent space(fixed latent noise / seed?)

### ISSUE THREAD

**Issue by brandostrong** [comfyanonymous/ComfyUI#3198]
In Auto1111, in the txt2image section you have the ability to generate images within the same latent space. For example, with the seed and prompt static, changing the controlnet driving image will lead to a small difference in the output image. This is the same for a small change in prompt.

In Comfyui however, making a batch of latents but only changing the controlnet per latent will produce wildly different images, even with the same seed.

Is there any existing node that can copy Auto1111's behavior in this? It greatly improves consistency on batch animations, because the sampler isn't sampling from a new latent space each latent.

**Comment by ltdrdata** [comment]
What you are talking about means applying noise generated with the same seed to all frames within a batch. From what I remember, there is a feature that allows you to set it to work in such a way when sampling using https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved.

**Comment by ltdrdata** [comment]
AFAIK, there is no feature provided to collapse messages at the warning level.

**Comment by NeedsMoar** [comment]
The LatentBatchSeedBehavior node set to fixed will produce very similar images across a batch, the default is random I think.  It should be a built-in node.

**Comment by brandostrong** [comment]
> What you are talking about means applying noise generated with the same seed to all frames within a batch. From what I remember, there is a feature that allows you to set it to work in such a way when sampling using https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved.

Hi, this is pretty much the answer I'm looking for. It's not *exactly* like auto1111's, there's more flicker and randomness, but it's pretty close. Thank you.

**Comment by Lalimec** [comment]
Is there a way to keep the seed literally fixed? That node doesnt seem to work correctly.

![image](https://github.com/comfyanonymous/ComfyUI/assets/65521426/19cff942-211f-4e92-8e70-ec30f188d93f)
![image](https://github.com/comfyanonymous/ComfyUI/assets/65521426/87a701b0-0c88-493a-a98c-31f64040c46a)

**Comment by ltdrdata** [comment]
Make sure you are not using stochastic sampler.  ( _ancestral, _sde)

**Comment by Lalimec** [comment]
So its not possible to use a stochastic sampler and get the same seeds in a batch you say? I have a wf which outputs a person in different ages, so i need to keep the seed same through out the images, to reduce unwanted changes. It is obviously possible if I gave ksampler a "list" of prompts and set the seed to fixed. But generating in batches is a little more faster, so I wanted to utilize that. 

![image](https://github.com/comfyanonymous/ComfyUI/assets/65521426/c20c0c26-be23-4d0f-a130-e847bd5bb501)

**Comment by ltdrdata** [comment]
In a stochastic sampler, randomness is added intermittently during the sampling process. The seed only determines the initial noise of the latent, but it does not control the randomness of the sampling process.

**Comment by Lalimec** [comment]
Interesting, do you know any non-stochastic sampler that works with turbo models? I was using dpm++ sde with these ones, since it's a lengthy generaion i would like to keep the step count as low as its possible.
