### ISSUE TITLE
Allow for nodes to define whether they default to a widget or input

### ISSUE THREAD

**Issue by HaydenReeve** [comfyanonymous/ComfyUI#3205]
Hello 👋

I've run into a small problem that I've realised I can't solve in a straightforward manner using a custom node.

This issue arises when you want to create a node with a string, int, or other primitive, as an input by default. I don't want to invoke the widget as a side effect of a node input.

The problem:

I am creating a stacking string node. It's an incredibly simple implementation of a default multiline string that allows for easier visibility into prompts in a node-based style.

Now, that's fine, they work great and I'm quite happy. But, I want to add stacking. Stack multiple text nodes into each other, therefore combining their contents as a concat.

It's quite simple to add another string input, but there does not appear to be a way to display the widget as an input by default. I don't want to display two text boxes to the user as that leads to a confusing interaction.

Ideally, it should be

| IN | OUT |
|--------|--------|
| INPUT: String | STRING |
| WIDGET: Multiline String | 

This would take the String, add it to the multiline string at the front, then output the result. The current implementation of the string node allows only for this:

| IN | OUT |
|--------|--------|
|  | STRING |
| WIDGET: Multiline String | 
| WIDGET: Multiline String | 

We are specifically talking about node default formats here.

I'm vaguely aware that you can append specific node formats to nodes somehow (I';ve seen colours and shapes defined as defaults) but I think it would be beneficial for this functionality to be applied as a default.

I've been diving into the UI with pycharm recently and trying to familiarise myself with the repo, but I'm no python guru by an stretch so I'm making slow progress.

At least now I have a document to work from here, and maybe other people are able to add their thoughts. I do intend to follow this up with a PR hopefully soon, but guidance beyond my rather narrow vision scope would be appreciated.

Currently, my solution thinks to add another argument alongside multiline to allow a widget to default to an input instead, like `"widget=true"` in the argument section.

Hopefully that makes sense to everyone reading.

**Comment by HaydenReeve** [comment]
Here's a visual example.

This is the current implementation and the desired default output for this functionality:

![image](https://github.com/comfyanonymous/ComfyUI/assets/39004735/230e659c-320b-48cc-8e7c-aec42f768e5f)

But by default, these nodes will initialise as a widget:

![image](https://github.com/comfyanonymous/ComfyUI/assets/39004735/542f9a2f-f605-4c5c-ac09-f3c732eed4ff)

Which means you actually end up with a rather confusing interface.

**Comment by Quasimondo** [comment]
One workaround that you could use, which is not super-elegant is to use the "any type" input type "*" instead of "STRING". Of course this means that you will have to check the validity of your input in your code:
`"optional": {"chain": ("*",  ),  }`

**Comment by HaydenReeve** [comment]
This isn't actually a half-bad workaround. You would basically leverage the native `.ToString()` kind of call to let it consume most inputs in this way as well...

I like it!

The downside is that it's less explicit, but unless comfy decides to support these features I think it may be the most viable solution.

**Comment by Spinaster** [comment]
I'm not sure how it could e related with the initial issue but I'm running into the same problem since a month now and I can't understand how to fix it.

I'm having the same issue with almost every node that allow a text input. By default thy miss this input and if I try to switch from widget to input there's no options for that.

This happened to different nodes from different pack so it's not related to the nodes itself, It's seam to be a Comfy issue that propagate to all that kind of input nodes.

Any help?

**Comment by ltdrdata** [comment]
Currently, this functionality is supported through `'defaultInput': True` or `'forceInput': True`.
'defaultInput' creates the widget as an input when the node is generated, and it can be switched to a widget.
'forceInput' allows the widget to exist only as an input.

**Comment by Spinaster** [comment]
Thank you for the answer.
Do you know how to fix that in Comfy?
Is there a procedure to change or reset this behaviour to all the nodes as a default state?

I'm not developing nodes, this behaviour happen when I just use the nodes in Comfy.
Thanks

**Comment by ltdrdata** [comment]
> Thank you for the answer. Do you know how to fix that in Comfy? Is there a procedure to change or reset this behaviour to all the nodes as a default state?
> 
> I'm not developing nodes, this behaviour happen when I just use the nodes in Comfy. Thanks

This feature is at the development level for custom node developers.

**Comment by HaydenReeve** [comment]
> Currently, this functionality is supported through `'defaultInput': True` or `'forceInput': True`. 'defaultInput' creates the widget as an input when the node is generated, and it can be switched to a widget. 'forceInput' allows the widget to exist only as an input.

You beauty.

I'll dig into this soon with my nodes and hopefully come away with a very big smile on my face. Cheers!

**Comment by HaydenReeve** [comment]
This worked like a treat. Thank you.

I noticed that unless you include the `'forceInput': True` text, it adds an over-exaggerated amount of padding between the inputs and the text box, but that is a different issue.

**Comment by ltdrdata** [comment]
Unfortunately, the documentation is still in progress. Please note that this feature was added through a PR.
https://github.com/comfyanonymous/ComfyUI/pull/318
https://github.com/comfyanonymous/ComfyUI/pull/1452

**Comment by schoenid** [comment]
Thank you!
