### ISSUE TITLE
LCM Scheduler

### ISSUE THREAD

**Issue by davedaverave** [comfyanonymous/ComfyUI#3213]
Error occurred when executing LCMScheduler:

module 'comfy.samplers' has no attribute 'calculate_sigmas_scheduler'

File "/notebooks/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/notebooks/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/notebooks/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/notebooks/ComfyUI/custom_nodes/ComfyUI-sampler-lcm-alternative/sampler_lcm_alt.py", line 81, in get_sigmas
sigmas = comfy.samplers.calculate_sigmas_scheduler(model.model, "sgm_uniform", total_steps).cpu()

**Comment by WeiQingSong** [comment]
nnnn

**Comment by Ari-Wagner** [comment]
same problem
In fact, until a few hours ago, before updating some nodes everything was working fine for me.

**Comment by comfyanonymous** [comment]
Replace  `comfy.samplers.calculate_sigmas_scheduler(model.model, "sgm_uniform", total_steps)` in that custom_nodes/ComfyUI-sampler-lcm-alternative/sampler_lcm_alt.py custom node with: 

`comfy.samplers.calculate_sigmas_scheduler(model.get_model_object("model_sampling"), "sgm_uniform", total_steps)`

**Comment by mike-rowley** [comment]
@comfyanonymous 
That change doesn't work for me.  The error message is 'comfy.samplers' has no attribute 'calculate_sigmas_scheduler' so changing the parameters in the call to calculate_sigmas_scheduler is not going to help as calculate_sigmas_scheduler is the problem.

**Comment by Ari-Wagner** [comment]
@comfyanonymous
didn't work for me either

**Comment by comfyanonymous** [comment]
Here this should work:

Replace  `comfy.samplers.calculate_sigmas_scheduler(model.model, "sgm_uniform", total_steps)` in that custom_nodes/ComfyUI-sampler-lcm-alternative/sampler_lcm_alt.py custom node with: 

`comfy.samplers.calculate_sigmas(model.get_model_object("model_sampling"), "sgm_uniform", total_steps)`

**Comment by Ari-Wagner** [comment]
@comfyanonymous
it's working, thanks!!

**Comment by davedaverave** [comment]
Thanks :)

**Comment by Unnonamed** [comment]
It's work Update all
