### ISSUE TITLE
BNK_TiledKSampler:  module 'comfy.sample' has no attribute 'convert_cond'

### ISSUE THREAD

**Issue by attyru** [comfyanonymous/ComfyUI#3221]
```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\TOOLS\GIT\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\TOOLS\GIT\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\TOOLS\GIT\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\TOOLS\GIT\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 320, in sample
    return sample_common(model, 'enable', seed, tile_width, tile_height, tiling_strategy, steps_total, cfg, sampler_name, scheduler, positive, negative, latent_image, steps_total-steps, steps_total, 'disable', denoise=1.0, preview=True)
  File "C:\TOOLS\GIT\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 124, in sample_common
    positive_copy = comfy.sample.convert_cond(positive)
AttributeError: module 'comfy.sample' has no attribute 'convert_cond'
```

Hello. After the update I started to have similar problems on different nodes. It is advised to update extensions, but it is unlikely that some extensions will receive fixes in the near future. Is it possible to return attributes from previous versions as stubs?
SeargeSDXL:
`ImportError: cannot import name 'prepare_mask' from 'comfy.sample' (C:\TOOLS\GIT\ComfyUI\comfy\sample.py)`
ComfyUI_smZNodes (fixed):
`AttributeError: module 'comfy.samplers' has no attribute 'CFGNoisePredictor'`

**Comment by TheBill2001** [comment]
Relevance report BlenderNeko/ComfyUI_TiledKSampler#42.

**Comment by Evilinside3357** [comment]
I have the same problem with the unsampler node:

!!! Exception during processing !!!
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Noise/nodes.py", line 221, in unsampler
    positive = comfy.sample.convert_cond(positive)
AttributeError: module 'comfy.sample' has no attribute 'convert_cond'

Prompt executed in 495.29 seconds

**Comment by ltdrdata** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/128333288/5a0a3fe9-04b9-40a6-983b-216a8f7a994a)

An update to the custom node is required due to the ComfyUI update, but unfortunately, the original repository seems to be unmaintained at the moment.

For now, a hotfix has been registered on the Manager's forked channel. Uninstalling the current installation and reinstalling with this version should resolve the issue.

**Comment by attyru** [comment]
I take it we can close the issue? I've installed from fork everything seems to work except SeargeSDXL, also waiting for fixes in its repository?

**Comment by ltdrdata** [comment]
> I take it we can close the issue? I've installed from fork everything seems to work except SeargeSDXL, also waiting for fixes in its repository?

My PR has been merged into the original repository. It is recommended to reinstall and use from the original repository.

**Comment by liyunfei54** [comment]
> > 我想我们可以关闭这个问题吗？我已经从 fork 安装了所有东西，除了 SeargeSDXL 之外，似乎一切正常，还在等待其存储库中的修复？
> 
> 我的 PR 已合并到原始存储库中。建议从原始存储库重新安装并使用。
> 
> [BlenderNeko/ComfyUI_TiledKSampler#43](https://github.com/BlenderNeko/ComfyUI_TiledKSampler/pull/43)

thanks

**Comment by Akidioyan** [comment]
Uninstall the plugin and reinstall it to solve your problem

**Comment by lisboa2024** [comment]
I have uninstalled and then installed, but to no avail, there are still errors (executing KSamplerSeq:

Module "comfy.sample" has no attribute "convert_cond")

**Comment by AbrahamCui** [comment]
卸载重装就好了
