### ISSUE TITLE
CosXL issue: If first generating with Playground v2.5 then switching to CosXL, images will be corrupted

### ISSUE THREAD

**Issue by jepjoo** [comfyanonymous/ComfyUI#3231]
1. Generate an image with CosXL - quality is as expected
2. Switch to Playground 2.5, generate image - quality is as expected
3. Switch back to CosXL - quality is bad

Example images from steps 1. and 3.:

1:
![IPAdapter_00174_](https://github.com/comfyanonymous/ComfyUI/assets/48107422/6c529dec-6e11-41b3-88b1-d45663c0d69a)
3:
![IPAdapter_00176_](https://github.com/comfyanonymous/ComfyUI/assets/48107422/3e45dd63-6e39-4ccd-abcc-a777c0ba3ae9)

Fixed seed and no settings have been touched.

**Comment by comfyanonymous** [comment]
Should be fixed with: https://github.com/comfyanonymous/ComfyUI/commit/831511a1eecbe271e302f2f2053f285f00614180
