### ISSUE TITLE
Insightface node not available

### ISSUE THREAD

**Issue by vishusinghal** [comfyanonymous/ComfyUI#3248]
Hi, I just downloaded the portable comfyui copy  on my windows machine. The Inghtface or prepare for insightface nodes are nowhere to be found. I have also manually installed the insightface whl file
Can someone please help?

**Comment by zmwv823** [comment]
Install custom node "ComfyUI_IPAdapter_plus" or "ComfyUI-InstantID"(8GB+ VRAM)
![image](https://github.com/comfyanonymous/ComfyUI/assets/13308350/2fc60357-edaf-4541-bc9d-cd1e7f33023a)

**Comment by CHENERICK1** [comment]
i have meet this problem,i finally found that just restart comfyui every time u open it

**Comment by miguelgargallo** [comment]
> i have meet this problem,i finally found that just restart comfyui every time u open it

You should check this https://github.com/kijai/ComfyUI-LivePortraitKJ/issues/92

**Comment by ltdrdata** [comment]
This issue should be handled related custom node repo.
