### ISSUE TITLE
[Help] Image generated inside comfyui crashes

### ISSUE THREAD

**Issue by baicai99** [comfyanonymous/ComfyUI#3251]
### My graphics card is a 4080.
![IMG_2860](https://github.com/comfyanonymous/ComfyUI/assets/101706274/a6d035e9-cef5-419e-8989-0b74fdbda578)
![img_v3_029s_ca2bc482-4fe9-4a19-84fb-7e81e0974d5g](https://github.com/comfyanonymous/ComfyUI/assets/101706274/993b37b5-7218-4eb6-8ac1-714a85d896f5)
### But this is all normal in webui.
![IMG_2861](https://github.com/comfyanonymous/ComfyUI/assets/101706274/87a6fe38-dd91-4246-8281-0568d64901b9) 
### Meanwhile if I crank the step to 40 it can be much better, but still not as clean as webui.
![img_v3_029s_8e038c32-4634-46c1-9759-d592c9c8554g](https://github.com/comfyanonymous/ComfyUI/assets/101706274/7deb0e2f-13e0-4676-b9d0-5a48870fdba7)

**Comment by ltdrdata** [comment]
Lower the weights in prompt.

**Comment by baicai99** [comment]
> Lower the weights in prompt. Interpretation of weights is different with A1111.
> 
> https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb

Thank you very much for your help, I seem to have an improvement after pulling the CFG down. 

I have one more question for you. It is that my terminal prompts me:
`clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']`, how do I fix it, I didn't find any model on the web that I can use.
