### ISSUE TITLE
update all problem with text widget and c comments

### ISSUE THREAD

**Issue by tester4488** [comfyanonymous/ComfyUI#3261]
today I did an update all, 
pip installed some packages:

![Immagine 2024-04-13 181439](https://github.com/comfyanonymous/ComfyUI/assets/160387045/0fd793e5-7242-418a-83e4-beabe3e8301f)

now I can no longer use comments in the various text widgets:

![Immagine 2024-04-13 182057](https://github.com/comfyanonymous/ComfyUI/assets/160387045/d3990baa-6501-449e-813f-9dbb0ed7392c)

if i put a //
or /* text */
it no longer lets me edit the text, it moves the cursor to the end.

**Comment by Ahmet0691** [comment]
+1

**Comment by pkollmar** [comment]
+1

**Comment by tester4488** [comment]
i have reinstalled

**Comment by tester4488** [comment]
problem is caused by https://github.com/kijai/ComfyUI-KJNodes
