### ISSUE TITLE
D:\a\ComfyUI\python_embeded\python.exe

### ISSUE THREAD

**Issue by EntityinArray** [comfyanonymous/ComfyUI#3263]
I'm using the standalone ComfyUI on Win10 with NVidia GPU.

I'm getting this error when trying to use CRM in ComfyUI
https://pastebin.com/Qsxa1pbT

I need to install module nvdiffrast into your python_embeded
I go to `ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Scripts`
and run `./pip.exe install git+https://github.com/NVlabs/nvdiffrast/` from there:
```
Fatal error in launcher: Unable to create process using '"D:\a\ComfyUI\python_embeded\python.exe"
"C:\Users\entityinarray\Downloads\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Scripts\pip.exe" install git+https://github.com/NVlabs/nvdiffrast/': The system cannot find the file specified.
```

Where this `D:\a\ComfyUI\python_embeded\python.exe` path comes from?
How to install pip modules into your embeded_python in a standalone ComfyUI?

**Comment by dh9527** [comment]
This is a feature of the python"embeded" version, which needs to be used as follows: Python - m pip ...

**Comment by Falkonar** [comment]
I sometimes get this error when using the portable version. But it is strange that I use it on the S drive, but the error is about the D drive. It is not even a question of the disc marking, but that sometimes it disappears after changing the letters of the disc. Of course I install everything via python.exe -m pip install --user . For example onnxruntime usually show the same error and I reinstall it. I think the system variables path also gives effect on this

**Comment by wiopen** [comment]
Ref to: https://stackoverflow.com/questions/37220055/pip-fatal-error-in-launcher-unable-to-create-process-using
Using cmd line: python -m pip install --upgrade --force-reinstall pip

**Comment by euneno** [comment]
> python -m pip install --upgrade --force-reinstall pip

thx, resolve my problem.
