### ISSUE TITLE
Adding "//" to a CLIPTextEncode text field causes the cursor to always move to the end of the field

### ISSUE THREAD

**Issue by jmole** [comfyanonymous/ComfyUI#3279]
Repro:

1) Open a fresh instance of ComfyUI
2) Add two forward slashes somewhere inside the prompt
3) Notice that you can no longer select text or move the text cursor around with arrow keys, because it always jumps to the end of the text box

**Comment by JorgeR81** [comment]
You you have the cg-use-everywhere custom nodes ?

They can cause this issue:

https://github.com/chrisgoringe/cg-use-everywhere/issues/172

**Comment by jmole** [comment]
> You you have the cg-use-everywhere custom nodes ? They can cause this issue If you disable "_Anything Everywhere highlight connected nodes_", in the options, it should work correctly.
> 
> [chrisgoringe/cg-use-everywhere#172](https://github.com/chrisgoringe/cg-use-everywhere/issues/172)

Yes, this was apparently the problem, thank you
