### ISSUE TITLE
Updating portable version

### ISSUE THREAD

**Issue by dadadies** [comfyanonymous/ComfyUI#3287]
Is there a way to update the portable version without downloading the full latest portable version? I did not find any info on it.  I think this is supposed to be under discussion i apologize if this is the wrong place.

**Comment by gtx155** [comment]
RECOMMENDED WAY TO UPDATE:
To update the ComfyUI code: update\update_comfyui.bat

**Comment by dadadies** [comment]
Iv tried that a few times in the past and it never worked but now it did work and it updated in a few seconds. However I did download the full portable release again so ill be using that. But next time ill use the update method and hopefully it will work again.
