### ISSUE TITLE
Loading API file: Titles lost

### ISSUE THREAD

**Issue by seghier** [comfyanonymous/ComfyUI#3307]
Hello
I change the titles of some nodes and save the API file
When i load the API json file again all titles changed to the default names, why?
If this is how it work please fix it

**Comment by seghier** [comment]
I load them normaly like other json files

**Comment by robinjhuang** [comment]
API json does not contain that information. You need to save the non-api version of the json file.

**Comment by shesung** [comment]
> API json does not contain that information. You need to save the non-api version of the json file.

But title is already added to api json in https://github.com/comfyanonymous/ComfyUI/pull/2380
