### ISSUE TITLE
Is there any effective methods to clean RAM ?

### ISSUE THREAD

**Issue by GeLi1989** [comfyanonymous/ComfyUI#3308]
May I ask help, I used the/free command

RAM memory seems to have not been effectively cleared. And VRAM has been effectively cleaned up.

Do I have any effective methods to clean RAM.
It accumulates higher and higher, as I start the comfyui service for a longer time

################
**json_data = {
        "unload_models": True,
        "free_memory": True
    }**

 @routes.post("/free")
        async def post_free(request):
            json_data = await request.json()
            unload_models = json_data.get("unload_models", False)
            free_memory = json_data.get("free_memory", False)
            if unload_models:
                self.prompt_queue.set_flag("unload_models", unload_models)
            if free_memory:
                self.prompt_queue.set_flag("free_memory", free_memory)
            return web.Response(status=200)

**Comment by viebrix** [comment]
I have the suspect that it has something to do with the bottom frame - which is showing the generated pictures. Decreasing the size of this pictures  also lowers memory usage. Maybe you can check if this also changes memory at your installation? 

Is there any function/button to delete this images?

**Comment by viebrix** [comment]
https://www.reddit.com/r/comfyui/comments/15wydgf/bottom_section/
