### ISSUE TITLE
When loading the graph, the following node types were not found: IPAdapterApply

### ISSUE THREAD

**Issue by nitinmukesh** [comfyanonymous/ComfyUI#3314]
<img width="1059" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/2102186/87478d79-de8b-46ae-bb05-dc5ccc075f84">

Install missing nodes show nothing
<img width="1034" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/2102186/82626bd5-36f0-4908-a40a-289fe681a18e">

I did installed all missing nodes.

<img width="545" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/2102186/0244b47f-3305-42a5-a446-264baf8cfde8">

Total VRAM 8188 MB, total RAM 16108 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\sd\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\__init__.py", line 1, in <module>
    from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'inference_core_nodes'

Cannot import C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes module for custom nodes: No module named 'inference_core_nodes'
### ComfyUI Revision: 2139 [644a3ae5] | Released on '2024-04-20'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
DWPose: Onnxruntime with acceleration providers detected

Import times for custom nodes:
   0.0 seconds: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes
   0.0 seconds: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.3 seconds: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.3 seconds: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
FETCH DATA from: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
FETCH DATA from: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\2259715867_alter-list.json
FETCH DATA from: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json
Update ComfyUI
FETCH DATA from: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
FETCH DATA from: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json
FETCH DATA from: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json
FETCH DATA from: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json
FETCH DATA from: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json
FETCH DATA from: C:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json

**Comment by ltdrdata** [comment]
That is deprecated node. But you can install it from Legacy channel in ComfyUI-Manager.

**Comment by nitinmukesh** [comment]
> That is deprecated node. But you can install it from Legacy channel in ComfyUI-Manager.

Thank you for your response.

This is the first time I am using ComfyUI. Please could you help with the steps. Struggling with this from past several hours.
<img width="761" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/2102186/d3ed20fd-7439-4eb8-b159-c83d9acb4ef1">

**Comment by ltdrdata** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/128333288/d5bb7056-f922-46dd-9027-c1a302f712dd)
![image](https://github.com/comfyanonymous/ComfyUI/assets/128333288/ff65f816-0de9-41bf-a6b6-960efc7a3c5b)

**Comment by nitinmukesh** [comment]
@ltdrdata  Thank you.

**Comment by shayneleee** [comment]
HI, @ltdrdata , i have followed your settings but could not find the ComfyUI_IPAdapter_plus.old to install. Could you please help to have a look? 

Thanks
![e203285149088999afa9b618c82102d](https://github.com/comfyanonymous/ComfyUI/assets/34502436/3bbc889d-ed68-4bc0-b802-bfedc7b8d94a)

![4b2806becd7ad5febe0d8ad8e774003](https://github.com/comfyanonymous/ComfyUI/assets/34502436/a4d37f2e-c4a7-468d-9f8a-70625e78891c)

**Comment by sarojkumarss** [comment]
Bro Read this link if you are still there.
https://www.reddit.com/r/comfyui/comments/1btu6n8/when_loading_the_graph_the_following_node_types/

**Comment by ltdrdata** [comment]
> HI, @ltdrdata , i have followed your settings but could not find the ComfyUI_IPAdapter_plus.old to install. Could you please help to have a look?
> 
> Thanks ![e203285149088999afa9b618c82102d](https://private-user-images.githubusercontent.com/34502436/338971903-3bbc889d-ed68-4bc0-b802-bfedc7b8d94a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjAxODMsIm5iZiI6MTcyMTgxOTg4MywicGF0aCI6Ii8zNDUwMjQzNi8zMzg5NzE5MDMtM2JiYzg4OWQtZWQ2OC00YmMwLWI4MDItYmZlZGM3YjhkOTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDExMTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMGI0Mjk4MDIyN2QwODc3NDJjYzI4N2ExNTIxMzkxN2Y1YTk5Mzk1YzIwMTVkNGM1NjQ4ZDAxZmZkYjY2ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OVWYkMxrXrhQwk27gIWVZs0ui37QePj5XVAoRXKT2B8)
> 
> ![4b2806becd7ad5febe0d8ad8e774003](https://private-user-images.githubusercontent.com/34502436/338971944-a4d37f2e-c4a7-468d-9f8a-70625e78891c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjAxODMsIm5iZiI6MTcyMTgxOTg4MywicGF0aCI6Ii8zNDUwMjQzNi8zMzg5NzE5NDQtYTRkMzdmMmUtYzRhNy00NjhkLTlmOGEtNzA2MjVlNzg4OTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDExMTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMTBjZTEzM2FjNTRkZjJkOTIxNjAzMTkwMDVjODc3MGQxNmYxODc4MjRiMDc4MmM4NmQ2MGI1ZDVjMWFiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XQsIuLgQu9f1HlEEqg9nOg4irn3ALiOQvGuAQRs0kXY)

You can find it `forked channel` istead of `legacy channel`.
