### ISSUE TITLE
// comment or /* comment */ is no work

### ISSUE THREAD

**Issue by za-wa-n-go** [comfyanonymous/ComfyUI#3315]
It seems that using "convert" to connect the prompt from external sources causes "//" to stop working. It works if you directly mention it in ClipTextEncode, but this is inconvenient.

**Comment by za-wa-n-go** [comment]
This bug has been occurring since this commit.

[744ac944db24795881cf41fc4ea015e5ea07a444](https://github.com/comfyanonymous/ComfyUI/commit/744ac944db24795881cf41fc4ea015e5ea07a444)

**Comment by tester4488** [comment]
yep, same here 
![immagine](https://github.com/comfyanonymous/ComfyUI/assets/160387045/95164dac-3b40-4b92-9ec7-3635cbde9c08)

**Comment by ltdrdata** [comment]
> This bug has been occurring since this commit.
> 
> [744ac944db24795881cf41fc4ea015e5ea07a444](https://github.com/comfyanonymous/ComfyUI/commit/744ac944db24795881cf41fc4ea015e5ea07a444)

That is not a bug. Just a policy is changed.

Previously, if a dynamic prompt was not explicitly set for the multi-line widget, it was applied by default. 
However, now if a dynamic prompt is not explicitly applied, it is disabled.

For built-in nodes, the behavior remains the same as before.
For custom nodes, it is up to the developer's discretion.

**Comment by za-wa-n-go** [comment]
thankyou.
Hmm. It's very inconvenient that it doesn't work when converting text...
Is there a custom node that would work for this?
I think it's a big change, so I'd like you to show me specifically what I should do instead.

**Comment by tester4488** [comment]
https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/issues/158
need add 
"dynamicPrompts": True 
to the prompt nodes
