### ISSUE TITLE
How to deploy ComfyUI workflow and connect to a mobile app via API (is it possible to message you directly ?)

### ISSUE THREAD

**Issue by chalkncheese** [comfyanonymous/ComfyUI#3320]
I have a ComfyUI workflow saved in API format, my client would like to deploy it as backend on Runpod or equivalent and connect it via API to a mobile app ( created using React by another developer) I have very limited knowledge of setting up the API, and would very much appreciate some help if possible. Thank you in advance.

**Comment by perlinson** [comment]
you can use comfyui-deploy (github project)
