### ISSUE TITLE
[Bug / Feature Request] Input Text & Title Too Long / Need Fade Cutoff

### ISSUE THREAD

**Issue by aphaits** [comfyanonymous/ComfyUI#3335]
I feel like this issue is one of the most prevalent and oldest GUI issue in ComfyUI nodes, especially considering now people are naming their checkpoints and loras with long names and versions, combined with using subfolders. It is also a much needed quality of life improvements for general usability of the UI workflow.

Note: I'm not a coder/programmer and I am aware that ComfyUI is based on Litegraph.js but unsure if the suggested features are possible or not to implement.

---

**Main issue 1 - Input text too long:**
Long input text / title spills from node input text boundary

![ComfyUI_Suggestion_01_InputTextCutoff](https://github.com/comfyanonymous/ComfyUI/assets/132622276/683f83cd-8339-4025-8047-75d5798a97ba)

**Suggestion:**
- Cutting spilled text to left input boundary
- Also fading text to left boundary
- Removing folder path from title
- Removing file type extension from title
- Full title info on mouse hover

---

**Main Issue 2 - Node title text too long:**
Long node title prevents node from being resized to smallest possible size

![ComfyUI_Suggestion_02_NodeTitleCutoff](https://github.com/comfyanonymous/ComfyUI/assets/132622276/311a9943-83d5-4166-9059-4396023886b8)

**Suggestion:**
- Cutting title with ... indicator with Full title info on mouse hover
- OR fading title to right boundary with Full title info on mouse hover

---

**Main issue 3 - Group title text too long:**
Big title text on groups are great but tends to spill right on thin groups, especially when text size is increased for legibility

![ComfyUI_Suggestion_03_GroupTitleCutoff](https://github.com/comfyanonymous/ComfyUI/assets/132622276/cb9c90ec-c777-4f86-851e-b548d4a9743a)

Suggestion:
- Cutting group title with ... indicator with full title info on mouse hover
- OR Fading group title to right boundary with full title info on mouse hover

**Comment by Trung0246** [comment]
Unfortunately these requires direct modification of the litegraph library itself. Another thing we're dealing with canvas since litegraph use that to draw the nodes (not css) so this is tedious to change for achieving such small gain.

**Comment by slezica** [comment]
@Trung0246 I've made small changes to `litegraph.core.js` to fix things in my local fork. I'm tempted to tackle this one.

I've been directly editing the compiled file like a lunatic, though. If I wanted to contribute an actual fix for Comfy that involved litegraph, how would I go about it?

**Comment by Trung0246** [comment]
@slezica https://github.com/Comfy-Org/ComfyUI_frontend/issues

**Comment by huchenlei** [comment]
Has been fixed in https://github.com/Comfy-Org/litegraph.js/pull/17
