### ISSUE TITLE
PermissionError: [Errno 13] error while attempting to bind on address ('127.0.0.1', 8188)

### ISSUE THREAD

**Issue by zerobell-lee** [comfyanonymous/ComfyUI#3345]
```powershell

D:\Workspace\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 12288 MB, total RAM 65459 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints D:/Workspace/stable-diffusion-webui-docker/data\models/Stable-diffusion
Adding extra search path configs D:/Workspace/stable-diffusion-webui-docker/data\models/Stable-diffusion
Adding extra search path vae D:/Workspace/stable-diffusion-webui-docker/data\models/VAE
Adding extra search path loras D:/Workspace/stable-diffusion-webui-docker/data\models/Lora
Adding extra search path loras D:/Workspace/stable-diffusion-webui-docker/data\models/LyCORIS
Adding extra search path upscale_models D:/Workspace/stable-diffusion-webui-docker/data\models/ESRGAN
Adding extra search path upscale_models D:/Workspace/stable-diffusion-webui-docker/data\models/RealESRGAN
Adding extra search path upscale_models D:/Workspace/stable-diffusion-webui-docker/data\models/SwinIR
Adding extra search path embeddings D:/Workspace/stable-diffusion-webui-docker/data\embeddings
Adding extra search path hypernetworks D:/Workspace/stable-diffusion-webui-docker/data\models/hypernetworks
Adding extra search path controlnet D:/Workspace/stable-diffusion-webui-docker/data\models/ControlNet

Import times for custom nodes:
   0.0 seconds: D:\Workspace\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Traceback (most recent call last):
  File "D:\Workspace\ComfyUI_windows_portable\ComfyUI\main.py", line 254, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 654, in run_until_complete
  File "D:\Workspace\ComfyUI_windows_portable\ComfyUI\main.py", line 149, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "D:\Workspace\ComfyUI_windows_portable\ComfyUI\server.py", line 627, in start
    await site.start()
  File "D:\Workspace\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\base_events.py", line 1536, in create_server
PermissionError: [Errno 13] error while attempting to bind on address ('127.0.0.1', 8188): 액세스 권한에 의해 숨겨진 소 켓에 액세스를 시도했습니다

D:\Workspace\ComfyUI_windows_portable>pause
```

- Distribution : Windows portable (latest at 2024-04-25 16:18:00 UTC)
- Is Port 8188 occupied by other application? : No. I already checked it with `netstat`
- Does your firewall allow that port? : I added the rule and still it does not work. By the way, I've been able to run any python server application so easily without any firewall settings until now. This one is the only exception.
- Did you try turning off Windows Defender or any antivirus? : I only use Windows Defender and I tried turning off it. And I got the same result.
- Did you try rebooting? : Of course. And I got the same result.

**Comment by zerobell-lee** [comment]
Self solution: I STILL don't get what caused it. Anyway, I could modify port by passing argument `--port 8080` and it worked.

I needed to find out `comfy/cli_args.py`. I don't know why these arguments were not describe in README.md. Anyway, I solved it. So I close this issue.

**Comment by ZHHUIDE** [comment]
thanks very much

**Comment by oputo** [comment]
Thank you for the information.
I was able to use it until a few days ago, but I've started to have similar symptoms.

--- message log 

Traceback (most recent call last):
  File "D:\AI\ComfyUI\main.py", line 264, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "C:\Users\haton\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\AI\ComfyUI\main.py", line 159, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "D:\AI\ComfyUI\server.py", line 677, in start
    await site.start()
  File "D:\AI\ComfyUI\venv\lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
  File "C:\Users\haton\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1519, in create_server
    raise OSError(err.errno, 'error while attempting '
PermissionError: [Errno 13] error while attempting to bind on address ('127.0.0.1', 8188): You tried to access a socket in a way that is prohibited by the access permissions.

---

Trying some of the responses I got from chatGPT.
___ answer by GPT
This error may be caused by a permissions problem when accessing the port that ComfyUI is trying to use (in this case, port 8188).
Solution 5: Reset the network settings
Resetting your network settings may solve the problem. Execute the following command with administrator privileges.
'''
netsh winsock reset
netsh int ip reset
'''
___
And after rebooting the PC, it was fixed.

**Comment by ltdrdata** [comment]
> Thank you for the information. I was also able to use it without any problems until a few days ago, but I started to experience the same symptoms.
> 
> --- message log
> 
> Traceback (most recent call last): File "D:\AI\ComfyUI\main.py", line 264, in loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start)) File "C:\Users\haton\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete return future.result() File "D:\AI\ComfyUI\main.py", line 159, in run await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop()) File "D:\AI\ComfyUI\server.py", line 677, in start await site.start() File "D:\AI\ComfyUI\venv\lib\site-packages\aiohttp\web_runner.py", line 119, in start self._server = await loop.create_server( File "C:\Users\haton\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1519, in create_server raise OSError(err.errno, 'error while attempting ' PermissionError: [Errno 13] error while attempting to bind on address ('127.0.0.1', 8188): You tried to access a socket in a way that is prohibited by the access permissions.
> 
> Trying some of the responses I got from chatGPT. ___ answer by GPT This error may be caused by a permissions problem when accessing the port that ComfyUI is trying to use (in this case, port 8188). Solution 5: Reset the network settings Resetting your network settings may solve the problem. Execute the following command with administrator privileges. ''' netsh winsock reset netsh int ip reset '''
> 
> And after rebooting the PC, it was fixed.

If it's fixed by rebooting, in most cases ComfyUI is still running somewhere in a window you've forgotten about.
To check if this is actually the case, you can verify whether you can access it through your browser.

**Comment by lewddev** [comment]
Try this! It's works for me.
net stop hns
net start hns

**Comment by Manifold01** [comment]
The most probable cause is port 8188 is excluded by tcp protocol. It is reserved for other use. Use the following command to find if port 8188 falls into any exclusion ranges. If so, modify the port by adding option `--port <port-number>`.
```
netsh interface ipv4 show excludedportrange protocol=tcp
```
