### ISSUE TITLE
After update, xformers is missing

### ISSUE THREAD

**Issue by edwinzeng2005** [comfyanonymous/ComfyUI#3348]
This is the second time that has happened since yesterday.

I found out that after updating ComfyUI, it now uses torch 2.3.0, which has no compatible version of xformers, so the log complained that I had no xformers installed.
So I downgraded torch to 2.2.2, torchvision to 0.17.2, and re-installed xformers 0.0.25.post1.

I will refrain from updating ComfyUI until the next xformers release is ready.

**Comment by mayo-Z** [comment]
+1

**Comment by Fexcron** [comment]
+1

**Comment by askmyteapot** [comment]
I've found that Pytorch attention is slightly faster than xformers now anyway. Especially since pytorch 2.3.0

**Comment by robinjhuang** [comment]
xformer is no longer shipped with standalone windows build. Is xformers is needed, please follow this issue: 
https://github.com/comfyanonymous/ComfyUI/issues/1065

**Comment by Amit30swgoh** [comment]
yes Xformers missing 

pip install xformers
