### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

### ISSUE THREAD

**Issue by jokero3answer** [comfyanonymous/ComfyUI#3352]
![微信截图_20240426205638](https://github.com/comfyanonymous/ComfyUI/assets/130854108/8c5f8b6e-8e90-426c-8ebf-b1b2927e9abc)
![微信截图_20240426204929](https://github.com/comfyanonymous/ComfyUI/assets/130854108/5cfd7176-e776-442c-bbc5-eb123c5cccb6)
![微信截图_20240426210040](https://github.com/comfyanonymous/ComfyUI/assets/130854108/c95ec438-417a-46f7-8dc6-939b7390c967)
Author, thank you very much, requesting a fix for this old bug, it has reappeared and all my nodes and comfyui are up to date!
@tobbez @jeske @realazthat @FaridSafi @tjhayasaka

**Comment by jokero3answer** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/130854108/d7505507-f142-4f4a-af86-53716b875f6e)

**Comment by jokero3answer** [comment]
@comfyanonymous，@pythongosssss

**Comment by techzuhaib** [comment]
Restart comfy solved this for me many times

**Comment by Xyem** [comment]
> Restart comfy solved this for me many times

I'm getting this error with `Conditioning (Concat)` and restarting ComfyUI does not resolve it.

**Comment by designex** [comment]
me too~The problem persists

**Comment by ltdrdata** [comment]
> ![微信截图_20240426205638](https://private-user-images.githubusercontent.com/130854108/325986033-8c5f8b6e-8e90-426c-8ebf-b1b2927e9abc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTA2OTIsIm5iZiI6MTcyNzQxMDM5MiwicGF0aCI6Ii8xMzA4NTQxMDgvMzI1OTg2MDMzLThjNWY4YjZlLThlOTAtNDI2Yy04ZWJmLWIxYjI5MjdlOWFiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwNDEzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDgxNjE1MmIwMzRkYTliYzMzYWRlYWZhMjM5NzFlNWMzNWUzMzVlYWViNzhlNmZmMWIzODQ1NDEzMmYwNjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kN3pyVUGW48HeJXrjL_xAYqQ2SexwHn5syki_KFAByM) ![微信截图_20240426204929](https://private-user-images.githubusercontent.com/130854108/325986063-5cfd7176-e776-442c-bbc5-eb123c5cccb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTA2OTIsIm5iZiI6MTcyNzQxMDM5MiwicGF0aCI6Ii8xMzA4NTQxMDgvMzI1OTg2MDYzLTVjZmQ3MTc2LWU3NzYtNDQyYy1iYmM1LWViMTIzYzVjY2NiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwNDEzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWM2YjhkMGEzNjFhOGQ0N2NkOTZmODJmYmE3Mzk5MDAzMjIxZDA1OTYxYjk5MmUyNjAwOGEyZjRlNTQ5MDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LR_VAuOQhO-h5NiQK1j-Ssg3aFTbbUwAOdvb7UTDCFo) ![微信截图_20240426210040](https://private-user-images.githubusercontent.com/130854108/325986079-c95ec438-417a-46f7-8dc6-939b7390c967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTA2OTIsIm5iZiI6MTcyNzQxMDM5MiwicGF0aCI6Ii8xMzA4NTQxMDgvMzI1OTg2MDc5LWM5NWVjNDM4LTQxN2EtNDZmNy04ZGM2LTkzOWI3MzkwYzk2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwNDEzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDdlNWU3ZWIwZDAxZTllNzE5MTIwZjY4ZTMzNTFkMzI2NjMyNzNiNTc5MTI4NzZlYzY4M2I3Y2E5YjJkN2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._bf-zpu-O15GDMgtuvlePYKgMyCU05YkRnYMKH96IiM) Author, thank you very much, requesting a fix for this old bug, it has reappeared and all my nodes and comfyui are up to date! @tobbez @jeske @realazthat @FaridSafi @tjhayasaka

This workflow is using incompatible nodes mixed together. You should not connect the SAMLoader from Impact Pack to the SAM_MODEL of segment anything.

**Comment by ltdrdata** [comment]
For others, please check your workflow as well. For issues arising from custom nodes, please inquire at the respective custom node's repository.

**Comment by designex** [comment]
![微信截图_20240928183216](https://github.com/user-attachments/assets/d095aba4-f224-49ef-8c92-139e136c9c12)

**Comment by 1295179385** [comment]
![image](https://github.com/user-attachments/assets/00164e83-4e11-4fee-a6af-61bd03e110e5)
