### ISSUE TITLE
The same parameters in webUI and comfyUI, and I got different results.

### ISSUE THREAD

**Issue by OriginSXC** [comfyanonymous/ComfyUI#337]
The first is generated in webUI, and the second is comfyUI. You can see the second happened somewhat overfit. No idea why. Same parameters, same Lora, and same checkpoint.
![00282-1647461790-yurisa, best quality, ultra high res, (photorealistic_1 4), 1girl,solo, full lips, a sultry gaze, school uniform, A sexy student (1)](https://user-images.githubusercontent.com/127317551/228963081-9da52ab9-3492-4902-9bb4-dc4a0a0f1777.png)
![ComfyUI_00023_](https://user-images.githubusercontent.com/127317551/228963097-dbb22ab6-d8a6-4312-abae-e94dea27a765.png)

**Comment by comfyanonymous** [comment]
Lower your (prompt weights:1.1), they are more sensitive in ComfyUI

**Comment by OriginSXC** [comment]
Looks lower CFG would help, too. Thank you!

**Comment by Kelier** [comment]
> Looks lower CFG would help, too. Thank you!

hello, could you share this arg?
