### ISSUE TITLE
Sam Detector from Load Image doesn't have a CPU only option

### ISSUE THREAD

**Issue by Maveyyl** [comfyanonymous/ComfyUI#3375]
Sam Detector from Load Image doesn't have a CPU only option, which makes it impossible to run on an AMD card.

**Comment by shawnington** [comment]
> Sam Detector from Load Image doesn't have a CPU only option, which makes it impossible to run on an AMD card.

This would be an issue for @ltdrdata but from my looking through the code, you can definitely set it to run cpu only. 

```
@server.PromptServer.instance.routes.post("/sam/detect")
async def sam_detect(request):
    global sam_predictor
    with sam_lock:
        if sam_predictor is not None:
            if impact.config.get_config()['sam_editor_cpu']:
                device = 'cpu'
            else:
                device = comfy.model_management.get_torch_device()

            sam_predictor.model.to(device=device)

```

**Comment by Maveyyl** [comment]
My bad, it is a feature of Impact pack not of main ComfyUI! I modified the .ini file from impact folder and could make it work. Many thanks @shawnington
