### ISSUE TITLE
Add stable diffusion 3 / MMDiT based model support

### ISSUE THREAD

**Issue by isidentical** [comfyanonymous/ComfyUI#3378]
SD3 is coming up and it's architecture is already public / described in paper. I think it can be supported even before the weights drop or at least the initial work can be started. Here is an example MMDiT implementation by @kabachuha https://github.com/NUS-HPC-AI-Lab/OpenDiT/pull/92

**Comment by ltdrdata** [comment]
Comfy implemented SD3, already. Just it seems that comfy is waiting the release.

**Comment by isidentical** [comment]
Is there a branch already?

**Comment by mcandre** [comment]
Several weeks have passed. Which milestone will include SD3 support?

**Comment by mcmonkey4eva** [comment]
Support for SD3 in Comfy will be released on the day SD3 itself is released, ie June 12th
