### ISSUE TITLE
ImageSharpen is broken on macOS due to a commit a week ago

### ISSUE THREAD

**Issue by bigcat88** [comfyanonymous/ComfyUI#3383]
This [commit](https://github.com/comfyanonymous/ComfyUI/commit/4ee9aad6caf4c23e69e9e166573c505e757062e5) broke the ImageSharpen node.

*macOS 14.4.1, PyTorch 2.3, M2 Max*

<img width="677" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/13381981/653f9a38-e7cb-4449-89ba-7b60d9be95b9">

**Comment by bigcat88** [comment]
@comfyanonymous

**Comment by austinmw** [comment]
Is this fixed?
