### ISSUE TITLE
showing blanck screen 

### ISSUE THREAD

**Issue by priya-ml-halohues** [comfyanonymous/ComfyUI#3387]
comfyui screen does not show anything. does anyone know how to solve this problem?

i got this from my Termial
To see the GUI go to: http://127.0.0.1:8188/

this is from browser console log (F12)
1. uncaught type error: Object.hasOwn is not a function at $el (ui.js:43) at logging.js:4
2. Failed to load resource: the server responded with a status of 404 (Not found)

How to solve this ? TIA

**Comment by silverlining21** [comment]
I got the same situation with you, in a offline env.

**Comment by silverlining21** [comment]
After some diving search, I found it might the chrome version lower the minimum requirement of the function `Object.hasOwn`, if you're using a different browser, here is the Browser compatibility table, check it accordingly.

[Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#browser_compatibility)


BRs

**Comment by mcmonkey4eva** [comment]
Please keep your browsers up to date! Not just for functionality/features like this, but also security vulnerabilities!
You had a version of chrome from prior to 2021, 3 years ago! You were undoubtedly at risk to a large variety of potential major security issues.
