### ISSUE TITLE
Ask for help: TLS/SSL question, failed to startup with the arg --tls-keyfile key.pem --tls-certfile cert.pem

### ISSUE THREAD

**Issue by hanetyb** [comfyanonymous/ComfyUI#3391]
i success to generate key by openssl. but it prompt unrecognized arguments. could you please give some advice? thanks

System: Ubantu 20.04
Comfyui: 2150

![image](https://github.com/comfyanonymous/ComfyUI/assets/136415996/9be4e265-e122-4913-a45e-4a03cc53126b)

![image](https://github.com/comfyanonymous/ComfyUI/assets/136415996/9bce31c2-6af9-4625-9ace-8bb2859e9e55)

**Comment by bigcat88** [comment]
do you have updated ComfyUI with support for this arguments?

*from info from screen you provided, you do not*

**Comment by hanetyb** [comment]
thanks  for the help. it works after git pull.
