### ISSUE TITLE
Error starting the server: startup_server() missing 1 required positional argument: 'port'

### ISSUE THREAD

**Issue by davidchenhs** [comfyanonymous/ComfyUI#3401]
![屏幕截图 2024-05-04 125439](https://github.com/comfyanonymous/ComfyUI/assets/164337292/c763ad94-fb97-4c63-972d-673ef7c771b9)
As you see,i can't open my comfyui.It seems to get trouble with the port,but i can't deal with it.It happens after i update the core of comfyui.So i'm only able to switch the earlier version before 2024/5/1.

**Comment by ltdrdata** [comment]
https://github.com/comfyanonymous/ComfyUI/issues/3382

Update `comfyui-mixlab-nodes` custom node.

**Comment by davidchenhs** [comment]
It works!!!Thank u so much for solving my problem!!

**Comment by postmrtm** [comment]
i still get the error after updating mixlabs :(
any thoughts anyone?

**Comment by ky007ge** [comment]
Very effective, thanks

**Comment by jackliaud4** [comment]
It works!!!Thank u so much  @ltdrdata，
