### ISSUE TITLE
NumPy isn't available when saving image

### ISSUE THREAD

**Issue by Rild2** [comfyanonymous/ComfyUI#3413]
Installed portable version to win10, launched, all works perfectly but the last step

![image](https://github.com/comfyanonymous/ComfyUI/assets/93258437/d673f9cb-3aff-438e-b25d-fa5d80a5a7f3)

I didn't find any mentions of this problem anywhere, so I share it here.

**Comment by ltdrdata** [comment]
Post your workflow.
The issue requires determining what was passed to the Save Image node.

**Comment by Rild2** [comment]
> Post your workflow. The issue requires determining what was passed to the Save Image node.

It's the default one. 
![image](https://github.com/comfyanonymous/ComfyUI/assets/93258437/98a6da3a-b177-4d2b-8d2c-4375228ae52f)
![image](https://github.com/comfyanonymous/ComfyUI/assets/93258437/9b4945d3-71f8-4138-8bec-3a17be2ce91f)

Checkpoint doesn't matter, I tried it with SDXL turbo, 1.5 and my custom merge

**Comment by Rild2** [comment]
> Try using the model loaded by the VAE Loader instead of directly connecting the VAE model from the checkpoint to the VAE Decode.

Like that? Didn't work either

![image](https://github.com/comfyanonymous/ComfyUI/assets/93258437/553f944f-ca10-434c-a7dc-03ac14c0bc17)

**Comment by ltdrdata** [comment]
You'd better print the value. 

Edit `ComfyUI/nodes.py` and goto 1407 line.

And insert `print` code like this.
```
        for (batch_number, image) in enumerate(images):
            print(f"image: {image}")
            i = 255. * image.cpu().numpy()
```

**Comment by Rild2** [comment]
No progress
![image](https://github.com/comfyanonymous/ComfyUI/assets/93258437/a17b7a71-ff6a-4945-b10a-77972d92fd3c)
After inserting:
![image](https://github.com/comfyanonymous/ComfyUI/assets/93258437/5d05b639-f0fe-444a-a10d-ed5557782e4b)

**Comment by ltdrdata** [comment]
> No progress ![image](https://private-user-images.githubusercontent.com/93258437/328183995-a17b7a71-ff6a-4945-b10a-77972d92fd3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDAxODEsIm5iZiI6MTcxNDk5OTg4MSwicGF0aCI6Ii85MzI1ODQzNy8zMjgxODM5OTUtYTE3YjdhNzEtZmY2YS00OTQ1LWIxMGEtNzc5NzJkOTJmZDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEyNTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YWIzMDhmYzhlNzhjYWJlYTliM2YxZWRmNzViYTRlZmY1MGM1YTMyMjcxOWViNjgwMDBmZGI3ZmFhNTIyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0-oMYtYGxOJqDYeQD5Uncrsg9uC8SMFps1aGVCt1MdM) After inserting: ![image](https://private-user-images.githubusercontent.com/93258437/328184073-5d05b639-f0fe-444a-a10d-ed5557782e4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDAxODEsIm5iZiI6MTcxNDk5OTg4MSwicGF0aCI6Ii85MzI1ODQzNy8zMjgxODQwNzMtNWQwNWI2MzktZjBmZS00NDRhLWExMGQtZWQ1NTU3NzgyZTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEyNTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3Y2Y2NGZhNTI2YWIyMTU3ODZlZDQ3NzYxYWQwNzkxNGRhOTk5Y2M3YTA0OTQxN2I1OTExOTg0NzU1Y2NlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ah9KHKY2e14OuVNPXPXphpvxD13WzBD5me53Sns5QCA)

What is displayed on terminal?

**Comment by Rild2** [comment]
Oh, right:
![image](https://github.com/comfyanonymous/ComfyUI/assets/93258437/2c2a80cb-f6b1-458e-97d1-03e86fc43c44)
And after that same traceback
![image](https://github.com/comfyanonymous/ComfyUI/assets/93258437/c1f528ba-961b-49e0-b5e9-f4ef67dfaad8)

**Comment by Rild2** [comment]
> It seems that you numpy is outdated.
> 
> Go `Install PIP packages ` in ComfyUI-Manager menu.
> 
> ![image](https://private-user-images.githubusercontent.com/128333288/328186296-04f9050e-e60b-4035-8cc4-a59379d71385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDA2OTgsIm5iZiI6MTcxNTAwMDM5OCwicGF0aCI6Ii8xMjgzMzMyODgvMzI4MTg2Mjk2LTA0ZjkwNTBlLWU2MGItNDAzNS04Y2M0LWE1OTM3OWQ3MTM4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxMjU5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmMwZjk1NjEyMGU5OGExOWU4ODYwYjRmYzhkODZjZGY3Mjc3NzY4NmM2NGUwNjE1MmM0ZmJjOTA3MTM0NDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vOLRSSmohOsJg-Hf2LnR86gsktDH9bh2IMA5mJOd7tc)
> 
> And input `numpy` and restart.

Many thanks, I installed your extension and got my Numpy updated, it works now.
<details>
<summary>here, take a cat picture</summary>

![][1]
 
[1]: https://imgbly.com/ib/L3oV3WJOXN.png
</details>
