### ISSUE TITLE
Error occurred when executing CLIPSetLastLayer

### ISSUE THREAD

**Issue by xiecon** [comfyanonymous/ComfyUI#3418]
```
Error occurred when executing CLIPSetLastLayer:
'SD1ClipModel' object has no attribute 'diffusion_model'
```
![image](https://github.com/comfyanonymous/ComfyUI/assets/49284675/cc62bbf1-2967-42be-860b-025ec594172f)

![image](https://github.com/comfyanonymous/ComfyUI/assets/49284675/079c4579-79a5-4858-a8a1-20d58b31a2a1)

**Comment by comfyanonymous** [comment]
Can you post the full traceback?

**Comment by xiecon** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/49284675/1cadb83a-0e65-40bf-873a-34f6a7f97239)

**Comment by xiecon** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/49284675/2453d1b5-04e9-422f-b298-19845e9a67da)

**Comment by xiecon** [comment]
I found that the reason may be a conflict with the custom node of onediff.
