### ISSUE TITLE
[Feature Request] ToMe (Token Merge)

### ISSUE THREAD

**Issue by paulo-coronado** [comfyanonymous/ComfyUI#342]
Could you please add [ToMe](https://github.com/dbolya/tomesd) compatibility? With this implementation, we'll have up to 5.4x faster generations. 🤯

**Comment by comfyanonymous** [comment]
Implemented in: https://github.com/comfyanonymous/ComfyUI/commit/18a6c1db3335c6898181920aa6c9bb5b060fd85f

**Comment by paulo-coronado** [comment]
@comfyanonymous Do I need to do something to activate ToMe, such as cloning [dbolya/tomesd repo](https://github.com/dbolya/tomesd)? Or is it activated by default?
