### ISSUE TITLE
Need some hook callbacks in `server.py`

### ISSUE THREAD

**Issue by liusida** [comfyanonymous/ComfyUI#3429]
Since #3297 doesn't have the potential to be merged, I'll close it again.

And, @comfyanonymous , can you simply add an empty callback function after ws connection is closed and after sending a sync to the client:

https://github.com/comfyanonymous/ComfyUI/blob/c33412288fbdcd132265c9029a38001fd9696aa5/server.py#L118
and 
https://github.com/comfyanonymous/ComfyUI/blob/c33412288fbdcd132265c9029a38001fd9696aa5/server.py#L617

so that I can write a custom node to override this callback function and do some clean up?

Or any other suggestion to save resource when multiple instances of ComfyUI are running concurrently?

**Comment by pixelass** [comment]
Please see this comment: https://github.com/comfyanonymous/ComfyUI/issues/3192#issuecomment-2102802907

Memory can be freed by adding a simple web extension. Available via our compy-ui extensions: https://github.com/blib-la/blibla-comfyui-extensions?tab=readme-ov-file#unload-models

:heart:
