### ISSUE TITLE
Need help to set the path of a111 in "extra_model_paths.yaml"

### ISSUE THREAD

**Issue by BoosterCore** [comfyanonymous/ComfyUI#343]
Sorry, I have no knowledge about the yaml.
For example, my ComfyUI and A111 are in the same drive D:
ComfyUI --> D:\ComfyUI_windows_protable
A111--> D:\stable-diffusion-webui
Then how to set the "/path/to/stable-diffusion-webui/" in the "extra_model_paths.yaml" ?

**Comment by comfyanonymous** [comment]
Replace  "/path/to/stable-diffusion-webui/" with "D:\stable-diffusion-webui" ?

**Comment by BoosterCore** [comment]
> Replace "/path/to/stable-diffusion-webui/" with "D:\stable-diffusion-webui" ?
no, I try that, not work

**Comment by BoosterCore** [comment]
> Replace "/path/to/stable-diffusion-webui/" with "D:\stable-diffusion-webui" ?

I tryed "D:\stable-diffusion-webui",  "./stable-diffusion-webui", "../stable-diffusion-webui"

all get this
`D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Set vram state to: NORMAL VRAM
Using xformers cross attention
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\main.py", line 123, in <module>
    load_extra_path_config(extra_model_paths_config_path)
  File "D:\ComfyUI_windows_portable\ComfyUI\main.py", line 75, in load_extra_path_config
    config = yaml.safe_load(stream)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "D:\ComfyUI_windows_portable\ComfyUI\extra_model_paths.yaml", line 9, column 12

D:\ComfyUI_windows_portable>pause
请按任意键继续. . .`

**Comment by comfyanonymous** [comment]
Can you paste the contents of your extra_model_paths.yaml here?

**Comment by BoosterCore** [comment]
> Can you paste the contents of your extra_model_paths.yaml here?

`#Rename this to extra_model_paths.yaml and ComfyUI will load it

#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
a111:
    base_path: D:\stable-diffusion-webui

checkpoints: models/Stable-diffusion
    configs: models/Stable-diffusion
    vae: models/VAE
    loras: models/Lora
    upscale_models: |
                  models/ESRGAN
                  models/SwinIR
    embeddings: embeddings
    controlnet: models/ControlNet


#other_ui:
#    base_path: path/to/ui
#    checkpoints: models/checkpoints



`

**Comment by BoosterCore** [comment]
![微信图片_20230401011515](https://user-images.githubusercontent.com/73834045/229186867-c6b9ea70-8907-4c5d-983c-d197b64df020.png)

**Comment by pythongosssss** [comment]
checkpoints needs to be indented to the same level as configs

**Comment by comfyanonymous** [comment]
Yes make sure your checkpoints has spaces in front like this: https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example

**Comment by BoosterCore** [comment]
wow, thanks very much, it is done!

**Comment by owenmatrix** [comment]
![image](https://user-images.githubusercontent.com/24802575/229275988-706212f3-53f2-420c-8057-513c8db3ab17.png)
This is my file. It is not work either.

**Comment by No565** [comment]
Hi, i have similar problem as well! I have all my models etc in my stable-diffusion-webui folder. I would like to use the same models etc in Comfyui, how can i link it ? Im using anaconda in Windows 10!
I tried to put the path like : 

 #config for a1111 ui
#all you have to do is change the base_path to where yours is installed
a111:
    base_path: C:\Users\No565\Stable-Diffusion-Automatic1111\stable-diffusion-webui

    checkpoints: models/Stable-diffusion
    configs: models/Stable-diffusion

... i did not changed anyting else ...

And it did not worked... i tried to add the path to the "checkpoints" as well with the same structure ( C:\Users\No565\Stable-Diffusion-Automatic1111\stable-diffusion-webui\models\Stable-diffusion) but nothing. I even tried to use as the "base_path" the comfyui folder and than the path to the models in the stable diffusion folder under checkpoints but nothing as well... ( : 
--------------------------------------------------

The original file looks like this : 

#Rename this to extra_model_paths.yaml and ComfyUI will load it


#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
a111:
    base_path: path/to/stable-diffusion-webui/

    checkpoints: models/Stable-diffusion
    configs: models/Stable-diffusion
    vae: models/VAE
    loras: |
         models/Lora
         models/LyCORIS
    upscale_models: |
                  models/ESRGAN
                  models/RealESRGAN
                  models/SwinIR
    embeddings: embeddings
    hypernetworks: models/hypernetworks
    controlnet: models/ControlNet

#config for comfyui
#your base path should be either an existing comfy install or a central folder where you store all of your models, loras, etc.

#comfyui:
#     base_path: path/to/comfyui/
#     checkpoints: models/checkpoints/
#     clip: models/clip/
#     clip_vision: models/clip_vision/
#     configs: models/configs/
#     controlnet: models/controlnet/
#     embeddings: models/embeddings/
#     loras: models/loras/
#     upscale_models: models/upscale_models/
#     vae: models/vae/

#other_ui:
#    base_path: path/to/ui
#    checkpoints: models/checkpoints
#    gligen: models/gligen
#    custom_nodes: path/custom_nodes

1) Should i use the "a111:" or the "comfyui"? 
-> In case the "comfyui" i need to put an "#" in front of all the entries of the "a111" and remove the ones before the "comfyui", right?



Could someone make me an example with the correct path structure, please ? Thank you in advance !

**Comment by No565** [comment]
I was impatient so i tried it again and this time worked ... i did the same thing though (  : ....

Now it looks like this : 

#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
a111:
base_path: C:\Users\No565\Stable-Diffusion-Automatic1111\stable-diffusion-webui

checkpoints: models/Stable-diffusion
configs: models/Stable-diffusion
vae: models/VAE
...

I did not changed anything else, only added the path as shown above . Maybe because i restarted comfyui... although i refreshed it when i tried the first time .. it worked with a model.. anyway , thx :)

**Comment by jesusisavailable** [comment]
Is there a way to use more than one path for the models, loras, etc?
Exemple: base_path: models/Stable-diffusion & F:\AI\ModelsLinked\ComfyUI
Thank you.

**Comment by Christopher-Moonlight** [comment]
I know I'm late to the party here but if anyone searching for the answer to this is reading through, here's a simple possibility that makes all of this moot. Here's the first question to ask. 

**Is the .example hidden and you're just editing the text file?**

Confirm the File Extension Change:

    If file extensions are hidden, you might not see the .example part. To ensure you're renaming it correctly, enable file extensions:

        Open File Explorer.

        Click on the View tab.

        Check the box for File name extensions.

    Now, copy and rename the file again if necessary to ensure it ends with .yaml.
