### ISSUE TITLE
Can we add a judgment node that can ignore nodes？

### ISSUE THREAD

**Issue by 807502278** [comfyanonymous/ComfyUI#3447]
![image](https://github.com/comfyanonymous/ComfyUI/assets/46019416/1f3e234c-3ec0-492d-97c1-d0dc54f3e677)
For example, when # 10 is true, # 11 and # 12 will not run under any circumstances
(Switch any is the logical switch node of the plugin)

Reason: This can optimize nodes that have no impact on the final result, greatly improving the efficiency of large-scale workflows!

**Comment by ltdrdata** [comment]
https://www.youtube.com/watch?v=KLe1hShwVDs

**Comment by 807502278** [comment]
Oh, oh, impact can actually do it. Thank you for notifying me!
