### ISSUE TITLE
[Functionality] Add Disco Diffusion

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#345]
Add disco diffusion model loading and sampling

**Comment by comfyanonymous** [comment]
How do they compare to stable diffusion?

**Comment by WASasquatch** [comment]
> How do they compare to stable diffusion?

It's slow, but the effect is totally unique, and not obtainable with SD without fine-tuning on Disco Diffusion images, which just means a very biased model doing only what the user imputed it with. 

It has a great charm about it, and the communities are still active on facebook, discord, and reddit. I imagine they would absolutely love a new program to use, and mix with stable diffusion that isn't the old Disco Diffusion colab or my old Easy Diffusion colab.

**Comment by robinjhuang** [comment]
@WASasquatch Is this still needed? I see this custom node exists
https://github.com/space-nuko/ComfyUI-Disco-Diffusion

**Comment by WASasquatch** [comment]
The custom node is unfortunately abandoned, but no I don't think it's necessary now. While the DD community was trying to hang on *then*, it's rather dead now.
