### ISSUE TITLE
Checkpoint save not saving the model resuting from LORA

### ISSUE THREAD

**Issue by LinTevis** [comfyanonymous/ComfyUI#3452]
By using an old portable ver from 31-07-2023 I'm able to merge the lora to the model by applying lora to them and then then save checkpoint but by using newer(don't know exactly version) portable version it end up saving the checkpoint.

Basically

(31-07-2023) Load checkpoint -- load lora -- checkpoint save => checkpoint with lora

(Newest) Load checkpoint -- load lora -- checkpoint save => checkpoint without lora

Extra datails: the (31-07-2023) version run in a HDD with ~180gb of space while the (Newest) version run in a SSD with 12gb space left. flags --lowvram --force-fp16 --fp16-vae --disable-smart-memory.

**Comment by shawnington** [comment]
Have you made sure all your packages are up to date? What are your packager versions? This process works fine for me.

**Comment by comfyanonymous** [comment]
This should be fixed now.
