### ISSUE TITLE
Loading checkpiont become extremely slow recently

### ISSUE THREAD

**Issue by 90aspark** [comfyanonymous/ComfyUI#3457]
I have a 3050ti GPU laptop, and I'm loading checkpoints from an external SSD.
Usually, loading an XL checkpoint would take around 30-60 seconds to complete.
But started from 3 days ago, it took more than 5 minutes to just loaded the model, which is not normal.

**I've already tried:**(I will keep updating this list)
- Load checkpionts from internal disk rather than the external one.
- Completely re-install comfyui.
- Update comfyui and all python dependencies (both system and python_embeded).
- Downgrade GeForce Game Ready Driver (from 552.44 to 552.22).
- Referred issues from #972, #1992 and tried out.
- Forced comfyui to use normalvram instead of lowvram.

But non of the above fixed my problem.

```
got prompt
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 1733.6152935028076
  0%|                                                                                           | 0/30 [00:00<?, ?it/s]C:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:345: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchsde\_brownian\brownian_interval.py:608: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:56<00:00,  3.88s/it]
Requested to load AutoencoderKL
Loading 1 new model
Prompt executed in 468.42 seconds
```
Please help, thanks!

**Edited: **the problem doesn't appeared when I load checkpoint in A1111.

**Comment by 90aspark** [comment]
Problem solved. Just update comfyui again and everything works fine.

**Comment by subspecs** [comment]
Using Wan 2.2 it even more of an issue, up to date comfi and all.
Everything runs fast, from clips to any other processing, including the sampler.
But when it comes to loading diffusion models (even with default node) it for some reason FIRST loads into RAM, which it does VERY SLOWLY even on an ssd (like 13GB model takes literally 5 minutes), and then it instantly drops it in the GPU's VRAM and everything moves along like it should.
Doesn't matter if I use a CLIP of 11GB or more, that one loads fast and fine, but anything to do with loading diffusion models does this.
FFs, why can't it drop it STRAIGHT into the GPU instead?

If I use the --normal-vram option then this issue happens and is a massive pain with comfi.
But If I use the -high-vram option then it loads FUCKING INSTANTLY, BUT, it shoves everything else in VRAM as well(Why df would you not let me just pick which nodes/models I want in my vram instead?) and making it go OOM.

Honestly, comfi's memory management is utter trash these days, I had to write a custom hack-ish memory cleaner to save many GB's of vram and ram just to get some things even to not throw OOM.

And all I am trying to run is a 13GB Wan model (Nothing else needs to exist in the GPU's VRAM or my RAM, other than sampler working cache and CLIP/VAE produced positives/negatives, NOT THEIR MODELS), and this is supposed to work on a 32GB RAM and a 3090 24GB rig as well.
