### ISSUE TITLE
Updated now lost my text box.

### ISSUE THREAD

**Issue by DarkAlchy** [comfyanonymous/ComfyUI#3474]
I then started with a fresh install to then have it install everything then start up and 
![image](https://github.com/comfyanonymous/ComfyUI/assets/10561690/5c06dc86-8f35-452e-ba15-4acb73409ef9)

any ideas how to fix this?

**Comment by ltdrdata** [comment]
It is deprecated node of https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes.
The node is no more exists. You have to replace it to DF_TextBox.

**Comment by shawnington** [comment]
> It is deprecated node of https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes. The node is no more exists. You have to replace it to DF_TextBox.

Im mildly impressed by your ability to pick random nodes out the ether with relatively little information. Impressive.

**Comment by DarkAlchy** [comment]
Thank you.
