### ISSUE TITLE
How can i remove an uploaded image?

### ISSUE THREAD

**Issue by liusida** [comfyanonymous/ComfyUI#3475]
I was now using ComfyUI as a backend.
I was planning to remove the uploaded image after the process finished for privacy reason. But I can't find a "/remove" api to do it. What is the suggested way to remove the recently uploaded image?

Thanks.

**Comment by ltdrdata** [comment]
You cannot remove files through API. If you need that you need to develop your own extension.

**Comment by shawnington** [comment]
If you were running local, go to /ComfyUI/input/ all the data you input into your local version will be there.

**Comment by liusida** [comment]
Cool, I'll just D-I-Y. :D

**Comment by liusida** [comment]
https://github.com/liusida/ComfyUI-Login?tab=readme-ov-file#upload-privacy-nodes

I've just made this. And I think it is secure enough. xD

**Comment by shawnington** [comment]
> https://github.com/liusida/ComfyUI-Login?tab=readme-ov-file#upload-privacy-nodes
> 
> I've just made this. And I think it is secure enough. xD

That is not actually secure, deleting the file after saving still allows for another actor to copy the file before it's deleted, or change file permissions on all files saved to prevent deletion. 

It should be preventing the file from being saved in the first place.
