### ISSUE TITLE
[Feature Request] Invoke Lora via Prompts (ClipTextEncode Nodes)

### ISSUE THREAD

**Issue by Neverdusk** [comfyanonymous/ComfyUI#348]
Would it be possible to complement Lora loading through prompts, similar to Auto1111? For example, a ClipTextEncode node might contain: `masterpiece, best quality, rest of the prompt, <lora:loraName:1>`. 

I'm mostly requesting this because my workflow uses multiple models (one for generation, another for high-pass, etc), and managing model and clip connections feels more complicated with the addition of LoraLoader nodes, especially when using the same Lora for each one. Moreover, there's currently no way to select "No Lora", so generating without them involves removing LoraLoader nodes and rerouting the nodes around them each time. 

Perhaps I'm missing something that would make using Loras simpler, but at the moment it feels less intuitive than it could be.

**Comment by comfyanonymous** [comment]
I don't think loras belong in the text prompt because they have nothing to do with the text prompts. Embeddings belong there because they are like words but Loras are a patch on the model.

If you want "No Lora" you can set the strength to zero.

**Comment by Neverdusk** [comment]
That makes sense. In that case, would it be possible to implement some alternative that wouldn't involve requiring a separate LoraLoader mode for each model? Though I'm not sure what that would look like.
