### ISSUE TITLE
--dont-upcast-attention missing

### ISSUE THREAD

**Issue by vicentecarro** [comfyanonymous/ComfyUI#3488]
I'm getting an error launching comfyui with my typical parameters and it fails to load because:
main.py error: unrecognized arguments: --dont-upcast-attention
Was this feature removed? replaced with something else?
Linux Ubuntu 24.04, 64bits, Nvidia 8GB VRAM.

**Comment by ltdrdata** [comment]
Yup that is removed.

https://github.com/comfyanonymous/ComfyUI/commit/bb4940d837f0cfd338ff64776b084303be066c67

**Comment by vicentecarro** [comment]
> Yup that is removed.
> 
> [bb4940d](https://github.com/comfyanonymous/ComfyUI/commit/bb4940d837f0cfd338ff64776b084303be066c67)

I see. Thanks
