### ISSUE TITLE
 Updated ComfyUi and I cannot edit text. 

### ISSUE THREAD

**Issue by korinho23** [comfyanonymous/ComfyUI#3490]
![image](https://github.com/comfyanonymous/ComfyUI/assets/28938332/c2beeba8-0949-48b3-a6d2-4e01276af759)

 I have recently updated ComfyUi and am unable to modify text (No text box). I tried different browsers, same problem.

**Comment by bollenta** [comment]
oh yeah just wrote the same problem, please merge if you want

**Comment by korinho23** [comment]
The problem is with the MixLab Node. Turn it off until there is an update! :-)

**Comment by rexorp** [comment]
> The problem is with the MixLab Node. Turn it off until there is an update! :-)

I am having the same problem with Fizznodes Batch Prompt Schedule and seemingly any other prompt text input node I choose.
😔
