### ISSUE TITLE
after update: all text nodes don't work anymore

### ISSUE THREAD

**Issue by bollenta** [comfyanonymous/ComfyUI#3491]
I just updated ComfyUI and none of my workflows work anymore as the text field in all text nodes disappeared,
does anyone have an idea what could have happened?
![image](https://github.com/comfyanonymous/ComfyUI/assets/19305323/482a9a27-3289-431b-a1a7-383ff9534571)

**Comment by mcmonkey4eva** [comment]
see https://github.com/comfyanonymous/ComfyUI/issues/3490
