### ISSUE TITLE
Closed due to others with same issue opened, was Text boxes in nodes not showing.

### ISSUE THREAD

**Issue by Aenon1** [comfyanonymous/ComfyUI#3492]
After updating everything today, none of the nodes that contain a text box will show the box or the text. I tried 4 different browsers(javascript enabled, nothing blocked), cache, etc., cleaned, the image shows what I am getting. It worked fine before the update.

It is ALL nodes that contain text boxes, not just certain ones.

I also have a clean version with no extra nodes installed(just manager and it was not updated today) through Pinokio and it is working fine.

The prompt that shows in the command window after running what is in the image is:
text_positive_styled: Cubism Art, , flat geometric forms, cubism art
text_negative_styled: ugly, deformed, noisy, blurry, low contrast
![error](https://github.com/comfyanonymous/ComfyUI/assets/131623315/5c9e7c85-85c3-4b03-b9a8-7ea13db91d9c)

**Comment by Aenon1** [comment]
Closing this, I see 2 other issues with the same problem have been opened.

**Comment by Aenon1** [comment]
Sorry.

**Comment by NeedsMoar** [comment]
Just reminding you :-)  Thanks btw, most people just open bugs here and leave them that way forever.

**Comment by rexorp** [comment]
I am having the same problem. What is the fix?
