### ISSUE TITLE
 [HELP with __init__.py] I have the problem with the following Custom Nodes, which when I want to install manually, I get an error 

### ISSUE THREAD

**Issue by metahades18892** [comfyanonymous/ComfyUI#3498]
**I have the problem with the following Custom Nodes, which when I want to install manually, I get an error:

- Clip-interrogator-ext

- ComfyUI-AnimateDiff-Evolved-main

- distill2

- LAMA**

__________________________________________________

Total VRAM 6144 MB, total RAM 16334 MB

Set vram state to: NORMAL_VRAM

Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER : cudaMallocAsync

VAE dtype: torch.float32

Using pytorch cross attention

Traceback (most recent call last):

File "C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\[nodes.py](https://nodes.py/)", line 1879, in load_custom_node

module_spec.loader.exec_module(module)

File "<frozen importlib._bootstrap_external>", line 936, in exec_module

File "<frozen importlib._bootstrap_external>", line 1073, in get_code

File "<frozen importlib._bootstrap_external>", line 1130, in get_data

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\clip-interrogator-ext\\__init__.py'

Cannot import C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\clip-interrogator-ext module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\clip-interrogator-ext\\__init__.py'

Traceback (most recent call last):

File "C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\[nodes.py](https://nodes.py/)", line 1879, in load_custom_node

module_spec.loader.exec_module(module)

File "<frozen importlib._bootstrap_external>", line 936, in exec_module

File "<frozen importlib._bootstrap_external>", line 1073, in get_code

File "<frozen importlib._bootstrap_external>", line 1130, in get_data

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-AnimateDiff-Evolved-main\\__init__.py'

Cannot import C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-main module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-AnimateDiff-Evolved-main\\__init__.py'

Adding C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path

Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!

Loaded Efficiency nodes from C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui

Loaded ControlNetPreprocessors nodes from C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux

Loaded AdvancedControlNet nodes from C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet

Loaded AnimateDiff from C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff\animatediff/sliding_schedule.py

Could not find IPAdapter nodes

Loaded VideoHelperSuite from C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite

Could not load ImpactPack nodes Could not find ImpactPack nodes

Total VRAM 6144 MB, total RAM 16334 MB

Set vram state to: NORMAL_VRAM

Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER : cudaMallocAsync

VAE dtype: torch.float32

### ComfyUI Revision: 2186 [46daf0a9] | Released on '2024-05-16'

#fix sys.stdout.isatty

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

--------------

### Mixlab Nodes: Loaded

LaMaInpainting.available True

ClipInterrogator.available True

PromptGenerate.available True

ChinesePrompt.available True

RembgNode_.available True

--------------

------------------------------------------

Comfyroll Studio v1.76 : 175 Nodes Loaded

------------------------------------------

** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md

** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki

------------------------------------------

Traceback (most recent call last):

File "C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\[nodes.py](https://nodes.py/)", line 1879, in load_custom_node

module_spec.loader.exec_module(module)

File "<frozen importlib._bootstrap_external>", line 936, in exec_module

File "<frozen importlib._bootstrap_external>", line 1073, in get_code

File "<frozen importlib._bootstrap_external>", line 1130, in get_data

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\distill2\\__init__.py'

Cannot import C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\distill2 module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\distill2\\__init__.py'

Traceback (most recent call last):

File "C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\[nodes.py](https://nodes.py/)", line 1879, in load_custom_node

module_spec.loader.exec_module(module)

File "<frozen importlib._bootstrap_external>", line 936, in exec_module

File "<frozen importlib._bootstrap_external>", line 1073, in get_code

File "<frozen importlib._bootstrap_external>", line 1130, in get_data

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\LAMA\\__init__.py'

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Manager/issues/687

**Comment by metahades18892** [comment]
solved: https://github.com/ltdrdata/ComfyUI-Manager/issues/687#issuecomment-2116422200

**Comment by metahades18892** [comment]
solved: https://github.com/ltdrdata/ComfyUI-Manager/issues/687#issuecomment-2116422200
