### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\clip-interrogator-ext\\__init__.py'

### ISSUE THREAD

**Issue by metahades18892** [comfyanonymous/ComfyUI#3499]
any solution for this?:

Cannot import C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\clip-interrogator-ext module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\clip-interrogator-ext\\__init__.py'
Traceback (most recent call last):
  File "C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-AnimateDiff-Evolved-main\\__init__.py'

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Manager/issues/687

**Comment by metahades18892** [comment]
solved: https://github.com/ltdrdata/ComfyUI-Manager/issues/687#issuecomment-2116422200

**Comment by metahades18892** [comment]
solved: https://github.com/ltdrdata/ComfyUI-Manager/issues/687#issuecomment-2116422200

**Comment by metahades18892** [comment]
solved: https://github.com/ltdrdata/ComfyUI-Manager/issues/687#issuecomment-2116422200
