### ISSUE TITLE
Is it possible to have checkpoints, embeddings, models, vae, etc. on an external drive? 

### ISSUE THREAD

**Issue by oakif** [comfyanonymous/ComfyUI#35]
I keep all of the above files on an external drive due to the large space requirements. Is there an option to select a custom directory where all my models are located, or even directly select a checkpoint/embedding/vae by absolute filesystem path?

**Comment by xPheo** [comment]
While it may not be ideal for some, what I do is keep my large files on a NAS and I soft link them to the local checkpoint folder. Works like a charm.

**Comment by GeneralAwareness** [comment]
> While it may not be ideal for some, what I do is keep my large files on a NAS and I soft link them to the local checkpoint folder. Works like a charm.

With WebUI there are a couple of extensions I ran into that threw errors up.  Seems WebUI doesn't care much for symlinks so the folder I was using for those extensions I had to bring back to the same drive they used else gradio would complain and cause the extensions to not really work.  It is an issue with gradio, but those people are too touchy-feely so instead of farting with them I brought the folders back over.  Streamit is better anyway.

I am not sure what this is written on but if it uses gradio the same issue will arrise as it had for me in every app that used gradio (never an issue with streamit apps).

**Comment by comfyanonymous** [comment]
ComfyUI does not and will never use gradio. The code that searches for the checkpoints/etc.. should follow symlinks without any issue.

The plan is to have an option to add search paths but that isn't implemented yet.

**Comment by GeneralAwareness** [comment]
> ComfyUI does not and will never use gradio. The code that searches for the checkpoints/etc.. should follow symlinks without any issue.
> 
> The plan is to have an option to add search paths but that isn't implemented yet.

LOVE IT.

Thank you.

**Comment by siraxe** [comment]
> While it may not be ideal for some, what I do is keep my large files on a NAS and I soft link them to the local checkpoint folder. Works like a charm.

how do you do that ?

**Comment by butaixianran** [comment]
So, since it supports symlinks, please put this into readme.md Document.

## Custom Model Folder
Symlinks is supported. For windows, symlinks can be used as mklink command in cmd window. Search "Windows mklink" in google for tutorial.

**Comment by oakif** [comment]
> > So, since it supports symlinks, please put this into readme.md Document.
> > ## Custom Model Folder
> > Symlinks is supported. For windows, symlinks can be used as mklink command in cmd window. Search "Windows mklink" in google for tutorial.
> 
> symlinks are an OS feature supported by every program, they have nothing to do with this one.

Given that there are multiple issues regarding this subject, I don't think it'll hurt to add this information into the README. If we left only pertinent information in README files that were not available anywhere else, that would defeat the purpose of a README.

**Comment by rfletchr** [comment]
> > > So, since it supports symlinks, please put this into readme.md Document.
> > > ## Custom Model Folder
> > > Symlinks is supported. For windows, symlinks can be used as mklink command in cmd window. Search "Windows mklink" in google for tutorial.
> > 
> > 
> > symlinks are an OS feature supported by every program, they have nothing to do with this one.
> 
> Given that there are multiple issues regarding this subject, I don't think it'll hurt to add this information into the README. If we left only pertinent information in README files that were not available anywhere else, that would defeat the purpose of a README.

yeah as a workflow thing it makes allot of sense

**Comment by comfyanonymous** [comment]
This was fixed with: https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example

**Comment by GithubStable** [comment]
Is there a way to link MULTIPLE paths on this yaml?
