### ISSUE TITLE
Patch NSFW Default Prompt

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#350]
The default prompt yields nudity in like 90% of the gens I do on any model. Additionally, it uses girl, which means a good number are underage nudity. Maybe it should be a more neutral prompt like a place, building or setting?

**Comment by comfyanonymous** [comment]
I tried the prompt quickly on SD1.5, anythingv3 and WD1.5 beta 2 to make sure and none of the ~30 images I generated had any nudity in them....

I have been thinking of changing it though so that the default image it generates is more visually impressive.

**Comment by WASasquatch** [comment]
1.5 is more modest, but I still get barely clothed girls in a lot of gens, some nude

![image](https://user-images.githubusercontent.com/1151589/229244785-ceaf84fd-93c6-45aa-afe6-1139c8e7bdd1.png)

I don't use Anything/WD cause that's mainly anime. I use stuff like Protogen, Redshift, Dreamlike,  etc. Only anime model I have is a mix from a friend, but that produces nudes too.

**Comment by comfyanonymous** [comment]
If you craft me a simple and visually impressive prompt for SD1.5 I'll replace it with that.

**Comment by WASasquatch** [comment]
> If you craft me a simple and visually impressive prompt for SD1.5 I'll replace it with that.

This is simple, and cute for the "ComfyUI" sorta name that instills such feelings. Some of the images are over sharpened cause my workflow was applying highpass sharpening before I realized and unhooked it. 

Positive
`vector graphic, centered cute kawaii kitten, sticker art`
Negative
`drawing, sketch, bad artwork`

### 1.5
![ComfyUI_00794_](https://user-images.githubusercontent.com/1151589/229247946-cde61f95-1db0-4bd9-b248-04475ecefb41.png)
![ComfyUI_00790_](https://user-images.githubusercontent.com/1151589/229247956-ec559c91-8689-4b05-8a56-ac2fc8fe8e73.png)
![ComfyUI_00784_](https://user-images.githubusercontent.com/1151589/229247965-78b7619b-60e7-4086-9792-284ff1fc39f0.png)
![ComfyUI_00785_](https://user-images.githubusercontent.com/1151589/229247973-f94ba7a2-3dbe-4c7b-8d6f-74a1b0edd7c7.png)
![ComfyUI_00783_](https://user-images.githubusercontent.com/1151589/229247979-b1ef4949-8535-4fbe-9533-2cd6db8a489b.png)
![ComfyUI_00762_](https://user-images.githubusercontent.com/1151589/229248002-38c1eeed-d3bc-4550-a146-627800c380f4.png)
![ComfyUI_00736_](https://user-images.githubusercontent.com/1151589/229248022-95d0f041-5038-4006-bc81-4123e0c3eaa4.png)

# Protogen 2.2
![ComfyUI_00802_](https://user-images.githubusercontent.com/1151589/229248299-dbb2b095-230c-492f-8ed1-724c5c58c298.png)
![ComfyUI_00804_](https://user-images.githubusercontent.com/1151589/229248303-15d434da-ed92-458c-904f-2148c8a4d900.png)
![ComfyUI_00808_](https://user-images.githubusercontent.com/1151589/229248313-3c573265-936d-4159-a826-fb323b219efd.png)
![ComfyUI_00815_](https://user-images.githubusercontent.com/1151589/229248319-474805e0-0031-4885-981f-fc70decc283f.png)
![ComfyUI_00819_](https://user-images.githubusercontent.com/1151589/229248337-5c99191f-93b4-4388-a211-ea65417eaef4.png)

**Comment by abbail** [comment]
I'm partial to `cozy bedroom` it generally makes good results and you can include `person` or `people` in the negative if you want to be doubly sure no one shows up on a bed, but I've never seen nudity using it on SD 1.5

**Comment by WASasquatch** [comment]
> I'm partial to `cozy bedroom` it generally makes good results and you can include `person` or `people` in the negative if you want to be doubly sure no one shows up on a bed, but I've never seen nudity using it on SD 1.5

Do you mean juuust `cozy bedroom`? Reminds me a lot of looking for housing when moving, and that's triggering... xD Lol

**Comment by abbail** [comment]
perhaps `comfy bedroom` is more appropriate!

**Comment by WASasquatch** [comment]
Pretty unappealing, honestly. Just looks like realty images.

**Comment by comfyanonymous** [comment]
Should be fixed now: https://github.com/comfyanonymous/ComfyUI/commit/ebd7f9bf80213a44a8e2cadc75875a4b980991e5

**Comment by WASasquatch** [comment]
> Should be fixed now: [ebd7f9b](https://github.com/comfyanonymous/ComfyUI/commit/ebd7f9bf80213a44a8e2cadc75875a4b980991e5)

Nice, I like that one. Cool results like Disco Diffusion default prompt
