### ISSUE TITLE
Cannot listen executing event in websocket 

### ISSUE THREAD

**Issue by Arthur-xu** [comfyanonymous/ComfyUI#3503]
In the  websocket example script seems like prmpt job is finisehd if type event is  'executing' and node is null. But I found cannot trigger executing event in websocket. Only status and progress event type are available(text2image and img2image).
<img width="559" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/44384100/714962a9-f796-4b5c-a3c8-65069236092d">
<img width="635" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/44384100/2e7eec1c-24f4-4194-be3d-9006d0d32083">

Anything wrong?
https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py#L36C25-L36C29

**Comment by SachiaLanlus** [comment]
@Arthur-xu 
Do you find the solution?
I am facing the same issue here.
Trying to figure out the flow of api...
