### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by metahades18892** [comfyanonymous/ComfyUI#3505]
hello, solution for this?

  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\motion_module_ad.py", line 1112, in forward
    x = x + self.pe[:, : x.size(1)]
        ^~~~~~~
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by LILILIBIU** [comment]
This is the internal behavior of the plugin and has nothing to do with ComfyUI itself. If you want to use this plugin normally, you should move the relevant tensor to the CPU before the code error occurs

**Comment by mcmonkey4eva** [comment]
post in https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved
