### ISSUE TITLE
I can't load workflows through the Jason file.

### ISSUE THREAD

**Issue by razvanab** [comfyanonymous/ComfyUI#3509]
I can't load workflows through the Jason file, and the only way to load any workflow is only through the ComfyUI-Manager load button. There is no error in the logs either.

**Comment by ltdrdata** [comment]
Press F12 (if chrome) and see the console log.

**Comment by razvanab** [comment]
2exifr.js:2  Uncaught (in promise) Error: Unknown file format

[default.json](https://github.com/comfyanonymous/ComfyUI/files/15360423/default.json)

**Comment by razvanab** [comment]
Any ideas on how to fix this?

**Comment by ltdrdata** [comment]
> 2exifr.js:2 Uncaught (in promise) Error: Unknown file format
> 
> [default.json](https://github.com/comfyanonymous/ComfyUI/files/15360423/default.json)

It seems that you have installed some custom nodes which is causing that issue.
Disable all custom nodes and try again.

**Comment by razvanab** [comment]
You are right. I searched for that file, and I found it in this extension:
"ComfyUI_ExtendedImageFormats"
So I uninstalled it, and now everything is working.

**Comment by ltdrdata** [comment]
This issue is patched.
https://github.com/kaanyalova/ComfyUI_ExtendedImageFormats/issues/1
