### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI\\ComfyUI\\custom_nodes\\controlnet_aux\\__init__.py'

### ISSUE THREAD

**Issue by metahades18892** [comfyanonymous/ComfyUI#3510]
**I have this error, help pls**:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI\\ComfyUI\\custom_nodes\\controlnet_aux\\__init__.py'

Cannot import C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\controlnet_aux module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\kevin\\Desktop\\ComfyUI\\ComfyUI\\custom_nodes\\controlnet_aux\\__init__.py'
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite: `ffmpeg_bin_path` is set to: C:♀fmpeg♀fmpeg-2024-01-20-git-6c4388b468-full_builin
WAS Node Suite: Finished. Loaded 212 nodes successfully.

        "Art is the most intense mode of individualism that the world has known." - Oscar Wilde

Import times for custom nodes:
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds (IMPORT FAILED): C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\controlnet_aux
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.1 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.3 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.3 seconds (IMPORT FAILED): C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   0.4 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.8 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\eden_comfy_pipelines
   1.4 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes
   3.4 seconds: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
!!! Exception during processing!!! No module named 'controlnet_aux.color'
Traceback (most recent call last):
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\color.py", line 15, in execute
    from controlnet_aux.color import ColorDetector
ModuleNotFoundError: No module named 'controlnet_aux.color'

Prompt executed in 0.11 seconds
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]

**Comment by mcmonkey4eva** [comment]
use https://github.com/Fannovel16/comfyui_controlnet_aux
