### ISSUE TITLE
ModuleNotFoundError: No module named 'controlnet_aux.color'

### ISSUE THREAD

**Issue by metahades18892** [comfyanonymous/ComfyUI#3511]
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
!!! Exception during processing!!! No module named 'controlnet_aux.color'
Traceback (most recent call last):
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\color.py", line 15, in execute
    from controlnet_aux.color import ColorDetector
ModuleNotFoundError: No module named 'controlnet_aux.color'

Prompt executed in 0.11 seconds
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]

**Comment by metahades18892** [comment]
thx for the amazing help

**Comment by mcmonkey4eva** [comment]
The controlnet aux repo is here: https://github.com/Fannovel16/comfyui_controlnet_aux
