### ISSUE TITLE
 I can't interact with the workspace.

### ISSUE THREAD

**Issue by stalker168** [comfyanonymous/ComfyUI#3515]
After the latest update I can't interact with the workspace.
When the page loads, the workspace is dark grey and does not display the background grid along with the nodes. I can't navigate through the space. Any changes in the workspace and nodes are displayed after scaling the page. 
At the same time, the generation process works.

After launch
![image](https://github.com/comfyanonymous/ComfyUI/assets/31571343/c75c9342-4313-4a42-a167-8d402472342d)
After scaling
![image](https://github.com/comfyanonymous/ComfyUI/assets/31571343/71de147d-170b-4d7e-8ea2-d6e1e81b3afa)

**Comment by mcmonkey4eva** [comment]
It looks like you have a bunch of custom nodepacks modifying your UI - try removing them. I'd suspect most likely one of them is at fault
