### ISSUE TITLE
ControlNet Causes Black Images

### ISSUE THREAD

**Issue by pphoto808** [comfyanonymous/ComfyUI#3516]
ControlNet seems to be the culprit (at least for me) for black images. If I bypass or remove controlnet (apply or apply advance), images are generated. I saw the other thread about black images, but none addressed controlnet. 

I just now updated Comfy and that's when the problems started. I saw an update for controlnet aux when i did update via manger. Thought that would solve the problem but it did not. 

Manger says Comfy is up to date.

**Comment by pphoto808** [comment]
Doing more testing. Even after removing ControlNet from previous workflows, still get black images.  if I delete loaders (checkpoint, lora, etc), prompts, and sampler, install them again I get images. However still black images if I add controlnet.

**Comment by comfyanonymous** [comment]
What's your GPU, checkpoint you are using, controlnet, etc..?

**Comment by pphoto808** [comment]
Sorry, normal I lead off with specs: 
Apple Studio M2 Ultra, MacOS Sonoma 14.5

okkkkkk....I just spent the last two hours running through various combinations of configs. I would get black images sometimes depending on how many steps I used. Fewer steps, less black images. But what finally dawn on me was the default workflow worked with any amount of steps EVERY TIME.  The sampler and scheduler was the key. This time narrowed it down for sure. Karras! I tested euler, euler_a, dpmpp_sde, dpmpp_2m, dpmpp_2m_sde with normal, exponential, and sgm_uniform schedulers. No black images, even with workflows prior to updates. ANDDDD with ControlNet. EVERY TIME I used Karras, black images. I say this every time...not sure if this is just a Mac issue or not. But the last two hours were not wasted.

**Comment by comfyanonymous** [comment]
Can you give me a simple workflow that returns a black image for you?

**Comment by pphoto808** [comment]
![Screenshot 2024-05-19 at 14 25 55](https://github.com/comfyanonymous/ComfyUI/assets/134026421/47c20626-c983-4d70-8ed8-2091b4a9009b)
[blackscreen.json](https://github.com/comfyanonymous/ComfyUI/files/15371344/blackscreen.json)

Default workflow. Just changed the scheduler to karras.  Included screen shot so you see what i see.

**Comment by comfyanonymous** [comment]
If you run ComfyUI with `--dont-upcast-attention` does that fix it?

**Comment by pphoto808** [comment]
Nope :(

**Comment by comfyanonymous** [comment]
Sorry I meant `--force-upcast-attention`

Can you also try updating pytorch to see if it fixes the issue?

**Comment by pphoto808** [comment]
> Sorry I meant `--force-upcast-attention`
> 
> Can you also try updating pytorch to see if it fixes the issue?

Ok, the --force-upcast-attention did the trick. Tested with controlnet at 30 steps and all looks good. 

Updating pytorch was the first thing i tried lol.  

I just need to modify start script for Pinokio now and test it there.

**Comment by pphoto808** [comment]
Modified start.json for Pinokio. All good. 

Thanks for the assist!
