### ISSUE TITLE
ERROR WHEN LOADING LORA 

### ISSUE THREAD

**Issue by Suka4GitHub** [comfyanonymous/ComfyUI#3518]
I'm getting the following error when using sdxl or any model with lora.

lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_in.alpha
lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_in.lora_down.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_in.lora_up.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_out.alpha
lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_out.lora_down.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_out.lora_up.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_out.lora_down.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_out.lora_up.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_k.alpha
lora key not loaded: lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_k.lora_down.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_k.lora_up.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_out_0.alpha
lora key not loaded: lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_out_0.lora_down.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_out_0.lora_up.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_q.alpha

Any suggestions would be much appreciated thank you in advance!

xo

**Comment by andreszs** [comment]
Probably a plugin-related error or your comfyui installation is too outdated. Update it with ComfyUI manager extension and retry.

**Comment by Suka4GitHub** [comment]
Hi andreszs, thank you sweetie.
Comfy up to date, will check plug ins. any info on which plug ins cause issues with loras?

**Comment by Suka4GitHub** [comment]
I worked it out. xo
