### ISSUE TITLE
search for types should not be (only) unsorted dropdown list

### ISSUE THREAD

**Issue by oO0** [comfyanonymous/ComfyUI#3520]
When install many nodes, dropdown list of input, output types (3rd field in search window) contains too many items, that are not sorted.
Possible improvement:
* replace 3rd field with combo box or make another search field to type characters

or

* use 1st search field 

to filter dropdown lists: so if i type "latent" - dropdown list (3rd field in search window) will contains only items with "latent"

**Comment by ltdrdata** [comment]
This has now been improved through the node library provided in the sidebar of the New UI.
