### ISSUE TITLE
"--preview-method taesd" cmd line arg does not appear to work properly

### ISSUE THREAD

**Issue by not-ski** [comfyanonymous/ComfyUI#3526]
The new code to change the default "auto" preview mode to Latent2RGB seems to have broken TAESD previews. I tried changing my cmd line arg to "--preview-method taesd", but it's clearly still using Latent2RGB.

I verified this by going into my local installation, reverting the change, and changing my --preview-method back to auto. This then gave me TAESD previews as before.

Not entirely sure what's causing this; the code _looks_ like it should be working (as long as --preview-method is set to "taesd") but it's not, at least on my machine. I even double-checked my spelling of "taesd" multiple times (by copy-pasting the string that corresponds to the enum value).

**Comment by ltdrdata** [comment]
If you are using ComfyUI-Manager. It overrides the preview method setting. Make sure that.

![image](https://github.com/comfyanonymous/ComfyUI/assets/128333288/35eafb13-7dc9-4f50-ba3d-3852231ffad5)

**Comment by not-ski** [comment]
Ah, yeah that is almost certainly the issue. Thanks! Closed.
