### ISSUE TITLE
    raise ClientConnectorError(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]

### ISSUE THREAD

**Issue by Dengjun21** [comfyanonymous/ComfyUI#3529]
I think the problem was the network issue because I check the code verified_ssl set False already at 3.8.6 aiohttp package, and this log snippet:
` custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 583, in get_data 
  async with session.get(uri) as resp:`

I print the uri was to get 3 json files of the  `ComfyUI-Manager` , So We have another solution can help me ?

**Comment by ltdrdata** [comment]
Set `bypass_ssl = True` in `ComfyUI-Manager/config.ini`
And try again.

**Comment by Dengjun21** [comment]
Well,I Change the `etc/hosts` to resolve `raw.githubusercontent.com`, And
 > Set bypass_ssl = True in ComfyUI-Manager/config.ini
This error has been resolved,I try restart server,But I still didn't see Manager in slider panel of the GUI.
So I  try to drag some workflow  json to GUI,It prompt me failed to load some custom_nodes(ImageResize+...etc).
Anyway,Can I install these custom_nodes with manual way?Where I can find these url of resource ? 
Thanks! @ltdrdata

**Comment by ltdrdata** [comment]
> This error has been resolved,I try restart server,But I still didn't see Manager in slider panel of the GUI.
> So I try to drag some workflow json to GUI,It prompt me failed to load some custom_nodes(ImageResize+...etc).
> Anyway,Can I install these custom_nodes with manual way?Where I can find these url of resource ?
> Thanks! @ltdrdata

Just custom node git dir clone to `ComfyUI/custom_nodes` If you want to install them manually.
You can see custom nodes from here.
https://ltdrdata.github.io/
