### ISSUE TITLE
The text box component cannot be loaded

### ISSUE THREAD

**Issue by lhh012** [comfyanonymous/ComfyUI#3535]
![Quicker_20240521_174231](https://github.com/comfyanonymous/ComfyUI/assets/145631306/14378943-7ce5-4ca1-a282-67cdd51c1bc8)
![Quicker_20240521_174245](https://github.com/comfyanonymous/ComfyUI/assets/145631306/3ae7eefb-5aa2-4a9e-80bc-8c1e9098d8cb)
![Quicker_20240521_174317](https://github.com/comfyanonymous/ComfyUI/assets/145631306/72a887a9-c5ac-410d-843e-a16e1cc5ab8d)
The text box component cannot be loaded，No other components are missing

**Comment by ltdrdata** [comment]
This nodes is renamed to DF_TextBox you have to replace to new node.
