### ISSUE TITLE
python crashes in Ksampler after MacOS 14.5 update

### ISSUE THREAD

**Issue by denisvanw** [comfyanonymous/ComfyUI#3540]
Mac Studio M1 Max 32 Mos / MacOS 14.5 / Python 3.12.2 / Torch 2.4
(after updating MacOS and maybe (?) ComfyUI via manager)

- at first it still worked but the preview were broken (noise instead of picture) 
- then it began to systematically crash on Ksampler, evenr for the basic workflow.
- Python crashes with always the same message :

/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

???

**Comment by ManuelEsteves** [comment]
Same problem for me (Mac Studio M2 Max 64 GB).
I've just updated ComfyUI ...

**Comment by ManuelEsteves** [comment]
@denisvanw
Unfortunately we'll have to wait for a fix.
For your information, I've installed an old version (from 2 weeks ago), and it works for me on M2 Max.
If it helps, here's the link to the working version :
[https://github.com/comfyanonymous/ComfyUI/tree/f374ea714d8c32c2f214e818146b06754c963028](url)

**Comment by denisvanw** [comment]
> @denisvanw Unfortunately we'll have to wait for a fix. For your information, I've installed an old version (from 2 weeks ago), and it works for me on M2 Max. If it helps, here's the link to the working version : https://github.com/comfyanonymous/ComfyUI/tree/f374ea714d8c32c2f214e818146b06754c963028

Are you also on MacOS 14.5 ?

**Comment by ManuelEsteves** [comment]
> Are you also on MacOS 14.5 ?

I'm on Ventura 13.6
But we're having the same problem with the latest version of ComfyUI

**Comment by denisvanw** [comment]
After spending half an hour trying to make sense of the various Git explanations and tutorials I found online... I must admit that I am a Git newbie and I still don't know how to clone a specific Git branch...  ; (

**Comment by comfyanonymous** [comment]
If you disable the previews does it work?

**Comment by ManuelEsteves** [comment]
> If you disable the previews does it work?

I tried this first.
I deactivated the preview and tried all the available screensavers.
I get a black output image.
However, if I do about 8 Steps on the KSampler I manage to get an image. But after that I get nothing.
Obviously I've tried different models, but that doesn't change anything.

**Comment by comfyanonymous** [comment]
Just to make sure this with ComfyUI updated to the latest version?

**Comment by ManuelEsteves** [comment]
Yes, it's the latest version.
I did the update today, and it stopped working straight away

**Comment by comfyanonymous** [comment]
if you install pytorch stable 2.3 do you have the same issue?

**Comment by denisvanw** [comment]
Yup !
Same thing exactly.

**Comment by comfyanonymous** [comment]
Should be fixed now if you update ComfyUI.

**Comment by ManuelEsteves** [comment]
It works for me.
Thank you so much!

**Comment by denisvanw** [comment]
Working here too.
Thanx so much for this fast and efficient answer !

**Comment by Rooky404** [comment]
Got this error again...sadly. ksampler image 60% stopped and changed to solid black
RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))

comfyui up-to-date (08-06)
Mac Sonoma 14.6
torch 2.4.0
(pillow downgrade to 9.5.0 cause psd-tools incompatible...
