### ISSUE TITLE
After updating to the latest version, an issue occurred where the environment crashes as soon as an image is displayed

### ISSUE THREAD

**Issue by yiwangsimple** [comfyanonymous/ComfyUI#3541]
Hi god, mine is m1 max 64G
After updating to the latest and getting out the graphs normally a couple of times, after rebooting, there is a problem - the base text born graphs out of the graphs will directly cause the Python environment to crash. The error is as follows:
Python(1820,0x35ef87000) malloc: Incorrect checksum for freed object 0x3eb64a600: probably modified after being freed.
Corrupt value: 0x6e94fb5376ce2999
Python(1820,0x35ef87000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
(comfyui) weiweideMacBook-Pro:comfyui weiwei$ /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

**Comment by yoland68** [comment]
What's your torch version and macOS version?

**Comment by comfyanonymous** [comment]
Should be fixed now.
