### ISSUE TITLE
When using the prompt randomizing feature of ComfyUI, the cursor will automatically and constantly jump to the end of the prompt.

### ISSUE THREAD

**Issue by Jellybit** [comfyanonymous/ComfyUI#3543]
1. Clear the workflow.
2. Insert a Clip Text Encode node (you can even add one from other developers).
3. Enter a random selection in a prompt, like so:
```
{option1|option2|option3}
rest of prompt
```
4. Now attempt to edit any of the options, or really anything in the prompt except for the end of it.

Result:
The cursor will jump to the end of the prompt (in the case above, the end of the word "prompt"). This makes it nearly impossible to edit the prompt if using the randomizing feature described here:

https://blenderneko.github.io/ComfyUI-docs/Interface/Textprompts/

Using Chrome on Windows 10.

**Comment by ltdrdata** [comment]
This issue should be reported to here:
https://github.com/pythongosssss/ComfyUI-Custom-Scripts

**Comment by Jellybit** [comment]
Thank you. For anyone else running into this, I have reported it in this issue: https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/257
