### ISSUE TITLE
Quick Search Palette not working

### ISSUE THREAD

**Issue by vootox** [comfyanonymous/ComfyUI#3544]
Although all my nodes are listed in the Search Palette window nothing is found when I type a character in the search box. The drop-down lists are also empty. Using Windows Portable I have three and two of them are doing this. Also, when I go to close the box it won't go away like it usually does if I click outside on the canvas (or node window/board) I have to use ESC key.

**Comment by vootox** [comment]
Disabling Malwarebytes Browser Guard seems to have fixed the searching part. For closing I still have to use the ESC key, though it will automatically close assuming you find what you're looking for so that's wasn't my main concern just another sympom, I guess. I'll see how it goes for a few days because it did randomly work now and then but more often it would not.

**Comment by mcmonkey4eva** [comment]
That's weird that malwarebytes broke things, but... yeah unfortunately browser extensions breaking things is pretty common and hard to fix from the webdev side, usually it has to be reported as a bug with the extension

**Comment by vootox** [comment]
It's now working fine with MB enabled, all good.
