### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by pppigrui** [comfyanonymous/ComfyUI#3546]
can you write the package version to the requirements.txt like torch==2.3.0

**Comment by bigcat88** [comment]
*many people use PyTorch nightly version*

**Comment by doctorpangloss** [comment]
use the instructions for installation here - https://github.com/hiddenswitch/ComfyUI?tab=readme-ov-file#installing

**Comment by mcmonkey4eva** [comment]
Made a meta-issue for requirements.txt versioning #3679
