### ISSUE TITLE
widgets_values order relies on JSON Object keys order.

### ISSUE THREAD

**Issue by ganlvtech** [comfyanonymous/ComfyUI#3547]
https://github.com/comfyanonymous/ComfyUI/blob/6507a9c71691102fcba3d3a6adcf68303cb33895/web/scripts/app.js#L1641-L1646

**Comment by mj321** [comment]
FWIW: I consider it a really bad design flaw that the widgets values are stored without keys in the JSON. When a custom node adds a new property somewhere in the middle, and you load an older workflow, all following properties are off by one.

```
      "widgets_values": [
        "enable",
        366053738524694,
        "randomize",
        20,
        8,
        "euler",
        "normal",
        0,
        10000,
        "disable"
      ]
```

**Comment by geroldmeisinger** [comment]
see: https://github.com/Comfy-Org/rfcs/pull/2

**Comment by ganlvtech** [comment]
The new `widgets_values_named` can be a successor of `widgets_values`. https://github.com/Comfy-Org/ComfyUI_frontend/pull/10392
