### ISSUE TITLE
Workflow suggestion

### ISSUE THREAD

**Issue by cgwers** [comfyanonymous/ComfyUI#3548]
Hi,

I love comfy, but the windows portable version is extremely unstable and tends to die rather quickly and require a reinstall. No, really. Once the portable begins complaining about torch it's all over but the re-install.

I install from the repo installation if there was a STABLE branch. MASTER is a development branch and is therefore not stable by DevOps's definition.

Please, please, I know you're swamped. I can see the open issues. IMHO, making a side project to create a STABLE release branch would relieve a great deal of the pressure from users who are complain about the unstable dev build (i.e., the MASTER). That's where tester's should play. I'm certain that if you asked you'd have no shortage of seasoned ComfyUI users volunteering to help. 

As a second suggestion, not scanning and updating comfy's modules during launch that would solve the issue of broken or conflicting upstream packages into a comyfui instance that worked just fine on its last run.

I'd not a dev, but I do code, I even have an app in production where I worked. I've been working with dev teams for 40 years and IMHO, the development workflow and project management are your biggest obstacles. 

I want you to succeed.

**Comment by ltdrdata** [comment]
As long as the version of torch installed doesn't change, such issues shouldn't occur. Have you checked if the version of torch has changed?

FYI, a safeguard has recently been added to ComfyUI-Manager to prevent custom nodes from arbitrarily changing the version of torch and some other pip packages.
