### ISSUE TITLE
Comfyui shows high-quality previews?

### ISSUE THREAD

**Issue by A-B-01** [comfyanonymous/ComfyUI#3551]
Hi, after the latest updates, I noticed that the "K sampler preview" seems to generate corrupted images 

![corrupted preview](https://github.com/comfyanonymous/ComfyUI/assets/122019053/6123eade-0b53-4fa6-9148-8d68fa9c1ff3)

**Comment by comfyanonymous** [comment]
I changed the "auto" previews to the low quality ones, if you want the high quality ones you need to use "taesd" instead of "auto".

**Comment by A-B-01** [comment]
> I changed the "auto" previews to the low quality ones, if you want the high quality ones you need to use "taesd" instead of "auto".

--preview-method taesd


Great! It worked!

Thanks a lot!!!

**Comment by ltdrdata** [comment]
> > I changed the "auto" previews to the low quality ones, if you want the high quality ones you need to use "taesd" instead of "auto".
> 
> --preview-method taesd
> 
> Great! It worked!
> 
> Thanks a lot!!!

FYI, the default setting changing to `low` from `auto` is because `taesd` causes significant performance loss.

**Comment by shawnington** [comment]
> > > I changed the "auto" previews to the low quality ones, if you want the high quality ones you need to use "taesd" instead of "auto".
> > 
> > 
> > --preview-method taesd
> > Great! It worked!
> > Thanks a lot!!!
> 
> FYI, the default setting changing to `low` from `taesd` is because `taesd` causes significant performance loss.

Thats very confusing naming, I get it, but I feel like we should try and standardize away form method naming when other options are implemented especially without other alternatives. `low` and `high`. Some of the launch options are quite cryptic, which if you have no problems looking around the code base isn't an issue, but for your average person, some of them, are a bit... well.. yeah you know of have to have bit of background to know what the terminology means.

**Comment by ltdrdata** [comment]
> > > > I changed the "auto" previews to the low quality ones, if you want the high quality ones you need to use "taesd" instead of "auto".
> > > 
> > > 
> > > --preview-method taesd
> > > Great! It worked!
> > > Thanks a lot!!!
> > 
> > 
> > FYI, the default setting changing to `low` from `taesd` is because `taesd` causes significant performance loss.
> 
> Thats very confusing naming with the command line options, going from normal being high quality to now you have to know what taesd is to re-enable it.
> 
> but also, its very questionable to have gui options be command line, when it should just be a toggle in the gui. No reason there can't be a toggle for quality.
> 
> Some of the launch options are quite cryptic, which if you have no problems looking around the code base isn't an issue, but for your average person, some of them, are a bit... googling will make you even more confusedish.

So the ComfyUI-Manager supports opitons for preview.

**Comment by wisniew** [comment]
This should be addressed at least in the readme.

**Comment by andreszs** [comment]
After the last update v0.2.3-13-g7390ff3, the `--preview-method taesd` option persists in rendering blurry, noisy previews instead of hight quality ones. This is after restarting comfyui and the browser countless times.
