### ISSUE TITLE
Xformers seems does not work

### ISSUE THREAD

**Issue by A-B-01** [comfyanonymous/ComfyUI#3552]
After installing Xformers on the Comfyui, I got this message
![xformers corrupted](https://github.com/comfyanonymous/ComfyUI/assets/122019053/c74daf8d-84a5-4ce3-9eb5-495cb169306e)
![xformers corrupted1](https://github.com/comfyanonymous/ComfyUI/assets/122019053/4d7a311b-0fef-4004-a2f2-544b207cb17a)

**Comment by NeedsMoar** [comment]
What's the question? You highlighted the exact part of the error message telling you why it won't load already.  Go download the right wheel for your version or upgrade torch to 2.3.0

**Comment by A-B-01** [comment]
> What's the question? You highlighted the exact part of the error message telling you why it won't load already. Go download the right wheel for your version or upgrade torch to 2.3.0

Ok, so I'm using ComfyUI Portable, now I deleted it and downloaded it again, 
then I did a "comfyui update" but, I still having some errors

![Captura de tela 2024-05-23 140107](https://github.com/comfyanonymous/ComfyUI/assets/122019053/fe57a8d4-1fb8-41e7-bcfc-2bd4a5983d4d)


Could you explain to me how to do this upgrade, because I am having many difficulties here.

**Comment by ltdrdata** [comment]
> > What's the question? You highlighted the exact part of the error message telling you why it won't load already. Go download the right wheel for your version or upgrade torch to 2.3.0
> 
> Ok, so I'm using ComfyUI Portable, now I deleted it and downloaded it again, then I did a "comfyui update" but, I still having some errors
> 
> ![Captura de tela 2024-05-23 140107](https://private-user-images.githubusercontent.com/122019053/333278413-fe57a8d4-1fb8-41e7-bcfc-2bd4a5983d4d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDg5MTgsIm5iZiI6MTcxNjUwODYxOCwicGF0aCI6Ii8xMjIwMTkwNTMvMzMzMjc4NDEzLWZlNTdhOGQ0LTFmYjgtNDFlNy1iY2ZjLTJiZDRhNTk4M2Q0ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMzU2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWMzMDJiMDYyNWRkNzAwODYwYTA2NzdhOTk0ZTRlNzQ3MjRlY2ExZjA3M2IwNzkyYWQzODU5ZWU5ZjNlNGUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aCPK-kzMLpi5i9Ql6SSHrlLmQwzDCH85kyqgahdLeSU)
> 
> Could you explain to me how to do this upgrade, because I am having many difficulties here.

Your pytorch and xformers version is mismatched.

**Comment by mcmonkey4eva** [comment]
You might also just remove xformers, pytorch has native transformer acceleration that works equally well nowadays
