### ISSUE TITLE
After 1 generation with SDXL model ComfyUI crashes

### ISSUE THREAD

**Issue by Lewis-Di39** [comfyanonymous/ComfyUI#3566]
I've been using ComfyUI for a while and don't have any issue until now, using the same workflow with SDXL models I was able to work for hours now after the first generation Comfy crashed. I am using a laptop with 8gb of RAM and RTX  3060 with 6gbVRAM. 
![Captura de pantalla 2024-05-24 194234](https://github.com/comfyanonymous/ComfyUI/assets/122175613/1a47bd5f-8bc2-46a4-92cb-d2abc7f76e34)
![Captura de pantalla 2024-05-24 194627](https://github.com/comfyanonymous/ComfyUI/assets/122175613/e147c1c3-10d9-47f9-9137-7c51d7e31b5f)

**Comment by ltdrdata** [comment]
Your 8GB RAM is too small. 
Once the SDXL checkpoint is loaded while the OS or other applications are running, it is already a miracle that it holds up.

**Comment by NeedsMoar** [comment]
The iterative upscale probably doesn't help anything either, nodes that do that in one go tend to do silly things like not freeing the latents until the end...  plus SDXL can probably already generate at your final resolution (well a less silly version of it anyway) in a single shot which should use far less memory than any upscaling method.  I've done SD 1.5 generations @ 1280x1280 during the first ~40 steps without even using deep shrink on some of the newest tuned checkpoints without defects creeping in.

**Comment by mcmonkey4eva** [comment]
The CLI argument `--fp8_e4m3fn-unet` might be useful here to save you from RAM crashes


.. but yeah also look into if your laptop has upgradable RAM, if you can even just get that up to 16GiB you'll be much better off

**Comment by Lewis-Di39** [comment]
> Your 8GB RAM is too small. Once the SDXL checkpoint is loaded while the OS or other applications are running, it is already a miracle that it holds up.

Thanks, you were right I updated my RAM to 32GB and now it works perfect

**Comment by Lewis-Di39** [comment]
> The CLI argument `--fp8_e4m3fn-unet` might be useful here to save you from RAM crashes
> 
> .. but yeah also look into if your laptop has upgradable RAM, if you can even just get that up to 16GiB you'll be much better off

Thanks, I upgraded my RAM and it works perfect.
