### ISSUE TITLE
Karras give black image after ComfyUI update 

### ISSUE THREAD

**Issue by Creative-comfyUI** [comfyanonymous/ComfyUI#3567]
I solved the problem using  --force-upcast-attention

When I try to render an image with Karras Sampler using a batch size of 3, I get a black image with all types of Ksampler.  If I use a batch size of 1 instead of 3 images, there is no black image. If I want to access the image with a batch size of 3 images without having a black image, I have to use the latent from the batch.  Worst of all sometimes if I use two ksamplers in the same workflow and one is set to karras the other will also give a black image until I change the karras it is not often but it can happen. The problem seems to be the same for the simple sampler. 

I have tried all possible combinations with no change. There is no error in the terminal.

**Comment by DDlisit** [comment]
+1
