### ISSUE TITLE
When loading the graph, the following node types were not found

### ISSUE THREAD

**Issue by metahades18892** [comfyanonymous/ComfyUI#3571]
I installed Stylegan, but when I click on Install Missing Custom Nodes or Install Custom Nodes, the missing nodes do not appear

![zxczxczxczxcxc](https://github.com/comfyanonymous/ComfyUI/assets/163777886/b6790b9c-cd99-4619-99d4-753442bbcf9f)

**Comment by mcmonkey4eva** [comment]
This is an issue with the stylegan node pack, not comfy itself
