### ISSUE TITLE
RuntimeError: input must be 4-dimensional

### ISSUE THREAD

**Issue by cognizant951** [comfyanonymous/ComfyUI#3572]
System: Ryzen 3600x - RX 6800 16 GB - Windows 10 - Latest comfyui

can successfully run and generate vids from sv3d (https://huggingface.co/stabilityai/sv3d) using CPU flag, each iteration taking around 30 min.
using --directml flag produces this runtime error.

[comfyui.log](https://github.com/comfyanonymous/ComfyUI/files/15444569/comfyui.log)

**Comment by Eyefinitys** [comment]
same error

VAEEncode

input must be 4-dimensional
