### ISSUE TITLE
Error occurred when executing DWPreprocessor

### ISSUE THREAD

**Issue by eduardocodes** [comfyanonymous/ComfyUI#3578]
I'm following the [V2_ipadapter_face_clothes_controlnet.json](https://github.com/dataleveling/ComfyUI-IPAdapter-FaceIDv2-Workflow) workflow, but I'm getting an error at the ControlNet step:

`OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:275: error: (-5:Bad argument) Can't read ONNX file: D:\Área de Trabalho\PROJETO\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v/DWPose\dw-ll_ucoco_384.onnx in function 'cv::dnn::dnn4_v20231225::ONNXImporter::ONNXImporter'`

## Troubleshooting Steps Taken:

1) Confirmed dw-ll_ucoco_384.onnx file is in the correct folder.
2) Verified dw-ll_ucoco_384.onnx file integrity (not corrupted).
3) Reinstalled ComfyUI, nodes, and models.
4) Installed dependencies (onnx, opencv).
5) Converted ONNX file to a different opset version.

These steps didn't solve the issue. Any ideas on how to fix it?

**Comment by ltdrdata** [comment]
Try moving your ComfyUI directory to a location other than `D:\Área de Trabalho`.

**Comment by eduardocodes** [comment]
Works! Thank you so much!

**Comment by eduardocodes** [comment]
Works! Thank you so much!
