### ISSUE TITLE
Slot Name will auto reset every time.

### ISSUE THREAD

**Issue by K-O-N-B** [comfyanonymous/ComfyUI#3580]
I have rename the slot name from "image" to "result".

but it will turn to "image" again when I reflash the page or restart the comfyui.

What can I do?

**Comment by mcmonkey4eva** [comment]
What do you mean "slot name"?

**Comment by K-O-N-B** [comment]
> What do you mean "slot name"?

![image](https://github.com/comfyanonymous/ComfyUI/assets/152141077/8684a222-5abb-400e-b34e-76e60dcbbadf)

**Comment by LPG-VERSION** [comment]
+1, This issue made my experience with Comfyui extremely poor when defining components myself

**Comment by LPG-VERSION** [comment]
> +1, This issue made my experience with Comfyui extremely poor when defining components myself

I deleted AIGODLIKE-ComfyUI Translation， This problem has been resolved 

read Node title and slots are always reset. #214

**Comment by LPG-VERSION** [comment]
> +1, This issue made my experience with Comfyui extremely poor when defining components myself

https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/issues/214,
I deleted AIGODLIKE-ComfyUI Translation， This problem has been resolved
