### ISSUE TITLE
executing KSampler

### ISSUE THREAD

**Issue by Idiosyncras** [comfyanonymous/ComfyUI#3581]
Error occurred when executing KSampler:

Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 8, 192, 128] to have 4 channels, but got 8 channels instead

**Comment by mcmonkey4eva** [comment]
... how did you do that, what? Can you post your workflow?

**Comment by zmczmc123654** [comment]
@mcmonkey4eva i have the same issue,
<img width="1238" alt="msedge_P4uLJnC04Q" src="https://github.com/user-attachments/assets/d8ef00d1-a2d5-4d4a-a373-cf6f0f97a2e9">

**Comment by mcmonkey4eva** [comment]
That's an ICLight node breaking, so report to ICLight's github
