### ISSUE TITLE
How to handle an exception in the prompt_worker thread?

### ISSUE THREAD

**Issue by WooXinyi** [comfyanonymous/ComfyUI#3599]
Sometimes thread exception occurred when using custom nodes, but comfyui server process will not terminate. In this situation, I have to kill it by PID and restart it, is there another elegant way?

**Comment by mcmonkey4eva** [comment]
... How exactly did you create an exception so severe that it blocked shutdown?

The only way I can see this happening normally is an infinite loop / lockup, something that actually prevents signal processing like that
