### ISSUE TITLE
Command line Flag --deterministic breaking KSampler preview 

### ISSUE THREAD

**Issue by DukeSniper** [comfyanonymous/ComfyUI#3600]
Got "blank white" KSampler previews for a few days now when using command line flag `--deterministic`. Reverting [this commit](https://github.com/comfyanonymous/ComfyUI/commit/58c9838274f53c6aa8912992db9f73e9a0721227)  fixes them again. Alternatively, starting without the command line option is a temporary workaround.

Windows 10, NVIDIA GeForce 4070 Super, pytorch 2.3.0+cu121, Python 3.12.3

**Comment by mcmonkey4eva** [comment]
Oh probably fixed by https://github.com/comfyanonymous/ComfyUI/commit/bf3e334d468876bbf69d022e7a6770b0c52dd615
