### ISSUE TITLE
[Bug]: When I set the face model of the reactor function of the comfy ui to GFPGAN, it does not come out normally.

### ISSUE THREAD

**Issue by devZu9** [comfyanonymous/ComfyUI#3610]
What happened?
When I set the face model of REACTOR, an extension of comfyUI, to GFPGAN and run the prompt, the face is not displayed normally, and the face is displayed as white smoke.

Also, on a black screen, the following message appears.

Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
WARNING: comfy_extras.chainner_models is deprecated and has been replaced by the spandrel library.

I tried uninstalling and reinstalling this to fix the issue, but that didn't work.

When I use codeformer, I don't get that message and the faces look fine. I want to solve this problem.

![image](https://github.com/comfyanonymous/ComfyUI/assets/45079090/459ca296-bd54-43c4-8dbc-134a4e7547b4)

Steps to reproduce the problem
Set the face model of the reactor function to GFPGAN. Start the prompt.

What should have happened?
The face should have changed clearly.

What browsers do you use to access the UI ?
Google Chrome

[2024-05-28.json](https://github.com/user-attachments/files/15506919/2024-05-28.json)

For Stable Diffusion I use the StabilityMatrix project. It has the ability to create separate configurations. It monitors and suggests updates, all through the UI.
But besides this, it is possible to install releases. I don’t know what kind of information this is, but most likely knowledgeable people will tell you.
So, I did my research, installing all possible releases. And I can say exactly after which release it broke.

bf3e334 - broken
71ec5b1 - broken
91542d4 - broken
b26da22 - broken
0920e0e - broken
34030fe - broken
f6a2039 - broken
16a493a - broken
9a151b7 - broken (but even Reacor won’t start here)
8cfd677 - broken (but even Reacor won’t start here)
ffc4b7c - **WORKS!**
5b87369 - WORKS!

**Comment by shawnington** [comment]
This is an already open issue #3594
