### ISSUE TITLE
Branched Execution Order Control Node

### ISSUE THREAD

**Issue by 807502278** [comfyanonymous/ComfyUI#3611]
Add a router node with multiple outputs,Execute subsequent branches in order from top to bottom.
Because when connecting multiple branches, it is impossible to control which branch runs first,
A simple example: Image connects two save nodes and cannot control which one saves first,
Of course, the actual situation will not be so simple. For example, I hope a fast running branch will produce results first.

**Comment by mcmonkey4eva** [comment]
Likely https://github.com/comfyanonymous/ComfyUI/pull/2666 is a prerequisite

**Comment by 807502278** [comment]
Thank you for the tip, it turns out someone has raised this issue before.
