### ISSUE TITLE
No Webcam Image Capture loop

### ISSUE THREAD

**Issue by tuangd** [comfyanonymous/ComfyUI#3612]
Hi,

I tried the new webcam node. 
When it cause error because webcam is not there or can't capture anything, it will cause an endless loop of error. 
I restart ComfyUI to comeback to the same error as ComfyUI loaded the same workflow up.

I have to try to delete that node by quickly select the node and click delete while in between that error pop-up.
So, alternately press 'enter' and 'delete' very quick to get out of that situation.

I think I should report it here.

I was trying to find a way to load ComfyUI with some other workflow before staring the server. But not sure how.

Windows 11
Browser: Vivaldi
Logitech webcam

**Comment by shawnington** [comment]
Do you get an error in console? If so, please paste the error here.

**Comment by tuangd** [comment]
No error in the comfyUI console but there some error log in the browser dev tool though.
here
[127.0.0.1-1717306427907.log](https://github.com/user-attachments/files/15524291/127.0.0.1-1717306427907.log)
![image](https://github.com/comfyanonymous/ComfyUI/assets/8474403/e98db276-65dd-4226-9430-80d7ef253767)

**Comment by ltdrdata** [comment]
> No error in the comfyUI console but there some error log in the browser dev tool though. here [127.0.0.1-1717306427907.log](https://github.com/user-attachments/files/15524291/127.0.0.1-1717306427907.log) ![image](https://private-user-images.githubusercontent.com/8474403/335842242-e98db276-65dd-4226-9430-80d7ef253767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MTQ4MTIsIm5iZiI6MTczMTUxNDUxMiwicGF0aCI6Ii84NDc0NDAzLzMzNTg0MjI0Mi1lOThkYjI3Ni02NWRkLTQyMjYtOTQzMC04MGQ3ZWYyNTM3NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTNUMTYxNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDMzOGE5MWIxNmJiZTE5Mzk3MDQ1OTJiOWFhNzcxZGIzYWY3ZjE5MmQxNTc5ZjI1MTY4Yjc2YTgxYjM4MWI3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mZCdhFqX_NjQBKneyjF497E3ONzK9svqbvHqvzOPBFM)

Disable "use everywhere" and test it.
