### ISSUE TITLE
Sticky Mouse On Failed Nodes

### ISSUE THREAD

**Issue by AtomicPerception** [comfyanonymous/ComfyUI#3614]
Easy to recreate. Drop a workflow on ComfyUI with a node you don't have. Click on the broken RED node box. On my Windows 10 machine, the mouse refuses to drop the node and moves it all around everywhere, stuck to the mouse pointer.  My guess is broken nodes have no event processors.

So, that's probably the fix. When ComfyUI generates a RED placeholder node, that node should have basic event processing to register when a mouse-up event occurs, and the node can drop back to the workspace.

**Comment by mcmonkey4eva** [comment]
I can't replicate this, I can drop the red box of a broken node just fine

**Comment by ltdrdata** [comment]
This could be an error caused by the extension.
If it happens consistently, try disabling all custom nodes and test again.

**Comment by AtomicPerception** [comment]
Confirmed, it is related to rgthree custom nodes. I guess it's their bug.

**Comment by AtomicPerception** [comment]
Confirmed, it is related to rgthree custom nodes. I guess it's their bug.
