### ISSUE TITLE
Switching workflows back and forth, GPU memory leakage

### ISSUE THREAD

**Issue by garbe-github-support** [comfyanonymous/ComfyUI#3616]
Nvidia GPU, windows, lastest comfyui
There are some custom nodes in the workflow.
When I run workflow A and call soft_empty_cache, 60% of the GPU memory is still occupied. If I switch to workflow B to run more, then run workflow A, and switch back and forth, the video memory occupation will continue to increase, greater than the sum of A and B video memory requirements, like a video memory leak. May I know how to solve this problem.

**Comment by comfyanonymous** [comment]
Post the workflows that cause issues.

**Comment by garbe-github-support** [comment]
> Post the workflows that cause issues.发布导致问题的工作流。
[换发型-火影鸣人.json](https://github.com/user-attachments/files/16048964/-.json)
[地中海-正式版.json](https://github.com/user-attachments/files/16048965/-.json)
Switching back and forth using a workflow like this will cause the GPU memory to rapidly increase, exceeding the total memory required for the two workflows

**Comment by mcmonkey4eva** [comment]
That workflow is full of custom nodes, it's quite likely that one of them is at fault -- try testing with only vanilla comfy nodes and see if the same issue occurs. Presuming it doesn't add back some of the custom nodes and test that way - you'll be able to pretty quickly narrow down which one is broken. Once you do, report the issue on the github for that custom node pack.
