### ISSUE TITLE
ComfyUI has any LLM chatbot or chatinterface implementation plan?

### ISSUE THREAD

**Issue by frankchieng** [comfyanonymous/ComfyUI#3619]
IMO gradio has [chatbot](https://www.gradio.app/guides/creating-a-chatbot-fast) already,i'm curious if ComfyUI will integrate LLM in future?

**Comment by mcmonkey4eva** [comment]
There are several custom node packs for LLMs, such as https://github.com/huchenlei/ComfyUI_omost and https://github.com/if-ai/ComfyUI-IF_AI_tools and https://github.com/get-salt-AI/SaltAI_Language_Toolkit

Integrated natively may come in the future but is not a current priority
