### ISSUE TITLE
something wrong after update today

### ISSUE THREAD

**Issue by daizhuo** [comfyanonymous/ComfyUI#3622]
Hi.........Everything went smoothly yesterday. 
But everything goes wrong today.
I can't even generate a picture when using sdxl models..
It made my computer restart when the processing was near the end.
I'm using RTX3060 12G.

**Comment by shawnington** [comment]
Is there an error log you can post?

**Comment by daizhuo** [comment]
Thanks for your help!
Nothing error, just keep restarting.......
GPU RAM issue?

> Is there an error log you can post?

**Comment by ltdrdata** [comment]
> Thanks for your help! Nothing error, just keep restarting....... GPU RAM issue?
> 
> > Is there an error log you can post?

If the computer is restarting, it is likely a hardware issue rather than a software issue. Alternatively, it could be caused by a driver.
