### ISSUE TITLE
Hunyuan DiT Support?

### ISSUE THREAD

**Issue by MoRanYue** [comfyanonymous/ComfyUI#3624]
I hear that tencent Hunyuan DiT can understand both the english and chinese prompt better, will it be supported?

https://github.com/Tencent/HunyuanDiT

https://huggingface.co/Tencent-Hunyuan/HunyuanDiT

**Comment by brayevalerien** [comment]
If you want to use Hunyuan DiT (and other various models) in ComfyUI, there is the [ExtraModels extension](https://github.com/city96/ComfyUI_ExtraModels).

**Comment by MoRanYue** [comment]
> If you want to use Hunyuan DiT (and other various models) in ComfyUI, there is the [ExtraModels extension](https://github.com/city96/ComfyUI_ExtraModels).

thank you, but i am still looking forward to official support

**Comment by NineMeowICT** [comment]
This is Tencent's official implementation: https://github.com/Tencent/HunyuanDiT/tree/main/comfyui-hydit

**Comment by brayevalerien** [comment]
Great. They have recently been addes to 🤗 diffusers too, so that's another option.

**Comment by MoRanYue** [comment]
> This is Tencent's official implementation: https://github.com/Tencent/HunyuanDiT/tree/main/comfyui-hydit

thank you very much, i will try it then

**Comment by doctorpangloss** [comment]
hunyuandit is complex to use. read more about installing it easily here: https://github.com/hiddenswitch/ComfyUI?tab=readme-ov-file#lts-custom-nodes
