### ISSUE TITLE
Export/Load JSON API Format is broken.

### ISSUE THREAD

**Issue by PeterTucker** [comfyanonymous/ComfyUI#3627]
Attached are two json files exported from ComfyUI, one normal the other for api.  The normal one can be imported with no issues, while the API version's nodes have broken links.

[workflow.json](https://github.com/user-attachments/files/15525721/workflow.json)
[workflow_api.json](https://github.com/user-attachments/files/15525722/workflow_api.json)

**Comment by Amorano** [comment]
> Attached are two json files exported from ComfyUI, one normal the other for api. The normal one can be imported with no issues, while the API version's nodes have broken links.
> 
> [workflow.json](https://github.com/user-attachments/files/15525721/workflow.json) [workflow_api.json](https://github.com/user-attachments/files/15525722/workflow_api.json)

That isnt broken, that is how it works. Those are two different formats. One is for the UX and the other is for the non-UX (API).

You can easily open them and see they are not the same format -- nor are they targeted to be the same.
