### ISSUE TITLE
doest find enter point

### ISSUE THREAD

**Issue by sunlery** [comfyanonymous/ComfyUI#3644]
![image](https://github.com/comfyanonymous/ComfyUI/assets/20901030/5b388eb2-f726-486e-9641-aa162087e554)

**Comment by mcmonkey4eva** [comment]
xformers is a bit messy - I'd recommend just uninstalling xformers and using modern pytorch's built in transformers acceleration. if you use the default comfy install https://github.com/comfyanonymous/ComfyUI/releases this is done properly by default.
