### ISSUE TITLE
--listen issue for local network

### ISSUE THREAD

**Issue by aniketgore** [comfyanonymous/ComfyUI#3646]
I am getting below error after doing a fresh install on a local network linux machine.

 File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
  File "aiohttp/_http_parser.pyx", line 732, in aiohttp._http_parser.cb_on_header_value
aiohttp.http_exceptions.LineTooLong: 400, message:
  Got more than 8190 bytes (9188) when reading Header value is too long.

I tried reinstall, removing the custom nodes and other things, but whenever I use --listen this error comes.

**Comment by shawnington** [comment]
Is there a longer error you can post?

**Comment by all4you** [comment]
I have met the same issue after I updated all nodes by ComfyUI-Manager
I start up comfyui by running:
```shell
LOG_FILE="logs/comfyui.log"
APP_SCRIPT="main.py --listen 0.0.0.0 --port 7860"

start_app() {
        echo "Starting the application..."
        nohup python -u $APP_SCRIPT > $LOG_FILE 2>&1 &
        echo "Application started."
}
```
The error msg is:
```python
Error handling request
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
  File "aiohttp/_http_parser.pyx", line 732, in aiohttp._http_parser.cb_on_header_value
aiohttp.http_exceptions.LineTooLong: 400, message:
  Got more than 8190 bytes (8214) when reading Header value is too long.
```
![image](https://github.com/comfyanonymous/ComfyUI/assets/6661305/df571a31-617f-4515-a27d-322576d06f9a)

![image](https://github.com/comfyanonymous/ComfyUI/assets/6661305/e897b593-e326-4990-80b9-ac05c389dbdf)

But I can visit it in Traceless mode：
![image](https://github.com/comfyanonymous/ComfyUI/assets/6661305/cb640f77-79f5-45f3-8398-5e42672b312f)

**Comment by all4you** [comment]
Is there any progress？
