### ISSUE TITLE
Websocket Help

### ISSUE THREAD

**Issue by ameen-roayan** [comfyanonymous/ComfyUI#3647]
Hi all,

I'm working on a project where I need to establish a WebSocket connection to comfy between a device and a server running on my home PC. The goal is to send data from the device to the server for processing and get a response back. an img2img workflow

Setup:

WebSocket Server: Running on my home PC.

WebSocket Client: Running on another device (e.g., Raspberry Pi).

Port Forwarding: Configured ports 8764-8766 on the router.

Firewall: Allowed inbound connections on port 8765.

Public IP: Confirmed and used correctly.

Issue:

The WebSocket client on the device fails to connect to the server on the home PC, resulting in a TimeoutError.

Troubleshooting Steps Taken:

Tested Local Connection: Successful on the home PC.

Checked Port Forwarding: Verified on the router.

Firewall Settings: Configured to allow port 8765.

Scripts:
**WebSocket Server:**

`import asyncio
import websockets

async def echo(websocket, path):
    async for message in websocket:
        await websocket.send(message)

start_server = websockets.serve(echo, "0.0.0.0", 8765)

asyncio.get_event_loop().run_until_complete(start_server)
print("WebSocket server running on ws://0.0.0.0:8765")
asyncio.get_event_loop().run_forever()
`
**WebSocket Client:**

`import asyncio
import websockets

async def test_connection():
    uri = "ws://<public-ip>:8765"  # Replace with your public IP address
    try:
        async with websockets.connect(uri, timeout=20) as websocket:
            await websocket.send("ping")
            response = await websocket.recv()
            print(f"Response: {response}")
    except Exception as e:
        print(f"Connection failed: {e}")
        import traceback
        print(traceback.format_exc())

asyncio.run(test_connection())
`

Any ideas on what might be causing the timeout or how to fix it?

Thanks!

**Comment by MrFredrixon** [comment]
To troubleshoot your WebSocket connection issue, consider the following steps:

	1.	Check IP and Port Configuration:
	•	Ensure you are using the correct public IP and port in your WebSocket client script:

uri = "ws://your-public-ip:8765"


	2.	Verify Port Forwarding:
	•	Double-check that port 8765 is correctly forwarded to your home PC’s local IP in the router settings.
	3.	Firewall Settings:
	•	Confirm that both inbound and outbound rules for port 8765 are properly configured on your home PC’s firewall.
	4.	Test Connectivity:
	•	Use tools like telnet or nc to test the connectivity to your public IP and port from the remote device.
	5.	Server Address:
	•	Ensure the WebSocket server binds to the correct interface (e.g., “0.0.0.0” for all interfaces).
	6.	Error Handling:
	•	Modify your client script to provide more detailed debugging information.

Example client script update:

import asyncio
import websockets

async def test_connection():
    uri = "ws://your-public-ip:8765"  # Replace with your public IP address
    try:
        async with websockets.connect(uri, timeout=20) as websocket:
            await websocket.send("ping")
            response = await websocket.recv()
            print(f"Response: {response}")
    except Exception as e:
        print(f"Connection failed: {e}")
        import traceback
        print(traceback.format_exc())

asyncio.run(test_connection())

If these steps don’t resolve the issue, please provide more details about the network setup or any specific error messages encountered.

**Comment by doctorpangloss** [comment]
read more about using comfyui as an API here: https://github.com/hiddenswitch/ComfyUI?tab=readme-ov-file#using-comfyui-as-an-api--programmatically
