### ISSUE TITLE
Feature Request - Embeddings Subfolders

### ISSUE THREAD

**Issue by Merijeek** [comfyanonymous/ComfyUI#365]
From what I can see, there's no ability for the ComfyUI to find embeddings that are in subfolders. It will find any given .pt if it is in the main folder, but it isn't able to find anything in a subfolder - or, if it is, I can't seem to find the syntax to do so.

**Comment by fractal-fumbler** [comment]
so there is issue with subfolders for embeddings, i've thought i have local problems ^_^

**Comment by Merijeek** [comment]
Well, I'm going to guess so, unless someone else has better info. 

But if I've got betsyross.pt in  \embeddings\people, I can't get it to work with embeddings:betsyross or embeddings:\betsyross or embeddings:/betsyross. 

But if I move it to \embeddings I can get it to work with embeddings:betsyross

**Comment by airtonix** [comment]
what about `embedding:people/betsyross` ?

**Comment by comfyanonymous** [comment]
This was fixed when I made ComfyUI also search in subfolders for embeddings.
