### ISSUE TITLE
Comfy Server

### ISSUE THREAD

**Issue by abaybektursun** [comfyanonymous/ComfyUI#3651]
Can I run Comfy purely as a server without the UI? I just want to inference the exported API workflows. 
My hope is to reduce the boot up time and hopefully add performance to inference.

**Comment by abaybektursun** [comment]
@ltdrdata True.
Is there server only mode? If there are no custom nodes, would it speed up the bootup time?

**Comment by doctorpangloss** [comment]
read more about how to run ComfyUI as a server, use it as an embedded library, or use it as a worker against a queue here: https://github.com/hiddenswitch/ComfyUI?tab=readme-ov-file#using-comfyui-as-an-api--programmatically

**Comment by mcmonkey4eva** [comment]
Comfy works fine as a server in default mode, it doesn't waste much of any time/resources loading the UI, there's no real reason to turn that off. Note that comfy's UI uses its own API, ie it doesn't need to load anything special on the backend to handle it. (or you can use doctorpangloss's solution if you prefer that or other comfy-as-a-library options out there).
