### ISSUE TITLE
Is there a way to automate a workflow that includes ComfyUI?

### ISSUE THREAD

**Issue by 0000F8** [comfyanonymous/ComfyUI#3660]
Let's say I want another LLM to generate a prompt or some params for ComfyUI
Is there a way to interact through API or something? 

Curious about current workflows that include ComfyUI

**Comment by ltdrdata** [comment]
Using this approach would be better than using an API: https://github.com/huchenlei/ComfyUI_omost

**Comment by mcmonkey4eva** [comment]
^ Yes as data says you should seek to use nodes for those things.

If you wish to interact with Comfy as an API though, there are example scripts here: https://github.com/comfyanonymous/ComfyUI/tree/master/script_examples
