### ISSUE TITLE
FaceRestoreCF + GFPGAN 1.4 or 1.3 does not work after COMFYUI update

### ISSUE THREAD

**Issue by LSI86** [comfyanonymous/ComfyUI#3661]
Hello, 
I have updated COMFYUI and FaceRestoreCF with GFPGAN 1.4 does not make any change. With the codeformer model everything works. it is displayed:

WARNING: comfy_extras.chainner_models is deprecated and has been replaced by the spandrel library.
        Starting restore_face with codeformer_fidelity: 0.5
        Failed inference for CodeFormer: ImageModelDescriptor.__call__() got an unexpected keyword argument 'w'
        Failed inference for CodeFormer: ImageModelDescriptor.__call__() got an unexpected keyword argument 'w'
        Failed inference for CodeFormer: ImageModelDescriptor.__call__() got an unexpected keyword argument 'w'

**Comment by shawnington** [comment]
Have you updated your extensions? Comfy migrated to Spandrel.

**Comment by jkla139** [comment]
And in addition, if remove the 'w' argment, faces will become gray.
![image](https://github.com/comfyanonymous/ComfyUI/assets/44624598/70be2ec0-5b5a-46f3-9acb-f0dca03b5b6b)

**Comment by jkla139** [comment]
And in addition, if remove the 'w' argment, faces will become gray.
![image](https://github.com/comfyanonymous/ComfyUI/assets/44624598/70be2ec0-5b5a-46f3-9acb-f0dca03b5b6b)

**Comment by devZu9** [comment]
This has been going on for a very long time. Several problems have already been created here. Latest working update ffc4b7c

**Comment by mcmonkey4eva** [comment]
That's this node pack https://github.com/mav-rik/facerestore_cf ? You would need to post an issue there asking them to update, or open a fork to fix it.
