### ISSUE TITLE
ERROR : module 'keras.backend' has no attribute 'is_tensor'

### ISSUE THREAD

**Issue by makeoo1** [comfyanonymous/ComfyUI#3664]
I tried to install a custom node and after running the -r requirements of that node ( which now i have deleted ) i am now getting some errors when running comfyui. 
node link: https://github.com/AIGODLIKE/ComfyUI-ToonCrafter/blob/main/ToonCrafter/requirements.txt

At first comfyui wasn't opening at all due to "unclear error" or something similar reported in console. 
I had to **reinstall the requirements** but then i was getting the CUDA error so i used **pip uninstall torch**  and then reinstall by now I am getting this errors and some custom nodes are not loading. 
I have tried to pip install tensor but didn't fix it.

i have attached my console log as well
here is the full list of requiremets that i installed that lead to this error:
decord==0.6.0
einops==0.3.0
imageio==2.9.0
numpy==1.24.2
omegaconf==2.1.1
opencv_python
pandas==2.0.0
Pillow==9.5.0
pytorch_lightning==1.9.3
PyYAML==6.0
setuptools==65.6.3
torch==2.0.0
torchvision
tqdm==4.65.0
transformers==4.25.1
moviepy
av
xformers
gradio
timm
scikit-learn 
open_clip_torch==2.22.0
kornia

![image](https://github.com/comfyanonymous/ComfyUI/assets/113861865/4e26aa99-a89b-448e-bebf-1e08961ef52c)
![image](https://github.com/comfyanonymous/ComfyUI/assets/113861865/43fee680-c6c8-480c-8652-b799f2dc3a0d)
![image](https://github.com/comfyanonymous/ComfyUI/assets/113861865/3120f5b1-b6b6-48dc-b4df-50aa8dd11bc6)
![image](https://github.com/comfyanonymous/ComfyUI/assets/113861865/86f9a925-0c82-4915-97b6-3349208705ed)

[log.txt](https://github.com/user-attachments/files/15612363/log.txt)

**Comment by AngryLoki** [comment]
@makeoo1 , someone needs to specify `einops>=0.7.0` in requirements.txt. Ideally both ComfyUI and [ComfyUI-ToonCrafter](https://github.com/AIGODLIKE/ComfyUI-ToonCrafter/blob/main/ToonCrafter/requirements.txt).

Reference: https://github.com/PKU-YuanGroup/Open-Sora-Plan/pull/105/files

**Comment by makeoo1** [comment]
@AngryLoki thx dude! right now i got the 0.8 version installed and as i was saying the "keras.backend" error is fixed.

the problem now is that i can't get those custom nodes to work even tho i have run the -r rquirements of each all of them individually and all the requiremets results as satisfied 
![image](https://github.com/comfyanonymous/ComfyUI/assets/113861865/8cd55dd9-15d8-4341-b811-5ce329911362)

**Comment by mcmonkey4eva** [comment]
Made a meta-issue for requirements.txt versioning #3679
