### ISSUE TITLE
Error when extracting comfyui setup (portable version)

### ISSUE THREAD

**Issue by lilblue22** [comfyanonymous/ComfyUI#3668]
![Screenshot 2024-06-07 083435](https://github.com/comfyanonymous/ComfyUI/assets/5098987/1c803061-4983-48eb-bacf-cfbf322fa9cf)

I have nothing to add as I have no idea why this doesn't work?

**Comment by AngryLoki** [comment]
Explained here: https://github.com/comfyanonymous/ComfyUI/issues/3274
