### ISSUE TITLE
comments not working in PromptText

### ISSUE THREAD

**Issue by manuiageek** [comfyanonymous/ComfyUI#3669]
Hello, 
I just updated my comfyui and find out that the comments "//" are not working anymore. The workflow doesn't care about them and execute everyline of prompts (even the ones "commented").
I looked on the other issues related to that, I tried to add the "dynamicPrompts": True inside the class CR_PromptText in nodes_core.py. Still no chance after the reboot. 
I understand that the behaviour of that node has changed lately but it's not very friendly to have that "feature" changed  this way. I mean it should be normal to have "//" as a comment ... why it's not the default behaviour anymore ?
Anyway, anyone has an idea of how to make the "past-behaviour" work again in normal CR TextPrompt ?

**Comment by manuiageek** [comment]
If people are having the same issue, I found a way to make the "//" comments working.
I used the "DynamicPrompts Text Box" node that I connect to the inputtext of a prompt of a clip text encode.

**Comment by mcmonkey4eva** [comment]
This sounds related to a custom node pack you're using rather than to Comfy itself

**Comment by manuiageek** [comment]
> This sounds related to a custom node pack you're using rather than to Comfy itself
You might have right!
I reinstalled everything, now it works as expected. This time I use the : ComfyUI_windows_portable_nightly_pytorch
It works like a charm :)
