### ISSUE TITLE
uncancelable stuck queue

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#3670]
Every once in a while something like a VAE Decode gets stuck and utilises my whole GPU while infinitely running.

I have a whole queue I basically seem to have no way of saving + canceling does not work.

At previous tries ctrl + shift + windows + B worked to reset the GPU and create an error to keep it running. but right now this method is failing.

**Comment by BrechtCorbeel** [comment]
for the saving haven't tried yet bu this might do the trick:

https://github.com/atmaranto/ComfyUI-SaveAsScript

**Comment by brayevalerien** [comment]
I have already struggled with the same issue in the past, with no log in the terminal.

**Comment by SJ-Y054** [comment]
I have the same issue too. Did you solve the issue?

**Comment by BrechtCorbeel** [comment]
> I have the same issue too. Did you solve the issue?

Haven't had this in a while, but I now run multiple server on linux much better and much faster.
