### ISSUE TITLE
Where the inference actually happens

### ISSUE THREAD

**Issue by miaoqiz** [comfyanonymous/ComfyUI#3673]
Hi, 

Thanks very much for this fantastic framework and code base!

This is not an issue but more like a question - 

I am studying the code base and try to understand where the inference actually happens.

I saw the functions that "image_upload", "get_queue" and other things in the class of "PromptServer". 

Each node class defined in the "nodes.py" has a function that does the inference.

However, on the server side, when a request is processed, when is the actual inference carried out?

Thanks very much and have a good day!

**Comment by ltdrdata** [comment]
You can start tracking from here:
https://github.com/comfyanonymous/ComfyUI/blob/56333d48508f95bdef23870cad3239ba0ebdb8a9/nodes.py#L1301

https://github.com/comfyanonymous/ComfyUI/blob/56333d48508f95bdef23870cad3239ba0ebdb8a9/comfy/sample.py#L34

https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/samplers.py
