### ISSUE TITLE
COSXL broken after new update

### ISSUE THREAD

**Issue by amir84ferdos** [comfyanonymous/ComfyUI#3681]
Hello friends, 
COSXL broken after the new update, would you please check it?

**Comment by mcmonkey4eva** [comment]
Do you mean CosXL itself, or CosXL-Edit?

**Comment by mcmonkey4eva** [comment]
At a quick test both CosXL regular and CosXL-Edit work fine on the latest ComfyUI update.

Would need more details about what issue you're experiencing to address it

**Comment by mcmonkey4eva** [comment]
comfy was able to replicate a bug with the Edit model and fixed it: https://github.com/comfyanonymous/ComfyUI/commit/a82fae2375744a73d63268bc4e167649e3f026e0

**Comment by amir84ferdos** [comment]
Thank you for your response. I am now going to update my ComfyUI.
