### ISSUE TITLE
After updating the latest version, a BUG will appear in the prompt queue.

### ISSUE THREAD

**Issue by LAOGOU-666** [comfyanonymous/ComfyUI#3686]
I spent two nights reinstalling the nodes and dependencies, and finally found out that it was a version update problem, which caused a bug in the queue. Under the condition that it is automatically executed when the status changes, dragging the mouse or other operations will also be executed.

**Comment by davidchenhs** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/164337292/d44e58ff-1614-4e5f-981b-0a1647aed864)
This is after I reinstalled the old version of the UI. No matter what I did, its queue number would not change, while the new version would be forced to do so due to various factors, causing the queue to keep increasing.
![image](https://github.com/comfyanonymous/ComfyUI/assets/164337292/21d8de5a-ecf8-483b-b7c9-e71427e7a333)
This is what I get after updating the version

**Comment by ltdrdata** [comment]
see the browser log

**Comment by davidchenhs** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/164337292/2f172931-1f42-4fad-8189-25af4458da5b)
Is it this one?

**Comment by ltdrdata** [comment]
> ![image](https://private-user-images.githubusercontent.com/164337292/338662791-2f172931-1f42-4fad-8189-25af4458da5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjI1MjYsIm5iZiI6MTcxODEyMjIyNiwicGF0aCI6Ii8xNjQzMzcyOTIvMzM4NjYyNzkxLTJmMTcyOTMxLTFmNDItNGZhZC04MTg5LTI1YWY0NDU4ZGE1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxNjEwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODM1ZmM1ZGE5NjI3OWRjYzJlMmQ5YzFjZjJjZGNkMTg5NzdmMDMxYzU4ZDFjNWE5YzA0ZTgwZTRiM2NmZmFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3T24t_lLc-e7r45BNR9cRDN505P9YHWtARWscKcWFjU) Is it this one?

what about console?

**Comment by davidchenhs** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/164337292/348f007f-5d88-4d60-b450-edac90e9e54e)
This is an updated version. It seems that the problem occurs in the security scan. This problem seems to have occurred since this thing was introduced.

**Comment by ltdrdata** [comment]
> ![image](https://private-user-images.githubusercontent.com/164337292/338664805-348f007f-5d88-4d60-b450-edac90e9e54e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjI4NDMsIm5iZiI6MTcxODEyMjU0MywicGF0aCI6Ii8xNjQzMzcyOTIvMzM4NjY0ODA1LTM0OGYwMDdmLTVkODgtNGQ2MC1iNDUwLWVkYWM5MGU5ZTU0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxNjE1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTQwNjM3NWIxODM5MjNmNDdmMzI3NDRkYzQzNTAyMGJlNjFlZjg1YmMyN2U4MjUxYzg5OGYxYTg1NDhlYTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7Je2X15ZqveEEkF0tZXmnKQIRFr9v1kZtKYDxioKBOQ) This is an updated version. It seems that the problem occurs in the security scan. This problem seems to have occurred since this thing was introduced.

Security scan is irrelevant. It cannot affect to anything after launch.
Disable rgthree and try again.

**Comment by davidchenhs** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/164337292/1474b710-046b-4b9e-ae81-49a97d4ee5b9)
It has nothing to do with rgthree

**Comment by ltdrdata** [comment]
> Author

That message doesn't meaning anything. Just prompt is passed. That's all. It doesn't mean execute again.
Just the weired part is the queue items in browser.

**Comment by davidchenhs** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/164337292/268e0f8a-2dfc-4542-82a7-95c0c955b828)

**Comment by davidchenhs** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/164337292/dc02dfa7-6575-4589-b75d-4dfef674444c)
I finally found the update date that caused the problem. The ones that were checked indicated that this problem occurred after updating to this version. The ones that were not checked meant that there was no problem.

**Comment by shawnington** [comment]
I have no idea how commit f374ea7 would cause this issue, unless it somehow introduced a namespace conflict that causes unexpected behavior downstream. 
What browser is being used?

**Comment by rgthree** [comment]
I've looked into this since @davidchenhs originally filed a bug in rgthree-comfy. Looking into it, they're correct that f374ea7 introduces unintended behavior that causes auto-queue to fire while just dragging the canvas (whereas before that, it did not).

This is due to f374ea7 changing the returned workflow that's returned from `LGraph.prototype.serialize` in the `workflow.extra` field.

However, in `extensions/core/undoRedo.js` there's a `checkState` function that checks the return value every time `LGraph.prototype.serialize` is invoked to see if it's changed so it can add to the undo stack and, if it has, then fires a `graphChanged` event. This event is also listened to in `web/scripts/ui.js` and queues a prompt when enabled (and the queue size is 0).

If this was not intended, then either that `checkState` function should not consider the new fields as data to add to the undo stack, OR, there should be a better event fired only when the _actual workflow_ being sent to the server is changed (instead of just positioning).

(Note, even before f374ea7 autoqueue would fire when moving a node and, arguable, that's not necessary).

**Comment by davidchenhs** [comment]
Under complex workflow conditions, if I add a prompt queue, the queue will be repeated many times. Not only the log will be repeated, but the loading of the nodes inside will also be repeated. For example, if I use a node that plays sound, when After I add the prompt queue, it will keep making sounds

**Comment by davidchenhs** [comment]
> 我不知道提交[f374ea7](https://github.com/comfyanonymous/ComfyUI/commit/f374ea714d8c32c2f214e818146b06754c963028)会如何导致此问题，除非它以某种方式引入了命名空间冲突，从而导致下游出现意外行为。 正在使用哪种浏览器？

Chrome

**Comment by davidchenhs** [comment]
I tested it again today and found that there is still a problem with 0fecfd2, but it will be fine if I switch to the previous version.

![image](https://github.com/comfyanonymous/ComfyUI/assets/164337292/6c058e96-3ed4-4222-887a-b4440c0ec032)

There's nothing wrong with being selected

**Comment by davidchenhs** [comment]
> ![image](https://private-user-images.githubusercontent.com/164337292/338670515-dc02dfa7-6575-4589-b75d-4dfef674444c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzAzMTksIm5iZiI6MTcxODE3MDAxOSwicGF0aCI6Ii8xNjQzMzcyOTIvMzM4NjcwNTE1LWRjMDJkZmE3LTY1NzUtNDU4OS1iNzVkLTRkZmVmNjc0NDQ0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwNTI2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTdjYTAxZjAyYTMxYzEzMTI0NWUyN2Y3ODZlNmI5N2IwNWI1M2MwMjNjODljYzdiYjliMjRjMzMyZGUzYjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6uYrf7t_aPEC8CMda4N1tAayuGuCzQLqT-5NzmZ1Twg) I finally found the update date that caused the problem. The ones that were checked indicated that this problem occurred after updating to this version. The ones that were not checked meant that there was no problem.


I found that switching versions can improve the automatic execution of the drag and drop interface, but if there is rgthree's image compare node, there will be a situation where the parameters are adjusted once and then the queue is loaded all the time. I finally changed back to the 0fecfd2 version and disabled rgthree's image compare node. The method perfectly solved the problem. @rgthree @shawnington @ltdrdata
