### ISSUE TITLE
[Feature Request] Implement Rectified Flow inference for SD3

### ISSUE THREAD

**Issue by SLAPaper** [comfyanonymous/ComfyUI#3694]
According to SD3 research paper:

SD3 employs a Rectified Flow (RF) formulation, based on a number of research papers

(Arxiv Links: [1](https://arxiv.org/abs/2209.03003), [2](https://arxiv.org/abs/2209.15571), [3](https://arxiv.org/abs/2210.02747))

which “…results in straighter inference paths, which then allow sampling with fewer steps.”

[Per [SD3 Research Paper announcement](https://stability.ai/news/stable-diffusion-3-research-paper)]

**Comment by comfyanonymous** [comment]
That is implemented.
