### ISSUE TITLE
SD3 Image resolution problem

### ISSUE THREAD

**Issue by LordAlex2015** [comfyanonymous/ComfyUI#3697]
I don't if the model is not suited for that resolution or something, but when i use the default workflow (with the default prompts) and with Stable Diffusion 3 (This model: [sd3_medium_incl_clips_t5xxlfp8.safetensors](https://huggingface.co/stabilityai/stable-diffusion-3-medium/tree/main)) 
But with the resolution 1920x1080 (Full HD) it pixelates the sides:
![ComfyUI_00205_](https://github.com/comfyanonymous/ComfyUI/assets/50046996/6bc16594-5853-44a0-a604-2a71afb0d50c)

But if I do in 1024x1024, everything is back to normal:

![ComfyUI_00206_](https://github.com/comfyanonymous/ComfyUI/assets/50046996/a9088394-ec7d-4331-83d0-9899c2f274a9)

Maybe it's not an issue with ComfyUI but the model itself...(Just thinking "out-loud", I'm not an expert in AI)

**Comment by gtx155** [comment]
The model was made to work with resolutions around 1MP aka 1024x1024, anything far off this resolution is a gamble if it would work or not

**Comment by LordAlex2015** [comment]
Ok, but it still worked pretty well on sdxl and on sd 1.5
Pretty sad it doesn't work anymore, I made a lot of wallpaper with sdxl, now i can't use sd3 to make them even more stunning
