### ISSUE TITLE
error: Your local changes to the following files would be overwritten by merge:

### ISSUE THREAD

**Issue by jyju972** [comfyanonymous/ComfyUI#3700]
![Capture d’écran 2024-06-12 164205](https://github.com/comfyanonymous/ComfyUI/assets/169610368/30a9f543-4e62-403f-bdc8-f95d089215da)
![Capture d’écran 2024-06-12 165401](https://github.com/comfyanonymous/ComfyUI/assets/169610368/3ba23684-166a-4619-a94e-db713f52158f)

**Comment by Svring** [comment]
try this snippet, you could insert a new code cell to execute it after you've mounted your google drive.
!cd /content/drive/MyDrive/ComfyUI  #change this to your own folder path
!git restore .ci/update_windows/update.py
!git restore .ci/update_windows/update_comfyui.bat
!git restore .ci/update_windows/update_comfyui_and_python_dependencies.bat
!git restore .ci/update_windows_cu118/update_comfyui_and_python_dependencies.bat
!git pull

**Comment by ltdrdata** [comment]
The reason is that Google Drive removes the execution permissions of files, which causes them to be considered as modified. You need to manually reset the permissions to their original settings or ignored from git as mentioned above.
