### ISSUE TITLE
loading fbgemm error.  fbgemm.dll or one of its dependencies.

### ISSUE THREAD

**Issue by heiheiheibj** [comfyanonymous/ComfyUI#3703]
K:\ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch\ComfyUI_windows_portable_nightly_pytorch>.\python_embeded\python.exe -s ComfyUI\main.py --cpu --windows-standalone-build
Traceback (most recent call last):
  File "K:\ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\main.py", line 73, in <module>
    import comfy.utils
  File "K:\ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\comfy\utils.py", line 1, in <module>
    import torch
  File "K:\ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found.。 Error loading "K:\ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

OS: WIN10

I have installed VC_redist.x64
How should I solve this problem.

thanks

**Comment by SergeySypalo** [comment]
Experiencing the same issue
1) Run ComfyUI\update\update_comfyui_and_python_dependencies.bat
2) Got Pytorch and other stuff updated
Now can't start the ComfyUI due to the missing fbgemm.dll
Win 11, Python 3.11.9, but guess portable version of CmfyUI uses 3.11.8

**Comment by babacar1979** [comment]
Same problem here

**Comment by pavelvanecekcz** [comment]
Exactly same problem.

**Comment by comfyanonymous** [comment]
Should be fixed if you update the standalone.

**Comment by SergeySypalo** [comment]
Thanks, after the update working now.

**Comment by comfyanonymous** [comment]
If anyone is getting this and isn't using the standalone the fix is to go in your: site-packages\torch\lib\ folder and copy: libiomp5md.dll to libomp140.x86_64.dll

You can also run ComfyUI once with this argument and it will automatically do the above patch to fix your pytorch install: --windows-standalone-build

**Comment by Semiotikal** [comment]
> If anyone is getting this and isn't using the standalone the fix is to go in your: site-packages\torch\lib\ folder and copy: libiomp5md.dll to libomp140.x86_64.dll
> 
> You can also run ComfyUI once with this argument and it will automatically do the above patch to fix your pytorch install: `--windows-standalone-build`

Sorry might be a dumb question but what do you mean "copy libiomp5md.dll to libomp140.x86_64dll"? 

Like make a copy of the first file and rename it to override the second file?
