### ISSUE TITLE
Import/Ksampler Issue

### ISSUE THREAD

**Issue by iiAbstract** [comfyanonymous/ComfyUI#3707]
I noticed a bug when importing images into Comfy after updating recently. When an image is imported and processed using the exact same workflow as the original it produces a very similar but slightly different image. This so far to me seems to be an issue with the Ksampler.

After rendering the first image (the slightly different one), I increased the CFG by 0.1, rendered a new image then decreased the CFG by 0.1, setting it back to the original imported value. After queuing it again it produced the correct/same image as the original without any slight differences. I also tested changing the seed instead of CFG and it was the same thing.

For some reason when I import an image every time this happens and only by changing the value slightly then rendering a new image and changing it back seems to fix this issue.

This was tested using a image from a older version of comfy and using a SDXL model. You can also try and test this using a new/recent image by rendering one then close comfy and reopen, import the image increase the seed by 1, render that image, then decrease it by one and you may notice a slight difference even though its the exact same seed and settings. Not completely sure if this is just a issue with my install or something else interfering.

**Comment by ltdrdata** [comment]
I'm not sure how significant the difference in the images you're talking about is.

Due to the nature of PyTorch, there is always a slight variation regardless of the version. Generally, it's so subtle that it's hard to notice, but numerically, it has always been there.

Even that difference can be observed at the latent level when simply encoding the same image with VAE, as it always varies.

**Comment by iiAbstract** [comment]
Thanks for clarifying I just noticed for some reason the difference seemed to become unnoticeable or go away when I tested it this way and it was just a slight but noticeable variation in the image when importing. This was with a default workflow and no custom nodes active.
