### ISSUE TITLE
How to show each image AS it is generated, not all at the end?

### ISSUE THREAD

**Issue by TheBitcoinBaron** [comfyanonymous/ComfyUI#3711]
Basically title, in a1111 you could just up the batch amount and ask it to display after each image is generated (effectively making a slideshow). How to do this in this program?

**Comment by ltdrdata** [comment]
The term "batch" is used in two different contexts: one refers to a batch of tensors, and the other refers to a batch execution. What you mentioned is the latter.

![image](https://github.com/comfyanonymous/ComfyUI/assets/128333288/c5d68cb9-6f93-458f-8a61-0913d3461304)
