### ISSUE TITLE
Required input is missing: upscale_model_name

### ISSUE THREAD

**Issue by sassansa** [comfyanonymous/ComfyUI#3713]
hi, i have a problem when clicked queue prompt, i got this error, hope to help me about this error
regards
![Screenshot 2024-06-13 163739](https://github.com/comfyanonymous/ComfyUI/assets/124548612/06060b65-2a06-4bef-9daf-18efdafea006)

**Comment by ltdrdata** [comment]
You need to refresh and browser and recreate pipeKSampler node.

**Comment by sassansa** [comment]
> You need to refresh and browser and recreate pipeKSampler node.

i do that but i got this error again! i find out legacy V1 works fine but V2 give this error!
![Screenshot 2024-06-14 060347](https://github.com/comfyanonymous/ComfyUI/assets/124548612/1ad3124b-0b01-4207-8bce-9b4adc2fbb52)

**Comment by ltdrdata** [comment]
> > You need to refresh and browser and recreate pipeKSampler node.
> 
> i do that but i got this error again! i find out legacy V1 works fine but V2 give this error!
> ![Screenshot 2024-06-14 060347](https://github.com/comfyanonymous/ComfyUI/assets/124548612/1ad3124b-0b01-4207-8bce-9b4adc2fbb52)
> 

Oh then. You'd better this issue to ttn's repo.
