### ISSUE TITLE
Documents of making Custom Nodes

### ISSUE THREAD

**Issue by SLAPaper** [comfyanonymous/ComfyUI#372]
Is there any document of making custom nodes?

I'd like to porting [tomesd](https://github.com/dbolya/tomesd) optimization to ComfyUI, which gives a nice ~30% speed boost to `1024*1024` generation.

Just like [what I do](https://github.com/SLAPaper/a1111-sd-webui-tome) for A1111 WebUI, where can find some benchmarks I did.

**Comment by comfyanonymous** [comment]
Already implemented, see the  TomePatchModel node in the _for_testing section.
