### ISSUE TITLE
Stuck for inpaiting

### ISSUE THREAD

**Issue by abumolly** [comfyanonymous/ComfyUI#3724]
Hi guys, anyone can help fix below error? my workflow was stuck when running the inpainting part. I used imac M3 and just updated transformers to 4.41.2.

Error occurred when executing VAEEncodeForInpaint:

convolution_overrideable not implemented. You are likely triggering this with tensor backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function

Thank you so much for your kind reply.

**Comment by spaetische** [comment]
Hi, I have just run into your topic and have the same issue.
Have you managed to solve this error somehow by any chance?

**Comment by jcroseLee** [comment]
how to  solve this error?
