### ISSUE TITLE
How to solve it? Can anyone help?

### ISSUE THREAD

**Issue by muskcookie** [comfyanonymous/ComfyUI#3726]
Error occurred when executing CLIPTextEncode:

'NoneType' object has no attribute 'tokenize'

File "/Users/mac/Downloads/comfyui/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/mac/Downloads/comfyui/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/mac/Downloads/comfyui/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/mac/Downloads/comfyui/ComfyUI/nodes.py", line 57, in encode
tokens = clip.tokenize(text)
^^^^^^^^^^^^^

**Comment by DrWine** [comment]
I didnt solve it, but for some context, i got this error when i tried to use Stable diffusion 3.
![image](https://github.com/comfyanonymous/ComfyUI/assets/74111418/bc3ff0c2-f831-4282-81d5-9404829f566d)

**Comment by muskcookie** [comment]
> I didn't solve it, but for some context, i got this error when i tried to use Stable diffusion 3. . ![image](https://private-user-images.githubusercontent.com/74111418/339918848-bc3ff0c2-f831-4282-81d5-9404829f566d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6 IkpXVCJ9..1hehPxu H9Xh77mZSBxnsud2g4TwksvzFcUsblM7O74w)

What problem caused this error

**Comment by liusida** [comment]
Are you trying to use the CLIP output from the `Load Checkpoint` like this:
![image](https://github.com/comfyanonymous/ComfyUI/assets/14249458/37b14501-28fb-4cbb-b922-a66d2c777766)

No, it doesn't work. SD3 has its dedicated CLIP Loader called `TripleCLIPLoader`. You do this instead:
![image](https://github.com/comfyanonymous/ComfyUI/assets/14249458/e2a7dfa6-58ad-476a-9093-0dba439cfd7b)


If you want to use my custom version of SD3 nodes, which I think is more understandable, at least I removed the unused CLIP output which caused your confusion, here is the link: 
 https://github.com/liusida/ComfyUI-SD3-nodes

![image](https://github.com/comfyanonymous/ComfyUI/assets/14249458/33af51a5-370c-4af6-8181-8f7b8851abae)

Related to #3721
