### ISSUE TITLE
[BUG][37a08a4] using fooocus occuer Error

### ISSUE THREAD

**Issue by lwbiuchsjk** [comfyanonymous/ComfyUI#3730]
When using Load Fooocus Inpaint node and choose inpaint_v26.fooocus.path，Error occurred. 
Commit with 37a08a4
![image](https://github.com/comfyanonymous/ComfyUI/assets/4362242/5fec8831-b27a-4e74-be21-a127a2fcf61c)

**Comment by mcmonkey4eva** [comment]
that'd be an issue with the relevant nodepack, not comfy itself
