### ISSUE TITLE
[Feature] Support for SD3 ControlNet

### ISSUE THREAD

**Issue by Fannovel16** [comfyanonymous/ComfyUI#3734]
Chads from InstantX (who created InstantID) has made several ControlNet for SD3-Medium, including:
* [InstantX/SD3-Controlnet-Canny](https://huggingface.co/InstantX/SD3-Controlnet-Canny)
* [InstantX/SD3-Controlnet-Pose](https://huggingface.co/InstantX/SD3-Controlnet-Pose)
* [InstantX/SD3-Controlnet-Tile](https://huggingface.co/InstantX/SD3-Controlnet-Tile)
* [InstantX/SD3-Controlnet-Inpainting](https://huggingface.co/InstantX/SD3-Controlnet-Inpainting)

Their implementation can be found at https://github.com/huggingface/diffusers/pull/8566

**Comment by kadirnar** [comment]
+1

**Comment by sanjay-uzu** [comment]
But these models are not working in comfyui

**Comment by Fannovel16** [comment]
@sanjay-uzu That is why we need an issue

**Comment by zsxkib** [comment]
"Chads from InstantX" lol @Fannovel16

**Comment by geroldmeisinger** [comment]
controlnet support merged into diffusers
https://github.com/huggingface/diffusers/pull/8566#event-13208383785

**Comment by geroldmeisinger** [comment]
state of the model seems subpar atm https://huggingface.co/InstantX/SD3-Controlnet-Canny/discussions/4
but I guess a 1.0 version will follow soon

**Comment by kijai** [comment]
> state of the model seems subpar atm https://huggingface.co/InstantX/SD3-Controlnet-Canny/discussions/4 but I guess a 1.0 version will follow soon anyone had better results yet?

Here's some of my tests, post and tile work pretty good. This is using diffusers with a wrapper node I made to test this, I added some of the standard CN features that was missing (start/end, guess_mode). Canny seems to work better with more defined input, I found using lineart preproc better. I do definitely think it's worth implementing!

![sd3_canny_lines](https://github.com/comfyanonymous/ComfyUI/assets/40791699/0b5a074f-d5b8-4d60-b01a-c89eb952b166)
![sd3_pose_02](https://github.com/comfyanonymous/ComfyUI/assets/40791699/0ea793d3-720f-454a-82d6-df4c6488db93)
![sd3_tilecn](https://github.com/comfyanonymous/ComfyUI/assets/40791699/e970691c-8d6e-40e1-aba6-8f82ae29b34f)
![sd3_pose_gorilla](https://github.com/comfyanonymous/ComfyUI/assets/40791699/a16dac2d-caca-419d-9cf5-932a623ea82b)
![sd3_pose_cn](https://github.com/comfyanonymous/ComfyUI/assets/40791699/f15180e2-17bb-455f-ab55-a1fac9d5eacf)

![sd3_pose_tile_cn_02](https://github.com/comfyanonymous/ComfyUI/assets/40791699/9a9f154d-bbf1-4b79-ad52-9370417b5002)

**Comment by al-swaiti** [comment]
its here but in diffusers mode 
https://github.com/ZHO-ZHO-ZHO/ComfyUI-SD3-Medium-CN-Diffusers
waiting for normal one

**Comment by mcmonkey4eva** [comment]
Added to Comfy yesterday https://github.com/comfyanonymous/ComfyUI/commit/264caca20e1e051f3bcbec59d7209513ea99d4ed use `ControlNetApplySD3` node

**Comment by geroldmeisinger** [comment]
@kijai can you please try it again with something non-human and non-architectural, like an animal. the controlnet seems to have an effect and working but i'm not getting any good results with the dog2.png test image of the original controlnet :/

dog2 square-cropped and upscaled to 1024x1024:
![dog2upscale](https://github.com/comfyanonymous/ComfyUI/assets/112266044/4dac5a0c-6abb-48e2-a7be-541b4ee1890f)

![dog2canny](https://github.com/comfyanonymous/ComfyUI/assets/112266044/925bf591-3ac0-47d0-9397-efe4dbe50ab5)

![dog2result](https://github.com/comfyanonymous/ComfyUI/assets/112266044/5d27a4eb-b84e-4544-9679-fb743d538148)

I trained canny controlnets on my own and this result looks to me as if a) the CN didn't yet fully converge or b) the model collapsed at some point.
