### ISSUE TITLE
Connection errors makeing installing nodes fail + The custom node DB is currently being updated

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#3736]
Today and a bit before adding new nodes is not working due to connection errors as of my knowledge it might be because I needed to change to local db as for what I am currently trying, but one of the issues besides that is the following:

When I am trying stuff to troubleshoot and solve this problem I get: "The custom node DB is currently being updated, and updates to custom nodes are being checked for. NOTE: Update only checks for extensions that have been fetched." at various points trying to do updates and other things to make sure I find a solution, but when "The custom node DB is currently being updated" appears I cannot leave that screen, nothing is happening I can't do anything while it's there, there's no way of clicking it away.

**Comment by ltdrdata** [comment]
1. This issue should be reported in https://github.com/ltdrdata/ComfyUI-Manager/issues
2. What's your environment (colab, local, ...)?

**Comment by BrechtCorbeel** [comment]
This issue was solved by temporarily setting the db to local, from the 1-day cache it kept reverting itself to in comfy manager.
