### ISSUE TITLE
Backend Read-Only/Restricted/Frozen Mode?

### ISSUE THREAD

**Issue by liusida** [comfyanonymous/ComfyUI#3740]
I was thinking about why researchers are still using the old way to showcase their work, like a Gradio-based GUI. Why don't they use ComfyUI instead to demonstrate their new models or methods? Why don't they make a set of custom nodes for their new papers directly?

I came to the conclusion that deploying ComfyUI directly as the public demo is not quite appropriate, because users can install malicious programs or simply repurpose that instance to generate other stuff.

So, I think, what if we have a restriction on the backend side, so that it will be frozen, preventing the installation of additional custom nodes and allowing only a subset of nodes to be used.

To give a concrete example, let's imagine that the authors of [B-LoRA project](https://b-lora.github.io/B-LoRA/) want to use ComfyUI to showcase their new method. They can set up a ComfyUI instance, develop one single custom node `Load B-LoRA`, and freeze the backend, so that only the nodes in the white list can be accepted in the prompt json.

By doing so, the users can click their link, open the frozen ComfyUI, and drag around multiple nodes, test different seeds to generate images. What a wonderful scene~

Would this proposal be considered?

**Comment by ltdrdata** [comment]
ComfyUI-Manager is a separate extension, and in vanilla ComfyUI, custom nodes cannot be installed arbitrarily.

**Comment by liusida** [comment]
> ComfyUI-Manager is a separate extension, and in vanilla ComfyUI, custom nodes cannot be installed arbitrarily.

hmm... a powerful extension... Maybe I can provide this restricted/frozen mode with my [ComfyUI-Login](https://github.com/liusida/ComfyUI-Login/)...

**Comment by BrechtCorbeel** [comment]
Yes I was thinking of the login too, maybe your login should be an instance that can open different comfyui instances so multiple people can create workflows and view other people's instances and have seperate work environments on the same server.
