### ISSUE TITLE
An error on KSampler

### ISSUE THREAD

**Issue by wazkee** [comfyanonymous/ComfyUI#3742]
I've installed ComfyUI yesterday. And after some black magic rituals (since i have AMD GPU on windows), it was working perfectly. Today it worked too, but i did something and... broke it?

Long story short - when i try to generate an image, ComfyUI gets stuck on KSampler (on image it's asymmetric tiled KSampler, but i have tried all types i had) and then the cmd crashes.

Here's the message cmd is giving me:
![Screenshot 2024-06-16 171409](https://github.com/comfyanonymous/ComfyUI/assets/163148639/31845c23-2860-4b81-83e9-44d6887c5af4)

And here's the workflow i currently have (ignore the notes. I like to make some funny messages to myself when i can)
![Screenshot 2024-06-16 171627](https://github.com/comfyanonymous/ComfyUI/assets/163148639/de1ab0f4-e72a-4163-a9e7-cbdc2c2559e2)

![Screenshot 2024-06-16 171642](https://github.com/comfyanonymous/ComfyUI/assets/163148639/99a3129f-c364-4f20-b7c7-294db2beb701)

My PC specs:
GPU: AMD Radeon RX 570
16 GBytes of RAM

**Comment by GraftingRayman** [comment]
Try changing the Lora, either the model or lora does not have an attribute for width from my guess

**Comment by wazkee** [comment]
I've just tried removing the lora node, but it doesn't help. I've also tried to generate an image with default workflow and cmd gives me the same message.

**Comment by edwardsdigital** [comment]
1) pony models require -2 clip skip to work - use a "CLIP Set Last Layer" node to fix that.
2) your CFG is off the charts high, set it down to 5-8 to start with, adjust slowly from there. the civitai pages for the models tend to have decent suggested settings to start with before going off on your own experiments.
3) try using 1024x1024 resolution to start and review the preferred resolutions for SDXL / SD1.5 models. Some resolutions can give weird errors in rendering or not work at all.

**Comment by ltdrdata** [comment]
As already mentioned, the Load LoRA node is loading the wrong file.
