### ISSUE TITLE
GUI gets progressively laggy over time.

### ISSUE THREAD

**Issue by TijuanaKez** [comfyanonymous/ComfyUI#3748]
Anyone know why the UI tends to slow down over time?
I seem to have to restart the browser every hour or so as it starts to lock up.
It happens in both Safari and Chrome, though chrome tends to work slightly better.
I'm accessing the web interface of another machine (Ubuntu) on my network that's running ComfyUI.

eg. just dragging the interface, or typing in a box starts out instantaneous if the browser has just been opened. 
Then half hour later there's a second or so delay before it updates, then 2 seconds etc etc until eventually it's barely useable. Sometimes a browser refresh helps, other times I need to quite the. browser entirely and release it's ram, and start the Browser again.
I can see also the browser starting to use huge amounts of ram when its in this slow state.

**Comment by ltdrdata** [comment]
I can't see your workflow, but if such issues are occurring even with a small amount of image previews, it means there is browser leak.
