### ISSUE TITLE
Unable to access port 8188

### ISSUE THREAD

**Issue by cpken** [comfyanonymous/ComfyUI#3750]
# Unable to access port 8188（无法访问 8188 端口）

启动 comfyui，其它本地电脑无法访问 8188 端口，运行 comfyui 的本地电脑访问 127.0.0.1:8188 是可以的。
Starting comfyui, other local computers cannot access port 8188. Local computers running comfyui can access port 127.0.0.1:8188.

是否需要在 comfyui 的哪里配置后外部才可以访问 8188 端口？
Do I need to configure where in comfyui to access port 8188 externally?

我使用以下代码外部是可以访问 8188 端口的：
I can access port 8188 externally using the following code:
```python
# coding: utf-8
from http.server import BaseHTTPRequestHandler, HTTPServer
PORT = 8188


class MyServer(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == '/':
            self.send_response(200)
            self.send_header('Content-type', 'text/html')
            self.end_headers()
            # 发送"Hello, World!"消息
            self.wfile.write(b"Hello, World!")
        else:
            # 如果路径不是/，则返回404错误
            self.send_error(404, 'File Not Found: %s' % self.path)


def run(server_class=HTTPServer, handler_class=MyServer, port=PORT):
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    print('Starting httpd...')
    httpd.serve_forever()


if __name__ == '__main__':
    run()

```

希望能获取到解决方式，感谢。
Hope to obtain a solution, thank you.

**Comment by cpken** [comment]
问题已解决，在运行 python main.py 需要另外添加一些参数

```python
python main.py --listen='0.0.0.0' --port=8188
```

这样子就可以解决问题了。
源码在这里可以看到

main.py
```python
try:
    loop.run_until_complete(run(server, 
                            address=args.listen, 
                            port=args.port, 
                            verbose=not args.dont_print_server, 
                            call_on_start=call_on_start))
except KeyboardInterrupt:
    logging.info("\nStopped server")
```

**Comment by KIaiser** [comment]
可以具体教下 这个怎么加吗  在运行 python main.py 需要另外添加一些参数

**Comment by Tong2026** [comment]
无法访问此网站
127.0.0.1 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
[检查代理服务器和防火墙](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED


请问这种情况如何解决呢

**Comment by Tong2026** [comment]
<img width="558" alt="Image" src="https://github.com/user-attachments/assets/04dd4040-c6bc-46c7-9ca5-a509e3cedcc6" />
