### ISSUE TITLE
Can't connect small nodes

### ISSUE THREAD

**Issue by GraftingRayman** [comfyanonymous/ComfyUI#3757]
Anyone have any idea how to fix this? Since the SD3 update, this has been happening 

The background becomes smaller and the nodes can't be connected to or from

![2024-06-17 10-01-01 00_00_02_37 Still001](https://github.com/comfyanonymous/ComfyUI/assets/156515434/4efb66c2-be68-4be7-8fbb-326b296ec5a3)
![2024-06-17 10-01-01 00_00_03_46 Still002](https://github.com/comfyanonymous/ComfyUI/assets/156515434/98303dd3-c173-4690-b953-7b675a699665)

**Comment by GraftingRayman** [comment]
Found a workaround, but this should not be happening in the first place

**Comment by ltdrdata** [comment]
How did you reproduce that issue?

**Comment by GraftingRayman** [comment]
It is constantly happening when adding a new node that has one input/output, all other nodes have the issue as well, but due to them having more than 1 input/output they can be expanded with the mouse

Manually changing the node dimensions is the workaround

When checking the dimensions, the height of these nodes is shown as 0 as in the image below

![image](https://github.com/comfyanonymous/ComfyUI/assets/156515434/cabb7b2c-e49f-45fc-b280-265a5fe77bdf)
![image](https://github.com/comfyanonymous/ComfyUI/assets/156515434/d169726b-0378-408c-8cce-ea455a93b0c8)

If you look at ksampler in the below image, the bottom is messed up, the height is wrong for the background of the node

![image](https://github.com/comfyanonymous/ComfyUI/assets/156515434/29cd6aa1-2653-493c-a940-172f2bbf12f8)

**Comment by ltdrdata** [comment]
> It is constantly happening when adding a new node that has one input/output, all other nodes have the issue as well, but due to them having more than 1 input/output they can be expanded with the mouse
> 
> Manually changing the node dimensions is the workaround
> 
> When checking the dimensions, the height of these nodes is shown as 0 as in the image below
> 
> ![image](https://private-user-images.githubusercontent.com/156515434/340284565-cabb7b2c-e49f-45fc-b280-265a5fe77bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzMyODUsIm5iZiI6MTcxODYzMjk4NSwicGF0aCI6Ii8xNTY1MTU0MzQvMzQwMjg0NTY1LWNhYmI3YjJjLWU0OWYtNDVmYy1iMjgwLTI2NWE1ZmU3N2JkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxNDAzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzQ4MzYzNjcwOTYwYjAzYWQ0ZmI1ODQwMGI1YWI5N2JkNDM1OGE1ODk3OGQ5ZjMzNDNiZThlMGVhMjc4NDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i0J4TpMk-Nt1LySCGiWu-iXSnog3iHLKba0Mcsm6N0E) ![image](https://private-user-images.githubusercontent.com/156515434/340284601-d169726b-0378-408c-8cce-ea455a93b0c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzMyODUsIm5iZiI6MTcxODYzMjk4NSwicGF0aCI6Ii8xNTY1MTU0MzQvMzQwMjg0NjAxLWQxNjk3MjZiLTAzNzgtNDA4Yy04Y2NlLWVhNDU1YTkzYjBjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxNDAzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzQ5MzQ1OTgyZDBlNTQ5OTdkYTU5OWIwZGQzY2U3NmJiNDJmMmI3MDEwN2I2MDMzMjM5ZmNjYTU2ZTY2MGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LONVG3buad6sAbTk4wtBrv_if-at0M-R2kiHyvdTk1c)
> 
> If you look at ksampler in the below image, the bottom is messed up, the height is wrong for the background of the node
> 
> ![image](https://private-user-images.githubusercontent.com/156515434/340285278-29cd6aa1-2653-493c-a940-172f2bbf12f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzMyODUsIm5iZiI6MTcxODYzMjk4NSwicGF0aCI6Ii8xNTY1MTU0MzQvMzQwMjg1Mjc4LTI5Y2Q2YWExLTI2NTMtNDkzYy1hOTQwLTE3MmYyYmJmMTJmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxNDAzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWFiZDRjMTNjOWYzMDVhMTFmZTRhYzY4NjkzNmY2YTI5ZWEyMGYxNmM2YWVkMzkwYzE3NzIyNDdhMjE5NTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hLxVCmesuWNAclSbW7DWfMOX-9VIopPvlmeTdjgIa7Y)

hmm.. I cannot reproduce that. Have you tried without any custom node?

**Comment by GraftingRayman** [comment]
Will try that, got a queue running that takes hours, will update

**Comment by GraftingRayman** [comment]
After moving all my custom nodes out and bringing them back one by one, I found the culprit

ComfyUI-Custom-Scripts

This has been causing this issue
