### ISSUE TITLE
Error window needs a scrollbar

### ISSUE THREAD

**Issue by AngryLoki** [comfyanonymous/ComfyUI#3761]
As demonstrated in https://github.com/comfyanonymous/ComfyUI/issues/3714 and https://github.com/comfyanonymous/ComfyUI/issues/3755, users don't understand that traceback is can be scrolled, because it looks like this:

<img width="819" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/108563/3cd8dfbe-a00b-4c22-a349-8b8dbab1ce98">

Proposed fix:
```
:root {
    color-scheme: dark;
}

.comfy-modal-content {
    max-width: 100%;
    /* other existing styles */
}
```

With updated CSS:
<img width="823" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/108563/9044a9e2-1165-4192-b176-337e6a65118a">

**Comment by nothingness6** [comment]
Hi, I have the same issue. 
Could you tell me where the css file is, please?

**Comment by mcmonkey4eva** [comment]
frontend issue https://github.com/Comfy-Org/ComfyUI_frontend
