### ISSUE TITLE
How to delete the image cache in the image loading?

### ISSUE THREAD

**Issue by 0002kgHg** [comfyanonymous/ComfyUI#3767]
I have loaded a lot of pictures, and for convenience, I want to delete some duplicates.
![image](https://github.com/comfyanonymous/ComfyUI/assets/90631570/c0f0c527-97e4-4480-a8fd-b2d4ba51dfed)

**Comment by jiayezi** [comment]
Just delete the images in the ComfyUI_windows_portable\ComfyUI\input directory

**Comment by hunghuynh0811** [comment]
How do I clear load image history? Hepl me, please

**Comment by ltdrdata** [comment]
> How do I clear load image history? Hepl me, please

That is not a history. You need to remove file from `ComfyUI/inputs`.

**Comment by hunghuynh0811** [comment]
Can you guide me to clear the image cache in collab, I have cleared the image in input/output, but when running WF, the image that was loaded before is still there, even though I have cleared it

**Comment by Jay021** [comment]
> > How do I clear load image history? Hepl me, please
> 
> That is not a history. You need to remove file from `ComfyUI/input`.

Thank you very much, you've been helpful to me too.

**Comment by ivanvsm123** [comment]
Como faço isso no ComfyUI Cloud? Me ajudem, por favor
