### ISSUE TITLE
I updated ComfyUI and now CheckpointLoaderSimple is nowhere to be found!!!

### ISSUE THREAD

**Issue by Torcelllo** [comfyanonymous/ComfyUI#3771]
I updated ComfyUI and now CheckpointLoaderSimple is nowhere to be found!!!

Win 10, ComfyUI version Windows Portable

**Comment by mcmonkey4eva** [comment]
Most likely the entire install has failed to load properly in some way, rather than that node specifically being lost - can you post terminal logs, browser screenshots, ...?

**Comment by Torcelllo** [comment]
Sorted - thank you!

**Comment by Torcelllo** [comment]
Sorted
