### ISSUE TITLE
could you please add a node achive convert hexadecimal color values to hue values？

### ISSUE THREAD

**Issue by hexiaoyu946** [comfyanonymous/ComfyUI#3775]
Dear developer, I want to convert hexadecimal color values to hue values, please ask if you can add a node to achieve this function, thank you very much
![屏幕截图 2024-06-19 011941](https://github.com/comfyanonymous/ComfyUI/assets/72909117/030eafa6-cd2c-4c1c-a3d4-c4573f702d4b)

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/646#event-13204761895
