### ISSUE TITLE
[Feature request] Add ability to store prompt execution history on some kind of database.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [comfyanonymous/ComfyUI#3776]
Hello everyone.

Currently ComfyUI stores all of it's prompt executions [as dictionary in memory](https://github.com/comfyanonymous/ComfyUI/blob/master/execution.py#L815) which has some downsides if we want to run it as service on remote server. All of it's history will be wiped out if we reload service, and when service is being run for too long time, and if it has significant traffic, then it will start using more memory.

I think there should be options of how prompt execution history will be stored. Memory by default and some kind of storage service (PostgreSQL, sqlite3 and etc.)

It could be even better if users can install these loggers separately and apply them in some kind of **config.py**

**Comment by ltdrdata** [comment]
This would be better written in the form of a custom node.
Using add_on_prompt_handler, you can handle the transmitted prompt in the backend.
