### ISSUE TITLE
portable version has tons of issues with installing nodes properly and they turn out red by default

### ISSUE THREAD

**Issue by 3blackbar** [comfyanonymous/ComfyUI#3777]
This is crazy, why this isnt taken care of ? I hav eto manually use python from embedded folder and reinstal requirements.txt for most git pulled shit.
Cmon this cant stay like this .

**Comment by Amorano** [comment]
Embedded is embedded. If you used something else then that "something else" installed to your system or its own self-contained environments.

This is not a comfyui problem; that is a local system python management problem.

**Comment by mcmonkey4eva** [comment]
Use https://github.com/ltdrdata/ComfyUI-Manager to install custom nodes more easily
