### ISSUE TITLE
[Feature request] implement CFG++

### ISSUE THREAD

**Issue by dfl** [comfyanonymous/ComfyUI#3778]
re: https://cfgpp-diffusion.github.io
this seems like a pretty simple thing, injecting unconditional noise instead of predicted noise.

the diffusers code is like this:
`zt = at_next.sqrt() * z0t + (1-at_next).sqrt() * noise_pred`

whereas the CFG++ version uses noise_uc instead of noise_pred:
`zt = at_next.sqrt() * z0t + (1-at_next).sqrt() * noise_uc`

then one just uses CFG scale values between 0 and 1 (lambda in the CFG++ paper)

I think it should be relatively easy to patch this with sampler_post_cfg_function?

**Comment by dfl** [comment]
my comfy installation is busted atm so I can't test it out just now, but thinking something like this:
```
import comfy.model_patcher
import comfy.samplers

class CFGpp:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "model": ("MODEL",),
            }
        }

    RETURN_TYPES = ("MODEL",)
    FUNCTION = "patch"

    CATEGORY = "_for_testing"

    def patch(self, model, scale):
        m = model.clone()

        def post_cfg_function(args):
            return args["uncond_denoised"]

        m.set_model_sampler_post_cfg_function(post_cfg_function)

        return (m,)


NODE_CLASS_MAPPINGS = {
    "CFGpp": CFGpp,
}

```

**Comment by dfl** [comment]
actually the cfg_function stuff doesn't need to be patched, but we need to modify how the output calculation is scaled by uncond_denoised (instead of cfg_function). Not sure how to do this.

**Comment by mcmonkey4eva** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/73ca7800192f6bc2e2194966b316b7cc3028e09a comfy added support yesterday
