### ISSUE TITLE
Add a node to select some image from a batch for further use

### ISSUE THREAD

**Issue by SLAPaper** [comfyanonymous/ComfyUI#378]
Since ComfyUI doesn't handle batch seed like A1111 WebUI do (discussed in #165 )
I cannot reproduce a seed unless use the same batch count when first generation
But in many scenario, there is only a few images in a batch are what I needed and valuable to do something more with (like scaling up or hires fix)
So a node that can select some of batch images and pipe out would be helpful

**Comment by SLAPaper** [comment]
I impleted the custom node on my own: github.com/SLAPaper/ComfyUI-Image-Selector

**Comment by comfyanonymous** [comment]
I implemented a node to do this: https://github.com/comfyanonymous/ComfyUI/commit/6f7852bc47de2fa432672a1b93c1727c0824d78b

You can use it before sampling (to generate a single image from a batch with the same "seed") or after sampling (to pick a generated latent from a batch).
