### ISSUE TITLE
When loading the graph, the following node types were not found: UltimateSDUpscale

### ISSUE THREAD

**Issue by majestichou** [comfyanonymous/ComfyUI#3780]
I downloaded all of stabilityai/stable-diffusion-3-medium's files from huggingface. I installed the latest version of ComfyUI as per ComfyUI's repository on centos 7. I started comfyui by executing the command, `python main.py`.
There are three workflows in the comfy_example_workflows folder of stabilityai/stable-diffusion-3-medium. I have `sd3_medium_example_workflow_basic.json` and `sd3_medium_example_workflow_multi_prompt.json` workflows loaded, and both workflows worked correctly to generate the images. But when I load the `sd3_medium_example_workflow_upscaling.json` workflow, the comfyUI window gives the following error message:
```
When loading the graph, the following node types were not found:
    UltimateSDUpscale
Nodes that have failed to load will show as red on the graph.
```

**Comment by mcmonkey4eva** [comment]
That is a custom node you have to install separately.
Comfy Manager can help with that https://github.com/ltdrdata/ComfyUI-Manager

**Comment by JuvenileLocksmith** [comment]
> That is a custom node you have to install separately. Comfy Manager can help with that https://github.com/ltdrdata/ComfyUI-Manager

It appears that it does not, despite my best efforts.
<img width="944" alt="Screenshot 2024-07-03 at 12 42 07" src="https://github.com/comfyanonymous/ComfyUI/assets/83825290/ca14c80b-ea63-426b-b8b4-037ea4968227">
<img width="731" alt="Screenshot 2024-07-03 at 12 43 16" src="https://github.com/comfyanonymous/ComfyUI/assets/83825290/00212f49-f463-4880-9892-f00448d6e94a">
<img width="832" alt="Screenshot 2024-07-03 at 12 43 27" src="https://github.com/comfyanonymous/ComfyUI/assets/83825290/8c5f093f-9537-4425-9136-31679d9019f3">

**Comment by ltdrdata** [comment]
That's an unknown custom node. You need to inquire with the workflow creator.
