### ISSUE TITLE
ComfyUI keeps downgrading to older versions on me.

### ISSUE THREAD

**Issue by LockMan007** [comfyanonymous/ComfyUI#3782]
ComfyUI keeps downgrading to older versions on me.

— 06/16/2024 12:08 AM
ComfyUI: 2255[bb1969](2024-06-15)
Manager: V2.38

 — 06/19/2024 1:19 AM
ComfyUI: 2141[d09b5e](2024-04-22)
Manager: V2.38

I don't understand what is going on. (windows install)
I made a new folder and did a new install of ComfyUI and installed everything from new files and was running everything fine for 2 days, then it is back to being downgraded again.

One of my friends, who runs this on Linux, was having issues upgrading and had to do a new install also.

**Comment by ltdrdata** [comment]
What is your full log of startup?
