### ISSUE TITLE
Extra Models Configuration with subfolders

### ISSUE THREAD

**Issue by parlt** [comfyanonymous/ComfyUI#3783]
If you want to use web ui models in Comfy Ui and for structural reasons have structured the checkpoints, VAE etc in the Web Ui models folder in subfolders, these are not recognized by Comfy Ui. It would be desirable if ComfyUI would also recognize subfolders
f.e. Extra Models Folder -> Checkpoints -> SD 1.5, SD 2.1, SD 3 Medium

**Comment by mcmonkey4eva** [comment]
Subfolders are supported fine? I have all my stuff in subfolders and it works great
