### ISSUE TITLE
I don't know why this error happened

### ISSUE THREAD

**Issue by myoni00** [comfyanonymous/ComfyUI#3794]
Error occurred when executing PreviewImage:

Numpy is not available

File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1434, in save_images
i = 255. * image.cpu().numpy()
^^^^^^^^^^^^^^^^^^^

**Comment by artegoser** [comment]
Idk why numpy==2.0.0 is installed.

Run this:
```
pip install numpy==1.26.4
```

**Comment by ltdrdata** [comment]
> Idk why numpy==2.0.0 is installed.
> 
> Run this:
> 
> ```
> pip install numpy==1.26.4
> ```

Recently, anyone installing ComfyUI will inevitably have numpy 2 installed.
Simply installing the basic requirements of ComfyUI will result in numpy 2 being installed.

**Comment by jwvanderbeck** [comment]
Having this issue as well on a new Comfy installation.  i have one instance running just fine, but I'm installing it on a second computer so I can have access to a free GPU more often and with that new install I ran into this issue.  Going to try the suggestion to roll numpy back, but numpy 2.0 was what I ended up with when I ran the install requirements.
