### ISSUE TITLE
Error 0x80070003: The system cannot find the path specified.

### ISSUE THREAD

**Issue by Xenchip** [comfyanonymous/ComfyUI#3796]
Error while extracting the compressed build. 
![bandicam 2024-06-20 16-34-08-557](https://github.com/comfyanonymous/ComfyUI/assets/108058470/4b56dd6c-52da-4f77-b066-2fc1688777d6)

**Comment by ltdrdata** [comment]
It seems that your path is too long. Don't install ComfyUI into deep path. Windows cannot handle long path well.
