### ISSUE TITLE
Numpy version

### ISSUE THREAD

**Issue by Nestorchik** [comfyanonymous/ComfyUI#3798]
ComfyUI Installed by:   comfy install  (comfy_cli)

![image](https://github.com/comfyanonymous/ComfyUI/assets/74113797/a7decfa8-b368-489f-804a-5fc0f1332d64)

Help this operation:

python -m pip uninstall numpy -y
python pip install numpy==1.26.4

**Comment by robinjhuang** [comment]
This issue should probably be moved to the comfy-cli repo. 
https://github.com/Comfy-Org/comfy-cli

**Comment by Nestorchik** [comment]
This error also on installing ComfyUI + Manager + CrysTools

**Comment by Nestorchik** [comment]
> same issue
> 
> Run this: pip install numpy==1.26.4

![image](https://github.com/comfyanonymous/ComfyUI/assets/74113797/91930acf-cfb7-4893-9343-700f368ea534)
