### ISSUE TITLE
[Bug] SD3 unconditional seems to be incorrect, model can do the infamous 'woman laying in grass' image generating the unconditional a different way

### ISSUE THREAD

**Issue by CodeExplode** [comfyanonymous/ComfyUI#3800]
The Clip Text Encode (Negative Prompt) seems to be generating the incorrect negative conditioning for the model. Using the SD3 triple text encoder node with empty padding: None to generate the unconditional seems to greatly improve things.

It would appear that it is generating an unconditional tensor of 1x1x4096 shape, rather than 1x154x4096 shape, based on some early testing.

See the workflow in these images:

![SD3_02449_](https://github.com/comfyanonymous/ComfyUI/assets/79982924/4931fd53-f454-4786-9fec-ad2a05f60ad3)

![SD3_02445_](https://github.com/comfyanonymous/ComfyUI/assets/79982924/77ca372e-e54c-430f-a63a-ab8561f8cde0)

**Comment by CodeExplode** [comment]
After some testing, generating the pure unconditional prediction gives very coherent images with zeroes in batch_size x 154 x 4096 shape, and noise with batch_size x 77 x 4096 shape as is currently implemented.

![SD3_02453_](https://github.com/comfyanonymous/ComfyUI/assets/79982924/0be31e15-89d0-4c0c-bb73-723072ee5827)

**Comment by CodeExplode** [comment]
After some testing, it looks like SD 2B's best unconditional is a single encoded T5 token (the T5 EOS token according to Kenji on Discord) which is 1x4096 in dimensions. You can use zeroes in those dimensions and it may look a little less cooked, but it seems to introduce phantom limbs. For pooled it's just 1x2048 zeroes. This seems to greatly improve results over the current implementation.

**Comment by mcmonkey4eva** [comment]
Your images are coming out cleanly because you're _not_ doing the infamous `woman lying in grass` prompt, you're doing an actual decent prompt, and the model is keeping the character upright (not sideways).

The same prompt works perfectly fine on a pure default workflow with none of the overcomplication
![image](https://github.com/comfyanonymous/ComfyUI/assets/4000772/4b4d7354-21be-4aa9-9849-cf25fe8895bf)
