### ISSUE TITLE
ReferenceError: app is not defined

### ISSUE THREAD

**Issue by zyseu** [comfyanonymous/ComfyUI#3803]
all node is missing

**Comment by zyseu** [comment]
![Uploading Snipaste_2024-06-21_11-35-25.png…]()

**Comment by zyseu** [comment]
1

**Comment by mcmonkey4eva** [comment]
This is very vague, any number of things could have gone wrong. You might just need to restart or reinstall. If not, please post screenshots of terminal logs, your browser, etc.

**Comment by zyseu** [comment]
> This is very vague, any number of things could have gone wrong. You might just need to restart or reinstall. If not, please post screenshots of terminal logs, your browser, etc.

Thanks, I had resolve the problem. I noticed the run log, it shows that my server has no access to the network

**Comment by zyseu** [comment]
My issue is caused by [comfyui-reactor-node], solution is https://github.com/Gourieff/comfyui-reactor-node/issues/216
