### ISSUE TITLE
how could i change the temp floder from comfyui to z drive?

### ISSUE THREAD

**Issue by robert10981** [comfyanonymous/ComfyUI#3808]
how could i change the temp floder from comfyui to z drive?

**Comment by AlUlkesh** [comment]
Did you try this commandline parameter?

https://github.com/comfyanonymous/ComfyUI/blob/0ec513d8774fc0b14fc3fdbb3f09745244532146/comfy/cli_args.py#L45

**Comment by robert10981** [comment]
> 您是否尝试过此命令行参数？
> 
> https://github.com/comfyanonymous/ComfyUI/blob/0ec513d8774fc0b14fc3fdbb3f09745244532146/comfy/cli_args.py#L45

may i tell you i am a idiot, and i do not know how. can you tell me what should i do,  as i am a idiot. thank you.

**Comment by AlUlkesh** [comment]
😆 
Well, if you normally start with `python main.py` you would instead use, for example `python main.py --temp-directory "z:/temp"`

**Comment by mcmonkey4eva** [comment]
If you have the comfy portable install, edit `run_nvidia_gpu.bat` to add that
If you use Swarm, edit the CLI args under Server -> Backends

**Comment by robert10981** [comment]
thank you bro its work, love you, kiss you, mua mua mua

> 😆 Well, if you normally start with `python main.py` you would instead use, for example `python main.py --temp-directory "z:/temp"`
