### ISSUE TITLE
API access from C#

### ISSUE THREAD

**Issue by teodor-krastev** [comfyanonymous/ComfyUI#3809]
Hello,
anybody with a library or even an example to access ComfyUI API from C#? 

I translated the python example and I can queue one prompt but any attempt to send a second one has failed.

I would much appreciate any advice or clue.

Thank you
Theo

**Comment by mcmonkey4eva** [comment]
Can look at Swarm's C# comfy backend code https://github.com/mcmonkeyprojects/SwarmUI/blob/master/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs

**Comment by BrechtCorbeel** [comment]
Python is written in C, I would imagine you could do anything you want without an API if you know how to build onto it, but maybe I don't know enough to know why C and C# would not be cross compatible.

**Comment by teodor-krastev** [comment]
Thank you mcmonkey4eva that helped me a lot but the problem I was having was due to sending two exact copies of workflow json. The second one was ignored for obvious reason. 
On a related matter, as experienced in ConfyUI API do you know a proper API documentation/manual/tutorial? 
Cheers
Theo

**Comment by mcmonkey4eva** [comment]
There's the official python examples here https://github.com/comfyanonymous/ComfyUI/tree/master/script_examples

In the coming weeks/months we'll probably add API docs to https://docs.comfy.org/get_started/introduction or https://github.com/comfyanonymous/ComfyUI/wiki
