### ISSUE TITLE
Certain Stable Cascade UNETs cannot load using UNetLoader

### ISSUE THREAD

**Issue by narukaze132** [comfyanonymous/ComfyUI#3813]
I've been using a model called SoteDiffusion lately, which is a Stable Cascade model. (Technically it's Wuerstchen3, but it loads into ComfyUI with Stable Cascade.) It has a ComfyUI checkpoint for both the main model (Stage C) and the decoder (Stage B). Unfortunately, my computer is somewhat RAM-constrained (only 16GB), and loading in both of those models is pushing its limits. In order to save a little bit of space, I tried loading the UNet and VAE of the decoder (downloaded from HuggingFace) separately instead of using the decoder checkpoint (so I wouldn't have to load in the unused CLIP model).

That's where I ran into a problem: ComfyUI's UNetLoader wouldn't load the decoder UNet. After some digging, I figured out that it couldn't detect the model type correctly: SoteDiffusion's decoder UNet doesn't have the `clip_mapper.weight` key that both of the standard Stable Cascade decoder UNets (stage_b and stage_b_lite) have, which is what `comfy.model_detection.detect_unet_config` uses to distinguish them from Stage C UNets. (It does have the `clf.1.weight` key used to distinguish Stable Cascade UNets in general.) As such, the model can't load correctly.

I'd try to patch this myself, but I'm unfortunately unfamiliar with the architecture and what other keys could be used to distinguish Stage B from Stage C.

**Comment by comfyanonymous** [comment]
They are probably in diffusers format which are not supported for stable cascade.

**Comment by narukaze132** [comment]
> They are probably in diffusers format which are not supported for stable cascade.

They are, but when I did a complete hackjob to work around it (which involved literally checking for which file it was loading), the image still generated, though it wasn't as good as the ComfyUI checkpoint's version. I ended up just making a custom node to save UNets, like the nodes for saving CLIPs and VAEs, to save that one separately.

I'm just gonna close the issue since I "solved" it for myself, but feel free to reopen it if you actually think this needs work.
