### ISSUE TITLE
Why my INT input created as a slider value instead of a pad that can be connected?

### ISSUE THREAD

**Issue by longtermgoals** [comfyanonymous/ComfyUI#3814]
Hi everyone, 

First of all, thanks for this amazing project and let me show my gratitude of sharing with the rest of us. 

Lately I have been trying to implement some custom nodes for some customized effect and I need to take two INT input value from upper stream to make it work, so I'm looking for something like this:

![1718988922359](https://github.com/comfyanonymous/ComfyUI/assets/50180943/a0544b0e-8072-4471-a404-e5ba552c11f9)

So below are my sample implementation for the custom node, and also I have deployed under "custom_nodes" folder and ComfyUI loaded it fine.

     class TestNode:

        def __init__(self):
            pass

        @classmethod
        def INPUT_TYPES(cls):
            return {
                "required": {
                    "original_image": ("IMAGE", ),
                    "image_gen_width": ("INT", {"default": 512, "min": 64, "max": 1000, "step": 8}),
                    "image_gen_height": ("INT", {"default": 512, "min": 64, "max": 1000, "step": 8}),
                    "resize_mode": ([1, 2, 4], {"default": 1})
                }
            }

        RETURN_TYPES = ("FLOAT", )
        RETURN_NAMES = ("result", )

        FUNCTION = "TestNode"

        # OUTPUT_NODE = False

        CATEGORY = "TestTools"

        def TestNode(self, original_image, image_gen_width, image_gen_height, resize_mode):
            return  (float(image_gen_height),)

        # @classmethod
        # def IS_CHANGED(cls, image, string_field, int_field, float_field, print_to_screen):
        #    return ""

     NODE_CLASS_MAPPINGS = {
        "TestNode": TestNode
     }

     NODE_DISPLAY_NAME_MAPPINGS = {
        "TestNode": "Test Node"
     }

`

and below is what I got:

![1718989134401](https://github.com/comfyanonymous/ComfyUI/assets/50180943/47fbaf6f-ad59-4586-8b4d-6c55411e42be)

So you can see that in my node, image_gen_width and image_gen_height are two sliders input but not two INPUT pad as shown in PixelPerfectResolution node, which is very very much weird for me, since I basically copied all the code from PixelPerfectResolution implementation.

I'm using python 3.9 for deployment and development if that matters.

I think it must be some kind of silly problem I made, but I can't figure this out. Please help me out on this. Really appreciate all the help!

**Comment by ltdrdata** [comment]
add `"defaultInput": True` 
By default, the INT type is represented as a widget.

**Comment by longtermgoals** [comment]
> add `"defaultInput": True` By default, the INT type is represented as a widget.

Cool, thanks! It works like a charm~
