### ISSUE TITLE
comfy.org Issue: James Kwon's GitHub URL is incorrect.

### ISSUE THREAD

**Issue by VMaston** [comfyanonymous/ComfyUI#3815]
I'm posting this issue here for lack of a better place, as I can't find if the [comfy.org](https://www.comfy.org/) website has a public repo to post issues on.

The comfy.org website currently links hongil0316/James Kwon's GitHub icon to a user that doesn't exist.

`https://github.com/hongil0316` needs to be replaced with the correct URL: https://github.com/james03160927

**Comment by robinjhuang** [comment]
Thanks for letting us know! Fixed here: 
https://github.com/Comfy-Org/homepage/commit/64d05a20d2d9fb8ef03928f69c2e4e23ea39969d
The landing page repo is public now.
