### ISSUE TITLE
Nodes Recalculating and Models Reloading Unexpectedly

### ISSUE THREAD

**Issue by torealise** [comfyanonymous/ComfyUI#3833]
Nodes in ComfyUI are recalculating and models are reloading unexpectedly, even when inputs haven't changed. This happens inconsistently and isn't related to VRAM usage, idle time, or external usage.

Steps to Reproduce:

1. Run the workflow successfully.
2. Let the system idle for a while (issue occurs regardless of idle duration).
3. Re-run the workflow without changing inputs.

Expected Behavior:
ComfyUI should use cached values and not reload models if inputs haven't changed.

Actual Behavior:
Nodes recalculate and models reload, starting from the beginning.

Sometimes it happens every 5 minutes, sometimes not happening for hours. 

Environment:

ComfyUI version: Noticed it few months ago
OS: Linux (Runpod)
VRAM: A40 (48GB)

**Comment by robinjhuang** [comment]
@torealise Can you share which workflow / custom nodes you are using? ComfyUI already caches node outputs unless the inputs have changed. Some custom nodes can override this by saying the node has always changed.

**Comment by ltdrdata** [comment]
Is it correct that you are not running other tabs or other workflows concurrently?
