### ISSUE TITLE
What is the function of the Clipspace button?

### ISSUE THREAD

**Issue by 748226917** [comfyanonymous/ComfyUI#3837]
I clicked it and it said Clipspace is empty.

**Comment by ltdrdata** [comment]
In the image node, if you select "Copy (clipspace)," you will see the following:
It is a space where you can manipulate the data contained in the clipspace.

![image](https://github.com/comfyanonymous/ComfyUI/assets/128333288/a9fb44a5-7ea2-41fe-8c56-2ccf0766fe44)

Clipspace is designed to contain data other than images, but currently, the extended features provided by clipspace are only related to images.

**Comment by 748226917** [comment]
I got it,thankyou.
