### ISSUE TITLE
Question: how to repurpose UI with ChatGPT/Claude?

### ISSUE THREAD

**Issue by ldmtwo** [comfyanonymous/ComfyUI#3846]
Hi,
I'm really interested to develop my own tools inside this UI. I would want to combine many modes: video/image, audio, and text/document. I can make operators with Python, but how to connect my classes into the UI?

**Comment by injet-zhou** [comment]
Are you asking about creating a custom node? If so, you can find the documentation here: https://github.com/chrisgoringe/Comfy-Custom-Node-How-To/wiki/aaa_index
