### ISSUE TITLE
Support swapping the I/O connection placement/direction

### ISSUE THREAD

**Issue by rhdunn** [comfyanonymous/ComfyUI#3855]
## Use Case
When generating an image it can be useful to show the image next to the input parameters of the workflow. This requires sending the data right-to-left (backwards).

This is currently doable but the pipeline connections are not optimally positioned.

Having nodes (specifically the Reroute node, but also and N I/O channel variants from #3851 and the various pipe extension nodes) that can swap the side the inputs and outputs are located would make these workflow graphs cleaner.

Maybe have an arrow in the middle of the inputs/outputs to show the direction, e.g.:

```
  | o model      model o |
  | o clip   <=   clip o |
  | o vae          vae o |
```

**Comment by rhdunn** [comment]
For example, this is a workflow of mine where it will be helpful (see the top output line):

![workflow-with-reversing-nodes](https://github.com/comfyanonymous/ComfyUI/assets/47298/2ec4e2a4-1d4f-4da6-9c0a-632280740246)

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend

The issue of input/output confusion should be handled with care.
