### ISSUE TITLE
Include the EulerCFG++ sampler in the list in KSampler nodes.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [comfyanonymous/ComfyUI#3859]
The new EulerCFG++ sampler is proving to be very popular, but it isn't included in the sampler list for KSampler nodes. The only way to use it at the moment is to use a custom node setup, but this has some limitations. For example; I want to define steps in the KSampler(Advanced) node and use the EulerCFG++ sampler with it.

**Comment by comfyanonymous** [comment]
Which one do you think looks better? "regular" or "alternative"?

**Comment by GalaxyTimeMachine** [comment]
Alternative seems to be the one everyone is using.

**Comment by GalaxyTimeMachine** [comment]
Clownshark added it through his repo by adding this block:

```from comfy_extras.nodes_advanced_samplers import sample_euler_cfgpp_alt
extra_samplers = {
    "res_momentumized_advanced": sample_res_solver_advanced,
    "dpmpp_dualsde_momentumized_advanced": sample_dpmpp_dualsdemomentum_advanced,
    "dpmpp_sde_advanced": sample_dpmpp_sde_advanced,
    "eulercfgpp_alt": sample_euler_cfgpp_alt
}

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/69d710e40f43b87dd7124b9ee1e8982f987827e9
