### ISSUE TITLE
Possible issue with some (?) extra model paths

### ISSUE THREAD

**Issue by netdzynr** [comfyanonymous/ComfyUI#3862]
Mac M1, Ventura OS 13.6.7
ComfyUI: 2284[69d710](2024-06-25)
Manager: V2.42

Extra model paths assigned to **facedetection** and **facerestore_model** paths seem to be ignored.

Custom paths are reflected in Terminal, models exist on external drive. But when a workflow is run that relies on face detection/face restore, FaceRestoreModelLoader node shows "null" under models, and FaceRestoreCFWithModel node auto-downloads required models.

Currently using symlinks as a workaround.

Checkpoint/Lora paths are not affected.

![image](https://github.com/comfyanonymous/ComfyUI/assets/4701640/cc29e9ae-1af2-4881-8dcd-a03b67736d26)

**Comment by mcmonkey4eva** [comment]
These nodes aren't part of ComfyUI Core, they come from a custom node extension you downloaded - you should report the issue on the github for whichever custom node provided those

**Comment by jiyeong08** [comment]
Did you solve this problem?
