### ISSUE TITLE
Prompt node text area rendered incorrectly when overlapped

### ISSUE THREAD

**Issue by huchenlei** [comfyanonymous/ComfyUI#3866]
![image_720](https://github.com/comfyanonymous/ComfyUI/assets/20929282/b6447f9d-2894-4782-b1ff-bd3323901930)

Test report:
https://github.com/comfyanonymous/ComfyUI/actions/runs/9671779755

Reproduction:
- Load default workflow
- Drag one CLIP node over another
- Click somewhere else to unfocus the dragged node

![image](https://github.com/comfyanonymous/ComfyUI/assets/20929282/68577e60-9021-4fa2-80d1-4bcc7d301970)

**Comment by BrechtCorbeel** [comment]
Noticed similar, like when you enter an integer a note node will overlap over it making the input for the value that pops up disappear behind it.
