### ISSUE TITLE
[Frontend] Unable to remove workflow in Beta UI

### ISSUE THREAD

**Issue by huchenlei** [comfyanonymous/ComfyUI#3867]
Related PR: https://github.com/comfyanonymous/ComfyUI/pull/3112

Reproduction Steps:
1. Click x on a workflow

![image](https://github.com/comfyanonymous/ComfyUI/assets/20929282/c1bbd36b-77dc-4f78-8ad8-177ba5a39781)

2. Click `No` in the popup dialog

![image](https://github.com/comfyanonymous/ComfyUI/assets/20929282/cea56506-c7da-43fd-af71-1982b5874bdd)

3. Click workflow tab to verify that a new workflow is created

![image](https://github.com/comfyanonymous/ComfyUI/assets/20929282/8e931238-db8d-412e-bcd6-4f240505b733)

**Comment by BrechtCorbeel** [comment]
Show me where the code for this is and I will look for a solution, is this installed by node or part of ComfyUI?

**Comment by JorgeR81** [comment]
It's part of Comfy UI, but it's in "Beta". You can enable it in the settings. 
It was added a couple of days ago, but it's being worked on for a few months now ( see PR conversation: https://github.com/comfyanonymous/ComfyUI/pull/3112 )

![set](https://github.com/comfyanonymous/ComfyUI/assets/72734038/4ff384be-34a5-4ce8-9fd0-8a376bcd8c90)

**Comment by JorgeR81** [comment]
OK, it's working now.

**Comment by HWiese1980** [comment]
Why is this closed? The bug persists, even today. I still experience the behavior described by @JorgeR81, never being able to return to an unsaved workflow. It always opens new tabs.

**Comment by JorgeR81** [comment]
> Why is this closed? The bug persists, even today. I still experience the behavior described by @JorgeR81, never being able to return to an unsaved workflow. It always opens new tabs.


It's working mostly fine for me.
But I did notice a strange behaviour:
 
Here I have 4 open workflows, 2 saved and e 2 unsaved. 

![Image](https://github.com/user-attachments/assets/d9a5e79a-62a2-45db-bec8-09e0cfab19f1)

I'm able to close all of them, from right to left, starting with **"unsaved workflow (6)"**.
But after closing the last one ( **"base"** ), then an **"unsaved workflow (5)"**, opens automatically.
Although this new **"unsaved workflow (5)"** it's not the same as I had before. It's just the default workflow.

![Image](https://github.com/user-attachments/assets/f1ec69ed-3c8f-4c39-824b-375c0448710e)

![Image](https://github.com/user-attachments/assets/26882049-c3a8-42be-b74b-f68620e8585b)

But am still able to close this new **"unsaved workflow (5)"**, to show no tabs and another default workflow. 

![Image](https://github.com/user-attachments/assets/367250db-711e-4243-8b64-58696f61b84f)

So maybe a more intuitive behaviour would be to don't' open this new **"unsaved workflow (5)"** or name it **"unsaved workflow (7)"** 

---

But anyways, a new UI is about to get added: https://github.com/Comfy-Org/ComfyUI_frontend/pull/4374

So, let's see how it behaves then.

----

By the way, frontend issues are now here: https://github.com/Comfy-Org/ComfyUI_frontend/issues
