### ISSUE TITLE
Could not allocate tensor with 58982400 bytes. There is not enough GPU video memory available!

### ISSUE THREAD

**Issue by gitspringcould** [comfyanonymous/ComfyUI#3869]
Could not allocate tensor with 58982400 bytes. There is not enough GPU video memory available!

**Comment by mcmonkey4eva** [comment]
That... sounds like you ran out of VRAM. If you need help with this, you'll need to specify more information (what are you trying to do? What GPU do you have? Be sure to post the rest of your logs as well)

**Comment by gitspringcould** [comment]
I don't have GPU. How I try it

**Comment by gitspringcould** [comment]
> That... sounds like you ran out of VRAM. If you need help with this, you'll need to specify more information (what are you trying to do? What GPU do you have? Be sure to post the rest of your logs as well)

I don't have GPU. How I try it

**Comment by mcmonkey4eva** [comment]
(A) use your CPU: Use the portable ComfyUI installer and use the `run_cpu.bat` file, or if using eg swarm, edit `--cpu` into your launch args -- note that AI on CPU is extremely slow.
or (B) use a cloud GPU provider: eg Colab, Runpod, etc. If you're new to AI stuff I'd recommend you use Swarm (friendlier frontend wrapper around Comfy). Cloud usage info for Swarm here <https://github.com/mcmonkeyprojects/SwarmUI?tab=readme-ov-file#try-it-on-google-colab-or-runpod>

**Comment by gitspringcould** [comment]
> (A) use your CPU: Use the portable ComfyUI installer and use the `run_cpu.bat` file, or if using eg swarm, edit `--cpu` into your launch args -- note that AI on CPU is extremely slow. or (B) use a cloud GPU provider: eg Colab, Runpod, etc. If you're new to AI stuff I'd recommend you use Swarm (friendlier frontend wrapper around Comfy). Cloud usage info for Swarm here https://github.com/mcmonkeyprojects/SwarmUI?tab=readme-ov-file#try-it-on-google-colab-or-runpod

Thank you. I solved my problem by using --cpu

**Comment by Starkallofc** [comment]
sorry @mcmonkey4eva  by going back on this question, my board is an rx5500xt and this giving this error would have how to help me? Could not allocate tensor with 58982400 bytes. There is not enough GPU video memory available
