### ISSUE TITLE
[Feature Request] Support Intel Extension for PyTorch (IPEX)

### ISSUE THREAD

**Issue by kwaa** [comfyanonymous/ComfyUI#387]
Similar to https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6417

Useful links:
- https://github.com/intel/intel-extension-for-pytorch
- https://pytorch.org/tutorials/recipes/intel_extension_for_pytorch.html

**Comment by comfyanonymous** [comment]
I don't have an arc card but if it's like MPS it should be possible to implement with just some modifications to the comfy/model_management.py file like this pull request for example: https://github.com/comfyanonymous/ComfyUI/pull/244

**Comment by kwaa** [comment]
> I don't have an arc card but if it's like MPS it should be possible to implement with just some modifications to the comfy/model_management.py file like this pull request for example: #244

Ok, I will try to modify this section to support IPEX.
One more question: is torchaudio a required dependency? It is mentioned in the README, but doesn't seem to be used within the source code.

**Comment by comfyanonymous** [comment]
It's not required. There's a few dependencies that get pulled in that are not actually required, I just don't have time to properly get rid of them.
