### ISSUE TITLE
Loading API-format workflow from new images does not work

### ISSUE THREAD

**Issue by kk-89** [comfyanonymous/ComfyUI#3870]
New images with the API-style JSON workflows embedded do not load the workflow correctly; nodes are created but aren't linked and their values look to be defaults. There are also litegraph warnings in the dev console. Old images with the old workflow JSON spec still seem to load correctly from a quick test.

It looks like the issue is related to the calls to `app.graph.add` and `graph.add` in `loadApiJson`. I tried removing the latter and things seem to be working.

**Comment by mcmonkey4eva** [comment]
likely broken in https://github.com/comfyanonymous/ComfyUI/pull/3112

**Comment by mcmonkey4eva** [comment]
fix pr https://github.com/comfyanonymous/ComfyUI/pull/3876

**Comment by mcmonkey4eva** [comment]
PR merged, bug confirmed fixed for me

**Comment by rabidcopy** [comment]
Can also confirm this fixed workflows created with an API-format. 👍
