### ISSUE TITLE
Default prompt is not perfect

### ISSUE THREAD

**Issue by brayevalerien** [comfyanonymous/ComfyUI#3874]
### Feature Idea

The prompt when you load the default graph seems to be missing a part and has an extra comma at the end:
```beautiful scenery nature glass bottle landscape, , purple galaxy bottle,```

This might look superficial to fix, but I think that the default workflow should be flawless and it should not be necessary to modify it when loading it.

### Existing Solutions

Simply correct the mistakes at [line 29 in defaultGraph.js](https://github.com/comfyanonymous/ComfyUI/blob/edfce78c86c7615039dd8d74e89957a0eebbdc03/web/scripts/defaultGraph.js#L29).

The new prompt could for instance simply be `beautiful scenery nature glass bottle landscape, purple galaxy bottle` if there is nothing more to add.

**Comment by ltdrdata** [comment]
The second comma is not a mistake. It's an intentional thing, kinda prompt engineering separating two prompts
