### ISSUE TITLE
Right click menu options order is unstable/indeterministic.

### ISSUE THREAD

**Issue by huchenlei** [comfyanonymous/ComfyUI#3883]
Right click menu options are unstable.
![image](https://github.com/comfyanonymous/ComfyUI/assets/20929282/06e766bd-c45f-4f05-b4d3-ea7adac54199)

_Originally posted by @huchenlei in https://github.com/comfyanonymous/ComfyUI/issues/3882#issuecomment-2192439044_

**Comment by huchenlei** [comment]
Following code's execution is not derministic: https://github.com/comfyanonymous/ComfyUI/blob/f12fa1d8d7b42888b6491aa6aa4956aefca3aba5/web/extensions/core/groupOptions.js#L71-L84

**Comment by BrechtCorbeel** [comment]
Might be like a numpy issue if they are ordered in a numpy array, same thing happens to me with que, did not notice that one yet.

**Comment by huchenlei** [comment]
> Might be like a numpy issue if they are ordered in a numpy array, same thing happens to me with que, did not notice that one yet.

I think it is caused by extension invoke sequence which happens in JS. It is definitely not a numpy issue.

**Comment by BrechtCorbeel** [comment]
Could be I'm going by recent mentions of numpy version issues I stumbled upon.
