### ISSUE TITLE
loading api json failure

### ISSUE THREAD

**Issue by zhangp365** [comfyanonymous/ComfyUI#3889]
### Expected Behavior

After updating to the latest version, the explorer cannot correctly load the API format JSON workflow. However, after enabling Dev Mode options and saving a new API workflow, the loading issue is resolved.

### Actual Behavior

loading the api format workflow may failure.

### Steps to Reproduce

just load the api workflow.

### Debug Logs

```powershell
no
```

**Comment by mcmonkey4eva** [comment]
update again, this was fixed yesterday
