### ISSUE TITLE
 Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated

### ISSUE THREAD

**Issue by xueqing0622** [comfyanonymous/ComfyUI#3893]
### Expected Behavior

F:\ComfyUI\python_embeded\Lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)

### Actual Behavior

I use "pip install -U transformers (>4.37.2)"  like this web
https://huggingface.co/stabilityai/stable-diffusion-3-medium-diffusers/discussions/18
still show same issue.

### Steps to Reproduce

It show in the cmd in comfyui

### Debug Logs

```powershell
how will fixed
```

**Comment by mcmonkey4eva** [comment]
This isn't something you need to worry about, just a deprecation warning, probably related to a custom node you have somewhere using outdated code. Nothing's actually broken from a deprecation notice

**Comment by xueqing0622** [comment]
Yes, it doesn't affect the use, but when cmd window starts, it stops there for a long time!
![image](https://github.com/comfyanonymous/ComfyUI/assets/114840118/9aeae145-a39b-4ba3-a611-548aa7c8075b)
