### ISSUE TITLE
When I enable the New Menu & Workflow, the entire canvas becomes unresponsive.

### ISSUE THREAD

**Issue by shmilyfuu** [comfyanonymous/ComfyUI#3894]
### Expected Behavior

I hope the New Menu & Workflow functions properly after being enabled.

### Actual Behavior

![bug](https://github.com/comfyanonymous/ComfyUI/assets/47942250/4b954366-940d-49bb-afb4-386cd59cf9b3)
When I change the "Use new menu and workflow management." option to top or bottom, an issue arises. While the new menu appears, something else shows up in the top left corner, seemingly related to color or style, which I've marked with a red box. During this time, I cannot operate the canvas or add or delete nodes; it appears frozen. I can use the new menu to switch or create workflows and use 11cafe's comfyui-workspace-manager to switch or create workflows, but whether I create a new workflow or open an existing one, the canvas remains blank. However, I can still interact with the new menu. When I click the new menu to open settings and disable the "Use new menu and workflow management." option, everything returns to normal.

### Steps to Reproduce

Currently, I encounter this issue with any workflow or when creating a new workflow.

### Debug Logs

```powershell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-27 22:55:16.250887
** Platform: Windows
** Python version: 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]
** Python executable: N:\CondaComfyUI\comfyenv\python.exe
** Log path: N:\CondaComfyUI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.2 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24563 MB, total RAM 65209 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention
Adding extra search path checkpoints N:/Stable Disffusion/Stable Disffusion SDXL/models/Stable-diffusion
Adding extra search path configs N:/Stable Disffusion/Stable Disffusion SDXL/models/Stable-diffusion
Adding extra search path vae N:/Stable Disffusion/Stable Disffusion SDXL/models/VAE
Adding extra search path loras N:/Stable Disffusion/Stable Disffusion SDXL/models/Lora
Adding extra search path loras N:/Stable Disffusion/Stable Disffusion SDXL/models/LyCORIS
Adding extra search path upscale_models N:/Stable Disffusion/Stable Disffusion SDXL/models/ESRGAN
Adding extra search path upscale_models N:/Stable Disffusion/Stable Disffusion SDXL/models/RealESRGAN
Adding extra search path upscale_models N:/Stable Disffusion/Stable Disffusion SDXL/models/SwinIR
Adding extra search path embeddings N:/Stable Disffusion/Stable Disffusion SDXL/embeddings
Adding extra search path hypernetworks N:/Stable Disffusion/Stable Disffusion SDXL/models/hypernetworks
Adding extra search path controlnet N:/Stable Disffusion/Stable Disffusion SDXL/models/ControlNet
Web extensions folder found at N:\CondaComfyUI\ComfyUI\web\extensions\ComfyLiterals
Warn!: xFormers is available (Attention)
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
Adding N:\CondaComfyUI\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from N:\CondaComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V5.18.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Impact-Pack (V5.18.3)
Loaded ImpactPack nodes from N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Crystools INFO] Crystools version: 1.12.0
[Crystools INFO] CPU: Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4090
[Crystools INFO] NVIDIA Driver: 555.99
Comfy-Easy-Use v1.2.0: Loaded
Total VRAM 24563 MB, total RAM 65209 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (V5.18.3)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.80.4)
### Loading: ComfyUI-Manager (V2.42)
### ComfyUI Revision: 2295 [4f9d2b05] | Released on '2024-06-27'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
--------------
 ### Mixlab Nodes: Loaded
ChatGPT.available True
edit_mask.available True
LaMaInpainting.available True
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
ClipInterrogator.available True
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available
 --------------
ComfyUI-N-Sidebar is loading...
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ReActor] - STATUS - Running v0.5.0-b4 in ComfyUI
Torch version: 2.3.0+cu121
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider

From Bmad Custom Nodes
 Loaded 124 nodes:
  + api nodes (14)
  + simple utility nodes (58)
  + CV nodes (49)
  + color clip ade20k node (1)
  + extension dependent nodes (2)

------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
Node -> DeepTranslatorNode [Loading]
Node -> ExtrasNode [Loading]
Node -> GoogleTranslateNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
# 😺dzNodes: LayerStyle -> Warning: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Find 1 LUTs in N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\lut
# 😺dzNodes: LayerStyle -> Find 1 Fonts in N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\font
[tinyterraNodes] Loaded
[comfy_mtb] | INFO -> loaded 77 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://192.168.0.108:27098/mtb if you want more information.
WARNING: Could not find OPENAI_API_KEY in .env, disabling gpt prompt generation.

[rgthree] Loaded 40 exciting nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `N:\CondaComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 217 nodes successfully.

        "Success is not the key to happiness. Happiness is the key to success." - Albert Schweitzer


Import times for custom nodes:
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\sd-perturbed-attention
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-ELLA
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_restart_sampling
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Dev-Utils
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Video-Matting
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-N-Sidebar
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-BrushNet
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui_bmad_nodes
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\comfy_mtb
   0.1 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.1 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_TensorRT
   0.1 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\eden_comfy_pipelines
   0.1 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Anyline
   0.1 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything
   0.1 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.2 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node
   0.3 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.4 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\clipseg.py
   0.9 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui-art-venture
   1.2 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-SUPIR
   1.2 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   1.3 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID
   1.6 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   1.6 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   1.7 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
   2.9 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools
   3.9 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui_LLM_party
   5.0 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack
  12.1 seconds: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

https_key OK:  N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\certificate.crt N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\private.key




Starting server
To see the GUI go to: http://192.168.0.108:27098
To see the GUI go to: https://192.168.0.108:27099
Start Log Catchers...
[LogConsole] client [e6823c6a639f4846b154cd42024d649f], console [08a783c6-db63-49ef-9f66-c8c441718ab6], connected
FETCH DATA from: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[LogConsole] client [e6823c6a639f4846b154cd42024d649f], console [08a783c6-db63-49ef-9f66-c8c441718ab6], disconnected
# 😺dzNodes: LayerStyle -> Warning: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
[comfy_mtb] | INFO -> Found multiple match, we will pick the last N:/Stable Disffusion/Stable Disffusion SDXL/models/SwinIR
['N:\\CondaComfyUI\\ComfyUI\\models\\upscale_models', 'N:/Stable Disffusion/Stable Disffusion SDXL/models/ESRGAN', 'N:/Stable Disffusion/Stable Disffusion SDXL/models/RealESRGAN', 'N:/Stable Disffusion/Stable Disffusion SDXL/models/SwinIR']
start_local_llm error
# 😺dzNodes: LayerStyle -> Warning: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
[LogConsole] client [e6823c6a639f4846b154cd42024d649f], console [7827760c-0526-4a7b-8ebf-3a7dd465ddcd], connected
#read_workflow_json_files_all N:\CondaComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\
```

**Comment by pythongosssss** [comment]
Have you updated all your custom nodes? There were initially some incompatibilities with e.g comfyui-workspace-manager that have been resolved

**Comment by JorgeR81** [comment]
It could be the ComfyUI-N-Sidebar ( https://github.com/Nuked88/ComfyUI-N-Sidebar ).
Is that the sidebar on your screenshot ?

I don't have it but, I have the ComfyUI-Custom-Scripts ( https://github.com/pythongosssss/ComfyUI-Custom-Scripts ) and the Image Feed also causes some issues in sidebar mode ( with location = left, in the settings).

**Comment by shmilyfuu** [comment]
> Have you updated all your custom nodes? There were initially some incompatibilities with e.g comfyui-workspace-manager that have been resolved

Yes, I confirm that I have updated all the nodes and ensured that ComfyUI is up to date.

**Comment by shmilyfuu** [comment]
> It could be the ComfyUI-N-Sidebar ( https://github.com/Nuked88/ComfyUI-N-Sidebar ). Is that the sidebar on your screenshot ?
> 
> I don't have it but, I have the ComfyUI-Custom-Scripts ( https://github.com/pythongosssss/ComfyUI-Custom-Scripts ) and the Image Feed also causes some issues in sidebar mode ( with location = left, in the settings).

Yes, it's the sidebar, but the part marked in red in the top left corner is not part of the sidebar. I don't know what is causing it.

**Comment by JorgeR81** [comment]
It could be part of the settings of a custom node, that's not working correctly. 
There seem to be an incompatibility between the new menu bar, and some custom nodes that also draw similar menu bars.

Try to disable the ComfyUI-N-Sidebar, in the Manager. You don't have to uninstall. 
If that doesn't work, try to disable other extensions that create its own menu.

**Comment by pythongosssss** [comment]
I've made a slight update in a draft PR to the way the elements are arranged which should make them more resilient to extra elements being added by custom nodes, if you could see if this improves it for you #3909

**Comment by shmilyfuu** [comment]
> It could be part of the settings of a custom node, that's not working correctly. There seem to be an incompatibility between the new menu bar, and some custom nodes that also draw similar menu bars.
> 
> Try to disable the ComfyUI-N-Sidebar, in the Manager. You don't have to uninstall. If that doesn't work, try to disable other extensions that create its own menu.

I uninstalled the sidebar, but the issue still persists.

**Comment by shmilyfuu** [comment]
> I've made a slight update in a draft PR to the way the elements are arranged which should make them more resilient to extra elements being added by custom nodes, if you could see if this improves it for you #3909
> 
> It should cause the custom element that is being added to go to the end of the body

I ran the command, and here is the result. I don't know what to do next.
![test](https://github.com/comfyanonymous/ComfyUI/assets/47942250/655358f9-27ff-4071-8576-4e0e74bb186c)

**Comment by JorgeR81** [comment]
Is that after the PR changes ?!

Try to disable the node that's drawing this small GUI element.
You don't have to uninstall it. 
You can disable it and enable it again later.

![side](https://github.com/comfyanonymous/ComfyUI/assets/72734038/2a51e630-5601-4a7e-abae-355c43a8bb0d)

**Comment by shmilyfuu** [comment]
> Is that after the PR changes ?!
> 
> Try to disable the node that's drawing this small GUI element. You don't have to uninstall it. You can disable it and enable it again later.
> 
> ![side](https://private-user-images.githubusercontent.com/72734038/344431529-2a51e630-5601-4a7e-abae-355c43a8bb0d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2OTg0MzUsIm5iZiI6MTcxOTY5ODEzNSwicGF0aCI6Ii83MjczNDAzOC8zNDQ0MzE1MjktMmE1MWU2MzAtNTYwMS00YTdlLWFiYWUtMzU1YzQzYThiYjBkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDIxNTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYjk5Mjg5ODAyMmJlODdkYTZhY2I0YjkwYjYxZWIxOTUyOTE1MDJmYWViMjEyNTIwYzIwMjlmZjA3ZGM2ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8abMZ00l0ByzS-HIKT8MM6UVui1zbqSjayGySBREgBY)

No, it's always been there. These two buttons are from the [Easy Use](https://github.com/yolain/ComfyUI-Easy-Use) node. 
I have now disabled it, but the issue still persists.

**Comment by JorgeR81** [comment]
I see that you also have the rgthree progress bar.
But that's not causing the issue either, because I also use it.  

Did you try the @pythongosssss's branch with the fixes ( https://github.com/pythongosssss/ComfyUI/tree/newmenu-fixes2 ) ?
Is that what's causing the other artifacts in your new screenshot ?

**Comment by shmilyfuu** [comment]
> I see that you also have the rgthree progress bar. But that's not causing the issue either, because I also use it.  
> 
> Did you try the @pythongosssss's branch with the fixes ( https://github.com/pythongosssss/ComfyUI/tree/newmenu-fixes2 ) ? Is that what's causing the other artifacts in your new screenshot ?

I have never used this branch before. Should I try it now?

**Comment by JorgeR81** [comment]
You only have issues when the new menu is enabled, right ?
If you're not experienced with the cmd line, perhaps it's better to just wait for that to be merged into the main branch. 

Also, the developer of the extension causing this, will eventually notice it, and could also fix it on their side.

**Comment by shmilyfuu** [comment]
> You only have issues when the new menu is enabled, right ? If you're not experienced with the cmd line, perhaps it's better to just wait for that to be merged into the main branch.
> 
> Also, the developer of the extension causing this, will eventually notice it, and could also fix it on their side.

Yes, it seems like trying what you suggested is the best approach. I hope it will resolve the issue.

**Comment by shmilyfuu** [comment]
> You only have issues when the new menu is enabled, right ? If you're not experienced with the cmd line, perhaps it's better to just wait for that to be merged into the main branch.
> 
> Also, the developer of the extension causing this, will eventually notice it, and could also fix it on their side.

I tried switching to the branch you mentioned and enabled the new menu. Now I can operate the canvas, and the functions on it seem to be back to normal. However, the content I initially marked with a red box has moved from the top left corner to the bottom left corner, regardless of whether I choose the new menu to be on the top or bottom. Additionally, there appears to be a section on the left side of the canvas that is obscured by something unknown, which I have marked with a yellow box.
![test](https://github.com/comfyanonymous/ComfyUI/assets/47942250/6e969d31-0799-47fe-88d8-5c666476026d)

**Comment by JorgeR81** [comment]
Try to disable the rgthree progress bar, in the rgthree settings.
I think that duplicated "Idle" word may come from that. 
Only the small world is related to the progress bar and should be there.

If so, there could be some else wrong, besides a specific extension. 
Because that rgthree progress bar is working well for me, with the new menu. 

![idle](https://github.com/comfyanonymous/ComfyUI/assets/72734038/9bbee19d-240a-48c3-a585-85ce63e37e67)

Also, try to disable and enable the new menu again, and then move it to the top and see what happens.

-----

I didn't try the new branch, but  @pythongosssss also made some fixes, on the custom node side ( Image Feed ).
Now the workflow is also working, but with some similar glitches.

https://github.com/comfyanonymous/ComfyUI/pull/3112#issuecomment-2198347518

**Comment by shmilyfuu** [comment]
> Try to disable the rgthree progress bar, in the rgthree settings. I think that duplicated "Idle" word may come from that.  Only the small world is related to the progress bar and should be there.
> 
> If so, there could be some else wrong, besides a specific extension.  Because that rgthree progress bar is working well for me, with the new menu. 
> 
> ![idle](https://private-user-images.githubusercontent.com/72734038/344450019-9bbee19d-240a-48c3-a585-85ce63e37e67.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzQyNTIsIm5iZiI6MTcxOTczMzk1MiwicGF0aCI6Ii83MjczNDAzOC8zNDQ0NTAwMTktOWJiZWUxOWQtMjQwYS00OGMzLWE1ODUtODVjZTYzZTM3ZTY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDA3NTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MmE4YzhhMmY1MzUwMjU2MGNkZDRhOTQyYjFlYjQ4MjQxMTZjMzI4OGUwMWRkZDlkYWJhNzFlNDlkYTAyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LKYIVrZ2jKQi7Ji4XstknidYbw4C14k8ZNYTSh0DNak)
> 
> Also, try to disable and enable the new menu again, and then move it to the top and see what happens.
> 
> I didn't try the new branch, but  @pythongosssss also made some fixes, on the custom node side ( Image Feed ). Now the workflow is also working, but with some similar glitches.
> 
> [#3112 (comment)](https://github.com/comfyanonymous/ComfyUI/pull/3112#issuecomment-2198347518)

I have tried disabling rgthree, but it didn't help. The current screenshot shows it disabled. Additionally, I have tried enabling and disabling the new menu many times. After switching to the branch you mentioned, regardless of whether the menu is at the top or bottom, the content marked with the red box stays in the bottom left corner, and the content marked with the yellow box stays on the left side. When I disable the new menu, everything returns to normal. I also tried switching browsers, but whether it's Edge or Chrome, the problem remains the same.
![test1](https://github.com/comfyanonymous/ComfyUI/assets/47942250/87583514-18ac-471b-9ccb-38ec11c9c4bc)

**Comment by JorgeR81** [comment]
Well, I guess we just have to wait for @pythongosssss next fixes.
Maybe it's just a matter of increasing tolerances a bit more ... 
https://github.com/pythongosssss/ComfyUI/commit/1a1624c39d31b2661eadc99ed0eebbd2fd6f0f40

**Comment by shmilyfuu** [comment]
Alright, it seems that's all I can do.

**Comment by shmilyfuu** [comment]
By disabling all custom nodes and then re-enabling them one by one, I identified that the node causing the issue is ([ComfyUI-3D-Pack](https://github.com/MrForExample/ComfyUI-3D-Pack)). It appears the problem is not with the new menu. I apologize for any confusion.
