### ISSUE TITLE
Unable to generate images

### ISSUE THREAD

**Issue by vararth** [comfyanonymous/ComfyUI#39]
Getting this in powershell -

ValueError: The device_map provided does not give any device for the following parameters: betas, alphas_cumprod, alphas_cumprod_prev, sqrt_alphas_cumprod, sqrt_one_minus_alphas_cumprod, log_one_minus_alphas_cumprod, sqrt_recip_alphas_cumprod, sqrt_recipm1_alphas_cumprod, posterior_variance, posterior_log_variance_clipped, posterior_mean_coef1, posterior_mean_coef2

**Comment by comfyanonymous** [comment]
Can you give me more information about your system like which GPU you have and how you are running comfyUI?

**Comment by vararth** [comment]
I have a Nvidia 3050, 4GB running on a Lenovo Ideapad. I have automatic1111 already installed so I went to the comfyui folder, started up powershell, ran the Activate.ps1 script and in the models folder, I have waifu diffusion ckpt loaded.
Once the url showed up, I did not make any changes just to do a dry run of the tool but nothing was generated after I pressed the button.

**Comment by comfyanonymous** [comment]
It looks like the a1111 ui venv has an outdated version of accelerate. I use that package for the lowvram mode in my UI which gets automatically enabled on your GPU.

Try: pip install accelerate --upgrade
