### ISSUE TITLE
After use sd3_medium_incl_clips_t5xxlfp16.safetensors model , ComfyUI  is disconnected.

### ISSUE THREAD

**Issue by Desperado1001** [comfyanonymous/ComfyUI#3911]
### Your question

After use sd3_medium_incl_clips_t5xxlfp16.safetensors model , ComfyUI  is disconnected.But other model,such as dreamshaperXL_v21TurboDPMSDE.safetensors can run right.

### Logs

```powershell
G:\comfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 12288 MB, total RAM 32605 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch cross attention

Import times for custom nodes:
   0.0 seconds: G:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation-main
   0.0 seconds: G:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type FLOW
Using pytorch attention in VAE
Using pytorch attention in VAE

G:\comfyUI\ComfyUI_windows_portable>pause
请按任意键继续. . .
```

**Comment by mcmonkey4eva** [comment]
Does the same happen using a non-T5 model?

It's likely just you're using enough of your RAM on other things that loading the full fat model with the big fat T5 on it is pushing you over the limit and the process is crashing from running out of memory.

**Comment by mo-bai** [comment]
It's happening to me, too.
 I tried sd3_medium_incl_clips_t5xxlfp16.safetensors model and sd3_medium_incl_clips_t5xxlfp8.safetensors model.

 I checked the resource usage tab of task manager while loading.  and then the cpu and memory peak usage is less than 50% and the GPU usage  is hardly up at all

### log
`E:\program_files\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 16380 MB, total RAM 32607 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention

Import times for custom nodes:
   0.0 seconds: E:\program_files\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\program_files\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation-main

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type FLOW
Using pytorch attention in VAE
Using pytorch attention in VAE

E:\program_files\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>pause`

**Comment by huangkun1985** [comment]
same issues happened to me, i cannot fix it, here is the coding:

D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 24564 MB, total RAM 32606 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type FLOW
Using pytorch attention in VAE
Using pytorch attention in VAE

D:\ComfyUI_windows_portable>pause
请按任意键继续. . .
