### ISSUE TITLE
Wrong name in windows portable build

### ISSUE THREAD

**Issue by vincenzoml** [comfyanonymous/ComfyUI#3912]
### Expected Behavior

In the windows portable build, the python directory should be called "python_embedded"

### Actual Behavior

It's called "python_embeded" with just one "d", which is a typo in english

### Steps to Reproduce

It's a packaging bug

### Debug Logs

```powershell
It's a packaging bug
```

**Comment by mcmonkey4eva** [comment]
Yes this is known, it's a small typo and it'd cause some problems to change it and nothing is actually improved by fixing it
