### ISSUE TITLE
What's wrong with the quality of image rendering?

### ISSUE THREAD

**Issue by hyuck9859** [comfyanonymous/ComfyUI#3914]
### Your question

<img width="2560" alt="스크린샷 2024-07-01 오전 10 18 14" src="https://github.com/comfyanonymous/ComfyUI/assets/44662630/d08d5f2a-7d38-4f1b-b1f7-c3a6fa8821dc">

The image rendering quality looks very low, like the screenshot image. I think I set the node correctly, what's the problem?
I'm using Mac OS and running on an intel CPU.

System Specifications
CPU : 3.8 GHz 8 core Intel Core i7
Memory : 32GB 2667 MHz DDR4
Graphic : AMD Radeon pro 5700 XT 16GB

**Comment by KillyTheNetTerminal** [comment]
Try with another Sampler like Euler_a

**Comment by hyuck9859** [comment]
> Try with another Sampler like Euler_a

I still have the same problem when I change the sampler

**Comment by KillyTheNetTerminal** [comment]
maybe this model works with clip skip 2, set the clip skip in 2 and try again
![image](https://github.com/comfyanonymous/ComfyUI/assets/120438550/26ad7080-e516-44f1-9d62-62adf5e01b7b)

**Comment by hyuck9859** [comment]
I tried the setting you told me, but I still can't solve the problem
![Uploading 스크린샷 2024-07-02 오전 9.18.00.png…]()

**Comment by edwardsdigital** [comment]
from the civitai page:

- VAE is included (840000)
- Clip skip: 2
- CFG scale: 8
- Sampler: DPM++ SDE Karras
    Sampling Steps : 30+
- Upscaler (Hires. fix): R-ESRGAN 4x+ Anime6B
    Hires steps: 14
    Denoising strength: 0.35
    Upscale by: 1.5+

set your config back to 8 and up your sampling steps to 30 or more.

**Comment by hyuck9859** [comment]
I don't understand this very well, can you share a screenshot?

**Comment by KillyTheNetTerminal** [comment]
can you share your workflow json? to set all this values to screenshot

**Comment by ltdrdata** [comment]
![workflow (21)](https://github.com/comfyanonymous/ComfyUI/assets/128333288/e965b4ea-6167-4159-9508-33630a83e09a)

It runs without issues with that model and settings. This could be a hardware or driver related issue.
