### ISSUE TITLE
Add a zoom speed setting

### ISSUE THREAD

**Issue by rainlizard** [comfyanonymous/ComfyUI#3924]
### Feature Idea

My finger gets tired with this slow mouse wheel zoom speed, and yet I've also seen others who've had trouble with the zoom speed being too fast for them in the past, and so what this means is it really needs to be a configurable setting for each individual.

### Existing Solutions

Luckily I figured out how to do it myself so this can serve as a guide for anyone who comes across it:

- Open the file in a text editor: `ComfyUI\web\lib\litegraph.core.js`
- Search for `scale *= 1.1;`
- Replace the 1.1 with a larger number like 1.5 for a faster zooming in speed, or use a smaller number like 1.05 for a slower zooming in speed.
- Two lines below that is the zooming *out* speed, which you'll also want to change: `scale *= 1 / 1.1;`, you can just replace this 1.1 with the same number as before.

But hopefully this can get added an official setting for better ease of use.

**Comment by huchenlei** [comment]
Issue transferred to litegraph repo.
