### ISSUE TITLE
Image Feed Location left or right with New menu and workflow management cover screen

### ISSUE THREAD

**Issue by xueqing0622** [comfyanonymous/ComfyUI#3925]
### Expected Behavior

Image Feed Location left or right with New menu and workflow management cover screen like that.

### Actual Behavior

![PixPin_2024-07-02_09-05-08](https://github.com/comfyanonymous/ComfyUI/assets/114840118/8779b2fc-fed6-419c-a515-0eb7f7e1026d)

### Steps to Reproduce

also the image feed text no hide like before

### Debug Logs

```powershell
hope will fixed quickly
```

**Comment by mcmonkey4eva** [comment]
That feed is not part of ComfyUI's core, it comes from a custom node pack you have installed - report the issue on the github for that project

**Comment by xueqing0622** [comment]
oh, thx!
