### ISSUE TITLE
the node "SamplerEulerCFG++" causes an error if "alternative" is selected

### ISSUE THREAD

**Issue by wildage** [comfyanonymous/ComfyUI#3929]
### Expected Behavior

in previous version, if I select "alternative" in the node "SamplerEulerCFG++", and set scheduler to "karras", steps to "28", "denoise" to 0.90 in the node "BasicScheduler", it worked very well and did a fine modification to the original picture without any detriments.
I understand that in the newest version of comfyui there would be a choice allowing me to use "euler_cfg_pp" as sampler, but it won't produce a fine result as it did.
If I select "regular" in the node, it doesn't cause an error, the image quality is poor, and it becomes unusable with a denoise value over 0.55, and that will be the same as it is when I use "euler_cfg_pp" in a normal "KSampler" node

### Actual Behavior

it will cause an error as below:

Error occurred when executing SamplerEulerCFGpp:

module 'comfy.k_diffusion.sampling' has no attribute 'sample_euler_pp'

File "C:\stable-diffusion-ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\stable-diffusion-ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\stable-diffusion-ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\stable-diffusion-ComfyUI\comfy_extras\nodes_advanced_samplers.py", line 102, in get_sampler
sampler = comfy.samplers.ksampler("euler_pp")
File "C:\stable-diffusion-ComfyUI\comfy\samplers.py", line 596, in ksampler
sampler_function = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))

### Steps to Reproduce

[Untitled Flow.json](https://github.com/user-attachments/files/16069030/Untitled.Flow.json)

### Debug Logs

```powershell
!!! Exception during processing!!! module 'comfy.k_diffusion.sampling' has no attribute 'sample_euler_pp'
Traceback (most recent call last):
  File "C:\stable-diffusion-ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\stable-diffusion-ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\stable-diffusion-ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\stable-diffusion-ComfyUI\comfy_extras\nodes_advanced_samplers.py", line 102, in get_sampler
    sampler = comfy.samplers.ksampler("euler_pp")
  File "C:\stable-diffusion-ComfyUI\comfy\samplers.py", line 596, in ksampler
    sampler_function = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))
AttributeError: module 'comfy.k_diffusion.sampling' has no attribute 'sample_euler_pp'. Did you mean: 'sample_euler'?
```

**Comment by wildage** [comment]
I need to add some more information: because the uploaded workflow can only be a simplified version without custom nodes, I created a new workflow. To simplify reproducing the issue, I didn't use the SD3 model in this workflow. The image quality problem I mentioned occurs when using the SD3 model. I just tested it, and the SDXL model still runs quite well.

**Comment by comfyanonymous** [comment]
Should be fixed now.
