### ISSUE TITLE
Latent upscale causes black image on some resolutions

### ISSUE THREAD

**Issue by sALTaccount** [comfyanonymous/ComfyUI#394]
Using a base resolution of 576x960, going with ~1.5x latent upscale (to 896x1472) is possible
![image](https://user-images.githubusercontent.com/18043686/229883803-aef724ee-9a63-4025-9d43-f9aed8b8ea48.png)
However, trying to do ~2x latent upscale (1152x1920) just causes a black image to be output by the upscaler
![image](https://user-images.githubusercontent.com/18043686/229884125-7df0e9e8-07db-4cb3-bf43-e421c01c6bb8.png)
Here is my pip freeze https://pastebin.com/kZvQpFYH
I'm using a 4090 wth a Ryzen 7 5800x with 40gb of ram. I'm not running out of vram or ram either.

**Comment by comfyanonymous** [comment]
Is this a one off bug or something you are constantly able to reproduce even after restarting the backend?

**Comment by erikmackinnon** [comment]
I can confirm that I'm getting this issue as well with a 4090. At first I thought it was specific VAE causing it, but after seeing this it's actually changing resolutions that is producing this issue, similar to what sALTaccount said.

**Comment by comfyanonymous** [comment]
Can you test if the VAEDecodeTiled node in the _for_testing also gives you black images so that I can know if the problem is because of the VAE decoding or because of something else.

**Comment by sALTaccount** [comment]
![image](https://user-images.githubusercontent.com/18043686/229949064-5a362919-3f6c-4fda-95c0-c6cdc6f34eef.png)
yup it does appear to be VAE related, tiled VAE works just fine
![image](https://user-images.githubusercontent.com/18043686/229949775-cf7f844c-c15f-49dd-9d13-c08a8b228b28.png)
no vram spikes or anything though and no error messages

**Comment by WASasquatch** [comment]
Black images from decoding is usually actually because VRAM hit a limit and the tensor zeroed out. This is a problem with diffusers, a1111, etc,

**Comment by comfyanonymous** [comment]
This is a problem related to xformers 0.0.18, downgrading to 0.0.17 will fix it. I have filed an issue with xformers so they can fix it: https://github.com/facebookresearch/xformers/issues/719

**Comment by sALTaccount** [comment]
Damn, was trying to avoid having to compile xformers for the 5483th time 😢 thanks for looking into this. I'll close the issue as its upstream

**Comment by sALTaccount** [comment]
Although maybe a warning should be added if xformers 0.0.18 is detected 🤔

**Comment by comfyanonymous** [comment]
ComfyUI runs the VAE in full precision. I just disabled xformers in the VAE for 0.0.18 so it will use the split optimization instead which is slower but will actually work. https://github.com/comfyanonymous/ComfyUI/commit/e46b1c3034a23eeb048e279d0d285737d39a4b1a

**Comment by WASasquatch** [comment]
FYI, I don't use xformers in WebUI, or Diffusers, and it still happens if VRAM comes hits the ceiling. I do use xformers in comfyui though as I try to keep settings absolutely vanilla while developing.

**Comment by oakif** [comment]
I'm getting this issue on the latest commit, which is f84f250

![image](https://user-images.githubusercontent.com/48932412/230494070-8cad3c27-92b5-4d32-9aae-b4c380e62635.png)

**Comment by comfyanonymous** [comment]
How did you install comfyUI and which xformers version do you have exactly?

**Comment by oakif** [comment]
I used `git clone` on the repo in WSL, installed the requirements using `pip install -r requirements`, and am running it using `python main.py`. According to A1111 WebUI, I'm using xformers 0.0.14.dev

**Comment by WASasquatch** [comment]
> I used `git clone` on the repo in WSL, installed the requirements using `pip install -r requirements`, and am running it using `python main.py`. According to A1111 WebUI, I'm using xformers 0.0.14.dev

Are you running within WebUI? WebUI holds on to models and other stuff into VRAM which leaves very little for ComfyUI

**Comment by oakif** [comment]
> > I used `git clone` on the repo in WSL, installed the requirements using `pip install -r requirements`, and am running it using `python main.py`. According to A1111 WebUI, I'm using xformers 0.0.14.dev
> 
> Are you running within WebUI? WebUI holds on to models and other stuff into VRAM which leaves very little for ComfyUI. I actually haven't used A1111 except to train, cause I can make significantly larger images in ComfyUI due to much better memory management.

I'm not exactly sure, but I'm running ComfyUI separately from WebUI

**Comment by justanothernguyen** [comment]
Installing xformers 0.0.17 solved black images issue for me.

ComfyUI and A1111 probably use different Python environment, so the version info from A1111 is unreliable.

To know which version of xformers you have, go to where you deployed ComfyUI and look into the folder `python_embeded\Lib\site-packages\`. If there's a folder named `xformers-0.0.18.dist-info`, then you have xformers 0.0.18 installed.

To downgrade to xformers 0.0.17, open a command prompt where you deploy ComfyUI and run this

`python_embeded\python.exe -s -m pip install xformers==0.0.17`

This should uninstall whichever xformers you have and install 0.0.17.

Obviously this is for Windows, but if you're using Linux, chances are you already know what to do already.

**Comment by comfyanonymous** [comment]
The latest ComfyUI prints your xformers version on startup along with a warning if it's 0.0.18
