### ISSUE TITLE
these symbols aren't defined in the comfy controlnet mmdit code

### ISSUE THREAD

**Issue by doctorpangloss** [comfyanonymous/ComfyUI#3946]
I found this with `pylint comfy/`.

https://github.com/comfyanonymous/ComfyUI/blob/24b969d3dace581ed3fb547eedfbdf502ad0f7e9/comfy/cldm/mmdit.py#L62

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/739b76630e0298561c39d0d3341bc2856e55d995
