### ISSUE TITLE
Beta menu bar overlaps close button for properties panel

### ISSUE THREAD

**Issue by wearsshoes** [comfyanonymous/ComfyUI#3948]
### Expected Behavior

Properties panel is entirely shown on screen and is closeable.

### Actual Behavior

Menu is laid on top of properties panel, covering the close button.

### Steps to Reproduce

1. Enable "Settings > Use new menu > Top"
2. Right click on any module, select Properties panel.

<img width="573" alt="Screenshot 2024-07-04 at 1 43 11 PM" src="https://github.com/comfyanonymous/ComfyUI/assets/6755414/d9cc2ea3-ae4d-498b-a07b-9f467b62045f">

### Debug Logs

```powershell
n/a
```

### Other
ComfyUI: `1[739b76](2024-07-04)`
Manager: V2.44.1

Google Chrome
Chrome is up to date
Version 126.0.6478.127 (Official Build) (arm64)

_No response_

**Comment by huchenlei** [comment]
Issue already filed in custom node repo: https://github.com/Nuked88/ComfyUI-N-Sidebar/issues/79
