### ISSUE TITLE
Workflow Layout Destruction

### ISSUE THREAD

**Issue by Yggdrasil777** [comfyanonymous/ComfyUI#395]
This is what the layout should look like (took awhile to set this up):
![image](https://user-images.githubusercontent.com/775705/229897356-d3469ce0-5b45-42cd-8f30-71ca971dcee2.png)

This is what happens when it is loaded in:
![image](https://user-images.githubusercontent.com/775705/229899972-88107916-73f1-4168-b85a-154deb331512.png)

Here is an overview of the entire node system:
![image](https://user-images.githubusercontent.com/775705/229900060-c29fd077-f83b-490e-b60b-6aab8cccaec0.png)

Attached is the .zip file containing the .json file saved.
[WorkingWorkflow.zip](https://github.com/comfyanonymous/ComfyUI/files/11152290/WorkingWorkflow.zip)

**Comment by comfyanonymous** [comment]
Are you on the latest code? This is what I see when I load your workflow (the nodes are red because I don't have your custom nodes) but it seems to be loading it correctly?
![Screenshot_20230404_153518](https://user-images.githubusercontent.com/121283862/229900967-81828d11-0a74-4b9f-be9f-238c1bd3b7f1.png)

**Comment by Yggdrasil777** [comment]
I believe so, here is the console output from about one minute ago:
![image](https://user-images.githubusercontent.com/775705/229905375-eeb7c937-7770-4ae6-9e01-b409bd66bfa8.png)

**Comment by wyrde** [comment]
![Yggdrasil777 test 2023-04-05 18_39_17-Mozilla Firefox](https://user-images.githubusercontent.com/9657443/230227315-85846136-330e-4a0e-b775-b7e175af76dc.png)

**Comment by robinjhuang** [comment]
@Yggdrasil777 This should be fixed. Please reopen if it's still an issue.
