### ISSUE TITLE
Variables support

### ISSUE THREAD

**Issue by gaardiolor** [comfyanonymous/ComfyUI#3951]
### Feature Idea

Hello, 

I can't find how to use variables in ComfyUI. If it cannot be done now, it would be beneficial to add support.

I have a workflow, many nodes have a fps or frame_rate setting. Those have to be aligned. It would be great if there was a node in which a user can define variables like `fps = 30`, and reference them in other nodes + do some basic calculations like `$fps/2`

### Existing Solutions

Can't find any solutions for this.

**Comment by mcmonkey4eva** [comment]
that'd be the Primitive node. There are various custom node packs for math available
