### ISSUE TITLE
Add a scrollbar to lists

### ISSUE THREAD

**Issue by BlinkerHigh** [comfyanonymous/ComfyUI#3957]
### Feature Idea

I have a lot of LORAs, and it takes forever to scroll down to the bottom of the list using the mouse wheel.
A scrollbar would be a huge QoL addition.

**Comment by mcmonkey4eva** [comment]
Good frontend feature suggestion, I agree

Though I'll note some options in the meantime:
- You can of course type while a list is open to filter by name, this is usually the most convenient for large lists to find what you want
- With [Swarm](https://github.com/mcmonkeyprojects/SwarmUI) there's a full lora browser tab that makes choosing loras to use super clean and easy

**Comment by BlinkerHigh** [comment]
> * You can of course type while a list is open to filter by name, this is usually the most convenient for large lists to find what you want

Yeah but most of the time I don't know what I'm looking for, or I simply don't remember the name.
I'm sure I'm not the only one in this situation.

**Comment by huchenlei** [comment]
Issue transferred to https://github.com/Comfy-Org/ComfyUI_frontend/issues/102

**Comment by devrosx** [comment]
could it not be done if the list is very long with several columns next to each other?
