### ISSUE TITLE
Error: local variable 'sigmas' referenced before assignment

### ISSUE THREAD

**Issue by thinkingjimmy** [comfyanonymous/ComfyUI#3961]
### Your question

When I use AYS scheduler, it shows the following error:

```
local variable 'sigmas' referenced before assignment
```

Device: Macbook M3
Workflow: Default workflow

<img width="1174" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/37492595/b37a5575-b251-407c-bcc4-9f5f230191ff">

**Comment by ltdrdata** [comment]
You cannot use AYS scheduler in default workflow.
That means your efficiency nodes is outdated.
