### ISSUE TITLE
Text fields overlapping input/output labels when zoomed out

### ISSUE THREAD

**Issue by brbbbq** [comfyanonymous/ComfyUI#3965]
### Expected Behavior

The text field should be anchored properly to the node so it doesn't overlap with the labels when zoomed out.

### Actual Behavior

The text field slides up when zooming out blocking the input/output labels.

### Steps to Reproduce

Add a node with a text field, like the CLIP Text Encode node for example, and zoom out.
![240707-103548-chrome](https://github.com/comfyanonymous/ComfyUI/assets/135537138/6bb4548e-f11a-4980-9802-876c5411f8d1)

### Debug Logs

```powershell
This is a user interface issue.
```

**Comment by makeitrad** [comment]
Im seeing the same thing. reported to VHAS nodes yesterday but I believe this to be a larger ComfyUI issue as Im seeing it in other packages as well.

**Comment by brbbbq** [comment]
Yes, some nodes like _Load Image_ and _Preview Image_ are fine, but nodes like _Display Any (rgthree)_, _Video Combine_, _Create Fade Mask_ and _Note_ are suffering from it.
![240707-170357-chrome](https://github.com/comfyanonymous/ComfyUI/assets/135537138/80126ce1-7592-4a6f-9c9a-0731d46d55b7)
![240707-170521-chrome](https://github.com/comfyanonymous/ComfyUI/assets/135537138/bbea3184-fd7b-4e08-8207-a9e49d8d0e6f)

**Comment by shawnington** [comment]
I experience this same issue some times. If I inspect element in the browser, it recalculates everything and things line up again. 

I haven't really looked around to try and fix it.

**Comment by huchenlei** [comment]
I am having some difficulties reproducing this locally. Do you have any special setup to reproduce this issue?

**Comment by Koitenshin** [comment]
It just happens from time to time, it's most likely a Z-Clipping issue. The "Note" node under utils will occasionally just display over everything else.

**Comment by mcmonkey4eva** [comment]
frontend issue https://github.com/Comfy-Org/ComfyUI_frontend
