### ISSUE TITLE
网页失去响应

### ISSUE THREAD

**Issue by LeeKIngKIng** [comfyanonymous/ComfyUI#3968]
### Your question

经排查，后台能正常输出信息，但PromptServer的send_sync方法异常，self.messages.put_nowait能正常往队列增加元素，但是元素未能正常执行发出，导致socket失去响应。请问各路大神需要怎么解决？

**Comment by huchenlei** [comment]
Merged into https://github.com/comfyanonymous/ComfyUI/issues/3980
