### ISSUE TITLE
CORS support in backend

### ISSUE THREAD

**Issue by space-nuko** [comfyanonymous/ComfyUI#397]
I want to test a frontend on a different port than the backend on `localhost`, but get blocked by CORS.

Sadly however `aiohttp_cors` has a 5-year-old bug that breaks CORS support for POST requests (while GET works fine): https://github.com/aio-libs/aiohttp-cors/issues/155

I found that I had to use this code to work around it, but I couldn't get around modifying the backend https://github.com/home-assistant/core/issues/40513#issuecomment-700654471

**Comment by comfyanonymous** [comment]
Isn't CORS just a header? Why would we need a library for that?

**Comment by space-nuko** [comment]
I don't know, I wasn't sure how complicated it was since it seemed their library was the first search result for "cors aiohttp." If there's a simpler way to add it it should be fine.

**Comment by johndpope** [comment]
` python main.py --listen --enable-cors-header "*"`
