### ISSUE TITLE
What projects and plugins have implemented the separation of the frontend and backend in ComfyUI?

### ISSUE THREAD

**Issue by joyoungzhang** [comfyanonymous/ComfyUI#3973]
### Feature Idea

Frontend: Extracting the ComfyUI frontend into a separate project. 
Backend: A GPU cluster receives tasks and runs them in ComfyUI worker, with multiple frontends sharing these GPU clusters.

The number of frontend users is much greater than the number of backend GPU nodes, and user tasks are queued for execution.

Thanks.

**Comment by Koitenshin** [comment]
If I'm reading your request right, have you seen [SDFX](https://github.com/sdfxai/sdfx)?

**Comment by mcmonkey4eva** [comment]
[Swarm](https://github.com/mcmonkeyprojects/SwarmUI) does this, allowing both many-users and many-backends relatively cleanly.

There are also various webservices that do things like dynamic backends, such as [ComfyDeploy](https://www.comfydeploy.com/)
