### ISSUE TITLE
API接口

### ISSUE THREAD

**Issue by YSblack** [comfyanonymous/ComfyUI#3981]
### Your question

有完整的API接口请求文档吗 ？

**Comment by huchenlei** [comment]
Currently you have to directly referece impl in https://github.com/comfyanonymous/ComfyUI/blob/master/server.py

We have some API return values typed in https://github.com/Comfy-Org/ComfyUI_frontend/blob/9762b7884cc9bc7267f3e2115bdbe02d3bdccebc/src/types/apiTypes.ts

**Comment by YSblack** [comment]
> 目前，您必须直接引用 [impl in https://github.com/comfyanonymous/ComfyUI/blob/master/server.py](https://github.com/comfyanonymous/ComfyUI/blob/master/server.py)
> 
> 我们有一些 API 返回值键入 https://github.com/Comfy-Org/ComfyUI_frontend/blob/9762b7884cc9bc7267f3e2115bdbe02d3bdccebc/src/types/apiTypes.ts

有获取当前正在使用的workflow.json名称的接口吗？

**Comment by YSblack** [comment]
> 您可以调用 API 端点以获取当前排队和当前正在执行的工作流`/queue`

comfyui导出的workflow.json，有没有固定的唯一参数？或者唯一编号以及标识

**Comment by jensen1207** [comment]
API已跑通，咨询+vx：八七六八七六二七

**Comment by programming-pupil** [comment]
> https://github.com/comfyanonymous/ComfyUI/blob/master/server.py
Don't make a fool of yourself.

**Comment by programming-pupil** [comment]
> API已跑通，咨询+vx：八七六八七六二七

Don't make a fool of yourself.
