### ISSUE TITLE
native iteration support

### ISSUE THREAD

**Issue by nanamicat** [comfyanonymous/ComfyUI#3982]
### Feature Idea

small changes on one or more field is really using in comparing or fine-tuning final image.
https://github.com/jags111/efficiency-nodes-comfyui provides XY Plot support, but it's limited to 2D and only support some of fields. 

generally, any number type variable could iteration in same way.
let's assume there is a `for` node, take (initial, step, count) or (initial, final, count) as input. and output a number, that could connect to any number field input.
On queue task, It will batch add $\prod range_i.count$ numbers of task. and assign input to each task.

string fields is almost same but only changing values to `foreach` in array list.

### Existing Solutions

https://github.com/jags111/efficiency-nodes-comfyui

**Comment by mcmonkey4eva** [comment]
https://github.com/mcmonkeyprojects/SwarmUI has a Grid Generator tool to make grids of any parameter(s) in any workflows with any arbitrary number of axes

**Comment by ltdrdata** [comment]
A general iteration feature is already in progress.
#2666
