### ISSUE TITLE
Restart sampling 

### ISSUE THREAD

**Issue by kawaii2020** [comfyanonymous/ComfyUI#3983]
### Feature Idea

Any plan to integrate the Restart sampler?
![image](https://github.com/comfyanonymous/ComfyUI/assets/32961592/18d5f026-16b5-4b1c-9d81-b8e980512ab6)

**Comment by ltdrdata** [comment]
There are two options for now.

https://github.com/ssitu/ComfyUI_restart_sampling
https://github.com/licyk/ComfyUI-Restart-Sampler

**Comment by kawaii2020** [comment]
> There are two options for now.
> 
> https://github.com/ssitu/ComfyUI_restart_sampling https://github.com/licyk/ComfyUI-Restart-Sampler

![image](https://github.com/comfyanonymous/ComfyUI/assets/32961592/1370e4b0-1524-4f03-843d-710f1958a438)

2nd one works, thank you.
