### ISSUE TITLE
Group node components do not preserve node values

### ISSUE THREAD

**Issue by lokimckay** [comfyanonymous/ComfyUI#3984]
### Expected Behavior

Group node component values should match the values that are saved in their JSON file

### Actual Behavior

Group node component values are reset to the defaults of the inner node(s)

### Steps to Reproduce

1. Create two `Empty Latent Image` nodes
1. Change the widths of both to `1024`
1. Convert these nodes as a Group Node
1. Note that widths are `1024` as expected
1. Save the Group Node as a component
1. Clear/create a new workflow
1. Add the component node to the workflow
1. Observe that widths have been reset to `512`

### Debug Logs

```
N/A
```

### Other

```
ComfyUI: 2280[73ca78](2024-06-23)
Manager: V2.41
```

**Comment by huchenlei** [comment]
How do you save Group as component? Can you attach a screenshot? Is it a feature provided by comfy core?

**Comment by lokimckay** [comment]
Sorry I thought it was core, but it appears it is provided by ComfyUI Manager
I will move this issue over to that repo and attach screenshots there
