### ISSUE TITLE
After loading the image drawing mask and saving it, the position of the drawing mask cannot be previewed.

### ISSUE THREAD

**Issue by Willy-Shenn** [comfyanonymous/ComfyUI#3986]
### Your question

I am using the "Load Image" function in ComfyUI. After drawing the mask and saving it, I am unable to preview the result of the mask I drew. All operations are done within the "Load Image" node. However, in my "input" folder, there are images with the completed masks. If I upload the images with completed masks from the "input" folder to the "Load Image" node, the masks still cannot be previewed. In other words, any mask on an image within my ComfyUI cannot be previewed.
![Original Image](https://github.com/comfyanonymous/ComfyUI/assets/79782696/08d28c51-6d80-451e-a835-f348c9977d16)

![Mask Image](https://github.com/comfyanonymous/ComfyUI/assets/79782696/25a617b8-39e5-4ba2-adc9-9b82f94723eb)

**Comment by shawnington** [comment]
mask2image->preview

**Comment by Willy-Shenn** [comment]
Thank you very much for your response. According to your instructions, it should be done this way, but this only generates a black and white mask image. What I need is as shown in the image below, a mask drawn on the original image. As mentioned above, the mask is generated after drawing, but the completed mask does not appear on the original image.
![螢幕擷取畫面 2024-07-10 165705](https://github.com/comfyanonymous/ComfyUI/assets/79782696/c0a6c3c4-3409-45c3-9f2d-ddfa952b2ac4)
![螢幕擷取畫面 2024-07-10 165821](https://github.com/comfyanonymous/ComfyUI/assets/79782696/3bd94f38-ba21-4fa8-b0e3-f2e20888394e)

**Comment by Willy-Shenn** [comment]
> mask2image->preview

Thank you very much for your response. According to your instructions, it should be done this way, but this only generates a black and white mask image. What I need is as shown in the image below, a mask drawn on the original image. As mentioned above, the mask is generated after drawing, but the completed mask does not appear on the original image.
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by Willy-Shenn** [comment]
> mask2image->preview

Thank you very much for your response. According to your instructions, it should be done this way, but this only generates a black and white mask image. What I need is as shown in the image below, a mask drawn on the original image. As mentioned above, the mask is generated after drawing, but the completed mask does not appear on the original image.
![螢幕擷取畫面 2024-07-10 165705](https://github.com/comfyanonymous/ComfyUI/assets/79782696/4efea622-216c-430a-a8eb-9269aa1077f7)
![螢幕擷取畫面 2024-07-10 165821](https://github.com/comfyanonymous/ComfyUI/assets/79782696/1cf8cfa4-b773-4c70-846f-7950d5a08a73)

**Comment by shawnington** [comment]
> > mask2image->preview
> 
> Thank you very much for your response. According to your instructions, it should be done this way, but this only generates a black and white mask image. What I need is as shown in the image below, a mask drawn on the original image. As mentioned above, the mask is generated after drawing, but the completed mask does not appear on the original image. ![螢幕擷取畫面 2024-07-10 165705](https://private-user-images.githubusercontent.com/79782696/347336185-4efea622-216c-430a-a8eb-9269aa1077f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjkzMTUsIm5iZiI6MTcyMDYyOTAxNSwicGF0aCI6Ii83OTc4MjY5Ni8zNDczMzYxODUtNGVmZWE2MjItMjE2Yy00MzBhLWE4ZWItOTI2OWFhMTA3N2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YTVhODVkMzllOGQxNjgyYTBiNWYxNWM3NjFiOTllMjQwM2VmMDg2Y2U5MjI4YmE2Y2IyZWZiMGFjYmYwZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.litAGHvj1Cfz4PoonzwRklAZhAhwqcR_0yZkYEu5_4o) ![螢幕擷取畫面 2024-07-10 165821](https://private-user-images.githubusercontent.com/79782696/347336237-1cf8cfa4-b773-4c70-846f-7950d5a08a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjkzMTUsIm5iZiI6MTcyMDYyOTAxNSwicGF0aCI6Ii83OTc4MjY5Ni8zNDczMzYyMzctMWNmOGNmYTQtYjc3My00YzcwLTg0NmYtNzk1MGQ1YTA4YTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ODIyM2EwYTdiMTJiZWM5ZjIxMjcxNTQ5NzUyZGIxOGZlMzQ4ZDk5NDVhMjYxMWRjYTFkODFiMDJlYWU4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uq37-N69Zdjc3aauqmmPNeqpss4HnXPaKahkn9_tDZw)

use the mask again to composite it over the image. 

The preview in the node uses the alpha channel and renders it transparent in the browser, the load image node, loads the image as rgb with no alpha, and the alpha is split to the mask.

**Comment by shawnington** [comment]
> > > > mask2image->preview
> > > 
> > > 
> > > Thank you very much for your response. According to your instructions, it should be done this way, but this only generates a black and white mask image. What I need is as shown in the image below, a mask drawn on the original image. As mentioned above, the mask is generated after drawing, but the completed mask does not appear on the original image. ![螢幕擷取畫面 2024-07-10 165705](https://private-user-images.githubusercontent.com/79782696/347336185-4efea622-216c-430a-a8eb-9269aa1077f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjkzMTUsIm5iZiI6MTcyMDYyOTAxNSwicGF0aCI6Ii83OTc4MjY5Ni8zNDczMzYxODUtNGVmZWE2MjItMjE2Yy00MzBhLWE4ZWItOTI2OWFhMTA3N2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YTVhODVkMzllOGQxNjgyYTBiNWYxNWM3NjFiOTllMjQwM2VmMDg2Y2U5MjI4YmE2Y2IyZWZiMGFjYmYwZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.litAGHvj1Cfz4PoonzwRklAZhAhwqcR_0yZkYEu5_4o) ![螢幕擷取畫面 2024-07-10 165821](https://private-user-images.githubusercontent.com/79782696/347336237-1cf8cfa4-b773-4c70-846f-7950d5a08a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjkzMTUsIm5iZiI6MTcyMDYyOTAxNSwicGF0aCI6Ii83OTc4MjY5Ni8zNDczMzYyMzctMWNmOGNmYTQtYjc3My00YzcwLTg0NmYtNzk1MGQ1YTA4YTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ODIyM2EwYTdiMTJiZWM5ZjIxMjcxNTQ5NzUyZGIxOGZlMzQ4ZDk5NDVhMjYxMWRjYTFkODFiMDJlYWU4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uq37-N69Zdjc3aauqmmPNeqpss4HnXPaKahkn9_tDZw)
> > 
> > 
> > use the mask again to composite it over the image.
> > The preview in the node uses the alpha channel and renders it transparent in the browser, the load image node, loads the image as rgb with no alpha, and the alpha is split to the mask. The image tensor does not have an alpha channel, matching the preview is not possible. However you can use nodes like porter-duff to do alpha based mixing functions.
> 
> Thank you very much for your response. According to your instructions, it should be done this way. Yes, I succeeded. Thank you very much. However, is there another way to solve this issue without using additional nodes to fix it? Although this does not affect the actual operation of ComfyUI, I still want to know where the problem occurs or which part of the code should be modified for a fix. Once again, thank you for taking the time to respond to my question. ![螢幕擷取畫面 2024-07-11 202510](https://private-user-images.githubusercontent.com/79782696/347816329-94e48fbd-5a04-483a-b771-1bac798fff5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDE0MjMsIm5iZiI6MTcyMDcwMTEyMywicGF0aCI6Ii83OTc4MjY5Ni8zNDc4MTYzMjktOTRlNDhmYmQtNWEwNC00ODNhLWI3NzEtMWJhYzc5OGZmZjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEyMzIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNGUyZWM4Yzk2YTE3YTk3NmExYTY1MzNjMTcwMWEwYWM3ZjZkNzcxOWI4M2M5MjY4YzE5M2FhMjBlYjEzYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.krVfgzE41nso8bRs7fu_kdfcs_r4r15YHb6SAjY62f8)

No, there is not another way, and there is nothing in the code that can be changed to make it not work like you are expecting. As I said the image tensor does not have an alpha channel, so the mask must be composited into the image tensor, if you want it there. 

This is expected behavior as the tensor is not an RGBA image.

**Comment by ltdrdata** [comment]
> > > > mask2image->preview
> > > 
> > > 
> > > Thank you very much for your response. According to your instructions, it should be done this way, but this only generates a black and white mask image. What I need is as shown in the image below, a mask drawn on the original image. As mentioned above, the mask is generated after drawing, but the completed mask does not appear on the original image. ![螢幕擷取畫面 2024-07-10 165705](https://private-user-images.githubusercontent.com/79782696/347336185-4efea622-216c-430a-a8eb-9269aa1077f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjkzMTUsIm5iZiI6MTcyMDYyOTAxNSwicGF0aCI6Ii83OTc4MjY5Ni8zNDczMzYxODUtNGVmZWE2MjItMjE2Yy00MzBhLWE4ZWItOTI2OWFhMTA3N2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YTVhODVkMzllOGQxNjgyYTBiNWYxNWM3NjFiOTllMjQwM2VmMDg2Y2U5MjI4YmE2Y2IyZWZiMGFjYmYwZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.litAGHvj1Cfz4PoonzwRklAZhAhwqcR_0yZkYEu5_4o) ![螢幕擷取畫面 2024-07-10 165821](https://private-user-images.githubusercontent.com/79782696/347336237-1cf8cfa4-b773-4c70-846f-7950d5a08a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjkzMTUsIm5iZiI6MTcyMDYyOTAxNSwicGF0aCI6Ii83OTc4MjY5Ni8zNDczMzYyMzctMWNmOGNmYTQtYjc3My00YzcwLTg0NmYtNzk1MGQ1YTA4YTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ODIyM2EwYTdiMTJiZWM5ZjIxMjcxNTQ5NzUyZGIxOGZlMzQ4ZDk5NDVhMjYxMWRjYTFkODFiMDJlYWU4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uq37-N69Zdjc3aauqmmPNeqpss4HnXPaKahkn9_tDZw)
> > 
> > 
> > use the mask again to composite it over the image.
> > The preview in the node uses the alpha channel and renders it transparent in the browser, the load image node, loads the image as rgb with no alpha, and the alpha is split to the mask. The image tensor does not have an alpha channel, matching the preview is not possible. However you can use nodes like porter-duff to do alpha based mixing functions.
> 
> Thank you very much for your response. According to your instructions, it should be done this way. Yes, I succeeded. Thank you very much. However, is there another way to solve this issue without using additional nodes to fix it? Although this does not affect the actual operation of ComfyUI, I still want to know where the problem occurs or which part of the code should be modified for a fix. Once again, thank you for taking the time to respond to my question. ![螢幕擷取畫面 2024-07-11 202510](https://private-user-images.githubusercontent.com/79782696/347816329-94e48fbd-5a04-483a-b771-1bac798fff5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDE1ODEsIm5iZiI6MTcyMDcwMTI4MSwicGF0aCI6Ii83OTc4MjY5Ni8zNDc4MTYzMjktOTRlNDhmYmQtNWEwNC00ODNhLWI3NzEtMWJhYzc5OGZmZjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEyMzQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOTFhMjZjOWMyZTY0YmNmMjcyNzAxODg4YmZkZGVkYmVmZmUyM2Q0YjY1YmU0MTczNjdlMTRlYWI2MDhiYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6bKO2RSDmA7AKkAlzpnXd0GaOFYnH4RKkJ7omIZnPSc)

In the `input/clipspace` directory, you can find a file named `clipspace-....`.
Rename the file to `masktest.png` and move it to the `ComfyUI/input` directory. 
After refreshing your browser, try selecting the `masktest.png` file in the LoadImage node.

How does it appear?

**Comment by Willy-Shenn** [comment]
> > > > > mask2image->preview
> > > > 
> > > > 
> > > > Thank you very much for your response. According to your instructions, it should be done this way, but this only generates a black and white mask image. What I need is as shown in the image below, a mask drawn on the original image. As mentioned above, the mask is generated after drawing, but the completed mask does not appear on the original image. ![螢幕擷取畫面 2024-07-10 165705](https://private-user-images.githubusercontent.com/79782696/347336185-4efea622-216c-430a-a8eb-9269aa1077f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjkzMTUsIm5iZiI6MTcyMDYyOTAxNSwicGF0aCI6Ii83OTc4MjY5Ni8zNDczMzYxODUtNGVmZWE2MjItMjE2Yy00MzBhLWE4ZWItOTI2OWFhMTA3N2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YTVhODVkMzllOGQxNjgyYTBiNWYxNWM3NjFiOTllMjQwM2VmMDg2Y2U5MjI4YmE2Y2IyZWZiMGFjYmYwZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.litAGHvj1Cfz4PoonzwRklAZhAhwqcR_0yZkYEu5_4o) ![螢幕擷取畫面 2024-07-10 165821](https://private-user-images.githubusercontent.com/79782696/347336237-1cf8cfa4-b773-4c70-846f-7950d5a08a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjkzMTUsIm5iZiI6MTcyMDYyOTAxNSwicGF0aCI6Ii83OTc4MjY5Ni8zNDczMzYyMzctMWNmOGNmYTQtYjc3My00YzcwLTg0NmYtNzk1MGQ1YTA4YTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ODIyM2EwYTdiMTJiZWM5ZjIxMjcxNTQ5NzUyZGIxOGZlMzQ4ZDk5NDVhMjYxMWRjYTFkODFiMDJlYWU4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uq37-N69Zdjc3aauqmmPNeqpss4HnXPaKahkn9_tDZw)
> > > 
> > > 
> > > use the mask again to composite it over the image.
> > > The preview in the node uses the alpha channel and renders it transparent in the browser, the load image node, loads the image as rgb with no alpha, and the alpha is split to the mask. The image tensor does not have an alpha channel, matching the preview is not possible. However you can use nodes like porter-duff to do alpha based mixing functions.
> > 
> > 
> > Thank you very much for your response. According to your instructions, it should be done this way. Yes, I succeeded. Thank you very much. However, is there another way to solve this issue without using additional nodes to fix it? Although this does not affect the actual operation of ComfyUI, I still want to know where the problem occurs or which part of the code should be modified for a fix. Once again, thank you for taking the time to respond to my question. ![螢幕擷取畫面 2024-07-11 202510](https://private-user-images.githubusercontent.com/79782696/347816329-94e48fbd-5a04-483a-b771-1bac798fff5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDE1ODEsIm5iZiI6MTcyMDcwMTI4MSwicGF0aCI6Ii83OTc4MjY5Ni8zNDc4MTYzMjktOTRlNDhmYmQtNWEwNC00ODNhLWI3NzEtMWJhYzc5OGZmZjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEyMzQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOTFhMjZjOWMyZTY0YmNmMjcyNzAxODg4YmZkZGVkYmVmZmUyM2Q0YjY1YmU0MTczNjdlMTRlYWI2MDhiYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6bKO2RSDmA7AKkAlzpnXd0GaOFYnH4RKkJ7omIZnPSc)
> 
> In the `input/clipspace` directory, you can find a file named `clipspace-....`. Rename the file to `masktest.png` and move it to the `ComfyUI/input` directory. After refreshing your browser, try selecting the `masktest.png` file in the LoadImage node.
> 
> How does it appear?

Thank you very much for your response. According to your instructions, the situation still appears to be the same. Here is the test image and the directory path.
![螢幕擷取畫面 2024-07-11 204910](https://github.com/comfyanonymous/ComfyUI/assets/79782696/2266b398-afd9-4752-9213-2bd3d7b7cba1)

**Comment by ltdrdata** [comment]
Disable all custom nodes. And restart and refresh brower.
Does the issue persist?

**Comment by Willy-Shenn** [comment]
Thank you very much for your guidance. The issue has been resolved, and I can successfully preview after removing all custom nodes. Should I now try debugging one node at a time?
![螢幕擷取畫面 2024-07-11 223721](https://github.com/comfyanonymous/ComfyUI/assets/79782696/d93161a4-0111-4a55-ae46-09c14b074bee)

**Comment by Willy-Shenn** [comment]
> Disable all custom nodes. And restart and refresh brower. Does the issue persist?

Thank you very much for your guidance. The issue has been resolved, and I can successfully preview after removing all custom nodes. Should I now try debugging one node at a time?

![螢幕擷取畫面 2024-07-11 223721](https://github.com/comfyanonymous/ComfyUI/assets/79782696/7ca74788-283c-46c5-9ef7-0a72df353b3b)

**Comment by ltdrdata** [comment]
> > Disable all custom nodes. And restart and refresh brower. Does the issue persist?
> 
> Thank you very much for your guidance. The issue has been resolved, and I can successfully preview after removing all custom nodes. Should I now try debugging one node at a time?
> 
> ![螢幕擷取畫面 2024-07-11 223721](https://private-user-images.githubusercontent.com/79782696/347866500-7ca74788-283c-46c5-9ef7-0a72df353b3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDkzOTUsIm5iZiI6MTcyMDcwOTA5NSwicGF0aCI6Ii83OTc4MjY5Ni8zNDc4NjY1MDAtN2NhNzQ3ODgtMjgzYy00NmM1LTllZjctMGE3MmRmMzUzYjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE0NDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNGY1OTk2M2VjNDg2YTYyOTUwZjNkZjMyN2U1Mjc1NzUyM2Y3ZGExYWNhY2FlNWFjMzZmNDI3N2VkNGQ0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hvpSBQFnAD7-QuHdd5kmSABKceEB5IFC1cWqEE71Meg)

unfortunately......

**Comment by Willy-Shenn** [comment]
> > > Disable all custom nodes. And restart and refresh brower. Does the issue persist?
> > 
> > 
> > Thank you very much for your guidance. The issue has been resolved, and I can successfully preview after removing all custom nodes. Should I now try debugging one node at a time?
> > ![螢幕擷取畫面 2024-07-11 223721](https://private-user-images.githubusercontent.com/79782696/347866500-7ca74788-283c-46c5-9ef7-0a72df353b3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDkzOTUsIm5iZiI6MTcyMDcwOTA5NSwicGF0aCI6Ii83OTc4MjY5Ni8zNDc4NjY1MDAtN2NhNzQ3ODgtMjgzYy00NmM1LTllZjctMGE3MmRmMzUzYjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE0NDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNGY1OTk2M2VjNDg2YTYyOTUwZjNkZjMyN2U1Mjc1NzUyM2Y3ZGExYWNhY2FlNWFjMzZmNDI3N2VkNGQ0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hvpSBQFnAD7-QuHdd5kmSABKceEB5IFC1cWqEE71Meg)
> 
> unfortunately......

I apologize for the confusion. After troubleshooting all the custom nodes one by one, everything is now working fine. All I did was move the custom nodes to another folder and then gradually put them back one by one. The issue is now resolved. I am truly grateful for both of your guidance and support.

Wishing you both continued success and all the best in your endeavors!

![螢幕擷取畫面 2024-07-11 225916](https://github.com/comfyanonymous/ComfyUI/assets/79782696/ddccdf02-72e0-4140-aba8-3859e01128f7)

**Comment by ltdrdata** [comment]
> I apologize for the confusion. After troubleshooting all the custom nodes one by one, everything is now working fine. All I did was move the custom nodes to another folder and then gradually put them back one by one. The issue is now resolved. I am truly grateful for both of your guidance and support.
> 
> Wishing you both continued success and all the best in your endeavors!

What node is the issue node?

**Comment by Willy-Shenn** [comment]
> > I apologize for the confusion. After troubleshooting all the custom nodes one by one, everything is now working fine. All I did was move the custom nodes to another folder and then gradually put them back one by one. The issue is now resolved. I am truly grateful for both of your guidance and support.
> > Wishing you both continued success and all the best in your endeavors!
> 
> What node is the issue node?

After removing all my custom nodes and restarting ComfyUI, I gradually put the nodes back into the custom node folder one by one. After completing this process and restarting, the masks can still be used normally as shown above. Therefore, there are no issues with any of the nodes currently. I am truly sorry for wasting your time on this matter, and I sincerely apologize and thank you for your help.

**Comment by ltdrdata** [comment]
> > > I apologize for the confusion. After troubleshooting all the custom nodes one by one, everything is now working fine. All I did was move the custom nodes to another folder and then gradually put them back one by one. The issue is now resolved. I am truly grateful for both of your guidance and support.
> > > Wishing you both continued success and all the best in your endeavors!
> > 
> > 
> > What node is the issue node?
> 
> After removing all my custom nodes and restarting ComfyUI, I gradually put the nodes back into the custom node folder one by one. After completing this process and restarting, the masks can still be used normally as shown above. Therefore, there are no issues with any of the nodes currently. I am truly sorry for wasting your time on this matter, and I sincerely apologize and thank you for your help.

There is a possibility of the import order sensitive issue.
