### ISSUE TITLE
希望凌乱的连线更加一目了然并且美观

### ISSUE THREAD

**Issue by zffffff** [comfyanonymous/ComfyUI#3990]
### Feature Idea

ComfyUI: 2349[8d3f97](2024-07-09)
Manager: V2.38.2
节点多的时候连线凌乱遮挡，链接不清晰的情况非常常见

### Existing Solutions

![image](https://github.com/comfyanonymous/ComfyUI/assets/21136110/8d30cc7d-43a5-4ed0-a4d5-f04fbffe0dc7)
勉强能够做到线路清晰但是不美观

**Comment by huchenlei** [comment]
There is a auto arrange feature provided by comfyui_custom_scripts. 
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/b0f21a3c13bac21068d1dcceb7c2d466167054b3/web/js/graphArrange.js#L4

![image](https://github.com/comfyanonymous/ComfyUI/assets/20929282/32456093-16e8-408b-9bbc-1f32fbd134de)

You can also use reroute node to reganize node connection.

**Comment by zffffff** [comment]
> There is a auto arrange feature provided by comfyui_custom_scripts. https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/b0f21a3c13bac21068d1dcceb7c2d466167054b3/web/js/graphArrange.js#L4
> 
> ![image](https://private-user-images.githubusercontent.com/20929282/347448681-32456093-16e8-408b-9bbc-1f32fbd134de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NTQwNjQsIm5iZiI6MTcyMTQ1Mzc2NCwicGF0aCI6Ii8yMDkyOTI4Mi8zNDc0NDg2ODEtMzI0NTYwOTMtMTZlOC00MDhiLTliYmMtMWYzMmZiZDEzNGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA1MzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NTI5OGM2ODIxZjBiMTRhOTMzMDRmODk0Njk3NjE2YWRmMjljY2M4YmZlOGU5ZjgyY2U3YzI2Mjg4MGVmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sonl557r--ZrSpzc6572--slFQOAsyjWwDLtxYQ1wKc)
> 
> You can also use reroute node to reganize node connection.

![image](https://github.com/user-attachments/assets/e5a8e8c9-2cc9-4427-99c9-1e62f793aff9)
![image](https://github.com/user-attachments/assets/f204b532-22e5-4e67-abb2-a6b7e71899e3)
阁下没有看懂我的意思，我说的不是整齐的那种美观，而是希望线条不要被遮挡，（线条不出现交叉似乎是不可能了）但还是希望能让人看清每个节点的来龙去脉，很多时候节点多了，自己都搞迷糊了，更不要说网上下载的别人的工作流，简直是个灾难
