### ISSUE TITLE
how to run with cloudflared with tunnel, cloudflared token, port, and certfile ?

### ISSUE THREAD

**Issue by mikebilly** [comfyanonymous/ComfyUI#3991]
### Your question

how to run with cloudflared with tunnel, cloudflared token, port, and certfile?, I want to tunnel using cloudflared

**Comment by mcmonkey4eva** [comment]
cloudflared has its own usage documentation https://github.com/cloudflare/cloudflared#cloudflare-tunnel-client

you just run it at the same time as comfy, pointed at port 8188
