### ISSUE TITLE
Copy/paste of nodes stopped working.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [comfyanonymous/ComfyUI#3995]
### Expected Behavior

Copy nodes (ctrl+c) and paste them (ctrl+v) in the same workflow, and to another tab.

### Actual Behavior

Until today I was able to select nodes(s), copy them (ctrl+c) and paste them (ctrl+v) in the same workflow, and even to another tab. I used it yesterday without any problem, I update every day and updated to commit 8d3f979b633dab9824c59bf8a06c748a533eec0b this morning. If I try to copy/paste now, I only paste the last node I copied yesterday, even if I right click a node and copy it to clipspace I get the same behaviour. I have tried in private browsing and another browser, but nothing is pasted. I can copy/paste text within nodes, but node nodes themselves.

https://github.com/comfyanonymous/ComfyUI/assets/52193044/35735e4f-dce2-4a92-a407-37fd877b1893

### Steps to Reproduce

Try copy pasting nodes with keyboard.

### Debug Logs

```powershell
There are no relating errors to show.
```

**Comment by huchenlei** [comment]
Can you add `--disable-all-custom-nodes` to your launch script and see if the issue persists? I cannot reproduce it locally.

**Comment by KookaFr** [comment]
Same pb for me.

**Comment by huchenlei** [comment]
`Ctrl + Shift + V` should paste with connections.

**Comment by KookaFr** [comment]
Only "an old one" is pasted. 
The copy function seems to be broken.

**Comment by GalaxyTimeMachine** [comment]
It does work without the custom nodes. I guess it's a case of enabling all 103 of them 1 at a time until it breaks again :(

**Comment by GalaxyTimeMachine** [comment]
Information for anyone else having the same problem...

I've resolved this by deleting the rgthree custom node folder and then reinstalling it via the manager. There must be some lingering old code in there that caused it.

**Comment by KookaFr** [comment]
Reinstalling rgthree nodes fixed the pb. Thank you.

**Comment by zhangleyan** [comment]
Yes, I had the same problem as Galaxy and KookaFr, uninstalling rgthree and then reinstalling rgthree solved it

**Comment by DrJKL** [comment]
Any idea what the root cause was?

**Comment by Aljnk** [comment]
My case - ComfyUI-Easy-Use - work after uninstall this node

**Comment by jimrhoskins** [comment]
I had this issue. I disabled all custom nodes, and still had the pasting issues.

I had the issue using Brave as the browser. When I tried it in Chrome it worked. I tried Brave in a private session, and the issue persisted.

It is weird, in that the copy/paste all worked for a while, and then when it stopped any time I would paste, it was some old selection. It seemed copying with ctrl-c or copy into clipspace in the menu would not actually update the clipspace. Maybe it is a browser related bug. I don't know how to trigger it.

**Comment by Sheng-Charles** [comment]
The same ComfyUI works fine in Edge, but Chrome cannot copy and paste, even with all nodes disabled

**Comment by ltdrdata** [comment]
> I had this issue. I disabled all custom nodes, and still had the pasting issues.
> 
> I had the issue using Brave as the browser. When I tried it in Chrome it worked. I tried Brave in a private session, and the issue persisted.
> 
> It is weird, in that the copy/paste all worked for a while, and then when it stopped any time I would paste, it was some old selection. It seemed copying with ctrl-c or copy into clipspace in the menu would not actually update the clipspace. Maybe it is a browser related bug. I don't know how to trigger it.

Copying to clipspace has a different meaning. This refers to copying the node's content to a special editable storage called Clipspace, not copying the node itself.

**Comment by shimmery1210** [comment]
I have similar issue. After I restore my Windows10, it suddenly cannot copy nodes in ComfyUI. copy and paste text works fine, but copy nodes doesn't work, I tried to copy content of .json file and paste in ComfyUI, it works. But then I copied some nodes and paste,  it pastes the same nodes from .json file. I even restore my OS again and try with brand new 0.3.14 comfyui, same problem. I guess it is because the function that copying nodes to clipboard is broken......

**Comment by karleong** [comment]
I tried update the entire comfyui through comfyui manager. the copy and paste works again after updating.

**Comment by McWh1sper** [comment]
> I have similar issue. After I restore my Windows10, it suddenly cannot copy nodes in ComfyUI. copy and paste text works fine, but copy nodes doesn't work, I tried to copy content of .json file and paste in ComfyUI, it works. But then I copied some nodes and paste, it pastes the same nodes from .json file. I even restore my OS again and try with brand new 0.3.14 comfyui, same problem. I guess it is because the function that copying nodes to clipboard is broken......

Faced the same problem with copy/paste. --disable-all-custom-nodes doesn't help. Then I tried update_comfyui_and_python_dependencies Batch at .\ComfyUI\update folder. All work fine now.

**Comment by DevCT001** [comment]
I had the same problem. It got fixed after I started ComfyUI with the latest frontend version (currently 1.10.4).
Start ComfyUI with --front-end-version Comfy-Org/ComfyUI_frontend@latest
I don't know if there is a fix in this frontend version, or just the change of frontend versions itself reset whatever was wrong.

**Comment by drgrib** [comment]
I switched from Chrome to Firefox to fix this without having to dig into config files.

**Comment by yash-711** [comment]
I reinstalled rgthree, didn't work then switching to Firefox worked for me.

**Comment by badpinkman** [comment]
Try again after enabling Caps Lock, it works for me.

**Comment by DreamerBY** [comment]
> Попробуйте еще раз, включив Caps Lock, мне это помогает.

THS

**Comment by Latentnaut** [comment]
> Try again after enabling Caps Lock, it works for me.

YOU ROCK!!!

**Comment by audovoice** [comment]
THE CAPSLOCK REALLY WORKS!
NOW i HAVE TO INTERNET SHOUT ALL THE TIME, BUT IT IS A PRICE i AM WILLING TO PAY!

**Comment by kanarch66** [comment]
CAPLOCK WORKS! HOW DID YOU FIND THIS OUT? AMAZING

**Comment by diefallen** [comment]
Got mine solved (some 50 custom-nodes via Brave-browser) after enabled CAPSLOCK then 'Ctrl+Shift+V' worked while common 'C+V' still not.

**Comment by by-ae** [comment]
Just piling on Capslock worked for me also.
I'm certain it's just a custom-node bug but this is such a simple workaround.

[Enable Capslock] Ctrl+C -> Ctrl+Shift+V
