### ISSUE TITLE
Run Code main.py not working in VSCode but is working in Smatrix

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#3997]
### Your question

Tried running server.py and main.py same error message.

### Logs

```powershell
## ComfyUI-Manager: installing dependencies. (GitPython)

[notice] A new release of pip is available: 24.0 -> 24.1.2[notice] To update, run: python.exe -m pip install --upgrade pip
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-10 17:37:18.385574       
** Platform: Windows
** Python version: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
** Python executable: C:\Omniscient\Python\Python310\python.exe
** Log path: W:\smatrix\Data\Packages\ComfyUI\comfyui.log 

Prestartup times for custom nodes:
  12.7 seconds: \\Newestgtx1650\18 tb\smatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "w:\smatrix\Data\Packages\ComfyUI\main.py", line 76, in <module>
    import execution
  File "w:\smatrix\Data\Packages\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "w:\smatrix\Data\Packages\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "w:\smatrix\Data\Packages\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "w:\smatrix\Data\Packages\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "w:\smatrix\Data\Packages\ComfyUI\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "w:\smatrix\Data\Packages\ComfyUI\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())      
  File "C:\Omniscient\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 674, in current_device       
    _lazy_init()
  File "C:\Omniscient\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by BrechtCorbeel** [comment]
I know it's a CUDA issue and I have to figure out how to get this to work, but it's an issue I encounter often with Torch and Tensorflow.

**Comment by mcmonkey4eva** [comment]
This issue is related to understanding the installation process, which smatrix has likely abstracted away from you - you'll want to install per the readme https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#installing or use an installer that keeps the underlying package paths clear (eg if you use Swarm, you still get the comfy native launch scripts out of the box inside)

**Comment by BrechtCorbeel** [comment]
> This issue is related to understanding the installation process, which smatrix has likely abstracted away from you - you'll want to install per the readme https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#installing or use an installer that keeps the underlying package paths clear (eg if you use Swarm, you still get the comfy native launch scripts out of the box inside)

Yes, but my installs are done, I have all the packages for both pytorch or tensorflow, but intermittently on certain projects I get this sort of error, which makes me believe I need to specify how to use the proper package and cuda, but all my environment variables are set and installed properly.

I'm going to try on another pc, but I am guessing I will once again get this error message.

**Comment by mcmonkey4eva** [comment]
There's a direct answer to "how to use the proper packages" with python commands, but I have no idea what it is in the context of smatrix.

For running comfy from the Releases tab or from a Swarm install, it's: open a terminal in the folder above ComfyUI, and type `python_embeded\python.exe -s ComfyUI\main.py`
