### ISSUE TITLE
ComfyUI portable:  python embeded version to python 3.10.11 instead please....

### ISSUE THREAD

**Issue by RGX650** [comfyanonymous/ComfyUI#4000]
### Your question

There is no Comfyui portable with Python 3.10

- Can it be uploaded?
- Or how can i do it myself properly?

Thanks

**Comment by huchenlei** [comment]
You can export the python environment from your portable python and reinstall them to any python environment you want to use , i.e. 3.10 or higher.

Export `pip freeze > requirements.txt`
Import `pip install -r requirements.txt`

Then change the python path in `run*.bat` to point to your new python environment
https://github.com/comfyanonymous/ComfyUI/blob/90389b3b8a69c08c3ed0bcc9d87a92246578a8e3/.ci/windows_base_files/run_nvidia_gpu.bat#L1C1-L2

**Comment by RGX650** [comment]
@huchenlei Thanks for your reply! However, i want to do something slighly different:

ComfyUI_portable_311 (original one with my installed packages)

ComfyUI_portable_310 (can i replace the python used in python_embeded with python310?)
i still want it embeded...

**Comment by ql0wn4** [comment]
> @huchenlei Thanks for your reply! However, i want to do something slighly different:
> 
> ComfyUI_portable_311 (original one with my installed packages)
> 
> ComfyUI_portable_310 (can i replace the python used in python_embeded with python310?) i still want it embeded...

I have the same issue, did you manage to solve it?

**Comment by ltdrdata** [comment]
If you can read shell scripts, this will be helpful.

The release of ComfyUI that includes python_embeded is generated like this.
https://github.com/comfyanonymous/ComfyUI/actions/runs/10729898373/workflow
