### ISSUE TITLE
AuraFlow safety checker

### ISSUE THREAD

**Issue by specblades** [comfyanonymous/ComfyUI#4007]
Hello! 
I played with the new model and got the following result. I went looking for the security checker module in the Comfyui repository, but couldn’t find it. Is it safety layer or? Help me out. And i cannot reproduce it dont know why.
Also, it is exactly the same image as Ideogram have when the safety check triggers. (https://www.reddit.com/r/StableDiffusion/comments/1b41ah5/psa_you_cannot_delete_images_from_ideogramai_when/)

![image](https://github.com/user-attachments/assets/4ad3353e-c7aa-4600-a54d-6e720f83d365)

**Comment by comfyanonymous** [comment]
There is no safety checker this is an issue with the model itself and how it was trained.
