### ISSUE TITLE
run signle node,control flow

### ISSUE THREAD

**Issue by YmStrip** [comfyanonymous/ComfyUI#4009]
### Feature Idea

support run single node(this might be api friendly)
support control flow,it seems that trigger is implement here, but why is there no logic node,example loop?

### Existing Solutions

control flow example,if,for,implement it on electron , litegraph

https://github.com/user-attachments/assets/897749e2-d27d-4756-9875-b9e07449d8b6

**Comment by ltdrdata** [comment]
Current workflow execution of ComfyUI has a limitation.
Loop feature will be enabled via this PR https://github.com/comfyanonymous/ComfyUI/pull/2666
