### ISSUE TITLE
JAVA PROBLEMS? NOT working right-click on image preview to SAVE & other

### ISSUE THREAD

**Issue by Maelstrom2014** [comfyanonymous/ComfyUI#4015]
### Expected Behavior

JAVA PROBLEMS? 

1) NOT working right-click on image preview to SAVE
2) NOT working outputs from text nodes 
3) NOT working SHOW ANY and SHOW TENSOR SHAPE - for debugging workflows

tryed:
1) Chrome, firefox, cent browser, EDGE

### Actual Behavior

nothing to show

### Steps to Reproduce

dont know

### Debug Logs

```powershell
output (if supported in nodes) is ok.
```

**Comment by ltdrdata** [comment]
First, if you are using custom nodes, disable all custom nodes, restart, then refresh the browser and test again.
If the issue still occurs, press F12 in Chrome to open the console and show me the logs.

**Comment by Maelstrom2014** [comment]
> First, if you are using custom nodes, disable all custom nodes, restart, then refresh the browser and test again. If the issue still occurs, press F12 in Chrome to open the console and show me the logs.

thanx for plan!
I found fist rotten apple custom node: 
Jovimetrix 
https://github.com/Amorano/Jovimetrix

It disables right-click save image on preview. And I'm sure something else. WHATS NEXT STEP?
Second BUGGISH custom node i'm in process of finding....

**Comment by mcmonkey4eva** [comment]
Should probably open an issue on the github for jovimetrix

cc @Amorano

**Comment by Maelstrom2014** [comment]
SECOND BUGGET NODE: DEEPFUZE
https://github.com/SamKhoze/ComfyUI-DeepFuze/

It somehow disable all outputs (text for sure) from nodes.
Tried delete and reinstall, not change.

![image](https://github.com/user-attachments/assets/ff858bc7-d3d2-4a3e-9150-1d157d359543)

**Comment by Amorano** [comment]
> > First, if you are using custom nodes, disable all custom nodes, restart, then refresh the browser and test again. If the issue still occurs, press F12 in Chrome to open the console and show me the logs.
> 
> thanx for plan! I found fist rotten apple custom node: Jovimetrix https://github.com/Amorano/Jovimetrix
> 
> It disables right-click save image on preview. And I'm sure something else. WHATS NEXT STEP? Second BUGGISH custom node i'm in process of finding....

So the first part of that is not correct. I dont disable any functions in the core of comfy, only add. 

If something is bugged, please post a proper workflow with the problem so I can investigate. Please feel free to do that on the issue you started where you didnt post anything.

Cheers.
