### ISSUE TITLE
first image and image to image doesn't display image correctly

### ISSUE THREAD

**Issue by Creative-comfyUI** [comfyanonymous/ComfyUI#4016]
### Expected Behavior

The first image of a batch size or the image to image should be a clear and well define image 

### Actual Behavior

The first image of batch size  1 and batch size 2  is not clear and not well defined 
The bug disapeared with batch size superior or equal to 3 

### Steps to Reproduce

![Screenshot 2024-07-13 at 7 09 40 PM](https://github.com/user-attachments/assets/f9164cf5-5536-4a00-b095-859fb4bfb33c)
![Screenshot 2024-07-13 at 7 14 11 PM](https://github.com/user-attachments/assets/d46fd75f-0630-410f-acca-e1b1c01f9b55)
![Screenshot 2024-07-13 at 7 08 26 PM](https://github.com/user-attachments/assets/66564c16-3799-4e36-853b-fac39fb8e1aa)

![workflowBug](https://github.com/user-attachments/assets/86d81595-1ac8-4639-aa33-0b8c1ae2f4ac)
![workflowBug_img](https://github.com/user-attachments/assets/929580e2-7f2e-4efe-b42b-ca61b5038130)

### Debug Logs

```powershell
Last login: Sun Jul 14 17:37:06 on ttys000
ComfyUI % python3 main.py --disable-all-custom-nodes
Total VRAM 16384 MB, total RAM 16384 MB
pytorch version: 2.3.0.dev20240304
Set vram state to: SHARED
Device: mps
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type EPS
Using split attention in VAE
Using split attention in VAE
Requested to load SD1ClipModel
Loading 1 new model
Requested to load BaseModel
Loading 1 new model
100%|███████████████████████████████████████████| 20/20 [00:47<00:00,  2.39s/it]
Requested to load AutoencoderKL
Loading 1 new model
```

### Other

This bug is what is called a progressive bug. 

The first bug was black screen, after this was repaired and comfyUI updated, the problem start to look like the one I describe but instead of having not well defined image it was coloured image. With the latest update I start having this not well defined image instead of the colour one.

**Comment by huchenlei** [comment]
Is there any special setup required for this bug? I cannot reproduce this locally.

**Comment by Creative-comfyUI** [comment]
There is no specific configuration. I disable all nodes and use the default workflow to be sure that the problem is not from other nodes or extension without success. 

What I can see is that the way the ksampler manages the information is the problem. Is it possible that it is a script corruption?  This has been my intuition since the beginning.  

I tried changing the scheduler. The problem is solved for SD and SDXL only when I use ddmi_uniform with other scheduler the bug is still there. It seems that the bug come from the scheduler, why with the first image batch size 1 and 2 and not 3, that it is the mystery 

![Screenshot 2024-07-14 at 11 18 58 PM](https://github.com/user-attachments/assets/9087e3bc-dc0f-4815-bf98-b57ebbd6187f)

**Comment by Creative-comfyUI** [comment]
Yes my environment is mac OS

**Comment by ltdrdata** [comment]
Then this appears to be an issue caused by the Sonoma update for macOS.
https://github.com/comfyanonymous/ComfyUI/issues/3186
https://github.com/comfyanonymous/ComfyUI/issues/3346

Update pytorch to the latest version and try again.

**Comment by Creative-comfyUI** [comment]
Fantastic, It solves the problem. Thank you for your support.
