### ISSUE TITLE
How to delete a generated image?

### ISSUE THREAD

**Issue by mohit-kapadia-at-lirisoft** [comfyanonymous/ComfyUI#4021]
### Expected Behavior

Is there a way we can delete the generated image. I have the file name to delete post image creation. I don't want my storage to get filled and do manual clean up.

### Actual Behavior

There should be an API to delete, like /view, /history etc.

### Steps to Reproduce

NA

### Debug Logs

```powershell
NA
```

**Comment by ltdrdata** [comment]
First of all, this is not a bug but very much intended behavior.

And your intention is unclear. If you use `Preview Image`, it will be saved in the temp folder and automatically deleted on the next startup.

However, your question seems to suggest that you want to manually control image deletion through an API.

**Comment by crystalwizard** [comment]
is it hard to just go to the output folder and delete the images in it?

**Comment by injet-zhou** [comment]
My custom node, [comfyui_extra_api](https://github.com/injet-zhou/comfyui_extra_api), provides APIs to retrieve and delete all the output images. Feel free to give it a try
