### ISSUE TITLE
A faster Preview Image node?

### ISSUE THREAD

**Issue by liusida** [comfyanonymous/ComfyUI#4022]
### Feature Idea

Currently, the image is displayed only after the whole image has been loaded, while some other plugins display the image progressively.

Here is an extreme example, where I've captured a screenshot right before the image is displayed in the 'Preview Image' node:

![image](https://github.com/user-attachments/assets/66559236-d83b-4514-a0a2-503f420c049a)

While using blob can make this preview faster, showing an incomplete image while downloading, but the logic of the built-in preview node is not that easy to understand. So maybe someone can take a look at it. Thanks.

**Comment by ltdrdata** [comment]
If the goal is simply to increase the preview speed, this method exists.

![image](https://github.com/user-attachments/assets/43e0bedb-4a91-48dd-ade0-83a1c409f225)

**Comment by mcmonkey4eva** [comment]
frontend issue https://github.com/Comfy-Org/ComfyUI_frontend
