### ISSUE TITLE
more responsive async queue prompt button

### ISSUE THREAD

**Issue by mcandre** [comfyanonymous/ComfyUI#4024]
### Expected Behavior

The frontend should continue operating seamlessly when rapidly pressing the Queue Prompt button several times.

The frontend should immediately place new items in the dedicated pending section, and then send the network signals to the ComfyUI server asynchronously, in the background.

### Actual Behavior

The frontend freezes until 100% of the prompts are sent to the ComfyUI server.

### Steps to Reproduce

Rapidly click the Queue Prompt button twenty times.

### Debug Logs

```powershell
.
```

**Comment by huchenlei** [comment]
Moved to frontend repo.
