### ISSUE TITLE
Optional number of Queue Prompt copies

### ISSUE THREAD

**Issue by mcandre** [comfyanonymous/ComfyUI#4025]
### Feature Idea

Would love a box to specify a number of copies to apply to a single Queue Prompt click. By default, 1 total queued item.

Note that this is distinct from the number of images in a work item. For example, you can't specify 1000000 images within a single ComfyUI work item. So there is a need to be able to conveniently queue many separate work items, without having to click the Queue Prompt button a million times.

### Existing Solutions

An advanced user could theoretically script a for loop with successive HTTP requests to the ComfyUI frontend or backend servers. The REST API is convoluted, however, requiring low level details of the JSON workflow.

**Comment by ltdrdata** [comment]
Do you meaning this?
![image](https://github.com/user-attachments/assets/b5cf320f-cc02-4f5a-b091-dc10a5e76162)

And if you set `On change` it will generate infinitely.

**Comment by SlayerHKSHIN** [comment]
I would love this feature

**Comment by mcandre** [comment]
Confirmed, ltdrdata. Thank you for pointing this out!

Separately would like to persist this value. It seems to reset each time I refresh the page. It's not faithfully restoring when I save and load workflow.json files.
