### ISSUE TITLE
cuda and GPU version

### ISSUE THREAD

**Issue by Qiuhao-Wu** [comfyanonymous/ComfyUI#4031]
### Your question

I have one nvidia GPU GTX1660ti, which support cuda 10.1, 10.2, 11.4
I want to know, whether this GPU can run_gpu.bat.
cuda12.1 is must needed??????????

**Comment by mcmonkey4eva** [comment]
yes a GTX 1660 Ti should work, albeit not well nor fast. It's missing key optimizations (eg fp16) that more modern cards take advantage of. Just search `1660` in the issues page and you'll see posts from 1660 users.

Worst case you might need to manually install an older version of torch.

**Comment by Qiuhao-Wu** [comment]
RuntimeError: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
======================================================================
========================================================================
when i use gtx1660ti cuda 10.2，i meet this problem

**Comment by theseriouscoder1** [comment]
@Qiuhao-Wu did you solve this issue am facing the same one?
