### ISSUE TITLE
More scalable LoRA UI

### ISSUE THREAD

**Issue by mcandre** [comfyanonymous/ComfyUI#4036]
### Feature Idea

Provide a node with a multiselect checkbox list of multiple LoRA's.

Initialization defaults to lexicographic order. 

If LoRA order is significant, then we can later introduce the ability for users to reorder the LoRA list. Newly discovered LoRA's append to the list.

### Existing Solutions

Painstakingly wire together dozens of LoRA's.

**Comment by ltdrdata** [comment]
Several solutions already exist through custom nodes.

lora stacker - eifficiency nodes, tiny terra nodes
Impact Wildcard Encode, Wildcard Encode, Prompt Control - impact/inspire pack, comfyui-prompt control

**Comment by JorgeR81** [comment]
You can also try the rghree node suite. 
It also allows to reorder the loras. 
https://github.com/rgthree/rgthree-comfy?tab=readme-ov-file#power-lora-loader

**Comment by JorgeR81** [comment]
If you decide to have a lora stacker as default in Comfy UI, you could also consider a similar node to merge / stack models. 
I suggested the idea to rgthree a while ago, although he hasn't looked into that yet.
https://github.com/rgthree/rgthree-comfy/issues/195

**Comment by huchenlei** [comment]
I am going to close this if there is existing solution for the problem. Feel free to open another issue if the existing solutions don't work.
