### ISSUE TITLE
Error using the new [ SetUnionControlNetType ] node

### ISSUE THREAD

**Issue by JorgeR81** [comfyanonymous/ComfyUI#4040]
### Expected Behavior

The [ SetUnionControlNetType ] node works correctly with the new Union ControlNet model, on Windows 10. 

### Actual Behavior

When using the new [ SetUnionControlNetType ] node I have an error at the KSamper stage. 

### Steps to Reproduce

Just add the new node after the [ ControlNetLoader ] node, using the Union ControlNet model.

### Debug Logs

```powershell
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`
```

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/281ad42df4fae74ed11c1e7ff14cff6b7db6498c

Should be fixed now.
