### ISSUE TITLE
Is there an official workflow example of the built-in photomaker node?

### ISSUE THREAD

**Issue by kawaii2020** [comfyanonymous/ComfyUI#4047]
### Your question

https://github.com/comfyanonymous/ComfyUI/commit/d1533d9c0f1dde192f738ef1b745b15f49f41e02

**Comment by huchenlei** [comment]
The photomaker node is not built-in. Please file issue in the custom node repo instead. Thanks!

**Comment by huchenlei** [comment]
https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus

**Comment by kawaii2020** [comment]
On the node page, it says 
![image](https://github.com/user-attachments/assets/43856290-0b16-40eb-986e-798d92fc3d81)

**Comment by ltdrdata** [comment]
![photomaker](https://github.com/user-attachments/assets/fb7eb71e-b43f-46c6-8d4a-0d152fd4604b)

There is no official example.
But you can use this workflow.
