### ISSUE TITLE
Why is there a 6-Second Delay for the First Image When Switching Workflows, Even with the Same Model?

### ISSUE THREAD

**Issue by menahem121** [comfyanonymous/ComfyUI#4053]
### Your question

Hi,

I’m trying to use ComfyUI as a server API for my app. After completing all my workflows, I wanted to do a final check to ensure they were all working correctly. I noticed that when loading a new workflow, the first image takes three times longer to generate (9 seconds instead of 3 seconds), even though I’m always using the same model. This happens consistently, even with the most basic workflows like text2img and img2img.

This is a significant issue for me because my app frequently switches between workflows, and I can’t afford to lose 6 seconds each time.

I’ve also tried using the –highvram option, but the problem persists.

I would appreciate any help or advice thanks in advance

### Logs

First generation load the model
Second one is the same workflow
Third one is the same model but another basic similar workflow
Last one is also the same model but with the workflow of the first and second ones

model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Requested to load SDXLClipModel
Loading 1 new model
Requested to load AutoencoderKL
Loading 1 new model
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.40it/s]
Prompt executed in 57.66 seconds
got prompt
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.62it/s]
Prompt executed in 2.98 seconds
got prompt
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Requested to load SDXLClipModel
Loading 1 new model
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.61it/s]
Requested to load AutoencoderKL
Loading 1 new model
Prompt executed in 8.84 seconds
got prompt
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Requested to load SDXLClipModel
Loading 1 new model
Requested to load AutoencoderKL
Loading 1 new model
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.60it/s]
Prompt executed in 8.10 seconds

**Comment by mcmonkey4eva** [comment]
What might be hitting you here is that the current caching system is sensitive to _node id_.

For example, in [Swarm](https://github.com/mcmonkeyprojects/SwarmUI)'s workflow generator, I intentionally always generate that `CheckpointLoaderSimple` has node id `4`, to ensure that the model always grab from cache.
I have an entire table of reserved node IDs for this: https://github.com/mcmonkeyprojects/SwarmUI/blob/master/src/BuiltinExtensions/ComfyUIBackend/WorkflowGeneratorSteps.cs#L25

For automated usages on a controlled service, you can match this.

Beyond that -- there's an ongoing discussion about core Comfy upgrades right now, and one of the key ones a lot of us agree on is the need for better caching control for advanced usages like this.

**Comment by menahem121** [comment]
> What might be hitting you here is that the current caching system is sensitive to _node id_.
> 
> 
> 
> For example, in [Swarm](https://github.com/mcmonkeyprojects/SwarmUI)'s workflow generator, I intentionally always generate that `CheckpointLoaderSimple` has node id `4`, to ensure that the model always grab from cache.
> 
> I have an entire table of reserved node IDs for this: https://github.com/mcmonkeyprojects/SwarmUI/blob/master/src/BuiltinExtensions/ComfyUIBackend/WorkflowGeneratorSteps.cs#L25
> 
> 
> 
> For automated usages on a controlled service, you can match this.
> 
> 
> 
> Beyond that -- there's an ongoing discussion about core Comfy upgrades right now, and one of the key ones a lot of us agree on is the need for better caching control for advanced usages like this.

Thank you for your answer its really helpful 🙏

Ii there a way to set node ID straight in comfyUI ? I never used swarm and i dont know if can be used for serving deployment

**Comment by ltdrdata** [comment]
> > What might be hitting you here is that the current caching system is sensitive to _node id_.
> > For example, in [Swarm](https://github.com/mcmonkeyprojects/SwarmUI)'s workflow generator, I intentionally always generate that `CheckpointLoaderSimple` has node id `4`, to ensure that the model always grab from cache.
> > I have an entire table of reserved node IDs for this: https://github.com/mcmonkeyprojects/SwarmUI/blob/master/src/BuiltinExtensions/ComfyUIBackend/WorkflowGeneratorSteps.cs#L25
> > For automated usages on a controlled service, you can match this.
> > Beyond that -- there's an ongoing discussion about core Comfy upgrades right now, and one of the key ones a lot of us agree on is the need for better caching control for advanced usages like this.
> 
> Thank you for your answer its really helpful 🙏
> 
> Is there a way to set node ID straight in comfyUI ? I never used swarm and i dont know if it can be used for serving deployment
> 
> Also you are saying you are setting the same id for the checkpoint loaded but you are not mentioning the other nodes, so i have two questions about this:
> 
> 1. Is keeping the id of a node will work only if all the nodes before him are exactly the same in the same order?
> 2. Is there any time benefits of using the same node id for small nodes such as clip text, blur mask etc.. ? Or the time to load them is not significant?

You can't unless you edit workflow json.
But you can utilize Inspire Pack's backend cache nodes.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/cache-workflow1.png

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/cache-workflow2.png

![image](https://github.com/user-attachments/assets/7385ee0f-4bea-4c1c-afdb-5a364c8d2c86)

**Comment by menahem121** [comment]
> > > What might be hitting you here is that the current caching system is sensitive to _node id_.
> > > For example, in [Swarm](https://github.com/mcmonkeyprojects/SwarmUI)'s workflow generator, I intentionally always generate that `CheckpointLoaderSimple` has node id `4`, to ensure that the model always grab from cache.
> > > I have an entire table of reserved node IDs for this: https://github.com/mcmonkeyprojects/SwarmUI/blob/master/src/BuiltinExtensions/ComfyUIBackend/WorkflowGeneratorSteps.cs#L25
> > > For automated usages on a controlled service, you can match this.
> > > Beyond that -- there's an ongoing discussion about core Comfy upgrades right now, and one of the key ones a lot of us agree on is the need for better caching control for advanced usages like this.
> > 
> > 
> > Thank you for your answer its really helpful 🙏
> > Is there a way to set node ID straight in comfyUI ? I never used swarm and i dont know if it can be used for serving deployment
> > Also you are saying you are setting the same id for the checkpoint loaded but you are not mentioning the other nodes, so i have two questions about this:
> > 
> > 1. Is keeping the id of a node will work only if all the nodes before him are exactly the same in the same order?
> > 2. Is there any time benefits of using the same node id for small nodes such as clip text, blur mask etc.. ? Or the time to load them is not significant?
> 
> You can't unless you edit workflow json via text editor. But you can utilize Inspire Pack's backend cache nodes.
> 
> https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/cache-workflow1.png
> 
> https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/cache-workflow2.png
> 
> ![image](https://private-user-images.githubusercontent.com/128333288/350428264-7385ee0f-4bea-4c1c-afdb-5a364c8d2c86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NTIxMTEsIm5iZiI6MTcyMTU1MTgxMSwicGF0aCI6Ii8xMjgzMzMyODgvMzUwNDI4MjY0LTczODVlZTBmLTRiZWEtNGMxYy1hZmRiLTVhMzY0YzhkMmM4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQwODUwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDAzYTVlNDA2ODM1MThjZGNiZjNmYmRiNWRlMTI3MzJiMjA2YzdjNDcxM2EwMTU0ZjA0YjY1YzJhNGFkNGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wWvoizewYjhDC1ctJLY-W-_W-Nhc7mIU9gmKy-70anI)

it worked thank you!
