### ISSUE TITLE
error cliptxetencode

### ISSUE THREAD

**Issue by Zsy2024** [comfyanonymous/ComfyUI#4056]
### Expected Behavior

Generate images

### Actual Behavior

<img width="1060" alt="Snipaste_2024-07-19_11-18-45" src="https://github.com/user-attachments/assets/976a01e9-5fcc-42ab-8fce-1d7b18ce6e98">
hello!After I clicked on the picture, it popped up for me what this means?

### Steps to Reproduce

Not use custom nodes just use default node

### Debug Logs

```powershell
.
```

**Comment by mcmonkey4eva** [comment]
you added a cliploader node, but you used the model's CLIP instead of the cliploader's CLIP - presumably that's a model without CLIP, which is why you have the separate cliploader
