### ISSUE TITLE
When you click Show Image Feed from the new menu, the new menu will disappear.

### ISSUE THREAD

**Issue by wencxxxxxx** [comfyanonymous/ComfyUI#4059]
### Expected Behavior

.

### Actual Behavior

When you click Show Image Feed from the new menu, the new menu will disappear.
![cd4af7ec-5d2d-4cc4-9ab5-8dca2e68dce7](https://github.com/user-attachments/assets/010be67b-3d2c-47c9-9eda-f8c047226f85)

### Steps to Reproduce

.

### Debug Logs

```powershell
.
```

**Comment by wencxxxxxx** [comment]
Why not make it a core feature? It is very convenient for browsing pictures.

**Comment by ltdrdata** [comment]
> Why not make it a core feature? It is very convenient for browsing pictures.

There's a difference between what's convenient and what's essential. Some people dislike that feature because it takes up space.
