### ISSUE TITLE
can you add some nodes to support using the kolors model more natively？

### ISSUE THREAD

**Issue by hexiaoyu946** [comfyanonymous/ComfyUI#4064]
### Feature Idea

Dear developer, can you add some nodes to support using the kolors model more natively，thank you very much！
https://huggingface.co/Kwai-Kolors/Kolors

### Existing Solutions

1、https://github.com/kijai/ComfyUI-KwaiKolorsWrapper
2、https://github.com/MinusZoneAI/ComfyUI-Kolors-MZ?tab=readme-ov-file

**Comment by robinjhuang** [comment]
Consolidating Kolors feature support in https://github.com/comfyanonymous/ComfyUI/issues/4113
