### ISSUE TITLE
Can't load any safetensors

### ISSUE THREAD

**Issue by chuhang** [comfyanonymous/ComfyUI#4067]
I can load ckpt files, but whenever the model is a safetensor file I got this:

Error occurred when executing LoraLoader:

No such device (os error 19)

File "/home/ubuntu/comfyui/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/comfyui/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/comfyui/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/comfyui/ComfyUI/nodes.py", line 611, in load_lora
lora = comfy.utils.load_torch_file(lora_path, safe_load=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/comfyui/ComfyUI/comfy/utils.py", line 15, in load_torch_file
sd = safetensors.torch.load_file(ckpt, device=device.type)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/anaconda3/lib/python3.12/site-packages/safetensors/torch.py", line 308, in load_file
with safe_open(filename, framework="pt", device=device) as f:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by ltdrdata** [comment]
What is your GPU?

**Comment by FawazKadem** [comment]
+1 with cloud hosted instance. My GPU is a Nvidia A10 with 24gb vram

I'm not able to find the exact issue for some hopefully helpful observations.

Seems issue is here.
```
def load_torch_file(ckpt, safe_load=False, device=None):
    if device is None:
        device = torch.device("cpu")
    if ckpt.lower().endswith(".safetensors") or ckpt.lower().endswith(".sft"):
        sd = safetensors.torch.load_file(ckpt, device=device.type)
    else:
        if safe_load:
            if not 'weights_only' in torch.load.__code__.co_varnames:
                logging.warning("Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.")
                safe_load = False
        if safe_load:
            pl_sd = torch.load(ckpt, map_location=device, weights_only=True)
        else:
            pl_sd = torch.load(ckpt, map_location=device, pickle_module=comfy.checkpoint_pickle)
        if "global_step" in pl_sd:
            logging.debug(f"Global Step: {pl_sd['global_step']}")
        if "state_dict" in pl_sd:
            sd = pl_sd["state_dict"]
        else:
            sd = pl_sd
    return sd
```

When load_file is called from load_checkpoint_guess_config, device type is always None:

```
def load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, output_clipvision=False, embedding_directory=None, output_model=True):
    sd = comfy.utils.load_torch_file(ckpt_path)
 ```
 
 I'm not sure if that's expected, but safetensors.torch.load_file() will always be called with device being None. Therefore device.type won't work. Could definitely be something I'm missing as I'm not an expert. Really appreciate all the work put into this project btw.

**Comment by ltdrdata** [comment]
https://github.com/huggingface/diffusers/issues/3258#issuecomment-2248483847

I think you need to reinstall python environment.

**Comment by FawazKadem** [comment]
This solved it. Thank you
