### ISSUE TITLE
SetUnionContolNetType: Tile crashing

### ISSUE THREAD

**Issue by robertvoy** [comfyanonymous/ComfyUI#4068]
### Expected Behavior

The tile ControlNet to work without crashing.

### Actual Behavior

When I set it to Tile it crashes, but the other ones work fine. Didn't test all of them though.

![firefox_0CUTngEvWQ](https://github.com/user-attachments/assets/df842c02-db19-41fc-ab6e-97295712646a)

When i say crashes this is the console:

> Loading 1 new model
> Prompt executed in 46.42 seconds
> got prompt
>   0%|                                                                                            | 0/8 [00:00<?, ?it/s]
> E:\ComfyUI>pause
> Press any key to continue . . .

### Steps to Reproduce

See above

### Debug Logs

```powershell
> Loading 1 new model
> Prompt executed in 46.42 seconds
> got prompt
>   0%|                                                                                            | 0/8 [00:00<?, ?it/s]
> E:\ComfyUI>pause
> Press any key to continue . . .
```

**Comment by huchenlei** [comment]
You need the ProMax model for Tile and Inpaint control type.

**Comment by huchenlei** [comment]
https://huggingface.co/xinsir/controlnet-union-sdxl-1.0/tree/main

![image](https://github.com/user-attachments/assets/0b65b8ce-8dab-4f1d-8260-736bd295345e)
