### ISSUE TITLE
Reinstalling comfyUI does not start

### ISSUE THREAD

**Issue by chenzaitian306** [comfyanonymous/ComfyUI#4071]
### Your question

After I deleted the original comfyUI project, re-pulled comfyUI and installed the dependency. It won't start properly and is stuck at the Using pytorch cross attention step. I tested three versions: Release v0.0.1, Release v0.0.2, ComfyUI_windows_portable_nightly_pytorch

### Logs

```powershell
D:\ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch\ComfyUI_windows_portable_nightly_pytorch>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 10239 MB, total RAM 65345 MB
pytorch version: 2.5.0.dev20240720+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using pytorch cross attention
```

### Other

I had the same problem with both webUI and ForgeUI.

**Comment by marianbasti** [comment]
Same over here, without any custom nodes

**Comment by marianbasti** [comment]
Was using pytorch nightly 2.5.0, downgraded to 2.3.1
Still not launching, stuck on `Using pytorch cross attention`, no error message or resource usage

**Comment by marianbasti** [comment]
Did a git pull in the repo directory, it now works  🦆

**Comment by ltdrdata** [comment]
> Was using pytorch nightly 2.5.0, downgraded to 2.3.1 Still not launching, stuck on `Using pytorch cross attention`, no error message or resource usage
> 
> Running on CPU has the same result, getting stuck on `Using sub quadratic optimization for cross attention`
> 
> Edit: downgrading to torch 2.0.0 hasn't worked either, must be something else?

CPU mode doesn't work, too?

It's clear that this is not a pytorch issue.
If the problem occurs on CPU as well, it's not related to GPU drivers either.
Have you tried this with different model files?

It seems necessary to also check if reading the model files from storage is working correctly.

**Comment by marianbasti** [comment]
On CPU it works.

Updated Nvidia drivers to 560.70 (windows) and now inference works

Thanks for your support!

**Comment by chenzaitian306** [comment]
I upgraded the graphics card driver to 560.70 (windows)  and it still can't run. 
At the same time, I also can't run it in CPU mode.

**Comment by marianbasti** [comment]
> I upgraded Nvidia drivers to 560.70 (windows) and it still can't run. At the same time, I also can't run it in CPU mode.

Is it still stuck on 'Using pytorch cross attention' ? Have you tried pulling the last update?

**Comment by chenzaitian306** [comment]
I pulled the latest resources,  it still stuck on 'Using pytorch cross attention'.
I found that webUI and forgeUI would stop at the create UI step.

**Comment by chenzaitian306** [comment]
When I use cpu mode, it also stops at the same place:
`D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --cpu --use-split-cross-attention
Total VRAM 65345 MB, total RAM 65345 MB
pytorch version: 2.3.1+cu121
Set vram state to: DISABLED
Device: cpu
Using split optimization for cross attention`

**Comment by chenzaitian306** [comment]
An error will be prompted in the nightly environment：
`D:\ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch\ComfyUI_windows_portable_nightly_pytorch>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 10239 MB, total RAM 65345 MB
pytorch version: 2.5.0.dev20240711+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using pytorch cross attention
D:\ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\comfy\extra_samplers\uni_pc.py:18: SyntaxWarning: invalid escape sequence '\h'
  """Create a wrapper class for the forward SDE (VP type).`

**Comment by chenzaitian306** [comment]
The problem was caused by the firewall settings. I reset the firewall and solved the problem.
