### ISSUE TITLE
Mouse drag threshold is needed to avoid unintentional value change when clicking on numeric value input slider

### ISSUE THREAD

**Issue by tajino** [comfyanonymous/ComfyUI#4074]
### Feature Idea

Currently in ComfyUI, mouse down with a 1 pixel move is considered as a mouse drag action, this causes unintentional mouse drag action for example unintentional value change when clicking on a value slider if the mouse down is not precise enough with zero pixel move. This is especially difficult to avoid when using a tablet input device such as a Wacom tablet.

I would suggest to have a mouse drag threshold implemented, which can be defaulted to 3 pixels mouse down movement before the mousedown is considered as a mouse drag action. The drag threshold value in pixels should be exposed to user in the Settings panel.

Hope to see this implemented. Thanks.

**Comment by huchenlei** [comment]
The legacy js frontend will be deprecated soon. Please consider file the issue to https://github.com/Comfy-Org/ComfyUI_frontend. Thanks! Issue moved.
