### ISSUE TITLE
Comfy Colab upscale missing plugins

### ISSUE THREAD

**Issue by VisualizersImages** [comfyanonymous/ComfyUI#4080]
### Your question

I have tried to use the ERSGAN Ultrasharp4x model in google colab, but all I can't find any active option to use it.
I need a type of upscale by model and a load model

![Comfy error](https://github.com/user-attachments/assets/8d5c813a-d303-432f-9e99-e569939bfae3)
![Comfy models](https://github.com/user-attachments/assets/608e3463-6d21-4c2a-899a-e9439d3eccf5)

**Comment by ltdrdata** [comment]
disable all custom nodes and try again.

**Comment by VisualizersImages** [comment]
I have installed the missing plugins, but they are still available for repair.

![Captura de pantalla 2024-07-22 152912](https://github.com/user-attachments/assets/e914d90b-ce5b-4ae9-baf3-a67fd1dff418)

**Comment by ltdrdata** [comment]
> I have installed the missing plugins, but they are still available for repair.
> 
> ![Captura de pantalla 2024-07-22 152912](https://private-user-images.githubusercontent.com/176293084/350982417-e914d90b-ce5b-4ae9-baf3-a67fd1dff418.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTk5NjMsIm5iZiI6MTcyMTY1OTY2MywicGF0aCI6Ii8xNzYyOTMwODQvMzUwOTgyNDE3LWU5MTRkOTBiLWNlNWItNGFlOS1iYWYzLWE2N2ZkMWRmZjQxOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNDQ3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Nzc2NTIzNmVmNDFiZTgyOTJkZmNmZWFkMGJlN2UzNTFkZDI0MDZmMWI3MmM5ZGMxM2EzMjljMmJhYzlhMDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vjLx0ds1MlJ0Jic3f_RySTFopJGgt4vyh1uklBEA170)

What I meant was not to install the missing custom node, but to remove all installed custom nodes.
This is because the "Load Upscale Model" node is a default node and should not be missing. And it's suspected that the culprit causing this issue is a custom node.

The installation issue with the wlsh node is something that should be dealt with afterwards, and it needs to be addressed by inquiring with the repository of that custom node.

**Comment by robinjhuang** [comment]
@VisualizersImages Did you try uninstalling all the custom nodes?
