### ISSUE TITLE
blank white screen comfiyu

### ISSUE THREAD

**Issue by lavibeats** [comfyanonymous/ComfyUI#4084]
### Your question

 ComfyUI was working  super nice my other drive yesterday afternoon, after suddenly stop working . What could be happens?
Just white blank screen comes.

### Other

I installed my C driver and no reason to works bad I'm not sure what is wrong with it ?
(btw from F12 no issue detected. )

![issue-comfyui](https://github.com/user-attachments/assets/2eab37ea-baee-4354-8e65-383260b1ea72)

**Comment by ltdrdata** [comment]
Given that the favicon is showing, it seems the server is not completely non-functional.
Try disabling all custom nodes and attempt again.

**Comment by lavibeats** [comment]
> Given that the favicon is showing, it seems the server is not completely non-functional.
> 
> Try disabling all custom nodes and attempt again.

So you say should I disable comfyui that installed my other drive ? Well I just moved all my custom nodes and tried. same situation. I have 3 comfyui 3 different drive, moved custom nodes and non of them works that's sucks.

**Comment by ltdrdata** [comment]
press F12 and click `Network`.
And then refresh. What is displayed?

![image](https://github.com/user-attachments/assets/b092cc67-5475-4d31-a5cb-628b1a8a5e01)

**Comment by lavibeats** [comment]
![sdfsdfsdf](https://github.com/user-attachments/assets/18e1e52b-4068-4d33-85be-81c458d53cb1)

**Comment by lavibeats** [comment]
IF ANYONE ENCOUNTER THIS KIND OF SITUATION , SOLUTION IS UPDATE YOUR WINDOWS!!! Finally worked
