### ISSUE TITLE
How to set default workflow?

### ISSUE THREAD

**Issue by HenryBao91** [comfyanonymous/ComfyUI#4085]
### Feature Idea

I import other's workflow.json file or make my own workflow, but it can't be set as default workflow . It'll  reset as default workflow if I export image and reimport the image again.

**Comment by idesign2018** [comment]
The setting method is as follows, but I don’t know whether it is a built-in function of ComfyUI or a function of a plug-in, because I have installed too many plug-ins
![image](https://github.com/user-attachments/assets/878da263-0a63-42cc-9ef6-f9eb809b25e7)

**Comment by huchenlei** [comment]
> The setting method is as follows, but I don’t know whether it is a built-in function of ComfyUI or a function of a plug-in, because I have installed too many plug-ins ![image](https://private-user-images.githubusercontent.com/42263070/351180440-878da263-0a63-42cc-9ef6-f9eb809b25e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzQ4MzIsIm5iZiI6MTcyMTczNDUzMiwicGF0aCI6Ii80MjI2MzA3MC8zNTExODA0NDAtODc4ZGEyNjMtMGE2My00MmNjLTllZjYtZjllYjgwOWIyNWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDExMzUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NDkzZjZiNjg3ODUwN2VmZWE2NTBiNzZiN2IyZGNjNWY1NjJhMGFhZTQwZGIwYjkzN2YxZjMxN2RjZTNlYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I9xUIJqWbB5wEk_sULa3GaqzM9-Fdpam17OA6z9PgRw)

It comes from https://github.com/pythongosssss/ComfyUI-Custom-Scripts

**Comment by XksA-me** [comment]
> > The setting method is as follows, but I don’t know whether it is a built-in function of ComfyUI or a function of a plug-in, because I have installed too many plug-ins ![image](https://private-user-images.githubusercontent.com/42263070/351180440-878da263-0a63-42cc-9ef6-f9eb809b25e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzQ4MzIsIm5iZiI6MTcyMTczNDUzMiwicGF0aCI6Ii80MjI2MzA3MC8zNTExODA0NDAtODc4ZGEyNjMtMGE2My00MmNjLTllZjYtZjllYjgwOWIyNWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDExMzUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NDkzZjZiNjg3ODUwN2VmZWE2NTBiNzZiN2IyZGNjNWY1NjJhMGFhZTQwZGIwYjkzN2YxZjMxN2RjZTNlYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I9xUIJqWbB5wEk_sULa3GaqzM9-Fdpam17OA6z9PgRw)
> 
> It comes from https://github.com/pythongosssss/ComfyUI-Custom-Scripts

cool, thank you, this works for me 

1、Download and restart
```bash
cd ComfyUI/custom_nodes
git clone https://github.com/pythongosssss/ComfyUI-Custom-Scripts
cd ComfyUI
python main.py --listen
```
2、Import your own workflow to be saved, then `Save to Workflow`
<img width="388" alt="image" src="https://github.com/user-attachments/assets/3805fa27-d50f-4b6a-be2b-a4c86d2839df">
3、Load from a saved workflow
<img width="402" alt="image" src="https://github.com/user-attachments/assets/7f8050b4-032c-406f-850e-b12916767753">

**Comment by turndown** [comment]
> The setting method is as follows, but I don’t know whether it is a built-in function of ComfyUI or a function of a plug-in, because I have installed too many plug-ins ![image](https://private-user-images.githubusercontent.com/42263070/351180440-878da263-0a63-42cc-9ef6-f9eb809b25e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDYyNzYsIm5iZiI6MTcyNzQwNTk3NiwicGF0aCI6Ii80MjI2MzA3MC8zNTExODA0NDAtODc4ZGEyNjMtMGE2My00MmNjLTllZjYtZjllYjgwOWIyNWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyNTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMzVmN2IxZDdmOGM3NGQ0YjcxYWQxYzI1OWVlNGFiNzQ2ZTdhYTM0ZWQ3ZDFlZDNlOTEwYTFhYzY3ZDVmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gdeJNX8mFkHxGFJliiQUTX6UsXlfHzt8mzUEFLzcvWw)

Hello, I installed the plug and have already save a workflow of flux , but I can't choose any other workflow? It doesn't list any other workflow. What's the problem?
![image](https://github.com/user-attachments/assets/51a9f616-2224-4030-b49a-69b1a7c59f65)
![image](https://github.com/user-attachments/assets/31d57b70-b428-457d-8115-75c4430881e0)

**Comment by Shituation** [comment]
2025, still can't set the default workflow.

**Comment by VideoFX** [comment]
Can the default workflow be cleared, so its blank upon new tab?

**Comment by smbell1979** [comment]
I made a blank workflow and put it into the root comfyUI folder and it loads that on startup now!
