### ISSUE TITLE
`Load Image` displays the contents of deep subfolders

### ISSUE THREAD

**Issue by idesign2018** [comfyanonymous/ComfyUI#4086]
### Feature Idea

Hope that `Load Image` node can support the display of deep subfolder contents
![image](https://github.com/user-attachments/assets/30d247e2-ee65-417e-ab98-6f6dbec3ee7b)

**Comment by huchenlei** [comment]
Moved to frontend repo.

**Comment by idesign2018** [comment]
> Moved to frontend repo.移至前端存储库。

Thanks!!
