### ISSUE TITLE
Show model cover image

### ISSUE THREAD

**Issue by idesign2018** [comfyanonymous/ComfyUI#4088]
### Feature Idea

When the mouse passes over the model folder or model, the cover image of the model can be displayed. The cover image type needs to support common image formats such as `png`, `jpg`, `gif`, `webp`, etc., as shown in ① and ② in the figure
![image](https://github.com/user-attachments/assets/ba759ec1-8a93-4bb0-a787-1e04b34e832a)

### Other

If there is a plugin that can achieve this function, I would like to try it

**Comment by huchenlei** [comment]
https://github.com/11cafe/comfyui-workspace-manager Has a model management panel that shows you model cover image. We are going to build the feature in native ComfyUI in the TS repo later. https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by idesign2018** [comment]
> https://github.com/11cafe/comfyui-workspace-manager Has a model management panel that shows you model cover image. We are going to build the feature in native ComfyUI in the TS repo later. https://github.com/Comfy-Org/ComfyUI_frontendhttps://github.com/11cafe/comfyui-workspace-manager 有一个模型管理面板，可显示模型封面图像。我们稍后将在 TS 仓库的原生 ComfyUI 中构建该功能。https://github.com/Comfy-Org/ComfyUI_frontend

very good, thank you
