### ISSUE TITLE
After clicking "update_comfyui_and_python_dependencies" and updating, running ComfyUI resulted in an error

### ISSUE THREAD

**Issue by Simwake** [comfyanonymous/ComfyUI#4093]
### Expected Behavior

update_comfyui_and_python_dependencies

### Actual Behavior

Prestartup times for custom nodes:
   1.2 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\main.py", line 77, in <module>
    import comfy.utils
  File "E:\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 1, in <module>
    import torch
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

### Steps to Reproduce

update_comfyui_and_python_dependencies

### Debug Logs

```powershell
Prestartup times for custom nodes:
   1.2 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\main.py", line 77, in <module>
    import comfy.utils
  File "E:\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 1, in <module>
    import torch
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
```

**Comment by norflin321** [comment]
same

**Comment by miurgh** [comment]
same

**Comment by densladkov13** [comment]
same(

**Comment by ltdrdata** [comment]
See this: https://github.com/comfyanonymous/ComfyUI/issues/3687

**Comment by Espral** [comment]
same

**Comment by yoland68** [comment]
<img width="2020" alt="Screenshot 2024-07-24 at 9 35 43 AM" src="https://github.com/user-attachments/assets/888305e3-58fe-444c-a176-4c4ce1ccfa4d">
This is failing on torch nightly. I will take a closer look at the issue today.

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/19944ad252106e46a40e0b952c86c1cebc8486ab

Not sure if it's the best fix but it works.

**Comment by comfyanonymous** [comment]
If you have this issue, run the updater another time and it should be fixed.

**Comment by babacar1979** [comment]
It still doesn't work, even with the fix

**Comment by babacar1979** [comment]
> It still doesn't work, even with the fix

It's OK now, but i don't know why 😂

**Comment by Simwake** [comment]
> try to install Visual Studio, and download the C++ package, it works for me.

thank!! it works.
