### ISSUE TITLE
When I used the kolors model to generate images, there were irregularities in the content of the images

### ISSUE THREAD

**Issue by yueyangqingshu** [comfyanonymous/ComfyUI#4095]
### Expected Behavior

help me！

### Actual Behavior

![image](https://github.com/user-attachments/assets/5f7571d9-f804-4caa-8287-87ec962cac95)

### Steps to Reproduce

I use kolors' model to generate text graphs, but the generated pictures are not understandable, I don't know why, I need everyone's help, thank you very much

### Debug Logs

```powershell
got prompt
device= mps
blue sky 
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [01:59<00:00,  4.78s/it]
Using split attention in VAE
Using split attention in VAE
Requested to load AutoencoderKL
Loading 1 new model
Prompt executed in 187.71 seconds
```

**Comment by robinjhuang** [comment]
If you are using this please open an issue in their repository. 

https://github.com/kijai/ComfyUI-KwaiKolorsWrapper
