### ISSUE TITLE
Save Current Workflow Dropdown unclickable when Beta Menu is mounted at bottom

### ISSUE THREAD

**Issue by jujaga** [comfyanonymous/ComfyUI#4099]
### Expected Behavior

As a user, I should be able to select the save current workflow dropdown, hover over, and select one of the dropdown options presented.

### Actual Behavior

The menu appears when the mouse hovers over the dropdown caret button. However, as soon as the mouse moves off of the caret (like when you are intending to hover over one of the 3 presented options) the menu immediately disappears. The dropdown options are inaccessible.

![Capture](https://github.com/user-attachments/assets/241185ba-e064-4012-a58a-1e8a5190c309)

### Steps to Reproduce

Ensure that the beta menu is activated, and set to render at the bottom of the page. Then hover over the save current workflow caret button; the menu should appear. Bug appears when user moves mouse immediately off the caret button in any direction where the dropdown menu disappears immediately.

### Debug Logs

```powershell
N/A
```

### Other

This behavior does not appear to be present when the beta menu is mounted at the top.

**Comment by ltdrdata** [comment]
In my case, this issue cannot be reproduced.

The most reliable solution would be to change the functionality from hover-based to click-based, which would completely eliminate any potential functional issues.

**Comment by huchenlei** [comment]
If the issue persists, please file an issue to https://github.com/Comfy-Org/ComfyUI_frontend instead. Thanks!
