### ISSUE TITLE
Add Upscaler + more documentation?

### ISSUE THREAD

**Issue by esloc03** [comfyanonymous/ComfyUI#41]
This UI is amazing! :)
Which folder can I add my own upscaler such as 4x-AnimeSharp? - 
Also is there more documentation on this UI? I'd love to read it!

**Comment by comfyanonymous** [comment]
ESRGAN support is coming soon so is better documentation.

For now the only documentation is the README and the examples page: https://comfyanonymous.github.io/ComfyUI_examples/

**Comment by comfyanonymous** [comment]
ESRGAN/etc... support is implemented now so you should be able to use your own upscale models: https://comfyanonymous.github.io/ComfyUI_examples/upscale_models/

**Comment by jwvanderbeck** [comment]
How do you specify the upscale amount?

**Comment by comfyanonymous** [comment]
Upscale models have a fixed scale amount that can't be changed. If you want a specific resolution you have to ImageScale after.

**Comment by angelmankel** [comment]
@comfyanonymous Is there a specific reason why its set to a fixed amount?

**Comment by ltdrdata** [comment]
> @comfyanonymous Is there a specific reason why its set to a fixed amount?

The question was incorrect. The scaling of the size is determined by the model itself. ComfyUI does not intervene in sizing at all. Many people transitioning from A1111 often find this aspect confusing. A1111 implicitly handles the process of upscaling and downscaling through the model. 
In ComfyUI, this process is not hidden; rather, an "Image Scale" node is explicitly attached to handle it.

**Comment by robinjhuang** [comment]
Closing the issue. Please reopen if not resolved.
