### ISSUE TITLE
Prompt validate failed but workflow keeps running and no error dialog popup

### ISSUE THREAD

**Issue by AdrianDuan** [comfyanonymous/ComfyUI#4105]
### Expected Behavior

When prompt validated failed, there should be an error dialog popup and display error message like this
<img width="687" alt="image" src="https://github.com/user-attachments/assets/1d33ac21-4f60-4491-88ce-424ea1a0c91d">

### Actual Behavior

In some custom nodes, when prompt validate failed, workflow keeps running and there is no error dialog, `/prompt` api returns with `node_errors` but status code is `200`.

https://github.com/comfyanonymous/ComfyUI/blob/10c919f4c77b3615f0efa9014e8b77f294c23a2d/execution.py#L736

### Steps to Reproduce

1. Install custom nodes https://github.com/chflame163/ComfyUI_LayerStyle
2. Add Node `LayerColor: LUT Apply`
3. Edit node widget info with lut cube file which doesn't exists 
4. Run prompt
5. There should be error popup but this workflow keeps running

### Debug Logs

```powershell
got prompt
Failed to validate prompt for output 195:
* LayerColor: LUT Apply 457:
  - Value not in list: LUT: 'Fujifilm.cube' not in ['BlueArchitecture.cube']
Output will be ignored
```

**Comment by robinjhuang** [comment]
Was not able to reproduce. Also ran with an non-existent lut file and got the expected error pop up.

[test.json](https://github.com/user-attachments/files/16420163/test.json)

<img width="765" alt="Screenshot 2024-07-29 at 4 59 40 PM" src="https://github.com/user-attachments/assets/ce16ba92-617f-4a77-9b5c-2a135f11d182">

**Comment by robinjhuang** [comment]
Please re-open if this is still an issue.
