### ISSUE TITLE
The new Hunyuan nodes will give a tensor mismatch if the prompt is too long

### ISSUE THREAD

**Issue by RandomGitUser321** [comfyanonymous/ComfyUI#4115]
### Expected Behavior

That it will work

### Actual Behavior

That it doesn't work if the prompt is too long

### Steps to Reproduce

If the prompt exceeds the underlying token limit of the encoder(s), it will give this error. If you trim it to be under the limit, it will work. 

### Debug Logs

```powershell
File "G:\ComfyUI\ComfyUI\comfy\ldm\hydit\models.py", line 328, in forward
    text_states = torch.where(clip_t5_mask.unsqueeze(2), text_states, self.text_embedding_padding.to(text_states))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (410) must match the size of tensor b (333) at non-singleton dimension 1
```

### Other

I should also note that my client is up to date and includes the  "[Own BertModel implementation that works with lowvram.](https://github.com/comfyanonymous/ComfyUI/commit/a9ac56fc0db5777de0edf2fe4b8ed628ccab1293)" update as well.

I'm assuming the encoders cap at 77 and 256 under the hood. In the error in the log, 410-77=333 and 333-77=256. So it's likely the bert encoder having issues and trying to add another batch or something if the prompt is larger than 77 tokens.

**Comment by comfyanonymous** [comment]
Should be fixed now.
