### ISSUE TITLE
Through the API, how to POST a workflow with an image input, right after the image was generated with another workflow?

### ISSUE THREAD

**Issue by MasterAbsinthe** [comfyanonymous/ComfyUI#4122]
### Your question

I have a simple UI where the user generates four 512x512 images, chooses one of them, and requests an upscaled 1024x1024 version of that image. 
I first generate the images by posting the JSON txt2img workflow to ComfyUI enpoint /prompt. ComfyUI then returns the promptID, which I use to post to the /history endpoint in order to get the image filenames, which I THEN use to view and extract the images in the /view endpoint... and then display to the user.

When the user selects an image and requests highResFix, I started to worry that I'd have to upload the image to the ComfyUI/upload/image, meaning I'd have to physically save the image in a folder instead of just using the base64 string that I was using in my program. But then I though, ComfyUI _already_ has the file in there, which is how I could view it given the filename, subfolder, and type:
`http://127.0.0.1:8188/view?filename=ComfyUI_temp_ybfly_00001_.png&subfolder=&type=temp`
So then I tried to simply post the JSON workflow with the filename (such as "ComfyUI_temp_ybfly_00001_.png") in the upload image node imput, the same way I successfully did it with already-uploaded images, but ComfyUI just told me the filename was invalid.

Looking closer at the images that I COULD use (images that I uploaded manually in the ComfyUI UI), they are all of type "input" and are located in the ComfyUI\input folder. The generated temp images that I want to use, are located in the ComfyUI\temp folder. 

Is there a way to tell ComfyUI to use the generated images in the temp folder, without having to mess with moving/saving images in folders? 

EDIT: From the [following blog post](https://9elements.com/blog/hosting-a-comfyui-workflow-via-api/):
![image](https://github.com/user-attachments/assets/f50591d4-a00b-41ae-9e70-b4e93c746f45)
If it's possible to upload an image to "output" or "temp" instead of the default "input", surely there is a way to somehow specify in the JSON file, in the image upload node, which folder the image can be found in?

**Comment by MasterAbsinthe** [comment]
Okay I found a simple solution for this. I installed [ComfyUI_Ib_CustomNodes](https://github.com/Chaoses-Ib/ComfyUI_Ib_CustomNodes) through the manager, one of which is "Load Image From Path". In this node you can input the file path relative to the temp folder like so:
`ComfyUI_temp_iodzi_00002_.png [temp]`
worked perfectly!

**Comment by robinjhuang** [comment]
Awesome! Thanks for sharing your solution.

**Comment by WorkSync** [comment]
> ### Your question
> I have a simple UI where the user generates four 512x512 images, chooses one of them, and requests an upscaled 1024x1024 version of that image. I first generate the images by posting the JSON txt2img workflow to ComfyUI enpoint /prompt. ComfyUI then returns the promptID, which I use to post to the /history endpoint in order to get the image filenames, which I THEN use to view and extract the images in the /view endpoint... and then display to the user.
> 
> When the user selects an image and requests highResFix, I started to worry that I'd have to upload the image to the ComfyUI/upload/image, meaning I'd have to physically save the image in a folder instead of just using the base64 string that I was using in my program. But then I though, ComfyUI _already_ has the file in there, which is how I could view it given the filename, subfolder, and type: `http://127.0.0.1:8188/view?filename=ComfyUI_temp_ybfly_00001_.png&subfolder=&type=temp` So then I tried to simply post the JSON workflow with the filename (such as "ComfyUI_temp_ybfly_00001_.png") in the upload image node imput, the same way I successfully did it with already-uploaded images, but ComfyUI just told me the filename was invalid.
> 
> Looking closer at the images that I COULD use (images that I uploaded manually in the ComfyUI UI), they are all of type "input" and are located in the ComfyUI\input folder. The generated temp images that I want to use, are located in the ComfyUI\temp folder.
> 
> Is there a way to tell ComfyUI to use the generated images in the temp folder, without having to mess with moving/saving images in folders?
> 
> EDIT: From the [following blog post](https://9elements.com/blog/hosting-a-comfyui-workflow-via-api/): ![image](https://private-user-images.githubusercontent.com/43134939/352709649-f50591d4-a00b-41ae-9e70-b4e93c746f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDM0ODEsIm5iZiI6MTcyMjM0MzE4MSwicGF0aCI6Ii80MzEzNDkzOS8zNTI3MDk2NDktZjUwNTkxZDQtYTAwYi00MWFlLTllNzAtYjRlOTNjNzQ2ZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEyMzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZjM1NjVlYWU1ZGJmZmU4ZDI5OWI5Yjk3NGE3ZmUwMzQwZjUyZDA2MDMwOTcyZjA2MTAzNDQ1NzUxM2QyYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p9r2oO6nyyuycW7feks6qETzCIDTLQ__e_fnCwzKgHs) If it's possible to upload an image to "output" or "temp" instead of the default "input", surely there is a way to somehow specify in the JSON file, in the image upload node, which folder the image can be found in?
> 
> ### Logs
> _No response_
> 
> ### Other
> _No response_

May I ask how you achieved image upload? I tried sending JSON files using only Python and calling APIs, but I found that images cannot be uploaded to comfyui.comfyui. Do I need any changes to receive image data?

The code I tried is as follows:
```
def upload_image(input_path, name, server_address, image_type="input", overwrite=False):
	with open(input_path, 'rb') as file:
		multipart_data = MultipartEncoder(
      fields= {
        'image': (name, file, 'image/png'),
        'type': image_type,
        'overwrite': str(overwrite).lower()
      }
		)

		data = multipart_data
		headers = { 'Content-Type': multipart_data.content_type }
		request = urllib.request.Request("http://{}/upload/image".format(server_address), data=data, headers=headers)
		with urllib.request.urlopen(request) as response:
			return response.read()
```

**Comment by WorkSync** [comment]
> > ### Your question
> > I have a simple UI where the user generates four 512x512 images, chooses one of them, and requests an upscaled 1024x1024 version of that image. I first generate the images by posting the JSON txt2img workflow to ComfyUI enpoint /prompt. ComfyUI then returns the promptID, which I use to post to the /history endpoint in order to get the image filenames, which I THEN use to view and extract the images in the /view endpoint... and then display to the user.
> > When the user selects an image and requests highResFix, I started to worry that I'd have to upload the image to the ComfyUI/upload/image, meaning I'd have to physically save the image in a folder instead of just using the base64 string that I was using in my program. But then I though, ComfyUI _already_ has the file in there, which is how I could view it given the filename, subfolder, and type: `http://127.0.0.1:8188/view?filename=ComfyUI_temp_ybfly_00001_.png&subfolder=&type=temp` So then I tried to simply post the JSON workflow with the filename (such as "ComfyUI_temp_ybfly_00001_.png") in the upload image node imput, the same way I successfully did it with already-uploaded images, but ComfyUI just told me the filename was invalid.
> > Looking closer at the images that I COULD use (images that I uploaded manually in the ComfyUI UI), they are all of type "input" and are located in the ComfyUI\input folder. The generated temp images that I want to use, are located in the ComfyUI\temp folder.
> > Is there a way to tell ComfyUI to use the generated images in the temp folder, without having to mess with moving/saving images in folders?
> > EDIT: From the [following blog post](https://9elements.com/blog/hosting-a-comfyui-workflow-via-api/): <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/43134939/352709649-f50591d4-a00b-41ae-9e70-b4e93c746f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDM0ODEsIm5iZiI6MTcyMjM0MzE4MSwicGF0aCI6Ii80MzEzNDkzOS8zNTI3MDk2NDktZjUwNTkxZDQtYTAwYi00MWFlLTllNzAtYjRlOTNjNzQ2ZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEyMzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZjM1NjVlYWU1ZGJmZmU4ZDI5OWI5Yjk3NGE3ZmUwMzQwZjUyZDA2MDMwOTcyZjA2MTAzNDQ1NzUxM2QyYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p9r2oO6nyyuycW7feks6qETzCIDTLQ__e_fnCwzKgHs"> If it's possible to upload an image to "output" or "temp" instead of the default "input", surely there is a way to somehow specify in the JSON file, in the image upload node, which folder the image can be found in?
> > ### Logs
> > _No response_
> > ### Other
> > _No response_
> 
> May I ask how you achieved image upload? I tried sending JSON files using only Python and calling APIs, but I found that images cannot be uploaded to comfyui.comfyui. Do I need any changes to receive image data?
> 
> The code I tried is as follows:
> 
> ```
> def upload_image(input_path, name, server_address, image_type="input", overwrite=False):
> 	with open(input_path, 'rb') as file:
> 		multipart_data = MultipartEncoder(
>       fields= {
>         'image': (name, file, 'image/png'),
>         'type': image_type,
>         'overwrite': str(overwrite).lower()
>       }
> 		)
> 
> 		data = multipart_data
> 		headers = { 'Content-Type': multipart_data.content_type }
> 		request = urllib.request.Request("http://{}/upload/image".format(server_address), data=data, headers=headers)
> 		with urllib.request.urlopen(request) as response:
> 			return response.read()
> ```

It's all set now, sorry for the interruption.
