### ISSUE TITLE
DEFAULT_GROUP_FONT can't be modified.

### ISSUE THREAD

**Issue by metsweet999** [comfyanonymous/ComfyUI#4123]
### Expected Behavior

modify "DEFAULT_GROUP_FONT": to be 66, so when i add a new group next time, the new group's text size will be as big as 66.

### Actual Behavior

i exported a color palette file called "custom_obsidian.json".
inside this file,
i replaced " 'DEFAULT_GROUP_FONT': 24," to " 'DEFAULT_GROUP_FONT': 66," ,
replaced " "id": "obsidian"," to  " "id": "myTheme",",
replaced " "name": "Obsidian","  to  " "name": "MyTheme",",
and renamed the file as "myTheme.json",
then imported this file at color palette panel in comfyui.
restarted comfyui, created a new group,
and saw the text size of the group didn't change.
![屏幕截图 2024-07-27 164211](https://github.com/user-attachments/assets/925ec73a-8c9a-4da4-b350-fe857da5e4e9)

### Steps to Reproduce

described step by step in "Actual Behavior" colume.

### Debug Logs

```powershell
no debug logs, because not a bug that gives back logs.
```

**Comment by robinjhuang** [comment]
Was able to reproduce this.

**Comment by huchenlei** [comment]
Fixed in https://github.com/Comfy-Org/ComfyUI_frontend/pull/275
