### ISSUE TITLE
i cant udapte ComfyUI 

### ISSUE THREAD

**Issue by R1t0k1** [comfyanonymous/ComfyUI#4124]
### Your question

i just install ComfyUI, but i can't update it, when i click on "update_comfyui" that send me an error, with a friend we try to solve this error, i already reinstall in ( git, python and ComfyUI) but that dont change anything

### Logs

```powershell
stashing current changes
nothing to stash
creating backup branch: backup_branch_2024-07-27_15_09_57
checking out master branch
Traceback (most recent call last):
  File "C:\IA\ComfyUI_windows_portable\update\update.py", line 65, in <module>
    ref = repo.lookup_reference(branch.name)
                                ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by ltdrdata** [comment]
goto ComfyUI dir in cmd.
and execute `git checkout main` and `git pull`

**Comment by R1t0k1** [comment]
when i go to ComfyUI in cmd and execute git checkout main that's send me this:

**Comment by ltdrdata** [comment]
> when i go to ComfyUI in cmd and execute git checkout main that's send me this:
> 
> C:\IA\ComfyUI_windows_portable>git checkout main fatal: not a git repository (or any of the parent directories): .git


goto `C:\IA\ComfyUI_windows_portable\ComfyUI` dir.

**Comment by R1t0k1** [comment]
know i have this: 

C:\IA\ComfyUI_windows_portable\ComfyUI>git checkout main
error: pathspec 'main' did not match any file(s) known to git

**Comment by ltdrdata** [comment]
> know i have this:
> 
> C:\IA\ComfyUI_windows_portable\ComfyUI>git checkout main error: pathspec 'main' did not match any file(s) known to git

oh... my fault....

that should be `git checkout master`

**Comment by R1t0k1** [comment]
oh don't worry, 
i think i'ts ok, that send me this: 

C:\IA\ComfyUI_windows_portable\ComfyUI>git checkout master
Previous HEAD position was 1d47ec3 Set torch version to be 2.3.1 for v0.0.3
branch 'master' set up to track 'origin/master'.
Switched to a new branch 'master'

C:\IA\ComfyUI_windows_portable\ComfyUI>git pull
Already up to date.

**Comment by R1t0k1** [comment]
thank you for you time itdrdata, that's work, thank you very much

**Comment by R1t0k1** [comment]
thanks
