### ISSUE TITLE
Numpy is not available. I would appreciate it if an expert could provide guidance.

### ISSUE THREAD

**Issue by wappe55** [comfyanonymous/ComfyUI#4125]
### Your question

When generating images, the following message appears. I would appreciate it if an expert could provide guidance.
![スクリーンショット 2024-07-27 221620](https://github.com/user-attachments/assets/b6454b62-7647-494d-8596-040501fb28a8)

**Comment by ltdrdata** [comment]
Check the version of numpy package.

If you are using portable version then use this command.
`.\python_embeded\python.exe -m pip freeze`

**Comment by wappe55** [comment]
Thank you for your feedback. The version is 1.26.4.

**Comment by ltdrdata** [comment]
> Thank you for your feedback. The version is 1.26.4.

How do you go about running ComfyUI?

This symptom occurs when numpy is installed as version 2.0. It appears that the Python environment running ComfyUI and the Python environment you've checked are different.

https://github.com/comfyanonymous/ComfyUI/issues/3794

**Comment by wappe55** [comment]
Understood. I will check again.　Thank you

**Comment by wappe55** [comment]
> > Thank you for your feedback. The version is 1.26.4.
> 
> How do you go about running ComfyUI?
> 
> This symptom occurs when numpy is installed as version 2.0. It appears that the Python environment running ComfyUI and the Python environment you've checked are different.
> 
> #3794


Thank you very much. It seems I made the same mistake as others. Thanks to you, I was able to handle the problem calmly.
(´>؂∂｀)
 I wish you happiness.
