### ISSUE TITLE
What is 'transformers' and how to stop ComfyUI from updating and checking Missing or outdated packages at startup?  

### ISSUE THREAD

**Issue by DIRECTEDBYKUBA** [comfyanonymous/ComfyUI#4129]
### Your question

Is there a way of editing a file in the ConfyUI Folder so it stops Updating packages at Startup?
What File and in what Line?

I have a Node Error and i think it is because the wrong transformers version gets loaded, but im not sure if this the case that the newer version of transformers can not utalize 'VitMatteImageProcessor' in transformers-4.43.3 so i wanted to try transformers-4.33.2 (as its in the node requrements.txt), if it helps but ComfyUI automaticly Updates it at Startup to transformers-4.43.3.

And for general understanding of 'transformers' is it possible that newer versions leave out things that older Versions have, like ''cannot import name 'VitMatteImageProcessor' '' is it because the structure changes to pull requests and it cant find it anymore even it is in 'transformers', why cant they build and upgrade packages so all requirements are still given when a older version is overwritten? cant wrap my head around that whats going on with all the diffrent packages Versions that exist and some Nodes need specific versions but not newer, if thats the case for my Node Error.

### Logs

```powershell
Main Node Error:
Error occurred when executing LayerMask: SegformerB2ClothesUltra:
cannot import name 'VitMatteImageProcessor' from 'transformers'

Try to fix it by SegformerB2ClothesUltra:
pip install -r requrements.txt

Installing collected packages: tokenizers, transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.19.1
    Uninstalling tokenizers-0.19.1:
      Successfully uninstalled tokenizers-0.19.1

  Attempting uninstall: transformers
    Found existing installation: transformers 4.43.3
    Uninstalling transformers-4.43.3:
      Successfully uninstalled transformers-4.43.3
Successfully installed tokenizers-0.13.3 transformers-4.33.2

At Startup:

Missing or outdated packages: transformers>=4.38.2
Installing/Updating missing packages...

Installing collected packages: tokenizers, transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.13.3
    Uninstalling tokenizers-0.13.3:
      Successfully uninstalled tokenizers-0.13.3

Attempting uninstall: transformers
    Found existing installation: transformers 4.33.2
    Uninstalling transformers-4.33.2:
      Successfully uninstalled transformers-4.33.2
Successfully installed tokenizers-0.19.1 transformers-4.43.3
```

**Comment by ltdrdata** [comment]
The automatic installation of packages is not a feature of ComfyUI itself, but is done by custom nodes.

In the case of nodes like ComfyUI_VLM_nodes, if dependency issues occur, it determines that the installation is incomplete and performs the installation on its own.
