### ISSUE TITLE
An error message "Allocation on device" appears when the SAM model is loaded

### ISSUE THREAD

**Issue by Tanglinling** [comfyanonymous/ComfyUI#4141]
### Your question

在最新版本comfyui上运行“segmentation”功能的节点在加载SAM模型时会出现这个报错。我分别尝试了“comfyui_segment_anything
”节点和“ComfyUI_LayerStyle”节点中的“SegmentAnythingUltra V2”都出现了这个报错。我确定不是我的显存不够，因为在（ab76abc）这个版本中是可以使用的。
Nodes running the "segmentation" function on the latest version of comfyui will encounter this error when loading the SAM model. I tried "comfyui_segment_anything" separately
This error occurs on both the "SegmentAnythingUltra V2" node and the "ComfyUI_LayerStyle" node. I'm sure it's not that I don't have enough video memory, because it's available in this version (ab76abc).
![image](https://github.com/user-attachments/assets/846fe69d-6066-469d-9ff3-5a2e37287528)

**Comment by kwj0413** [comment]
我也是这个问题，请问您解决了吗

**Comment by ltdrdata** [comment]
This issue should be handled in https://github.com/chflame163/ComfyUI_LayerStyle
