### ISSUE TITLE
在运行LivePortrait时出现的问题

### ISSUE THREAD

**Issue by lambbigcc** [comfyanonymous/ComfyUI#4142]
### Your question

我是一位初学者，再运行LivePortrait工作流时出现的问题，请问怎么解决这个问题。谢谢~

**Comment by lambbigcc** [comment]
![微信截图_20240730133748](https://github.com/user-attachments/assets/01d88776-3fd3-4d46-a03a-6d7df0759ebf)

**Comment by ltdrdata** [comment]
You don't have model file.
It seems to have failed when it should have been downloaded automatically.
You need to download it, manually.

See details:
https://github.com/kijai/ComfyUI-LivePortraitKJ
