### ISSUE TITLE
send error: [WinError 64] The specified network name is no longer available

### ISSUE THREAD

**Issue by Orenji-Tangerine** [comfyanonymous/ComfyUI#4155]
### Expected Behavior

If I leave the ComfyUI idle for a while, this error will appear and the page on the browser will go into disconnected status like web page not found. I will just need to reenter the page link or refresh again to get it working.

### Actual Behavior

![Error](https://github.com/user-attachments/assets/2cae1a96-26e1-49d6-bd6e-56d56b4ef06b)

### Steps to Reproduce

If I leave the ComfyUI idle for a while, this error will appear and the page on the browser will go into disconnected status like web page not found.

### Debug Logs

```powershell
send error: [WinError 64] The specified network name is no longer available
```

**Comment by ltdrdata** [comment]
1. Is it correct that you don't use any special options when running ComfyUI?
2. Does the issue occur only after a long period of time, with no problems initially?
3. Does the issue still occur when all custom nodes are disabled?
