### ISSUE TITLE
Unable to download new SAM2 node by Kijai

### ISSUE THREAD

**Issue by tristan22mc** [comfyanonymous/ComfyUI#4156]
### Expected Behavior

download SAM2 nodes by kijai

### Actual Behavior

![Screenshot 2024-07-31 145652](https://github.com/user-attachments/assets/248dba47-91fd-449b-9a81-9c01102af47e)
Unable to download the new kijai SAM2 node located here: https://github.com/kijai/ComfyUI-segment-anything-2

### Steps to Reproduce

try to download node pack

### Debug Logs

```powershell
![Screenshot 2024-07-31 145652](https://github.com/user-attachments/assets/248dba47-91fd-449b-9a81-9c01102af47e)
```

### Other

I'm unable to figure out how to turn off this security so I can download

**Comment by ltdrdata** [comment]
This is not a bug. And this is a not a issue of ComfyUI.

https://github.com/ltdrdata/ComfyUI-Manager/issues/917
