### ISSUE TITLE
[Beta] Use new menu and workflow management. 【improvement suggestions】

### ISSUE THREAD

**Issue by fc100b** [comfyanonymous/ComfyUI#4159]
### Your question

[Beta] Use new menu and workflow management. Note: On small screens the menu will always be at the top.
I set the menu at the bottom, when i browse the workflow, the menu drops down.  It is very inconvenient . Clound you kindly make it expansion up? I know your guys must very busy, i hope the ideas will be taken on board. Many thanks!
![微信截图_20240801091837](https://github.com/user-attachments/assets/bcf0406c-3d5f-4836-8654-d441d030c31a)

**Comment by huchenlei** [comment]
The workflow management will be reworked as a sidebar tab in https://github.com/Comfy-Org/ComfyUI_frontend/pull/265
