### ISSUE TITLE
[Announcement] ComfyUI Frontend Modernization: Transitioning to a New Era on August 15, 2024

### ISSUE THREAD

**Issue by huchenlei** [comfyanonymous/ComfyUI#4169]
### Summary
Effective August 15, 2024, we will be replacing the legacy frontend currently hosted in this repository with our new frontend (https://github.com/Comfy-Org/ComfyUI_frontend).

### Why a New Frontend?
Our current frontend is built using vanilla JavaScript ESM modules without package management, which has led to significant challenges in development. We've been reinventing solutions for problems that already have established, efficient answers. The new frontend leverages TypeScript, Vue, and Vite, offering a more robust and maintainable codebase. We've also developed a custom shim extension in the Vite build process to ensure full compatibility with our existing frontend extension ecosystem. This new tech stack will dramatically accelerate the development of new frontend features.

### New Features
The new frontend introduces numerous quality-of-life improvements. For a comprehensive list, please visit: https://github.com/Comfy-Org/ComfyUI_frontend#qol-changes

### Early Adoption
If you're eager to experience the new frontend before the official transition, you can opt-in now by adding the following command line argument to your ComfyUI launch script:

```
--front-end-version Comfy-Org/ComfyUI_frontend@latest
```

This will use the latest release of the new frontend. If you prefer to use a specific version for stability, you can specify a version number:

```
--front-end-version Comfy-Org/ComfyUI_frontend@1.2.2
```

### Legacy UI Access After Deprecation
Following the transition on August 15, 2024, we will preserve a snapshot of the legacy UI in a new repository: Comfy-Org/ComfyUI_legacy_frontend. Users who need to revert to the legacy UI can do so using the following command line argument:

```
--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest
```

We're excited about this update and the improvements it brings to ComfyUI. Thank you for your continued support and feedback as we evolve our platform.

**Comment by aimgdev** [comment]
is this true? @comfyanonymous

**Comment by mcmonkey4eva** [comment]
Yes

**Comment by comfyanonymous** [comment]
Yes, if you have any concerns you can go test the new frontend and report any issues you have.

**Comment by tpcdaz** [comment]
Is the new frontend still noodle junction or is it actually made for regular people now?

**Comment by ltdrdata** [comment]
> Is the new frontend still noodle junction or is it actually made for regular people now?
> 
> EDIT : Never mind just tried it and noticed it's still made without regular users in mind.

The current stage is more about laying the foundation rather than focusing on the outwardly visible aspects.

**Comment by Creative-comfyUI** [comment]
I try it on Mac M2. I get a white screen. Nothing appears.

**Comment by huchenlei** [comment]
> I try it on Mac M2. I get a white screen. Nothing appears.

Any browser console logs? (Toggle dev tools with f12)

**Comment by Creative-comfyUI** [comment]
> > I try it on Mac M2. I get a white screen. Nothing appears.
> 
> Any browser console logs? (Toggle dev tools with f12)

This time the screen is not white. ComfyUI appeared after something seems to load 

Error: Invalid ComfyNodeDef: {"input":{"required":{"data":["*",""],"text":["STRING",{"multiline":true}]},"hidden":{"prompt":"PROMPT","extra_pnginfo":"EXTRA_PNGINFO","unique_id":"UNIQUE_ID"}},"output":[],"output_is_list":[],"output_name":[],"name":"ImpactLogger","display_name":"ImpactLogger","description":"","python_module":"custom_nodes.ComfyUI-Impact-Pack","category":"ImpactPack/Debug","output_node":true}
Validation error: Array must contain at most 1 element(s) at "input.required.data"
    validateComfyNodeDef apiTypes.ts:292
    getNodeDefs api.ts:253
    registerNodes app.ts:1968
    registerNodes workflow-component.js:328
    setup app.ts:1901
    setup GraphCanvas.vue:45
    createHook runtime-core.esm-bundler.js:1808
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:1788
    flushPostFlushCbs runtime-core.esm-bundler.js:379
    render3 runtime-core.esm-bundler.js:5805
    mount runtime-core.esm-bundler.js:3062
    mount runtime-dom.esm-bundler.js:1530
    <anonymous> main.ts:41
Caused by: ZodValidationError: Validation error: Array must contain at most 1 element(s) at "input.required.data"
    ValidationError index.mjs:11
    fromZodErrorWithoutRuntimeCheck index.mjs:207
    fromZodError index.mjs:186
    validateComfyNodeDef apiTypes.ts:291
    getNodeDefs api.ts:253
    registerNodes app.ts:1968
    registerNodes workflow-component.js:328
    setup app.ts:1901
    setup GraphCanvas.vue:45
    createHook runtime-core.esm-bundler.js:1808
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:1788
    flushPostFlushCbs runtime-core.esm-bundler.js:379
    render3 runtime-core.esm-bundler.js:5805
    mount runtime-core.esm-bundler.js:3062
    mount runtime-dom.esm-bundler.js:1530
    <anonymous> main.ts:41
Caused by: ZodError: [
  {
    "code": "too_big",
    "maximum": 1,
    "inclusive": true,
    "exact": false,
    "type": "array",
    "path": [
      "input",
      "required",
      "data"
    ],
    "message": "Array must contain at most 1 element(s)"
  }
]
    ZodError index.mjs:164
    get error index.mjs:587
    validateComfyNodeDef apiTypes.ts:291
    getNodeDefs api.ts:253
    registerNodes app.ts:1968
    registerNodes workflow-component.js:328
    setup app.ts:1901
    setup GraphCanvas.vue:45
    createHook runtime-core.esm-bundler.js:1808
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:1788
    flushPostFlushCbs runtime-core.esm-bundler.js:379
    render3 runtime-core.esm-bundler.js:5805
    mount runtime-core.esm-bundler.js:3062
    mount runtime-dom.esm-bundler.js:1530
    <anonymous> main.ts:41
[api.ts:256:16](http://127.0.0.1:8188/src/scripts/api.ts)
    getNodeDefs api.ts:256
    registerNodes app.ts:1968
    registerNodes workflow-component.js:328
    setup app.ts:1901
    setup GraphCanvas.vue:45
    createHook runtime-core.esm-bundler.js:1808
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:1788
    flushPostFlushCbs runtime-core.esm-bundler.js:379
    render3 runtime-core.esm-bundler.js:5805
    mount runtime-core.esm-bundler.js:3062
    mount runtime-dom.esm-bundler.js:1530
    <anonymous> main.ts:41
15:36:02.731
Error: Invalid ComfyNodeDef: {"input":{"required":{"text":["STRING",{"forceInput":true}],"substring":["STRING",{"default":"","multiline":false}],"pattern":["STRING",{"default":"","multiline":false}]}},"output":"BOOLEAN","output_is_list":[false,false,false,false,false,false,false],"output_name":"found","name":"Text Find","display_name":"Text Find","description":"","python_module":"custom_nodes.was-node-suite-comfyui","category":"WAS Suite/Text/Search","output_node":false}
Validation error: Expected array, received string at "output"; Expected array, received string at "output_name"
    validateComfyNodeDef apiTypes.ts:292
    getNodeDefs api.ts:253
    registerNodes app.ts:1968
    registerNodes workflow-component.js:328
    setup app.ts:1901
    setup GraphCanvas.vue:45
    createHook runtime-core.esm-bundler.js:1808
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:1788
    flushPostFlushCbs runtime-core.esm-bundler.js:379
    render3 runtime-core.esm-bundler.js:5805
    mount runtime-core.esm-bundler.js:3062
    mount runtime-dom.esm-bundler.js:1530
    <anonymous> main.ts:41
Caused by: ZodValidationError: Validation error: Expected array, received string at "output"; Expected array, received string at "output_name"
    ValidationError index.mjs:11
    fromZodErrorWithoutRuntimeCheck index.mjs:207
    fromZodError index.mjs:186
    validateComfyNodeDef apiTypes.ts:291
    getNodeDefs api.ts:253
    registerNodes app.ts:1968
    registerNodes workflow-component.js:328
    setup app.ts:1901
    setup GraphCanvas.vue:45
    createHook runtime-core.esm-bundler.js:1808
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:1788
    flushPostFlushCbs runtime-core.esm-bundler.js:379
    render3 runtime-core.esm-bundler.js:5805
    mount runtime-core.esm-bundler.js:3062
    mount runtime-dom.esm-bundler.js:1530
    <anonymous> main.ts:41
Caused by: ZodError: [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "string",
    "path": [
      "output"
    ],
    "message": "Expected array, received string"
  },
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "string",
    "path": [
      "output_name"
    ],
    "message": "Expected array, received string"
  }
]
    ZodError index.mjs:164
    get error index.mjs:587
    validateComfyNodeDef apiTypes.ts:291
    getNodeDefs api.ts:253
    registerNodes app.ts:1968
    registerNodes workflow-component.js:328
    setup app.ts:1901
    setup GraphCanvas.vue:45
    createHook runtime-core.esm-bundler.js:1808
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:1788
    flushPostFlushCbs runtime-core.esm-bundler.js:379
    render3 runtime-core.esm-bundler.js:5805
    mount runtime-core.esm-bundler.js:3062
    mount runtime-dom.esm-bundler.js:1530
    <anonymous> main.ts:41

**Comment by mcmonkey4eva** [comment]
@tpcdaz if you want a friendlier frontend to the Comfy core you can use https://github.com/mcmonkeyprojects/SwarmUI

**Comment by huchenlei** [comment]
@Creative-comfyUI 

The impact pack def is fixed in the latest version. 
https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/674

The WAS def is still an unmerged PR to fix. 
https://github.com/WASasquatch/was-node-suite-comfyui/pull/440

These erorr messages only affect the corresponding node only. If you don't use these nodes. You should be fine.

**Comment by Creative-comfyUI** [comment]
> @Creative-comfyUI
> 
> The impact pack def is fixed in the latest version. [ltdrdata/ComfyUI-Impact-Pack#674](https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/674)
> 
> The WAS def is still an unmerged PR to fix. [WASasquatch/was-node-suite-comfyui#440](https://github.com/WASasquatch/was-node-suite-comfyui/pull/440)
> 
> These erorr messages only affect the corresponding nodes only (Not the whole pack). If you don't use these nodes. You should be fine.

That is, if I disable these nodes, will I see the new interface?  I hope WAS will fix it before the release date

**Comment by huchenlei** [comment]
> > @Creative-comfyUI
> > The impact pack def is fixed in the latest version. [ltdrdata/ComfyUI-Impact-Pack#674](https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/674)
> > The WAS def is still an unmerged PR to fix. [WASasquatch/was-node-suite-comfyui#440](https://github.com/WASasquatch/was-node-suite-comfyui/pull/440)
> > These erorr messages only affect the corresponding nodes only (Not the whole pack). If you don't use these nodes. You should be fine.
> 
> That is, if I disable these nodes, will I see the new interface? I hope WAS will fix it before the release date

The new frontend is replacing the underlying code. You should still see the same ComfyUI interface you use in the legacy JS. There is a beta UI in progress, which is not part of this release, but you are welcomed to try it:
![image](https://github.com/user-attachments/assets/f1ae2aef-bca1-4ef7-b110-d5952f6356d0)

The node def errors you see in the console do not block the normal functionality of the other frontend code.

**Comment by ofersadgat** [comment]
@comfyanonymous @huchenlei the main feature I'm looking for is subgraphs. i.e. the ability to hide parts of the graph in subcomponents (or even have workflows themselves be subgraphs) so that we can compose things without creating monstrosities. @space-nuko @rsamf have both worked on their own versions of this, but with this rewrite will we get an officially supported version of this? thanks!

**Comment by ltdrdata** [comment]
> @comfyanonymous @huchenlei the main feature I'm looking for is subgraphs. i.e. the ability to hide parts of the graph in subcomponents (or even have workflows themselves be subgraphs) so that we can compose things without creating monstrosities. @space-nuko @rsamf [have both worked on their own versions of this](https://github.com/comfyanonymous/ComfyUI/issues/669) , but with this rewrite will we get an officially supported version of this? thanks!

While it's not happening immediately, we are developing a roadmap for frontend improvements through various discussions.

**Comment by hdworkstation103** [comment]
> Is the new frontend still noodle junction or is it actually made for regular people now?
> 
> EDIT : Never mind just tried it and noticed it's still made without regular users in mind.

The limitations of the current vanilla framework are hindering the dev's ability to enhance user friendliness. Building a robust frontend is challenging when the underlying foundation is not optimal.

The new frontend aims to address these issues, among other enhancements. A recent improvement in regards to user friendliness is the addition of tooltips that appear when hovering over nodes.

While these changes take time, recent commits that the developers have made indicate they are working at a very fast pace.

**Comment by amimi818** [comment]
Love the new UI!
In addition, can the menu bar on the left be made left and right selectable?

**Comment by gisu** [comment]
I like the new UI Direction, but with over 1000 custom nodes and ZOD schema to validate the types, I see a lot of problems coming up for people. If one of the nodes works against the ZOD scheme, the workflow will no longer work. The majority of users will not have any dev experience and will struggle with debugging.

**Comment by dchatel** [comment]
Any plans on building a custom text area that doesn't use the html one? In order to avoid that ugly thing where the textareas' z-index takes precedence over anything else on the canvas.

**Comment by siliconecomputervision** [comment]
Awesome. Just wondering if you will/already are implementing a new font or the ability for the end user to select a font.

Many thanks!

**Comment by davoodice** [comment]
Haw can we access to manager?

**Comment by ltdrdata** [comment]
> Haw can we access to manager?

![image](https://github.com/user-attachments/assets/a55c321b-805a-4bab-86e3-ed1be9a45738)

**Comment by ltdrdata** [comment]
> > Haw can we access to manager?
> 
> ![image](https://private-user-images.githubusercontent.com/128333288/356237837-a55c321b-805a-4bab-86e3-ed1be9a45738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjM1MTYsIm5iZiI6MTcyMzEyMzIxNiwicGF0aCI6Ii8xMjgzMzMyODgvMzU2MjM3ODM3LWE1NWMzMjFiLTgwNWEtNGJhYi04NmUzLWVkMWJlOWE0NTczOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMzIwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDU2ZDdiOGMwOGEzMjZhNjFhZWY2NzRkZmUzYzExYjA2MzJjNzk0N2FlYWMwYjQwMWI0YmVlZWE1YjdhNDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pe3Uja1hUP4SAOiCOcNvo8w_84ZWzFkkWYJEXnmckwQ)

Manager support New UI, already.

**Comment by huchenlei** [comment]
> I like the new UI Direction, but with over 1000 custom nodes and ZOD schema to validate the types, I see a lot of problems coming up for people. If one of the nodes works against the ZOD scheme, the workflow will no longer work. The majority of users will not have any dev experience and will struggle with debugging.

The node def validation only drop the nodes with invalid defs. It should not block you using rest of nodes. We have tested most popular node packs and submitting fixing PRs to their repos to fix a few invalid defs. Please make sure you custom nodes are updated to include these fixing PRs.

**Comment by davoodice** [comment]
> > Haw can we access to manager?
> 
> ![image](https://private-user-images.githubusercontent.com/128333288/356237837-a55c321b-805a-4bab-86e3-ed1be9a45738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjU5MDIsIm5iZiI6MTcyMzEyNTYwMiwicGF0aCI6Ii8xMjgzMzMyODgvMzU2MjM3ODM3LWE1NWMzMjFiLTgwNWEtNGJhYi04NmUzLWVkMWJlOWE0NTczOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNDAwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDU3MWRlOTJkOWJjNWFmYjViNjE1ZTkyNWE2NWM4NTE4MzNjMDBiYzIxZmU2OTMzZjFkNjAyNDgzY2I5MWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pHUYWdBEYkw2rq1nSPAw2c3qTmTEqCY2bEpkTKi01lE)
> 
> Manager supports New UI, already.

![image](https://github.com/user-attachments/assets/4c1966d7-2329-41e3-ab0a-3399c08e790d)
]
I cant see that

**Comment by huchenlei** [comment]
> > > Haw can we access to manager?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/128333288/356237837-a55c321b-805a-4bab-86e3-ed1be9a45738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjU5MDIsIm5iZiI6MTcyMzEyNTYwMiwicGF0aCI6Ii8xMjgzMzMyODgvMzU2MjM3ODM3LWE1NWMzMjFiLTgwNWEtNGJhYi04NmUzLWVkMWJlOWE0NTczOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNDAwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDU3MWRlOTJkOWJjNWFmYjViNjE1ZTkyNWE2NWM4NTE4MzNjMDBiYzIxZmU2OTMzZjFkNjAyNDgzY2I5MWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pHUYWdBEYkw2rq1nSPAw2c3qTmTEqCY2bEpkTKi01lE)
> > Manager supports New UI, already.
> 
> ![image](https://private-user-images.githubusercontent.com/68325902/356253554-4c1966d7-2329-41e3-ab0a-3399c08e790d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjYxMTAsIm5iZiI6MTcyMzEyNTgxMCwicGF0aCI6Ii82ODMyNTkwMi8zNTYyNTM1NTQtNGMxOTY2ZDctMjMyOS00MWUzLWFiMGEtMzM5OWMwOGU3OTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE0MDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMGJkNTc0NDg3YWUwNjMzYjI0ZDI5NGI2N2FjMWY2YmNhNTI2OTI3MGFlYTg1YTA3NWRlNWY5ZmI0MzkxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PWjHN4ZNszAhJwYLLQPYZvTvQEp97rWOTJUEIHZ1nb4) ] I cant see that

You probably need to update your ComfyUI manager.

**Comment by davoodice** [comment]
yes. you are right.

**Comment by davoodice** [comment]
did we lost the search button? (when we drag from an output slot)
![image](https://github.com/user-attachments/assets/586e1d14-2563-4744-8f4d-ac3d2eb67f58)
![image](https://github.com/user-attachments/assets/d480e5d4-3116-4c89-9e55-8bab035aa079)

**Comment by CambridgeComputing** [comment]
> did we lost the search button? (when we drag from an output slot)

I can confirm this, the search is missing. Was it removed or just temporarily missing?

**Comment by davoodice** [comment]
![image](https://github.com/user-attachments/assets/fd0af61b-f836-495c-8700-b4c7751fd5ea)
 I think this menu should open to above itself.

**Comment by CambridgeComputing** [comment]
Just played for a few hours, and I'm unable to copy nodes and paste them. Right click menu is missing the Paste (Clipspace) option after right clicking on a node and selecting Copy (Clipspace).

**Comment by huchenlei** [comment]
> > did we lost the search button? (when we drag from an output slot)
> 
> I can confirm this, the search is missing. Was it removed or just temporarily missing?

Release with shift brings up the searchbox. We might want to make that as default behavior without shift later.

**Comment by davoodice** [comment]
I am sure I could do simple mathematic operation directly inside numeric fields, but now it is not possible. It's awesome if this feature back. (for example: making a field double by typing *2 in that field)

**Comment by raysers** [comment]
大神好！我用前面提到的命令行先行体验了一下，发现比起旧版AI最不便的是节点搜索功能，对我这样的英文菜鸟不甚友好。中文使用人数众多，中文用户一般都会安装汉化插件，旧版在搜索节点的时候十分便捷，可以直接中文搜索，而新版仅剩下英文搜索功能，当然我也尝试了在搜索框里输入中文，但搜到的结果为0

**Comment by ltdrdata** [comment]
> Just played for a few hours, and I'm unable to copy nodes and paste them. Right click menu is missing the Paste (Clipspace) option after right clicking on a node and selecting Copy (Clipspace).

In my tests, there are no issues. Disable all custom nodes, restart, then refresh the browser and test again.

**Comment by huchenlei** [comment]
> 大神好！我用前面提到的命令行先行体验了一下，发现比起旧版AI最不便的是节点搜索功能，对我这样的英文菜鸟不甚友好。中文使用人数众多，中文用户一般都会安装汉化插件，旧版在搜索节点的时候十分便捷，可以直接中文搜索，而新版仅剩下英文搜索功能，当然我也尝试了在搜索框里输入中文，但搜到的结果为0

You can still fall back to the litegraph searchbox in the new frontend. Probably the translation extension author need to followup with us to support translation in the new UI.
![image](https://github.com/user-attachments/assets/89075db3-b4e5-4ac6-ba23-dd1782b423dc)

**Comment by aaqiming** [comment]
> 大神好！我用前面提到的命令行先行体验了一下，发现了林旧版AI最不便的是节点搜索功能，对我这样的英文菜鸟不甚友好。中文使用人数群体，中文用户一般都会安装汉化插件，旧版在搜索节点的时候十分便捷，可以直接中文搜索，而新版只剩下英文搜索功能，当然我也尝试了在搜索框里输入中文，但搜到的结果为0

+加1

**Comment by wcde** [comment]
> with over 1000 custom nodes and ZOD schema to validate the types, I see a lot of problems coming up for people

I have only 140 custom node packs and new UI already doesn't work, just black screen. I see huge number of errors in browser console, first of which is from Impact-Pack. I don't even want to try to debug this piece of broken code, even though I could. I'll just sit on old UI as long as possible. ComfyUI didn't have stable API before and nodes were constantly breaking after updates, but now something really sad is happening.

**Comment by ltdrdata** [comment]
> > with over 1000 custom nodes and ZOD schema to validate the types, I see a lot of problems coming up for people
> 
> I have only 140 custom node packs and new UI already doesn't work, just black screen. I see huge number of errors in browser console, first of which is from Impact-Pack. I don't even want to try to debug this piece of broken code, even though I could. I'll just sit on old UI as long as possible. ComfyUI didn't have stable API before and nodes were constantly breaking after updates, but now something really sad is happening.

It's strange. I use Impact Pack every day, and I'm not experiencing any issues.

**Comment by hartmark** [comment]
When I restart ComfyUI I get this error.
![image](https://github.com/user-attachments/assets/d7dd2c27-060a-41eb-ab70-d188dc120238)

However if I click the load button for temp under "browse" list at the bottom it loads the latest save and it loads perfectly. The thing is that I have already saved it before shutting down ComfyUI so selecting temp from "open" fails before loading it from "browse" section.
![image](https://github.com/user-attachments/assets/c75785d2-4695-42c5-aff6-652a9e590c1f)

It's a bit of an annoyance, but as long as I remember to save often I can recover my view when I restart ComfyUI

**Comment by hartmark** [comment]
Sometimes I get this layout:
![image](https://github.com/user-attachments/assets/a625f3b3-7ac2-4985-86db-f7d8a3370a4f)

This layout is missing the history list.

There's another view that I have gotten aswell that has the history list but I have this with both top and left bar. The other layout had only a top bar. I have 1440p resolution so I think that should be enough for that layout?

**Comment by hartmark** [comment]
I also get these errors in the log:
![image](https://github.com/user-attachments/assets/fb565a90-af39-4ccf-a719-2d04bdef1a62)

**Comment by hartmark** [comment]
Hmm, is it okay to just post the bugs here or should I create separate issues for them?

**Comment by ManOrMonster** [comment]
I have about 120 custom nodes. After updating everything yesterday and trying out the new UI for the first time, I had several issues and had to revert to the legacy UI using the command line argument. Reverting to legacy UI made everything go back to normal.

First, it took quite a while to load the interface, and after loading, this Vue overlay doesnt go away. I have to tell it to "display: none" in devtools before I can use Comfy:
`<div style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 1101;" class="p-blockui-mask p-overlay-mask p-overlay-mask-enter p-blockui-mask-document" data-pc-section="mask"></div>`
Even after that, the circle loading image in the middle keeps animating. I left it sitting for several minutes to see it it would ever think it's done loading, but no luck.

The Manager UI is missing from the bar. I'm unable to access it.

The crystools RAM/GPU/VRAM display is missing from the bar.

Rgthree's bypassers/muter nodes are red.

The Note node is even red.

**Comment by Humanoidme** [comment]
@comfyanonymous @huchenlei gents, I came across this new front end framework and made me think about comfyui's new interface. Have you consider this when you decided on TypeScript, Vue, and Vite ? https://fastht.ml/

**Comment by 1038lab** [comment]
![image](https://github.com/user-attachments/assets/1f2cab30-7daa-41c2-b3ff-bd708faf3941)
dont like this 9/23 new UI,  why make a Huge queue button and hide "refresh, clipspace, reset view and clear"

when export png, no background lower right corner 
![workflow](https://github.com/user-attachments/assets/da723840-bb54-4e11-9bbe-7e9cd037ee5c)

Last version looks great, how to check it back?
