### ISSUE TITLE
Flux files can't be recognized

### ISSUE THREAD

**Issue by kawaii2020** [comfyanonymous/ComfyUI#4178]
### Your question

![image](https://github.com/user-attachments/assets/e58b6202-87bf-4acf-ae27-f5a660697253)

![image](https://github.com/user-attachments/assets/84190ffc-7963-41e3-8c06-aca1fa76e9c1)

![image](https://github.com/user-attachments/assets/48492639-c068-4a17-8f06-837c756e6fb8)

the .sft files have been put into the right place, but can't be recognized.

**Comment by ltdrdata** [comment]
Your ComfyUI is outdated version.

**Comment by kawaii2020** [comment]
![image](https://github.com/user-attachments/assets/620ba05f-4431-47c9-be97-9e294db5f193)


wait, dude!  what should I do?

**Comment by ltdrdata** [comment]
> ![image](https://private-user-images.githubusercontent.com/32961592/354701084-620ba05f-4431-47c9-be97-9e294db5f193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjY1NTcsIm5iZiI6MTcyMjYyNjI1NywicGF0aCI6Ii8zMjk2MTU5Mi8zNTQ3MDEwODQtNjIwYmEwNWYtNDQzMS00N2M5LWJlOTctOWUyOTRkYjVmMTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE5MTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYTdkZTM4MWYwOGNjYjU0YjJlYjE2NTZkNjgxZDI3YTBjYzUxYjAwOWE0MTk5YjQxMTI3ZGNjN2FiYTA3NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jY4R2LjVZWVpYM8qc4deJJV_CsxUwDTSIj1DRCo3nq8)
> 
> wait, dude! what should I do?

This issue occurred because you modified some files.
You can check which files were modified by running `git status` in the ComfyUI directory.

Typically, you can undo the modifications using `git reset --hard`, but if that doesn't work, you'll need to handle it manually.

**Comment by kawaii2020** [comment]
solved it by downloading and overwriting all comfyui files.
thank you.
