### ISSUE TITLE
ComfyUI dos not see the Flux model

### ISSUE THREAD

**Issue by protector131090** [comfyanonymous/ComfyUI#4181]
### Expected Behavior

Comfu sees the checkpoint

### Actual Behavior

![Снимок экрана (3091)](https://github.com/user-attachments/assets/89061810-3cf5-4dd1-ab9a-5008961605f4)
ComfyUI does not see any checkpoints. Checkpoint is in checkpoint folder

### Steps to Reproduce

![Снимок экрана (3091)](https://github.com/user-attachments/assets/89061810-3cf5-4dd1-ab9a-5008961605f4)
ComfyUI does not see any checkpoints. Checkpoint is in checkpoint folder

### Debug Logs

```powershell
![Снимок экрана (3091)](https://github.com/user-attachments/assets/89061810-3cf5-4dd1-ab9a-5008961605f4)
ComfyUI does not see any checkpoints. Checkpoint is in checkpoint folder
```

**Comment by huchenlei** [comment]
update your ComfyUI to latest version.

**Comment by protector131090** [comment]
> update your ComfyUI to latest version.

its updated. Not updated does not recognise the nodes. This one recognises the nodes. Vae is fine but Checkpoint it doesnt see. i have 2 installs of comfy and they both same.

**Comment by ltdrdata** [comment]
FLUX model isn't checkpoint. That model should be placed into `models/unet` instead of `models/checkpoint`

**Comment by gisu** [comment]
Same here. Updated to the last ComfyUI Version (several updates now). Had no Flux Nodes, FluxGuidance Nodes also not available. Unet Models are in model/unet. The Unet Loader wont show flux-schnell.sft. Used the Workflows from the example, nothing works.
![image](https://github.com/user-attachments/assets/e18cae55-6182-4da3-b3c9-d126fa1cb822)

![image](https://github.com/user-attachments/assets/d0bbe159-41a4-4879-bb1e-f6d5b2ad44ae)

**Comment by ltdrdata** [comment]
> Same here. Updated to the last ComfyUI Version (several updates now). Had no Flux Nodes, FluxGuidance Nodes also not available. Unet Models are in model/unet. The Unet Loader wont show flux-schnell.sft. Used the Workflows from the example, nothing works. ![image](https://private-user-images.githubusercontent.com/442468/354828270-e18cae55-6182-4da3-b3c9-d126fa1cb822.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDM5MzcsIm5iZiI6MTcyMjcwMzYzNywicGF0aCI6Ii80NDI0NjgvMzU0ODI4MjcwLWUxOGNhZTU1LTYxODItNGRhMy1iM2M5LWQxMjZmYTFjYjgyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNjQ3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmY5MWY4MTQzNWMxNDFlMmRlNGRiMDU0YTdjOTYyZTBiMGJiOWMwNjYwMGVhNjY2Yjg1NjUyNzA1MGIzOWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cHv-3nVpRoqNlyGErEf_n-fO5udSi5ezB53SjlVHLz8)
> 
> ![image](https://private-user-images.githubusercontent.com/442468/354828196-d0bbe159-41a4-4879-bb1e-f6d5b2ad44ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDM5MzcsIm5iZiI6MTcyMjcwMzYzNywicGF0aCI6Ii80NDI0NjgvMzU0ODI4MTk2LWQwYmJlMTU5LTQxYTQtNDg3OS1iYjFlLWY2ZDViMmFkNDRhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNjQ3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmJhN2YxM2VhMTU0ZDM5YzgxYmY5N2Q1NWZmZjk5Yzc4NjlmMDExODIwODFkZTk3YWI2ZmY4MjQyY2NhMmRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kit1S4K-6W2y53I_EePRsKvjCUt5t07C36JLd1DUIig)

If you can see `UNETLoader` node. Your ComfyUI is outdated version.
That node is renamed to `Load Diffusion Model`.
