### ISSUE TITLE
Image preview shows the last image, on the first step.

### ISSUE THREAD

**Issue by JorgeR81** [comfyanonymous/ComfyUI#4183]
**EDIT:**

This is also happening with other models ( e.g. SD1.5 ), not only Flux ...
I noticed it on Flux first, because it's slower ... 

### Expected Behavior

 When using the Flux models, the Sampler node shows the image preview starting from step 1.

### Actual Behavior

In the first step preview, we see the last step from the previous generation. 
And in the first image generation it shows a black image, as a preview for the first step.

This is a minor issue.
The preview works fine after the first step. 

---

At step 1 the Sampler node shows the final preview from the last generation.

![flux1](https://github.com/user-attachments/assets/7ff79afc-4b4e-4c28-b12f-0b3dc1879423)

From Step 2 onwards, the preview works correctly. 

![flux3](https://github.com/user-attachments/assets/09afad57-0262-425f-b813-3e1bc3e1813d)

![flux6](https://github.com/user-attachments/assets/4b32221c-3da0-495e-99e5-8074e4da2ecf)

### Steps to Reproduce

Tested on the Flux example workflows.
The preview method is set to "Auto", in the Manager. 

### Debug Logs

```powershell
( No errors are shown in the terminal )
```

**Comment by ltdrdata** [comment]
I also experience this phenomenon occasionally. It seems to be occurring since the introduction of async to the preview.

**Comment by JorgeR81** [comment]
This seems to be fixed now.

Also, after this commit ( https://github.com/comfyanonymous/ComfyUI/commit/1770fc77ed91348f4060e3c0b040c1519d6f91d0 ) I added the `taef1` files, and the Flux preview was greatly improved. 

https://github.com/madebyollin/taesd
