### ISSUE TITLE
Memory Optimization issue since "Better Flux vram estimation" update

### ISSUE THREAD

**Issue by Djanghost** [comfyanonymous/ComfyUI#4184]
### Expected Behavior

Being able to render

### Actual Behavior

The PC slows down at the KSampler step and nothing happens. If i wait a while, a memory allocation error message appears (RTX4090 / 64Gb RAM)

### Steps to Reproduce

Simply by updating ComfyUI. The problem appears at commit 47da42d9283815a58636bd6b42c0434f70b24c9c

### Debug Logs

```powershell
Nothing as nothing happens
```

### Other
Using KSamplerAdvancedProgress //Inspire with AYS Scheduler with LCM sampler.

_No response_

**Comment by JorgeR81** [comment]
To use Flux you need the [ SamplerCustomAdvanced ] node

https://comfyanonymous.github.io/ComfyUI_examples/flux/

**Comment by Djanghost** [comment]
> To use Flux you need the [ SamplerCustomAdvanced ] node
> 
> https://comfyanonymous.github.io/ComfyUI_examples/flux/

I don't use Flux

**Comment by JorgeR81** [comment]
OK, I see, ... so this happens on other models, after the "Better Flux vram estimation" update.

I just tried the KSampler Advanced Progress (Inspire) node, with SD1.5, and it works for me. 
I'm on Windows 10. 

![insp](https://github.com/user-attachments/assets/d475c2b2-9af6-4ae6-9c4a-c714b979ee8f)

**Comment by Djanghost** [comment]
Thank you @JorgeR81 . So maybe the scheduler is the problem, i'm using AYO 1.5 with lcm :
![Capture d'écran 2024-08-03 154527](https://github.com/user-attachments/assets/6fc17829-b0a6-49bc-987b-6dc7160223d5)

**Comment by comfyanonymous** [comment]
Can you test if things are improved now?

**Comment by Djanghost** [comment]
> Can you test if things are improved now?

I'm in the middle of a render, i tell you this in a few minutes and will edit this message, thank you !

**Comment by Djanghost** [comment]
> Can you test if things are improved now?

Still not, looks like an OOM error : 
![Capture d'écran 2024-08-03 181629](https://github.com/user-attachments/assets/523773f2-4ff3-43f1-9e7e-a94b2562c9fc)

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/sampler_helpers.py#L64

If you change:

`memory_required = model.memory_required([noise_shape[0] * 2] + list(noise_shape[1:])) + inference_memory`

to:

`memory_required = model.memory_required([noise_shape[0] * 4] + list(noise_shape[1:])) + inference_memory`

Does that fix it?

**Comment by Djanghost** [comment]
Going to test but i notice a weird thing. If i revert to the right ComfyUI commit (for me it's 17bbd83176268c76a8597bb3a88768d325536651), but without revert to the right Impact Pack commit too, i also get an error : 

![Capture d'écran 2024-08-03 183756](https://github.com/user-attachments/assets/f3ac1323-34c4-4b23-bdcd-89f65926cb51)

**Comment by Djanghost** [comment]
> memory_required = model.memory_required([noise_shape[0] * 4] + list(noise_shape[1:])) + inference_memory

And yes the same OOM error appears with this tweak too

**Comment by Djanghost** [comment]
As mentioned here after many tests https://github.com/ltdrdata/ComfyUI-Inspire-Pack/issues/135 : 

Everything works fine when I have these commits:

ComfyUI: 17bbd83176268c76a8597bb3a88768d325536651
Inspire pack: https://github.com/ltdrdata/ComfyUI-Inspire-Pack/commit/cf9bae0718c42077722a66269d6b4f2424b255c2

Updates following these commits crash the KSamplerAdvancedProgress //Inspire node when using AYS Scheduler with LCM sampler. Hope it helps, i revert back to the right commits waiting a fix. Thank you!

**Comment by rabidcopy** [comment]
It's kinda fun to have Flux cause issues for people not even inferencing it. Everything was fine before it was implemented. Oh well.

**Comment by comfyanonymous** [comment]
There has been some optimizations to the lowvram mode which should speed things up for most people. If you have issues you need to post your hardware and which model you are using.

**Comment by rabidcopy** [comment]
Cascade is still 1.5-2 seconds per iteration slower on DirectML on a 4GB RX 570. I don't expect a meaningful fix because DirectML support is an afterthought at this point and requires a line change in model_management.py (`    lowvram_available = True #TODO: need to find a way to get free memory in directml before this can be enabled by default.
`, setting this to True made 4GB seemingly work for everything ranging from SD, SDXL, SD3, and Cascade with performance comparable to ROCM on Linux if not slightly better) to even work on 4GB.  ROCM on Linux was already slower in general before the changes. I'll just chalk it as user error. It probably is unreasonable to expect low-end hardware edge cases to be supported.

**Comment by Djanghost** [comment]
> There has been some optimizations to the lowvram mode which should speed things up for most people. If you have issues you need to post your hardware and which model you are using.

I use an RTX4090 + 64gb RAM. Before the update, everything worked perfectly. Until yesterday, on my current project I could render batches between 200 and 250 frames (depending on the number of cn I was using) at a resolution of 1256x712. If i update I can't even render 50 frames sadly. 
The problem i mention is not visible if you only render one frame, it concerns videos actually maybe i should have mention it.

**Comment by comfyanonymous** [comment]
Does the change I made you do above have any effect on the number of frames you can do?

**Comment by Djanghost** [comment]
> Does the change I made you do above have any effect on the number of frames you can do?

No, i tested them all and they are no effect, PC barely freeze and i've got the same OOM message.

**Comment by rabidcopy** [comment]
> Edit2: [d420bc7](https://github.com/comfyanonymous/ComfyUI/commit/d420bc792af0b61a6ef7410c65fa2d4dcc646c56) is the exact commit that I start having speed degradation on Cascade.

My speed and OOM issue goes away on latest commit simply reverting `model_base.py` to https://github.com/comfyanonymous/ComfyUI/raw/1589b58d3e29e44623a1f3f595917b98f2301c3e/comfy/model_base.py

AFAIK my issues weren't caused at all by the lowvram changes in `model_management.py`, just d420bc792af0b61a6ef7410c65fa2d4dcc646c56

Not sure if this could be the culprit of the problem in this issue thread specifically, but I narrowed it down in my own situation.

**Comment by Djanghost** [comment]
Nice you solved your problem, unfortunately it doenst work the problem here. Thanks for sharing though !

**Comment by Djanghost** [comment]
EDIT : after many new tests following all different repo updates, ComfyUI doesn't seem to be the problem anymore. The problem apparently comes from Impact pack. Waiting for an answer from ltdrdata to get confirmation before closing this thread.

**Comment by zhangifonly** [comment]
I have the same question. Run the Comfuyi alone to solve the problem.
