### ISSUE TITLE
Increasing hires-fix resolution to 2x produces blank image

### ISSUE THREAD

**Issue by oakif** [comfyanonymous/ComfyUI#419]
When modifying the resolution of the hires-fix image [here](https://github.com/comfyanonymous/ComfyUI_examples/tree/master/2_pass_txt2img) from 1152x1152 to 1600x1600, the output turns blank. A lower resolution such as 1200x1200 still works.

**Comment by comfyanonymous** [comment]
Are you on the latest ComfyUI code?

This might be related to: https://github.com/comfyanonymous/ComfyUI/issues/394

**Comment by oakif** [comment]
My bad, I missed that issue. When I posted this issue, I had been using the latest version of ComfyUI. I will close this issue as it's a duplicate.
