### ISSUE TITLE
Mouse scrolling in add nodes menu is painfully slow (Linux)

### ISSUE THREAD

**Issue by crotalidae75** [comfyanonymous/ComfyUI#4193]
### Expected Behavior

I expected the mouse wheel scrolling to be of reasonable speed, similar to other programs, when scrolling up and down through the add nodes menu.  

### Actual Behavior

The actual speed of the scrolling in the menu, on my machine, under Linux (Kubuntu 24.04) is much too slow and is rather annoying.  Like many of us, I have a lot of nodes in my menu and it actually takes 20 mouse wheel scrolls with my middle finger to get to the top.  That's too much, and takes far too long to navigate through. It moves only about 2-4 list entries up or down per full scroll with my finger, depending on my zoom level.  I included a screenshot - the left is when I open up the add nodes menu, and on the right is the position after one mouse wheel scroll - it only moved a mere two entries.  Although I had to re-open the menu to take the second image (on the right), I started where the entry to the right of 'Add Node' is the same (Optical Flow). 

![slowscroll](https://github.com/user-attachments/assets/41e97082-bce2-4836-915c-90b9f6a32652)

### Steps to Reproduce

Not sure.  Might be an issue on Linux alone? I haven't used ComfyUI on Windows.

### Debug Logs

```powershell
No debug logs. I doubt they're of use in this case.
```

### Other

Is there some way to find and edit the mouse wheel scrolling in the source?

**Comment by gobshyte** [comment]
It is horrendously slow (and inverted) in all sub menus, very painful with lots of Loras. 

I used to use a workaround from here:
https://www.reddit.com/r/comfyui/comments/16wbok0/so_is_there_a_fix_for_the_abysmal_scrolling_in/

However \ComfyUI\web\lib\litegraph.core.js no longer exists, so I am at a loss now :(

**Comment by ltdrdata** [comment]
Please move this issue to frontend repo.
https://github.com/Comfy-Org/ComfyUI_frontend/issues
