### ISSUE TITLE
Alternative UI

### ISSUE THREAD

**Issue by jac3km4** [comfyanonymous/ComfyUI#42]
Hi,
This isn't really an issue, but more of a question. I've been using a fork of your repo with various changes applied on top of it. One of them is [a quick prototype of a React/TailwindCSS interface](https://github.com/jac3km4/comfyweb) with slightly altered UI elements and things like a gallery view. I intend to maintain it and use it for my own purposes, but I can contribute it back to your repo if you wish.
I have a ready-to-use demo branch available here that only makes minimal changes to your existing code: https://github.com/jac3km4/ComfyUI/tree/reactui

Let me know if you'd be interested in integrating it. If not, feel free to close this PR.

**Comment by comfyanonymous** [comment]
I'm going to have to make a list of UIs somewhere because you are not the only one making one. 

I love people using the backend to make their own UIs. I encourage it.

With how things are going it might be best for the main repo to have a simple "reference" UI but nothing is decided yet.

**Comment by oakif** [comment]
@jac3km4 I love your UI! I created an issue #36 about poor scaling on my 4K monitor, and it looks like your UI doesn't have that problem at all. I also really like the way the output images are presented in the UI.

@comfyanonymous It would be great to create a list of alternative UIs. I'm curious what others are doing.

**Comment by VOOM108** [comment]
I have some issues with the UI, but I don't understand how to install the alternative UI mentioned here, so it works together with the portable download for Windows. I tried cloning the repo on top of the previous instance, but that did not work...

**Comment by nistvan86** [comment]
Wow, this looks really nice! With the added problem of diverging codebases. But still.

**Comment by skyler14** [comment]
> I'm going to have to make a list of UIs somewhere because you are not the only one making one.
> 
> I love people using the backend to make their own UIs. I encourage it.
> 
> With how things are going it might be best for the main repo to have a simple "reference" UI but nothing is decided yet.

is there any update on this list, I saw OPs repo but am a bit sad to see it's a month stale and probably not being developed much more
