### ISSUE TITLE
When using cancel button, models aren't unloaded from VRAM

### ISSUE THREAD

**Issue by BassJMagan** [comfyanonymous/ComfyUI#4203]
### Expected Behavior

I expect presssing cancel to be the same as having a batch be completed normally, all things unloaded and not taking all sys resources.

### Actual Behavior

Pressing cancel leads VRAM for instance to still be 22/24GB VRAM on Flux, and I believe this leads to sometimes when trying to make an image after the s/it shoot waaay up from 2-3 s/it on a 3090 to 10-20s/it or worse. The issue is solved by restarting but very inconvenient if i want to try a lot of diff ideas and queue up generations and want to cancel midway to change prompt.

### Steps to Reproduce

Queue up multiple images to be generated, then cancel them all while it's still well into the generation process.

### Debug Logs

```powershell
n/a
```

**Comment by mcmonkey4eva** [comment]
Cancelling a queue entry does not unload models

**Comment by BassJMagan** [comment]
this wasn't really an issue before but with the flux model taking up 22gb vram by itself without being actively used, isn't there something that could be added to make this happen? else I have to never use the cancel button at any point pretty much.

**Comment by ltdrdata** [comment]
> this wasn't really an issue before but with the flux model taking up 22gb vram by itself without being actively used, isn't there something that could be added to make this happen? else I have to never use the cancel button at any point pretty much.

If you mute/remove the node that loaded the flux model and execute the workflow, it will be removed from the cache and unloaded
