### ISSUE TITLE
Cannot import ComfyUI-Logic

### ISSUE THREAD

**Issue by mikebilly** [comfyanonymous/ComfyUI#4204]
### Expected Behavior

It should be imported normally. (not showing red)

### Actual Behavior

Shows red, no matter how I install it. Issue happened after I updated to the latest version of ComfyUI and ComfyUI-Manager (V2.48.5) and Comfy-Org_ComfyUI_frontend/1.2.9
ComfyUI Revision: 2464 [0a6b0081] | Released on '2024-08-04'
![image](https://github.com/user-attachments/assets/acca6a6e-3b6e-427d-baee-7ad2c3b3fa02)

### Steps to Reproduce

Latest versions of ComfyUI and ComfyUI-Manager. Then go to Install Missing Custom Nodes to install Comfy-Logic (because I'm working on a workflow that already uses Comfy-Logic)

### Debug Logs

```powershell
n/a
```

**Comment by mcmonkey4eva** [comment]
This is an issue with presumably the comfy-logic nodepack, not comfy's core
