### ISSUE TITLE
Failed to validate prompt for output 32:

### ISSUE THREAD

**Issue by jdc4429** [comfyanonymous/ComfyUI#4213]
### Your question

I am getting the following error when trying to call my python code to use the API:

Prompt executed in 0.67 seconds
got prompt
Failed to validate prompt for output 32:
* LoadImage 3:
  - Custom validation failed for node: image - Invalid image file: 1GIMSOIM.jpg
Output will be ignored
Failed to validate prompt for output 33:
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

I saved the workflow API after running the workflow and added to my python code.
I know these are the save file nodes but I don't understand how to get it to accept my filename and execute.  It worked the first time I did it but then when I changed the file it failed with these errors.  I don't understand how these nodes work for storing information.

  "32": {
    "inputs": {
      "images": [
        "31",
        0
      ]
    },
    "class_type": "PreviewImage",
    "_meta": {
      "title": "Preview Image"
    }
  },
  "33": {
    "inputs": {
      "filename_prefix": "ComfyUI",
      "images": [
        "23",
        0
      ]
    },
    "class_type": "SaveImage",
    "_meta": {
      "title": "Save Image"
    }

Can you please explain how to get this working... 

Here is my code at the end for saving the images..

prompt = json.loads(prompt_text)
rnumber = random_number()
filename = sys.argv[1]
prompt["3"]["inputs"]["image"] = filename

prompt["3"]["inputs"]["seed"] = rnumber
ws = websocket.WebSocket()
ws.connect("ws://{}/ws?clientId={}".format(server_address, client_id))
images = get_images(ws, prompt)
for node_id in images:
    for image_data in images[node_id]:
        image = Image.open(io.BytesIO(image_data))
        image.save("output.png")

I'm the guy that asked you for help about a year ago with my website. Check it out now.. I have been improving it... https://AiImageCentral.com

Just having trouble getting my Remove Background python code to work...

Thanks in advance..  Jeff

**Comment by jdc4429** [comment]
Nevermind, I figured it out.  makes no sense why it worked sometimes even without BUT it turns out I needed to send the full path as well as filename... not just the filename.. even though it worked sometimes when I first manually ran from comfyui interface. weird.

**Comment by Gabbaarrr** [comment]
I am facing this same error how do I resolve this
