### ISSUE TITLE
Unloading models no longer works

### ISSUE THREAD

**Issue by Thireus** [comfyanonymous/ComfyUI#4217]
### Expected Behavior

Models successfully unloaded

### Actual Behavior

Models are not unloaded from memory

### Steps to Reproduce

1. Use Flux example provided here: https://comfyanonymous.github.io/ComfyUI_examples/flux/
2. Click Queue Prompt and wait for image to be generated
3. Manager -> Unload Models button

### Debug Logs

```powershell
n/a
```

### Other

I've been using the unload models feature successfully for the past couple of months, but for some reason it is no longer working and I'm not sure why. When clicking the Unload Models button the following message appears: "Models' have been unloaded.", but the GPU VRAM is not freed. This used to work before.

**Comment by huchenlei** [comment]
Please file issue to https://github.com/ltdrdata/ComfyUI-Manager/issues
