### ISSUE TITLE
The mouse scroll wheel doesn't zoom in and out; instead, it scrolls the page up and down. Is this a feature or a setting option?

### ISSUE THREAD

**Issue by gtbloody** [comfyanonymous/ComfyUI#4219]
### Your question

After an update, my mouse scroll wheel started scrolling pages up and down, and I need to use Ctrl + mouse scrolling for zooming, similar to the browser's operation logic. Originally, it was used for zooming. Is this a feature of the update? Is there a setting option to revert to the previous operation logic?

### Logs

```powershell
nope
```

**Comment by huchenlei** [comment]
Cannot reproduce.

Also please file frontend related issues to https://github.com/Comfy-Org/ComfyUI_frontend as we are deprecating the legacy frontend soon (2024-08-15)

**Comment by joorgejose** [comment]
That's probably this issue from the tbox node:
https://github.com/ai-shizuka/ComfyUI-tbox/issues/3#issue-2447396154
Disable it if you have it and check if it's back to normal

**Comment by gtbloody** [comment]
> That's probably this issue from the tbox node: [ai-shizuka/ComfyUI-tbox#3 (comment)](https://github.com/ai-shizuka/ComfyUI-tbox/issues/3#issue-2447396154) Disable it if you have it and check if it's back to normal

Yes!!!

**Comment by novice-101** [comment]
Had the same issue, disabling 1116 [ComfyUI-tbox](https://github.com/ai-shizuka/ComfyUI-tbox) fixed the issue.

**Comment by pollo98b52** [comment]
> Had the same issue, disabling 1116 [ComfyUI-tbox](https://github.com/ai-shizuka/ComfyUI-tbox) fixed the issue.

how do i disable it? i dont have it in any of my workflows and it still happens

**Comment by Ivan213131314** [comment]
Yes, it's definitely issue with [ComfyUI-tbox](https://github.com/ai-shizuka/ComfyUI-tbox) node
Manager > Custom nodes manager > ComfyUI-tbox

**Comment by KINGLIFER** [comment]
tbox is going to loose a LOT of users. 
Dropped it like a bad habit.

**Comment by novice-101** [comment]
> > Had the same issue, disabling 1116 [ComfyUI-tbox](https://github.com/ai-shizuka/ComfyUI-tbox) fixed the issue.
> 
> how do i disable it? i dont have it in any of my workflows and it still happens

It doesn't need to be in your active workflow, it only needs to be in your active nodes list. Search for it in your ComfyUI manager and disable it via the manager.

**Comment by er1cw00** [comment]
> That's probably this issue from the tbox node: [ai-shizuka/ComfyUI-tbox#3 (comment)](https://github.com/ai-shizuka/ComfyUI-tbox/issues/3#issue-2447396154) Disable it if you have it and check if it's back to normal

ComfyUI-tbox is using on our own headless server. I don't think anyone else is using this node ?
It integrates [TinkerBot-tech-for-ComfyUI-Touchpad](https://github.com/subtleGradient/TinkerBot-tech-for-ComfyUI-Touchpad) which disable mouse scroll and using Two-finger gestures on Mac."
