### ISSUE TITLE
FLUX UNETLoader: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#4220]
### Expected Behavior

Run the workflow

### Actual Behavior

throw the error

### Steps to Reproduce

Using a workflow at the Load Difussion Stage

### Debug Logs

```powershell
Error occurred when executing UNETLoader:

'NoneType' object has no attribute 'lower'

  File "W:\smatrix\Data\Packages\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "W:\smatrix\Data\Packages\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "W:\smatrix\Data\Packages\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "W:\smatrix\Data\Packages\ComfyUI\nodes.py", line 836, in load_unet
    model = comfy.sd.load_unet(unet_path, dtype=dtype)
  File "W:\smatrix\Data\Packages\ComfyUI\comfy\sd.py", line 626, in load_unet
    sd = comfy.utils.load_torch_file(unet_path)
  File "W:\smatrix\Data\Packages\ComfyUI\comfy\utils.py", line 14, in load_torch_file
    if ckpt.lower().endswith(".safetensors") or ckpt.lower().endswith(".sft"):
```

**Comment by BrechtCorbeel** [comment]
Changing the model worked apparently whatever folder it is pulling from only has the schnell model even though I only downloaded the Dev model.

Weird

**Comment by BrechtCorbeel** [comment]
This issue if someone has the same and used the model browser to download flux might be caused by this issue:

[![image](https://github.com/user-attachments/assets/a966dda0-2597-4978-a453-688d4c4f4f94)](https://github.com/comfyanonymous/ComfyUI/issues/4221)

**Comment by ltdrdata** [comment]
Fixed.

**Comment by thinghesi** [comment]
Please guide me how to fix the error

**Comment by ltdrdata** [comment]
> Please guide me how to fix the error

This was simply an issue with the model storage path.

It was an issue where the model, which wasn't a checkpoint model, was saved in the checkpoints folder, allowing it to be loaded with the `Load Checkpoint` node instead of the `Load Diffusion Model` node.

If you're experiencing this error, it means you're loading that model with the wrong node.
