### ISSUE TITLE
Wrongly named model in model browser?

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#4221]
### Your question

![image](https://github.com/user-attachments/assets/467eb76c-3aba-4ad4-9cf1-f81578e9da8f)
If you look at this image and look at the GB's the [schnell] model is 23.8 GB

The 2 [dev] models are 11.9 GB and 17.2 GB

only 1 [schnell] model is the expected 11.9 GB

**Comment by JorgeR81** [comment]
The 23.8 GB models are the original (fp16) Flux models, from black forest labs.
Both "dev" and "schnell" versions have the same size.
https://huggingface.co/black-forest-labs/FLUX.1-schnell
https://huggingface.co/black-forest-labs/FLUX.1-dev

----

The 11.9 GB models are fp8 versions created by Kijai, a custom node creator.
https://github.com/kijai
https://huggingface.co/Kijai/flux-fp8

----

The 17.2 GB models are created by Comfy org
https://huggingface.co/Comfy-Org/flux1-dev/tree/main
https://huggingface.co/Comfy-Org/flux1-schnell

These Comfy org models include (fp8) Flux versions + text encoders ( Clip L + T5 in fp8 version ), 
to be used with the default Checkpoint Loader node, instead for the Unet loader. 
https://huggingface.co/comfyanonymous/flux_text_encoders/tree/main
https://comfyanonymous.github.io/ComfyUI_examples/flux/#simple-to-use-fp8-checkpoint-version

**Comment by JorgeR81** [comment]
Looking at the Model Manager, it seems the "Save Path" for the 17.2 GB Flux models should be "**_checkpoints/FLUX1_**", instead of "**_unet/FLUX1_**".

These 17.2 GB models models got into the "checkpoints" folder, not the "unet" folder. 
https://comfyanonymous.github.io/ComfyUI_examples/flux/#simple-to-use-fp8-checkpoint-version

**Comment by ltdrdata** [comment]
Fixed.

**Comment by BrechtCorbeel** [comment]
> The 23.8 GB models are the original (fp16) Flux models, from black forest labs. Both "dev" and "schnell" versions have the same size. https://huggingface.co/black-forest-labs/FLUX.1-schnell https://huggingface.co/black-forest-labs/FLUX.1-dev
> 
> The 11.9 GB models are fp8 versions created by Kijai, a custom node creator. https://github.com/kijai https://huggingface.co/Kijai/flux-fp8
> 
> The 17.2 GB models are created by Comfy org https://huggingface.co/Comfy-Org/flux1-dev/tree/main https://huggingface.co/Comfy-Org/flux1-schnell
> 
> These Comfy org models include (fp8) Flux versions + text encoders ( Clip L + T5 in fp8 version ), to be used with the default Checkpoint Loader node, instead for the Unet loader.  https://huggingface.co/comfyanonymous/flux_text_encoders/tree/main https://comfyanonymous.github.io/ComfyUI_examples/flux/#simple-to-use-fp8-checkpoint-version

If both schnell and dev have the same size why is there no 2 properly named models with the same size?

**Comment by mcmonkey4eva** [comment]
the comfy-org fp8 schnell came a couple days after the fp8 dev. It should be added to the list

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/dab47069-67db-48c1-89fb-e982ee16ae21)

It is added already.
