### ISSUE TITLE
My friend, the time has come to put some folder path settings in ComfyUI

### ISSUE THREAD

**Issue by NPDX909** [comfyanonymous/ComfyUI#4227]
### Feature Idea

It seems like the only existing solution is editing  https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example  which would be fine, except there's no instructions on how to do this properly. "Just put in your existing A1111/SD.Webui path" ... people don't know which folder that is, and assume it's the A1111 installation folder. It makes people point the paths to a folder that doesn't have any models in it, because the A1111 dev has now put those models down a level in the folder tree. And this will be an ongoing thing, these changes to other GUIs.

So maybe just have settings in ComfyUI that point to folder paths?  "Server settings"? Default node on startup, at the top of the GUI? There must be a better solution than editing a yaml over and over until you figure out the path needs a trailing slash.

### Existing Solutions

Here is my existing solution: https://www.reddit.com/r/comfyui/comments/1ekw30i/pointing_comfyui_to_your_existing_model_folders/

**Comment by 36590798** [comment]
Got the same question.

**Comment by mcmonkey4eva** [comment]
in the short term you can use [SwarmUI](https://github.com/mcmonkeyprojects/SwarmUI) which wraps all that in a friendly UI, in the medium term there is an ongoing project to refactor how paths are handled in ComfyUI and an ongoing project to revamp the frontend with friendly settings UI and all, and once those converge this request will be done
