### ISSUE TITLE
[Bug] /object_info leaks user data

### ISSUE THREAD

**Issue by l1k3beef** [comfyanonymous/ComfyUI#4240]
### Expected Behavior

Users can only access the resources they are supposed to access through the /object_info interface.

### Actual Behavior

Accessing the /objecti_info interface will print out the paths of all uploaded images on the service. When used by multiple users, user B can directly obtain the path of the private image uploaded by user A, which is similar to the format of /image/{uuid}.png, and then directly read it through /view?filename={uuid}.png

### Other

Does ComfyUI need to design a reasonable user identity mechanism? This might be a security bug

**Comment by ltdrdata** [comment]
That's because ComfyUI is not currently designed for multi-user functionality. 
I believe it needs to be improved in the future.
