### ISSUE TITLE
RuntimeWarning: invalid value encountered in cast img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))

### ISSUE THREAD

**Issue by Rooky404** [comfyanonymous/ComfyUI#4241]
Got this error again...sadly. ksampler image 60% stopped and changed to solid black
RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))

comfyui up-to-date (08-06)
Mac Sonoma 14.6
torch 2.4.0
(pillow downgrade to 9.5.0 cause psd-tools incompatible...

comfyui default workflow works fine, but other tex2img workflows generate black imgs, like IC-light, ipadapter, just add simple lora, etc...

_Originally posted by @Rooky404 in https://github.com/comfyanonymous/ComfyUI/issues/3540#issuecomment-2270927748_

**Comment by Rooky404** [comment]
It works well just by adding "--force-upcast-attention"(It means forcing up the computational precision of the attention mechanism) after the "python main.py".
Maybe for now, but it worth it...😂😂

**Comment by polarNerd204** [comment]
ran into the same problem briefly using flux character sheet workflow (Mac Studio sonoma, 128g ram). Thought it was a overheating type error cus second run worked without causing black image generation. but stats said never used more than 60 mem and 7% cpu.

for future reference...WHAT and or how is the force-upcast-attention deployed? after running main.py to start comfyui then enter jus that line n hit enter?
