### ISSUE TITLE
what happend with ae.sft?

### ISSUE THREAD

**Issue by marioteodoru** [comfyanonymous/ComfyUI#4247]
### Your question

There was a ae.sft file in https://huggingface.co/black-forest-labs/FLUX.1-schnell/tree/main/vae around 300mb or something... I was just about to download it than i got a 404 and now there's a diffusion_pytorch_model.safetensors file of 168.mb. 

Anyone knows what happened? Flux.1-schnell works with diffusion_pytorch_model.safetensors, but is it important?

**Comment by mcmonkey4eva** [comment]
The file is at https://huggingface.co/black-forest-labs/FLUX.1-schnell/blob/main/ae.safetensors now
