### ISSUE TITLE
Run on CPU mode,but CPU useage is verlow.Not sure it is a bug or what.

### ISSUE THREAD

**Issue by bxjxxyy** [comfyanonymous/ComfyUI#4264]
### Your question

comfyui run on cpu mode(don't have gpu),but cpu useage is verlow,less than 10%.
![3f72a914182f3f6902f3b178803998a](https://github.com/user-attachments/assets/df4c669e-6776-404a-b846-c478f92d3731)
About 1 year ago,I was tried on another computer with 8700K CPU,it was 100% CPU useage.

**Comment by bxjxxyy** [comment]
I found my old version of ComfyUI,and it maximize CPU load on one CPU
![1723183590470](https://github.com/user-attachments/assets/8240b98d-749c-4b5d-8fc7-5953d1d10318)

**Comment by comfyanonymous** [comment]
That's a bug with pytorch 2.4. Use the package linked on here: https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.0.4 it has pytorch 2.3.1 or downgrade to pytorch 2.3.1

**Comment by ArdeniusAI** [comment]
I use this Comfyui-cpu to run on cpu only web servers. 
Comfyui-cpu is a trimmed down fork here https://github.com/ArdeniusAI/ComfyUI-cpu
