### ISSUE TITLE
embedding not work

### ISSUE THREAD

**Issue by Lorssi** [comfyanonymous/ComfyUI#4280]
### Your question

With the same model and configuration, embedding works well in webui, but seems to have no effect in comfyui. Only when the weight of embedding is increased can it work, but I am not sure whether it is the embedding that works or the increase in weight that makes the model recognize the keywords in the file name. 
The tutorials I found online are to use embedding through "embedding:filename", but it doesn't work for me. I hope someone who knows what's going on can help me solve my confusion, thank you!
The following is "embedding:HDA_SportsXL",
![image](https://github.com/user-attachments/assets/0e0918dc-081d-4b0c-82d2-c4556ea8d6a6)
The following is "(embedding:HDA_SportsXL:1.1)",
![image](https://github.com/user-attachments/assets/759fd9cd-92bd-4aec-a986-09af24f121b7)

**Comment by comfyanonymous** [comment]
it might be because you have a comma: , beside it.

**Comment by Lorssi** [comment]
> it might be because you have a comma: , beside it.

Thanks, I tested some pictures and indeed it worked well if "embedding:filename," was changed to ",
embedding:filename ," that is, "embedding:filename" was not close to "," before and after, thank you for your help.
I really hope you can consider fixing this bug, if it can be called a bug. I like comfyui very much and am very excited. I will modify it to a better-looking front end later. I hope this project can get better and better. Thank you very much for your answer.
