### ISSUE TITLE
Flux LoRA getting loaded only partially on a low VRAM GPU after commit 08f92d55e934c19f753b47ec4c51760c68bbe2b7

### ISSUE THREAD

**Issue by mhirki** [comfyanonymous/ComfyUI#4282]
### Expected Behavior

LoRA should get applied fully, e.g. image should look like this:
![fluxs_1723188953_0001_before](https://github.com/user-attachments/assets/febfd1fc-20ce-472c-bce0-fa7562a09bad)

### Actual Behavior

LoRA is getting loaded only partially and producing an image with diminished effect:
![fluxs_1723189106_0001_after_08f92d55e934c19f753b47ec4c51760c68bbe2b7](https://github.com/user-attachments/assets/0030104a-3ef8-4b64-8450-cfe3b15ff99d)

Here's an image with LoRA strength set to zero for comparison:
![fluxs_1723189152_0001_strength_0](https://github.com/user-attachments/assets/ed73ef5b-c0b0-49f7-af62-539736e751f1)

### Steps to Reproduce

I'm using a potato GPU with only 8 GB of VRAM. I'm using my own LoRA from here:
https://huggingface.co/mikaelh/flux-sanna-marin-lora-v0.2-fp8
Any other Flux LoRA will presumably also have the same issue.

Workflows are attached in the images above.

### Debug Logs

```powershell
got prompt
model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type FLOW
Model doesn't have a device attribute.
clip missing: ['text_projection.weight']
Requested to load FluxClipModel_
Loading 1 new model
Requested to load Flux
Loading 1 new model
loaded in lowvram mode 6233.7625
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:42<00:00, 10.60s/it]
Using pytorch attention in VAE
Using pytorch attention in VAE
Model doesn't have a device attribute.
Requested to load AutoencodingEngine
Loading 1 new model
Prompt executed in 68.62 seconds
```

### Other

With some manual bisecting I traced the issue back to commit 08f92d55e934c19f753b47ec4c51760c68bbe2b7. Before this commit everything works fine and afterwards I'm getting the diminished effect. The issue still persists even with the latest version.

**Comment by markrmiller** [comment]
I wonder if this is what I'm seeing. Flux Lora's were working fine, but now they seem to have almost no effect, with no error / warnings output.

**Comment by comfyanonymous** [comment]
loras still seem to work fine, they might just be weaker when weights are in fp8 so you might have to bump up the strength a bit.

**Comment by mhirki** [comment]
I tested the latest changes on my 8 GB card and the issue still persists. I did briefly test the LoRA on a 24 GB card couple of days ago and it was working fine.

**Comment by comfyanonymous** [comment]
Can you try with 16bit weights to see if it works?

**Comment by mhirki** [comment]
Results with weight_dtype = default are even worse. Now the LoRA is having almost no effect.
![fluxs_00013_default_precision](https://github.com/user-attachments/assets/c7731c1c-87a5-4877-bedf-d41460cf8a0d)

I did also test commit 39fb74c5bd13a1dccf4d7293a2f7a755d9f43cbd from a few minutes ago and it made no difference.

**Comment by rabidcopy** [comment]
Just adding this also seems to be the case for me. Loras applied in ComfyUI don't match how the lora is expected to perform. Seems very weak. Same lora applied to the same FP8 model in Forge performs as expected. No missing keys reported in the console. Same seeds are "similar" but Forge's output matches the expectation for what the lora should be accomplishing. (It's an artstyle lora, the likeness to the style is next to nothing in Comfy.) Seems like a strength of 1 in comfy is more like 0.25 when compared to Forge's strength of 1.

**Comment by mhirki** [comment]
Commit 83f343146ae1e8ccaf21da5b012bf59c78b97179 fixes this issue.

**Comment by rabidcopy** [comment]
Wanted to add 83f3431 also resolved the issue I had. Not sure if https://github.com/comfyanonymous/ComfyUI/commit/bb222ceddb232aafafa99cd4dec38b3719c29d7d was still necessary. (haven't tried it)

**Comment by listmaster21** [comment]
i can't rerun queue prompt,,, first queue its normal, but when i queque again for a second time,,, output same result or burn... i tried to configure my step and cfg... and nothing happend... just burn image...

**Comment by ltdrdata** [comment]
> i can't rerun queue prompt,,, first queue its normal, but when i queque again for a second time,,, output same result or burn... i tried to configure my step and cfg... and nothing happend... just burn image...

Is this phenomenon occurring in a workflow constructed using only core nodes?
