### ISSUE TITLE
The bug occurs on InstantID with commit:55ad9d5f8c8b906102313e894e471d2f5e833577

### ISSUE THREAD

**Issue by dingguoli** [comfyanonymous/ComfyUI#4288]
### Expected Behavior

when I update to commit:55ad9d5f8c8b906102313e894e471d2f5e833577 ,comfyui-InstantId got useless at the Ksample part .
return : AttributeError: 'NoneType' object has no attribute 'shape'

I'm not an expert, I submitted the file, if it's a BUG, please fix it, thank you!

### Actual Behavior

![image](https://github.com/user-attachments/assets/533603e0-5588-4ffa-8ebd-d87ba1d234a7)

### Steps to Reproduce

It got work by revert to  the older version.

### Debug Logs

```powershell
[Diagnostics-1723220900.log](https://github.com/user-attachments/files/16564400/Diagnostics-1723220900.log)
```

**Comment by comfyanonymous** [comment]
Can you update and try again?

**Comment by somenewaccountthen** [comment]
> Can you update and try again?

Is this the change to  comfy/model_patcher.py

  File "/my_dev/big_ai_etc/imaging/comfyUI/comfy/model_patcher.py", line 421, in patch_model_lowvram
    self.lowvram_load(device_to, lowvram_model_memory=lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "/my_dev/big_ai_etc/imaging/comfyUI/comfy/model_patcher.py", line 399, in lowvram_load
    weight = param[0]
             ~~~~~^^^
IndexError: list index out of range

**Comment by comfyanonymous** [comment]
This is fixed right on the latest commit?

**Comment by dingguoli** [comment]
> 这在最新的提交中已修复吗？

yes，It got work at the last commit,thx!
