### ISSUE TITLE
Laxhar/Freeway_Animation_HunYuan_Demo cannot be load

### ISSUE THREAD

**Issue by a-ru2016** [comfyanonymous/ComfyUI#4294]
### Expected Behavior

Freeway_Animation_HunYuan_Demo works with ComfyUI

### Actual Behavior

I tried to load mp_rank_00_model_states.pt with Load Diffusion Model, but it was not possible.

### Steps to Reproduce

Specify mp_rank_00_model_states.pt in Load Diffusion Model.
Clip and vae use comfyui's hunyuan_dit_1.2.safetensors.

### Debug Logs

```powershell
!!! Exception during processing!!! 'collections.OrderedDict' object has no attribute 'nelement'
Traceback (most recent call last):
  File "/Users/naganuma/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/naganuma/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/naganuma/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/naganuma/ComfyUI/nodes.py", line 836, in load_unet
    model = comfy.sd.load_unet(unet_path, dtype=dtype)
  File "/Users/naganuma/ComfyUI/comfy/sd.py", line 627, in load_unet
    model = load_unet_state_dict(sd, dtype=dtype)
  File "/Users/naganuma/ComfyUI/comfy/sd.py", line 583, in load_unet_state_dict
    parameters = comfy.utils.calculate_parameters(sd)
  File "/Users/naganuma/ComfyUI/comfy/utils.py", line 63, in calculate_parameters
    params += w.nelement()
AttributeError: 'collections.OrderedDict' object has no attribute 'nelement'
```

### Other

There may be some strange parts because I used Google Translate.
mp_rank_00_model_states.pt https://huggingface.co/Laxhar/Freeway_Animation_HunYuan_Demo/blob/main/freeway_demo_ema_model/mp_rank_00_model_states.pt
hunyuan_dit_1.2.safetensors https://huggingface.co/comfyanonymous/hunyuan_dit_comfyui/blob/main/hunyuan_dit_1.2.safetensors

**Comment by comfyanonymous** [comment]
https://huggingface.co/comfyanonymous/Freeway_Animation_Hunyuan_Demo_ComfyUI_Converted/tree/main

Use the converted checkpoints.

**Comment by a-ru2016** [comment]
thank you!
