### ISSUE TITLE
invalid prompt: Prompt has no properly connected outputs

### ISSUE THREAD

**Issue by GeneralAwareness** [comfyanonymous/ComfyUI#43]
Since I have no idea what I am doing in this I just hit the queue prompt button with the defaults that came up and no image just this error.

**Comment by comfyanonymous** [comment]
Click on field in the CheckpointLoader and pick a checkpoint that actually exists.

**Comment by GeneralAwareness** [comment]
Just coming from a user standpoint, I honestly feel this needs a simple interface, then we can get into the weeds if we wanted.  Think of DaVinci Resolve where it does most things out of the box, but you can start to diving into their nodes if you wish.  My hope is that is where this ends up eventually.
