### ISSUE TITLE
/ComfyUI/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-gpu.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev

### ISSUE THREAD

**Issue by Whackjob** [comfyanonymous/ComfyUI#4306]
### Your question

I haven't run ComfyUI straight for a good while.  Busy with college work.  Saw flux, desperately want to give it a go.  But now I can't even start it.  What's weird is, I can get it to run in a docker container, using a premade one out there, but I cannot make it work locally.  And fix inside the docker just freezes my whole system after an attempt or two.  So I've gone back to my regular install.  I've moved my models and such out, removed the folder, and rebuilt everything per the instructions.  I've redone it several times, in part and in whole.

I'm running linux mint with an intel arc A770 16GBvram.  

Thank you ahead of time to whomever can help.

### Logs

```powershell
whackjob@WhackjobONE:/media/whackjob/16Tons1/AI/ComfyUI$ source venv/bin/activate
(venv) whackjob@WhackjobONE:/media/whackjob/16Tons1/AI/ComfyUI$ source /opt/intel/oneapi/setvars.sh
 
:: WARNING: setvars.sh has already been run. Skipping re-execution.
   To force a re-execution of setvars.sh, use the '--force' option.
   Using '--force' can result in excessive use of your environment variables.
  
usage: source setvars.sh [--force] [--config=file] [--help] [...]
  --force        Force setvars.sh to re-run, doing so may overload environment.
  --config=file  Customize env vars using a setvars.sh configuration file.
  --help         Display this help message and exit.
  ...            Additional args are passed to individual env/vars.sh scripts
                 and should follow this script's arguments.
  
  Some POSIX shells do not accept command-line options. In that case, you can pass
  command-line options via the SETVARS_ARGS environment variable. For example:
  
  $ SETVARS_ARGS="ia32 --config=config.txt" ; export SETVARS_ARGS
  $ . path/to/setvars.sh
  
  The SETVARS_ARGS environment variable is cleared on exiting setvars.sh.
  
(venv) whackjob@WhackjobONE:/media/whackjob/16Tons1/AI/ComfyUI$ ipexrun main.py --use-pytorch-cross-attention --highvram
/media/whackjob/16Tons1/AI/ComfyUI/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/media/whackjob/16Tons1/AI/ComfyUI/venv/bin/ipexrun", line 5, in <module>
    from intel_extension_for_pytorch.launcher import main
  File "/media/whackjob/16Tons1/AI/ComfyUI/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/__init__.py", line 93, in <module>
    from .utils._proxy_module import *
  File "/media/whackjob/16Tons1/AI/ComfyUI/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: /media/whackjob/16Tons1/AI/ComfyUI/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-gpu.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev
(venv) whackjob@WhackjobONE:/media/whackjob/16Tons1/AI/ComfyUI$
```

**Comment by alpertunga-bile** [comment]
Hello @Whackjob, did you follow [this page](https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.40%2bxpu&os=linux%2fwsl2&package=pip) for intel-extension-for-pytorch library and the ```Intel® oneAPI Base Toolkit``` package version compatibility? Maybe upgrading your packages with the instructions from the page will solve the issue.

I don't know if you saw these links, but I found some links about your issue. I hope these will help:
- https://github.com/intel-analytics/ipex-llm/issues/10941
- https://github.com/intel/intel-extension-for-pytorch/issues/317#issuecomment-1493281457
- https://community.intel.com/t5/Intel-Developer-Cloud/ImportError-libintel-ext-pt-gpu-so-undefined-symbol/m-p/1561667

**Comment by Whackjob** [comment]
This issue is closed.  Apologies!  The fix was updating the intel extension for pytorch to the most recent version, rather than the specific version in the guide.
