### ISSUE TITLE
Queue becoming unusable

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#4309]
### Expected Behavior

work as expected

### Actual Behavior

Very often using and creating workflow, suddenly the queue stops functioning.

I ignore it usually, but I have bad workflows with errors waiting in line, I have to restart or wait for it to maybe at some point get back to working (which rarely happens)

I cannot delete them, cannot add new ones, this is annoying when using large batches especially given there's still no queue saving support.

### Steps to Reproduce

Toy around a lot importin new workflows

### Debug Logs

```powershell
/
```

**Comment by BrechtCorbeel** [comment]
After restarting in the browser a bunch of crystools saving errors poped up related to workflows, I forgot to screenshot the message, but as I am back to being unable to add anything so I might get it again in a second.

**Comment by BrechtCorbeel** [comment]
I got it again after closing Firefox, which is unusable because of another unrelated error that makes Firefox unusavle to me.

after closing firefox and getting the message the issue disappeared.

in firefox the queue did update, I guess it was an issue with connectivity and some browser related functionality.

**Comment by BrechtCorbeel** [comment]
but after getting to work again, either it is lagging again or just once again not working..

**Comment by huchenlei** [comment]
Please file issue in the downstream custom node repo. Thanks!
