### ISSUE TITLE
The uploaded images can be automatically deleted after the work is completed

### ISSUE THREAD

**Issue by Edisonwei54** [comfyanonymous/ComfyUI#4325]
### Feature Idea

When I use Comfyui to create a workflow, upload an image, and after the workflow is completed, a new image is successfully generated. I hope that when I successfully obtain this new image, the old image can be automatically deleted, which is the saved image in the input folder. At the same time, I also hope that the new image generated can be automatically deleted, which is the saved image in the output folder. By the way, I use Comfyui through an API.

### Existing Solutions

Do the development team leaders of Comfyui have any suggestions?
@comfyanonymous

**Comment by injet-zhou** [comment]
As a workaround, you can try my [custom node](https://github.com/injet-zhou/comfyui_extra_api) to delete images in the output folder.

**Comment by Edisonwei54** [comment]
> As a workaround, you can try my [custom node](https://github.com/injet-zhou/comfyui_extra_api) to delete images in the output folder.

thank you,it is a good idea. I didn't consider custom node.
