### ISSUE TITLE
errors occur during the FaceDetailer process

### ISSUE THREAD

**Issue by sqcoolee** [comfyanonymous/ComfyUI#4334]
### Your question

Prior to version 1c08bf3 on August 7, the FaceDetailer based on the SDXL model was able to proceed smoothly. After updating to later versions, including the latest version (as of August 13), errors occur during the FaceDetailer process. This issue is observed on a 4070 Ti Super with 16GB of memory.

**Comment by ltdrdata** [comment]
This should be reported to Impact Pack repo with full log.
