### ISSUE TITLE
[Feature Request] Calculation node

### ISSUE THREAD

**Issue by meor9zcu12** [comfyanonymous/ComfyUI#434]
Add node for addition, subtraction, multiplication, and division
Useful for LatentUpscale , e.g. 2x value from a primitive node
Or relocate the x or y offset for ConditioningSetArea base on change of image size

**Comment by Abhishekrazy** [comment]
Here is the link for your request 
[https://civitai.com/models/21558/comfyui-derfuu-math-and-modded-nodes](url)

**Comment by WASasquatch** [comment]
I also have a operator node in WAS Suite which handles math operations in one node: https://github.com/WASasquatch/was-node-suite-comfyui

There is a merge by @omar92 into LiteGraph which, down scope will allow you to perform math inline in a  input field too which can be handy.

**Comment by omar92** [comment]
the owner of  litegraph.js  accepted my merge for the inline math calculations 
what is needed now is that  litegraph.js  gets updated in comfiui 
https://github.com/jagenjo/litegraph.js/pull/358

**Comment by omar92** [comment]
ok litegraph is now updated with that change XD

so you can do it on number nodes now

**Comment by jwd-dev** [comment]
Is this still needed? Looking for issues to tackle atm.

**Comment by WASasquatch** [comment]
> Is this still needed? Looking for issues to tackle atm.

There are like three plugin systems with math nodes, plus can do math in fields now, so not sure. It would be cool to try and PR something to base though cause a lot of people are unaware of plugins and running base from what people share online.

**Comment by robinjhuang** [comment]
Looks like this is fixed. Please reopen if not.
