### ISSUE TITLE
extra_model_paths.yaml can't work on flux model

### ISSUE THREAD

**Issue by unever** [comfyanonymous/ComfyUI#4342]
### Expected Behavior

i use [extra_model_paths.yaml] file to share model folders

### Actual Behavior

[extra_model_paths.yaml] does not work on flux model.
it's work in comfyui/models folders.

### Steps to Reproduce

every time

### Debug Logs

```powershell
no logs
but i cant select model in the notes, both unet_name and clip.
```

**Comment by ltdrdata** [comment]
It doesn't matter whether it's FLUX or not.
If you're using a diffusion model, you can add the `unet` item into `extra_model_paths.yaml`.
In the case of clip models, you can add the `clip` item.

**Comment by unever** [comment]
> It doesn't matter whether it's FLUX or not. If you're using a diffusion model, you can add the `unet` item into `extra_model_paths.yaml`. In the case of clip models, you can add the `clip` item.
> 
> If you need more detailed help, please upload your `extra_model_paths.yaml` file. And the path to the model.

Thanks a lot.
I neglected that there are no unet and clip item in the extra_model_paths.yaml file. when I add it, it's work~
