### ISSUE TITLE
Flux models broken since recent update (8-13-24) on Mac

### ISSUE THREAD

**Issue by pphoto808** [comfyanonymous/ComfyUI#4346]
### Your question

Mac Studio M2 Ultra

All of my Flux (dev/schnell) workflows now result in these white noise images. 
No errors reported in terminal. 

![Screenshot 2024-08-13 at 17 07 10](https://github.com/user-attachments/assets/7d1ff1d8-4add-496a-b48c-30a96988a4a1)

**Comment by comfyanonymous** [comment]
If you `git checkout v0.0.8` does it work?

**Comment by fideuacaprichos** [comment]
Same issue.M2 24GB.

**Comment by timothyallan** [comment]
> If you `git checkout v0.0.8` does it work?

Did a git pull initially and got the same sparkly mess. 
Did `git checkout v0.0.8` and it works again...
M2 MAX 64GB

**Comment by brkirch** [comment]
@comfyanonymous 34608de broke inference for MPS. The previous commit, 39fb74c, works without issue.

**Comment by timothyallan** [comment]
lol @ the commit message, famous last words "Not sure if this actually changes anything but it can't hurt."

**Comment by comfyanonymous** [comment]
Can you test if --fp16-unet fixes it on the latest commit and makes inference faster?

**Comment by timothyallan** [comment]
> Can you test if --fp16-unet fixes it on the latest commit and makes inference faster?

Fairly new here, so if that's just a command line flag, I checked out main again, ran `python main.py --fp16-unet`, and got the noise again.

**Comment by brkirch** [comment]
Doesn't fix it, however in previous commits I found that `--fp16-unet` gives a ~25% performance boost on my M1 Max. However, that is likely only because M1 Macs don't have bfloat16 support at the hardware level. Any newer Macs (M2 and later) should have proper bfloat16 support and likely won't see any significant change in performance by using float16 instead.

**Comment by pphoto808** [comment]
> git checkout v0.0.8

Everything good on my native Comfy install. Now need to figure out how to implement same fix in Pinokio install. 

Thanks.

**Comment by fideuacaprichos** [comment]
> If you `git checkout v0.0.8` does it work?

It worked, thank you.

**Comment by brkirch** [comment]
There's no longer any need for `git checkout v0.0.8`, the latest commit no longer has this issue.
Use `git checkout master; git pull` to go to the latest commit.

**Comment by sanctimon** [comment]
I am getting the same issue on Apple M3 Max, 96GB RAM. I am not sure what you guys mean by git checkout master; git pull. Which directory must this be run in? Thank you.

**Comment by ununiform** [comment]
I'm also getting dotted noise. M1 Ultra. I've tried git checkout v0.0.8 with no luck. Am I supposed to download anything to the VAE or Unet folders?
