### ISSUE TITLE
When using the flux model of controlnet, this problem occurs: Error occurred when executing ControlNetLoader:  MMDiT.__init__() got an unexpected keyword argument 'image_model'

### ISSUE THREAD

**Issue by GFY2000** [comfyanonymous/ComfyUI#4349]
### Your question

I encountered this problem when using the flux model of controlnet. My comfyui is already the latest version. I don't know why. Has anyone encountered the same situation as me? How to solve it?
![image](https://github.com/user-attachments/assets/588d8aa7-ea18-48ff-b787-bbba8884ab54)

**Comment by Lusus-Naturae** [comment]
I think you're using a model from InstantX and that they aren't supported yet. I might be mistaken, but I think only the Flux Controlnets by XLabs-AI are supported

**Comment by GFY2000** [comment]
Thank you two brothers above, this is indeed the reason. I just need to switch to XLabs-AI's controlnet. I was using InstantX's controlnet before.

**Comment by VictorLab75** [comment]
Problem is Xlabs controlnet sucks at inpaint, and InstantX doesn't. The Union ControlNet works great but is quite heavy. Would be nice to be able to use the Canny (lighter).

**Comment by eusoumax** [comment]
replace the controlnet load for "InstantX Flux Union ControlNet Loader". I had the same error and after I replaced the node it worked. 
https://www.youtube.com/watch?v=DVZikxmIbo0

**Comment by liuzhihan** [comment]
update comfyui，all nodes，done！！！

**Comment by LorisTecnology** [comment]
how did you update? from manager?

**Comment by GlenCarpenter** [comment]
> how did you update? from manager?

If you are using ComfyUI Windows Portable,

- run `ComfyUI_windows_portable\update\update_comfyui.bat`
- Restart ComfyUI > Manager > Update all
