### ISSUE TITLE
request: add the "unet" to extra_model_paths.yaml

### ISSUE THREAD

**Issue by metsweet999** [comfyanonymous/ComfyUI#4353]
### Feature Idea

In the file "e: \ a \ comfyui \ extra _ model _ paths.yaml",
Activate this paragraph (remove the "#" in front of each line of this paragraph):
“
comfyui:
base_path: E:/B/ComfyUI
checkpoints: models/checkpoints/
clip: models/clip/
clip_vision: models/clip_vision/
configs: models/configs/
controlnet: models/controlnet/
embeddings: models/embeddings/
loras: models/loras/
upscale_models: models/upscale_models/
vae: models/vae/
"
Run the comfyui in the "E:\A\ComfyUI" directory,
Models such as ckpt and vae in the "E:/B/ComfyUI/models" directory can be loaded, but models such as unet cannot be loaded.

Add "unet: models/unet/" to the file "e: \ a \ comfyui \ extra _ model _ paths.yaml".
Invalid, unet model still cannot be loaded.

hope the extra model path of unet can be configed in the  "extra _ model _ paths.yaml" file.

since flux model can be of the format of unet, this requested feature seemed more and more essential maybe.

**Comment by bedovyy** [comment]
You can add whatever you want on extra_model_paths.yaml file.

```
extern:
    base_path: /ai/data/sd
    clip: models/clip
    clip_vision: models/clip_vision
    checkpoints: |
         models/Stable-diffusion
         models/checkpoints
    configs: models/Stable-diffusion
    vae: models/VAE
    loras: |
         models/Lora
         models/LyCORIS
    upscale_models: |
                  models/ESRGAN
                  models/RealESRGAN
                  models/SwinIR
                  models/upscale_models
    embeddings: embeddings
    hypernetworks: models/hypernetworks
    controlnet: models/ControlNet
    photomaker: models/photomaker
    unet: models/unet
```

as you can see, I am using unet directory from /ai/data/sd

**Comment by pixelpainter** [comment]
checkpoints: F:/models
    configs: models/Stable-diffusion/
    vae: D:/Program Files/StableDiffusion/Vae/
    loras: D:/Program Files/StableDiffusion/Lora/
    embeddings: D:/Program Files/StableDiffusion/embeddings/
    hypernetworks: D:/Program Files/StableDiffusion/hypernetworks/
    controlnet: D:/Program Files/StableDiffusion/controlnet/
    wildcards: D:/Program Files/StableDiffusion/Wildcards/
    upscale_models: D:/Program Files/StableDiffusion/upscale_models/
    unet: D:/Program Files/StableDiffusion/unet/

I have the above paths configured in my extra_model_paths.yaml all of them work perfectly except unet.

The unet path is not working, I see you have mentioned it should, but my flux models are not being seen I the directory I want them to be seen, Comfy is still looking in models/unet

**Comment by LukeG89** [comment]
@pixelpainter Try changing the `unet` with `diffusion_models` (unet folder is deprecated)

**Comment by pixelpainter** [comment]
> @pixelpainter Try changing `unet` with `diffusion_models` (unet folder is deprecated)

Thank you! It works, sorta, it appears to be reading from the new path, but also from the original ComfyUI path: models/unet as well. Since this works, I can still move everything to the new path, but it's interesting lol  not sure if it was intended :)
