### ISSUE TITLE
add support for InstantX/FLUX.1-dev-Controlnet-Union

### ISSUE THREAD

**Issue by geroldmeisinger** [comfyanonymous/ComfyUI#4355]
### Feature Idea

https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Union-alpha

**Comment by geroldmeisinger** [comment]
https://www.reddit.com/r/StableDiffusion/comments/1euaeum

**Comment by hartmark** [comment]
Awesome, it seems each day in AI is like a year in other technologies.

Looking forward to this. 

I tried using an image with low denoise with flux and sometimes the results were good but it was after tweaking the prompt and denoise value for each photo I wanted to generate.

**Comment by EeroHeikkinen** [comment]
Once #4444 gets merged it will add support for loading InstantX's union controlnet using this custom loader node: https://github.com/EeroHeikkinen/ComfyUI-eesahesNodes
Until the PR is merged you can use it using the instructions from here:
https://www.reddit.com/r/StableDiffusion/comments/1euz2a9/union_flux_controlnet_running_on_comfyui_workflow/

**Comment by geroldmeisinger** [comment]
it works great, thank you so much!
memory requirements are quite high though

**Comment by hartmark** [comment]
> it works great, thank you so much! memory requirements are quite high though. I wasn't able to create a 1024x1024 image with all flux and t5 in fp8 and even turning off all desktop managers and browser to free VRAM. I guess we need fp8 controlnets too.

How much vram did you have?

**Comment by geroldmeisinger** [comment]
16 VRAM (about 200M occupied by DM), 64 SRAM, 4 swap

**Comment by geroldmeisinger** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/10a79e989869f8878e27a8f373d85aef31822415

**Comment by rootliuat** [comment]
The downloaded instantX flux union controller loader model should be placed in that directory
