### ISSUE TITLE
How to output one picture in parallel on multi GPU?

### ISSUE THREAD

**Issue by Rardluca-Love-Everyone** [comfyanonymous/ComfyUI#4371]
### Your question

I tried looking in several discussions about running graphics on multi GPU, but couldn't figure out how to do this in comfyUI.
For example, is it possible to use some pytorch commands or some nodes in comfyUI? I have no idea about this and need some help.
Orz.

**Comment by Rardluca-Love-Everyone** [comment]
Would using multiple A100sxm4s speed up the creation of images? Is it worth trying?

**Comment by ltdrdata** [comment]
Currently, the most practical method is to use multiple ComfyUI servers through systems like NetDist or SwarmUI.

https://github.com/mcmonkeyprojects/SwarmUI
https://github.com/city96/ComfyUI_NetDist

**Comment by bedovyy** [comment]
refer.
https://github.com/xdit-project/xDiT
https://github.com/DefTruth/Awesome-SD-Inference?tab=readme-ov-file
