### ISSUE TITLE
Deep-Live-Cam  läuft nicht mehr. 

### ISSUE THREAD

**Issue by lattemaqui** [comfyanonymous/ComfyUI#4372]
sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\kingz\Desktop\Deep-Live-Cam\models\inswapper_128_fp16.onnx failed:Protobuf parsing failed.

Es lief kurz, doch das bild war nicht flüssig.  fror ein undlässt sich nicht mehr stsrten

**Comment by mcmonkey4eva** [comment]
This is the github for ComfyUI, you're in the wrong place

**Comment by lattemaqui** [comment]
Ups... Scuzii.
