### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower' when load_vae in 

### ISSUE THREAD

**Issue by xia-huang-411303** [comfyanonymous/ComfyUI#4377]
### Expected Behavior

The VAE model was loaded normally

### Actual Behavior

ComfyUI Version: master `[ad76574](https://github.com/comfyanonymous/ComfyUI/commit/ad76574cb8b28ee498f3dceafc9d00b56f12f992)` 2024-08-1212:23:29

![image](https://github.com/user-attachments/assets/7fe51cf2-f917-4698-8ceb-2ce59ee8904a)

```
!!! Exception during processing!!! 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/mnt/e/LSY/comfyui/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/e/LSY/comfyui/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/e/LSY/comfyui/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/e/LSY/comfyui/nodes.py", line 704, in load_vae
    sd = comfy.utils.load_torch_file(vae_path)
  File "/mnt/e/LSY/comfyui/comfy/utils.py", line 33, in load_torch_file
    if ckpt.lower().endswith(".safetensors") or ckpt.lower().endswith(".sft"):
AttributeError: 'NoneType' object has no attribute 'lower'
```

### Steps to Reproduce

This error will be reported when I load the VAE model 'sdxl.vae.safetensors' Use the default VAE loader. I have checked the code and found no obvious error.
The problem was solved when I changed the model name to 'sdxl_vae.safetensors', which made me a little confused and a little inclined to laugh

### Debug Logs

```powershell
None
```

### Other

Operating environment: WSL2

**Comment by taladro** [comment]
+1

**Comment by PcChip** [comment]
having the same error message when clicking "import from generate tab"

![image](https://github.com/user-attachments/assets/1252c6a1-1db7-4403-8312-88456e401699)

**Comment by ltdrdata** [comment]
> having the same error message when clicking "import from generate tab"
> 
> ![image](https://private-user-images.githubusercontent.com/28493830/367625999-1252c6a1-1db7-4403-8312-88456e401699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NDg5ODIsIm5iZiI6MTcyNjQ0ODY4MiwicGF0aCI6Ii8yODQ5MzgzMC8zNjc2MjU5OTktMTI1MmM2YTEtMWRiNy00NDAzLTgzMTItODg0NTZlNDAxNjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDAxMDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNDc3ZmZlZGRkMDhhZjJhNDdhZDVjMmRjMWI1NmQzMGNjOGVmN2U5OTcyOTkzZmQ0ZDFiNjVjZDQzNjRlODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VNtDAZ6Psaa3PiTmqvzBpWlC0TyohR-1hus6VOKdPp0)

Make sure the model file is valid.
