### ISSUE TITLE
Flux Update doesn't Work Half the nodes I download Don't Work

### ISSUE THREAD

**Issue by EddieSoloProjects** [comfyanonymous/ComfyUI#4382]
### Expected Behavior

I expect the nodes to load properly. Setting the Dev options does Nothing at all...

### Actual Behavior

I download nodes with the Comfy UI Manager. It says they load but half of them don't

### Steps to Reproduce

Download and try to use Comfy

### Debug Logs

```powershell
bbb
```

### Other

bbb

**Comment by huchenlei** [comment]
Missing reproduction steps.
