### ISSUE TITLE
After comfyui is updated, nodes cannot cover each other.

### ISSUE THREAD

**Issue by wencxxxxxx** [comfyanonymous/ComfyUI#4383]
### Expected Behavior

Before comfyui update,  nodes can cover each other.

### Actual Behavior

After comfyui is updated, Move a few files from comfy -> comfy_execution. nodes cannot cover each other.This causes the occlusion relationship of nodes in the pre-update workflow to become chaotic. This also caused some third-party node load errors.
![屏幕截图 2024-08-16 065724](https://github.com/user-attachments/assets/1e639ad4-e9df-4f19-8767-09dcdf05efb9)

### Steps to Reproduce

.

### Debug Logs

```powershell
.
```

**Comment by JorgeR81** [comment]
Same for me.
That's the new new frontend.
https://github.com/comfyanonymous/ComfyUI/issues/4169

Please make it behave like the old one.

**Comment by huchenlei** [comment]
Closing because already filed in the frontend repo.
