### ISSUE TITLE
文本框内字体大小颜色调整，实在是太难受了太小了

### ISSUE THREAD

**Issue by 52Hz-p** [comfyanonymous/ComfyUI#4387]
### Feature Idea

目前clip文本内，包括其他文本显示内的文字大小都无法调整大小，旧版本可以通过修改css文件调整，但是新版本更新后，我不知道怎么修改了

**Comment by huchenlei** [comment]
You can still add style rule to https://github.com/comfyanonymous/ComfyUI/blob/master/web/user.css

**Comment by 52Hz-p** [comment]
> 您仍然可以将样式规则添加到https://github.com/comfyanonymous/ComfyUI/blob/master/web/user.css

原来的css文件格式我还会根据gpt调整，但是新的实在是看不懂了0.0

**Comment by 52Hz-p** [comment]
![Snipaste_2024-08-16_10-30-30](https://github.com/user-attachments/assets/fe372abf-5d50-4127-ac98-063ba97925b4)
不知道能否帮助我具体怎么添加user，就像原来的css.comfy-multiline-input {
	background-color: var(--comfy-input-bg);
	color: #feb808;
	overflow: hidden;
	overflow-y: auto;
	padding: 2px;
	resize: none;
	border: none;
	box-sizing: border-box;
	font-size: 18px;
}我调整成这个样式一样

**Comment by huchenlei** [comment]
Copy
```
css.comfy-multiline-input {
background-color: var(--comfy-input-bg);
color: #feb808;
overflow: hidden;
overflow-y: auto;
padding: 2px;
resize: none;
border: none;
box-sizing: border-box;
font-size: 18px !imporant;
}
```
and paste to `web/user.css` should make it work. You might want to add `!important` to some rules to make sure they are not overwritten by other rules.
![image](https://github.com/user-attachments/assets/889946d3-6f6c-4bce-b45b-4e74380dc8f5)
