### ISSUE TITLE
Comfy hanging at loading screen with black/greyed out overlay on latest commit

### ISSUE THREAD

**Issue by Jantolick** [comfyanonymous/ComfyUI#4388]
### Expected Behavior

For ComfyUI to load

### Actual Behavior

Black overlay, comfyUI unable to be interacted with, loading state forever

### Steps to Reproduce

Install main branch with commit bfc214f434e9c92d05d755857c597733a7fd3b91 and restart server/reload

### Debug Logs

```powershell
runtime-core.esm-bundler.js:270 TypeError: Cannot read properties of undefined (reading 'default')
    at _ComfyInputsSpec2.transformSingleInputSpec (nodeDefStore.ts:125:25)
    at _ComfyInputsSpec2.transformInputSpecRecord (nodeDefStore.ts:96:37)
    at Object.transformFn (nodeDefStore.ts:82:45)
    at TransformOperationExecutor.js:373:30
    at Array.forEach (<anonymous>)
    at TransformOperationExecutor2.applyCustomTransformations (TransformOperationExecutor.js:372:19)
    at _loop_1 (TransformOperationExecutor.js:308:49)
    at TransformOperationExecutor2.transform (TransformOperationExecutor.js:337:17)
    at _loop_1 (TransformOperationExecutor.js:307:49)
    at TransformOperationExecutor2.transform (TransformOperationExecutor.js:337:17)
```

### Other

Rolling back to the commit right before this one lets everything work as expected.

**Comment by thosupercop2** [comment]
Got the same problem? Any help please

**Comment by comfyanonymous** [comment]
This is likely because of a custom script you have installed, can you post which custom nodes you have installed?


If you want to easily revert back to the previous stable ComfyUI version:

If you are on the standalone -> update/update_comfyui_stable.bat , if the file doesn't exist run update/update_comfyui.bat first.

If you have a manual install -> git checkout v0.0.8

**Comment by Jantolick** [comment]
/websocket_image_save.py
   /ComfyUI-Photopea
   /conditioning_sizing_for_SDXL.py
   /ComfyUI_SeeCoder
   /ComfyUI_TiledKSampler
   /ComfyUI_JPS-Nodes
   /ComfyUI-Custom-Scripts
   /ComfyUI_NestedNodeBuilder
   /ComfyUI-WD14-Tagger
   /ComfyUI-QualityOfLifeSuit_Omar92
   /Derfuu_ComfyUI_ModdedNodes
   /rgthree-comfy
   /ComfyUI-AnimateDiff-Evolved
   /ComfyUI-Workflow-Component
   /ComfyUI_UltimateSDUpscale
   /ComfyUI_Comfyroll_CustomNodes
   /ComfyUI_TensorRT
   /comfyui_controlnet_aux
   /ComfyUI_IPAdapter_plus
   /comfyui_segment_anything
   /ComfyUI-Impact-Pack
   /ComfyUI-Manager
   /comfy_controlnet_preprocessors
   /was-node-suite-comfyui
   /facedetailer

**Comment by huchenlei** [comment]
Please file an issue in the frontend repo here: https://github.com/Comfy-Org/ComfyUI_frontend

Thanks!

The issue is likely caused by a custom node's definition sneak through the zod schema validation and reached class-transformer layer.

**Comment by DonDanDojo** [comment]
> Please file an issue in the frontend repo here: https://github.com/Comfy-Org/ComfyUI_frontend
> 
> Thanks!
> 
> The issue is likely caused by a custom node's definition sneak through the zod schema validation and reached class-transformer layer.

I've added --front-end-version Comfy-Org/ComfyUI_frontend@latest argument to ComfyUI launch script (through Stability Matrix) and suddenly front end is loading correctly (except for nodes I can't find in search bar, they are loading for eternity. I can find them manually though)

**Comment by DonDanDojo** [comment]
> If you have a manual install -> git checkout v0.0.8

Frontend is working at this version with all nodes. Will need to wait for another stable version I guess.
