### ISSUE TITLE
Show node class name on search bar

### ISSUE THREAD

**Issue by bedovyy** [comfyanonymous/ComfyUI#4389]
### Feature Idea

![image](https://github.com/user-attachments/assets/782435d3-d306-49db-9796-a75984a54159)
Previously, I coud see node class name (or name for connecting?) on search bar,
and it is so easy to find node.

new UI also can search using class name, but doesn't show the name.
![image](https://github.com/user-attachments/assets/7fa7cd9d-9b72-4ce2-afd7-e4739959a858)

### Existing Solutions

previouse UI.

### Other

the font of new UI is too big and can't change it smaller.

**Comment by mcmonkey4eva** [comment]
frontend issues go @ https://github.com/Comfy-Org/ComfyUI_frontend/
