### ISSUE TITLE
json文件打不开，之前做的工作流有好几个直接打不开

### ISSUE THREAD

**Issue by upboy-web** [comfyanonymous/ComfyUI#4393]
![c2402291f3b791c59be9502bf5be0e0](https://github.com/user-attachments/assets/99a569ff-7b34-4783-9e64-41a0ac3e85d1)

**Comment by huchenlei** [comment]
Please share the workflow you are having issue with.

For now you can disable workflow validation in settings.
![image](https://github.com/user-attachments/assets/15e0a7a8-261d-427b-a538-fc439eeac556)

**Comment by upboy-web** [comment]
禁用验证可以正常使用了，谢谢您，我上传一下工作流，以便您能更好分析原因
[炮老师 一键真实换脸优化版.json](https://github.com/user-attachments/files/16632524/default.json)

**Comment by huchenlei** [comment]
It's pretty wield that the pos field has some extra zeroes. 
![image](https://github.com/user-attachments/assets/7d79710e-b365-4c46-93e8-3e8ab6ca1384)

I am not sure if it is the effect of custom nodes.
