### ISSUE TITLE
加载图像节点直接可以直接访问剪切板，现在只能手动加载，很不方便

### ISSUE THREAD

**Issue by upboy-web** [comfyanonymous/ComfyUI#4394]
### Feature Idea

跟之前一样，可以直接复制剪切板内容上去就好了

### Existing Solutions

跟之前一样，可以直接复制剪切板内容上去就好了

### Other

跟之前一样，可以直接复制剪切板内容上去就好了

**Comment by huchenlei** [comment]
Bug confirmed reproducable.

**Comment by mcmonkey4eva** [comment]
frontend issues go @ https://github.com/Comfy-Org/ComfyUI_frontend/
