### ISSUE TITLE
Hope there will be settings that can adjust these UIs.

### ISSUE THREAD

**Issue by 807502278** [comfyanonymous/ComfyUI#4397]
### Feature Idea

1. The icon size can be set(It is recommended that the minimum be 6 pixels.), and the UI can automatically adapt to the width.
![image](https://github.com/user-attachments/assets/df4668e4-faf3-4913-a110-c99f62f9e0bd)

2. The font size and line spacing can be set (it is recommended that the minimum font size is 6 pixels and the minimum spacing is -2 pixels).
![image](https://github.com/user-attachments/assets/ea1c22e5-6834-4bd6-9653-391bcb7e70b8)

### Other

For example, settings like those of  ComfyUI-N-Sidebar.
![image](https://github.com/user-attachments/assets/ace7a206-2980-47a6-b0cc-30b473abe454)

**Comment by huchenlei** [comment]
There is already sizebar size control in settings. https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.2.20

**Comment by mcmonkey4eva** [comment]
frontend issues go @ https://github.com/Comfy-Org/ComfyUI_frontend/

**Comment by 807502278** [comment]
Thank you all for the reminder
