### ISSUE TITLE
Not work on baseUrl

### ISSUE THREAD

**Issue by GitHub4LP** [comfyanonymous/ComfyUI#4398]
### Expected Behavior

Nomal

### Actual Behavior

Only index.html loaded

### Steps to Reproduce

You can test it on WSL2 and code-server.
`export VSCODE_PROXY_URI=./proxy/{{port}}/ &&  code-server --disable-workspace-trust --disable-telemetry --auth none ~ --bind-addr 0.0.0.0:8888`
OR WSL2 and jupyterlab + jupyter-server-proxy
`jupyter lab --no-browser --ip=0.0.0.0 --allow-root --notebook-dir=~ --LabApp.token= --LabApp.allow_origin=* `
and run the ComfyUI
request http://127.0.0.1:8888/proxy/8188/

### Debug Logs

```powershell
frontend
```

**Comment by huchenlei** [comment]
Should be fixed by https://github.com/Comfy-Org/ComfyUI_frontend/pull/472.

Please wait for the next frontend release (1.2.27) today and add --front-end-version Comfy-Org/ComfyUI_frontend@latest to your cmd line arg list to opt-in to use latest front-end.

**Comment by GitHub4LP** [comment]
> Should be fixed by [Comfy-Org/ComfyUI_frontend#472](https://github.com/Comfy-Org/ComfyUI_frontend/pull/472).
> 
> Please wait for the next frontend release (1.2.27) today and add --front-end-version Comfy-Org/ComfyUI_frontend@latest to your cmd line arg list to opt-in to use latest front-end.

Well, While
