### ISSUE TITLE
with the latest update it has stopped working.

### ISSUE THREAD

**Issue by lunatico67** [comfyanonymous/ComfyUI#4400]
When opening comfyui a green circle spins eternally and does not open. On the console there is no error. I can't load any workflow or manager. I update from update folder with update_comfyui.bat, update_comfyui_and_python_dependencies.bat and update_comfyui_stable.bat and it still doesn't open.
![ComfyUI](https://github.com/user-attachments/assets/22859db9-2356-4214-b136-0e959a1427e5)

**Comment by lunatico67** [comment]
Now appears this error 
![error](https://github.com/user-attachments/assets/c504522b-1ee0-4180-92f9-00bc57609d2c)

**Comment by lunatico67** [comment]
Now apperas this error:
python.exe - Entry Point Not Found

The procedure entry point ??0Error@c10@@QEAA@V?Sbasic_string@DU?Schar_traits@D@std@@V?sallocator@D@2@@std@@OPEBX@Z could not be located in the dynamic link library C\Users\----\Documents\ComfyUI_Window_portable|python_embeded|Lib|site-packages\xformers\_Cpyd.

**Comment by nerdylive123** [comment]
How did you solve this??

**Comment by lunatico67** [comment]
Hi nerdylive123 and CCpt5. 
I sent all ComfyUI to the trash and started with a new installation.
