### ISSUE TITLE
How to increase font size in new UI

### ISSUE THREAD

**Issue by zlobniyshurik** [comfyanonymous/ComfyUI#4405]
### Your question

I want to increase font size in UI

It looks like that old trick with
**ComfyUI/web/user.css**
```
.comfy-multiline-input, .litecontextmenu .litemenu-entry {
    font-size: 20px;
}
```
 no longer works.

What method can be recommended for the new user interface?

**Comment by huchenlei** [comment]
The CSS load order got adjusted a bit. You can add "!important" after "20px" for now. I will fix the load order and add a setting to adjust font size in the next front end version

**Comment by zlobniyshurik** [comment]
Thank you! 
Workaround works perfectly.

**Comment by christian-byrne** [comment]
For anyone arriving in future, please refer to docs on cusotmizing UI appearance: https://docs.comfy.org/interface/appearance#troubleshooting
