### ISSUE TITLE
Implement support for taef1 latent previews

### ISSUE THREAD

**Issue by mturnshek** [comfyanonymous/ComfyUI#4408]
### Feature Idea

madebyollin has released taef1 here, last week: https://github.com/madebyollin/taesd

However, it is currently unsupported in ComfyUI.

**Comment by mturnshek** [comment]
I'll take a shot at this myself first.

**Comment by kadirnar** [comment]
@mturnshek 

```bash
  File "/workspace/ComfyUI/comfy/sd.py", line 318, in decode
    memory_used = self.memory_used_decode(samples_in.shape, self.vae_dtype)
                                                            ^^^^^^^^^^^^^^
AttributeError: 'VAE' object has no attribute 'vae_dtype'
````
Workflow:
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/3872965a-ce71-46e0-9808-88b861591ef7">
