### ISSUE TITLE
Old UI showing up next to New UI

### ISSUE THREAD

**Issue by oliverban** [comfyanonymous/ComfyUI#4414]
### Expected Behavior

Just the new search node box instead of the old one.

### Actual Behavior

Both the old node search and the new search node box comes up when double-clicking in the workflow space. You can see it briefly in the beginning of the video.

### Steps to Reproduce

Start comfy
Double click to add node

### Debug Logs

```powershell
Have nothing special to show here, no errors in terminal.
```

### Other

https://github.com/user-attachments/assets/60477418-0615-4555-8b08-feafeb21e936

**Comment by huchenlei** [comment]
Already reported: https://github.com/Comfy-Org/ComfyUI_frontend/issues/443

Can you file an issue in the frontend repo with a list of extensions you enabled? I heavily suspect this is caused by some extensions writing litegraph configs.

**Comment by oliverban** [comment]
> Already reported: [Comfy-Org/ComfyUI_frontend#443](https://github.com/Comfy-Org/ComfyUI_frontend/issues/443)
> 
> Can you file an issue in the frontend repo with a list of extensions you enabled? I heavily suspect this is caused by some extensions writing litegraph configs.

Oh, sorry! Didn't see that one! Will do! I suspect you won't like that list though...it's...extensive!
