### ISSUE TITLE
Save Image from the preview node is not working

### ISSUE THREAD

**Issue by buggsi** [comfyanonymous/ComfyUI#4420]
### Expected Behavior

Not sure about what to expect, perhaps get a dialog box asking where to save the file, or save it automatically in the `ComfyUI\output` folder, like the behavior of a `Save Image` node.

### Actual Behavior

The file isn't saved anywhere, there's no dialogue box to where to save the file. The images are temporarly stored in the `ComfyUI\temp` folder, however that folder is deleted when ComfyUI is shut down.

### Steps to Reproduce

Create `Preview Image` node, generate an image, right-click in the preview box and do `Save Image`. I'm using the latest version `ComfyUI: 2548[05a9f3](2024-08-16)`.

![image](https://github.com/user-attachments/assets/bea64a19-43ca-4cef-b38e-118b2879d506)`

### Debug Logs

```powershell
None
```

**Comment by buggsi** [comment]
I just realized the files were being saved in the browser's download folder! For some reason, my LibreWolf doesn't show the download progress, so the saves went unnoticed.

**Comment by rivasmig** [comment]
yeah, I think it's on your browser then. You should config your browser so that you determine where downloads go. I tried this just now, seems to be working fine
