### ISSUE TITLE
After generating the image, the function of saving it as a model preview image is gone 生成图片后，保存成模型预览图功能不见了

### ISSUE THREAD

**Issue by upboy-web** [comfyanonymous/ComfyUI#4421]
### Feature Idea

生成图片后，保存成模型预览图功能不见了

### Existing Solutions

生成图片后，保存成模型预览图功能不见了

### Other

生成图片后，保存成模型预览图功能不见了

**Comment by mcmonkey4eva** [comment]
That's not a ComfyUI feature in the first place? You might be thinking of SwarmUI, or a comfy extension
