### ISSUE TITLE
The size of the right UI panel has become too large, so it is inconvenient to use.

### ISSUE THREAD

**Issue by hyuck9859** [comfyanonymous/ComfyUI#4423]
### Your question

After doing something, the right UI panel size got too big, making it difficult to use all the features. Is there a function to adjust the size of the area?

![image](https://github.com/user-attachments/assets/88514242-5921-44e7-9807-1679cbb48a98)

**Comment by ltdrdata** [comment]
Move mouse cursor to the right panel.
 And then `ctrl + mouse wheel`.

**Comment by mcmonkey4eva** [comment]
frontend issues go @ https://github.com/Comfy-Org/ComfyUI_frontend/
