### ISSUE TITLE
unet merge save needed 

### ISSUE THREAD

**Issue by al-swaiti** [comfyanonymous/ComfyUI#4424]
### Feature Idea

already there is checkpoint save , clip  save and vae save , but theres no unet save 

### Existing Solutions

i think cancel vae and clip input enough

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/310ad09258cd6ba80c44d31e183063455726dcb8

**Comment by DarkAlchy** [comment]
Which doesn't work for the good stuff such as extraction.  We need a node that will save in the same format the save checkpoint did as that we could extract from.

**Comment by DarkAlchy** [comment]
safetensors_rust.SafetensorError: File does not contain tensor double_blocks.0.img_attn.proj.weight

The save you now do is a bad save because it is missing the key we need, and we can't extract from them because of it.

**Comment by tarkansarim** [comment]
> safetensors_rust.SafetensorError: File does not contain tensor double_blocks.0.img_attn.proj.weight
> 
> The save you now do is a bad save because it is missing the key we need, and we can't extract from them because of it.

Getting the same error in Kohya when trying to extract a Lora from a comfyUI Flux model save node.

**Comment by sitatec** [comment]
@tarkansarim, you can run this script to make the weights compatible with kohya:
```python
from safetensors.torch import load_file, save_file

# Load original model
weights = load_file("model.safetensors")

# Rename keys by removing "model.diffusion_model."
renamed_weights = {k.replace("model.diffusion_model.", ""): v for k, v in weights.items()}

# Save the modified model
save_file(renamed_weights, "model.safetensors")
```

The issue is that it seems comfy uses a "model.diffusion_mode" prefix for the keys
