### ISSUE TITLE
Can't navigate with touch screen

### ISSUE THREAD

**Issue by KintCark** [comfyanonymous/ComfyUI#4426]
Before this new update I was able to navigate comfyui with touchscreen on my phone now that u guys added the new front-end I can't move around with touch h screen I'm forced to use a mouse. Thank God I bought  an USB docker or I would have been so upset. Please bring back touch h screen feature please. Yes comfyui works on Android termux flux and all except aura flow right now.

**Comment by mcmonkey4eva** [comment]
frontend issues go @ https://github.com/Comfy-Org/ComfyUI_frontend/
