### ISSUE TITLE
Search no longer searches nested folders

### ISSUE THREAD

**Issue by brandostrong** [comfyanonymous/ComfyUI#4427]
### Expected Behavior

When selecting loras, search will be able to search inside any nested folders.

### Actual Behavior

When selecting loras, search will not search inside nested folders, only the root. The dropdown ui still shows the loras, but search does not

### Steps to Reproduce

Using any lora loader node

### Debug Logs

```powershell
None
```

**Comment by VantomPayne** [comment]
Having same problem, the text input filter is gone and only giving me a dropdown on any lora loader, which is impractical when you have hundreds of GBs of lora.

**Comment by enternalsaga** [comment]
same problems, the new front end is still buggy to me...
![image](https://github.com/user-attachments/assets/69c31ac3-639f-45a9-818f-c6f489b836fa)

**Comment by Shingkyo** [comment]
The single most important feature which is now missing. I would like to know how to retrieve this feature...

**Comment by mcmonkey4eva** [comment]
frontend issues go @ https://github.com/Comfy-Org/ComfyUI_frontend/

**Comment by christian-byrne** [comment]
- https://github.com/Comfy-Org/ComfyUI_frontend/issues/480
