### ISSUE TITLE
Could not detect model type

### ISSUE THREAD

**Issue by bronig** [comfyanonymous/ComfyUI#4428]
![image(1)](https://github.com/user-attachments/assets/99f72f67-b603-4c58-bd16-d25486f3685d)

link to the model :https://civitai.com/models/383621/marceline-abadeer-adventure-time-ponyxl
im pretty new so i could be doing smth wrong

**Comment by ltdrdata** [comment]
That is LoRA not a checkpoint. You should move that file to `models/loras` and use `Load LoRA` instead of `Checkpoint Loader`
