### ISSUE TITLE
Queue preview Image should pull from save image node or last (not first) image preview

### ISSUE THREAD

**Issue by JLuke73** [comfyanonymous/ComfyUI#4429]
### Feature Idea

Currently in a workflow with multiple preview images, the new Queue feature's image history pulls from the first image preview node. So, for example, in a ControlNet workflow you might get a preview of an unchanging depth map as you iterate over several seeds, or in a SEGM workflow you might get a mask preview.

**Comment by mcmonkey4eva** [comment]
frontend issues go @ https://github.com/Comfy-Org/ComfyUI_frontend/
