### ISSUE TITLE
Too Few Nodes Displayed in the Search Bar of the New Interface

### ISSUE THREAD

**Issue by cilantrocatsoup** [comfyanonymous/ComfyUI#4431]
### Your question

In the new interface, the search bar displays too few nodes, making it more challenging to find the desired node compared to the previous version. I suggest either reducing the font size or extending the drop down to show more nodes. Personally, I preferred the previous layout, where up to 35 nodes were displayed at once, allowing for quicker and easier navigation to the needed node.

**Comment by mcmonkey4eva** [comment]
frontend issues go @ https://github.com/Comfy-Org/ComfyUI_frontend/
