### ISSUE TITLE
GUI Scaling Issues and File Upload Problems on iOS Browsers

### ISSUE THREAD

**Issue by xdtxkbf** [comfyanonymous/ComfyUI#4435]
### Expected Behavior

I'm experiencing issues with the GUI scaling when running ComfyUI's latest version using listen on an iPad/iPhone (Safari and Edge browsers). When I zoom in or out on the workflow, the side toolbar resizes as well, but the workflow preview does not scale logically; it merely stretches the image. This makes it difficult to use. This issue did not occur before the recent major update.
![IMG_2132](https://github.com/user-attachments/assets/a26d61c1-4e43-49d6-bf35-e7125147406a)
1.The GUI should scale logically when zooming, keeping the layout and elements readable.
2.The "Choose File" dialog should allow users to select and upload files from their device.
Additionally, I have been unable to upload images (select files) on my iPad or iPhone for a long time. Despite trying various methods, the "Choose File" functionality does not work on these devices. 

### Actual Behavior

https://github.com/user-attachments/assets/b548df3c-7fb4-4301-9289-d051436b7693

1.The GUI scales incorrectly, making the workflow preview hard to read and navigate.
2.The "Choose File" functionality is non-functional on iOS devices.

### Steps to Reproduce

1.Start ComfyUI using the listen command.
2.Connect to the GUI from an iPad or iPhone using Safari or Edge.
3.Try to zoom in or out on the workflow.
4.Attempt to select files for uploading.

### Debug Logs

```powershell
The console is not outputting anything, which is likely due to an issue with the GUI.
```

### Other

I've tested this behavior by switching between different versions of ComfyUI, and the issue consistently appears only in the latest version.This issue did not occur before the recent major update.
ComfyUI Version: f1d6cef/1770fc7/others
Device: iPad/iPhone
Browser: Safari, Edge
OS: iOS 17/ipados17

**Comment by huchenlei** [comment]
Should be fixed by https://github.com/Comfy-Org/ComfyUI_frontend/pull/483

**Comment by huchenlei** [comment]
Please wait for the next frontend release today and add `--front-end-version Comfy-Org/ComfyUI_frontend@latest` to your cmd line arg list to opt-in to use latest front-end.

**Comment by xdtxkbf** [comment]
I apologize, although the scaling issue has been resolved, there are still severe touch control problems on the iPad, making it very easy to get stuck in a frozen state. There are also error displays in the Edge browser (this doesn't happen in Safari).

**Comment by ltdrdata** [comment]
> I apologize, although the scaling issue has been resolved, there are still severe touch control problems on the iPad, making it very easy to get stuck in a frozen state. There are also error displays in the Edge browser (this doesn't happen in Safari).

As mentioned above, please submit an issue to the front repo.
