### ISSUE TITLE
[FEATURE REQUEST] Arbitrary Generation Size

### ISSUE THREAD

**Issue by Nechochwen-D** [comfyanonymous/ComfyUI#444]
I've been trying to regenerate some images but I keep running into the problem that the sampler will not accept latent images that are not clean multiples of 64. Is there any way to change this?

**Comment by DivinoAG** [comment]
That's a Stable Diffusion limitation, not exclusive to this UI. There's no way around it, so I can only recommend making images at the next bigger size and cropping to your desired size.

**Comment by Nechochwen-D** [comment]
Is that how Automatic does it?

**Comment by DivinoAG** [comment]
On A1111 WebUI there is a text field that in theory lets you type whatever value, but if you try to render anything outside of multiples of 64px it will just go back to the nearest multiple. The slider however just sticks to the multiples.

**Comment by Nechochwen-D** [comment]
I wonder if they precollapse the latent image in those areas, if they just crop the resultant image, or if they stretch/compress the image to make it fit the desired size. The image I was trying to work with is 512x712.

**Comment by fractal-fumbler** [comment]
is it even possible in ComfyUI to make picture with non-x64 resolutions: like 512x712?

**Comment by DivinoAG** [comment]
> I wonder if they precollapse the latent image in those areas, if they just crop the resultant image, or if they stretch/compress the image to make it fit the desired size. The image I was trying to work with is 512x712.

I think you missed my point. A1111 Web UI is not capable of making images at arbitrary, non-multiple of 64px sizes at all. You can type such a value in the input for image sizes (let's say 520x520px), but the rendered image will just reset back to the nearest multiple of 64px values (in that example, 512x512px), and the slider that is more commonly used for settings sizes does not allow selecting values that are not multiple of 64.

Stable diffusion only generates images at sizes that are multiples of 64, it's how it works internally, and these UIs are just that: user interfaces. They are all using the same basic Stable Diffusion AI under the hood. 

If you want to make images at 512x712, just make them at 512x768 and crop the extra pixels.

**Comment by comfyanonymous** [comment]
This is implemented. You can now sample latents that are multiples of 8 instead of 64.
