### ISSUE TITLE
 UI Text Shaking

### ISSUE THREAD

**Issue by tianxu1998** [comfyanonymous/ComfyUI#4440]
### Expected Behavior

normal display， no text shaking

### Actual Behavior

 The text on the UI starts to shake when I move the mouse.

### Steps to Reproduce

Hello,
I am experiencing an issue with ComfyUI while using it for AI drawing. The text on the UI starts to shake when I move the mouse. This makes it difficult to interact with the interface properly.
no error log.
like this: 

https://github.com/user-attachments/assets/717bbfef-e103-4ab4-9164-5c81ad35f69e

### Debug Logs

```powershell
no error log
```

**Comment by huchenlei** [comment]
Please follow instruction to disable all custom nodes and re-open if bug persists. I suspect it is caused by a custom node.

> - **3:** You confirmed that the bug is not caused by a custom node. You can disable all custom nodes by passing
        `--disable-all-custom-nodes` command line argument.
