### ISSUE TITLE
更新新版UI后对于AIGODLIKE-ComfyUI-Studio插件中的模型管理功能失效，希望能调整

### ISSUE THREAD

**Issue by 52Hz-p** [comfyanonymous/ComfyUI#4451]
### Expected Behavior

正确打开AIGODLIKE-ComfyUI-Studio中的模型管理界面
![Snipaste_2024-08-18_12-13-10](https://github.com/user-attachments/assets/2305abc3-6ddf-4ecb-bb84-9c2d216f7191)

### Actual Behavior

打开直接comfyui界面空白，需要刷新页面才可以纠正
![Snipaste_2024-08-18_12-13-46](https://github.com/user-attachments/assets/e60f9a78-375c-42bc-8e9e-898c93e63903)
![Snipaste_2024-08-18_12-13-50](https://github.com/user-attachments/assets/74369b23-f22a-4617-8c85-0b2c6fb7ad4e)

### Steps to Reproduce

无

### Debug Logs

```powershell
终端没有报错
```

### Other

无

**Comment by leohu1** [comment]
这个问题不应该在这里提吧？

**Comment by 52Hz-p** [comment]
> 这个问题不应该在这里提吧？

额，我去插件作者提，结果人家插件作者跟你回复的一模一样

**Comment by 52Hz-p** [comment]
> 这个问题不应该在这里提吧？
所以，这种问题该去哪里提0.0
