### ISSUE TITLE
Major issue with UI for mobile/touchscreen devices 

### ISSUE THREAD

**Issue by ShashwatDubey99** [comfyanonymous/ComfyUI#4470]
I know comfyui is for pc use, but it works on mobile devices also, and I use it many times on my tablet. Since the new implementation of ui, its been so much worse, the freelook doesn't work anything like it meant to be, moving nodes have been become a pain in a**, moving nodes causes slider to change and many more issues, please. really please just someone fix it.

I hate TS...

**Comment by huchenlei** [comment]
Fixed in https://github.com/Comfy-Org/ComfyUI_frontend/pull/483
