### ISSUE TITLE
Menu moves offscreen when switching apps

### ISSUE THREAD

**Issue by mcandre** [comfyanonymous/ComfyUI#4472]
### Expected Behavior

The menu should persist pan and zoom.

### Actual Behavior

The primary Que Prompt button moves offscreen every time I switch to another app and back to ComfyUI.

### Steps to Reproduce

1. Use ComfyUI in iPhone Chrome.

### Debug Logs

```powershell
N/A
```

**Comment by huchenlei** [comment]
https://github.com/comfyanonymous/ComfyUI/issues/4470
