### ISSUE TITLE
Can multi workflows share same lora or basemodel in comfyui workflows?

### ISSUE THREAD

**Issue by t00350320** [comfyanonymous/ComfyUI#4479]
### Feature Idea

can multi workflows share same lora or basemodel?
use case1: workflow 1 load basemodel base1 and lora1 and lora2
use case2: workflow 2 load basemodel base1 and lora2
use case3: workflow 3 load basemodel base2 and lora1
these cases will be loaded randomly and frequently in one comfyui server, will these models be reloaded in advance ,in another word how to preload these basemodels and loras to reduce time cost???

**Comment by ltdrdata** [comment]
You can utilize backend cache nodes in Inspire Pack.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/cache-workflow1.png
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/cache-workflow2.png

**Comment by dailingx** [comment]
> ### Feature Idea
> can multi workflows share same lora or basemodel? use case1: workflow 1 load basemodel base1 and lora1 and lora2 use case2: workflow 2 load basemodel base1 and lora2 use case3: workflow 3 load basemodel base2 and lora1 these cases will be loaded randomly and frequently in one comfyui server, will these models be reloaded in advance ,in another word how to preload these basemodels and loras to reduce time cost???
> 
> ### Existing Solutions
> _No response_
> 
> ### Other
> _No response_

hi, I have the same problem as you. 
Can you tell me how you solved it? this is very important to me, thank you.

**Comment by t00350320** [comment]
> > ### Feature Idea
> > can multi workflows share same lora or basemodel? use case1: workflow 1 load basemodel base1 and lora1 and lora2 use case2: workflow 2 load basemodel base1 and lora2 use case3: workflow 3 load basemodel base2 and lora1 these cases will be loaded randomly and frequently in one comfyui server, will these models be reloaded in advance ,in another word how to preload these basemodels and loras to reduce time cost???
> > ### Existing Solutions
> > _No response_
> > ### Other
> > _No response_
> 
> hi, I have the same problem as you. Can you tell me how you solved it? this is very important to me, thank you.

utilize the inspire-pack custom , then search cache backend data, retrieve backend data. On top of that, you create an init workflow to load all models with cache, and then call these models in different service workflows with retrieve. Feel free to left your question

**Comment by dailingx** [comment]
> > > ### Feature Idea
> > > can multi workflows share same lora or basemodel? use case1: workflow 1 load basemodel base1 and lora1 and lora2 use case2: workflow 2 load basemodel base1 and lora2 use case3: workflow 3 load basemodel base2 and lora1 these cases will be loaded randomly and frequently in one comfyui server, will these models be reloaded in advance ,in another word how to preload these basemodels and loras to reduce time cost???
> > > ### Existing Solutions
> > > _No response_
> > > ### Other
> > > _No response_
> > 
> > 
> > hi, I have the same problem as you. Can you tell me how you solved it? this is very important to me, thank you.
> 
> utilize the inspire-pack custom node, then search cache backend data, retrieve backend data. On top of that, you create an init workflow to load all models with cache, and then call these models in different service workflows with retrieve.
thank you very much for your reply. I did encounter a problem when using it. When using "retrieve backend data", I found that input prompt is not supported, and KSimpler (pipe) does not support prompt guider input, so I don’t understand how my prompt workflow should run.
![Image](https://github.com/user-attachments/assets/f737286c-c081-4ed6-9fd3-3478d461e456)

**Comment by dailingx** [comment]
It would be wonderful if you could give me an example of a workflow json.
