### ISSUE TITLE
Adding FLUX.1-dev-gguf files in the model manager

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#4489]
### Feature Idea

![image](https://github.com/user-attachments/assets/c29afec6-b9db-491a-bf6d-8812f130a514)

![image](https://github.com/user-attachments/assets/4b00f03f-6998-402f-8277-549bcf59d838)

**Comment by ltdrdata** [comment]
This request should be posted into ComfyUI-Manager.

And I will do it.
