### ISSUE TITLE
Save Checkpoint with DiT only, to minimize wasting space on t5, clip, vae - Flux space optimization

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [comfyanonymous/ComfyUI#4492]
### Feature Idea

With a lot of new models people mainly use DiT - particular with Flux.
Save Checkpoint only with DiT makes it more easy to use, expecially with large models like Flux.

### Existing Solutions

Save Checkpoint node requires Clip and Vae - making them optional would allow to save space.

**Comment by comfyanonymous** [comment]
There is a SaveModel node.
