### ISSUE TITLE
main.py: error: unrecognized arguments: --listen --gpu-only

### ISSUE THREAD

**Issue by xia-huang-411303** [comfyanonymous/ComfyUI#4496]
### Expected Behavior

running the latest version of ComfyUI on WSL with RTX4090 and RTX3090.
commit 5a69f84c3c38481dd0a78b25eb1111e82ade04b0
run `python main.py --listen --port 8888 --gpu-only` 

### Actual Behavior

![image](https://github.com/user-attachments/assets/2be79e4c-7059-4cd1-b575-247835d6491d)
I got Nothing but Blank.
Nothing reactive on cmd.

### Steps to Reproduce

None

### Debug Logs

```powershell
(ComfyUI) wangyan@JKY-DESKTOP:/mnt/e/LSY/comfyui$ python main.py --port 8888 --listen --gpu-only --disable-all-custom-nodes
Total VRAM 24564 MB, total RAM 64303 MB
pytorch version: 2.3.1+cu121
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/e/LSY/comfyui/web
Adding extra search path checkpoints ./models/Stable-diffusion/
Adding extra search path loras ./models/loras/
Adding extra search path vae ./models/vae/
Adding extra search path clip ./models/clip/
Adding extra search path clip_vision ./models/clip_vision/
Adding extra search path configs ./models/configs/
Adding extra search path controlnet ./models/controlnet/
Adding extra search path embeddings ./models/embeddings/
Adding extra search path upscale_models ./models/upscale_models/
Adding extra search path hypernetworks ./models/hypernetworks
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://0.0.0.0:8888
```
```


### Other

_No response_

**Comment by xia-huang-411303** [comment]
I tried to revert to an older version
`git reset --hard e68763f`
At first, everything worked fine, but after I loaded some custom nodes, it failed again, again with the same error

I suspect the error is related to the following two nodes：
ComfyUI-RVC
ComfyUI-MimicMotionWrapper

**Comment by Icedcocon** [comment]
I have the same problem as you. It is a problem with the ComfyUI-RVC node. It is recommended to use Comfy-RVC. The following problems still exist.


```python3
unknown args: ['--listen']
```

But comfyui and nodes work.

**Comment by xia-huang-411303** [comment]
I understand what is going on, https://github.com/AIFSH/ComfyUI-Live2DViewer
This project tampers with the./web/index.html file to refer to some non-existent js code
Cause front-end error:
` ` `
GET http://localhost:8080/lib/litegraph.css net::ERR_ABORTED 404 (Not Found)
localhost/:8

GET http://localhost:8080/style.css net::ERR_ABORTED 404 (Not Found)
localhost/:10

GET http://localhost:8080/lib/litegraph.core.js net::ERR_ABORTED 404 (Not Found)
Live2d.min.js :2 Live2D 2.1.00_1
live2d.min.js:2 profile : Desktop
live2d.min.js:2   [PROFILE_NAME] = Desktop
live2d.min.js:2   [USE_ADJUST_TRANSLATION] = false
live2d.min.js:2   [USE_CACHED_POLYGON_IMAGE] = false
live2d.min.js:2   [EXPAND_W] = 2
localhost/:11

GET http://localhost:8080/lib/litegraph.extensions.js net::ERR_ABORTED 404 (Not Found)
app.js:2  Uncaught TypeError: Cannot read properties of undefined (reading 'app')
at app.js:2:52
` ` `
My solution to this problem is to remove the ComfyUI-Live2DViewer plugin
