### ISSUE TITLE
weight_dtype fp8_e4m3fn slower than weight_dtype default problem seems fixed today

### ISSUE THREAD

**Issue by deepfree2023** [comfyanonymous/ComfyUI#4501]
### Your question

Just mention it to all the guys who've had this problem before.

I've got 3.6x s/it today instead of about 20s/it before, with weight_dtype fp8_e4m3fn.

And it's still about 5s/it with weight_dtype default.

**Comment by JorgeR81** [comment]
I just updated.
For me Flux fp8 is still slower than Flux fp16.

I'm on Windows 10
GTX 1070 ( 8GB VRAM )
32 GB RAM

I'm using the UNET loader. 

![unet](https://github.com/user-attachments/assets/bf91b5e2-8d96-4935-a7c5-219accfbdca7)

**Comment by deepfree2023** [comment]
Have you updated all nodes? 

Don't know if it's related to the new UI change, the main difference in the log seems to be "[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed."

I'm using torch 2.4.0+CUDA12.1 with xformers 0.0.27.post2, 12G vram + 64G ram

**Comment by JorgeR81** [comment]
I updated all via manager.

---

> Don't know if it's related to the new UI change, the main difference in the log seems to be "[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed."

Yeah, that seems to be related to the new UI:
https://github.com/rgthree/rgthree-comfy/issues/304

**Comment by JorgeR81** [comment]
> And some older generation GPUs have half speed fp16 operations, which these weights are likely being cast to and/or calculated at.

I have a Pascal GPU, so this commit ( https://github.com/comfyanonymous/ComfyUI/commit/8115d8cce97a3edaaad8b08b45ab37c6782e1cb4 ) made generation slower for me, both with Flux fp16 and fp8.

But after the recent performance improvements, Flux fp16 got even faster than before.
Flux GUFF and Flux fp16 now have about the same speed, for me.
Only Flux FP8 is slower.

**Comment by deepfree2023** [comment]
> > torch 2.4.0+CUDA12.1 with xformers 0.0.27.post2
> 
> This might be a problem. They don't recommend using 2.4 yet with windows, should be 2.3.1+cu121 if I recall correctly. There are some issues with 2.4.0 and Windows at the moment (unless you're using a nightly build). Also xformers isn't really needed these days since pytorch is usually equal to or better.
> 
> And some older generation GPUs have half speed fp16 operations, which these weights are likely being cast to and/or calculated at.

I've tried to install torch 2.3.1 1-2 days ago, FP8 speed increased to 10.x s/it, still much slower than FP16, so I switched back to troch 2.4.0. And found FP8 speed increased a lot today even with torch 2.4.0.

**Comment by deepfree2023** [comment]
xformers 0.0.27.post2
