### ISSUE TITLE
Date formatting of filenames: new location?

### ISSUE THREAD

**Issue by dewarrn1** [comfyanonymous/ComfyUI#4508]
### Your question

After the UI/backend refactor, I can't find the code or hooks for datetime formatting of output filenames from nodes like `SaveImage`. It used to live in `web/extensions/core/saveImageExtraOutput.js`, but that file no longer exists. Does anyone know where this lives now?

**Comment by dewarrn1** [comment]
Disregard, went ahead and implemented what I needed locally, will try to submit a PR.

**Comment by mcmonkey4eva** [comment]
see https://github.com/comfyanonymous/ComfyUI/pull/4030
