### ISSUE TITLE
Unable to pan around workspace in mobile browser after updating 

### ISSUE THREAD

**Issue by LocalYokelNZ** [comfyanonymous/ComfyUI#4509]
### Your question

I use comfyui on my phone through a vpn tunnel system and it has been working fine up until the last update which now doesn't let me pan around the workspace fluidly, its become sluggish and swiping a finger across results in a millimetre of movement.

I know mobile usage may not be strictly supported but something seems to have changed with the last update.

Ive tried this in edge and kiwi browsers with same results.  Windows usage is fine.

**Comment by huchenlei** [comment]
See https://github.com/comfyanonymous/ComfyUI/issues/4435
