### ISSUE TITLE
Operator based boolean workflow split

### ISSUE THREAD

**Issue by TathaLabs** [comfyanonymous/ComfyUI#4517]
### Feature Idea

For an example,
If imageReward score < 0, end current run
or,, If <10 and >30, execute this route

**Comment by ltdrdata** [comment]
You can utilize `Inversed Switch` in `Impact Pack`.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/switch.md#inversedswitch-any
