### ISSUE TITLE
Mouse becomes sluggish and lagging even when not running a job

### ISSUE THREAD

**Issue by W00PIE** [comfyanonymous/ComfyUI#4527]
### Your question

Hi there,

I wonder if anybody ran into the same issue: today I freshly installed ComfyUI on my Arch Linux and I experienced a heavily impacted responsiveness from my system. The mouse lagged and Alt-Tabbing to other applications also appeared delayed. This also applies to the time when there was no job running with just the web UI doing nothing other than showing the workflow nodes. I rebooted at least ten times and there hadn't been any background processes that might have interfered.

It does not make a difference if I use Chromium or Firefox. Rendering an image works flawlessly and really fast (as expected) but it seems something is wrong here. It is also not dependant on the checkpoint or any other settings, as soon as the Web UI is loaded (even with the default one), the responsiveness breaks down.

I did not experience this issue with Automatic1111 or Fooocus, here I can let the respective application render big queues without any impact on the general responsiveness. I think this somehow feels like a frontend issue... or is it?

Any ideas? Or is this reproducable/normal and I have to live with it?

### Other

My specs: up-to-date Arch Linux, 64 GB DDR4 RAM, AMD Radeon 7900 XTX with 24 GB VRAM, AMD Ryzen 9 5900X 12-Core Processor, Chromium 128.0.6613.36 without any extensions or plugins, ComfyUI running in venv with Python 3.10 and ROCm 6.1

**Comment by huchenlei** [comment]
This seems to be a frontend issue. Can you file an issue in the frontend repo with full browser log? Thanks!

https://github.com/Comfy-Org/ComfyUI_frontend/issues
