### ISSUE TITLE
flux model doesn't work, flux1-dev-fp8.safetensors

### ISSUE THREAD

**Issue by bryanray** [comfyanonymous/ComfyUI#4530]
ComfyUI_windows_portable

### Debug Logs

```powershell
Error occurred when executing CheckpointLoaderSimple:

ERROR: Could not detect model type of: D:\ComfyUI_windows_portable\ComfyUI\models\checkpoints\flux1-dev-fp8.safetensors

File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 518, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 513, in load_checkpoint_guess_config
raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
```

**Comment by bryanray** [comment]
was using "flux1-dev-fp8.json" workflow, added missing nodes with "manager".....produce the error message as above.

**Comment by Arron17** [comment]
I'd suggest providing where you got that checkpoint from. Theres a full "checkpoint" that includes the UNET plus the text encoder and vae.

But there's also one where it's just the UNET. I think the likely issue is you have the UNET version, but you are trying to load it with the checkpoint loader and not the diffusion model loader node, which gets items from the UNET folder.

**Comment by bryanray** [comment]
I THINK YOU ARE RIGHT

it is so confusing, and i download the 16.gb version which worked with comfyui,

thank you

**Comment by taiczhi** [comment]
这是因为你们都使用了错误的fp8链接。
https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors
这个才是可用模型

**Comment by wangyizhi1213** [comment]
意思是两个fp8同名模型里面一个是内置clip和vae的一个没有是吗？

**Comment by YoucanBaby** [comment]
> 这是因为你们都使用了错误的fp8链接。 https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors 这个才是可用的模型

This works for me.

**Comment by Tmerowr** [comment]
> 这是因为你们都使用了错误的fp8链接。 https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors 这个才是可用模型

fp16呢？

**Comment by ltdrdata** [comment]
> > 这是因为你们都使用了错误的fp8链接。 https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors 这个才是可用模型
> 
> fp16呢？

You are recommended to download a model where the diffusion model and text encoder are separated, instead of using a checkpoint, and to use `Load Diffusion Model` and `DualCLIPLoader`.

![Screenshot_20250731_081946_Chrome.jpg](https://github.com/user-attachments/assets/20412a0f-a8c3-447a-9b9c-d04b0a47a289)
