### ISSUE TITLE
torch._scaled_mm is only supported on devices with compute capability >= 9.0

### ISSUE THREAD

**Issue by GavChap** [comfyanonymous/ComfyUI#4531]
Using --fast I get the above error. However running this snippet in the same venv as comfy:
```bash
$  python -c "import torch; print(torch.cuda.get_arch_list())"
['sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'sm_90']
```

shows I do have the capability to run 9.0 on a 4060ti 16Gb.

Running Ubuntu 22.04 in WSL on Windows 11 with the latest Nvidia drivers.

**Comment by comfyanonymous** [comment]
Try updating your pytorch.

**Comment by GavChap** [comment]
That has now worked! Thanks for you help. Do you know if it will also work on .gguf models loaded with the gguf loader or is that up to the owner of that loader repo to work out?
