### ISSUE TITLE
The first update on August 15th caused all the if judgments of the plugins to only output true.

### ISSUE THREAD

**Issue by 807502278** [comfyanonymous/ComfyUI#4540]
### Expected Behavior

The if judgment node of the plugin works normally.

### Actual Behavior

For all plugins, the if judgment only outputs true. Changing the boolean value has no effect at all.

### Steps to Reproduce

Specific version:ab4dd19b913be95dc7f1a8080cd49aa940345c96
As shown in the figure, when it starts running,it should output the box generated by the lower node. However,in fact, it outputs the bottle generated by the upper node.
![image](https://github.com/user-attachments/assets/1e2d093b-ac57-4c39-95ea-eec8689873b9)

I tested many if nodes and they are all like this.
![image](https://github.com/user-attachments/assets/90c9db20-7b4f-4c59-8593-7aa6adea901f)

When I use the version before August 15th, it is normal. So I am sure that there is a problem with the update here.

### Debug Logs

```powershell
(The log shows no abnormalities)
```

### Other
win11  python3.11  cuda12.1  torch2.3.0

**Comment by 807502278** [comment]
In addition, there is another request. When fixing this, can those nodes that do not meet the judgment conditions not run? Because these unnecessary calculations can sometimes be extremely time-consuming.

**Comment by huchenlei** [comment]
Please file the issue in the custom node repo. Thanks!

**Comment by 807502278** [comment]
Thank you very much, it is now available for normal use!
Also, may I ask where the custom node repository is located? I only found the frontend repository:
![image](https://github.com/user-attachments/assets/3dcb8006-c8c9-4625-9d3a-67fa2b376d90)

**Comment by ltdrdata** [comment]
> Thank you very much, it is now available for normal use! Also, may I ask where the custom node repository is located? I only found the frontend repository: ![image](https://private-user-images.githubusercontent.com/46019416/360888344-3dcb8006-c8c9-4625-9d3a-67fa2b376d90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NDg1MzksIm5iZiI6MTcyNDQ0ODIzOSwicGF0aCI6Ii80NjAxOTQxNi8zNjA4ODgzNDQtM2RjYjgwMDYtYzhjOS00NjI1LTlkM2EtNjdmYTJiMzc2ZDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDIxMjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYjQ2M2NjMmVjNGM0NWViZDYzZTI2OTdjNDE3MDE0NTEzOWRhNDIwZGVjMTIzM2QyNjI0MGViMzlkYmUwOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dkPlTzmQsRTiw3KYJvTwyX0BsS6Cdwq_Z7gbETVez2Q)

The badge shows that that node is belongs to Crytools.
https://github.com/ThisKwasior/CryTools

**Comment by 807502278** [comment]
Oh, thank you for the reminder
