### ISSUE TITLE
Do not unload the model.

### ISSUE THREAD

**Issue by jiaxintang894** [comfyanonymous/ComfyUI#4543]
### Your question

"My GPU memory is large enough, and I want some models to remain in memory without being released. What should I do? Are there any suitable parameters or code modification strategies?

**Comment by ltdrdata** [comment]
You have two options. If you use the `--highvram` cli option, anything loaded into VRAM will always be kept there.
The other option is to use the `Backend Cache` nodes from the Inspire Pack.
This stores objects in a separate cache, so even if the workflow is reset, you can retrieve and use them with the Retrieve Backend Cache node.

**Comment by huangqiaobo** [comment]
you can hook the function `execution.recursive_execute`  and cache the output what you want
```python
old_recursive_execute = execution.recursive_execute
def maas_recursive_execute(
        server,
        prompt,
        outputs,
        current_item,
        extra_data,
        executed,
        prompt_id,
        outputs_ui,
        object_storage,
):
if cached_output_data:
            # use cache
            outputs[current_item] = cached_output_data
            executed.add(current_item)
res = old_recursive_execute(
            server,
            prompt,
            outputs,
            current_item,
            extra_data,
            executed,
            prompt_id,
            outputs_ui,
            object_storage,
        )
if success and current_item in outputs:
            output_data = outputs[current_item]
            # cache the output_data. if you cache it, comyfui will cant release it
return res
```

**Comment by ltdrdata** [comment]
> recursive_execute

recursive_execute is removed since PR2666 is merged.
