### ISSUE TITLE
Could you implement soft inpainting for flux?

### ISSUE THREAD

**Issue by wodsoe** [comfyanonymous/ComfyUI#4544]
@comfyanonymous 
Could you implement soft inpainting for flux?
Please refer to the below:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/14208/files

**Comment by HelloClyde** [comment]
ComfyUI has already implemented.
see https://www.reddit.com/r/comfyui/comments/1aulgmx/soft_inpainting_a1111_new_feature_is_there_any/

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/2d569dec-0701-4437-bb94-21d8123cc0c4)

**Comment by ltdrdata** [comment]
> How to use with flux? Any example workflow? @HelloClyde @ltdrdata

There's nothing special about FLUX. When you apply that and use SetLatentNoiseMask to apply a mask with varying intensities like a Gaussian blur, different levels of denoising are applied.

For your reference, when using the Detailer in Impact Pack, if noise_feather_mask is greater than 0, it automatically applies that internally.

**Comment by ltdrdata** [comment]
> But I have tested differential-diffusion before, and its effect is not as good as soft inpainting

That entirely depends on the mask you've created. 

The function is very clear, and when you preview it during sampling, it clearly shows how the effect is applied. 

If there isn't a proper difference, then you've made the blur mask incorrectly.
