### ISSUE TITLE
Try fix for missing nodes should be handled by default

### ISSUE THREAD

**Issue by TathaLabs** [comfyanonymous/ComfyUI#4546]
### Expected Behavior

Try fix for missing nodes should be handled by default because servers often need to be restarted and doing try fix everytime is a pain

### Actual Behavior

Try Fix everytime launched on missing nodes just to work fine 

### Steps to Reproduce

Default

### Debug Logs

```powershell
None
```

**Comment by ltdrdata** [comment]
Use `your_python cm-cli.py restore-dependencies` in ComfyUI-Manager dir.
And take a look https://github.com/Comfy-Org/comfy-cli
