### ISSUE TITLE
Undo feature for textareas

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [comfyanonymous/ComfyUI#4552]
### Feature Idea

I would like the textareas to have their own undo buffer when the textarea is selected.
The way undo works with textareas now is that you undo by clicking outside of the node, and then you can CTRL + Z to undo.

It's quite annoying though, if you accidentally delete something while working in a text-area, you now have to click outside to undo the action, and then click back it.

**Comment by mcmonkey4eva** [comment]
frontend issue https://github.com/Comfy-Org/ComfyUI_frontend
