### ISSUE TITLE
ComfyUI low detail of any modes with different samplers, too fast processing

### ISSUE THREAD

**Issue by Kowari1** [comfyanonymous/ComfyUI#4570]
### Your question

I use Stabiliti Matrix and I tested in ComfyUI and Automatic 1111 with different models such as the perfect world etc. I specifically wrote simple tips or took others in the public domain and used the DPM++ 2M sampler and others, in the end I came to the conclusion that I have a strange problem, in all models I have very poor detailing of characters even at a short distance, I used Automatic 1111 before and I did not have such problems but I needed to reinstall Windows after which I encountered this problem, I also downloaded ComfiUI portable version separately and it did not help also image generation is unnaturally fast with very low quality, I can not understand what to do because it is very strange, maybe you know what the problem is, because even when installing ComfyUI from scratch and minimal settings for the image on different models the problem is not eliminated. I used the most basic node scheme, just installed another sampler DPM++ 2M Karras and entered a simple prompt, and still nothing helps. When generating an image, there is practically no load on the system, despite the fact that I have 1070 16 GB of RAM, I run it on the GPU and entered the commands --force-fp16 --fp16-vae --use-pytorch-cross-attention --normalvram.

**Comment by ltdrdata** [comment]
Did this phenomenon start occurring after a specific ComfyUI update?
If so, can you confirm exactly which commit it started happening with?

**Comment by Kowari1** [comment]
> Это явление началось после определенного обновления ComfyUI? Если да, можете ли вы подтвердить, с какого именно коммита это началось?

I started using ComfyUI a month ago and I immediately had this problem, now I did a manual installation with cuda installation and it seems to be much better
