### ISSUE TITLE
ComfyUI on Google Colab - no progress indication with the green node color

### ISSUE THREAD

**Issue by DigiClau** [comfyanonymous/ComfyUI#4573]
### Your question

Is there anyone here using ComfyUI on Google Colab?
Normally, during the image generation process, each node turns green to indicate which node is currently being executed. However, that no longer appears. When I click the "Queue Prompt" button, the number in the queue increases and the image is generated, but the green progress indicator doesn’t show up at all. Does anyone know about this issue?  It happened just today—or maybe yesterday, since I didn’t use it then.

### Other

I wonder if it’s caused by the newly updated front-end UI.

**Comment by mcmonkey4eva** [comment]
Are you using cloudflared to forward the URL? there appears to be a current bug with cloudflared where it's not forwarding websockets properly

**Comment by YazzCasillas** [comment]
The same thing happened to me yesterday. And instead of using: Run Comfy with cloudflared (recommended Way) use: Run ComfyUI with localtunel. There is no that problem (or that BUG) there.

**Comment by DigiClau** [comment]
> Are you using cloudflared to forward the URL? there appears to be a current bug with cloudflared where it's not forwarding websockets properly

Thank you for your reply, [mcmonkey4eva](https://github.com/mcmonkey4eva).
Yes, I use cloudflared (Recommended Way).  It seems it happened recently and hope it is just a temporary issue and will be fixed by CloudFlaured soon.
By the way, great please to talk to you, [mcmonkey4eva](https://github.com/mcmonkey4eva). 😁

**Comment by DigiClau** [comment]
> The same thing happened to me yesterday. And instead of using: Run Comfy with cloudflared (recommended Way) use: Run ComfyUI with localtunel. There is no that problem (or that BUG) there.

Thank you for your reply, YazzCasillas.
I’m glad to know I wasn’t the only one with this issue yesterday. 😉
I’ll try running ComfyUI with localtunnel and hope it works for me too. 🙏

**Comment by mcmonkey4eva** [comment]
if you swap the download link to `https://github.com/cloudflare/cloudflared/releases/download/2024.8.2/cloudflared-linux-amd64.deb` that might make it work (older version before the breaking change)

**Comment by DigiClau** [comment]
Hi everyone,
I just tried Colab again, and it’s now working as normal. It was obviously a temporary issue, and everything is good now. 👍
