### ISSUE TITLE
Diffusers

### ISSUE THREAD

**Issue by al-swaiti** [comfyanonymous/ComfyUI#4575]
### Feature Idea

there's a big problem when convert any diffusers model to comfyui models (noraml ) ,"this problem fill the websites " , in the other hand all models its easy to convert any model to diffusers , whatever i tried many times to load diffusers models through diffusers node ,, the first promplem its search for unet folder (which is now transformers ) , i succeed loading diffusers sd3 model , by change unet folder name to transformer , but the flux not supported yet , its a good idea to become support diffusers models more which make convert them easy through save unet node ,,, and you know this become more and more popular  

### Existing Solutions

reverse diffusers codes

**Comment by ltdrdata** [comment]
Overall, your request is confusing.

1. It's not clear what models are being referred to by "diffusers" and "comfyui node (normal)". There are `DiffusersLoader` (deprecated), `Load Diffusion Model` (previously UNet Loader), and `Load Checkpoint`. Each refers to a model with a different meaning. Please explain specifically which one you are referring to. More precisely, please provide the URL for each model.

2. Load Diffusion Model was originally a node that read from the `unet` folder, and recently its name was changed to `diffusion_models`. (The `transformer` directory does not exist.)

3. To load Diffusion Model, Text Encoder, and VAE separately is achieved through the `Load Diffusion Model` node, `DualClipLoader`, and `VAELoader`. Diffusers-type FLUX models are being used in this way. Is it correct that you are aware of this method?

4. Please accurately restate the request as well.

**Comment by Scorpinaus** [comment]
Hi Ai-swaiti, do you mean loading checkpoints that have been converted to diffusers format? You can try out my custom node pack listed here: https://github.com/Scorpinaus/ComfyUI-DiffusersLoader.

It allows for loading of diffusers-format checkpoints, and supports SD3 and Flux.

**Comment by al-swaiti** [comment]
thanks @Scorpinaus  ,,, @ltdrdata thanks for support , i  mean load diffusers model its not supported in comfyui

**Comment by al-swaiti** [comment]
@Scorpinaus nice code , but need to much memory , could you import diffusers library and pip it as checkpoint loader , without convert !

**Comment by Scorpinaus** [comment]
> @Scorpinaus nice code , but need too much memory , could you import diffusers library and pip it as checkpoint loader , without convert model !

Can you elaborate on what do you mean by without convert model? You can use the Combined Diffusers Loader node, which does not convert the diffusers model.

**Comment by Scorpinaus** [comment]
Hi al-swaiti, in a recent update to the node pack, I've modified the loading method to allow multiple-file loading. That should save some memory and time. A few more questions to understand your situation:

1.  Which models are you trying to load?
2. What is your system configuration?

**Comment by al-swaiti** [comment]
sorry i was replied to u , but i notice now the messege not there , during the process the model of diffusers , converted first look at cmd during model loading

**Comment by Scorpinaus** [comment]
Hi al-swaiti, please update the node pack to the latest PR. I've made some improvements to the implementation. If it happens again, can you open up a issue on the DiffusersLoader repo?

**Comment by al-swaiti** [comment]
what i found there , some thing better than loader which is converter , you could make a node for convert diffusers to comfyui models , this very needed plus not exist
