### ISSUE TITLE
How to check the version of installed Comfyui?

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#4579]
### Your question

run update_comfyui.bat will keep comfyui always up-to-date ?

**Comment by ltdrdata** [comment]
`git describe --tags`

**Comment by pandayummy** [comment]
it returns
v0.1.2-1-g8ae23d8e

so it's the v0.1.2 Dora hotfix?

**Comment by ltdrdata** [comment]
> it returns v0.1.2-1-g8ae23d8e
> 
> so it's the v0.1.2 Dora hotfix?

That means v0.1.2 + 1 more commit

**Comment by pandayummy** [comment]
Thank you!
