### ISSUE TITLE
Unable to drag multiple nodes now

### ISSUE THREAD

**Issue by kyle215ps3** [comfyanonymous/ComfyUI#458]
Seem like i can't drag multiple nodes at once anymore. I just updated and now not letting me.

**Comment by revisited-contrast** [comment]
Also broken for me, updated master 10 minutes ago.

**Comment by fractal-fumbler** [comment]
to select: while holding `ctrl` select with LMB
to drag: while holding `shift` move mouse pointer to node. Drag with LMB

**Comment by kyle215ps3** [comment]
ok thank you, I'm curious why it got changed but it's no problem anyways :)
