### ISSUE TITLE
Plug-in suggestion

### ISSUE THREAD

**Issue by alex13by** [comfyanonymous/ComfyUI#4586]
### Feature Idea

There are many plug-ins in the function is repeated, and there are many plug-ins often only one or two nodes are required, but other functions are a lot of messy, if you can select the independent operation of the node to merge into the launch plug-in, Then the redundancy of the plug-in will be greatly improved. Or to provide a free entry into a single node, at the discretion of the user and not at the discretion of the plug-in author

**Comment by ltdrdata** [comment]
Even if the externally exposed nodes seem simple, their internal code often uses shared code with other functions. 

It's not possible to simply take some nodes and merge them to make them work.
This would be similar to developing a new node pack.
