### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode_image'

### ISSUE THREAD

**Issue by MODOMison** [comfyanonymous/ComfyUI#4591]
### Expected Behavior

run perfectly and crrate a video

### Actual Behavior

error - AttributeError: 'NoneType' object has no attribute 'encode_image'

### Steps to Reproduce

download 
run from run_nvidia_gpu
use template "crate video"

### Debug Logs

```powershell
C:\Users\matto\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
Requested to load BaseModel
Loading 1 new model
loaded completely 0.0 1639.406135559082 True
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:01<00:00, 13.53it/s]
Requested to load AutoencoderKL
Loading 1 new model
loaded completely 0.0 159.55708122253418 True
!!! Exception during processing !!! 'NoneType' object has no attribute 'encode_image'
Traceback (most recent call last):
  File "C:\Users\matto\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matto\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matto\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\matto\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matto\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_video_model.py", line 46, in encode
    output = clip_vision.encode_image(init_image)
             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode_image'

Prompt executed in 10.52 seconds
```

### Other

N/A

**Comment by ltdrdata** [comment]
Please attach your workflow so that we can diagnose the problem.

**Comment by MODOMison** [comment]
i am using this work flow from the examplle workflow set

https://comfyanonymous.github.io/ComfyUI_examples/video/

the 25 fps item

**Comment by ltdrdata** [comment]
> i am using this work flow from the examplle workflow set
> 
> https://comfyanonymous.github.io/ComfyUI_examples/video/
> 
> the 25 fps item
> 
> here is a photo ![Screenshot 2024-08-24 195851](https://private-user-images.githubusercontent.com/87583994/361181894-f34d9ae8-4228-491e-8ea7-2dc6fc4a1766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTY2NzcsIm5iZiI6MTcyNDU5NjM3NywicGF0aCI6Ii84NzU4Mzk5NC8zNjExODE4OTQtZjM0ZDlhZTgtNDIyOC00OTFlLThlYTctMmRjNmZjNGExNzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE0MzI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3Y2UwNGEzOTJjMjBlNWI3Y2IxMWVlODgzNTU2Y2M5MTk3YzQ2M2IyMWZlNTE1ZmI0NjFkOWM1Mjg1NTlhY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bydq9GuGfY-VqIbFUIzLP5qZRJkzrA3LOmqD_OVE1mE)

Selected model on `Image Only Checkpoint Loader` node is invalid.
That should be `svd_xt.safetensors`.

**Comment by zgq732** [comment]
你的问题解决了吗我也遇到了相同问题

**Comment by yi10101** [comment]
我也有问题

**Comment by yi10101** [comment]
我也有我问题，有没有人帮忙看看
