### ISSUE TITLE
After the update, ComfyUI cannot start and prompts ImportError: DLL load failed while importing_quadpack: Cannot find the specified program

### ISSUE THREAD

**Issue by ye-pei-sheng** [comfyanonymous/ComfyUI#4592]
### Expected Behavior

startup

### Actual Behavior

![825](https://github.com/user-attachments/assets/69c2a010-b937-44b2-bb9c-5028f2255009)

### Steps to Reproduce

At startup

### Debug Logs

```powershell
H:\ComfyUI_windows\ComfyUI_20240818>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --fast
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-25 06:02:09.360267
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: H:\ComfyUI_windows\ComfyUI_20240818\python_embeded\python.exe
** ComfyUI Path: H:\ComfyUI_windows\ComfyUI_20240818\ComfyUI
** Log path: H:\ComfyUI_windows\ComfyUI_20240818\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: H:\ComfyUI_windows\ComfyUI_20240818\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: H:\ComfyUI_windows\ComfyUI_20240818\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.5 seconds: H:\ComfyUI_windows\ComfyUI_20240818\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 16325 MB
pytorch version: 2.4.0+cu121
H:\ComfyUI_windows\ComfyUI_20240818\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
H:\ComfyUI_windows\ComfyUI_20240818\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
xformers version: 0.0.27.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2070 SUPER : cudaMallocAsync
Using xformers cross attention
Traceback (most recent call last):
  File "H:\ComfyUI_windows\ComfyUI_20240818\ComfyUI\main.py", line 86, in <module>
    import execution
  File "H:\ComfyUI_windows\ComfyUI_20240818\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "H:\ComfyUI_windows\ComfyUI_20240818\ComfyUI\nodes.py", line 22, in <module>
    import comfy.samplers
  File "H:\ComfyUI_windows\ComfyUI_20240818\ComfyUI\comfy\samplers.py", line 1, in <module>
    from .k_diffusion import sampling as k_diffusion_sampling
  File "H:\ComfyUI_windows\ComfyUI_20240818\ComfyUI\comfy\k_diffusion\sampling.py", line 3, in <module>
    from scipy import integrate
  File "H:\ComfyUI_windows\ComfyUI_20240818\python_embeded\Lib\site-packages\scipy\__init__.py", line 147, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "H:\ComfyUI_windows\ComfyUI_20240818\python_embeded\Lib\site-packages\scipy\integrate\__init__.py", line 96, in <module>
    from ._quadpack_py import *
  File "H:\ComfyUI_windows\ComfyUI_20240818\python_embeded\Lib\site-packages\scipy\integrate\_quadpack_py.py", line 7, in <module>
    from . import _quadpack
ImportError: DLL load failed while importing _quadpack: 找不到指定的程序。

H:\ComfyUI_windows\ComfyUI_20240818>pause
```

**Comment by ye-pei-sheng** [comment]
`H:\ComfyUI_windows\ComfyUI_20240818\python_embeded>.\python.exe -m pip list
Package                   Version
------------------------- ------------------
absl-py                   2.1.0
accelerate                0.33.0
addict                    2.4.0
aiohttp                   3.9.5
aiosignal                 1.3.1
albucore                  0.0.13
albumentations            1.4.14
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
anyio                     4.4.0
arrow                     1.3.0
attrs                     23.2.0
beautifulsoup4            4.12.3
binaryornot               0.4.4
bitsandbytes              0.43.3
boto3                     1.35.0
botocore                  1.35.0
cachetools                5.5.0
certifi                   2024.7.4
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        3.3.2
click                     8.1.7
clip-interrogator         0.6.0
cmake                     3.30.2
colorama                  0.4.6
coloredlogs               15.0.1
colorlog                  6.8.2
colour-science            0.4.4
contourpy                 1.2.1
cookiecutter              2.6.0
cpm-kernels               1.0.11
cryptography              43.0.0
cssselect2                0.7.0
cycler                    0.12.1
Cython                    3.0.11
deepdiff                  7.0.1
Deprecated                1.2.14
diffusers                 0.30.0
easydict                  1.13
einops                    0.8.0
eval_type_backport        0.2.0
fairscale                 0.4.13
fastapi                   0.112.1
filelock                  3.15.4
flatbuffers               24.3.25
flet                      0.23.2
flet-core                 0.23.2
flet-runtime              0.23.2
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.6.1
ftfy                      6.2.3
fvcore                    0.1.5.post20221221
gdown                     5.2.0
gguf                      0.9.1
gitdb                     4.0.11
GitPython                 3.1.43
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.24.2
humanfriendly             10.0
idna                      3.7
imageio                   2.35.1
importlib_metadata        8.2.0
inference                 0.14.1
insightface               0.7.3
intel-openmp              2021.4.0
iopath                    0.1.10
jax                       0.4.31
jaxlib                    0.4.31
Jinja2                    3.1.4
jmespath                  1.0.1
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
kornia                    0.7.3
kornia_rs                 0.1.5
lark-parser               0.12.0
lazy_loader               0.4
lightning-utilities       0.11.6
llvmlite                  0.43.0
lxml                      5.3.0
manifold3d                2.5.1
mapbox_earcut             1.0.2
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.8.0
matrix-client             0.4.0
mdurl                     0.1.2
mediapipe                 0.10.14
mkl                       2021.4.0
ml-dtypes                 0.4.0
mpmath                    1.3.0
multidict                 6.0.5
networkx                  3.3
numba                     0.60.0
numpy                     1.26.4
oauthlib                  3.2.2
omegaconf                 2.3.0
onnx                      1.16.2
onnxruntime               1.19.0
onnxruntime-gpu           1.19.0
open_clip_torch           2.26.1
opencv-contrib-python     4.10.0.84
opencv-python             4.10.0.84
opencv-python-headless    4.10.0.84
opt-einsum                3.3.0
ordered-set               4.1.0
packaging                 23.2
pandas                    2.2.2
piexif                    1.1.3
pilgram                   1.2.1
pillow                    10.4.0
pip                       24.2
pixeloe                   0.0.10
platformdirs              4.2.2
pooch                     1.8.2
portalocker               2.10.1
prettytable               3.11.0
protobuf                  4.25.4
psutil                    6.0.0
py-cpuinfo                9.0.0
pycocoevalcap             1.2
pycocotools               2.0.8
pycollada                 0.8
pycparser                 2.22
pydantic                  2.8.2
pydantic_core             2.20.1
pygit2                    1.15.1
PyGithub                  2.3.0
Pygments                  2.18.0
PyJWT                     2.9.0
PyMatting                 1.1.12
PyNaCl                    1.5.0
pynvml                    11.5.3
pyparsing                 3.1.2
pypng                     0.20220715.0
pyreadline3               3.4.1
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-slugify            8.0.4
pytorch-lightning         2.4.0
pytz                      2024.1
pywin32                   306
PyYAML                    6.0.1
qrcode                    7.4.2
qudida                    0.0.4
referencing               0.35.1
regex                     2024.7.24
rembg                     2.0.58
repath                    0.9.0
reportlab                 4.2.2
requests                  2.32.3
rich                      13.7.1
rpds-py                   0.20.0
Rtree                     1.3.0
s3transfer                0.10.2
safetensors               0.4.3
scikit-image              0.24.0
scikit-learn              1.5.1
scipy                     1.14.0
seaborn                   0.13.2
segment-anything          1.0
sentencepiece             0.2.0
setuptools                72.1.0
shapely                   2.0.5
shellingham               1.5.4
simpleeval                0.9.13
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
sounddevice               0.5.0
soundfile                 0.12.1
soupsieve                 2.6
spandrel                  0.3.4
starlette                 0.38.2
svg.path                  6.3
svglib                    1.5.1
sympy                     1.13.1
tabulate                  0.9.0
tbb                       2021.13.0
termcolor                 2.4.0
text-unidecode            1.3
threadpoolctl             3.5.0
tifffile                  2024.8.10
timm                      0.6.13
tinycss2                  1.3.0
tokenizers                0.19.1
tomli                     2.0.1
torch                     2.4.0+cu121
torchaudio                2.4.0
torchmetrics              1.4.1
torchsde                  0.2.6
torchvision               0.19.0
tqdm                      4.66.4
trampoline                0.1.2
transformers              4.43.3
transparent-background    1.3.1
trimesh                   4.4.6
typer                     0.12.4
types-python-dateutil     2.9.0.20240316
typing_extensions         4.12.2
tzdata                    2024.1
ultralytics               8.2.78
ultralytics-thop          2.0.3
urllib3                   1.26.19
uvicorn                   0.30.6
vhacdx                    0.0.8.post1
watchdog                  4.0.2
watchfiles                0.23.0
wcwidth                   0.2.13
webencodings              0.5.1
websockets                12.0
wget                      3.2
wheel                     0.44.0
wrapt                     1.16.0
xatlas                    0.0.9
xformers                  0.0.27.post2
xxhash                    3.5.0
yacs                      0.1.8
yapf                      0.40.2
yarl                      1.9.4
zipp                      3.20.0

H:\ComfyUI_windows\ComfyUI_20240818\python_embeded>
`

**Comment by ye-pei-sheng** [comment]
After disabling xformer, ComfyUI returns to normal
`--disable-xformers`
However, until ComfyUI is updated today, xformer can load normally

**Comment by ltdrdata** [comment]
> After disabling xformer, ComfyUI returns to normal `--disable-xformers` However, until ComfyUI is updated today, xformer can load normally

support of xformers for latest pytorch is very bad, recently.
you need to build xformers on your machine by your self.
