### ISSUE TITLE
Node search not working

### ISSUE THREAD

**Issue by ChrisTello** [comfyanonymous/ComfyUI#4603]
### Expected Behavior

when double clicking on empty area a search bar for searching nodes should appear and typing in a name of a node should show results.

### Actual Behavior

The search bar appears but nothing happens even after typing in a name of a node that is installed.

### Steps to Reproduce

Updated to recent comfyui release

### Debug Logs

```powershell
no errors appear in the command line window outside of this line 
"IMPORT FAILED: nodes_audio.py

This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
Please do a: pip install -r requirements.txt"
```

**Comment by gangisbrawn** [comment]
hey im having the same issue! my node search is not working Aswell i have my confy ui fully updated

**Comment by ltdrdata** [comment]
For those who can't use node search, check if `NestedNodeBuilder` is installed in the `custom_nodes` path and delete it.

**Comment by ChrisTello** [comment]
> For those who can't use node search, check if `NestedNodeBuilder` is installed in the `custom_nodes` path and delete it.

that worked, thanks.
