### ISSUE TITLE
[Bug] Can't connect primitive nodes to some converted inputs of cloned nodes

### ISSUE THREAD

**Issue by Bocian-1** [comfyanonymous/ComfyUI#461]
So far, I've only seen it in both KSamplers with _sampler_name_, _scheduler_, _add_noise_, and _return_with_leftover_noise_

To reproduce:
 - make a KSampler
 - convert widgets to inputs
 - clone the KSAMPLER
 - can't connect some of the inputs of both nodes to a primitive node

If converted back to the widget and back to input again it fixes itself

**Comment by fractal-fumbler** [comment]
noticed same behaviour like day or 1.5 ago, but didn't pay attention to this issue
