### ISSUE TITLE
Text Animation

### ISSUE THREAD

**Issue by MODOMison** [comfyanonymous/ComfyUI#4613]
### Your question

I am working on this workflow from open art
here is the link to the workflow online, it is also bugged: aprrox 5 months old
https://openart.ai/workflows/fish_upbeat_83/text-animation/JGUFPZp6GnYgHfty0aEw

only this small area is bugged maybe you can fix it 
here is a screen shot
![Screenshot 2024-08-26 030934](https://github.com/user-attachments/assets/04a95689-9568-4d04-bd2f-f00206f98841)

here is a screen shot from the site, also bugged. 
![Screenshot 2024-08-26 031350](https://github.com/user-attachments/assets/38c0e6bc-c630-4a12-a909-d7a96ba56468)
ps. please fix the other error not this error
the 2nd screen shot is only for reference

**Comment by ltdrdata** [comment]
That workflow is so much outdated.

Some of the node is renamed so it isn't exists anymore.
(see this: https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes)
You need to replace it to new node.
