### ISSUE TITLE
After clicking on the full preview of the historical generated images in the new ComfyUI interface, it is not possible to save the images by right clicking. We hope for optimization

### ISSUE THREAD

**Issue by Beseting** [comfyanonymous/ComfyUI#4623]
### Your question

After clicking on the full preview of the historical generated images in the new ComfyUI interface, it is not possible to save the images by right clicking. We hope for optimization

**Comment by christian-byrne** [comment]
Fixed in #4691 (Comfy-Org/ComfyUI_frontend#588)
