### ISSUE TITLE
Issue with loading queues (invalid workflow against zod schema) validation error

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#4627]
### Your question

![image](https://github.com/user-attachments/assets/e9f5a09a-b60b-466c-934a-f7b82b5ace8c)

I am loading a list of queues from a .json and get these error messages after update.

**Comment by BrechtCorbeel** [comment]
I am using a utility I created to get the prompts out of the file, but it seems a datatype issue, no idea why these should be read fine in comfy, it might be update related, but on this file I now seem to have an error indicating I should read it with utf-8:
![image](https://github.com/user-attachments/assets/e8f1ee6e-0d6c-4d2b-953c-55c05f9e00da)

**Comment by BrechtCorbeel** [comment]
ok so I had badly converted utf-8 characters in my prompts causing this issue:

if you want it solved run this script I created to solve the issue:

```
import json
import codecs

# Load the JSON file
with open('J:\\brech\\Documents\\after error2.json', 'r', encoding='utf-8') as file:
    data = json.load(file)

# Function to fix encoding
def fix_encoding(text):
    try:
        # Decode the text using the wrong encoding and re-encode it correctly
        return text.encode('latin1').decode('utf-8')
    except (UnicodeEncodeError, UnicodeDecodeError):
        # If there's an issue, return the original text
        return text

# Fix encoding for the 'populated_text' key
if 'populated_text' in data:
    data['populated_text'] = fix_encoding(data['populated_text'])

# Save the corrected JSON back to the file
with open('J:\\brech\\Documents\\your_file_fixed.json', 'w', encoding='utf-8') as file:
    json.dump(data, file, ensure_ascii=False, indent=4)

print("File encoding fixed and saved as 'your_file_fixed.json'")
```

**Comment by Whitespidee88** [comment]
How do i add this in script?
