### ISSUE TITLE
cannot import name 'args' from 'cli_args' 

### ISSUE THREAD

**Issue by laojingwei** [comfyanonymous/ComfyUI#463]
**File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors-main\../../comfy/model_management.py", line 3, in <module>
    from cli_args import args
ImportError: cannot import name 'args' from 'cli_args' (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\cli_args\__init__.py)**

I got the above error when I went to install comfy_controlnet_preprocessors and ran install.py. I entered this file model_management.py and saw that it used cli_args, but the args inside could not be obtained normally. What is the reason for this? I guarantee that cli_args is installed, and executing import cli_args is normal, but I don’t know why from cli_args import args reports an error. I don’t understand python. How can I solve this?

**Comment by WASasquatch** [comment]
Try leaving your issue with the actual creator of the preprocessors nodes: https://github.com/Fannovel16/comfy_controlnet_preprocessors 

It is Fannovel16's responsibility to maintain his project in scope with ComfyUI.
