### ISSUE TITLE
Almost unusably-slow - nodes fail to cache after recent update. ComfyUI now redundantly reprocesses unchanged inputs at every queue (IPAdapter reloads its model, ControlNet reloads depth map image, etc.)

### ISSUE THREAD

**Issue by robertalanbevan** [comfyanonymous/ComfyUI#4631]
I use ComfyUI on Windows 10, running Stable Diffusion 1.5. I've tested this in Brave browser and Microsoft Edge and had the same results. 

I always use a Save Image node to render the processed ControlNet depth map for my analysis, and it's never done this before. The processed depth image normally shows up in the output feed once, and never has to be reloaded again until I change something relevant to the depth map, like changing my depth image or how the depth image is cropped. This new redundant reprocessing occurs with or without that Save Image node, and it hugely impacts my processing times. I made the following workflow from scratch to ensure this wasn't just a quirk of my usual workflow:
![comfyui bug](https://github.com/user-attachments/assets/3ea2d884-8d5e-4b8c-81a4-86067ee87edc)

I'd also give an example or proof of this with IPAdapter if I could, but all I can discern is that it takes around twice the processing time compared to usual (ControlNet was removed from that workflow when I tested this). IPAdapter seems to reprocess its model (e.g., from two unchanging images) at every queue.

The actual SD models don't reload, thankfully. Switching the "randomized" latent seed to "fixed" also did nothing - so it even fails when the entire workflow is static and unchanging. The log contains no errors.

I put this under User Support because my current guess is that this is just me missing a newly-introduced setting, or the result of some of my prior tinkering that's interfering with a new feature. Possibly something to do with the recent update's new RAM handling features. I've also noticed the "free model and node cache" and "unload models" buttons on the new top/bottom menu, which seems like it must be related.

Have I just unticked a "Reuse unchanged node and model inputs in cache" setting somewhere?

**Update:** after a fresh install, this seems to be resolved. I haven't installed any extra nodes. No update on what caused it.

**Comment by icchansan** [comment]
Yeh its taking 30mins what usually took 20-30secs

**Comment by comfyanonymous** [comment]
Can you post the actual workflow?

**Comment by robertalanbevan** [comment]
> Can you post the actual workflow?
[testing-node-cache-workflow.json](https://github.com/user-attachments/files/16766556/testing-node-cache-workflow.json)
It doesn't seem to be the result of anything I manually changed in my workflow - I noticed it immediately after updating and restarting. I always update my installed nodes along with ComfyUI itself, so I suppose it's possible an updated node is the culprit and not ComfyUI.

**Comment by comfyanonymous** [comment]
if you replace that Zoe-DepthMapPreprocessor with the "Canny" node does it have the same behaviour?

**Comment by robertalanbevan** [comment]
![image](https://github.com/user-attachments/assets/5d03aed2-4b1a-4987-a2ba-7ff054427593)
No change when I switched to the Canny image processor node. I tried it with both the Canny ControlNet model as well as the Depth model. I'll make a new install of ComfyUI and report if that fixes it.

**Comment by comfyanonymous** [comment]
Can you reproduce it on a simple workflow with core only nodes?

**Comment by robertalanbevan** [comment]
![image](https://github.com/user-attachments/assets/61f01950-f9c4-4e1b-ab9f-906e7b60b5ca)
I removed the obvious non-core nodes and went through and made sure the rest were all core nodes - no change. This is still on my main ComfyUI install, so I haven't yet gotten around to testing a fresh install.

**Comment by robertalanbevan** [comment]
The fresh install seems to have fixed the problem. Still not sure what caused it.
