### ISSUE TITLE
bnb4-unet support

### ISSUE THREAD

**Issue by al-swaiti** [comfyanonymous/ComfyUI#4636]
### Feature Idea

sorry  i reopen this issue because its needed , and its closed without reason 
![image](https://github.com/user-attachments/assets/7d05a710-4f8c-4012-bc4d-d8d956ba7ffa)
![image](https://github.com/user-attachments/assets/47fa5501-a42e-4c8b-949f-7db673233709)

**Comment by Mikerhinos** [comment]
It's supported through custom nodes, I use both everyday.
I can understand if Comfy doesn't want to implement it natively in ComfyUI as we don't know how many time these will be used.
Maybe tomorrow there will be a new version different from NF4 and GGUF, that will need another custom node, and ComfyUI will become bloated by useless loading nodes.
