### ISSUE TITLE
Floating point precision warning in brownian_interval.py

### ISSUE THREAD

**Issue by LaughterOnWater** [comfyanonymous/ComfyUI#4645]
### Expected Behavior

Error free image generation.

### Actual Behavior

It's not stopping my generation, but I'm encountering the following warning when generating images using ComfyUI (which utilizes torchsde):

:\Users\Chris\miniconda3\envs\comfy_new\lib\site-packages\torchsde\_brownian\brownian_interval.py:608: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")

### Steps to Reproduce

Generate an image using SDXL in comfyui with various nodes

### Debug Logs

```powershell
no debug logs
```

### Other

I'm reporting this here too in case the problem is not with torchsde but rather some other conflict within ComfyUI. It's not stopping my generation, but I'm encountering the following warning when generating images using ComfyUI (which utilizes torchsde):

:\Users\Chris\miniconda3\envs\comfy_new\lib\site-packages\torchsde\_brownian\brownian_interval.py:608: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")

Environment:
- ComfyUI version: v0.1.x (Build 2621, Commit 6bbdcd, 2024-08-27, "Devil In the Details")
- torchsde version: 0.2.6
- Python version: 3.10.14
- Operating System: Windows 10, Nvidia RTX 3090

Additional context:
This appears to be a floating point precision issue in the comparison between `tb` and `t1`.

Please let me know if you need any additional information.

**Comment by mcmonkey4eva** [comment]
warnings like that can be ignored
