### ISSUE TITLE
How i to do int to float Node (can link value from other node)

### ISSUE THREAD

**Issue by Gotppsn** [comfyanonymous/ComfyUI#4652]
### Feature Idea

I went this node i find on goolgle and github but not have like this
can you help me find this node or find way to do this
![image](https://github.com/user-attachments/assets/3a3f4da1-f22b-46fb-ab0e-e8ce7c7749eb)

### Existing Solutions

am try this but not work it don't have link value from other node
DF_Int_to_Float Node
IntToFloat Node

**Comment by blepping** [comment]
seems like it's from this node pack: https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes

i found it using a Google search for `comfyui "int to float" df`
