### ISSUE TITLE
ComfyUI started but the page crashes the browser

### ISSUE THREAD

**Issue by kurophali** [comfyanonymous/ComfyUI#4657]
### Expected Behavior

start ui normally

### Actual Behavior

I started it via vscode and got the log
`
Starting server
To see the GUI go to: http://127.0.0.1:8188
`

I tried with chrome and only the menu flashed for 1 frame then the browser said the page crashed with STATUS_BREAKPOINT. I also tried edge and it did not work.

I'm wondering if it's my workflow that caused this. Is there anyway I can replace the startup workflow in comfyUI to try if it works out?

### Steps to Reproduce

I did not find the cause

### Debug Logs

```


### Other

_No response_

**Comment by lord-lethris** [comment]
FYI - this started happening to me yesterday WITHOUT updating anything.
After updating, sometimes it works, sometimes it doesn't.

I don't think its the start-up workflow, as I have tried different browsers (which have there own ComfyUI cache).

Tried in:
- Chrome
- Edge
- Opera GX

They all either take ages to spin up or present this error:

![image](https://github.com/user-attachments/assets/a6b164f5-e9af-4c76-86ef-e1b3d3520cfa)

**Comment by kurophali** [comment]
> p

For me I just found that it was the custom nodes in Jovimetrix that caused the problem, even if you didn't use it in the workflow. Refreshing did not work and there's no additional error logs either.
BTW I tried fast clicking on the load button before the page crashes but it didn't work lols.
Try to move your custom nodes in one by one to identify which one causes the problem.

**Comment by huchenlei** [comment]
Issue transferred.

**Comment by Amorano** [comment]
[ERROR] An error occurred while retrieving information for the 'ClipTextFromTemplateEncode' node.
Traceback (most recent call last):
  File "D:\apps\SD-WebUI\ComfyUI\server.py", line 468, in get_object_info
    out[x] = node_info(x)
  File "D:\apps\SD-WebUI\ComfyUI\server.py", line 436, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\apps\SD-WebUI\ComfyUI\custom_nodes\CLIPTextFromTemplateEncode.py", line 36, in INPUT_TYPES
    cls.styles = [row for row in reader if len(row) == 3 and row[1] != "prompt" and row[0] != "None"]
  File "D:\apps\SD-WebUI\ComfyUI\custom_nodes\CLIPTextFromTemplateEncode.py", line 36, in <listcomp>
    cls.styles = [row for row in reader if len(row) == 3 and row[1] != "prompt" and row[0] != "None"]
  File "D:\apps\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 61: character maps to <undefined>

That isnt a Jovimetrix problem, that is a problem in ClipText not being able to decode the unicode emoji.

**Comment by Amorano** [comment]
> CLIPTextFromTemplateEncode

Can you tell us where you even got this node? The error implies is a raw CLIPTextFromTemplateEncode.py file in your custom node directory which is either something you made or is not within the Manager repository of registered nodes.

The problem that node is having, not my pack, is the use of old encoding methods. Update the encoding to Unicode not just the older Windows Codepage 1252.

**Comment by without-ordinary** [comment]
I'm still able to repo the tab process crash on head without Jovimetrix enabled.
https://github.com/Comfy-Org/ComfyUI_frontend/issues/641

**Comment by huchenlei** [comment]
> I'm still able to repo the tab process crash on head without Jovimetrix enabled. [Comfy-Org/ComfyUI_frontend#641](https://github.com/Comfy-Org/ComfyUI_frontend/issues/641)

These are not the same error.

**Comment by christian-byrne** [comment]
> > CLIPTextFromTemplateEncode
> 
> Can you tell us where you even got this node? The error implies is a raw CLIPTextFromTemplateEncode.py file in your custom node directory which is either something you made or is not within the Manager repository of registered nodes.
> 
> The problem that node is having, not my pack, is the use of old encoding methods. Update the encoding to Unicode not just the older Windows Codepage 1252.

That node can be found here: https://civitai.com/models/28238/simple-text-style-template-node-for-comfyui
