### ISSUE TITLE
New Search Function Seems to Not Work

### ISSUE THREAD

**Issue by lord-lethris** [comfyanonymous/ComfyUI#4658]
### Expected Behavior

When I Double click on a workflow space to add a new node via search, I expect the search to have a pre-listed cache of nodes.

### Actual Behavior

Currently the Search bar pops up and the little throbber just sits there spinning.  I have left it for a good 45 min (in the hope its trying to cache for the first time) whilst I got some lunch, but nothing happens.  There is no node list.  The filter also does not do anything when I click on it, by that I mean I click on it and nothing happens.

![image](https://github.com/user-attachments/assets/1767f809-eb50-4b40-b9fa-38e2e3ec312d)

### Steps to Reproduce

Load ComfyUI
Double click on a workflow space
wait...

### Debug Logs

```powershell
There are no errors or logs when this happens, even in debug.
```

### Other

As a note, would it be possible to add in the setting the option to revert to "classic search" (_the one we had before_) it was perfect.
If not, can this not pre-cache on bootup?

Thank you in advance.

**Comment by ltdrdata** [comment]
Remove `NestedNodeBuilder` from `custom_nodes` dir.

**Comment by lord-lethris** [comment]
Quite bold closing this without conformation

Irrelevant now - I found the old menu, which IMHO is better.
For anyone stumbling across this post - the legacy menu is here.

![image](https://github.com/user-attachments/assets/3154e99a-5044-4d10-8f01-bd9c82f069a4)
