### ISSUE TITLE
[FEATURE REQUEST] Upscale as a percentage

### ISSUE THREAD

**Issue by Gorislav** [comfyanonymous/ComfyUI#466]
Make a change in the size of images (latent including) not through the exact values, but through the percentage with preservation of proportions. As separate node or just another field for Upscale Latent / Upscale Image

**Comment by WASasquatch** [comment]
You should peer around town at node packages people have. This has been added to almost all node plugin packages like my own: https://github.com/WASasquatch/was-node-suite-comfyui (Image Resize Node)

**Comment by DivinoAG** [comment]
> You should peer around town at node packages people have. This has been added to almost all node plugin packages like my own: https://github.com/WASasquatch/was-node-suite-comfyui (Image Resize Node)

I noticed that both yours, and some other node plugin package I found before only include **latent** upscale with multiply, but not the standard upscale. Is that a limitation that exists somehow, or just an oversight?

**Comment by Gorislav** [comment]
> You should peer around town at node packages people have. This has been added to almost all node plugin packages like my own: https://github.com/WASasquatch/was-node-suite-comfyui (Image Resize Node)

I looked it up and latent upscale by factor is what I need!

**Comment by DivinoAG** [comment]
> There is both a Latent Upscale by Factor (should probably have been named Latent Rescale), and Image Resize (which can do rescaling, and resizing)
> 
> Do downscale just use a factor below 1 (which would be same size). So 0.5 would be half sized.

I don't see an option to upscale using a factor besides the latent one after installing your package. This is all I have:

![image](https://user-images.githubusercontent.com/5044664/231006571-f1a97689-1a72-456f-81ed-e23f83d5997e.png)

ImageScale is the native one, being displayed on the left.

**Comment by WASasquatch** [comment]
> This has been added to almost all node plugin packages like my own: https://github.com/WASasquatch/was-node-suite-comfyui (Image Resize Node)

> I don't see an option to upscale using a factor besides the latent one after installing your package. This is all I have:

I made a repo to start tracking plugins: https://github.com/WASasquatch/comfyui-plugins/blob/main/README.md

**Comment by miasik** [comment]
> As separate node or just another field for Upscale Latent / Upscale Image
Here is one more module to look for "upscale by factor"
https://civitai.com/models/21996

**Comment by morphles** [comment]
Such feature seems like unneeded, provided math nodes are implemented that can work with base primitives, which I think is not the case, yet, at least not in rev I have checked out. For some reason WAS math nodes do not operate on primitives of base nodes. So from UI this all seems messy, and IMO math nodes on general fields (which they should also always be able to act as outputs...), would solve this "for free".

**Comment by WASasquatch** [comment]
> Such feature seems like unneeded, provided math nodes are implemented that can work with base primitives, which I think is not the case, yet, at least not in rev I have checked out. For some reason WAS math nodes do not operate on primitives of base nodes. So from UI this all seems messy, and IMO math nodes on general fields (which they should also always be able to act as outputs...), would solve this "for free".

You can't use `INT` and `FLOAT` as only inputs strangely in custom nodes. Front end won't even allow you. So the node just doesn't make sense to if user has to right click and convert the inputs. That seems like a bug to me. 

But you can use math in the fields now so if you upscaling 4x you can use math on the value it's in resize nodes. Like `*0.5`

**Comment by morphles** [comment]
I agree it seems like a bug, and math nodes should just work on "builtin" number types. As for math in fields, yeah discovered that some time ago, nice but still, proper math node on arbitrary numbers would be much better. As math in field is only for manual adjustments, if I want to have flow, that does say hres fixes of various params, and then change base width or height, I have to go and manually reenter in any connected hi res fixes. Which is just silly.

**Comment by WASasquatch** [comment]
> 

Yeah definitely agree. I figured with the introduction of primitive it might come with those and stopped working on new math nodes. Though on that note I just added Number Input Switch based on boolean and Number Input Condition which is basically a lot of comparisons, some are in basic Number Operations node.

**Comment by comfyanonymous** [comment]
"Upscale Image by" and "Upscale Latent by".
