### ISSUE TITLE
Node Search Box not working with custom nodes

### ISSUE THREAD

**Issue by earnshame** [comfyanonymous/ComfyUI#4662]
### Your question

I updated comfy to the latest version yesterday, everything seemed to work fine. Re-enabled the custom nodes I use and searching for nodes no longer works, it never actually displays results. I disabled the custom nodes and it worked again, after that I tested just enabling one set of custom nodes and it didn't work. I tested other single sets and none of them worked either. I can add more details if needed. Also I apologize if this should be considered a bug report, I wasn't sure.

Edit: This seems to only apply to the new search style, not the legacy setting

**Comment by huchenlei** [comment]
It's known that https://github.com/coolzilj/ComfyUI-LJNodes interferes with the new searchbox.

**Comment by huchenlei** [comment]
Please file an issue to https://github.com/Comfy-Org/ComfyUI_frontend/issues with browser logs and custom nodes you installed. Thanks!
