### ISSUE TITLE
Hyper-FLUX Guider_Basic error

### ISSUE THREAD

**Issue by maxin9966** [comfyanonymous/ComfyUI#4665]
### Expected Behavior

1

### Actual Behavior

1

### Steps to Reproduce

            hyper_lora = "Hyper-FLUX.1-dev-8steps-lora.safetensors"
            unet_lora = LoraLoaderModelOnly.load_lora_model_only(unet, hyper_lora, 0.125)

            cond, pooled = clip.encode_from_tokens(clip.tokenize(positive_prompt), return_pooled=True)
            cond = [[cond, {"pooled_output": pooled}]]
            cond = FluxGuidance.append(cond, guidance)[0]
            noise = RandomNoise.get_noise(seed)[0]
            guider = BasicGuider.get_guider(unet_lora, cond)[0]
            sampler = KSamplerSelect.get_sampler(sampler_name)[0]
            sigmas = BasicScheduler.get_sigmas(unet_lora, scheduler, steps, 1.0)[0]
            latent_image = EmptyLatentImage.generate(closestNumber(width, 16), closestNumber(height, 16))[0]
            sample, sample_denoised = SamplerCustomAdvanced.sample(noise, guider, sampler, sigmas, latent_image)
            # model_management.soft_empty_cache()
            decoded = VAEDecode.decode(vae, sample)[0].detach()

### Debug Logs

```powershell
Traceback (most recent call last):
  File "/home/ma/work/flux/demo/TotoroUI/flux-demo-lora.py", line 542, in gen
    img_path, image = gen_with_api(prompt, steps, guidance, width, height, seed)
  File "/home/ma/work/flux/demo/TotoroUI/flux-demo-lora.py", line 404, in gen_with_api
    return generate2(prompt, steps, guidance, width, height, seed)
  File "/home/ma/work/flux/demo/TotoroUI/flux-demo-lora.py", line 523, in generate2
    guider = BasicGuider.get_guider(unet_lora, cond)[0]
  File "/home/ma/work/flux/demo/TotoroUI/comfy_extras/nodes_custom_sampler.py", line 485, in get_guider
    guider = Guider_Basic(model)
  File "/home/ma/work/flux/demo/TotoroUI/comfy/samplers.py", line 667, in __init__
    self.model_options = model_patcher.model_options
AttributeError: 'tuple' object has no attribute 'model_options'
```

**Comment by peki12345** [comment]
Hi, I have the same problem, how did you solve it?
