### ISSUE TITLE
[FEATURE REQUEST] Comment box

### ISSUE THREAD

**Issue by Gorislav** [comfyanonymous/ComfyUI#468]
Make a field where you can leave a comment in an arbitrary place.

**Comment by ltdrdata** [comment]
While I do think that this feature is necessary, for now, we can use the prompt node as a substitute.

**Comment by Gorislav** [comment]
Yes, that's what I'm doing now.

**Comment by jwd-dev** [comment]
As a good first issue, I can try to take this one up. Looking to learn in depth about ComfyUI. I'll let everyone know how it goes.

**Comment by jwd-dev** [comment]
Voting to mark this as closed.

**Comment by Gorislav** [comment]
Thank you!
