### ISSUE TITLE
installed comfy from scratch on my pc and the minute i open it manager says its out of date

### ISSUE THREAD

**Issue by rachelcenter** [comfyanonymous/ComfyUI#4686]
### Expected Behavior

i expect to install comfyui portable from scratch, install manager and not have manager say out of date. 

### Actual Behavior

I install comfyui portable to my external hard drive (SSD), installed manager, opened comfyui,. opened manager,. only to be told its out of date when i literally just installed it from scratch 

### Steps to Reproduce

i've installed comfyui from scratch on my pc. _(and i'm getting pretty good at it too, this is like a weekly occurrence having to reinstall from scratch due to a hard drive going bad or a bad custom node bricking me from being able to get back into the program.....)._ i downloaded the "direct link" for comfyui portable from the official git hub page https://github.com/comfyanonymous/ComfyUI/releases/latest/download/ComfyUI_windows_portable_nvidia.7z and I unzip it, and the only folder I added to the custom nodes was "manager" (i cloned it from github into the custom nodes folder) and then the minute I open comfyui and open manager it tells me its out of date. and if i try to hit update it says failed. how is it outdated when I literally just installed from scratch? 

### Debug Logs

```powershell
E:\Comfyui MOVE THIS\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-29 19:18:24.119922
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI
** Log path: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.1 seconds: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 10240 MB, total RAM 32471 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\web
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)

Import times for custom nodes:
   0.0 seconds: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
Update ComfyUI
ComfyUI update fail: Cmd('git') failed due to: exit code(128)
  cmdline: git remote show origin
  stderr: 'fatal: detected dubious ownership in repository at 'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI'
'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI' is on a file system that does not record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory 'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI''
Update ComfyUI
ComfyUI update fail: Cmd('git') failed due to: exit code(128)
  cmdline: git remote show origin
  stderr: 'fatal: detected dubious ownership in repository at 'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI'
'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI' is on a file system that does not record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory 'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI''
```

**Comment by comfyanonymous** [comment]
It's out of date with the latest git version but not the latest stable version.

**Comment by rachelcenter** [comment]
where do i find the stable version for PC?

**Comment by rachelcenter** [comment]
> It's out of date with the latest git version but not the latest stable version.

where do i find the stable version for PC?

**Comment by comfyanonymous** [comment]
Latest stable version is the standalone package linked in the readme, you can use update/update_comfyui_stable.bat to update to the latest stable.

**Comment by rachelcenter** [comment]
> Latest stable version is the standalone package linked in the readme, you can use update/update_comfyui_stable.bat to update to the latest stable.

I went to the "read me.md" https://github.com/comfyanonymous/ComfyUI/blob/master/README.md and it jsut takes me to the same link I already used today that says direct download. This response from you is not very helpful. Can you please give me the exact link since theres clearly confusion about which "read me" file you're talking about. and by the way, with the "direct download" version that I installed today , i did your bat file. ALL OF THEM. and it still says outdated.

**Comment by rachelcenter** [comment]
> It's out of date with the latest git version but not the latest stable version.

please update it then on github

**Comment by rachelcenter** [comment]
is this the website youre talking about? https://github.com/comfyanonymous/ComfyUI/releases

**Comment by rachelcenter** [comment]
i installed the one that says it was uploaded "4 days ago" on this website https://github.com/comfyanonymous/ComfyUI/releases and immediately upon opening it, it says my comfy is out of date. So I ran the "update_comfyui_stable" file, as well as "update_comfyui_and_python_dependencies" and "update_comfyui". opened comfy back up, went to manager and it still says outdated. tried updating comfy from manager and it said failed.

**Comment by rachelcenter** [comment]
E:\Comfyui MOVE THIS\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-29 20:46:06.023303
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI
** Log path: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.0 seconds: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 10240 MB, total RAM 32471 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\web
E:\Comfyui MOVE THIS\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)

Import times for custom nodes:
   0.0 seconds: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.2 seconds: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]

**Comment by rachelcenter** [comment]
close this ticket. the issue is that the "stable" version you were talking about related to manager installation, not comfy installation. Please always be more clear and provide links.
