### ISSUE TITLE
flux fp8 inference

### ISSUE THREAD

**Issue by JayL323** [comfyanonymous/ComfyUI#4689]
### Your question

Thanks open Source for such an excellent project. May I ask if the input is quantified by default during inference?Whether it refers to input quantization

**Comment by comfyanonymous** [comment]
The default is weights are in fp8 and are upcasted to bf16 or fp16 during inference. With the --fast option the matrix mults are performed in fp8 which means the input is downcasted to fp8 before being passed to the fp8 matrix mult function. The accumulator is in 32 bit so the output is in higher precision.

**Comment by JayL323** [comment]
Thanks for the detailed answer！It's very useful to me.
