### ISSUE TITLE
Updating having symbolic link

### ISSUE THREAD

**Issue by NOTlinnkoln** [comfyanonymous/ComfyUI#4692]
### Expected Behavior

Update ComfyUI or notify about the error outside then console log

### Actual Behavior

Do not updates, but writes that update was successful 

### Steps to Reproduce

Remove the model folder
Make a symlink to model folder
Try to update the ComfyUI

### Debug Logs

```powershell
Update ComfyUI
Cmd('git') failed due to: exit code(1)
  cmdline: git stash
  stderr: 'error: 'models/checkpoints/put_checkpoints_here' is beyond a symbolic link
fatal: Unable to process path models/checkpoints/put_checkpoints_here
Cannot save the current worktree state'
Install: pip packages
Line is comment...skipping
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
All extensions are already up-to-date.

![image](https://github.com/user-attachments/assets/070e1e5e-a045-4d8b-a535-dd244f15e76b)
```

**Comment by ltdrdata** [comment]
This is a limitation of git system. Files belonging to a git repository should not be modified using symlinks.
