### ISSUE TITLE
Load OneTrainer Flux LoRas and DoRas

### ISSUE THREAD

**Issue by ejektaflex** [comfyanonymous/ComfyUI#4695]
### Feature Idea

It looks like the Flux branch for OneTrainer is nearing completion - and the results are looking great! However, it seems as though ComfyUI cannot load the resulting .safetensors file. Attached is a text file with all of the keys of the resulting DoRa.

[no-work.txt](https://github.com/user-attachments/files/16822683/no-work.txt)

**Comment by DarkViewAI** [comment]
+1 Same for me as well

**Comment by comfyanonymous** [comment]
Can I have an example file for this?

**Comment by ejektaflex** [comment]
I'll see what I can do - GitHub is limited to 25MB and my rank 1 DoRa was 26MB if I remember right 🥲

**Comment by comfyanonymous** [comment]
Just upload it on huggingface or civitai.

**Comment by ejektaflex** [comment]
Here you are:

https://github.com/ejektaflex/ot_dora_test

**Comment by ejektaflex** [comment]
I tried this after [d043997](https://github.com/comfyanonymous/ComfyUI/commit/d043997d30d91ab057f770d3396c2e288e37b38a) and I do indeed get working results with a *LoRa*, but *not* with a *DoRa*.

I updated the repo above with a non-fried example DoRa model.

**Comment by comfyanonymous** [comment]
That's a problem with the dora file.

**Comment by Enyakk** [comment]
> That's a problem with the dora file.
It seems to be a general problem. I've had the exact same pink noise effect with a DoRA trained out of Onetrainer.

**Comment by comfyanonymous** [comment]
should be fixed now.
