### ISSUE TITLE
【Feature】：Double click GROUP title to edit

### ISSUE THREAD

**Issue by amimi818** [comfyanonymous/ComfyUI#4703]
### Feature Idea

a similar function like node title editing:
    "Double click GROUP title to edit"

**Comment by brayevalerien** [comment]
Being able to edit the color of a group in a similar manner would be a great feature too.

Maybe a color picker could be displayed alongside the text field when you are editing a group title?

**Comment by huchenlei** [comment]
Done in https://github.com/Comfy-Org/ComfyUI_frontend/pull/715
