### ISSUE TITLE
ComfyUI cloudflared on Google Colab does not start at all.

### ISSUE THREAD

**Issue by DigiClau** [comfyanonymous/ComfyUI#4705]
### Your question

If anyone is using ComfyUI on Google Colab, please help.

I use Cloudflared (the recommended way) to run ComfyUI on Google Colab. When I click the ComfyUI link in the output console, ComfyUI opens in another browser tab as normal. However, the page immediately stops loading and shows nothing. This has been happening since August 30, 2024.

I actually posted about another issue with Cloudflare last week https://github.com/comfyanonymous/ComfyUI/issues/4573. 
I heard there might be a bug with Cloudflared, and [mcmonkey4eva](https://github.com/mcmonkey4eva) suggested using an older version of the Cloudflared package (before the breaking change) https://github.com/comfyanonymous/ComfyUI/issues/4573#issuecomment-2307838541.
I switched to the older version to see if it might fix the issue this time, but ComfyUI is still not loading.
I’m worried that we may no longer be able to run ComfyUI with Cloudflared on Google Colab after Cloudflare's recent update.

Dear developers, please support Colab users.

**Comment by Dam88en** [comment]
I've been having this issue ALL DAY, appreciate you pointing this out! I thought I must've downloaded the wrong models/noads, or something terrible happened where ComfyUI just didn't work anymore, I guess I'm not the only one

**Comment by Dam88en** [comment]
Can anyone come to a solution on how to fix this?

**Comment by BorisB82** [comment]
Bit late maybe, but i had the same problem with it just being stuck on loading when using CF tunnels. I only managed to solve it by installing Cloudflared with CLI not the dashboard, and for some reason it works with it.  you can still manage access from applications even with the CLI method

**Comment by DigiClau** [comment]
> Bit late maybe, but i had the same problem with it just being stuck on loading when using CF tunnels. I only managed to solve it by installing Cloudflared with CLI not the dashboard, and for some reason it works with it. you can still manage access from applications even with the CLI method

Thank you for this.  I just tested the notabook on https://github.com/ltdrdata/ComfyUI-Manager/tree/main/notebooks days ago and it works fine.  This one seems recently updated.

**Comment by DigiClau** [comment]
The notebook on https://github.com/ltdrdata/ComfyUI-Manager/tree/main/notebooks works fine now.
