### ISSUE TITLE
The new front end selects nodes from the node interface-add Node-, this function is invalid.

### ISSUE THREAD

**Issue by hben35096** [comfyanonymous/ComfyUI#4722]
### Expected Behavior

Create new node

### Actual Behavior

No new node is created

### Steps to Reproduce

https://github.com/user-attachments/assets/dc3b46d0-9b6b-4653-9192-b9095862d448

### Debug Logs

```powershell
no
```

**Comment by ltdrdata** [comment]
It seems that your front is outdated. Update to latest version. And try again.


https://github.com/user-attachments/assets/48ca7120-dea1-47a0-b447-ec8cc0f2bda2

**Comment by hben35096** [comment]
No, sorry, it's my fault for not explaining clearly.
I've just upgraded, and the current version is: b643eae08b7f0c8eb69b77bd61e31009bfb325b9, but the issue still persists.
Out of habit, I set "Node search box implementation" to "litegraph (legacy)" because it allows node selection through the menu.

---

The issue of not being able to create nodes via "add Node" started occurring from version: c90459eba0daf15796de2fd7b9e7d8d42f7c7e71. It was working fine before that.

**Comment by hben35096** [comment]
I always find it tiring to search for nodes from a long dropdown list.
![PixPin_2024-09-01_20-41-10](https://github.com/user-attachments/assets/e6caccb6-c010-46c5-b845-426acdbe4f63)

**Comment by ltdrdata** [comment]
This issue is not occurring in the legacy search box.
Try disabling the custom node and test it.

**Comment by hben35096** [comment]
Thank you for your reply .
What I mean is that searching for nodes in the search box and creating nodes works without any issues in any version of ComfyUI. The issue lies specifically with the "add Node" menu in the "litegraph (legacy)" mode.

I have switched between different versions of ComfyUI, tried different operating systems, and used different browsers. All versions before c90459eba0daf15796de2fd7b9e7d8d42f7c7e71 were working normally after clicking the "Add Node" menu, but the problem started from version "c90459e".

https://github.com/user-attachments/assets/f66d63c2-9706-40f1-8db4-9e7ce048340b

**Comment by ltdrdata** [comment]
@huchenlei I cannot reproduce the issue on my end. However, it seems that it needs to be looked into.

**Comment by ltdrdata** [comment]
> Thank you for your reply . What I mean is that searching for nodes in the search box and creating nodes works without any issues in any version of ComfyUI. The issue lies specifically with the "add Node" menu in the "litegraph (legacy)" mode.
> 
> I have switched between different versions of ComfyUI, tried different operating systems, and used different browsers. All versions before [c90459e](https://github.com/comfyanonymous/ComfyUI/commit/c90459eba0daf15796de2fd7b9e7d8d42f7c7e71) were working normally after clicking the "Add Node" menu, but the problem started from version "c90459e".
> 
>  20240901_233835.mp4

Try on chrome browser instead of edge.

**Comment by hben35096** [comment]
OK, here's what fires in the Firefox and Google Chrome consoles:
![PixPin_2024-09-02_00-56-22](https://github.com/user-attachments/assets/85e74cfc-96a3-4a9d-90e4-88d641bbe8d3)
![PixPin_2024-09-02_00-50-07](https://github.com/user-attachments/assets/ff0b190f-0800-43cc-97a1-367c738f7f9d)

**Comment by hben35096** [comment]
It seems to have nothing to do with browser plug-ins or VPN settings. I will ask others tomorrow if they have the same problem.

**Comment by huchenlei** [comment]
I cannot reproduce it locally. Can you try disable all custom node and see if the problem persists?

**Comment by hben35096** [comment]
OK, I'll try it

**Comment by hben35096** [comment]
I found it, it is:
ComfyUI-Custom-Scripts
I moved this folder outside of ComfyUI and everything went back to normal
