### ISSUE TITLE
[Bug]: torch.OutOfMemoryError in KSampler

### ISSUE THREAD

**Issue by paco690** [comfyanonymous/ComfyUI#4725]
The report has been copied to the clipboard. Please paste it here.

**Comment by robinjhuang** [comment]
@paco690 Can you provide more information? Please copy over the information in error dialog and paste it here.

**Comment by ltdrdata** [comment]
This issue typically occurs due to lack of resources and is too vague, so I'm closing it.
If you believe it's a bug, please register it as a specific issue.
