### ISSUE TITLE
About huggingface-hub forced downgrade issue

### ISSUE THREAD

**Issue by wuzhonghui56** [comfyanonymous/ComfyUI#4737]
### Your question

I have upgraded huggingface-hub to a new version, why does it force me to downgrade every time I start comfyui? How can I solve this problem? Because my integration package has installed many plug-ins, it is not convenient to use the latest one, so I want to know from which file I can modify the relevant code
![微信截图_20240901232907](https://github.com/user-attachments/assets/9d4b5ff6-8790-47a1-920e-1493d445f950)

**Comment by ltdrdata** [comment]
This is an issue of ComfyUI_VLM_nodes
https://github.com/gokayfem/ComfyUI_VLM_nodes
