### ISSUE TITLE
Custom nodes: import js files dynamically

### ISSUE THREAD

**Issue by lucafoscili** [comfyanonymous/ComfyUI#4746]
### Your question

Hi! I'm coding a custom node that lets the user chat in real time with a local LLM.
I included a code viewer, however the languages modules would have to be loaded dynamically to avoid a bunch of useless js to be loaded upfront.

![Screenshot 2024-09-02 142443](https://github.com/user-attachments/assets/c9c8c8e0-e1c1-498a-8101-358200d1ada2)

I searched far and wide but I didn't find a way to "mark" which Javascript files in the `web` directory should be loaded or not.
Is there actually a way to do that and did I miss it, or this option is currently not supported?

Thank you and keep up the awesome work 💯

**Comment by ltdrdata** [comment]
Instead of configuring which files to find, use the approach of placing only the `.js` files that should be loaded in the target path.
