### ISSUE TITLE
Few nodes does not exist

### ISSUE THREAD

**Issue by rafikg** [comfyanonymous/ComfyUI#4749]
### Expected Behavior

I am following some tutorial on Youtube and It seems that some Node does not exist. I want to insert nodes:
1. Image Enhance Difference
2. Tensor Shape Debug
These are not existing

### Actual Behavior

I could not find these nodes

### Steps to Reproduce

Double click to insert the node and search for it.

### Debug Logs

```powershell
I did not get any log
```

**Comment by teward** [comment]
There are a lot of tutorials that use third party node packs.  Did you check the tutorial and its description to see if they say to install a third party node pack first?

**Comment by rafikg** [comment]
Not really, he did not mention. I write him, so if I got an answer I'll update the issue. thanks
