### ISSUE TITLE
Inserting another workflow with a Reroute node doesn't work

### ISSUE THREAD

**Issue by IcyIntuition** [comfyanonymous/ComfyUI#4750]
### Expected Behavior

I expect to be able to add any saved workflow into the current workflow by clicking the "Insert this workflow into the current workflow" button in the saved workflows list.

### Actual Behavior

When the saved workflow includes a `Reroute` node the workflow isn't inserted and an error is logged in the browser console.

### Steps to Reproduce

Try to add a workflow with a reroute to the current workflow.

### Debug Logs

```powershell
Uncaught (in promise) TypeError: app2.graph.links[l] is undefined
    types rerouteNode.ts:48
    onConnectionsChange rerouteNode.ts:48
    configure litegraph.es.js:2011
    configure litegraph.es.js:1825
    configure app.ts:1681
    configure snapToGrid.js:160
    configure reroutePrimitive.js:14
    _LGraph2 litegraph.es.js:656
    insert workflows.ts:379
    action workflows.ts:669
    ComfyButton button.ts:112
    ComfyButton button.ts:106
    #getInsertButton workflows.ts:655
    #getWorkflowElement workflows.ts:697
    #createLeafNode workflows.ts:705
    #createNode workflows.ts:729
    updateTree workflows.ts:538
    load workflows.ts:372
    ComfyWorkflowsContent workflows.ts:345
    #show popup.ts:80
    open popup.ts:51
    set utils.ts:146
    toggle popup.ts:58
    ComfyButton button.ts:109
rerouteNode.ts:48:28
```

**Comment by PitticusFinch** [comment]
Same here. I use Comfyui with StabilityMatrix on Mac. I hadn´t found out, why some workflows are added, some not. Yes, it´s reroute. At least an advice. Thanks

**Comment by mcmonkey4eva** [comment]
frontend issue https://github.com/Comfy-Org/ComfyUI_frontend
