### ISSUE TITLE
ComfyUI Settings menu not scrollable without mousewheel

### ISSUE THREAD

**Issue by brknsoul** [comfyanonymous/ComfyUI#4751]
There should be a scroll bar in the settings menu.

### Steps to Reproduce

Open settings menu, attempt to scroll the menu without using the mousewheel.
(Arrow keys work, if the centre frame is focused, but that's non-obvious.)

**Comment by mcmonkey4eva** [comment]
frontend issue https://github.com/Comfy-Org/ComfyUI_frontend
