### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by DTdota** [comfyanonymous/ComfyUI#4759]
### Expected Behavior

How To Solve This??

### Actual Behavior

after update, and get this problem

### Steps to Reproduce

![Screenshot (633)](https://github.com/user-attachments/assets/2a030561-7538-4e02-9d87-cfdaf8ff00f9)

### Debug Logs

```powershell
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
pause
```

**Comment by ltdrdata** [comment]
You need to reinstall torch.
Use this command.

https://github.com/comfyanonymous/ComfyUI/issues/3663#issuecomment-2303313684

**Comment by Vektor369** [comment]
> You need to reinstall torch. Use this command.
> 
> [#3663 (comment)](https://github.com/comfyanonymous/ComfyUI/issues/3663#issuecomment-2303313684)

Y'think? Torch **was** installed. You want to help, tell us how to prevent ComfyUI from uninstalling it again, or re-installing it wrong again, or whatever it did.
