### ISSUE TITLE
How to start from your own workflow.json

### ISSUE THREAD

**Issue by XksA-me** [comfyanonymous/ComfyUI#4760]
### Your question

How to set your own workflow.json when running python main.py

**Comment by XksA-me** [comment]
from #4085 

This works for me 

1、Download and restart
```bash
cd ComfyUI/custom_nodes
git clone https://github.com/pythongosssss/ComfyUI-Custom-Scripts
cd ComfyUI
python main.py --listen
```
2、Import your own workflow to be saved, then `Save to Workflow`
<img width="388" alt="image" src="https://github.com/user-attachments/assets/3805fa27-d50f-4b6a-be2b-a4c86d2839df">
3、Load from a saved workflow
<img width="402" alt="image" src="https://github.com/user-attachments/assets/7f8050b4-032c-406f-850e-b12916767753">

**Comment by XksA-me** [comment]
It would be even better if the user could specify the workflow.json parameter when starting it. Thank you for your work.

**Comment by mcmonkey4eva** [comment]
the workflow shown when you open up is whatever you last had open
