### ISSUE TITLE
Problem with installing "Reactor".

### ISSUE THREAD

**Issue by Padraix** [comfyanonymous/ComfyUI#4767]
### Your question

Problem with installing "Reactor".

Hello. I have a problem with installing Reactor. I have tried many ways but with each solved problem a new one appeared, and i noticed that I got lost and started going around in circles. I have three files in the insight face folder:

insightface-0.7.3-cp311-cp311-win_amd64.whl,
inswapper_128.onnx,
insightface-0.7.3-cp310-cp310-win_amd64.whl,

However, when I try to run (reactor) it in ComfyUI, the program does not see it. I have  latest version of ComfyUI. I did it  update_comfyui and update_comfyui_and_python_dependencies

Please help :)

### Logs

```powershell
\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build  --gpu-only
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-03 15:44:55.896421
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: D:\Programy\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI
** Log path: D:\Programy\ComfyUI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   2.4 seconds: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main

Total VRAM 6144 MB, total RAM 8190 MB
pytorch version: 2.4.0+cu121
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\web
D:\Programy\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: 2643 [00a5d081] | Released on '2024-09-03'
Traceback (most recent call last):
  File "D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[comfy_mtb] | INFO -> loaded 80 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.

Import times for custom nodes:
   0.0 seconds: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.5 seconds (IMPORT FAILED): D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.7 seconds: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main
   2.0 seconds: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main\extension-node-map.json [DONE]
```

**Comment by JorgeR81** [comment]
I had a similar issue ( IMPORT FAILED ).

You need `insightface-0.7.3-cp311-cp311-win_amd64.whl`, because that's the one that matches your python version.

You need to place it in the `ComfyUI_windows_portable` folder.

Then you have to run a cmd. See here: https://github.com/ltdrdata/ComfyUI-Manager/issues/188#issuecomment-1899134188

More info in the developer's instructions here: https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

**Comment by Padraix** [comment]
I followed your directions and it seems I have installed Reactor:
C:\Windows\system32>cd D:\Programy\ComfyUI\ComfyUI_windows_portable\python_embeded

C:\Windows\system32>python.exe -m pip install D:\Programy\ComfyUI\insightface-0.7.3-cp310-cp310-win_amd64.whl
Processing d:\programy\comfyui\insightface-0.7.3-cp310-cp310-win_amd64.whl
Requirement already satisfied: numpy in d:\programy\python\lib\site-packages (from insightface==0.7.3) (1.26.2)
Requirement already satisfied: onnx in d:\programy\python\lib\site-packages (from insightface==0.7.3) (1.14.0)
Requirement already satisfied: tqdm in d:\programy\python\lib\site-packages (from insightface==0.7.3) (4.66.1)
Requirement already satisfied: requests in d:\programy\python\lib\site-packages (from insightface==0.7.3) (2.31.0)
Requirement already satisfied: matplotlib in d:\programy\python\lib\site-packages (from insightface==0.7.3) (3.8.2)
Requirement already satisfied: Pillow in d:\programy\python\lib\site-packages (from insightface==0.7.3) (9.2.0)
Requirement already satisfied: scipy in d:\programy\python\lib\site-packages (from insightface==0.7.3) (1.11.4)
Requirement already satisfied: scikit-learn in d:\programy\python\lib\site-packages (from insightface==0.7.3) (1.3.2)
Requirement already satisfied: scikit-image in d:\programy\python\lib\site-packages (from insightface==0.7.3) (0.22.0)
Requirement already satisfied: easydict in d:\programy\python\lib\site-packages (from insightface==0.7.3) (1.11)
Requirement already satisfied: cython in d:\programy\python\lib\site-packages (from insightface==0.7.3) (3.0.7)
Requirement already satisfied: albumentations in d:\programy\python\lib\site-packages (from insightface==0.7.3) (1.3.1)
Requirement already satisfied: prettytable in d:\programy\python\lib\site-packages (from insightface==0.7.3) (3.9.0)
Requirement already satisfied: PyYAML in d:\programy\python\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
Requirement already satisfied: qudida>=0.0.4 in d:\programy\python\lib\site-packages (from albumentations->insightface==0.7.3) (0.0.4)
Requirement already satisfied: opencv-python-headless>=4.1.1 in d:\programy\python\lib\site-packages (from albumentations->insightface==0.7.3) (4.9.0.80)
Requirement already satisfied: networkx>=2.8 in d:\programy\python\lib\site-packages (from scikit-image->insightface==0.7.3) (3.2.1)
Requirement already satisfied: imageio>=2.27 in d:\programy\python\lib\site-packages (from scikit-image->insightface==0.7.3) (2.33.1)
Requirement already satisfied: tifffile>=2022.8.12 in d:\programy\python\lib\site-packages (from scikit-image->insightface==0.7.3) (2023.12.9)
Requirement already satisfied: packaging>=21 in d:\programy\python\lib\site-packages (from scikit-image->insightface==0.7.3) (23.2)
Requirement already satisfied: lazy_loader>=0.3 in d:\programy\python\lib\site-packages (from scikit-image->insightface==0.7.3) (0.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\programy\python\lib\site-packages (from matplotlib->insightface==0.7.3) (1.2.0)
Requirement already satisfied: cycler>=0.10 in d:\programy\python\lib\site-packages (from matplotlib->insightface==0.7.3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\programy\python\lib\site-packages (from matplotlib->insightface==0.7.3) (4.47.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\programy\python\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in d:\programy\python\lib\site-packages (from matplotlib->insightface==0.7.3) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in d:\programy\python\lib\site-packages (from matplotlib->insightface==0.7.3) (2.8.2)
Requirement already satisfied: protobuf>=3.20.2 in d:\programy\python\lib\site-packages (from onnx->insightface==0.7.3) (4.25.1)
Requirement already satisfied: typing-extensions>=3.6.2.1 in d:\programy\python\lib\site-packages (from onnx->insightface==0.7.3) (4.9.0)
Requirement already satisfied: wcwidth in d:\programy\python\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.12)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\programy\python\lib\site-packages (from requests->insightface==0.7.3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\programy\python\lib\site-packages (from requests->insightface==0.7.3) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\programy\python\lib\site-packages (from requests->insightface==0.7.3) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\programy\python\lib\site-packages (from requests->insightface==0.7.3) (2023.11.17)
Requirement already satisfied: joblib>=1.1.1 in d:\programy\python\lib\site-packages (from scikit-learn->insightface==0.7.3) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\programy\python\lib\site-packages (from scikit-learn->insightface==0.7.3) (3.2.0)
Requirement already satisfied: colorama in d:\programy\python\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Requirement already satisfied: six>=1.5 in d:\programy\python\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
insightface is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.

C:\Windows\system32>

But when I restart ComfyUI I get the info:

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-03 20:38:13.138412
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\Programy\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI
** Log path: D:\Programy\ComfyUI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   2.4 seconds: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main

Total VRAM 6144 MB, total RAM 8190 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\web
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: 2641 [f1c23016] *DETACHED | Released on '2024-09-01'
Traceback (most recent call last):
  File "D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus\__init__.py", line 1, in <module>
    from .photomaker import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus\photomaker.py", line 19, in <module>
    from .insightface_package import analyze_faces, insightface_loader
  File "D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus\insightface_package.py", line 3, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

Cannot import D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus module for custom nodes: No module named 'insightface'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Traceback (most recent call last):
  File "D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
D:\Programy\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(

Import times for custom nodes:
   0.0 seconds: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.1 seconds (IMPORT FAILED): D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus
   0.3 seconds: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing
   0.6 seconds (IMPORT FAILED): D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.7 seconds: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main\extension-node-map.json [DONE]
FETCH DATA from: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: D:\Programy\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main\.cache\746607195_github-stats.json [DONE]


And still i have :

![Reactor error](https://github.com/user-attachments/assets/28ba9054-1e96-4c05-9811-f111e792f67b)

**Comment by JorgeR81** [comment]
Your cmd line says:

> insightface is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.

I also don't have much experience with the cmd line.
But I think it has not installed correctly, because you need to run the cmds from the portable Comty UI folder. 
You have to go to the "**ComfyUI_windows_portable**" folder and type "cmd" in the address bar, to open the cmd line.

The full cmd depends on where you have the Comfy UI folder, but in your case I think it should look like this: ...

`D:\Programy\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl`

... instead of this:

> C:\Windows\system32>python.exe -m pip install D:\Programy\ComfyUI\insightface-0.7.3-cp310-cp310-win_amd64.whl
> Processing d:\programy\comfyui\insightface-0.7.3-cp310-cp310-win_amd64.whl

---
If this does not work,  you can try `--force-reinstall` like it says in your cmd line  ( maybe like this, I'm not sure ):

D:\Programy\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe -m pip --force-reinstall insightface-0.7.3-cp311-cp311-win_amd64.whl

---

But it may be better to just uninstall and install again:

D:\Programy\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe -m pip uninstall insightface

**Comment by mcmonkey4eva** [comment]
issue is with reactor, not core comfy
