### ISSUE TITLE
Pull out the cable from the node and click "add node".

### ISSUE THREAD

**Issue by Tanglinling** [comfyanonymous/ComfyUI#4770]
### Your question

Pull out the cable from the node and click "add node".
![image](https://github.com/user-attachments/assets/cc622e9b-e4f5-4a3c-9abd-7fd2d7188b91)
And the original in the upper right corner of the node will show the node belongs to the plug-in, but one day it does not show all, I am very square! I have tried all the options in the Settings and can not be restored, anyone know what is wrong?还有原来在节点右上角会显示这个节点所属的插件，但是有一天它全部不显示了，我很方！我尝试了设置里所有的选项都没办法恢复，有人知道是咋回事吗？
![image](https://github.com/user-attachments/assets/8984458d-f258-498a-bb86-cf9d74e24a8e)

**Comment by ltdrdata** [comment]
That is a feature of ComfyUI-Manager.
ComfyUI-Manager is either not installed, failed to import, or the option is turned off.

If it has been installed correctly, you can set the nickname option in the ComfyUI-Manager's dialog.

**Comment by Tanglinling** [comment]
> 这是 ComfyUI-Manager 的一个功能。ComfyUI -Manager 可能未安装、导入失败或该选项已关闭。
> 
> 如果已正确安装，您可以在 ComfyUI-Manager 的对话框中设置昵称选项。

感谢！Thank you very much! I found where to set it, I thought it was comfyui's own feature, no wonder I haven't found it. Thanks for the tip!
