### ISSUE TITLE
After updating comfyui v0.2.1, an error occurred and the clip text encoder turned red

### ISSUE THREAD

**Issue by wuzhonghui56** [comfyanonymous/ComfyUI#4777]
### Your question

![20240904163757](https://github.com/user-attachments/assets/c709d361-6c07-425f-abb2-f5789be1af96)

**Comment by Dam88en** [comment]
DWPreprocssor does this to me

**Comment by ltdrdata** [comment]
Please upload the full log file (comfyui.log).

**Comment by wuzhonghui56** [comment]
> 请上传完整的日志文件（comfyui.log）。

[comfyui.log](https://github.com/user-attachments/files/16885811/comfyui.log)
No error is prompted, only the node turns red when an error occurs

**Comment by ltdrdata** [comment]
Disable all custom nodes and check if `CLIPTextEncode` node is restored.

**Comment by wuzhonghui56** [comment]
> 禁用所有自定义节点并检查`CLIPTextEncode`节点是否恢复。

When I removed all custom nodes and restarted, it returned to normal. What should I do?

**Comment by ltdrdata** [comment]
> > 禁用所有自定义节点并检查`CLIPTextEncode`节点是否恢复。
> 
> When I removed all custom nodes and restarted, it returned to normal. What should I do?

You need to identify which custom node is causing the problem by restoring the custom nodes one by one.

After identifying the custom node causing the problem, please post an issue in the corresponding repository. Additionally, leave a note here indicating which custom node it was for the benefit of other users.

**Comment by wuzhonghui56** [comment]
> > > 取消所有节点并检查`CLIPTextEncode`节点是否恢复。
> > 
> > 
> > 当我删除所有自定义节点并重新启动时，它恢复正常。我该怎么办？
> 
> 您需要通过逐个恢复自定义节点来确定哪个自定义节点导致了问题。
> 
> 确定导致问题的自定义节点后，请在相应的存储库中发布问题。此外，请在此处留下注释，指出是哪个自定义节点，以便其他用户参考。
Thank you, I found the problem caused by the node "cg-use-everywhere".
