### ISSUE TITLE
Native support for Flux MistoLine ControlNet

### ISSUE THREAD

**Issue by JorgeR81** [comfyanonymous/ComfyUI#4784]
### Feature Idea

Support the new MistoLine ControlNet for Flux.
https://huggingface.co/TheMistoAI/MistoLine_Flux.dev

### Existing Solutions

Custom node from the model creator:
https://github.com/TheMistoAI/MistoControlNet-Flux-dev

**Comment by kakachiex2** [comment]
Mistoline for SDXL is excellent, but this implementation is super slow and give Noised render in the sampler.

**Comment by JorgeR81** [comment]
This was just implemented: https://github.com/comfyanonymous/ComfyUI/commit/5cbaa9e07c97296b536f240688f5a19300ecf30d

But I get an KSampler error: `mat1 and mat2 shapes cannot be multiplied (1x1280 and 768x3072)`

I get the same error with and without the SD3 apply node ( with the vae input )

**Comment by JorgeR81** [comment]
No, it's working ! ( I had a wrong setting )
