### ISSUE TITLE
::: | Pytorch Update 2.3.1 | Popup error while loading ComfyUI

### ISSUE THREAD

**Issue by kakachiex2** [comfyanonymous/ComfyUI#4785]
### Expected Behavior

Load smoothly

### Actual Behavior

I get this errors after update to Pytorch 2.3.1 ::
conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=12.1 -c pytorch -c nvidia

"" the procedure entry point
element size@tensoriteratorbase@at@QEBA_JH@Z
could not be locate in the dynamic link library
k:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\lib\site-packages\xformers\_C.pyd. ""

![Screenshot 2024-09-04 130615](https://github.com/user-attachments/assets/56e6f7b4-ad63-435b-b7ce-eaaaa8efb0f0)

### Steps to Reproduce

Update to Pytorch 2.3.1

### Debug Logs

```powershell
None
```

**Comment by Brostopher** [comment]
The links provided were useful in resolving the pop-up issue and the sluggish ksampler, but I want to avoid sharing incorrect information.

https://github.com/facebookresearch/xformers/discussions/717 https://github.com/facebookresearch/xformers/actions/runs/10559887009

**Comment by mcmonkey4eva** [comment]
you should probably not install xformers at all, but if you do, you need to update it when you update torch
