### ISSUE TITLE
After updating to v0.2.1 my custom node fails to load

### ISSUE THREAD

**Issue by acorderob** [comfyanonymous/ComfyUI#4788]
### Your question

My own node (https://github.com/acorderob/sd-webui-prompt-postprocessor) fails after updating.

Logs don't show any related error, even in verbose mode, and it even says that the custom node was imported (when it shows the import times). I even made sure that the class is initialized. But after that in the interface it shows a popup error and the node does not load and is not available anywhere (not search nor manager).

![image](https://github.com/user-attachments/assets/0d3674ed-88f6-4060-8541-543077b622a2)

Reverting to previous commits, i found out the culprit at bfc214f434e9c92d05d755857c597733a7fd3b91 which is weird because it is a frontend change. Reverting to the commit before that makes it work again.

Hoping @huchenlei can find the reason and fix it or tell me what should i change in the extension to make it work.

**Comment by acorderob** [comment]
I managed to make it work up to date but with the old frontend launching with the argument:

--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest

I will try to find out which specific version of the frontend has the problem and open an issue in that repository.

**Comment by acorderob** [comment]
Never mind. It was a validation error due to an improperly defined property in my node (a required INT that had a default of None, instead of putting it as optional).

**Comment by darkpixel** [comment]
I have the same issue with a bunch of custom nodes I created here: https://github.com/darkpixel/darkprompts
The version I have on my machine hasn't been pushed yet because I'm in the middle of adding a bunch of features...but I'm getting zero errors in the console when starting ComfyUI.  It appears like everything loads without a problem, but in the front end half of my nodes work and half don't.
Looking at the javascript console I see messages like:
```
Skipping invalid node definition: DarkPrompt. See debug log for more information.
```
What debug log?  There are no errors in the console...

**Comment by darkpixel** [comment]
Found it.  Apparently you need to adjust the log levels in the Chrome console here:

![Screenshot from 2024-09-07 10-03-45](https://github.com/user-attachments/assets/bd97e3d6-88e0-417b-a848-401f657014ae)

...and apparently ComfyUI no longer allows defaults of ```None```.

**Comment by darkpixel** [comment]
Apparently the front end doesn't "morph" types in the same way Python does.
If you have a data type of Boolean in python, 0 and 1 are valid default values:
```
>>> bool(1)
True
>>> bool(0)
False
>>> 
```
...but not in the front end.  It expects ```True``` or ```False``` or your node gets silently dumped.
Same with floats.  A string of 1.25 is a valid float:
```
>>> float("1.25")
1.25
>>> 
```
...but not in the front end.  Your float default must be ```1.25``` and NOT ```"1.25"```.
