### ISSUE TITLE
Updated frontend, no ComfyUI manager button, not load/unload model buttons on menu bar

### ISSUE THREAD

**Issue by RikkB** [comfyanonymous/ComfyUI#4790]
### Expected Behavior

After front end update (v1.2.40) and switching to beta menu system, expected Manager button, model load & unload buttons.
![Screenshot 2024-09-04 193247](https://github.com/user-attachments/assets/72155a43-250e-493a-8064-14d300823426)

### Actual Behavior

ComfyUI Manager button, model load button & model unload button missing.  Win 11, Chrome browser, updated
![Screenshot 2024-09-04 193226](https://github.com/user-attachments/assets/73f9bf62-17b4-42f9-905a-f2e13797d5d8)

### Steps to Reproduce

Restarted comfy, refreshed browser, enabled/disabled beta menu, Manager button never appears on menu bar.  Switching back to old menu system, Manager button reappears.

### Debug Logs

```powershell
nothing logged
```

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-Manager. 
Also, press F12 in Chrome to open the dev tools, then refresh and capture the content output in the browser console. Please attach the screenshot.
