### ISSUE TITLE
Output model type on the [ Load Diffusion Model ] node

### ISSUE THREAD

**Issue by JorgeR81** [comfyanonymous/ComfyUI#4794]
### Feature Idea

Add a model type output to the `Load Diffusion Model` node.
The model type could then be connectected to the `Dual Clip Loader` node.

### Existing Solutions

Set the type option manually, in the `Dual Clip Loader`.

### Other

I'm sure this would be useful in other scenarios. 
So a type output for the `Load Checkpoint` node could also be useful. 

And if you don't want to make the current nodes more complicated, you could just create "advanced" versions.

**Comment by ltdrdata** [comment]
Strictly speaking, the diffusion model and CLIP are completely separate.
It's possible to not use the model at all, load the CLIP with `DualClipLoader` for text encoding, then unload the CLIP and separately utilize only the generated conditioning

**Comment by JorgeR81** [comment]
So, you mean that this is not a practical solution ?

Because we could have a scenario where the CLIP encoder is loaded before the UNET model, and then the "model type" would not be available ?

**Comment by ltdrdata** [comment]
They are just completely independent. The model loader cannot represent the functionality of the clip loader.
