### ISSUE TITLE
"The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1" when using ImageCompositeMasked

### ISSUE THREAD

**Issue by BenDes21** [comfyanonymous/ComfyUI#4796]
### Your question

Hi there, getting **The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1**  when using the node  ImageCompositeMasked, this node receive as input 1 mask anc 2 images of the same size.

<img width="565" alt="Untitled" src="https://github.com/user-attachments/assets/b971a375-978f-4691-b875-ce2391166d84">

**Comment by piaolingxue** [comment]
+1

**Comment by ltdrdata** [comment]
This issue should be moved to ComfyUI_LayerStyle repo.
https://github.com/chflame163/ComfyUI_LayerStyle/issues

**Comment by Hasasasa** [comment]
Has it been resolved？

**Comment by mgroeninger** [comment]
I believe this is caused by the difference between an RGB image and an RGBA image. An RGB image will be of size 3, while an RGBA image will be of size 4.  You can test this with the "Show Tensor Shape" node in the Easy-Use custom nodes (https://github.com/yolain/ComfyUI-Easy-Use) or you can try to use the "Image Remove Alpha" node, for example, in the Essential custom nodes (https://github.com/cubiq/ComfyUI_essentials).

**Comment by bru-ber** [comment]
> I believe this is caused by the difference between an RGB image and an RGBA image. An RGB image will be of size 3, while an RGBA image will be of size 4. You can test this with the "Show Tensor Shape" node in the Easy-Use custom nodes (https://github.com/yolain/ComfyUI-Easy-Use) or you can try to use the "Image Remove Alpha" node, for example, in the Essential custom nodes (https://github.com/cubiq/ComfyUI_essentials).

Thank you very much, this did the trick (removing the alpha)! I think this problem occurs for people that try to mix masquerade nodes and CropAndStitch nodes.

**Comment by YYYUIOPLK** [comment]
我遇到了同样的问题，我已经解决了他，问题是由于输入目标图像和参考图像的通道不同导致的，在连接他们之前可以加入节点：Masquerade Nodes的改变通道节点，将输入的通道统一为RGB即可
![Snipaste_2024-11-23_22-09-44](https://github.com/user-attachments/assets/3dc285d3-7780-4bba-b85f-56c76ec3b626)

**Comment by tsnky** [comment]
> I believe this is caused by the difference between an RGB image and an RGBA image. An RGB image will be of size 3, while an RGBA image will be of size 4. You can test this with the "Show Tensor Shape" node in the Easy-Use custom nodes (https://github.com/yolain/ComfyUI-Easy-Use) or you can try to use the "Image Remove Alpha" node, for example, in the Essential custom nodes (https://github.com/cubiq/ComfyUI_essentials).

this is the best answer, put "Image Remove Alpha" node after "removebg node" then connect it to "ImagecompostiteMasked"

**Comment by Sevinc-Lab** [comment]
![image](https://github.com/user-attachments/assets/4bc0eff0-f9ea-4d1f-93c9-e9855f2c690f)
Thank You!
