### ISSUE TITLE
how to use instantx controlnet union in comfyui

### ISSUE THREAD

**Issue by akk-123** [comfyanonymous/ComfyUI#4804]
how to use [controlnet-union](https://huggingface.co/Shakker-Labs/FLUX.1-dev-ControlNet-Union-Pro) in comfyui, this model need a params control mode

**Comment by JorgeR81** [comment]
I think the old node ( for SDXL ) still works, but the option names were not updated for Flux.

I've opened an issue for this: https://github.com/comfyanonymous/ComfyUI/issues/4823
