### ISSUE TITLE
ComfyUI Crazy slow

### ISSUE THREAD

**Issue by MaxaAI** [comfyanonymous/ComfyUI#4810]
### Expected Behavior

Creating an image in 2-3 minutes with flux

### Actual Behavior

it takes hours for an image
![LongLoading](https://github.com/user-attachments/assets/65c0f885-154f-406e-9035-11046bffb08c)

### Steps to Reproduce

To Reproduce
[WorkflowForTesting.json](https://github.com/user-attachments/files/16909083/WorkflowForTesting.json)

just run the workflow

### Debug Logs

```powershell
in the terminal is nothing standing because it is "running"
```

### Other

Before that error happened i took all the models and put them into a safe folder so i can load them in after i have deleted comfy and reinstalled it because a custom_node fucked it up before. But since then generating is crazy slow and thats really weird because it took the last weeks only 2-3 minutes per image

**Comment by ltdrdata** [comment]
What is your hardware spec and software environment?

**Comment by MaxaAI** [comment]
> What is your hardware spec and software environment?

im using an rtx 3070 with 8gb of vram and 64gb of ram

**Comment by ltdrdata** [comment]
Try with `--disable-smart-memory` option.

**Comment by MaxaAI** [comment]
how can i do it?

**Comment by ltdrdata** [comment]
> how can i do it?

Nevermind. I have reproduced that issue.

**Comment by ltdrdata** [comment]
Oh wow... the resolution is too big.

**Comment by MaxaAI** [comment]
oh i will try make that to 1 again

**Comment by MaxaAI** [comment]
Yeah now its working properly again thank you very much
