### ISSUE TITLE
The ksampler cannot display a preview during execution.

### ISSUE THREAD

**Issue by Willy-Shenn** [comfyanonymous/ComfyUI#4811]
### Your question

Hi, after updating ComfyUI, I noticed that the ksampler, which used to allow real-time preview during sampling, no longer shows the preview in real-time. I have to wait until the ksampling is finished and decoded to see the preview. Can anyone assist me in resolving this issue? I would be very grateful.
![001](https://github.com/user-attachments/assets/f486b1f2-792a-45da-a586-76b7e144ad0f)

**Comment by marhensa** [comment]
@Willy-Shenn I have this same problem, how do you fix this? 

You make this issue as completed without any explanation.

**Comment by Willy-Shenn** [comment]
> @Willy-Shenn I have this same problem, how do you fix this?
> 
> You make this issue as completed without any explanation.

Navigate to ComfyUI Manager - Preview Method, and select the preview type.
![001](https://github.com/user-attachments/assets/b0b9c84b-4cb5-415b-9cce-cb8c2524d8f8)
