### ISSUE TITLE
Long flux model loading time before inference

### ISSUE THREAD

**Issue by deepfree2023** [comfyanonymous/ComfyUI#4812]
### Your question

As the execution goes to the samplerCustomAdvanced node, before the first inference step, there will be a long time loading the model to vram. 

I'm using Flux.d, the real inference time is about 75s, and the model loading time is about 20s.  No cpu usage increasement or disk accessing during model loading.

Why does model loading take so long time?

### Logs

```powershell
got prompt
loaded partially 9617.495919891357 9617.35546875 0
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [01:15<00:00,  3.76s/it]
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Prompt executed in 94.81 seconds
```

**Comment by wogam** [comment]
This should only be for the first time you load the model/apply a LoRA. For subsequent generations it should be faster. Do you experience the model loading time of 20s after the first image generation?

**Comment by deepfree2023** [comment]
yes, every time. The first time loading time was counted in load diffusion model and dual clip loader nodes, not related to the samplerCustomAdvanced node.

**Comment by ltdrdata** [comment]
This is typically a environment issue.
For questions like this, you first need to list your operating environment in detail to allow for a basic diagnosis.
Including precisely which model file it is.

**Comment by richardm1** [comment]
OP, what storage technology is this loading from?  Is it a network drive?  SATA SSD?  SATA HDD?
