### ISSUE TITLE
求助大佬

### ISSUE THREAD

**Issue by wosajhg** [comfyanonymous/ComfyUI#4813]
### Expected Behavior

![022f6bef4122fe41d67688f625e30d6](https://github.com/user-attachments/assets/5e81ade2-9995-4462-a530-c9563c07f8e7)
![e38bd82e57cc2c27d8a5ca491ce09a5](https://github.com/user-attachments/assets/0f41a339-8c63-4e6c-a699-464b291fbf50)
请问大佬们这是什么情况？改如何解决？

### Actual Behavior

![022f6bef4122fe41d67688f625e30d6](https://github.com/user-attachments/assets/5e81ade2-9995-4462-a530-c9563c07f8e7)
![e38bd82e57cc2c27d8a5ca491ce09a5](https://github.com/user-attachments/assets/0f41a339-8c63-4e6c-a699-464b291fbf50)
请问大佬们这是什么情况？改如何解决？

### Steps to Reproduce

![022f6bef4122fe41d67688f625e30d6](https://github.com/user-attachments/assets/5e81ade2-9995-4462-a530-c9563c07f8e7)
![e38bd82e57cc2c27d8a5ca491ce09a5](https://github.com/user-attachments/assets/0f41a339-8c63-4e6c-a699-464b291fbf50)
请问大佬们这是什么情况？改如何解决？

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** FaceDetailer
- **Exception Type:** AttributeError
- **Exception Message:** 'NoneType' object has no attribute 'shape'
## Stack Trace

  File "D:\Ai\ComfyUI-aki-v1.3\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\Ai\ComfyUI-aki-v1.3\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\Ai\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\Ai\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
```

### Other

单独可以运行，加入INSTANTID后就卡再面部优化了。

**Comment by mcmonkey4eva** [comment]
this is an issue with those custom nodes, not core comfy
