### ISSUE TITLE
[Feature Request] Detection Detailer

### ISSUE THREAD

**Issue by DivinoAG** [comfyanonymous/ComfyUI#482]
Detection Detailer is a plugin that is available for the Automatic1111 WebUI.

https://github.com/dustysys/ddetailer

![Detection Detailer Masks](https://github.com/dustysys/ddetailer/raw/master/misc/ddetailer_example_1.png)

Is is possible to implement something similar to this for ComfyUI? It would be very helpful to procedurally improve character detail on images in a single workflow without the need to manually create masks. This would possibly only need to output a mask that could be used with existing nodes for img2img detail improvement, although a process for "inpainting a full resolution" would be ideal, which I'm not sure currently exists.

**Comment by scripterTW** [comment]
FYI, you can try this, it works.
https://github.com/ltdrdata/ComfyUI-Impact-Pack
