### ISSUE TITLE
求助大佬

### ISSUE THREAD

**Issue by wosajhg** [comfyanonymous/ComfyUI#4826]
### Expected Behavior

![ee750e4dad8dc6942dcbc7211285424](https://github.com/user-attachments/assets/d5a578a9-2868-44f0-b032-3b81aa57b39d)
![02f19952c139893a10d2cc9d3bc399f](https://github.com/user-attachments/assets/8850e2c9-dc10-4899-ac4e-10af7858f12f)
奇异矩阵是什么意思？我再使用换脸形的时候出现的问题，还望大佬赐教。

### Actual Behavior

![ee750e4dad8dc6942dcbc7211285424](https://github.com/user-attachments/assets/d5a578a9-2868-44f0-b032-3b81aa57b39d)
![02f19952c139893a10d2cc9d3bc399f](https://github.com/user-attachments/assets/8850e2c9-dc10-4899-ac4e-10af7858f12f)
奇异矩阵是什么意思？我再使用换脸形的时候出现的问题，还望大佬赐教。

### Steps to Reproduce

![ee750e4dad8dc6942dcbc7211285424](https://github.com/user-attachments/assets/d5a578a9-2868-44f0-b032-3b81aa57b39d)
![02f19952c139893a10d2cc9d3bc399f](https://github.com/user-attachments/assets/8850e2c9-dc10-4899-ac4e-10af7858f12f)
奇异矩阵是什么意思？我再使用换脸形的时候出现的问题，还望大佬赐教。

### Debug Logs

```powershell
![ee750e4dad8dc6942dcbc7211285424](https://github.com/user-attachments/assets/d5a578a9-2868-44f0-b032-3b81aa57b39d)
![02f19952c139893a10d2cc9d3bc399f](https://github.com/user-attachments/assets/8850e2c9-dc10-4899-ac4e-10af7858f12f)
奇异矩阵是什么意思？我再使用换脸形的时候出现的问题，还望大佬赐教。
```

**Comment by mcmonkey4eva** [comment]
this looks to be an issue with 'faceshaper' custom nodes?
