### ISSUE TITLE
UNETLoader Error

### ISSUE THREAD

**Issue by SamuelViol** [comfyanonymous/ComfyUI#4828]
### Expected Behavior

The UI is not running

### Actual Behavior

![Screenshot 2024-09-07 113611](https://github.com/user-attachments/assets/ced1a9bf-ab2a-4ddd-bb5a-53d7cc77e773)
I get this error every time

### Steps to Reproduce

![Screenshot 2024-09-07 113723](https://github.com/user-attachments/assets/bc2ddcb9-8cbb-4130-b9f6-13a7843da127)
I'm using a default configuration and installation metod for flux

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** UNETLoader
- **Exception Type:** RuntimeError
- **Exception Message:** Error(s) in loading state_dict for Flux:
	size mismatch for img_in.weight: copying a param with shape torch.Size([98304, 1]) from checkpoint, the shape in current model is torch.Size([3072, 64]).
	size mismatch for time_in.in_layer.weight: copying a param with shape torch.Size([393216, 1]) from checkpoint, the shape in current model is torch.Size([3072, 256]).
	size mismatch for time_in.out_layer.weight: copying a param with shape torch.Size([4718592, 1]) from checkpoint, the shape in current model is torch.Size([3072, 3072]).
	size mismatch for vector_in.in_layer.weight: copying a param with shape torch.Size([1179648, 1]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
	size mismatch for vector_in.out_layer.weight: copying a param with shape torch.Size([4718592, 1]) from checkpoint, the shape in current model is torch.Size([3072, 3072]).


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

### Other

tanks for the help

**Comment by JorgeR81** [comment]
In Comfy UI, the NF4 format requires a custom node, but it may be deprecated in favor of the GGUF models. 
https://github.com/comfyanonymous/ComfyUI_bitsandbytes_NF4

So it only supports the NF4 format in checkpoint version ( not the UNET version ).
https://github.com/comfyanonymous/ComfyUI_bitsandbytes_NF4/issues/44

And it was not updated for NF4 v2, so it's much slower with that.
https://github.com/comfyanonymous/ComfyUI_bitsandbytes_NF4/issues/35
