### ISSUE TITLE
Search Missing?

### ISSUE THREAD

**Issue by Orenji-Tangerine** [comfyanonymous/ComfyUI#4829]
### Your question

I used to be able to see the search input when I drag a node to a new node, but now it is nowhere to be seen and I try to look at option but I cant seem to find it. Your help is much appreciated.

![image](https://github.com/user-attachments/assets/24144006-2562-40db-994c-60c05e6d0dd3)

**Comment by Orenji-Tangerine** [comment]
![image](https://github.com/user-attachments/assets/83ec5ae3-2edd-4f06-9ee0-bfb75304f7e3)

**Comment by ThimoDEV** [comment]
I have the same issue, the aboe settings don't seem to repair it

**Comment by nux1111** [comment]
So I had the same problem but fixed it after disabling 'Easy Use node'

**Comment by ThimoDEV** [comment]
> So I had the same problem but fixed it after disabling 'Easy Use node'

Where can I find this setting?

**Comment by ThimoDEV** [comment]
I found the issue for me. If you hold shift you get the search box. 
![image](https://github.com/user-attachments/assets/98d6c2f3-f414-4224-8107-bf685e765b26)

You can change this behaviour by setting Action on link release (no modifier) to search box

**Comment by ltdrdata** [comment]
This issue should be handled in easy use:
https://github.com/yolain/ComfyUI-Easy-Use/issues
