### ISSUE TITLE
OneTrainer loras trained with clip l and t5 keys are not loaded 

### ISSUE THREAD

**Issue by DarkViewAI** [comfyanonymous/ComfyUI#4837]
### Feature Idea

Ability to use them 
<img width="936" alt="xz" src="https://github.com/user-attachments/assets/901edd36-d630-473f-a78e-0efca727088c">

added the loras here

https://huggingface.co/Maxivi/sda/tree/main

**Comment by DarkViewAI** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1727#issuecomment-2336601675

forge has fixed it

**Comment by comfyanonymous** [comment]
I wouldn't call that "fixed" lol here's an actual fix: https://github.com/comfyanonymous/ComfyUI/commit/32a60a7bacc9f623099ef41dcc1b4a7a2d22f23d

**Comment by DarkViewAI** [comment]
f

> I wouldn't call that "fixed" lol here's an actual fix: [32a60a7](https://github.com/comfyanonymous/ComfyUI/commit/32a60a7bacc9f623099ef41dcc1b4a7a2d22f23d)

lol forge is now broken with kohya loras hehehe
