### ISSUE TITLE
Torch not being compiled with CUDA enabled

### ISSUE THREAD

**Issue by Vektor369** [comfyanonymous/ComfyUI#4845]
### Expected Behavior

ComfyUI to start

### Actual Behavior

Errors-out with something about Torch not being compiled with CUDA enabled

### Steps to Reproduce

I literally just restarted ComfyUI.

### Debug Logs

```powershell
F:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-08 13:53:24.538612
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: F:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\AI\ComfyUI_windows_portable\ComfyUI
** Log path: F:\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   1.7 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\main.py", line 90, in <module>
    import execution
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 143, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 112, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 878, in current_device
    _lazy_init()
  File "F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 305, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

F:\AI\ComfyUI_windows_portable>pause
Press any key to continue . . .
```

### Other

It was running fine. I restarted, and I could see it doing a bunch of stuff in the terminal. Now, it just does this.

**Comment by TripStan79** [comment]
same issue after updating

**Comment by Vektor369** [comment]
Since my last post 'mysteriously' disappeared...

These are not solutions:
> You need to reinstall torch. Use this command.
> 
> [#3663 (comment)](https://github.com/comfyanonymous/ComfyUI/issues/3663#issuecomment-2303313684)

> > #2427
> > havent solved it yet
> 
> You need to reinstall torch.

Reinstalling torch kills xFormers, and introduces several other errors.

Running:
```
.\python_embeded\python.exe -m pip install --upgrade torch==2.3.0+cu121 torchvision==0.18.0+cu121 torchaudio==2.3.0+cu121 --index-url https://download.pytorch.org/whl/cu121
```
produces the following:
```
  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'F:\AI\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.27.post2 requires torch==2.4.0, but you have torch 2.3.0+cu121 which is incompatible.
```

Now, running ComfyUI, I get the following pop-up:
```
python.exe - Entry Point Not Found
The procedure entry point ?parseSchema@jit@torch@@YA?AUfunctionSchema@c10@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z could not be located in the dynamic link library F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\_C.pyd.
```
along with the following in the console:
```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.3.0+cu121)
    Python  3.11.9 (you have 3.11.9)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
xformers version: 0.0.27.post2
Could not find efficiency nodes
UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
ModuleNotFoundError: No module named 'loguru'
ModuleNotFoundError: No module named 'gguf'
ModuleNotFoundError: No module named 'bitsandbytes'
[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.
```

I'd reinstall from scratch, but aside from being a major pita, there are still no ideas about what caused this in the first place, (aside from ComfyUI updating,) so it seems like it would just happen all over again.

Any help would be greatly appreciated. Thanks in advance.

**Comment by MDMAchine** [comment]
You could try to **uninstall** then reinstall 0.27 / 2.3.1 in this order.

# Xformers:
python -m pip uninstall xformers
python -m pip install xformers==0.0.27

# PyTorch:
python -m pip uninstall torch
python -m pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --extra-index-url https://download.pytorch.org/whl/cu121

**Comment by MattMosquito** [comment]
> python -m pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --extra-index-url https://download.pytorch.org/whl/cu121

Perfect! Worked for me, thanks.

**Comment by Vektor369** [comment]
> You could try to **uninstall** then reinstall 0.27 / 2.3.1 in this order.
> 
> # Xformers:
> python -m pip uninstall xformers python -m pip install xformers==0.0.27
> 
> # PyTorch:
> python -m pip uninstall torch python -m pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --extra-index-url https://download.pytorch.org/whl/cu121

Unfortunately, it didn't work for me. Xformers installed, but with the following errors:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
audiolm-pytorch 2.0.7 requires accelerate>=0.24.0, but you have accelerate 0.20.3 which is incompatible.
fairseq 0.12.4 requires hydra-core<1.1,>=1.0.7, but you have hydra-core 1.3.2 which is incompatible.
fairseq 0.12.4 requires omegaconf<2.1, but you have omegaconf 2.3.0 which is incompatible.
torchaudio 2.3.0 requires torch==2.3.0, but you have torch 2.3.1 which is incompatible.
torchvision 0.18.0+cu121 requires torch==2.3.0+cu121, but you have torch 2.3.1 which is incompatible.
```
Then torch installed with the following errors:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
audiolm-pytorch 2.0.7 requires accelerate>=0.24.0, but you have accelerate 0.20.3 which is incompatible.
fairseq 0.12.4 requires hydra-core<1.1,>=1.0.7, but you have hydra-core 1.3.2 which is incompatible.
fairseq 0.12.4 requires omegaconf<2.1, but you have omegaconf 2.3.0 which is incompatible.
```
And everything's the same. I still get the Entry Point Not Found pop-up when I start ComfyUI, then all the same errors in the console, and trying to run a workflow results in the same massive amount of errors due to "xFormers not being built with CUDA support".

I'm just going to reinstall from scratch, and hope for the best. I feel like I'm just wasting time chasing down something when I have no idea what it is because I have no idea what ComfyUI did when it updated.

Never ceases to amaze (read: appal) me how you can get all set up, get all of your models and nodes downloaded, and be queueing and working your workflows...
...then restart, and spend the rest of your day troubleshooting, and have to start over from scratch.

Is there a way to _prevent_ ComfyUI from automatically updating? That would be an **excellent** feature.

**Comment by Vektor369** [comment]
I think I pissed it off, because I deleted everything, pulled it, but now whenever I run it, it immediately freezes. This is as far as it gets:
```
Microsoft Windows [Version 10.0.19045.4780]
(c) Microsoft Corporation. All rights reserved.

F:\AI\ComfyUI>python main.py
Total VRAM 8192 MB, total RAM 32648 MB
pytorch version: 2.3.1+cu121
```

**Comment by altoiddealer** [comment]
I could not successfully get Comfy working on my secondary computer (duplicate of my primary computer), on a fresh install.  It kept resulting with "Torch not compiled with CUDA enabled", I kept uninstalling and reinstalling torch per the instructions to no avail.

> python -m pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --extra-index-url https://download.pytorch.org/whl/cu121

This resolved the problem!

**Comment by ltdrdata** [comment]
Don't install xformers unless you are using tooncraft.

**Comment by MickeyJ** [comment]
> You could try to **uninstall** then reinstall 0.27 / 2.3.1 in this order.
> 
> # Xformers:
> python -m pip uninstall xformers python -m pip install xformers==0.0.27
> 
> # PyTorch:
> python -m pip uninstall torch python -m pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --extra-index-url https://download.pytorch.org/whl/cu121

Yes! Thank you.

**Comment by shalva97** [comment]
> PyTorch:
> python -m pip uninstall torch
> python -m pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --extra-index-url https://download.pytorch.org/whl/cu121

After running the above command I get the following error

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchmetrics 1.5.0 requires numpy<2.0,>1.20.0, but you have numpy 2.2.2 which is incompatible.
```

**Comment by shalva97** [comment]
only things that worked for me was to redownload portable version and copy&paste modules and workflows.

**Comment by Vektor369** [comment]
I grew _excruciatingly_ exhausted of Comfy breaking every time I wanted to try anything new. I was spending vastly more time troubleshooting Comfy than I was actually using it. So, I recently took a different tact: I put all my models etc. in a single folder, and I copy a fresh portable version of Comfy for each workflow. Tedious, yes. My hard-drive is hemorrhaging, yes. But you know what? It works. **Everything** works now. **Every** time. And I never ever have to be worried about it suddenly not working ever again.
#peaceofmind

**Comment by admiralnelson** [comment]
^trvthnvke

**Comment by mostafa5tommy** [comment]
> I could not successfully get Comfy working on my secondary computer (duplicate of my primary computer), on a fresh install. It kept resulting with "Torch not compiled with CUDA enabled", I kept uninstalling and reinstalling torch per the instructions to no avail.
> 
> > python -m pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --extra-index-url https://download.pytorch.org/whl/cu121
> 
> This resolved the problem!

This totally fix it for me ❤

**Comment by tommywright** [comment]
> I grew _excruciatingly_ exhausted of Comfy breaking every time I wanted to try anything new. I was spending vastly more time troubleshooting Comfy than I was actually using it. So, I recently took a different tact: I put all my models etc. in a single folder, and I copy a fresh portable version of Comfy for each workflow. Tedious, yes. My hard-drive is hemorrhaging, yes. But you know what? It works. **Everything** works now. **Every** time. And I never ever have to be worried about it suddenly not working ever again. #peaceofmind

I do the same but I have a separate folder for my Models and make a link inside each new ComfyUI so when I look for a model, they are all pointing to the same set of folders.

I still can't get ComfyUI to work ever since upgrading to a 5090 yesterday. :(  I've tried everything and still get the AssertionError: Torch not compiled with CUDA enabled. I'll keep trying stuff.

**Comment by Vektor369** [comment]
> > I grew _excruciatingly_ exhausted of Comfy breaking every time I wanted to try anything new. I was spending vastly more time troubleshooting Comfy than I was actually using it. So, I recently took a different tact: I put all my models etc. in a single folder, and I copy a fresh portable version of Comfy for each workflow. Tedious, yes. My hard-drive is hemorrhaging, yes. But you know what? It works. **Everything** works now. **Every** time. And I never ever have to be worried about it suddenly not working ever again. #peaceofmind
> 
> I do the same but I have a separate folder for my Models and make a link inside each new ComfyUI so when I look for a model, they are all pointing to the same set of folders.
> 
> I still can't get ComfyUI to work ever since upgrading to a 5090 yesterday. :( I've tried everything and still get the AssertionError: Torch not compiled with CUDA enabled. I'll keep trying stuff.

Oh, that's what I meant. A separate folder for Models, and I use the same extra_model_paths.yaml in each instance of ComfyUI to point to it.

That Torch not compiled with CUDA drove me half mad. Fortunately, (for you in this case,) I started keeping records of all the errors I run into because some of them would keep coming up, and there was just no way for me to remember the fixes for them all.

So, here's what I have in my notes on that one:
uninstall with:
```pip uninstall torch```
and reinstall with:
```pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124```
Now, there might be different ones that have something different than "cu124" at the end, but that's what worked for me.

Also, being on a 5090, there's a lot of stuff that just isn't going to work with it yet. There's going to be a gap til everything 'catches up' with it, so-to-speak. So, ymmv, but good luck!

**Comment by tommywright** [comment]
Awesome! I got it working now on the latest release of ComfyUI! All my old ones are broken though.. of course. :( My favorite way to use it is with Krita's AI plugin so I'm going to try and tackle that next.

**Comment by geekonweb** [comment]
I the error was gone when installed  2.3.1  

and for a higher CUDA version  v21.1  below worked   .. thanks to Gemini

python -m pip install --no-cache-dir torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 --extra-index-url https://download.pytorch.org/whl/cu128

**Comment by darioDesignCOMFYui** [comment]
Hi, I think I just arrived at the same issue and tried solving it with what was guided here, but i still cant get my ComfyUI to work. It was working fine up to this day until i decided to update it via MANAGER in the UI.

Here is the Log im getting, i dont know if anyone here could help, would appreciate it a lot, or maybe just redownload and restart new, but hoping there is a fix for this:


A:\COMFY\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-09-15 16:18:54.151
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: A:\COMFY\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: A:\COMFY\ComfyUI_windows_portable\ComfyUI
** ComfyUI Base Folder Path: A:\COMFY\ComfyUI_windows_portable\ComfyUI
** User directory: A:\COMFY\ComfyUI_windows_portable\ComfyUI\user
** ComfyUI-Manager config path: A:\COMFY\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: A:\COMFY\ComfyUI_windows_portable\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: A:\COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   6.7 seconds: A:\COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
Traceback (most recent call last):
  File "A:\COMFY\ComfyUI_windows_portable\ComfyUI\main.py", line 147, in <module>
    import execution
  File "A:\COMFY\ComfyUI_windows_portable\ComfyUI\execution.py", line 15, in <module>
    import comfy.model_management
  File "A:\COMFY\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 237, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "A:\COMFY\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 187, in get_torch_device
    return torch.device(torch.cuda.current_device())

**Comment by sajadi2001-max** [comment]
I had this problem too. My problem was solved by opening this file from comfuyi itself. This file is for troubleshooting, as I searched for it and it worked for me. 

open this file :
ComfyUI_windows_portable\update\update_comfyui_and_python_dependencies.bat 


Then it will tell you to press any key to continue. Press the key and it will start troubleshooting and downloading incomplete files.

**Comment by alexwyattdev** [comment]
For me using the ComfyUI_windows_portable\update\update_comfyui_and_python_dependencies.bat - is the reason I started having this problem

**Comment by builder-main** [comment]
> For me using the ComfyUI_windows_portable\update\update_comfyui_and_python_dependencies.bat - is the reason I started having this problem

Same for me. Shouldn't a version be specified for torch packages in the requirement file in order to avoid upgrading to a default latest release ?
