### ISSUE TITLE
UI Collision with mape helper

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [comfyanonymous/ComfyUI#4847]
### Expected Behavior

I expect ComfyUI to play nice with UI's created by extensions.

If ComfyUI can't know about extensions, we need a way to layer sidebars/top bars in a way where they know about each other and stack nicely without overlapping.

As an alternative solution, pressing [ESC] should perhaps close down one panel at a time, to allow for keyboard navigation of overlapping panels.

Another alternative solution is that when you select an UI element, it gets a higher drawing order / priority, so it's displayed on top.

### Actual Behavior

![image](https://github.com/user-attachments/assets/1c6e2c32-d993-4731-80f1-074b10a417ee)

![image](https://github.com/user-attachments/assets/63bcbfae-4142-420a-91a8-69cb4aa33497)

As we can see, we cannot access the hamburger menu because it's being rendered behind the mape helper extension. This is undesirable.

### Steps to Reproduce

Install https://github.com/mape/ComfyUI-mape-Helpers

### Debug Logs

```powershell
0.0 seconds: C:\AI\ComfyUI\custom_nodes\ComfyUI-mape-Helpers
```

### Other

Duplicate topic on the mape github: 
https://github.com/mape/ComfyUI-mape-Helpers/issues/41

**Comment by huchenlei** [comment]
Please file the issue in the custom nodes repo. https://github.com/mape/ComfyUI-mape-Helpers/issues. Thanks!
