### ISSUE TITLE
Save/Export Workflow dropdown arrow overlaps with the refresh-button

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [comfyanonymous/ComfyUI#4848]
### Expected Behavior

I expect to not have menus opened that I didn't intend to open.

### Actual Behavior

The little dropdown-arrow next to the SAVE-icon is too trigger happy. It pops up without clicking instantly, without any delay.

![image](https://github.com/user-attachments/assets/41bb80d0-9f84-4750-9c89-9ff5762ae314)

I very often use the "Refresh" icon, however, if I'm not accurate enough with my mouse cursor, I will fly over the little down arrow next to the save icon, and then I get a drop-down menu, which overlaps the refresh icon.

Please move the refresh-icon further away so they don't overlap.
Alternatively, add a 0.5-1 second delay to automatically opening the drop-down menu by just hovering. 
Alternatively, move the menu components away when the menu blocks them (but I think a moving UI is worse). So don't do this.

### Steps to Reproduce

Try to hit the refresh-button quickly with the mouse

### Debug Logs

```powershell
No debug logs needed for UI/UX advice.
```

**Comment by robinjhuang** [comment]
Can this be moved to the https://github.com/Comfy-Org/ComfyUI_frontend repo?

**Comment by MNeMoNiCuZ** [comment]
Yes, sorry, I didn't read the categories enough when I submitted. 
I can re-post if you want.
