### ISSUE TITLE
ComfyUI really needs to add XSRF-protection, or make it VERY clear to its users thats its insecure to run (even on `localhost`) 

### ISSUE THREAD

**Issue by vivax3794** [comfyanonymous/ComfyUI#4850]
### Feature Idea

Currently ComfyUI does not validation of the origins of requests, this allows a malicious website to execute arbitrary prompts. Which is in of it self a issue.  It gets worse when you consider a few popular custom nodes allow for ACE (Arbitrary-code-execution) via prompts (hell some packs even have warnings about this in the manager). A big issue here is that the manager allows you to (on default settings) install custom nodes, which sounds fine, but an attacker can force install vulnerable nodes without user consent. One option users can take is to ofc lower the security setting to block installing custom nodes entirely, but that doesnt help if they already have vulnerable nodes installed (for example the WAS nodes can lead to ACE).

Comfy needs to implement basic XRSF at minimum, (along with a api key style system from `/prompt` to still allow api use).

## Common misconceptions
* Yes a website can send requests to `localhost`
* No CORS doesnt protect you, it specifically stops websites from ***reading*** data, but comfy will still happily execute any post requests that come its way.

### Existing Solutions

* Two issues in a similar vein exist, #987 and #3461 , which both ask for password auth when running with `--listen`, which ofc I mean we should always have protections enabled as something running on `localhost` can still be targeted by malicious websites.
* There is a set of custom nodes that claim to solve this issue, but I haven't dug into their code to check if it is actually sufficient: https://github.com/liusida/ComfyUI-Login , but I ofc think this should be a core comfy feature.
* It is recommended often in chats to run comfyui in docker and/or a jail, which I 100% agree with, but is not something stated in the README (except a small mention in the TLS section). There is also nothing in the readme to suggest why this is something you should 100% do.

### Other

* https://en.wikipedia.org/wiki/Cross-site_request_forgery
* https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/CSRF_prevention
* https://en.wikipedia.org/wiki/Drive-by_download

and yes I know this will be a breaking change for users of the api, but its kinda a big security flaw.

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/3ab3516e46703376ebcb3d24a794e8405962398e

This should fix it.

**Comment by vivax3794** [comment]
I am not familiar enough with the web framework used, so I cant point out what is wrong with the above commit... it does detect the attempt... but it doesnt block it

![image](https://github.com/user-attachments/assets/42312ba4-a8f0-4427-95e1-f90220846470)

**Comment by vivax3794** [comment]
Again not familiar enough with the framework to say for certain, but you are calling the handler before checking the headers, I feel like moving the `await handler(request)` to after the header check should solve the issue
