### ISSUE TITLE
Process stagnant?

### ISSUE THREAD

**Issue by K-O-N-B** [comfyanonymous/ComfyUI#4864]
### Your question

um, after I update Comfyui last week, every time I click queue buttom, client window show "got prompt"
![image](https://github.com/user-attachments/assets/6fc02035-5b0e-4791-b5de-1dae988e08db)

and, the state bar show this
![image](https://github.com/user-attachments/assets/b588e992-6369-4255-ac0f-ad5bd0a15a27)

I have to wait 30s - 50s every time.  After this, the process will start. 
But this situation not happen last week.

btw,  seem only happen in large workflow.

### Logs

```powershell
got prompt
SELECTED: input6
Cee

1girl, solo, long_hair, breasts, looking_at_viewer, skirt, brown_hair, shirt, black_hair, brown_eyes, jewelry, full_body, white_shirt, earrings, parted_lips, shoes, shorts, sleeveless, day, indoors, black_footwear, high_heels, bracelet, from_side, lips, pillow, book, window, kneeling, sleeveless_shirt, bed, chair, black_shorts, sandals, tank_top, curtains, watch, wooden_floor, realistic, wristwatch, computer, hand_on_own_head, bedroom
SELECTED: input6
SELECTED: input1
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
Requested to load SDXL
Loading 1 new model
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
Requested to load SDXL
Loading 1 new model

```

**Comment by ltdrdata** [comment]
What is your ComfyUI version?

**Comment by K-O-N-B** [comment]
> What is your ComfyUI version?

c27ebeb，

upadte to 967867d today, still same.

**Comment by ltdrdata** [comment]
In that case, it seems that at least it's not an issue caused by the old execution model.

Now, the suspicion falls on custom nodes, but since it's described as a large workflow, it's quite a tricky issue because it's difficult to test by removing some custom nodes.

**Comment by K-O-N-B** [comment]
> In that case, it seems that at least it's not an issue caused by the old execution model.
> 
> Now, the suspicion falls on custom nodes, but since it's described as a large workflow, it's quite a tricky issue because it's difficult to test by removing some custom nodes.
> 
> The best approach here seems to be placing logs densely at various suspicious points to narrow down the range causing the problem.

Sad, seems like this is a hard problem for newbies to solve

**Comment by boundlessliving** [comment]
I have the same problem. So I started with the Default workflow, loaded an SDXL model, everything ran as expected. As soon as I added an IP Adapter, or a Control Net - or even just a Load Image node, that's when it starts getting hung up with "Got Prompt" and yes, a full minute sometimes before it starts doing anything, and this all just started a few days ago after an update.

**Comment by ltdrdata** [comment]
> I have the same problem. So I started with the Default workflow, loaded an SDXL model, everything ran as expected. As soon as I added an IP Adapter, or a Control Net - or even just a Load Image node, that's when it starts getting hung up with "Got Prompt" and yes, a full minute sometimes before it starts doing anything, and this all just started a few days ago after an update.

By the way, in the case of IPAdapter, loading insightface is an extremely time-consuming task.
It's perfectly normal for it to be slow during the workflow execution, not before the workflow starts.

**Comment by K-O-N-B** [comment]
> > I have the same problem. So I started with the Default workflow, loaded an SDXL model, everything ran as expected. As soon as I added an IP Adapter, or a Control Net - or even just a Load Image node, that's when it starts getting hung up with "Got Prompt" and yes, a full minute sometimes before it starts doing anything, and this all just started a few days ago after an update.
> 
> By the way, in the case of IPAdapter, loading insightface is an extremely time-consuming task. It's perfectly normal for it to be slow during the workflow execution, not before the workflow starts.

but the point is this problem not happening before upadte Comfyui 2weeks ago   :(

**Comment by ltdrdata** [comment]
> > > I have the same problem. So I started with the Default workflow, loaded an SDXL model, everything ran as expected. As soon as I added an IP Adapter, or a Control Net - or even just a Load Image node, that's when it starts getting hung up with "Got Prompt" and yes, a full minute sometimes before it starts doing anything, and this all just started a few days ago after an update.
> > 
> > By the way, in the case of IPAdapter, loading insightface is an extremely time-consuming task. It's perfectly normal for it to be slow during the workflow execution, not before the workflow starts.
> 
> but the point is this problem not happening before upadte Comfyui 2weeks ago   :(

Can you test which commit the phenomenon starts occurring from?

**Comment by nux1111** [comment]
@ltdrdata I also have this issue. It's not isolated to ipadapter or controlnet alone and the workflow doesn't have to be complex. there just seems to be a slight delay before generation.

**Comment by K-O-N-B** [comment]
I've update CUI today, seems problem has gone,  2-5 sec can start the process.

**Comment by boundlessliving** [comment]
Updating just now did not change anything for me. It's still trying to load all models, seemingly concurrently, whenever I hit Queue. But it seems to be worse with workflows with any "Load Image" nodes - at least for me.

**Comment by K-O-N-B** [comment]
LOL

It happen again when I update CUI from cf80d28 to ca08597.
I downdate to cf80d28, the speed go normal.
@ltdrdata

**Comment by K-O-N-B** [comment]
I've test again, 2 version of CUI
How long does it take from the time you press the queue button to actually start the process:
CF80d28：7 secs
B3ce8fb: 72 secs

**Comment by wisieeen** [comment]
In my case, solution was to update custom nodes and recreate workflow.
There may be some incompatibilities between different nodes and CUI versions I guess.

**Comment by K-O-N-B** [comment]
this problem seems fixed
