### ISSUE TITLE
LoadcheckpointSimple error, "Could not detect model type" if original 23 Gb Flux Dev is attempted to load with loadcheckpoint

### ISSUE THREAD

**Issue by cbresciano** [comfyanonymous/ComfyUI#4866]
### Your question

I´m trying to use Flux Dev.safetensors (the original on from Hugging Face, 23 Gb) and a message shows up, " Could not detect model type. recognize the model"

# ComfyUI Error Report
## Error Details
- **Node Type:** CheckpointLoaderSimple
- **Exception Type:** RuntimeError
- **Exception Message:** ERROR: Could not detect model type of: C:\Users\User\Desktop\StabilityMatrix-win-x64\Data\Models\StableDiffusion\Flux\flux_dev.safetensors
## Stack Trace
```
  File "C:\Users\User\Desktop\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\Users\User\Desktop\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\Users\User\Desktop\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\User\Desktop\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "C:\Users\User\Desktop\StabilityMatrix-win-x64\Data\Packages\ComfyUI\nodes.py", line 539, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))

  File "C:\Users\User\Desktop\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\sd.py", line 527, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))

```
## System Information
- **ComfyUI Version:** v0.2.2-17-gcd49553
- **Arguments:** C:\Users\User\Desktop\StabilityMatrix-win-x64\Data\Packages\ComfyUI\main.py --preview-method auto
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.2+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884246528
  - **VRAM Free:** 11793334272
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

**Comment by JorgeR81** [comment]
You need to use the [ Load Diffusion Model ] node ( for best quality set it to "default", to use in FP16 mode ).

You also need to load the Flux vae and text encoders, with other nodes. 

You can get the models and the example workflow here:
( I think this uses the [ SamplerCustom ] node, but you can also use the regular KSampler ).
https://comfyanonymous.github.io/ComfyUI_examples/flux/#regular-full-version

**Comment by ltdrdata** [comment]
That is not a checkpoint model. You have to use `Load Diffusion Model`.
