### ISSUE TITLE
CLIPTextEncode 'NoneType' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by fqfhqflkdsfsf12** [comfyanonymous/ComfyUI#4868]
### Your question

![za](https://github.com/user-attachments/assets/17d19c9b-bf1f-4d55-b331-afba6149b4e9)

I'm a beginner in comfy,
During installation, an error appears, such as a screenshot
What should I do?

**Comment by ltdrdata** [comment]
Selected checkpoint model is not a valid checkpoint model.

**Comment by boa1986** [comment]
一样的问题。为啥啊

**Comment by DarkDockDankDuckRice** [comment]
我也是这个问题，他们说是checkpoint模型和CLIP文本编码器冲突了，得换模型还是怎么搞嘞？

**Comment by clarkpo** [comment]
这个怎么解决

**Comment by jonathonbarton** [comment]
"Selected checkpoint model is not a valid checkpoint model."
That's not super helpful - what might be something else to check if you're 99% sure that the checkpoint in /models/checkpoints IS a valid checkpoint?

**Comment by ltdrdata** [comment]
> "Selected checkpoint model is not a valid checkpoint model." That's not super helpful - what might be something else to check if you're 99% sure that the checkpoint in /models/checkpoints IS a valid checkpoint?

The `tooncrafter` model should not be loaded through the `Load Checkpoint` node. 
It is a model that can only be used with its dedicated custom node.

**Comment by Fictiverse** [comment]
You need `Load Diffusion Model` Node instead

**Comment by nJpac6** [comment]
hi, I just figured it out! You need to add a triple clip in order to use it. I am totally new on this and please have a try (see the picture) to see if it works or not.
<img width="742" alt="Screenshot 2024-11-13 192516" src="https://github.com/user-attachments/assets/59274b08-d9f8-41af-88af-ef6eb7933d30">

**Comment by stumbras** [comment]
how do  you do that? where is mode templates?

**Comment by jinhai-ZJH** [comment]
换个checkpoint的模型因为你所选的模型和这个CLIP插件有冲突。
