### ISSUE TITLE
Comfy UI takes 50mins to generate an image for apple M1

### ISSUE THREAD

**Issue by GTP98** [comfyanonymous/ComfyUI#4872]
### Your question

Hi I installed comfyUI with pytorch 2.4.0 nightly and then tried with pytorch 2.3.1 but for both versions it took me almost an hour to generate an image. An error also occurs saying miniconda3/envs/comfyuienv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884.

Please help
<img width="1280" alt="Screenshot 2024-09-10 at 19 36 52" src="https://github.com/user-attachments/assets/a89c591a-e242-4f99-a634-f45a8640efe9">

**Comment by comfyanonymous** [comment]
8GB shared memory is only going to be enough to run SDXL if you have any other software running on your machine.
