### ISSUE TITLE
运行速度很慢，有很多警告

### ISSUE THREAD

**Issue by gitgit587** [comfyanonymous/ComfyUI#4873]
### Your question

工作流可以正常运行，但是速度极慢，日志里有很多警告，貌似关于\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead. 
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\__init__.py'

### Logs

```powershell
## 系统信息
-**ComfyUI 版本**：v0.2.2-22-g81778a7
- **参数**：ComfyUI\main.py --windows-standalone-build
-**操作系统：**nt
- **Python 版本**：3.11.6（tags/v3.11.6:8b6ee5b，2023 年 10 月 2 日，14:57:12）[MSC v.1935 64 位（AMD64）]
-**嵌入式 Python：** true
-**PyTorch 版本：**2.4.1+cu121
## 设备

-**名称**：cuda:0 NVIDIA GeForce GTX 1060 5GB：cudaMallocAsync
  -**类型：**cuda
  -**VRAM 总计：** 5368446976
  -**VRAM 可用：**1769172684
  -**Torch VRAM 总计：** 2617245696
  -**Torch VRAM 可用：**44474880
```

**Comment by huchenlei** [comment]
Try disable all custom nodes and reopen if the issue persists.
