### ISSUE TITLE
VAE Encode (For Inpaint)  'VAE' object has no attribute 'vae_dtype' 

### ISSUE THREAD

**Issue by FVolral** [comfyanonymous/ComfyUI#4875]
### Expected Behavior

VAEEncodeForInpaint should not Fail 

### Actual Behavior

VAEEncodeForInpaint does fail and this error message is displayed :
![image](https://github.com/user-attachments/assets/8b169e4b-0d05-4046-ab34-f4e4828fa166)

### Steps to Reproduce

Add a node "VAE Encode for Inpainting"
![image](https://github.com/user-attachments/assets/38f2fcd6-2368-463b-8d6a-abbb26b03b7b)

### Debug Logs

```powershell
I got this error

2024-09-10 18:46:41,889 - root - ERROR - Traceback (most recent call last):
  File "XXXX\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXXX\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXXX\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "XXXX\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXXX\ComfyUI_windows_portable\ComfyUI\nodes.py", line 363, in encode
    t = vae.encode(pixels)
        ^^^^^^^^^^^^^^^^^^
  File "XXXX\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 348, in encode
    memory_used = self.memory_used_encode(pixel_samples.shape, self.vae_dtype)
                                                               ^^^^^^^^^^^^^^
AttributeError: 'VAE' object has no attribute 'vae_dtype'
```

**Comment by FVolral** [comment]
Sorry I didn't saw the warning message here : 
WARNING - WARNING: No VAE weights detected, VAE not initalized.

**Comment by DevishMittal** [comment]
> Sorry I didn't saw the warning message here : WARNING - WARNING: No VAE weights detected, VAE not initalized.

hey how did you resolved this issue

**Comment by zhili007** [comment]
同样的问题 请问怎么解决的

**Comment by ltdrdata** [comment]
The `VAE Loader` should be used to load VAE Models, not to attempt loading checkpoint models.

**Comment by IL3DCR** [comment]
Hi, can you explain how to add the safetensors file as a VAE? I’m having trouble following the instructions because I can't download the image—my browser says it’s blocked or missing.

**Comment by LukeG89** [comment]
@IL3DCR To add only-VAE safetensors files, you need to place them inside `ComfyUI/models/vae` folder.
Then you can load them through `VAE Loader` node.

But if you mean "only a VAE from a Checkpoint", you need to load the entire model through `Load Checkpoint` and just connect the VAE. Or you can use `VAESave` node to extract the VAE from the Checkpoint, and then use `VAE Loader`.

**Comment by chinesewebman** [comment]
this error will triggered by using this checkpoint model : https://civitai.com/models/892280/metafilm-yuan-sd35lt-fp8-15-steps-asian-aesthetics-dpm2m?modelVersionId=998498 in ComfyUI while everything is OK using the same workflow with original SD3.5 checkpoint model

**Comment by RakibMohaimin726** [comment]
> Hi, can you explain how to add the safetensors file as a VAE? I’m having trouble following the instructions because I can't download the image—my browser says it’s blocked or missing.

Talk to ChatGPT, he can help you
