### ISSUE TITLE
LoraSave Node Usage

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#4879]
### Your question

![image](https://github.com/user-attachments/assets/75cbf1f3-c33e-478a-ae86-0c99eb4d66eb)

Any sample workflow ?

**Comment by deepfree2023** [comment]
Not only workflow, but also guidance. Such as how much vram is required or how to estimate that, what's the mean of the options, normally it takes how long to save one lora, etc.

**Comment by ltdrdata** [comment]
![lora-save](https://github.com/user-attachments/assets/0da0731d-8f6f-4b63-8812-104dc46ecfdb)

**Comment by pandayummy** [comment]
> ![lora-save](https://private-user-images.githubusercontent.com/128333288/375822041-0da0731d-8f6f-4b63-8812-104dc46ecfdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTAxNDEsIm5iZiI6MTcyODY4OTg0MSwicGF0aCI6Ii8xMjgzMzMyODgvMzc1ODIyMDQxLTBkYTA3MzFkLThmNmYtNGI2My04ODEyLTEwNGRjNDZlY2ZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQyMzM3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGIxMWIzMDk2OTMwYmJmZGI3NWZjZTIzYzE1MjJkMzMyYTg3MDhiMjg5NmFkYTE5YTA4YTQ4OTg3YTRmMmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g9JoCk4s-JYkhMSwi78QKmsbovmyZHcgEN6iuBqBKFk)

Thank you for your workflow.
But I don't understand what's the purpose of lorasave if we already have the separate lora file?
![image](https://github.com/user-attachments/assets/2f02a16a-2062-4d98-bafe-0ccc2f9b77c4)

I thought the lorasave node was to extract lora from community models/ finetuned models in cavitai.com

**Comment by ltdrdata** [comment]
> > ![lora-save](https://private-user-images.githubusercontent.com/128333288/375822041-0da0731d-8f6f-4b63-8812-104dc46ecfdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTAxNDEsIm5iZiI6MTcyODY4OTg0MSwicGF0aCI6Ii8xMjgzMzMyODgvMzc1ODIyMDQxLTBkYTA3MzFkLThmNmYtNGI2My04ODEyLTEwNGRjNDZlY2ZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQyMzM3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGIxMWIzMDk2OTMwYmJmZGI3NWZjZTIzYzE1MjJkMzMyYTg3MDhiMjg5NmFkYTE5YTA4YTQ4OTg3YTRmMmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g9JoCk4s-JYkhMSwi78QKmsbovmyZHcgEN6iuBqBKFk)
> 
> Thank you for your workflow. But I don't understand what's the purpose of lorasave if we already have the separate lora file? ![image](https://private-user-images.githubusercontent.com/32961592/375907203-2f02a16a-2062-4d98-bafe-0ccc2f9b77c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3ODk1NDcsIm5iZiI6MTcyODc4OTI0NywicGF0aCI6Ii8zMjk2MTU5Mi8zNzU5MDcyMDMtMmYwMmExNmEtMjA2Mi00ZDk4LWJhZmUtMGNjYzJmOWI3N2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDAzMTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxODk2MmEyNmM2NTk3NTEzZDIwZWRiZmRjMTU3NDdiN2NhMDI0MGEzYTNkZGFiZWYyYWE3YjljOWZlYWIyOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qUNHqpBQ174Z5ia_vQmeiT7yXOV1LYx3e4fb-60B4AQ)
> 
> I thought the lorasave node was to extract lora from community models/ finetuned models in cavitai.com

Multiple applied LoRAs can be bundled together and saved as a single LoRA.
Or you can save a LoRA that modifies the weights.
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/save-load-lbw.png

**Comment by pandayummy** [comment]
Thank you!
