### ISSUE TITLE
Remove default dimming on Preview Image

### ISSUE THREAD

**Issue by foxinni** [comfyanonymous/ComfyUI#4881]
### Your question

Is there a way to remove the default dimming that the image preview node does in the GRID view?

https://github.com/user-attachments/assets/a5ceafb3-7f72-4b4a-9643-0bd4c4ab27d1

**Comment by comfyanonymous** [comment]
Can you post your issue on the frontend repo: https://github.com/Comfy-Org/ComfyUI_frontend/issues
