### ISSUE TITLE
Why can't ComfyUI load SD3-Controlnet-Inpainting?

### ISSUE THREAD

**Issue by jakechai** [comfyanonymous/ComfyUI#4887]
### Your question

Error when loading SD3-Controlnet-Inpainting in ComfyUI (default Load ControlNet Model Node):

sd3 controlnet inpaint Error(s) in loading state_dict for ControlNet: size mismatch for pos_embed_input.proj.weight: copying a param with shape torch.Size([1536, 17, 2, 2]) from checkpoint, the shape in current model is torch.Size([1536, 16, 2, 2]).

diffusers: 0.30.2

![sd3 controlnet inpaint error](https://github.com/user-attachments/assets/682f1437-f314-4355-8a3e-f42f88c9ca1b)

### Logs

```powershell
[2024-09-11 22:53] got prompt
[2024-09-11 22:55] !!! Exception during processing !!! Error(s) in loading state_dict for ControlNet:
	size mismatch for pos_embed_input.proj.weight: copying a param with shape torch.Size([1536, 17, 2, 2]) from checkpoint, the shape in current model is torch.Size([1536, 16, 2, 2]).
[2024-09-11 22:55] Traceback (most recent call last):
  File "E:\Program Files\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Program Files\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable\ComfyUI\nodes.py", line 758, in load_controlnet
    controlnet = comfy.controlnet.load_controlnet(controlnet_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py", line 529, in load_controlnet
    return load_controlnet_mmdit(controlnet_data) #SD3 diffusers controlnet
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py", line 414, in load_controlnet_mmdit
    control_model = controlnet_load_state_dict(control_model, new_sd)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py", line 397, in controlnet_load_state_dict
    missing, unexpected = control_model.load_state_dict(sd, strict=False)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ControlNet:
	size mismatch for pos_embed_input.proj.weight: copying a param with shape torch.Size([1536, 17, 2, 2]) from checkpoint, the shape in current model is torch.Size([1536, 16, 2, 2]).
```

### Other

All other SD3 Controlnet models including Alimama's SD3-Controlnet-Softedge work fine.

**Comment by pandayummy** [comment]
[alimama](https://huggingface.co/alimama-creative) has not partnered with ComfyUI...

https://github.com/comfyanonymous/ComfyUI/issues/4888

**Comment by zhiselfly** [comment]
In new diffusers for official, I find a new parameter "extra_conditioning_channels" for SD3ControlNetModel.
That may be a new feature in SD3ControlNetModel which comfyUI not supported.
[official diffusers](https://github.com/huggingface/diffusers/blob/6cf8d98ce11867ebe6577d03508e3e06b37ade03/src/diffusers/models/controlnet_sd3.py#L58C9-L58C36)
<img width="826" alt="image" src="https://github.com/user-attachments/assets/be03616c-bff5-49a3-91f8-bfa8b84b9060">

**Comment by jakechai** [comment]
Great. Maybe it's the same issue for Alimama's SD3 and Flux's ControlNet Inpaint models.

**Comment by pandayummy** [comment]
[alimama](https://huggingface.co/alimama-creative) has SD3 and Flux controlnet inpainting models, but obviously they don't use ComfyUI, so their models can't run on ComfyUI. 

The community is hoping for xinsir's controlnet-union for SD3/Flux 
https://huggingface.co/xinsir/controlnet-union-sdxl-1.0

**Comment by jakechai** [comment]
Yeah, I like Xinsir.
But why Alimama's Alimama's SD3-Controlnet-Softedge works fine, Is it just a coincidence? I've created a discussion with them but no response.

**Comment by zhiselfly** [comment]
> Yeah, I like Xinsir. But why Alimama's Alimama's SD3-Controlnet-Softedge works fine, Is it just a coincidence? I've created a discussion with them but no response.

That's because the layers and inputs of SD3-controlnet-Softedge are of standard size, but the inpaint model is not. I also learned about extra_conditioning_channels by tracing the code of this model.

**Comment by zhiselfly** [comment]
@jakechai I wrote a demo that is compatible with the Alimama-SD3-ControlNet-Inpaint model. You can put it in custom_nodes to see it.
[https://github.com/zhiselfly/ComfyUI-Alimama-ControlNet-compatible](https://github.com/zhiselfly/ComfyUI-Alimama-ControlNet-compatible)

**Comment by pandayummy** [comment]
> @jakechai I wrote a demo that is compatible with the Alimama-SD3-ControlNet-Inpaint model. You can put it in custom_nodes to see it. https://github.com/zhiselfly/ComfyUI-Alimama-ControlNet-compatible Please use "Alimama SD3 Inpaint ControlNet Loader" to load the ControlNet model and "Alimama SD3 Inpaint ControlNet Apply Advanced" to apply the ControlNet. <img alt="image" width="1185" src="https://private-user-images.githubusercontent.com/12087946/367399358-1e6953b6-c35a-40ba-a960-afc55246e962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTM0MzMsIm5iZiI6MTcyNjI1MzEzMywicGF0aCI6Ii8xMjA4Nzk0Ni8zNjczOTkzNTgtMWU2OTUzYjYtYzM1YS00MGJhLWE5NjAtYWZjNTUyNDZlOTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE4NDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ODNmYWE1ZTFkZjE3ODlhOTZiNTZmZjE4OTQzOTk0MWZlOTBiMjc0MThiZWE1OTIwODAyOGJlNGJiMTQ0ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Mduk_nhlGpptl8coWqo6-QpZNY6BB57hxSuBbAeWKc">

Does it work with the Flux controlnet too?

**Comment by jakechai** [comment]
@zhiselfly I can’t wait to test it out.

**Comment by zhiselfly** [comment]
> > @jakechai I wrote a demo that is compatible with the Alimama-SD3-ControlNet-Inpaint model. You can put it in custom_nodes to see it. https://github.com/zhiselfly/ComfyUI-Alimama-ControlNet-compatible Please use "Alimama SD3 Inpaint ControlNet Loader" to load the ControlNet model and "Alimama SD3 Inpaint ControlNet Apply Advanced" to apply the ControlNet. <img alt="image" width="1185" src="https://private-user-images.githubusercontent.com/12087946/367399358-1e6953b6-c35a-40ba-a960-afc55246e962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTM0MzMsIm5iZiI6MTcyNjI1MzEzMywicGF0aCI6Ii8xMjA4Nzk0Ni8zNjczOTkzNTgtMWU2OTUzYjYtYzM1YS00MGJhLWE5NjAtYWZjNTUyNDZlOTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE4NDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ODNmYWE1ZTFkZjE3ODlhOTZiNTZmZjE4OTQzOTk0MWZlOTBiMjc0MThiZWE1OTIwODAyOGJlNGJiMTQ0ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Mduk_nhlGpptl8coWqo6-QpZNY6BB57hxSuBbAeWKc">
> 
> Does it work with the Flux controlnet too?

I don’t have a Flux model😂. I need to find some time to download and see how other libraries can be migrated into comfyUI.

**Comment by jakechai** [comment]
https://github.com/zhiselfly/ComfyUI-Alimama-ControlNet-compatible
It works for SD3. Great job! @zhiselfly

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/f48e390032f8d27a450a35ef4aa4b775b078cbf9
