### ISSUE TITLE
Support for  FLUX.1-dev-Controlnet-Inpainting ControlNet checkpoint

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#4888]
### Feature Idea

https://huggingface.co/alimama-creative/FLUX.1-dev-Controlnet-Inpainting-Alpha

![image](https://github.com/user-attachments/assets/45d49bb2-7ec6-4baa-965b-1aa1666b9f4d)

![image](https://github.com/user-attachments/assets/63b28e85-b375-4728-b02b-f805c3dc1205)

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/f48e390032f8d27a450a35ef4aa4b775b078cbf9

**Comment by kadirnar** [comment]
@comfyanonymous 

```bash
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_CUDA_cat)
```

Workflow:
<img width="1265" alt="image" src="https://github.com/user-attachments/assets/5e0a8691-d03f-4f89-9c5e-75b2ef275ff7">

**Comment by 31415pi** [comment]
same thing happened to me after installing Deforum custom node. 
I made a new pull dir, a new venv, and went from scratch.
Its popping on animatediff node for me now, even after fresh install.
Ryzen9 7950x
MSI 4070 Super OC
Gigabyte AORUS MOBO
4x16GB system memory 6000MHz
RUNLOG:
[username@systemname ~]$  cd AI-land/ComfyUI/
[username@systemname ComfyUI]$ source comfyvenv/bin/activate
(comfyvenv) [username@systemname ComfyUI]$ python main.py 
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-18 10:06:01.010791
** Platform: Linux
** Python version: 3.12.6 (main, Sep  8 2024, 13:18:56) [GCC 14.2.1 20240805]
** Python executable: /home/username/AI-land/ComfyUI/comfyvenv/bin/python
** ComfyUI Path: /home/username/AI-land/ComfyUI
** Log path: /home/username/AI-land/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.4 seconds: /home/username/AI-land/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 11904 MB, total RAM 63433 MB
pytorch version: 2.6.0.dev20240918+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /home/username/AI-land/ComfyUI/web
/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: 2702 [0bfc7cc9] | Released on '2024-09-18'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
loading image tools...

Import times for custom nodes:
   0.0 seconds: /home/username/AI-land/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/username/AI-land/ComfyUI/custom_nodes/image-resize-comfyui
   0.0 seconds: /home/username/AI-land/ComfyUI/custom_nodes/comfyui-animatediff
   0.0 seconds: /home/username/AI-land/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: /home/username/AI-land/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /home/username/AI-land/ComfyUI/custom_nodes/ComfyUI-Manager
   0.5 seconds: /home/username/AI-land/ComfyUI/custom_nodes/ComfyUI-Image-Tools

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: /home/username/AI-land/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
model weight dtype torch.float16, manual cast: None
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Requested to load SD1ClipModel
Loading 1 new model
loaded completely 0.0 235.84423828125 True
INFO: the IPAdapter reference image is not a square, CLIPImageProcessor will resize and crop it at the center. If the main focus of the picture is not in the middle the result might not be what you are expecting.
Requested to load CLIPVisionModelProjection
Loading 1 new model
loaded completely 0.0 1208.09814453125 True
Requested to load BaseModel
Loading 1 new model
loaded completely 0.0 1639.406135559082 True
100%|████████████████████████████████████████████████████████████████████████| 33/33 [00:20<00:00,  1.58it/s]
[AnimateDiff] - INFO - Loading motion module mm-Stabilized_mid.pth
FETCH DATA from: /home/username/AI-land/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
[AnimateDiff] - INFO - Converting motion module to fp16.
[AnimateDiff] - INFO - Injecting motion module with method default.
[AnimateDiff] - INFO - Hacking GroupNorm.forward function.
[AnimateDiff] - INFO - Injecting sliding context sampling function.
[AnimateDiff] - INFO - Video length: 20
[AnimateDiff] - INFO - Context length: 16
[AnimateDiff] - INFO - Context schedule: uniform
Requested to load BaseModel
Loading 1 new model
  0%|                                                                                 | 0/12 [00:00<?, ?it/s]
[AnimateDiff] - INFO - Restore GroupNorm.forward function.
[AnimateDiff] - INFO - Ejecting motion module with method default.
!!! Exception during processing !!! Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_group_norm)
Traceback (most recent call last):
  File "/home/username/AI-land/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/username/AI-land/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/sampler.py", line 277, in animatediff_sample
    return super().sample(
           ^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/nodes.py", line 1430, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/nodes.py", line 1397, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/sliding_context_sampling.py", line 78, in sample
    return orig_comfy_sample(model, *args, **kwargs, callback=callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/k_diffusion/sampling.py", line 855, in sample_heunpp2
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/sliding_context_sampling.py", line 408, in sampling_function
    cond, uncond = sliding_calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/sliding_context_sampling.py", line 387, in sliding_calc_cond_uncond_batch
    sub_cond_out, sub_uncond_out = calc_cond_uncond_batch(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/sliding_context_sampling.py", line 297, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 857, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/sampler.py", line 28, in forward_timestep_embed
    x = layer(x, context)
        ^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/motion_module.py", line 183, in forward
    return self.temporal_transformer(input_tensor, encoder_hidden_states, attention_mask)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/motion_module.py", line 244, in forward
    hidden_states = self.norm(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/sampler.py", line 42, in groupnorm_mm_forward
    input = group_norm(input, self.num_groups, self.weight, self.bias, self.eps)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/AI-land/ComfyUI/comfyvenv/lib/python3.12/site-packages/torch/nn/functional.py", line 2955, in group_norm
    return torch.group_norm(
           ^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_group_norm)

Prompt executed in 27.94 seconds

**Comment by kadirnar** [comment]
@comfyanonymous I am getting the same error. Can you check?

```bash
  File "/workspace/ComfyUI/comfy/controlnet.py", line 242, in get_control
    self.cond_hint = torch.cat([self.cond_hint] + to_concat, dim=1)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_CUDA_cat)
```
