### ISSUE TITLE
Queue List in new UI - Recommendation

### ISSUE THREAD

**Issue by ricperry** [comfyanonymous/ComfyUI#4889]
### Feature Idea

The updated Queue that combines the output preview seems pretty terrible:

![image](https://github.com/user-attachments/assets/07434d42-8f25-4dba-8d01-8824c45b4a9b)

 There are many clicks needed to clear queued jobs that I don't want to run, and it's difficult to distinguish which ones are queued up. IF we're going to keep the overall UI design of this queue, it would help to at least have a bit more information in the empty space, such as the timestamp or something. Even a hyperlinked workflow that opens in a different tab would be helpful. But actually, the old interface with the floating queue was MUCH better, and could be implemented as a dropdown menu from the existing queue button/menu: 
![image](https://github.com/user-attachments/assets/c1d6d52f-05d6-489b-b618-3992546ac495)

### Existing Solutions

Old floating menu had a nicer and easier to use queue/history list

**Comment by huchenlei** [comment]
You can still fall back to the legacy frontend following instruction here: https://github.com/comfyanonymous/ComfyUI#accessing-the-legacy-frontend
