### ISSUE TITLE
High UI load on a 4090 when idleing and nodes visible

### ISSUE THREAD

**Issue by Smai-Lee** [comfyanonymous/ComfyUI#4890]
### Your question

Hello,
i updated ComfyUI 3 or 4 days ago and now i have high load on a 4090 GPU just to render the nodes inside the UI.
![image](https://github.com/user-attachments/assets/9997e8af-0bdc-41c5-82e4-8cc0da4f8360)

Last update before this issue was right after flux release, and everything was fine. Fans stopped when idleing.

Load is now at 18-20% and with hardware acceleration in browser enabled, it will spike up to 40-50%. At the same time there is some Bus Transfer. All that can easily seen in HWMon.
If i move all the nodes out of view, the fans stop spinning and GPU usage is back to 0-2% like before. All that happens without any generations running.

Nodes in view:
![image](https://github.com/user-attachments/assets/5c943b12-3402-448f-98d3-78dcd198e161)

Nodes out of view (or Tab in the background)
![image](https://github.com/user-attachments/assets/8c80ad3d-b28c-49e1-aa85-52cf61b8d6e5)

I am using Chrome and i tried Edge, nearly the same behaviour.

**Comment by NeedsMoar** [comment]
Make sure you have a framerate limit set for the browser in the nvidia settings app and it'll probably fix this.  I've had the same problem in some games on AMD years ago where I forced the framerate in the game's own options to a bit above my max refresh to avoid wasting power generating hundreds of frames that never get drawn, but when I went back to menus it would remove the frame rate cap and hit like 3000fps and board power would go through the roof.  Capping the framerate globally fixed it.

**Comment by Smai-Lee** [comment]
Thank you for the reply. Frame Rate limit is set since i bought the 4090. Framerate counter from Comfy shows 30-40fps. Nothing was changed between the update. Rechecked the option in the driver, still all limits set.

The fan spinning drives me crazy, idling with UI open is louder here than generating nonstop with the tab in the background.

**Comment by christian-byrne** [comment]
If possible, you do a performance profile on the UI using browser devtools and export/share the results.

**Comment by LukeG89** [comment]
@Smai-Lee Have you tried disabling all custom nodes with the `--disable-all-custom-nodes` argument?

Because I had a similar problem in March, I could hear the fans on my laptop increase for no reason, and I found out that the cause was [cg-use-everywhere](https://github.com/chrisgoringe/cg-use-everywhere). Maybe there is a custom node that is doing the same thing to you.

**Comment by Smai-Lee** [comment]
> If possible, you should do a performance profile on the UI using browser devtools and export/share the results.

Hi,
I don't know what you need at all. Here is a full screenshot, i recorded it for like 7-8 secs. At 6sec i moved all the current nodes 'outofview'.
![image](https://github.com/user-attachments/assets/c385199f-4198-401f-86be-ee3008a17153)

Something more detailed with nodes in view
![image](https://github.com/user-attachments/assets/f0068394-c694-4267-86cb-b5ed72836c10)

If you need more information, Please let me know which ones.

**Comment by Smai-Lee** [comment]
> Thank you. In the top left corner there is an option to save the profile. After saving, you can share here and we can determine the cause.

Hi, i saved the json. Again, after approx 5.5 sec i moved the nodes out of view.
[Trace-20240917T153822.json](https://github.com/user-attachments/files/17029077/Trace-20240917T153822.json)

**Comment by christian-byrne** [comment]
> > Thank you. In the top left corner there is an option to save the profile. After saving, you can share here and we can determine the cause.
> 
> Hi, i saved the json. Again, after approx 5.5 sec i moved the nodes out of view. [Trace-20240917T153822.json](https://github.com/user-attachments/files/17029077/Trace-20240917T153822.json)

Thanks. There is a lot of overhead on reflow of DOM widgets:

![1-frame-render](https://github.com/user-attachments/assets/85626f36-780a-4f97-b3c0-41eaee576a5f)

This is a known issue (Comfy-Org/ComfyUI_frontend#470) that will likely be improved soon.

For an immediate fix in the meantime, the only custom node with relatively high overhead is SaltAI_Language_Toolkit (help icon rendering). If you disable that node, and then remove as many nodes with DOM Widgets (e.g., multiline text inputs) as possible, does the GPU utilization go down?

**Comment by Smai-Lee** [comment]
> For an immediate fix in the meantime, the only custom node with relatively high overhead is SaltAI_Language_Toolkit (help icon rendering). If you disable that node, and then remove as many nodes with DOM Widgets (e.g., multiline text inputs) as possible, does the GPU utilization go down?

Yay, that worked, load is now dow to 0-1% like usualy.
I disabled:
![image](https://github.com/user-attachments/assets/2cc78d65-96ea-4561-b5bf-9b1682ec0071)
and the result:
![image](https://github.com/user-attachments/assets/70e3502f-acf1-4635-883e-f45b96c1131c)

**Comment by NeedsMoar** [comment]
Interesting.  When SaltAI showed up as a new custom node I filed a bug against it suggesting they change the description to something that didn't look like it was produced by a drunk sales team with no product.  At the time when I looked through the code it consisted almost entirely of empty directories which seemed extremely suspect.  I wonder what they're actually doing...

**Comment by NeedsMoar** [comment]
It looks like for every node that's loaded and has documentation according to their CSV file, it creates a hook on the drawNodeShape method that draws a help button on it like so:

If I'm not mistaken this will get called more or less continuously since it sets everything as dirty for each node it updates which could potentially be all of them, every time the UI is touched and maybe when it isn't since the whole canvas is being flagged dirty whenever a node with a help button is drawn.  

```
                node.helpRect = new DOMRect(node.size[0]-22, -34, 27, 24);
                
				ctx.font = "11px sans";
  				ctx.fillText("?", parseInt(node.size[0])-11, -18);

				ctx.lineWidth = 1;
				ctx.strokeStyle = "#444";
				ctx.beginPath(); // Start a new path
				ctx.moveTo(node.size[0]-18, -30);
				ctx.lineTo(node.size[0]-18, -14);
				ctx.lineTo(node.size[0]+1, -14);
				ctx.stroke();
				
                node.graph?.setDirtyCanvas(true);
                return result;
```

That and it sets up an onMouseMove method that continuosly checks whether it's within the help button by comparing physical coordinates...  for every node.   That's a rather exciting number of onMouseMove handlers running constantly, but that shouldn't be GPU related. The manual graphics drawing is.
