### ISSUE TITLE
What is happening? I use comfyui and keep getting this error. KSampler 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by senpaiiss** [comfyanonymous/ComfyUI#4892]
### Your question

I used automatic 11111 but now starting to use comfyui and boy is it hard to fix all the millions of errors. 
Here is what i get for errors. 

Also oddly my Controlnet Openpose is also bugging out it wont do it but it can make other controlnet works. What am i doing wrong? 

![Desktop 2024-09-11 3-21-55 PM-261](https://github.com/user-attachments/assets/8b18e42e-3b7c-4286-a4b0-612907a6c2b1)
![Desktop 2024-09-11 8-30-52 AM-664](https://github.com/user-attachments/assets/07b44f1f-f580-4034-ba28-31d5d9ce792e)
![Desktop 2024-09-11 8-30-57 AM-783](https://github.com/user-attachments/assets/bf8900aa-6b0d-40e6-87c2-228185421c66)
![Desktop 2024-09-11 8-31-05 AM-900](https://github.com/user-attachments/assets/8516e6ee-4ed9-4a23-b99a-185d279c7139)
![Desktop 2024-09-11 8-31-10 AM-214](https://github.com/user-attachments/assets/f9a38cbb-581b-42f2-8522-ec67b04d78db)
[New Text Document (2).txt](https://github.com/user-attachments/files/16970562/New.Text.Document.2.txt)

**Comment by senpaiiss** [comment]
Text doc 2 has all error info

**Comment by ltdrdata** [comment]
You should not use FLUX Clip for SD1.5 checkpoint.

**Comment by senpaiiss** [comment]
> You should not use FLUX Clip for SD1.5 checkpoint.

So flux has no openpose models yet?

**Comment by ltdrdata** [comment]
> > You should not use FLUX Clip for SD1.5 checkpoint.
> 
> So flux has no openpose models yet?

ControlNet Union includes Pose capability as well.
https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Union

**Comment by senpaiiss** [comment]
> > > You should not use FLUX Clip for SD1.5 checkpoint.
> > 
> > 
> > So flux has no openpose models yet?
> 
> ControlNet Union includes Pose capability as well. https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Union

isnt it combined? i just need open pose.

**Comment by ltdrdata** [comment]
> > > > You should not use FLUX Clip for SD1.5 checkpoint.
> > > 
> > > 
> > > So flux has no openpose models yet?
> > 
> > 
> > ControlNet Union includes Pose capability as well. https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Union
> 
> isnt it combined? i just need open pose.

AFAIK, There are no pose-specific controlnet models yet that are not union models.

**Comment by senpaiiss** [comment]
> > > > > You should not use FLUX Clip for SD1.5 checkpoint.
> > > > 
> > > > 
> > > > So flux has no openpose models yet?
> > > 
> > > 
> > > ControlNet Union includes Pose capability as well. https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Union
> > 
> > 
> > isnt it combined? i just need open pose.
> 
> AFAIK, There are no pose-specific controlnet models for FLUX yet that are not union models.

that is kinda weird, open pose is hands down one of the most important controlnet. oh well

**Comment by ltdrdata** [comment]
> > > > > > You should not use FLUX Clip for SD1.5 checkpoint.
> > > > > 
> > > > > 
> > > > > So flux has no openpose models yet?
> > > > 
> > > > 
> > > > ControlNet Union includes Pose capability as well. https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Union
> > > 
> > > 
> > > isnt it combined? i just need open pose.
> > 
> > 
> > AFAIK, There are no pose-specific controlnet models for FLUX yet that are not union models.
> 
> that is kinda weird, open pose is hands down one of the most important controlnet. oh well

There is a diminished need for training individual models because the union model already covers many use cases.
Training dedicated models individually also requires significant cost, and training a dedicated CNET model doesn't necessarily guarantee the best quality.
