### ISSUE TITLE
There is no search option for the menu item after dragging the connecting line with the mouse!

### ISSUE THREAD

**Issue by aiise117** [comfyanonymous/ComfyUI#4901]
### Your question

The latest stable version does not have a search option in the menu after dragging the connection line with the mouse! The search box will only appear when you double-click the mouse. I remember in the old version, when you drag and drop a node and release it, a search option would appear

**Comment by ltdrdata** [comment]
It should appear normally. A specific extension might be causing a conflict.
Try disabling all custom nodes, refresh, and then test it again.

**Comment by LukeG89** [comment]
I think it's related to this: https://github.com/Comfy-Org/ComfyUI_frontend/issues/771

**Comment by aiise117** [comment]
Thank you for your enthusiastic help!
