### ISSUE TITLE
About VAE Encode (for Inpainting) Node

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#4904]
### Your question

![image](https://github.com/user-attachments/assets/ec8f43bb-e4e6-45c4-9ce6-8282ac91ea1a)

Is group 1 and 2 supposed to have the same effect?

**Comment by ltdrdata** [comment]
Nope. `VAE Encode (for inpainting)` is a special-purpose tool used when filling in with a denoise value of 1.0 using an inpainting model.
It fills the masked area with a grayscale image because the inpainting model requires it.

**Comment by pandayummy** [comment]
When using **InpaintModelConditioning** node instead of the **VAE Encode (for inpainting)**, should we also make the input image grayscale masked? 

![image](https://github.com/user-attachments/assets/2ec4e5b7-da1c-4d95-9251-36ee77431bf7)

**Comment by ltdrdata** [comment]
> When using **InpaintModelConditioning** node instead of the **VAE Encode (for inpainting)**, should we also make the input image grayscale masked?

No. Using `InpaintModelConditioning` is for the purpose of lowering the denoise to less than 1.0 in the form of img2img, so you shouldn't erase it to gray. For that, you need to configure the workflow using the conventional `SetLatentNoiseMask` method.

**Comment by pandayummy** [comment]
You mean this?
![image](https://github.com/user-attachments/assets/08231101-d856-4520-a268-6d6bce20ad6b)

**Comment by ltdrdata** [comment]
> You mean this? ![image](https://private-user-images.githubusercontent.com/32961592/367209870-08231101-d856-4520-a268-6d6bce20ad6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTcxNDIsIm5iZiI6MTcyNjIxNjg0MiwicGF0aCI6Ii8zMjk2MTU5Mi8zNjcyMDk4NzAtMDgyMzExMDEtZDg1Ni00NTIwLWEyNjgtNmQ2YmNlMjBhZDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA4NDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZDM3MDM4ZTAwMjdkY2FiMGVjZmMzNjU3ZmY5Zjk2OGFhM2FlMzVhYjQ1OWE0Njc2Njc1ZWRlN2M3ZWIyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.brUwLa1QTqaMLumTtb-8zeE0B8hdKOA_eR92-EINuFY)
> 
> Can you share a standard inpainting workflow using InpaintModelConditioning node?
> 
> thanks!

Oh, my mistake. When using that, there's no need to use `SetLatentNoiseMask`.

**Comment by pandayummy** [comment]
When using inpainting model, whether we should grayscale the masked area, depends on the denoise value.
If it's 1, then we should grayscale it.
If it's 0.99 or lower, we should leave it as it is.

Am I right ?

**Comment by pandayummy** [comment]
OK, thanks for your time!

**Comment by pandayummy** [comment]
One more question, I see many people use  Differential Diffusion  node in inpainting workflow, what does that do?

![image](https://github.com/user-attachments/assets/e74480da-be19-40ed-aa26-9a82ae87b43b)

**Comment by ltdrdata** [comment]
> One more question, I see many people use Differential Diffusion node in inpainting workflow, what does that do?
> 
> ![image](https://private-user-images.githubusercontent.com/32961592/367220889-e74480da-be19-40ed-aa26-9a82ae87b43b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTg3MTYsIm5iZiI6MTcyNjIxODQxNiwicGF0aCI6Ii8zMjk2MTU5Mi8zNjcyMjA4ODktZTc0NDgwZGEtYmUxOS00MGVkLWFhMjYtOWE4MmFlODdiNDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA5MDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YzMwMTVhZDdjNTQzNmRmMTliYWMwYjNmNGI5NDJlM2M4YjYxMTcyMDJiMzFlZThjNWY5MTExOWIwYWFkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QmDiHvCuY0UiUUUuW3PZk3vih1k_rviVgfS4pc04Wfs)

This allows you to adjust the strength of denoising when the mask is given in grayscale. Most commonly, when blur is applied to the mask, the edges are softly weakened. This way, even if strong denoising is applied to the central part, the denoising becomes weaker towards the edges, resulting in smooth inpainting.
