### ISSUE TITLE
Maybe frontend issue? UI won't display texts in text-box

### ISSUE THREAD

**Issue by HWT-WalterHu** [comfyanonymous/ComfyUI#4908]
### Your question

Code and workflow are pretty simple,  and the log shows the string param was properly delivered into the function, but the UI just does not display it.  Anyone has ideas? 
<img width="895" alt="image" src="https://github.com/user-attachments/assets/a6337cf0-4678-4ff9-bf60-1d7e2e60e0a8">

# codes: 
  class DisplayText_Zho:
      def __init__(self):
          pass
      @classmethod
      def INPUT_TYPES(s):
  
          return {
              "required": {        
                  "text": ("STRING", {"forceInput": True}),     
                  },
              "hidden": {"prompt": "PROMPT", "extra_pnginfo": "EXTRA_PNGINFO"},
              }
  
      RETURN_TYPES = ("STRING",)
      RETURN_NAMES = ("text",)
      OUTPUT_NODE = True
      FUNCTION = "display_text"
  
      CATEGORY = "Zho模块组/✨Gemini"
  
      def display_text(self, text, prompt=None, extra_pnginfo=None):
          print('text', text)
          return {"ui": {"string": [text,]}, "result": (text,)}

### Logs

```powershell
got prompt
text 111, 222
Prompt executed in 0.00 seconds
```

**Comment by wandrzej** [comment]
Finally, someone has the same problem as I do! 
Not sure if this will help but, on my end:
- happens in different browsers
- fresh install  of comfyui does NOT have this problem
- getting some typeerror in browser, but nothing that would seem related. 
- happens with all similar nodes, that dynamically should output text "Show any to console" from Crystools etc. 
- outputing to console does work, showing within the UI doesn't

**Comment by HWT-WalterHu** [comment]
> Finally, someone has the same problem as I do! Not sure if this will help but, on my end:
> 
> * happens in different browsers
> * fresh install  of comfyui does NOT have this problem
> * getting some typeerror in browser, but nothing that would seem related.
> * happens with all similar nodes, that dynamically should output text "Show any to console" from Crystools etc.
> * outputing to console does work, showing within the UI doesn't
Mine is similar with yours. I didn't notice fresh installed comfyui situation. 

Will re-install comfyui solve this problem? Or the problem will occur again when comfyui become not "fresh“ ？

**Comment by HWT-WalterHu** [comment]
> Finally, someone has the same problem as I do! Not sure if this will help but, on my end:
> 
> * happens in different browsers
> * fresh install  of comfyui does NOT have this problem
> * getting some typeerror in browser, but nothing that would seem related.
> * happens with all similar nodes, that dynamically should output text "Show any to console" from Crystools etc.
> * outputing to console does work, showing within the UI doesn't


I just solved my problem. 
I enabled page dev tools in my browser(F12) and found there was an error saying cannot connect to ws://...:8188/ws
Then I somehow set the permission of websocket connection for my server and the problem disappeared.

**Comment by alenhrp** [comment]
I encountered the same problem, the version is the latest, is it related to which plug-in or dependency, how to solve, thank you!

**Comment by sipie800** [comment]
+1, positive prompt or negtive prompt is disappearing at restarting, randomly.

**Comment by zzubnik** [comment]
My problems started when I updated to the latest version. Nothing that displays text in a node works now. All the various nodes that display text are now broken. My computed text-based workflows are no longer functional. I will have to roll back until this is resolved.

A fresh install does not fix this for me. This seems like a very basic requirement. I am surprised it's not a bigger issue.

**Comment by zzubnik** [comment]
Closed when the problem is not solved?

**Comment by christian-byrne** [comment]
Would you be able to check if its a custom node/extension issue? https://docs.comfy.org/troubleshooting/custom-node-issues#is-it-a-custom-node-problem%3F. That will help pinpoint the problem
