### ISSUE TITLE
euler == ddim ?

### ISSUE THREAD

**Issue by ytoaa** [comfyanonymous/ComfyUI#4915]
### Your question

I know that the original two samplers are different, and the results are different in the other (a1111), etc.
However, comfyui outputs the same results from the same seed.
I tested it in the latest version comfyui updated on September 14.
The test node is the primary node.

**Comment by comfyanonymous** [comment]
Euler is DDIM, though if you want to have the same results as the official DDIM you need to use the ddim_uniform scheduler.
