### ISSUE TITLE
Comfyui distribute execution for customer nodes

### ISSUE THREAD

**Issue by qingyuan18** [comfyanonymous/ComfyUI#4919]
### Feature Idea

whether we can define node execution on different server instance and GPU core
which will allow big model(like flux unet) run different server/GPU rather than all in single GPU/hosts, also we can distribute the pipeline DAG into different server , which large model on advance server(like A100), and small model on small server(like legacy T4）

**Comment by ltdrdata** [comment]
We are discussing this.
https://github.com/comfyanonymous/ComfyUI/discussions/3683

I'll close because this is redundant issue.
