### ISSUE TITLE
comfyui DetectFaces

### ISSUE THREAD

**Issue by qq1571574320** [comfyanonymous/ComfyUI#4920]
### Expected Behavior

[ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from E:\ComfyUI-aki-v1.4\models\landmarks\fan2_68_landmark.onnx failed:Load model E:\ComfyUI-aki-v1.4\models\landmarks\fan2_68_landmark.onnx failed. File doesn't exist

### Actual Behavior

no

### Steps to Reproduce

no

### Debug Logs

```powershell
no
```

**Comment by ltdrdata** [comment]
This issue should be moved to comfyui_facetools repo.
https://github.com/dchatel/comfyui_facetools
