### ISSUE TITLE
After Update comfy downgrade torch from 2.4.0+cu124 to 2.1.2+cu121

### ISSUE THREAD

**Issue by BlackVortexAI** [comfyanonymous/ComfyUI#4925]
### Your question

After every update my ComfyUI downgrades torch to 2.1.2+cu121 and I have to manually bring it back to 2.4.0+cu124 via pip otherwise xFormers causes an error. Where can I set the default version?

**Comment by ZeroCool22** [comment]
How you upgrade in what folder you need to be?

**Comment by ltdrdata** [comment]
Please upload the logs when downgrading to 2.1.2 and then upgrading back to 2.4.0.

**Comment by BlackVortexAI** [comment]
> How you upgrade in what folder you need to be?
> 
> It's here?:
> 
> C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\python_embeded\Scripts

Do you mean ComfyUI or torch? ComfyUI via StabilityMatrix. For torch I activate the venv in the ComfyUI root folder and with the pip commandos I first uninstall the old version and then I install the needed version.

pip uninstall torch
pip install torch==2.4.0+cu124 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124

**Comment by BlackVortexAI** [comment]
> The upgrade to 2.4.0 is intentionally blocked due to a bug in Windows. The latest version is set to skip 2.4.0 and use 2.4.1 instead. If you insist on using 2.4.0, you should not use the upgrade script.

Ah ok then I'll try the 2.4.1 version. Thanks for the info

**Comment by ZeroCool22** [comment]
> The upgrade to 2.4.0 is intentionally blocked due to a bug in Windows. The latest version is set to skip 2.4.0 and use 2.4.1 instead. If you insist on using 2.4.0, you should not use the upgrade script.

In what folder i need to be when update Xformers?

Here?:

C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded

**Comment by ltdrdata** [comment]
> > The upgrade to 2.4.0 is intentionally blocked due to a bug in Windows. The latest version is set to skip 2.4.0 and use 2.4.1 instead. If you insist on using 2.4.0, you should not use the upgrade script.
> 
> Ah ok then I'll try the 2.4.1 version. Thanks for the info
> 
> Edit: whent i install version 2.4.1 I get an error xformers 0.0.27.post2 requires torch==2.4.0, but you have torch 2.4.1+cu124 which is not compatible.
> 
> and i cannot update xformers subprocess-exited-with-error
> 
> i think i will create a new venv

It is correct that you should use 
```
C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded\python.exe -m pip install
```
However, I can't be certain that a compatible version of `xformers` for that specific `pytorch` will be available on Windows.
In this case, you might need to build it yourself.

**Comment by BlackVortexAI** [comment]
> > The upgrade to 2.4.0 is intentionally blocked due to a bug in Windows. The latest version is set to skip 2.4.0 and use 2.4.1 instead. If you insist on using 2.4.0, you should not use the upgrade script.
> 
> In what folder i need to be when update Xformers?
> 
> Here?:
> 
> C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded

I would need to know whether you have a venv or are running comfyui directly on your system. It doesn't matter from where you execute the pip commands only if you have a venv you have to activate it before that you work on the venv.

**Comment by MDMAchine** [comment]
I think this version works with 2.4.1. 
python -m pip install xformers==0.0.28.dev895

**Comment by NeedsMoar** [comment]
It is available in the default torch repo, it's 0.0.28.post1 for torch 2.4.1 / cu124.  Xformers isn't releasing anything for old cuda versions anymore on Windows. but it works fine for me.

**Comment by NeedsMoar** [comment]
You don't need to specify that version by the way, just use the 

pip3 install -U torch torchvision torchaudio xformers --index-url https://download.pytorch.org/whl/cu124

That'll always pull the most recent cu124 release version and compatible libraries.  You wouldn't be able to download a cu121 torch from the cu124 url anyway.  

Xformers originally had a bad / no wheel uploaded for 2.4.1 cuda 12.4 but it was just a screwup instead of whatever issue prevented it from existing for 2.4.0 so if you tried that before try it again.  If you already have the torch* libraries upgraded you can just get xformers from there but if you grab them all at once you'll always get the compatible versions if something else was updated and it should skip downloading versions you already have.

**Comment by BlackVortexAI** [comment]
> You don't need to specify that version by the way, just use the
> 
> pip3 install -U torch torchvision torchaudio xformers --index-url https://download.pytorch.org/whl/cu124
> 
> That'll always pull the most recent cu124 release version and compatible libraries. You wouldn't be able to download a cu121 torch from the cu124 url anyway.
> 
> Xformers originally had a bad / no wheel uploaded for 2.4.1 cuda 12.4 but it was just a screwup instead of whatever issue prevented it from existing for 2.4.0 so if you tried that before try it again. If you already have the torch* libraries upgraded you can just get xformers from there but if you grab them all at once you'll always get the compatible versions if something else was updated and it should skip downloading versions you already have.

Thanks a lot its now working
