### ISSUE TITLE
[Bug]: RuntimeError in KSampler

### ISSUE THREAD

**Issue by orange5288** [comfyanonymous/ComfyUI#4929]
WARNING SHAPE MISMATCH diffusion_model.input_blocks.0.0.weight WEIGHT NOT MERGED torch.Size([320, 8, 3, 3]) != torch.Size([320, 4, 3, 3]) loaded completely 0.0 1639.406135559082 True
!!! Exception during processing !!! Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 96, 64] to have 4 channels, but got 8 channels instead

**Comment by ltdrdata** [comment]
Please upload your workflow.
