### ISSUE TITLE
Missing file 

### ISSUE THREAD

**Issue by Mythomyth** [comfyanonymous/ComfyUI#4931]
![image](https://github.com/user-attachments/assets/2c3fb0e9-d750-4f3b-9cb9-cb574a9c19f2)
Help me on this issue to fix

What are these highlighted path
![image](https://github.com/user-attachments/assets/bed72af5-741a-46c7-ad65-7f9145e488ef)

**Comment by ltdrdata** [comment]
You have to move this issue to ComfyUI-tbox repo.
https://github.com/ai-shizuka/ComfyUI-tbox

Windows is unable to properly handle paths longer than 260 characters, and the  ComfyUI-tbox is using a path that is too deep.

Altenatively, you can modify regsitry.
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#registry-setting-to-enable-long-paths
