### ISSUE TITLE
Don't understand

### ISSUE THREAD

**Issue by wohomecome** [comfyanonymous/ComfyUI#4941]
### Your question
```
cd CharacterFaceSwap
# if you use ported ComfyUI
../../../python_embeded/python install.py
# otherwise
python install.py
```
I don't understand this step and it makes me not install

**Comment by mcmonkey4eva** [comment]
this is a question about that node pack https://github.com/ArtBot2023/CharacterFaceSwap?tab=readme-ov-file#character-face-swap not core comfy

**Comment by wohomecome** [comment]
cd CharacterFaceSwap
# if you use ported ComfyUI
../../../python_embeded/python install.py
# otherwise
python install.py
Here I need to install something manually


> 这是关于节点包的问题https://github.com/ArtBot2023/CharacterFaceSwap?tab=readme-ov-file#character-face-swap不是核心舒适

**Comment by wohomecome** [comment]
> Is there a reason for not using ComfyUI-Manager?



> 有什么理由不使用 ComfyUI-Manager？

cd CharacterFaceSwap
# if you use ported ComfyUI
.. /.. /.. /python_embeded/python install.py
# otherwise
python install.py
Here I need to enter or install something in order to use it
