### ISSUE TITLE
no checkpoint in my ComfyUI + Link broken plus HF profile empty

### ISSUE THREAD

**Issue by JOduMonT** [comfyanonymous/ComfyUI#4953]
### Your question

I would like to follow Scott with his [ComfyUI - Getting Started : Episode 1](https://www.youtube.com/watch?v=AbB33AxrcZo)
But it seems I have no checkpoint in my ComfyUI

and the link Download a checkpoint file on the [Getting Started](https://docs.comfy.org/get_started/gettingstarted) page is broken ;(

and the team [runwayml](https://huggingface.co/runwayml) doesn't have any model

so how could I get Start ?

**Comment by LukeG89** [comment]
You can go to [CivitAI](https://civitai.com/), there are plenty of models to choose from.

I would also suggest this YT channel: [Latent Vision](https://www.youtube.com/@latentvision)
He is the developer of [IPAdapter Plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus) node and he makes really great content. Check for example his [ComfyUI Basics series](https://www.youtube.com/watch?v=_C7kR2TFIX0&list=PLcW1kbTO1uPhDecZWV_4TGNpys4ULv51D)

**Comment by Molnfront** [comment]
On the missing runawayml page you have instructions for other models
