### ISSUE TITLE
Blender-like node interface

### ISSUE THREAD

**Issue by XJF2332** [comfyanonymous/ComfyUI#4956]
### Feature Idea

I’ve noticed that the current node interface in ComfyUI has its own unique approach, but I believe adopting Blender’s node design could significantly enhance user experience.

### Existing Solutions

Consider implementing Blender’s node design, where each node has both a text input box and a connection input. Here’s a visual example of what I’m referring to:
![image](https://github.com/user-attachments/assets/6e892d95-6879-4d19-a9e9-080c537fac46)
In ComfyUI, users must manually convert their desired input, which can be time-consuming and less intuitive compared to Blender’s approach.
Here are some advantages of Blender's node interface:
- Dual Input Mode: Nodes should display both a text input box and a connection port. This allows for quick adjustments and direct connections.
- Automatic Textbox Disable: When a node’s input is connected to another node’s output, the text input box should be automatically disabled. This prevents conflicting inputs and streamlines the workflow.

**Comment by asagi4** [comment]
I'm all for this, but I think you should make this feature request to the ComfyUI frontend repository instead, since it's developed separately nowadays.

**Comment by huchenlei** [comment]
Please move the issue to the frontend repo https://github.com/Comfy-Org/ComfyUI_frontend/issues. Thanks!
