### ISSUE TITLE
LoKr Lycoris support for SDXL (Trained via SimpleTuner)

### ISSUE THREAD

**Issue by blu3nh** [comfyanonymous/ComfyUI#4957]
### Feature Idea

Simply said, please add LoKr Lycoris support for sdxl as well.

You recently added exactly that for flux:
https://github.com/comfyanonymous/ComfyUI/commit/ea63b1c092e2974be9bcf4753d5305213f188e25

Same issue as here:
https://github.com/comfyanonymous/ComfyUI/issues/4476

except for sdxl

Could you please add it for sdxl as well?

**Comment by comfyanonymous** [comment]
Do you have an example lora?

**Comment by davidrd123** [comment]
I'd love to see this added - I have an example SDXL LoKr [here](https://huggingface.co/davidrd123/john-singer-sargent-sdxl-lokr-02)

**Comment by comfyanonymous** [comment]
Should be implemented now.
