### ISSUE TITLE
节点和节点连线出现严重的错乱！如何解决如何解决？？？

### ISSUE THREAD

**Issue by BannyLon** [comfyanonymous/ComfyUI#4964]
### Expected Behavior

我的电脑是MAC，今早升级到最新版后，节点和节点连线出现严重的错乱！如何解决如何解决？？？
![11](https://github.com/user-attachments/assets/25464c40-447c-44ef-9d3a-a2cc1b7fc1ff)
![1726632044469](https://github.com/user-attachments/assets/17f0fd2f-578a-43d8-bd21-7a8f2a74d1c7)

### Actual Behavior

我的电脑是MAC，今早升级到最新版后，节点和节点连线出现严重的错乱！如何解决如何解决？？？
![11](https://github.com/user-attachments/assets/25464c40-447c-44ef-9d3a-a2cc1b7fc1ff)
![1726632044469](https://github.com/user-attachments/assets/17f0fd2f-578a-43d8-bd21-7a8f2a74d1c7)

### Steps to Reproduce

我的电脑是MAC，今早升级到最新版后，节点和节点连线出现严重的错乱！如何解决如何解决？？？
![11](https://github.com/user-attachments/assets/25464c40-447c-44ef-9d3a-a2cc1b7fc1ff)
![1726632044469](https://github.com/user-attachments/assets/17f0fd2f-578a-43d8-bd21-7a8f2a74d1c7)

### Debug Logs

```powershell
我的电脑是MAC，今早升级到最新版后，节点和节点连线出现严重的错乱！如何解决如何解决？？？
![11](https://github.com/user-attachments/assets/25464c40-447c-44ef-9d3a-a2cc1b7fc1ff)
![1726632044469](https://github.com/user-attachments/assets/17f0fd2f-578a-43d8-bd21-7a8f2a74d1c7)
```

**Comment by dnlzsy** [comment]
I updated to the latest code and this is the problem. I just rolled it back.

**Comment by bruibbruib** [comment]
Same issue here.

**Comment by Kosinkadink** [comment]
Uninstall mixlab to fix your issue

**Comment by bruibbruib** [comment]
No mixlab here.
 I'm trying to find what other extension it may be...

**Comment by chan-n12** [comment]
Just switch the mixlab version to 9-12

**Comment by christian-byrne** [comment]
Fixed in Mixlab https://github.com/shadowcz007/comfyui-mixlab-nodes/commit/d9edbd535eb6f5705583833e3133b11cc95b27c4. Update the extension.

**Comment by xiaowuzicode** [comment]
Same issue here.

**Comment by hillleaf** [comment]
更新mixlab到最新版既可以解决（卸载，再安装）。

**Comment by Lee957-kp** [comment]
That's the way it's been solved
