### ISSUE TITLE
Update comfyui failed，How to solve this problem?

### ISSUE THREAD

**Issue by wuzhonghui56** [comfyanonymous/ComfyUI#4966]
### Your question

Update ComfyUI
Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v -- origin
  stderr: 'error: The following untracked working tree files would be overwritten by merge:'
CUSTOM NODE PULL: Fail
Install: pip packages
Line is comment...skipping

**Comment by ltdrdata** [comment]
goto ComfyUI dir in cmd.
And execute 
```
git pull
```
What is the error message?

**Comment by wuzhonghui56** [comment]
> 在 cmd 中转到 ComfyUI 目录。 然后执行
> 
> ```
> git pull
> ```
> 
> 错误信息是什么？

E:\ComfyUI_windows_portable\ComfyUI>git pull
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 17 (delta 14), reused 17 (delta 14), pack-reused 0 (from 0)
Unpacking objects: 100% (17/17), 3.21 KiB | 164.00 KiB/s, done.
From https://github.com/comfyanonymous/ComfyUI
   7183fd1..0bfc7cc  master      -> origin/master
   6b14fc8..e80dc96  patch_hooks -> origin/patch_hooks
Updating f067ad1..0bfc7cc
error: The following untracked working tree files would be overwritten by merge:
        web/assets/index-BRhY6FpL.css
        web/assets/index-CrROdkG4.js
        web/assets/index-CrROdkG4.js.map
        web/assets/index-Dfv2aLsq.js
        web/assets/index-Dfv2aLsq.js.map
        web/assets/index-W4jP-SrU.css
        web/assets/userSelection-CF-ymHZW.css
        web/assets/userSelection-DSpF-zVD.js
        web/assets/userSelection-DSpF-zVD.js.map
        web/dist.zip
Please move or remove them before you merge.
Aborting

**Comment by ltdrdata** [comment]
> > 在 cmd 中转到 ComfyUI 目录。 然后执行
> > 
> > ```
> > git pull
> > ```
> > 
> > 错误信息是什么？
> 
> E:\ComfyUI_windows_portable\ComfyUI>git pull
> remote: Enumerating objects: 17, done.
> remote: Counting objects: 100% (17/17), done.
> remote: Compressing objects: 100% (3/3), done.
> remote: Total 17 (delta 14), reused 17 (delta 14), pack-reused 0 (from 0)
> Unpacking objects: 100% (17/17), 3.21 KiB | 164.00 KiB/s, done.
> From https://github.com/comfyanonymous/ComfyUI
>    7183fd1..0bfc7cc  master      -> origin/master
>    6b14fc8..e80dc96  patch_hooks -> origin/patch_hooks
> Updating f067ad1..0bfc7cc
> error: The following untracked working tree files would be overwritten by merge:
>         web/assets/index-BRhY6FpL.css
>         web/assets/index-CrROdkG4.js
>         web/assets/index-CrROdkG4.js.map
>         web/assets/index-Dfv2aLsq.js
>         web/assets/index-Dfv2aLsq.js.map
>         web/assets/index-W4jP-SrU.css
>         web/assets/userSelection-CF-ymHZW.css
>         web/assets/userSelection-DSpF-zVD.js
>         web/assets/userSelection-DSpF-zVD.js.map
>         web/dist.zip
> Please move or remove them before you merge.
> Aborting


Remove ComfyUI/web dir.
And
Execute this
```
git reset --hard
git pull
```

**Comment by wangminxing2019** [comment]
If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
这个问题怎么解决呢

**Comment by wangminxing2019** [comment]
D:\Xing_Chi\AI_ruanjian\ComfyUI_windows\ComfyUI>git branch --set-upstream-to=origin/<branch> master
系统找不到指定的文件。

D:\Xing_Chi\AI_ruanjian\ComfyUI_windows\ComfyUI>git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

**Comment by ltdrdata** [comment]
```
git checkout master
git pull
```
