### ISSUE TITLE
Spandrel's latest update has breaking changes

### ISSUE THREAD

**Issue by Kim2091** [comfyanonymous/ComfyUI#4973]
https://github.com/chaiNNer-org/spandrel/releases/tag/v0.4.0

**Comment by ltdrdata** [comment]
In my tests, it's working fine even in 0.4.0.
Can you elaborate what kind of issue is occurring?

**Comment by comfyanonymous** [comment]
is there any specific model that doesn't work?

**Comment by Kim2091** [comment]
I posted this just to inform you guys that there were breaking changes in the new release vs 0.3.4. If it's all working okay, then that's great 🙂

This issue can be closed in that case

**Comment by Kim2091** [comment]
@comfyanonymous I just tested. The new architectures that spandrel added support for do not function in ComfyUI. Old archs function fine.

Samples:
[RealPLKSR Dysample](https://github.com/Phhofm/models/releases/download/4xNature_realplksr_dysample/4xNature_realplksr_dysample.pth)
[MoSR](https://drive.google.com/drive/u/1/folders/151LT6sOCbFQiaSaXkIyO_zcPulopVPo6)

**Comment by Kim2091** [comment]
Turns out I forgot to manually update Spandrel to 0.4.0. Never mind, sorry for the pings.
