### ISSUE TITLE
can't set attribute 'device' for hunyuandit

### ISSUE THREAD

**Issue by sipie800** [comfyanonymous/ComfyUI#4982]
### Expected Behavior

https://github.com/Tencent/HunyuanDiT/tree/main/comfyui-hydit

use this node, it used to work well. After some updates of comfy durning August. It says that error.

### Actual Behavior

none

### Steps to Reproduce

none

### Debug Logs

```powershell
none
```

**Comment by comfyanonymous** [comment]
This was added to the core so you don't need to use these nodes anymore.

**Comment by sipie800** [comment]
can you provide a new workflow for hunyuandit? I use the official ones. Now they all go usable. It's very tired to convert them to new comfyui.

**Comment by sipie800** [comment]
or please tell me where to roll back. I always update comfy. Now maybe it's getting too complicated for reusing old things.

**Comment by ltdrdata** [comment]
> can you provide a new workflow for hunyuandit? I use the official ones. Now they all go unusable. It's very tired to convert them to new comfyui.

Nothing special. Just you can load hunyuan model via `Load Checkpoint` node.
https://comfyanonymous.github.io/ComfyUI_examples/hunyuan_dit/

**Comment by sipie800** [comment]
> > can you provide a new workflow for hunyuandit? I use the official ones. Now they all go unusable. It's very tired to convert them to new comfyui.
> 
> Nothing special. Just you can load hunyuan model via `Load Checkpoint` node. https://comfyanonymous.github.io/ComfyUI_examples/hunyuan_dit/

will the hydit all-in-one loader support kohya trained lora ?

**Comment by sipie800** [comment]
lora is working if use the all-in-one hunyuandit loader. But what if it's a shared dit-only checkpoint? (just like https://civitai.com/models/638641/fantasy-vision-dit?modelVersionId=714161). Which official node should be used to load the dit ?
It's very usual to use a sub shared checkpoint, your example use the all-in-one checkpoint, which seems to make no much sense.
We can merge the checkpoints somehow into the all-in-one. That's just too much waste.

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/618f4c9c-2ac7-44c8-8013-39a529216e3b)

If you want more advanced text encoding, you can use dedicated Text Encode nodes for each model. 
This exists not only for HunyuanDiT, but also separately for SDXL, SDXLRefiner, FLUX, SD3, and controlnet.

**Comment by sipie800** [comment]
Which clip loader to use? this is tested and not working,
![2024-09-21_102903](https://github.com/user-attachments/assets/ed9ec34e-b472-4ce3-89e4-96b6db2b62aa)

**Comment by ltdrdata** [comment]
> Which clip loader to use? this is tested and not working, ![2024-09-21_102903](https://private-user-images.githubusercontent.com/42767079/369589835-ed9ec34e-b472-4ce3-89e4-96b6db2b62aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4ODcwNTYsIm5iZiI6MTcyNjg4Njc1NiwicGF0aCI6Ii80Mjc2NzA3OS8zNjk1ODk4MzUtZWQ5ZWMzNGUtYjQ3Mi00Y2UzLTg5ZTQtOTZiNmRiMmI2MmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDAyNDU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkODk4ZWNlYmE2OTczY2IxMjI0OWUzYzhiOGE5NTcyMDcwYWQ3MzhjMzQ2ZmRhMzBlMjQyY2RkMTNlNTg0OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U1abGHj53Gg2sklhcu0z5J-ZQBuO8ayAR8P_DfIErB8) There is no type for hunyuandit.

The clip model inside the Checkpoint is already dual clip model. 
Unfortunately, the CLIP Loaders supported in the core do not support the clip model for HunyuanDiT.
This will require a separate feature request.
