### ISSUE TITLE
ComfyUI not running after multiple fresh installations

### ISSUE THREAD

**Issue by tomgreyman** [comfyanonymous/ComfyUI#4986]
### Your question

I have tried my level best to reinstall a fresh copy of ComfyUi to no avail. i keep getting an error message. Can anyone help me?
![Capture](https://github.com/user-attachments/assets/829d7a63-5a13-4bfe-adb3-a449ce3084c7)
)

**Comment by jmorbit** [comment]
I have been having the same issue.  I had a problem with llama-cpp not working or not installing correctly and tried to do fresh install of Comfy and now none of the installs will launch.  I feel your pain.

**Comment by ltdrdata** [comment]
The recently added feature appears to have a bug that causes issues due to blanks in your path

**Comment by jmorbit** [comment]
> The recently added feature appears to have a bug that causes issues due to blanks in your path

None of my links have blanks.  I am at a loss.

**Comment by tomgreyman** [comment]
At this point I can't do a thing but just waiting for a fix to drop.

**Comment by ltdrdata** [comment]
> > The recently added feature appears to have a bug that causes issues due to blanks in your path
> 
> None of my links have blanks. I am at a loss.

Oh.. Then this could potentially be a Windows path issue.

**Comment by Grantyz** [comment]
Try running it in the base folder (in "C:\"). A space in the username can cause errors in python.

**Comment by tomgreyman** [comment]
OK I will try to do that. Will update soon

**Comment by CGstunts** [comment]
Having the same issue in Nov 2025
