### ISSUE TITLE
--lowvram throws an error.

### ISSUE THREAD

**Issue by GeneralAwareness** [comfyanonymous/ComfyUI#50]
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 173, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "D:\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "D:\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "D:\ComfyUI\execution.py", line 62, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "D:\ComfyUI\nodes.py", line 760, in sample
    return common_ksampler(self.device, model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
  File "D:\ComfyUI\nodes.py", line 650, in common_ksampler
    model_management.load_model_gpu(model)
  File "D:\ComfyUI\comfy\model_management.py", line 114, in load_model_gpu
    accelerate.dispatch_model(real_model, device_map=device_map, main_device="cuda")
  File "D:\stable-diffusion-webui\venv\lib\site-packages\accelerate\big_modeling.py", line 212, in dispatch_model
    check_device_map(model, device_map)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\modeling.py", line 581, in check_device_map
    raise ValueError(
ValueError: The device_map provided does not give any device for the following parameters: betas, alphas_cumprod, alphas_cumprod_prev, sqrt_alphas_cumprod, sqrt_one_minus_alphas_cumprod, log_one_minus_alphas_cumprod, sqrt_recip_alphas_cumprod, sqrt_recipm1_alphas_cumprod, posterior_variance, posterior_log_variance_clipped, posterior_mean_coef1, posterior_mean_coef2

**Comment by comfyanonymous** [comment]
lowvram needs an up to date accelerate package:

Try this:
pip install accelerate --upgrade

**Comment by GeneralAwareness** [comment]
I am using the venv from Automatic1111 that you said we could.  Will that blow his up?

**Comment by comfyanonymous** [comment]
Updating it shouldn't break anything.

**Comment by GeneralAwareness** [comment]
You also have to hit requirements_versions.txt or it will push it back down to 0.12.0.

I also get this warning and wonder if this is affecting my gens?

![image](https://user-images.githubusercontent.com/124339252/223235521-74822e8a-5fcd-4131-bf06-4413a773662a.png)

**Comment by comfyanonymous** [comment]
That warning is completely harmless and can be ignored.

**Comment by GeneralAwareness** [comment]
Thank you for your help.
