### ISSUE TITLE
Generating absurd amounts of the same over and over. [AFTER NEW UPDATE]

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#5003]
### Expected Behavior

normal amount of queues added

### Actual Behavior

It at random, suddenly in my queue has something like 50 concurrent jobs all the same prompt, same aspect ratio and all setting the same except the randomisers. has happened 6-7 times by now (generating 1000s of images all being the same prompt)

### Steps to Reproduce

Do 100s of jobs in a queue.

### Debug Logs

```powershell
/
```

**Comment by mcmonkey4eva** [comment]
Sounds like you're describing a frontend issue? https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by BrechtCorbeel** [comment]
No idea but it is getting annoying, I think I have a row of 20 of these in batches of 7 images and just closed 30 queues, it would be +- 500 images every 7 images taking 5-6 minutes, an hour or 2 of generating too much:

![image](https://github.com/user-attachments/assets/bd38b9d0-2679-4669-8ff3-757ab1316504)
