### ISSUE TITLE
Error occurred when executing IPAdapterUnifiedLoader:  ClipVision model not found

### ISSUE THREAD

**Issue by MODOMison** [comfyanonymous/ComfyUI#5004]
### Your question

how can i fix this?
![Screenshot 2024-09-20 175238](https://github.com/user-attachments/assets/076a9d37-bff1-4045-bcfd-91f979d00864)
![Screenshot 2024-09-20 175319](https://github.com/user-attachments/assets/717eefd8-e571-4455-b347-abe356edce02)
![Screenshot 2024-09-20 180051](https://github.com/user-attachments/assets/25ba82ea-fcad-4d7d-bc4a-301a75b0ed48)

### Logs

```powershell
Error occurred when executing IPAdapterUnifiedLoader:

ClipVision model not found.

File "C:\Users\Owner\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Owner\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Owner\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "C:\Users\Owner\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Owner\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 559, in load_models
raise Exception("ClipVision model not found.")
```

### Other

i have a couple clip vision models in place, is it a bad download or name error
thansk a lot for the help!

**Comment by ltdrdata** [comment]
This issue should be moved to ComfyUI_IPAdapter_plus repo.
https://github.com/cubiq/ComfyUI_IPAdapter_plus

**Comment by wardenlee** [comment]
I have the same problem. I encountered the same issue while using a Brushnet workflow
![20240922024633](https://github.com/user-attachments/assets/b289289f-a71f-4072-9574-28a677db0b82)
![_20240922024551](https://github.com/user-attachments/assets/c7849d53-4b53-4102-a273-08ca1b65f2cc)

**Comment by wardenlee** [comment]
But I already have a clip-vision file
![20240922024945](https://github.com/user-attachments/assets/13ba0b4f-10c0-43c0-9e8c-5099eddd4bb3)

**Comment by ltdrdata** [comment]
https://github.com/cubiq/ComfyUI_IPAdapter_plus#installation
The ipadapter requires the exact model name.

**Comment by MODOMison** [comment]
does anyone know the name to use?

**Comment by wardenlee** [comment]
> does anyone know the name to use?

Now I may know the reason, you can refer to here！https://github.com/cubiq/ComfyUI_IPAdapter_plus
![20240922120645](https://github.com/user-attachments/assets/c2dd1c5f-ab2e-49ec-b3f7-f3aa10d71b56)

**Comment by wardenlee** [comment]
Now let me try to solve this similar problem

**Comment by 400123123** [comment]
rename bro

**Comment by Ekhlaszaki** [comment]
so what name should I keep then?

**Comment by wardenlee** [comment]
> so what name should I keep then?

The name above is the correct name. This was not the name when you downloaded it. You're asking because you didn't download it or you forgot about it

**Comment by Ekhlaszaki** [comment]
![Screenshot 2024-10-29 011021](https://github.com/user-attachments/assets/04bd3133-f5f2-4b5b-b19b-736570b77e05)
i already renamed but still not working

**Comment by ltdrdata** [comment]
I recommend redownload via ComfyUI-Manager.

![image](https://github.com/user-attachments/assets/5df6be23-f49a-45db-a5ab-23c14a7e2529)

**Comment by sigmayang** [comment]
> ![Screenshot 2024-10-29 011021](https://private-user-images.githubusercontent.com/185719538/380867557-04bd3133-f5f2-4b5b-b19b-736570b77e05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDM1MTAsIm5iZiI6MTczMDIwMzIxMCwicGF0aCI6Ii8xODU3MTk1MzgvMzgwODY3NTU3LTA0YmQzMTMzLWY1ZjItNGI1Yi1iMTliLTczNjU3MGI3N2UwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxMjAwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjA4YTE4YjY0ZTFkMTNlZjE5MzliMWQyYWFmZjc3ZGJlMDRlNDY5MTg1YzM0ZWI3MDk2OWM2NzAwMDVmNjgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7kgUJlFaj-iSPnHjKNlj5U-K8hEIm_9GcJbZI--fpNg) i already renamed but still not working

![image](https://github.com/user-attachments/assets/8e241cdc-c3f2-4db4-a915-c2bb28d29cc6)
download these models and move "/ComfyUI/models/ipadapter" path

**Comment by ltdrdata** [comment]
> > I recommend redownload via ComfyUI-Manager.
> > ![image](https://private-user-images.githubusercontent.com/128333288/381239586-5df6be23-f49a-45db-a5ab-23c14a7e2529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDcyMzgsIm5iZiI6MTczMjgwNjkzOCwicGF0aCI6Ii8xMjgzMzMyODgvMzgxMjM5NTg2LTVkZjZiZTIzLWY0OWEtNDVkYi1hNWFiLTIzYzE0YTdlMjUyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNTE1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWI2NjI3ZjQ4YjA1Zjk2Yjg1ZmI3MjI3NWQzYTg1OGJiMWY3NDU4YzkzZTgwNWJjMzk1YzFmMjkzMGEzZDdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h-Un-QOvtuHtfyZLOVVshAbadzLii4G_y5Q1haortZ8)
> 
> ![image](https://private-user-images.githubusercontent.com/166925016/390838455-cca14be8-e779-493d-95d2-119fe015ba71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDc5MjIsIm5iZiI6MTczMjgwNzYyMiwicGF0aCI6Ii8xNjY5MjUwMTYvMzkwODM4NDU1LWNjYTE0YmU4LWU3NzktNDkzZC05NWQyLTExOWZlMDE1YmE3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNTI3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTk3YWYxYmNlMjVmOGM5NDZjNzgzMDlmY2Q4MDI5OTY4MDQ0M2NkNWQzN2U2MzY0YzA2YWY4ZDk3NDIwYWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GMMCwmqWgTItahPswR1vwsKtRZO4yIyDjblzh_VcAB8)
> 
> How you get this in manager?

click `Model Manager` instead of `Custom Nodes Manager` in Manager dialog.

**Comment by Abilashs003** [comment]
For anybody its working please help

**Comment by LukeG89** [comment]
> For anybody its working please help

@Abilashs003 You just have to follow the installation instructions in the IPAdapter Plus repo: https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#installation

**Comment by Bockbidir** [comment]
I hope that everyone who writes read the instructions will shit themselves and at the same time their water will be turned off. and the same idiots will tell them just open the tap

**Comment by zer20210824** [comment]
I updated Comfyui and re downloaded iPdapter, and checked the folders for clipvision and iPdapter to ensure that the model is correct. However, when I run it, errors still occur. Please tell me what I should do. Thank you very much @ltdrdata @nikola43 

![Image](https://github.com/user-attachments/assets/da4abd10-49b0-4d6a-8849-195465f4eee9)
![Image](https://github.com/user-attachments/assets/5ac90499-d0dd-46a6-9c75-936de2fa37dd)
![Image](https://github.com/user-attachments/assets/73b8f054-3e35-45a6-b55a-d4785ec2583e)
![Image](https://github.com/user-attachments/assets/e750d2b8-50cc-48ad-8b71-3e1606703043)
![Image](https://github.com/user-attachments/assets/406cce6f-90f1-4f82-92fe-cd6c5ab89cd1)

**Comment by ltdrdata** [comment]
> I updated Comfyui and re downloaded iPdapter, and checked the folders for clipvision and iPdapter to ensure that the model is correct. However, when I run it, errors still occur. Please tell me what I should do. Thank you very much @ltdrdata @nikola43 
> 
> ![Image](https://github.com/user-attachments/assets/da4abd10-49b0-4d6a-8849-195465f4eee9)
> ![Image](https://github.com/user-attachments/assets/5ac90499-d0dd-46a6-9c75-936de2fa37dd)
> ![Image](https://github.com/user-attachments/assets/73b8f054-3e35-45a6-b55a-d4785ec2583e)
> ![Image](https://github.com/user-attachments/assets/e750d2b8-50cc-48ad-8b71-3e1606703043)
> ![Image](https://github.com/user-attachments/assets/406cce6f-90f1-4f82-92fe-cd6c5ab89cd1)
> 

You'd better post this issue to the ipadatper plus repo.
https://github.com/cubiq/ComfyUI_IPAdapter_plus

**Comment by LW-001** [comment]
如何解决，我现在和遇到的是同一个问题。

**Comment by LW-001** [comment]
我刚刚用了这位兄弟的方法，下载过后，终于成功的跑起来了。

![Image](https://github.com/user-attachments/assets/4ac1a45b-eaf8-4256-864b-b669f0bc5936)

![Image](https://github.com/user-attachments/assets/2b7a31cf-9fec-44db-a8d5-fa896a8db99e)

![Image](https://github.com/user-attachments/assets/08fd4032-92b6-43da-ac39-2f52e4ffac84)

**Comment by LW-001** [comment]
> 我刚刚用了这位兄弟的方法，下载过后，终于成功的跑起来了。
> 
> ![Image](https://github.com/user-attachments/assets/4ac1a45b-eaf8-4256-864b-b669f0bc5936)
> 
> ![Image](https://github.com/user-attachments/assets/2b7a31cf-9fec-44db-a8d5-fa896a8db99e)
> 
> ![Image](https://github.com/user-attachments/assets/08fd4032-92b6-43da-ac39-2f52e4ffac84)

我自己从官方网站上下载也找不到文件，现在用自带的manager下载后，就可以正常跑动了

**Comment by davidyoungjunsong** [comment]
I had the same problem, but when I 
1. Downloaded the 3 files for "/ComfyUI/models/clip_vision", renamed them as "CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors", "clip_vision_model.safetensors", and "clip-vit-large-patch14-336.bin" respectively,
2. Downloaded all the CLIPVision models  from the ComfyUI Manager,
3. Downloaded all the files for "/ComfyUI/models/ipadapter",
4. Created a new folder named "ipadapter" (in /ComfyUI/models/ipadapter),  
5. Moved all the (ipadapter) files to the new folder named "ipadapter,
6. Restarted ComfyUI, and
7. Reopened ComfyUI,

the problem was solved. Thank you so much for your advice, @ltdrdata!
