### ISSUE TITLE
Add Option to Make Nodes Translucent

### ISSUE THREAD

**Issue by HighInBC** [comfyanonymous/ComfyUI#5005]
### Feature Idea

Description
It would be helpful to have an option to make nodes translucent in the ComfyUI interface. This feature could improve user experience when working with complex node graphs by allowing better visibility of overlapping elements or connections. The translucency could be adjustable (e.g., via a slider or pre-set levels), giving users control over how transparent they want the nodes to appear.

Use Case
When working with large and complex node graphs, it can become difficult to track connections and manage layout. Having translucent nodes would help users keep a clearer view of their workspace, especially when multiple nodes overlap or are placed close together. This feature could make workflow management easier and more intuitive, without having to constantly rearrange nodes for visibility.

Suggestions for Implementation

Add a UI control to adjust node opacity (e.g., a slider or toggle button).
Alternatively, add a simple CSS or graphical setting in the configuration files to manually adjust node translucency.
Consider providing customizable levels of opacity (e.g., 25%, 50%, 75%) for user flexibility.
This feature would be a valuable addition for users who frequently work with dense and complex node structures, improving visibility and ease of use.

**Comment by LukeG89** [comment]
You should open this feature request to the Front-End repo: https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by HighInBC** [comment]
Thank you for the advice. I will do that and close this here.
