### ISSUE TITLE
CatVTONWrapper

### ISSUE THREAD

**Issue by Zdeamon505** [comfyanonymous/ComfyUI#5007]
### Your question

why ? who can help me please 
![Untitled](https://github.com/user-attachments/assets/92a030f4-b9ae-4b94-a76f-8a8fa434ed68)

### Logs

```powershell
e couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like C:\Users\MsDoo\Downloads\Compressed\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CatVTON\stable-diffusion-inpainting is not the path to a directory containing a scheduler_config.json file. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
```

### Other

e couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like C:\Users\MsDoo\Downloads\Compressed\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CatVTON\stable-diffusion-inpainting is not the path to a directory containing a scheduler_config.json file. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

**Comment by ltdrdata** [comment]
This issue should be moved to ComfyUI_CatVTON_Wrapper repo.
https://github.com/chflame163/ComfyUI_CatVTON_Wrapper/issues

**Comment by PoshEstop** [comment]
Ever found the issue?

**Comment by thearturord** [comment]
Go here and use the link to download the models: https://github.com/chflame163/ComfyUI_CatVTON_Wrapper
