### ISSUE TITLE
Better Model Matching with SHA256

### ISSUE THREAD

**Issue by kjenney** [comfyanonymous/ComfyUI#5009]
### Feature Idea

Model selection is critical in workflows. References to models are currently ambiguous. Adding metadata about models - specifically the SHA256 fingerprint will ensure reproducibility of example workflows and accelerate user adoption. 

I recommend that we add a metadata section to the workflow json to reference the SHA256 fingerprint of models.

### Existing Solutions

Possible matches in issues: 
* https://github.com/comfyanonymous/ComfyUI/issues/3003

Some nodes have coded fingerprint checking into them, but this solution would be an update to core.

**Comment by mcmonkey4eva** [comment]
model metadata in workflows is an already planned work in progress

**Comment by kjenney** [comment]
Great news! Please link to an issue and/or PR that I can follow.

**Comment by mcmonkey4eva** [comment]
that's part of a big main goal so it will be announced on https://blog.comfy.org/ when it's done

**Comment by geroldmeisinger** [comment]
@mcmonkey4eva any update on this or issue/PR/roadmap link?
