### ISSUE TITLE
Diffusers deprecated. ComfyUI doesn't auto-upgrade. MANY NODES CANNOT WORK

### ISSUE THREAD

**Issue by StrikerMax** [comfyanonymous/ComfyUI#5010]
### Feature Idea

Need to auto-update diffusers version.

Many nodes cannot work..

Do it manually...
Run this in ComfyUI_windows_portable folder:
python_embeded\python.exe -m pip install -U diffusers

**Comment by mcmonkey4eva** [comment]
Comfy core does not use diffusers, this is an issue with either the relevant nodes (improper requirements list) or comfy manager (not handling requirements properly), or diffusers itself (deprecating things constantly causing compat issues)
