### ISSUE TITLE
Mixlab-nodes breaking ComfyUI after latest ComfyUI update

### ISSUE THREAD

**Issue by martintomov** [comfyanonymous/ComfyUI#5022]
After updating to the latest version of ComfyUI, mixlab-nodes are misaligned, and connections are stretched or distant, disrupting the workflow. This issue was also mentioned in this Reddit post.

![image](https://github.com/user-attachments/assets/97c8dd1c-82b5-476a-ae21-f35a4521dc85)

https://www.reddit.com/r/comfyui/comments/1fd08ur/misaligned_nodes_and_distant_connections/

_Originally posted by @martintomov in https://github.com/shadowcz007/comfyui-mixlab-nodes/issues/331_

**Comment by Jojo-xqt** [comment]
重新安装mixlab扩展。就可以恢复正常了。
Reinstall the mixlab extension. It will return to normal.

**Comment by martintomov** [comment]
Thanks
