### ISSUE TITLE
Supports both ipv4 and ipv6

### ISSUE THREAD

**Issue by maomaoyan** [comfyanonymous/ComfyUI#5027]
### Feature Idea

What listening configuration should I modify to support both ipv4 and ipv6? I have tried --listen ipv6 and it works, but ipv4 is no longer available.

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/447da7ea8676975f18eafe56a408e4572b17f2e7
https://github.com/comfyanonymous/ComfyUI/commit/3a0eeee32053f6c45c5ad4b3975f4ee229b01fbb
