### ISSUE TITLE
Noise Images after latest update

### ISSUE THREAD

**Issue by pphoto808** [comfyanonymous/ComfyUI#5028]
### Your question

Mac Studio M2 Ultra, MacOS 18
Just updated Comfy and now getting noise images. All was good till I updated. 
![Screenshot 2024-09-22 at 15 52 42](https://github.com/user-attachments/assets/e53163d4-75d4-42ee-a9b2-afafc845ea02)

**Comment by JSoon** [comment]
Same problem here while using GGUF, any ideas?
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/e01786ce-d8db-410a-bd61-b9fa4b0d7bf2">

**Comment by JSoon** [comment]
BTW, this is running under `--cpu` mode.
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/ab8bb2c1-8417-4e5e-af1e-f7650889d8ea">

**Comment by winjoe-z** [comment]
Same problem here
<img width="901" alt="image" src="https://github.com/user-attachments/assets/2b37b91b-dd61-4bc6-8611-3c5a8b4f35d3">

**Comment by pphoto808** [comment]
> BTW, this is running under `--cpu` mode. Apple M1 Pro, macOS 14.5 <img alt="image" width="1511" src="https://private-user-images.githubusercontent.com/7589350/369745455-ab8bb2c1-8417-4e5e-af1e-f7650889d8ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNjQ1NjIsIm5iZiI6MTcyNzA2NDI2MiwicGF0aCI6Ii83NTg5MzUwLzM2OTc0NTQ1NS1hYjhiYjJjMS04NDE3LTRlNWUtYWYxZS1mNzY1MDg4OWQ4ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMDQwNDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTRlYjkyOWRkNTAyNmQxNjQ0NzQ4Y2I4MzJjYWExNmI3NTM3YmEwZGIzZjY5YzNlMTRjMDE0ODY2MWQ4MTYxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2q3k9znhQ_IUFKNDoOJHYm9QqkKkiv9RnICLvunWVH8">

CPU?? At the cost of how much speed performance. That has to be much slower.

**Comment by JSoon** [comment]
> > BTW, this is running under `--cpu` mode. Apple M1 Pro, macOS 14.5 <img alt="image" width="1511" src="https://private-user-images.githubusercontent.com/7589350/369745455-ab8bb2c1-8417-4e5e-af1e-f7650889d8ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNjQ1NjIsIm5iZiI6MTcyNzA2NDI2MiwicGF0aCI6Ii83NTg5MzUwLzM2OTc0NTQ1NS1hYjhiYjJjMS04NDE3LTRlNWUtYWYxZS1mNzY1MDg4OWQ4ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMDQwNDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTRlYjkyOWRkNTAyNmQxNjQ0NzQ4Y2I4MzJjYWExNmI3NTM3YmEwZGIzZjY5YzNlMTRjMDE0ODY2MWQ4MTYxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2q3k9znhQ_IUFKNDoOJHYm9QqkKkiv9RnICLvunWVH8">
> 
> CPU?? At the cost of how much speed performance. That has to be much slower.

yep, using `--cpu` is a bad idea, just a comparison for this issue.

**Comment by RambleRainbow** [comment]
try the parameter  --force-upcast-attention

**Comment by pphoto808** [comment]
> try the parameter --force-upcast-attention

That was probably one of the first things i did lol
