### ISSUE TITLE
v0.2.2 without  workflow image export png ? 

### ISSUE THREAD

**Issue by zxy2020** [comfyanonymous/ComfyUI#5029]
### Your question

I  download the v0.2.2 [ComfyUI_windows_portable_nvidia.7z package  when run it 
I cant find the worflow image export/impot
the v0.2.2 
![image](https://github.com/user-attachments/assets/17c47c02-7103-4aef-8250-a06a40a83692)

the old version 
![image](https://github.com/user-attachments/assets/513b0e87-cb1d-4afe-91c6-33a278a9ab1f)

**Comment by ltdrdata** [comment]
It is not a feature of comfyui core.
This issue should be moved to ComfyUI-Custom-Scripts.

https://github.com/pythongosssss/ComfyUI-Custom-Scripts


Check if the custom node has been imported without any issues. If there are no problems, report this along with the browser error log
