### ISSUE TITLE
the connection lines of the workflow were displayed incorrectly

### ISSUE THREAD

**Issue by yatoubusha** [comfyanonymous/ComfyUI#5031]
I updated the latest Comfyui and when I reopened the page, I found that the connection lines of the workflow were displayed incorrectly
![image](https://github.com/user-attachments/assets/0dbfa2ee-6088-44d8-bbc2-0be83f3dedd3)

**Comment by liushh39** [comment]
how to solve it?

**Comment by mountlin** [comment]
The same problem occurred, it seems to be related to the zoom setting. My screen is set to zoom to 150%. When I zoom the page to 67% in the browser, it behaves correctly.

**Comment by ltdrdata** [comment]
If you have installed mixlab, then update it.

**Comment by yatoubusha** [comment]
> If you have installed mixlab, then update it.

Thank you very much. The issue was resolved after updating mixlab

**Comment by yatoubusha** [comment]
> how to solve it?

If you have installed mixlab, then update it.
