### ISSUE TITLE
Why does chaining models increase GPU memory usage?

### ISSUE THREAD

**Issue by educator-art** [comfyanonymous/ComfyUI#5032]
### Your question

Hello,

I learned that the ComfyUI team will have a meeting in Tokyo on September 27th (Friday). Unfortunately, I cannot attend, so I am posting this as feedback. I hope you enjoy Tokyo!

Question: 
In the ComfyUI flow, I connected the models in series.

I connected the first KSampler to VAE Decode and instead of outputting an image, I connected it to VAE Encode. Then, I connected the latent_image of the second KSampler to the VAE Encode, and when I output the image, I noticed an increase in GPU usage.

I assumed that once the first KSampler finished its output, it would no longer use GPU resources. Therefore, I thought the second KSampler would operate with a similar level of GPU usage. Is it possible to release GPU resources once each model has completed its output?

※ Sorry, This text uses a translation tool.

### Other

Usage Environment:
Google Colab Pro

**Comment by comfyanonymous** [comment]
ComfyUI will keep things in GPU memory as much as possible to speed up inference.

If you want it to free memory after every step you can use: --disable-smart-memory

**Comment by educator-art** [comment]
Thank you for your comment.
Your response helped deepen my understanding.
I didn’t know there was an option called "--disable-smart-memory." I apologize for the trouble.
Since I sometimes run out of VRAM on the T4 GPU, I’ll give it a try.

※ Sorry, This text uses a translation tool.
