### ISSUE TITLE
Embed comfyui on the website

### ISSUE THREAD

**Issue by jstit** [comfyanonymous/ComfyUI#5034]
### Your question

I want to embed comfyui into my website, just show the preview, it will look like this image, do you have any ideas on how to do it?
![image](https://github.com/user-attachments/assets/8d75ca5f-8859-49ad-9a62-07f482052a9b)

**Comment by Yasminebaby** [comment]
一个女孩穿着漂亮的公主裙在月亮下跳舞，心爱的男孩为她献上鲜花

**Comment by Yasminebaby** [comment]
小狗兔子蝴蝶都为他们在一起而感到开心
