### ISSUE TITLE
I'm running two installations of ComfyUI. One on port 8188 and one on port 8190. Specify 8190 but sends to 8188 anyway!

### ISSUE THREAD

**Issue by jdc4429** [comfyanonymous/ComfyUI#5043]
### Your question

I'm running two installations of ComfyUI. One on port 8188 and one on port 8190. Specify 8190 through API but sends to 8188 anyway!  How do I get it to go to 8190??? 

I tried to figure it out.  But still can't get it to work. Something like this?

server_address = "127.0.0.1:8190"
client_id = str(uuid.uuid4())
url = f"https://{server_address}"
headers = {"Client-Id": client_id}
response = requests.get(url, headers=headers)

def queue_prompt(prompt):
    p = {"prompt": prompt, "client_id": client_id}
    data = json.dumps(p).encode('utf-8')
    headers = {"Host": "localhost:8190"}
    req = urllib.request.Request("http://{}/prompt".format(server_address), data=data, headers=headers)
    return json.loads(urllib.request.urlopen(req).read())

**Comment by robinjhuang** [comment]
You are using a python script to call the API to hit `localhost:8190`?

I modified your script a bit and was not able to reproduce. 

```
import uuid
import json
import requests

server_address = "127.0.0.1:8190"
client_id = str(uuid.uuid4())
headers = {"Client-Id": client_id}

def queue_prompt(prompt: str):
    p = {"prompt": prompt, "client_id": client_id}
    data = json.dumps(p).encode('utf-8')
    headers = {"Content-Type": "application/json"}
    url = f"http://{server_address}/prompt"
    req = requests.post(url, data=data, headers=headers)
    req.raise_for_status()  # Raise an exception for HTTP errors
    return req.json()


queue_prompt("a beautiful landscape with a river and mountains")

```

To start the servers I did: 

`python main.py --port=8190`

`python main.py` which starts it on 8188. 

Can you provide more details?

**Comment by jdc4429** [comment]
The problem is.. I can make all these scripts to run the API and run from command line without any issue.  It will go to port 8190.  BUT if I try and run the same python script after clicking a button on my website, it sends to my comfy API running on 8188 even though I specify 8190!  It's so agravating since it's preventing me from running Flux on my second card (P40).  It seems no matter what I do, if it's executed from the website, it won't go to 8190!

**Comment by pyoliu** [comment]
me too!

**Comment by pyoliu** [comment]
> 我也是！

And I can't open the 8188 port webpage, it keeps spinning. Is there any solution?

**Comment by jdc4429** [comment]
I even tried doing it by creating my own server which checks to see if a file is present and if so the server executes the command so it's not going through my website.. but it's still going to 8188 and not 8190 like I specified.  I don't understand why it does this when it works if I do it manually with the script from a cmd prompt.

**Comment by jdc4429** [comment]
The only way I found around this (I'm no expert though) was to create a trigger file and have my chat server watch and if the file appears to call the bat file.  It works and so far the only way I found around the issue of going to the wrong API port.

**Comment by jdc4429** [comment]
Will use my method as it works and nobody seems to be able to explain the weird behavior.

**Comment by jdc4429** [comment]
I made a workaround using a created file with the prompt to trigger another server to execute the commands via a bat file when the file was detected.  You can now generate with Flux as well as SDXL Lightning. https://AiImageCentral.com
