### ISSUE TITLE
Start the ComfyUI webpage with the command line and load a specific workflow.

### ISSUE THREAD

**Issue by difsch2077** [comfyanonymous/ComfyUI#5044]
### Feature Idea

I am developing a software that will display all workflow.json files in the directory tree of the path "ComfyUI_windows_portable\ComfyUI\user\default\workflows".

I want to click on a workflow.json file to open the ComfyUI webpage and load that specific workflow.json file.

**Comment by difsch2077** [comment]
![Uploading image.png…]()
I am trying to set workflow file in front-end.

**Comment by difsch2077** [comment]
I found the solution:

await webviewElem.executeJavaScript(
          `window.comfyAPI.app.app.workflowManager.setWorkflow('workflow.json')`
)

**Comment by Yu-SKun** [comment]
How is this command implemented
