### ISSUE TITLE
Replace `websocket-client` with popular `websockets` lib

### ISSUE THREAD

**Issue by afiaka87** [comfyanonymous/ComfyUI#5047]
### Feature Idea

In https://github.com/comfyanonymous/ComfyUI/blob/fdf37566ef7f636387aa5fc887030e454bf2d836/script_examples/websockets_api_example_ws_images.py#L4

You are using a custom websocket repository that I am personally not familiar with. This has caused some confusion for me and perhaps for others. I'm curious, why use this library when the `websockets` (plural) package is available and more commonly used? The former repo being used is a typo collision with the latter suggested `websockets` (again, **plural**, just to make sure it's clear). This seems like it might be a pain point for anyone trying to learn how to use ComfyUI programmatically.

Would you be open to a rewrite of these scripts? It's possible I could dedicate some time of my own to this effort but only if it's likely to be merged in. 

Thanks!

edit: Softened some language

**Comment by comfyanonymous** [comment]
I don't remember why I picked that one but these are just examples and the websockets library doesn't seem to be much more popular (5.2k stars vs 3.6k stars on github for websocket-client).

**Comment by afiaka87** [comment]
Fair enough.
