### ISSUE TITLE
[Feature request] Clone should preserve connections

### ISSUE THREAD

**Issue by morphles** [comfyanonymous/ComfyUI#505]
Clone now just clones node, which is of extremely limited utility (at least if viewed as "work saving tool"), it is especially annoying when you are cloning cluster of nodes, since you want to have a variation with one param or input changed (think maybe all same pipe but passed through lora). But you get to redo all internal routing of cluster, and also try to scramble for whatever far away connections you have coming into it.

**Comment by comfyanonymous** [comment]
Try the copy/paste keyboard shortcuts: https://github.com/comfyanonymous/ComfyUI#shortcuts

There's also the: select a bunch of nodes -> right click canvas -> save selected as template.

**Comment by morphles** [comment]
Thanks!, missed that.
