### ISSUE TITLE
Flux embedding loading

### ISSUE THREAD

**Issue by aiXander** [comfyanonymous/ComfyUI#5051]
### Feature Idea

Enable FLUX token embeddings (eg from textual_inversion) to be loaded by the CLIPTextEncode nodes.

### Existing Solutions

The primitives for this prob need to get added somwhere here:
https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/text_encoders/flux.py
https://github.com/comfyanonymous/ComfyUI/blob/fdf37566ef7f636387aa5fc887030e454bf2d836/comfy/sd.py#L403

### Other

I've checked, and loading an embedding into the CLIPTextEncodeFlux will actually inject that embedding into the token_id list for clip_l, but it wont do that for t5xxl (meaning it just regards `embeddings:your_embedding_name.safetensors` as actual text tokens instead of replacing it with the loaded embedding.)

**Comment by comfyanonymous** [comment]
Is it fixed now?

**Comment by aiXander** [comment]
Yup, thank you!
Fixed by 
https://github.com/comfyanonymous/ComfyUI/commit/bdd4a22a2edb20a6ee55fc4dab8ad18ab4ea5348
