### ISSUE TITLE
workflow stuck loading? 

### ISSUE THREAD

**Issue by spiritform** [comfyanonymous/ComfyUI#5055]
### Your question

i was wondering if there's a way to clear what workflow is being loaded when it boots up, for some reason i was working on workflow with dwpose and now i can't get past the loading workflow screen... just a spinning wheel forever.

**Comment by christian-byrne** [comment]
You can clear localstorage at chrome://settings/content/all?searchSubpage=localhost

If you don't want to reset all your settings, you can F12 > Sources Tab > Breakpoints > Pause on uncaught exceptions > F5 > Applications Tab > Click `Local storage` > click `http://localhost:8188` > Right click `workflow` in middle pane > Delete > repeat For the `Session storage`. It's necessary because the worklfow is saved on a 1s interval

**Comment by christian-byrne** [comment]
> a little confused by the second part...
> 
> do you mean delete these lines?
> ![2024-09-25 07_59_12-](https://github.com/user-attachments/assets/8af87f15-7d46-4293-a9e7-63413bae91d7)
> 
> 
> 

Yes. Delete the `workflow` line there and in session storage

**Comment by spiritform** [comment]
thanks for the quick reply... once it's deleted what to i do? when i restart it just does the same thing. 
![2024-09-25 08_12_20-](https://github.com/user-attachments/assets/1fd4265c-2c80-47c6-9b30-9d1c07a7d1ff)

**Comment by spiritform** [comment]
it's a bummer because i even reinstalled a copy of comfyui, but when i go to install the controlnet aux and run the node it just crashes my computer. was thinking it could be a windows portable version issue tho.

**Comment by spiritform** [comment]
yeah, i restarted the bat and it's just doing the same thing. probably a different issue not related to workflow. doesn't show anything now when i F12 it.
![2024-09-25 07_52_44-](https://github.com/user-attachments/assets/9a3d1e8c-d537-484a-8545-ae9480961409)

**Comment by christian-byrne** [comment]
You can probably find the problematic custom node in the console there. You can also post it here for help.

**Comment by spiritform** [comment]
ok, thanks...  i saved the log... there seems to be a lot of issues. 

index-Drc_oD2f.js:sourcemap:1253 ComfyUI Front-end version: 1.2.60
:8188/favicon.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui/widgethider.js Error: Extension named 'efficiency.widgethider' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at widgethider.js:605:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui-main/appearance.js Error: Extension named 'efficiency.appearance' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at appearance.js:99:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui-main/previewfix.js Error: Extension named 'efficiency.previewfix' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at previewfix.js:4:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui/gif_preview.js Error: Extension named 'efficiency.gif_preview' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at gif_preview.js:144:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui/node_options/swapSamplers.js Error: Extension named 'efficiency.SwapSamplers' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at swapSamplers.js:178:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui/seedcontrol.js Error: Extension named 'efficiency.seedcontrol' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at seedcontrol.js:212:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui/node_options/swapScripts.js Error: Extension named 'efficiency.SwapScripts' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at swapScripts.js:87:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui/node_options/addLinks.js Error: Extension named 'efficiency.addLinks' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at addLinks.js:159:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui-main/node_options/addScripts.js Error: Extension named 'efficiency.addScripts' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at addScripts.js:138:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui-main/node_options/modelInfo.js Error: Extension named 'efficiency.ModelInfo' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at modelInfo.js:268:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui-main/node_options/swapLoaders.js Error: Extension named 'efficiency.SwapLoaders' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at swapLoaders.js:122:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui-main/node_options/swapXYinputs.js Error: Extension named 'efficiency.swapXYinputs' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at swapXYinputs.js:85:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui-main/node_options/addXYinputs.js Error: Extension named 'efficiency.addXYinputs' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at addXYinputs.js:71:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui-main/node_options/setResolution.js Error: Extension named 'efficiency.SetResolution' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at setResolution.js:75:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/efficiency-nodes-comfyui-main/workflowfix.js Error: Extension named 'efficiency.WorkflowFix' already registered.
    at ComfyApp.registerExtension (index-Drc_oD2f.js:sourcemap:82503:13)
    at workflowfix.js:142:5
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
:8188/extensions/ComfyUI-Crystools/comfy/index.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/ComfyUI-Crystools/common.js TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/ComfyUI-Crystools/common.js
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/ComfyUI-Crystools/extensions.js TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/ComfyUI-Crystools/extensions.js
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/ComfyUI-Crystools/monitor.js TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/ComfyUI-Crystools/monitor.js
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/ComfyUI-Crystools/progressBar.js TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/ComfyUI-Crystools/progressBar.js
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
index-Drc_oD2f.js:sourcemap:81590 Error loading extension /extensions/ComfyUI-Crystools/debugger.js TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/ComfyUI-Crystools/debugger.js
(anonymous) @ index-Drc_oD2f.js:sourcemap:81590
:8188/extensions/ComfyUI-Crystools/monitorUI.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/extensions/ComfyUI-Crystools/styles.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/extensions/ComfyUI-Crystools/utils.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/extensions/ComfyUI-Crystools/progressBarUIBase.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/extensions/ComfyUI-Crystools/progressBarUI.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
checkVersion_mixlab.js:12 Latest release version: v0.42.0

**Comment by spiritform** [comment]
maybe i should remove "efficiency-nodes-comfyui-main" i have a efficiency-nodes-comfyui folder already.. hm

**Comment by spiritform** [comment]
i think i'm just going to try to figure out the other issue with the fresh install... every time it hits the aio aux preprocessor node, it restarts my computer.

**Comment by sanebg** [comment]
I'm having the same issue since the last ComfyUI update. I can no longer load any workflows, anything is just stuck. I've tried different browsers, clearing cache and what not,

**Comment by christian-byrne** [comment]
It's probably a separate issue unless your logs are the same. Post a new issue with logs and someone may help.

**Comment by ltdrdata** [comment]
This issue appears to be caused by a conflict with a custom node, so I am closing it.
