### ISSUE TITLE
can't pick flux1-dev-fp1.safetensors in "load checkpoint" node.

### ISSUE THREAD

**Issue by margo2130** [comfyanonymous/ComfyUI#5056]
### Your question

hi,
i want to pick "flux1-dev-fp1.safetensors " in load checkpoint node like picture below:
picture 1:
![1](https://github.com/user-attachments/assets/b7b1ec38-303b-4a06-9d7d-34cdd6840fa8)

but i can't pick that "flux1-dev-fp1.safetensors ", there is no such this thing. there is only "flux-dev1-bnb-nf4...".
![2](https://github.com/user-attachments/assets/2d6d6492-0dcc-4725-a118-33aee5136266)

how should i pick that.
some one said you should use "load diffusion model" node.
![3](https://github.com/user-attachments/assets/9dc568dd-b547-4133-a3aa-b051fa3ddd3b)

but this node hasn't clip and vae like picture 1.

**Comment by JorgeR81** [comment]
To use the `Load Checkpoint` node, you need this model. 

https://huggingface.co/Comfy-Org/flux1-dev/tree/main

This is a 17 GB model, which means it includes the Flux weights ( in FP8 ) and also the CLIP and VAE for flux.

---

The smaller models ( 11 GB ) only have the Flux weights in FP8.
The larger ones ( 22 GB ) are also only Flux weights, but in FP16 format.

For them you need to use the `Load Diffusion Model` node.
But you also need to use the `Dual Clip Loader` and `Load VAE` nodes ( see image ).

The advantage of loading the models separately, is that you can save SSD space, if you use multiple models. 
Most 17 GB Flux models, on civitai include the exact same T5 encoder, in FP8 ( about 5 GB )

You have links to the models, in the examples page:
https://comfyanonymous.github.io/ComfyUI_examples/flux/#files-to-download-for-the-regular-version

![loaders](https://github.com/user-attachments/assets/b86da482-fbe6-4275-9166-158aa1c695a0)

**Comment by JorgeR81** [comment]
By the way, if you have used the NF4 models, you may also be interested in GGUF models. 
https://github.com/city96/ComfyUI-GGUF

**Comment by margo2130** [comment]
> Just to clarify, your NF4 model is also about 11.5 ~ 12 GB, because it includes Flux weights in the NF4 format + CLIP + VAE. The NF4 format is smaller than FP8, so it makes up the difference. https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/tree/main
> 
> By the way, if you have used the NF4 models, you may also be interested in GGUF models ( e.g.: Q4_K_S / Q6_K / Q8_0 /... ) Depending on the model, they are also smaller than FP8 / PF16, and may have better quality than NF4 / FP8. https://github.com/city96/ComfyUI-GGUF

thank you brother.
i have another problem in comfy ui. i am trying to extend image with this method.
https://openart.ai/workflows/myaiforce/flux-outpaint-pro/M3OEFh46Ojtb6RcdOCsI

the problem is when i generate, it stuck in KSAMPLER node and give me this error:
ksampler 'noneType' object has no attribute 'shape'.

![image](https://github.com/user-attachments/assets/56a46033-6dba-411d-99d5-38eafec388ef)

**Comment by JorgeR81** [comment]
> the problem is when i generate, it stuck in KSAMPLER node and give me this error:
> ksampler 'noneType' object has no attribute 'shape'.

The issue is in the SDXL_Outpaint group, right ?

Try bypassing the ControlNet node and see if the KSampler works.

If so, try the new ControlNet node.

It has an optional VAE input, but that's only needed for Flux models. 
I think the older `Apply ControlNet` nodes were deprecated.
 
 If this does not work, I may need to open a new issue for this.

![cnet](https://github.com/user-attachments/assets/b460b77b-ef91-4b1a-aef5-6d7d3749f0a7)

**Comment by margo2130** [comment]
> > the problem is when i generate, it stuck in KSAMPLER node and give me this error:
> > ksampler 'noneType' object has no attribute 'shape'.
> 
> The issue is in the SDXL_Outpaint group, right ?
> 
> Try bypassing the ControlNet node and see if the KSampler works.
> 
> If so, try the new ControlNet node.
> 
> It has an optional VAE input, but that's only needed for Flux models. I think the older `Apply ControlNet` nodes were deprecated.
> 
> If this does not work, I may need to open a new issue for this.
> 
> ![cnet](https://private-user-images.githubusercontent.com/72734038/370712065-b460b77b-ef91-4b1a-aef5-6d7d3749f0a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzA1NDMsIm5iZiI6MTcyNzI3MDI0MywicGF0aCI6Ii83MjczNDAzOC8zNzA3MTIwNjUtYjQ2MGI3N2ItZWY5MS00YjFhLWFlZjUtNmQ3ZDM3NDlmMGE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDEzMTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZDlmYzQ0NDc4YzdlMjdkYzYwMzFhYThmNmE0ZmM0Nzg2MDY5MmE3NDIxNzM3ODlmMGVmMTAxNzU4MzgxYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2gN-bIwT3iIlF6rcfyuDGgYWJVO2ZF3t0Lhtt7Vxlec)

Thank you.
Yes in SDXL_OUTPUTPANTING.

i bypass ControlNet node and "VAE Deocde" is red now.
![image](https://github.com/user-attachments/assets/a48ad208-99f4-480b-ac26-6e65affc4be1)

i change ControlNet node to "apply controlnet" with the node in picture you sent.
that is correct now. but the "VAE Deocde" is red now. i bypass it then in "Restore detail" group the "LayerColor: AutoAdjust V2" node is red not.
![image](https://github.com/user-attachments/assets/f1f53fbc-db5c-4322-86aa-c0aa8ac4819b)

i am so tired of these errors in row. i just wanted a simple tutorial for extend image. maybe i should ignore this tutorial.

**Comment by JorgeR81** [comment]
The red line around the node + the red circle around the input connection means the node is missing an input.

I think you need to connect the `KSampler` ( `LATENT` output) to the `Vae Decode` node ( `samples` input ).

Without this, the `Vae Decode` node cannot produce an image to feed the `LayerColor` node.

**Comment by margo2130** [comment]
> The red line around the node + the red circle around the input connection means the node is missing an input.
> 
> I think you need to connect the `KSampler` ( `LATENT` output) to the `Vae Decode` node ( `samples` input ).
> 
> Without this, the `Vae Decode` node cannot produce an image to feed the `LayerColor` node.

Thank you so much.
well i re run the workflow from creator and with a little change it work until "Flux_Repaint" group.

but in this group i get an error when i get into "KSampler" node :
#### It seems that models and clips are mixed and interconnected between SDXL Base, SDXL Refiner, SD1.x, and SD2.x. Please verify. ####

i think if i can solve this problem, i can fully use this extend. btw till group 3 i get extended image but by doing group 3 and 4, i can make hand natural.

my workflow: https://easyupload.io/lbe7m0

**Comment by margo2130** [comment]
> > The red line around the node + the red circle around the input connection means the node is missing an input.
> > I think you need to connect the `KSampler` ( `LATENT` output) to the `Vae Decode` node ( `samples` input ).
> > Without this, the `Vae Decode` node cannot produce an image to feed the `LayerColor` node.
> 
> Thank you so much. well i re run the workflow from creator and with a little change it work until "Flux_Repaint" group.
> 
> but in this group i get an error when i get into "KSampler" node :
> #### It seems that models and clips are mixed and interconnected between SDXL Base, SDXL Refiner, SD1.x, and SD2.x. Please verify.
> 
> i think if i can solve this problem, i can fully use this extend. btw till group 3 i get extended image but by doing group 3 and 4, i can make hand natural.
> 
> my workflow: https://easyupload.io/lbe7m0

i think i need the correct clip file for my " [flux1-dev-fp8.safetensors](https://huggingface.co/Kijai/flux-fp8/tree/main)".
do you know where is the clip file for it?

**Comment by JorgeR81** [comment]
Flux uses 2 text encoders: the T5 and the Clip L
So you need to use the `Dual Clip Loader` ( see the image on my first post ).

You can get text encoders here:
https://huggingface.co/comfyanonymous/flux_text_encoders/blob/main/clip_l.safetensors
https://huggingface.co/comfyanonymous/flux_text_encoders/blob/main/t5xxl_fp8_e4m3fn.safetensors

And the Flux vae ("ae") here:
https://huggingface.co/black-forest-labs/FLUX.1-schnell/blob/main/ae.safetensors

**Comment by margo2130** [comment]
> Flux uses 2 text encoders: the T5 and the Clip L So you need to use the `Dual Clip Loader` ( see the image on my first post ).
> 
> You can get text encoders here: https://huggingface.co/comfyanonymous/flux_text_encoders/blob/main/clip_l.safetensors https://huggingface.co/comfyanonymous/flux_text_encoders/blob/main/t5xxl_fp8_e4m3fn.safetensors
> 
> And the Flux vae ("ae") here: https://huggingface.co/black-forest-labs/FLUX.1-schnell/blob/main/ae.safetensors

finally i could solve all of it.
thank you so much.
this is the change should i do as you said.
![image](https://github.com/user-attachments/assets/32d2ba9a-40c2-4a1e-8582-9f133807d36e)

thank you all. if anyone couldn't pick "flux1-dev-fp8.safetensors" in "load checkpoint" node, he should put the nodes based the picture up.
