### ISSUE TITLE
Export png screenshot image missing background on lower right

### ISSUE THREAD

**Issue by 1038lab** [comfyanonymous/ComfyUI#5058]
### Expected Behavior

when export screenshot as png image, it's background on lower right

### Actual Behavior

when export screenshot as png image, it's background on lower right
![workflow](https://github.com/user-attachments/assets/7ed47c2f-c964-4486-92b1-e9da7773c8c7)

### Steps to Reproduce

it happen any workflow, i just use d
![workflow](https://github.com/user-attachments/assets/afef3cac-8e0d-42c3-97e5-a8ad3a57315a)
efault workflow as example

### Debug Logs

```powershell
no error output just incorrect image output
```

**Comment by ltdrdata** [comment]
That feature belongs to ComfyUI-Custom-Scripts.

https://github.com/pythongosssss/ComfyUI-Custom-Scripts
