### ISSUE TITLE
need help，My computer comfyui running error

### ISSUE THREAD

**Issue by DONGSHUIYANG** [comfyanonymous/ComfyUI#5060]
### Your question

The first time I installed comfyui, it worked normally, but after reinstalling the system for some reason, a running error occurred. Specifically, it crashes as soon as it starts running and shows that it is reconnecting.I hope someone can help me deal with related issues, thank you very much.
![1](https://github.com/user-attachments/assets/8aa15811-80d9-4b6b-8798-800075c9eed9)
![2](https://github.com/user-attachments/assets/06e63b25-20a3-42c6-9635-11d4ad17e216)
[Diagnostics-1727283583.log](https://github.com/user-attachments/files/17135323/Diagnostics-1727283583.log)

**Comment by ltdrdata** [comment]
What is your workflow?

**Comment by DONGSHUIYANG** [comment]
> What is your workflow?

Generate pictures from text，Workflow as the document
[flux1-schnell.json](https://github.com/user-attachments/files/17141798/flux1-schnell.json)

**Comment by ltdrdata** [comment]
Have you tested without the LoRA?
