### ISSUE TITLE
VAEEncode division by zero

### ISSUE THREAD

**Issue by oolongmi** [comfyanonymous/ComfyUI#5069]

**Comment by oolongmi** [comment]
So how should I fix this, many thanks T_T

**Comment by ltdrdata** [comment]
There is no information in your issue report.
Please upload the workflow and full logs.

**Comment by niyonghui** [comment]
<img width="1195" alt="图片" src="https://github.com/user-attachments/assets/b77085cc-8937-45c5-b3b3-1abc4d7a90f9">

I had the same problem

**Comment by ltdrdata** [comment]
> <img alt="图片" width="1195" src="https://private-user-images.githubusercontent.com/12841686/372037412-b77085cc-8937-45c5-b3b3-1abc4d7a90f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzE4NDIsIm5iZiI6MTcyODUzMTU0MiwicGF0aCI6Ii8xMjg0MTY4Ni8zNzIwMzc0MTItYjc3MDg1Y2MtODkzNy00NWM1LWIzYjMtMWFiYzRkN2E5MGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAzMzkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YmRjMGFmMjJmNTk5NTA3ZTg0MTRjMmJjNjNmZDllNmJiNDE2ZDgxODJkMjI4N2NlZDVmOTJkYmU2YTQ4OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2XoEnnuuvA0BUAzccSKyKCYVhfGkamha2ggls8-Bgx8">
> I had the same problem

This is patched.

**Comment by LsZiChen** [comment]
The Late input result is incorrect, the divisor is 0

**Comment by ltdrdata** [comment]
> The Late input result is incorrect, the divisor is 0

That is patched already.

https://github.com/comfyanonymous/ComfyUI/pull/5121

**Comment by yarikmoscow** [comment]
just make CROP - DISABLED in LTXV Base Sampler node
