### ISSUE TITLE
The new apply controlnet node

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#5070]
### Your question

Is these 2 the only existing Apply ControlNet nodes?

![image](https://github.com/user-attachments/assets/b8a57871-09a1-412d-9d54-79c4fa29cbea)

1. Apply ControlNet 
2. ControlNetInpaintingAliMamaApply

**Comment by JorgeR81** [comment]
You can get the old ones ( deprecated ) via the right click menu.

![cn](https://github.com/user-attachments/assets/4d38083d-1f12-4301-b633-e3547bf59889)

---

But in the new `Apply ControlNet` node, the VAE input is optional, so it should work for both SD1.5 / SDXL ( without VAE ) as well as SD3 / Flux ( with VAE ). 
In the latest Frontend version, we can already see the red input has a hole in this node, signaling that this input is optional.

![cn1](https://github.com/user-attachments/assets/c7ab9985-b0b3-4b6e-a0be-8d8dd010bec6)

**Comment by JorgeR81** [comment]
By the way, where did you get that `Set Shakker Labs Union ControlNet type` node ?

Is that from a custom node suite ?

**Comment by pandayummy** [comment]
Thank you.
I didn't use that [Set Shakker Labs Union ControlNet type] node.
The old  SetUnionControlNetType node works great for depth and canny/lineart.

![image](https://github.com/user-attachments/assets/7ee3e8e8-d969-4601-bf6b-535df5f8fb5a)

**Comment by JorgeR81** [comment]
The final image may look good, but the ControlNet is probably not operating in the "depth" mode.
I think the Union ControlNets, just use the "number" of the option, not the "words", as input.

The old `SetUnionControlNetType` is for SDXL ControlNet.
But the Flux ControlNet, from Shakker AI, has the options in a different order ( see the issue I mentioned above ).

I think this `Set Shakker Labs Union ControlNet` node , is just outputting a number ( like `SetUnionControlNetType` ), but it has the options labeled in the correct order.

**Comment by pandayummy** [comment]
oh, never noticed that. I always use depth and canny together...
I just realised that the output image is not 3D style, not enough depth, will switch to _Set Shakker Labs Union ControlNet type_
