### ISSUE TITLE
Would it be possible to reference a CustomNode instance and change the output?

### ISSUE THREAD

**Issue by educator-art** [comfyanonymous/ComfyUI#5072]
### Your question

Hello,

I am trying to create a CustomNode that reads the DirectoryPath.
The function takes the index of the image file and increments it so that a different file is output each time.

What I've tried: 
I run the Prompt Queue.
the first time, it creates an instance of the CustomNode and outputs it.
but from the second time onwards, it appears to reference the same file. 

Also, I saw "is_changed" in example_node.py.example.
https://github.com/comfyanonymous/ComfyUI/blob/master/custom_nodes/example_node.py.example
and I looked at the load_image example, 
However, it seemed to me that it was being used for a different purpose.

As a result, I determined that ComfyUI explicitly asks for user input.

Question:
Would it be possible to reference a CustomNode instance and change the output?

※ Sorry, This text uses a translation tool.

**Comment by educator-art** [comment]
Since then, I've been thinking about this in consultation with Google Search, GPT, and Claude, and I thought that allowing the concept of cycles in ComfyUI would create a contradiction. 

I'd like to try creating a static CustomNode for ComfyUI and consider a different approach.

**Comment by christian-byrne** [comment]
You may consult https://docs.comfy.org/essentials/custom_node_server_overview#is-changed

From that link:

> To specify that your node should always be considered to have changed (which you should avoid if possible, since it stops Comfy optimising what gets run), `return float("NaN")`. This returns a NaN value, which is not equal to anything, even another NaN.

**Comment by educator-art** [comment]
Thank you for the link and quote for the "is_changed" function.
While referring to this information, i can do what i want to do in a different way.
※ Sorry, This text uses a translation tool.

**Comment by educator-art** [comment]
The other day, I was able to automate it using the API for the [Custom Node](https://github.com/educator-art/ComfyUI-Load-DirectoryFiles) I created. Thank you very much.
※ Sorry, This text uses a translation tool.

**Comment by christian-byrne** [comment]
Very nice. I can also iterate through the folder while using it in the UI

![Selection_469](https://github.com/user-attachments/assets/c6d82022-52b1-4161-9986-dee17e8d7191)
