### ISSUE TITLE
Queue Button Problem ! 

### ISSUE THREAD

**Issue by GreyHound55** [comfyanonymous/ComfyUI#5074]
### Expected Behavior

The Queue Button with the new UI was in the top-right. A perfect spot for it ! 

### Actual Behavior

Workspace real estate is at a premium. Updated ComfyUI today and now ... The Queue Button is situated at the lower-center of the window. On top of the Workflow. Blocking a portion of the Workflow. That section of Workflow is no longer visible ! 

I have to admit, whoever dreamed this up and implemented it, thought they were making an improvement. But in reality, this was a really DUMB idea. 

Please make this block DRAG'ABLE and the ability to REPOSITION. Again, Workflow Space is at a PREMIUM !!! 

### Steps to Reproduce

Today's (Sept 27, 2024) Update

This is bad ... It's not a Bug ... It's someone's pipe dream of an improvement. Again, extremely Dumb ! 

### Debug Logs

```powershell
N/A
```

### Other

"Other" , again ... Dumb ... Did the Designer bounce this off anyone else ?????

**Comment by ltdrdata** [comment]
Please move this issue to the front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
