### ISSUE TITLE
I can't open the UI

### ISSUE THREAD

**Issue by pyhint** [comfyanonymous/ComfyUI#5076]
### Your question

I need help! This is my first time encountering this. After downloading and running it, I got this and can’t enter the UI. How should I solve this problem?By the way, my operating system is Windows 7
![1727422046636](https://github.com/user-attachments/assets/82e1fc5c-c233-486a-a054-2b3a4b0a6960)

**Comment by pyhint** [comment]
> PYTHONPATH 或 PYTHONHOME 环境变量是否偶然设置？ 如果是这样，请尝试删除它们并重试。
> 
> https://stackoverflow.com/questions/65184937/fatal-python-error-init-fs-encoding-failed-to-get-the-python-codec-of-the-file

I don't know, I got this error after downloading the built-in UI runtime environment and running it.
In fact, I don't understand this at all, but following these steps still didn't solve the problem.
![7a9e791f264805163892242e0127fec](https://github.com/user-attachments/assets/5af6a5e3-bd52-4562-9acd-5bc7a34b9a24)
![ef297824611040703c0077083fd925e](https://github.com/user-attachments/assets/f03853d4-1b8a-4f2c-bcb8-0325281f5430)

**Comment by ltdrdata** [comment]
If the provided solution doesn't work, we currently don't know a solution for this issue.
However, you can try the following:

1. If Python is already installed on Windows, try uninstalling it and attempt again
2. Try using venv instead of portable version.
    - This means reinstall `Python` and try setting up the `venv` environment directly
