### ISSUE TITLE
Black channel was removed from image to mask node

### ISSUE THREAD

**Issue by tzekeong** [comfyanonymous/ComfyUI#508]
Black channel was removed from image to mask node since recent update.

**Comment by comfyanonymous** [comment]
Do you mean the "Convert Image to Mask" node that was added yesterday to master?

**Comment by tzekeong** [comment]
yes

**Comment by comfyanonymous** [comment]
I'm not sure I understand can you give me an example?

**Comment by tzekeong** [comment]
![IMG_20230415_115941](https://user-images.githubusercontent.com/81726140/232181888-0484332c-143d-4759-9a14-8ef72a592fd9.jpg)
The channel used to have red blue green and black.

**Comment by missionfloyd** [comment]
There isn't a black channel. You mean alpha? These images don't have alpha channels.

**Comment by tzekeong** [comment]
![IMG_20230415_141321](https://user-images.githubusercontent.com/81726140/232190114-f4f71732-1482-471a-a8c7-39ca2a6225fd.jpg)
I used a depth approximation to generate a greyscale image and threshold it to bnw as a mask. Previously there is a black channel (or alpha), but it was removed after previous update. Is there any way that I can continue with the scenario?

**Comment by missionfloyd** [comment]
With grayscale images, the red, green, and blue channels are all the same, so it doesn't matter which one you choose.

**Comment by tzekeong** [comment]
Apparently, I messed up with the masking color, just need to invert the mask to make it work 😅
