### ISSUE TITLE
Support for jasperai ControlNets ( Flux )

### ISSUE THREAD

**Issue by JorgeR81** [comfyanonymous/ComfyUI#5087]
### Feature Idea

Some new Flux ControlNets just came out :

https://huggingface.co/jasperai/Flux.1-dev-Controlnet-Depth
https://huggingface.co/jasperai/Flux.1-dev-Controlnet-Upscaler
https://huggingface.co/jasperai/Flux.1-dev-Controlnet-Surface-Normals

**Comment by comfyanonymous** [comment]
As far as I know those always worked.

**Comment by JorgeR81** [comment]
Ah, yes ! I noticed it's already included it's in some Comfy UI upscaling workflows:

https://www.reddit.com/r/FluxAI/comments/1fsqtm8/flux_scifi_enhance_upscale_workflow_included/
https://github.com/dicksondickson/dickson-sci-fi-enhance-upscale
