### ISSUE TITLE
Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install accelerate`

### ISSUE THREAD

**Issue by margo2130** [comfyanonymous/ComfyUI#5089]
### Your question

hi every one.
what should i do for this error:
Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install accelerate`

i get this error from "DownloadAndLoadFlorence2Model" node. 
my workflow
[11111.json](https://github.com/user-attachments/files/17173526/11111.json)

**Comment by ltdrdata** [comment]
Please move this issue to the related repo.
https://github.com/kijai/ComfyUI-Florence2
