### ISSUE TITLE
addmm_cuda" not implemented for 'Float8_e4m3fn

### ISSUE THREAD

**Issue by Orenji-Tangerine** [comfyanonymous/ComfyUI#5090]
### Expected Behavior

When I load a LoRA in inferencing wih Flux fp8, the following will happen
1. Batch size of 1, no error
2. Batch size of 2, no error
3. Batch size of 3, this error only, about 20 lines of the same error: ERROR lora diffusion_model.double_blocks.0.img_attn.proj.weight "addmm_cuda" not implemented for 'Float8_e4m3fn'

![image](https://github.com/user-attachments/assets/eb51b6b4-17d5-4c00-bec1-1e7f882a0469)

4. Batch size of 4, repeated loop of error from blocks 0 to 18 (the figure 0 below loops from 0 to 18, and for about 20 of the same loop, refers to the diagnostic:
ERROR lora diffusion_model.double_blocks.0.img_attn.qkv.weight "addmm_cuda" not implemented for 'Float8_e4m3fn'
ERROR lora diffusion_model.double_blocks.0.txt_attn.qkv.weight "addmm_cuda" not implemented for 'Float8_e4m3fn'
ERROR lora diffusion_model.double_blocks.0.img_attn.proj.weight "addmm_cuda" not implemented for 'Float8_e4m3fn'
ERROR lora diffusion_model.double_blocks.0.txt_attn.proj.weight "addmm_cuda" not implemented for 'Float8_e4m3fn'

![image](https://github.com/user-attachments/assets/cf78c98e-ab03-46f7-8deb-fe891cb726a8)

Environment: Pytorch 2.4.1 + CU 12.4
[Diagnostics-1727507072.log](https://github.com/user-attachments/files/17173557/Diagnostics-1727507072.log)

### Actual Behavior

Error as per above and attached.

### Steps to Reproduce

Error as per above and attached.

### Debug Logs

```powershell
Error as per above and attached.
```

**Comment by comfyanonymous** [comment]
Should be fixed now.

**Comment by Orenji-Tangerine** [comment]
Yes, it is fixed. Thanks for your amazing works 😍😍

On a side note, just notice it is #5090 
![image](https://github.com/user-attachments/assets/4a510016-70f1-4068-8b14-320bb2c2f650)
