### ISSUE TITLE
first test, blurry output 

### ISSUE THREAD

**Issue by zz64** [comfyanonymous/ComfyUI#5091]
### Your question

Hi,
Is it normal that I get blurry output?
![20240928_09-59-46](https://github.com/user-attachments/assets/291af8cb-f9cc-4016-a8fa-c5647a7571ea)

Thanks.

### Logs

```powershell
lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 4777.53759765625 True
Requested to load Flux
Loading 1 new model
loaded partially 6216.98701171875 6215.712951660156 0
```

### Other

Total VRAM 8113 MB, total RAM 32060 MB
pytorch version: 2.6.0.dev20240919+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 980M : native

**Comment by patientx** [comment]
you are using dev and only 8 steps,if you doing it because it takes too much  try using schnell with the same settings and you'll get good results. Or some hybrid model.

**Comment by Kittusirkh** [comment]
I am trying pensive load model in comfy 

model - https://huggingface.co/enhanceaiteam/MidFlow/resolve/main/midflow.safetensors
clip_l - https://huggingface.co/enhanceaiteam/MidFlow/resolve/main/clip/clip_l.safetensors
Vae/Autoencoder - https://huggingface.co/enhanceaiteam/MidFlow/resolve/main/vae/vae.safetensors
T5xxl -  @https://huggingface.co/enhanceaiteam/MidFlow/resolve/main/text_encoder/t5xxl.safetensors

I failed raised_handsclap anyone help me

**Comment by JorgeR81** [comment]
In the Flux examples page you can download models and workflows:    

https://comfyanonymous.github.io/ComfyUI_examples/flux/

**Comment by freyandere** [comment]
Please lower cfg to 1, it's not supposed to be 8.
