### ISSUE TITLE
Is there a way to make certain custom node run in a dedicated python environment?

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#5092]
### Your question

I'm having difficulty installing this node:
https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait/blob/main/requirements.txt
```
numpy>=1.26.4
opencv-python-headless
imageio-ffmpeg>=0.5.1
lmdb>=1.4.1
timm>=1.0.7
rich>=13.7.1
albumentations>=1.4.10
ultralytics
tyro==0.8.5
dill
```

After installing, I got errors:
```
inference 0.20.1 has requirement rich<=13.5.2, but you have rich 13.8.1.
inference-cli 0.20.1 has requirement rich<=13.5.2, but you have rich 13.8.1.
inference-gpu 0.20.1 has requirement rich<=13.5.2, but you have rich 13.8.1.
```

inference is a very important module, I need to keep it working.

Is there a way to make ComfyUI-AdvancedLivePortrait  run in its own dedicated environment without affecting the global python env?

**Comment by Orenji-Tangerine** [comment]
Create an environment for your another ComfyUI n build from there, alternatively you may build a ComfyUI using the link below for launcher from Aki (Chinese interface but can change from the launcher itself). Do change the file download not from the mirror (China based) else you will experience slow download.

https://files.fm/u/wufx8d3vbe

**Comment by thecat99z** [comment]
try to update inference to the latest version 0.21.0 and see if it resolves the issue.

**pip install inference==0.21.0
pip install inference-cli==0.21.0
pip install inference-gpu==0.21.0**

**Comment by pandayummy** [comment]
thanks.
