### ISSUE TITLE
ComfyUI Display Scaling and Connection Line Issues on iPad via Screen Sharing

### ISSUE THREAD

**Issue by Killer-PD** [comfyanonymous/ComfyUI#5093]
### Your question

I'm experiencing a display issue with ComfyUI on my iPad when using screen sharing with my notebook. While the connections and nodes display correctly on my PC, they appear distorted and jumbled when viewed on the iPad screen. The connection lines between nodes are particularly problematic, making it difficult to understand the relationships between different elements. Could you please advise on how to resolve this cross-platform compatibility issue?

### Other

![PixPin_2024-09-28_20-33-18](https://github.com/user-attachments/assets/329a8a0e-862a-491f-90f3-41a39e196905)
![PixPin_2024-09-28_20-33-37](https://github.com/user-attachments/assets/96527f18-b806-48a5-bf06-4e4ea96dfe36)

**Comment by ParticleDog** [comment]
The same

**Comment by christian-byrne** [comment]
Update mixlab
