### ISSUE TITLE
The image preview window cannot stretch the size of the image

### ISSUE THREAD

**Issue by aiise117** [comfyanonymous/ComfyUI#5094]
### Your question

https://github.com/user-attachments/assets/5279cb8a-7f3e-410c-bfdc-027739b8693b

**Comment by ltdrdata** [comment]
The Image Preview does not enlarge beyond the original size. 
However, it's strange that it's not centered and sticks to the bottom.
Try disabling all custom nodes, refresh the browser, and then test it.

**Comment by aiise117** [comment]
Thank you for the prompt, the issue has been resolved. It is caused by the ComfyUI Custom Nodes node
