### ISSUE TITLE
 It seems that models and clips are mixed and interconnected between SDXL Base, SDXL Refiner, SD1.x, and SD2.x. Please verify. 

### ISSUE THREAD

**Issue by zhengzetao1** [comfyanonymous/ComfyUI#5098]
### Your question

[workflow (1).json](https://github.com/user-attachments/files/17177468/workflow.1.json)

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/4f458151-8759-4c36-abcf-af02ea039d90)

Literally you should not use SD1.5 controlnet for SDXL checkpoint.

**Comment by savitar07** [comment]
I have the same error but im using flux, and im sure everything in my workflow is flux based, i dont know why im getting the same error can you help me too. i will share the work flow here.
[flux-fp8-dev-Depth-error.json](https://github.com/user-attachments/files/17968211/flux-fp8-dev-Depth-error.json)
Thank you.

**Comment by ltdrdata** [comment]
There are no issues, at least when the workflow is configured in the active state.
![workflow (41)](https://github.com/user-attachments/assets/d26ce460-f132-4cdc-a874-d3d43956a192)

**Comment by savitar07** [comment]
Bro I swear to god, i was trying to make this work for 2 days, i tried to modify this workflow and make it work, 
Modified workflow : ![workflow Modified](https://github.com/user-attachments/assets/99666d15-af6c-4e7f-9e1c-3790ce08369b)
Original Workflow : ![workflow OG](https://github.com/user-attachments/assets/8d35f6b2-d94d-48cf-b8b9-c33e390ab224)
BUT BOTH OF THEM WORKS FINE NOW JUST AFTER YOUR REPLY I DONT KNOW HOW.

**Comment by ahrimanes** [comment]
I got the same error... i changed the lora to another lora executed then back the te original lora and worked!

**Comment by ltdrdata** [comment]
> I also encountered this problem, could you please tell me how to do it? Thanks！
> 
> ![Image](https://github.com/user-attachments/assets/90a0a861-51be-4572-96e9-7343a92e1fdf)
> 
> [image_to_video_wan_example.json](https://github.com/user-attachments/files/19849813/image_to_video_wan_example.json)

You have selected vae model instead of clip model in Load CLIP loader

wrong:
![Image](https://github.com/user-attachments/assets/3fcbb41d-9005-45c5-94fe-20dd5dece17f)

correct:
![Image](https://github.com/user-attachments/assets/4e4fc867-e4af-46bb-bb01-bcc41ade5394)

**Comment by jczhao2022-del** [comment]
![Image](https://github.com/user-attachments/assets/31d948e9-0f4c-4fae-ba4b-d9ab6cec830e)      I also encountered this problem, could you please tell me how to do it?
Thanks！
