### ISSUE TITLE
Anyone know how to use xinsir/controlnet-tile-sdxl-1.0?

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#5104]
### Your question

I know it might not be the right place to ask this question, but the huggingface forum just no infomation. So I come here to see if someone could share a workflow on
https://huggingface.co/xinsir/controlnet-tile-sdxl-1.0

![image](https://github.com/user-attachments/assets/4977ee42-9afb-4e3c-9d7d-ac2ba38d356e)

**Comment by raysers** [comment]
我推测你看得懂中文视频，因此给一个B站链接，关于xinsir的promax使用，tile版估计也差不多。链接：【Union模型发布ProMax版本，SDXL已成究极形态，xinsir剑指SD3控制之王-哔哩哔哩】 https://b23.tv/pI2aJlb

**Comment by pandayummy** [comment]
> Here's how I use it: [tiled-diffusion-example.json](https://github.com/user-attachments/files/17224617/tiled-diffusion-example.json)
> 
> Basic steps:
> 
> 1. Generate your image
> 2. Upscale it normally (model, lanczos, etc)
> 3. Apply TilePreprocessor to the full image before sending to the controlnet
> 4. Apply tile controlnet to the conditioning and preprocessed image
> 5. Apply TiledDiffusion (Mixture of Diffusers) to the model before sending it to the resampler
> 6. Tiled vae encode
> 7. Resample
> 8. Tiled vae decode
> 
> Things to know:
> 
> * This depends on custom nodes
>   
>   * [Tiled Diffusion & VAE for ComfyUI](https://github.com/shiimizu/ComfyUI-TiledDiffusion): VAEEncodeTiled_TiledDiffusion, TiledDiffusion, VAEDecodeTiled_TiledDiffusion
>   * [ComfyUI's ControlNet Auxiliary Preprocessors](https://github.com/Fannovel16/comfyui_controlnet_aux): TilePreprocessor
> * Adjust tile size on the encoder/decoder (bigger = more VRAM). Recreate the nodes to get defaults for your system (I think?)
> * You may need to mess with the Tiled Diffusion parameters too if VRAM is an issue
> * MultiDiffusion never worked for me, but Mixture of Diffusers did
> * It doesn't really matter if the seeds are the same or not
> * For denoise on the resampler, 0.5 is the highest I'll go. Otherwise it changes too much. I use multiple detailer and upscale passes, and for each pass I'll lower the denoise value as the image becomes larger and more refined. You should experiment with this value and find what works for you.
> 
> Hope that helps.
> 
> Edit: Clarification, forgot to mention tile preprocessor

Thank you for your detailed instructions. I have a new question now, the TilePreprocessor seems like image blur, what’s the point of blurring the input image if we’re going to use it to condition the image generation process?

**Comment by pandayummy** [comment]
So ControlNet tile is meant for detailing low resolution images.
We don't need any image preprocessor for the conditioning image unless the output being too sharp.
Cheers!

**Comment by alFrame** [comment]
What a great workflow! Thanks for that!

**Comment by alFrame** [comment]
Sorry for double posting... But a question arises.

Did you not connect the vae to the Apply ContolNet node on purpose?

<img width="420" height="416" alt="Image" src="https://github.com/user-attachments/assets/fd93e0de-a01d-4ab1-8b66-3226f1620e45" />

**Comment by ArubaitoDev** [comment]
The output is the same with or without the VAE connected. It doesn't seem to matter, so I left it disconnected.
Sorry for the late reply; I barely use this account.
