### ISSUE TITLE
Does not show in Ui links between nodes.

### ISSUE THREAD

**Issue by Romanio1997** [comfyanonymous/ComfyUI#5105]
### Your question

Does not show in Ui links between nodes.
<img width="1132" alt="5tySZZWEsV" src="https://github.com/user-attachments/assets/082237fc-ab68-4128-ab75-2655469d9082">

**Comment by ltdrdata** [comment]
Disable all custom nodes and refresh browser and test again.

**Comment by killliu** [comment]
@ltdrdata 你的意思是不要用自定义节点啦？

**Comment by Sebastian-Zok** [comment]
Thanks, @ltdrdata! I had the same issue, and disabling Mixlab-nodes solved it for me :)

**Comment by barepixels** [comment]
thanks [Sebastian-Zok](https://github.com/Sebastian-Zok).  I had the same problem and disable Mixlab solved for me too
