### ISSUE TITLE
My Comfyui paused for some reasons

### ISSUE THREAD

**Issue by mukuluu** [comfyanonymous/ComfyUI#5109]
### Your question

Hey guys, i was using comfyui but somehow it start no response so i restart the comfyui, after that, i can't start my comfyui anymore, or is there any ways to reinstall my comfyui without lose everything
![image](https://github.com/user-attachments/assets/f30a08ab-6a18-4fa2-984e-7f95a04a7679)

**Comment by ltdrdata** [comment]
Please disable all custom nodes and try again.

**Comment by Jahid-Hasan-kafi** [comment]
> Please disable all custom nodes and try again.

it's work Thank You

**Comment by stefanlanecreative** [comment]
how do you disable the nodes?
