### ISSUE TITLE
why There is a significant difference in time consumption between running the workflow using the web interface and calling the workflow using the API?

### ISSUE THREAD

**Issue by LianShuaiLong** [comfyanonymous/ComfyUI#5110]
### Your question

Why does the same Flux workflow not require the "Requested to load AutoencodingEngine" step when using the web interface? The first image shows the workflow running with the web interface. However, when using the API to call the workflow, it requires the "Requested to load AutoencodingEngine" step, which results in doubling the time taken to generate the image with the same prompt. The second image shows the workflow called using the API
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/255f9f0d-c160-4209-bc14-be850ed80db4">
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/739414fd-e6c5-440c-8a1b-caa6974f4475">

**Comment by TowhidKashem** [comment]
hey @LianShuaiLong sorry I don't have an answer to your question but can you tell me how to use comfy in api mode? I am running comfy on runpod and am trying to make a POST request to the same web ui url with `/prompt` path. Is that how it should be done or does the url look different and also do u need to do anything to enable api mode in comfy itself?

**Comment by ltdrdata** [comment]
Create `dbg_prompt.py` file into `ComfyUI/custom_nodes`
```
from server import PromptServer

def onprompt(json_data):
    print(f"[DBG] PROMPT: {json_data['prompt']}")
    return json_data

PromptServer.instance.add_on_prompt_handler(onprompt)


NODE_CLASS_MAPPINGS = {}
```

This will print prompt.
Now you can compare difference between api and queue from front.

**Comment by TowhidKashem** [comment]
> json_data

thanks! was able to use ur script to get the real payload shape. It's working in api mode now even on a regular pod.
