### ISSUE TITLE
how can i upgrade pytorch?

### ISSUE THREAD

**Issue by Lecho303** [comfyanonymous/ComfyUI#5111]
### Your question

i not a programmer,and i found that my pytorch is 2.3.1,i do not know how to upgrade the pytorch?
this is my comfyui/python/cuda/pytorch 's version:
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: D:\comfyUI\ComfyUI_windows_portable_nvidia.7z\python_embeded\python.exe
ComfyUI v0.2.2 Release

i was download the "comfyUI\ComfyUI_windows_portable_nvidia.7z"zip.have trying to double click thecomfyUI\ComfyUI_windows_portable_nvidia.7z\update- "update"、"update_comfyui_and_python_dependencies"\"update_comfyui_stable",seems not update the pytorch…
and i have try to upgrade the pytorch in miniconda,it show me the version is 2.4.1,but reload the comfyui,still got the version 2.3.1…

**Comment by Mescalamba** [comment]
Seems you are using portable distribution of ComfyUI, that must be upgraded from within itself.

Unless you have some specific reason to upgrade I would leave it as it is. Ofc it can be upgraded, I would just need to look into how. :D

**Comment by Lecho303** [comment]
> Seems you are using portable distribution of ComfyUI, that must be upgraded from within itself.
> 
> Unless you have some specific reason to upgrade I would leave it as it is. Ofc it can be upgraded, I would just need to look into how. :D

yes,i am using portable distribution of Comfyui…cause i am not a programmer,i just know search "how to upgrade pytorch in miniconda",the copy the code …

so，that means i can not click the "update" to upgrade pytorch,right?

**Comment by LukeG89** [comment]
@Lecho303 You can update it by opening terminal inside the main folder (where run_nvidia_gpu.bat is located) and using this:
```
python_embeded\python.exe -m pip install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124
```

**Comment by Lecho303** [comment]
> Seems you are using portable distribution of ComfyUI, that must be upgraded from within itself.
> 
> Unless you have some specific reason to upgrade I would leave it as it is. Ofc it can be upgraded, I would just need to look into how. :D

i find the way:uninstall that zip,and download the zip again……now show me that the pytorch is 2.4.1…
![Uploading 屏幕截图 2024-10-01 011620.png…]()

**Comment by Lecho303** [comment]
> @Lecho303 You can update it by opening terminal inside the main folder (where run_nvidia_gpu.bat is located) and using this:
> 
> ```
> python_embeded\python.exe -m pip install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124
> ```

thank you so much！！！！！！but  i just uninstall that zip……anyway, next time i will try this way

**Comment by ltdrdata** [comment]
You should not use the portable version if you wanna use the miniconda environment.

**Comment by Lecho303** [comment]
> You should not use the portable version if you wanna use the miniconda environment.

use nimiconda because i was installed SD with a tutorial hhhhhh

**Comment by kakkkarot** [comment]
[LukeG89](https://github.com/LukeG89) mate you a hero, I have done a countless installs for comfyUI whenever I would encounter this error but this one single line solved it, thanks a lot

**Comment by andreszs** [comment]
Sorry to reuse your Pytorch topic but, my GPU has CUDA 12.7, however, the **update/update_comfyui_and_python_dependencies.bat** is downloading **download.pytorch.org/whl/cu118/torch-2.5.1**, shouldn't it download the **cu124** version instead? The bat file has no version info, it seems the version is handled somewhere else.

![update_comfyui_and_python_dependencies](https://github.com/user-attachments/assets/1757d25f-fa97-4534-99b4-cdd6eb5745d6)

**Comment by LukeG89** [comment]
> however, the update/update_comfyui_and_python_dependencies.bat is downloading download.pytorch.org/whl/cu118/torch-2.5.1, shouldn't it download the cu124 version instead?

@andreszs It should, but you probably have a very outdated installation, and inside the .bat file there is a link to 2.0.1+cu118
