### ISSUE TITLE
Can we have a usable path field for Save Image please?

### ISSUE THREAD

**Issue by n0valis** [comfyanonymous/ComfyUI#5113]
### Feature Idea

I find the path field is unusable. 
Not only is it way to small, it can not be used if converted to input, which I did in the beginning, but does not accept variable placeholders.
As I get more comfortable with Comfy I get more and more uncomfy with the input fields. They are just bad to use.. Click, enter text, click. Where possible I convert them to input and put a string or int or whatever in front.

With the Save Image path field this is unfortunately not possible. My paths usually look like this: /path/to/images/buildings/incoming/Random/sharp/%XlabsSampler.noise_seed%/%XlabsSampler.noise_seed%_sharp 

So try to cope with that with the given fields we have today in the Save Image node. Impossible. You have to construct your path elsewhere. But then you cannot use a string node to connect because the variable will not be evaluated.

So all together this is a pain in the a**, sorry to say.
Maybe someone will try and fix this one day. I'd be happy and gratefull.
Many thanks.

**Comment by ltdrdata** [comment]
Please move this issue to the front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
