### ISSUE TITLE
Lora fails to generate an image, ends up producing noise 

### ISSUE THREAD

**Issue by therevelator86** [comfyanonymous/ComfyUI#5119]
### Your question

Hey, my LoRA suddenly broke after updating comfy yesterday. I rolled back to the previous release and it is still broken, then I reinstalled everything and it still the same result. Anyone else facing this? Im on Mac M2

<img width="407" alt="Screenshot 2024-10-01 at 16 11 43" src="https://github.com/user-attachments/assets/c5b3b66f-3fa3-4ac0-86d5-e9cae6fce5e5">
<img width="1761" alt="Screenshot 2024-10-01 at 16 18 14" src="https://github.com/user-attachments/assets/af7213dd-3c6b-4e61-aa02-b999499848cf">

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/9c43f5f1-1a09-4bb2-835f-2ac54682aaaa)

What is the `model.safetensor` in dualcliploader?

**Comment by DeepSeaCatz** [comment]
Supposed to be Clip L + your fp8.
![image](https://github.com/user-attachments/assets/501516f2-1f28-4159-b211-ff39b8709413)

Also, Flux don't accept Negative prompt, so you can remove the 2nd text encoder and connect the FluxGuidance on both Positive and Negative input of the KSampler:
![image](https://github.com/user-attachments/assets/b43514b4-ad07-494b-bcfa-3e6005e875f5)

**Comment by therevelator86** [comment]
thanks guys, I renamed the clip_l to model.safetensors, after downloading fresh clip_l and removing the negative prompt it is still the same 😔 this setup and the exact same lora worked 2 days ago without any issues..
<img width="1392" alt="Screenshot 2024-10-01 at 19 33 00" src="https://github.com/user-attachments/assets/9df264ee-8ec6-4254-9bc9-c50203912d4b">

**Comment by therevelator86** [comment]
it works again after changing the cfg value in ksampler to 8.0

**Comment by therevelator86** [comment]
thanks guys!

**Comment by DeepSeaCatz** [comment]
I was about to test out your KSampler settings. Never used the Beta scheduler and 1cfg is extremely low. In another Flux Workflow, I don't even think CFG is needed. You can try this one if you have further issues:
https://education.civitai.com/quickstart-guide-to-flux-1/#third-party-flux-models

Glad it worked out!
