### ISSUE TITLE
Node Preview Tooltip UI

### ISSUE THREAD

**Issue by DeepSeaCatz** [comfyanonymous/ComfyUI#5123]
### Feature Idea

Add a Preview button that when hover or pressed, a tooltip of all the nodes are displayed next to it. I'm imagining the nodes would be displayed like Flex rows, kind of like Pinterest. A scroll bar would appear if there are many nodes.
![NodeManagerUI](https://github.com/user-attachments/assets/1d68f9e3-4cab-490c-88a8-3934a6cf9d21)

With the new addition of visually seeing each nodes in the ComfyUI search, I thought it would be very nice to see what node you're actually downloading before you actually do. Seeing a preview of the nodes input/outputs would also help to see their compatibility with your current workflow.
![image](https://github.com/user-attachments/assets/4116501e-34f9-487b-84d5-ea938bf3b1de)

There are Custom Nodes pack with tons of nodes that you might not use. This would let user have a smarter decision before bloating their custom nodes folder. Many nodes are starting to repeat themself and this could be a first step to visually optimizing your custom node toolkit. 

### Existing Solutions

1. Currently you need to open the GitHub repo and hope to see a preview of the nodes.
2. Alternatively you can bite the bullet and download the node Pack. I've stubbled upon one node that reinstalled Torchvision, which broke my entire ComfyUI. Had to flag it and it got removed from the manager.

### Other

I think this addition will be a step forward into making this more user-friendly than programmer friendly.
If it's even possible, letting the user interact with the nodes values/dropdowns/interactions before even downloading them would be pretty cool.

**Comment by huchenlei** [comment]
Can you transfer the issue to https://github.com/ltdrdata/ComfyUI-Manager? The custom node panel is a feature offered in the ComfyUI manager.
