### ISSUE TITLE
problems with node dwpose

### ISSUE THREAD

**Issue by Rairlan** [comfyanonymous/ComfyUI#5131]
### Your question

Every time I try to use a structure that involves the DWpose node, this message appears, I've already tried reinstalling comfyUi and even downloading the file that says it's incomplete and putting it in the folder but the problem persists, would there be another solution to solve this problem? ?

### Logs

```powershell
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ComfyUI_windows_portable_nvidia (1)\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-tbox\\..\\..\\models\\annotator\\hr16\\DWPose-TorchScript-BatchSize5\\.cache\\huggingface\\download\\dw-ll_ucoco_384_bs5.torchscript.pt.d86a0b2b59fddc0901a7076e9f59c9f8602602133ed72511c693fd11eea23d91.incomplete'
```

**Comment by LukeG89** [comment]
I believe that the problem is your long folder path. You need to reduce it as much as you can, and also avoid spaces in the folder names like in your case: `\ComfyUI_windows_portable_nvidia (1)\`

**Comment by ltdrdata** [comment]
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

**Comment by Rairlan** [comment]
Problem solved! That was exactly it, I was almost giving up, thank you very much.
