### ISSUE TITLE
bert-base-uncased does not appear

### ISSUE THREAD

**Issue by celinecsw** [comfyanonymous/ComfyUI#5134]
### Your question

G-Dino模型加载器
bert-base-uncased does not appear to have a file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt or flax_model.msgpack.

**Comment by StarDragonDaYan** [comment]
有人知道吗

**Comment by ishaangupta2311** [comment]
I am also having this issue, dont understand how to solve it
