### ISSUE TITLE
RuntimeError: No HIP GPUs are available on Linux Mint 22 and rx 6600

### ISSUE THREAD

**Issue by skulldsp** [comfyanonymous/ComfyUI#5138]
### Your question

how do i install comfy UI if i have an amd gpu and use linux mint? I'm on Linux Mint 22.0 and have an RX 6600
I follow the steps on the front page on a fresh installation but get this issue: RuntimeError: No HIP GPUs are available

first i installed pytorch with: pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.1
it didn't work so I uninstalled with pip uninstall torch
then I tried nightly pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124

and I tried HSA_OVERRIDE_GFX_VERSION=10.3.0 python main.py but I get the same error No HIP GPUs are available
Is my gpu not compatible?

**Comment by koskoakos** [comment]
For AMD GPUs to work correctly with pytorch you need ROCM pytorch build

The first one is correct for ROCM (AMD):
```pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.1``` 

This installs CUDA pytorch (NVIDIA):
```pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124``` 
You can't have both in one environment.

Install latest AMD drivers, create fresh venv, and try installing pytorch+rocm again.

**Comment by skulldsp** [comment]
thanks, successfully installed rocm and got comfyui running after following this guide https://github.com/Joyfreaky/ROCm-RX6600
