### ISSUE TITLE
conditioning to text

### ISSUE THREAD

**Issue by Chengym2023** [comfyanonymous/ComfyUI#5144]
### Your question

my prompt is use wildcard like {a|b} "__file__" etc, and link to pos conditioning,is there a node like show text,show the prompt is a or b?

**Comment by LukeG89** [comment]
You could use `Show Text 🐍` node from [ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts)

![show_text](https://github.com/user-attachments/assets/adc49175-ff0c-47d7-a0f2-b8a557edcc55)

**Comment by Chengym2023** [comment]
> You could use `Show Text 🐍` node from [ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts)
> 
> ![show_text](https://private-user-images.githubusercontent.com/161304036/373541933-adc49175-ff0c-47d7-a0f2-b8a557edcc55.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNTIxNjIsIm5iZiI6MTcyODA1MTg2MiwicGF0aCI6Ii8xNjEzMDQwMzYvMzczNTQxOTMzLWFkYzQ5MTc1LWZmMGMtNDdkNy1hMGYyLWI4YTU1N2VkY2M1NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNDI0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWU1NGFhNmViOTBkOTMxYmE3MDU4NjMxN2IzZTllZGZlZjNkZmYzYzRjMmE3YzZiYmYxNDM0NmIxZDFjZDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PlKFL_xB_a_KWwVGrA2k0iH1GbXqK5tWk6oLEJrHDbg)
![image](https://github.com/user-attachments/assets/bb153384-854f-419b-aacb-44557a48b050)
why i do not have show text? just save text?

**Comment by Chengym2023** [comment]
> You could use `Show Text 🐍` node from [ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts)
> 
> ![show_text](https://private-user-images.githubusercontent.com/161304036/373541933-adc49175-ff0c-47d7-a0f2-b8a557edcc55.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNTI5MzUsIm5iZiI6MTcyODA1MjYzNSwicGF0aCI6Ii8xNjEzMDQwMzYvMzczNTQxOTMzLWFkYzQ5MTc1LWZmMGMtNDdkNy1hMGYyLWI4YTU1N2VkY2M1NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNDM3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmVmNGI5ZmQ0YWJkNzAzNWUwMjUzYzJiYTY1OWFmNzg1Mjg0NWRiMjdiZDk1NGQ4NDY2MGJkODNjMzFkYjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h6FD9weCGuRz5ZvMt_Csfc5gLVbwvaUP2ndlZ7lKMH4)

and how to connect conditioning node to text node?

**Comment by LukeG89** [comment]
> why i do not have show text? just save text?

I don't know, maybe your custom node is outdated?

> and how to connect conditioning node to text node?

You have to convert the text widget to input:

![convert_widget](https://github.com/user-attachments/assets/1fd3158d-eade-438c-8d2a-a1bdf906236d)

![text_input](https://github.com/user-attachments/assets/7a0c41bb-e569-4d8f-afb3-7c0a5a080803)

**Comment by LukeG89** [comment]
You can't connect conditioning outputs, you can only connect text and string outputs.

**Comment by DeepSeaCatz** [comment]
I use this Chibi wildcard with a combination of Mikey's Wildcard Processor
[https://github.com/chibiace/ComfyUI-Chibi-Nodes](https://github.com/chibiace/ComfyUI-Chibi-Nodes)

It even has a seed so you can repeat the wildcard prompt again if you want to re-generate for upscale
![image](https://github.com/user-attachments/assets/ac26a2eb-0da9-40b0-9be2-f6e86ce0298a)

**Comment by Chengym2023** [comment]
> You can't connect conditioning outputs, you can only connect text and string outputs.

ok

**Comment by Chengym2023** [comment]
> I use this Chibi wildcard with a combination of Mikey's Wildcard Processor https://github.com/chibiace/ComfyUI-Chibi-Nodes
> 
> It even has a seed so you can repeat the wildcard prompt again if you want to re-generate for upscale ![image](https://private-user-images.githubusercontent.com/114247596/373777253-ac26a2eb-0da9-40b0-9be2-f6e86ce0298a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDA5ODEsIm5iZiI6MTcyODEwMDY4MSwicGF0aCI6Ii8xMTQyNDc1OTYvMzczNzc3MjUzLWFjMjZhMmViLTBkYTktNDBiMC05YmUyLWY2ZTg2Y2UwMjk4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwMzU4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWRlYTc4YWQ5YjI1NWIwNDI4NzcyYWQxYjdhYTEzNTllMDY4NTRhNDkxNTU3MmE2NjljZTUxNTJiOWViNWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UcxNR6XzLnlC6boszFmDuAsiGGDPPLa71mf2oMgHtCo)

another node?i have a lot nodes __^^__

**Comment by ltdrdata** [comment]
To use file-based wildcards, you need to use custom nodes. Various custom node packs provide functionality to support wildcards, so use them according to your needs and preferences.
