### ISSUE TITLE
[ Feature ] in-progress preview node

### ISSUE THREAD

**Issue by JorgeR81** [comfyanonymous/ComfyUI#5148]
### Feature Idea

I'd like to separate the KSampler node from the in-progress preview image.
I want a larger preview, especially with wider images, without having to increase the size of the other widgets.

This would be more useful now, because we can have larger previews ( e.g. `--preview-size 768` )

Is it possible to have an independent in-progress preview node ?

![prev3](https://github.com/user-attachments/assets/d3e5d5b5-bc1a-4d8b-a378-d04183d6b614)

### Existing Solutions

We can turn all the KSampler widgets into inputs ( or use the `SamplerCustomAdvanced` node ).
But we still have a big empty space on the Sampler node ( to make space for the inputs ), and a lot of extra nodes to deal with, in the workflow. 

### Other

I've also opened this in the Frontend repo, so you can close the one that's not relevant.
https://github.com/Comfy-Org/ComfyUI_frontend/issues/1093

**Comment by JorgeR81** [comment]
Another advantage of this approach would be to have an in-progress preview image only for some KSamplers, resulting in a visually simpler workflow / canvas.
For instance I want an in-progress preview for the main Sampler, but I don't need it in the refiner / upscaler.

**Comment by ltdrdata** [comment]
As mentioned, this has already been reported to the front, so I'm closing this request.
