### ISSUE TITLE
Issue with Dynamically Created Widgets type STRING Not Appearing in "Convert to Input" Menu

### ISSUE THREAD

**Issue by numz** [comfyanonymous/ComfyUI#5150]
### Your question

Hi,

I'm working on creating a custom widget and have encountered an issue.
When I dynamically create a widget of type STRING using the following command:
`this.addWidget("STRING", field_name, value[1].inputs, () => {});`

the widget does not appear in the context menu option "convert to input."

After investigating the code, I discovered the issue seems to arise because the addWidget function converts the "type" to lowercase. However, when checking if a widget can be converted to an input, it searches within this list:

`const VALID_TYPES = ["STRING", "combo", "number", "toggle", "BOOLEAN"];`
Since "string" (in lowercase) isn't included in this list, it fails. When I manually add "string" to the list, everything works as expected.

So I have two questions:
- Is there a specific reason the type is being converted to lowercase in addWidget()?
- Am I missing something, or is there a better approach to creating a widget of type STRING?

Thanks in advance for your help!

**Comment by ltdrdata** [comment]
Please this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
