### ISSUE TITLE
Make the background node stay still when editing text fields with Ctrl + Arrow

### ISSUE THREAD

**Issue by DeepSeaCatz** [comfyanonymous/ComfyUI#5151]
### Feature Idea

When rapidly selecting words with Ctrl + arrow keys from a text field, the node in the background moves around. It should stay still and the Ctrl + arrow keys command should only be focused on the text field, not both.
![image](https://github.com/user-attachments/assets/2a6e96c0-5730-4081-97c2-e460d8418d39)

This can be annoying when organizing your nodes in groups and they shift out of bound or touch another group that could be disabled. 

### Existing Solutions

Be a peasant and use your mouse to select or only use arrow keys for each letters to move the text cursor.

**Comment by LukeG89** [comment]
Do you mean Shift + Arrow keys? This key combination for selecting text works fine.

Anyway, you shoud move this issue to the frontend repo: https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by DeepSeaCatz** [comment]
Ctrl + Shift + Arrow select entire words while Shift + Arrow select letters. Going by word is faster.

Didn't know there was a dedicated frontend repo. I'll post there, thanks

**Comment by LukeG89** [comment]
> Ctrl + Shift + Arrow select entire words

@DeepSeaCatz I didn't know that! I just tried it and it works fine to me:

https://github.com/user-attachments/assets/b6d9d786-b602-439a-88f5-f247c3aa4dcb

**Comment by DeepSeaCatz** [comment]
Hmm, must be a Custom node that affect everything then, darn
