### ISSUE TITLE
help me about region prompt

### ISSUE THREAD

**Issue by Chengym2023** [comfyanonymous/ComfyUI#5155]
### Your question

![image](https://github.com/user-attachments/assets/86df8907-cd80-4478-9d66-99b23c1e655f)
i use "conditioning set area" to draw image like this:
![image](https://github.com/user-attachments/assets/48544000-51c0-4df2-bb36-2f733e62f063)
it seems Regular area..
i want draw like no regular,look like comic book:
![image](https://github.com/user-attachments/assets/9af1c947-27f6-4521-b926-fd6c3d85fbfc)
what could i do?

**Comment by ltdrdata** [comment]
If you want to use such a free-form region, you need to use `Conditioning (Set Mask)`.
![image](https://github.com/user-attachments/assets/c3a99f78-85ef-4c95-84bb-19f644341014)

Using `Regional Conditioning By Color Mask` from the **Inspire Pack** allows you to set up the workflow more easily.
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/regional-conditioning-img2img.png
