### ISSUE TITLE
torch.OutOfMemoryError: HIP out of memory. 

### ISSUE THREAD

**Issue by skulldsp** [comfyanonymous/ComfyUI#5161]
### Your question

got this issue on amd + linux
 rx 6600
linux mint 22.0

very first generation, never used comfyui before.

> torch.OutOfMemoryError: HIP out of memory. Tried to allocate 2.25 GiB. GPU 0 has a total capacity of 7.98 GiB of which 1.45 GiB is free. Of the allocated memory 5.91 GiB is allocated by PyTorch, and 237.18 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

why is only 1.48gb free? how can I allocate more?
![Screenshot from 2024-10-05 18-57-57](https://github.com/user-attachments/assets/1e8ae816-a9ec-4eb3-8936-e815321f5099)

**Comment by LukeG89** [comment]
Related issue: https://github.com/comfyanonymous/ComfyUI/issues/4676

You should try the `--reserve-vram` argument (e.g. `--reserve-vram 1.5` to allocate 1.5GB more). Find a value that suits you.

**Comment by ltdrdata** [comment]
Looking at the static state of free vram like that isn't helpful. Use task manager or similar tools to monitor the changes in VRAM usage while the workflow is actually running.
