### ISSUE TITLE
What are these ModelSamplingXXXX nodes do?

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#5164]
### Your question

![image](https://github.com/user-attachments/assets/f41d20e0-0dc2-491c-abe1-791ac4e638be)

Should we add them in workflow? What do they do?

I think we already have sampling setting in the main Ksampler node.

![image](https://github.com/user-attachments/assets/5f9a2a68-4065-48ea-99b0-ed63011edc28)

**Comment by DeepSeaCatz** [comment]
Separating the samplers help a lot when your workflow doesn't require the entire settings of the KSampler. I am thinking of Flux image and when building LCM videos. You only need to connect a sampler somewhere and the model and seed will be scatterer elsewhere.

So basically it's very good for specific situations, but you can still keep using the KSampler for smaller projects/workflow as it's well compacted.

**Comment by comfyanonymous** [comment]
These nodes are to set settings specific to the sampling of the model itself (ex: shift values for flux) or for setting a different sampling type for a model (ex: if you have a vpred sd1.5 model you can use the sampling discrete node with vpred set to sample it correctly).

**Comment by pandayummy** [comment]
Thanks.
