### ISSUE TITLE
I can't use Pony's Lora

### ISSUE THREAD

**Issue by wuyougg** [comfyanonymous/ComfyUI#5168]
I tried to use Pony's Lora in ComfyUI, but failed, even though I wrote "<Lora:Char-HonkaiSR-Sparkle-Pony-V3.safetensors:1:1>" on the prompt, the generated image still has no association with the image.

**Comment by LukeG89** [comment]
have you tried through the lora loader?

**Comment by wuyougg** [comment]
Yes, it works well on the sd1.5 model, but it has no effect on the pony

**Comment by LukeG89** [comment]
May I see your workflow?
Are there any errors in the logs?

**Comment by wuyougg** [comment]
![SharedScreenshot](https://github.com/user-attachments/assets/0fab1b15-d7cc-4b17-9351-cae5ef85bf22)

**Comment by LukeG89** [comment]
No errors or lora key warnings in the logs when you generate with Pony model?

**Comment by wuyougg** [comment]
Yes, normal operation

**Comment by wuyougg** [comment]
I tried Lora's trigger words again, but still no effect

**Comment by LukeG89** [comment]
I don't know, try bypass this clip set last layer node:
![clip_skip](https://github.com/user-attachments/assets/1669547b-e66c-49f7-9032-91b073a10a7a)

If nothing has change I can't help you, sorry

**Comment by wuyougg** [comment]
I tried, but it still doesn't work，I also,used Pony Diffusion V6 XL , still no use

**Comment by LukeG89** [comment]
At this point I can only assume that this lora is for SD1.5 and is not compatible with Pony. Try another lora specific for Pony and see if it works.

**Comment by ltdrdata** [comment]
> ![SharedScreenshot](https://private-user-images.githubusercontent.com/107295176/373944856-0fab1b15-d7cc-4b17-9351-cae5ef85bf22.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjI5NjEsIm5iZiI6MTcyODIyMjY2MSwicGF0aCI6Ii8xMDcyOTUxNzYvMzczOTQ0ODU2LTBmYWIxYjE1LWQ3Y2MtNGIxNy05MzUxLWNhZTVlZjg1YmYyMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxMzUxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODhhYjM0YmYxYzUzMDljZTMzYzQxZDg4ZmU4MWE1ODIzNzJiNzdkMmJlN2MxNGZiY2IzMzkxODcwYTRlYTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qyBIoFI_uYubjxwx_4Z-GtOO3381jG-zga0skrH8N8Y)

You shouldn't use `<lora:...>` in the prompt text. That's only supported in custom nodes that specifically support it. You need to put the trigger words + lora loader there instead.

**Comment by wuyougg** [comment]
I tried the trigger words and the lora loader, but it still didn't work. I can only temporarily determine that the large model is incompatible, even though I am sure that this lora supports pony.

**Comment by Ph0rk0z** [comment]
rgthree has a node that will do this. I think it's called powerprompt or something. I had problems moving my lora inside prompts from old forge and that was my solution. the names change to the filename though, instead of the one in metadata.

**Comment by wuyougg** [comment]
Thank you, now the image has one-third of Lora's appearance, the rest should be the problem of the large model
