### ISSUE TITLE
Set vram state to: HIGH_VRAM?

### ISSUE THREAD

**Issue by lunatico67** [comfyanonymous/ComfyUI#5169]
### Your question

Hi
When i open ComfyUI these words appear at the beginning of the console:
Total VRAM 24564 MB, total RAM 32536 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM

- Is there any way to set it to HIGH_VRAM instead of NORMAL_VRAM?
- If you switch to HIGH_VRAM ComfyUI will it go faster?

**Comment by LukeG89** [comment]
Yes, you can use the `--highvram` argument

**Comment by lunatico67** [comment]
> Yes, you can use the `--highvram` argument

Thanks for the help Luke. Where should I write  --highvram?

**Comment by LukeG89** [comment]
If you use the portable version, you can write it inside the `run_nvidia_gpu.bat` file with notepad

**Comment by lunatico67** [comment]
Thanks Luke foe the help.
This is what is written inside:
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
pause

Then, it should be written like this?:
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
pause
--highvram

**Comment by LukeG89** [comment]
@lunatico67 No, you should write it next to the other argument:
```
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --highvram
pause
```

**Comment by lunatico67** [comment]
> @lunatico67 No, you should write it next to the other argument:
> 
> ```
> .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --highvram
> pause
> ```

A lot of thanks for your freat help. I will try it

**Comment by latheeshmahendran** [comment]
It doesnt work for me :/

**Comment by cdanielc-git** [comment]
add --gpu
