### ISSUE TITLE
Save Checkpoint crashing after merge

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [comfyanonymous/ComfyUI#5170]
### Expected Behavior

Save Checkpoint to save a checkpoint.

### Actual Behavior

Save Checkpoint crashing with "Killed" message in terminal.

### Steps to Reproduce

Workflow:
![checkpoints_merge_crash](https://github.com/user-attachments/assets/55e882ec-c705-494a-add1-817ddb354226)
[checkpoints_merge_crash.json](https://github.com/user-attachments/files/17269301/checkpoints_merge_crash.json)

Using nodes for checkpoints merges: ModelMergeSimple and CLIPMregeSimple, SDXL merge seems to be handling memory inefficiently. Comfy UI just crashes without errors when trying to save a checkpoint that is result of 6 merges of 7 SDXL checkpoints. Using 32GB Ram. The crash doesn't showing an error in terminal only "Killed" message. With efficient scheme of model merges the system should be able to handle infinite number of merges while holding at most 3 checkpoints at memory, 2 inputs and 1 output - at most. When new merge is happens, previous model can be removed from the memory. 
If I remove the last merge (5 merges remaining in total), the model is saved without crashing - so the problem is with checkpoint not being released from the memory.

### Debug Logs

```powershell
--disable-all-custom-nodes
Total VRAM 16076 MB, total RAM 32041 MB
pytorch version: 2.1.2+cu121
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: /home/alexds9/Documents/stable_diffusion/ComfyUI/web
Successfully imported spandrel_extra_arches: support for non commercial upscale models.
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://192.168.0.124:8188
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
model weight dtype torch.float16, manual cast: None
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
model weight dtype torch.float16, manual cast: None
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
model weight dtype torch.float16, manual cast: None
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
model weight dtype torch.float16, manual cast: None
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
model weight dtype torch.float16, manual cast: None
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
Requested to load SDXL
Loading 1 new model
loaded completely 0.0 4897.0483474731445 True
Killed
```

**Comment by ltdrdata** [comment]
You are doing too many model merges, more than your RAM can handle.
Every time you perform a model merge, the merged model is additionally loaded into RAM.

**Comment by a-l-e-x-d-s-9** [comment]
@ltdrdata 
There is no reason to keep all the models in memory after the merge. 
Bad memory management is a matter that needs to be addressed.

**Comment by a-l-e-x-d-s-9** [comment]
Why not to do the merge on level of blocks, it would allow to do infinite merges with a small fraction of the RAM?

**Comment by ltdrdata** [comment]
When a workflow is executed, the results of each node are cached in memory.
The cache results are reset when a new workflow execution invalidates the cache of the corresponding node. This is a fundamental principle for minimizing recalculations.

**Comment by a-l-e-x-d-s-9** [comment]
@ltdrdata 
Ok, but this isn’t good approach for memory management for merges. There’s no need to keep all checkpoints in memory, only the top-most merge. Maybe this could be addressed by introducing a volatile node attribute with auto-cache clearing, or a new node that clears the cache for nodes before it. Either way, this is an important use case for ComfyUI that should be discussed and handled with a fundamental solution, instead of  ignoring it.
Another option could be to implement a dedicated merge node that’s very efficient with memory, performing merges at the block level, handling loading, merging, and memory release internally.

**Comment by ltdrdata** [comment]
The merge model functionality was added later. Nodes like merge model have extremely high memory usage, so it is indeed necessary to handle them in a different way.

**Comment by ltdrdata** [comment]
> @ltdrdata There is no workaround or something that can be done to clear the cached nodes to avoid this crash?

Currently there isn't one, and the simplest method would be to develop special nodes that perform each operation using only a reference to the model, instead of using the model itself as input/output.

I'll try to develope one when I have some free time later.

**Comment by ltdrdata** [comment]
After examining this issue more closely, it is not simply an issue with `ModelMergeSimple`.
MODELs are already being handled in a special way. The primary problem is that you are loading too many models through `CheckpointLoader`.

This is causing memory shortages as they are all being cached.
ModelMergeSimple is designed to merge each model at the point when it's needed, allowing for delayed processing. In other words, model usage does not increase at the point of `ModelMergeSimple` execution.

However, `ModelMergeSimple` prevents the two original models from being unloaded at runtime.
In a scenario like yours, merging with less caching within limited resources is not possible in the current structure. A completely new mechanism would be needed.

It seems that handling such scenarios should be addressed in a discussion.
