### ISSUE TITLE
The `Load Diffusion Model` node can't load in FP8 as "default"

### ISSUE THREAD

**Issue by JorgeR81** [comfyanonymous/ComfyUI#5171]
### Expected Behavior

When I use a Flux FP8 UNET model ( 11 GB ) and set `weight_type` as `default` in the `Load Diffusion Model` node, the model will be loaded in FP8.

https://civitai.com/models/673188/acorn-is-spinning-flux?modelVersionId=862095

![model](https://github.com/user-attachments/assets/328c1039-8235-4a0b-8ca4-a98ff981084c)

### Actual Behavior

When I use the `default` setting, my RAM usage is higher than normal.
It's the same RAM usage as when I use the full size Flux UNET model ( 22 GB ), with the `default` option.

But If I use the `fp8_e4m3fn` option, the RAM usage is normal again. 

### Steps to Reproduce

Load a Flux FP8 UNET model, with the "default" and FP8 options and check the RAM usage differences.

### Debug Logs

```powershell
.
```

### Other

Windows 10 
```
Total VRAM 8192 MB, total RAM 32727 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
```

**Comment by Ph0rk0z** [comment]
It gets cast to the native precision of the card. That is technically "default".

**Comment by JorgeR81** [comment]
> It gets cast to the native precision of the card. That is technically "default".

Ah, yes. That makes sense.
