### ISSUE TITLE
IOT instruction (core dumped) when running with ROCm

### ISSUE THREAD

**Issue by ExposedCat** [comfyanonymous/ComfyUI#5179]
### Expected Behavior

`python main.py` runs Comfy UI

### Actual Behavior

`python main.py` crashes with IOT instruction error

### Steps to Reproduce

- Clone latest Comfy UI
- Create and enter virtual env
- Install ROCm torch libs
```python -m pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.2 --force-reinstall```
- Install requirements.txt
- RUn `main.py`

### Debug Logs

```powershell
** ComfyUI start up time: 2024-10-07 10:31:08.869676

Prestartup times for custom nodes:
   0.0 seconds: /home/.../ComfyUI/custom_nodes/ComfyUI-Manager

terminate called after throwing an instance of 'c10::Error'
  what():  Cannot use cudaMallocAsyncAllocator with cuda < 11.4.
Exception raised from allocator at ../c10/hip/HIPMallocAsyncAllocator.cpp:915 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fb8aeded6c6 in /home/.../ComfyUI/venv/lib64/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x68 (0x7fb8aed97861 in /home/.../ComfyUI/venv/lib64/python3.10/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x56ad3 (0x7fb8aeed7ad3 in /home/.../ComfyUI/venv/lib64/python3.10/site-packages/torch/lib/libc10_hip.so)
frame #3: <unknown function> + 0x51bbd (0x7fb8aeed2bbd in /home/.../ComfyUI/venv/lib64/python3.10/site-packages/torch/lib/libc10_hip.so)
frame #4: <unknown function> + 0x14c3c (0x7fb8aee95c3c in /home/.../ComfyUI/venv/lib64/python3.10/site-packages/torch/lib/libc10_hip.so)
frame #5: <unknown function> + 0x5437 (0x7fb8be25f437 in /lib64/ld-linux-x86-64.so.2)
frame #6: <unknown function> + 0x552d (0x7fb8be25f52d in /lib64/ld-linux-x86-64.so.2)
frame #7: _dl_catch_exception + 0x142 (0x7fb8be25b5c2 in /lib64/ld-linux-x86-64.so.2)
frame #8: <unknown function> + 0xc4fc (0x7fb8be2664fc in /lib64/ld-linux-x86-64.so.2)
frame #9: _dl_catch_exception + 0xa3 (0x7fb8be25b523 in /lib64/ld-linux-x86-64.so.2)
frame #10: <unknown function> + 0xc904 (0x7fb8be266904 in /lib64/ld-linux-x86-64.so.2)
frame #11: <unknown function> + 0x932b4 (0x7fb8bdca22b4 in /lib64/libc.so.6)
frame #12: _dl_catch_exception + 0xa3 (0x7fb8be25b523 in /lib64/ld-linux-x86-64.so.2)
frame #13: <unknown function> + 0x1679 (0x7fb8be25b679 in /lib64/ld-linux-x86-64.so.2)
frame #14: <unknown function> + 0x92da3 (0x7fb8bdca1da3 in /lib64/libc.so.6)
frame #15: dlopen + 0x6f (0x7fb8bdca236f in /lib64/libc.so.6)
<omitting python frames>

[1]    122701 IOT instruction (core dumped)  python main.py
```

### Other

OS: Linux, Fedora 40
ComfyUI commit: `e5ecdfdd2dd980262086b0df17cfde0b1d505dbc`
GPU: RX 6800 XT, ROCm

**Comment by FabianMonjaraz** [comment]
Same issue here, I tried using the `HSA_OVERRIDE_GFX_VERSION=10.3.0 python main.py` command, but the result is similar

```
terminate called after throwing an instance of 'c10::Error'
  what():  Cannot use cudaMallocAsyncAllocator with cuda < 11.4.
Exception raised from allocator at ../c10/hip/HIPMallocAsyncAllocator.cpp:915 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f125396c6c6 in /home/dm0n/.local/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x68 (0x7f1253916861 in /home/dm0n/.local/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x56ad3 (0x7f1253d3aad3 in /home/dm0n/.local/lib/python3.12/site-packages/torch/lib/libc10_hip.so)
frame #3: <unknown function> + 0x51bbd (0x7f1253d35bbd in /home/dm0n/.local/lib/python3.12/site-packages/torch/lib/libc10_hip.so)
frame #4: <unknown function> + 0x14c3c (0x7f1253cf8c3c in /home/dm0n/.local/lib/python3.12/site-packages/torch/lib/libc10_hip.so)
frame #5: <unknown function> + 0x5437 (0x7f12633e1437 in /lib64/ld-linux-x86-64.so.2)
frame #6: <unknown function> + 0x552d (0x7f12633e152d in /lib64/ld-linux-x86-64.so.2)
frame #7: _dl_catch_exception + 0x142 (0x7f12633dd5c2 in /lib64/ld-linux-x86-64.so.2)
frame #8: <unknown function> + 0xc4fc (0x7f12633e84fc in /lib64/ld-linux-x86-64.so.2)
frame #9: _dl_catch_exception + 0xa3 (0x7f12633dd523 in /lib64/ld-linux-x86-64.so.2)
frame #10: <unknown function> + 0xc904 (0x7f12633e8904 in /lib64/ld-linux-x86-64.so.2)
frame #11: <unknown function> + 0x932b4 (0x7f1262aa22b4 in /lib64/libc.so.6)
frame #12: _dl_catch_exception + 0xa3 (0x7f12633dd523 in /lib64/ld-linux-x86-64.so.2)
frame #13: <unknown function> + 0x1679 (0x7f12633dd679 in /lib64/ld-linux-x86-64.so.2)
frame #14: <unknown function> + 0x92da3 (0x7f1262aa1da3 in /lib64/libc.so.6)
frame #15: dlopen + 0x6f (0x7f1262aa236f in /lib64/libc.so.6)
<omitting python frames>
frame #48: <unknown function> + 0x2a088 (0x7f1262a39088 in /lib64/libc.so.6)
frame #49: __libc_start_main + 0x8b (0x7f1262a3914b in /lib64/libc.so.6)
```

**Comment by retowyss** [comment]
```
terminate called after throwing an instance of 'c10::Error'
  what():  Cannot use cudaMallocAsyncAllocator with cuda < 11.4.
Exception raised from allocator at ../c10/hip/HIPMallocAsyncAllocator.cpp:915 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7a512e1be576 in /home/reto/Apps/comfyui/venv/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x68 (0x7a512e168851 in /home/reto/Apps/comfyui/venv/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x56ad3 (0x7a512e2a8ad3 in /home/reto/Apps/comfyui/venv/lib/python3.10/site-packages/torch/lib/libc10_hip.so)
frame #3: <unknown function> + 0x51bbd (0x7a512e2a3bbd in /home/reto/Apps/comfyui/venv/lib/python3.10/site-packages/torch/lib/libc10_hip.so)
frame #4: <unknown function> + 0x14c3c (0x7a512e266c3c in /home/reto/Apps/comfyui/venv/lib/python3.10/site-packages/torch/lib/libc10_hip.so)
frame #5: <unknown function> + 0x647e (0x7a51305ac47e in /lib64/ld-linux-x86-64.so.2)
frame #6: <unknown function> + 0x6568 (0x7a51305ac568 in /lib64/ld-linux-x86-64.so.2)
frame #7: _dl_catch_exception + 0xe5 (0x7a5130374af5 in /lib/x86_64-linux-gnu/libc.so.6)
frame #8: <unknown function> + 0xdff6 (0x7a51305b3ff6 in /lib64/ld-linux-x86-64.so.2)
frame #9: _dl_catch_exception + 0x88 (0x7a5130374a98 in /lib/x86_64-linux-gnu/libc.so.6)
frame #10: <unknown function> + 0xe34e (0x7a51305b434e in /lib64/ld-linux-x86-64.so.2)
frame #11: <unknown function> + 0x9063c (0x7a513029063c in /lib/x86_64-linux-gnu/libc.so.6)
frame #12: _dl_catch_exception + 0x88 (0x7a5130374a98 in /lib/x86_64-linux-gnu/libc.so.6)
frame #13: _dl_catch_error + 0x33 (0x7a5130374b63 in /lib/x86_64-linux-gnu/libc.so.6)
frame #14: <unknown function> + 0x9012e (0x7a513029012e in /lib/x86_64-linux-gnu/libc.so.6)
frame #15: dlopen + 0x48 (0x7a51302906c8 in /lib/x86_64-linux-gnu/libc.so.6)
<omitting python frames>
```

same error here on popOS 22.04 using RX 7900 XTX

**Comment by mhares2** [comment]
Same error here on Ubuntu 24.04.01 with AMD Radeon™ RX 7600 XT, Python 3.12.3
`
$ python main.py 
terminate called after throwing an instance of 'c10::Error'
  what():  Cannot use cudaMallocAsyncAllocator with cuda < 11.4.
Exception raised from allocator at ../c10/hip/HIPMallocAsyncAllocator.cpp:915 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7ec24d56c576 in .../ComfyUI/venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x68 (0x7ec24d516851 in .../ComfyUI/venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x56ad3 (0x7ec24d9a1ad3 in .../ComfyUI/venv/lib/python3.12/site-packages/torch/lib/libc10_hip.so)
frame #3: <unknown function> + 0x51bbd (0x7ec24d99cbbd in .../ComfyUI/venv/lib/python3.12/site-packages/torch/lib/libc10_hip.so)
frame #4: <unknown function> + 0x14c3c (0x7ec24d95fc3c in .../ComfyUI/venv/lib/python3.12/site-packages/torch/lib/libc10_hip.so)
frame #5: <unknown function> + 0x571f (0x7ec24f49871f in /lib64/ld-linux-x86-64.so.2)
frame #6: <unknown function> + 0x5824 (0x7ec24f498824 in /lib64/ld-linux-x86-64.so.2)
frame #7: _dl_catch_exception + 0x132 (0x7ec24f4945b2 in /lib64/ld-linux-x86-64.so.2)
frame #8: <unknown function> + 0xcd7c (0x7ec24f49fd7c in /lib64/ld-linux-x86-64.so.2)
frame #9: _dl_catch_exception + 0x9c (0x7ec24f49451c in /lib64/ld-linux-x86-64.so.2)
frame #10: <unknown function> + 0xd164 (0x7ec24f4a0164 in /lib64/ld-linux-x86-64.so.2)
frame #11: <unknown function> + 0x98194 (0x7ec24f098194 in /lib/x86_64-linux-gnu/libc.so.6)
frame #12: _dl_catch_exception + 0x9c (0x7ec24f49451c in /lib64/ld-linux-x86-64.so.2)
frame #13: <unknown function> + 0x1669 (0x7ec24f494669 in /lib64/ld-linux-x86-64.so.2)
frame #14: <unknown function> + 0x97c73 (0x7ec24f097c73 in /lib/x86_64-linux-gnu/libc.so.6)
frame #15: dlopen + 0x6f (0x7ec24f09824f in /lib/x86_64-linux-gnu/libc.so.6)
frame #16: python() [0x6bc8fc]
frame #17: python() [0x6a99ba]
frame #18: python() [0x6a9142]
frame #19: python() [0x582287]
<omitting python frames>
frame #21: python() [0x549c97]
frame #26: python() [0x5d38bc]
frame #27: python() [0x58206d]
frame #29: python() [0x549c97]
frame #34: python() [0x5d38bc]
frame #35: python() [0x58206d]
frame #37: python() [0x549c97]
frame #42: python() [0x608e12]
frame #43: python() [0x6b5253]
frame #48: <unknown function> + 0x2a1ca (0x7ec24f02a1ca in /lib/x86_64-linux-gnu/libc.so.6)
frame #49: __libc_start_main + 0x8b (0x7ec24f02a28b in /lib/x86_64-linux-gnu/libc.so.6)
`

**Comment by dfmonjarazf** [comment]
> I had to downgrade torch to a previous version and it worked again

Which version you're using?

**Comment by FabianMonjaraz** [comment]
> I had to downgrade torch to a previous version and it worked again

Which version are you using?

**Comment by FabianMonjaraz** [comment]
The nightly version of ROCM6.2 showed me my error message. Installing torch with ROCM6.1 I could launch the main.py file. `ip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.1`

**Comment by sykez98** [comment]
it was one of the earlier versions of 6.2, 
![image](https://github.com/user-attachments/assets/e721cc33-f507-41fd-af30-19bd7f690b09)
I actually just told it to install an invalid version then it listed all of the valid ones for me and so I just tried the earliest one and it worked

so something like 

pip install torchvision==2.4.0.dev20240823+rocm6.2 --index-url https://download.pytorch.org/whl/nightly/rocm6.2/

**Comment by ltdrdata** [comment]
I'm closing this issue as it's a compatibility issue between a specific version of rocm and torch.
