### ISSUE TITLE
Cannot connect to host huggingface.co:443 ssl:default [信号灯超时时间已到]

### ISSUE THREAD

**Issue by dksg65130** [comfyanonymous/ComfyUI#5184]
### Your question

Cannot connect to host huggingface.co:443 ssl:default [信号灯超时时间已到]

**Comment by injet-zhou** [comment]
Please check your network connection; connecting to huggingface may require a VPN.
请检查网络连接，连接到huggingface可能需要vpn

**Comment by winwest** [comment]
I also encountered this problem, so how did I solve it in the end.

**Comment by BAIGUO1314** [comment]
I also encountered this problem, so how did I solve it in the end.

**Comment by denzel10247** [comment]
好嘛，又是vpn不行，对网络要求也太高了，我c站下东西就没事，结果装节点运行节点就都是网络问题

**Comment by Barry-del** [comment]
这个问题怎么解决，无响应，VPN也开了，还是不行

**Comment by mayjack0312** [comment]
Could you please tell me exactly which files I need to download from Huggingface? Could you provide the full file path and file names? These options don't seem to exist in the console, thank you.
The solution I can think of is manually downloading and placing the files.

**Comment by xhd230** [comment]
不光要有模型文件，还要把csv文件放到models文件夹下，csv文件与onnx文件名相同

**Comment by mayjack0312** [comment]
<img width="604" alt="ee858de026c8752ba3ad846b77b209b" src="https://github.com/user-attachments/assets/39b1be4a-17dc-49ef-a6a8-560fea6a3d3c" />

**Comment by Fallenstarstwice** [comment]
following "offline use" part in https://github.com/pythongosssss/ComfyUI-WD14-Tagger, after you changed files' name as tutorials, switch model into `wd-v1-4-convnext-tagger-v2`  in `WD14 Tagger` node

![Image](https://github.com/user-attachments/assets/6569a478-4dbe-4539-90a6-2a88e9b6acec)

**Comment by haijiazeng1970** [comment]
> flowing "offline use" part in https://github.com/pythongosssss/ComfyUI-WD14-Tagger, after you changed files' name as tutorials, switch model into `wd-v1-4-convnext-tagger-v2` in `WD14 Tagger` node
> 
> ![Image](https://github.com/user-attachments/assets/6569a478-4dbe-4539-90a6-2a88e9b6acec)

thanks very much

**Comment by cpj101** [comment]
> > https://github.com/pythongosssss/ComfyUI-WD14-Tagger 中流转 “offline use” 部分，将文件名更改为 tutorials 后，将模型切换到 in 节点`wd-v1-4-convnext-tagger-v2``WD14 Tagger`
> > ![Image](https://github.com/user-attachments/assets/6569a478-4dbe-4539-90a6-2a88e9b6acec)
> 
> 非常感谢

新手看不懂啊 可以细说下操作吗 大仙

**Comment by miyabiyaya** [comment]
> > > https://github.com/pythongosssss/ComfyUI-WD14-Tagger 中流转 “offline use” 部分，将文件名更改为 tutorials 后，将模型切换到 in 节点`` wd-v1-4-convnext-tagger-v2``WD14 Tagger ``
> > > ![Image](https://github.com/user-attachments/assets/6569a478-4dbe-4539-90a6-2a88e9b6acec)
> > 
> > 
> > 非常感谢
> 
> 新手看不懂啊 可以细说下操作吗 大仙
在下载的WD节点里找到pysssss.json，然后打开找到域名并改成"HF_ENDPOINT": "https://hf-mirror.com"（问题出在下载模型，如果开始下载模型则ok了)

**Comment by eymao** [comment]
下载offline use 离线模式的对应2个文件，重命名为特定的名称，放在特定的文件夹中，就解决了。例如：Simplest way is to use it online, interrogate an image, and the model will be downloaded and cached, however if you want to manually download the models:

Create a models folder (in same folder as the wd14tagger.py)
Use URLs for models from the list in pysssss.json
Download model.onnx and name it with the model name e.g. wd-v1-4-convnext-tagger-v2.onnx
Download selected_tags.csv and name it with the model name e.g. wd-v1-4-convnext-tagger-v2.csv

我手动下载了"models": {
		"wd-eva02-large-tagger-v3": "https://huggingface.co/SmilingWolf/wd-eva02-large-tagger-v3", 解决了，

**Comment by ajiegu108** [comment]
The same problem is under study

**Comment by Sdreamtale** [comment]
大陆地区有哪些VPN比较好用？我试过好几个，没有一个满意的，对于节点联网、管理器获取节点列表信息、Git拉取等方面总是出问题。

**Comment by Sdreamtale** [comment]
> Typically, this issue occurs with China-based users because network access is restricted. A VPN is required to bypass this issue.

Which VPN model is more suitable for the Chinese mainland?

**Comment by sadsad123156489712** [comment]
感谢截图改镜像网站的兄弟！！

**Comment by yueyueyushi111222** [comment]
> 将.pyssssjson文件中的huggingface链接改为镜像站链接 https://hf-mirror.com
> 
> ![Image](https://github.com/user-attachments/assets/eebe3ab3-f191-461e-91d1-fdac17614f7b)
> 
> ![Image](https://github.com/user-attachments/assets/8b0487e7-49e1-4570-8d17-22907ac48acc)

我太喜欢你了，兄弟，这个镜像链接帮了新手的大忙
