### ISSUE TITLE
DefaultCPUAllocator: not enough memory: you tried to allocate 13005619200 bytes

### ISSUE THREAD

**Issue by CuddleAI** [comfyanonymous/ComfyUI#5185]
### Your question

how can i change the Vram usage to work with my GPU i have aka. gtx 1650

### Logs

```powershell
i tried to reduce it with in the startup bat by using --lowvram but it is still loading [Set vram state to: NORMAL_VRAM]

so it doesnt seem to work. we have a uni project to create ai video, so if there is any known ways to reduce needed Vram and increase the time since it doesnt mater how long the pc is running.
```

### Other

full error message is: 

[enforce fail at alloc_cpu.cpp:114] data. DefaultCPUAllocator: not enough memory: you tried to allocate 13005619200 bytes.

**Comment by Grantyz** [comment]
It seems like the issue isn't about your VRAM. ComfyUI is trying to allocate RAM (approximately 13.0056192 GB) but it can't. Adjust your project requirements, workflow nodes and try to add SWAP memory if needed. SWAP can visibly decrease performance, so I'd suggest it as the last option.

**Comment by ltdrdata** [comment]
Your system cannot run the FLUX model. Even gguf models quantized to q2 require more than 4GB of VRAM.
