### ISSUE TITLE
FLUX DoRAs that work when generating sample images in OneTrainer make a pink mess in ComfyUI

### ISSUE THREAD

**Issue by envy-ai** [comfyanonymous/ComfyUI#5188]
### Expected Behavior

FLUX DoRAs should work in Comfy if they work while being trained in OneTrainer.

### Actual Behavior

The generated image turns pink and has a lot of messy artifacts.

### Steps to Reproduce

Train a FLUX DoRA in OneTrainer with all layers enabled.  The sample images generated with that DoRA in OneTrainer will look as expected, but images generated with that same DoRA in ComfyUI are pink and garbled

### Debug Logs

```powershell
No errors associated with this issue.
```

### Other

I can provide a DoRA, a OneTrainer sample image, and a ComfyUI sample image, if that helps.  Please let me know.

**Comment by comfyanonymous** [comment]
can you give me a dora to test?

**Comment by comfyanonymous** [comment]
should be fixed now.

**Comment by envy-ai** [comment]
Thanks, that fixed it!
