### ISSUE TITLE
Redundant output of xformers version and vram state at start

### ISSUE THREAD

**Issue by FraYoshi** [comfyanonymous/ComfyUI#519]
commit deb2b93e797cb345d18e5fd54dff20837fd5ba02 introduced double notification about the `xformers version` and the `vram state`.

just after `python main.py`, terminal outputs:
```
xformers version: 0.0.16
Set vram state to: NORMAL_VRAM
Using xformers cross attention
xformers version: 0.0.16
Set vram state to: NORMAL_VRAM
```

![2023-04-16_00-38-04](https://user-images.githubusercontent.com/14005514/232256061-f7544e96-e3c6-4aa0-a78e-00a06b37f3d6.png)

**Comment by comfyanonymous** [comment]
Should be fixed now.

**Comment by FraYoshi** [comment]
hmm.. not for me 🤔

![2023-04-16_01-38-01](https://user-images.githubusercontent.com/14005514/232258471-a60ba95b-85eb-4a62-bf75-ca7d878fab74.png)

**Comment by comfyanonymous** [comment]
I don't see it on colab, are you using some custom nodes?

**Comment by FraYoshi** [comment]
Yes, disabling custom nodes fixed the redundancy!
![2023-04-16_01-45-01](https://user-images.githubusercontent.com/14005514/232258672-0ea3a564-b1f8-47eb-8f27-e3b39055f657.png)

**Comment by FraYoshi** [comment]
Confirmed that are the `comfy_controlnet_preprocessors` !
