### ISSUE TITLE
Why does AutoencodingEngine need to be reloaded every time it runs?

### ISSUE THREAD

**Issue by phoenixor** [comfyanonymous/ComfyUI#5190]
### Your question

I use an Ubuntu server. The hardware information is : cuda:0 Tesla T4 : cudaMallocAsync  15G
I use the official sample workflow. The loader used is as follows.
1. t5xxl_fp8_e4m3fn.safetensors
2. flux1-dev-fp8.safetensors
3. clip_l.safetensors
4. ae.safetensors

every time i run the workflow, it will reload model AutoencodingEngine and takes 150 seconds to ouput the image. How can i fix this problem?

**Comment by ltdrdata** [comment]
There isn't enough space in your VRAM to load both t5 and flux simultaneously.
If you modify the prompt, t5 needs to be loaded again to recalculate the conditioning.
If you skip the ksampling step and only create conditioning consecutively, there's no need to reload t5.

The fact that loading takes such a long time means your RAM is insufficient and swapping is occurring. If both t5 and flux were properly in RAM, switching between them would be instantaneous.

**Comment by ltdrdata** [comment]
There isn't enough space in your VRAM to load both t5 and flux simultaneously.
If you modify the prompt, t5 needs to be loaded again to recalculate the conditioning.
At this point, VAE and FLUX are unloaded to free up VRAM.
If you skip the ksampling step and only create conditioning consecutively, there's no need to reload t5.
And if you only perform the steps after KSampling using the pre-created conditioning, the phenomenon of VAE being reloaded will also disappear.

The long loading time suggests that your RAM is insufficient, causing swapping to occur. If both t5 and flux were properly loaded in RAM, switching between them would be instantaneous.

**Comment by AbstractEyes** [comment]
I'm getting this without the prompt being modified. The thing reloads each time as of the current build.

**Comment by ltdrdata** [comment]
> I'm getting this without the prompt being modified. The thing reloads each time as of the current build using Flux. Loads, spins up, finishes, unloads everything. Has to reload slowly yet again every single time I start it back up and I'm running it on the windows build with a 4090. I'm capping at about 18 out of 24 gigs vram and it does it anyway.

What is your `--reserved-vram` setting?

**Comment by AbstractEyes** [comment]
> > I'm getting this without the prompt being modified. The thing reloads each time as of the current build using Flux. Loads, spins up, finishes, unloads everything. Has to reload slowly yet again every single time I start it back up and I'm running it on the windows build with a 4090. I'm capping at about 18 out of 24 gigs vram and it does it anyway.
> 
> What is your `--reserved-vram` setting?

Whatever the default is.

**Comment by ltdrdata** [comment]
> I'm getting this without the prompt being modified. The thing reloads each time as of the current build using Flux. Loads, spins up, finishes, unloads everything. Has to reload slowly yet again every single time I start it back up and I'm running it on the windows build with a 4090. I'm capping at about 18 out of 24 gigs vram and it does it anyway.

It's flux fp8, and
Is it correct that this phenomenon occurs simply by changing the seed?

**Comment by AbstractEyes** [comment]
> Collaborator

No. Happens even when I leave the seed the same and have unfinished generations.

**Comment by AbstractEyes** [comment]
So I noticed it wasn't happening with other models. Primarily this one.

https://civitai.com/models/637170/flux1-compact-or-clip-and-vae-included

**Comment by ltdrdata** [comment]
> So I noticed it wasn't happening with ALL other models. Primarily this one. When I load fp8 unet with the fp16 xxl as standalone it doesn't need to reload every time I change seeds.
> 
> https://civitai.com/models/637170/flux1-compact-or-clip-and-vae-included
> 
> Unless something was patched to make it more stable, in which case I'll hold my tongue.

In the case of fp16, the diffusion model alone already reaches 23.8GB, so it may be freeing up VRAM space to load the VAE.
This is because the system attempts to secure a bit of extra VRAM to cover VRAM consumption used by other apps like browsers and basic display, and VRAM consumption that isn't captured in measurements.

**Comment by AbstractEyes** [comment]
> > So I noticed it wasn't happening with ALL other models. Primarily this one. When I load fp8 unet with the fp16 xxl as standalone it doesn't need to reload every time I change seeds.
> > https://civitai.com/models/637170/flux1-compact-or-clip-and-vae-included
> > Unless something was patched to make it more stable, in which case I'll hold my tongue.
> 
> In the case of fp16, the diffusion model alone already reaches 23.8GB, so it may be freeing up VRAM space to load the VAE. There is a shortage of VRAM due to consumption by other apps such as browsers. Additionally, ComfyUI attempts to secure a bit of extra VRAM to cover VRAM consumption that isn't accurately captured in its measurements.

This isn't fp16. Even when loading both unet and t5xxl_fp8 I end up with this problem. It unloads both, and it's still doing it. It's gotten to the point where I might as well just switch to forge full time, since it actually works and this one is just patching itself into a laggier and laggier state.

**Comment by comfyanonymous** [comment]
This was fixed like 2 months ago. Try downloading a fresh version of the latest standalone package.

If you still have issues at least post the logs.
