### ISSUE TITLE
Invoke tips pop-up windows

### ISSUE THREAD

**Issue by yaosheng216** [comfyanonymous/ComfyUI#5192]
### Your question

Hi, author.
First, thanks for your work. I have a question, how can invoke below of this pop-up windows to tips user.
![iwEcAqNwbmcDAQTRCFIF0QS4BrD7tntJDxTo2AbtcrtKtIYAB9IAjNzyCAAJomltCgAL0gAPkAM png_720x720q90](https://github.com/user-attachments/assets/4d1c9280-4909-46f7-ba05-d2571f13e817)

Wish your answer.
Thanks!

**Comment by ltdrdata** [comment]
Issues that occur in custom nodes should be reported to the respective custom node repository.

**Comment by yaosheng216** [comment]
@ltdrdata Hi, can you give me a demo code to invoke custom node repository.
Thanks!

**Comment by ltdrdata** [comment]
> @ltdrdata Hi, can you give me a demo code to invoke custom node repository. Thanks!

I misunderstood the issue.
Your question was about how to display a pop-up from your extension.

This functionality is related to the front-end, so you can inquire about it here.
https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by yaosheng216** [comment]
@ltdrdata Thanks for your answer.But i want invoke pop-up windows in the python code, ComfyUI whether to provide api to invoke.
