### ISSUE TITLE
fatal: detected dubious ownership in repository

### ISSUE THREAD

**Issue by lemocpv6link** [comfyanonymous/ComfyUI#5193]
### Expected Behavior

E:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 8192 MB, total RAM 32509 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI_windows_portable\ComfyUI\web
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
fatal: detected dubious ownership in repository at 'E:/ComfyUI_windows_portable/ComfyUI'
'E:/ComfyUI_windows_portable/ComfyUI' is on a file system that does not record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory E:/ComfyUI_windows_portable/ComfyUI
Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.

### Actual Behavior

E:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 8192 MB, total RAM 32509 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI_windows_portable\ComfyUI\web
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
fatal: detected dubious ownership in repository at 'E:/ComfyUI_windows_portable/ComfyUI'
'E:/ComfyUI_windows_portable/ComfyUI' is on a file system that does not record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory E:/ComfyUI_windows_portable/ComfyUI
Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.

### Steps to Reproduce

E:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 8192 MB, total RAM 32509 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI_windows_portable\ComfyUI\web
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
fatal: detected dubious ownership in repository at 'E:/ComfyUI_windows_portable/ComfyUI'
'E:/ComfyUI_windows_portable/ComfyUI' is on a file system that does not record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory E:/ComfyUI_windows_portable/ComfyUI
Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.

### Debug Logs

```powershell
E:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 8192 MB, total RAM 32509 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI_windows_portable\ComfyUI\web
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
fatal: detected dubious ownership in repository at 'E:/ComfyUI_windows_portable/ComfyUI'
'E:/ComfyUI_windows_portable/ComfyUI' is on a file system that does not record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory E:/ComfyUI_windows_portable/ComfyUI
Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
```

**Comment by LukeG89** [comment]
Related issue: https://github.com/comfyanonymous/ComfyUI/issues/4686

Try to update ComfyUI with the `update_comfyui_stable.bat` inside `update/` folder.

**Comment by ltdrdata** [comment]
This is not an issue with ComfyUI itself, but rather an issue with your system environment.

This occurs when ComfyUI is installed in an unconventional location (such as a network drive or a location with incorrect ownership/permissions).

On Windows, Git is designed to block such functionality for security reasons when it determines that the situation is unsafe.

As mentioned in the message, this needs to be resolved through git configuration.
