### ISSUE TITLE
Is VAE Encode (for Inpainting) broken?

### ISSUE THREAD

**Issue by a-ru2016** [comfyanonymous/ComfyUI#5194]
### Expected Behavior

Can be inpainted with VAE Encode (for Inpainting)

### Actual Behavior

The mask part behaved like initial noise.

### Steps to Reproduce

When you set denoise to about 0.6 with VAE Encode (for Inpainting), the masked part becomes gray.

### Debug Logs

```powershell
Nothing in particular
```

### Other

InpaintModelConditioning works fine

**Comment by ltdrdata** [comment]
`VAE Encode (for Inpainting)` is a node for using the inpainting model in its most basic form. The inpainting model requires that the area to be inpainted be filled with a specific gray color and that the denoise value be set to 1.0. In other words, it's a model intended to completely fill in the target area anew.
For this purpose, it only works properly when the workflow is set up precisely for this use.
`InpaintModelConditioning` is a node that allows the use of the inpainting model at denoise values less than 1.0 by applying additional techniques.
