### ISSUE TITLE
Where can I find a comfyUI version that has Torch 2.4.0 instead of 2.4.1?

### ISSUE THREAD

**Issue by GPU-server** [comfyanonymous/ComfyUI#5196]
### Your question

Where can I find a comfyUI version that has Torch 2.4.0 instead of 2.4.1?

**Comment by ltdrdata** [comment]
You have to install torch manually.

https://pytorch.org/

![image](https://github.com/user-attachments/assets/adf6263a-efd1-4ec1-a5a1-8ab84d093c8a)

**Comment by GPU-server** [comment]
Yes but the problem @ltdrdata  is that after I have installed torch 2.4.0 manually (which I DID), anytime I use the comfy MANAGER to fix a missing node, it UNINSTALL my 2.4.0 torch ! And then comfy Does not start again! Believe me. This is true. I figured that somehow comfyui Will always revert to the DEFAULT Torch even when I have installed a new one myself.
Look:
https://github.com/MrForExample/ComfyUI-3D-Pack/issues/341

I was trying to get the "impack pack " or similar (not that one necessary), inside one of the "example workflows". I battled to make that custom node work (by isntalling Torch 2.4.0 a bunch of other things), and only then to hit: TRY FIX -> ComfyUi found my Torch 2.4.0 and UNINSTALLED IT.

Happened to me several times! 
But not all missing nodes did that. But it happened too many times.

Believe me this is true.
That's why I figured I probably need a new comfyui BASE installation with 2.4.0 instead!
Did you understand the issue?
Thanks

**Comment by ltdrdata** [comment]
> Yes but the problem @ltdrdata is that after I have installed torch 2.4.0 manually (which I DID), anytime I use the comfy MANAGER to fix a missing node, it UNINSTALL my 2.4.0 torch ! And then comfy Does not start again! Believe me. This is true. I figured that somehow comfyui Will always revert to the DEFAULT Torch even when I have installed a new one myself. Look: [MrForExample/ComfyUI-3D-Pack#341](https://github.com/MrForExample/ComfyUI-3D-Pack/issues/341)
> 
> I was trying to get the "impack pack " or similar (not that one necessary), inside one of the "example workflows". I battled to make that custom node work (by isntalling Torch 2.4.0 a bunch of other things), and only then to hit: TRY FIX -> ComfyUi found my Torch 2.4.0 and UNINSTALLED IT.
> 
> Happened to me several times! But not all missing nodes did that. But it happened too many times.
> 
> Believe me this is true. That's why I figured I probably need a new comfyui BASE installation with 2.4.0 instead! Did you understand the issue? Thanks

It's a completely different issue.

Occasionally, some custom nodes have incorrectly written requirements, causing `torch` to be forcibly reinstalled during the installation process.
ComfyUI-Manager has measures in place to prevent such issues as much as possible, but there are still some blind spots.

If you report which custom node installation caused this issue to the ComfyUI-Manager repo, I will add a warning message for it.

**Comment by GPU-server** [comment]
Thanks for listening I was writing a whole new issue for it. Shoud I proceed with that other issue or leave it as is?
So The solution would be to go install the custom node MANUALLY, and check its requirements.txt and make sure that if there is a mention of Torch then to add version==2.4.0 something like that? Or is there something else to check?

**Comment by ltdrdata** [comment]
Since this issue is not related to ComfyUI core, please report it in the ComfyUI-Manager repository.
There's no need to delete this issue.

**Comment by GPU-server** [comment]
Ok thanks. What about my stategy to solve it (in the meantime) Is that the best way to prevent that behaviour or do you suggest extra actions? (that I might not be aware of?)

**Comment by ltdrdata** [comment]
> Ok thanks. What about my stategy to solve it (in the meantime) Is that the best way to prevent that behaviour or do you suggest extra actions? (that I might not be aware of?)

For `torch`, simply specifying the version is not enough; the `--index-url` must be specified. (In fact, this is more important.)
