### ISSUE TITLE
Add custom path for "models" folder and etc in the settings menu

### ISSUE THREAD

**Issue by M4Mahdi** [comfyanonymous/ComfyUI#5201]
### Feature Idea

I need to have shared paths(folders) for models(and any big sized stable file) to share them between different versions of ComfyUI.
Due to this issue(https://github.com/comfyanonymous/ComfyUI/issues/5200), i need different versions of ComfyUI in some situations. If there was a way to change path of the "models" folder in the settings menu as a custom path(as an "absolute path" or with a "../" as a "relative path" like "../models" to go to previous folder and load from it), i could load them from any version of ComfyUI as shared folder between different versions.

I think it can be useful to reduce using hard drive in such situations.

**Comment by LukeG89** [comment]
You can already set a shared model path to all your ComfyUI versions by editing the `extra_model_paths.yaml.example` file in the ComfyUI folder.
