### ISSUE TITLE
Is there an option to be available to change back the GUI back to the earlier new frontend?

### ISSUE THREAD

**Issue by Orenji-Tangerine** [comfyanonymous/ComfyUI#5206]
### Feature Idea

The queue button/refresh/cancel/clear is now in a moveable group, however, the previous set up seems better. Will there be a possibility for user to make such changes?

![image](https://github.com/user-attachments/assets/e2347cb5-2d43-4828-b88c-cdb3d305aa3b)

**Comment by hxinsss** [comment]
In the new version, the workflow fold is moved to sidebar, it is really hard to be used.  Now I use the argument: --front-end-version Comfy-Org/ComfyUI_frontend@1.2.64. back to the pervious version, it's really fine now.
