### ISSUE TITLE
Snap to Grid is not working in v1.3.17

### ISSUE THREAD

**Issue by camoody1** [comfyanonymous/ComfyUI#5211]
### Expected Behavior

I expect node boxes to snap to a grid-line when I move them like they always have.

### Actual Behavior

Since the most recent update, the node boxes no longer snap to grid lines. I can move them between grid lines, now.

### Steps to Reproduce

Using Comfy front end v1.3.17 and Snap to Grid enabled in Settings, just try to move a node box between grid lines.

### Debug Logs

```powershell
N/A
```

**Comment by huchenlei** [comment]
Duplicated https://github.com/Comfy-Org/ComfyUI_frontend/issues/1181
