### ISSUE TITLE
Error loading workflows: Failed to fetch

### ISSUE THREAD

**Issue by HenryBao91** [comfyanonymous/ComfyUI#5214]
### Your question

I clone Comfyui repo and run `pip install -r requirement.txt` successfully. Then I want to start it with `python main.py --listen`.
The Comfyui Web auto open with `Error loading workflows: Failed to fetch`
<img width="1587" alt="iShot_2024-10-11_16 29 20" src="https://github.com/user-attachments/assets/c8a91bed-ddbe-4c51-a595-4afcb23c27d4">

### Logs

```powershell
root@notebook-58899:~/ComfyUI# python main.py --listen
Total VRAM 45596 MB, total RAM 2063658 MB
pytorch version: 2.1.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA L20 : cudaMallocAsync
Using pytorch cross attention
****** User settings have been changed to be stored on the server instead of browser storage. ******
****** For multi-user setups add the --multi-user CLI argument to enable multiple user profiles. ******
[Prompt Server] web root: /root/ComfyUI/web

Import times for custom nodes:
   0.0 seconds: /root/ComfyUI/custom_nodes/websocket_image_save.py

Starting server

To see the GUI go to: http://0.0.0.0:8188
```

**Comment by yafangwang9** [comment]
this issue can solve https://github.com/comfyanonymous/ComfyUI/issues/3750
python main.py --listen='0.0.0.0' --port=8188

**Comment by HenryBao91** [comment]
> this issue can solve #3750 python main.py --listen='0.0.0.0' --port=8188

Thank you. But it seems not the same problem. From my console log , it can be seen that 
`To see the GUI go to: http://0.0.0.0:8188` . It's already `0.0.0.0`. 

And I also try your issue, it doesn't work.
```
root@notebook-1845743037106208770-openaimodels-28698:~/ComfyUI# python main.py --listen='0.0.0.0' --port=8188
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-14 16:56:47.314625
** Platform: Linux
** Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
** Python executable: /opt/conda/bin/python
** ComfyUI Path: /root/ComfyUI
** Log path: /root/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.7 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 45596 MB, total RAM 2063658 MB
pytorch version: 2.2.0
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA L20 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /root/ComfyUI/web
Adding extra search path checkpoints /root/ComfyUI/models/checkpoints/
Adding extra search path clip /root/ComfyUI/models/clip/
Adding extra search path clip_vision /root/ComfyUI/models/clip_vision/
Adding extra search path configs /root/ComfyUI/models/configs/
Adding extra search path controlnet /root/ComfyUI/models/controlnet/
Adding extra search path embeddings /root/ComfyUI/models/embeddings/
Adding extra search path loras /root/ComfyUI/models/loras/
Adding extra search path upscale_models /root/ComfyUI/models/upscale_models/
Adding extra search path vae /root/ComfyUI/models/vae/
### Loading: ComfyUI-Manager (V2.48.4)
### ComfyUI Revision: 2448 [bfb52de8] | Released on '2024-08-02'

Import times for custom nodes:
   0.0 seconds: /root/ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: /root/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://0.0.0.0:8188
```
<img width="1292" alt="iShot_2024-10-14_17 00 21" src="https://github.com/user-attachments/assets/54990736-76f1-4cc3-aec7-89276ef90660">
<img width="1333" alt="iShot_2024-10-14_17 00 03" src="https://github.com/user-attachments/assets/61ac5e11-647c-4840-9044-de517e6d05c7">

**Comment by HenryBao91** [comment]
Help

**Comment by ltdrdata** [comment]
I don't know where you cloned it from, but your ComfyUI is a very outdated version, and your pytorch is also a very outdated version.

Before any further diagnosis, it seems necessary to update to the latest version first.

**Comment by HenryBao91** [comment]
> I don't know where you cloned it from, but your ComfyUI is a very outdated version, and your pytorch is also a very outdated version.
> 
> Before any further diagnosis, it seems necessary to update to the latest version first.

I cloned it from this github，and I haved tried many version include the newest version, my torch verison is :`pytorch version: 2.2.0`. But it come with the same error.

**Comment by ltdrdata** [comment]
> > I don't know where you cloned it from, but your ComfyUI is a very outdated version, and your pytorch is also a very outdated version.
> > Before any further diagnosis, it seems necessary to update to the latest version first.
> 
> I cloned it from this github，and I haved tried many version include the newest version, my torch verison is :`pytorch version: 2.2.0`. But it come with the same error.

The reason I recommended updating to the latest version was to check for potential issues that may not occur in the current latest version, and because if error logs appear, it would be difficult to properly analyze them due to code differences.

BTW, While the PyTorch version may not be directly related to this issue, given that version 2.5.0 is already available, is there a reason for using such an old version?


Your issue appears to be related to network configuration in the notebook environment.
