### ISSUE TITLE
bfloat16 scalar not supported on image save error? new since  v0.2.3

### ISSUE THREAD

**Issue by EricRollei** [comfyanonymous/ComfyUI#5227]
### Your question

![image](https://github.com/user-attachments/assets/b7142143-823e-4414-9a48-b1369853da6c)
Getting this error since updating on Oct 11 2024.    Bottom of screen says type error 82 if that's helpful.  
Posting log from the save image node I normally use, but I got similar with several other save image nodes and even preview image nodes.

### Logs

```powershell
Traceback (most recent call last):
  File "A:\Comfy_Dec\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Dec\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Dec\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "A:\Comfy_Dec\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Dec\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 7391, in was_save_images
    i = 255. * image.cpu().numpy()
               ^^^^^^^^^^^^^^^^^^^
TypeError: Got unsupported ScalarType BFloat16
```

**Comment by ltdrdata** [comment]
Please move this issue to was-node-suite-comfyui repo.
https://github.com/WASasquatch/was-node-suite-comfyui

**Comment by EricRollei** [comment]
I don't believe you understood. This is not specifically about the WAS node.  I get the same error on EVERY save image node and EVERY preview image node including the ones native to ComfyUI.   The problem started after the latest comfyui update.   This is not only WAS nodes so it doesn't make sense to post there.

**Comment by ltdrdata** [comment]
> ```powershell
> WAS_Node_Suite.py
> ```

In that case, please post a scenario where this can be reproduced without custom nodes, along with more detailed information about your execution environment and workflow.

**Comment by comfyanonymous** [comment]
Can I see your workflow?

**Comment by EricRollei** [comment]
Just to simplify things as most as possible, this workflow was causing the same bfloat16 error.    
![image](https://github.com/user-attachments/assets/8b229862-c311-4872-ba07-86a132c4f70a)

I tried setting the following command line arguments one at a time but none worked  --fp8, --fp16, --unet-fp8
so I ended up using dickerson's bat file to redo my venv and torch and that seems to have done the trick.  Closing the issue, sorry for the trouble. Must have just been a gremlin in my venv.. dependencies or something.

**Comment by currenttime** [comment]
same error on v0.2.7

**Comment by Quest79** [comment]
Sill an issue.

**Comment by se7enth** [comment]
same error  after update today,   and it would  fixed when disable all custom nodes. But I only update comfyui... and not happened before. 


pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
Using xformers attention
ComfyUI version: 0.3.14
### Loading: ComfyUI-Manager (V3.17.10)
### ComfyUI Version: v0.3.14-19-g1d5d658 | Released on '2025-02-12'


2025-02-13 07:00:36,701- root:397- ERROR- Traceback (most recent call last):
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\nodes.py", line 1608, in save_images
    i = 255. * image.cpu().numpy()
TypeError: Got unsupported ScalarType BFloat16
