### ISSUE TITLE
[ feature ] improve Flux-dev-de-distill model performance ( with cfg > 1 )

### ISSUE THREAD

**Issue by JorgeR81** [comfyanonymous/ComfyUI#5234]
### Feature Idea

This de-distilled model gives great results, but it uses cfg > 1, instead of Flux Guidance.
https://huggingface.co/nyanko7/flux-dev-de-distill

But a cfg > 1, makes the generation significatively slower.
Can this be optimized ?

### Existing Solutions

.

### Other

I tried the Q8_0 version, but I think the other versions have the same issue. 
https://huggingface.co/TheYuriLover/flux-dev-de-distill-GGUF

**Comment by comfyanonymous** [comment]
When CFG is not 1.0 it needs to run the model once for the positive and once for the negative prompt so it might slow down generations up to 2x which is normal.

**Comment by JorgeR81** [comment]
Yes, that's about my speed decrease.
