### ISSUE TITLE
About the unCLIPConditioning node

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#5244]
### Your question

I'm trying the unCLIPConditioning node to use image as conditioning. but the result seems too far away from expected.

![workflow](https://github.com/user-attachments/assets/6c1c6770-3fe4-407b-a791-08e66713dc33)

Is there something wrong with the workflow or the unCLIPConditioning node is just bad at conditioning?

The image has workflow embeded. Have tried several other base models.

**Comment by LukeG89** [comment]
Seems you need to use specific UnClip checkpoints in order to use UnClipConditioning:
https://comfyanonymous.github.io/ComfyUI_examples/unclip/

**Comment by pandayummy** [comment]
Thank you.
