### ISSUE TITLE
How to configure "extra_model_paths.yaml" for xlabs models?

### ISSUE THREAD

**Issue by ClothingAI** [comfyanonymous/ComfyUI#5248]
### Your question

Xlabs models (https://github.com/XLabs-AI/x-flux-comfyui) explian to us that models shall be put inside this path: 
**ComfyUI/models/xlabs/loras** and **ComfyUI/models/xlabs/controlnets**

I would like to have the models in another path, could you tell me if it's possible to do it with the yaml file?
I tried to create a new entry like this:

> ....
> vae: models/vae/
> xlabs: ..._\models\xlabs

It did not work that great!
Ho to configure it what to write in the yaml?
![image](https://github.com/user-attachments/assets/68caeb55-07c7-42cf-84d1-03a71f838574)

Btw this is how it looks in base install:

![image](https://github.com/user-attachments/assets/3ba26801-a32a-4a53-9a43-9f19abadbd14)

**Comment by Yaiol** [comment]
you can use the standard windows mklink command which is much more versatile than the yaml file
move all xlabs files to [xlabs-path]
cd models
mklink /d xlabs [xlabs-path]
for instance mklink /d xlabs d:\models\xlabs

**Comment by ClothingAI** [comment]
my machine does not allow this.

**Comment by LukeG89** [comment]
I'm not an expert, but if you have already set the base path, you need to add a relative path to the xlab folder.

Have you tried this way?

```
    xlabs: models/xlabs
```
If it doesn't work I would also try something like that:

```
    xlabs: |
         models/xlabs/flux
         models/xlabs/loras
         models/xlabs/controlnets
         models/xlabs/ipadapters
```

(I just copied these formats from the yaml file)

**Comment by ClothingAI** [comment]
I just noticed that I tried this: 
`xlabs: models\xlabs`
and it should have beedn \ instead of /
but doubt it would work

**Comment by LukeG89** [comment]
> I just noticed that I tried this:
> xlabs: models\xlabs
> and it should have been \ instead of /
> but doubt it would work, because there are some codes related to these in nodes.py or and config paths scripts etc

Yeah, it should work both ways. 

If changing `\` to `/` didn't work, I would also give a chance to this format as a last attempt:

```
    xlabs: |
         models/xlabs/flux
         models/xlabs/loras
         models/xlabs/controlnets
         models/xlabs/ipadapters
```

**Comment by ClothingAI** [comment]
I think there should be some changes in **folder_paths.py** and nodes.py (from main comfy) to accompany these changes. I tried with ChatGPT but could not find a good working solution.

**Comment by ltdrdata** [comment]
> I think there should be some changes in **folder_paths.py** and nodes.py (from main comfy) to accompany the yaml changes. I tried with ChatGPT but could not find a good working solution.

Is this symptom happening after updating ComfyUI?

**Comment by lldacing** [comment]
![image](https://github.com/user-attachments/assets/71f6696a-b979-49f0-b461-5bab0c3d4629)

You can try xlabs_controlnets
