### ISSUE TITLE
Impossible to create SUBDIRECTORIES insides "\models\unets"..

### ISSUE THREAD

**Issue by ClothingAI** [comfyanonymous/ComfyUI#5249]
### Expected Behavior

So I was installing some GGUF model (from here: https://huggingface.co/city96/FLUX.1-dev-gguf/tree/main), and it seems they should be added to unet subdirectory.
Which I configured with the yaml file.
I had it inside a subfolder :
models\unet\GGUF_something
It was not read.
I moved it to models\unet and it was recongized after restart.

### Actual Behavior

models\unet\subDirectory is not recongize by Unet Loader GGUF node. (This is probbaly related to ComfyUI)

### Steps to Reproduce

Install one of the gguf models and put it inside models\unet\subDirectory
Open the webserver and load Unet Loader (GGUF), 
You can see that the model does not appear unless you put it inside models\unet directy without any subdirectory.

### Debug Logs

```powershell
.
```

**Comment by LukeG89** [comment]
I think this is an issue with `Unet Loader (GGUF)` because I can see the subdirectories in `Load Diffusion Model`

You should move this bug report to [ComfyUI-GGUF](https://github.com/city96/ComfyUI-GGUF) repo.

**Comment by ClothingAI** [comment]
ok done.

**Comment by LukeG89** [comment]
Ah, and also I know that ComfyUI recently changed the `unet` folder to `diffusion_models` folder.
I think you have to move all your models in the new directory.
See this: https://github.com/city96/ComfyUI-GGUF/issues/39

**Comment by ClothingAI** [comment]
Already did that:
![image](https://github.com/user-attachments/assets/9cbaec21-af46-4572-829f-a49d95e39198)

**Comment by ltdrdata** [comment]
> So I was installing some GGUF model (from here: https://huggingface.co/city96/FLUX.1-dev-gguf/tree/main), and it seems they should be added to unet subdirectory.
> Which I configured with the yaml file.
> I had it inside a subfolder :
> models\unet\GGUF_something
> It was not read.
> I moved it to models\unet and it was recongized after restart.

gguf's directory should be specified `unet_gguf` instead of `diffusion_models` in extra_model_paths.yaml.
