### ISSUE TITLE
Feed images when clicked to Preview are overlapped by the feed

### ISSUE THREAD

**Issue by anonymousoneday** [comfyanonymous/ComfyUI#5252]
### Feature Idea

![image](https://github.com/user-attachments/assets/931c558d-75c7-4a5a-83e8-6451713584fc)

large images when viewed from the feed are shown full size.  I suggest 2 new features:

1.  Auto sizing the image to fit the screen with # 2 taken into account.

2.  Centering to fit in the middle where the middle is marked from the top of the feed (bottom) to the top of the web browser.

Right now about 15% of the image is blocked off the bottom by the feed enabled with an image of 1024 hight.

Shrinking the feed helps but not perfered.

As always - LOVE comfyui !!!  Excellent program !!

### Other

This is a wish list, nothing is broken

**Comment by LukeG89** [comment]
Image Feed extension comes from [ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts), you should move your issue there

**Comment by anonymousoneday** [comment]
@LukeG89 THank you - will do
