### ISSUE TITLE
ImageCompositeMasked - Exception when validating inner node - Output will be ignored

### ISSUE THREAD

**Issue by GPU-server** [comfyanonymous/ComfyUI#5253]
### Your question

What can I inspect to find a solution?
its a faceswap workflow

This is the Node (faceX) that says (Exception when validating inner node: '173') :
![image](https://github.com/user-attachments/assets/a215b722-cb41-424c-bb51-c71143d39489)

**Comment by ltdrdata** [comment]
Please move this issue to mape-Helpers repo.
https://github.com/mape/ComfyUI-mape-Helpers
