### ISSUE TITLE
新版本连线

### ISSUE THREAD

**Issue by tangyuming99** [comfyanonymous/ComfyUI#5257]
![微信图片_20241016210320](https://github.com/user-attachments/assets/cfb85721-a829-4c61-957e-4826be1c6f55)
![image](https://github.com/user-attachments/assets/4ef368cb-ca1d-4cf0-b21d-f6b45b60cede)

**Comment by yoland68** [comment]
Is this only an issue for the new version? Can you paste your About Info here?
<img width="259" alt="Screenshot 2024-10-16 at 8 57 00 AM" src="https://github.com/user-attachments/assets/2ffe1ab3-ce8b-4178-b208-3b640ce69995">

**Comment by tangyuming99** [comment]
已经解决了，是网页缩放的问题，新版就会，旧版不会，也有可能是我电脑的问题。
![微信图片_20241017133843](https://github.com/user-attachments/assets/69be9690-9104-40d6-a613-4cb1041046a6)

**Comment by VitoChenLY** [comment]
try update mixlab node to latest version

**Comment by VitoChenLY** [comment]
您的信件已收到，我会尽快回复，谢谢。
