### ISSUE TITLE
How to update the version when using ComfyUI_ windows_portable_nvidia.7z

### ISSUE THREAD

**Issue by JoeanAmier** [comfyanonymous/ComfyUI#5258]
### Your question

I am using ComfyUI_ windows_portable_nvidia.7z. How can I update if there are new versions in the future? Is it downloading a compressed file and decompressing it to overwrite the old file?

**Comment by yoland68** [comment]
You need to double click on `update_comfyui_stable.bat` (stable) or `update_comfyui.bat` (nightly). It actually just pulls in the code without redownloading the 7z file.
