### ISSUE TITLE
clip missing: ['text_projection.weight']

### ISSUE THREAD

**Issue by GPU-server** [comfyanonymous/ComfyUI#5260]
### Your question
I am getting: 
**clip missing: ['text_projection.weight']**

In a workflow that has flux and sdxl a the same time:
![image](https://github.com/user-attachments/assets/eadfcba4-fac3-4081-8ec7-6383d26553f0)

I wonder what is problem

**Comment by Maevertigo** [comment]
I have the same problem in Flux FP8 Dev, but if I run GGUF there is no problem.

**Comment by GPU-server** [comment]
I can simply replace "Load Diffusion Model" with GGUF node, and I can keep the rest of the workflows as is? Nothign else to change? if yes, please inform me. @Maevertigo

**Comment by Maevertigo** [comment]
> I can simply replace "Load Diffusion Model" with GGUF node, and I can keep the rest of the workflows as is? Nothign else to change? if yes, please inform me. @Maevertigo

Change clip_I.safetensors this is the problem whit [CLIP-GmP-ViT-L-14](https://huggingface.co/zer0int/CLIP-GmP-ViT-L-14) no have problem.

**Comment by GPU-server** [comment]
Can you show me your workflow if you dont mind? :)  (you can modify it before sending if you want, i just want t workign part of that part)

**Comment by Maevertigo** [comment]
> Can you show me your workflow if you dont mind? :) (you can modify it before sending if you want, i just want t workign part of that part)
[Civitai guide](https://education.civitai.com/quickstart-guide-to-flux-1/)
[Flux GGUF text2img Workflow](https://education.civitai.com/wp-content/uploads/2024/08/Flux-GGUF-text2img-Workflow.zip)

**Comment by Tanglinling** [comment]
My background also has this error, but the workflow works. Other cilp related error messages are: DualCLIPLoader 64:
- Value not in list: clip_name2:  'clip_l.safetensors' not in ['model.fp16.safetensors', 'siglip-so400m-patch14-384\\model.safetensors',  'stable-diffusion-2-1-clip-fp16.safetensors', 'text_encoders\\ViT-L-14-TEXT-detail-improved-hiT-GmP-HF.safetensors',  'text_encoders\\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors', 'text_encoders\\clip_g.safetensors',  'text_encoders\\clip_l.safetensors', 'text_encoders\\t5xxl_fp16.safetensors',  'text_encoders\\t5xxl_fp8_e4m3fn.safetensors']
- Value not in list: clip_name1:  't5xxl_fp16.safetensors' not in ['model.fp16.safetensors', 'siglip-so400m-patch14-384\\model.safetensors',  'stable-diffusion-2-1-clip-fp16.safetensors', 'text_encoders\\ViT-L-14-TEXT-detail-improved-hiT-GmP-HF.safetensors',  'text_encoders\\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors', 'text_encoders\\clip_g.safetensors',  'text_encoders\\clip_l.safetensors', 'text_encoders\\t5xxl_fp16.safetensors',  'text_encoders\\t5xxl_fp8_e4m3fn.safetensors']
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details':  '', 'extra_info': {}}
![{6C4D7303-DEE2-4FBA-99A1-7B2AC2317481}](https://github.com/user-attachments/assets/41bdaef5-bd01-4e4e-8ab7-be6d6e666317)

**Comment by GPU-server** [comment]
> My background also has this error, but the workflow works. Other cilp related error messages are: DualCLIPLoader 64:
> 
> * Value not in list: clip_name2:  'clip_l.safetensors' not in ['model.fp16.safetensors', 'siglip-so400m-patch14-384\model.safetensors',  'stable-diffusion-2-1-clip-fp16.safetensors', 'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-HF.safetensors',  'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors', 'text_encoders\clip_g.safetensors',  'text_encoders\clip_l.safetensors', 'text_encoders\t5xxl_fp16.safetensors',  'text_encoders\t5xxl_fp8_e4m3fn.safetensors']
> * Value not in list: clip_name1:  't5xxl_fp16.safetensors' not in ['model.fp16.safetensors', 'siglip-so400m-patch14-384\model.safetensors',  'stable-diffusion-2-1-clip-fp16.safetensors', 'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-HF.safetensors',  'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors', 'text_encoders\clip_g.safetensors',  'text_encoders\clip_l.safetensors', 'text_encoders\t5xxl_fp16.safetensors',  'text_encoders\t5xxl_fp8_e4m3fn.safetensors']
>   Output will be ignored
>   invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details':  '', 'extra_info': {}}
>   ![{6C4D7303-DEE2-4FBA-99A1-7B2AC2317481}](https://private-user-images.githubusercontent.com/146339730/378207585-41bdaef5-bd01-4e4e-8ab7-be6d6e666317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDc3NzIsIm5iZiI6MTcyOTQ0NzQ3MiwicGF0aCI6Ii8xNDYzMzk3MzAvMzc4MjA3NTg1LTQxYmRhZWY1LWJkMDEtNGU0ZS04YWI3LWJlNmQ2ZTY2NjMxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxODA0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzNhYmUzNTM3MGIwNDYxMzY3OWIwM2UwNTMzNGUyOGQ5YjE4NjJhYTc0MTlkMDM3ZjJmMjE0NmQ1ZThiYWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6e7eM6DDkJnY32I9uAZsJ0Eqls0wjB98DsGQxXVbTgM)

@Tanglinling  if you are able to make it work, please tell me. I am also interested.

**Comment by Tanglinling** [comment]
> > My background also has this error, but the workflow works. Other cilp related error messages are: DualCLIPLoader 64:
> > 
> > * Value not in list: clip_name2:  'clip_l.safetensors' not in ['model.fp16.safetensors', 'siglip-so400m-patch14-384\model.safetensors',  'stable-diffusion-2-1-clip-fp16.safetensors', 'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-HF.safetensors',  'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors', 'text_encoders\clip_g.safetensors',  'text_encoders\clip_l.safetensors', 'text_encoders\t5xxl_fp16.safetensors',  'text_encoders\t5xxl_fp8_e4m3fn.safetensors']
> > * Value not in list: clip_name1:  't5xxl_fp16.safetensors' not in ['model.fp16.safetensors', 'siglip-so400m-patch14-384\model.safetensors',  'stable-diffusion-2-1-clip-fp16.safetensors', 'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-HF.safetensors',  'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors', 'text_encoders\clip_g.safetensors',  'text_encoders\clip_l.safetensors', 'text_encoders\t5xxl_fp16.safetensors',  'text_encoders\t5xxl_fp8_e4m3fn.safetensors']
> >   Output will be ignored
> >   invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details':  '', 'extra_info': {}}
> >   ![{6C4D7303-DEE2-4FBA-99A1-7B2AC2317481}](https://private-user-images.githubusercontent.com/146339730/378207585-41bdaef5-bd01-4e4e-8ab7-be6d6e666317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDc3NzIsIm5iZiI6MTcyOTQ0NzQ3MiwicGF0aCI6Ii8xNDYzMzk3MzAvMzc4MjA3NTg1LTQxYmRhZWY1LWJkMDEtNGU0ZS04YWI3LWJlNmQ2ZTY2NjMxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxODA0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzNhYmUzNTM3MGIwNDYxMzY3OWIwM2UwNTMzNGUyOGQ5YjE4NjJhYTc0MTlkMDM3ZjJmMjE0NmQ1ZThiYWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6e7eM6DDkJnY32I9uAZsJ0Eqls0wjB98DsGQxXVbTgM)
> 
> @Tanglinling if you are able to make it work, please tell me. I am also interested.

I didn't fix the error, but it doesn't seem to affect use
![image](https://github.com/user-attachments/assets/b266596e-78dc-476a-9515-9d01f7dc62d0)

**Comment by GPU-server** [comment]
> > > My background also has this error, but the workflow works. Other cilp related error messages are: DualCLIPLoader 64:
> > > 
> > > * Value not in list: clip_name2:  'clip_l.safetensors' not in ['model.fp16.safetensors', 'siglip-so400m-patch14-384\model.safetensors',  'stable-diffusion-2-1-clip-fp16.safetensors', 'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-HF.safetensors',  'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors', 'text_encoders\clip_g.safetensors',  'text_encoders\clip_l.safetensors', 'text_encoders\t5xxl_fp16.safetensors',  'text_encoders\t5xxl_fp8_e4m3fn.safetensors']
> > > * Value not in list: clip_name1:  't5xxl_fp16.safetensors' not in ['model.fp16.safetensors', 'siglip-so400m-patch14-384\model.safetensors',  'stable-diffusion-2-1-clip-fp16.safetensors', 'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-HF.safetensors',  'text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors', 'text_encoders\clip_g.safetensors',  'text_encoders\clip_l.safetensors', 'text_encoders\t5xxl_fp16.safetensors',  'text_encoders\t5xxl_fp8_e4m3fn.safetensors']
> > >   Output will be ignored
> > >   invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details':  '', 'extra_info': {}}
> > >   ![{6C4D7303-DEE2-4FBA-99A1-7B2AC2317481}](https://private-user-images.githubusercontent.com/146339730/378207585-41bdaef5-bd01-4e4e-8ab7-be6d6e666317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDc3NzIsIm5iZiI6MTcyOTQ0NzQ3MiwicGF0aCI6Ii8xNDYzMzk3MzAvMzc4MjA3NTg1LTQxYmRhZWY1LWJkMDEtNGU0ZS04YWI3LWJlNmQ2ZTY2NjMxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxODA0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzNhYmUzNTM3MGIwNDYxMzY3OWIwM2UwNTMzNGUyOGQ5YjE4NjJhYTc0MTlkMDM3ZjJmMjE0NmQ1ZThiYWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6e7eM6DDkJnY32I9uAZsJ0Eqls0wjB98DsGQxXVbTgM)
> > 
> > 
> > @Tanglinling if you are able to make it work, please tell me. I am also interested.
> 
> I didn't fix the error, but it doesn't seem to affect use ![image](https://private-user-images.githubusercontent.com/146339730/378215677-b266596e-78dc-476a-9515-9d01f7dc62d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDg3NDQsIm5iZiI6MTcyOTQ0ODQ0NCwicGF0aCI6Ii8xNDYzMzk3MzAvMzc4MjE1Njc3LWIyNjY1OTZlLTc4ZGMtNDc2YS05NTE1LTlkMDFmN2RjNjJkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxODIwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2NlN2YzNWI5MzdiMjNmMDg3MzdkYWU3NjEyMGJkZWRkMmNmYTE0MGU4YzY1NTIwMmNjZGUwNjNmNzNiNDA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4uPXR6Tb4RNqUbywbturoK74z42E8vzVuydXyiPyrBg)

But In this one there is no input!
If you are able to make the input (from the first image/workflow) work then inform me please.

**Comment by ltdrdata** [comment]
duplication: https://github.com/comfyanonymous/ComfyUI/issues/5222

**Comment by VEGETABLET** [comment]
To sum up, I tried both GGUF and modified clip:

download this https://huggingface.co/city96/FLUX.1-dev-gguf/blob/main/flux1-dev-Q8_0.gguf and use it with GGUF custom nodes (instead of flux_dev)

cought this error:
File "Z:\Program Files\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 151, in _get
    .newbyteorder(override_order or self.byte_order)
     ^^^^^^^^^^^^
AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

solved this way:
https://github.com/ggerganov/llama.cpp/issues/9021#issuecomment-2392935229

download this https://huggingface.co/zer0int/CLIP-GmP-ViT-L-14/blob/main/ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors and use it instead of clip_l.safetensors

worked!

**Comment by GPU-server** [comment]
> To sum up, I tried both GGUF and modified clip:
> 
> download this https://huggingface.co/city96/FLUX.1-dev-gguf/blob/main/flux1-dev-Q8_0.gguf and use it with GGUF custom nodes (instead of flux_dev)
> 
> cought this error: File "Z:\Program Files\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 151, in _get .newbyteorder(override_order or self.byte_order) ^^^^^^^^^^^^ AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.
> 
> solved this way: [ggerganov/llama.cpp#9021 (comment)](https://github.com/ggerganov/llama.cpp/issues/9021#issuecomment-2392935229)
> 
> download this https://huggingface.co/zer0int/CLIP-GmP-ViT-L-14/blob/main/ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors and use it instead of clip_l.safetensors
> 
> worked!

Thank you!

**Comment by BassJMagan** [comment]
Getting same error on SD3.5, but I don't think it really means anything?

**Comment by VEGETABLET** [comment]
> Getting same error on SD3.5, but I don't think it really means anything?

That means, it's a global problem with some comfyui updates. I thought that happens only with Flux clip/model... Hope that would be fixed soon 😓

**Comment by aalleexx5** [comment]
> > I can simply replace "Load Diffusion Model" with GGUF node, and I can keep the rest of the workflows as is? Nothign else to change? if yes, please inform me. @Maevertigo
> 
> Change clip_I.safetensors this is the problem whit [CLIP-GmP-ViT-L-14](https://huggingface.co/zer0int/CLIP-GmP-ViT-L-14) no have problem.
> 
> In GGUF workflows whit clip_I.safetensors no have problem.

This not only worked but the "smooth" version also improved images too.

**Comment by BassJMagan** [comment]
does that same fix work for stable diffusion 3.5 large? same error. same clip-l i think.

**Comment by jun8456** [comment]
Hello I'm having this same issue did you ever figure out the solution?
