### ISSUE TITLE
Prompt Outputs failed validation Checkpoint loader simple Value not in list

### ISSUE THREAD

**Issue by ZaEvab55555** [comfyanonymous/ComfyUI#5263]
### Your question

Hi, when I try to generate an image, it always says that the prompt outputs failed validation. What did I do wrong? 

### Other

![image](https://github.com/user-attachments/assets/54d2fc74-74ce-43d4-b55e-2b418718be1b)
This is what I was talking about.

**Comment by LukeG89** [comment]
I think you simply don't have the model in your `models/checkpoints` folder.

**Comment by ZaEvab55555** [comment]
Sorry, how should I get the model? I watched a tutorial but it didn't say anything about it.

**Comment by ZaEvab55555** [comment]
Do you have any recommendations?

**Comment by ZaEvab55555** [comment]
On which one I should use?

**Comment by Jimmvision** [comment]
I have loaded the model checked the version and get the same error still any suggestions?

**Comment by ltdrdata** [comment]
> I have loaded the model checked the version and get the same error still any suggestions?

There are 2 possibiliites.

One case is when the model is placed in the specified location but not refreshed, and the other case is when the **ComfyUI-Flow-Control** node pack is installed.

**Comment by abream1127** [comment]
Prompt outputs failed validation:
UNETLoader:
- Value not in list: unet_name: 'wan2.1_t2v_1.3B_fp16.safetensors' not in []
CLIPLoader:
- Value not in list: clip_name: 'umt5_xxl_fp8_e4m3fn_scaled.safetensors' not in []
VAELoader:
- Value not in list: vae_name: 'wan_2.1_vae.safetensors' not in []
Hi, when I try to generate a video, it always says that the prompt outputs failed validation. What did I do wrong?
my models/checkpoints folder have v1-5-pruned-emaonly-fp16.safetensors.
