### ISSUE TITLE
ComfyUI crashes at KSampler after loading LoCon/LoHa

### ISSUE THREAD

**Issue by sbstratos79** [comfyanonymous/ComfyUI#527]
Works fine with LoRA, but loading a LoCon or LoHa and running a KSampler increases the cpu usage and memory usage dramatically and then the script crashes. KSampler doesn't even get to the sampling stage. The moment its border turns green, cpu/ram usage spikes and after some time ComfyUI just terminates without any errors.

My pc is low-end so other users might not face this issue. I have 4GB VRAM and 8GB RAM.
I can generate ~1400px images with high res fix without any issues, so it's not unreasonable to expect that I should be able to generate a 512x640 image with a LoCon/LoHa.

I have tested these LoHa/LoCon files with stable-diffusion-webui on Google Colab, so the files aren't corrupted.

**Comment by comfyanonymous** [comment]
Can you give me an example of a lora that works and a loha/locon that causes the issue?

Locon/loha patch more things in the model which is why they take a bit more ram.

**Comment by sbstratos79** [comment]
LoHa: https://civitai.com/models/27995/hitoimim-style-loha
LoRA: https://civitai.com/models/8429/helltaker-lora

For me, all LoRAs work. 
No LoHA/LoCon works.

**Comment by comfyanonymous** [comment]
Is it running out of regular ram or vram?

**Comment by sbstratos79** [comment]
Regular RAM.

**Comment by sbstratos79** [comment]
Update: It's working. It's a little slower than LoRA but at least the cpu/ram usage doesn't shoot up too significantly. I still don't know the cause.
