### ISSUE TITLE
About not print start success information in the terminal.

### ISSUE THREAD

**Issue by yaosheng216** [comfyanonymous/ComfyUI#5271]
### Expected Behavior

Hi, author.
Thanks for your contribution. I met a problem during of development custom node.
In the custom node invoke dependent module，comfyui start not print success information in the terminal, but comfyui page can be accessed to and custom node can load success. Can you know this problem.

Wish you can solve this problem help me.

<img width="1434" alt="截屏2024-10-18 10 30 17" src="https://github.com/user-attachments/assets/213b6e0e-5baa-493d-8122-1bc2d397e4ef">

### Actual Behavior

Start ComfyUI not print success information, but ComfyUI page can be be accessed to and custom node can load success.

### Steps to Reproduce

Load custom node, start ComfyUI, not print success information in the terminal.

### Debug Logs

```powershell
Total VRAM 81093 MB, total RAM 125402 MB
pytorch version: 2.4.1+cu121
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A100-SXM4-80GB : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: /home/yaosheng/comfyui/ComfyUI/web
/home/yaosheng/.local/lib/python3.10/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
2024-10-18 10:29:31,801 - modelscope - INFO - PyTorch version 2.4.1+cu121 Found.
2024-10-18 10:29:31,802 - modelscope - INFO - Loading ast index from /home/yaosheng/.cache/modelscope/ast_indexer
2024-10-18 10:29:31,827 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 b703851ea6c59e32c5b86055528381a2 and a total number of 976 components indexed
PyTorch version 2.4.1+cu121 available.
JAX version 0.4.31 available.
```

**Comment by ltdrdata** [comment]
First, if it's certain that the connection is not possible when the instance is terminated, an additional point to check is that there's an issue with certain outdated versions of ComfyUI-Manager where logs are not displayed on the screen.
