### ISSUE TITLE
C;\ is being used when comfyui is running, then liberated when comfyui is shut down.

### ISSUE THREAD

**Issue by ClothingAI** [comfyanonymous/ComfyUI#5279]
### Your question

My device went as low as:
![image](https://github.com/user-attachments/assets/201db009-fdb8-48bb-beba-d4e865bb75c1)
When running a workflow related to pulid: https://github.com/cubiq/PuLID_ComfyUI/issues/93
As you can see in that issue I was trying different configurations of models versions trying to make it work (still don't know which config works)

____

When I closed comfyui, it went back to:
![image](https://github.com/user-attachments/assets/865fd980-d9ea-4fb4-86d3-e10d1192dc2c)

____

How can I tell ComfyUI **to not use** memory from C:\?

BTW, the running comfyui I was using was located in another disk than C.
Also my cache base path for huggingFace stuff is outside C normally. 
So I don't know..

**Comment by ltdrdata** [comment]
The rapid decrease in C: drive capacity while ComfyUI is running is typically due to insufficient RAM, causing swap to occur.
Please check this.
