### ISSUE TITLE
Configuring insightface model paths with yaml  file

### ISSUE THREAD

**Issue by ClothingAI** [comfyanonymous/ComfyUI#5280]
### Expected Behavior

Leaving ComfyUI\models\insightface empty, whereas having an external path to the actual localization of the models, via .yaml file:

```
comfyui:
    base_path: ExternalPath
    ...
    pulid: models/pulid/
    insightface: |
        models/insightface/models/antelopev2/
        models/insightface/models/
        models/insightface/
        models/
```

and actually having the models in 
ExternalPath\models\insightface

Should be enough to make comfy recognize the insightface models.

### Actual Behavior

Despite configuring the yaml file and having the insightface models in the external pointed path,
anytime Insightface is called in a workflow, the file "antelopev2.zip" is downloaded and put inside the original model path: ComfyUI\models\insightface\models 
then its unzipped to give:
ComfyUI\models\insightface\models\antelopev2
But it fails to work anyway. (But that besides the points)
The point here is that yaml file configuration would not work, unless I miss configured it?

### Steps to Reproduce

install comfyui
install pulid from https://github.com/cubiq/PuLID_ComfyUI
Make sure it is correclty installed with everything needed (insightface etc)
Run the workflow from the examples folder: "pulid_flux_16bit_simple.json"
configure yaml with external path and all the correct insightface models inside the external path.
When the insightface part is reached in the workflow, you will observe an error and downloading of antelopev2.zip.
If you put all the correct models inside the regular path (of comfy \ models etc) you will not have an error.

### Debug Logs

```powershell
.
```

**Comment by ltdrdata** [comment]
Please this issue to PuLID_ComfyUI repo.
https://github.com/cubiq/PuLID_ComfyUI

**Comment by ClothingAI** [comment]
But isnt the yaml related to main comfy files such as path files py etc?

**Comment by ltdrdata** [comment]
> But isnt the yaml related to main comfy files such as path files py etc?

`insightface` is not a model supported by ComfyUI core, and configuration extensions for `extra_model_paths.yaml` can be added in custom nodes.

Therefore, it is correct for the custom node that uses this path to provide it.
