### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled even after re-installing torch

### ISSUE THREAD

**Issue by chamidusuraweera** [comfyanonymous/ComfyUI#5281]
### Your question

Hi everyone,

I’m encountering an AssertionError stating that "Torch not compiled with CUDA enabled" despite having reinstalled PyTorch. Here are my system specifications:

- Laptop Model: Dell G5 5500
- GPU: NVIDIA GeForce RTX 2070
- Windows Version: 24H2
- CUDA Version: 12.7

Current Versions:
- Python: 3.12.0
- pip: 23.2.1
- xformers: 0.0.27

Has anyone experienced this issue and found a solution? Any help would be greatly appreciated!
Thank you!

![Screenshot 2024-10-19 003159](https://github.com/user-attachments/assets/f66e36bb-9633-42a4-9c51-4d96940d78ea)

**Comment by LukeG89** [comment]
I think you need to: 

Uninstall xformers

```
pip uninstall xformers
```
Uninstall pytorch
```
pip uninstall torch torchvision torchaudio
```
And then reinstall both pytorch and the compatible xformers with this command:
```
pip install torch torchvision torchaudio xformers --extra-index-url https://download.pytorch.org/whl/cu124
```
