### ISSUE TITLE
SamplerCustomAdvanced Error

### ISSUE THREAD

**Issue by nishanthr227** [comfyanonymous/ComfyUI#5288]
### Your question

[workflow sample.json](https://github.com/user-attachments/files/17445136/workflow.sample.json)

![Screenshot 2024-10-19 170700](https://github.com/user-attachments/assets/2d8459a0-be1c-4dd3-9f9a-046ec8bbaed0)

![Screenshot 2024-10-19 170644](https://github.com/user-attachments/assets/186482f4-afd6-4e8d-8f68-1059dea2f856)

**Comment by LukeG89** [comment]
I think it goes out of memory because you set 19 in "repeat", so a batch of 19 images (and with Flux is a lot):

![repeat_image](https://github.com/user-attachments/assets/8a5efef3-9993-4f93-b9df-f17d4ff1ca59)
