### ISSUE TITLE
Creating Folders with the "/" Symbol in its Name Breaks the Bookmark Feature of the Node Library

### ISSUE THREAD

**Issue by tiosolid** [comfyanonymous/ComfyUI#5292]
### Expected Behavior

Creating a folder with a "/" character in its name ( like "Image I/O" for example) should not break the bookmark feature and be allowed.

### Actual Behavior

Creating a folder with a "/" character in its name ( like "Image I/O" for example) crashes the whole functionality of bookmarks in the Node Library

### Steps to Reproduce

1. Expand the Node Library from the sidebar
2. Inside the Node Library, click the "New Folder" button on the top right 
![image](https://github.com/user-attachments/assets/75595503-07b2-4f5e-aac5-494dfb3ae7e6)
3. Give the new folder a name that has the slash character "/" in it, for example "Image I/O" and confirm 
![image](https://github.com/user-attachments/assets/aa01f60b-1734-4c61-9eb7-46d917a11ac4)
4. As soon as the action is confirmed, the whole top side of the node explorer (that contains the actual bookmarks) disappears and an Exception appears in the BROWSERS dev log 
![image](https://github.com/user-attachments/assets/e553ff31-fab1-41d0-8762-031b2bd6f28d)

> settingStore.ts
```typescript
TypeError: Cannot read properties of undefined (reading 'nodePath')
    at Object.getIcon (NodeBookmarkTreeExplorer.vue:147:64)
    at getTreeNodeIcon (TreeExplorer.vue:69:23)
    at fillNodeInfo (TreeExplorer.vue:90:11)
    at Array.map (<anonymous>)
    at TreeExplorer.vue:65:22
    at ReactiveEffect.fn (reactivity.esm-bundler.js:990:13)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:19)
    at get value (reactivity.esm-bundler.js:1002:102)
    at Proxy.<anonymous> (TreeExplorer.vue:181:2)
    at renderComponentRoot (runtime-core.esm-bundler.js:887:16)
```

The button "New Folder" continues working and it creates the new folders, but not give you the chance to set a name since the whole tree list has disappeared (but you can see the folders in your comfy.settings.json file)

### Debug Logs

```powershell
No error is logged in the console
```

### **Important Secondary Issue with Node Names**
Note that this issue also seems to affect nodes that have a "/" in the name too. The feature doesn't break but if you bookmark a node that has a name like "Some Node / With Slash", it never appears in the main tree list

### How to Temporarily Fix the Issue
* Edit the file ComfyUI\user\defaultcomfy.settings.json
* Find the JSON array property `"Comfy.NodeLibrary.Bookmarks.V2"`
* Search the line with the bad folder name and delete it from the array (fix the comma in the line above if needed)
* Save the file and refresh the ComfyUI frontend. The bookmarks should be back as they should and the feature works again just fine

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by tiosolid** [comment]
> Please move this issue to front repo. https://github.com/Comfy-Org/ComfyUI_frontend

Done! https://github.com/Comfy-Org/ComfyUI_frontend/issues/1272
