### ISSUE TITLE
Resize Group BUG

### ISSUE THREAD

**Issue by OneMonkeyArmy** [comfyanonymous/ComfyUI#5295]
### Expected Behavior

When resizing any group by clicking and holding the bottom right of it.
User should not be able to move the bottom right point above or left of the top left point !!

### Actual Behavior

Because the new highlighted area of this inverted group with title at bottom and adjustment triangle at the top, is no longer adjustable, or also it can't be deleted...

unless User manually edit the workflow json file

### Steps to Reproduce

Reproduce is explain in the first line...

repair: I didn't took the time to check if the groups are delimited by (x1,y1) + (x2,y2)  or  (x , y)+width and height.. but it is the same solutions...

Sol 1:  add a minimum size in x an y of the GROUP area.

Either prevent the user to move the resize corner above or left of the top left corner, 
or let user do it but on MOUSE RELEASE, swap the values or make validations/corrections on them. 

### Debug Logs

```powershell
WORKAROUND FOR USERS: find the ENTRY in the JSON file ( workflow ) and remove or correct it...
```

### Other

An image worth a 1000 words !
![image](https://github.com/user-attachments/assets/f66a0fd1-8850-4ca6-ac08-f945bfa79a8c)

**Comment by LukeG89** [comment]
You should move this issue to the frontend repo: https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by OneMonkeyArmy** [comment]
Do I have to do it manually?  Piece by piece?

**Comment by LukeG89** [comment]
> Do I have to do it manually? Piece by piece?

Unfortunately yes.

**Comment by OneMonkeyArmy** [comment]
then just make a link to here...
