### ISSUE TITLE
[Feature Request] Bring in the 2 samplers made by "Forge Webui"

### ISSUE THREAD

**Issue by GPU-server** [comfyanonymous/ComfyUI#5296]
### Feature Idea

Sampler 1: [Forge] Flux Realistic (Slow)
Sampler 2: [Forge] Flux Realistic

They are quite realistic. I just made comparisons of all samplers, and they are the 2 most impressive ones (quality of Adetailer without adetailer).

**Comment by comfyanonymous** [comment]
Those are already in comfyui. The slow one is just the dpmpp_2s_ancestral sampler. The forge author just obfuscated the code and renamed them because he didn't want people to notice.

**Comment by pellaaa93** [comment]
and which is the other one in comfy?  [Forge] Flux Realistic
