### ISSUE TITLE
What is the right way to run Comfy in API mode?

### ISSUE THREAD

**Issue by TowhidKashem** [comfyanonymous/ComfyUI#5303]
### Your question

I am running comfyui in runpod, I can access the web ui at a url like this:

https://jsqxxxxxxt3q5-8188.proxy.runpod.net/

From the settings menu I enabled dev mode.

Next I downloaded my workflow which was already working in the web ui by clicking "Save (API Format)" format.

Next I made a POST request to:

https://jsqxxxxxxt3q5-8188.proxy.runpod.net/prompt

and for the payload I used the entire api workflow json I downloaded in the previous step.

But I get this response:

```
{
    "error": "no prompt",
    "node_errors": []
}
```

Is there something I am doing wrong? Is the url correct? or perhaps the payload is the issue?

I also tried connecting via web sockets (at the wss:// version instead of https://) and I can't even connect in that case.

**Comment by ltdrdata** [comment]
Have you tried with this script?

https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py

**Comment by TowhidKashem** [comment]
> Have you tried with this script?
> 
> 
> 
> https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py

Yea I did, I think the issue is running comfy on run pod as a "pod" doesn't work with the api like it does when running comfy locally. I found a server less worker for comfy that I think I'll try which is supposed to work in run pod. Thanks anyway.

**Comment by kning** [comment]
what serverless worker did you end up choosing?

**Comment by TowhidKashem** [comment]
> what serverless worker did you end up choosing?

I was actually able to use the api in a regular pod. the problem was my payload shape, if u want a serverless docker image try https://github.com/blib-la/runpod-worker-comfy?tab=readme-ov-file#bring-your-own-models

**Comment by josephrocca** [comment]
For others hitting this thread via search: My issue when getting the "no prompt" error was that I was sending `workflow_json` as the body of the request, when I should have actually been sending: `{prompt:workflow_json}`
