### ISSUE TITLE
設置界面和拖拽彈出搜索菜單卡頓

### ISSUE THREAD

**Issue by ghft665** [comfyanonymous/ComfyUI#5307]
### Your question

我也不清楚這是個例還是什麽問題，就是使用新版界面的時候，點擊設置那裏很卡頓，得等3S左右，關閉也需要等2S。從節點拉出綫彈出搜索界面需要等5S才能正常搜索，選擇節點后也是，還有在界面雙擊的時候需要等3S才出搜索框，關閉也需要等，沒有任何提示，筆記本和臺式機都有這個情況，請問有知道是什麽問題的嗎？

**Comment by gsy111** [comment]
我也有这个问题

**Comment by 8264allan** [comment]
我也有这个问题

**Comment by AiD-teng** [comment]
same issue here. So laggy when use "serach" window

**Comment by PandaBalls** [comment]
我刚升级用起来搜索不会的，就第三天发现搜索输入一个字母需要等好久才能输入第二个，非常卡。
明显的变化条件是我从win10升级到了win11系统。然后comfyui安装了SUPIR和APISR的插件。其他似乎没有改变
I just upgraded and used it to search, but it didn't work. On the third day, I found that it took a long time to enter a letter in the search before entering the second one, which was very slow.
The obvious change condition is that I upgraded from win10 to win11 system. Then comfyui installed the plugins for SUPIR and APISR. Others don't seem to have changed

**Comment by 9l** [comment]
disable AIGODLIKE-ComfyUI-Translation or git checkout AIGODLIKE/AIGODLIKE-ComfyUI-Translation@cf8f9a848e183d8a3f5892afe6a6c5f09767cb2a this commit fix the laggy problem

禁用 AIGODLIKE-ComfyUI-Translation 翻译插件，或者 git checkout AIGODLIKE-ComfyUI-Translation 到 cf8f9a848e183d8a3f5892afe6a6c5f09767cb2a 这个 commit 搜索节点就不卡顿了

**Comment by theshy-tang** [comment]
The only solution is to disable it, the other one is unlikely to work.
