### ISSUE TITLE
FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated.

### ISSUE THREAD

**Issue by TheDarkLordz** [comfyanonymous/ComfyUI#5312]
### Your question

FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.

![image](https://github.com/user-attachments/assets/0a509c9f-8155-4dec-8831-49316dc653ff)

**Comment by LukeG89** [comment]
It's a warning to developers about deprecated features, you can just ignore it.

**Comment by ltdrdata** [comment]
This issue should be addressed in the kornia package repository.
