### ISSUE TITLE
Unable to successfully implement the function of 'convert widget to input

### ISSUE THREAD

**Issue by yatoubusha** [comfyanonymous/ComfyUI#5317]
### Your question

![img_v3_02ft_355adaa8-e9cf-44e2-a45b-77d03156eb5g](https://github.com/user-attachments/assets/6a070129-130a-435a-b4d0-67a66315ac7f)
As shown in the figure, clicking the button does not enable the conversion of this function

**Comment by yatoubusha** [comment]
> Try disabling all custom nodes, refresh, and then try again.
Thank you for your reply, but even after restarting the Comfyui service, the issue still persists,Is there any other way to disable nodes?

**Comment by ltdrdata** [comment]
> Thank you for your reply, but even after restarting the Comfyui service, the issue still persists,Is there any other way to disable nodes?

You can move all custom nodes from ComfyUI/custom_nodes to some other place. Or you can use `--disable-all-custom-nodes`
And since your issue is a front-end issue, you must disable and restart, and then refresh your browser.
