### ISSUE TITLE
incomplete loading of json workflows

### ISSUE THREAD

**Issue by chri002** [comfyanonymous/ComfyUI#5325]
### Expected Behavior

load the workflow with all its components

### Actual Behavior

loads the ‘CLIP text Encoder (prompt)’ without the text inside it, although it is there in the json file.

### Steps to Reproduce

normal loading a workflow or drag and drop a file

### Debug Logs

```powershell
the load not produce any logs
```

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend

@huchenlei This is a phenomenon that has been observed intermittently since before the new front, and it appears to be a race condition issue. Typically, when reloading, it loads normally.

**Comment by chri002** [comment]
No, I tried to reload but the text does not appear, the text just does not arrive to the server. Instead, reloading after an inference sometimes happens that other text disappears.
