### ISSUE TITLE
Error occurred when loading the upscale model

### ISSUE THREAD

**Issue by yatoubusha** [comfyanonymous/ComfyUI#5329]
### Your question

![image](https://github.com/user-attachments/assets/1b113610-d62b-4840-bd5a-ad72c7407be7)
![image](https://github.com/user-attachments/assets/14ea1c1e-a485-431a-a227-367f88ac4eca)
![image](https://github.com/user-attachments/assets/3e9d87f6-3536-4935-b92a-1be38b656e63)

**Comment by CypherReymax96** [comment]
i made this now is it a update

**Comment by CypherReymax96** [comment]
i made this now is it a update

**Comment by yatoubusha** [comment]
> i made this now is it a update

Thank you very much. After upgrading Comfyui, I can now use it normally
