### ISSUE TITLE
SD3.5 clip missing: ['text_projection.weight']

### ISSUE THREAD

**Issue by ialhabbal** [comfyanonymous/ComfyUI#5330]
### Your question

I'm getting the following error with SD3.5: clip missing: ['text_projection.weight']. I had already downloaded the clips from 4 months ago, in the right directory, and loaded in the example workflow from the StabilityAI website. It is generating a vertical thin line of colors.
![Screenshot 2024-10-23 100839](https://github.com/user-attachments/assets/9643c094-5dcb-4cd0-b0d9-0d176625ad08)

### Other

I updated ComfyUI. The clip models and txt clip models were downloaded about 4 months ago and not yesterday from the StabilityAI website.

**Comment by ltdrdata** [comment]
duplicate issue:
https://github.com/comfyanonymous/ComfyUI/issues/5222

**Comment by ltxskyyincha** [comment]
i encounter the same

**Comment by BassJMagan** [comment]
have same issue.
