### ISSUE TITLE
The sidebar is full of chinese characters

### ISSUE THREAD

**Issue by joneschunghk** [comfyanonymous/ComfyUI#5331]
### Expected Behavior

My UI language is English

### Actual Behavior

Too many Chinese characters

### Steps to Reproduce

![sidebar](https://github.com/user-attachments/assets/4ed0ee99-3167-4abe-ab44-22848ea86cb7)

### Debug Logs

```powershell
---
```

**Comment by LukeG89** [comment]
You need to set "en" in Locale.

![locale](https://github.com/user-attachments/assets/9eda7211-cd70-408a-a98e-2efbc4af8311)

**Comment by LukeG89** [comment]
You have and outdated version of the frontend (1.2.26). Update your ComfyUI.
But I warn you, currently the latest frontend is 1.3.11 and they changed a lot of things.

**Comment by ltdrdata** [comment]
Disable all custom nodes and try again.

**Comment by joneschunghk** [comment]
> You have an outdated version of the frontend (1.2.26). Update your ComfyUI. But I warn you, currently the latest frontend is 1.3.11 and they changed a lot of things.

Thank you.
But there's another issus with the new version. The top menu always goes out of the screen.

**Comment by LukeG89** [comment]
> But there's another issus with the new version. The top menu always goes out of the screen.

@joneschunghk What do you mean?

**Comment by joneschunghk** [comment]
> > But there's another issus with the new version. The top menu always goes out of the screen.
> 
> @joneschunghk What do you mean?

Similar to this
![Screenshot 2024-10-26 011519](https://github.com/user-attachments/assets/61b1d8a5-783d-42ef-840d-0d2dc4ce902a)

**Comment by ltdrdata** [comment]
> > > But there's another issus with the new version. The top menu always goes out of the screen.
> > 
> > 
> > @joneschunghk What do you mean?
> 
> Similar to this ![Screenshot 2024-10-26 011519](https://private-user-images.githubusercontent.com/30347563/380441395-61b1d8a5-783d-42ef-840d-0d2dc4ce902a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzA3MDcsIm5iZiI6MTczMDAzMDQwNywicGF0aCI6Ii8zMDM0NzU2My8zODA0NDEzOTUtNjFiMWQ4YTUtNzgzZC00MmVmLTg0MGQtMGQyZGM0Y2U5MDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDEyMDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMTMzYjM4NmFiODZkZjNkZDNmMGUzYmU0MTQ2NzgxZDU1MzliM2FjZGFlYTdkNmE3NjAxYzQ1MDY1ZjgyMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IoopkW-yuWENUI6emgJ2yS5dMpjH0mXj1XV7R6F3HGI)

Please check if this issue also occurs in a fresh install of ComfyUI without any custom nodes.
If the same issue still occurs, please submit an issue to the front repo.

https://github.com/Comfy-Org/ComfyUI_frontend
