### ISSUE TITLE
UI Lag

### ISSUE THREAD

**Issue by AssassinsLament** [comfyanonymous/ComfyUI#5347]
### Expected Behavior

No lag when trying to search for nodes, and clicking UI elements and or changing settings on nodes

### Actual Behavior

There is a lag when there is a good amount of nodes on the screen. If you crop the UI (like make chrome half the size, it doesn't lag), or if you put comfyui's chrome window on a smaller screen size monitor (i have three monitors), then it doesn't lag. When I say lag, i mean sluggish mouse actions, like when you double click to add a node, it opens up the search but when you type in a word, it doesn't find it. It's like it's trying to catch up. Also, if you right click elements and try to change settings, your select click doesn't register, again, because of lag.

### Steps to Reproduce

Open up a workflow that has a good amount of nodes, UI lags.

### Debug Logs

```powershell
There aren't any errors, or even warnings.
```

### Other

I tried reinstalling, I tried removing all nodes, I don't know what it could be. Like I said, it works fine if the UI screen size is made smaller. My screen resolution is 2560x1440. If I change my main monitor's screen resolution to 1920x1080, the UI doesn't lag.

Any ideas?

**Comment by LukeG89** [comment]
I don't know what it could be. But you should open this issue in the frontend repo: [ComfyUI_frontend](https://github.com/Comfy-Org/ComfyUI_frontend)

**Comment by AssassinsLament** [comment]
Ok, I think I figured it out... I had to uninstall, reinstall, disabled all my nodes one by one... I think the culprit is "Use Everywhere (UE Nodes)".  everytime I disable it, it doens't lag. When I enable it, it lags the UI. I don't see any recent changes, so maybe something changed on comfy that borked it. Ok, closing.
