### ISSUE TITLE
How should I add a new sampler?

### ISSUE THREAD

**Issue by areinius** [comfyanonymous/ComfyUI#5348]
### Your question

Added the new sampler using the git command as per the developer's instructions, But this new sampler is not found inside the sampler selection box. I restarted the UI but it still doesn't work.
Here's the GitHub link for the new sampler：
https://github.com/ssitu/ComfyUI_restart_sampling
How do I install this new sampler?
![屏幕截图 2024-10-24 210209](https://github.com/user-attachments/assets/640c9a34-66a5-417c-862e-9eca8758658c)
The installation path should be correct.
![屏幕截图 2024-10-24 211835](https://github.com/user-attachments/assets/3ffa8467-d0b6-4243-8ee9-967c694811c7)

**Comment by LukeG89** [comment]
The sampler is not implemented there.
You need to search for the new nodes: https://github.com/ssitu/ComfyUI_restart_sampling?tab=readme-ov-file#nodes
