### ISSUE TITLE
Not generating images but no errors

### ISSUE THREAD

**Issue by ironico** [comfyanonymous/ComfyUI#5350]
### Your question

After installing a plugin called "crystools" that allows GPU monitoring, I encountered the infamous Windows blue screen than
I restart pc,   removed the plugin, but now ComfyUI blocked when executes the  SamplerCustomNode (for FLux) or KSampler (for sdxl)

No error in console, blocked at 0% progress.

I tried installing new version (git clone/ windows portable or in pinokio env) but I still had the same issue. 

Someone can help me?

Problem whith Ksampler:

![57f79f49-881d-4de1-b065-8fc1f8fb2e91](https://github.com/user-attachments/assets/767e4ada-f19c-4540-8e38-11a51a0cadd8)

### Logs

Problem with Flux:

```powershell
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLUX
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 9319.23095703125 True
Requested to load Flux
Loading 1 new model
loaded completely 0.0 11350.048889160156 True
  0%|                                                      | 0/20 [00:00<?, ?it/s]
```

### Other

[ComfyUI v0.2.4-5-gaf8cf79] 
[ComfyUI_frontend v1.3.11]

Python Version
3.12.7 (tags/v3.12.7:0b05ead, Oct 1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
Embedded Python
true
Pytorch Version
2.5.0+cu124

RAM Total 63.75 GB
RAM Free  37.69 GB

cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VRAM Total
23.99 GB
VRAM Free
2.84 GB
Torch VRAM Total
19.50 GB
Torch VRAM Free
313 MB

**Comment by LukeG89** [comment]
Have you tried reinstalling the Nvidia driver?

**Comment by ironico** [comment]
@LukeG89  I update nvidia driver. Now it's all ok.

thanks
