### ISSUE TITLE
Impact Pack requirements file missing ultralytics

### ISSUE THREAD

**Issue by EmmaShredda** [comfyanonymous/ComfyUI#5368]
### Expected Behavior

impact relies on ultralytics but it's requirements file is missing it. 

### Actual Behavior

it's missing

### Steps to Reproduce

^

### Debug Logs

```powershell
^
```

**Comment by ltdrdata** [comment]
First of all, this is an issue that should be raised in the ComfyUI-Impact-Pack repo, not in ComfyUI.

For ultralytics requirements, when installing through the manager, it's separately supported by the manager, and the requirements.txt definition is in ComfyUI-Impact-Subpack, not in ComfyUI-Impact-Pack.
