### ISSUE TITLE
Node Box Shape

### ISSUE THREAD

**Issue by gobshyte** [comfyanonymous/ComfyUI#5370]
### Expected Behavior

Choosin shape Box for nodes should make them nice and sharp and not bevelly wevelly mushy melting on my eyes

### Actual Behavior

My eyes are not so sharp as the boxes are not sharp

### Steps to Reproduce

Choose shape box
Shape it not box

### Debug Logs

```powershell
no
```

**Comment by gobshyte** [comment]
Apologies but ctrl+a >  Shape > Box has been my thing for ages... How can I line everything up if they are all curvy!

**Comment by gobshyte** [comment]
(Maybe only in the beta thingy)

**Comment by LukeG89** [comment]
Don't worry @gobshyte, this is a temporary issue they are about to fix soon!

**Comment by LukeG89** [comment]
In the meanwhile, you can temporary revert to a previous frontend version by using this argument: `--front-end-version Comfy-Org/ComfyUI_frontend@1.3.10`

**Comment by LukeG89** [comment]
Version 1.3.24 of frontend fixed the issue, and it will probably be released in ComfyUI in about two weeks.

This is the argument for using the nightly versions of frontend, so you can use it right away: `--front-end-version Comfy-Org/ComfyUI_frontend@latest`

**Comment by gobshyte** [comment]
Yay!
