### ISSUE TITLE
Note node doesn't save

### ISSUE THREAD

**Issue by JokerMartini** [comfyanonymous/ComfyUI#5372]
### Expected Behavior

When saving with the API format I would expect the Note node to be including in the file when saving.

### Actual Behavior

Currently when saving a workflow that contains a Note node, it doesn't get included in the Save Api workflow.json file that is generated. It appears to be stripped out entirely.

### Steps to Reproduce

1. Create a workflow
2. Create a Note node with text 
3. Save workflow with Api method

### Debug Logs

```powershell
There are no logs regarding this issue found in the logs.
```

**Comment by huchenlei** [comment]
It is expected behaviour, as not node does affect the API execution.
