### ISSUE TITLE
HivisionIDPhotos-ComfyUI节点无法正常使用：HivisionNode  not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by lyh111901886** [comfyanonymous/ComfyUI#5374]
# ComfyUI Error Report
## Error Details
- **Node Type:** HivisionNode
- **Exception Type:** ValueError
- **Exception Message:** not enough values to unpack (expected 4, got 3)
## Stack Trace
```
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\HivisionIDPhotos-ComfyUI\__init__.py", line 430, in gen_img
    result = creator(input_image, size=size,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\HivisionIDPhotos-ComfyUI\hivision\creator\__init__.py", line 121, in __call__
    self.beauty_handler(ctx)

  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\HivisionIDPhotos-ComfyUI\hivision\plugin\beauty\handler.py", line 46, in beauty_face
    _, _, _, alpha = cv2.split(ctx.matting_image)
    ^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.4-8-gd605677
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices
File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\HivisionIDPhotos-ComfyUI\__init__.py", line 430, in gen_img
    result = creator(input_image, size=size,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\HivisionIDPhotos-ComfyUI\hivision\creator\__init__.py", line 121, in __call__
    self.beauty_handler(ctx)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\HivisionIDPhotos-ComfyUI\hivision\plugin\beauty\handler.py", line 46, in beauty_face
    _, _, _, alpha = cv2.split(ctx.matting_image)
    ^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 3)

2024-10-26 13:54:57,507 - root - INFO - Prompt executed in 0.12 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":29,"last_link_id":35,"nodes":[{"id":20,"type":"PreviewImage","pos":{"0":1161.5999755859375,"1":67.60000610351562},"size":{"0":210,"1":246},"flags":{},"order":4,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":16,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":19,"type":"PreviewImage","pos":{"0":898,"1":60},"size":{"0":210,"1":246},"flags":{},"order":3,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":22,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":26,"type":"HivisionLayOutNode","pos":{"0":392,"1":637},"size":{"0":380.4000244140625,"1":78},"flags":{},"order":6,"mode":0,"inputs":[{"name":"input_img","type":"IMAGE","link":28,"label":"input_img"},{"name":"normal_params","type":"PARAMS","link":35,"label":"normal_params"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[30],"slot_index":0,"shape":3,"label":"IMAGE"},{"name":"4ch_hd_img","type":"IMAGE","links":null,"shape":3,"label":"4ch_hd_img"}],"properties":{"Node name for S&R":"HivisionLayOutNode"},"widgets_values":[]},{"id":27,"type":"PreviewImage","pos":{"0":957,"1":611},"size":{"0":210,"1":246},"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":30,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":22,"type":"PreviewImage","pos":{"0":1123,"1":363},"size":{"0":210,"1":246},"flags":{},"order":8,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":19,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":21,"type":"PreviewImage","pos":{"0":866,"1":342},"size":{"0":210,"1":246},"flags":{},"order":10,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":32,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":29,"type":"ENHivisionParamsNode","pos":{"0":37,"1":477},"size":{"0":315,"1":154},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"normal_params","type":"PARAMS","links":[33,34,35],"slot_index":0,"shape":3,"label":"normal_params"}],"properties":{"Node name for S&R":"ENHivisionParamsNode"},"widgets_values":["One inch\t\t(413, 295)","Blue","pure_color",300,300]},{"id":11,"type":"AddBackgroundNode","pos":{"0":105,"1":263},"size":{"0":253.60000610351562,"1":78},"flags":{},"order":5,"mode":0,"inputs":[{"name":"input_img","type":"IMAGE","link":17,"label":"input_img"},{"name":"normal_params","type":"PARAMS","link":34,"label":"normal_params"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[28,31],"slot_index":0,"shape":3,"label":"IMAGE"},{"name":"4ch_hd_img","type":"IMAGE","links":[19],"slot_index":1,"shape":3,"label":"4ch_hd_img"}],"properties":{"Node name for S&R":"AddBackgroundNode"},"widgets_values":[]},{"id":14,"type":"LoadImage","pos":{"0":30,"1":48},"size":{"0":315,"1":314},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[13],"slot_index":0,"shape":3,"label":"图像"},{"name":"MASK","type":"MASK","links":null,"shape":3,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["23.jpeg","image"]},{"id":18,"type":"HivisionNode","pos":{"0":432,"1":64},"size":{"0":380.4000244140625,"1":342},"flags":{},"order":2,"mode":0,"inputs":[{"name":"input_img","type":"IMAGE","link":13,"label":"input_img"},{"name":"normal_params","type":"PARAMS","link":33,"label":"normal_params"}],"outputs":[{"name":"standard_img","type":"IMAGE","links":[22],"slot_index":0,"shape":3,"label":"standard_img"},{"name":"hd_img","type":"IMAGE","links":[16,17],"slot_index":1,"shape":3,"label":"hd_img"}],"properties":{"Node name for S&R":"HivisionNode"},"widgets_values":[false,"birefnet-v1-lite","retinaface-resnet50","hivision_modnet","retinaface-resnet50",0.2,0.12,2,0,0,0,0]},{"id":28,"type":"AddWaterMarkNode","pos":{"0":418,"1":367},"size":{"0":400,"1":216},"flags":{},"order":7,"mode":0,"inputs":[{"name":"input_img","type":"IMAGE","link":31,"label":"input_img"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[32],"slot_index":0,"shape":3,"label":"IMAGE"},{"name":"4ch_hd_img","type":"IMAGE","links":null,"shape":3,"label":"4ch_hd_img"}],"properties":{"Node name for S&R":"AddWaterMarkNode"},"widgets_values":["AIFSH","#FFFFFF",20,0.15,30,25,true]}],"links":[[13,14,0,18,0,"IMAGE"],[16,18,1,20,0,"IMAGE"],[17,18,1,11,0,"IMAGE"],[19,11,1,22,0,"IMAGE"],[22,18,0,19,0,"IMAGE"],[28,11,0,26,0,"IMAGE"],[30,26,0,27,0,"IMAGE"],[31,11,0,28,0,"IMAGE"],[32,28,0,21,0,"IMAGE"],[33,29,0,18,1,"PARAMS"],[34,29,0,11,1,"PARAMS"],[35,29,0,26,1,"PARAMS"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.9646149645000006,"offset":[272.80315729437297,45.29904673534638]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by ltdrdata** [comment]
Please move this issue to HivisionIDPhotos-ComfyUI repo.
https://github.com/AIFSH/HivisionIDPhotos-ComfyUI
