### ISSUE TITLE
it loads? But the web browser remains blank.

### ISSUE THREAD

**Issue by Maikhool** [comfyanonymous/ComfyUI#5376]
### Your question

So I did a fresh install and i've done the updates but nothing seems to change. it finishes in the command window but nothing the browser remains white with nothing loading.  The logs are below but i can't really decipher what the problem is or what i'm meant to be looking for. It doesn't load anything like it used to (reinstalled as the update messed things up for me). Any guidance or direction would be appreciated. I wouldn't even know what to look for if i were to search the 1.7k other issues this program has.

### Logs

```powershell
F:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 12287 MB, total RAM 65480 MB
pytorch version: 2.5.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: F:\ComfyUI_windows_portable\ComfyUI\web
F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by ltdrdata** [comment]
Have you tried using a different browser? Your issue might be caused by browser extensions blocking ComfyUI from loading.

**Comment by Maikhool** [comment]
yeh you're right. I felt pretty stupid when i tried loading it in another browser. I tried opera and it loaded straight away. same with chrome. what bothers me though is i've used microsoft edge for comfyui for a year and now it doesn't work but owell, it is what it is. thank you for helping me out.
