### ISSUE TITLE
Sizes of tensors must match

### ISSUE THREAD

**Issue by Lsama666** [comfyanonymous/ComfyUI#5378]
### Your question

![屏幕截图 2024-10-26 233334](https://github.com/user-attachments/assets/5c35cd51-d4b5-4c7f-85c7-267405b63975)
![2](https://github.com/user-attachments/assets/2dd39b45-44da-4578-aed9-ae8cae6669ab)

The picture is 512*512, I don't know how to solve it

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-Flowty-TripoSR
https://github.com/flowtyone/ComfyUI-Flowty-TripoSR
