### ISSUE TITLE
Seed inconsistent in batch size > 1

### ISSUE THREAD

**Issue by chrish-slingshot** [comfyanonymous/ComfyUI#538]
Seed does not work consistently - if I generate a single image with a fixed seed I get a different first image to when I use the same seed but for a batch size of 4.

**Comment by comfyanonymous** [comment]
Seems to work fine when I try it, can you give me an example of a workflow that causes this?

**Comment by omar92** [comment]
if you use Euler A or any other A thing , they add noise so you might git different results each time (i saw that on video not sure)

**Comment by chrish-slingshot** [comment]
Sorry, I must have had something wrong in my workflow as I've just trued to reproduce it and it works fine now. Thanks, keep up the great work :)
