### ISSUE TITLE
VRAM consumption of bypassed nodes

### ISSUE THREAD

**Issue by zlobniyshurik** [comfyanonymous/ComfyUI#5383]
### Your question

I have a workflow with nodes that are often in bypass state (like LORA loader).
Are these nodes still eating up my VRAM or can I not worry about it?
In other words. Do I need to have 2 different workflows to save my VRAM (with LORA and without LORA) or can I use a universal workflow with LORA (with bypass setting enabled|disabled)?

**Comment by ltdrdata** [comment]
When executing a workflow with bypassed nodes, ComfyUI treats those nodes as if they don't exist.
