### ISSUE TITLE
Why is it that when you open comfyui's hover window, the menu goes to the middle and then disappears when you click on it again, and you can't find the menu?

### ISSUE THREAD

**Issue by wuliang19869312** [comfyanonymous/ComfyUI#5384]
### Expected Behavior

![屏幕截图 2024-10-27 154746](https://github.com/user-attachments/assets/a462c3e5-e28b-4a72-baef-8481583fb09e)

### Actual Behavior

Why is it that when you open comfyui's hover window, the menu goes to the middle and then disappears when you click on it again, and you can't find the menu?

### Steps to Reproduce

The interface at the start, the menu looks like it's broken, split in half, and then the top and bottom are reversed, the bottom half and the top half are reversed

### Debug Logs

```powershell
There are no errors in the logs, just in the display.
```

**Comment by ltdrdata** [comment]
Please check if the same issue occurs after disabling all custom nodes, restarting, and refreshing your browser.
To disable custom nodes, move the nodes in `ComfyUI/custom_nodes` to a different location,
and in `ComfyUI/web/extensions`, delete all files except for core.
