### ISSUE TITLE
about areacondition

### ISSUE THREAD

**Issue by Chengym2023** [comfyanonymous/ComfyUI#5386]
### Your question

i see some vedio ,they use this node [ComfyUI_Dave_CustomNode](https://github.com/Davemane42/ComfyUI_Dave_CustomNode),but i clone this,cannot use ,it seems broken,freeze workflow,does someone have a backup version

**Comment by LukeG89** [comment]
That node has been archived.

Here's an alternative node: [ComfyUI-VisualArea-Nodes](https://github.com/Fuwuffyi/ComfyUI-VisualArea-Nodes)

**Comment by Chengym2023** [comment]
> That node has been archived.
> 
> Here's an alternative node: [ComfyUI-VisualArea-Nodes](https://github.com/Fuwuffyi/ComfyUI-VisualArea-Nodes)

ths,i try,and do you konw this node https://github.com/hako-mikan/sd-webui-regional-prompter.git ,have a comfyui verison?

**Comment by ltdrdata** [comment]
FYI, You can find tutorial workflows of Inspire Pack.
https://github.com/ltdrdata/ComfyUI-extension-tutorials/tree/Main/ComfyUI-Inspire-Pack/workflow
