### ISSUE TITLE
Create instance option node

### ISSUE THREAD

**Issue by wilzamguerrero** [comfyanonymous/ComfyUI#5391]
### Feature Idea

Sometimes some nodes only create one output response then I have to duplicate the node and copy its settings again, but it would be useful if we could add the instance option to all nodes, that is, to make an exact duplicate of the original where it follows the value changes of the original but can connect it to other nodes to generate its response.

### Existing Solutions

I have not found anything like that

**Comment by ltdrdata** [comment]
I don't understand what your request is.
How is it different from duplicating nodes and making new connections?

**Comment by ltdrdata** [comment]
Could you create a virtual example workflow to explain this?

**Comment by ltdrdata** [comment]
Do you mean that you want the widget values of the duplicated nodes to be shared?

**Comment by ltdrdata** [comment]
> Yes, they would be duplicate nodes, if one is updated, the instances are updated, but you can connect them with other nodes separately. The only thing that is maintained are the same values, since it is an instance and not just a copy.

Is there a reason for not using the existing "convert to input" method?

**Comment by ltdrdata** [comment]
> Well the problem is that not all attributes are enabled with this option and that in some nodes, for example in the image that I share, the editor expression only receives one image and in the same way it does not process multiple batches, the solution is to separate the images and connect them to an individual editor expression, but here the need arises, what if I want the value of an editor expression to be the same for the others, here I would apply the instance nodes.
> 
> ![image](https://github.com/user-attachments/assets/3825551e-2bfc-45da-9fda-fbcc1c3cd654)
> 
> 
> 
> 

You need to convert batch to list.
