### ISSUE TITLE
Don't override Ctrl+D

### ISSUE THREAD

**Issue by mcandre** [comfyanonymous/ComfyUI#5392]
### Expected Behavior

Windows: Ctrl+D bookmarks the foregrounded tab in most Web browsers.

macOS: Ctrl+D erases the character to the right of the cursor.

### Actual Behavior

ComfyUI: Ctrl+D irreversibly loses most settings and applies factory defaults.

### Steps to Reproduce

Press `Ctrl+D`

### Debug Logs

```powershell
N/A
```

### Other

Until #2395 is implemented, it is unsafe for ComfyUI to assign a strange behavior like resetting the UI to the common hotkey Ctrl+D.

Please move this logic out of the Ctrl+D hotkey and reserve a dedicated button for it instead.

**Comment by huchenlei** [comment]
You can customize keybinding since v1.3.7 frontend. 
![image](https://github.com/user-attachments/assets/8993bdcf-4a1a-4415-bd6e-76825e725a45)

**Comment by mcandre** [comment]
Confirmed, the hotkey customization appears to work.

For safety, would prefer that resetting the entire workflow is not mapped to any hotkey by default, especially not one that normally just bookmarks the webpage in Windows.
