### ISSUE TITLE
How to upgrade the standalone portable package to python 3.12 and cu124

### ISSUE THREAD

**Issue by IAFFeng** [comfyanonymous/ComfyUI#5399]
Executed update_comfyui_and_python_dependencies.bat. After the update, only pytorch was upgraded to 2.5.1, and python and cu were still the old versions.

**Comment by oliverban** [comment]
YES! I wanna know this too. For the regular venv version we need to delete the whole venv and start over, but how do we do this for portable? I wanna upgrade the internal python from 3.11 to 3.12!

**Comment by Amorano** [comment]
Can you clarify? Standalone or embedded? I feel you mean embedded, and correct, embedded already comes with a locked python version. 

For standalone, it uses your system python, so you are free to update/upgrade that and continue onward, given you know what other packages to update for it.

**Comment by IAFFeng** [comment]
> Can you clarify? Standalone or embedded? I feel you mean embedded, and correct, embedded already comes with a locked python version, which will be "updated" when they release a new embedded with an updated python.
> 
> For standalone, it uses your system python, so you are free to update/upgrade that and continue onward, given you know what other packages to update for it.

Portable version, that is, to replace the contents of the compressed package?

**Comment by metamountain** [comment]
??? Still no  answer ???

**Comment by Amorano** [comment]
> ??? Still no answer ???

still no answer to what? I literally asked clarification questions and got no answers.

The update will not REPLACE the embedded python installation. You need to pull a new embedded, if you want a new python version.

**Comment by GitHongWu** [comment]
> > ??? Still no answer ???
> 
> still no answer to what? I literally asked clarification questions and got no answers.
> 
> The update will not REPLACE the embedded python installation. You need to pull a new embedded, if you want a new python version.

Let's say I want to update embedded python from 3.11 to 3.12, I will need to pull the latest ComfyUI and replace the old 3.11 embedded_python with new pulled 3.12 embedded_python folder completely, is that correct approach? Is there anything could potentially be broke? Thanks

**Comment by ltdrdata** [comment]
> > > ??? Still no answer ???
> > 
> > still no answer to what? I literally asked clarification questions and got no answers.
> > 
> > The update will not REPLACE the embedded python installation. You need to pull a new embedded, if you want a new python version.
> 
> Let's say I want to update embedded python from 3.11 to 3.12, I will need to pull the latest ComfyUI and replace the old 3.11 embedded_python with new pulled 3.12 embedded_python folder completely, is that correct approach? Is there anything could potentially be broke? Thanks

That's correct. Additionally, you should extract the list of installed dependencies from the existing Python environment using `python_embeded/python.exe -m pip freeze`, and then carefully reinstall them in the new Python environment. 
(You should not reinstall torch related packages.)
One thing to watch out for is that some dependencies may not be installable in the newer Python version.
