### ISSUE TITLE
Float type input has been changed to VAE type in the ControlNet node after my ComfyUI updated.

### ISSUE THREAD

**Issue by AyaseEUmi** [comfyanonymous/ComfyUI#5400]
### Expected Behavior

![3](https://github.com/user-attachments/assets/a911b0e6-831b-44bb-89d3-70d1ee1ed895)

### Actual Behavior

After my ComfyUI updated, when I load a workflow from history queue, I found that  a float type input strength (I changed it to input before) of ControlNet Node was  changed to VAE type. If I change strength to widget then to input , it could work. However load same workflow from history queue , it reports error again.
Before:
![1](https://github.com/user-attachments/assets/1e8b730b-0b56-4687-b975-74780d1affff)
After:
![2](https://github.com/user-attachments/assets/4d0459ad-3140-448e-8b70-8ca41a7be08a)

### Steps to Reproduce

[Unsaved Workflow (8).json](https://github.com/user-attachments/files/17550769/Unsaved.Workflow.8.json)

### Debug Logs

```powershell
got prompt
Failed to validate prompt for output 227:
* ControlNetApplyAdvanced 10:
  - Return type mismatch between linked nodes: vae, FLOAT != VAE
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
```

**Comment by JialinSun1** [comment]
similar problem here. When running flux controlnet which needs vae, the node shows the following error:
![image](https://github.com/user-attachments/assets/4686c9c4-f207-43aa-973b-43fa6e5174db)
I guess there is a bug when they are trying to combine controlnet w/o vae into one Apply_Controlnet node.

**Comment by ltdrdata** [comment]
Your workflow created in an old version of ComfyUI appears to be broken due to compatibility issues. Please recreate the node.
