### ISSUE TITLE
Prompt outputs failed validation

### ISSUE THREAD

**Issue by MrMajorThorburn** [comfyanonymous/ComfyUI#5403]
### Your question

I am just starting using ComfyUI and followed the readme downloaded a copied V1-5-pruned-emaonly-ckpt to the models folder and got the following error message
Prompt outputs failed validation
CheckpointLoaderSimple:
- Value not in list: ckpt_name: 'v1-5-pruned-emaonly.ckpt' not in ['v1-5-pruned-emaonly-fp16.safetensors']

### Logs

```powershell
could not find the server. Running on Windows 11
```

**Comment by ltdrdata** [comment]
1. make sure the file name. 
2. the file should be placed into ComfyUI/models/checkpoints
3. refresh browser
4. reselect the file.

**Comment by MrMajorThorburn** [comment]
Renamed v1-5-pruned-emaonly-fp16.safetensors to v1-5-pruned-emaonly.ckpt
