### ISSUE TITLE
AMD GPU with WSL & ROCm

### ISSUE THREAD

**Issue by emircanerkul** [comfyanonymous/ComfyUI#5406]
### Feature Idea

Follow https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-radeon.html to install rocm wsl
Follow https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html install the magic behind the screen packages

Run without comfy requirements
```
python3 -c "import torch; print(f'device name [0]:', torch.cuda.get_device_name(0))"
```
See your GPU 
```
device name [0]: AMD Radeon RX 6800 XT
```
Clone ComfyUI and install requirements and install rocm wsl's magical packages
```
HSA_OVERRIDE_GFX_VERSION=10.3.0 python main.py
```
Then Run the test script again
```
python3 -c "import torch; print(f'device name [0]:', torch.cuda.get_device_name(0))"
```
See the result
```
No HIP GPUs are available
```

### Existing Solutions

Couldn't find it yet. I know directml could be workaround but i just want to squeeze last bit of performance.

**Comment by emircanerkul** [comment]
@Kademo15 yea *officially, thats why we have HSA_OVERRIDE_GFX_VERSION=10.3.0 arg.

**Comment by Kademo15** [comment]
That works on rocm but not wsl the gpu passthrough driver doesn't work on rdna 2.

**Comment by emircanerkul** [comment]
@Kademo15 Ah okay, thank you for the information. I'll not take it. And closing the issue.
