### ISSUE TITLE
When I updated to the latest version, the connection was misaligned

### ISSUE THREAD

**Issue by zergqyue** [comfyanonymous/ComfyUI#5407]
### Your question

When I updated to the latest version, the connection was misaligned, but it displayed normally using the old version (September 6th). What is the reason for this?
![360截图20241029213808](https://github.com/user-attachments/assets/0faedf2c-fdf0-4871-afab-751a125f0c95)

**Comment by zergqyue** [comment]
I have tested several times and found that the error is caused by the updated version: 9.22 11:28:54 89fa2fc update web content to release v1.2.60 (# 5017). How can I solve this problem?

**Comment by ltdrdata** [comment]
This is a known problem of outdated mixlab.
Update or remove the mixlab.
