### ISSUE TITLE
Daniel_Han

### ISSUE THREAD

**Issue by Danielhan626** [comfyanonymous/ComfyUI#5415]
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
![微信截图_20241030051517](https://github.com/user-attachments/assets/c7332040-bed4-469f-b500-187d41f439a4)

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUi_InstantID repo.
https://github.com/cubiq/ComfyUI_InstantID
