### ISSUE TITLE
"unsaved workflow (x).json" cannot be remove

### ISSUE THREAD

**Issue by Khampol** [comfyanonymous/ComfyUI#5419]
### Your question

"unsaved workflow (x).json" cannot be remove. I maybe miss something please suggest.

![image](https://github.com/user-attachments/assets/acd45c1b-8ba0-4ace-8b68-475331ec7ea3)

**Comment by ltdrdata** [comment]
Workflows in the 'open' section are workflows that are currently being edited.
Since at least one workflow must exist for the workflow you are currently viewing, you cannot remove this workflow until you switch to another workflow.

**Comment by Khampol** [comment]
ohh.... I see. Thanks 😅
