### ISSUE TITLE
[Feature Request]  Request for Ascend NPU support

### ISSUE THREAD

**Issue by statelesshz** [comfyanonymous/ComfyUI#5420]
### Background
Currently, the project supports various hardware accelerators such as GPUs, but there is no support for NPUs. Adding NPU support could significationly benefit users who have access to these devices, enabling faster and more efficient computations.

Similar to https://github.com/comfyanonymous/ComfyUI/pull/409, a minor adjustment will enable this project to operate smoothly on Ascend NPUs without issues.(Since diffusers/transformers/accelerate/peft already has support of NPUs enabled)

### Reference Materials
- Ascend is a full-stack AI computing infrastructure for industry applications and services based on Huawei Ascend processors and software. For more information about Ascend, see [Ascend Community](https://www.hiascend.com/en/).

- [CANN](https://www.hiascend.com/en/software/cann) (Compute Architecture of Neural Networks), developped by Huawei, is a heterogeneous computing architecture for AI.

- Pytorch has officially announced [support for Ascend NPU](https://pytorch.org/blog/pytorch-2-1/) (through key PrivateUse1), please see the PrivateUse1 tutorial [here](https://pytorch.org/tutorials/advanced/privateuseone.html).

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/pull/5273

If someone can confirm that this PR works I will merge it.
