### ISSUE TITLE
After updating ComfyUI, an error message appears when running the Stable Diffusion 3.5 Medium model.

### ISSUE THREAD

**Issue by zhuyuxiangcn** [comfyanonymous/ComfyUI#5422]
### Your question

The error message is as follows:Error occurred when executing CheckpointLoaderSimple:

Error(s) in loading state_dict for OpenAISignatureMMDITWrapper:
size mismatch for joint_blocks.0.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.0.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.1.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.1.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.2.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.2.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.3.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.3.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.4.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.4.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.5.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.5.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.6.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.6.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.7.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.7.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.8.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.8.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.9.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.9.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.10.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.10.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.11.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.11.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
size mismatch for joint_blocks.12.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
size mismatch for joint_blocks.12.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).

File "H:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "H:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "H:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "H:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "H:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 539, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
File "H:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 525, in load_checkpoint_guess_config
out = load_state_dict_guess_config(sd, output_vae, output_clip, output_clipvision, embedding_directory, output_model, model_options, te_model_options=te_model_options)
File "H:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 567, in load_state_dict_guess_config
model.load_model_weights(sd, diffusion_model_prefix)
File "H:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 222, in load_model_weights
m, u = self.diffusion_model.load_state_dict(to_load, strict=False)
File "H:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
![Snipaste_2024-10-30_14-51-25](https://github.com/user-attachments/assets/8c3928d6-a4bb-4f7c-949f-caeb0b0e2470)

### Other

I downloaded all the necessary files here at "(https://blog.comfy.org/sd-35-medium/)" After selecting the model according to the process, an error message appeared when running the initial SD 3.5 model section.

**Comment by WooXinyi** [comment]
same issue

**Comment by ltxskyyincha** [comment]
same

**Comment by MushroomFleet** [comment]
same issue

**Comment by starbuck100** [comment]
Same on ComfyUI running on ubuntu.
Got it fixed with updating comfyui via ComfyManager.
First ->Update Comfy
Then -> Update All

**Comment by zhuyuxiangcn** [comment]
> Ok Ladies & Gents:好的女士们与先生们：
> 
> UPDOOT: UPDOOT： 简体中文翻译：
> 
> if you update Torch to 2.5.1, Torchvision to 0.20.1, Torchaudio to 2.5.1 and also Transformers to 4.46.1-py3-none-any.whl如果你更新 Torch 到 2.5.1，Torchvision 到 0.20.1，Torchaudio 到 2.5.1，同时更新 Transformers 到 4.46.1-py3-none-any.whl
> 
> * it works 它工作
> * please include this in the model page instructions somewhere?请在模型页面说明的某个地方包含这个信息？
> 
> This has fixed the Issue :)这已经解决了问题 :)
> 
> (use the /update/update_comfyui_and_python_dependencies.bat)（使用 /update/update_comfyui_and_python_dependencies.bat）

Thank you for your answer.I have already updated these environment dependencies, but I still cannot run it. The same error message appears, so there might be other conflicts. If it doesn't work, I might have to reinstall ComfyUI to give it another try.

**Comment by CHINAGRIMACE** [comment]
😭
<img width="1441" alt="SCR-20241101-cquy" src="https://github.com/user-attachments/assets/dd40b67d-16e3-416a-9c6c-5f9e9c37f216">

**Comment by jdietl** [comment]
Same problem here. And, by the way, getting a consistent set of libraries on Python 3.12 including "LoRA Training in ComfyUI" was quite a pain. I've been working it out with claude.ai and I'm still not entirely sure I understand what is going on.

**Comment by ltdrdata** [comment]
> Same problem here. And, by the way, getting a consistent set of libraries on Python 3.12 including "LoRA Training in ComfyUI" was quite a pain. I've been working it out with claude.ai and I'm still not entirely sure I understand what is going on.

Make sure your ComfyUI is up to date.
