### ISSUE TITLE
error with first loaded backend on gpu 0 but not on second loaded backend on gpu 1

### ISSUE THREAD

**Issue by CalmClarity** [comfyanonymous/ComfyUI#5430]
### Your question

when trying to run some workflows - the  open comfy backend on local host 7801 on gpu 0 i get error. yet when i open workflow in backend 2 on host 7822 using seconded gpu on 1,  i do not get error please help me understand and possible fix issue.

TypeError: Cannot read properties of undefined (reading 'inputs')

i have searched through other issues and only found that the nodes aigodlike and mixlab need to be disabled or removed, and that cv2 file needs updating, i never installed the a1111 so  don't have the file conflict, and have updated CV2 file anyway, i still get the error it happens an multiple workflows but some it does not. 

it only happens in the first instance of the comfy ui backend loading not the second, but this means a reduced work output and a redundant gpu just to load.

**Comment by ltdrdata** [comment]
Please share the complete terminal log and workflow.
