### ISSUE TITLE
v0.2.6 Drag-and-drop pullout node right-click menu bugs

### ISSUE THREAD

**Issue by eokoo** [comfyanonymous/ComfyUI#5431]
### Expected Behavior

v0.2.6 Drag out the menu to display the set language normally
![微信截图_20241031015926](https://github.com/user-attachments/assets/56a810b8-1859-402f-9069-90a3d964910c)

### Actual Behavior

v0.2.6 Drag-and-drop pullout node context menu bug that can't be translated to the right language，And the button to switch languages disappears，Displayed normally after falling back to v0.2.5
![微信截图_20241031020501](https://github.com/user-attachments/assets/a02423da-e180-48b9-ab32-365602f2eb60)

### Steps to Reproduce

Upgrade comfyui to 0.2.6

### Debug Logs

```powershell
none
```

**Comment by ltdrdata** [comment]
Multi-language support is not a default feature of ComfyUI. 
Please inquire at the translation custom node repo.

https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation
