### ISSUE TITLE
IPAdapterUnifiedLoader IPAdapter model not found.

### ISSUE THREAD

**Issue by bel-en-s** [comfyanonymous/ComfyUI#5435]
### Your question

i got stuck on my workfloy in Comfy ui using Florence2, where i am creating a img 2 img workflow. This error i dont know where it comes from as i have installed IPAdapterUnifier

**Comment by ltdrdata** [comment]
See this:
https://github.com/cubiq/ComfyUI_IPAdapter_plus#installation
