### ISSUE TITLE
 (IMPORT FAILED) ComfyUI-PuLID-Flux-Enhanced

### ISSUE THREAD

**Issue by nehorayshimoni** [comfyanonymous/ComfyUI#5461]
### Your question

Hello, I am experiencing an issue importing the ComfyUI-PuLID-Flux-Enhanced custom node in ComfyUI. I manually downloaded pulid_flux_v0.9.0.safetensors (\ComfyUI_windows_portable\ComfyUI\models\pulid), AntelopeV2 (\ComfyUI\models\insightface\antelopev2), ip-adapter_pulid_sdxl_fp16.safetensors ( \ComfyUI_windows_portable\ComfyUI\models\pulid).

After starting ComfyUI, I receive a "Missing Node Types" error message (see screenshots attached). When I check for Install Missing Custom Nodes using the Manager the option to "Try fix" appears, but it does not resolve the issue.

I have followed all the instructions provided in the setup guide here: [ComfyUI Setup Guide](https://docs.google.com/document/d/1Hjf1LwpEy2KVmKb0TU4cjkzIofdi6tCP7qI7Sr6NtZs/edit?tab=t.0)

![Screenshot 2024-11-02 034833](https://github.com/user-attachments/assets/cc465699-0505-4ce9-ba0d-7fc9c8d628ec)

![Screenshot 2024-11-02 034821](https://github.com/user-attachments/assets/0afdc723-2575-4b83-b8b3-0155f8841d39)

Thank you for your assistance!

**Comment by samanstudio** [comment]
I have the same problem!

**Comment by nehorayshimoni** [comment]
Logs

**Comment by samanstudio** [comment]
Could you fix the problem?

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-PuLID-Flux-Enhanced
https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced

**Comment by nehorayshimoni** [comment]
Thank you :)
I have not found a solution yet for my issue, but I will try to fix it in the future, if someone has a fix feel free to contact me

**Comment by kebtime100** [comment]
> Thank you :) I have not found a solution yet for my issue but I will try to fix it in the future. If someone has a fix feel free to contact me

Try to manually install facexlib and insightface. think that will fix your problem.

**Comment by nehorayshimoni** [comment]
Unfortunately it didn't work for me but thank you for your help. I now installed correctly insightface but maybe I need to try to install facexlib again

**Comment by khalsbaai** [comment]
@nehorayshimoni can you share the fix please

**Comment by nehorayshimoni** [comment]
Hello, I still haven't found a fix for this issue but as soon as I do I'll be happy to share. If someone else found a solution and can share that would be great

**Comment by HTPAUN** [comment]
If you have downloaded insightface, but "cannot import for custom nodes: No module named 'insightface.app' "
Follow this 
:
(ComfyUI Portable) From the root folder check the version of Python:
**_run CMD and type python_embeded\python.exe -V_**

Download prebuilt Insightface package [for Python 3.10](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl) or [for Python 3.11](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl) (if in the previous step you see 3.11) or [for Python 3.12](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp312-cp312-win_amd64.whl) (if in the previous step you see 3.12) and put into the stable-diffusion-webui (A1111 or SD.Next) root folder (where you have "webui-user.bat" file) or into ComfyUI root folder if you use ComfyUI Portable

From the root folder run:

(ComfyUI Portable) run CMD

Then update your PIP:

**_(ComfyUI Portable) python_embeded\python.exe -m pip install -U pip_**

Then install Insightface:

(ComfyUI Portable) python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl (for 3.10) or python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl (for 3.11) or python_embeded\python.exe -m pip install insightface-0.7.3-cp312-cp312-win_amd64.whl (for 3.12)

II. "AttributeError: 'NoneType' object has no attribute 'get'"
This error may occur if there's smth wrong with the model file inswapper_128.onnx

_**Try to download it manually from [here](https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx) and put it to the ComfyUI\models\insightface replacing existing one**_

Then,
maybe said : ImportError: DLL load failed while importing onnx_cpp2py_export

you
_python -m pip show onnx 
python -m pip uninstall onnx
python -m pip install onnx==1.16.1_

**Comment by thinghesi** [comment]
I have the same problem!

**Comment by brandonlmoreau** [comment]
same exact problem here for a week now, ive tried a few solutions. any update? @nehorayshimoni

**Comment by kecikub** [comment]
guys, get the newest Microsoft Visual C++. It solved problems with importing PuLID for me

**Comment by ShoWorld** [comment]
> conda install -c conda-forge libstdcxx-ng

Thank you, this method helped me><//

**Comment by WyyzHot** [comment]
https://www.youtube.com/watch?v=o_JOs56Q3zk

this fix my problem, i manually install facexlib and insightface

**Comment by chuckstarza** [comment]
> If you have downloaded insightface, but "cannot import for custom nodes: No module named 'insightface.app' " Follow this : (ComfyUI Portable) From the root folder check the version of Python: **_run CMD and type python_embeded\python.exe -V_**
> 

Legend! Sorted a whole day of frustration..

**Comment by somewhatsquishy** [comment]
> If you have downloaded insightface, but "cannot import for custom nodes: No module named 'insightface.app' " Follow this : (ComfyUI Portable) From the root folder check the version of Python: **_run CMD and type python_embeded\python.exe -V_**

This finally fixed it!!!! I MADE AN ACCOUNT HERE JUST TO THANK YOU!

**Comment by 9esw7** [comment]
> If you have downloaded insightface, but "cannot import for custom nodes: No module named 'insightface.app' " Follow this : (ComfyUI Portable) From the root folder check the version of Python: **_run CMD and type python_embeded\python.exe -V_**
> 
> Download prebuilt Insightface package [for Python 3.10](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl) or [for Python 3.11](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl) (if in the previous step you see 3.11) or [for Python 3.12](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp312-cp312-win_amd64.whl) (if in the previous step you see 3.12) and put into the stable-diffusion-webui (A1111 or SD.Next) root folder (where you have "webui-user.bat" file) or into ComfyUI root folder if you use ComfyUI Portable
> 
> From the root folder run:
> 
> (ComfyUI Portable) run CMD
> 
> Then update your PIP:
> 
> **_(ComfyUI Portable) python_embeded\python.exe -m pip install -U pip_**
> 
> Then install Insightface:
> 
> (ComfyUI Portable) python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl (for 3.10) or python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl (for 3.11) or python_embeded\python.exe -m pip install insightface-0.7.3-cp312-cp312-win_amd64.whl (for 3.12)
> 
> II. "AttributeError: 'NoneType' object has no attribute 'get'" This error may occur if there's smth wrong with the model file inswapper_128.onnx
> 
> _**Try to download it manually from [here](https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx) and put it to the ComfyUI\models\insightface replacing existing one**_
> 
> Then, maybe said : ImportError: DLL load failed while importing onnx_cpp2py_export
> 
> you _python -m pip show onnx python -m pip uninstall onnx python -m pip install onnx==1.16.1_

i don't have "(ComfyUI Portable) python_embeded", just using flux on comfyui with zluda, any solution for me?

**Comment by ltdrdata** [comment]
> > If you have downloaded insightface, but "cannot import for custom nodes: No module named 'insightface.app' " Follow this : (ComfyUI Portable) From the root folder check the version of Python: **_run CMD and type python_embeded\python.exe -V_**
> > Download prebuilt Insightface package [for Python 3.10](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl) or [for Python 3.11](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl) (if in the previous step you see 3.11) or [for Python 3.12](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp312-cp312-win_amd64.whl) (if in the previous step you see 3.12) and put into the stable-diffusion-webui (A1111 or SD.Next) root folder (where you have "webui-user.bat" file) or into ComfyUI root folder if you use ComfyUI Portable
> > From the root folder run:
> > (ComfyUI Portable) run CMD
> > Then update your PIP:
> > **_(ComfyUI Portable) python_embeded\python.exe -m pip install -U pip_**
> > Then install Insightface:
> > (ComfyUI Portable) python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl (for 3.10) or python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl (for 3.11) or python_embeded\python.exe -m pip install insightface-0.7.3-cp312-cp312-win_amd64.whl (for 3.12)
> > II. "AttributeError: 'NoneType' object has no attribute 'get'" This error may occur if there's smth wrong with the model file inswapper_128.onnx
> > _**Try to download it manually from [here](https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx) and put it to the ComfyUI\models\insightface replacing existing one**_
> > Then, maybe said : ImportError: DLL load failed while importing onnx_cpp2py_export
> > you _python -m pip show onnx python -m pip uninstall onnx python -m pip install onnx==1.16.1_
> 
> i don't have "(ComfyUI Portable) python_embeded", just using flux on comfyui with zluda, any solution for me?

If you are using a custom-configured Python environment, you need to use the `pip` of that environment. In this case, unlike `python_embedded`, it will vary for each environment.

The important thing is that you need to use the `pip` associated with the Python environment that runs ComfyUI for installation.

**Comment by 9esw7** [comment]
> > > If you have downloaded insightface, but "cannot import for custom nodes: No module named 'insightface.app' " Follow this : (ComfyUI Portable) From the root folder check the version of Python: **_run CMD and type python_embeded\python.exe -V_**
> > > Download prebuilt Insightface package [for Python 3.10](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl) or [for Python 3.11](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl) (if in the previous step you see 3.11) or [for Python 3.12](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp312-cp312-win_amd64.whl) (if in the previous step you see 3.12) and put into the stable-diffusion-webui (A1111 or SD.Next) root folder (where you have "webui-user.bat" file) or into ComfyUI root folder if you use ComfyUI Portable
> > > From the root folder run:
> > > (ComfyUI Portable) run CMD
> > > Then update your PIP:
> > > **_(ComfyUI Portable) python_embeded\python.exe -m pip install -U pip_**
> > > Then install Insightface:
> > > (ComfyUI Portable) python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl (for 3.10) or python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl (for 3.11) or python_embeded\python.exe -m pip install insightface-0.7.3-cp312-cp312-win_amd64.whl (for 3.12)
> > > II. "AttributeError: 'NoneType' object has no attribute 'get'" This error may occur if there's smth wrong with the model file inswapper_128.onnx
> > > _**Try to download it manually from [here](https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx) and put it to the ComfyUI\models\insightface replacing existing one**_
> > > Then, maybe said : ImportError: DLL load failed while importing onnx_cpp2py_export
> > > you _python -m pip show onnx python -m pip uninstall onnx python -m pip install onnx==1.16.1_
> > 
> > 
> > i don't have "(ComfyUI Portable) python_embeded", just using flux on comfyui with zluda, any solution for me?
> 
> If you are using a custom-configured Python environment, you need to use the `pip` of that environment. In this case, unlike `python_embedded`, it will vary for each environment.
> 
> The important thing is that you need to use the `pip` associated with the Python environment that runs ComfyUI for installation.

I am using comfyui which is integrated with zluda (this:https://github.com/patientx/ComfyUI-Zluda) because I have amd graphics card and i still can't solve the problem.

**Comment by ltdrdata** [comment]
In that case, it would be best to ask about the installation method in the `ComfyUI-Zluda` repository.

**Comment by limmy389** [comment]
> If you have downloaded insightface, but "cannot import for custom nodes: No module named 'insightface.app' " Follow this : (ComfyUI Portable) From the root folder check the version of Python: **_run CMD and type python_embeded\python.exe -V_**
> 
> Download prebuilt Insightface package [for Python 3.10](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl) or [for Python 3.11](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl) (if in the previous step you see 3.11) or [for Python 3.12](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp312-cp312-win_amd64.whl) (if in the previous step you see 3.12) and put into the stable-diffusion-webui (A1111 or SD.Next) root folder (where you have "webui-user.bat" file) or into ComfyUI root folder if you use ComfyUI Portable
> 
> From the root folder run:
> 
> (ComfyUI Portable) run CMD
> 
> Then update your PIP:
> 
> **_(ComfyUI Portable) python_embeded\python.exe -m pip install -U pip_**
> 
> Then install Insightface:
> 
> (ComfyUI Portable) python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl (for 3.10) or python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl (for 3.11) or python_embeded\python.exe -m pip install insightface-0.7.3-cp312-cp312-win_amd64.whl (for 3.12)
> 
> II. "AttributeError: 'NoneType' object has no attribute 'get'" This error may occur if there's smth wrong with the model file inswapper_128.onnx
> 
> _**Try to download it manually from [here](https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx) and put it to the ComfyUI\models\insightface replacing existing one**_
> 
> Then, maybe said : ImportError: DLL load failed while importing onnx_cpp2py_export
> 
> you _python -m pip show onnx python -m pip uninstall onnx python -m pip install onnx==1.16.1

You just fixed my issue! Thanks!

**Comment by panxxpan** [comment]
Here is my slolution:
REASON: The virtual Python environment runs different version with the one which runs on you computer. In my case, i have installed python 3.11. However, under the comfyui root folder, it installed the python 3.12 in the virtual environment. For that matter, when comfyui manager runs the script, the system might be confused about where is the installation target folder. So, on my computer, the script runs 3.11 instead and install the facexlib into my C driver. 

SOLUTION: Just check _C:\Users\username\AppData\Roaming\Python\Python311\site-packages_ 
if you have the same problem just as mine, check those four folder: 
facexlib, facexlib-0.3.0.dist-info, filterpy,filterpy-1.4.5.dist-info
Then, copy and paste them into _..\ComfyUI_windows_portable\python_embeded\Lib\site-packages_

run comfyui again, the problem should be solved.

**Comment by limmy389** [comment]
> Here is my slolution: REASON: The virtual Python environment runs different version with the one which runs on you computer. In my case, i have installed python 3.11. However, under the comfyui root folder, it installed the python 3.12 in the virtual environment. For that matter, when comfyui manager runs the script, the system might be confused about where is the installation target folder. So, on my computer, the script runs 3.11 instead and install the facexlib into my C driver.
> 
> SOLUTION: Just check _C:\Users\username\AppData\Roaming\Python\Python311\site-packages_ if you have the same problem just as mine, check those four folder: facexlib, facexlib-0.3.0.dist-info, filterpy,filterpy-1.4.5.dist-info Then, copy and paste them into _..\ComfyUI_windows_portable\python_embeded\Lib\site-packages_
> 
> run comfyui again, the problem should be solved.

thanks for your help!
hmm I dont have such a path for Python. Mine was AppdData/Local/Programs/Python. 
However I didn't have a folder with site-packages.
I uninstalled Python now on Windows and now I'm trying to make everything new from scratch, but I'm still having same errors..

**Comment by ElvenNinja** [comment]
So I had this problem pop up out of nowhere, I didn't change anything but just ran Comfy UI and getting the same issue. I tried all the fixed mentioned here and none of them work for me. It was running just fine a couple of weeks before.

**Comment by NICOYESs** [comment]
> 
> Then install Insightface:
> 
> (ComfyUI Portable) python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl (for 3.10) or python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl (for 3.11) or python_embeded\python.exe -m pip install insightface-0.7.3-cp312-cp312-win_amd64.whl (for 3.12)
> 
This dint work I have python 312 and when I run the 312whl i get this error..... Any solotion???

\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable>python_embeded\python.exe -m pip install insightface-0.7.3-cp312-cp312-win_amd64
ERROR: Could not find a version that satisfies the requirement insightface-0.7.3-cp312-cp312-win_amd64 (from versions: none)
ERROR: No matching distribution found for insightface-0.7.3-cp312-cp312-win_amd64

**Comment by Nakasara1** [comment]
i have the same issue after intalling some custom nodes for an inpaint workflow.... tried reinstall and fix them but both did not work

**Comment by blue2024888** [comment]
请问已经解决这个问题了吗？困扰了好久，一直没解决

**Comment by blue2024888** [comment]
> 我也有同样的问题！

请问有解决了这个问题的方法吗

**Comment by bozkut** [comment]
Still there is no fix:(

**Comment by mdkberry** [comment]
same

**Comment by Azool2** [comment]
same problem

**Comment by Mental-diffusion** [comment]
> Here is my slolution: REASON: The virtual Python environment runs different version with the one which runs on you computer. In my case, i have installed python 3.11. However, under the comfyui root folder, it installed the python 3.12 in the virtual environment. For that matter, when comfyui manager runs the script, the system might be confused about where is the installation target folder. So, on my computer, the script runs 3.11 instead and install the facexlib into my C driver.
> 
> SOLUTION: Just check _C:\Users\username\AppData\Roaming\Python\Python311\site-packages_ if you have the same problem just as mine, check those four folder: facexlib, facexlib-0.3.0.dist-info, filterpy,filterpy-1.4.5.dist-info Then, copy and paste them into _..\ComfyUI_windows_portable\python_embeded\Lib\site-packages_
> 
> run comfyui again, the problem should be solved.




this is the correct answer, but I think its defrent from user to user, in my case "facexlib" folders not on Roaming it os on local and i had 3 version of python folder, 3.10, 3.11, 3.12 , facelibs has installed on 3.10 , but my comfy ui running on 3.11, what i did was, I copied,

facexlib,
 facexlib-0.3.0.dist-info,
 filterpy,
filterpy-1.4.5.dist-info 

folders, and pasted on python 3.11 and " ComfyUI_windows_portable\python_embeded\Lib\site-packages_" 
then I runed comfy ui and it works for me, every nodes works,  no errors,

check if you have installed facexlib properly, try manually installing, 

run "pip install facexlib"

if you already have installed it will show the file path on the terminal.


Sorry for my langiage, if this is confusing, Im not native, hope this owrks for you too,

**Comment by mananjabrik** [comment]
install filterpy 
```shell
python -m pip install filterpy
```
```shell
python -m pip install -r <node_directory>/requirement.txt
```

if u are using portable 
```shell
python -m pip install filterpy
```
```shell
.\python_embeded\python.exe -m pip install -r <node_directory>/requirement.txt
```

**Comment by EdwardFate** [comment]
❗️ Problem: ModuleNotFoundError: No module named 'insightface' in ComfyUI
Even though insightface is installed on your system, ComfyUI throws a ModuleNotFoundError. This usually happens because ComfyUI Portable uses its own embedded Python environment, which is isolated from your system-wide Python installation.

✅ Solution: Install insightface into ComfyUI’s Embedded Python
If you have the .whl file (e.g. insightface-0.7.3-cp312-cp312-win_amd64.whl), follow these steps:

Place the .whl file somewhere accessible, for example:

makefile

C:\Users\YourName\Desktop\insightface-0.7.3-cp312-cp312-win_amd64.whl
Open Command Prompt (CMD) and navigate to ComfyUI’s embedded Python folder:


cd C:\Users\YourName\Desktop\ComfyUI_windows_portableL\python_embeded
Install the .whl using ComfyUI’s Python:


python.exe -m pip install C:\Users\YourName\Desktop\insightface-0.7.3-cp312-cp312-win_amd64.whl
Verify the installation:

python.exe -m pip show insightface
Make sure the Location is within the ComfyUI_windows_portableL\python_embeded\Lib\site-packages path.

Restart ComfyUI. The error should now be gone.

**Comment by mminc2** [comment]
> Here is my slolution: REASON: The virtual Python environment runs different version with the one which runs on you computer. In my case, i have installed python 3.11. However, under the comfyui root folder, it installed the python 3.12 in the virtual environment. For that matter, when comfyui manager runs the script, the system might be confused about where is the installation target folder. So, on my computer, the script runs 3.11 instead and install the facexlib into my C driver.
> 
> SOLUTION: Just check _C:\Users\username\AppData\Roaming\Python\Python311\site-packages_ if you have the same problem just as mine, check those four folder: facexlib, facexlib-0.3.0.dist-info, filterpy,filterpy-1.4.5.dist-info Then, copy and paste them into _..\ComfyUI_windows_portable\python_embeded\Lib\site-packages_
> 
> run comfyui again, the problem should be solved.

This sorted my problem out, thank you so much for sharing!

**Comment by zcakkoit-arch** [comment]
did u find any solution?
