### ISSUE TITLE
Minor bug with RandomNoise node, with randomize - seed not randomizing after being set to fixed

### ISSUE THREAD

**Issue by crotalidae75** [comfyanonymous/ComfyUI#5462]
### Expected Behavior

Expected a new random seed, on the first time I select "randomize", (after using a fixed seed), in the RandomNoise node, as per usual. 

### Actual Behavior

When set to "randomize", after switching from fixed, the seed will remain the same on the first generation, unless you change the seed (even up or down by 1 digit).  On the second generation after the repeated generation, it works, as well.

### Steps to Reproduce

Easy enough to try in ComfyUI.  This is an issue with a core node.

### Other

I'm using ComfyUI in Linux (Kubuntu 24.10), with a Ryzen 5900x, 64GB of RAM and an RTX 4080 Super.  I don't think this issue is hardware related, of course.  There seems to be a bug with the node itself.  Note that is was with using Flux Dev.  I'm uncertain that it happens with other models, but I don't see why it would affect that node.

**Comment by LukeG89** [comment]
Have you tried "before" in Widget control mode?

![control](https://github.com/user-attachments/assets/b9c4f44d-f53a-43a7-8b30-8fd50595c96f)
