### ISSUE TITLE
apply pulid fulx unexpected EOF, expected 2113284 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by food6u** [comfyanonymous/ComfyUI#5463]
### Your question

unexpected EOF, expected 2113284 more bytes. The file might be corrupted.

**Comment by ltdrdata** [comment]
Your error information is too sparse. However, it's likely that the model file you're using is incorrect.

Additionally, since the PULID feature is not part of ComfyUI core, please reach out to the repository of the custom node for assistance.
