### ISSUE TITLE
about group

### ISSUE THREAD

**Issue by Chengym2023** [comfyanonymous/ComfyUI#5466]
### Your question

![image](https://github.com/user-attachments/assets/9176502a-6c69-4713-af2a-c21cc95f8d4d)
if i change group like this,it become un-delete or edit

**Comment by LukeG89** [comment]
This bug has been already reported here: 
- https://github.com/Comfy-Org/litegraph.js/issues/216

They should fix it soon.

In the meanwhile, here's a workaround to fix the issue:

- Open the .json file of your workflow with Notepad
- Find the entry of the specific group
- Correct the last two values; they has to be positive (e.g. put 300 and 300)
- Save the changes

![group_json](https://github.com/user-attachments/assets/f3132883-3aa5-470b-b50d-09d3c5b77f12)

**Comment by Chengym2023** [comment]
> This bug has been already reported here:
> 
> * [[Bug]: Resize Group Comfy-Org/litegraph.js#216](https://github.com/Comfy-Org/litegraph.js/issues/216)
> 
> They should fix it soon.
> 
> In the meanwhile, here's a workaround to fix the issue:
> 
> * Open the .json file of your workflow with Notepad
> * Find the entry of the specific group
> * Correct the last two values; they has to be positive (e.g. put 300 and 300)
> * Save the changes
> 
> ![group_json](https://private-user-images.githubusercontent.com/161304036/382479976-f3132883-3aa5-470b-b50d-09d3c5b77f12.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NjA0NTUsIm5iZiI6MTczMDU2MDE1NSwicGF0aCI6Ii8xNjEzMDQwMzYvMzgyNDc5OTc2LWYzMTMyODgzLTNhYTUtNDcwYi1iNTBkLTA5ZDNjNWI3N2YxMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNTA5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTA3N2Q2NjZiMTM3ODZmNWZlNzVjOTkxZTBmZmU5MmQ5ZjIwMTg0OGJiZWQ3YjliZTdmMDY5MWM0OGM5NjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JHrkn8GeYyV4ZK6486A-mhKURQ_073Tw4VN_oxdpEKE)

ok ,ths
