### ISSUE TITLE
download speeds when comfy needs to fetch a model

### ISSUE THREAD

**Issue by zethfoxster** [comfyanonymous/ComfyUI#5468]
### Expected Behavior

you get normal 2024 modern day high speed internet download speeds.

### Actual Behavior

you get 56k dialup internet speeds.

### Steps to Reproduce

unsure. just don't have a model for something like control net, insight face, pulid....anything really.

### Debug Logs

```powershell
Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.2.0/parsing_bisenet.pth" to C:\WebUi\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\facexlib\weights\parsing_bisenet.pth

 38%|█████████████████████████████                                                | 19.2M/50.8M [06:21<10:29, 52.7kB/s]
```

### Other

im literally seeing what files its trying to download, exiting comfy, downloading it myself in less then the blink of an eye and dropping it where it wants it.

**Comment by ltdrdata** [comment]
The model download functionality is handled by custom nodes, not by ComfyUI itself.
