### ISSUE TITLE
AttributeError: 'Segment' object has no attribute 'detect'

### ISSUE THREAD

**Issue by JS-codehub** [comfyanonymous/ComfyUI#5469]
### Your question

FaceDetailer Error: !!! Exception during processing !!! 'Segment' object has no attribute 'detect'
solution: python_embeded\python.exe -s -m pip install ultralytics==8.2.42
torchversion: 2.4.0+cu118

**Comment by waitercolor** [comment]
Already done what solutions say but still getting that error, anything else comes to mind ?
