### ISSUE TITLE
[ General ] - What are people using to fix faces inside Comfy?

### ISSUE THREAD

**Issue by rethink-studios** [comfyanonymous/ComfyUI#547]
Hey hey,
Reaching out to see what others are using to fix faces inside of ComfyUI.

Thanks in advance!

**Comment by rethink-studios** [comment]
Thanks for this.
I've installed as instructed, and received the error below. How can I fix?

Traceback (most recent call last):
  File "G:\StableDiffusion\ComfyUI\ComfyUI\nodes.py", line 1246, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\StableDiffusion\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack-Main\\__init__.py'

Cannot import G:\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main module for custom nodes: [Errno 2] No such file or directory: 'G:\\StableDiffusion\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack-Main\\__init__.py'
Davemane42 Custom Nodes: Loaded
xformers version: 0.0.16
Set vram state to: NORMAL_VRAM
WAS Node Suite: Running At: G:\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py
WAS Node Suite: Running From: G:\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
WAS Node Suite: Loaded
Starting server

**Comment by ltdrdata** [comment]
No. You don't create directory for custom node.

There are 2 kind of custom node.

1. single file structure custom node
> just copy single file into custom_node directory itself.
> doesn't require init.py

2. directory structure custom node
> git clone directory under custom_node.
> requires init.py

ComfyUI-Impact-Pack and was are case 1.
