### ISSUE TITLE
Floating node wires

### ISSUE THREAD

**Issue by tristan22mc** [comfyanonymous/ComfyUI#5474]
### Expected Behavior

wires to route visually accurately between nodes

### Actual Behavior

wires between nodes are floating separately from the nodes on the canvas 
![Screenshot 2024-11-02 224026](https://github.com/user-attachments/assets/c8ba0a28-1189-4faf-b302-bd7985d7a29c)

### Steps to Reproduce

updated my comfyui not exactly sure what else is needed. May need to update something else?

### Debug Logs

```powershell
no logs
```

**Comment by ltdrdata** [comment]
Update or remove the mixlab.
