### ISSUE TITLE
MaskEditor missing origin image 

### ISSUE THREAD

**Issue by tengshaofeng** [comfyanonymous/ComfyUI#5485]
### Your question

When I new a Load Image Node, and right click to open in MaskEditor. None image exists in popup. 
I reinstall comfyui, the problem is still exists.
![image](https://github.com/user-attachments/assets/bc412969-d64c-4c62-961f-01b80a462ae2)
![image](https://github.com/user-attachments/assets/e1f13f6b-24c0-4b30-9a3f-ccd7fc406300)
 

### Logs

```powershell
black popup,none image
```

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
