### ISSUE TITLE
[Feature Request] True cancel job/ Unload models.

### ISSUE THREAD

**Issue by GPU-server** [comfyanonymous/ComfyUI#5488]
### Feature Idea

Whenever I run a workflow that takes all my vram (typically flux workflows), comfy button "cancel" current job becomes unresponsive. I wish there was a way to tell it to cancel everyrithing withotu having to close comfy completely and restarting it. Despite having my full vram used (and slowing computer). This happen when the workflow is "stuck". Vram close to 100%. Comfy.. is stuck in that case.

In addition to that, whenever a model is loaded after running one workflow a part of vRAM stays "used", can we tell comfy to unload everything without closing it? 

This post contain 2 features requests.

**Comment by ltdrdata** [comment]
You can use --disable-smart-memory --lowvram

**Comment by GPU-server** [comment]
> You can use `--disable-smart-memory --lowvram`
> 
> Keeping the last used model in VRAM after workflow execution is intended to maximize performance by minimizing the cost of moving models between RAM and VRAM.

Yes for the second part of my issue/feature request (unload VRAm etc)
But I still have the problem of "cancel job" stays unresponsive whenever my full VRAM is used (when comfy is slow / frozen almost)
Only solution in that state is: close comfy and restart. I cannot cancel job anymore.
