### ISSUE TITLE
Save Flow 405

### ISSUE THREAD

**Issue by GitHub4LP** [comfyanonymous/ComfyUI#5491]
### Expected Behavior

Save Flow OK

### Actual Behavior

Save Flow 405

### Steps to Reproduce

Save Flow 
![屏幕截图 2024-11-05 132155](https://github.com/user-attachments/assets/ada8bb64-ad2c-44ca-b55d-72ca6e282696)

### Debug Logs

```powershell
No care
```

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by GitHub4LP** [comment]
api is./api/userdata/
workflows%2FUnsaved%20Workflow.json
but server decodes %2f to /, resulting in (./api/userdata/workflows/Unsaved%20Workflow.json) no API acceptable
@ltdrdata
