### ISSUE TITLE
Error Prompt on Console: lora key not loaded: double_blocks...

### ISSUE THREAD

**Issue by Orenji-Tangerine** [comfyanonymous/ComfyUI#5492]
### Expected Behavior

It happens only when I use checkpoint version Flux below and load a LoRA
https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors

![image](https://github.com/user-attachments/assets/2089987c-3ff8-4f18-8766-802175cf3e1b)

Error message: (the figure 0 will be from 0 to 18, each number has 8 of the same below)
lora key not loaded: double_blocks.0.processor.proj_lora1.down.weight
lora key not loaded: double_blocks.0.processor.proj_lora1.up.weight
lora key not loaded: double_blocks.0.processor.proj_lora2.down.weight
lora key not loaded: double_blocks.0.processor.proj_lora2.up.weight
lora key not loaded: double_blocks.0.processor.qkv_lora1.down.weight
lora key not loaded: double_blocks.0.processor.qkv_lora1.up.weight
lora key not loaded: double_blocks.0.processor.qkv_lora2.down.weight
lora key not loaded: double_blocks.0.processor.qkv_lora2.up.weight

Environment: Python 3.10.11, Pytorch 2.5.0 + CU 12.4 + xformers 0.0.28.post2

Diagnostic Log: 
[Diagnostics-1730792002.log](https://github.com/user-attachments/files/17628736/Diagnostics-1730792002.log)

### Actual Behavior

As per above

### Steps to Reproduce

As per above

### Debug Logs

```powershell
As per above
```

**Comment by ltdrdata** [comment]
What is your lora file?

**Comment by Orenji-Tangerine** [comment]
https://huggingface.co/XLabs-AI/flux-RealismLora/tree/main

I was using this Realism LoRA but it happens to all LoRAs. Or is it Pytorch version related?

**Comment by ltdrdata** [comment]
> https://huggingface.co/XLabs-AI/flux-RealismLora/tree/main
> 
> I was using this Realism LoRA but it happens to all LoRAs. Or is it Pytorch version related?

And what is your workflow?

**Comment by Orenji-Tangerine** [comment]
> > https://huggingface.co/XLabs-AI/flux-RealismLora/tree/main
> > I was using this Realism LoRA but it happens to all LoRAs. Or is it Pytorch version related?
> 
> And what is your workflow?


![image](https://github.com/user-attachments/assets/17e739b8-c0c4-49ab-a63e-27260d65f665)

[Workflow.json](https://github.com/user-attachments/files/17631676/Workflow.json)

**Comment by comfyanonymous** [comment]
Use the converted lora: https://huggingface.co/comfyanonymous/flux_RealismLora_converted_comfyui/tree/main
