### ISSUE TITLE
ConditioningSetArea not compatible with sd 3.5, but compatible well with flux.1 dev

### ISSUE THREAD

**Issue by binarytahr** [comfyanonymous/ComfyUI#5493]
### Your question

i test ConditioningSetArea and ConditioningCombine node with sd 3.5 large and flux.1 dev.
flux.1 dev's results are what it supposed to be: dog in the center, robot in the right corner, without quality loss.
sd 3.5 large's results are disordered.
so i am thinking if there are some compatibility issue?

flux.1 dev:
![f2c7a522-5f85-4a1f-9fe9-a2b3c12b26f7](https://github.com/user-attachments/assets/bd137605-fd45-4b51-81bc-420f6e4c0e7c)

sd 3.5 large:
![c5ca66d9-8f3e-41ce-bf50-6950592a1119](https://github.com/user-attachments/assets/066a9b5b-3942-4f3b-929c-8c1eb3bb64b5)
![f28a841d-30a9-45ac-b380-609ce964e579](https://github.com/user-attachments/assets/d40a5abc-d3f5-43e4-baab-35e0cbc129ad)

**Comment by ltdrdata** [comment]
Rather than being a compatibility issue, it's a characteristic of the model. Things like conditioning combine actually interfere with and intervene in the model's learned image generation process. FLUX handles this more flexibly and effectively, while SD3.5 doesn't handle it well.
