### ISSUE TITLE
MOCHI problem: "model weight dtype torch.bfloat16, manual cast: torch.float32" + "unet unexpected: ['scaled_fp8']" DESPITE USING ALL THE RIGHT MODELS.

### ISSUE THREAD

**Issue by moreAImore** [comfyanonymous/ComfyUI#5501]
### Your question

Hi,
As you can see in the following screenshot, I am using all the right models for fp8 (scaled etc)

![image](https://github.com/user-attachments/assets/988305b0-4c03-488e-9069-883ce4de81ea)

Yet my comfy (fresh install), keeps doing a manual cast to 32 or whatever, and it says it was expecting scaled fp8 (which I loaded yet it says it's not there???)

What could be the problem? :)
Thanks

### Other

Current usage of VRAM (despite very SLOW iterations):
![image](https://github.com/user-attachments/assets/be2f5a39-91ed-4631-abb2-4cd065d3d58b)
![image](https://github.com/user-attachments/assets/4db83cef-dcf0-4a52-89b8-401e59e7be9a)

**Comment by Brostopher** [comment]
https://github.com/kijai/ComfyUI-MochiWrapper 
Have you tried with these nodes?
