### ISSUE TITLE
SamplerCustomAdvanced - expected scalar type Half but found BFloat16

### ISSUE THREAD

**Issue by sorc1900** [comfyanonymous/ComfyUI#5503]
### Your question

When my workflow gets to about 30% I get this error (per the subject).

I am running an RTX5000, I have 196gb ram in my machine and I use the nvidia.bat to launch Comfy.  I have seen a number of posts where people say to use certain parameters when loading but I simply use the .bat.

I would love to know if there is a attribute to add to the .bat file or somewhere in a py file or a node to get around this error.

Many thanks.

**Comment by ThisCodeIsMine** [comment]
Same here.. But it doesn't seem this is getting a fix...

**Comment by RuneGjerde** [comment]
Same issue here. Hope it can be fixed, would love to use this extension

**Comment by MifuneJackson** [comment]
Exact same issue here.

**Comment by sorc1900** [comment]
Found the fix here
https://github.com/balazik/ComfyUI-PuLID-Flux/commit/5867d664e55a9a2736f10f451ee6b4a64c679ee3

**Comment by ltdrdata** [comment]
Is this issue occurring only when using PuLID?

**Comment by RuneGjerde** [comment]
issue is with with PuLID for me yes

**Comment by kapedi** [comment]
same here for me

**Comment by navarisun1982** [comment]
same here, is there any solution ?

**Comment by ltdrdata** [comment]
It seems that updating **ComfyUI-PuLID-Flux** resolves the issue.  
Closing this as it is related to a custom node issue.
