### ISSUE TITLE
py:784: FutureWarning: You are using `torch.load` with `weights_only=False` 

### ISSUE THREAD

**Issue by IAFFeng** [comfyanonymous/ComfyUI#5516]
### Expected Behavior

There is a long list of security reminders. I hope it can be fixed as soon as possible. I don’t want to see

### Actual Behavior

py:784: FutureWarning: You are using `torch.load` with `weights_only=False` 

### Steps to Reproduce

The ultralyticsf segmentation image model appears when loading. It seems that most models have prompts when loading. For some models, I added weights_only=True to the code, and the error prompt does not exist. However, this modification will report an error. You may need to load all weights before running.

### Debug Logs

```powershell
H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\nn\tasks.py:784: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")
```

**Comment by ltdrdata** [comment]
In my tests, this warning is not occurring in the latest PyTorch and latest ComfyUI.
Are you sure your environment is up to date?

```
pytorch version: 2.6.0.dev20241106+cu124
```

**Comment by IAFFeng** [comment]
> 在我的测试中，最新的 PyTorch 和最新的 ComfyUI 中没有出现此警告。 您确定您的环境是最新的吗？
> 
> ```
> pytorch version: 2.6.0.dev20241106+cu124
> ```

My version is: pytorch version: 2.5.1+cu124. Isn't the latest version pytorch: 2.5.1? I just updated it not long ago

**Comment by IAFFeng** [comment]
> In my tests, this warning is not occurring in the latest PyTorch and latest ComfyUI. Are you sure your environment is up to date?
> 
> ```
> pytorch version: 2.6.0.dev20241106+cu124
> ```

My version is: pytorch version: 2.5.1+cu124. Isn't the latest version pytorch: 2.5.1? I just updated it not long ago

**Comment by IAFFeng** [comment]
> > > In my tests, this warning is not occurring in the latest PyTorch and latest ComfyUI. Are you sure your environment is up to date?
> > > ```
> > > pytorch version: 2.6.0.dev20241106+cu124
> > > ```
> > 
> > 
> > My version is: pytorch version: 2.5.1+cu124. Isn't the latest version pytorch: 2.5.1? I just updated it not long ago
> 
> I'm using the nightly version.

OK, thanks. To upgrade pytorch, do I need to download a new compressed package or directly execute update_comfyui_and_python_dependencies.bat? This is a bit troublesome. The desktop version does not need it, right? It should be updated automatically, right?

**Comment by IAFFeng** [comment]
> > To upgrade pytorch, do I need to download a new compressed package or directly execute update_comfyui_and_python_dependencies.bat?
> 
> Just go into the python_embeded folder where you have comfyui installed, at the folder address bar at the top: type cmd and press enter. This will open a command prompt already pathed to the directory.
> 
> Then run `python.exe -m pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124` and this will install it to your comfyui's python virtual environment.
> 
> Any time you want to manually install something to comfyui's embedded python, just navigate to that directory and run `python.exe -m pip <stuff you want to do here>`

This is the same as the one executed in update_comfyui_and_python_dependencies.bat

**Comment by IAFFeng** [comment]
> > > To upgrade pytorch, do I need to download a new compressed package or directly execute update_comfyui_and_python_dependencies.bat?
> > 
> > 
> > Just go into the python_embeded folder where you have comfyui installed, at the folder address bar at the top: type cmd and press enter. This will open a command prompt already pathed to the directory.
> > Then run `python.exe -m pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124` and this will install it to your comfyui's python virtual environment.
> > Any time you want to manually install something to comfyui's embedded python, just navigate to that directory and run `python.exe -m pip <stuff you want to do here>`
> 
> This is the same as the one executed in update_comfyui_and_python_dependencies.bat

Oh, yours is the night version

**Comment by ltdrdata** [comment]
Check the ComfyUI version first before upgrading pytorch.
It's more likely that this issue is caused by an outdated ComfyUI rather than something that could be resolved by upgrading pytorch.

**Comment by IAFFeng** [comment]
> Check the ComfyUI version first before upgrading pytorch. It's more likely that this issue is caused by an outdated ComfyUI rather than something that could be resolved by upgrading pytorch.

But I am using the latest version v0.2.7, and the latest pull has not been synchronized yet. This should not be the problem. This problem is a bit strange, but it can complete the work and run. I will ignore it for now.

**Comment by IAFFeng** [comment]
> Check the ComfyUI version first before upgrading pytorch. It's more likely that this issue is caused by an outdated ComfyUI rather than something that could be resolved by upgrading pytorch.

But I'm using the latest version v0.2.7, and I just downloaded the latest version, so this shouldn't be the problem. This problem is a bit strange.

**Comment by IAFFeng** [comment]
> Check the ComfyUI version first before upgrading pytorch. It's more likely that this issue is caused by an outdated ComfyUI rather than something that could be resolved by upgrading pytorch.

But I'm using the latest version v0.2.7, and I just git-pull the latest version, so this shouldn't be the problem. This problem is a bit strange.

**Comment by LukeG89** [comment]
@ltdrdata I also get the future warning with Ultralytics (but "py:833" instead of "py:784")

I'm using the latest ComfyUI and Pytorch 2.6.0.dev20241101+cu124.

> In my tests, this warning is not occurring in the latest PyTorch and latest ComfyUI.

Could it be the portable version?

@IAFFeng However, it's just a warning, so I guess you can just ignore it.

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-09 10:23:50.663403
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\python_embeded\python.exe
** ComfyUI Path: E:\ComfyUI
** Log path: E:\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\ComfyUI\custom_nodes\rgthree-comfy
   1.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.6.0.dev20241101+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.37
E:\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Impact-Pack (V7.11.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
### Loading: ComfyUI-Inspire-Pack (V1.6)
[Impact Pack] Wildcards loading done.
Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.6.0.dev20241101+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.51.9)
### ComfyUI Revision: 2817 [6ee066a1] | Released on '2024-11-08'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

[rgthree-comfy] Loaded 42 epic nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite: `ffmpeg_bin_path` is set to: /ffmpeg/bin
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "Be the change that you wish to see in the world." - Mahatma Gandhi


Import times for custom nodes:
   0.0 seconds: E:\ComfyUI\custom_nodes\cg-controller
   0.0 seconds: E:\ComfyUI\custom_nodes\quick-connections
   0.0 seconds: E:\ComfyUI\custom_nodes\loadImageWithSubfolders.py
   0.0 seconds: E:\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: E:\ComfyUI\custom_nodes\rgthree-comfy
   0.3 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager
   1.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.6 seconds: E:\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
Update ComfyUI
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
All extensions are already up-to-date.
got prompt
E:\python_embeded\Lib\site-packages\ultralytics\nn\tasks.py:833: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")
```

**Comment by IAFFeng** [comment]
> @ltdrdata I also get the future warning with Ultralytics (but "py:833" instead of "py:784")
> 
> I'm using the latest ComfyUI and Pytorch 2.6.0.dev20241101+cu124.
> 
> > In my tests, this warning is not occurring in the latest PyTorch and latest ComfyUI.
> 
> Could it be the portable version?
> 
> @IAFFeng However, it's just a warning, so I guess you can just ignore it.
> 
> ```powershell
> E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
> [START] Security scan
> [DONE] Security scan
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2024-11-09 10:23:50.663403
> ** Platform: Windows
> ** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
> ** Python executable: E:\python_embeded\python.exe
> ** ComfyUI Path: E:\ComfyUI
> ** Log path: E:\comfyui.log
> 
> Prestartup times for custom nodes:
>    0.0 seconds: E:\ComfyUI\custom_nodes\rgthree-comfy
>    1.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Total VRAM 8192 MB, total RAM 65277 MB
> pytorch version: 2.6.0.dev20241101+cu124
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
> Using pytorch cross attention
> Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
> [Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.37
> E:\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
>   @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
> ### Loading: ComfyUI-Impact-Pack (V7.11.2)
> ### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
> ### Loading: ComfyUI-Inspire-Pack (V1.6)
> [Impact Pack] Wildcards loading done.
> Total VRAM 8192 MB, total RAM 65277 MB
> pytorch version: 2.6.0.dev20241101+cu124
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
> ### Loading: ComfyUI-Manager (V2.51.9)
> ### ComfyUI Revision: 2817 [6ee066a1] | Released on '2024-11-08'
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
> 
> [rgthree-comfy] Loaded 42 epic nodes. 🎉
> 
> WAS Node Suite: OpenCV Python FFMPEG support is enabled
> WAS Node Suite: `ffmpeg_bin_path` is set to: /ffmpeg/bin
> WAS Node Suite: Finished. Loaded 218 nodes successfully.
> 
>         "Be the change that you wish to see in the world." - Mahatma Gandhi
> 
> 
> Import times for custom nodes:
>    0.0 seconds: E:\ComfyUI\custom_nodes\cg-controller
>    0.0 seconds: E:\ComfyUI\custom_nodes\quick-connections
>    0.0 seconds: E:\ComfyUI\custom_nodes\loadImageWithSubfolders.py
>    0.0 seconds: E:\ComfyUI\custom_nodes\websocket_image_save.py
>    0.0 seconds: E:\ComfyUI\custom_nodes\stability-ComfyUI-nodes
>    0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI_experiments
>    0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
>    0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
>    0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-KJNodes
>    0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI_essentials
>    0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
>    0.1 seconds: E:\ComfyUI\custom_nodes\rgthree-comfy
>    0.3 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager
>    1.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
>    1.6 seconds: E:\ComfyUI\custom_nodes\was-node-suite-comfyui
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188
> FETCH DATA from: E:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
> Update ComfyUI
> FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
> All extensions are already up-to-date.
> got prompt
> E:\python_embeded\Lib\site-packages\ultralytics\nn\tasks.py:833: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
>   ckpt = torch.load(file, map_location="cpu")
> ```

It seems that your Pytorch 2.6.0.dev20241101+cu124 has the same warning. Can it complete the task? I can

**Comment by LukeG89** [comment]
> It seems that your Pytorch 2.6.0.dev20241101+cu124 has the same warning. Can it complete the task? I can

Yes, as I said, it's just a warning (a security warning about pickle files), so it can be just ignored.

**Comment by IAFFeng** [comment]
> > It seems that your Pytorch 2.6.0.dev20241101+cu124 has the same warning. Can it complete the task? I can
> 
> Yes, as I said, it's just a warning (a security warning about pickle files), so it can be just ignored.

I have obsessive-compulsive disorder, I don't want to see errors, I just want to be clean, I'll ignore it for now

**Comment by ltdrdata** [comment]
I just investigated this issue.

If it's occurring in ultralytics, it has nothing to do with ComfyUI.
This is an issue with the latest ultralytics package, and the problem lies with the model being used.
Unfortunately, if we don't ignore this issue, all existing models will become unusable.

Although it's not the recommended approach, I plan to patch it in impact pack to ignore the issue.
(you can downgrade ultralytics until then.)
Anyway, since this is unrelated to ComfyUI, I will close this.

**Comment by AJaeger74** [comment]
I updated my Pytorch to get this fixed
