### ISSUE TITLE
Any idea how to make Stable Video GEN Faster? (And consumer more GPU?)

### ISSUE THREAD

**Issue by moreAImore** [comfyanonymous/ComfyUI#5518]
### Your question

Any idea how to make Stable Video GEN Faster? (And consumer more GPU?) Or at least be able to run 2 gen AT ONCE? 
Can we do that if we run 2 Comfy at once? 
I want to use the rest of GPU, as you can see it is NOT BEING USED ALL Here:
![image](https://github.com/user-attachments/assets/355bfdb8-2309-481f-8c6e-d5e5fb53dde7)

(Posted it here because this is native to ComfyUI, not a custom node ;))

**Comment by ltdrdata** [comment]
At present, the only available method is to run multiple instances of ComfyUI separately on each GPU.

**Comment by moreAImore** [comment]
> At present, the only available method is to run multiple instances of ComfyUI separately on each GPU.
> 
> ```
>   --cuda-device DEVICE_ID
>                         Set the id of the cuda device this instance will use.
> ```

Meaning using multiple GPUs. 
I see
