### ISSUE TITLE
Arithmetic Operation Nodes

### ISSUE THREAD

**Issue by rhdunn** [comfyanonymous/ComfyUI#5527]
### Feature Idea

Add nodes to support arithmetic operations (addition, subtraction, multiplication, and division) on two INTEGER or FLOAT inputs producing an INTEGER or FLOAT output as follows:
- INTEGER ~ INTEGER -> INTEGER
- INTEGER ~ FLOAT -> FLOAT
- FLOAT ~ INTEGER -> FLOAT
- FLOAT ~ FLOAT -> FLOAT

Note: There should be an integer division operation that always produces an INTEGER result. It could take a rounding mode option:
- floor -- select the lower integer value
- round -- if 0.5 or greater then round up, otherwise round down
- round to zero -- select the closest integer to zero

### Existing Solutions

Creating a custom node, e.g.:
```python
ARITHMETIC_OPERATION = ("addition", "subtraction", "multiplication", "division")

class IntegerArithmeticNode:
    @classmethod
    def INPUT_TYPES(cls):
        return {"required": {"a": ("INT", {"defaultInput": True}),
                             "b": ("INT", {"defaultInput": True}),
                             "operation": (ARITHMETIC_OPERATION, {"default": "addition"}),},
               }

    RETURN_TYPES = ("INT", )
    RETURN_NAMES = ("c", )
    FUNCTION = "apply"

    def apply(self, a, b, operation):
        if operation == "addition":
            return (a + b, )
        if operation == "subtraction":
            return (a - b, )
        if operation == "multiplication":
            return (a * b, )
        if operation == "division":
            return (a // b, )
        raise Exception(f"Unsupported operation: {operation}")
```

### Use Case
Calculating the `steps` and `start_at_steps` values for a KSampler in image-to-image, pre/post refiner, upscaler, etc. workflows. Here:
- the `start_at_steps` is the `start_at_steps` for the previous phase added to the steps in the current phase;
- the `steps` is the sum of the steps in all phases, or the `start_at_steps` of the last phase added to the steps in that phase.

This helps prevent errors when adjusting the `steps`/`start_at_steps` across multiple phases.

### Notes
It's not possible to perform the type logic with custom nodes so there has to be a separate custom node for each type combination.

**Comment by ltdrdata** [comment]
You can find mutiple custom nodes for arithmetic operation.
This is one of the oldest node.
https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes
