### ISSUE TITLE
[Feature Request] Multiple Torch/cuda versions SWAPPING withing ONE comfy installation.

### ISSUE THREAD

**Issue by GPU-server** [comfyanonymous/ComfyUI#5529]
### Feature Idea

This will solve all problems.
Simple, user wanna try the best torch/cuda combination for a certain custom node? Just select it and press restart, comfy will restart with everything (that is not affected by torch) the samme, and all other libraries that depend on the torch version (such as transformer or whatever) and cuda of course well.. changed.

No more problem with pack 3D.
nor problem with custom nodes that decrease versions of my current torch. No more comfy stopping workign and being break.

harder to write than to implement? Perhaps Impossible? I don't know :).

**Comment by ltdrdata** [comment]
For this, you need to set up multiple venvs directly and install separate pip dependencies for each venv.
