### ISSUE TITLE
VRAM remaining after excecuting comfy.model_management.unload_all_models()

### ISSUE THREAD

**Issue by jsjtczh** [comfyanonymous/ComfyUI#5536]
### Your question

Why is it that after executing the command comfy.model_management.unload_all_models(), the GPU memory usage does not clear back to its initial state (i.e., a few hundred MB as seen with nvidia-smi), and there remains 1-2 GB of residual GPU memory, which only returns to the initial state after killing the process and restarting Comfy? How to completely clear GPU memory usage in comfy?

**Comment by comfyanonymous** [comment]
Are you using any custom nodes?

**Comment by jsjtczh** [comment]
> Are you using any custom nodes?

Thanks for your reply. Yes, I've used some custom nodes. I'm also suspecting that it might be due to some custom nodes. So, is comfy.model_management.unload_all_models() not able to completely clear the models loaded by custom nodes? Do I have to go through each custom node and delete the model in the code using something like “del model"? Is there any way to uniformly clear all GPU memory usage?

**Comment by ltdrdata** [comment]
> > Are you using any custom nodes?
> 
> Thanks for your reply. Yes, I've used some custom nodes. I'm also suspecting that it might be due to some custom nodes. So, is comfy.model_management.unload_all_models() not able to completely clear the models loaded by custom nodes? Do I have to go through each custom node and delete the model in the code using something like “del model"? Is there any way to uniformly clear all GPU memory usage?

ComfyUI's model manager functionality can only manage models that are managed by ComfyUI.
It cannot handle VRAM usage that occurs outside of ComfyUI.
