### ISSUE TITLE
CLIP Text Encode (Prompt) node - too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by 4lt3r3go** [comfyanonymous/ComfyUI#5539]
### Expected Behavior

_

### Actual Behavior

_

### Steps to Reproduce

_

### Debug Logs

```powershell
_
```

### Other

only happening sometimesm with no apparent reasons.
no other nodes involved. simple flux workflow.
using latest comfy version.

**Comment by 4lt3r3go** [comment]
```
!!! Exception during processing !!! too many values to unpack (expected 2)
Traceback (most recent call last):
  File "F:\Comfy2\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Comfy2\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Comfy2\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\Comfy2\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Comfy2\ComfyUI\nodes.py", line 65, in encode
    output = clip.encode_from_tokens(tokens, return_pooled=True, return_dict=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Comfy2\ComfyUI\comfy\sd.py", line 127, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Comfy2\ComfyUI\comfy\text_encoders\flux.py", line 55, in encode_token_weights
    t5_out, t5_pooled = self.t5xxl.encode_token_weights(token_weight_pairs_t5)
    ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

Prompt executed in 5.90 seconds
```

**Comment by ltdrdata** [comment]
What is your workflow?

**Comment by 4lt3r3go** [comment]
![image](https://github.com/user-attachments/assets/32de218a-10b5-4043-aa0b-978b8899518c)

whatever workflow. even the simpliest one. 
the error kicks in randomly.

**Comment by 4lt3r3go** [comment]
same 
![image](https://github.com/user-attachments/assets/122e6545-6391-4bd2-941d-33451846283d)

**Comment by 4lt3r3go** [comment]
i swapped the node with "load diffusion model" and worked.
I don't understand how it is possible that worked before, sometimes yes sometimes no, with this other model loader node.
so looks like the loader node was the issue

**Comment by 4lt3r3go** [comment]
no. the issue is still there even when using this other node.
must be something else

**Comment by 4lt3r3go** [comment]
sometimes i can fix it for a while when i switch to another clip and then switch back to clip_l 
then the problem comes again
https://github.com/user-attachments/assets/2c2a8699-0f70-4961-ae5c-15bde54ebe13

**Comment by 4lt3r3go** [comment]
https://huggingface.co/comfyanonymous/flux_text_encoders/blob/main/clip_l.safetensors

i always used that clip_l and as you can see sometimes works.
only having this issue with last comfy update.
i even did a clean install and still having the issue

**Comment by ltdrdata** [comment]
oh.. that's weird. Is your ComfyUI latest version?

**Comment by 4lt3r3go** [comment]
yes
comfy latest downloaded 2 days ago
the issue occur even with standard workflow. any workflows

**Comment by ltdrdata** [comment]
> yes comfy latest downloaded 2 days ago the issue occur even with standard included workflows. any workflows

What's in the workflow isn't the important part - what's important is whether the custom nodes are installed.
Sometimes certain custom nodes can change the basic operation.

**Comment by 4lt3r3go** [comment]
this is my custom node list i just finished reinstall cause i made a clean install to try solve this problem and is still here.
i had way more nodes before and everythig was working exceptionally, then i updated comfy.

please don't tell me i have to install everything again from the beginning😢
what can i do? i'm loosing days in this.
![image](https://github.com/user-attachments/assets/4dcb9138-b7d6-4bfa-8e75-458e7cc9e921)

**Comment by ltdrdata** [comment]
> this is my custom node list i just finished reinstall cause i made a clean install to try solve this problem and is still here. i had way more nodes before and everythig was working exceptionally, then i updated comfy.
> 
> please don't tell me i have to install everything again from the beginning😢 what can i do? i'm loosing days in this. ![image](https://private-user-images.githubusercontent.com/44883288/384636454-4dcb9138-b7d6-4bfa-8e75-458e7cc9e921.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExODAyNTgsIm5iZiI6MTczMTE3OTk1OCwicGF0aCI6Ii80NDg4MzI4OC8zODQ2MzY0NTQtNGRjYjkxMzgtYjdkNi00YmZhLThlNzUtNDU4ZTdjYzllOTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDE5MTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMzc0MDAxZmJmOGFkNmMyMGQwOTkzMGM2NzYzMWRjMDc5NWRhOTBjZjhjMDNjYWY5NzRhNWQ5Y2Y4NzkxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2JDzv4ruopDCEq1xJMLY_n7pm3we5zQ_B1KI0kOefQA)

Try move out all custom nodes from the custom_nodes directory and check if the issue still reproduce.

**Comment by 4lt3r3go** [comment]
moved folder away in another folder
loaded comfy and worked (who knows if is temporary thing as is always doing?
moved all custom nodes back to their original places and now i have import failed, should i do something else?
![image](https://github.com/user-attachments/assets/b6705a52-0ef0-4de8-869f-aa32c726535e)

**Comment by ltdrdata** [comment]
> moved folder away in another folder loaded comfy and worked (who knows if is temporary thing as is always doing? moved all custom nodes back to their original places and now i have import failed, should i do something else? ![image](https://private-user-images.githubusercontent.com/44883288/384639560-b6705a52-0ef0-4de8-869f-aa32c726535e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTE0OTIsIm5iZiI6MTczMTIxMTE5MiwicGF0aCI6Ii80NDg4MzI4OC8zODQ2Mzk1NjAtYjY3MDVhNTItMGVmMC00ZGU4LTg2OWYtYWEzMmM3MjY1MzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDAzNTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YzNmMDY0NzZkYzM2MjI1NmIxYTNhZDYwNmM2NzI4ZjQwZmRhZGI3NzEwZjc3OTAxYmEyYzY3MWY3NTNiOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bLRF-RGy8tFATqPSbhaReCsqK8aq5vunaOCJIcB8yVE)

Did you move only the contents inside the directory while keeping the directory itself in place?

**Comment by 4lt3r3go** [comment]
the issue in not resolved.
i had to reinstall the nodes one by one and testing at each install 
then randomly the issue come back, wich make me think "oh ok i found the node, let me move it away"
i move it away and the issue is there.
i move away other nodes: still there.
at that point i just rolled back to a previous comfy and reinstalled everything again, for the 4th time 😑
and now no issues whatsoever.

thank you for your time
