### ISSUE TITLE
Need Help using the REPOSER workflow by Nerdy Rodent

### ISSUE THREAD

**Issue by PoulsCL** [comfyanonymous/ComfyUI#5544]
### Your question

If anyone has been using or has used the workflow id appreciate to hace your help with this issue Im trying to generate  but im faceing this problem
![image](https://github.com/user-attachments/assets/4292eda6-ab9d-45ec-8cce-683cb418113e)
![Captura de pantalla 2024-11-08 120426](https://github.com/user-attachments/assets/02681478-e307-4b9d-a0b4-144e3e6e5554)
I already tried using this is this it? https://huggingface.co/InvokeAI/ip-adapter-full-face_sd15/tree/main and placed it here
![image](https://github.com/user-attachments/assets/8d4eaa45-ca4e-4b24-81b1-22d0238ff663)

**Comment by ltdrdata** [comment]
That is an invalid model folder.
https://github.com/cubiq/ComfyUI_IPAdapter_plus#installation
