### ISSUE TITLE
Will someone help out a Noob?

### ISSUE THREAD

**Issue by reefor** [comfyanonymous/ComfyUI#5548]
### Your question

I have 2 or 3 issues, I'm using Comfy Portable on an old Windows machine.

I don't think I've ever been able to install llama. I get the error message below when I boot up Comfy but it still runs so I never worried about it. Is llama important and do I need to install it. If so, can someone please tell me which folder to do the CMD install?
This is the error message:
from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

This one is new and more concerning. This error message just started today. I know nothing about Python, do I need to upgrade it? Is it as simple as finding it and doing the PIP install in a certain folder via CMD? If so, what version should I look for and what folder to I install it in?
Unsupported Python version. Please use Python 3.9, 3.10 or 3.11.

The problems I notice:
It's always run slow. For example, when using Liveportrait vid2vid I can only do 2 second segments at a time, anything more will lock up my computer. And it takes about a half hour to do a 2 second clip. I always just assumed it's because I have an old system and not enough vram & ram.

The new problem since downloading the latest version of portable is that the webui locks up. I have to drop in the Liveportrait workflow then refresh the page before it will unlock. By locking up I mean I can't do anything on the main screen but the right hand side with the nodes manager still works. Not sure what's causing it and there are no error messages to point me in the right direction.

Anyway, if someone can shed some light on the llama & python version things, I'd really appreciate it

### Logs

```powershell
I'm running portable and don't see any folder for "system" or "logs". If there is one of if I have to get to it a different way please let me know and I'll be happy to post it.
```

**Comment by ltdrdata** [comment]
Performance issues are typically due to hardware specifications so I cannot comment on those. 
To diagnose the other issues, please provide the full log first.

**Comment by reefor** [comment]
> Performance issues are typically due to hardware specifications so I cannot comment on those. To diagnose the other issues, please provide the full log first.

I'd love to, but I can't find the log. If you can tell me where to look I'll post it. I'm running Comfy Portable and can't seem to find the folder.

**Comment by reefor** [comment]
I also recently ran the 3 update bat files. (update_comfyui, update_comfyui_and_python_dependencies, & update_comfyui_stable)

**Comment by psycottx** [comment]
this fixed that issue for me 

pip install llama-cpp-python==0.1.78 --no-cache-dir

you should consider more vram that's no good for videos at all, maybe try running using cloud service

**Comment by ltdrdata** [comment]
```
"C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\gptcpp_node.py", line 4, in
from llama_cpp import Llama
```

This log indicates that this is an issue that should be addressed in ComfyUI-N-Nodes repo.

**Comment by reefor** [comment]
> this fixed that issue for me
> 
> pip install llama-cpp-python==0.1.78 --no-cache-dir
> 
> you should consider more vram that's no good for videos at all, maybe try running using cloud service

Thanks, I guess that's a requirement of the comfy-n-nodes, I'll post a msg there so they can add it to the requirements.txt. Do I install that  I'm guessing I just run that in the main folder (C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes), or do I run it in one of the folders in the main folder?

I know I need more vram, my laptop is old. I'm trying to save for a new one now. Till then I just have to try to muttle through.

**Comment by reefor** [comment]
> "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\gptcpp_node.py", line 4, in
> from llama_cpp import Llama
> ```
> 
> This log indicates that this is an issue that should be addressed in ComfyUI-N-Nodes repo. And for some reason, the dependencies were not installed properly during installation process.

Thanks, I'm trying to fix that now. And now that I see the line above that indicates it's in the N Nodes I can hopefully do better reading this kind of thing from now on.

I don't see a custom node listed above the Python error. I'm running portable, does portable use Cuda instead of Python? Or is it something else?

**Comment by reefor** [comment]
> > this fixed that issue for me
> > pip install llama-cpp-python==0.1.78 --no-cache-dir
> > you should consider more vram that's no good for videos at all, maybe try running using cloud service
> 
> Thanks, I guess that's a requirement of the comfy-n-nodes, I'll post a msg there so they can add it to the requirements.txt. Do I install that I'm guessing I just run that in the main folder (C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes), or do I run it in one of the folders in the main folder? Or do I install it in the PY folder?
> 
> I know I need more vram, my laptop is old. I'm trying to save for a new one now. Till then I just have to try to muttle through.

Nevermind, I figured it out. The same folder as the requirement.txt file I'm guessing. Hope that's right :)
