### ISSUE TITLE
Image generation quality Flux

### ISSUE THREAD

**Issue by Eroy09** [comfyanonymous/ComfyUI#5569]
### Your question

This is now happening in comfyui for me (original issue encounter was forge though)
-----------------------
Original message -

I run forge webui from a custom notebook in Google colab, I use the A100 GPU (NVIDIA), it has 40GB VRAM. Using for continuously since the support of flux has made it my preference.

Over the past few weeks though, (with no changes to my routine) attempting similar tasks now nearly always results in terrible image quality that was not present in the earlier days (like early August to early September) of Flux support. The image issues usually are along the lines of blurry, artifact ridden, pixelated, unfinished, uncanny… and other similarities of that nature.

Interestingly though, reverting to a previous commit does not solve the issue… Making me think maybe it’s a dependency within the colab environment, or some update to their memory, GPU/AI architecture, or other changes variable related to processing on forge, maybe? I don’t know.

I’m seeking any recommendations or ideas that anyone has about this issue, particularly if you have similar troubles and have potentially found some workaround? Thank you all in advance.

++ If you have a commit recommendation please share as I will be happy to try!

Attached is a PNG with generation parameters in the metadata from forge
r/FluxAI - Inquiry for recent flux issues

### Other

(https://github.com/black-forest-labs/flux/issues/192#issue-2646639226)

**Comment by ltdrdata** [comment]
What is your workflow?

**Comment by Eroy09** [comment]
[MultiUseOptimized.json](https://github.com/user-attachments/files/17708348/MultiUseOptimized.json)
--------------------
Using the txt2img group of this work flow only, i am able to reproduce some poopy quality image that i originally got from forge, attached to the image is parameter metadata for generation 
--------------------------------
![00000-4132367344](https://github.com/user-attachments/assets/1cbd13ed-b2c5-4701-b919-42a4519c7957)

**Comment by ltdrdata** [comment]
> Using the txt2img group of this work flow only, i am able to reproduce some poopy quality image that i originally got from forge, attached to the image is parameter metadata for generation

I tried to reproduce it by loading that workflow, but your result image and prompt appear to be completely different with attached json.
And your workflow combining a lot of LoRAs - did you get that bad quality image while using so many LoRAs combined together as well?
