### ISSUE TITLE
Half Loading

### ISSUE THREAD

**Issue by Stein59** [comfyanonymous/ComfyUI#5578]
### Your question

I had installed comfyui, and had lot of fun. But as i was restarting the program to implement Lora training tools the PC crashed, (Windows11) and when i tried to start it again, it simply didn't. Its initial cmd screen said program paused, complaints over cuda not enabled and something torch. And press any key to continue... So any key i pressed made the Init screen close and no program was launched. 
So i thought reinstall could be a thing. Files removed, downloaded again, unzipped and placed. This time the program just half loads. Below is a pic of how it looks. Its not usable, and i didn't get further. I have done a Python reinstall/restore to get path updated. But otherwise i am simply out of ideas of what i can do, and in what direction i shall look. So I am desperate for a hint.

![C-Ui](https://github.com/user-attachments/assets/ce803f16-e6f2-4351-b0eb-ce2b5ddc8577)

### Logs

```powershell
The init message:
C:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 16376 MB, total RAM 32581 MB
pytorch version: 2.3.1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\AI\ComfyUI_windows_portable\ComfyUI\web

Import times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by ltdrdata** [comment]
Try with a different browser.

**Comment by Stein59** [comment]
I have now also tried Opera, chrome and firefox, but no change, but thanks for ideas, I fear i must reinstall windows, which i really dont want to

**Comment by Stein59** [comment]
So i run update_comfyui.bat and the server/browser went blank. As i tried the other browsers, some few things showed up in Chrome. similar to depicted, but on black. The init screen says pytorchversion: 2.3.1+cu118 , that is the same as before.
Isnt there anything i can ask the cmd ?

**Comment by Stein59** [comment]
Java enabled, and browser refreshed. I dont know why, but Comfyui chooses my microsoft edge only, and i dont know how to change that. I dont use it for anything else so it is basic and default.

However as i think back, i tried to install 4-5 things when it crashed and upon restart i watched it work, a lot, to install those things. SO something must have happened there which made change to my pc.  It is therefore annoying that there is no uninstalling procedure which could revert situation to what it was, Or what is common to do in difficult situations?

**Comment by ltdrdata** [comment]
> Java enabled, and browser refreshed. I dont know why, but Comfyui chooses my microsoft edge only, and i dont know how to change that. I dont use it for anything else so it is basic and default.
> 
> However as i think back, i tried to install 4-5 things when it crashed and upon restart i watched it work, a lot, to install those things. SO something must have happened there which made change to my pc. It is therefore annoying that there is no uninstalling procedure which could revert situation to what it was, Or what is common to do in difficult situations?

When running ComfyUI, Edge launches because Edge is selected as the default browser in your Windows settings.
