### ISSUE TITLE
 clip missing: ['text_projection.weight']

### ISSUE THREAD

**Issue by IAFFeng** [comfyanonymous/ComfyUI#5579]
### Expected Behavior

Can it be corrected?

### Actual Behavior

All are updated versions, this problem still exists: clip missing: ['text_projection.weight']

### Steps to Reproduce

Standard flux dev fp8 workflow for generating images from text

### Debug Logs

```powershell
clip missing: ['text_projection.weight']
```

**Comment by ltdrdata** [comment]
duplication:
https://github.com/comfyanonymous/ComfyUI/issues/5222
