### ISSUE TITLE
Blank Screen on loading ComfyUI (Found solution whilst debugging) 

### ISSUE THREAD

**Issue by tomscwills** [comfyanonymous/ComfyUI#5582]
### Expected Behavior

Loading ComfyUi with last workflow 

### Actual Behavior

Blank screen shows up, UI present able to use the UI buttons, unable to add additional nodes to the screen. Unable to change workflows or add additional nodes
![actual_behaviour_console_log](https://github.com/user-attachments/assets/b1b1b813-3bae-46d4-8477-489197817282)
![actual_behaviour](https://github.com/user-attachments/assets/6ec7274f-5931-4013-afe6-6adb100a5448)
![expected behaviour](https://github.com/user-attachments/assets/eefc0829-f667-40a8-8e3e-75dc037a8962)

### Steps to Reproduce

Have ComfyUI_frontend v1.3.39 installed. 

### Debug Logs

```powershell
N/A
```

### Other

(SOLUTION) turns out whilst creating this bug report that issue was I had ComfyUI_front end v1.3.39 installed (Nil issues earlier in the same day). When I imitated update all via Comfy Manager all the issues were fixed. 
The reasoning for continuing with this post was to help others who may have similar issue in the future. I have added it here as neither CMD logs or chrome debug/console referred to ComfyUI_frontend (at least to someone with moderate knowledge) and I think lots of people will refer here first before triaging to other sources. 
Creators/Mods - Thankyou for all you hard work I love using ComfyUI, thought this may help with novice users.

**Comment by huchenlei** [comment]
You are probably using a frontend-only custom node that does not inherit from LGraphNode class. Can you file a bug in the frontend repo with a list of nodes you used? Also please make sure these nodes are updated to latest version. Thanks!

**Comment by huchenlei** [comment]
@webfiltered PTAL. I think a custom might be doing something wield on litegraph internals, but I cannot think of anything that could be related.
