### ISSUE TITLE
how to add controlnet when we using samplercustomadvanced node

### ISSUE THREAD

**Issue by Nomination-NRB** [comfyanonymous/ComfyUI#5588]
### Your question

how to add controlnet when we using samplercustomadvanced node?
If it is possible?

This is the part of my workflow, I want to add controlnet condition
![image](https://github.com/user-attachments/assets/e70d3250-7741-47d1-9317-91d0bfa585f6)

**Comment by ltdrdata** [comment]
Simply apply it to the `conditioning` that goes into the `BasicGuider`. 
For cases where `negative` conditioning isn't used (like in BasicGuider), you can just ignore the `negative` output.

**Comment by Nomination-NRB** [comment]
> Simply apply it to the `conditioning` that goes into the `BasicGuider`. For cases where `negative` conditioning isn't used (like in BasicGuider), you can just ignore the `negative` output.

Thanks for your reply, but I want to use flux controlnet, and I can't line controlnet_condition to condition
![image](https://github.com/user-attachments/assets/7dabfc41-6ce0-49f1-9dce-b3a16c650dc1)

**Comment by ltdrdata** [comment]
> > Simply apply it to the `conditioning` that goes into the `BasicGuider`. For cases where `negative` conditioning isn't used (like in BasicGuider), you can just ignore the `negative` output.
> 
> Thanks for your reply, but I want to use flux controlnet, and I can't line controlnet_condition to condition
> ![image](https://github.com/user-attachments/assets/7dabfc41-6ce0-49f1-9dce-b3a16c650dc1)
> 

That node is not a part of ComfyUI core. You need to inquire about it to the related repo.
