### ISSUE TITLE
No Prompt Error with Flux Upscaling API Workflow in CLI

### ISSUE THREAD

**Issue by yogotatara3** [comfyanonymous/ComfyUI#5593]
### Your question

Hey everyone,

I’m trying to execute my flux upscaling API workflow via CLI, but I keep running into an issue. Every time I attempt to generate an upscaled image, 

I get this error in my execution output: 
{"error": "no prompt", "node_errors": []} 
C:\Users\RAIIN Studios\Downloads>curl -X POST --data [@Raiin_upscalerefine](https://t.me/Raiin_upscalerefine).json http://127.0.0.1:8188/prompt

In the ComfyUI CLI, I see this:
[WARN] ComfyUI-Impact-Pack: Error on prompt - several features will not work. 'prompt' 
[ERROR] An error occurred during the on_prompt_handler processing Traceback (most recent call last): File "c:\tools\StabilityMatrix\Packages\ComfyUI\[server.py](https://server.py/)", line 862, in trigger_on_prompt json_data = handler(json_data) File "C:\tools\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\inspire_[server.py](https://server.py/)", line 366, in onprompt workflow_loadimage_update(json_data) File "C:\tools\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\inspire_[server.py](https://server.py/)", line 253, in workflow_loadimage_update prompt = json_data['prompt'] KeyError: 'prompt' 

Interestingly, everything works fine in the web interface, so it seems like an issue specifically with the CLI. I've also recently updated my ComfyUI environment to Torch 2.51 + Cu12.4.

I’ve read that Flux can be pretty buggy, so I'm wondering if anyone else has run into this and found a fix. Tried a standard sd1.5 workflow with no issues and even converted the txt2img workflow to Flux, but I keep getting the same error. Any help from fellow diffusers would be greatly appreciated. Thanks in advance!

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-Inspire-Pack repo.
https://github.com/ltdrdata/ComfyUI-Inspire-Pack

**Comment by ltdrdata** [comment]
And, your API request is strange. Why wasn't a `prompt` provided?

**Comment by yogotatara3** [comment]
I exported the wf as API wf and Prompt field is not empty. Had it in string literal before. Then tried deleting the widget and placed it back in Clip text encode for flux. Is still not recognizing the prompt. Tried it with one of default workflows, wierdly with SD1.5 it works, the tried the normal clip text encode but same error. Do u have an Idea what the rpoblem could be?

**Comment by yogotatara3** [comment]
Also tried it with a fresh comfy instance via SDMatrix, just tried to execute the default txt2img wf again as apiwf but got a similar error again:

execute cli:
C:\Users\RAIIN Studios\Downloads>curl -X POST --data @txt2img_api.json http://127.0.0.1:8188/prompt
{"error": "no prompt", "node_errors": []}

and comfy sd matrix cli:
got prompt
got prompt

I use this curl command to execute:
curl -X POST -H "Content-Type: application/json" --data @txt2img_api.json http://127.0.0.1:8188/prompt

JSON here is 
[txt2img_api.json](https://github.com/user-attachments/files/17748038/txt2img_api.json)

**Comment by jeppevinkel** [comment]
Just for the sake of anyone arriving from search.  

The simple answer is that the json contents output from comfy can't be used directly as the request body, it should be used as the value for a property called `prompt`.
