### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [comfyanonymous/ComfyUI#5596]
### Expected Behavior

Hello,

Github Security Lab has found a potential vulnerability in ComfyUI. Please let us know a good point of contact to disclose privately. Github has [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) if you need a private point of contact.

Kevin

### Actual Behavior

N/A

### Steps to Reproduce

Disclosed Privately

### Debug Logs

```powershell
Disclosed Privately
```

**Comment by comfyanonymous** [comment]
I enabled the "Private vulnerability reporting".

**Comment by Kwstubbs** [comment]
I have submitted the report. Closing issue now.
