### ISSUE TITLE
Update broke PuLID

### ISSUE THREAD

**Issue by Pantonia4** [comfyanonymous/ComfyUI#5601]
### Expected Behavior

It should just work and run i guess

### Actual Behavior

Gives an Error and doesnt work.

### Steps to Reproduce

Just use PuLID.

### Debug Logs

```powershell
!!! Exception during processing !!! forward_orig() takes from 7 to 9 positional arguments but 10 were given
Traceback (most recent call last):
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 633, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy\samplers.py", line 740, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy\samplers.py", line 719, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy\samplers.py", line 624, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy\k_diffusion\sampling.py", line 155, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy\samplers.py", line 706, in __call__
    return self.predict_noise(*args, **kwargs)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy\samplers.py", line 709, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy\samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy\model_base.py", line 144, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\comfy\ldm\flux\model.py", line 181, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control, transformer_options)
TypeError: forward_orig() takes from 7 to 9 positional arguments but 10 were given
```

### Other

Going back one version makes it work again.

**Comment by amao2001** [comment]
the same error
forward_orig() takes from 7 to 9 positional arguments but 10 were given

**Comment by ltdrdata** [comment]
This is a backward compatibility issue.
This should be handled in the PuLID custom node repo.
Please move this issue to the repo.

**Comment by adydeejay** [comment]
It seems that the problem comes from [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeR181) line. I modified it back to [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeL159) and now image generation works with PuLID.

**Comment by Madushan996** [comment]
> It seems that the problem comes from [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeR181) line. I modified it back to [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeL159) and now image generation works with PuLID.

Thank you

**Comment by Malie73** [comment]
> It seems that the problem comes from [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeR181) line. I modified it back to [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeL159) and now image generation works with PuLID.

Great, thank you!

**Comment by fogostudio** [comment]
> It seems that the problem comes from [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeR181) line. I modified it back to [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeL159) and now image generation works with PuLID.
> 
> **_Please note that this is a temporary workaround for simple workflows with PuLID and is not a permanent fix; it may also impact the functionality of other nodes._**

That worked, thanks!

**Comment by prog-ape** [comment]
After updating to the latest version, several plugins have this problem.

**Comment by ialhabbal** [comment]
> It seems that the problem comes from [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeR181) line. I modified it back to [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeL159) and now image generation works with PuLID.
> 
> **_Please note that this is a temporary workaround for simple workflows with PuLID and is not a permanent fix; it may also impact the functionality of other nodes._**

Where can I find the [comfy/ldm/flux/model.py]? I couldn't find it in the portable ComfyUI installation.

**Comment by songkangfeng** [comment]
update to the latest version ,it doesn't work

**Comment by chenpipi0807** [comment]
不管事啊老师

**Comment by 2129518511** [comment]
删除transformer_options使pulid完全失效了

**Comment by 2129518511** [comment]
> 删除transformer_options使pulid完全失效了

以上问题是影响了大模型导致，更换大模型可以解决

**Comment by Fipu-merged** [comment]
For some reason code change in model.py resultet in Boolean value of Tensor with more than one value is ambiguous

**Comment by stoutimon** [comment]
> It seems that the problem comes from [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeR181) line. I modified it back to [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeL159) and now image generation works with PuLID.
> 
> **_Please note that this is a temporary workaround for simple workflows with PuLID and is not a permanent fix; it may also impact the functionality of other nodes._**

this has worked for me too

**Comment by sorc1900** [comment]
Does this fix work with portable?

**Comment by trai78** [comment]
Go into your comfyui folder > cmd > git reset --hard cc9cf6d1bd957d764ad418258b61d7e08187573b

**Comment by yropbv** [comment]
> It seems that the problem comes from [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeR181) line. I modified it back to [this](https://github.com/comfyanonymous/ComfyUI/commit/96b2080971b1e6606bdbaf2aa4f24b7faca3999a#diff-453e6e6c1a6fa355aa5f5b6aabb5f9153c526c115d08ad757c0243d9f8ca31eeL159) and now image generation works with PuLID.
> 
> **_Please note that this is a temporary workaround for simple workflows with PuLID and is not a permanent fix; it may also impact the functionality of other nodes._**

SamplerCustomAdvanced
Boolean value of Tensor with more than one value is ambiguous

I get this after changing this

**Comment by adydeejay** [comment]
https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced/issues/30

**Comment by aprisma2008** [comment]
> Go into your comfyui folder > cmd > git reset --hard [cc9cf6d1bd957d764ad418258b61d7e08187573b](url)

This works of course because it sets back to an older version. But then all the good new things like LTX Video aso. do not work any more. So till this is solved we have to switch between the version case to case. I hope they fix it with the new desktop model :-)

**Comment by swdvb** [comment]
Go into your comfyui folder > cmd > git reset --hard cc9cf6d1bd957d764ad418258b61d7e08187573b

Then start your comfy, it should help.

**Comment by chenpipi0807** [comment]
git reset --hard a72d152b0c8788b954004ee8c01e957701514e32

看起来我回退到了远古版本

**Comment by CaptailTyler** [comment]
The issue has now been fixed. Just update your FLUX PULID vis ComfyUI Manager.

**Comment by cgl13207205048** [comment]
> 此问题现已修复。只需使用 ComfyUI Manager 更新您的 FLUX PULID 即可。
> 
> 编辑：仍然收到“预期所有张量都在同一设备上，但发​​现至少两个设备，cuda：0 和 cpu！”
> 
> 请按照下面 adydeejay 的修复方法操作，因为它现在已经为我解决了所有问题。也不再有速度问题。

我试过更新comfyui和flux_pulid都不行

**Comment by nzmajid77** [comment]
I got the same problem. But today after I have updated my ComfyUI, the error is gone.

**Comment by chenpipi0807** [comment]
![微信截图_20241204192057](https://github.com/user-attachments/assets/9b2eb6d6-d1a5-45eb-b72b-7f67c5b85293)
forward_orig() takes from 7 to 9 positional arguments but 10 were given
这个问题依然存在
pulid插件也是最新版

**Comment by faizzed** [comment]
Use this repo instead https://github.com/zhangp365/ComfyUI-PuLID-Flux
