### ISSUE TITLE
Did this prompts format still work?

### ISSUE THREAD

**Issue by K-O-N-B** [comfyanonymous/ComfyUI#5602]
### Your question

I do want random one prompts in five of it:

{sitting|lie_down|squatting|standing|kneeling}

**Comment by LukeG89** [comment]
Yes, it's working


https://github.com/user-attachments/assets/35d90e21-d2c6-463c-ab1e-51f9167972c8

**Comment by adydeejay** [comment]
> Previously, it worked on all textbox widgets, but since it caused many problems, now it can only be used on textbox widgets where the feature has been explicitly enabled.

Hi @ltdrdata . I recently realized that {blue|red|yellow} no longer works in Power Prompt (rgthree). Has this feature been removed from ComfyUI or rgthree node? How can I reactivate it? Or do I need to use something else?

**Comment by ltdrdata** [comment]
> > Previously, it worked on all textbox widgets, but since it caused many problems, now it can only be used on textbox widgets where the feature has been explicitly enabled.
> 
> Hi @ltdrdata . I recently realized that {blue|red|yellow} no longer works in Power Prompt (rgthree). Has this feature been removed from ComfyUI or rgthree node? How can I reactivate it? Or do I need to use something else?

In that case, it's likely that Power Prompt hasn't been updated to accommodate changes in ComfyUI. 
It would be a good idea to ask about alternatives in the rgthree repo.

**Comment by adydeejay** [comment]
OK. Thank you very much! 🙏
