### ISSUE TITLE
LayerMask: MediapipeFacialSegment  module 'cv2' has no attribute 'cvtColor'

### ISSUE THREAD

**Issue by Thanh1988-star** [comfyanonymous/ComfyUI#5605]
### Expected Behavior

LayerMask: MediapipeFacialSegment

module 'cv2' has no attribute 'cvtColor'

### Actual Behavior

LayerMask: MediapipeFacialSegment

module 'cv2' has no attribute 'cvtColor'

### Steps to Reproduce

LayerMask: MediapipeFacialSegment

module 'cv2' has no attribute 'cvtColor'

### Debug Logs

```powershell
LayerMask: MediapipeFacialSegment

module 'cv2' has no attribute 'cvtColor'
```

### Other

LayerMask: MediapipeFacialSegment

module 'cv2' has no attribute 'cvtColor'

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI_LayerStyle
https://github.com/chflame163/ComfyUI_LayerStyle
