### ISSUE TITLE
Save flow 405

### ISSUE THREAD

**Issue by GitHub4LP** [comfyanonymous/ComfyUI#5607]
### Expected Behavior

Normal

### Actual Behavior

save flow 405

### Steps to Reproduce

api is./api/userdata/ workflows%2FUnsaved%20Workflow.json
but some proxy decodes %2f to /, 
resulting in (./api/userdata/workflows/Unsaved%20Workflow.json) no API acceptable

### Debug Logs

```powershell
server respones 405
```

### Other

/api/userdata/workflows api

**Comment by huchenlei** [comment]
Fixed in https://github.com/comfyanonymous/ComfyUI/pull/5620

**Comment by GitHub4LP** [comment]
no completed @huchenlei

**Comment by ltdrdata** [comment]
> no completed @huchenlei

If the same error persists, please create an issue on the front repo with a detailed log message, including version information.

https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by gg22mm** [comment]
还是不行 https://github.com/comfyanonymous/ComfyUI/issues/9664
