### ISSUE TITLE
FrontEnd frozen

### ISSUE THREAD

**Issue by HumbertoJrGH** [comfyanonymous/ComfyUI#5626]
### Expected Behavior

I used ComfyUI in my C drive for quite some time, but as the folder grew I switched my portable folder to my D drive. It did not work at all, so I decided to install clean, just backed up my models and output image in other folders. I start the comfyUI bat for Nvidia cards but it does not work.

### Actual Behavior

![image](https://github.com/user-attachments/assets/5846f26c-5209-4b14-a392-1297ba126920)
Even trying to zoom or panning the screen nothing happens, the screen is stuck. There are no errors in the console as well. I tried decompressing it to C drive again but the same problem happens. If I open up an image with nodes the screen pops the missing nodes alert but the screen is also buggy. And the button for the manager is not available as well.

### Steps to Reproduce

Just decompressing the .zip file into D and C drive after deleting my older ComfyUI folder. It seems that something may be stored elsewhere and may be corrupting the front-end.

### Debug Logs

```powershell
C:\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 8188 MB, total RAM 32604 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
****** User settings have been changed to be stored on the server instead of browser storage. ******
****** For multi-user setups add the --multi-user CLI argument to enable multiple user profiles. ******
[Prompt Server] web root: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\web
C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by sneccc** [comment]
i also get froozen when copying image from preview image or sometimes on clicking on image chooser it freezes the ui and cant move

**Comment by huchenlei** [comment]
Please file issue in https://github.com/Comfy-Org/ComfyUI_frontend. Also please confirm that the issue still exists after you disable all custom nodes with `--disable-all-custom-nodes` launch arg.
