### ISSUE TITLE
i have a problem with the node UltralyticsDetectorProvider 

### ISSUE THREAD

**Issue by ABIA2024** [comfyanonymous/ComfyUI#5628]
### Your question

How can i fo find a solution? with the message 
👍 UltralyticsDetectorProvider
PytorchStreamReader failed reading zip archive: failed finding central directory

### Logs

```powershell
2024-11-15T19:35:53.505413 - Traceback (most recent call last):
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 30, in doit
    model = subcore.load_yolo(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 30, in load_yolo
    return YOLO(model_path)
           ^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 143, in __init__
    self._load(model, task=task)
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 295, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\nn\tasks.py", line 857, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\nn\tasks.py", line 784, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 24, in torch_wrapper
    return orig_torch_load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1326, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 671, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

2024-11-15T19:35:53.507408 - Prompt executed in 278.24 seconds
2024-11-15T19:35:53.507408 - Prompt executed in 278.24 seconds
2024-11-15T19:35:53.507408 - Prompt executed in 278.24 seconds


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":31,"last_link_id":34,"nodes":[{"id":1,"type":"SamplerCustomAdvanced","pos":{"0":2940.7900390625,"1":812.9525756835938},"size":[355.20001220703125,326],"flags":{},"order":20,"mode":0,"inputs":[{"name":"noise","type":"NOISE","link":1},{"name":"guider","type":"GUIDER","link":2},{"name":"sampler","type":"SAMPLER","link":3},{"name":"sigmas","type":"SIGMAS","link":4},{"name":"latent_image","type":"LATENT","link":5}],"outputs":[{"name":"output","type":"LATENT","links":[10],"slot_index":0},{"name":"denoised_output","type":"LATENT","links":null}],"properties":{"Node name for S&R":"SamplerCustomAdvanced"},"widgets_values":[]},{"id":2,"type":"RandomNoise","pos":{"0":2606.56787109375,"1":641.188720703125},"size":{"0":315,"1":82},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"NOISE","type":"NOISE","links":[1]}],"properties":{"Node name for S&R":"RandomNoise"},"widgets_values":[582110970643966,"randomize"]},{"id":3,"type":"BasicGuider","pos":{"0":2636.56787109375,"1":775.188720703125},"size":{"0":241.79998779296875,"1":46},"flags":{},"order":17,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":6},{"name":"conditioning","type":"CONDITIONING","link":7}],"outputs":[{"name":"GUIDER","type":"GUIDER","links":[2]}],"properties":{"Node name for S&R":"BasicGuider"},"widgets_values":[]},{"id":4,"type":"KSamplerSelect","pos":{"0":2591.56787109375,"1":885.188720703125},"size":{"0":315,"1":58},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"SAMPLER","type":"SAMPLER","links":[3]}],"properties":{"Node name for S&R":"KSamplerSelect"},"widgets_values":["euler"]},{"id":10,"type":"VAEDecode","pos":{"0":3369.234619140625,"1":821.8414916992188},"size":{"0":210,"1":46},"flags":{},"order":22,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":10},{"name":"vae","type":"VAE","link":11}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[12,13],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":11,"type":"VAELoader","pos":{"0":3073.56787109375,"1":650.188720703125},"size":{"0":315,"1":58},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[11]}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["ae.safetensors"]},{"id":12,"type":"PreviewImage","pos":{"0":3626.56787109375,"1":862.188720703125},"size":{"0":321.7779541015625,"1":303.20831298828125},"flags":{},"order":24,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":12}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":13,"type":"Anything Everywhere","pos":{"0":3518.56787109375,"1":678.188720703125},"size":{"0":239.40000915527344,"1":26},"flags":{},"order":25,"mode":0,"inputs":[{"name":"IMAGE","type":"*","link":13,"shape":7,"color_on":"#64B5F6"}],"outputs":[],"properties":{"Node name for S&R":"Anything Everywhere","group_restricted":0,"color_restricted":0},"widgets_values":[]},{"id":14,"type":"ImpactSimpleDetectorSEGS","pos":{"0":4486.56787109375,"1":539.188720703125},"size":{"0":315,"1":310},"flags":{},"order":15,"mode":0,"inputs":[{"name":"bbox_detector","type":"BBOX_DETECTOR","link":14},{"name":"image","type":"IMAGE","link":null},{"name":"sam_model_opt","type":"SAM_MODEL","link":15,"shape":7},{"name":"segm_detector_opt","type":"SEGM_DETECTOR","link":null,"shape":7}],"outputs":[{"name":"SEGS","type":"SEGS","links":[18],"slot_index":0}],"properties":{"Node name for S&R":"ImpactSimpleDetectorSEGS"},"widgets_values":[0.5,0,3,10,0.5,0,0,0.7,0]},{"id":17,"type":"SAMLoader","pos":{"0":4084.56787109375,"1":837.188720703125},"size":{"0":315,"1":82},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"SAM_MODEL","type":"SAM_MODEL","links":[15,17],"slot_index":0}],"properties":{"Node name for S&R":"SAMLoader"},"widgets_values":["sam_vit_b_01ec64.pth","AUTO"]},{"id":18,"type":"UltralyticsDetectorProvider","pos":{"0":4092.56787109375,"1":1048.188720703125},"size":{"0":340.20001220703125,"1":78},"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"BBOX_DETECTOR","type":"BBOX_DETECTOR","links":[16]},{"name":"SEGM_DETECTOR","type":"SEGM_DETECTOR","links":null}],"properties":{"Node name for S&R":"UltralyticsDetectorProvider"},"widgets_values":["bbox/Eyeful_v1.pt"]},{"id":15,"type":"ImpactSimpleDetectorSEGS","pos":{"0":4497.56787109375,"1":947.188720703125},"size":{"0":315,"1":310},"flags":{},"order":12,"mode":0,"inputs":[{"name":"bbox_detector","type":"BBOX_DETECTOR","link":16},{"name":"image","type":"IMAGE","link":null},{"name":"sam_model_opt","type":"SAM_MODEL","link":17,"shape":7},{"name":"segm_detector_opt","type":"SEGM_DETECTOR","link":null,"shape":7}],"outputs":[{"name":"SEGS","type":"SEGS","links":[20],"slot_index":0}],"properties":{"Node name for S&R":"ImpactSimpleDetectorSEGS"},"widgets_values":[0.5,0,3,10,0.5,0,0,0.7,0]},{"id":20,"type":"BitwiseAndMaskForEach","pos":{"0":5377,"1":600},"size":{"0":277.20001220703125,"1":46},"flags":{},"order":21,"mode":0,"inputs":[{"name":"base_segs","type":"SEGS","link":19},{"name":"mask_segs","type":"SEGS","link":20}],"outputs":[{"name":"SEGS","type":"SEGS","links":[21],"slot_index":0}],"properties":{"Node name for S&R":"BitwiseAndMaskForEach"},"widgets_values":[]},{"id":23,"type":"CLIPTextEncode","pos":{"0":5331,"1":975},"size":{"0":400,"1":200},"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":null}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[23]}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":[""],"color":"#962123","bgcolor":"#B71C1C"},{"id":26,"type":"Anything Everywhere","pos":{"0":5862.6982421875,"1":426.61578369140625},"size":{"0":239.40000915527344,"1":26},"flags":{},"order":19,"mode":0,"inputs":[{"name":"CLIP","type":"*","link":28,"shape":7,"color_on":"#FFD500"}],"outputs":[],"properties":{"Node name for S&R":"Anything Everywhere","group_restricted":0,"color_restricted":0},"widgets_values":[]},{"id":30,"type":"Image Comparer (rgthree)","pos":{"0":7587.0830078125,"1":710.3258056640625},"size":{"0":535.5350952148438,"1":417.7565612792969},"flags":{},"order":29,"mode":0,"inputs":[{"name":"image_a","type":"IMAGE","link":34,"shape":7},{"name":"image_b","type":"IMAGE","link":null,"shape":7}],"outputs":[],"properties":{"Node name for S&R":"Image Comparer (rgthree)"},"widgets_values":[]},{"id":9,"type":"DualCLIPLoader","pos":{"0":1762.5677490234375,"1":719.188720703125},"size":{"0":315,"1":106},"flags":{},"order":6,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[9]}],"properties":{"Node name for S&R":"DualCLIPLoader"},"widgets_values":["clip_l.safetensors","t5xxl_fp8_e4m3fn.safetensors","flux"]},{"id":8,"type":"CLIPTextEncode","pos":{"0":2136.56787109375,"1":559.188720703125},"size":{"0":400,"1":200},"flags":{},"order":13,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":9}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[7]}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["a beautiful cyborg lady with dirty and damaged synthetic skin"]},{"id":7,"type":"UNETLoader","pos":{"0":2210.56787109375,"1":898.188720703125},"size":{"0":315,"1":82},"flags":{},"order":7,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[6,8],"slot_index":0}],"properties":{"Node name for S&R":"UNETLoader"},"widgets_values":["flux1-dev-fp8.safetensors","fp8_e4m3fn"]},{"id":5,"type":"BasicScheduler","pos":{"0":2589.56787109375,"1":1003.188720703125},"size":{"0":315,"1":106},"flags":{},"order":14,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":8}],"outputs":[{"name":"SIGMAS","type":"SIGMAS","links":[4]}],"properties":{"Node name for S&R":"BasicScheduler"},"widgets_values":["simple",20,1]},{"id":6,"type":"EmptyLatentImage","pos":{"0":2596.56787109375,"1":1166.188720703125},"size":{"0":315,"1":106},"flags":{},"order":8,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[5]}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[1024,1024,1]},{"id":16,"type":"UltralyticsDetectorProvider","pos":{"0":4097.56787109375,"1":600.188720703125},"size":{"0":340.20001220703125,"1":78},"flags":{},"order":9,"mode":0,"inputs":[],"outputs":[{"name":"BBOX_DETECTOR","type":"BBOX_DETECTOR","links":[14]},{"name":"SEGM_DETECTOR","type":"SEGM_DETECTOR","links":null}],"properties":{"Node name for S&R":"UltralyticsDetectorProvider"},"widgets_values":["bbox/face_yolov8m.pt"]},{"id":19,"type":"ImpactSEGSOrderedFilter","pos":{"0":4937.83349609375,"1":620.0232543945312},"size":{"0":315,"1":150},"flags":{},"order":18,"mode":0,"inputs":[{"name":"segs","type":"SEGS","link":18}],"outputs":[{"name":"filtered_SEGS","type":"SEGS","links":[19],"slot_index":0},{"name":"remained_SEGS","type":"SEGS","links":null}],"properties":{"Node name for S&R":"ImpactSEGSOrderedFilter"},"widgets_values":["x1",true,0,1]},{"id":24,"type":"LoraLoader","pos":{"0":5353,"1":404},"size":{"0":315,"1":126},"flags":{},"order":16,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":25},{"name":"clip","type":"CLIP","link":26}],"outputs":[{"name":"MODEL","type":"MODEL","links":[24]},{"name":"CLIP","type":"CLIP","links":[28],"slot_index":1}],"properties":{"Node name for S&R":"LoraLoader"},"widgets_values":["add-detail-xl.safetensors",0.8,1]},{"id":22,"type":"CLIPTextEncode","pos":{"0":5322,"1":724},"size":{"0":400,"1":200},"flags":{},"order":10,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":null}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[22]}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["Detailed Face, natural skin,\nskinpores"],"color":"#145013","bgcolor":"#1B5E20"},{"id":21,"type":"DetailerForEach","pos":{"0":5854.89013671875,"1":653.0631103515625},"size":{"0":400,"1":620},"flags":{},"order":23,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":null},{"name":"segs","type":"SEGS","link":21},{"name":"model","type":"MODEL","link":24},{"name":"clip","type":"CLIP","link":null},{"name":"vae","type":"VAE","link":27},{"name":"positive","type":"CONDITIONING","link":22},{"name":"negative","type":"CONDITIONING","link":23},{"name":"detailer_hook","type":"DETAILER_HOOK","link":null,"shape":7},{"name":"scheduler_func_opt","type":"SCHEDULER_FUNC","link":null,"shape":7}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[29],"slot_index":0}],"properties":{"Node name for S&R":"DetailerForEach"},"widgets_values":[512,true,1024,286383071592786,"randomize",20,6,"dpmpp_2m","simple",0.3,5,true,true,"",1,false,0]},{"id":27,"type":"ImageSharpen","pos":{"0":6384.56884765625,"1":644.60400390625},"size":{"0":315,"1":106},"flags":{},"order":26,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":29}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[30],"slot_index":0}],"properties":{"Node name for S&R":"ImageSharpen"},"widgets_values":[1,0.3,1]},{"id":31,"type":"ImageApplyLUT+","pos":{"0":7122,"1":668},"size":{"0":315,"1":130},"flags":{"collapsed":false},"order":28,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":33}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[34],"slot_index":0}],"properties":{"Node name for S&R":"ImageApplyLUT+"},"widgets_values":["PB_Boulder.CUBE",false,false,0.30000000000000004]},{"id":25,"type":"CheckpointLoaderSimple","pos":{"0":4951,"1":373},"size":{"0":315,"1":98},"flags":{},"order":11,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[25]},{"name":"CLIP","type":"CLIP","links":[26],"slot_index":1},{"name":"VAE","type":"VAE","links":[27],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["epiCrealism.safetensors"]},{"id":28,"type":"CR Upscale Image","pos":{"0":6740,"1":671},"size":{"0":315,"1":222},"flags":{},"order":27,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":30}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[33],"slot_index":0},{"name":"show_help","type":"STRING","links":null}],"properties":{"Node name for S&R":"CR Upscale Image"},"widgets_values":["x1_ITF_SkinDiffDetail_Lite_v1.pth","rescale",2,1024,"lanczos","true",8]}],"links":[[1,2,0,1,0,"NOISE"],[2,3,0,1,1,"GUIDER"],[3,4,0,1,2,"SAMPLER"],[4,5,0,1,3,"SIGMAS"],[5,6,0,1,4,"LATENT"],[6,7,0,3,0,"MODEL"],[7,8,0,3,1,"CONDITIONING"],[8,7,0,5,0,"MODEL"],[9,9,0,8,0,"CLIP"],[10,1,0,10,0,"LATENT"],[11,11,0,10,1,"VAE"],[12,10,0,12,0,"IMAGE"],[13,10,0,13,0,"IMAGE"],[14,16,0,14,0,"BBOX_DETECTOR"],[15,17,0,14,2,"SAM_MODEL"],[16,18,0,15,0,"BBOX_DETECTOR"],[17,17,0,15,2,"SAM_MODEL"],[18,14,0,19,0,"SEGS"],[19,19,0,20,0,"SEGS"],[20,15,0,20,1,"SEGS"],[21,20,0,21,1,"SEGS"],[22,22,0,21,5,"CONDITIONING"],[23,23,0,21,6,"CONDITIONING"],[24,24,0,21,2,"MODEL"],[25,25,0,24,0,"MODEL"],[26,25,1,24,1,"CLIP"],[27,25,2,21,4,"VAE"],[28,24,1,26,0,"CLIP"],[29,21,0,27,0,"IMAGE"],[30,27,0,28,0,"IMAGE"],[33,28,0,31,0,"IMAGE"],[34,31,0,30,0,"IMAGE"]],"groups":[{"title":"Group","bounding":[1753,486,2206,797],"color":"#3f789e","font_size":24,"flags":{}},{"title":"detailer","bounding":[4074,300,4058,984],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.6830134553650705,"offset":[-2722.7357007724186,-244.30628611693604]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

**Comment by ltdrdata** [comment]
This issue should be moved to Impact Pack repo.
https://github.com/ltdrdata/ComfyUI-Impact-Pack.

And your log message suggests that the model file you downloaded might be corrupted. Please check the file size of the model.

**Comment by ABIA2024** [comment]
Please excuse me in advance if I'm taking a long time with this exchange, it's going to be exceptional and, please understand, it's because I really want to have a clean, reliable installation and understand as many of the technical nuts and bolts as possible, with as much autonomy as possible, and therefore with the minimum of disturbance to you.First of all, thank you for the point about the LOG log; I have no idea how to use this LOG and as I'm also having problems with corrupted files (I've just gone through all the Windows 10 explorer and registry repair tools - it's done), I wanted to ask you aQUESTION 1What is your technique for reading in the LOG that a model is corrupted? In your comment, which one? And is it in relation to an abnormal weight?QUESTION 2Thank you for informing me that I was not always depositing my “ISSUES” in the right place.Is it possible to forward the misplaced ISSUES? How can I do this?QUESTION 3To cope with the problems encountered with the various OMNIGEN nodes and other COMFY Compact, RGTHREE, etc., I installed a 2nd COMFYUI directory dedicated to OMNIGEN.Do you think this is a good idea, or is it pointless?Or, apart from RESTAR from ComfyUI MANAGER and UPDATE ALL, how can I get a clean platform?

Sincerely yoursAlexandre B.

    Le samedi 16 novembre 2024 à 08:41:07 UTC+1, Dr.Lt.Data ***@***.***> a écrit :  
 
 


This issue should be moved to Impact Pack repo.
https://github.com/ltdrdata/ComfyUI-Impact-Pack.

And your log message suggests that the model file you downloaded might be corrupted. Please check the file size of the model.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Sans virus.www.avast.com |

**Comment by ltdrdata** [comment]
@ABIA2024 


A1. This is the part where the model file is loaded, and such issues typically occur not only with the Impact Pack but also when the model file is corrupted in general.
```
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 671, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

A2. I don't have the permission to transfer issues to another repository.

A3. 
Installing certain custom nodes can cause many dependency issues, and if those custom nodes are not always necessary, setting up a separate environment can also be a good approach.
