### ISSUE TITLE
Refresh node button missing after 4ac401a

### ISSUE THREAD

**Issue by Orenji-Tangerine** [comfyanonymous/ComfyUI#5634]
### Your question

Version 4ac401a
![image](https://github.com/user-attachments/assets/47e28606-94d8-4601-91ea-8ec91fc508d9)

Prior to this
![image](https://github.com/user-attachments/assets/3b385991-43d9-433a-a6bd-17a19c1aa0bf)

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/25f0b0e5-c15c-45a4-859f-4dd4e526a790)

It is moved to here.
