### ISSUE TITLE
Support For TPU/XLA Devices

### ISSUE THREAD

**Issue by radna0** [comfyanonymous/ComfyUI#5635]
### Feature Idea

Support For TPU/XLA Devices

**Comment by gabriel-montrose** [comment]
It's good Idea. Now we have to do manual work to install Intel OneAPI, for windows VIsual Studio, set correct version pytorch... Exhausted. I am not sure that now it use shared GPU, where I have Intel UHD and Nvidia

**Comment by radna0** [comment]
I'm experimenting to see if I can add support for TPU/XLA devices within the comfy code myself. If possible, I can try to open a PR to add support for it.

As for shared TPUs, the most common way I see is with SPMD or FSDPv2. I believe you can also do that with XMP? but I haven't had much luck with it using TPUv2-8 or TPUv3-8.

Torch XLA: https://github.com/pytorch/xla
SPMD: https://pytorch.org/xla/master/spmd.html
FSDPv2:https://github.com/pytorch/xla/issues/6379

**Comment by radna0** [comment]
hi @gabriel-montrose, I have just created a PR. https://github.com/comfyanonymous/ComfyUI/pull/5650

**Comment by radna0** [comment]
If anyone needs TPU/XLA devices support for ComfyUI please refer to my own fork [ComfyUI-TPU](https://github.com/radna0/ComfyUI-TPU). I shall maintain it as long as there's interest.

**Comment by krisheetu** [comment]
Hey @radna0 hope you are doing great! is it possible to update the TPU branch?

**Comment by radna0** [comment]
Hey @krisheetu , yes! I would be happy to!

**Comment by krisheetu** [comment]
> Hey [@krisheetu](https://github.com/krisheetu) , yes! I would be happy to!

Wow it would be great! Waiting for the update.
