### ISSUE TITLE
Queue prompt button

### ISSUE THREAD

**Issue by yamatazen** [comfyanonymous/ComfyUI#5638]
### Your question

Where is the queue prompt button in the updated ComfyUI?

**Comment by LukeG89** [comment]
It has become a floating menu that you can dock to the topbar. It's hard to tell where it is unless you show your screen. But it is probably at the bottom, under Image Feed (I guess).

**Comment by LukeG89** [comment]
If you still can't find it, you can delete all data of 127.0.0.1 site in your browser. This way, the menu position will be reset at the bottom of the screen.

**Comment by yamatazen** [comment]
This is the new ComfyUI. I can't find the queue prompt button.

![firefox_jRU4zWLmhO](https://github.com/user-attachments/assets/e2231f7d-62df-4633-9b05-0ab9999d8f86)

**Comment by LukeG89** [comment]
Yeah, as I suggested, you need to delete all data of 127.0.0.1 site

**Comment by yamatazen** [comment]
I cleared the cookies and the button is there now.

![3pwLRfI2oa](https://github.com/user-attachments/assets/24566d65-7da5-44f5-8f55-60697b305219)
