### ISSUE TITLE
(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lllyasviel/Annotators/resolve/main/body_pose_model.pth (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))"), '(Request ID: 77f7326b-a6a7-48e7-b04f-948195fe5c7f)')

### ISSUE THREAD

**Issue by MrLi1225** [comfyanonymous/ComfyUI#5639]
### Your question

(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lllyasviel/Annotators/resolve/main/body_pose_model.pth (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))"), '(Request ID: 77f7326b-a6a7-48e7-b04f-948195fe5c7f)')
![Uploading 屏幕截图 2024-11-16 222436.png…]()

**Comment by ltdrdata** [comment]
See this:
https://github.com/comfyanonymous/ComfyUI/issues/1549
