### ISSUE TITLE
New ComfyUI breaks when loading previous workflows

### ISSUE THREAD

**Issue by jeffufu** [comfyanonymous/ComfyUI#5643]
### Expected Behavior

I expected to use ComfyUI as I always do.

### Actual Behavior

When I start up Comfy (via Paperspace), the default workflow loads up fine but if I try to load a different one, it suddenly becomes non-responsive.

The rest of the UI such as Settings and Manager work fine. 

### Steps to Reproduce

Open ComfyUI.

Try to use a different workflow. 

### Debug Logs

```powershell
None to provide/not sure what to share.
```

### Other

It seems like a purely GUI issue; the process of opening saved workflows in the menu functions as normal, but I just can't see what's going on in the canvas area. Something broke with the latest update and I don't know how to rollback.

**Comment by yoland68** [comment]
Can you try disable all the custom nodes and run it again?

**Comment by jeffufu** [comment]
> Can you try disable all the custom nodes and run it again?

Thank you! I did that (it was a very slow process) and confirmed it was https://github.com/chrisgoringe/cg-use-everywhere that was the issue. I've submitted a ticket to their git page.

**Comment by yoland68** [comment]
There is a tool we have in comfy-cli for https://github.com/Comfy-Org/comfy-cli?tab=readme-ov-file#bisect-custom-nodes
You can probably try it next time if it works

**Comment by DarkAlchy** [comment]
I can confirm that even in 2025 Anything everywhere locks up the workflow if an older workflow as it just happened to me.
