### ISSUE TITLE
Workflows Directory

### ISSUE THREAD

**Issue by brucew4yn3rp** [comfyanonymous/ComfyUI#5652]
### Your question

After updating ComfyUI to the latest version, it now seems that workflows are saved to the user/default/workflows folder. How can this be changed to a custom path? 

Additionally, after updating to the new version, I can't seem to find my generation history in the UI.

**Comment by LukeG89** [comment]
> How can this be changed to a custom path?

Currently you can't change it, I think for a security reason. There is already a feature request in the frontend repo about it:
- https://github.com/Comfy-Org/ComfyUI_frontend/issues/688

> I can't seem to find my generation history in the UI.

History has been replaced by Queue in sidebar.

![image](https://github.com/user-attachments/assets/e46ec0d0-6b09-4043-8d94-68e713ccd09a)

**Comment by brucew4yn3rp** [comment]
I'd assume that the code reference to the user/default/workflows directory can be changed in the js or py code that the workflows menu looks at?

Also, the issue with loading historical gens is that it will not allow a loading of something that was "cancelled", which was very useful in the past. I use the preview chooser node and sometimes I cancel a run 75% of the way through but I still want to load the same workflow inputs.

![image](https://github.com/user-attachments/assets/1ed378ca-b52c-40fd-b8f4-ad8c22617163)

**Comment by LukeG89** [comment]
> I'd assume that the code reference to the user/default/workflows directory can be changed in the js or py code that the workflows menu looks at?

I don't know, I'm just a normal user, you need to ask @huchenlei 

> Also, the issue with loading historical gens is that it will not allow a loading of something that was "cancelled", which was very useful in the past. I use the preview chooser node and sometimes I cancel a run 75% of the way through but I still want to load the same workflow inputs.

You mean like this option when you right-click?

![option](https://github.com/user-attachments/assets/306d6ff8-dec9-403e-8c12-ea8d0a65a87e)

**Comment by brucew4yn3rp** [comment]
Lol, that was easy. I wish instead of showing a blank slate for cancelled workflows, it showed the last generated pic in that workflow. 

For example, I have Ksampler -> preview -> Ksampler -> preview -> facedetailer -> preview. If I cancel before the facedetailer, I'd want to see that image instead of a blank box in the queue. It would be the most recent image in temp.

**Comment by LukeG89** [comment]
> I wish instead of showing a blank slate for cancelled workflows, it showed the last generated pic in that workflow.
>
> For example, I have Ksampler -> preview -> Ksampler -> preview -> facedetailer -> preview. If I cancel before the facedetailer, I'd want to see that image instead of a blank box in the queue. It would be the most recent image in temp.

You can open a feature request in the frontend repo: [ComfyUI_frontend](https://github.com/Comfy-Org/ComfyUI_frontend)

**Comment by brucew4yn3rp** [comment]
Just for avoidance of doubt - this issue is still open with the below question

>I'd assume that the code reference to the user/default/workflows directory can be changed in the js or py code that the workflows menu looks at?

**Comment by Moorer624** [comment]
I would hope it can be set easily - a cmd switch would be great. It just seems like such a "basic" user config need.

**Comment by ltdrdata** [comment]
Use `--user-directory` cli option.

**Comment by Moorer624** [comment]
Thanks. One follow up question - I'm assuming the argument I should enter is --user-directory C:\..., If I expect to route the directory somewhere on my C drive. How do I deal with spaces? My file path is c:\users\moore\My Programs\Stability Matrix\ComfyUI Workflows\Baseline. I just keep getting errors whether I use "" on the string, or around the space. Any thoughts?

**Comment by Moorer624** [comment]
How about creating a cli option just for a user-defined location to store workflows?

**Comment by brbbbq** [comment]
> Use `--user-directory` cli option.

Will this cause any issues if you have multiple versions of ComfyUI pointing to the same user folder? In my installations I'm seeing the cache folder populated, along with channels.list and config.ini

I just want to have a centralized place to create a workflow library that's shared between different installations while trying to avoid symbolic linking, because it's caused issues with updating in the past.

**Comment by ltdrdata** [comment]
> > Use `--user-directory` cli option.
> 
> Will this cause any issues if you have multiple versions of ComfyUI pointing to the same user folder? In my installations I'm seeing the cache folder populated, along with channels.list and config.ini
> 
> I'm just looking for a centralized workflow library that's shared between different installations while trying to avoid symbolic links, because it's caused issues with updating in the past.

There shouldn’t be any major issues aside from various settings being shared across the different ComfyUI installations.
