### ISSUE TITLE
Displaying images from cancelled workflow in the history

### ISSUE THREAD

**Issue by brucew4yn3rp** [comfyanonymous/ComfyUI#5656]
### Feature Idea

I wish instead of showing a blank slate for cancelled workflows, it showed the last generated pic in that workflow.

For example, I have Ksampler -> preview -> Ksampler -> preview -> facedetailer -> preview. If I cancel before the facedetailer, I'd want to see that image instead of a blank box in the queue. It would be the most recent image in temp.

Currently, it only shows a blank slate.

![image](https://github.com/user-attachments/assets/fe6c7811-99b5-4ecd-bb25-1d9135bbdb11)

**Comment by LukeG89** [comment]
As I said in the other issue, you need to open this feature request in the frontend repo: [ComfyUI_frontend](https://github.com/Comfy-Org/ComfyUI_frontend)
