### ISSUE TITLE
UI Layout Not Saving

### ISSUE THREAD

**Issue by tdtrumble** [comfyanonymous/ComfyUI#5658]
### Your question

Every time I launch comfy the UI layout resets. I close the output stream thing at the bottom and drag the queue button into the top menu, then next time I launch I do it again. I'm using the portable windows version. Am I missing something? A setting to save the layout?

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/8f304f6e-5af5-42e0-b214-fa98799292c6)

You can save workflow.

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
