### ISSUE TITLE
I am really looking forward to the desktop version. Come on!

### ISSUE THREAD

**Issue by sjsdwwy** [comfyanonymous/ComfyUI#5659]

**Comment by ltdrdata** [comment]
Yeah!
https://www.comfy.org/waitlist

**Comment by sjsdwwy** [comment]
> 是的！ https://www.comfy.org/waitlist

Will there be a Linux version? Ha ha

**Comment by ltdrdata** [comment]
> > 是的！ https://www.comfy.org/waitlist
> 
> Will there be a Linux version? Ha ha

There is a plan, but for now, only versions for Windows (nvidia gpu) and macOS are available.
