### ISSUE TITLE
Group Snap to Grid Malfunction

### ISSUE THREAD

**Issue by shmilyfuu** [comfyanonymous/ComfyUI#5663]
Since updating to the new version, the group snap to grid is no longer functioning properly. Would you mind taking a moment to check what might be causing this? Your help would be greatly appreciated.

commit 9a0a5d32ee49e79beae551fe2a165ac1108378e9 (HEAD -> master, origin/master, origin/HEAD)
Date:   Mon Nov 18 02:20:43 2024 -0500

https://github.com/user-attachments/assets/da7597e9-4803-40d2-9a79-019f6265a9cb

**Comment by LukeG89** [comment]
It's a known issue:

- https://github.com/Comfy-Org/ComfyUI_frontend/issues/1428

They are about to fix it in the next frontend release:

- https://github.com/Comfy-Org/ComfyUI_frontend/pull/1572

**Comment by Lenny5245** [comment]
会尽快更新吗？
