### ISSUE TITLE
How to trigger Queue Prompt from within a node?

### ISSUE THREAD

**Issue by GraftingRayman** [comfyanonymous/ComfyUI#5667]
### Your question

Is it possible to trigger the Queue prompt to run from within a node?

I have a script that parses a large file, when it encounters certain data, I need it to trigger the queue prompt, is this possible?

**Comment by LukeG89** [comment]
I've never use it, but you could try `Queue Trigger` node from [ComfyUI-Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack)

![image](https://github.com/user-attachments/assets/ec2bdd97-5708-46fd-ad30-9be3584a004d)

**Comment by GraftingRayman** [comment]
Thank you, looks like that would work

   def doit(self, signal, mode):
        if(mode):
            PromptServer.instance.send_sync("impact-add-queue", {})

        return (signal,)
