### ISSUE TITLE
KSampler infer time

### ISSUE THREAD

**Issue by zeng121** [comfyanonymous/ComfyUI#5670]
### Your question

As the number of inference increases, the sampling time increases

### Other

[ai_bg_relighting_v2.json](https://github.com/user-attachments/files/17808168/ai_bg_relighting_v2.json)

**Comment by zeng121** [comment]
![ks](https://github.com/user-attachments/assets/5cb09d13-d042-4e77-8ec6-875e1ff2b8bf)

**Comment by ltdrdata** [comment]
Does the same issue occur in the default workflow as well?
What is your environment? (OS, Torch version, etc.)

**Comment by zeng121** [comment]
Linux、torch2.3.0、
[ai_bg_relighting_v2.json](https://github.com/user-attachments/files/17810391/ai_bg_relighting_v2.json)

**Comment by zeng121** [comment]
This does not happen in default workflows

**Comment by edumes** [comment]
same problem here
