### ISSUE TITLE
websocket 只能接受到 crystools.monitor 类型的数据

### ISSUE THREAD

**Issue by hashmap521** [comfyanonymous/ComfyUI#5674]
### Expected Behavior

crystools.monitor

### Actual Behavior

crystools.monitor

### Steps to Reproduce

crystools.monitor

### Debug Logs

```powershell
(WebSocketConnectReadThread-28) 接收到websocket连接参数：{"type": "crystools.monitor", "data": {"cpu_utilization": 15.5, "ram_total": 676312485888, "ram_used": 71159975936, "ram_used_percent": 14.1, "hdd_total": -1, "hdd_used": -1, "hdd_used_percent": -1, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 30, "vram_total": 42949672960, "vram_used": 6170476544, "vram_used_percent": 14.36676025390625}]}}
```

**Comment by LukeG89** [comment]
That console warning is caused by Resources Monitor from [ComfyUI-Crystools](https://github.com/crystian/ComfyUI-Crystools)

You need to open an issue in the custom node repo.

![image](https://github.com/user-attachments/assets/2fc75564-7772-4e41-8eb6-616b04618f17)
