### ISSUE TITLE
Pleas help! After hard reseting Git: git reset --hard , my menu in comfyui reduceod only to button Queue. How can I make it full again? Thanks

### ISSUE THREAD

**Issue by RustyG0ld** [comfyanonymous/ComfyUI#5686]
### Your question

<img width="406" alt="Screen Shot 11-20-24 at 04 09 PM" src="https://github.com/user-attachments/assets/9ee4c0da-f5c2-4ed1-9279-7bfabe05331b">

**Comment by LukeG89** [comment]
That's the floating Queue menu, you can dock it on the topbar if you want:


https://github.com/user-attachments/assets/be867cf0-2165-4101-a204-2953b1f17c71

**Comment by ltdrdata** [comment]
See `🎨 New UI Now Default` part.
https://blog.comfy.org/comfyui-v0-3-0-release/

You can turn off new UI.

**Comment by RustyG0ld** [comment]
Thank you very much. The UI changed right after the hard git reset, I didn't realize it was a new interface :-D
