### ISSUE TITLE
Using Scroll Wheel to Zoom in Firefox Causes Visual/Usability Issues

### ISSUE THREAD

**Issue by prezofpizza** [comfyanonymous/ComfyUI#5698]
### Expected Behavior

I should be able to zoom in and still use ComfyUI as expected

### Actual Behavior

The grid disappears, I cannot  zoom in or out with the mouse wheel, I cannot move around in the workspace.

Before scroll:
![image](https://github.com/user-attachments/assets/7d1ba8e8-c371-4213-b56b-608a955d5fe7)

After Scroll:
![image](https://github.com/user-attachments/assets/27e0cdba-fb7c-440f-924e-e5fb1d1ae78d)

### Steps to Reproduce

Use the mouse scroll wheel in Firefox

### Debug Logs

```powershell
No logs produced
```

### Other

Seems to only happen in Firefox.

**Comment by LukeG89** [comment]
Do you have any error in the browser console?
Have you tried disabling your custom nodes with the `--disable-all-custom-nodes` argument?

**Comment by prezofpizza** [comment]
Great call! Nothing in console but the argument does make the issue go away.

Going to try to narrow it down from there.

Thanks!

**Comment by prezofpizza** [comment]
@LukeG89 process of elimination, seems to be caused by https://github.com/ai-shizuka/ComfyUI-tbox.
