### ISSUE TITLE
Keybinding for "Fit Group To Nodes"

### ISSUE THREAD

**Issue by PrometheusDante** [comfyanonymous/ComfyUI#5701]
### Feature Idea

Having a keybinding for the "Fit Group To Nodes" function would be a helpful addition for me, as I use it all the time.

### Existing Solutions

Manually going through the process of right-clicking and selecting "Fit Group To Nodes" from the dropdown menu, which is getting tedious when working with lots of groups and the nodes snap to the grid differently than the groups.

**Comment by LukeG89** [comment]
You have to open this feature request in the frontend repo: [ComfyUI_frontend](https://github.com/Comfy-Org/ComfyUI_frontend)

**Comment by PrometheusDante** [comment]
Got it, thank you
