### ISSUE TITLE
 i met an issue when using the the latest flux fill model in comfyu

### ISSUE THREAD

**Issue by huangkun1985** [comfyanonymous/ComfyUI#5710]
### Expected Behavior

run the default work flow of fill model

### Actual Behavior

unfortunately i met an issue when using the the latest flux fill model in comfyui, it says:

```
UNETLoader
Error(s) in loading state_dict for Flux:
size mismatch for img_in.weight: copying a param with shape torch.Size([3072, 384]) from checkpoint, the shape in current model is torch.Size([3072, 64]).
```

what does it means? how can i fix it?

check the log as below:

### Steps to Reproduce

![微信截图_20241122130959](https://github.com/user-attachments/assets/dc1b5ec7-18c0-4cf2-9fef-367a0b92586a)

### Debug Logs

```powershell
got prompt
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 9319.23095703125 True
clip missing: ['text_projection.weight']
model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
!!! Exception during processing !!! Error(s) in loading state_dict for Flux:
        size mismatch for img_in.weight: copying a param with shape torch.Size([3072, 384]) from checkpoint, the shape in current model is torch.Size([3072, 64]).
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 875, in load_unet
    model = comfy.sd.load_diffusion_model(unet_path, model_options=model_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 660, in load_diffusion_model
    model = load_diffusion_model_state_dict(sd, model_options=model_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 651, in load_diffusion_model_state_dict
    model.load_model_weights(new_sd, "")
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 222, in load_model_weights
    m, u = self.diffusion_model.load_state_dict(to_load, strict=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for Flux:
        size mismatch for img_in.weight: copying a param with shape torch.Size([3072, 384]) from checkpoint, the shape in current model is torch.Size([3072, 64]).

Prompt executed in 55.84 seconds
```

**Comment by FruitPigFoot** [comment]
yeah me too. i got the same exact error

**Comment by ltdrdata** [comment]
Is your ComfyUI the latest version (v0.3.1)?

**Comment by FruitPigFoot** [comment]
i forgot about that. So updating right now.

**Comment by FruitPigFoot** [comment]
i've just updated and still got the same error

**Comment by ltdrdata** [comment]
> i've just updated and still got the same error

Your ComfyUI has not been properly updated. Go to the ComfyUI directory in the command line and run `git pull`. It is likely failing.

**Comment by TonTonTWMAN** [comment]
Hi, I encountered the same issue specifically when using the FLUX.1 Fill model. 
The problem was resolved after updating the repository with git pull. It seems the latest updates addressed this issue.

If you're also using FLUX.1 Fill, you can try the following steps:

`git pull`

Once updated, restart ComfyUI and see if the problem is resolved. It worked for me, and I hope it helps others facing the same issue!

**Comment by tre4b** [comment]
git pull just gets me a message saying I need to specify a branch.  I don't know why.

C:\Users\trevor\Programs\ComfyUI\ComfyUI>git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

I also cannot figure out how I might be able to check the version of Comfy the closest I have is this.

![image](https://github.com/user-attachments/assets/9119c728-3920-4166-92c2-b96401a42f4b)

if this is the right way then it suggests I am on 0.2.3?

**Comment by ltdrdata** [comment]
```
git checkout master
git pull
```

**Comment by tedtninety** [comment]
Thanks everyone, that fixed it for me as well!

**Comment by tedtninety** [comment]
Thanks everyone, that fixed it for me as well!

**Comment by blue2024888** [comment]
> > > 我刚刚更新，但仍然出现相同的错误
> > 
> > 
> > 您的 ComfyUI 尚未正确更新。在命令行中进入 ComfyUI 目录并运行`git pull`.很可能会失败。
> > ![图像](https://private-user-images.githubusercontent.com/128333288/388814790-17f6e8e5-c07b-44b7-b5ac-5cd6d4fbaa24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNTgzMzEsIm5iZiI6MTczMjI1ODAzMSwicGF0aCI6Ii8xMjgzMzMyODgvMzg4ODE0NzkwLTE3ZjZlOGU1LWMwN2ItNDRiNy1iNWFjLTVjZDZkNGZiYWEyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwNjQ3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTRhOWYyNDQ2NGE3Nzc0OTIzNWY4ZDJhNTFmNGExYTJmZTVkNWMwZWI1MmRiY2Y1NzEzZDBiZjBkODVlMDJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i9Z5OMqQDJ5U5TJ4jv1S3m7QPs7YOf1wXzrwmkYPVDo)
> 
> 谢谢，我解决了问题，只需使用“git pull origin master”来更新 comfyui

按照此方法更新后，谷歌浏览器不能双击出搜索框了，这个有解决方案吗？

**Comment by dyanxi** [comment]
I am using the following version, and this error still exists.
commit 82ecb02c1ed29455047dcaa3839497b2cfa92852 (HEAD -> master, origin/master, origin/HEAD)
Author: catboxanon <122327233+catboxanon@users.noreply.github.com>
Date:   Sun Dec 29 20:06:49 2024 -0500

    Remove duplicate calls to INPUT_TYPES (#6249)
    
![image](https://github.com/user-attachments/assets/b165d895-b50b-426e-8e7c-e95eef7b3e23)

**Comment by appsmalthouse** [comment]
I just got a similar error running a flux - nf4 model (flux1-dev-bnb-nf4-v2.safetensors) :

size mismatch for img_in.weight: copying a param with shape torch.Size([98304, 1]) from checkpoint, the shape in current model is torch.Size([3072, 0])...   sizes were very different tho but 3072 lead me here.. thanx I guess :)

this is because it requires [BitsAndBytes NF4 Loaders](https://github.com/silveroxides/ComfyUI_bitsandbytes_NF4) to run

leaving this in case anyone else is in similar circumstances
