### ISSUE TITLE
comfyui server start successful, but cannot open gui page

### ISSUE THREAD

**Issue by EstherLee1995** [comfyanonymous/ComfyUI#5711]
### Your question

![image](https://github.com/user-attachments/assets/854a45c1-fc70-46d6-b74e-24d72e6b89d3)
![43E401A1-E11C-4611-894E-2F3AE51FEE0E](https://github.com/user-attachments/assets/6f5d2b21-061b-4b4d-b87a-f814d7180045)

**Comment by gxbsyxh** [comment]
Yes, I also have the same issue, in order to install and use the new flux version model, after upgrading comfyui to the latest version, the interface is stuck and the workflow cannot be opened

**Comment by gxbsyxh** [comment]
> Yes, I also have the same issue, in order to install and use the new flux version model, after upgrading comfyui to the latest version, the interface is stuck and the workflow cannot be opened

I just did 'Update All' from the ComfyUI Manager Menu and my broken workflows are loading correctly again
https://www.reddit.com/r/comfyui/comments/1gscasy/comfyui_v1_is_default_now/
I found it from here
