### ISSUE TITLE
PatchModelAddDownscale (Kohya Deep Shrink)

### ISSUE THREAD

**Issue by IAFFeng** [comfyanonymous/ComfyUI#5716]
### Feature Idea

Patch Model Add Downscale (Kohya Deep Shrink)
It seems not suitable for flux and cannot work with flux. Is there a chance to develop Deep Shrink for flux?

**Comment by ltdrdata** [comment]
DeepShrink is designed based on the characteristics of the UNet architecture. Since FLUX uses DiT, this technique cannot be applied.

**Comment by IAFFeng** [comment]
> DeepShrink is designed based on the characteristics of the UNet architecture. Since FLUX uses DiT, this technique cannot be applied.

ok
