### ISSUE TITLE
Open MaskEditor But can not draw anything

### ISSUE THREAD

**Issue by Hazukiaoi** [comfyanonymous/ComfyUI#5719]
### Expected Behavior

right click Load Image Node and Open MaskEditor should be open a draw window and I can draw anything.

### Actual Behavior

when i right click Load Image Node and Open MaskEditor, the editor look like it:
![image](https://github.com/user-attachments/assets/34e2fb72-1d2e-4d3e-98bd-41015d3f5540)

<img width="721" alt="msedge_Txf6xx6GIa" src="https://github.com/user-attachments/assets/5b0acee9-7881-4dbf-9ab6-f52a20b0a1b3">

there have nothing and can't draw anything.
and console not output anything.
![image](https://github.com/user-attachments/assets/f40c1d82-f3c0-42dd-b4ad-9bff9ccc9a5f)

### Steps to Reproduce

1. add a Load Image Node, and select an image.
2. right click the node and Select [Open In MaskEditor]
I use the Flux Example workflow and disable all custoom node: 
https://comfyanonymous.github.io/ComfyUI_examples/flux/

And here is my python environment version:
[pipVersion.txt](https://github.com/user-attachments/files/17867613/pipVersion.txt)

### Debug Logs

```powershell
nothing output in terminal.
```

**Comment by ltdrdata** [comment]
Attach the browser's console log (press F12 if Chrome) and create an issue in the front-end repository.
https://github.com/Comfy-Org/ComfyUI_frontend
