### ISSUE TITLE
Add a reverse mask in MaskEditor

### ISSUE THREAD

**Issue by yizhangliu** [comfyanonymous/ComfyUI#5720]
### Feature Idea

I hope to add a reverse mask in MaskEditor

**Comment by LukeG89** [comment]
Open a feature request in the frontend repo: [ComfyUI_frontend](https://github.com/Comfy-Org/ComfyUI_frontend)

FYI they recently implemented this new Mask Editor, it will be added in the next release:
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/1284
