### ISSUE TITLE
KSamplerSDXLAdvanced

### ISSUE THREAD

**Issue by Farhad-F10** [comfyanonymous/ComfyUI#5726]
### Your question

Hi All,
I created a project using ComfyUI and (KSampler Advanced) that I really need now, but it's not working. Can anyone help me find a solution?

I've already updated ComfyUI and installed both the Manager and Missing Node, but neither fixed the issue.

Thanks for your help!

Error Message:

**Comment by ltdrdata** [comment]
What is your workflow?

**Comment by Farhad-F10** [comment]
> What is your workflow?

Thanks for your quick answer, appreciate it  <3
How could I send you Private file please?

May I have your email to send file privately, please?
or Can I send here privately?

If so, could you tell me how?

Many Thanks

**Comment by brayevalerien** [comment]
The whole point of open source is that it's public and easily accessible. The best option would be to make a [MWE](https://stackoverflow.com/help/minimal-reproducible-example) (the smallest workflow that you can make that reproduces your issue) and share it here so anyone can access it and work on helping you or fixing the potential bug.

**Comment by Farhad-F10** [comment]
Dear friend,

Thank you for your comment
I understand the value of open-source projects and community collaboration. However, due to specific confidentiality agreements with the organization involved, I'm unable to share this project publicly! Sorry :(

Regarding to my question, please look at this image
![Ksampler-Advanced](https://github.com/user-attachments/assets/37118ef6-6d05-4fb4-8eb8-0d0ee6861661)


can I have same setting as this with different name in Custom-Manager was?

Many Thanks

**Comment by ltdrdata** [comment]
> Dear friend,
> 
> Thank you for your comment I understand the value of open-source projects and community collaboration. However, due to specific confidentiality agreements with the organization involved, I'm unable to share this project publicly! Sorry :(
> 
> Regarding to my question, please look at this image

The original request for the workflow is generally intended to verify if an incorrect model has been loaded. However, since this appears to be confidential, reviewing the workflow alone might not be sufficient for diagnosis.

Simply verify the model and try testing with the KSampler node instead of the KSamplerAdvanced node for now.
Especially since the node in the screenshot appears to be a private custom node, it is difficult to provide accurate guidance.
