### ISSUE TITLE
The [Comfy.LoadDefaultWorkflow] Keybinding should not exist.

### ISSUE THREAD

**Issue by misov1** [comfyanonymous/ComfyUI#5728]
### Feature Idea

By default, pressing Ctrl+D loads the default workflow, but it's a very deadly and unnecessary feature that if you don't know about the existence of that keybinding and accidentally type it, it will completely wipe out the workflow you're using or creating without any warning or message.
That's right, I just lost a workflow I was optimizing for an hour because of that keybinding.
Once you overwrite a workflow with that keybinding, it's impossible to go back to the old workflow unless you have an intermediate save or backup, and even then it was impossible to go back with the Ctrl+Z keybinding.
I might have been able to recover if I had the new menu feature, which was marked as BETA, turned on, but it was off by default, and unfortunately I didn't have it enabled.
While that keybinding to invoke the default workflow may be necessary for other users, I think it's an unnecessary and dangerous feature for users who aren't prepared for it.
I think the default designation for that keybinding should be null, or better yet, removed altogether.

### Other

Translator in use. KO > EN

**Comment by ltdrdata** [comment]
That's legit.

**Comment by huchenlei** [comment]
You can unbind that keybinding in settings for now. The binding will be removed in the next frontend release.
![image](https://github.com/user-attachments/assets/1ca34418-decc-4470-ab99-b8ffae1d2bad)
