### ISSUE TITLE
CheckPointLoaderSimple invalid load key, \xfe.

### ISSUE THREAD

**Issue by MrMajorThorburn** [comfyanonymous/ComfyUI#5729]
### Your question

New user. Got this problem on first try. The title is the info from the web page.
The windows command window has 

 File "D:\Tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1628, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   
_pickle.UnpicklingError: invalid load key, '\xfe'.

Anyone any hints for me?

### Logs

```powershell
I am sorry I do not know how to get this info.
```

**Comment by ltdrdata** [comment]
Please make sure that the model you downloaded is the correct one.

**Comment by MrMajorThorburn** [comment]
I have downloaded and installed the latest version.
I got a red error so downloaded https://huggingface.co/Comfy-Org/stable-diffusion-v1-5-archive/blob/main/v1-5-pruned-emaonly-fp16.safetensors and renamed it to v1-5-pruned-emaonly-fp16.ckpt and copied it to ComfyUI_windows_portable\comfyUI\models\checkpoints
and got 

Prompt outputs failed validation
CheckpointLoaderSimple:
- Value not in list: ckpt_name: 'v1-5-pruned-emaonly.ckpt' not in ['v1-5-pruned-emaonly-fp16.ckpt']

How am I supposed to get the safetensors file into the ckpt_name list.
I need more information in the README_VERY-IMPORTANT file.

**Comment by ltdrdata** [comment]
> I have downloaded and installed the latest version. I got a red error so downloaded https://huggingface.co/Comfy-Org/stable-diffusion-v1-5-archive/blob/main/v1-5-pruned-emaonly-fp16.safetensors and renamed it to v1-5-pruned-emaonly-fp16.ckpt and copied it to ComfyUI_windows_portable\comfyUI\models\checkpoints and got
> 
> Prompt outputs failed validation CheckpointLoaderSimple:
> 
> * Value not in list: ckpt_name: 'v1-5-pruned-emaonly.ckpt' not in ['v1-5-pruned-emaonly-fp16.ckpt']
> 
> How am I supposed to get the safetensors file into the ckpt_name list. I need more information in the README_VERY-IMPORTANT file.

Refresh browser and reselect file.

**Comment by MrMajorThorburn** [comment]
Refresh did the trick.

**Comment by Nelis-AI** [comment]
ERROR: **_pickle.UnpicklingError: invalid load key, '\xfe'.** 

I am running a ARM machine with snapdragon X elite, and I have a feeling that is holding me back, 

------

# ComfyUI Error Report
## Error Details
- **Node ID:** 4
- **Node Type:** CheckpointLoaderSimple
- **Exception Type:** _pickle.UnpicklingError
- **Exception Message:** invalid load key, '\xfe'.
## Stack Trace
```
  File "C:\Users\X\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.3.7
- **Arguments:** ComfyUI\main.py --cpu --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cpu
  - **Type:** cpu
  - **VRAM Total:** 33893679104
  - **VRAM Free:** 16824102912
  - **Torch VRAM Total:** 33893679104
  - **Torch VRAM Free:** 16824102912

## Logs
```
2024-12-13T14:00:12.044567 - Total VRAM 32324 MB, total RAM 32324 MB
2024-12-13T14:00:12.044567 - pytorch version: 2.5.1+cu124
2024-12-13T14:00:12.044567 - Set vram state to: DISABLED
2024-12-13T14:00:12.044567 - Device: cpu
2024-12-13T14:00:12.825282 - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1384, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1628, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**_pickle.UnpicklingError: invalid load key, '\xfe'.**

2024-12-13T14:00:17.017285 - Prompt executed in 0.02 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":9,"last_link_id":9,"nodes":[{"id":7,"type":"CLIPTextEncode","pos":[413,389],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":6,"type":"CLIPTextEncode","pos":[415,186],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["beautiful scenery nature glass bottle landscape, , purple galaxy bottle,"]},{"id":5,"type":"EmptyLatentImage","pos":[473,609],"size":[315,106],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":3,"type":"KSampler","pos":[863,186],"size":[315,262],"flags":{},"order":4,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":1},{"name":"positive","type":"CONDITIONING","link":4},{"name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[424183492161701,"randomize",20,8,"euler","normal",1]},{"id":8,"type":"VAEDecode","pos":[1209,188],"size":[210,46],"flags":{},"order":5,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":[1451,189],"size":[210,58],"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":4,"type":"CheckpointLoaderSimple","pos":[26,474],"size":[315,98],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[1],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1},{"name":"VAE","type":"VAE","links":[8],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["v1-5-pruned-emaonly.ckpt"]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7513148009015777,"offset":[128.59600000000006,150.54700000000014]}},"version":0.4}
```
