### ISSUE TITLE
Noob Needs Help - Unsupported Python Version

### ISSUE THREAD

**Issue by reefor** [comfyanonymous/ComfyUI#5731]
### Your question

I'm running Comfyui Portable on an old windows laptop with Nvidia.

I have a couple of errors that I can figure out how to fix. One of them tells me that I'm running an unsupported version of Python and I should convert to  Python 3.9, 3.10 or 3.11.

I don't run python outside of Comfyui, I don't even know if the portable uses python. Can someone tell me how to fix this please? (I've been searching for an answer for weeks)

### Logs

```powershell
C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-22 09:58:33.205758
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI
** Log path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   2.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16271 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\web
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Adding C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Could not find efficiency nodes
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
Loaded ControlNetPreprocessors nodes from C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V7.11.4)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
### Loading: ComfyUI-Impact-Pack (V7.11.4)
Loaded ImpactPack nodes from C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\nodes.py", line 9, in <module>
    from diffusers import ConsistencyDecoderVAE
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py). Did you mean: 'hf_hub_download'?

Cannot import C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes module for custom nodes: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py)
### Loading: ComfyUI-Impact-Pack (V7.11.4)
[Impact Pack] Wildcards loading done.
C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.21 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Total VRAM 6144 MB, total RAM 16271 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.51.9)
### ComfyUI Revision: 2851 [94323a26] | Released on '2024-11-22'
------------------------------------------
### N-Suite Revision: ae7cc848
Current version of packaging: 23.2
Version of cpuinfo: Not found
Current version of git: 3.1.43
Current version of moviepy: 1.0.3
Current version of cv2: 4.10.0
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Current version of skbuild: 0.18.1
Version of typing: Not found
Current version of diskcache: 5.6.3
Installing llama_cpp...
Python version: None
OS: Windows
OS bit: 64
Platform tag: cp312-cp312-win_amd64
Unsupported Python version. Please use Python 3.9, 3.10 or 3.11.
Current version of timm: 1.0.11
Traceback (most recent call last):
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\__init__.py", line 64, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\gptcpp_node.py", line 4, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'
[tinyterraNodes] Loaded

[rgthree-comfy] Loaded 42 extraordinary nodes. 🎉


Import times for custom nodes:
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Img2PaintingAssistant
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-copilot
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds (IMPORT FAILED): C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes
   0.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Anyline
   0.5 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   0.7 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-propost
   0.7 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
   1.4 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg
   3.3 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes
```

**Comment by askmyteapot** [comment]
My suggestion would be to uninstall python, then download and install 3.10.11 from here https://www.python.org/downloads/release/python-31011/
You might need to delete and redo the 'install' of portable comfyui so it gets all the python 3.10 compatible packages.

**Comment by reefor** [comment]
> My suggestion would be to uninstall python, then download and install 3.10.11 from here https://www.python.org/downloads/release/python-31011/ You might need to delete and redo the 'install' of portable comfyui so it gets all the python 3.10 compatible packages.

Thanks for the help, but I never installed python, and comfy portable isn't really an install, it just sort of resides in it's own folder.

That's why I'm confused. I thought comfy portable was supposed to have all the python and/or cuda files it needed to run in it's folder.

Keep in mind that I am a noob at this, I never touched python before this and rarely even used the windows command prompt before this.

Am I mistaken about how portable runs?

**Comment by LostDiffusion** [comment]
The very first line of your error message shows you where python is being called from. The next few lines tell you that Python 3.12 is running.
```
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-22 09:58:33.205758
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe
```
And comfy won't run with Python 3.12. So yes, at some point Comfy updated the python version, and it has to be downgraded. It might have happened if you went into Comfy manager and chose one of the Update options.

The portable installer looks like it has 3.11 in it. Just download the portable again and extract it into the same location so it can overwrite your python. 

If it makes you nervous, installed it in a different location and just try copying the python-embedded folder over.

There is no Python for Comfy. It's just Python.

**Comment by IAFFeng** [comment]
> 错误消息的第一行显示了 python 的调用位置。接下来的几行告诉您正在运行 Python 3.12。
> 
> ```
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2024-11-22 09:58:33.205758
> ** Platform: Windows
> ** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
> ** Python executable: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe
> ```
> 
> 而且 comfy 无法在 Python 3.12 上运行。所以是的，Comfy 在某些时候更新了 Python 版本，因此必须降级。如果您进入 Comfy 管理器并选择其中一个更新选项，则可能会发生这种情况。
> 
> 便携式安装程序看起来里面有 3.11。只需再次下载便携式安装程序并将其解压到同一位置，它就可以覆盖你的 Python。
> 
> 如果这让您感到紧张，请将其安装在其他位置，然后尝试复制 python-embedded 文件夹。
> 
> Comfy 没有 Python。它只有 Python。

Don't mislead others, the latest python version of comfyui is 3.12

**Comment by reefor** [comment]
> > The first line of the error message shows where python is being called from. The next few lines tell you that you are running Python 3.12.
> > ```
> > ## ComfyUI-Manager: installing dependencies done.
> > ** ComfyUI startup time: 2024-11-22 09:58:33.205758
> > ** Platform: Windows
> > ** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
> > ** Python executable: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And comfy does not run on Python 3.12. So yes, Comfy updated the Python version at some point, so it had to be downgraded. This can happen if you go into the Comfy manager and select one of the update options.
> > The portable installer looks like it has 3.11 inside it. Just download the portable installer again and extract it to the same location and it should overwrite your Python.
> > If this makes you nervous, install it somewhere else and try copying the python-embedded folder over.
> > Comfy doesn't have Python. It just has Python.
> 
> Don't mislead others, the latest python version of comfyui is 3.12



Thanks to both of you, I feel like I'm getting closer to a solution.

The version currently in that folder (C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe) and in the zip folder are both 3.12.7.

When I saw the error message I automatically thought that I have to upgrade, not downgrade. A noob mistake I guess.

So I just have to find one of the other versions (3.9, 3.10 or 3.11), download it, and replace the current version? That won't mess anything up and I don't have to do a pip install?

**Comment by reefor** [comment]
Or is this not really a problem, just some tag that needs to be updated to Comfy doesn't report an incompatibility that doesn't really exist?

**Comment by ltdrdata** [comment]
This issue occurs when using ComfyUI-N-Nodes.

The portable version of ComfyUI is provided with Python 3.12. 
To resolve this issue, you need to manually install Python 3.11 and set up a venv.

**Comment by reefor** [comment]
> This issue occurs when using `ComfyUI-N-Nodes`.
> 
> The portable version of ComfyUI is provided with Python 3.12. To resolve this issue, you need to manually install Python 3.11 and set up a venv.

Thanks

So then it's not a problem that really isn't a problem that I can just ignore. Cool

I'm sure I can find the right version but I have no idea about setting up a venv. Is there a tutorial video somewhere?

**Comment by ltdrdata** [comment]
> > This issue occurs when using `ComfyUI-N-Nodes`.
> > The portable version of ComfyUI is provided with Python 3.12. To resolve this issue, you need to manually install Python 3.11 and set up a venv.
> 
> Thanks
> 
> So then it's not a problem that really isn't a problem that I can just ignore. Cool
> 
> I'm sure I can find the right version but I have no idea about setting up a venv. Is there a tutorial video somewhere?

1. Install Python 3.11 on your system (make sure to remove any previously installed versions of Python, if applicable).  
2. Open the Command Prompt (`cmd`).  
3. Navigate to the directory where you want to create a virtual environment (venv). It’s convenient to place the venv near the target application path since you need to activate the venv before running the application.  
   *(Assuming you are creating the venv inside the ComfyUI directory)*  
4. Run the command:  
   ```bash
   python -m venv venv
   ```  
   *(This will create a `venv` directory inside the `ComfyUI` folder)*  
5. Activate the virtual environment by running:  
   ```bash
   .\venv\scripts\activate
   ```  
   *(The venv environment will now be active)*  
6. Within the activated venv environment, install `torch` and the `ComfyUI` requirements by running:  
   ```bash
   pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
   pip install -r requirements.txt
   ```  
   *(If you have any previously installed custom nodes, ensure that everything in each custom node path is installed, or reinstall the custom nodes.)*  
7. While the venv environment is still active, run:  
   ```bash
   python main.py
   ```

**Comment by reefor** [comment]
> This issue occurs when using `ComfyUI-N-Nodes`.
> 
> The portable version of ComfyUI is provided with Python 3.12. To resolve this issue, you need to manually install Python 3.11 and set up a venv.

Thanks, but I'm now confused about something else. Using Comfyui Portable I don't remember ever setting up a venv for it, unless it's done automatically when running the requirements or something. Unless I'm wrong I just unzipped it, installed requirements and any bat files I saw, and ran it. I think I might have done some pathing as well.

After 2 hours of searching and watching videos on venv for comfyui I've come up with nothing useful. I just have 2 questions at this point.

Will manually installing python 3.11 and setting up a venv mess anything up in comfy portable?

Is there a good video tutorial on how to do it without messing things up?

**Comment by CosplayCookoff** [comment]
Why TF is this closed????   I am having the same problem and the moron that closed it did so without a solution!

**Comment by ltdrdata** [comment]
> > This issue occurs when using `ComfyUI-N-Nodes`.
> > 
> > The portable version of ComfyUI is provided with Python 3.12. To resolve this issue, you need to manually install Python 3.11 and set up a venv.
> 
> Thanks, but I'm now confused about something else. Using Comfyui Portable I don't remember ever setting up a venv for it, unless it's done automatically when running the requirements or something. Unless I'm wrong I just unzipped it, installed requirements and any bat files I saw, and ran it. I think I might have done some pathing as well.
> 
> After 2 hours of searching and watching videos on venv for comfyui I've come up with nothing useful. I just have 3 questions at this point.
> 
> Will manually installing python 3.11 and setting up a venv mess anything up in comfy portable?
> 
> Is there a good video tutorial on how to do it without messing things up?
> 
> Or, is the comfyui-n-nodes not compatible with comfyui portable?

Yup. The one of the dependencies of the ComfyUI-N-Nodes isn't compatible with the portable version.
Because the version of the portable versions is 3.12.
That is the reason why I suggest manual set up the venv.

**Comment by Tapyon** [comment]
OKEY GUYS ! WAIT A SECOND !!
im getting lost with all this big words!!!

i get it, some want to downgrade to make it work, some wants us to stay in lastest version cuz is gonna help from now on, but at the end , should we go to NOT PORTABLE? if thats a real question!! .. with the creation of the ENVIOREMENT (VENV) ??? 
is this making sense, even that i dont get nothing about it !!? ...

 im using portable on windows and have so many NODES BROKEN , that is unfair ! .. every pack of custom nodes i want to use is broken, FACESWAP, REACTOR, INSTANTID, 3dPACK, and keeps going ... is this the problem  of that? .. and can keep asking questions like the other guys,..

so what the PROS think about here?
