### ISSUE TITLE
Broken preprocessor after update

### ISSUE THREAD

**Issue by wardensc2** [comfyanonymous/ComfyUI#5732]
### Expected Behavior

After update the latest version to use Flux tool, I try to run preprocessor of DW pose on my workflow change a lot of node that can do prepocessor still get the same error and ComfyUI closed. 
Could not locate cudnn_cnn_infer64_8.dll. Please make sure it is in your library path!

![image](https://github.com/user-attachments/assets/a304beaa-cf33-4cba-bc90-4557e9fb2360)

Please fix it, thank in advance

### Actual Behavior

![image](https://github.com/user-attachments/assets/18f0f147-8073-4dcc-8c5f-516e0a405c88)

### Steps to Reproduce

[Preprocessor DW Pose.json](https://github.com/user-attachments/files/17873018/Preprocessor.DW.Pose.json)

### Debug Logs

```powershell
Starting server

To see the GUI go to: http://127.0.0.1:8188
C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
FETCH DATA from: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
←[33mQualityOfLifeSuit_Omar92:←[0m:NSP ready
[]
[]
got prompt
model_path is C:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v/DWPose\yolox_l.onnx
model_path is C:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16/DWPose-TorchScript-BatchSize5\dw-ll_ucoco_384_bs5.torchscript.pt

DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384_bs5.torchscript.pt for pose estimation
DWPose: Caching ONNXRuntime session yolox_l.onnx...
DWPose: Caching TorchScript module dw-ll_ucoco_384_bs5.torchscript.pt on ...
Could not locate cudnn_cnn_infer64_8.dll. Please make sure it is in your library path!
```

**Comment by brayevalerien** [comment]
This is not a ComfyUI issue, you should open an issue on the [auxiliary ControlNet extension](https://github.com/Fannovel16/comfyui_controlnet_aux/issues).

But it looks like an installation issue with cuDNN, make sure it's properly installed.

**Comment by wardensc2** [comment]
> This is not a ComfyUI issue, you should open an issue on the [auxiliary ControlNet extension](https://github.com/Fannovel16/comfyui_controlnet_aux/issues).
> 
> But it looks like an installation issue with cuDNN, make sure it's properly installed.

No it's definitely ComfyUI because I use another node which use DWpose, same error:

![image](https://github.com/user-attachments/assets/50c3e1aa-cea5-4ae2-b5b5-24cbea471970)

this is same error when I run above workflow:

![image](https://github.com/user-attachments/assets/fb2bd882-f0de-4681-98cd-e8363bf4e53d)

**Comment by wardensc2** [comment]
Thank I already find by reinstall ONNX
