### ISSUE TITLE
Well when I updated to the new ComfyUI it broke everything !!!!

### ISSUE THREAD

**Issue by Infinitusvoid** [comfyanonymous/ComfyUI#5749]
### Expected Behavior

Well the thing does not start anymore and did crash my computer 

### Actual Behavior

Well it should not do that 

### Steps to Reproduce

Well idk, you should test the software a little bit

![image](https://github.com/user-attachments/assets/3e2d6daa-ae24-4a82-aa6f-25e34b9ed8b2)

### Debug Logs

```powershell
wtf
```

### Other

wtf

**Comment by ltdrdata** [comment]
Check the file `ComfyUI/user/default/comfy.settings.json`
