### ISSUE TITLE
upscale mask

### ISSUE THREAD

**Issue by Chengym2023** [comfyanonymous/ComfyUI#5754]
### Your question

i edit mask at load image node,if i upscale this image by 2, how to make the mask upscale by 2?

**Comment by LukeG89** [comment]
You can use these nodes from [ComfyUI-KJNodes](https://github.com/kijai/ComfyUI-KJNodes)

Connect the mask to `Resize Mask` and the upscaled image to `Get Image Size & Count`

![resize_mask+get_image_size](https://github.com/user-attachments/assets/7110b502-95c6-4d4f-ab44-d9a910d14921)

**Comment by Chengym2023** [comment]
> You can use these nodes from [ComfyUI-KJNodes](https://github.com/kijai/ComfyUI-KJNodes)
> 
> Connect the mask to `Resize Mask` and the upscaled image to `Get Image Size & Count`
> 
> ![resize_mask+get_image_size](https://private-user-images.githubusercontent.com/161304036/389264471-7110b502-95c6-4d4f-ab44-d9a910d14921.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NDUxNTMsIm5iZiI6MTczMjQ0NDg1MywicGF0aCI6Ii8xNjEzMDQwMzYvMzg5MjY0NDcxLTcxMTBiNTAyLTk1YzYtNGQ0Zi1hYjQ0LWQ5YTkxMGQxNDkyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxMDQwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDMxNzM1N2VjMjBmNzQ1YzM3NzU4MTAwZGFkZWNhOTFhYTNiNTlhNDE3YjI3NDcyNzllMDM5ZTFmOGM5ZDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JwQERJth_VWveGCFVjQgNUzenoEWlomaUHVh_WtFkcs)

thank you!!!

**Comment by ltdrdata** [comment]
For reference, when using KSampler, mask upscale is performed automatically, so no additional upscaling is required.
