### ISSUE TITLE
Comfyui  Joy caption Error

### ISSUE THREAD

**Issue by Kimutaku66** [comfyanonymous/ComfyUI#5755]
### Your question

1 - After I installed everything, I got this error when running：Unrecognized model in D:\XXX\comfyui-portable-nfc1.2-windows\ComfyUI\models\Joy_caption_two\text_model. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: albert, align, altclip, audio-spectrogram-transformer, autoformer, bark......
2 - I made sure that all the files in the Joy_caption_two folder have the same names as shown above on Huggingface.
3 - Here is the address where I downloaded the file: https://github.com/EvilBT/ComfyUI_SLK_joy_caption_two

**Comment by LukeG89** [comment]
It's a problem with the custom node, you should ask for help in the node repo.

There's already a issue about your error:
- https://github.com/EvilBT/ComfyUI_SLK_joy_caption_two/issues/26
