### ISSUE TITLE
Did core nodes deleted?

### ISSUE THREAD

**Issue by kimnamwook1** [comfyanonymous/ComfyUI#5757]
### Your question

I try some controlnet and inpainting but the nodes that I use before gone. 

Node name is 

1. controlnetapply SD3 and Hunyuan DIT 
2. Differential Diffusion

these two nodes belongs to comfy-core nodes but I cant find it 

my comfyUI version is  3d802710 which Released on 2024-11-24

<img width="729" alt="sd3" src="https://github.com/user-attachments/assets/eacf6178-dfed-4a01-afb2-4215aade562d">
<img width="156" alt="sd32" src="https://github.com/user-attachments/assets/58382b6b-0347-4a1f-9ed5-5d01c66c2ec4">
<img width="721" alt="2" src="https://github.com/user-attachments/assets/ae133625-821c-45cf-960a-7441fc7321e8">
<img width="128" alt="21" src="https://github.com/user-attachments/assets/93bc1ee5-b8e2-4914-8121-4a9207f5f124">

**Comment by ltdrdata** [comment]
1.In the case of ControlNet, everything has been consolidated into `ControlNetApplyAdvanced`. The node is now named `Apply ControlNet`. The previous nodes have been deprecated, so while they can still be used for backward compatibility in existing workflows, they can no longer be manually added.

2.`Differential diffusion` still exists. If it cannot be found, that is an unusual issue.

**Comment by kimnamwook1** [comment]
> 1.In the case of ControlNet, everything has been consolidated into `ControlNetApplyAdvanced`. The node is now named `Apply ControlNet`. The previous nodes have been deprecated, so while they can still be used for backward compatibility in existing workflows, they can no longer be manually added.
> 
> 2.`Differential diffusion` still exists. If it cannot be found, that is an unusual issue.

will you notice me how to activate beta function in comfyUI? I knew that Differential diffusion is a beta version node

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/f1bd1dc7-998a-4b72-a000-761ff06247a4)

**Comment by kimnamwook1** [comment]
> ![image](https://private-user-images.githubusercontent.com/128333288/389272458-f1bd1dc7-998a-4b72-a000-761ff06247a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NTE4ODMsIm5iZiI6MTczMjQ1MTU4MywicGF0aCI6Ii8xMjgzMzMyODgvMzg5MjcyNDU4LWYxYmQxZGM3LTk5OGEtNGI3Mi1hMDAwLTc2MWZmMDYyNDdhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxMjMzMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTE4MDAzNjJkN2ZjZWJkNDcyYzdmOWFiMmRjZGUwN2E5NDAzMGUzM2Y2YzdhZWQzODA4MTVhNGIwYzM5ZDQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8MYhQ5wWaRXzJtW-YawwdD_xNc0MzDsZ7miL70QuKGQ)

your my guardian angel
