### ISSUE TITLE
about gpu used

### ISSUE THREAD

**Issue by Chengym2023** [comfyanonymous/ComfyUI#5758]
### Your question

my workflow looke like ollama+flux+ltxv
,how could i free gpu used after flux generate a image?
if not free ltxv run failed
![Uploading image.png…]()

**Comment by ltdrdata** [comment]
Does the issue still occur if you re-execute after a failure?

Anything loaded into VRAM is designed to be automatically released at the appropriate time through smart memory management. While there is a minor bug that can temporarily prevent complete release, re-executing after an error should resolve the issue.

Check if this is the case.

If you want to disable smart memory, you can add --disable-smart-memory as a CLI argument. In this case, models will always be released from VRAM after each node execution.
