### ISSUE TITLE
Missing Node Types 

### ISSUE THREAD

**Issue by H0icky** [comfyanonymous/ComfyUI#5770]
### Feature Idea

@huchenlei Hi
When we load some workflow with missing node types. The node will show red and replace the name with undefined. Can we just remain the original the node name, or maybe just add a suffix of “[undefined]”. So that even we can't run the workflow, we can read the workflow and try to understand what's going on without running it. I think it's better for user to quickly read and understand the workflow.

**Comment by LukeG89** [comment]
Yes, I agree. Whenever I try to help someone with their workflow, I can't figure anything out unless I have all the custom nodes installed.

If possible, it would be great to also see the widgets, so it is clearer what the problem might be (e.g. wrong models, wrong values, etc.).

**Comment by huchenlei** [comment]
This is actually a litegraph issue. Can you move the issue to https://github.com/Comfy-Org/litegraph.js?

**Comment by H0icky** [comment]
move to https://github.com/Comfy-Org/litegraph.js/issues/345
