### ISSUE TITLE
can not read properties of null

### ISSUE THREAD

**Issue by Chengym2023** [comfyanonymous/ComfyUI#5779]
### Your question

![image](https://github.com/user-attachments/assets/46aabceb-e292-4864-9c75-19ec40a14d65)
when i click 
![image](https://github.com/user-attachments/assets/26423934-58dd-4718-9de8-dde96139890b)

**Comment by ltdrdata** [comment]
Have you tried disabling all custom nodes and refreshing?
If the issue still persists, please report it on the front repo along with detailed logs (Press F12 if chrome).
https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by LukeG89** [comment]
That error is normal, because they replaced Reset View to Fit View. Fit View works if there are nodes on canvas.


https://github.com/user-attachments/assets/6f664ea8-4528-41ee-b865-00e74ad9f57a

**Comment by ltdrdata** [comment]
> @Chengym2023 @ltdrdata That error is normal, because they replaced Reset View with Fit View. Fit View works if there are nodes on canvas.
> 
>  Fit-View.mp4

@huchenlei It seems that the inappropriate error displayed in the empty state needs to be fixed.
