### ISSUE TITLE
disable gpu/memory/power consumption when not idle for more than 5 minute

### ISSUE THREAD

**Issue by ruwwww** [comfyanonymous/ComfyUI#5780]
### Feature Idea

option to enable disabling gpu when not idle for more than 5/10/30 minute. mainly to save electricity

**Comment by tomudo** [comment]
ComfyUI has no process running in background.

**Comment by ltdrdata** [comment]
> > ComfyUI has no process running in background.
> 
> is there a way to confirm this or check power usage in windows (desktop), because my wattmeter says otherwise

Is your hardware configured with at least two GPUs, where one Nvidia GPU is fully allocated to ComfyUI, and the monitor is assigned to another GPU, such as an integrated GPU?

If not, the GPU may not remain idle due to usage by the browser or other applications.
