### ISSUE TITLE
Misalignment of connection lines and nodes.

### ISSUE THREAD

**Issue by muxin159** [comfyanonymous/ComfyUI#5782]
### Expected Behavior

I can only use it normally when the browser zoom is set to 67%. If I increase or decrease the zoom level, the connection lines and nodes become misaligned.

### Actual Behavior

<img width="1787" alt="10ee6008693ee168c31f3bfa5a522e2" src="https://github.com/user-attachments/assets/f2d55094-32f9-4c51-9ca8-688e1f0cf73f">
<img width="1656" alt="f4a990fed7f9152ee0e426aecef3914" src="https://github.com/user-attachments/assets/468b96bf-f203-48c0-b954-4d03d77e5f1d">
<img width="1812" alt="71d41620b97fcbb9cb3eafcb91233de" src="https://github.com/user-attachments/assets/efc3794a-210a-4a8b-a6d0-0407bf1de107">

### Steps to Reproduce

Adjust the browser's display scale.

### Debug Logs

```powershell
nothing
```

**Comment by LukeG89** [comment]
Make sure everything is up-to-date (ComfyUI and all custom nodes). 

If you still have the problem, try disabling your nodes with `--disable-all-custom-nodes` argument and see if the problem is gone.
There might be an extension that is causing the issue.

**Comment by NeoGitCrt1** [comment]
Fixed after  upgrade comfyui-mixlab-nodes
