### ISSUE TITLE
Nodes and lines cannot correspond

### ISSUE THREAD

**Issue by RobinChen007** [comfyanonymous/ComfyUI#5798]
### Expected Behavior

after update version 0.3.5, open it from google browser in my computer,  all workflow's Nodes and lines cannot correspond. like the picture
<img width="1771" alt="截屏2024-11-27 18 13 19" src="https://github.com/user-attachments/assets/e94a70d8-54b0-445e-96ba-b42ae25bc367">

### Actual Behavior

![Uploading 截屏2024-11-27 18.13.19.png…]()

### Steps to Reproduce

I git clone version 0.3.5 comfyui project, but i do not want to install all old custom_nodes again, so i copy the folder from last version of comfyui. and then my question appeared.

### Debug Logs

```powershell
maybe it's not a bug, but it is truly affect my experience.
```

### Other

nothing to add

**Comment by LukeG89** [comment]
Update your nodes, it's probably mixlab

**Comment by RobinChen007** [comment]
> Update your nodes, it's probably mixlab

yes! this question has be solved !
