### ISSUE TITLE
Freezing Interface & Workflow

### ISSUE THREAD

**Issue by Domi443** [comfyanonymous/ComfyUI#5802]
### Expected Behavior

Load a Workflow, start generating an Image, Video etc.

### Actual Behavior

Load a Workflow and nothing showes up (Wheter I see nothing from the workflow or I see a freeze Image from it)

[image](https://github.com/user-attachments/assets/b432d533-f306-446e-9a82-a93a1eb87923))

### Steps to Reproduce

I had the old Version of ComfyUi with the old Interface and with the update I have now this Problem

### Debug Logs

```powershell
//
```

### Other

Please help me :(

**Comment by Domi443** [comment]
> scroll wheel to zoom-in 

no its freezing, I can't move, scroll etc.

**Comment by ltdrdata** [comment]
Disable all custom nodes and try again.
If the issue persist then report to here with detailed browser console log (press F12 if Chrome)
https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by vrgamegirl19** [comment]
Any updates on this? Mine was working just fine and today its freezing and some WF's won't load up.. and if they do I can't move around. If I press queue I do get images with the old prompt that was in there before but i can't change it. So strange. I uninstalled most of my custom nodes that are not needed but still have issues.

**Comment by ltdrdata** [comment]
> Any updates on this? Mine was working just fine and today its freezing and some WF's won't load up.. and if they do I can't move around. If I press queue I do get images with the old prompt that was in there before but i can't change it. So strange. I uninstalled most of my custom nodes that are not needed but still have issues. 

As mentioned above, please check the browser console logs.
