### ISSUE TITLE
Freezing Interface & Workflow

### ISSUE THREAD

**Issue by Domi443** [comfyanonymous/ComfyUI#5805]
### Expected Behavior

Load a Workflow, start generating an Image, Video etc.

### Actual Behavior

Load a Workflow and nothing showes up (Wheter I see nothing from the workflow or I see a freeze Image from it). I can not move, scroll etc.

I have already updated all and updated "comfyui and python dependencies". Whats should I do?

### Steps to Reproduce

I had the old Version of ComfyUi with the old Interface and with the update I have now this Problem

### Debug Logs

```powershell
//
```

### Other

Please help me :( To the Mods: don't close it when its not solved!

**Comment by LukeG89** [comment]
Try disabling your custom nodes using `--disable-all-custom-nodes` argument and see if you can load your workflows.

Probably one of the custom nodes is conflicting with the frontend.

**Comment by Domi443** [comment]
> Have you also updated all your nodes?
> 
> Try disabling your custom nodes using `--disable-all-custom-nodes` argument and see if you can load your workflows.
> 
> Probably one of the custom nodes is conflicting with the frontend.

Thanks my Problem is soved, it was a costom node.

**Comment by shenyx8lm** [comment]
> > Have you also updated all your nodes?
> > Try disabling your custom nodes using `--disable-all-custom-nodes` argument and see if you can load your workflows.
> > Probably one of the custom nodes is conflicting with the frontend.
> 
> Thanks my Problem is soved, it was a costom node.

Could you please tell me how you resolved it? I'm encountering the same issue as you, but I can't figure out which custom node is causing the problem.

**Comment by Domi443** [comment]
> > > Have you also updated all your nodes?
> > > Try disabling your custom nodes using `--disable-all-custom-nodes` argument and see if you can load your workflows.
> > > Probably one of the custom nodes is conflicting with the frontend.
> > 
> > 
> > Thanks my Problem is soved, it was a costom node.
> 
> Could you please tell me how you resolved it? I'm encountering the same issue as you, but I can't figure out which custom node is causing the problem.

Its still laging. In the Manager i have updated: all, ComfyUi and fetch. Now its lets say playable :)
