### ISSUE TITLE
Legacy Frontend command line is suddenly an invalid argument

### ISSUE THREAD

**Issue by ChatsideFires** [comfyanonymous/ComfyUI#5809]
### Expected Behavior

main.py to understand that "main.py --front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest" is supposed to be a thing.

### Actual Behavior

main.py is like 'what do you think you're talking about?'

### Steps to Reproduce

run "main.py --front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest" from the ComfyUI directory

### Debug Logs

```powershell
closed it but it just gave a list of acceptable command line things I might have meant, like --lowvram
```

**Comment by LukeG89** [comment]
I think the only way to access the legacy frontend is disabling the new one in Settings.

![image](https://github.com/user-attachments/assets/393a04f1-4545-4332-9573-502bb29213dc)

**Comment by ChatsideFires** [comment]
They might want to erase how it says to use that command line on the home page of the ComfyUI repo then - but better still, they should still support it.

**Comment by LukeG89** [comment]
As reported in this announcement:
- https://github.com/comfyanonymous/ComfyUI/issues/5395

### Will the legacy UI be removed?
Yes, we plan to eventually remove the legacy UI code to reduce maintenance overhead for both core and extension developers. This will streamline development and allow us to focus on new features without maintaining dual UI support.

The exact deprecation timeline will be determined based on user feedback and adoption rates of the new UI. We'll ensure a smooth transition period to accommodate our user community's needs.

**Comment by ChatsideFires** [comment]
I know it's the default option I just don't want to not have it anymore. It doesn't matter anyway because 'main.py' won't run anything for me now, line 12 errs out with 'Namespace has no attribute 'verbose.''

Messing with this stuff is fine that's what coders do but this doesn't DO anything anymore

**Comment by ChatsideFires** [comment]
This is still live here on the main page: github.com/comfyanonymous/ComfyUI:

Accessing the Legacy Frontend

If you need to use the legacy frontend for any reason, you can access it using the following command line argument:

--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest

**Comment by comfyanonymous** [comment]
The command line argument still works fine here. It sounds like your ComfyUI install might have issues so I recommend starting over with a fresh one.

**Comment by huchenlei** [comment]
The `--front-end-version` arg is definitely still supported. Please confirm that your ComfyUI is up-to-date.
