### ISSUE TITLE
good the bad

### ISSUE THREAD

**Issue by paiotao** [comfyanonymous/ComfyUI#5812]
### Your question

just got comfy loaded a model worked great clear and crisp, then it all went to hell, blurry images and low quality didnt change any settings how do i fix?

**Comment by ltdrdata** [comment]
There isn't enough information, so we can't provide any help with this.

**Comment by Buumcode** [comment]
Looks like you change your prompt. Start your promt with tehnical tags, like: score_9, score_8_up, score_7_up, score_6_up, score_5_up, score_4_up, concept art, realistic, best quality, detailed, detailed body, detailed face, extremely detailed, ultra detailed, masterpiece, photorealistic, cinematic
