### ISSUE TITLE
InpaintModelConditioning InpaintModelConditioning.encode() missing 1 required positional argument: 'noise_mask'

### ISSUE THREAD

**Issue by north151** [comfyanonymous/ComfyUI#5813]
### Expected Behavior

The method described in #5741  does not solve this problem
Both new and old versions of comfyui and Comfyui-inpaint-Nodes.

### Actual Behavior

.

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/f64bb1f4-9c30-435f-8ac3-c7744f003b22)

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** InpaintModelConditioning
- **Exception Type:** TypeError
- **Exception Message:** InpaintModelConditioning.encode() missing 1 required positional argument: 'noise_mask'
## Stack Trace

  File "/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
```

**Comment by huangguoyang** [comment]
+1

**Comment by huangjianyi0701** [comment]
> ### Expected Behavior
> The method described in #5741 does not solve this problem Both new and old versions of comfyui and Comfyui-inpaint-Nodes.
> 
> ### Actual Behavior
> .
> 
> ### Steps to Reproduce
> ![image](https://private-user-images.githubusercontent.com/70125880/390628244-f64bb1f4-9c30-435f-8ac3-c7744f003b22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODg1MzMsIm5iZiI6MTczMjc4ODIzMywicGF0aCI6Ii83MDEyNTg4MC8zOTA2MjgyNDQtZjY0YmIxZjQtOWMzMC00MzVmLThhYzMtYzc3NDRmMDAzYjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDEwMDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjODU1ZTgwNGI4M2FhOGUwZDAwZDNmYjFmZDg3Zjg5ZjVhYzBlMDcwNzJiMDdkYjNiNDk3OTU1NTVhNWQ0ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ElHCyP2XADIzydSfAHoLxIO3T1A29aLfCxJfOOBi-L0)
> 
> ### Debug Logs
> ```powershell
> # ComfyUI Error Report
> ## Error Details
> - **Node Type:** InpaintModelConditioning
> - **Exception Type:** TypeError
> - **Exception Message:** InpaintModelConditioning.encode() missing 1 required positional argument: 'noise_mask'
> ## Stack Trace
> 
>   File "/ComfyUI/execution.py", line 323, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
> 
>   File "/ComfyUI/execution.py", line 198, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
> 
>   File "/ComfyUI/execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
> 
>   File "/ComfyUI/execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
> ```
> 
> ### Other
> _No response_

Update impact-pack to the latest version

**Comment by comfyanonymous** [comment]
Should be fixed now.

**Comment by ltdrdata** [comment]
> The error is still reported as before

Update ComfyUI to latest version.

**Comment by ltdrdata** [comment]
> 0.3.5 is the latest version

Nope. This update is not released. So you have to update to nightly patch.
goto ComfyUI dir and execute `git pull`
