### ISSUE TITLE
Replace "pip" with "uv pip" - faster dependency installation/management

### ISSUE THREAD

**Issue by HWiese1980** [comfyanonymous/ComfyUI#5819]
### Feature Idea

There are several places where ComfyUI uses pip to install and update dependencies. They can be drop-in replaced with `uv pip install` instead of `python -m pip install`. `uv` is way faster than pip. It is just an additional dependency that needs to be installed alongside ComfyUI itself.

### Existing Solutions

I don't think there is any.

**Comment by ltdrdata** [comment]
It is an issue to be addressed in packaging rather than the ComfyUI repository, and it is already being implemented in the Desktop version.

https://blog.comfy.org/open-sourcing-v1-desktop/

**Comment by TPO-Code** [comment]
> ### Feature Idea
> 
> There are several places where ComfyUI uses pip to install and update dependencies. They can be drop-in replaced with `uv pip install` instead of `python -m pip install`. `uv` is way faster than pip. It is just an additional dependency that needs to be installed alongside ComfyUI itself.
> ### Existing Solutions
> 
> I don't think there is any.
> ### Other
> 
> _No response_

I was thinking the same thing. if you are on linux you could try doing what i did and  route calls to pip to uv pip before installing comfy's requirements create the .venv and run this to make 'pip' get routed to uv pip.
just read through the code first before you run it to be sure you are happy with it (im not responsible if it goes wrong).
pip-uv.sh:
```bash
# from ComfyUI root
source .venv/bin/activate
cd .venv/bin

# Keep originals
[ -f pip.real ] || mv pip pip.real
[ -f python.real ] || mv python python.real

# 1) pip wrapper: try uv, else real pip
cat > pip <<'SH'
#!/usr/bin/env bash
set -e
# If uv is missing, go straight to real pip
if command -v uv >/dev/null 2>&1; then
  # Try uv pip first; if it fails, fall back to real pip
  if uv pip "$@"; then
    exit 0
  fi
fi
# Fallback
exec "$(dirname "$0")/pip.real" "$@"
SH
chmod +x pip

# 2) python wrapper: intercept "python -m pip ..."
cat > python <<'SH'
#!/usr/bin/env bash
# If invoking "python -m pip", try uv pip then fall back
if [ "$#" -ge 2 ] && [ "$1" = "-m" ] && [ "$2" = "pip" ]; then
  shift 2
  if command -v uv >/dev/null 2>&1; then
    if uv pip "$@"; then
      exit 0
    fi
  fi
  exec "$(dirname "$0")/python.real" -m pip "$@"
else
  exec "$(dirname "$0")/python.real" "$@"
fi
SH
chmod +x python

# Optional: also wrap pip3 to be safe
[ -e pip3 ] || ln -s pip pip3
```

This works for me and was super fast, may not work for everyone
