### ISSUE TITLE
Question* Is there a list of prefix?

### ISSUE THREAD

**Issue by Blitzarts** [comfyanonymous/ComfyUI#582]
I ask this cause i need to know if There is anyway to save the outputs in separated folders like on SD web-ui?
like ex:

Comfyui/outputs/
folder: 28-04-2023
folder: 27-04-2023

and so on.

pd: incredible work, i really like this way to work with SD :D!

**Comment by comfyanonymous** [comment]
Yes, if you put a prefix like folder/ComfyUI it will create the folder.

For how to use dates and other variables in the prefix see: https://github.com/comfyanonymous/ComfyUI/pull/321

**Comment by Blitzarts** [comment]
I knew there was a way, I just didn't know how hahaha, but there always is. Thank you so much!
