### ISSUE TITLE
PerpNegGuider empty conditioning

### ISSUE THREAD

**Issue by tsharipov** [comfyanonymous/ComfyUI#5827]
Hi. What should i put into empty conditioning input? Example please, if i have pos and neg clips.

<img width="1666" alt="Screenshot 2024-11-28 at 19 50 28" src="https://github.com/user-attachments/assets/1706ebfe-3bd2-4fc1-8d53-5bc5ff1aaf8e">

**Comment by LukeG89** [comment]
You have to connect a CLIP Text Encode node and keep it empty
