### ISSUE TITLE
flux1-dev-bnb-nf4-v2 doesn't work anymore

### ISSUE THREAD

**Issue by djdance** [comfyanonymous/ComfyUI#5832]
### Your question

I used to run **flux1-dev-bnb-nf4-v2** from SwarmUI and it worked fine (yes, I know, this is ComfyUI, but wait a bit). I've upgraded ComfyUI. And now it can not work with flux nf4. The crash is

> ComfyUI execution error: All input tensors need to be on the same GPU, but found some tensors to not be on a GPU:
>  [(torch.Size([4718592, 1]), device(type='cpu')), (torch.Size([1, 3072]), device(type='cuda', index=0)), (torch.Size([1, 3072]), device(type='cuda', index=0)), (torch.Size([147456]), device(type='cpu')), (torch.Size([16]), device(type='cpu'))]

I tried ComfyUI alone (got the same crash), I tried SDXL & SD3 (they work fine). 
I googled, upgraded python, reinstalled all, it doesn't help.

1. Does anyone know what to do?

2. ComfyUI's help only says how to work with Flux dev/schnell. Where are notes about nf4? 

Thanks.

**Comment by ltdrdata** [comment]
https://github.com/silveroxides/ComfyUI_bnb_nf4_fp4_Loaders
