### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied (256x4096 and 768x320)

### ISSUE THREAD

**Issue by sokpheak168** [comfyanonymous/ComfyUI#5836]
### Expected Behavior

mat1 and mat2 shapes cannot be multiplied (256x4096 and 768x320)

### Actual Behavior

mat1 and mat2 shapes cannot be multiplied (256x4096 and 768x320)

### Steps to Reproduce

mat1 and mat2 shapes cannot be multiplied (256x4096 and 768x320)

### Debug Logs

```powershell
mat1 and mat2 shapes cannot be multiplied (256x4096 and 768x320)
```

### Other

mat1 and mat2 shapes cannot be multiplied (256x4096 and 768x320)

**Comment by ltdrdata** [comment]
Do not mix and use incompatible models such as checkpoint, ControlNet, CLIP, etc.

**Comment by laobenmao** [comment]
![Image](https://github.com/user-attachments/assets/b71fd693-adcc-4f79-ad08-9c79110ed4cb)
![Image](https://github.com/user-attachments/assets/7f9ef102-9def-4f58-8e42-05cb4dcb60c4)

![Image](https://github.com/user-attachments/assets/7673c559-e5bd-4c3a-ae8f-f83e70115800)
same problem. I don't know why.

**Comment by Stay-cpu** [comment]
蹲，我也不知道该如何解决？求大佬留下宝贵的意见。
