### ISSUE TITLE
how could redux work with bach >1

### ISSUE THREAD

**Issue by jasoncow007** [comfyanonymous/ComfyUI#5839]
### Expected Behavior

redux works fine

### Actual Behavior

Prompt executed in 0.34 seconds
got prompt
!!! Exception during processing !!! Sizes of tensors must match except in dimension 1. Expected size 8 but got size 1 for tensor number 1 in the list.

### Steps to Reproduce

bach size >1

### Debug Logs

```powershell
Prompt executed in 0.34 seconds
got prompt
!!! Exception during processing !!! Sizes of tensors must match except in dimension 1. Expected size 8 but got size 1 for tensor number 1 in the list.
```

**Comment by ltdrdata** [comment]
![workflow (39)](https://github.com/user-attachments/assets/5b9e17d2-200b-4eb8-9257-7d02fc997201)
There is no issue with using Redux in batch mode. The workflow has been set up incorrectly.

**Comment by jasoncow007** [comment]
> There is no issue with using Redux in batch mode. The workflow has been set up incorrectly.

![image](https://github.com/user-attachments/assets/73543b7a-ab0f-402a-b6f0-7911936408b9)
batch in this way

**Comment by ltdrdata** [comment]
That issue seems to be something that should be addressed to the ComfyUI_essentials repository:  
https://github.com/cubiq/ComfyUI_essentials

**Comment by ltdrdata** [comment]
> > That issue seems to be something that should be addressed to the ComfyUI_essentials repository: https://github.com/cubiq/ComfyUI_essentials
> 
> nope，change empty latent to comfy core, same result

I mentioned that because of the `Batch Prompt Schedule`.
First, check if the issue occurs without using a custom node.

**Comment by jasoncow007** [comment]
> > > That issue seems to be something that should be addressed to the ComfyUI_essentials repository: https://github.com/cubiq/ComfyUI_essentials
> > 
> > 
> > nope，change empty latent to comfy core, same result
> 
> I mentioned that because of the `Batch Prompt Schedule`. First, check if the issue occurs without using a custom node.

of course not, but I hope it could be ran in this way, to keep more consist

**Comment by jasoncow007** [comment]
beside this attempting to get more consistency,#5777 qwen2vl flux is a second choice
