### ISSUE TITLE
work flow switch

### ISSUE THREAD

**Issue by Chengym2023** [comfyanonymous/ComfyUI#5842]
### Your question

is there a node like this:
i use ollama write one prompt and test it,
send it to ksampler if image looks fine, and use it generate a lot images or upscale..,if not quit workflow.
my thinking:
#
![870669cf-4c2a-432c-bbba-0e9b4c94e499](https://github.com/user-attachments/assets/c3024d62-53b5-437a-99d5-5af7180d20d0)

**Comment by ltdrdata** [comment]
It seems that your attached image is broken.

**Comment by Chengym2023** [comment]
> It seems that your attached image is broken.
add the image

**Comment by ltdrdata** [comment]
There is a switch node available, but your scenario seems more suited for the control bridge in the Impact Pack.
