### ISSUE TITLE
0.3.5v no longer saves node titles in the API export

### ISSUE THREAD

**Issue by berkut0** [comfyanonymous/ComfyUI#5850]
### Expected Behavior

For example, if I save a workflow that has a CLIPTextEncoder and the title of the node is ‘POSITIVE’, I expect that title to be saved in JSON as in previous versions.

### Actual Behavior

For some reason, with the upgrade to the new version, the API stopped saving the title of the node. And now I can't select a specific node in JSON via title.

### Steps to Reproduce

Create a workflow, put any node (like CLIPTextEncoder), give it a name (and colour), save normally first, then export for API.

### Debug Logs

```powershell
{
  "1": {
    "inputs": {
      "text": ""
    },
    "class_type": "CLIPTextEncode"
  }
}
```

It used to look like this:

```powershell
{
  "1": {
    "inputs": {
      "text": ""
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "POSITIVE"
  }
}
```

### Other

Maybe I'm doing something wrong. Literally everything worked before the update.

I used JSONPath to select and edit the part of the JSON I wanted.
```$..[?(@.class_type == 'CLIPTextEncode' && @._meta.title=='POSITIVE')].inputs```
But without titles it becomes much more difficult and flexibility is lost.

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
