### ISSUE TITLE
cannot see queue execution button, help!

### ISSUE THREAD

**Issue by Gooneysea** [comfyanonymous/ComfyUI#5852]
### Your question

After running comfyui for the first time and starting sample workflow again I can't find the queue execution button, can anyone tell me how to bring up the queue button again?
![Screenshot 2024-12-01 114503](https://github.com/user-attachments/assets/f1a16e8e-3990-4c59-be6d-1d266d27905d)

**Comment by ltdrdata** [comment]
Clear the browser cache and try again.

**Comment by Gooneysea** [comment]
oh, yes, it's solved after clear browser cache, thank you!
