### ISSUE TITLE
No module named 'pytorch_lightning'

### ISSUE THREAD

**Issue by xiguan2022** [comfyanonymous/ComfyUI#5853]

**Comment by ltdrdata** [comment]
`pytorch_lightning` is not a dependency used by ComfyUI.  
You missed installing the `pytorch_lightning` dependency during the process of setting up a custom node.  

Install the `pytorch_lightning` package in the Python environment where you are running ComfyUI.
(`.\python_embeded\python.exe -m pip install pytorch_lightning` if your ComfyUI is portable version)
