### ISSUE TITLE
Primitive node attached to seed input of Ksampler switching from "randomize" to "fixed" when copying nodes

### ISSUE THREAD

**Issue by user37708** [comfyanonymous/ComfyUI#5857]
### Expected Behavior

Workflow where the seed widget of the Ksampler node has been converted to input and a primitive node is attached to input the seed.
The primitive node is set to "randomize" to generate a random seed each run.
 Copying and pasting these nodes should retain the "randomize" state of the primitive node.

![Screenshot1](https://github.com/user-attachments/assets/b70f8694-9456-4b84-9868-6967289db14f)

### Actual Behavior

When pasted, the primitive node switches to "fixed"

![Screenshot2](https://github.com/user-attachments/assets/a5dc0db3-2926-42c0-a19c-408177fb782e)

### Steps to Reproduce

Copy and paste a workflow or part of a workflow (including the primitive and Ksampler nodes) where the seed widget of the Ksampler node has been converted to input and a primitive node is attached to input a randomized seed. The state of the primitive node will change from randomize to fixed.

### Debug Logs

```powershell
-
```

**Comment by user37708** [comment]
May seem inconsequential but I use this in many workflows and when experimenting I copy and paste parts of workflows a lot, the seed generation becoming fixed without realizing it has caused wasted generation time.

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
