### ISSUE TITLE
New UI is hidden by custom nodes that introduced UIs (Must have custom nodes.. and I don't know their name anyway)

### ISSUE THREAD

**Issue by moreAImore** [comfyanonymous/ComfyUI#5865]
### Your question

Hello
The new UI while it is, I cannot get rid of the UI that was introduced another custom node (I don't know its name), so we have a problem, the new comfy UI is being HIDDEN by the custom node UI, look at the blue buttons they are hidde, I inserted arrows in the image:
![image](https://github.com/user-attachments/assets/083e1086-50c2-41fe-b1e4-efe80c43ace3)

**Comment by moreAImore** [comment]
> You need to open a bug report in the custom node repository to fix the issue. I guess it's [ComfyUI-mape-Helpers](https://github.com/mape/ComfyUI-mape-Helpers)?

I will now, thanks for finding its name.
I also wanted comfy to be aware of it so they mayeb make some changes that would automatically make all uis fit together?

**Comment by LukeG89** [comment]
> I also wanted comfy to be aware of it so they mayeb make some changes that would automatically make all uis fit together?

All frontend related issues and requests should be opened here: [ComfyUI_frontend](https://github.com/Comfy-Org/ComfyUI_frontend)
But most of the time, when an extension conflicts, custom node developers have to fix it. With all the new changes, this happens very often.
