### ISSUE TITLE
Strange behaviour with LTX-Video i2v

### ISSUE THREAD

**Issue by whitespace-rebel** [comfyanonymous/ComfyUI#5867]
### Expected Behavior

Correct reproduction of the image to video example

### Actual Behavior

The first frames of the video are very noisy. The noise goes away after 18~20 frames.

### Steps to Reproduce

https://github.com/user-attachments/assets/5159e42e-054f-4032-8bd5-16df63b306ca

Drag it into Comfy-UI in your browser.

### Debug Logs

```powershell
# Starting with:
export HSA_OVERRIDE_GFX_VERSION=9.0.0
python main.py --gpu-only --cpu-vae

Total VRAM 20480 MB, total RAM 31470 MB
pytorch version: 2.5.1+rocm6.2
Set vram state to: HIGH_VRAM
Device: cuda:0 AMD Radeon Graphics : native

100%|████████████████████████████████████████████████████████████| 30/30 [1:22:51<00:00, 165.72s/it]
Prompt executed in 5312.59 seconds

(So the term "Real time video" is a bit overstreched on my system)

My system:
Renoire APU (6 compute units)
32 GiB DDR4-RAM
Debian 12
```

### Other

I replaced the text encoder with the GGUF version to not get OOM.

**Comment by ltdrdata** [comment]
```
Set vram state to: HIGH_VRAM
```
You have to turn off  highvram mode.
Use `--normalvram`

**Comment by whitespace-rebel** [comment]
> You have to turn off highvram mode. Use `--normalvram`

Could you explain what is the rationale for this?

I did the inference again with "--normalvram" but it did not help.
I would consider reopening this issue, or were you able to use a similar system to mine and couldn't reproduce the noisy video, @ltdrdata ?

**Comment by whitespace-rebel** [comment]
I pulled the latest comfyui version and ran the inference with the default "Load CLIP" node with t5xxl_fp16.safetensors. The video was rendered correctly without noise at the beginning.
But the new comfyui version broke the "CLIPLoader (GGUF)" node. So I can't test it right now.
Maybe "CLIPLoader (GGUF)" node was the cause of the problem.

**Comment by whitespace-rebel** [comment]
Okay, I just found there is the same issue already reported here:
https://github.com/city96/ComfyUI-GGUF/issues/163

Closing this one.
