### ISSUE TITLE
Required input is missing: vae

### ISSUE THREAD

**Issue by yunchangxiaoguan** [comfyanonymous/ComfyUI#5877]
### Your question

i can't run the code
error like this：
got prompt
Failed to validate prompt for output 9:
* VAEDecode 8:
  - Required input is missing: vae
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

![111](https://github.com/user-attachments/assets/1a9bc407-8777-4a9c-9dc3-13899eb5c12e)

**Comment by ltdrdata** [comment]
Literally. You have to connect VAE from Checkpoint to VAELoader.
