### ISSUE TITLE
Update has messed up math nodes!

### ISSUE THREAD

**Issue by MarisKay** [comfyanonymous/ComfyUI#5884]
Simple math from essentials can't multiply two floats taken as inputs no more. Everything was perfect before today's update.

Failed to validate prompt for output 243:
* SimpleMath+ 266:
  - Return type mismatch between linked nodes: a, received_type(INT) mismatch input_type(*)
  - Return type mismatch between linked nodes: b, received_type(FLOAT) mismatch input_type(*)
* SimpleMath+ 267:
  - Return type mismatch between linked nodes: a, received_type(INT) mismatch input_type(*)
  - Return type mismatch between linked nodes: b, received_type(FLOAT) mismatch input_type(*)

Previously worked no matter whether you pass INT or FLOAT to the node. All my workflows are messed up now.

**Comment by Shangooriginal** [comment]
Same problem, the math nodes are no longer working as previously

**Comment by LukeG89** [comment]
@abozahran To solve your problem, you need to update mixlab

**Comment by LukeG89** [comment]
@MarisKay @Shangooriginal  This commit is the culprit: https://github.com/comfyanonymous/ComfyUI/commit/8d4e06324fb6c477c1f7f409c857c33d0b3b0ce2

**Comment by MarisKay** [comment]
So to get this straight, mixlab (whatever it is) should be updated and then the problem is gone? Could you please point how to update it on ubuntu? I am not sure what it even is, a program installed on ubuntu? or some comfy module?

**Comment by LukeG89** [comment]
@MarisKay the mixlab problem was only for @abozahran

**Comment by MarisKay** [comment]
ok, will try to git reset then, thanks for quick response, good luck with fixing the problem

**Comment by abozahran** [comment]
> @abozahran To solve your problem, you need to update mixlab

Thank you, that worked out 🌹
