### ISSUE TITLE
Inpaint appear as null eventhough correctly install

### ISSUE THREAD

**Issue by ncksykes** [comfyanonymous/ComfyUI#5893]
### Your question

I install inpaint package and copy and paste head file and V26 file inside inpaint folder in ComfyUI/models/inpaints but when i try to using it the load fooocus inpaint always appear as null, I reset and restart many times and try to delete and install packages, please help
<img width="629" alt="Screenshot 2567-12-04 at 03 01 46" src="https://github.com/user-attachments/assets/68ef228a-c8f9-4747-b288-1415e69c3fbd">
<img width="879" alt="image" src="https://github.com/user-attachments/assets/71dba2d2-2bf4-4d8f-b8e5-addb128bd160">

**Comment by LukeG89** [comment]
You should ask for help here: [comfyui-inpaint-nodes](https://github.com/Acly/comfyui-inpaint-nodes)
