### ISSUE TITLE
Disabling xformers when using 3rd party venv

### ISSUE THREAD

**Issue by siraxe** [comfyanonymous/ComfyUI#59]
Run into a slight issue using webui venv.
![image](https://user-images.githubusercontent.com/27487254/224483835-5138cf04-8502-435c-bb20-411f2d68bf7d.png)
Xformers work in webui ,but here it doesn't as something might be not compatible
Is there a way to disable it when starting comfyUI  ?

**Comment by siraxe** [comment]
Ah, maybe it's the python version ?
I have 3.10.7

**Comment by comfyanonymous** [comment]
Try to reinstall xformers: 
```
pip uninstall xformers
pip install xformers
```

**Comment by patriciagomesoo** [comment]
Hello, how do I disable xformers from ComfyUI? I find it inconsistent and as I don't use it with automatic1111 I wanted to be ale to disable as well in ComfyUI. Thank you :)

**Comment by robinjhuang** [comment]
@patriciagomesoo Try `python main.py --disable-xformers`

**Comment by hassandawa** [comment]
Edit run_cpu.bat add --disable-xformers at the end. 

.\python_embeded\python.exe -s ComfyUI\main.py --cpu --windows-standalone-build --disable-xformers
pause
