### ISSUE TITLE
something wrong in edge

### ISSUE THREAD

**Issue by muxuezzz** [comfyanonymous/ComfyUI#5901]
### Expected Behavior

use 0.3.6 or 0.3.5 in edge

### Actual Behavior

I tried to update to the latest version but the updated comfyui is not responding when clicking on the canvas when accessed using the edge browser but it works fine in chrome, attached below is the output from the console.

### Steps to Reproduce

visit by edge

### Debug Logs

```powershell
Uncaught TypeError: this._group.toReversed is not a function
at LGraph2.getGroupOnPos(litegraph.es.js:10058:25)
at LGraph2.processMouseMove(litegraph.es.js:5208:36)
at LGraph2.processMouseMove(simpleTouchSupport.ts:149:27)
at LGraph2.processMouseMove(app.ts:1263:35)
```

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
