### ISSUE TITLE
When you use copy-paste on nodes, all links are broken

### ISSUE THREAD

**Issue by grinlau18** [comfyanonymous/ComfyUI#5904]
### Your question

The browser is Chrome for MacOS

![截屏2024-12-04 15 30 43](https://github.com/user-attachments/assets/6e1e9920-7ce6-45d0-899f-37ff4086ce22)
![截屏2024-12-04 15 31 05](https://github.com/user-attachments/assets/3c61906b-debb-41c4-af85-cfd8facc7b27)

**Comment by ltdrdata** [comment]
Disable all custom nodes and try again.
If the issue still persists, then move this issue to the front repo.

https://github.com/Comfy-Org/ComfyUI_frontend
