### ISSUE TITLE
Impact-pack ,SEGM_DETECTOR model location

### ISSUE THREAD

**Issue by Ericchenfeng** [comfyanonymous/ComfyUI#5911]
### Your question

In webUI,person_yolov8m-seg.pt loacated in ComfyUI\models\ultralytics\segm, but in deskUI,when use UltrealyticsDevtorProvider ,person_yolov8m-seg.pt can not be detected, i need help ,when should i put "person_yolov8m-seg.pt" file?

**Comment by LearningCreator** [comment]
ComfyUI_windows_portable\ComfyUI\models\ultralytics\segm
