### ISSUE TITLE
AttributeError: 'CLIP' object has no attribute 'encode_from_tokens_scheduled'

### ISSUE THREAD

**Issue by FrankGonzalez07** [comfyanonymous/ComfyUI#5912]
### Expected Behavior

The ComfyUI can work well with CLIP.

### Actual Behavior

When using the custom_nodes comfyui-hydit, it show the following error:
`
Traceback (most recent call last):
  File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/easyai/Projects/23_ComfyUI/ComfyUI/nodes.py", line 65, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
AttributeError: 'CLIP' object has no attribute 'encode_from_tokens_scheduled'
`

My env:
- transformers==4.45.2
- clip==0.2.0
- diffusers==0.31.0

### Steps to Reproduce

When excuting ComfyUI/nodes.py.

### Debug Logs

```powershell
`
Traceback (most recent call last):
  File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/easyai/Projects/23_ComfyUI/ComfyUI/nodes.py", line 65, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
AttributeError: 'CLIP' object has no attribute 'encode_from_tokens_scheduled'
`
```

**Comment by asagi4** [comment]
Where do you get the CLIP model you pass into the encoder node in your workflow? Is it a custom node?

There was a pretty large change recently that may have broken some custom nodes. That error looks like you have some node creating an old version of the CLIP class that doesn't have the required new method. Or alternatively that you have a weird mix of old comfyui core with new nodes somehow.

**Comment by FrankGonzalez07** [comment]
> Where do you get the CLIP model you pass into the encoder node in your workflow? Is it a custom node?
> 
> There was a pretty large change recently that may have broken some custom nodes. That error looks like you have some node creating an old version of the CLIP class that doesn't have the required new method. Or alternatively that you have a weird mix of old comfyui core with new nodes somehow.

The clip is from the following, and I am wonderijng which version of comfyui I should clone or download:
`https://huggingface.co/Tencent-Hunyuan/HunyuanDiT-v1.1/tree/main/t2i/clip_text_encoder`

**Comment by asagi4** [comment]
@FrankGonzalez07 I mean are you using a custom node to load it in your workflow?

**Comment by FrankGonzalez07** [comment]
> @FrankGonzalez07 I mean are you using a custom node to load it in your workflow? If you are, the bug is with the custom node most likely and it needs to be updated to work with newer ComfyUI.
> 
> You should really just post a workflow that reproduces this bug, so it's easier to figure out what is going wrong.

my workflow is below:
https://github.com/Tencent/HunyuanDiT/blob/main/comfyui-hydit/workflow/workflow_v1.2_lora.json

**Comment by FrankGonzalez07** [comment]
> @FrankGonzalez07 I mean are you using a custom node to load it in your workflow? If you are, the bug is with the custom node most likely and it needs to be updated to work with newer ComfyUI.
> 
> You should really just post a workflow that reproduces this bug, so it's easier to figure out what is going wrong.

It is solved. I should git reset the specific version of the custom node. Thanks.

**Comment by zentst** [comment]
> > @FrankGonzalez07 I mean are you using a custom node to load it in your workflow? If you are, the bug is with the custom node most likely and it needs to be updated to work with newer ComfyUI.
> > You should really just post a workflow that reproduces this bug, so it's easier to figure out what is going wrong.
> 
> It is solved. I should git reset the specific version of the custom node. Thanks.

May I ask How to git reset the custom node? I try to reinstall node Comfyui-HunyuanDiT, but not working. or Which version should I install?

**Comment by FrankGonzalez07** [comment]
> > > @FrankGonzalez07 I mean are you using a custom node to load it in your workflow? If you are, the bug is with the custom node most likely and it needs to be updated to work with newer ComfyUI.
> > > You should really just post a workflow that reproduces this bug, so it's easier to figure out what is going wrong.
> > 
> > 
> > It is solved. I should git reset the specific version of the custom node. Thanks.
> 
> May I ask How to git reset the custom node? I try to reinstall node Comfyui-HunyuanDiT, but not working. or Which version should I install?

Just follow:
git clone https://github.com/comfyanonymous/ComfyUI.git
cd ${ComfyUI}
git reset --hard 90389b3b8a69c08c3ed0bcc9d87a92246578a8e3
