### ISSUE TITLE
better keyboard implementation

### ISSUE THREAD

**Issue by kalle07** [comfyanonymous/ComfyUI#5913]
### Feature Idea

ok i see all your inputs are mouse or pad optimized but i think most nerds using **keyboard**

lets say i have this

![grafik](https://github.com/user-attachments/assets/f6a00f78-3814-4404-92dd-4b8863c95fb7)

so i must click on every single number write a number and  MUST hit enter
very unconfortable  ;)

so why not once click on a number write a number and lets say with arrow keys i can move to the next number with out hiting enter to confirm the number ... 

maybe also set, if no numbers are allowed, I can't write any
maybe set also  "coma" same as "point"

and if i use "ctrl"+mouse and mark some nodes than hit right mouse-button (where ever) i can only bypass one node, if i hit "crlr"+B it works for all  ... so thats inconsistent on the other hand ...

**Comment by huchenlei** [comment]
Please file the issue in https://github.com/Comfy-Org/ComfyUI_frontend/issues. Thanks!

**Comment by kalle07** [comment]
sorry dont know the different ^^

**Comment by ltdrdata** [comment]
> sorry dont know the different ^^

The **ComfyUI** repository focuses solely on backend-related parts, while frontend functionality is handled exclusively by the **frontend repository**.
