### ISSUE TITLE
ConditioningSetTimestepRange start/end not working properly when using Flux

### ISSUE THREAD

**Issue by Windecay** [comfyanonymous/ComfyUI#5917]
### Expected Behavior

check and repair~please

### Actual Behavior

When I use ConditioningSetTimestepRange, the start and end steps percent are always very strange~ 
When the steps = 30 and set start=0.100, it will start from 13 steps, and the calculation of steps is non-linear

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/ab53ccf9-3fbd-4c2e-97f8-fa31ccd0179d)

### Debug Logs

```powershell
The log did not display any errors
```

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/1e21f4c14e6a0ce68764e71170082ed2c2da5c79

This should fix it.
