### ISSUE TITLE
Misaligned UI Elements in Workflow Section - Unable to Interact with Workflow

### ISSUE THREAD

**Issue by GaboAzorin** [comfyanonymous/ComfyUI#5939]
### Expected Behavior

The UI for the workflows section should display correctly, allowing the user to open and interact with workflows. When clicking on any part of the workflow, I expect the UI to respond properly, for example by allowing me to select and move nodes, edit their content, or perform other actions.

### Actual Behavior

The workflow interface seems to be misaligned, and I cannot interact correctly with the nodes. Sometimes, clicking on an empty area of the workflow unintentionally interacts with the title of a node or some other part, but without any visible effect. It appears as if the clickable areas and the visual representation are not synchronized, making interaction with nodes very difficult or impossible.

### Steps to Reproduce

Open ComfyUI in the browser (I've tested it on multiple browsers).
Go to the "Workflows" section and load any workflow (e.g., Flux_Gabriel.json).
Notice that the entire UI is shifted to the right, and clicking on nodes or empty spaces often does not produce the expected interactions.
When clicking in specific spots, the UI seems to register the click on a different area (e.g., clicking on an empty space affects a node title), but no visible changes occur.

### Debug Logs

```powershell
I am attaching relevant logs from the terminal, but I did not see any specific errors during this interaction. If you need any further detailed logs, let me know how I can collect them for you.
```

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
