### ISSUE TITLE
NODE_DISPLAY_NAME_MAPPINGS Usage

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#595]
The `NODE_DISPLAY_NAME_MAPPINGS` usage is ambiguous in the example, and your own usage of it is also ambiguous due to the your naming conventions essentially being the same from class name to node name. 

So how do we use this? 

I tried (NODE_CLASS_MAPPINGS names)

```
    "Create Video from Path": "Create Video from Path (Experimental)",
    "Write to Video": "Write to Video (Experimental)",
```

And (NODE_CLASS_MAPPINGS class names)

```
    "WAS_Create_Video_From_Path": "Create Video from Path (Experimental)",
    "WAS_Video_Writer": "Write to Video (Experimental)",
```

But neither changes the name of the nodes in context menu or the nodes themselves. 

They exist in the node mapping as

```
    "Create Video from Path": WAS_Create_Video_From_Path,
```
And
```
    "Write to Video": WAS_Video_Writer,
```

**Comment by comfyanonymous** [comment]
The string you put as the key in the NODE_CLASS_MAPPINGS should be the same string you put as the key in: NODE_DISPLAY_NAME_MAPPINGS

**Comment by WASasquatch** [comment]
Hmm. So it seems to not be working for some reason.

**Comment by WASasquatch** [comment]
Figured it out. I forgot to export the node name dict in my `__init__.py`

**Comment by xm1085** [comment]
> 想通了。我忘了在我的`__init__.py`

请问你怎么解决的，我在__init__.py中修改了NODE_DISPLAY_NAMES_MAPPINGS，但是不起作用

**Comment by WASasquatch** [comment]
> > 想通了。我忘了在我的`__init__.py`
> 
> 请问你怎么解决的，我在__init__.py中修改了NODE_DISPLAY_NAMES_MAPPINGS，但是不起作用

您是否为 `__init__.py` 文件中的映射导入实际的节点类？

**Comment by xm1085** [comment]
> > > 想通了。我忘了在我的`__init__.py`
> > 
> > 
> > 请问你怎么解决的，我在__init__.py中修改了NODE_DISPLAY_NAMES_MAPPINGS，但是不起作用
> 
> 您是否为 文件中的映射导入实际的节点类？`__init__.py`

我导入过了，但是NODE_DISPLAY_NAMES_MAPPINGS没有作用，只有NODE_CLASS_MAPPINGS起作用
<img width="448" alt="联想截图_20240812131139" src="https://github.com/user-attachments/assets/265ace1a-6083-4153-9d84-7d2c5407d227">
<img width="419" alt="联想截图_20240812131147" src="https://github.com/user-attachments/assets/7a8f0200-e9c9-4f69-b3a6-eeca278b4cb8">
<img width="503" alt="微信图片_20240812131223" src="https://github.com/user-attachments/assets/bcc79c1d-40ee-4493-895d-7d268fec26ef">

**Comment by xm1085** [comment]
> The string you put as the key in the NODE_CLASS_MAPPINGS should be the same string you put as the key in: NODE_DISPLAY_NAME_MAPPINGS

大佬，为什么我修改NODE_DISPLAY_NAME_MAPPINGS的值，没有作用，comfui中只能显示NODE_CLASS_MAPPINGS的值

**Comment by WASasquatch** [comment]
> > The string you put as the key in the NODE_CLASS_MAPPINGS should be the same string you put as the key in: NODE_DISPLAY_NAME_MAPPINGS
> 
> 大佬，为什么我修改NODE_DISPLAY_NAME_MAPPINGS的值，没有作用，comfui中只能显示NODE_CLASS_MAPPINGS的值

我认为这是因为在上面的代码中它是“
`NODE_DISPLAY_NAMES_MAPPINGS`。它应该是`NODE_DISPLAY_NAME_MAPPINGS`

**Comment by xm1085** [comment]
> > > The string you put as the key in the NODE_CLASS_MAPPINGS should be the same string you put as the key in: NODE_DISPLAY_NAME_MAPPINGS
> > 
> > 
> > 大佬，为什么我修改NODE_DISPLAY_NAME_MAPPINGS的值，没有作用，comfui中只能显示NODE_CLASS_MAPPINGS的值
> 
> 我认为这是因为在上面的代码中它是 `NODE_DISPLAY_NAMES_MAPPINGS`。它应该是`NODE_DISPLAY_NAME_MAPPINGS`

感谢感谢，你太棒了
