### ISSUE TITLE
To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.   check_for_updates()

### ISSUE THREAD

**Issue by IAFFeng** [comfyanonymous/ComfyUI#5953]
### Expected Behavior

How to set

### Actual Behavior

Reminder warning during startup

### Steps to Reproduce

H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.22 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.   check_for_updates()

### Debug Logs

```powershell
H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.22 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.   check_for_updates()
```

**Comment by IAFFeng** [comment]
How to cancel this update reminder

**Comment by ltdrdata** [comment]
```
H:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -U albumentations
```

**Comment by Kallamamran** [comment]
> ```
> H:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -U albumentations
> ```

Don't just do this. It might mess up several of your other dependencies!!! It did for me!
