### ISSUE TITLE
Florence2 caption CLIP Text Encode

### ISSUE THREAD

**Issue by Chengym2023** [comfyanonymous/ComfyUI#5957]
### Your question

using [ComfyUI-Florence2](https://github.com/kijai/ComfyUI-Florence2)Florence2run node to caption images, and send to CLIP Text Encode input. this node 'list' object has no attribute 'replace' .
[https://github.com/kijai/ComfyUI-Florence2/issues/5](url)

**Comment by ltdrdata** [comment]
Issues with the custom node should be resolved in the respective node repository.
