### ISSUE TITLE
`ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.

### ISSUE THREAD

**Issue by zhentong520** [comfyanonymous/ComfyUI#5977]
### Expected Behavior

The code is no longer available in numPy2.0

### Actual Behavior

An error occurs when running tripoSR, indicating that numpy version is not supported

### Steps to Reproduce

![图片](https://github.com/user-attachments/assets/f97c0571-78e2-4cc5-88dd-ea5c6bb99dd5)

### Debug Logs

```powershell
`ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.
```

**Comment by ltdrdata** [comment]
numpy 2.0 and above are incompatible with many pip packages.  
At this stage, it is essentially impossible to use ComfyUI and custom nodes properly with Numpy 2.0.  
It is recommended to downgrade to `numpy<2`.
