### ISSUE TITLE
LoraLoader nodes will not display folder hierarchies correctly

### ISSUE THREAD

**Issue by muxuezzz** [comfyanonymous/ComfyUI#5994]
### Your question

After a recent update I noticed that the LoraLoader node does not display the folder hierarchy correctly but rather all the lora are displayed in a list, this is affecting my usage to a certain extent, any other solutions please?

**Comment by LukeG89** [comment]
You can try the "Auto Nest Subdirectories" feature from [rgthree-comfy](https://github.com/rgthree/rgthree-comfy)

![image](https://github.com/user-attachments/assets/ea0bbd5e-0874-456e-bc53-181a4e95cdf0)

**Comment by ltdrdata** [comment]
In ComfyUI, the ability to represent subdirectories in multiple levels was never available by default. The functionality you saw was provided by an extension.
