### ISSUE TITLE
Web Version - Nodes visually disconnects from noodles and groups background

### ISSUE THREAD

**Issue by ReinerBforartists** [comfyanonymous/ComfyUI#5995]
### Expected Behavior

When panning and zooming the nodes should stay connected with the background, groups and noodles

### Actual Behavior

When panning and zooming the nodes shows disconnected with the background, groups and noodles. There is no error report. There is no crash. But the elements disconnects visually. Which makes further adjustments at the nodes impossible.

### Steps to Reproduce

That's the million dollar question. I have yet to find out how to reproduce. It happens randomly, i had it now three times since yesterday. It seem to happen when i change the browser zoom. I will have an eye at it.

### Debug Logs

```powershell
I am not allowed to attach the log here. Message becomes too long then. This behaviour is not reported as an error in the console anyways.

The console content is attached below as a text file.
```

### Other

I use Opera latest version. Just in case, the workflow is also attached.

[cogvideo simple upscaling.json](https://github.com/user-attachments/files/18077282/cogvideo.simple.upscaling.json)
![CogVideoX_Fun_final_00001](https://github.com/user-attachments/assets/c3ea402f-51a8-400d-a443-ccfe88de5e4c)

[log.txt](https://github.com/user-attachments/files/18077312/log.txt)

![disconnected](https://github.com/user-attachments/assets/fe9742df-b1a4-42fd-ba97-327ee3d0fb35)

https://github.com/user-attachments/assets/cf1738eb-a890-485e-9c12-80993af4839d

**Comment by LukeG89** [comment]
Update your custom nodes, it's probably mixlab

**Comment by ReinerBforartists** [comment]
Thanks for the hint, will do. But i just updated everything today.

**Comment by ReinerBforartists** [comment]
But how can a extension mix up the draw code of comfy?

**Comment by LukeG89** [comment]
> But how can a extension mix up the draw code of comfy?

Usually it's a conflict with the frontend, it happens very often lately because of the changes they make in the core

**Comment by huchenlei** [comment]
You can try uninstall mixlab and see if the issue resolves.
