### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by GXMT** [comfyanonymous/ComfyUI#6]
Traceback (most recent call last):
  File "D:\ComfyUI\main.py", line 178, in execute
    executed += recursive_execute(prompt, self.outputs, x, extra_data)
  File "D:\ComfyUI\main.py", line 76, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "D:\ComfyUI\nodes.py", line 497, in save_images
    img.save(f"output/{filename_prefix}_{counter:05}_.png", pnginfo=metadata, optimize=True)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 2428, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'output/ComfyUI_00010_.png'

No idea how to solve this problem. 
I can't generate new image

**Comment by bazettfraga** [comment]
You're almost certainly missing an output directory in the base directory of ComfyUI.

**Comment by GXMT** [comment]
> 

I have a output directory, and error occurs in end of image making process. Even I make png file at output directory myself, it does not work

**Comment by comfyanonymous** [comment]
This should be fixed now.

**Comment by comfyanonymous** [comment]
I guess this is solved.
