### ISSUE TITLE
Extremely slow and laggy using flux-dev fp8, possibly after update

### ISSUE THREAD

**Issue by TobiTomatoe** [comfyanonymous/ComfyUI#6008]
### Expected Behavior

flux-dev (fp8) normally doesn't run super fast on my machine (rtx3060 12gb), and it loads with some hickups, meaning it can cause my OS to lag for a moment until it is loaded, but other than that it always worked perfectly fine. I generate at slightly higher resolutions, which makes generation slower, but that is expected and never bothered me. The issue is the entire loading process.

### Actual Behavior

Since yesterday using flux-dev causes my OS to lag and stutter permanently and the loading of all models in the workflow is extremely slow. However I noticed that generation speed seems to be the same as before (maybe a little slower), but it takes ages to even get to that stage. I update comfyUI on a daily basis.

### Steps to Reproduce

No, complicated steps to reproduce the issue. Just using flux-dev (fp8)

### Debug Logs

```powershell
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLOW
Requested to load FluxClipModel_
loaded completely 9.5367431640625e+25 4777.53759765625 True
Requested to load Flux
loaded partially 8564.878622619628 8564.497131347656 123
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [07:38<00:00, 13.09s/it]
Requested to load AutoencodingEngine
loaded completely 9.5367431640625e+25 159.87335777282715 True
Prompt executed in 971.44 seconds
```

### Other

Again, the issue is not about generation speed. It is always a little slow, especially because I initially generate at slightly higher resolutions. It is the entire process and loading that takes way too long.

**Comment by comfyanonymous** [comment]
Can you post the full log?

**Comment by zhangfeng0800** [comment]
I have the same question , very slowly in the first time use flux model

**Comment by TobiTomatoe** [comment]
I will post the full log later today, but there is nothing much to it tho. I did this with a simple flux workflow without any custom nodes and tested it on a fresh install of the portable version. Same issue. Slow loading and comfyUI takes like 10-15 minutes until the sampler starts even working. It is just stalling for a very long time before anything happens.

**Comment by ltdrdata** [comment]
> I will post the full log later today, but there is nothing much to it tho. I did this with a simple flux workflow without any custom nodes and tested it on a fresh install of the portable version. Same issue. Slow loading and comfyUI takes like 10-15 minutes until the sampler starts even working. It is just stalling for a very long time before anything happens.

Please check if you are using shared VRAM.

**Comment by TobiTomatoe** [comment]
> > I will post the full log later today, but there is nothing much to it tho. I did this with a simple flux workflow without any custom nodes and tested it on a fresh install of the portable version. Same issue. Slow loading and comfyUI takes like 10-15 minutes until the sampler starts even working. It is just stalling for a very long time before anything happens.
> 
> Please check if you are using shared VRAM.

Shared VRAM? I never changed anything to this option. How would I check to know if this was enabled? Also, I don't know if this might be important but I checked other models, like sdxl and ran some of my complex workflows with ipAdapters and multiple controlnet without issues. This happens only with flux, even on the simplest workflow.

**Comment by ltdrdata** [comment]
> > > I will post the full log later today, but there is nothing much to it tho. I did this with a simple flux workflow without any custom nodes and tested it on a fresh install of the portable version. Same issue. Slow loading and comfyUI takes like 10-15 minutes until the sampler starts even working. It is just stalling for a very long time before anything happens.
> > 
> > 
> > Please check if you are using shared VRAM.
> 
> Shared VRAM? I never changed anything to this option. How would I check to know if this was enabled? Also, I don't know if this might be important but I checked other models, like sdxl and ran some of my complex workflows with ipAdapters and multiple controlnet without issues. This happens only with flux, even on the simplest workflow.
> 
> Edit: I changed Cuda - system fallback policy to "Prefer no system fallback" if it is that what you meant, but it didn't fix anything. The issue feels like a memory leak or something, but I have no idea. All i can tell is that the problem isn't normal at all. The lag remains somewhat on the system even when I close comfyUI.

The symptoms you're describing seem to be caused by a lack of RAM, leading to swapping.  
Try monitoring your memory usage in **Task Manager** to check if this is the case.

**Comment by TobiTomatoe** [comment]
> > > > I will post the full log later today, but there is nothing much to it tho. I did this with a simple flux workflow without any custom nodes and tested it on a fresh install of the portable version. Same issue. Slow loading and comfyUI takes like 10-15 minutes until the sampler starts even working. It is just stalling for a very long time before anything happens.
> > > 
> > > 
> > > Please check if you are using shared VRAM.
> > 
> > 
> > Shared VRAM? I never changed anything to this option. How would I check to know if this was enabled? Also, I don't know if this might be important but I checked other models, like sdxl and ran some of my complex workflows with ipAdapters and multiple controlnet without issues. This happens only with flux, even on the simplest workflow.
> > Edit: I changed Cuda - system fallback policy to "Prefer no system fallback" if it is that what you meant, but it didn't fix anything. The issue feels like a memory leak or something, but I have no idea. All i can tell is that the problem isn't normal at all. The lag remains somewhat on the system even when I close comfyUI.
> 
> The symptoms you're describing seem to be caused by a lack of RAM, leading to swapping. Try monitoring your memory usage in **Task Manager** to check if this is the case.

Hey, Thanks for answering again. I observe cpu and ram usage in task manager regularly (I'm actually kinda obsessed due to my OCD) and nothing has changed, as far as I can tell. The only thing I can say so far is that flux worked pretty well a few days ago. Yes, my OS had hickups during the loading process of the model but once that was done, the workflow ran like a charm. Now it doesn't and I have no idea what has changed.

**Comment by PyrateGFXProductions** [comment]
> > > > I will post the full log later today, but there is nothing much to it tho. I did this with a simple flux workflow without any custom nodes and tested it on a fresh install of the portable version. Same issue. Slow loading and comfyUI takes like 10-15 minutes until the sampler starts even working. It is just stalling for a very long time before anything happens.
> > > 
> > > 
> > > Please check if you are using shared VRAM.
> > 
> > 
> > Shared VRAM? I never changed anything to this option. How would I check to know if this was enabled? Also, I don't know if this might be important but I checked other models, like sdxl and ran some of my complex workflows with ipAdapters and multiple controlnet without issues. This happens only with flux, even on the simplest workflow.
> > Edit: I changed Cuda - system fallback policy to "Prefer no system fallback" if it is that what you meant, but it didn't fix anything. The issue feels like a memory leak or something, but I have no idea. All i can tell is that the problem isn't normal at all. The lag remains somewhat on the system even when I close comfyUI.
> 
> The symptoms you're describing seem to be caused by a lack of RAM, leading to swapping. Try monitoring your memory usage in **Task Manager** to check if this is the case.

I too am using a windows portable install and I am having similar issues. I have 64gb ram 12gb vram and 128gb disk cache. I think there is more to this Flux memory issue than meets the eye. The real bog down in my work flow is when it gets to the Ksampler. It has taken 51 minutes just to start the process.
![image](https://github.com/user-attachments/assets/2e2a1ec9-0fdd-4a15-a1f0-ba1843009a53)
