### ISSUE TITLE
Unable to save node title

### ISSUE THREAD

**Issue by thinkluck** [comfyanonymous/ComfyUI#6009]
### Expected Behavior

![屏幕截图 2024-12-11 145618](https://github.com/user-attachments/assets/fd2d0c2d-6b73-46c6-b05a-45c6b1fad6ac)
I hope that after changing the node title, it will be saved successfully and will not be automatically restored

### Actual Behavior

When I try to change the node's title, the change is successful, and then I switch to another workflow, and then switch back, the title will be restored

### Steps to Reproduce

https://github.com/user-attachments/assets/7e3b9f25-5cef-4f8a-9c50-3c5cb2f63229

### Debug Logs

```powershell
components-manager.js:769 Empty components: policy ignored
ttNinterface.js:269  Uncaught TypeError: node.onResize is not a function
    at ttNinterface.js:269:22
```

**Comment by huchenlei** [comment]
Try disable https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation

BTW we should have official translation up in frontend 1.5.x
