### ISSUE TITLE
Request for ComfyUI support for Hunyuan Video

### ISSUE THREAD

**Issue by foreverpiano** [comfyanonymous/ComfyUI#6025]
### Feature Idea

HuanyuanVideo new SOTA video generation diffusion.

**Comment by foreverpiano** [comment]
cc @ltdrdata @comfyanonymous @ComfyUI-Community

**Comment by LukeG89** [comment]
There is a wrapper custom node created by @kijai: [ComfyUI-HunyuanVideoWrapper](https://github.com/kijai/ComfyUI-HunyuanVideoWrapper)

**Comment by foreverpiano** [comment]
looks good to me. I close this.
