### ISSUE TITLE
Load IPAdapter Flux Model Cannot load clip-vision mod

### ISSUE THREAD

**Issue by F-shift** [comfyanonymous/ComfyUI#6036]
<img width="2015" alt="微信图片_20241213193037" src="https://github.com/user-attachments/assets/ee10c0a9-4b48-46c8-b6ac-b94003145117" />
(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /google/siglip-so400m-patch14-384/resolve/main/config.json (Caused by SSLError(CertificateError("hostname \'huggingface.co\' doesn\'t match either of \'*.facebook.com\', \'*.facebook.net\', \'*.fbcdn.net\', \'*.fbsbx.com\', \'*.m.facebook.com\', \'*.messenger.com\', \'*.xx.fbcdn.net\', \'*.xy.fbcdn.net\', \'*.xz.fbcdn.net\', \'facebook.com\', \'messenger.com\'")))'), '(Request ID: ae919070-25c1-44ce-810e-b7c12c1ddb44)')
![image](https://github.com/user-attachments/assets/901365df-4073-4e76-a8ac-e88267d28884)

**Comment by LukeG89** [comment]
It's not a ComfyUI issue, you need to open a bug report here: https://github.com/Shakker-Labs/ComfyUI-IPAdapter-Flux
