### ISSUE TITLE
Incompatible with specific SD 1.5 model?

### ISSUE THREAD

**Issue by rular099** [comfyanonymous/ComfyUI#604]
When I tried to reproduce example images of the [OldFish model](https://civitai.com/models/14978/old-fish), I got this:
![workflow](https://user-images.githubusercontent.com/24962277/235651259-e8388f4c-3e0f-4426-887a-9630017191e8.svg)

It supposed to be a female nurse.

 I don't know what is the causation of this problem, but I can successfully generate an image of a female nurse by switching to AUTOMATIC1111's webui without changing anything else.

My ComfyUI is up to date till writing this post.

**Comment by morphles** [comment]
You will not reproduce A11 images. As text/token handling is different in comfyUI. There are some custom nodes that make it more similar, but I think it will still not be exact. In particular weighting is handled differently in comfy, So you should try editing prompt. Almost no weight should exceed 1.3, as that  tends to start breaking stuff in most cases.

**Comment by rular099** [comment]
> You will not reproduce A11 images. As text/token handling is different in comfyUI. There are some custom nodes that make it more similar, but I think it will still not be exact. In particular weighting is handled differently in comfy, So you should try editing prompt. Almost no weight should exceed 1.3, as that tends to start breaking stuff in most cases.

Thanks for your reply. 

Yes, I understand that A11 and ComfyUI may produce different images. The problem is when I use the [OldFish model](https://civitai.com/models/14978/old-fish) in ComfyUI, I always get semi-regular color patterns instead of meaningful images, no matter what prompt used. I also tried not specifying weight manually on any prompt (it should be all default to 1,right?), the result didn't change much. After switching to A11, it behaves as expected.

Here is an example basically the same as in the main post, but with all parenthesis/bracket in prompts removed.
![workflow (1)](https://user-images.githubusercontent.com/24962277/235818138-37f660b2-6548-43d9-b2c3-d4aa20f9d0cc.svg)

**Comment by comfyanonymous** [comment]
See entry number 2 in the FAQ: https://comfyanonymous.github.io/ComfyUI_examples/faq/#why-do-i-get-incoherent-images-with-some-checkpoints-that-are-less-than-19gb

**Comment by rular099** [comment]
> See entry number 2 in the FAQ: https://comfyanonymous.github.io/ComfyUI_examples/faq/#why-do-i-get-incoherent-images-with-some-checkpoints-that-are-less-than-19gb

It solves the problem. Thanks!

Sorry for asking something already listed in the FAQ.
