### ISSUE TITLE
Image slot labels are not loaded from json

### ISSUE THREAD

**Issue by karl-von-knecht** [comfyanonymous/ComfyUI#6054]
### Expected Behavior

When I do the following:
1. Create new workflow
2. Add a node "Upscale image"
3. rename the input slot "image" to "test"
4. Save Workflow
5. Close Workflow
6. Load Workflow

then I should see:
an "Upscale Image" node with an input slot labeled "test"

![image](https://github.com/user-attachments/assets/19c0e114-2092-4cb8-97bf-59b0711dfb65)

### Actual Behavior

Actual behaviour:
I see an "Upscale Image" node with an input slot labeled "image"

![image](https://github.com/user-attachments/assets/9e673d6e-b046-45a0-bd34-da55104e6606)

### Steps to Reproduce

1. Create new workflow
2. Add a node "Upscale image"
3. rename the input slot "image" to "test"
4. Save Workflow
5. Close Workflow
6. Load Workflow

### Debug Logs

```powershell
Additional notes: 
- this bug breaks workflows that use "Anything Everywhere" nodes because these rely on correct labeling
- the bug seems to affect only slots of type image. Slot labels of other types are preserved as expected.
```

**Comment by LukeG89** [comment]
There was an issue about that in the frontend repo:
- https://github.com/Comfy-Org/ComfyUI_frontend/issues/1899

The problem should be solved in the next release (when this PR will be merged):
- https://github.com/comfyanonymous/ComfyUI/pull/6048
