### ISSUE TITLE
ReduxAdvanced The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

### ISSUE THREAD

**Issue by jonnytracker** [comfyanonymous/ComfyUI#6058]
### Expected Behavior

picture

### Actual Behavior

ReduxAdvanced
The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

### Steps to Reproduce

just use human segmentation node with redux

### Debug Logs

```powershell
sorry
```

### Other

ReduxAdvanced
The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI_AdvancedRefluxControl repo.
https://github.com/kaibioinfo/ComfyUI_AdvancedRefluxControl
