### ISSUE TITLE
ExecutionBlocker is not properly handled for nodes with INPUT_IS_LIST = True

### ISSUE THREAD

**Issue by asaddi** [comfyanonymous/ComfyUI#6059]
### Expected Behavior

When a node with `INPUT_IS_LIST = True` is about to receive an `ExecutionBlocker` from upstream, it should not execute.

### Actual Behavior

When a node with `INPUT_IS_LIST = True` (such as "Rebatch Images") receives an `ExecutionBlocker`, it actually executes. Since the `ExecutionBlocker` is not an expected input (an image, in this case), it errors out.

![image](https://github.com/user-attachments/assets/1801ad67-d04e-4f21-a845-ae32bbff7e9e)

I guess it can be argued that this bug is more cosmetic than anything (unexpected error message), since downstream nodes aren't supposed to execute anyway.

### Steps to Reproduce

Unfortunately, there aren't any Core nodes that I'm aware of that conditionally return an `ExecutionBlocker`. (But a simple custom node can be easily created.)

And then connect it to a node with `INPUT_IS_LIST = True`, such as "Rebatch Images" or "Rebatch Latents"

### Debug Logs

```powershell
!!! Exception during processing !!! 'ExecutionBlocker' object has no attribute 'shape'
Traceback (most recent call last):
  File "C:\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\execution.py", line 164, in _map_node_over_list
    process_inputs(input_data_all, 0)
  File "C:\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\comfy_extras\nodes_rebatch.py", line 122, in rebatch
    for i in range(img.shape[0]):
                   ^^^^^^^^^
AttributeError: 'ExecutionBlocker' object has no attribute 'shape'

Prompt executed in 2.51 seconds
```

### Other

The issue is around line 153 of execution.py:

        execution_block = None
        for k, v in inputs.items():
            if isinstance(v, ExecutionBlocker):
                execution_block = execution_block_cb(v) if execution_block_cb else v
                break

When `INPUT_IS_LIST = True`, `v` can only be a list. So the `isinstance` check is never true.

**Comment by comfyanonymous** [comment]
Does this fix it? https://github.com/comfyanonymous/ComfyUI/commit/6d1a3f7d00d92b652b986ef69b4337ea0f208a1a

**Comment by asaddi** [comment]
That fixes it. Thanks!
