### ISSUE TITLE
TypeError: Object of type set is not JSON serializable

### ISSUE THREAD

**Issue by neverbiasu** [comfyanonymous/ComfyUI#6074]
### Expected Behavior

Web interface should be opened correctly.

### Actual Behavior

![image](https://github.com/user-attachments/assets/209b4d47-0fcf-4e1e-a731-ea12ca1f2fd4)
Web interface is always loading.

### Steps to Reproduce

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\quick-connections
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\style_aligned_comfy
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-NodeAligner
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ControlNet-LLLite-ComfyUI
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\FreeU_Advanced
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-ImageCaptioner
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-InstantStyle
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\PowerNoiseSuite
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\comfy_pixelization
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds (IMPORT FAILED): D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_experiments
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\comfyui-workspace-manager
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds (IMPORT FAILED): D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-LayerDivider
   0.1 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-SEED-Story
   0.1 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Dashscope
   0.1 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\PuLID_ComfyUI
   0.1 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-InstantID
   0.2 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\EchoMimicV2-ComfyUI
   0.6 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager
   0.8 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack
   0.8 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet
   1.2 seconds (IMPORT FAILED): D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IF_AI_tools
   1.5 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\comfyui-mixlab-nodes
   2.8 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
   4.6 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\was-node-suite-comfyui
   4.7 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GPT_SoVITS
   5.6 seconds: D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Crystools
   ''' I just install ComfyUI-GPT_SoVITS、 ComfyUI-IF_AI_tools and EchoMimicV2-ComfyUI. Then it occurs.

### Debug Logs

```powershell
Error handling request
Traceback (most recent call last):
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "<enhanced_experience vendors.sentry_sdk.integrations.aiohttp>", line 140, in sentry_app_handle
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1649, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.aiohttp>", line 130, in sentry_app_handle
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\server.py", line 62, in cache_control
    response: web.Response = await handler(request)
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\server.py", line 140, in origin_only_middleware
    response = await handler(request)
  File "<enhanced_experience patches.comfyui.html_resources_patcher>", line 26, in http_resource_injector
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\server.py", line 74, in cors_middleware
    response = await handler(request)
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\server.py", line 567, in get_object_info
    return web.json_response(out)
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\web_response.py", line 811, in json_response
    text = dumps(data)
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\ComfyUI-aki\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
```

**Comment by ltdrdata** [comment]
Remove the newly installed custom nodes and test again.

**Comment by neverbiasu** [comment]
I found it caused by a syntax err in my newly custom nodes:
```
"qwen_long": (["qwen_long"], {"default"**,** "qwen_long"}),
```
After I correct it, ComfyUI start as expected.
