### ISSUE TITLE
How to add a LORA?

### ISSUE THREAD

**Issue by Diegolzgz** [comfyanonymous/ComfyUI#6087]
### Feature Idea

Should these be the new node connections?

![Captura de pantalla 2024-12-17 164759](https://github.com/user-attachments/assets/dd213c62-0c2b-4631-a25f-769476b3aa70)

**Comment by LukeG89** [comment]
You have to connect it this way:

![image](https://github.com/user-attachments/assets/7b4c21f2-7f93-44ea-9561-fa14565d6eb8)

**Comment by Diegolzgz** [comment]
> You have to connect it this way:
> 
> ![image](https://private-user-images.githubusercontent.com/161304036/396574970-7b4c21f2-7f93-44ea-9561-fa14565d6eb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjQ2MzAsIm5iZiI6MTczNDQ2NDMzMCwicGF0aCI6Ii8xNjEzMDQwMzYvMzk2NTc0OTcwLTdiNGMyMWYyLTdmOTMtNDRlYS05NTYxLWZhMTQ1NjVkNmViOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxOTM4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGY2MjA5ODgzNzYwMDRlNGJlYzJjZWJkZTAxZjcyOTNlODRmZDBjY2E5N2YzMmY2MDg2MDQ0NmRlNGY3ZjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YIznWSNET15DfIFZfbwMn4Df5VMWe3TI-ATaP8HwVRM)

Thanks, working!
