### ISSUE TITLE
KSampler mixed dtype (CPU): expect parameter to have scalar type of Float

### ISSUE THREAD

**Issue by neipr3s** [comfyanonymous/ComfyUI#6091]
### Your question

Hello why am I getting this error from the K Sampler, it alternates between this and 'mat1 and mat2 must have same dtype, but float and bfloat16'

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 7
- **Node Type:** KSampler
- **Exception Type:** RuntimeError
- **Exception Message:** mixed dtype (CPU): expect parameter to have scalar type of Float
## Stack Trace
`
```

**Comment by LukeG89** [comment]
is your ComfyUI and all custom nodes updated?
Especially AnimateDiff Evolved, since you are using it: https://github.com/comfyanonymous/ComfyUI/discussions/6092

**Comment by neipr3s** [comment]
Hey Luke, yes they are. I’m reinstalling python now, maybe this helps. Will
keep you posted

**Comment by LukeG89** [comment]
In case you get the same errors, you should open a bug report in [ComfyUI-AnimateDiff-Evolved](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved)

**Comment by neipr3s** [comment]
Have done, thanks!
