### ISSUE TITLE
ComfyUI 桌面版上报错图片大小问题

### ISSUE THREAD

**Issue by rianwg** [comfyanonymous/ComfyUI#6095]
### Expected Behavior

[
![微信图片_20241218111511](https://github.com/user-attachments/assets/a4feb5b5-91fe-48bc-b50e-fe37ab379fae)
](url)

### Actual Behavior

各种调整都是这个报错的，用的是
ComfyUI: v0.3.2
         (2024-11-22)
Manager: V2.55.5

### Steps to Reproduce

1

### Debug Logs

```powershell
1
```

### Other

1

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI_AdvancedRefluxControl repo.
https://github.com/kaibioinfo/ComfyUI_AdvancedRefluxControl
