### ISSUE TITLE
DualCLIPLoader doesn't see the gguf clip models anymore, t5-v1_1-xxl-encoder-Q8_0.gguf

### ISSUE THREAD

**Issue by deceani** [comfyanonymous/ComfyUI#6098]
### Expected Behavior

It should show the t5-v1_1-xxl-encoder-Q8_0.gguf in the DualCLIPLoader
![image](https://github.com/user-attachments/assets/827c50e2-aa4f-4d40-8d67-f2cfd38d918c)

### Actual Behavior

It doesnt show the t5-v1_1-xxl-encoder-Q8_0.gguf in the DualCLIPLoader 
![image](https://github.com/user-attachments/assets/b349f0ed-c0eb-4292-bdf7-47102cfb143c)
![image](https://github.com/user-attachments/assets/ef8e7a9c-3bfc-4483-81aa-657431a29939)

### Steps to Reproduce

Add a DualCLIPLoader and try to find or select the DualCLIPLoader

### Debug Logs

```powershell
I don't have a debug log since I can not add the model and run it
```

### Other

I first thought that is because the the warning error of possible conflict with the gguf node since both have dualclip loader now
![image](https://github.com/user-attachments/assets/e8f46782-0a10-44a1-b307-a2adf9473b3e)
so the gguf node it actually shows that model but the comfyui one doesnt. 
![image](https://github.com/user-attachments/assets/420739ce-b47c-47cb-8b6c-59434c5b3ff2)
So i uninstalled the gguf to check if now I can see the t5-v1_1-xxl-encoder-Q8_0.gguf but I still can not see it.

**Comment by ltdrdata** [comment]
The core nodes of ComfyUI have never supported the `.gguf` format.  
The `gguf` format is only supported by custom nodes in `ComfyUI-GGUF`.

**Comment by QkiZMR** [comment]
I had the same problem. Resolved it by updating `ComfyUI-GGUF` node.
