### ISSUE TITLE
Ability to swap old nodes and maintain  as many connections as possible

### ISSUE THREAD

**Issue by prezofpizza** [comfyanonymous/ComfyUI#6104]
### Feature Idea

The ability to swap an old node out for a new one while maintaining connections would make upgrading/enhancing workflows much easier.

Example: CogVideoX node from Kijai had an update that deprecated the sampler node.  Swapping it out for the new one took a long while.  A hot swap would be really great.

**Comment by LukeG89** [comment]
As an alternative, you can use the copy connections feature from the Manager. It's "conflicting" with the double-click to rename feature, but it works anyways.


https://github.com/user-attachments/assets/1dd6da17-c16a-4723-bbd5-e4ebea10112e

**Comment by prezofpizza** [comment]
Oh my god you're amazing. Thank you!

**Comment by nathanshipley** [comment]
Just adding a comment here because I landed here from a Google search: this swap functionality has now been moved to it's own custom node.

As per @LukeG89 :

> Double-click to copy connection has been removed from ComfyUI-Manager, now it's a custom node: 
 https://github.com/ltdrdata/comfyui-connection-helper
