### ISSUE TITLE
Cache System management on Windows

### ISSUE THREAD

**Issue by adydeejay** [comfyanonymous/ComfyUI#6109]
### Your question

I am currently optimizing storage on my SSDs, particularly the one dedicated to the Windows operating system.

![image](https://github.com/user-attachments/assets/2116f3e5-52d1-4873-bd6c-3c03928b3a4c)

Thus far, I have successfully relocated the pip cache folder (~44GB) by configuring the PIP_CACHE_DIR environment variable. However, I am uncertain about the procedure for relocating the cache folder associated with HuggingFace, which occupies approximately 30GB.

![image](https://github.com/user-attachments/assets/80b26025-8ca0-4196-850f-bfbb2006380f)

Additionally, I am interested in understanding whether the HuggingFace cache can be optimized (e.g., through cleanup) and, if so, what the recommended process would be for this task.

I would greatly appreciate any guidance or recommendations on how to achieve this. Thank you in advance!

**Comment by ltdrdata** [comment]
You need to use `HF_HOME` environment variable.

**Comment by adydeejay** [comment]
Thank you!
