### ISSUE TITLE
stylemodelapply_mat1 and mat2 shapes cannot be multiplied (257X1280 and 1152X12288)

### ISSUE THREAD

**Issue by ryujongsu** [comfyanonymous/ComfyUI#6128]
### Expected Behavior

**stylemodelapply mat1 and mat2 shapes cannot be multiplied (257X1280 and 1152X12288)**

Hi, I was working through inpainting using flux1. fill and redux to replace the underwear model's outfit. I'm currently experiencing an error.

### Actual Behavior

![스크린샷 2024-12-20 113611](https://github.com/user-attachments/assets/3d6fb754-14c1-4813-bb9b-af2955c5508f)
![스크린샷 2024-12-20 113543](https://github.com/user-attachments/assets/0f900b3a-78a2-436c-8749-57bc95a9c78d)
An error occurs in the ApplyStyleModel.

### Steps to Reproduce

[1220 change fashion.json](https://github.com/user-attachments/files/18205413/1220.change.fashion.json)

### Debug Logs

```powershell
Prompt executed in 0.02 seconds
got prompt
!!! Exception during processing !!! mat1 and mat2 shapes cannot be multiplied (257x1280 and 1152x12288)
Traceback (most recent call last):
  File "C:\comfyuibudle\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyuibudle\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyuibudle\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\comfyuibudle\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyuibudle\ComfyUI\nodes.py", line 1022, in apply_stylemodel
    cond = style_model.get_cond(clip_vision_output).flatten(start_dim=0, end_dim=1).unsqueeze(dim=0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyuibudle\ComfyUI\comfy\sd.py", line 575, in get_cond
    return self.model(input.last_hidden_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyuibudle\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyuibudle\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyuibudle\ComfyUI\comfy\ldm\flux\redux.py", line 24, in forward
    projected_x = self.redux_down(torch.nn.functional.silu(self.redux_up(sigclip_embeds)))
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyuibudle\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyuibudle\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyuibudle\ComfyUI\comfy\ops.py", line 68, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyuibudle\ComfyUI\comfy\ops.py", line 64, in forward_comfy_cast_weights
    return torch.nn.functional.linear(input, weight, bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (257x1280 and 1152x12288)

Prompt executed in 0.02 seconds
```

**Comment by PyrateGFXProductions** [comment]
maybe change the Clip_Vision model? This is the one I use and is also the one recommended by ComfyUI Wiki

![image](https://github.com/user-attachments/assets/66785cba-c85f-49bc-a5cb-12f223e5e7a1)
![image](https://github.com/user-attachments/assets/9aecdca3-f626-45eb-9f52-d845312a0e9c)
https://comfyui-wiki.com/en/tutorial/advanced/flux-redux-workflow-step-by-step-guide

**Comment by ryujongsu** [comment]
Oh! Thank you very much. There are a lot of things I don't know because I'm still a beginner, but it was solved well because you answered kindly

**Comment by Raygens** [comment]
> maybe change the Clip_Vision model? This is the one I use and is also the one recommended by ComfyUI Wiki
> 
> ![image](https://private-user-images.githubusercontent.com/25160380/397606813-66785cba-c85f-49bc-a5cb-12f223e5e7a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzE5OTUsIm5iZiI6MTczNTUzMTY5NSwicGF0aCI6Ii8yNTE2MDM4MC8zOTc2MDY4MTMtNjY3ODVjYmEtYzg1Zi00OWJjLWE1Y2ItMTJmMjIzZTVlN2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA0MDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOTIwYmYzMDNjYzkxNWM1OGU1NTRjYWYzZTU0OGRjYTZjNjJlMmViZDU1ZDg1YzlkYzAxYTkyNjM5ZjhlMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D_xy0WfFdyjuOz1tqg7bBPKlUdHGzHIJSlqnzW54myY) ![image](https://private-user-images.githubusercontent.com/25160380/397607199-9aecdca3-f626-45eb-9f52-d845312a0e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzE5OTUsIm5iZiI6MTczNTUzMTY5NSwicGF0aCI6Ii8yNTE2MDM4MC8zOTc2MDcxOTktOWFlY2RjYTMtZjYyNi00NWViLTlmNTItZDg0NTMxMmEwZTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA0MDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NTc0YjI2OTVlZjYxMTY4OGViZmE0YWViZjM2ODdkODFkMTExNzMzZTY5NTIzMTI2ZDgyYzdhZjljNThiYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-lIXxeSiI9R27xqEYArLFZIBYeYDZRxGhuP9H2AjkEY) https://comfyui-wiki.com/en/tutorial/advanced/flux-redux-workflow-step-by-step-guide
Thanks a lot!Change the models is operating!

**Comment by joeson331** [comment]
Encountered the same question, thanks for the answer.
