### ISSUE TITLE
[WinError 3] 系统找不到指定的路径。: '/tmp/ultralytics_runner'

### ISSUE THREAD

**Issue by michael180831** [comfyanonymous/ComfyUI#6134]
when running Expression Editor (PHM) of Advanced LivePortrait nodes show the error as title. Are there any bro know how to solve it? 
![image](https://github.com/user-attachments/assets/18c4855d-7970-4d11-86bb-1ba1ca49d038)
![image](https://github.com/user-attachments/assets/e8eaf1d7-4e60-47c6-b718-6b8acd8635a5)

**Comment by ltdrdata** [comment]
Your ultralytics is compromised version.
https://blog.comfy.org/comfyui-statement-on-the-ultralytics-crypto-miner-situation/

Execute this command in cmd
```
F:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python -m  pip uninstall ultralytics
F:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python -m  pip install ultralytics==8.3.40
```
