### ISSUE TITLE
what is this ?

### ISSUE THREAD

**Issue by Chengym2023** [comfyanonymous/ComfyUI#6145]
### Your question

what is this in new version0.3.9
![image](https://github.com/user-attachments/assets/b291a677-36c7-431e-a27e-f4c5fc28729d)

**Comment by LukeG89** [comment]
Do you mean workflow tabs or the plus button? The plus button is just to create a new empty workflow.

Now worflow tabs are enabled by default, but you can select `sidebar` in "Opened workflows position" option
![image](https://github.com/user-attachments/assets/33d1d07a-be81-47fe-bb9c-2668b7684d0b)

**Comment by Chengym2023** [comment]
> `sidebar` in "Opened workflows position" option

tks,got it
