### ISSUE TITLE
Group all Pending items from the queue

### ISSUE THREAD

**Issue by andreszs** [comfyanonymous/ComfyUI#6147]
### Feature Idea

Currently, whenever the user adds a long batch to the queue, it becomes really difficult to browser the previously generated images from the queue, because it becomes populated with all the "**Pending**" items. It would be better to  group all pending items in a single item, to allow easy browsing of the previous images. You could use the badge counter that is shown in some cases, as the counter of Pending items.

### Existing Solutions

None that I know

### Other

![image](https://github.com/user-attachments/assets/d22cfcf2-4f9d-4cf5-89a2-ca089e1e59b4)

**Comment by LukeG89** [comment]
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/2000
