### ISSUE TITLE
display text in prompt queue

### ISSUE THREAD

**Issue by drmbt** [comfyanonymous/ComfyUI#6148]
### Feature Idea

it would be really helpful if printed text / strings showed up in the prompt queue alongside images, it would make iteration much simpler if one could see the results of a prompt or setting displayed this way in your queue history

![image](https://github.com/user-attachments/assets/d8807c93-db5d-47af-90b2-696ff8f990d1)

**Comment by LukeG89** [comment]
Open this feature request here: https://github.com/Comfy-Org/ComfyUI_frontend
