### ISSUE TITLE
The gallery jumps up every time an image finishes

### ISSUE THREAD

**Issue by oxysoft** [comfyanonymous/ComfyUI#6149]
### Expected Behavior

The gallery should not scroll up to the top.

### Actual Behavior

The gallery scrolls to the top every time.

### Steps to Reproduce

1. Execute the workflow several times.
2. Scroll down in the gallery to browse some images.
3. Execute the workflow.
4. Upon completion, the gallery scrolls to the top.

### Debug Logs

```powershell
Unnecessary
```

**Comment by andreszs** [comment]
And the currently opened image is changed whenever a new image is generated which shouldn't happen either. Unless some "auto show last generated image" is specifically enabled somewhere.

**Comment by LukeG89** [comment]
@oxysoft @andreszs  For bug reports/feature requests related to the frontend, you should refer to the official frontend repository: [ComfyUI_frontend](https://github.com/Comfy-Org/ComfyUI_frontend)
