### ISSUE TITLE
VHS_LoadVideo  module 'cv2' has no attribute 'VideoCapture'

### ISSUE THREAD

**Issue by nnppmm** [comfyanonymous/ComfyUI#6156]
### Your question

# ComfyUI Error Report
## Error Details
- **Node Type:** VHS_LoadVideo
- **Exception Type:** AttributeError
- **Exception Message:** module 'cv2' has no attribute 'VideoCapture'

**Comment by LukeG89** [comment]
Check this:
- https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/issues/298
