### ISSUE TITLE
Allow removing reroutes with Alt + right click

### ISSUE THREAD

**Issue by pkrasicki** [comfyanonymous/ComfyUI#6161]
### Feature Idea

Adding reroutes with `Alt + left mouse button` is very convenient. But it should be just as convenient to remove them. A good hotkey for this might be `Alt + right mouse button`.

**Comment by LukeG89** [comment]
You have to open this feature request in this repo (since it's about beta reroutes): https://github.com/Comfy-Org/litegraph.js

**Comment by pkrasicki** [comment]
@LukeG89 Thanks for letting me know! The new issue is: https://github.com/Comfy-Org/litegraph.js/issues/386
