### ISSUE TITLE
Dont Find Model in Load Diffusion Model FLUX

### ISSUE THREAD

**Issue by EdwardFate** [comfyanonymous/ComfyUI#6165]
### Your question

Node Load Diffusion Model dont find "flux1-schnell.safetensors", but finded files "flux1-dev-Q8_0.gguf".
The documentation for Flux says that the model file should be located at the following path ".../model/unet"
Workflow is basic example. Checkpoint workflow is working. 
![Monosnap _Flux-Schnell-ComfyUI-Workflow - ComfyUI ](https://github.com/user-attachments/assets/dd7357e8-6145-4c2c-9599-42d3f25d8eaa)

**Comment by LukeG89** [comment]
Try disabling all your nodes with `--disable-all-custom-nodes` argument, to see if this problem is caused by a custom node.
Other people are having this problem. For example, one culprit was ComfyUI-Flow-Control (see this [issue](https://github.com/krich-cto/ComfyUI-Flow-Control/issues/1)). Maybe other nodes are causing this same issue.

**Comment by EdwardFate** [comment]
Disabled custom nodes, everything worked. Thank you very much

**Comment by andriken** [comment]
for me it doesn't work at all, I tried setting that command but for me it doesn't shows gguf models only safetensors

**Comment by ltdrdata** [comment]
> for me it doesn't work at all, I tried setting that command but for me it doesn't shows gguf models only safetensors

The .gguf model is only supported in custom nodes and is not supported in the core. It cannot be loaded through the `Load Diffusion Model`.

https://github.com/city96/ComfyUI-GGUF

**Comment by user6927** [comment]
Same problem for newly installed portable version (no custom nodes except the ComfyUI Manager).

**Comment by tensae-b** [comment]
i disabled all custom nodes but it still didn't work for me. what worked was i edited the  extra_model_paths.yaml file and  added  `diffusion_models: /diffusion_models/` to let the load diffusion node locate the models only in that folder. also you don't need to disable all custom nodes just ones related  to gguf
