### ISSUE TITLE
[Feature]: Slowing down generation

### ISSUE THREAD

**Issue by pkrasicki** [comfyanonymous/ComfyUI#6166]
### Feature Idea

I would like to be able to artificially slow down generation by some amount. In my case the reason is that my GPU can get very loud and I would like to be able to generate at night without making too much noise, even if it's slower. For other people the reason might be keeping the temperatures lower.

It doesn't have to be a setting in the UI, it can just be a command line parameter.

**Comment by ltdrdata** [comment]
You are experiencing overheating.
In that case, you can utilize ComfyUI-GPU-temperature-protection  custom node.

https://github.com/meap158/ComfyUI-GPU-temperature-protection

Otherwise, you can use Sleep custom node from Impact Pack.

**Comment by pkrasicki** [comment]
ComfyUI-GPU-temperature-protection only works for Nvidia GPUs.

Can the Sleep node slow down generation of a single image? From the description on GitHub I don't understand how that would help.

**Comment by LukeG89** [comment]
@pkrasicki I don't know if it's possible, but maybe you can "underclock" or lowering the power to the GPU via software (or through BIOS)?

**Comment by pkrasicki** [comment]
@LukeG89 I found this app for GNU/Linux, [CoreCtrl](https://gitlab.com/corectrl/corectrl). It lets me change the power limit, so it solves my problem. Thanks for the suggestion!

**Comment by ltdrdata** [comment]
> ComfyUI-GPU-temperature-protection only works for Nvidia GPUs.
> 
> Can the Sleep node slow down generation of a single image? From the description on GitHub I don't understand how it could do that. I want to be able to use ComfyUI normally, but utilize my GPU at only 75% (for example) instead of 100%.

It is not intended to reduce GPU performance, but rather to apply forced idle time between each workflow execution during long image generation to prevent overheating.
