### ISSUE TITLE
ComfyUI is currently broken with python 3.13

### ISSUE THREAD

**Issue by akagohary** [comfyanonymous/ComfyUI#6169]
### Expected Behavior

for it to work.

### Actual Behavior

errors out with multiple missing modules mainly though 

ModuleNotFoundError: No module named 'torchvision'

### Steps to Reproduce

upgrade python from 3.12 to 3.13

### Debug Logs

```powershell
bash /data1/ComfyUI/sdstartupscript.sh 
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-23 02:08:26.865000
** Platform: Linux
** Python version: 3.13.1 (main, Dec  4 2024, 18:05:56) [GCC 14.2.1 20240910]
** Python executable: /data1/ComfyUI/venv/bin/python
** ComfyUI Path: /data1/ComfyUI
** Log path: /data1/ComfyUI/comfyui.log
[manager-core] Failed to restore PyTorch
'torchvision'

Prestartup times for custom nodes:
   0.0 seconds: /data1/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /data1/ComfyUI/custom_nodes/ComfyUI-Stable-Video-Diffusion
   1.2 seconds: /data1/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 11934 MB, total RAM 64215 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Traceback (most recent call last):
  File "/data1/ComfyUI/main.py", line 132, in <module>
    import execution
  File "/data1/ComfyUI/execution.py", line 13, in <module>
    import nodes
  File "/data1/ComfyUI/nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "/data1/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/data1/ComfyUI/comfy/sd.py", line 10, in <module>
    from .ldm.cascade.stage_c_coder import StageC_coder
  File "/data1/ComfyUI/comfy/ldm/cascade/stage_c_coder.py", line 19, in <module>
    import torchvision
ModuleNotFoundError: No module named 'torchvision'
```

### Other

i tried to baby the upgrade process.

i did `python3.13 -m venv upgrade (venv directory)` that went smooth.

tried to startup my comfyui starting script once again it errored out.

tried to do `pip install -r requirments.txt` it erorred out with `ERROR: No matching distribution found for torchvision`, i disabled it by adding # before it in the requirments.txt then there was also problems with `torchaudio` `sentencepiece` `koria` `spandrel` and i also disabled `soundfile` just in case at this point, the other packages in the requirments.txt did update to py313 variations.

yet am still stuck ofc because no `torchvision` .

https://github.com/pytorch/vision/issues/8747 

i don't think there is a workaround other than me downgrading to python 3.12 in the meantime i guess, other than that would be to wait for `torchvision` to upgrade, although `torch` is updated btw, am not python programmer so idk the difference.

Kudos.

**Comment by Archkon** [comment]
Actually, upgrading to python3.13 version is not very compatible for pytorch.Please use the lower version of python.This is not issue with comfyui.

**Comment by akagohary** [comment]
> Actually, upgrading to python3.13 version is not very compatible for pytorch.Please use the lower version of python.This is not issue with comfyui.

i didn't say it was an issue with ComfyUI itself but rather the current status of affairs with python 3.13, if updating python is breaking ComfyUI then i believe its a good thing for users to report it, to mitigate other people from upgrading and or bang their head against the wall when everything is not working when it used to.

**Comment by comfyanonymous** [comment]
Try pytorch nightly.

**Comment by ricperry** [comment]
python 3.13 is the default version with any ubuntu- or fedora- based distribution releasing in 2025 or later. This needs to be fixed. Specifically, I'm running into a problem with sentencepiece, not with pytorch. sentencepiece isn't the responsibility of the ComfyUI team, but depending on a dead/unsupported python package is problematic.

**Comment by huuck** [comment]
Failing to find dependencies for me (i.e. torch). As specified above, python 3.13 seeped into pretty much every distro in 2025.

**Comment by comfyanonymous** [comment]
I have been using ComfyUI with python 3.13 since the beginning of January and it works very well. If you have issues getting sentencepiece installed you need to install cmake and I think clang++ with your distros package manager.

Some custom nodes however might depend on dependencies that are only still available on 3.12

**Comment by akagohary** [comment]
A workaround i've been using since this issue has been closed, i installed [pyenv](https://github.com/pyenv/pyenv) and made ComfyUI's local directory python ver 3.11 not even 3.12 to maximize my options with various scenarios in comfy/addons eco system.

This will ensure that you don't have to downgrade your global python ver and manage a system wide obsolete version, yet be free to use ComfyUI.

I do get the idea of closing the issue since ComfyUI is not responsible of every dependency that the current AI technology workflow you might be using might rely on such as sentencepiece and whatnot, but a heads-up is really needed with the current Python 3.13 situation, not everyone is tech savvy to enter ComfyUI setup domain to begin with let alone troubleshoot all this when they had a working ComfyUI and after a GUI system upgrade of Ubunutu or something you bork evrything.

**Comment by JollySapien** [comment]
My ComfyUI install wont respect the pyenv local 3.11. When I do install the requirements.txt im still getting error and its referencing /usr/lib/python3.13. I do a pyenv versions and can clearly see that its "* 3.11.11 (set by /home/jemf/Downloads/ComfyUI/.python-version)" I went through continued with the install and tried running but obviously that got me no where.

**Comment by Nestorchik** [comment]
ComfyUI currently does not work with python 3.13, not all the packages it requires exist for python version 3.13. Torch for version 3.13 has already been released, but for now we are stuck with the lack of other python packages.

**Comment by JollySapien** [comment]
> ComfyUI currently does not work with python 3.13, not all the packages it requires exist for python version 3.13. Torch for version 3.13 has already been released, but for now we are stuck with the lack of other python packages.

That much I knew through searching. My issue ultimately was not being able to get a virtual python 3.12 environment to work. Ultimately reinstalled Arch and went through the same steps and worked. I hate taking the cowards way out but what are you gonna do. ✌️

**Comment by Nestorchik** [comment]
Example of running "ComfyUI" on Python 3.13 on Windows

Read the article: https://dzen.ru/a/aCj-mpJC5h243HWE

powershell -ExecutionPolicy ByPass -c "irm [https://astral.sh/uv/install.ps1](https://dzen.ru/away?to=https%3A%2F%2Fastral.sh%2Fuv%2Finstall.ps1) | iex"
uv python install 3.13
cd /D c:\
mkdir Test
cd c:\Test
git clone [https://github.com/comfyanonymous/ComfyUI.git](https://dzen.ru/away?to=https%3A%2F%2Fgithub.com%2Fcomfyanonymous%2FComfyUI.git)
git clone [https://github.com/Comfy-Org/ComfyUI-Manager.git](https://dzen.ru/away?to=https%3A%2F%2Fgithub.com%2FComfy-Org%2FComfyUI-Manager.git) c:\Test\ComfyUI\custom_nodes\ComfyUI-Manager
uv venv --python 3.13
uv pip install torch torchvision torchaudio --index-url [https://download.pytorch.org/whl/cu128](https://dzen.ru/away?to=https%3A%2F%2Fdownload.pytorch.org%2Fwhl%2Fcu128)
powershell Invoke-WebRequest -Uri "https://github.com/Nestorchik/Dzen/releases/download/dzen/sentencepiece-0.2.0-cp313-cp313-win_amd64.whl" -OutFile "sentencepiece-0.2.0-cp313-cp313-win_amd64.whl"
uv pip install sentencepiece-0.2.0-cp313-cp313-win_amd64.whl
uv pip install pip
uv pip install numpy==2.2.5
uv pip install -r c:\Test\ComfyUI\requirements.txt
uv run c:\Test\ComfyUI\main.py --windows-standalone-build --front-end-version Comfy-Org/ComfyUI_frontend@latest

**Comment by ltdrdata** [comment]
> Example of running "ComfyUI" on Python 3.13 on Windows
> 
> Read the article: https://dzen.ru/a/aCj-mpJC5h243HWE
> 
> powershell -ExecutionPolicy ByPass -c "irm [https://astral.sh/uv/install.ps1](https://dzen.ru/away?to=https%3A%2F%2Fastral.sh%2Fuv%2Finstall.ps1) | iex" uv python install 3.13 cd /D c: mkdir Test cd c:\Test git clone [https://github.com/comfyanonymous/ComfyUI.git](https://dzen.ru/away?to=https%3A%2F%2Fgithub.com%2Fcomfyanonymous%2FComfyUI.git) git clone [https://github.com/Comfy-Org/ComfyUI-Manager.git](https://dzen.ru/away?to=https%3A%2F%2Fgithub.com%2FComfy-Org%2FComfyUI-Manager.git) c:\Test\ComfyUI\custom_nodes\ComfyUI-Manager uv venv --python 3.13 uv pip install torch torchvision torchaudio --index-url [https://download.pytorch.org/whl/cu128](https://dzen.ru/away?to=https%3A%2F%2Fdownload.pytorch.org%2Fwhl%2Fcu128) powershell Invoke-WebRequest -Uri "https://github.com/Nestorchik/Dzen/releases/download/dzen/sentencepiece-0.2.0-cp313-cp313-win_amd64.whl" -OutFile "sentencepiece-0.2.0-cp313-cp313-win_amd64.whl" uv pip install sentencepiece-0.2.0-cp313-cp313-win_amd64.whl uv pip install pip uv pip install numpy==2.2.5 uv pip install -r c:\Test\ComfyUI\requirements.txt uv run c:\Test\ComfyUI\main.py --windows-standalone-build --front-end-version Comfy-Org/ComfyUI_frontend@latest

https://github.com/comfyanonymous/ComfyUI/discussions/8187#discussioncomment-13186499

**Comment by Nestorchik** [comment]
Look here:

https://github.com/Nestorchik/ComfyUI_Python_3.13_Windows
