### ISSUE TITLE
Bring Back the old code for displaying remaining queue (text), because the new one (images) is not working + I cannot choose to cancel one specific task from the other remaning task

### ISSUE THREAD

**Issue by moreAImore** [comfyanonymous/ComfyUI#6173]
### Expected Behavior

If I have 6 or 10 or 100 remaining tasks, the queue usually does not load quickly, or at least it does not show the remaning tasks to be done in the future , like we had in the past:
Even this button:
![image](https://github.com/user-attachments/assets/5b0c28b5-9ba2-401e-8a96-91886901924e)

Does not let me choose which task to cancel, there is only button that abort all remaining tasks.

### Actual Behavior

![image](https://github.com/user-attachments/assets/0fefe465-3d48-4196-b8eb-95ead52066e8)

As you can see, this seems to only show PAST PREVIOUS done images right?

### Steps to Reproduce

Open comfyUI, run 6 tasks, and only then go open the "queue" menu, you will find nothing:

- You can find nowhere your list or remaining tasks ,so you can select to cancel one particular (for example the 5th next task while keeping the 5 next tasks and 6th to 10th  next tasks
Bring back the ability to see the list of incoming tasks in text form and ability to cancel only few of them instead of aborting all.

### Debug Logs

```powershell
.
```

**Comment by LukeG89** [comment]
You can right-click on the task to delete it

![right-click](https://github.com/user-attachments/assets/627c25e6-598b-4fb0-8080-c3869880e221)


Btw, all frontend-related issues or feature requests need to be opened in the official frontend repo, not here: https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by moreAImore** [comment]
OK for the comfyui frontend tip but: where are you right cliking here? When I have 50 tasks where do I see them? Are you clicking int he 3 points and the square surrounding it?

**Comment by LukeG89** [comment]
> where are you right cliking here? 

Literally anywhere on the "quare" of the task. Just try it
