### ISSUE TITLE
Workflow that can follow different paths and skip some of them.

### ISSUE THREAD

**Issue by Aljnk** [comfyanonymous/ComfyUI#6177]
### Feature Idea

Hi.
I am very interested in the ability to create a workflow that can follow different paths and skip some if they are not needed.

For example, I want to create an image and save it under a fixed name (unique). But tomorrow (or after restart) I want to run this workflow again and work with the already created image, which I created and saved earlier, and not waste time on its creation (upscale, modification, etc.), but just check if this image is in my folder, and if it is, then just load it and work with the loaded image, and the branch that creates the image will not run at all (skip this branch).
But it's important that the script does this by itself (without MUTE or BYPASS).

Example 
![Screenshot_1](https://github.com/user-attachments/assets/840c86a0-7944-49ca-95fd-15825a632c7f)

This will help save a lot of time on complex workflows that need to be improved or modernized. And it can also save resources in case of a break or lack of memory - it will be possible to skip large parts of the scheme if they have already been made and saved (without keeping in memory models that have already worked).

### Existing Solutions

I've been trying for a long time to find out if such a possibility exists, but I couldn't find it. If such a feature is already implemented, where can I find it? Thanks.

**Comment by ltdrdata** [comment]
You can utilize switch nodes.
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/switch.md

**Comment by Aljnk** [comment]
Super! I used another switches (not help) but this one is perfect. Thanks a lot :)
