### ISSUE TITLE
Only the.gguf model can be loaded. Other flux models cannot be loaded. The comfyui version is the latest

### ISSUE THREAD

**Issue by huangjianyi0701** [comfyanonymous/ComfyUI#6179]
### Your question

![704f4959467fb7697de4c08b178945d](https://github.com/user-attachments/assets/d20b2cee-6544-4615-9472-6dc85977c642)
![f92f9070d373918dde9b6bd0b495179](https://github.com/user-attachments/assets/e65b6172-b596-4b7e-8464-b0fa61378abb)
Only the.gguf model can be loaded. Other flux models cannot be loaded. The comfyui version is the latest

**Comment by gabrielhrr** [comment]
![image](https://github.com/user-attachments/assets/ec97ae37-50fc-4832-bbfd-8b869fb334aa)
same here

**Comment by gabrielhrr** [comment]
> ### Your question
> ![704f4959467fb7697de4c08b178945d](https://private-user-images.githubusercontent.com/129131129/398144180-d20b2cee-6544-4615-9472-6dc85977c642.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Nzk0NjMsIm5iZiI6MTczNDk3OTE2MywicGF0aCI6Ii8xMjkxMzExMjkvMzk4MTQ0MTgwLWQyMGIyY2VlLTY1NDQtNDYxNS05NDcyLTZkYzg1OTc3YzY0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxODM5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGFkYTk2NGUwYjNjYjMxNmU3MTA2MzYyNDlhOTIzYzZkYzljM2RkNzlhYjBlMTM5NzRiNTE4NGJkMjkwZWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lsUjhx_r4fg5MBEDDNkltWihyu-F9FgmomJdLZydPyw) ![f92f9070d373918dde9b6bd0b495179](https://private-user-images.githubusercontent.com/129131129/398144198-e65b6172-b596-4b7e-8464-b0fa61378abb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Nzk0NjMsIm5iZiI6MTczNDk3OTE2MywicGF0aCI6Ii8xMjkxMzExMjkvMzk4MTQ0MTk4LWU2NWI2MTcyLWI1OTYtNGI3ZS04NDY0LWIwZmE2MTM3OGFiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxODM5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjBiMGMzNDM4ZjgzYjhiMzc3NDQ0N2U3YzI2MTNiNzg4ZWI1ZjYwMmJiYTY0YzQyNTdlYTVhNDM2YjViZjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Kh32IJ5JlJx9pIpz5CYpNdO5hGUxZoDoPgsXaXmn1vU) Only the.gguf model can be loaded. Other flux models cannot be loaded. The comfyui version is the latest
> 
> ### Logs
> _No response_
> 
> ### Other
> _No response_

I saw this post in Reddit (https://www.reddit.com/r/comfyui/comments/1hikaal/load_diffusion_doesnt_show_other_files_than_gguf/)

Just uninstall or disable the custom node ComfyUI-Flow-Control, them .safetensors come back
![image](https://github.com/user-attachments/assets/4ae4dba2-9c75-46ea-99a4-dddc5278d87e)

![image](https://github.com/user-attachments/assets/8b2fdb65-7fc1-4380-9234-c522df574b4b)

**Comment by huangjianyi0701** [comment]
> ComfyUI-Flow-Control

Thank you for your answer,that was great
