### ISSUE TITLE
Where to find "lahmysteriousSDXL_v330.safetensors" for Efficiency Loader Panel?

### ISSUE THREAD

**Issue by marcospopart** [comfyanonymous/ComfyUI#6187]
Hello, and thank you for the amazing work on this project!

I’m currently learning how to use ComfyUI, and I came across a tutorial that mentions the model lahmysteriousSDXL_v330.safetensors in the context of the Efficiency Loader Panel. The tutorial suggests including it in the ckpt_name line. However, I couldn’t locate this specific .safetensors file or its source.

Here’s the link to the tutorial I’m referring to: https://www.youtube.com/watch?v=BFr2oiO3l1s&t=232s&ab_channel=MonzonMedia

Could you please guide me on where I can find this model or suggest an alternative model that would work similarly with the Efficiency Loader Panel?

Thank you for your time and assistance! I really appreciate the work you’ve done on this project and the community’s support.

Best regards,

Marcospopart

**Comment by LukeG89** [comment]
You can choose any SDXL model you want, you can find plenty of them on [CivitAI](https://civitai.com/models)

About the model you are looking for, here it is: https://civitai.com/models/118441?modelVersionId=144237

You have to place it in `ComfyUI\models\checkpoints`

**Comment by marcospopart** [comment]
Thank you so much for your help and for providing the link! I really appreciate it. 😊

I'll download the model and place it in the ComfyUI\models\checkpoints folder as instructed. It's great to know I can use other SDXL models too—I'll explore the options on CivitAI.

Thanks again for your guidance and for making this learning process smoother! 🙌

Best regards,
Marcos
