### ISSUE TITLE
Hunyuan on 3090 keeps crashing (Reconnecting)

### ISSUE THREAD

**Issue by devingDev** [comfyanonymous/ComfyUI#6188]
### Your question

I am trying to run hunyuan video on my machine 
(Nvidia 3090, 32GB RAM)
but a bit after I click Queue it always seems to crash (no errors in console, just ends) and site says reconnecting.

I'm not sure what I'm doing wrong so please try to help me. Thanks for your efforts!

I tried these workflows:
https://old.reddit.com/r/StableDiffusion/comments/1hj7k7d/demo_of_hunyuan_video_on_a_3090/
https://old.reddit.com/r/StableDiffusion/comments/1hjolue/hunyuan_video_test_on_3090/

[Hunyuan-t2v.json](https://github.com/user-attachments/files/18233248/Hunyuan-t2v.json)
[Hunyan 12GB Workflow.json](https://github.com/user-attachments/files/18233249/Hunyan.12GB.Workflow.json)

### Logs

```powershell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-23 21:44:22.324215
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: C:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\AI\ComfyUI_windows_portable\ComfyUI
** Log path: C:\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.3 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 32612 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch attention
[Prompt Server] web root: C:\AI\ComfyUI_windows_portable\ComfyUI\web
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Revision: 2953 [418eb706] *DETACHED | Released on '2024-12-20'

Import times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.1 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.jsonStarting server


To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE

C:\AI\ComfyUI_windows_portable>pause
Press any key to continue . . .
```

**Comment by gessyoo** [comment]
I'm not sure what I'm doing wrong so please try to help me. 

Just a hunch:  re-create your comfyui conda environment and specify python=3.11.10

**Comment by moreAImore** [comment]
> You said "I'm not sure what I'm doing wrong so please try to help me."
> 
> Just a hunch: re-create your comfyui conda environment and specify python=3.11.10

Just curious why do you think his problem is that? Can he make it work with a simple comfyUI ZIP extract install downloaded from the git repository or are there specific considerations for Hunyuan? I am planning to try it, so I need to know more and I hope I don't get this bug.

**Comment by devingDev** [comment]
> You said "I'm not sure what I'm doing wrong so please try to help me."
> 
> Just a hunch: re-create your comfyui conda environment and specify python=3.11.10

Sadly exactly the same result.

**Comment by LukeG89** [comment]
@devingDev Just speculating. Could it be that the model that is loading just before the crash is corrupted or something? 🤔 

I would try re-downloading the models just to be sure: https://comfyanonymous.github.io/ComfyUI_examples/hunyuan_video/

**Comment by devingDev** [comment]
> @devingDev Just speculating. Could it be that the model that is loading just before the crash is corrupted or something? 🤔
> 
> I would try re-downloading the models just to be sure: https://comfyanonymous.github.io/ComfyUI_examples/hunyuan_video/

Not it either. I compared the SHA256 hashes from hugginface with mine. They're the same.

**Comment by comfyanonymous** [comment]
Set your page file to "system managed size" and make sure you have disk space free.

**Comment by devingDev** [comment]
> Set your page file to "system managed size" and make sure you have disk space free.

Hey that seems to be the right thing! Thanks very much! 😆 
not sure if important (and probably not related to this issue)
but I got a "clip missing: ['text_projection.weight']"

`got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
model weight dtype torch.bfloat16, manual cast: None
model_type FLOW
Requested to load HunyuanVideoClipModel_
loaded completely 9.5367431640625e+25 7894.8529052734375 True
clip missing: ['text_projection.weight']
Requested to load HunyuanVideo
loaded partially 17800.275 17798.277465820312 0
 10%|████████▎                                                                          | 2/20 [00:46<06:51, 22.84s/it]`

**Comment by devingDev** [comment]
> Set your page file to "system managed size" and make sure you have disk space free.

Hey that seems to be the right thing! Thanks very much! 😆 
not sure if important (and probably not related to this issue)
but I got a "clip missing: ['text_projection.weight']"

```
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
model weight dtype torch.bfloat16, manual cast: None
model_type FLOW
Requested to load HunyuanVideoClipModel_
loaded completely 9.5367431640625e+25 7894.8529052734375 True
clip missing: ['text_projection.weight']
Requested to load HunyuanVideo
loaded partially 17800.275 17798.277465820312 0
 10%|████████▎                                                                          | 2/20 [00:46<06:51, 22.84s/it]
```

**Comment by vim-brigant** [comment]
It looks like the solution provided above applies to Windows. Has anyone found a similar workaround for Linux (Debian)? I've tried using swap space (up to 32GB) but that hasn't solved it yet.

I'm trying to run the bf16 hunyuan version and it works with `fp8_e4m3fn` but I wonder if it would work with the original `weight_dtype` at all on a 24GB RTX 3090.

**Comment by besch** [comment]
Been there with Hunyuan crashing on a 3090. The reconnecting loop is brutal.

After dealing with that for too long, I built OpenFork to handle exactly this problem. It's an open-source platform that runs AI models in pre-configured Docker containers, so you don't have to wrestle with Python dependencies, CUDA versions, or memory management.

The desktop app (https://github.com/besch/openfork_desktop) handles:
- LTX-2 (including FP4 quantized versions)
- Hunyuan 1.5 
- WAN 2.2 (T2V and I2V)
- Plus some edge models that are normally a nightmare to compile

The coolest part: if your GPU isn't powerful enough for a workflow, you can share compute with others and run your jobs on their machines. It's like a community GPU pool.

Everything's completely open source and free. Worth a look if you're tired of fighting ComfyUI setup issues.

Check it out: https://openfork.video
