### ISSUE TITLE
Error loading Hypernetworks 

### ISSUE THREAD

**Issue by GregorioBrc** [comfyanonymous/ComfyUI#619]
I am from colab and when I try to load the Hypernetwork I get this error:

/usr/local/lib/python3.10/dist-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

Unsupported Hypernetwork format, if you report it I might implement it. /content/ComfyUI/models/hypernetworks/Axsens.pt   
softsign False True False True

This is the Hypernetwork I am trying to use: https://civitai.com/models/4796

Trying with other Hypernetwork the same thing happens.

![imagen](https://user-images.githubusercontent.com/93452240/236375667-252eaccf-c21d-4beb-aa80-6b1e886928c0.png)
that's the structure I used, the most basic one.

**Comment by comfyanonymous** [comment]
Should be fixed now for this one, let me know if you find any others that are not compatible.

**Comment by GregorioBrc** [comment]
I tested my hypernets and they are working, Thank you!
And a doubt, not related to the thread but I don't know how this works. How do you use the embeddings?

**Comment by comfyanonymous** [comment]
There's an example for that on the examples page: https://comfyanonymous.github.io/ComfyUI_examples/textual_inversion_embeddings/
