### ISSUE TITLE
Just starting ComfyUI without running anything consumes GPU? (11.6 GB VRAM used, why?)

### ISSUE THREAD

**Issue by moreAImore** [comfyanonymous/ComfyUI#6190]
### Your question

Hello, 
I would like to understand why does launching ComfyUI without clicking on any button (without running anything), makes my GPU consumption jump from normal pc usage to 11.6/24 GB?
Check this image:
![image](https://github.com/user-attachments/assets/9ce1435a-4231-4828-90af-8288645ebaf2)

![image](https://github.com/user-attachments/assets/1a01ef53-95b1-446a-a6e7-b4649c894c0a)

Don't know if it happens just before or at that line "loading pipeline components"?
Anyway is that normal?

**Comment by LukeG89** [comment]
Have you tried disabling all nodes with `--disable-all-custom-nodes` argument?

**Comment by moreAImore** [comment]
No But I will try it.

**Comment by LukeG89** [comment]
The problem is definitely a custom node, ComfyUI itself doesn't load anything until you press "Queue"
