### ISSUE TITLE
transformers.modeling_utils

### ISSUE THREAD

**Issue by xiaoyi1591** [comfyanonymous/ComfyUI#6199]
HyVideoModelLoader
cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (F:\ComfyUI-aki-v1.1\python\lib\site-packages\transformers\modeling_utils.py)

# ComfyUI Error Report
## Error Details
- **Node ID:** 1
- **Node Type:** HyVideoModelLoader
- **Exception Type:** ImportError
- **Exception Message:** cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (F:\ComfyUI-aki-v1.1\python\lib\site-packages\transformers\modeling_utils.py)
## Stack Trace

**Comment by ltdrdata** [comment]
Pleaes move this issue to ComfyUI-HunyuanVideoWrapper repo.
https://github.com/kijai/ComfyUI-HunyuanVideoWrapper
