### ISSUE TITLE
Update the latest code and use the api to execute exceptions

### ISSUE THREAD

**Issue by prog-ape** [comfyanonymous/ComfyUI#6202]
### Expected Behavior

Execute flux's normal text2image or image2image

Update the latest code, use the API to execute abnormally, but it can be executed and output normally in the UI

There is no problem with the f18ebbd version

### Actual Behavior

Failed to validate prompt for output 143:
* VAEDecodeTiled 88:
  - Required input is missing: temporal_overlap
  - Required input is missing: temporal_size

### Steps to Reproduce

Execute flux's normal text2image or image2image

### Debug Logs

```powershell
Failed to validate prompt for output 143:
* VAEDecodeTiled 88:
  - Required input is missing: temporal_overlap
  - Required input is missing: temporal_size
```

**Comment by huchenlei** [comment]
You need to add extra field in the API, as `VAEDecodeTiled` now has extra params.
