### ISSUE TITLE
Output to folder by date with generation data

### ISSUE THREAD

**Issue by carlbenjaminlyon** [comfyanonymous/ComfyUI#6203]
### Feature Idea

Fooocus has a handy way of organizing outputs by date, along with a log.html file that shows each of the generated images, along with their output data. If there is a way to integrate the way Fooocus does it in to ComfyUI, that would be excellent for workflow organization, especially when generating a lot of images.

**Comment by LukeG89** [comment]
You can use formatting: https://blenderneko.github.io/ComfyUI-docs/Interface/SaveFileFormatting/

For example, if you write something like this in `filename_prefix`: 

![save-formatting](https://github.com/user-attachments/assets/71f17c68-4f08-494c-bf8f-e19cd5f43703)

All the images will be saved in a subfolder with the current date on it:

![subfolder](https://github.com/user-attachments/assets/8f017cf6-ff9d-46d9-8339-90a1edc32452)
![saved_images](https://github.com/user-attachments/assets/74f4cd6a-cc2f-432e-bd86-4fc64c4ea3f1)
