### ISSUE TITLE
So what is the correct method of installing custom nodes?

### ISSUE THREAD

**Issue by oybritt0** [comfyanonymous/ComfyUI#6209]
Please move this issue to ComfyUI-Flowty-CRM repo.
https://github.com/flowtyone/ComfyUI-Flowty-CRM

Additionally, custom nodes should not be installed by downloading and extracting zip files. This method can cause essential files required for updates to be missing, making updates impossible.

_Originally posted by @ltdrdata in https://github.com/comfyanonymous/ComfyUI/issues/5795#issuecomment-2503786045_

**Comment by ltdrdata** [comment]
Use `git clone` or install via ComfyUI-Manager.

**Comment by oybritt0** [comment]
Thank you!
