### ISSUE TITLE
ComfyUI connections between nodes appear unconnected or misaligned

### ISSUE THREAD

**Issue by JavierDiazM** [comfyanonymous/ComfyUI#6210]
### Expected Behavior

Connections between nodes look far back behind the nodes and unconnected, if I pan the connections move at a different speed

### Actual Behavior

I have note been able to render Comfyui on Google Chrome, Chromium and Brave on Ubuntu, and also on IOS 17.6 for ipad Air 5th generation, the only one has ever

### Steps to Reproduce

just installed and opened

### Debug Logs

```powershell
what logs?
```

**Comment by huchenlei** [comment]
Closing for lack of context. Please file frontend issue here: 
![image](https://github.com/user-attachments/assets/1090d329-39a1-43a2-9be9-23d6cf752cf1)
