### ISSUE TITLE
Load images from path node.

### ISSUE THREAD

**Issue by razvanab** [comfyanonymous/ComfyUI#6218]
### Feature Idea

Just like the Load Image node, but instead of the "choose file to upload," there should be a path to a new location for your images you want to use. "images path"

### Existing Solutions

There are a number of solutions out there, but none give the functionality of the Load Image node.
Like choosing the next or previous image and, of course, the preview of the image.

### Other

An example of how it should look like:
![Screenshot 2024-12-25 133626](https://github.com/user-attachments/assets/cedad4f9-2992-4a5d-98a3-b77f57bda3bc)

**Comment by atomicitytech** [comment]
But reading arbitrary uploaded images is safe?  *headscratch*
