### ISSUE TITLE
invalid load key, '\xfe'.

### ISSUE THREAD

**Issue by beebase** [comfyanonymous/ComfyUI#6221]
### Expected Behavior

Installed the standalone Windows version and getting this error when starting the sample workflow.

`\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1628, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '\xfe'.`

![image](https://github.com/user-attachments/assets/174fc159-83f5-4c75-9930-1b798a890f0b)

### Actual Behavior

N/A

### Steps to Reproduce

N/A

### Debug Logs

```powershell
\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1628, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '\xfe'.
```

**Comment by ltdrdata** [comment]
It seems that the checkpoint file is invalid.
