### ISSUE TITLE
RuntimeError: The NVIDIA driver on your system is too old

### ISSUE THREAD

**Issue by lp19910807** [comfyanonymous/ComfyUI#6226]
### Your question

我使用centos7.9系统安装了comfyUI    使用了两张A100 80G显卡，运行python main.py报错
I installed ComfyUI on  CentOS 7.9 system with two A100 80G GPUs. When I run python main.py, an error occurred.
![image](https://github.com/user-attachments/assets/abfe31ee-17b9-47ce-b8b8-43ceb9b95b21)

**Comment by ltdrdata** [comment]
Literally, you need to update your GPU driver.  
PyTorch versions from 2.0.1 and above do not support CUDA 11.7.

https://pytorch.org/get-started/previous-versions/
