### ISSUE TITLE
what is this fuck!!

### ISSUE THREAD

**Issue by jacksonjack001** [comfyanonymous/ComfyUI#6231]
### Your question

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/fbe2bf5f-bd69-4997-ba06-e7fe20f0b6fe" />

**Comment by LukeG89** [comment]
It's a bug by one of your custom nodes + workflow tabs.

They should look this way:

![image](https://github.com/user-attachments/assets/0ce4680b-efe1-4014-83d2-12a2b72e902f)

 If you want, you can turn off workflows tabs in Settings (or find the culprit of the bug)

![image](https://github.com/user-attachments/assets/78f55758-dc3e-4e96-9710-44d7f2a9bb5e)

**Comment by jacksonjack001** [comment]
![image](https://github.com/user-attachments/assets/51ec1f1b-e7f9-4e70-bef2-2d45f72674fb)
after i update my language to english, the same question

**Comment by jacksonjack001** [comment]
another error when i want to upload a picture, i cant find my folders!!
![image](https://github.com/user-attachments/assets/90450311-d58a-4b9d-894f-c5c5241272b6)

**Comment by jacksonjack001** [comment]
i git clone from this repo directly, i need to git the realease version?

**Comment by ltdrdata** [comment]
This is because you have too many workflow tabs open, and the horizontal resolution is too low.

@huchenlei It seems necessary to consider making the tabs scrollable rather than displaying them in multiple lines.

**Comment by huchenlei** [comment]
Closing as the style is mainly altered by custom nodes.
