### ISSUE TITLE
KSampler not enough values to unpack (expected 8, got 4)

### ISSUE THREAD

**Issue by wayawaya123** [comfyanonymous/ComfyUI#6245]
### Expected Behavior

生成图片

### Actual Behavior

<img width="952" alt="0ef79ee3aca1e58754884bd07bb3ef0" src="https://github.com/user-attachments/assets/d8e17858-5ce9-4d18-a6c5-ee9ba614186d" />

### Steps to Reproduce

<img width="1109" alt="111" src="https://github.com/user-attachments/assets/9d3717e3-d9c7-443e-a4df-7d3031c0cfc5" />

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 10
- **Node Type:** KSampler
- **Exception Type:** ValueError
- **Exception Message:** not enough values to unpack (expected 8, got 4)
## Stack Trace
```

**Comment by LukeG89** [comment]
What model type have you used in the checkpoint loader? Is it a lora?

**Comment by bubbl000** [comment]
python -m pip install -U xformers==0.0.28.post3 --index-url https://download.pytorch.org/whl/cu124              Xformers, I reinstalled the original 0.29 version, just replace it with this version.

**Comment by yumijiiang** [comment]
help
