### ISSUE TITLE
Can PyTorch 2.0 work with CUDA 11.7?

### ISSUE THREAD

**Issue by Fireflower-March** [comfyanonymous/ComfyUI#6247]
### Your question

Due to driver limitations, the server is restricted to PyTorch 2.0 + CUDA 11.7. However, I noticed that the requirements in the README file specify a higher version. Can this setup still be compatible?

**Comment by ltdrdata** [comment]
https://pytorch.org/get-started/previous-versions/
PyTorch 2.0.1 supports CUDA11.7.

**Comment by Fireflower-March** [comment]
Thank you for your response. What I mean is whether this content supports PyTorch 2.0 + CUDA 11.7. I noticed that the version in the Linux command line installation steps is higher than this.

**Comment by ltdrdata** [comment]
> Thank you for your response. What I mean is whether this content supports PyTorch 2.0 + CUDA 11.7. I noticed that the version in the Linux command line installation steps is higher than this.

Some features are not supported on CUDA 11.7, which can be a limitation, but generally, it shouldn't cause significant issues.
