### ISSUE TITLE
[Feature Request] Please add public API for adding sidebar buttons and drawer widgets

### ISSUE THREAD

**Issue by JaredTherriault** [comfyanonymous/ComfyUI#6251]
### Feature Idea

The sidebar in the new UI is great! As a plugin developer, it would be extremely useful to be able to add custom buttons and widgets that go in the drawer when the button is clicked, similar to how we can add items to the settings element with 'app.menu.settingsGroup'. 

As a bonus, it would be fantastic from a user perspective to be able to enable/disable sidebar buttons just like being able to enable/disable extensions.

**Comment by ltdrdata** [comment]
Please move this issue to the front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
