### ISSUE TITLE
Ctrl+selection in Firefox doesn't work (in Chrome everything is all right)

### ISSUE THREAD

**Issue by ibobak** [comfyanonymous/ComfyUI#6252]
### Expected Behavior

if I hold Ctrl and if I press left mouse button and move it - I want to see the white rectangle which shows me WHAT I am selecting

### Actual Behavior

The white rectangle is not drawn in Firefox.

### Steps to Reproduce

Just use the firefox

### Debug Logs

```powershell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies. (GitPython)
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-29 00:53:44.655551
** Platform: Linux
** Python version: 3.12.8 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 16:31:09) [GCC 11.2.0]
** Python executable: /opt/anaconda3/envs/comfyui/bin/python
** ComfyUI Path: /home/ihor/ai/ComfyUI
** Log path: /home/ihor/ai/ComfyUI/comfyui.log

Prestartup times for custom nodes:
  14.2 seconds: /home/ihor/ai/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24105 MB, total RAM 257806 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch attention
[Prompt Server] web root: /home/ihor/ai/ComfyUI/web
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Revision: 2980 [ee9547ba] *DETACHED | Released on '2024-12-26'

Import times for custom nodes:
   0.0 seconds: /home/ihor/ai/ComfyUI/custom_nodes/websocket_image_save.py
   0.1 seconds: /home/ihor/ai/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
FETCH DATA from: /home/ihor/ai/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
FETCH DATA from: /home/ihor/ai/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
```

**Comment by ltdrdata** [comment]
Please move this issue to front repo.
https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by ibobak** [comment]
Are you sure I am the one who has to do it?  I know guys that you are doing a great work.  But I am just a user who spent time on reporting a bug.  So, after spending my time I have to work even more and do this again, seriously?

**Comment by ltdrdata** [comment]
> Are you sure I am the one who has to do it? I know guys that you are doing a great work. But I am just a user who spent time on reporting a bug. So, after spending my time I have to work even more and do this again, seriously?

The front repo and backend repo have been separated, and we are tracking issues for each repo in a specialized and organized manner.  

If front-related issues continue to be raised here, it will hinder proper issue management. Therefore, we provide guidance to redirect such issues. 
(This is not just about acknowledging and fixing the issue but also ensuring the process of resolving the issue is documented, allowing users who encounter the same issue in the future to find relevant information.)

Unfortunately, this repo is part of `comfyanonymous`, while the front is part of `Comfy Org`. Structurally, we do not have the authority to transfer issues between the two repos.
