### ISSUE TITLE
GETTING ERROR IN GENERATION

### ISSUE THREAD

**Issue by Zebronicsqwert1** [comfyanonymous/ComfyUI#6255]
### Your question

![Screenshot 2024-12-29 112617](https://github.com/user-attachments/assets/7ddeebee-4cca-4f50-8fca-db79fa8bda2e)
I am getting this error even when the checkpoint is copied in the checkpoint folder. The flows are designed properly. kindly help with this.

**Comment by ltdrdata** [comment]
Where did you download that model from? Based on the symptoms, it doesn't seem to be a checkpoint model.  
Check if it is a diffusion model.
