### ISSUE TITLE
C:Windows\System32>.\python embeded\python.exe-s ComfyUI main. py --windows standalone-build系统找不到指定的路径

### ISSUE THREAD

**Issue by zzzz88881** [comfyanonymous/ComfyUI#6258]
### Your question

![image](https://github.com/user-attachments/assets/aeb370db-3078-4311-a2f6-9f299610399d)

**Comment by zzzz88881** [comment]
I tried to put it on the C disk and the D disk and it can't run, but it can run when I put it on a mechanical hard disk, but it takes 1 minute to create a picture of ordinary text, and it runs very slowly

**Comment by Cp0204** [comment]
The issue with the path is a personal usage problem and not a problem with ComfyUI. This is not something the software author should address; please seek alternative solutions.

Just as the master who makes a kitchen knife won't teach you how to cook.

**Comment by ltdrdata** [comment]
The command must be executed from the directory where ComfyUI is installed.

**Comment by zzzz88881** [comment]
已解决，用管理员运行就是上面这种问题，正常打开可以运行
