### ISSUE TITLE
Run API call (same prompt) more than once

### ISSUE THREAD

**Issue by abcnorio** [comfyanonymous/ComfyUI#6261]
### Your question

Hello,

using ComfyUI via the API call and .json with

`curl -X POST --data @comfyui.json http://127.0.0.1:8188/prompt`

from the terminal works, but calling the same .json again nothing happens. If something is changed in the .json, it works again. How can I force to re-run the same API call again and again?
I need this for batch processing of images (upscaling) and it requires to re-run the same call several times during the development part. Using the terminal is essential to be able to script things.

Thanks!

PS: no log added, because nothing is stated on the commandline except for "`got prompt`" and "`prompt executed in 0.00 seconds`". No error or anything is logged.

OS = debian trixie
ComfyUI from 2024-12-25

**Comment by ltdrdata** [comment]
ComfyUI caches the execution results of all nodes within the workflow by default. If there are no changes in the input, the cached results of the nodes are reused instead of recalculating.  
This means that if you rerun the exact same prompt, nothing will happen since there is nothing to recalculate.  

For example, in a basic workflow, if you resend the request with a different seed value for KSampler, the loading and conditioning stages will be skipped, and only the KSampler, VAE Decode, and Save Image nodes will be re-executed.  

One important thing to note is that seed randomization occurs on the front end. Therefore, when using API mode, you must manually change the values in your code.

**Comment by abcnorio** [comment]
Thanks + understood.

But cached does not mean files are re-written by re-running the same API call. My workflow is as simple as that:

"load image from list/dir (inspire pack) -> upscale by model (+ load upscale model) -> save image (here: batch)"

Problem: re-running does not write the cache again to file(s). Tried out several times. So this is not about re-calculating but re-writing results to file(s).

seed is not relevant for upscaling-by-model.

So any chance to re-run it *with* writing the cache to file ie. save-images again? Otherwise I have to insert a dummy .json with something short and switch back to the first .json and re-run it as something "new".

thx + best.

ps: Actually I wanted to use chainner but chainner has some serious bugs regarding the cli version which are not fixed (same config works in the GUI but not cli).

Am 29.12.24 um 17:29 schrieb Dr.Lt.Data:

**Comment by ltdrdata** [comment]
> Thanks + understood. But cached does not mean files are re-written by re-running the same API call. My workflow is as simple as that: "load image from list/dir (inspire pack) -> upscale by model (+ load upscale model) -> save image (here: batch)" Problem: re-running does not write the cache again to file(s). Tried out several times. So this is not about re-calculating but re-writing results to file(s). seed is not relevant for upscaling-by-model. So any chance to re-run it *with* writing the cache to file ie. save-images again? Otherwise I have to insert a dummy .json with something short and switch back to the first .json and re-run it as something "new". thx + best. ps: Actually I wanted to use chainner but chainner has some serious bugs regarding the cli version which are not fixed (same config works in the GUI but not cli).

Caching means that the execution of the node is completely skipped, and this applies to the **Save Image** node as well. If the input connection to **Save Image** uses an unchanged cache, the **Save Image** node itself will not execute.  

One of the simplest trick is to change the **node id** of the **Save Image** node. This will make it regarded as a new node, causing the **Save Image** node to re-execute.

**Comment by abcnorio** [comment]
great tip! thanks, will do that.

best!


Am 29.12.24 um 19:37 schrieb Dr.Lt.Data:
