### ISSUE TITLE
Why is insightface installation never straightforward?

### ISSUE THREAD

**Issue by moreAImore** [comfyanonymous/ComfyUI#6262]
### Your question

Is it because custom node makers did not set up correclty their requirements.txt file? Or is it a problem with comfyUI? Or is something else?
Installing custom nodes that require insightface will tend to run workflows into error, solution is to use a WHEEL and install the right version. (This usage of wheel is also a solution for other complicated custom nodes that are not related to insightface sometimes)

I wanted to know if it was something that can be improved?
I mean I know how to install insightface with the wheel, but I wanted to know why it wasn't straightforwared like any other python library.

**Comment by ltdrdata** [comment]
The main reason is that the officially distributed `insightface` package is not pre-processed and packaged for easy installation like other packages. 

Depending on the operating system, this package often needs to be compiled and installed directly in the user's environment.

**Comment by moreAImore** [comment]
Ok thank you.
