### ISSUE TITLE
Creating custom nodes and combo boxes are wrong

### ISSUE THREAD

**Issue by DragonDiffusionbyBoyo** [comfyanonymous/ComfyUI#6266]
### Your question

I am attempting to make a custom node and all of my combo boxes keep going wrong. 

![Untitled](https://github.com/user-attachments/assets/882be2fb-cc4e-4f66-8c77-6953e267591b)

I am using this method:

 return {
            "required": {
                "model": ("MODEL",),
                "positive": ("TEXT",),
                "negative": ("TEXT",),
                "latent_image": ("LATENT",),
                "seed": ("INTEGER", {"default": 0}),
                "steps": ("INTEGER", {"default": 20, "min": 1, "max": 100}),
                "cfg": ("FLOAT", {"default": 7.5, "min": 0.1, "max": 30}),
                "sampler_name": ("COMBO", ["euler", "euler_ancestral", "ddim", "plms"]),
                "scheduler_name": ("COMBO", ["normal", "karras", "exponential", "sgm_uniform"]),
                "denoise": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 1.0}),
                "style": ((styles),),
                "apply_style": ("BOOLEAN", {"default": True, "label_on": "yes", "label_off": "no"}),
                "log_prompt": ("BOOLEAN", {"default": False, "label_on": "yes", "label_off": "no"})

Everything that has combo is displaying C O M B O in the drop down as show on the image. 
I am new to python and learning on the fly so assume I am an idiot please?

**Comment by ltdrdata** [comment]
```
"sampler_name": ("COMBO", ["euler", "euler_ancestral", "ddim", "plms"]),
"scheduler_name": ("COMBO", ["normal", "karras", "exponential", "sgm_uniform"]),
```

Should be
```
"sampler_name": (["euler", "euler_ancestral", "ddim", "plms"],),
"scheduler_name": (["normal", "karras", "exponential", "sgm_uniform"],),
```
