### ISSUE TITLE
UI fails to initialize on master

### ISSUE THREAD

**Issue by steverhoades** [comfyanonymous/ComfyUI#6267]
### Expected Behavior

api.ts calls /users which returns a result

### Actual Behavior

api.ts calls /api/users which returns a 404 not found error

### Steps to Reproduce

Checkout a618f768e06d72acc5b97d78a9ae209cbae14654

start ComfyUI.
```python
python main.py
```

### Debug Logs

```powershell
Running on 127.0.0.1:8188
App.vue:42 ComfyUI Front-end version: 1.5.19
api.ts:201 
        
        
       GET http://127.0.0.1:8188/api/users 404 (Not Found)
```

**Comment by steverhoades** [comment]
This issue was related to `custom_nodes`. Because of `custom_nodes` the if block on line 714 was not getting executed. This is a problem because the UI is expecting all routes to be available at /api prefix. There is a note saying that old and new endpoints are supported but i don't think that is accurate.

**Comment by xiaolinpeter** [comment]
> 此问题与有关`custom_nodes`。因为`custom_nodes`第 714 行上的 if 块未执行。这是一个问题，因为 UI 期望所有路由在 /api 前缀处可用。有一条注释说支持旧端点和新端点，但我认为这并不准确。

hi,  I get the same question, could you tell me how to solv the this question
