### ISSUE TITLE
Error related to wildcard `*` as output type

### ISSUE THREAD

**Issue by EricBCoding** [comfyanonymous/ComfyUI#6274]
### Expected Behavior

Outputs defined as `*` datatype should pass validation

### Actual Behavior

Error thrown when `*` passed to node expecting specific datatype

### Steps to Reproduce

Connect output where `RETURN_TYPES = ("*", )` to an input defined as a specific type, such as `IMAGE` and run queue

### Debug Logs

```powershell
Failed to validate prompt for output 13:
* VAEEncode 203:
  - Return type mismatch between linked nodes: pixels, received_type(*) mismatch input_type(IMAGE)
```

### Other

Hi, I see that the wildcard datatype was implemented in the ComfyUI core last month per #5890. However--unless I'm making a mistake--it seems that this type is not passing validation to a successive node as input.

The documentation on `*` is a little sparse, this is all I could find:

- https://docs.comfy.org/essentials/custom_node_more_on_inputs#wildcard-inputs

Is it still the case that wildcard is "not officially supported by the backend?"

I'm trying to figure out if it's possible to ditch the `AnyType()` class hack that custom node authors have been relying on for a while. Any clarification would be appreciated. Thank you!

**Comment by huchenlei** [comment]
You can use `IO.ANY` from `comfy.comfy_types` here now: https://github.com/comfyanonymous/ComfyUI/tree/master/comfy/comfy_types

**Comment by EricBCoding** [comment]
Thanks for pointing me in the right direction! It seems `IO.ANY` is working great.
