### ISSUE TITLE
When a node is abnormal, the node ID can be displayed at the same time

### ISSUE THREAD

**Issue by stone0018** [comfyanonymous/ComfyUI#6279]
### Feature Idea

![image](https://github.com/user-attachments/assets/50fdbc3e-61f0-4e4a-abd1-1223d05ed9d2)
![image](https://github.com/user-attachments/assets/b3c7d225-f647-4970-a16e-d8723fe12744)
When there are multiple node exceptions, I want to check the node with the first exception by clicking Execute, but I found that the node with the exception does not display the id. Should I add the node id to display in the next version?

**Comment by ltdrdata** [comment]
Please move this request to the front repo.
https://github.com/Comfy-Org/ComfyUI_frontend
