### ISSUE TITLE
ComfyUI and ANY FLUX Model Crashing (Worked perfectly for about 2 weeks up until 12/29/2024) [SDXL and any other model is Fine]

### ISSUE THREAD

**Issue by microchipmatt** [comfyanonymous/ComfyUI#6282]
### Your question

Hello all, I know others have experienced crashing with ComfyUI and FLUX models, but ALL of my workflows and FLUX models rendered out fine with no crashing for about 2 weeks (I know this has been the case with others as well).  I have scoured and read the about fixes in here and on reddit all yesterday day, evening and night, and tried all the suggested fixes and ComfyUI is still crashing with ANY flux models now. The Workflow starts and then when it reaches the FLUX model to load, ComfyUI just crashes. With the same workflow this was all was working for 2 weeks, no changes in the workflow and I have tried several different workflows. As well ALL of other NON flux models seem to be working [SDXP, SD XX, Dream shaper, Realistic etc work fine]. Here is what I have tried so far (I am Running ComfyUI Portable with ComfyUI Manager):

- Increased the page file size in
- Increased the page file size more (Page file increase was not needed in the past)
- Updated ComfyUI Portable via the update scripts
- Updated ComfyUI Portable via ComfyUI manager
- Tried different workflows
- Updated Nvidia drivers to newest one
- Downgraded Nvidia drivers to the suggested lower version in these forums
- Upgraded to the Nvidia Studio drivers
- Turned it off and then on again several time (No really, just the IT Crowd)
- Tried a NEW Install of ComfyUI (Same Error)
- Updated ALL Nodes in workflow after ComfyUI update (Right click, repair node, so that it recreates)

I don;t know what to do to make this work again:

My Basic System:
- Intel Core i7 (Hyperthreaded)
- 16 GB Ram
- 12 GB Nvidia 3060
Was working great with all of this until yesterday.
"See screenshot to see my previously working workflow and where it is crashing.

![FluxDevWorkFlow](https://github.com/user-attachments/assets/5b1f591c-a68c-44cf-aaa6-eb889c7cfa9c)
![FluxDevWorkFlowCrashError1](https://github.com/user-attachments/assets/2455c4b0-8c9f-49b3-9db8-f588243b791f)
![FluxDevWorkFlowCrashError2](https://github.com/user-attachments/assets/e0e5d342-fd41-4289-a53d-07d7b5ed39fd)

### Logs

```powershell
Logs show the same error as command line screenshot. If there is some sort of Debugging mode I can turn on in ComfyUI portable please let me know.
```

**Comment by microchipmatt** [comment]
Well, I solved the issue. My installation is on the a separate drive, and after trying all of the things listed in my last post, I desperately cleaned a bunch of space on the c:\ (OS) root drive, and......ComfyUI started working after that.

**Comment by PSImera** [comment]
i make my pagefile larger and its help me
