### ISSUE TITLE
TeaCache support native (LTX, Flux, Hunyuan)

### ISSUE THREAD

**Issue by cchance27** [comfyanonymous/ComfyUI#6285]
### Feature Idea

Would be great if this could be added to the native integration, that it seriously speeds things up especially when your hunting for a good seed and doing draft video renders.

### Existing Solutions

No custom nodes yet, the diffuser implementation is at https://github.com/ali-vilab/TeaCache

**Comment by super0nashwan** [comment]
Duplicate of https://github.com/comfyanonymous/ComfyUI/issues/6235

If you really want to use TeaCache right now, a PR for Kijai's Hunyuan video wrapper has implemented it: https://github.com/kijai/ComfyUI-HunyuanVideoWrapper/pull/226. That might give some clue how to smush it into the native ComfyUI video nodes, I might take a look myself later, the speedup is very appealing.

**Comment by cchance27** [comment]
ahhh didn't see that one was already open will close this, i was looking at trying to do it, but felt that we really need a clean implemntation for native, and as i still dont get how to use the ModelPatcher and there seems to be 0 notes on it :S
