### ISSUE TITLE
 couldn't connect to 'https://huggingface.co'

### ISSUE THREAD

**Issue by Ellsichan** [comfyanonymous/ComfyUI#6291]
### Your question

When run comfyui, here is a below question.
We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like /content/ComfyUI/custom_nodes/ComfyUI-InstantID/checkpoints/controlnet is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

**Comment by Ellsichan** [comment]
and I tried `ping huggingface.co` and checked the install requirement, I just followed steps which I should put the `config.json` in the directory /content/ComfyUI/custom_nodes/ComfyUI-InstantID/checkpoints/controlnet

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-InstantID repo.
https://github.com/cubiq/ComfyUI_InstantID
