### ISSUE TITLE
Variations in Output Using Sequential Advanced K-Samplers

### ISSUE THREAD

**Issue by Snimm** [comfyanonymous/ComfyUI#6293]
### Issue Description
I am trying to use the Advanced K-Sampler to peek at the image as it is generating. My approach involves creating two Advanced K-Samplers with separate start and end steps:  
- **First K-Sampler**: Start = 0, End = 10  
- **Second K-Sampler**: Start = 11, End = 20  

I also experimented with slightly adjusted ranges (e.g., 0-10 and 10-20). The JSON for the node setup is attached for reference:  
[midpeeksampcomp.json](https://github.com/user-attachments/files/18281751/midpeeksampcomp.json)

To compare results:  
1. I generated the **first image** using the above sequential setup.  
2. I then used a **single Advanced K-Sampler** with Start = 0 and End = 20 to generate the **second image**.  

### Observed Behavior
One would expect the outputs from the two approaches to be exactly the same. However, while the images are very similar, there are slight variations between them.  Look at the tusk of the elephant in both images. In the image created by single sampler (2nd image), tusk is not completely white, and the green part appear softer.  

![image](https://github.com/user-attachments/assets/0aa9da43-aa98-4aeb-ac6a-0e2ff84217ea)
![image](https://github.com/user-attachments/assets/e46ebec0-a40c-4fc2-bc28-1f4d1de709a8)
 

### Question
Why is there a difference between the two outputs? Is this expected due to internal variations in how Advanced K-Samplers handle state transitions, or is it a potential issue? How do I remove this variation? 

### Other

Some more examples 
There is a seam on the left side on the wooden floor in single sampler image (2nd image).
![image](https://github.com/user-attachments/assets/7a086dc0-9d3f-44bd-b079-c44f6a42d58c)
![image](https://github.com/user-attachments/assets/46873aae-7930-4015-9d5c-6d39401ad470)

**Comment by LukeG89** [comment]
You should get the same results with these changes:
- Return the leftover noise from the first KSampler
- Don't add noise in the second KSampler
- 1st end_at_step and 2nd start_at_step should be the same

![params](https://github.com/user-attachments/assets/75b5ec29-f802-426c-9ff6-d930b5e2df22)

![results](https://github.com/user-attachments/assets/11f43de8-2ddf-42d1-936e-2acab37951b3)
