### ISSUE TITLE
MydJorney hypernetwork mjv4Hypernetwork_v1.pt

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [comfyanonymous/ComfyUI#634]
Can you please adapt code for processing MydJorney hypernetwork mjv4Hypernetwork_v1.pt?

 Currently ComfyUI thows warning about not able to process this hypernetwork.

Thanks!

**Comment by comfyanonymous** [comment]
Update comfyui (update/update_comfyui.bat on the standalone) and it will work.
