### ISSUE TITLE
Don't throw when canceling prompt

### ISSUE THREAD

**Issue by Qudix** [comfyanonymous/ComfyUI#637]
Just a minor visual annoyance, I tend to cancel running prompts midway rather often and it results in the console getting filled with tracebacks due to this seemingly? unnecessary exception (on user action at least). I feel this could be made to simply log a one line `processing interrupted` message instead, or just nothing at all.

**Comment by comfyanonymous** [comment]
Should be fixed with: https://github.com/comfyanonymous/ComfyUI/commit/02ca1c67f87e46e926aba325e73b2845d5244874
