### ISSUE TITLE
[BUG] If you open too many images, ComfyUI freezes

### ISSUE THREAD

**Issue by MoonMoon82** [comfyanonymous/ComfyUI#640]
In the current branch of ComfyUI it seems theres a kind of maximum of amount of images you can load in the "Load Image" Node.
Every image you ever opened with the "Load Image" Node "choose file to upload" button gets saved in 
\ComfyUI\input
folder. In my case ComfiUI freezes at an amount of ~895 images in this folder if I try to load just one more image file. 

![grafik](https://github.com/comfyanonymous/ComfyUI/assets/41437842/aa8b637d-282d-499a-87e6-0868cc649820)

After I remove all images in this folder and restart ComfiUI everything works fine again.
I also tried it with another bunch images I copied into \ComfyUI\input which manually caused the same issue - So I guess it doesn't depend on any specific image, it just depends on the amount.

**Comment by comfyanonymous** [comment]
Can you check if this fixed it? https://github.com/comfyanonymous/ComfyUI/commit/8e3d1cbf3b8488b319675f952e1a868aa78f1161

**Comment by MoonMoon82** [comment]
@comfyanonymous Thank you very much, it seems to work, even with >900 files in input folder.

**Comment by MoonMoon82** [comment]
Ticket closed
