### ISSUE TITLE
[ Issues ]CompyUI can't find the ckpt_name

### ISSUE THREAD

**Issue by Wingto** [comfyanonymous/ComfyUI#641]
My PC configureation

- CPU: Intel Core i9-9900K
- GPU: NVIDA GeForce RTX 2080 Ti
- SSD: 512G

Here I ran the bat files, CompyUI can't find the ckpt_name in the node of the Load CheckPoint, So that return:
 ```
"got prompt
Failed to validate prompt for output 9 Required input is missing. CheckpointLoaderSimple, ckpt_name
output will be ignored
invalid prompt: Prompt has no properly connected outputs
 Required input is missing. CheckpointLoaderSimple, ckpt_name"
```

here is the detail, please check it out :>
![image](https://github.com/comfyanonymous/ComfyUI/assets/50476460/e8ada350-05a4-4858-a45b-3dd9d9b9321c)

**Comment by comfyanonymous** [comment]
Did you put a checkpoint in the ComfyUI/models/checkpoints folder? 

do that and refresh the page if you have not.

**Comment by Wingto** [comment]
> Did you put a checkpoin

Thank your reply, I am not sure where can I get the checkpoints, sorry I am just beginner :>

**Comment by comfyanonymous** [comment]
The readme in the package you downloaded should contain instructions how to download one.

**Comment by Wingto** [comment]
> The readme in the package you downloaded should contain instructions how to download one.

I see, and after downloading the checkpoints, which is sd-v1-4.ckpt, and it gave me other message:
`Traceback (most recent call last):
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 195, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 292, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 956, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 12, in load_torch_file
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "F:\SoftWare\StableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 58982400 bytes.

`

**Comment by NexusLightvale** [comment]
> DefaultCPUAllocator: not enough memory: you tried to allocate 58982400 bytes.

You are trying to load a checkpoint using a CPU right now. Try reinstalling torch with CUDA on their official page to use your NVIDIA graphics card
Here's the link if you want instructions: https://pytorch.org/get-started/locally/#windows-pip
Otherwise, you can simply copy and paste this command into PowerShell if Python is already installed
`pip3 install --force torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

**Comment by Wingto** [comment]
> > DefaultCPUAllocator: not enough memory: you tried to allocate 58982400 bytes.
> 
> You are trying to load a checkpoint using a CPU right now. Try reinstalling torch with CUDA on their official page to use your NVIDIA graphics card Here's the link if you want instructions: https://pytorch.org/get-started/locally/#windows-pip Otherwise, you can simply copy and paste this command into PowerShell if Python is already installed `pip3 install --force torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

Thank your reply, so need I install pytorch according to my configuration instead of following this step ->

![image](https://github.com/comfyanonymous/ComfyUI/assets/50476460/60f5cc31-4b37-4fd3-b691-a1ec02c5ccd8)

  cuz I saw [this tutorial](https://www.youtube.com/watch?v=gySLXbe7WZQ) how to use it

**Comment by comfyanonymous** [comment]
How much RAM do you have?

**Comment by Wingto** [comment]
> How much RAM do you have?

16GB

**Comment by comfyanonymous** [comment]
Make sure you have the latest gaming driver installed and the standalone should work.

You should try this checkpoint: https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/v1-5-pruned-emaonly.ckpt

The one you have might be too large for your RAM.

**Comment by Solomaha** [comment]
I'm getting this exact same issue. It worked once when I installed it, right out of the box with no alterations, then the checkpoint disappeared from that node selection box and there's no option to switch it back. I click on it and nothing happens. The files are where they're supposed to be, but ComfyUI won't recognize them.

I've made no changes after installing. Everything is where it's supposed to be.

**Comment by scottonanski** [comment]
> The readme in the package you downloaded should contain instructions how to download one.


Checking the readme, this is what you find;

 "Put your VAE in: models/vae"

Care you elaborate with specific information?

Thanks.

**Comment by Solomaha** [comment]
What... are you talking about?

**Comment by ltdrdata** [comment]
> I'm getting this exact same issue. It worked once when I installed it, right out of the box with no alterations, then the checkpoint disappeared from that node selection box and there's no option to switch it back. I click on it and nothing happens. The files are where they're supposed to be, but ComfyUI won't recognize them.
> 
> I've made no changes after installing. Everything is where it's supposed to be.

It means that the file is in the workflow, but not in your model folder.

**Comment by Solomaha** [comment]
I'm getting these messages in my email without context... I don't recall
saying that, but it must have been a long time ago, and I stopped using
Comfy. Plenty of no-hassle options out there. No reason to bother with time
wasting glitchware.

**Comment by ltdrdata** [comment]
> I'm getting these messages in my email without context... I don't recall saying that, but it must have been a long time ago, and I stopped using Comfy. Plenty of no-hassle options out there. No reason to bother with time wasting glitchware.

Oh, I just realized it's a really old thread.

**Comment by lewybagz** [comment]
> > I'm getting this exact same issue. It worked once when I installed it, right out of the box with no alterations, then the checkpoint disappeared from that node selection box and there's no option to switch it back. I click on it and nothing happens. The files are where they're supposed to be, but ComfyUI won't recognize them.
> > I've made no changes after installing. Everything is where it's supposed to be.
> 
> It means that the file is in the workflow, but not in your model folder.

bro please help i am having this same issue and i cant seem to fix it. the checkpoints are in the right directory but it still wont show up in the checkpoint loader
![Screenshot 2023-12-22 222949](https://github.com/comfyanonymous/ComfyUI/assets/133947298/60ebb237-f204-430e-aa59-175695fde0f3)
![Screenshot 2023-12-22 223002](https://github.com/comfyanonymous/ComfyUI/assets/133947298/300facd6-4183-4d72-9678-fcba85acc1dc)

**Comment by ltdrdata** [comment]
> > > I'm getting this exact same issue. It worked once when I installed it, right out of the box with no alterations, then the checkpoint disappeared from that node selection box and there's no option to switch it back. I click on it and nothing happens. The files are where they're supposed to be, but ComfyUI won't recognize them.
> > > I've made no changes after installing. Everything is where it's supposed to be.
> > 
> > 
> > It means that the file is in the workflow, but not in your model folder.
> 
> bro please help i am having this same issue and i cant seem to fix it. the checkpoints are in the right directory but it still wont show up in the checkpoint loader ![Screenshot 2023-12-22 222949](https://private-user-images.githubusercontent.com/133947298/292610648-60ebb237-f204-430e-aa59-175695fde0f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMTUzOTQsIm5iZiI6MTcwMzMxNTA5NCwicGF0aCI6Ii8xMzM5NDcyOTgvMjkyNjEwNjQ4LTYwZWJiMjM3LWYyMDQtNDMwZS1hYTU5LTE3NTY5NWZkZTBmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QwNzA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjhhOTQ0OGUxZDA1NGQ4MThiOWFmZDhjNDg2OWM3YTMwZTBhZTNlZTlmYjk0ZTJhMzJhOTljNmQ2YWE1OTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.smDHwbfXD5-65wwc92A5K0HELjkrg9VJ-wQCHhjrx6w) ![Screenshot 2023-12-22 223002](https://private-user-images.githubusercontent.com/133947298/292610650-300facd6-4183-4d72-9678-fcba85acc1dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMTUzOTQsIm5iZiI6MTcwMzMxNTA5NCwicGF0aCI6Ii8xMzM5NDcyOTgvMjkyNjEwNjUwLTMwMGZhY2Q2LTQxODMtNGQ3Mi05Njc4LWZjYmE4NWFjYzFkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QwNzA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGEyNWFkMWM3MDc1MzI4NWYzODFlOTFlYmY2MjdhNTI2NzExYjc3MjE2MDAyNzU0YmQ1ZWU5Mzg0NDk0NGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TFOChdqEhvR5lA4GllDs66Kcot7IeFdpw97mgrApSSU)

press refresh button. or refresh browser

**Comment by samitkumarsinha** [comment]
How to Load checkpoint on web UI
https://comfyuiweb.com/

**Comment by mirh** [comment]
FWIW my problem was that I thought the folder "models" in `extra_model_paths.yaml` referred back to the *base_path*, but instead it's actually a subfolder (for the records, I couldn't find any symbol or escape character to make them accept the root base path).

**Comment by fullstackwebdev** [comment]
this is the most fucked up problem now I have it. Why am I getting undefined evey though I have the models in the right place.

**Comment by samitkumarsinha** [comment]
Who built such an user friendly app 😁🤣😅😂 looks like a NASA project

**Comment by ChatNPlay** [comment]
Hello,
Getting same error for mac OS m4 chip, can someone please suggest:

<img width="418" alt="Image" src="https://github.com/user-attachments/assets/28fde594-10b6-4123-9376-5a263e4f7f7a" />

**Comment by e-caliskan** [comment]
C:\Users\%USER%\Documents\ComfyUI\models\checkpoints

**Comment by ChatNPlay** [comment]
It is resolved, have updated checkpoints folders
