### ISSUE TITLE
Add ability to overwrite image files in server.py code

### ISSUE THREAD

**Issue by AlekPet** [comfyanonymous/ComfyUI#644]
Hello, you can ask the server to contribute to the code. If possible, overwrite the image with the existing name in the folder. To make it possible to not create images Image.png, Image (1).png, etc. when loading, if this is not necessary.
Example server.py code edit:
Add after line: https://github.com/comfyanonymous/ComfyUI/blob/master/server.py#L129
```
        def image_upload(post, image_save_function=None):
            image = post.get("image")
            overwrite = post.get("overwrite") # add this code
```
Add before line : https://github.com/comfyanonymous/ComfyUI/blob/master/server.py#L148
```
                if not overwrite: # add this code
                    split = os.path.splitext(filename)
                    filepath = os.path.join(full_output_folder, filename)

                    i = 1
                    while os.path.exists(filepath):
                        filename = f"{split[0]} ({i}){split[1]}"
                        filepath = os.path.join(full_output_folder, filename)
                        i += 1
```

After that, it will be possible to overwrite images with an overwrite in the request in javascript.
```
		async function uploadFile(file, updateNode) {
			try {
				const body = new FormData();
				body.append("image", file);
				body.append("type", "temp"); // Directory to upload, default 'input'
				body.append("overwrite", '1');
				const resp = await fetch("/upload/image", {
					method: "POST",
					body,
				});

				if (resp.status === 200) {
					const data = await resp.json();
				} else {
					alert(resp.status + " - " + resp.statusText);
				}
			} catch (error) {
				alert(error);
			}
		}
```

I ask you to do this, because how it was solved some problems when creating extensions. Here are [my extensions](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet)  and one of them [PoseNode](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/tree/master/PoseNode) , and there it would be useful for resaving poses, otherwise when updating the comflow, I have to add the code again, so I did it without rewriting. Sorry for my english :)

**Comment by comfyanonymous** [comment]
Done: https://github.com/comfyanonymous/ComfyUI/commit/8ea165dd1ef877f58f3710f31ce43f27e0f739ab
