### ISSUE TITLE
how to save as a png which can be load?

### ISSUE THREAD

**Issue by better319** [comfyanonymous/ComfyUI#657]
how to save the   workflow.json     as a png which can be load.

**Comment by DivinoAG** [comment]
All PNG image files generated by ComfyUI can be loaded into their source workflows automatically. If you have an image created with Comfy saved either by the Same Image node, or by manually saving a Preview Image, just drag them into the ComfyUI window to recall their original workflow.

**Comment by WASasquatch** [comment]
https://colab.research.google.com/drive/1hQMjNUdhMQ3rw1Wcm3_umvmOMeS_K4s8

**Comment by better319** [comment]
thk
