### ISSUE TITLE
[Feature Request] Inpaint mask content settings.

### ISSUE THREAD

**Issue by eldragon0** [comfyanonymous/ComfyUI#668]
Inpaint mask content settings. 

While inpainting to fix small issues with color or location of an object, only being able to inpaint with latent noise makes it very hard to get the object set back in a scene after it's been generated. Or makes it near impossible to fix the thing you're working on. 

A1111 for example has the option of what content you want to be in the mask when you send it to the sampler :

![image](https://github.com/comfyanonymous/ComfyUI/assets/50936701/4eddf923-2ef2-4981-b7c8-b786cfcf14bb)

**Comment by Shir0an** [comment]
You can achieve what you're describing by first encoding the image to a latent (don't use the inpaint node):
![image](https://github.com/comfyanonymous/ComfyUI/assets/33666955/3fd8c9c5-adb3-4d42-85f8-8d7f781e7cc8)

And then plugging the new masked latent to two chained advanced KSampler nodes, one for noising and one for denoising:
![image](https://github.com/comfyanonymous/ComfyUI/assets/33666955/2f5acfb9-64c7-4ce4-b6c4-c5e0d42a1476)

The more you delay the start of the noising (start_at_step at the first KSampler), the more your final image will resemble the original.
I'm not sure why the VAEEncodeForInpaint doesn't work here, tho.
