### ISSUE TITLE
[Feature request]: Programmatic use and API

### ISSUE THREAD

**Issue by ebceu4** [comfyanonymous/ComfyUI#67]
I would like to request a feature that allows for the saving and loading of pipelines as JSON. This will enable users to create complex and advanced pipelines using the graph/nodes/flowchart based interface and then leverage the visually built pipelines programmatically or via API through a runner

**Comment by comfyanonymous** [comment]
See: https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py

**Comment by IcelandicIcecream** [comment]
Is there a guide on how the API works

**Comment by paulo-coronado** [comment]
@IcelandicIcecream I haven't seen yet... I am also trying to run [basic_api_example.py](https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py), but getting 400 (Bad Request) error.

**Comment by lunaticer** [comment]
I also want to use workflow struct my special API,because I can't process batch images now.It will make the workflow more powerful.

**Comment by icelandno1** [comment]
That's a good question, and I'd like to implement this functionality by calling the ComfyUI workflow directly from an external application, which eliminates the hassle of using the stable diffusion api.

**Comment by misza222** [comment]
+1

**Comment by comfyanonymous** [comment]
if you update to the latest you can "enable dev mode options" in the settings (gear beside the "Queue Size: ") this will enable a button on the UI to save workflows in api format.

You can then use these api jsons in these script examples: https://github.com/comfyanonymous/ComfyUI/tree/master/script_examples

**Comment by tomermesser** [comment]
Hi, Thanks for adding the "API Format" option it is super helpful !

**Comment by fidecastro** [comment]
I took a look at how the websocket service works, and created a simple class to use the already existing API. It facilitated my workflow a lot and maybe some of you can find it useful.

https://github.com/fidecastro/ComfyUI-serverless/

**Comment by kiriri** [comment]
I could not find an api documentation, so here's what I gleamed from the source code and everyone's comments :

## GET

```/history```
Last queued renders, including all nodes used in the prompt, and all output images.

```/view?filename={FILENAME}```
Access the images from history via this.

```/extensions```
paths to the javascript files for each extension? Not sure if this has any use.

```/embeddings```
Self  explanatory

```/object_info```
List of all types of nodes that are available. (Nothing instanced)

```/queue```
What's happening or queued at the moment. Surprisingly comprehensive

```/system_stats```
os, python version, torch devices (like gpus) and vram used

## POST
```/prompt```
https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py

The json data payload must be stored under the name "prompt". In JS, it would look like so :
```javascript
const res = axios.post('http://127.0.0.1:8188/prompt',{
	prompt:json_data_object	
}).then(response => {
  return response;
}).catch(err => {
console.log(err.response.data.error);
});
```
You can get an example of the json_data_object by enabling Dev Mode in the ComfyUI settings, and then clicking the newly added export button.

```/interrupt```
Interrupts the execution of the running prompt

```/queue```
```/history```
In POST, these apis should accept the payloads ```clear:true``` and ```delete:number[]```

## OTHER
You can retrieve the list of all available models from the CheckpointLoader object.
```GET /object_info```
Then CheckpointLoader->input->required->ckpt_name->0

**Comment by darkcurrent** [comment]
> I took a look at how the websocket service works, and created a simple class to use the already existing API. It facilitated my workflow a lot and maybe some of you can find it useful.
> 
> https://github.com/fidecastro/ComfyUI-serverless/

It's a great work

**Comment by zephirusgit** [comment]
Could anyone give me any functional example of the use of the API?
What is complete and that has an example embedded as those of the Save in Api Format?
I can't run the Basic Example:/

**Comment by rsandagon** [comment]
For sample usage you may check this small project I've created. 
https://github.com/rsandagon/comfyui-batch-image-generation

For websocket handling, check [here](https://github.com/rsandagon/comfyui-batch-image-generation/blob/main/app.js#L79C1-L127}

For API endpoint, check [here](https://github.com/rsandagon/comfyui-batch-image-generation/blob/main/app.js#L159-L166)

You need to have the same `client_id` for both API and websocket to get proper websocket updates on the worflow.

**Comment by rvion** [comment]
you can also look at  https://github.com/rvion/CushyStudio 

It is probably the biggest custom frontend around. 

I maintain the most comprehensive set of typings possible, along a higher level type-safe typescript ComfyUI SDK to build workflows with all possible goodies you can imagine.

CushyStudio also generates a whole type-safe SDK for your specific ComfyUI setup, with every custom node, and even model you have installed 

- https://gist.github.com/rvion/f68635427c7d5e9b0846121e4d9e87a7#file-global-d-ts-L6789
- https://gist.github.com/rvion/f68635427c7d5e9b0846121e4d9e87a7#file-global-d-ts-L5324
- https://gist.github.com/rvion/f68635427c7d5e9b0846121e4d9e87a7#file-global-d-ts-L5190

writing workflows and running them is super smooth.

Cushy also feature a scripting engine with hot reload, and a custom gradio-like framework (simpler and type-safe) to build custom apps with UI on top of the ComfyUI SDK. 

Only reason it's not popular yet is that it's not released yet (so no one knows about it), and that it probably has a few quirks here and there. but maybe you'll have fun trying it out. feel free to reach out on discord if you need help:)

**Comment by rvion** [comment]
Cushy also includes higher level API / typings for comfy manager, and host management too, (and other non-comfy things that works well with ComfyUI, like a full programmatic image building API to build masks, etc)

**Comment by zephirusgit** [comment]
Finally I found a page, which explained how to use it in Python and it worked for me
https://medium.com/@yushantripleseven/comfyui-websockets-api-part-1-618175802d5a

https://medium.com/@yushantripleseven/comfyui-using-the-api-part-2-daac17fd2727

**Comment by hippogamesunity** [comment]
> /I could not find an api documentation, so here's what I gleamed from the source code and everyone's comments :
> 
> ## GET
> `/history` Last queued renders, including all nodes used in the prompt, and all output images.
> 
> `/history/{UID}` A specific history entry by uid. When calling `prompt`, the result will contain this uid.
> 
> `/view?filename={FILENAME}` Access the images from history via this.
> 
> `/extensions` paths to the javascript files for each extension.
> 
> `/embeddings` Presumably a list of all embeddings. These aren't available as inputs in any Node, unlike models (see OTHERS).
> 
> `/object_info` List of all types of nodes that are available. (Not the actual node instances, just the node types.) This exposes a lot of important enumerable values in the form of input types.
> 
> `/queue` What's happening or queued at the moment. Surprisingly comprehensive.
> 
> `/system_stats` os, python version, torch devices (like gpus) and vram used.
> 
> ## POST
> `/prompt` https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py
> 
> The json data payload must be stored under the name "prompt". In JS, it would look like so :
> 
> ```js
> const res = await axios.post('http://127.0.0.1:8188/prompt',{
> 	prompt:json_data_object	
> });
> ```
> 
> You can get an example of the json_data_object by enabling Dev Mode in the ComfyUI settings, and then clicking the newly added export button.
> 
> `/interrupt` Interrupts the execution of the running prompt and starts the next one in the queue.
> 
> `/queue` `/history` In POST, these routes should accept the payloads `clear:true` and `delete:number[]` .
> 
> `/upload/image` `/upload/mask` This uploads an image and returns a short path under which the image can be referred to in comfyui. Takes payload 'image' in body.
> 
> ## SYNTAX
> The following typescript definitions are incomplete and may be wrong entirely. Please leave a comment if you spot errors or if you have improvements.
> 
> ```ts
> // This is what apis like "prompt" expect.
> export type JSON_ComfyGraph = {
>     [uid: string|number]: JSON_ComfyNode
> }
> 
> // A node instance.
> export type JSON_ComfyNode = {
>     // The type of the node as found in 'GET /object_info' by key
>     class_type: string;
>     // All incoming connections
>     inputs: {
>         [input_name: string]: JSON_ValueRef;
>     }
> }
> 
> // Any value that can is passed into a ComfyNode
> // This can be either an atomic value, like a string or a number, or a reference to another node's output.
> export type JSON_ValueRef = [target_node_uid: string, output_socket_index: number] | string | number | boolean
> 
> 
> // All possible input/output types. This type is incomplete.
> // string[] represents an enum dropdown.
> export type JSON_ComfyPrimitive = "MODEL" | "CLIP" | "STYLE_MODEL" | "CLIP_VISION_OUTPUT" | "CONTROL_NET" | "UPSCALE_MODEL" | "CLIP_VISION" | "VAE" | "LATENT" | "INT" | "FLOAT" | "IMAGE" | "TEXT" | "CONDITIONING" | "EXTRA_PNGINFO" | "MASK" | string[];
> 
> // Some types accept options like restrictions or special ui operations. So they are wrapped in an array of type + options
> export type JSON_ComfyPrimitiveDeclaration = 
> // An empty array means the name of the output/input is the same as the type. Case insensitive. Eg an output named 'latent' defaults to type "LATENT".
> [] 
> | [JSON_ComfyPrimitive]
> | [
>     "INT" | "FLOAT",
>     {
>         default?: number,
>         min?: number,
>         max?: number,
>         step?: number,
>         round?: number
>     }
> ]
> | [
>     "TEXT"|string[],
>     {
>         multiline?:boolean,
>         default?:string
>     }
> ]
> | [
>     "IMAGE"|string[],
>     {
>         image_upload?:boolean,
>         default?:string
>     }
> ]
> 
> // This is what apis like "object_info" return.
> export type JSON_ComfyNodeTypes = {
>     [key: string]: {
>         // This is what creates the submenus in the context menu.
>         category: string,
>         // Verbal description of the node for use in the ui.
>         description: string,
>         // The name which should be displayed in the editor.
>         display_name: string,
>         input: {
>             // List of all input types
>             required: {
>                 [name: string]: JSON_ComfyPrimitiveDeclaration
>             },
>             hidden: {
>                 [name: string]: JSON_ComfyPrimitiveDeclaration
>             }
>         },
>         // Unique name
>         name: string,
>         // Unique names of all the outputs
>         output: string[],
>         // Is the output a list?
>         output_is_list: boolean[],
>         // Labels of all the outputs
>         output_name: string[],
>         // Is this node an output? Useful for evaluating if a graph is valid.
>         output_node: boolean;
>     }
> }
> 
> // This is what apis like "history" return.
> export type JSON_History = {
>     [uid: string]: JSON_HistoryEntry;
> }
> 
> export type JSON_HistoryEntry = {
>     prompt: [id_maybe: number, uid:string, list_of_used_nodes:JSON_ComfyGraph, no_idea:any, no_idea2:[string]];
>     outputs: {
>         images: JSON_ImageReference[];
>     }[];
> }
> 
> export type JSON_ImageReference = {
>     filename: string;
>     subfolder: string;
>     type: "output";
> }
> ```
> 
> ## OTHER
> You can retrieve the list of all available models from the CheckpointLoader object. `GET /object_info` Then CheckpointLoader->input->required->ckpt_name->0 .

Thanks, this should be added to wiki)

**Comment by hippogamesunity** [comment]
Is there any way to cleare the output folder with API?

**Comment by CrossPr0duct** [comment]
@comfyanonymous is there a way to turn off nodes other than setting strength it doesn't seem like the api version of a workflow allows mode modification

**Comment by hippogamesunity** [comment]
> @comfyanonymous is there a way to turn off nodes other than setting strength it doesn't seem like the api version of a workflow allows mode modification

You can create xml workflows on fly and pass them to /promp with POST. Also I've found a 3rd article with API description based on code analysics.

Endpoints:

@routes.get('/ws')
# Called when establishing a ws connection

@routes.get("/")
# Serves index.html file when the root URL is accessed

@routes.get("/embeddings")
# Returns list of embeddings in embeddings folder

@routes.get("/extensions")
# Returns list of core and custom extensions in javascript.

@routes.get("/view")
# Get image to view, get history first, select filename, load that image.

@routes.get("/view_metadata/{folder_name}")
# Takes in folder name and safetensors file, and returns
# metadata (model hashes, recipes, and parameters etc)
# Not all files will contain metadata. some might just return {"format": "pt"}

@routes.get("/system_stats")
# Server system stats

@routes.get("/prompt")
# Only really returns total number of queue items remaining

@routes.get("/object_info")
# Outputs information on all available nodes inc. custom nodes

@routes.get("/object_info/{node_class}")
# Outputs information on a specific node given the class name

@routes.get("/history")
# Gets the history of all completed jobs (prompts) and
# their outputs (saved files)

@routes.get("/history/{prompt_id}")
# Gets the history of a completed job (prompt)
# and its output based on a prompt_id

@routes.get("/queue")
# Gets queues (running and pending)

@routes.post("/prompt")
# Posts your prompt/workflow and adds to queue
# The one we've been using this whole time)

@routes.post("/queue")
# Clears entire pending queue
# Or delete a specific item in the pending queue

@routes.post("/interrupt")
# Interrupts the current running job

@routes.post("/history")
# Similar to queue(POST) (clear/delete). Clears the entire history
# Or deletes a specific job from history

@routes.post("/upload/image")
# Upload an image places it in input folder

@routes.post("/upload/mask")
# Upload an image mask merges it with a specified image that already exist
# and saves it

**Comment by robinjhuang** [comment]
Closing after a week of inactivity.

**Comment by teodor-krastev** [comment]
Hi there,

is there a way to read via API the front UI parameters like width, height, cfg, etc. before doing anything?

Cheers
Theo

**Comment by ltdrdata** [comment]
> Hi there,
> 
> is there a way to read via API the front UI parameters like width, height, cfg, etc. before doing anything?
> 
> Cheers Theo

The question is incorrect.
You need to create the front data (i.e., prompt) and send it via API.
The backend doesn't have the front end's data.

**Comment by teodor-krastev** [comment]
Thank you ltdrdata for your prompt reply. I don't think my question is incorrect, simply the answer is NO. The backend acts as a server to the front end and towards API as clients.
Have a lovely weekend!
Theo

**Comment by teodor-krastev** [comment]
For anyone interested, I have found a "dirty" way to read the user web interface. If you execute an image generation from web UI and then get "http://127.0.0.1:8188/history" (without promptId) you will have the parameters from web UI in json format.

**Comment by saurabhthesuperhero** [comment]
@ltdrdata  Hi do you know how can i create prompt, i am suing object info but for bsic workflow like lora etc its working but not for complex ones ::

`private fun analyzeWorkflowForAPIPrompt(uiWorkflow: UiWorkflow): Pair<Set<String>, Map<String, Map<Int, Pair<String, Int>>>> {
    // Set of nodes that will be excluded from the API prompt (only bypassed/muted nodes)
    val excludedNodes = mutableSetOf<String>()

    // Identify nodes to exclude based solely on mode
    for (node in uiWorkflow.nodes) {
        // Exclude nodes that are bypassed/muted (mode = 4)
        if (node.mode == 4) {
            excludedNodes.add(node.id)
            Log.d(TAG, "Excluding bypassed/muted node ${node.id} (type=${node.type}, mode=${node.mode}) from API prompt")
        }
    }

    // Connection remapping: for each node that gets input from an excluded node,
    // remap to get input from the excluded node's input or a suitable alternative.
    val connectionRemapping = mutableMapOf<String, MutableMap<Int, Pair<String, Int>>>()

    // Build maps for easier analysis
    val linkMap = mutableMapOf<Int, UiLink>() // linkId -> UiLink
    val nodeInputs = mutableMapOf<String, MutableMap<Int, Int>>() // nodeId -> (slotIndex -> linkId)
    val nodeOutputs = mutableMapOf<String, MutableMap<Int, MutableList<Int>>>() // nodeId -> (slotIndex -> list of linkIds)

    // Populate linkMap
    uiWorkflow.links.forEach { link ->
        linkMap[link.id] = link
    }

    // Populate nodeInputs
    uiWorkflow.nodes.forEach { node ->
        nodeInputs[node.id] = mutableMapOf()
        node.inputs.forEachIndexed { index, input ->
            if (input.link != null && !input.link.isJsonNull && input.link.isJsonPrimitive && input.link.asJsonPrimitive.isNumber) {
                nodeInputs[node.id]!![index] = input.link.asInt
            }
        }
    }

    // Populate nodeOutputs
    uiWorkflow.nodes.forEach { node ->
        nodeOutputs[node.id] = mutableMapOf()
        node.outputs.forEachIndexed { index, output ->
            if (output.links != null && output.links.isNotEmpty()) {
                nodeOutputs[node.id]!![index] = output.links.toMutableList()
            }
        }
    }

    // Process excluded nodes to remap their connections
    for (excludedNodeId in excludedNodes) {
        // For each output slot of the excluded node, process its links
        val excludedNodeOutputMap = nodeOutputs[excludedNodeId] ?: continue
        for ((outputSlot, links) in excludedNodeOutputMap) {
            for (linkId in links) {
                val link = linkMap[linkId] ?: continue
                val targetNodeId = link.target_id
                val targetSlot = link.target_slot

                // Skip if target node is also excluded
                if (targetNodeId in excludedNodes) continue

                // Get the target node and its input for the target slot
                val targetNode = getNodeById(uiWorkflow, targetNodeId) ?: continue
                if (targetSlot >= targetNode.inputs.size) continue
                val targetInput = targetNode.inputs[targetSlot]
                val expectedType = if (!targetInput.type.isJsonNull && targetInput.type.isJsonPrimitive) {
                    targetInput.type.asString
                } else {
                    ""
                }

                // Special case for muted nodes: skip the connection if no valid input found
                if (targetNode.mode == 4) {
                    // Skip this connection as the target node is muted and the input is required
                    continue
                }

                if (targetNode.type == "SaveImage") {
                    // Special case: For SaveImage nodes, connect to VAEDecode output if possible
                    val vaeDecodeNode = uiWorkflow.nodes.find { it.type == "VAEDecode" && it.id !in excludedNodes }
                    if (vaeDecodeNode != null) {
                        Log.d(TAG, "Remapping SaveImage input: node ${targetNodeId} slot $targetSlot to VAEDecode ${vaeDecodeNode.id} slot 0")
                        connectionRemapping.getOrPut(targetNodeId) { mutableMapOf() }[targetSlot] = Pair(vaeDecodeNode.id, 0)
                    }
                } else {
                    // Try to find the appropriate input remap based on type matching
                    var chosenMapping: Pair<String, Int>? = null
                    var fallbackMapping: Pair<String, Int>? = null

                    // Get all candidate inputs from the excluded node
                    val excludedInputs = nodeInputs[excludedNodeId] ?: continue
                    for ((inputSlot, candidateLinkId) in excludedInputs) {
                        val candidateLink = linkMap[candidateLinkId] ?: continue
                        val candidateSourceNodeId = candidateLink.origin_id
                        val candidateSourceSlot = candidateLink.origin_slot

                        // Skip if candidate source is also excluded
                        if (candidateSourceNodeId in excludedNodes) continue

                        // Save the first found mapping as a fallback
                        if (fallbackMapping == null) {
                            fallbackMapping = Pair(candidateSourceNodeId, candidateSourceSlot)
                        }

                        // Try to obtain candidate type from the excluded node’s input at the candidate slot
                        if (inputSlot < targetNode.inputs.size) {
                            val candidateInput = targetNode.inputs[inputSlot]
                            val candidateType = if (!candidateInput.type.isJsonNull && candidateInput.type.isJsonPrimitive) {
                                candidateInput.type.asString
                            } else {
                                ""
                            }
                            if (candidateType == expectedType) {
                                chosenMapping = Pair(candidateSourceNodeId, candidateSourceSlot)
                                break
                            }
                        }
                    }

                    // Apply the chosen mapping or fallback
                    val mappingToApply = chosenMapping ?: fallbackMapping
                    if (mappingToApply != null) {
                        connectionRemapping.getOrPut(targetNodeId) { mutableMapOf() }[targetSlot] = mappingToApply
                        Log.d(TAG, "Remapped: target node $targetNodeId slot $targetSlot now uses source ${mappingToApply.first} slot ${mappingToApply.second}")
                    } else {
                        Log.d(TAG, "Could not find a suitable input remap for node $targetNodeId slot $targetSlot")
                    }
                }
            }
        }
    }

    // Return the set of nodes to exclude and the connection remapping
    return Pair(excludedNodes, connectionRemapping)
}
`
