### ISSUE TITLE
Show nodes that failed validation from `/prompt` input

### ISSUE THREAD

**Issue by space-nuko** [comfyanonymous/ComfyUI#681]
It would be a hash with fields like `nodeID`, `inputName`, `message`, `details` and would contain the actual value/expected range in the response

**Comment by comfyanonymous** [comment]
No fields yet but it returns a list of the nodes that failed validation: https://github.com/comfyanonymous/ComfyUI/commit/ffc56c53c9cccfcc21c92fe14cb095bb32ea2744
