### ISSUE TITLE
Confusion -int, float, bool

### ISSUE THREAD

**Issue by pennyvc** [comfyanonymous/ComfyUI#685]
why do the values for nodes using these inputs always have .000 on the end?

Now im no coder. but setting steps to 10.242  is probably not a good thing?
theres some messy stuff going on with numerical inputs in comfyUI. and its forcing me to have to open a text box and input numbers instead of using the click drag method.

I understand that behind the scenes, its probably doing the right thing, but user interface wise, it makes working with it kinda annoying.

![Capture](https://github.com/comfyanonymous/ComfyUI/assets/128430314/bc075fe7-20f8-44f8-8f0f-779d9965fc77)

Now, i could be wrong, but I figured it should get a mention.

edit: i mention bool, but theres no non modded use of this yet, but the WAS nodes suffer the same issue.

**Comment by comfyanonymous** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/121283862/53f9d38f-9387-4ad2-b041-6e84df55754b)

This is how it looks for me. Are you on the latest ComfyUI?

**Comment by pennyvc** [comment]
I thought I was >.< apologies
