### ISSUE TITLE
Image generated from API doesn't load the workflow on the page

### ISSUE THREAD

**Issue by jn-jairo** [comfyanonymous/ComfyUI#69]
I generated images using the basic_api_example.py but when I try to drag them into the page, it doesn't load the workflow.

I checked the difference between the metadata of the image generated inside the page and from the api and the api images don't have the workflow metadata.

**Comment by comfyanonymous** [comment]
That's normal the workflow metadata is generated by the UI itself. The api prompt format doesn't contain node sized, positions, etc...

Importing workflows from only the api prompt format is planned though.

**Comment by jn-jairo** [comment]
Thank you
