### ISSUE TITLE
[Feature request] Load images by dropping it into UI

### ISSUE THREAD

**Issue by ksorah1** [comfyanonymous/ComfyUI#70]
Hello,

As the title says. Loading a picture for the UI, ControlNET... etc, mean you have to move into folders each time. It's really really irritating. 

(Great UI gg)

**Comment by comfyanonymous** [comment]
The LoadImage node should have a button to "upload" images.

**Comment by ksorah1** [comment]
My English is rough, but I'm not talking about that.

A function to load the images by moving them in the browser window would be welcome, because navigating from one directory to another on each module and each operation is unpleasant.

**Comment by comfyanonymous** [comment]
Oh I understand. That might be an interesting feature to have.

**Comment by ksorah1** [comment]
Cool thank you !

**Comment by ksorah1** [comment]
two other improvements :

input text boxes (e.g. the prompt) have a problem: when you select the text and move the cursor outside the box, it deselects, it's annoying.

it could be cool to see the image used, on the controlNET module

Your UI is very good, it really replace 1111 for several reasons.

**Comment by ksorah1** [comment]
4 - right click on "Queue Prompt" to reduce the queue.
![2023-03-14 22_59_27-aezaeazddez0000000003 jpg - ACDSee Pro 10](https://user-images.githubusercontent.com/112913359/225151147-acc25dec-3854-4363-83f7-363026ab8df9.jpg)

5 - The possibility to delete a group with all its content.

6 - When you refresh the page, the view is not centered on the modules.

**Comment by ksorah1** [comment]
9 - An excellent trick I think : a new module that has several states and where you can "plug in" all possible connections, and return all possible connections. I explain: for example you want a state of this module that uses a ckpt, and another state that uses LORA, so you create a state 1 of this module that is connected to the ckpt_loader, and a state 2 connected to the LORA_loader, and you can change the state of the module in 1 click.

**Comment by comfyanonymous** [comment]
This has been implemented for a while now.
