### ISSUE TITLE
Traceback error (How to fix?)

### ISSUE THREAD

**Issue by rethink-studios** [comfyanonymous/ComfyUI#705]
Hey Team,
How do I fix this traceback error:

G:\StableDiffusion\ComfyUI\update>..\python_embeded\python.exe .\update.py ..\ComfyUI\
Traceback (most recent call last):
  File "G:\StableDiffusion\ComfyUI\update\update.py", line 45, in <module>
    repo = pygit2.Repository(str(sys.argv[1]))
  File "G:\StableDiffusion\ComfyUI\python_embeded\lib\site-packages\pygit2\repository.py", line 1759, in __init__
    path_backend = init_file_backend(path, flags)
_pygit2.GitError: ..\ComfyUI\: repository path 'G:/StableDiffusion/ComfyUI/ComfyUI/' is not owned by current user

Thanks in advance!

**Comment by comfyanonymous** [comment]
Try replacing the update.py in the update directory with the one in this zip:
[update.zip](https://github.com/comfyanonymous/ComfyUI/files/11592790/update.zip)
