### ISSUE TITLE
Bypass mechanism for muted nodes?

### ISSUE THREAD

**Issue by melMass** [comfyanonymous/ComfyUI#706]
Hi,

Sorry if it's a duplicate, but I was wondering if there could be a way to specify what happens when a node is muted?
For instance a method for custom nodes that could specify the muted output (in my case mostly passing the input) for now nothing get's sent

Thanks

**Comment by space-nuko** [comment]
Could there be a frontend node that picks the first non-muted output and forwards it? Here is one I made for my own project

<img width="1054" alt="2023-05-29 17_24_09-http___192 168 1 120_3000_# - Chromium" src="https://github.com/comfyanonymous/ComfyUI/assets/24979496/d388c720-4ec4-46a2-b31c-7c3b8935bb27">

**Comment by DoogeJ** [comment]
> Could there be a frontend node that picks the first non-muted output and forwards it? Here is one I made for my own project
> 
> <img alt="2023-05-29 17_24_09-http___192 168 1 120_3000_# - Chromium" width="1054" src="https://user-images.githubusercontent.com/24979496/241813151-d388c720-4ec4-46a2-b31c-7c3b8935bb27.png">

This looks amazing. Did you share this somewhere perhaps? 👀

**Comment by melMass** [comment]
I just learned that this is basically how the new CTLR+B works (By pass)

**Comment by ghostsquad** [comment]
@DoogeJ can you publish this node?

**Comment by DoogeJ** [comment]
@ghostsquad I think you meant to tag @space-nuko 

I asked for the same

**Comment by ghostsquad** [comment]
> @ghostsquad I think you meant to tag @space-nuko
> 
> I asked for the same

Yep! I grabbed the wrong name. Thanks! 😛

**Comment by akselsy** [comment]
Any Switch by rgthree works for me.

**Comment by ghostsquad** [comment]
> Any Switch by rgthree works for me.

Ya, I've found this works well for me too. :)

**Comment by shmilyfuu** [comment]
> Could there be a frontend node that picks the first non-muted output and forwards it? Here is one I made for my own project
> 
> <img alt="2023-05-29 17_24_09-http___192 168 1 120_3000_# - Chromium" width="1054" src="https://private-user-images.githubusercontent.com/24979496/241813151-d388c720-4ec4-46a2-b31c-7c3b8935bb27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTEwMTgsIm5iZiI6MTcyMzQ1MDcxOCwicGF0aCI6Ii8yNDk3OTQ5Ni8yNDE4MTMxNTEtZDM4OGM3MjAtNGVjNC00NmEyLWIzMWMtN2MzYjg5MzViYjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA4MTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZjY3ZGZmMzZmMzdjYzYwOGVhOTExYzk0MTlkZjljYTYxMDYxZDA0MTRlOGE4YzA0NzUzMDNjNDkxZjUwZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZZHa4MaG0G1yw10tiXhaTkONrGEUwtgCB4bg0OzMyE">

Would you happen to have any plans to release it? It would be incredibly useful.
