### ISSUE TITLE
Running on CPU only

### ISSUE THREAD

**Issue by stalker168** [comfyanonymous/ComfyUI#718]
Please tell me how I can run ComfyUI on Google Colab using only CPU.
Sometimes I can't use it because of the unavailability of the GPU.

**Comment by space-nuko** [comment]
You can pass the `--cpu` flag to `main.py`

**Comment by MathieuBusiness999** [comment]
can you elaborate more please ?

**Comment by MathieuBusiness999** [comment]
he mean in the note book last line where you run main.py you change the line --don't-use-server to --cpu but it's way slower like 10 minutes a pitcure with text to image

**Comment by MathieuBusiness999** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/136890088/1eaec62b-c578-4adb-9b0a-a4eaa0d17b5c)

**Comment by robinjhuang** [comment]
`python main.py --cpu`

**Comment by ArdeniusAI** [comment]
You can use Comfyui-cpu trimmed down version here https://github.com/ArdeniusAI/ComfyUI-cpu
