### ISSUE TITLE
cant get Textual Inversion to work I have tried all the example from the embedding example page and still not working 

### ISSUE THREAD

**Issue by tasslehawk** [comfyanonymous/ComfyUI#740]
I have tried all the example from the embedding example page and still not working and no matter what way i add it to the prompt it does not work. I used it in automatic1111 with the same Model and it works fine. what could I be doing wrong?

**Comment by comfyanonymous** [comment]
They are used slightly differently in ComfyUI: https://comfyanonymous.github.io/ComfyUI_examples/textual_inversion_embeddings/

**Comment by tasslehawk** [comment]
I did everything on that page all the different ways listed to add it to prompt ans still not working

**Comment by tasslehawk** [comment]
Both Model and Textual Inversion are SD 1.5

**Comment by tasslehawk** [comment]
Tried other Textual Inversion and it worked fine so must me broken. Decided to build a LORA to do the same thing and it worked better. Thank you
