### ISSUE TITLE
White theme is not white

### ISSUE THREAD

**Issue by linonetwo** [comfyanonymous/ComfyUI#741]
![图片](https://github.com/comfyanonymous/ComfyUI/assets/3746270/115a3c03-ef6c-4fa0-8ad0-3c9b4af7aa66)

![图片](https://github.com/comfyanonymous/ComfyUI/assets/3746270/8f31bd39-36e2-411c-b808-923e69703379)

Even change the bg-color in the palette, the black in the canvas is not changed.

**Comment by WASasquatch** [comment]
The canvas background is a image, not CSS color.

It should probably have a override so you can provide your own image base64 string @comfyanonymous . 

Here is a version with a white BG image encoded in it. 
[litegraph.core_white_bg.zip](https://github.com/comfyanonymous/ComfyUI/files/11691626/litegraph.core_white_bg.zip)

**Comment by linonetwo** [comment]
LOL looks like a Hidden Photo Optical Illusion, reveal low frequency pattern when you zoom out.
