### ISSUE TITLE
[Feature request] Keyboard shortcut to add queue

### ISSUE THREAD

**Issue by geeknessfr** [comfyanonymous/ComfyUI#76]
In A1111 when you press CTRL+Enter, it launches the generation... and.. maybe it's only me, but when I modify the prompt I use a lot this shortcut to view the changes rapidly... ;)

Maybe I missed a thing and there's the same behaviour on Comfy ?

**Comment by guzuligo** [comment]
Yeah, I've been working on it and finding myself using A1111 keyboard shortcut at first.
And after a while, I found myself hitting blender keyboard shortcuts.

It'd be really convenient

**Comment by geeknessfr** [comment]
Thanks guys ! As it's added and merged I close this issue,
