### ISSUE TITLE
Torch version chaos

### ISSUE THREAD

**Issue by JoBilert** [comfyanonymous/ComfyUI#77]
I tried following the NVIDIA installation guide of your ReadMe, but whenever i try to install xformers i get the following:
```
torchvision 0.15.0+cu117 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchaudio 2.0.0+cu117 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
```
can you help me resolve this problem?

**Comment by comfyanonymous** [comment]
try uninstalling torchvision and torchaudio with: pip uninstall torchvision torchaudio

**Comment by rakete** [comment]
I had the same problem, got it to work by first uninstalling torch, torchvision and torchaudion, then installing with  torch==1.13.1+cu117:
```
pip uninstall torch torchvision torchaudio
pip install torch==1.13.1+cu117 torchvision torchaudio -f https://download.pytorch.org/whl/torch_stable.html --extra-index-url https://download.pytorch.org/whl/cu118
```

**Comment by AntonyDwornikBuW** [comment]
It seems like there is a version compatibility issue between the version of PyTorch that you have installed and the version of torchvision and torchaudio that you are trying to install. The version of PyTorch you have installed is 1.13.1, while the versions of torchvision and torchaudio you are trying to install require PyTorch version 2.0.0.

One solution would be to upgrade your PyTorch installation to version 2.0.0, which is compatible with the versions of torchvision and torchaudio you are trying to install. You can do this by running the following command:

bash
Copy code
pip install torch==2.0.0 -f https://download.pytorch.org/whl/cu117/torch_stable.html
Once you have upgraded PyTorch to version 2.0.0, you should be able to install torchvision and torchaudio without any issues.

**Comment by robinjhuang** [comment]
Closing as problem seems to be resolved.
