### ISSUE TITLE
Error when running "Update_all.bat"

### ISSUE THREAD

**Issue by rethink-studios** [comfyanonymous/ComfyUI#78]
Ran update_all.bat and received this error:

Collecting xformers
  Using cached xformers-0.0.16-cp310-cp310-win_amd64.whl (40.0 MB)
  Using cached xformers-0.0.13.tar.gz (292 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\RETHINK\AppData\Local\Temp\pip-install-vlaokrbw\xformers_ae0f169475684b26844e6512005ab351\setup.py", line 239, in <module>
          ext_modules=get_extensions(),
        File "C:\Users\RETHINK\AppData\Local\Temp\pip-install-vlaokrbw\xformers_ae0f169475684b26844e6512005ab351\setup.py", line 157, in get_extensions
          raise RuntimeError(
      RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

D:\ComfyUI\update>pause

How can I fix?

**Comment by comfyanonymous** [comment]
You might want to try clearing your pip cache folder.

You should not really be using update_all.bat to update unless you want new versions of python packages for some reason, 

update_comfyui_only.bat is the recommended way to update.

**Comment by comfyanonymous** [comment]
I checked and it's because pytorch released pytorch 2.0 on pip but xformers hasn't updated yet.

You can ignore the error until they fix it.

**Comment by rethink-studios** [comment]
(( thumbs ))
