### ISSUE TITLE
Image reproducibility between different GPUs

### ISSUE THREAD

**Issue by aelitbythesea** [comfyanonymous/ComfyUI#788]
I have two different PCs, one mount an RTX 3080 while the other a GTX 1660. Problem is, the image generated varies based on which PC I use, even with great differences, and it's weird because ComfyUI supposedly creates the noise with the CPU, so the result should be the same.

Even the boot log is the same, except for the obvious differences in total VRAM:

```
Total VRAM 10240 MB, total RAM 16238 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080
Using xformers cross attention
```

```
Total VRAM 6144 MB, total RAM 16333 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER
Using xformers cross attention
```

And here's the same image, with exactly the same parameters, generated by the two PCs:
![geforce_rtx_3080](https://github.com/comfyanonymous/ComfyUI/assets/137496930/694f8f57-67b2-4d2f-a724-bb4d13ac42ac)
![geforce_gtx_1660_super](https://github.com/comfyanonymous/ComfyUI/assets/137496930/fb023283-ebde-4e14-9956-afbbcb3c9809)

**Comment by KaruroChori** [comment]
Based on your configuration some of the steps involved might not be deterministic.
From what I know xformers are known to result in different results for the same seed.

**Comment by comfyanonymous** [comment]
It's because ComfyUI uses fp32 on the 1660 and fp16 on the 3080 and the SDE sampler is one that greatly amplifies tiny differences like the imprecision between fp32 and fp16 sampling.

If you: --force-fp32 on the 3080 you should get the same results.

**Comment by aelitbythesea** [comment]
> If you: --force-fp32 on the 3080 you should get the same results.

I tried that but the result wasn't the same, it just took twice as long to output.

**Comment by comfyanonymous** [comment]
Does it happen on other samplers like euler or ddim?

**Comment by aelitbythesea** [comment]
> Does it happen on other samplers like euler or ddim?

I tried with DDIM and UniPC, there's some slight change in the background but it doesn't affect the whole composition like with SDE Karras. Euler A was completely different as expected. I also tried 2M both Normal and Karras, the output of the Normal scheduler was identic, without even smaller changes, while the Karras scheduler behaved as with SDE.

**Comment by aelitbythesea** [comment]
> Does it happen on other samplers like euler or ddim?

I tried with DDIM and UniPC, there's some slight change in the background but it doesn't affect the whole composition like with SDE Karras. Euler A was completely different as expected. I also tried 2M both Normal and Karras, changes were slight with both schedulers.
