### ISSUE TITLE
feat: LoRA as prompt

### ISSUE THREAD

**Issue by jjangga0214** [comfyanonymous/ComfyUI#794]
Hi!

As we know, in A1111 webui, LoRA(and LyCORIS) is used as prompt.
IMHO, LoRA as a prompt (as well as node) can be convenient. 

## Simplicity

When using many LoRAs(e.g. for character, fashion, background, etc), it becomes easily bloated.

<img width="606" alt="스크린샷 2023-06-25 오후 11 23 29" src="https://github.com/comfyanonymous/ComfyUI/assets/28584151/9afd563d-c6ee-495e-8d18-40192552553b">

Text prompts can reduce this.

## Sharability

People tend to share EXIF in A1111 format. 
Text prompt is good for copy-and-paste.
Sometimes what users want is getting started as rapid as possible.
That's because they are so excited by new ideas that just checking out the result ASAP has higher priority.

## Experiment

Users of ComfyUI are more hard-core than those of A1111.
They experiment a lot.
In many cases, text is faster to edit (with autocompletion or text editors).
For example, on A1111 webui, I use find-and-replace feature in VSCode for automatically replacing multiple LoRA weights at once.
What's more, I "generate" a text of list of LoRA with specific weights and additional args from a simple script(like .js, .py, or .sh) for experiments.
This practice saves time a lot and thus essential in my workflow.
 
## Conclusion

I like node-based workflow.
But things especially like LoRA can benefit us by being prompt.
Prompt grammar is DSL, and well-defined DSL becomes really productive.

How do you think?

Thank you :)

**Comment by david9039** [comment]
The Efficiency Nodes extension (https://github.com/LucianoCirino/efficiency-nodes-comfyui) has a three Lora stacker node, as well as a checkpoint loader with one optional Lora.

**Comment by tildebyte** [comment]
I *think* the ask here is something like allowing `<lora:foo.safetensors:1.4>` syntax, or something similar to how embeddings are done.

**Comment by knoopx** [comment]
fyi, [ImpactWildcardEncode](https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/2263985df93c3ac81edb5c4ec477a44d2c5d5dcd/README.md?plain=1#L146) node does this among other things

**Comment by highfiiv** [comment]
Looks like a native ComfyUI lora-stacker would solve this (according to the image he posted)

**Comment by ltdrdata** [comment]
I think it's appropriate for custom nodes to handle the convenience feature of replacing workflow configurations through text prompts.

**Comment by tildebyte** [comment]
Based on carefully re-reading OP, this is *definitely* about parsing LoRA embeds from prompts - nothing to do with stacking nodes or any of that.

>  LoRA as a prompt...can be convenient

> Text prompt is good for copy-and-paste.

> In many cases, text is faster to edit (with autocompletion or text editors).
> I use find-and-replace feature in VSCode for automatically replacing multiple LoRA weights at once

> I "generate" a text of list of LoRA with specific weights and additional args from a simple script(like .js, .py, or .sh)...

>But things especially like LoRA can benefit us by being prompt.
> Prompt grammar is DSL, and well-defined DSL becomes really productive.
