### ISSUE TITLE
[Bug] sample() got an unexpected keyword argument 'seed'

### ISSUE THREAD

**Issue by Lightsockie** [comfyanonymous/ComfyUI#797]
Just pulled in updates and started getting an error whenever I try to proompt. The issue was introduced in this commit: https://github.com/comfyanonymous/ComfyUI/commit/4eab00e14bc0b52a9c688486d7ee8b392e01020d . After reverting to the commit just before that one, the error goes away

I've loaded the default workflow and can confirm the issue exists there (so despite that commit msg, seems like it applies to non-SDEs like Euler?). Seemingly happens for all samplers

me:
```
Kernel: 6.3.6-artix1-1
Device: cuda:0 AMD Radeon RX 7900 XT
Build: 4eab00e14bc0b52a9c688486d7ee8b392e01020d
```
Torch vers:
```
torch==2.1.0.dev20230613+rocm5.5
torchaudio==2.1.0.dev20230613+rocm5.4.2
torchdiffeq==0.2.3
torchmetrics==0.11.4
torchsde==0.2.5
torchvision==0.16.0.dev20230613+rocm5.4.2
```

Error:
```
Error occurred when executing KSampler:

sample() got an unexpected keyword argument 'seed'

  File "/home/username/Work/StableDiffusion/ComfyUI/execution.py", line 141, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Work/StableDiffusion/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Work/StableDiffusion/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Work/StableDiffusion/ComfyUI/nodes.py", line 996, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Work/StableDiffusion/ComfyUI/nodes.py", line 966, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Queue size: 0
Extra options
Feed Size...
Image Size...
```

Probably a dupe of https://github.com/comfyanonymous/ComfyUI/issues/792, but they're getting a different error so not sure

**Comment by comfyanonymous** [comment]
That's strange, if you check the commit comfy.comfy.sample does have a seed argument: https://github.com/comfyanonymous/ComfyUI/commit/4eab00e14bc0b52a9c688486d7ee8b392e01020d#diff-2e28093f5c1fe698e3f531ad59f86e68cb6947e7c94f9ce142d2ae6ce0fd7506R68

can you do a: git stash
to see if it fixes your issue?

**Comment by Lightsockie** [comment]
Ah, yep sorry it does work with an unpolluted environment. Someone in /sdg/ mentioned that it was an AIT issue, fixed here https://github.com/hlky/AIT/commit/84ab26f5d77cbfecf1b002366d6cca19d78216e0. I just hadn't pulled in updates for AIT recently. Soz comfy, updating AIT fixes it
