### ISSUE TITLE
feat: interrupt(skip) button

### ISSUE THREAD

**Issue by jjangga0214** [comfyanonymous/ComfyUI#805]
As we know, A1111 webui provides an interrupt(skip) button.
This is useful to save time and resources when real-time preview seems not what the user wants. 
I think it will be good in ComfyUI as well, like below "Queue Prompt" button.
How do you think?
Thank :)

**Comment by comfyanonymous** [comment]
View Queue -> Running -> Cancel

**Comment by jjangga0214** [comment]
@comfyanonymous Thanks a lot!
