### ISSUE TITLE
4gb vram out of memory

### ISSUE THREAD

**Issue by clavar** [comfyanonymous/ComfyUI#81]
1 batch, 128 x 128, 20 steps, 8cfg, euler a.

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 4.00 GiB total capacity; 3.38 GiB already allocated; 0 bytes free; 3.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

It auto detects -lowvram but still cant generate imanges.
I tried -lowvram and -novram still same problem.

this gui works fine 512 x 512 50 steps.
https://github.com/n00mkrad/text2image-gui#features-and-how-to-use-them

I love the idea of your GUI, it looks awesome to learn with it.

**Comment by comfyanonymous** [comment]
Are you using the latest version? I fixed some vram related issues 1 day ago.

What's your GPU?

**Comment by clavar** [comment]
You are totally right, I had a version a day before your fix. Now its working, thanks.

512 x 512 50 steps euler a, gives me an output in ~20s (~3 it/s) with a 3050 ti notebook. Thank you!
