### ISSUE TITLE
Performance is worse than in AUTOMATIC1111

### ISSUE THREAD

**Issue by Yaruze66** [comfyanonymous/ComfyUI#811]
**I used AUTOMATIC1111 1.3.2 with xformers 0.0.20 on RTX 2070 Super:**

1. A1111 gives me 10.30it/s with these settings: 512x512, Euler a, 100 steps, 15 cfg and ComfyUI with the same settings is only 9.70it/s.

3. A1111 generates an image with the same settings (in spoilers) in 41 seconds, and ComfyUI in 54 seconds. Also ComfyUI takes up more VRAM (6400 MB in ComfyUI and 4200 MB in A1111).

<details> 
<summary>AUTOMATIC1111</summary>

![0JHQtdC30YvQvNGP0L3QvdGL0Lk=](https://github.com/comfyanonymous/ComfyUI/assets/138091206/1dc316d9-d729-4815-9998-81d2bf7b3d97)

</details>

<details> 
<summary>ComfyUI</summary>

![0KHQvdC40LzQvtC6INGN0LrRgNCw0L3QsCAyMDIzLTA2LTI5IDExMDIyMA==](https://github.com/comfyanonymous/ComfyUI/assets/138091206/bb615372-5846-4894-ba4c-545ca7dbe3db)

![0KHQvdC40LzQvtC6INGN0LrRgNCw0L3QsCAyMDIzLTA2LTI5IDExNDg0OQ==](https://github.com/comfyanonymous/ComfyUI/assets/138091206/938d865e-2446-41ae-b17c-e9e940fec88f)

</details>

At first I thought that the problem was in LoRA's and High res fix, but even if i compare without them ComfyUI loses A1111... It also seemed to me that in A1111 the faces and eyes are clearer.

I've been using A1111 for about half a year and I really really liked ComfyUI, it's a real breath of fresh air, but I'm somewhat upset by the slower generation. I was hoping ComfyUI would be even faster than the latest version of A1111. What could be the problem? 😞 
Maybe I did something wrong with the nodes? 🤔 

I will be grateful for any help! 😺

**Comment by comfyanonymous** [comment]
Can you show me the console output for a1111 so I can see if there's any large difference in step count and it/s?

**Comment by Yaruze66** [comment]
> Can you show me the console output for a1111 so I can see if there's any large difference in step count and it/s?

Yeah, sure:
<details> 
<summary>A1111 Console output</summary>

![A1111 Console Ouput](https://github.com/comfyanonymous/ComfyUI/assets/138091206/d51c9046-0f5c-4598-b6a6-da3aa6ad6da9)

</details>

**Comment by Yaruze66** [comment]
> Can you show me the console output for a1111 so I can see if there's any large difference in step count and it/s?

Yeah, sure: 

<details> 
<summary>AUTOMATIC1111 Console output</summary>

![A1111 Console Ouput](https://github.com/comfyanonymous/ComfyUI/assets/138091206/510277c3-39fc-48e7-9a8f-2fe1d4f7fc1c)

</details>

**Comment by comfyanonymous** [comment]
What does the "Tile 1/15", etc... mean? If it's doing tiled sampling that's going to be faster than regular sampling.

https://github.com/BlenderNeko/ComfyUI_TiledKSampler

**Comment by Yaruze66** [comment]
> What does the "Tile 1/15", etc... mean? If it's doing tiled sampling that's going to be faster than regular sampling.
> 
> https://github.com/BlenderNeko/ComfyUI_TiledKSampler


I do not know, I do not use any extensions (only lycoris, tagcomplete, controlnet, civitai helper), only basic High res fix 🤔 

![A1111](https://github.com/comfyanonymous/ComfyUI/assets/138091206/9ba69714-d3f8-4934-931d-3ee55e38b0d4)

**Comment by ltdrdata** [comment]
> > What does the "Tile 1/15", etc... mean? If it's doing tiled sampling that's going to be faster than regular sampling.
> > https://github.com/BlenderNeko/ComfyUI_TiledKSampler
> 
> I do not know, I do not use any extensions (only lycoris, tagcomplete, controlnet, civitai helper), only basic High res fix thinking
> 
> ![A1111](https://user-images.githubusercontent.com/138091206/249711394-9ba69714-d3f8-4934-931d-3ee55e38b0d4.png)


A1111 has too many implicit features, making it unclear. However, based on the logs, it appears that tiling has been applied. It would be beneficial to check if hires.fix is responsible for such behavior. Try disabling that option and see if the tiling message still appears.

**Comment by Yaruze66** [comment]
> A1111 has too many implicit features, making it unclear. However, based on the logs, it appears that tiling has been applied. It would be beneficial to check if hires.fix is responsible for such behavior. Try disabling that option and see if the tiling message still appears.

Without High res fix:

![A1111 Console Ouput](https://github.com/comfyanonymous/ComfyUI/assets/138091206/3d0aacd9-7c9f-4f53-ab3c-a95f396b6069)

**Comment by Yaruze66** [comment]
@comfyanonymous performance with "--use-pytorch-cross-attention" is slightly better, but still worse than in the newly installed AUTOMATIC1111 without extensions (even with TiledKSampler or no High res fix at all). In addition, the ComfyUI loads the GPU (CUDA) a couple of percent less than the A1111, but it requires more VRAM. I tried disabling hardware acceleration in browser and Hardware GPU scheduling, but it didn't help (which is quite expected)...

**Comment by MediumMechanism** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/10167550/ff420d72-80c7-4e1f-a274-dbbb3cb1cad1)

Well, yours is doing better than mine. Somewhere off in the distance, I can hear my high school programming teacher screaming in rage because no error message was given. Is there a flag that can be passed to have it tell me what happened between "Got prompt" and um... whatever happened to make it do nothing?

**Comment by comfyanonymous** [comment]
I pushed some performance improvements very recently so try it out again and performance should have improved.


>Well, yours is doing better than mine. Somewhere off in the distance, I can hear my high school programming teacher screaming in rage because no error message was given.

Update your nvidia drivers.

**Comment by Yaruze66** [comment]
@comfyanonymous commit e7bee85 solved my problem. With "--fp16-vae" the performance is now even slightly better than in A1111.

Thanks! 👍

**Comment by roygear** [comment]
is this improvement work for this version?
https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu118_or_cpu.7z

I manually updated ComfyUI, and then added --fp16-vae to run_nvidia_gpu.bat.
But I found no speed improvement.
