### ISSUE TITLE
Lora loading issue since commit earlier today

### ISSUE THREAD

**Issue by bourneash** [comfyanonymous/ComfyUI#819]
After updating today quite a few of my previous workflows will fail now when trying to load a Lora.

I get this error message:
`making attention of type 'vanilla-pytorch' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-pytorch' with 512 in_channels
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/home/user/ComfyUI/execution.py", line 145, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/user/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/user/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/user/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 441, in efficientloader
    model, clip = load_lora(lora_name, ckpt_name, lora_model_strength, lora_clip_strength, my_unique_id,
  File "/home/user/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 293, in load_lora
    lora_model, lora_clip = comfy.sd.load_lora_for_models(ckpt, clip, lora_path, strength_model, strength_clip)
  File "/home/user/ComfyUI/comfy/sd.py", line 506, in load_lora_for_models
    loaded = load_lora(lora, key_map)
  File "/home/user/ComfyUI/comfy/sd.py", line 98, in load_lora
    if alpha_name in lora.keys():
AttributeError: 'str' object has no attribute 'keys'
`

-- 

I've tried with the Efficiency loader, CR Lora Loader, Lora Loader, and Load Lora, all of them fail with the `AttributeError: 'str' object has no attribute 'keys'` error. Oddly enough, the "LoraLoader" is the only way for me to load a Lora now on the latest commit. I've even removed the lora loading nodes and recreated them with the same result, same on a new workspace too.

I rolled back to the commit below and I can load all of my previous workflows and they run without an issue.
6e9f28401f0942f9408dfc6a03abcd37032eec82

Looks like all of the loaders work again. Seems like there were some lora updates in the commits today that might have caused this. Thank you for all the help and support!!!

**Comment by comfyanonymous** [comment]
The issue is this commit and this function specifically:
https://github.com/comfyanonymous/ComfyUI/commit/5a9ddf94eb302f4a7384f7e50eee29355de3dd4f#diff-16fd00518fe6f54047b71d48522725da977410f8c2b77b15f6ba7d7dac85cf4fR503

Instead of taking a path to a lora it now takes a loaded lora because the lora loader node can now cache them between executions for increased speed.

**Comment by ltdrdata** [comment]
The ```Efficiency Loader``` is required update to reflect this patch

**Comment by LucianoCirino** [comment]
Please update to latest commit.
https://github.com/LucianoCirino/efficiency-nodes-comfyui

**Comment by bourneash** [comment]
@LucianoCirino This is testing good, thank you!
