### ISSUE TITLE
5x Slowdown for ControlNet/OpenPose 

### ISSUE THREAD

**Issue by AZmisc** [comfyanonymous/ComfyUI#828]
Hi! The updates from a few days ago had another side effect. The OpenPose ControlNet is now ~5x times slower. 

I attached a file with prompts. There are three successive renders of progressively larger canvas where performance per iteration used to be ~4s/8s/20s. The whole image would take ~280s to render. Without control net the render took ~2s/8s/20s and took about ~230s to render.

Now the ControlNet takes ~40s/22s/90s and takes about ~1200s to render (sometimes as long as ~2000-2500s). But the renders without ContolNet take the same time as before the updates. So, there was something that hit the ControlNet part hard.

<details>
<summary>Performance summary</summary>

![CN-ON summary](https://github.com/comfyanonymous/ComfyUI/assets/47092625/dbea8365-6ed8-4ce6-a9b2-73e5865551db)

</details>
<details>
<summary>Prompt</summary>

![a_12236_](https://github.com/comfyanonymous/ComfyUI/assets/47092625/49d48ba3-cad9-4d9b-ab35-14685e1d4499)

</details>

Thanks!

**Comment by ltdrdata** [comment]
I suspect that it might have switched to shared memory due to a shortage of VRAM. Is the same issue occurring in the latest version?

**Comment by AZmisc** [comment]
> I suspect that it might have switched to shared memory due to a shortage of VRAM. Is the same issue occurring in the latest version?

Sorry, I don't know how to test this hypothesis.
