### ISSUE TITLE
Please provide controlnet for SDXL in ComfyUI

### ISSUE THREAD

**Issue by arnold408** [comfyanonymous/ComfyUI#846]
Please provide controlnet for SDXL in ComfyUI
Thanks

**Comment by nistvan86** [comment]
You cannot use existing SD1.5 / 2.1 ControlNets with this model, those need to be retrained.
SDXL 1.0 supposed to come with ControlNet models once released on July 18th. Though I would not be surprised if only the main model gets released at that time and CNs will follow sometime later.

**Comment by arnold408** [comment]
Thanks a lot for reply.
I will wait for July 18th.
