### ISSUE TITLE
Upscale speed goes very slow almost everytime when opening and generate the first few task

### ISSUE THREAD

**Issue by kri1927** [comfyanonymous/ComfyUI#858]
I haven't used Comfyui since the last day of the last month and I just use it again yesterday but I notice a huge difference in generation speed. When I generate the base pic it usually takes 20-30 seconds to generate one, and now it barely changes cuz it goes up like 30-50 sometimes which I'm not sure if it is normal or weird but the thing that is very clear to me is the upscaler speed that It usually takes like 1:30 to 2 minutes to did one (6-8 it/s) but now it goes up to 8-10 minutes (50 it/s) (yesterday it was being like this but I generate once and swap the model from A to B and back to A and the speed goes normal so I thought it was gone but it wasn't.) today the first task was like 54 it/s and I cancel it and generate it again then it goes down to 35 it/s and has been at around 30+ no matter how many times I swap the model so I let it generate once and the speed goes back to normal. what could be the cause of this? how to fix it? I don't want to wait 10 minutes every time I run the program T_T

Ps. about earlier idk what day it is but I deleted the pip cache in the %appdata% could that be the cause of this?

**Comment by comfyanonymous** [comment]
Update with update/update_comfyui.bat or git pull. It might be fixed now.
