### ISSUE TITLE
[Feature Request] Please provide support for using MPS acceleration on Apple chips

### ISSUE THREAD

**Issue by NextDoorLaoHuang-HF** [comfyanonymous/ComfyUI#86]
I tried to load the comfy ui in the AUTOMATIC1111 webui venv environment, which uses MPS acceleration by default, but I failed. The comfy ui only ran in cpu mode on my m1 mac, which was too slow, and wanted MPS support

**Comment by NextDoorLaoHuang-HF** [comment]
Thank you for your positive response, and if you make any progress on this work, I would be more than happy to help you test and provide feedback

**Comment by linonetwo** [comment]
Please take this as an example: https://github.com/CompVis/stable-diffusion/compare/main...cruller0704:stable-diffusion-intel-mac:main

**Comment by GaidamakUA** [comment]
This would be highly appreciated. I have M1 Mac. And some reasonable python knowledge. I can help, but I need a little guidance how to start.

**Comment by GaidamakUA** [comment]
Thank you. Here is pull request. It works on my M1. DDIM sampler doesn't work, because it only accepts cuda device for now. Maybe some other stuff is broken, but basic flow works fine with euler sampler.
https://github.com/comfyanonymous/ComfyUI/pull/244

**Comment by comfyanonymous** [comment]
I merged the PR and the DDIM sampler should also work now.

**Comment by GaidamakUA** [comment]
@comfyanonymous I guess, you can close issue now.

**Comment by comfyanonymous** [comment]
ok make another issue if there's a specific problem with MPS support.

**Comment by or2008** [comment]
> conda activate comfyui && python ./main.py

thanks!
