### ISSUE TITLE
SDXL and poor performance on 3060 12G

### ISSUE THREAD

**Issue by franzkruhm** [comfyanonymous/ComfyUI#869]
Hi,
I just installed Comfy using the standalone for Win10, I used the update script and I am using the no ema safetensors with the demo workflow provided by the person who provided said pruned safetensors for SDXL 0.9

My machine is a laptop with external RTX 3060 12G, the laptop has 16gigs of RAM.

Rendering an image at 2048x1080 takes about 117 seconds (including the refiner pass); I've seen people claim to be able to reach 17s seconds for 4096x4096 on a 3070, which quite surprises me. I am using nvidia driver 531.41 so that should be okay and I have nothing else running...

Something to note is that VRAM using seems to remain fairly low (max 8gigs and keeps fluctuating between "passes", it seems like Comfy keeps loading the models in VRAM in between, so its 0 gig usage to 8gigs... on and off); the RAM usage is very high regularly paging

I usually use AUTOMATIC1111 and this would happen if my options were set to offload to RAM but I dont see how to check for this in Comfy.

**Comment by comfyanonymous** [comment]
On 16GB ram you are better off using only the base or refining with a SD1.x model instead of the refiner. Right now refiner + base takes maybe ~15GB ram together so it only works well on 16GB ram if you have nothing else ram hungry running on your computer.

This might improve a bit in the future though.

**Comment by franzkruhm** [comment]
Ok I decided to download more RAM :-)
