### ISSUE TITLE
Does ComfyUI have a venv?

### ISSUE THREAD

**Issue by Renaldas111** [comfyanonymous/ComfyUI#872]
If yes, how can I activate it?
I am not very advanced in all this stuff, but being acquainted to A1111 I saw and knew how to activate the venv. Here I dont see any venv folders and any activate.bat or smth similar anywhere. How can I see which packages are installed under ComfyUI venv, or it just runs "the way I dont understand and dont need to understand", just need to use the program as it is without going into the things which are too difficult to grasp for an amateur user?
Thanks!

**Comment by comfyanonymous** [comment]
If you are talking about the standalone windows version it uses embedded python instead of a venv.

**Comment by Renaldas111** [comment]
Thanks for an answer! It looks this is not for my amateur knowledge, as I dont even have a slightest grasp what an "embedded python" is . Lets close it :)
