### ISSUE TITLE
[Feature Request] Will Xformer be added in the future?

### ISSUE THREAD

**Issue by az2415112980** [comfyanonymous/ComfyUI#88]
Will Xformer be added in the future to solve the vrom usage problem?

**Comment by comfyanonymous** [comment]
Xformers is already supported. The regular standalone windows build comes with xformers in it.

**Comment by leppie** [comment]
> Xformers is already supported. The regular standalone windows build comes with xformers in it.

Are you building your own wheel for Torch 2.0.0?

**Comment by comfyanonymous** [comment]
No, the standalone with stable pytorch still has pytorch 1.13 in it. I have not updated it with stable pytorch 2.0 because I'm waiting for an xformers build.

The standalone with nightly pytorch uses the new pytorch2.0 cross attention functions instead of xformers which are supposed to be faster according to pytorch but that might not actually be the case.

**Comment by leppie** [comment]
> The standalone with nightly pytorch uses the new pytorch2.0 cross attention functions instead of xformers which are supposed to be faster according to pytorch but that might not actually be the case.

From quick testing on auto1111, it seems a little bit slower for small images, but gets quite slow on big images. Also a bit more vram hungry. 

I should have unofficial xformers wheel soon and report back.

**Comment by leppie** [comment]
Here is a build for xformers targeting torch 2.0.0 

https://github.com/ArrowM/xformers/releases/tag/xformers-0.0.17%2Bb6be33a.d20230315-cp310-cu118

Some comparitive tests (without vs with):

1. was 31 secs, now 25 secs
2. was 01:19, now 00:39
3. was 00:52, now 00:28

vram usage was more without it, but back to normal usage now with it.

**Comment by comfyanonymous** [comment]
Since I have been shipping the standalone build with pytorch2.0 + xformers for a few days now I think this is solved completely: https://github.com/comfyanonymous/ComfyUI/releases
