### ISSUE TITLE
Anyone has SDXL + LyCORIS Lora safetensors workflow?

### ISSUE THREAD

**Issue by FurkanGozukara** [comfyanonymous/ComfyUI#880]
I am doing a Kohya LoRA training atm

I need a workflow for using SDXL 0.9 safetensors + LoRA workflow + refiner

**Comment by comfyanonymous** [comment]
For a basic explanation how to use loras see the examples here: https://comfyanonymous.github.io/ComfyUI_examples/lora/

**Comment by FurkanGozukara** [comment]
> For a basic explanation how to use loras see the examples here: https://comfyanonymous.github.io/ComfyUI_examples/lora/

thankfully someone from your room gave me workflow.

i am gonna test and hopefully will make a tutorial video

this is my channel : https://www.youtube.com/SECourses

**Comment by michelleplur** [comment]
Would love to see that tutorial!

**Comment by Mikerhinos** [comment]
I think that I read that Loras from SD are compatible with SDXL but the one I try gives me an error at weight calculation (RuntimeError: shape '[5120, 1280]' is invalid for input of size 2359296).

**Comment by ltdrdata** [comment]
> I think that I read that Loras from SD are compatible with SDXL but the one I try gives me an error at weight calculation (RuntimeError: shape '[5120, 1280]' is invalid for input of size 2359296).
> 
> Edit : they need to be trained on SDXL model I'm just dumb sometimes lol.

No they are incompatible.
