### ISSUE TITLE
Latest litegraph breaks on Firefox 102ESR

### ISSUE THREAD

**Issue by city96** [comfyanonymous/ComfyUI#883]
The commit that updated litegraph to latest ( https://github.com/comfyanonymous/ComfyUI/commit/880c9b928befa6a7dda0a22a4569e3bfc56e0ca8 ) broke support for Extended Support Release Firefox version 102.

Specifically, the roundRect code removed in that commit is only [natively supported in Firefox 112+.](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect#browser_compatibility)

![image](https://github.com/comfyanonymous/ComfyUI/assets/125218114/2c974c92-9cd0-4685-8f50-d305144b1962)

**Comment by comfyanonymous** [comment]
Should be fixed now: https://github.com/comfyanonymous/ComfyUI/commit/90aa59709985ffa1b02b6330b7720ed399fbf4df
