### ISSUE TITLE
CLIPSetLastLayer is permanent

### ISSUE THREAD

**Issue by wlad-pescenko** [comfyanonymous/ComfyUI#894]
Hello,

I randomly found an issue with the CLIPSetLastLayer node.
When it is set, it becomes permanent for all the upcoming work.

I use the ComfyUI portable windows release with added DirectML support.

To reproduce: 

Workflow image to load : ![ComfyUI_temp_nonht_00003_](https://github.com/comfyanonymous/ComfyUI/assets/139562973/aad649fa-5100-4b72-ac1e-828e4538c19d)

1. Load the workflow and start generation, notice that the resulting image is different than what it is
2. Link "Load Checkpoint" with CLIPSetLastLayer, and CLIPSetLastLayer with both CLIP Text Encode nodes
3. Start generation, the image shows.
4. Remove the "CLIPSetLastLayer" node and link back the CLIP Text Encode nodes to the Load Checkpoint
5. Regenerate, the same image as before shows.

You have to restart ComfyUI for the CLIPSetLastLayer value to be actually forgotten.

My graphic card is Radeon RX 580 Series.

**Comment by comfyanonymous** [comment]
Fixed with: https://github.com/comfyanonymous/ComfyUI/commit/50b1180ddee4b86a7bc054079bf1a4b3be01f48a
