### ISSUE TITLE
Intermediate Steps 

### ISSUE THREAD

**Issue by guzuligo** [comfyanonymous/ComfyUI#91]
I'd like to see intermediate steps so I know what I'm doing. Isn't it possible to allow VAE's or KSamplers to have the ability to show a preview of what the sampler doing?

**Comment by leppie** [comment]
Using the full VAE is not cheap, but using something like this from auto1111 could work.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sd_vae_approx.py#L49-L61

Maybe have a collapsable preview section in the sampler node.

**Comment by nistvan86** [comment]
I'm also requesting this. This was the first thing I was missing from a1111 transitioning to ComfyUI.

**Comment by nistvan86** [comment]
I don't know when this was added, but you can now add the `--preview-method auto` switch to the ComfyUI startup script and it will show a live preview in the Sampler block while rendering.

**Comment by guzuligo** [comment]
@nistvan86 Thanks for sharing!
I wish it was something visible in the settings instead of being hidden in the command line.
