### ISSUE TITLE
Convert workflow to Python script

### ISSUE THREAD

**Issue by xings19** [comfyanonymous/ComfyUI#915]
I built a workflow, and now I want to generate images in batches. Is there a way to convert the built workflow into a Python script?

**Comment by comfyanonymous** [comment]
if you have the latest you can "enable dev mode options" in the settings (gear beside the "Queue Size: ") this will enable a button on the UI to save workflows in api format.

You can then use these api jsons in these script examples: https://github.com/comfyanonymous/ComfyUI/tree/master/script_examples

**Comment by xings19** [comment]
Thanks!
