### ISSUE TITLE
Black images produced above a certain resolution

### ISSUE THREAD

**Issue by kontori** [comfyanonymous/ComfyUI#924]
Vram 2GB, RAM 16GB. I am using the latest version of comfyUI, with xformers 0.0.20. When I tried to produce an image with 512x512 or above, it only outputs black images. But 256x256 works fine.

**Comment by kontori** [comment]
![1](https://github.com/comfyanonymous/ComfyUI/assets/42268180/722dd920-9e22-467d-bd81-eee2b86e8b58)

**Comment by kontori** [comment]
I add --force-fp32 option and it seems to work now.

**Comment by comfyanonymous** [comment]
what's your GPU?

**Comment by comfyanonymous** [comment]
This should fix it: https://github.com/comfyanonymous/ComfyUI/commit/18885f803a46adfe56b8fa0379e899e99fb286ab

**Comment by kontori** [comment]
Thanks a lot!
