### ISSUE TITLE
Feature request: QOL - Visually show all possible node inputs as connectable, auto-convert to input when connecting

### ISSUE THREAD

**Issue by thelemuet** [comfyanonymous/ComfyUI#947]
Instead of having to do a lot of right/left-clicking "convert X to input" and "convert X to widget", do similarly to other apps with nodes, ie: Blender.

Example:

![input0](https://github.com/comfyanonymous/ComfyUI/assets/86247933/277d87fc-f809-477e-abaa-72bbc9da81c6)

![input1](https://github.com/comfyanonymous/ComfyUI/assets/86247933/984a8b27-09f7-4823-9bbe-55d16409827d)

Disconnecting would auto-convert back to widget.

Admittedly, this doesn't take into account that it might not be that simple to make such a change to the UI (ie: adding the input dot next to widgets), this is just to demonstrate the idea.

An alternative could be a functionality similar to how it currently works when holding a "cable" where it highlights compatible inputs, the widget could visually show it can be converted to input like this (integer data):

![input2](https://github.com/comfyanonymous/ComfyUI/assets/86247933/acb0bd33-5295-410f-a0ae-a46ba44fadcd)

This functionality would be a very decent quality of life improvement, at least in my opinion.

The only problem that I just realized as I was writing this, at least for this example, is that Primitive nodes don't have a data type until it has been plugged into a node, so in that case it would not highlight the "compatible" inputs, oops. ;) I suppose this could be a simple custom node based on Primitive node but with pre-selectable datatype.

**Comment by aegis72** [comment]
Great idea!

**Comment by WolfExplode** [comment]
Great Idea! I wonder if the developers ever pay attention to non technical feedback like this. It seems like they never respond 😔

**Comment by MrForExample** [comment]
Exactly, this design should be default without saying, there are so much ComfyUI can learn from Unreal's Blueprint

**Comment by DrMechanica** [comment]
Adding a comment to show support for this. This would be a big time saver.

**Comment by drmbt** [comment]
another bump here

**Comment by ltdrdata** [comment]
Please move this feature request to ComfyUI_frontend
https://github.com/Comfy-Org/ComfyUI_frontend
