### ISSUE TITLE
SDXL invisible-watermark is not applied

### ISSUE THREAD

**Issue by bghira** [comfyanonymous/ComfyUI#949]
As stated in the SDXL license (reference: https://github.com/huggingface/diffusers/issues/4014) the outputs for SDXL must have the invisible watermark applied before they are shared publicly.

**Comment by comfyanonymous** [comment]
It's up to users to read and follow the license of the specific weights they are using. This repo doesn't ship any checkpoints or auto download any, it's just a tool to use them.

**Comment by bghira** [comment]
there doesn't seem to be any reference to the requirement in the official tutorial or SDXL workflow example. most users seem to be under the impression that it is not required.

**Comment by Extraltodeus** [comment]
> there doesn't seem to be any reference to the requirement in the official tutorial or SDXL workflow example. most users seem to be under the impression that it is not required.

It is of the responsability of the users to know what they are doing.

**Comment by bghira** [comment]
responsibility* means many things, please, let's not do philosophical debates on it.

i'll close this with a note that a StabilityAI staff member (comfy) just seems to dismiss the concerns around the watermark not being used.
