### ISSUE TITLE
Feature Request: coloured connecting wires

### ISSUE THREAD

**Issue by ghost** [comfyanonymous/ComfyUI#95]
As our work flows increase in complexity, it would be handy to either colour the wires at will, or different colours for different connector types. it would make at a glance debugging easier too.

**Comment by m957ymj75urz** [comment]
In the meantime you can try this extension : https://github.com/m957ymj75urz/ComfyUI-Custom-Nodes/tree/main/colors 

To install, put the `color.js` file in the `web/extensions/` folder.

![image](https://user-images.githubusercontent.com/125697471/225466787-eb15319a-104c-4b27-aaee-679c37d00419.png)
