### ISSUE TITLE
Feature Request: model and output path setting

### ISSUE THREAD

**Issue by mrgreaper** [comfyanonymous/ComfyUI#96]
Sym linking is not ideal, setting a model folder is pretty standard these days and most of us use more than one software that uses models. 
The same for choosing where to put the output images, personally mine go to a portable drive, not sure how to do that with ComfyUI.

**Comment by jordanbtucker** [comment]
See also #66 and #18

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example

Update the ui, copy the new ComfyUI/extra_model_paths.yaml.example to ComfyUI/extra_model_paths.yaml and edit it to set the path to your a1111 ui.

**Comment by mrgreaper** [comment]
Awesome, will test later. Thank you for adding this

**Comment by arijoon** [comment]
is it also possible to set the `output` path?

**Comment by comfyanonymous** [comment]
You can now use --output-directory directory/path to set the output path.

**Comment by tusharbhutt** [comment]
> You can now use --output-directory directory/path to set the output path.

That unfortunately does not work for UNC paths on Windows:

```
  File "C:\Applications\StableDiffusion\ComfyUI\ComfyUI\folder_paths.py", line 214, in get_save_image_path
    if os.path.commonpath((output_dir, os.path.abspath(full_output_folder))) != output_dir:
  File "ntpath.py", line 804, in commonpath
ValueError: Paths don't have the same drive
```

**Comment by Jandolek1** [comment]
Where did you try to change please? In the .bat file or in the .yaml file.

**Comment by tusharbhutt** [comment]
> Where did you try to change please? In the .bat file or in the .yaml file.

Batch file...

**Comment by Jandolek1** [comment]
Yes, I tried and does not work :/

**Comment by andreszs** [comment]
A setting to store the output files in the same format as a1111, which is **output/YYYY-MM-DD/batchnumber_seed.png** would be priceless.
Currently, all files are in the same folder, and they don't even include the date. Is there some solution, extension or any possible way to achieve this? Thanks.

**Comment by ltdrdata** [comment]
> I'm **astonished** to see that such an advanced and revolutionary piece of software just dumps all output files in the same folder with a meaningless **ComfyUI_00123.png** format.
> 
> A1111 is miles ahead here, naming files as **output/YYYY-MM-DD/batchnumber_seed.png** in a folder with the current date.
> 
> **Is there some solution, extension or any possible way to emulate the same output format from automatic1111?**

Maybe you can find it in the WAS node suite.

**Comment by andreszs** [comment]
@ltdrdata It seems the README says nothing about output paths, and that plugin seems to add other features which are irrelevant in this case.

**Comment by Schokostoffdioxid** [comment]
Hi, maybe im just dumb but is there no documentation / ability on how to set the output path inside the yaml?
im currently trying the following but this doesn't seem to work...

```
a111:
    base_path: E:\stable-diffusion-ai
    
    output-directory: stable-diff-output\comfyui

```

**Comment by andreszs** [comment]
@Schokostoffdioxid My model paths yaml doesn't include an output-directory value. However, I now set the output path and filename using a primitive node as explained here: [Change output file names in ComfyUI](https://www.andreszsogon.com/change-output-file-names-in-comfyui/)

Basically, to output files in a folder with current date you add this to your **Primitive** node:
`%date:yyyy-MM-dd%/%date:hhmmss%_%KSampler.seed%`

So the file would be saved as **output/2023-08-15/083821_109992800202691_00001_.png**, which means output/date/time_seed_00001_.png.

![image](https://github.com/comfyanonymous/ComfyUI/assets/10298071/ad152f30-d944-4180-a6e9-b0a0087deac5)

**Comment by Skettalee** [comment]
In my advanced menu i dont have any of the same stuff there.
ALL i have are "Loaders, conditioning & model_merging" in advanced. Anyone else?

**Comment by thedyze** [comment]
> I'm **astonished** to see that such an advanced and revolutionary piece of software just dumps all output files in the same folder with a meaningless **ComfyUI_00123.png** format.
> 
> A1111 is miles ahead here, naming files as **output/YYYY-MM-DD/batchnumber_seed.png** in a folder with the current date.
> 
> **Is there some solution, extension or any possible way to emulate the same output format from automatic1111?**

I've created a node for this purpose: https://github.com/thedyze/save-image-extended-comfyui

**Comment by jlitz** [comment]
the save image does not have an filename prefix  output  just  images

**Comment by githubarooski** [comment]
> > You can now use --output-directory directory/path to set the output path.
> 
> That unfortunately does not work for UNC paths on Windows:
> 
> ```
>   File "C:\Applications\StableDiffusion\ComfyUI\ComfyUI\folder_paths.py", line 214, in get_save_image_path
>     if os.path.commonpath((output_dir, os.path.abspath(full_output_folder))) != output_dir:
>   File "ntpath.py", line 804, in commonpath
> ValueError: Paths don't have the same drive
> ```

just fyi this works fine in Windows

in run_nvidia_gpu.bat just put it here
```
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --output-directory "G:\projects\project-name\comfy-output"
pause
```

Works great with network shares mounted as drive letters
