### ISSUE TITLE
please fix the dragging behavior

### ISSUE THREAD

**Issue by mattymatty** [comfyanonymous/ComfyUI#960]
Please match every other software out there to pan the canvas. Hold spacebar, cursor turns into the hand icon, then click and drag to pan canvas, when done panning release spacebar. There is no need to make a new pattern, it is a very bad user experience for such a common user interaction. It is always recommended to not stray from existing patterns.

**Comment by NeedsMoar** [comment]
Actually I've never seen spacebar used for that purpose.  Most software uses shift since it isn't expected to do anything by default.  Spacebar would enter a space if a text element was selected which causes a conflict.

**Comment by mattymatty** [comment]
Look at every single Adobe, Affinity, Blender, Sketch, Figma product. They all use space at.

**Comment by Lex-DRL** [comment]
As an experienced Photoshop, Maya, Houdini and  Nuke user, here are my 5 cents:
- Yes, current behavior is both extremely inconvenient and non-standard
- But no, I don't think spacebar-hold specifically is a good solution. Houdini was using it for years, but even they finally shifted to the industry standard: alt.
- ... But keeping in mind, that we're in a browser here, alt might be not the best solution. E.g.,in Firefox (I use it) alt displays legacy main menu.

So yes, we should use some function key instead, but alt itself seems as a bad choice.

My proposal: adopt Nuke's navigation. After all, it's a 2d package, not 3d. But also, it's somewhat compatible with patterns in 3d software. I.e:
- Zoom with right mouse button OR with Shift+middle.
- Pan with middle mose button OR with Alt+right.

"or" here that I suggest both to be working at the same time, not exclusively one or the other.

**Comment by vulpescodex** [comment]
I vote for middle mouse button panning, I have been able to use it in most of the software I use and the habit is difficult to break. 

I would additionally like to request that the default panning and zooming behavior of the browser would be allowed. Half of the time I'm using a MacBook Pro with a trackpad and Safari and currently the trackpad two finger panning gesture zooms the workspace. The speed is also quite rapid creating a jarring experience as most other software I use respects that panning method.

**Comment by LeeLorenzSr** [comment]
Zoom doesn't work at all for me with my scroll wheel, and from other comments I've seen I'm not the only one. One click of my scroll wheel zooms out to gigantic (beyond scope of window) or in microscopic size. Until I can figure out the simplest navigation issue on ComfyUI, it is unusable.

**Comment by Lex-DRL** [comment]
Panning with mouse also mentioned in:
#103 , #757 , #624 , #414

**Comment by subtleGradient** [comment]
This may be relevant:
https://github.com/subtleGradient/TinkerBot-tech-for-ComfyUI-Touchpad

**Comment by amansharma007** [comment]
> This may be relevant: https://github.com/subtleGradient/TinkerBot-tech-for-ComfyUI-Touchpad

Brrooooo. You just saved the whole group! Amazing solution!

**Comment by robinjhuang** [comment]
Consolidating mouse / dragging feature requests here: https://github.com/comfyanonymous/ComfyUI/issues/624
