### ISSUE TITLE
Embeddings/Textual Inversion not working

### ISSUE THREAD

**Issue by nextdimension** [comfyanonymous/ComfyUI#97]
RuntimeError: The expanded size of the tensor (1024) must match the existing size (768) at non-singleton dimension 0. Target sizes: [1024]. Tensor sizes: [768]

**Comment by nextdimension** [comment]
This actually might be because the embedding is not made for SD 2.0 models, Automatic111111 doesn't complain

**Comment by comfyanonymous** [comment]
Yes that sounds like you are using a SD1.x embedding on an SD2.x model which won't work.
