### ISSUE TITLE
[Feature request] A way to redo the last generation (with randomized values)

### ISSUE THREAD

**Issue by Lex-DRL** [comfyanonymous/ComfyUI#978]
In a general use case, you re-generate the graph a few times until you get something close to what you want...
But currently, after you get it, you're in a whole new task of restoring the graph to what it was when it was generated. Yes, you can find and load the image created with it... but then all the previews in the graph are lost.

So, it will be much more convenient if:
- Randomized values were randomized as the very first step, BEFORE new generation. Not after.
- There would be a "copy previous value" option in context menu for every node which has such fixed/randomized/incremented values.

I, personally, believe that the first solution is superior. This way, the graph always represents whatever is currently shown there - whether it's being generated right now or is finished already.

But feature request is open for debate.

**Comment by cubiq** [comment]
it has been suggested and a PR is ready since a few months, it doesn't seem a priority unfortunately but I learned to always work with fixed seeds at the end https://github.com/comfyanonymous/ComfyUI/pull/93

**Comment by Lex-DRL** [comment]
@cubiq Thanks for the info.

I'm closing this as duplicate then... And hope PR to be merged soon.

Yes, you can work with fixed value, but it defeats the sole convenince purpose of random fields.
