### ISSUE TITLE
[Feature request] Keeping the loaded workflow's filename visible.

### ISSUE THREAD

**Issue by pvp-by** [comfyanonymous/ComfyUI#983]
When I load my "workflow_perfect.json"✔, the filename of the loaded file disappears. I honestly tried to find where this name is assigned, but unfortunately, I was unsuccessful.

Perhaps it doesn't exist because when attempting to save, we always have the same name "workflow.json"❌ (I copy the name of the uploaded JSON if I remember correctly). 

![image](https://github.com/comfyanonymous/ComfyUI/assets/10133995/8b9cc76e-1d6d-4674-8696-126ff67408d7)

I'm working with several JSON files simultaneously (in different browsers - working, experimental, examples, etc.), and there is a slight confusion about which version of JSON I'm currently viewing.

When the workflow is loaded from a PNG file, the name should be taken from the PNG filename✔ (without extension).

**Comment by alexbofa** [comment]
+

**Comment by ryanontheinside** [comment]
this would be amazing

**Comment by baardev** [comment]
!!BUMP!!  I am currently adding a note to each workflow with the filename, but that is a HUGE PITA, especially if I do a rename.  I have resorted to a command line utility that updates a "Note" in all the workflows with the actual path/filename of the workflow, but it would be SO much more productive to have a builtin widget with the path, and, if possible, a 'status' icon to indicate is it has any unsaved changes.

I have never written a node before, but I am considering writing a websockets "File Status" node, which shows filename, status, "save/save as" and other metadata such as description, references, etc.... but I am not a very good programmer, so I hope you folks write something first ;)

**Comment by Metatronovich** [comment]
Any news on this?

another great option would be that the save button just saves the current workflow to its own filename (instead of "Saving As..." everytime)

**Comment by ltdrdata** [comment]
The workflow load and management system has completely changed in the new front, so this request is no longer valid.

Workflows managed within the new front are designed to maintain their names. 
Workflows loaded via drag & drop are identified as "unsaved workflow" to prevent conflicts with workflow names managed within the workflow system.

**Comment by fideal** [comment]
> The workflow load and management system has completely changed in the new front, so this request is no longer valid.
> 
> Workflows managed within the new front are designed to maintain their names. Workflows loaded via drag & drop are identified as "unsaved workflow" to prevent conflicts with workflow names managed within the workflow system.

The title of the feature request is "Keeping the loaded workflow's filename visible" and I still don't see that as an option. The comments drifted to requests about maintaining the name, and that was done as @ltdrdata points out, but the original feature request of _showing_ the file's name is still not addressed. Thus, this request should be reopened.

**Comment by christian-byrne** [comment]
> > The workflow load and management system has completely changed in the new front, so this request is no longer valid.
> > Workflows managed within the new front are designed to maintain their names. Workflows loaded via drag & drop are identified as "unsaved workflow" to prevent conflicts with workflow names managed within the workflow system.
> 
> The title of the feature request is "Keeping the loaded workflow's filename visible" and I still don't see that as an option. The comments drifted to requests about maintaining the name, and that was done as @ltdrdata points out, but the original feature request of _showing_ the file's name is still not addressed. Thus, this request should be reopened.

The workflow's filename is shown in the top menu:

https://github.com/user-attachments/assets/e623164e-b214-4bf7-b535-ec696959e847

Since frontend version 1.2.27 (Comfy-Org/ComfyUI_frontend#484)
