### ISSUE TITLE
[Feature request] Make save as png (screenshot page workflow as image-data)

### ISSUE THREAD

**Issue by pvp-by** [comfyanonymous/ComfyUI#984]
Save workflow as PNG. Currently, we can obtain a PNG by saving the image with 'save workflow include.' However, there are times when you want to save only the workflow without being tied to a specific result and have it visually displayed as an image for easier sharing and showcasing the workflow. We already have a canvas that contains all the data for image-data, and there's also an implementation of [WORKFLOW2PNG](https://colab.research.google.com/drive/1hQMjNUdhMQ3rw1Wcm3_umvmOMeS_K4s8#scrollTo=iysnRm-SBoxf) mentioned in [@WASasquatch](https://github.com/WASasquatch/comfyui-plugins#other-links).

What do you think about this improvement?

PS Partially has a connection with this #983

**Comment by tildebyte** [comment]
Do you mean something like #942?

**Comment by pvp-by** [comment]
Solution: png or svg.
https://github.com/pythongosssss/ComfyUI-Custom-Scripts#workflow-svg
