### ISSUE TITLE
Installing requirements.txt installs the wrong torch version.

### ISSUE THREAD

**Issue by subashc2023** [comfyanonymous/ComfyUI#99]
The README says to install Torch 1.13 with CUDA 11.8 in the command provided. 

Regardless of this, the requirements automatically installs Torch 2.0, and since your command to install the requirements comes after the torch and xformers installation, it uninstalled the existing version of Torch, and replaces it with this version, causing Xformers to fail to load.

Please fix this.

**Comment by comfyanonymous** [comment]
Fixed, the new command should actually work.

**Comment by subashc2023** [comment]
Your new command installs for CUDA 11.7 instead of 11.8. Is this intended? I don't think you should be downgrading

I just installed CUDA 11.8 too

**Comment by comfyanonymous** [comment]
The cu117 build should work even if you have cuda 11.8 installed.

I had to switch it to that or else it won't work with the xformers build on pip.

**Comment by subashc2023** [comment]
I just realized. Thank you for being so quick on that!

**Comment by leppie** [comment]
> The cu117 build should work even if you have cuda 11.8 installed.

Torch 2 is default on cu117 now as well. The situation is messy.

![image](https://user-images.githubusercontent.com/127666/225538654-8be53b3f-a4b3-4003-a8d9-f685e4e83427.png)

**Comment by comfyanonymous** [comment]
ComfyUI works fine with pytorch 2.0 it's if you want to use xformers that you'll have issues.
