### ISSUE TITLE
How to use deepbooru in ComfyUI?

### ISSUE THREAD

**Issue by VenkatLohithDasari** [comfyanonymous/ComfyUI#990]
Hey guys, I'm trying to convert some images into "almost" anime style using anythingv3 model. So It's like this, I first input image, then using deep-danbooru, I extract tags for that specific image then use that as a prompt to do img2img process. 

Sorry, I'm new in all of these, and first time using Comfy, so I wanted to know how can I use deep-Danbooru here like interrogate deepbooru feature in Auto1111 WebUI.

**Comment by ltdrdata** [comment]
https://github.com/pythongosssss/ComfyUI-WD14-Tagger

**Comment by VenkatLohithDasari** [comment]
> [pythongosssss/ComfyUI-WD14-Tagger](https://github.com/pythongosssss/ComfyUI-WD14-Tagger)

Thanks for that but How can I take the string (tags) and then put them to the clip prompt's text field? there seems to be no way to do that....plus no info is given regarding that in the extension repo

**Comment by ltdrdata** [comment]
> > [pythongosssss/ComfyUI-WD14-Tagger](https://github.com/pythongosssss/ComfyUI-WD14-Tagger)
> 
> Thanks for that but How can I take the string (tags) and then put them to the clip prompt's text field? there seems to be no way to do that....plus no info is given regarding that in the extension repo

https://www.youtube.com/watch?v=HV2kyxNoYAE

I'd uploaded usage video of WD14 Tagger.

**Comment by VenkatLohithDasari** [comment]
> [youtube.com/watch?v=HV2kyxNoYAE](https://www.youtube.com/watch?v=HV2kyxNoYAE)
> 
> I'd uploaded usage video of WD14 Tagger.

Dam! thankyou so much for uploading the usage video guide! It made understanding things simpler!!

**Comment by Seanscrafts** [comment]
Hi. I am so new to Comfy and have been enjoying it so much. In your You tube video above what happens at : 1:07 / 2:48
It is the point when the tagger is triggered. How did you trigger it ? I have watched it closely, it seems you went to the checkpoint node clicked it and then go to the tagger node. You elarge the tagger node and then something happens to trigger it and it goes green. You  did not click on the Queue Promt (i tried that) so Im assume you hit a key on the keyboard ? Thanks so much !

**Comment by ltdrdata** [comment]
> Hi. I am so new to Comfy and have been enjoying it so much. In your You tube video above what happens at : 1:07 / 2:48
> It is the point when the tagger is triggered. How did you trigger it ? I have watched it closely, it seems you went to the checkpoint node clicked it and then go to the tagger node. You elarge the tagger node and then something happens to trigger it and it goes green. You  did not click on the Queue Promt (i tried that) so Im assume you hit a key on the keyboard ? Thanks so much ! 

"ctrl-enter" is equivalent to "click queue prompt"

**Comment by Seanscrafts** [comment]
Hot dang! lol. It works now, it just does not preview the text in the tagger node but when I plug the string node into the clip text prompt it works. I do have the preview method in Comfi manager set to auto.

**Comment by TomLucidor** [comment]
Does Deepdanbooru use a different model compared to WD14? If so then are there other models out there with different base dataset?
P.S. WAS has a plugin with BLIP which is somewhat "CLIP Interrogator" but requires an initial prompt instead of being fully auto, wondering what can be done

**Comment by freemonopolydice** [comment]
DeepNude AI offers advanced tools for generating high-quality AI-powered imagery. With features like precision, ease of use, and seamless integration, it caters to beginners and professionals alike. Users can enjoy: https://deepnudefree.online/
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
3- Best undress ai for free without sing up : https://7070.lol/
4- surprise For an iPhone at a surprising price : https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21
No cost: Completely free with no hidden charges.
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://7070.lol/)
## [👉🔴 Click HERE >>](https://7070.lol/)
## [👉🔴 Click HERE >>](https://7070.us)
## [👉🔴 Click HERE >>](https://7070.us)
## [👉🔴 Click HERE >>](https://deepnudefree.online/)
## [👉🔴 Click HERE >>](https://deepnudefree.online/)
## [👉🔴 Click HERE >>](https://deepnudefree.online/)
## [👉🔴 Click HERE >>](https://deepnudefree.online/)
## [👉🔴 Click HERE >>](https://7070.lol/)
## [👉🔴 Click HERE >>](https://7070.lol/)
## [👉🔴 Click HERE >>](https://7070.lol/)
## [👉🔴 Click HERE >>](https://deepnudefree.online/)
## [👉🔴 Click HERE >>](https://deepnudefree.online/)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
DeepNude AI offers advanced tools for generating high-quality AI-powered imagery. With features like precision, ease of use, and seamless integration, it caters to beginners and professionals alike. Users can enjoy: https://deepnudefree.online/
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
3- Best undress ai for free without sing up : https://7070.lol/
4- surprise For an iPhone at a surprising price : https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21
No cost: Completely free with no hidden charges.
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://cd-sec.com/?a=256440&c=383557&co=316585&mt=21)
## [👉🔴 Click HERE >>](https://7070.us)
## [👉🔴 Click HERE >>](https://7070.us)
Accessibility: Available on various platforms.
Advanced results: Crisp and accurate outputs.
Why Choose DeepNude AI? https://7070.us
Trusted worldwide for its efficiency, DeepNude AI combines simplicity with reliability, making it an ideal choice for users seeking fast, effective AI solutions

**Comment by mnplly** [comment]
Accessibility: Available on various platforms. Advanced results: Crisp and accurate outputs. Why Choose DeepNude AI? https://frestr20.blogspot.com/ Trusted worldwide for its efficiency, DeepNude AI combines simplicity with reliability, making it an ideal choice for users seeking fast, effective AI solutions
withount sing up : 👍

[➤ ➤  DeepNude FREE ](https://frestr20.blogspot.com/)
[➤ ➤ ➤  DeepNude FREE Nude AI](https://frestr20.blogspot.com/)
[➤ ➤ ➤  DeepNude FREE Nude AI](https://frestr20.blogspot.com/)
[ ➤ ➤ ➤ DeepNude FREE Nude AI](https://frestr20.blogspot.com/)

**Comment by comiterrt** [comment]
## GET FREE UNDREES AI WITHOUT SING UP 
## [👉 Click HERE >>](https://frestr20.blogspot.com/)
## [👉 Click HERE >>](https://frestr20.blogspot.com/)

**Comment by fulvioborrego** [comment]
<p>🔥 **Looking to create Deepnude images in seconds?** Visit the **Undress AI website** and transform any photo instantly! Customize outfits, styles, and body types — then download your results for **FREE**! 🚀</p>
 <p> <a href="https://deepnudeai.online/" target="_blank" rel="dofollow">🔗 **👉🔴 _Get the Undress AI website — Create Deepnude Images for FREE!_ ✅**</a><br>

<a href="https://freedeepnude.blogspot.com/" target="_blank" rel="dofollow">🔗 👉🔴 Undress Anyone with AI — Instant Results & Free Downloads! ✅</a><br>

<a href="https://www.loyou.shop/" target="_blank" rel="dofollow">🔗 👉🔴 Try Our Free AI Undress Tool Now on the Website! ✅</a><br>

</p> <p>✨ **Don’t miss out — unleash AI-powered creativity now!** 🌟</p>

![Img4](https://github.com/user-attachments/assets/c6f7e852-6305-46bc-909c-a8612fbe1c88)

**Comment by plotkabarba** [comment]
<p>🔥  Looking to create Deepnude images in seconds?  Visit the Undress AI website  and transform any photo instantly! Customize outfits, styles, and body types — then download your results for FREE ! 🚀</p>
 <p> <a href="https://deepnudeai.online/" target="_blank" rel="dofollow">🔗 👉🔴 _Get the Undress AI website — Create Deepnude Images for FREE!_ ✅  </a><br>

<a href="https://freedeepnude.blogspot.com/" target="_blank" rel="dofollow">🔗 👉🔴 Undress Anyone with AI — Instant Results & Free Downloads! ✅</a><br>

<a href="https://www.loyou.shop/" target="_blank" rel="dofollow">🔗 👉🔴 Try Our Free AI Undress Tool Now on the Website! ✅</a><br>

</p> <p>✨  Don’t miss out — unleash AI-powered creativity now!  🌟</p>
